dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function sub01_uchuuritsunooka01_init()
  if FLAG.NowResumeFlag == CONST.FLAG_TRUE then
    subEveFromProgFadeSet()
    subSaveflagS01_080_01()
  end
end
function sub01_uchuuritsunooka01_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_GANBARE"), Volume(256))  
  CAMERA:SetAzimuthDifferenceVolume(Volume(2.5))
  CAMERA:SetFovy(SymCam("CAMERA_14"))
  CAMERA:SetEye(SymCam("CAMERA_14"))
  CAMERA:SetTgt(SymCam("CAMERA_14"))
  CH("PARTNER"):SetPosition(SymPos("P02_PLAYER"))
  CH("PARTNER"):SetDir(SymPos("P_CAMERA"))
  CH("SAZANDORA_LARGE"):SetDir(SymPos("P_CAMERA"))
  CH("SAZANDORA_LARGE"):SetNeckRot(RotateTarget(0), RotateTarget(20), RotateTarget(0), TimeSec(0))
  CH("PARTNER"):SetNeckRot(RotateTarget(0), RotateTarget(20), RotateTarget(0), TimeSec(0))
  CH("HERO"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  CH("HERO"):SetShadow(false)

  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- CH("SAZANDORA_LARGE"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  -- CH("HERO"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  -- CH("SAZANDORA_LARGE"):SetShadow(false)
  -- CH("HERO"):SetShadow(false)
  -- EFFECT:Create("effectStarLp", SymEff("EV_STAR_LP"))
  -- EFFECT:SetPosition("effectStarLp", SymPos("P_EFF_STAR_LP"))
  -- EFFECT:Play("effectStarLp")
  -- SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_DAIHYOUGA_02"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- CH("PARTNER"):WalkTo(SymPos("P01_PLAYER"), Speed(1.7))
  -- CH("PARTNER"):WaitMove()
  -- TASK:Sleep(TimeSec(0.5))
  -- CH("PARTNER"):SetMotion(SymMot("EV001_CONFIRMS"), LOOP.OFF)
  -- CH("PARTNER"):WaitPlayMotion()
  -- CH("PARTNER"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  -- TASK:Sleep(TimeSec(0.5))
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  -- WINDOW:SwitchTalk({PARTNER_0 = -210023038, PARTNER_1 = -362775357})
  -- WINDOW:SwitchTalk({PARTNER_0 = -1051906304, PARTNER_1 = -665444799})
  -- WINDOW:CloseMessage()
  -- CAMERA:MoveFollow(SymCam("CAMERA_01"), Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- CH("PARTNER"):WalkTo(SymPos("P02_PLAYER"), Speed(1.5))
  -- CH("PARTNER"):WaitMove()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  -- CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  -- CH("PARTNER"):WaitManpu()
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  -- WINDOW:SwitchTalk({PARTNER_0 = -1760065402, PARTNER_1 = -1911768633})
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  -- CAMERA:SetEye(SymCam("CAMERA_02"))
  -- CAMERA:SetTgt(SymCam("CAMERA_02"))
  -- CH("PARTNER"):SetMotion(SymMot("EV001_LOOK00"), LOOP.OFF)
  -- CH("PARTNER"):WaitPlayMotion()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  -- CH("PARTNER"):SetManpu("MP_SHOCK_R")
  -- CH("PARTNER"):SetMotion(SymMot("EV001_LOOK01"), LOOP.ON)
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  -- WINDOW:SwitchTalk({PARTNER_0 = -1524504060, PARTNER_1 = -1136993467})
  -- WINDOW:SwitchTalk({PARTNER_0 = 1000523658, PARTNER_1 = 582612683})
  -- WINDOW:CloseMessage()
  -- CH("PARTNER"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.5))
  -- TASK:Sleep(TimeSec(0.7))
  -- CH("PARTNER"):DirTo(RotateTarget(135), Speed(200), ROT_TYPE.NEAR)
  -- CH("PARTNER"):WaitRotate()
  -- CH("PARTNER"):SetNeckRot(RotateTarget(0), RotateTarget(20), RotateTarget(0), TimeSec(0.5))
  -- CH("PARTNER"):WaitNeckRot()
  -- SCREEN_A:FadeOut(TimeSec(0.3), true)
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetFovy(SymCam("CAMERA_03"))
  -- CAMERA:SetEye(SymCam("CAMERA_03"))
  -- CAMERA:SetTgt(SymCam("CAMERA_03"))
  -- CAMERA:MoveFollow(SymCam("CAMERA_03_5"), Speed(5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- SCREEN_A:FadeIn(TimeSec(0.3), true)
  -- CAMERA:WaitMove()
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  -- WINDOW:SwitchTalk({PARTNER_0 = 670791670, PARTNER_1 = 1054885559})
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  -- WINDOW:SwitchTalk({PARTNER_0 = 365761908, PARTNER_1 = 215360565})
  -- WINDOW:SwitchTalk({PARTNER_0 = 1134015218, PARTNER_1 = 1519158195})
  -- WINDOW:SwitchTalk({PARTNER_0 = 1906430064, PARTNER_1 = 1757077809})
  -- WINDOW:SwitchTalk({PARTNER_0 = -282919426, PARTNER_1 = -163984193})
  -- WINDOW:SwitchTalk({PARTNER_0 = 894359576, PARTNER_1 = 743827801})
  -- WINDOW:CloseMessage()
  -- SCREEN_A:FadeOut(TimeSec(0.3), true)
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  -- CAMERA:SetFovy(SymCam("CAMERA_02"))
  -- CAMERA:SetEye(SymCam("CAMERA_02"))
  -- CAMERA:SetTgt(SymCam("CAMERA_02"))
  -- TASK:Sleep(TimeSec(0.3))
  -- SCREEN_A:FadeIn(TimeSec(0.3), true)
  -- TASK:Sleep(TimeSec(0.3))
  -- WINDOW:Talk(SymAct("SAZANDORA"), 125352602)
  -- WINDOW:Talk(SymAct("SAZANDORA"), 509840347)
  -- WINDOW:CloseMessage()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  -- CH("PARTNER"):SetManpu("MP_NOTICE_R")
  -- CH("PARTNER"):WaitManpu()
  -- CH("PARTNER"):ResetNeckRot(TimeSec(0.2))
  -- CH("PARTNER"):WaitNeckRot()
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  -- WINDOW:SwitchTalk({PARTNER_0 = 1361190172, PARTNER_1 = 1211706461})
  -- WINDOW:CloseMessage()
  -- CAMERA:SetEye(SymCam("CAMERA_05"))
  -- CAMERA:SetTgt(SymCam("CAMERA_05"))
  -- TASK:Sleep(TimeSec(0.3))
  -- CH("SAZANDORA_LARGE"):SetDir(CH("PARTNER"))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SAZANDORA_GHOST"), Volume(256))
  -- CH("SAZANDORA_LARGE"):ChangeColor(Color(1, 1, 1, 1), TimeSec(30, TIME_TYPE.FRAME))
  -- CH("SAZANDORA_LARGE"):SetShadow(true)
  -- TASK:Sleep(TimeSec(1.5))
  -- CH("PARTNER"):DirTo(CH("SAZANDORA_LARGE"), Speed(350), ROT_TYPE.NEAR)
  -- CH("PARTNER"):WaitRotate()
  -- WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("SAZANDORA"), 1662287774)
  -- WINDOW:Talk(SymAct("SAZANDORA"), 2047823583)
  -- WINDOW:Talk(SymAct("SAZANDORA"), -40414704)
  -- WINDOW:Talk(SymAct("SAZANDORA"), -460561583)
  -- WINDOW:Talk(SymAct("SAZANDORA"), -1913471107)
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  -- WINDOW:SwitchTalk({PARTNER_0 = -1796633028, PARTNER_1 = -1077617153})
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("SAZANDORA"), -1495274306)
  -- WINDOW:Talk(SymAct("SAZANDORA"), -375489927)
  -- WINDOW:CloseMessage()
  -- subEveNod(CH("PARTNER"))
  -- TASK:Sleep(TimeSec(0.5))
  -- CH("PARTNER"):DirTo(RotateTarget(180), Speed(200), ROT_TYPE.NEAR)
  -- CH("PARTNER"):WaitRotate()
  -- SCREEN_A:FadeOut(TimeSec(0.3), true)
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetEye(SymCam("CAMERA_06"))
  -- CAMERA:SetTgt(SymCam("CAMERA_06"))
  -- TASK:Sleep(TimeSec(0.3))
  -- SCREEN_A:FadeIn(TimeSec(0.3), true)
  -- TASK:Sleep(TimeSec(0.3))
  -- CH("PARTNER"):SetNeckRot(RotateTarget(0), RotateTarget(-30), RotateTarget(0), TimeSec(0.15))
  -- CH("PARTNER"):WaitNeckRot()
  -- CH("PARTNER"):SetEyeMotion(EYE_MOTION.CLOSE)
  -- CH("PARTNER"):SetMouthMotion(MOUTH_MOTION.NORMAL)
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL01)
  -- WINDOW:SwitchTalk({PARTNER_0 = -259699912, PARTNER_1 = -609740549})
  -- WINDOW:SwitchTalk({PARTNER_0 = -1028445766, PARTNER_1 = 1160459637})
  -- WINDOW:SwitchTalk({PARTNER_0 = 1546650676, PARTNER_1 = 270895044})
  -- WINDOW:SwitchTalk({PARTNER_0 = 155104901, PARTNER_1 = 571729222})
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1.5))
  -- CAMERA:SetFovy(SymCam("CAMERA_07"))
  -- CAMERA:SetEye(SymCam("CAMERA_07"))
  -- CAMERA:SetTgt(SymCam("CAMERA_07"))
  -- EFFECT:Create("effectStarOneStartLp01", SymEff("EV_STAR_ONE_START_LP"))
  -- EFFECT:SetPosition("effectStarOneStartLp01", SymPos("P_EFF_STAR_ONE_START_LP_01"))
  -- EFFECT:Play("effectStarOneStartLp01")
  -- SOUND:PlaySe(SymSnd("SE_EVT_STAR"), Volume(256))
  -- TASK:Sleep(TimeSec(60, TIME_TYPE.FRAME))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetFovy(SymCam("CAMERA_06"))
  -- CAMERA:SetEye(SymCam("CAMERA_06"))
  -- CAMERA:SetTgt(SymCam("CAMERA_06"))
  -- TASK:Sleep(TimeSec(0.3))
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL01)
  -- WINDOW:SwitchTalk({PARTNER_0 = 990434311, PARTNER_1 = 1950958272})
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1.5))
  -- CAMERA:SetFovy(SymCam("CAMERA_07"))
  -- CAMERA:SetEye(SymCam("CAMERA_07"))
  -- CAMERA:SetTgt(SymCam("CAMERA_07"))
  -- EFFECT:Create("effectStarOneStartLp02", SymEff("EV_STAR_ONE_START_LP"))
  -- EFFECT:SetPosition("effectStarOneStartLp02", SymPos("P_EFF_STAR_ONE_START_LP_02"))
  -- EFFECT:Play("effectStarOneStartLp02")
  -- SOUND:PlaySe(SymSnd("SE_EVT_STAR"), Volume(256))
  -- TASK:Sleep(TimeSec(60, TIME_TYPE.FRAME))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetFovy(SymCam("CAMERA_06"))
  -- CAMERA:SetEye(SymCam("CAMERA_06"))
  -- CAMERA:SetTgt(SymCam("CAMERA_06"))
  -- TASK:Sleep(TimeSec(0.3))
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL01)
  -- WINDOW:SwitchTalk({PARTNER_0 = 1834120065, PARTNER_1 = 1182736450})
  -- WINDOW:SwitchTalk({PARTNER_0 = 1600393475, PARTNER_1 = -654570036})
  -- WINDOW:SwitchTalk({PARTNER_0 = -1041810291, PARTNER_1 = -1466310495})
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1.5))
  -- CAMERA:SetFovy(SymCam("CAMERA_07"))
  -- CAMERA:SetEye(SymCam("CAMERA_07"))
  -- CAMERA:SetTgt(SymCam("CAMERA_07"))
  -- TASK:Sleep(TimeSec(0.3))
  -- EFFECT:Create("effectStarOneStartLp03", SymEff("EV_STAR_ONE_START_LP"))
  -- EFFECT:SetPosition("effectStarOneStartLp03", SymPos("P_EFF_STAR_ONE_START_LP_03"))
  -- EFFECT:Play("effectStarOneStartLp03")
  -- SOUND:PlaySe(SymSnd("SE_EVT_STAR"), Volume(256))
  -- TASK:Sleep(TimeSec(60, TIME_TYPE.FRAME))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetFovy(SymCam("CAMERA_06"))
  -- CAMERA:SetEye(SymCam("CAMERA_06"))
  -- CAMERA:SetTgt(SymCam("CAMERA_06"))
  -- TASK:Sleep(TimeSec(0.3))
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL01)
  -- WINDOW:SwitchTalk({PARTNER_0 = -1316826656, PARTNER_1 = -1699773917})
  -- WINDOW:SwitchTalk({PARTNER_0 = -2085309598, PARTNER_1 = -856349275})
  -- WINDOW:SwitchTalk({PARTNER_0 = -705817372, PARTNER_1 = -20756697})
  -- WINDOW:SwitchTalk({PARTNER_0 = -405244314, PARTNER_1 = 1614834345})
  -- WINDOW:KeyWait()
  -- SOUND:FadeOutBgm(TimeSec(2))
  -- WINDOW:SwitchTalk({PARTNER_0 = 2036030440, PARTNER_1 = -1171501233})
  -- WINDOW:SwitchTalk({PARTNER_0 = -1556644338, PARTNER_1 = -2011550259})
  -- WINDOW:CloseMessage()
  -- SCREEN_A:FadeOut(TimeSec(0.3), true)
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1.5))
  -- CAMERA:SetFovy(SymCam("CAMERA_08"))
  -- CAMERA:SetEye(SymCam("CAMERA_08"))
  -- CAMERA:SetTgt(SymCam("CAMERA_08"))
  -- CAMERA:MoveTgt(SymCam("CAMERA_08_5"), Speed(2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- EFFECT:Remove("effectStarOneStartLp01")
  -- EFFECT:Remove("effectStarOneStartLp02")
  -- EFFECT:Remove("effectStarOneStartLp03")
  -- EFFECT:Create("effectStarAllStartLp01", SymEff("EV_STAR_ALL_START_LP"))
  -- EFFECT:SetPosition("effectStarAllStartLp01", SymPos("P_EFF_STAR_ALL_START_LP_01"))
  -- EFFECT:Play("effectStarAllStartLp01")
  -- SOUND:PlaySe(SymSnd("SE_EVT_STAR_SPREAD"), Volume(256))
  -- SOUND:PlaySe(SymSnd("SE_EVT_STAR"), Volume(256))
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- SOUND:PlaySe(SymSnd("SE_EVT_STAR"), Volume(128))
  -- TASK:Sleep(TimeSec(1))
  -- SOUND:PlaySe(SymSnd("SE_EVT_STAR"), Volume(256))
  -- SCREEN_A:FadeOut(TimeSec(0.5), true)
  -- SOUND:PlaySe(SymSnd("SE_EVT_STAR"), Volume(128))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetFovy(SymCam("CAMERA_09_5"))
  -- CAMERA:SetEye(SymCam("CAMERA_09_5"))
  -- CAMERA:SetTgt(SymCam("CAMERA_09_5"))
  -- CAMERA:MoveFollow2(SymCam("CAMERA_09"), Speed(0.8, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- CH("PARTNER"):ResetNeckRot(TimeSec(0))
  -- CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  -- TASK:Sleep(TimeSec(0.5))
  -- EFFECT:Create("effectStarAllStartLp02", SymEff("EV_STAR_ALL_START_LP"))
  -- EFFECT:SetPosition("effectStarAllStartLp02", SymPos("P_EFF_STAR_ALL_START_LP_02"))
  -- EFFECT:Play("effectStarAllStartLp02")
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- EFFECT:Create("effectStarOneStartLp02", SymEff("EV_STAR_ONE_START_LP"))
  -- EFFECT:SetPosition("effectStarOneStartLp02", SymPos("P_EFF_STAR_ONE_START_LP_02"))
  -- EFFECT:Play("effectStarOneStartLp02")
  -- TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
  -- EFFECT:Create("effectStarOneStartLp03", SymEff("EV_STAR_ONE_START_LP"))
  -- EFFECT:SetPosition("effectStarOneStartLp03", SymPos("P_EFF_STAR_ONE_START_LP_03"))
  -- EFFECT:Play("effectStarOneStartLp03")
  -- TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
  -- EFFECT:Create("effectStarOneStartLp04", SymEff("EV_STAR_ONE_START_LP"))
  -- EFFECT:SetPosition("effectStarOneStartLp04", SymPos("P_EFF_STAR_ONE_START_LP_04"))
  -- EFFECT:Play("effectStarOneStartLp04")
  -- TASK:Sleep(TimeSec(7, TIME_TYPE.FRAME))
  -- EFFECT:Create("effectStarOneStartLp01", SymEff("EV_STAR_ONE_START_LP"))
  -- EFFECT:SetPosition("effectStarOneStartLp01", SymPos("P_EFF_STAR_ONE_START_LP_01"))
  -- EFFECT:Play("effectStarOneStartLp01")
  -- TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
  -- EFFECT:Create("effectStarOneStartLp05", SymEff("EV_STAR_ONE_START_LP"))
  -- EFFECT:SetPosition("effectStarOneStartLp05", SymPos("P_EFF_STAR_ONE_START_LP_05"))
  -- EFFECT:Play("effectStarOneStartLp05")
  -- TASK:Sleep(TimeSec(3, TIME_TYPE.FRAME))
  -- EFFECT:Create("effectStarOneStartLp06", SymEff("EV_STAR_ONE_START_LP"))
  -- EFFECT:SetPosition("effectStarOneStartLp06", SymPos("P_EFF_STAR_ONE_START_LP_06"))
  -- EFFECT:Play("effectStarOneStartLp06")
  -- TASK:Sleep(TimeSec(7, TIME_TYPE.FRAME))
  -- EFFECT:Create("effectStarOneStartLp07", SymEff("EV_STAR_ONE_START_LP"))
  -- EFFECT:SetPosition("effectStarOneStartLp07", SymPos("P_EFF_STAR_ONE_START_LP_07"))
  -- EFFECT:Play("effectStarOneStartLp07")
  -- TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
  -- EFFECT:Create("effectStarOneStartLp08", SymEff("EV_STAR_ONE_START_LP"))
  -- EFFECT:SetPosition("effectStarOneStartLp08", SymPos("P_EFF_STAR_ONE_START_LP_08"))
  -- EFFECT:Play("effectStarOneStartLp08")
  -- TASK:Sleep(TimeSec(3, TIME_TYPE.FRAME))
  -- EFFECT:Create("effectStarOneStartLp09", SymEff("EV_STAR_ONE_START_LP"))
  -- EFFECT:SetPosition("effectStarOneStartLp09", SymPos("P_EFF_STAR_ONE_START_LP_09"))
  -- EFFECT:Play("effectStarOneStartLp09")
  -- TASK:Sleep(TimeSec(7, TIME_TYPE.FRAME))
  -- EFFECT:Create("effectStarOneStartLp10", SymEff("EV_STAR_ONE_START_LP"))
  -- EFFECT:SetPosition("effectStarOneStartLp10", SymPos("P_EFF_STAR_ONE_START_LP_10"))
  -- EFFECT:Play("effectStarOneStartLp10")
  -- TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
  -- EFFECT:Create("effectStarOneStartLp11", SymEff("EV_STAR_ONE_START_LP"))
  -- EFFECT:SetPosition("effectStarOneStartLp11", SymPos("P_EFF_STAR_ONE_START_LP_11"))
  -- EFFECT:Play("effectStarOneStartLp11")
  -- TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
  -- CAMERA:WaitMove()
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  -- WINDOW:SwitchTalk({PARTNER_0 = -1862198132, PARTNER_1 = -566195637})
  -- WINDOW:CloseMessage()
  -- SOUND:FadeOutSe(SymSnd("SE_EVT_STAR_SPREAD"), TimeSec(1.5))
  -- TASK:Sleep(TimeSec(2))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetFovy(SymCam("CAMERA_09_6"))
  -- CAMERA:SetEye(SymCam("CAMERA_09_6"))
  -- CAMERA:SetTgt(SymCam("CAMERA_09_6"))
  -- TASK:Sleep(TimeSec(0.2))
  -- EFFECT:Remove("effectStarAllStartLp02")
  -- EFFECT:Create("effectStarAllEnd02", SymEff("EV_STAR_ALL_END"))
  -- EFFECT:SetPosition("effectStarAllEnd02", SymPos("P_EFF_STAR_ALL_START_LP_02"))
  -- EFFECT:Play("effectStarAllEnd02")
  -- SOUND:PlaySe(SymSnd("SE_EVT_STAR_DIE"), Volume(256))
  -- EFFECT:ChangeColor("effectStarOneStartLp05", Color(1, 1, 1, 0), TimeSec(7, TIME_TYPE.FRAME))
  -- TASK:Sleep(TimeSec(15, TIME_TYPE.FRAME))
  -- SOUND:PlaySe(SymSnd("SE_EVT_STAR_DIE"), Volume(256))
  -- EFFECT:ChangeColor("effectStarOneStartLp03", Color(1, 1, 1, 0), TimeSec(7, TIME_TYPE.FRAME))
  -- TASK:Sleep(TimeSec(15, TIME_TYPE.FRAME))
  -- SOUND:PlaySe(SymSnd("SE_EVT_STAR_DIE"), Volume(256))
  -- EFFECT:ChangeColor("effectStarOneStartLp08", Color(1, 1, 1, 0), TimeSec(7, TIME_TYPE.FRAME))
  -- TASK:Sleep(TimeSec(15, TIME_TYPE.FRAME))
  -- SOUND:PlaySe(SymSnd("SE_EVT_STAR_DIE"), Volume(256))
  -- EFFECT:ChangeColor("effectStarOneStartLp07", Color(1, 1, 1, 0), TimeSec(7, TIME_TYPE.FRAME))
  -- TASK:Sleep(TimeSec(15, TIME_TYPE.FRAME))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetFovy(SymCam("CAMERA_09"))
  -- CAMERA:SetEye(SymCam("CAMERA_09"))
  -- CAMERA:SetTgt(SymCam("CAMERA_09"))
  -- TASK:Sleep(TimeSec(7, TIME_TYPE.FRAME))
  -- SOUND:PlaySe(SymSnd("SE_EVT_STAR_DIE"), Volume(256))
  -- EFFECT:ChangeColor("effectStarOneStartLp11", Color(1, 1, 1, 0), TimeSec(7, TIME_TYPE.FRAME))
  -- TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
  -- SOUND:PlaySe(SymSnd("SE_EVT_STAR_DIE"), Volume(256))
  -- EFFECT:ChangeColor("effectStarOneStartLp10", Color(1, 1, 1, 0), TimeSec(7, TIME_TYPE.FRAME))
  -- TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
  -- SOUND:PlaySe(SymSnd("SE_EVT_STAR_DIE"), Volume(256))
  -- EFFECT:ChangeColor("effectStarOneStartLp02", Color(1, 1, 1, 0), TimeSec(7, TIME_TYPE.FRAME))
  -- TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
  -- SOUND:PlaySe(SymSnd("SE_EVT_STAR_DIE"), Volume(256))
  -- EFFECT:ChangeColor("effectStarOneStartLp06", Color(1, 1, 1, 0), TimeSec(7, TIME_TYPE.FRAME))
  -- TASK:Sleep(TimeSec(7, TIME_TYPE.FRAME))
  -- EFFECT:Remove("effectStarAllStartLp01")
  -- EFFECT:Create("effectStarAllEnd01", SymEff("EV_STAR_ALL_END"))
  -- EFFECT:SetPosition("effectStarAllEnd01", SymPos("P_EFF_STAR_ALL_START_LP_01"))
  -- EFFECT:Play("effectStarAllEnd01")
  -- SOUND:PlaySe(SymSnd("SE_EVT_STAR_DIE"), Volume(256))
  -- EFFECT:ChangeColor("effectStarOneStartLp04", Color(1, 1, 1, 0), TimeSec(7, TIME_TYPE.FRAME))
  -- TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
  -- SOUND:PlaySe(SymSnd("SE_EVT_STAR_DIE"), Volume(256))
  -- EFFECT:ChangeColor("effectStarOneStartLp09", Color(1, 1, 1, 0), TimeSec(7, TIME_TYPE.FRAME))
  -- TASK:Sleep(TimeSec(6, TIME_TYPE.FRAME))
  -- SOUND:PlaySe(SymSnd("SE_EVT_STAR_DIE"), Volume(256))
  -- EFFECT:ChangeColor("effectStarOneStartLp01", Color(1, 1, 1, 0), TimeSec(7, TIME_TYPE.FRAME))
  -- TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
  -- SCREEN_A:FadeOut(TimeSec(0.5), true)
  -- EFFECT:Remove("effectStarOneStartLp01")
  -- EFFECT:Remove("effectStarOneStartLp02")
  -- EFFECT:Remove("effectStarOneStartLp03")
  -- EFFECT:Remove("effectStarOneStartLp04")
  -- EFFECT:Remove("effectStarOneStartLp05")
  -- EFFECT:Remove("effectStarOneStartLp06")
  -- EFFECT:Remove("effectStarOneStartLp07")
  -- EFFECT:Remove("effectStarOneStartLp08")
  -- EFFECT:Remove("effectStarOneStartLp09")
  -- EFFECT:Remove("effectStarOneStartLp10")
  -- EFFECT:Remove("effectStarOneStartLp11")
  -- EFFECT:Remove("effectStarAllEnd01")
  -- EFFECT:Remove("effectStarAllEnd02")
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetFovy(SymCam("CAMERA_08_5"))
  -- CAMERA:SetEye(SymCam("CAMERA_08_5"))
  -- CAMERA:SetTgt(SymCam("CAMERA_08_5"))
  -- CAMERA:MoveTgt(SymCam("CAMERA_08"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- EFFECT:Remove("effectStarLp")
  -- EFFECT:Create("effectStarEnd01", SymEff("EV_STAR_END"))
  -- EFFECT:SetPosition("effectStarEnd01", SymPos("P_EFF_STAR_END_01"))
  -- local taskSeiunKesu = function()
  --   EFFECT:Play("effectStarEnd01")
  --   TASK:Sleep(TimeSec(30, TIME_TYPE.FRAME))
  --   GM("EV_650_STARBACK_R"):ChangeColor(Color(1, 1, 1, 0), TimeSec(10, TIME_TYPE.FRAME))
  --   TASK:Sleep(TimeSec(20, TIME_TYPE.FRAME))
  --   GM("EV_650_STARBACK_L"):ChangeColor(Color(1, 1, 1, 0), TimeSec(15, TIME_TYPE.FRAME))
  -- end
  -- TASK:Regist(taskSeiunKesu)
  -- subEveFadeAfterTime()
  -- SOUND:PlaySe(SymSnd("SE_EVT_STAR_DIE_LP"), Volume(256))
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- SOUND:PlaySe(SymSnd("SE_EVT_STAR_DIE"), Volume(256))
  -- TASK:Sleep(TimeSec(1))
  -- SOUND:PlaySe(SymSnd("SE_EVT_STAR_DIE"), Volume(128))
  -- TASK:Sleep(TimeSec(1))
  -- SOUND:PlaySe(SymSnd("SE_EVT_STAR_DIE"), Volume(256))
  -- SCREEN_A:FadeOut(TimeSec(0.5), true)
  -- subEveFadeAfterTime()
  -- EFFECT:Remove("effectStarAllEnd01")
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetFovy(SymCam("CAMERA_09"))
  -- CAMERA:SetEye(SymCam("CAMERA_09"))
  -- CAMERA:SetTgt(SymCam("CAMERA_09"))
  -- EFFECT:Create("effectStarOneStartLp05", SymEff("EV_STAR_ONE_START_LP"))
  -- EFFECT:SetPosition("effectStarOneStartLp05", SymPos("P_EFF_STAR_ONE_START_LP_05"))
  -- EFFECT:Play("effectStarOneStartLp05")
  -- EFFECT:Create("effectStarOneStartLp06", SymEff("EV_STAR_ONE_START_LP"))
  -- EFFECT:SetPosition("effectStarOneStartLp06", SymPos("P_EFF_STAR_ONE_START_LP_06"))
  -- EFFECT:Play("effectStarOneStartLp06")
  -- EFFECT:Create("effectStarOneStartLp02", SymEff("EV_STAR_ONE_START_LP"))
  -- EFFECT:SetPosition("effectStarOneStartLp02", SymPos("P_EFF_STAR_ONE_START_LP_02"))
  -- EFFECT:Play("effectStarOneStartLp02")
  -- subEveFadeAfterTime()
  -- SCREEN_A:FadeIn(TimeSec(0.3), true)
  -- SOUND:PlaySe(SymSnd("SE_EVT_STAR_DIE"), Volume(256))
  -- EFFECT:ChangeColor("effectStarOneStartLp05", Color(1, 1, 1, 0), TimeSec(7, TIME_TYPE.FRAME))
  -- TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
  -- SOUND:PlaySe(SymSnd("SE_EVT_STAR_DIE"), Volume(256))
  -- EFFECT:ChangeColor("effectStarOneStartLp06", Color(1, 1, 1, 0), TimeSec(7, TIME_TYPE.FRAME))
  -- TASK:Sleep(TimeSec(20, TIME_TYPE.FRAME))
  -- SOUND:PlaySe(SymSnd("SE_EVT_STAR_DIE"), Volume(256))
  -- EFFECT:ChangeColor("effectStarOneStartLp02", Color(1, 1, 1, 0), TimeSec(7, TIME_TYPE.FRAME))
  -- TASK:Sleep(TimeSec(0.8))
  -- TASK:Sleep(TimeSec(2))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetFovy(SymCam("CAMERA_06"))
  -- CAMERA:SetEye(SymCam("CAMERA_06"))
  -- CAMERA:SetTgt(SymCam("CAMERA_06"))
  -- TASK:Sleep(TimeSec(0.5))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  -- CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  -- CH("PARTNER"):WaitManpu()
  -- TASK:Sleep(TimeSec(0.5))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetFovy(SymCam("CAMERA_05"))
  -- CAMERA:SetEye(SymCam("CAMERA_05"))
  -- CAMERA:SetTgt(SymCam("CAMERA_05"))
  -- SOUND:FadeInEnv(SymSnd("SE_EVT_EARTHQUAKE_M_LP"), TimeSec(1), Volume(64))
  -- CAMERA:SetShake(Vector2(0.01, 0), TimeSec(0.5, TIME_TYPE.FRAME))
  -- TASK:Sleep(TimeSec(0.5))
  -- TASK:Regist(subEveLookAround02, {
  --   CH("PARTNER"),
  --   Speed(600)
  -- })
  -- TASK:Sleep(TimeSec(0.2))
  -- TASK:Regist(subEveLookAround, {
  --   CH("SAZANDORA_LARGE"),
  --   Speed(400)
  -- })
  -- TASK:Sleep(TimeSec(0.5))
  -- SOUND:VolumeEnv(Volume(190), TimeSec(0.5))
  -- CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  -- TASK:Sleep(TimeSec(1.5))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  -- CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  -- CH("PARTNER"):WaitManpu()
  -- CH("PARTNER"):DirTo(CH("SAZANDORA_LARGE"), Speed(350), ROT_TYPE.NEAR)
  -- CH("PARTNER"):WaitRotate()
  -- WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  -- WINDOW:SwitchTalk({PARTNER_0 = -950289654, PARTNER_1 = -327751479})
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  -- CAMERA:SetFovy(SymCam("CAMERA_10"))
  -- CAMERA:SetEye(SymCam("CAMERA_10"))
  -- CAMERA:SetTgt(SymCam("CAMERA_10"))
  -- SOUND:PlayBgm(SymSnd("SE_EVT_YAYAKOWA_LP"), Volume(256))
  -- CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
  -- WINDOW:DrawFace(20, 20, SymAct("SAZANDORA"), FACE_TYPE.PAIN)
  -- WINDOW:Talk(SymAct("SAZANDORA"), -177350264)
  -- WINDOW:Talk(SymAct("SAZANDORA"), 1928709447)
  -- WINDOW:CloseMessage()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  -- CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  -- CH("PARTNER"):WaitManpu()
  -- WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  -- WINDOW:SwitchTalk({PARTNER_0 = 1810822150, PARTNER_1 = 43001898})
  -- subEveCloseMsg()
  -- CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.SAD)
  -- WINDOW:DrawFace(20, 20, SymAct("SAZANDORA"), FACE_TYPE.SAD)
  -- WINDOW:Talk(SymAct("SAZANDORA"), 462100843)
  -- WINDOW:Talk(SymAct("SAZANDORA"), 816204456)
  -- WINDOW:Talk(SymAct("SAZANDORA"), 700283881)
  -- WINDOW:Talk(SymAct("SAZANDORA"), 1727851822)
  -- WINDOW:Talk(SymAct("SAZANDORA"), 2145901679)
  -- WINDOW:KeyWait()
  -- CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
  -- WINDOW:DrawFace(20, 20, SymAct("SAZANDORA"), FACE_TYPE.PAIN)
  -- WINDOW:Talk(SymAct("SAZANDORA"), 1422561196)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  -- CAMERA:SetFovy(SymCam("CAMERA_11"))
  -- CAMERA:SetEye(SymCam("CAMERA_11"))
  -- CAMERA:SetTgt(SymCam("CAMERA_11"))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  -- CH("PARTNER"):SetManpu("MP_SHOCK_L")
  -- CH("PARTNER"):WaitManpu()
  -- WINDOW:DrawFace(324, 20, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  -- WINDOW:SwitchTalk({PARTNER_0 = 1305591533, PARTNER_1 = -901144030})
  -- WINDOW:CloseMessage()
  -- subEveLookAround(CH("PARTNER"), Speed(600))
  -- TASK:Sleep(TimeSec(0.3))
  -- CH("PARTNER"):DirTo(CH("SAZANDORA_LARGE"), Speed(350), ROT_TYPE.NEAR)
  -- CH("PARTNER"):WaitRotate()
  -- WINDOW:DrawFace(324, 20, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  -- WINDOW:SwitchTalk({PARTNER_0 = -749563037, PARTNER_1 = 1525889148})
  -- WINDOW:SwitchTalk({PARTNER_0 = 1139280189, PARTNER_1 = 1757764350})
  -- WINDOW:SwitchTalk({PARTNER_0 = 1910401983, PARTNER_1 = 1050672504})
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  -- CAMERA:SetFovy(SymCam("CAMERA_10"))
  -- CAMERA:SetEye(SymCam("CAMERA_10"))
  -- CAMERA:SetTgt(SymCam("CAMERA_10"))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  -- CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
  -- CH("SAZANDORA_LARGE"):SetManpu("MP_FLY_SWEAT")
  -- CH("SAZANDORA_LARGE"):WaitManpu()
  -- WINDOW:DrawFace(20, 20, SymAct("SAZANDORA"), FACE_TYPE.PAIN)
  -- WINDOW:Talk(SymAct("SAZANDORA"), 663014457)
  -- WINDOW:Talk(SymAct("SAZANDORA"), 212443130)
  -- WINDOW:Talk(SymAct("SAZANDORA"), 364031675)
  -- WINDOW:Talk(SymAct("SAZANDORA"), -1842695564)
  -- WINDOW:Talk(SymAct("SAZANDORA"), -1959689419)
  -- WINDOW:CloseMessage()
  -- CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  -- CAMERA:SetFovy(SymCam("CAMERA_13"))
  -- CAMERA:SetEye(SymCam("CAMERA_13"))
  -- CAMERA:SetTgt(SymCam("CAMERA_13"))
  -- TASK:Sleep(TimeSec(0.2))
  -- TASK:Regist(subEveDoubleJump, {
  --   CH("SAZANDORA_LARGE")
  -- })
  -- WINDOW:Talk(SymAct("SAZANDORA"), -498114791)
  -- WINDOW:Talk(SymAct("SAZANDORA"), -78352808)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  -- CAMERA:SetFovy(SymCam("CAMERA_11"))
  -- CAMERA:SetEye(SymCam("CAMERA_11"))
  -- CAMERA:SetTgt(SymCam("CAMERA_11"))
  -- TASK:Sleep(TimeSec(0.3))
  -- WINDOW:DrawFace(324, 20, SymAct("PARTNER"), FACE_TYPE.SAD)
  -- WINDOW:SwitchTalk({PARTNER_0 = -797360741, PARTNER_1 = -916321062})
  -- WINDOW:SwitchTalk({PARTNER_0 = -2044487139, PARTNER_1 = -1623676068})
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.PAIN)
  -- WINDOW:Talk(SymAct("SAZANDORA"), -1273628513)
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(324, 20, SymAct("PARTNER"), FACE_TYPE.SAD)
  -- WINDOW:SwitchTalk({PARTNER_0 = -1391539746, PARTNER_1 = 714528017})
  -- WINDOW:CloseMessage()
  -- CH("PARTNER"):DirTo(RotateTarget(-135), Speed(350), ROT_TYPE.NEAR)
  -- CH("PARTNER"):WaitRotate()
  -- TASK:Sleep(TimeSec(1.5))
  -- CH("PARTNER"):DirTo(CH("SAZANDORA_LARGE"), Speed(350), ROT_TYPE.NEAR)
  -- CH("PARTNER"):WaitRotate()
  -- SOUND:FadeOutBgm(TimeSec(2))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  -- CAMERA:SetFovy(SymCam("CAMERA_12"))
  -- CAMERA:SetEye(SymCam("CAMERA_12"))
  -- CAMERA:SetTgt(SymCam("CAMERA_12"))
  -- CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SHOUT)
  -- TASK:Regist(subEveDoubleJump, {
  --   CH("PARTNER")
  -- })
  -- WINDOW:SwitchTalk({PARTNER_0 = 864937040, PARTNER_1 = 303604051})
  -- WINDOW:SwitchTalk({PARTNER_0 = 184782866, PARTNER_1 = 539935697})
  -- WINDOW:SwitchTalk({PARTNER_0 = 959836816, PARTNER_1 = 1987339351})
  -- WINDOW:KeyWait()
  -- TASK:Regist(subEveDoubleJump, {
  --   CH("PARTNER")
  -- })
  -- WINDOW:SwitchTalk({PARTNER_0 = 1869567254, PARTNER_1 = 1145177813})
  -- WINDOW:SwitchTalk({PARTNER_0 = 1566128020, PARTNER_1 = -624874661})
  -- WINDOW:CloseMessage()
  -- SOUND:FadeOutEnv(TimeSec(1))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  -- CAMERA:SetFovy(SymCam("CAMERA_13"))
  -- CAMERA:SetEye(SymCam("CAMERA_13"))
  -- CAMERA:SetTgt(SymCam("CAMERA_13"))
  -- TASK:Sleep(TimeSec(0.2))
  -- WINDOW:Talk(SymAct("SAZANDORA"), -1009116646)
  -- SOUND:PlayBgm(SymSnd("BGM_EVE_GANBARE"), Volume(256))
  -- WINDOW:Talk(SymAct("SAZANDORA"), -1432041930)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  -- CAMERA:SetFovy(SymCam("CAMERA_12"))
  -- CAMERA:SetEye(SymCam("CAMERA_12"))
  -- CAMERA:SetTgt(SymCam("CAMERA_12"))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  -- CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  -- CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  -- CH("PARTNER"):WaitManpu()
  -- WINDOW:SwitchTalk({PARTNER_0 = -1279264905, PARTNER_1 = -1735220044})
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  -- CAMERA:SetFovy(SymCam("CAMERA_13"))
  -- CAMERA:SetEye(SymCam("CAMERA_13"))
  -- CAMERA:SetTgt(SymCam("CAMERA_13"))
  -- TASK:Sleep(TimeSec(0.3))
  -- WINDOW:Talk(SymAct("SAZANDORA"), -2121689611)
  -- WINDOW:Talk(SymAct("SAZANDORA"), -825752782)
  -- WINDOW:Talk(SymAct("SAZANDORA"), -674024845)
  -- WINDOW:Talk(SymAct("SAZANDORA"), -50437712)
  -- WINDOW:Talk(SymAct("SAZANDORA"), -437956367)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  -- CAMERA:SetFovy(SymCam("CAMERA_12"))
  -- CAMERA:SetEye(SymCam("CAMERA_12"))
  -- CAMERA:SetTgt(SymCam("CAMERA_12"))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  -- CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  -- CH("PARTNER"):WaitManpu()
  -- WINDOW:SwitchTalk({PARTNER_0 = 1652378686, PARTNER_1 = 2070314367})
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  -- CAMERA:SetFovy(SymCam("CAMERA_05"))
  -- CAMERA:SetEye(SymCam("CAMERA_05"))
  -- CAMERA:SetTgt(SymCam("CAMERA_05"))
  -- TASK:Sleep(TimeSec(0.3))
  -- WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("SAZANDORA"), -1206818344)
  -- WINDOW:Talk(SymAct("SAZANDORA"), -1593157479)
  -- WINDOW:Talk(SymAct("SAZANDORA"), -1977152678)
  -- WINDOW:CloseMessage()
  -- SOUND:PlaySe(SymSnd("SE_EVT_BEAT"), Volume(256))
  -- SCREEN_A:WhiteChange(Level(0), Level(0.5), TimeSec(0.05), true)
  -- TASK:Sleep(TimeSec(0.1))
  -- CAMERA:SetEye(SymCam("CAMERA_05_5"))
  -- CAMERA:SetTgt(SymCam("CAMERA_05_5"))
  -- EFFECT:StartMotionBlur(0.04, 0.9, 0)
  -- SCREEN_A:WhiteChange(Level(1), Level(0), TimeSec(0.02), true)
  -- TASK:Sleep(TimeSec(0.4))
  -- CAMERA:MoveFollow2(SymCam("CAMERA_05"), Speed(50, ACCEL_TYPE.NONE, DECEL_TYPE.NONE))
  -- CAMERA:WaitMove()
  -- EFFECT:EndMotionBlur()
  -- TASK:Sleep(TimeSec(0.3))
  -- WINDOW:Monologue(-1824769509)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  -- CAMERA:SetFovy(SymCam("CAMERA_12"))
  -- CAMERA:SetEye(SymCam("CAMERA_12"))
  -- CAMERA:SetTgt(SymCam("CAMERA_12"))
  -- WINDOW:SwitchTalk({PARTNER_0 = -595743524, PARTNER_1 = -983130723})
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  -- CAMERA:SetFovy(SymCam("CAMERA_13"))
  -- CAMERA:SetEye(SymCam("CAMERA_13"))
  -- CAMERA:SetTgt(SymCam("CAMERA_13"))
  -- TASK:Sleep(TimeSec(0.3))
  -- WINDOW:Talk(SymAct("SAZANDORA"), -297021858)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2.5))
  -- CAMERA:SetFovy(SymCam("CAMERA_14"))
  -- CAMERA:SetEye(SymCam("CAMERA_14"))
  -- CAMERA:SetTgt(SymCam("CAMERA_14"))
  -- CH("SAZANDORA_LARGE"):DirTo(SymPos("P_CAMERA"), Speed(200), ROT_TYPE.NEAR)
  -- CH("SAZANDORA_LARGE"):WaitRotate()
  -- CH("SAZANDORA_LARGE"):SetNeckRot(RotateTarget(0), RotateTarget(20), RotateTarget(0), TimeSec(0.45))
  -- CH("PARTNER"):DirTo(SymPos("P_CAMERA"), Speed(200), ROT_TYPE.NEAR)
  -- CH("PARTNER"):WaitRotate()
  -- CH("PARTNER"):SetNeckRot(RotateTarget(0), RotateTarget(20), RotateTarget(0), TimeSec(0.35))
  -- TASK:Sleep(TimeSec(0.8))
  -- WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("SAZANDORA"), -145686753)
  -- WINDOW:Talk(SymAct("SAZANDORA"), 1892213712)
  -- WINDOW:Talk(SymAct("SAZANDORA"), 1775489681)
  -- WINDOW:Talk(SymAct("SAZANDORA"), 11341501)
  -- WINDOW:Talk(SymAct("SAZANDORA"), 431374332)
  -- WINDOW:Talk(SymAct("SAZANDORA"), 849046591)
  -- WINDOW:Talk(SymAct("SAZANDORA"), 729832830)
  -- WINDOW:Talk(SymAct("SAZANDORA"), 1690422201)
  -- subEveCloseMsg()
  local taskBeatLoop = function()
    function TaskL.Loop()
      SCREEN_A:WhiteChange(Level(0), Level(0.5), TimeSec(0.05), true)
      TASK:Sleep(TimeSec(0.1))
      CAMERA:SetEye(SymCam("CAMERA_14_5"))
      CAMERA:SetTgt(SymCam("CAMERA_14_5"))
      SOUND:PlaySe(SymSnd("SE_EVT_BEAT"), Volume(256))
      EFFECT:StartMotionBlur(0.04, 0.9, 0)
      SCREEN_A:WhiteChange(Level(1), Level(0), TimeSec(0.02), true)
      TASK:Sleep(TimeSec(0.5))
      CAMERA:MoveFollow2(SymCam("CAMERA_14"), Speed(40, ACCEL_TYPE.NONE, DECEL_TYPE.NONE))
      CAMERA:WaitMove()
      EFFECT:EndMotionBlur()
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.5))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.5))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
    end
    function TaskL.Finish()
      return
    end
  end
  TASK:Regist(taskBeatLoop)
  local __LB_SCOPE = function()
    local __scopeFuncTbl = {}
    function __scopeFuncTbl.__LB_FIRST()
    end
    function __scopeFuncTbl.LABEL_TOP()
      WINDOW:Monologue(2111503096)
      subEveCloseMsg()
      WINDOW:SysMsg(1459071291)
      local __labelCnt = 0
      local __labelTbl = {}
      WINDOW:SelectStart()
      WINDOW:SelectChain(1340905594, __labelCnt)
      WINDOW:DefaultCursor(__labelCnt)
      __labelTbl[__labelCnt] = __scopeFuncTbl.LABEL_YES
      __labelCnt = __labelCnt + 1
      WINDOW:SelectChain(-931887947, __labelCnt)
      __labelTbl[__labelCnt] = __scopeFuncTbl.LABEL_NO
      __labelCnt = __labelCnt + 1
      local __res = WINDOW:SelectEnd(MENU_SELECT_MODE.DISABLE_CANCEL)
      return __labelTbl[__res]
    end
    function __scopeFuncTbl.LABEL_NO()
      TASK:WaitTask()
      EFFECT:Create("effectFrameBlackInLp", SymEff("BG_FRAME_BLACK_IN_LP"))
      EFFECT:SetPosition("effectFrameBlackInLp", SymPos("P_EFF_STAR_LP"))
      EFFECT:Play("effectFrameBlackInLp")
      SOUND:PlaySe(SymSnd("SE_EVT_GUWA_01"), Volume(256))
      EFFECT:StartMotionBlur(0.04, 0.9, 0)
      CAMERA:MoveFollow2(SymCam("CAMERA_14_6"), Speed(2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
      CAMERA:WaitMove()
      EFFECT:EndMotionBlur()
      TASK:Sleep(TimeSec(1))
      local taskBeatLoop02 = function()
        function TaskL.Loop()
          SCREEN_A:WhiteChange(Level(0), Level(0.5), TimeSec(0.05), true)
          TASK:Sleep(TimeSec(0.1))
          CAMERA:SetEye(SymCam("CAMERA_14"))
          CAMERA:SetTgt(SymCam("CAMERA_14"))
          SOUND:PlaySe(SymSnd("SE_EVT_BEAT"), Volume(256))
          EFFECT:StartMotionBlur(0.04, 0.9, 0)
          SCREEN_A:WhiteChange(Level(1), Level(0), TimeSec(0.02), true)
          TASK:Sleep(TimeSec(0.5))
          CAMERA:MoveFollow2(SymCam("CAMERA_14_6"), Speed(40, ACCEL_TYPE.NONE, DECEL_TYPE.NONE))
          CAMERA:WaitMove()
          EFFECT:EndMotionBlur()
          TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
          TASK:Sleep(TimeSec(0.5))
          TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
          TASK:Sleep(TimeSec(0.5))
          TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
          TASK:Sleep(TimeSec(0.25))
          TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
        end
        function TaskL.Finish()
          return
        end
      end
      TASK:Regist(taskBeatLoop02)
      WINDOW:Monologue(-781208076)
      WINDOW:Monologue(-1652935164)
      WINDOW:Monologue(-2074015931)
      WINDOW:Monologue(-1353952122)
      WINDOW:Monologue(-1235786297)
      subEveCloseMsg()
      WINDOW:SysMsg(-115936512)
      local __labelCnt = 0
      local __labelTbl = {}
      WINDOW:SelectStart()
      WINDOW:SelectChain(-535969215, __labelCnt)
      __labelTbl[__labelCnt] = __scopeFuncTbl.LABEL_YES_2
      __labelCnt = __labelCnt + 1
      WINDOW:SelectChain(-887058046, __labelCnt)
      WINDOW:DefaultCursor(__labelCnt)
      __labelTbl[__labelCnt] = __scopeFuncTbl.LABEL_TOP
      __labelCnt = __labelCnt + 1
      local __res = WINDOW:SelectEnd(MENU_SELECT_MODE.DISABLE_CANCEL)
      return __labelTbl[__res]
    end
    function __scopeFuncTbl.LABEL_YES_2()
      WINDOW:SysMsg(-767844157)
      local __labelCnt = 0
      local __labelTbl = {}
      WINDOW:SelectStart()
      WINDOW:SelectChain(1436793868, __labelCnt)
      __labelTbl[__labelCnt] = __scopeFuncTbl.LABEL_YES_3
      __labelCnt = __labelCnt + 1
      WINDOW:SelectChain(1287163213, __labelCnt)
      WINDOW:DefaultCursor(__labelCnt)
      __labelTbl[__labelCnt] = __scopeFuncTbl.LABEL_TOP
      __labelCnt = __labelCnt + 1
      local __res = WINDOW:SelectEnd(MENU_SELECT_MODE.DISABLE_CANCEL)
      return __labelTbl[__res]
    end
    function __scopeFuncTbl.LABEL_YES_3()
      SOUND:FadeOutBgm(TimeSec(2.5))
      TASK:WaitTask()
      TASK:Sleep(TimeSec(0.5))
      SOUND:PlaySe(SymSnd("SE_EVT_GUWA_02"), Volume(256))
      EFFECT:StartMotionBlur(0.04, 0.9, 0)
      CAMERA:MoveFollow2(SymCam("CAMERA_14_7"), Speed(2.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
      TASK:Sleep(TimeSec(0.5))
      SCREEN_A:FadeOut(TimeSec(1.5), true)
      CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
      EFFECT:EndMotionBlur()
      TASK:Sleep(TimeSec(1))
      WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), 633753953)
      WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), 1021141024)
      WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), 401617891)
      WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), 250282658)
      WINDOW:Narration(TimeSec(0.5), TimeSec(1), 1101698149)
      WINDOW:CloseMessage()
      SOUND:FadeOutBgm(TimeSec(2))
      TASK:Sleep(TimeSec(2))
      return __scopeFuncTbl.LABEL_END
    end
    function __scopeFuncTbl.LABEL_YES()
      TASK:WaitTask()
      -- SOUND:FadeOutBgm(TimeSec(2))
      -- WINDOW:Monologue(1488037156)
      -- WINDOW:Monologue(1939666663)
      -- WINDOW:CloseMessage()
      -- SCREEN_A:FadeOut(TimeSec(0), true)
      -- TASK:Sleep(TimeSec(0.3))
      -- EFFECT:Remove("effectFrameBlackInLp")
      -- CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
      -- WINDOW:Narration(TimeSec(0), TimeSec(0), 1787283366)
      -- WINDOW:Narration(TimeSec(0), TimeSec(0), -316679319)
      -- WINDOW:Narration(TimeSec(0), TimeSec(0), -201004504)
      -- WINDOW:Narration(TimeSec(0), TimeSec(0), 930348687)
      -- WINDOW:Narration(TimeSec(0), TimeSec(0), 778620878)
      -- WINDOW:CloseMessage()
      -- SOUND:PlaySe(SymSnd("SE_EVT_WHITEOUT"), Volume(256))
      -- SCREEN_A:WhiteOutAll(TimeSec(0.5), true)
      -- TASK:Sleep(TimeSec(2))
      -- SOUND:PlaySe(SymSnd("SE_EVT_STAR_SPREAD"), Volume(64))
      -- SCREEN_A:FadeIn(TimeSec(0), true)
      -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
      -- CAMERA:SetFovy(SymCam("CAMERA_08"))
      -- CAMERA:SetEye(SymCam("CAMERA_08"))
      -- CAMERA:SetTgt(SymCam("CAMERA_08"))
      -- CAMERA:MoveTgt(SymCam("CAMERA_08_5"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
      -- EFFECT:Create("effectStarLp", SymEff("EV_STAR_LP"))
      -- EFFECT:SetPosition("effectStarLp", SymPos("P_EFF_STAR_LP"))
      -- EFFECT:Play("effectStarLp")
      -- GM("EV_650_STARBACK_R"):ChangeColor(Color(1, 1, 1, 1), TimeSec(0, TIME_TYPE.FRAME))
      -- GM("EV_650_STARBACK_L"):ChangeColor(Color(1, 1, 1, 1), TimeSec(0, TIME_TYPE.FRAME))
      -- SCREEN_A:WhiteInAll(TimeSec(1.5), true)
      -- TASK:Sleep(TimeSec(2.5))
      -- SCREEN_A:FadeOut(TimeSec(0.5), true)
      -- subEveFadeAfterTime()
      -- CAMERA:SetAzimuthDifferenceVolume(Volume(2))
      -- CAMERA:SetFovy(SymCam("CAMERA_15"))
      -- CAMERA:SetEye(SymCam("CAMERA_15"))
      -- CAMERA:SetTgt(SymCam("CAMERA_15"))
      -- CAMERA:MoveFollow2(SymCam("CAMERA_15_5"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
      -- SCREEN_A:FadeIn(TimeSec(0.5), true)
      -- TASK:Regist(subEveLookAround02, {
      --   CH("PARTNER"),
      --   Speed(400)
      -- })
      -- TASK:Sleep(TimeSec(0.2))
      -- TASK:Regist(subEveLookAround, {
      --   CH("SAZANDORA_LARGE"),
      --   Speed(300)
      -- })
      -- CAMERA:WaitMove()
      -- SOUND:FadeOutSe(SymSnd("SE_EVT_STAR_SPREAD"), TimeSec(3))
      -- CAMERA:SetAzimuthDifferenceVolume(Volume(3))
      -- CAMERA:SetFovy(SymCam("CAMERA_16"))
      -- CAMERA:SetEye(SymCam("CAMERA_16"))
      -- CAMERA:SetTgt(SymCam("CAMERA_16"))
      -- SOUND:PlayBgm(SymSnd("BGM_EVE_END"), Volume(256))
      -- local taskLookAt01 = function()
      --   TASK:Sleep(TimeSec(0.5))
      --   CH("PARTNER"):ResetNeckRot(TimeSec(0.2))
      --   TASK:Sleep(TimeSec(0.3))
      --   CH("SAZANDORA_LARGE"):ResetNeckRot(TimeSec(0.2))
      --   CH("PARTNER"):WaitNeckRot()
      --   CH("PARTNER"):DirTo(SymPos("P01_EFF_LIGHT_HERO_LP"), Speed(200), ROT_TYPE.NEAR)
      --   CH("SAZANDORA_LARGE"):WaitNeckRot()
      --   CH("SAZANDORA_LARGE"):DirTo(SymPos("P01_EFF_LIGHT_HERO_LP"), Speed(200), ROT_TYPE.NEAR)
      --   CH("SAZANDORA_LARGE"):WaitRotate()
      -- end
      -- TASK:Regist(taskLookAt01)
      -- EFFECT:Create("effectLightHeroStart", SymEff("EV_LIGHT_HERO_START"))
      -- EFFECT:SetPosition("effectLightHeroStart", SymPos("P01_EFF_LIGHT_HERO_LP"))
      -- EFFECT:Create("effectLightHeroEnd", SymEff("EV_LIGHT_HERO_END"))
      -- EFFECT:SetPosition("effectLightHeroEnd", SymPos("P01_EFF_LIGHT_HERO_LP"))
      -- EFFECT:Play("effectLightHeroStart")
      -- SOUND:PlaySe(SymSnd("SE_EVT_HERO_LIGHT_APPEAR"), Volume(256))
      -- TASK:Sleep(TimeSec(2))
      -- CH("HERO"):ChangeColor(Color(1, 1, 1, 1), TimeSec(1, TIME_TYPE.FRAME))
      -- TASK:Sleep(TimeSec(30, TIME_TYPE.FRAME))
      -- EFFECT:Play("effectLightHeroEnd")
      -- EFFECT:ChangeColor("effectLightHeroEnd", Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
      -- TASK:Sleep(TimeSec(1, TIME_TYPE.FRAME))
      -- CH("HERO"):SetShadow(true)
      -- EFFECT:ChangeColor("effectLightHeroEnd", Color(1, 1, 1, 1), TimeSec(30, TIME_TYPE.FRAME))
      -- TASK:Sleep(TimeSec(29, TIME_TYPE.FRAME))
      -- EFFECT:Remove("effectLightHeroStart")
      -- TASK:Sleep(TimeSec(30, TIME_TYPE.FRAME))
      -- EFFECT:Remove("effectLightHeroEnd")
      -- CH("HERO"):DirTo(CH("PARTNER"), Speed(60), ROT_TYPE.NEAR)
      -- CH("HERO"):WaitRotate()
      -- TASK:Sleep(TimeSec(2))
      -- CAMERA:SetAzimuthDifferenceVolume(Volume(2))
      -- CAMERA:SetFovy(SymCam("CAMERA_17"))
      -- CAMERA:SetEye(SymCam("CAMERA_17"))
      -- CAMERA:SetTgt(SymCam("CAMERA_17"))
      -- TASK:Sleep(TimeSec(0.5))
      -- CH("PARTNER"):WalkTo(SymPos("P03_PLAYER"), Speed(1))
      -- TASK:Sleep(TimeSec(0.2))
      -- CH("SAZANDORA_LARGE"):DirTo(SymPos("P_LOOK_AT"), Speed(30), ROT_TYPE.NEAR, WITH_MOTION.OFF)
      -- CH("HERO"):WalkTo(SymPos("P01_HERO"), Speed(1.5))
      -- CH("PARTNER"):WaitMove()
      -- CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SHOUT)
      -- CH("PARTNER"):SetMotion(SymMot("EV018_CRY00"), LOOP.OFF, TimeSec(0.3))
      -- CH("PARTNER"):WaitPlayMotion()
      -- CH("PARTNER"):SetMotion(SymMot("EV018_CRY01"), LOOP.ON)
      -- TASK:Sleep(TimeSec(0.2))
      -- CH("HERO"):SetNeckRot(RotateTarget(0), RotateTarget(-20), RotateTarget(0), TimeSec(0.35))
      -- TASK:Sleep(TimeSec(1))
      SOUND:FadeOutBgm(TimeSec(1))
      SCREEN_A:FadeOut(TimeSec(1), true)
      TASK:Sleep(TimeSec(1))
      -- WINDOW:SwitchTalk({PARTNER_0 = 88448013, PARTNER_1 = 475966796})
      -- TASK:Sleep(TimeSec(4))
      -- WINDOW:ForceCloseMessage()
      -- WINDOW:SetWaitMode(TimeSec(4), TimeSec(1))
      -- WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), 1394555787)
      -- WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), 1241778890)
      -- WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), 1630099721)
      -- WINDOW:CloseMessage()
      -- WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
      -- TASK:Sleep(TimeSec(5))
      GROUND:SortPartyMember(false)
      SAVEPARTY()
      SYSTEM:UpdateNextDayParameter()
      FLAG.StoryPlayerMode = CONST.ST_MODE_NONE
      -- TASK:Sleep(TimeSec(0.2))
      -- if Ground_Save(ground) then
      --   return
      -- end
      subSaveflagS01_080_01()
      return __scopeFuncTbl.LABEL_NEXT
    end
    function __scopeFuncTbl.LABEL_END()
      SYSTEM:SetParadiseHomeLevel(PARADISE_HOME_LV.LV_2)
      SYSTEM:SetParadiseCenterLevel(PARADISE_CENTER_LV.LV_4)
      FLAG.StoryPlayerMode = CONST.ST_MODE_PARTNER
      FLAG.SCENARIOFLAG = CONST.S1_SEKAINOHESOYARARETA_END
      FLAG.MapFlags = CONST.EV_START_MAP
      FLAG.FreePlay = CONST.FLAG_FALSE
      FLAG.TrigNextEvent = CONST.FLAG_TRUE
      SYSTEM:UpdateNextDayParameter()
      SYSTEM:NextEntry()
    end
    function __scopeFuncTbl.LABEL_NEXT()
    end
    local __next = __scopeFuncTbl.LABEL_TOP
    while __next ~= nil do
      __next = __next()
    end
  end
  __LB_SCOPE()
end
function sub01_uchuuritsunooka01_end()
end
function subSaveflagS01_080_01()
  FLAG.StoryPlayerMode = CONST.ST_MODE_NONE
  FLAG.MapFlags = CONST.MAP_EVENT
  FLAG.FreePlay = CONST.FLAG_TRUE
  FLAG.TrigNextEvent = CONST.FLAG_FALSE
  FLAG.SceneFlag = CONST.FL_SC_01_FIRST
  FLAG.SCENARIOFLAG = CONST.S1_UCHUURITSUNOOKA_END
  SYSTEM:SetParadiseHomeLevel(PARADISE_HOME_LV.LV_2)
  SYSTEM:SetParadiseCenterLevel(PARADISE_CENTER_LV.LV_4)
  SYSTEM:NextSpecialEntry(SPECIAL_ENTRY.NEXT_DAY)
end
function groundEnd()
end

