dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main13_yoakenosangakuboss2nd01_init()
end
function main13_yoakenosangakuboss2nd01_start()
  subEveFromProgFadeSet()
  TASK:Sleep(TimeSec(1))
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HERO"):RunTo(SymPos("P01_HERO"), Speed(2.5))
  SOUND:PlayBgm(SymSnd("BGM_EVE_FEAR_01"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("HERO"):WaitMove()
  CH("HERO"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(subEveDoubleJump, {
    CH("DOKUROGGU")
  })
  WINDOW:DrawFace(272, 16, SymAct("DOKUROGGU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DOKUROGGU"), 1286321175)
  WINDOW:Talk(SymAct("DOKUROGGU"), 1437631830)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.DECIDE)
  WINDOW:Monologue(2124273301)
  WINDOW:Monologue(1736894420)
  subEveCloseMsg()
  CH("DOKUROGGU"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
  WINDOW:DrawFace(272, 16, SymAct("DOKUROGGU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DOKUROGGU"), 684159251)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(1.5))
  SOUND:PlaySe(SymSnd("SE_EVT_FLUSH"), Volume(256))
  subEveFlash()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.DECIDE)
  WINDOW:Monologue(836517970)
  subEveCloseMsg()
  CH("SHANDERA_1"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
  TASK:Sleep(TimeSec(0.1))
  CH("GIGAIASU_1"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
  WINDOW:DrawFace(272, 16, SymAct("DOKUROGGU"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("DOKUROGGU"), 452006801)
  WINDOW:CloseMessage()
  subEveFlash2()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.DECIDE)
  WINDOW:Monologue(65675984)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_BOSS_WIPE"), Volume(256))
  EFFECT:BossWipe(TimeSec(60, TIME_TYPE.FRAME), true)
  CAMERA:ResetAzimuthDifferenceVolume()
  FLAG.SceneFlag = CONST.FL_SC_01_FIRST
  FLAG.SCENARIOFLAG = CONST.M13_YOAKENOSANGAKUBOSS2ND_END
  SYSTEM:SetNextDungeonBanner(false)
  SYSTEM:EnterDungeon(Dg(14), DG_WAYPOINT.BOSS01)
end
function main13_yoakenosangakuboss2nd01_end()
end
function groundEnd()
end

