dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main17_burakkiitoeefi01_init()
end
function main17_burakkiitoeefi01_start()
  subEveFromProgFadeSet()
  TASK:Sleep(TimeSec(1))
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:MoveFollow(SymCam("CAMERA_01"), Speed(1.6, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("BURAKKII"):WalkTo(SymPos("P01_BURAKKII"), Speed(1.5))
  CH("EEFI"):WalkTo(SymPos("P01_EEFI"), Speed(1.5))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("BURAKKII"):WaitMove()
  CAMERA:WaitMove()
  CAMERA:SetAzimuthDifferenceVolume(Volume(6))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 88, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BURAKKII"), -1087368986)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("EEFI"):DirTo(CH("BURAKKII"), Speed(200), ROT_TYPE.NEAR)
  CH("EEFI"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("EEFI"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("EEFI"), -1507122777)
  WINDOW:CloseMessage()
  CH("BURAKKII"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  CH("BURAKKII"):WaitRotate()
  WINDOW:DrawFace(272, 16, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BURAKKII"), -1928957340)
  subEveCloseMsg()
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_DESPAIR_L1"), Volume(256))
  WINDOW:DrawFace(20, 88, SymAct("EEFI"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("EEFI"), -1810021595)
  WINDOW:Talk(SymAct("EEFI"), -614672926)
  WINDOW:Talk(SymAct("EEFI"), -1035475805)
  subEveCloseMsg()
  WINDOW:DrawFace(272, 16, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BURAKKII"), -378882208)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("EEFI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EEFI"), -260995551)
  WINDOW:Talk(SymAct("EEFI"), 2011798254)
  subEveCloseMsg()
  WINDOW:DrawFace(272, 16, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BURAKKII"), 1861397423)
  WINDOW:Talk(SymAct("BURAKKII"), 867219543)
  WINDOW:Talk(SymAct("BURAKKII"), 715884822)
  WINDOW:Talk(SymAct("BURAKKII"), 25615061)
  WINDOW:Talk(SymAct("BURAKKII"), 413002644)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.5))
  CH("EEFI"):WalkTo(SymPos("P02_EEFI"), Speed(1))
  CH("EEFI"):WaitMove()
  TASK:Sleep(TimeSec(0.2))
  CH("EEFI"):SetNeckRot(RotateTarget(0), RotateTarget(-20), RotateTarget(0), TimeSec(0.3))
  CH("EEFI"):WaitNeckRot()
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 88, SymAct("EEFI"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("EEFI"), 1474067795)
  WINDOW:Talk(SymAct("EEFI"), 1321683986)
  WINDOW:CloseMessage()
  CH("EEFI"):ResetNeckRot(TimeSec(0.3))
  CH("EEFI"):WaitNeckRot()
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 88, SymAct("EEFI"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("EEFI"), 1709842385)
  WINDOW:Talk(SymAct("EEFI"), 2096180880)
  subEveCloseMsg()
  TASK:Sleep(TimeSec(0.5))
  WINDOW:DrawFace(324, 88, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BURAKKII"), -76991905)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(2.5))
  SCREEN_A:FadeOutAll(TimeSec(1.5), true)
  SCREEN_A:FadeOut(TimeSec(0), false)
  SOUND:WaitBgm()
  CAMERA:ResetAzimuthDifferenceVolume()
  FLAG.SceneFlag = CONST.FL_SC_01_FIRST
  FLAG.SCENARIOFLAG = CONST.M17_BURAKKIITOEEFI_END
  SYSTEM:SetDungeonWaypointStat(Dg(20), DG_WAYPOINT.POINT01, DG_WAYPOINT_STAT.AFTER)
  SYSTEM:EnterDungeon(Dg(20), DG_WAYPOINT.POINT01)
end
function main17_burakkiitoeefi01_end()
end
function groundEnd()
end

