dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main09_aratananakama01_init()
end
function main09_aratananakama01_start()
  -- camera is a little wrong here for reason. can't get to the bottom of this, but it doesn't affect gameplay i guess
  CAMERA:SetAzimuthDifferenceVolume(Volume(3.5))
  CAMERA:SetEye(SymCam("CAMERA_09_5"))
  CAMERA:SetTgt(SymCam("CAMERA_09_5"))
  CH("HERO"):SetPosition(SymPos("P01_HERO"))
  CH("PARTNER"):SetPosition(SymPos("P01_PARTNER"))
  CH("PARTNER"):SetDir(CH("HERO"))
  CH("DOKKORAA_2"):SetPosition(SymPos("P00_DOKKORAA_2"))
  CH("DOKKORAA_2"):SetDir(CH("HERO"))
  CH("NOKOTCHI"):SetPosition(SymPos("P00_NOKOTCHI"))
  CH("NOKOTCHI"):SetDir(CH("HERO"))
  CH("NUOO"):SetPosition(SymPos("P01_NUOO"))
  CH("NUOO"):SetDir(CH("HERO"))
  CH("BIRIJION"):SetDir(CH("HERO"))
  CH("EEFI"):SetDir(CH("HERO"))
  CH("MINEZUMI"):SetPosition(SymPos("P00_MINEZUMI"))
  CH("MINEZUMI"):SetDir(CH("HERO"))
  CH("HERO"):SetPosition(SymPos("P02_HERO"))
  CH("EMONGA"):SetPosition(SymPos("P02_EMONGA"))
  CH("EMONGA"):SetDir(CH("HERO"))
  CH("HERO"):SetDir(CH("EMONGA"))
  CH("DOKKORAA_1"):SetPosition(SymPos("P00_DOKKORAA_1"))
  CH("DOKKORAA_1"):SetDir(SymPos("P02_HERO"))
  CH("BURAKKII"):SetDir(CH("EMONGA"))
  CH("ZURUGGU"):SetPosition(SymPos("P00_ZURUGGU"))
  CH("ZURUGGU"):SetDir(CH("BURAKKII"))
  CH("DOTEKKOTSU"):SetPosition(SymPos("P01_DOTEKKOTSU"))
  CH("DOTEKKOTSU"):SetDir(CH("BURAKKII"))
  CH("WASHIBON"):SetPosition(SymPos("P00_WASHIBON"))
  CH("WASHIBON"):SetDir(CH("BURAKKII"))
  CHARA:SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- CH("DOKKORAA_1"):SetVisible(false)
  -- CH("DOKKORAA_2"):SetVisible(false)
  -- CH("MINEZUMI"):SetVisible(false)
  -- CH("NOKOTCHI"):SetVisible(false)
  -- CH("EMONGA"):SetVisible(false)
  -- CH("ZURUGGU"):SetVisible(false)
  -- CH("DOTEKKOTSU"):SetVisible(false)
  -- CH("NUOO"):SetVisible(false)
  -- CH("WASHIBON"):SetVisible(false)
  -- CHARA:SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  -- CH("HERO"):WalkTo(SymPos("P00_HERO"), Speed(1.5))
  -- CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(1.5))
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- CH("HERO"):WaitMove()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  -- CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  -- WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  -- WINDOW:SwitchTalk({PARTNER_0 = 1211007311, PARTNER_1 = 1362472974})
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_01"))
  -- CAMERA:SetTgt(SymCam("CAMERA_01"))
  -- SOUND:PlayBgm(SymSnd("BGM_EVE_CALM_01"), Volume(256))
  -- TASK:Sleep(TimeSec(0.3))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  -- CH("BIRIJION"):SetManpu("MP_NOTICE_R")
  -- CH("BIRIJION"):WaitManpu()
  -- CH("BIRIJION"):DirTo(SymPos("P01_PARTNER"), Speed(200), ROT_TYPE.NEAR)
  -- CH("BIRIJION"):WaitRotate()
  -- CH("BURAKKII"):DirTo(SymPos("P01_PARTNER"), Speed(200), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("EEFI"):DirTo(SymPos("P01_PARTNER"), Speed(200), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.3))
  -- CH("PARTNER"):SetPosition(SymPos("P00_5_PARTNER"))
  -- CH("HERO"):SetPosition(SymPos("P00_5_HERO"))
  -- TASK:Regist(subEveMoveDir, {
  --   CH("PARTNER"),
  --   SymPos("P01_PARTNER"),
  --   Speed(1.5),
  --   CH("BURAKKII")
  -- })
  -- TASK:Regist(subEveMoveDir, {
  --   CH("HERO"),
  --   SymPos("P01_HERO"),
  --   Speed(1.5),
  --   CH("BURAKKII")
  -- })
  -- TASK:WaitTask()
  -- WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  -- WINDOW:SwitchTalk({PARTNER_0 = 2048451533, PARTNER_1 = 1661194892})
  -- subEveCloseMsg()
  -- CH("PARTNER"):DirTo(CH("BIRIJION"), Speed(200), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("HERO"):DirTo(CH("BIRIJION"), Speed(200), ROT_TYPE.NEAR)
  -- WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.THINK)
  -- WINDOW:Talk(SymAct("BIRIJION"), 742540363)
  -- subEveCloseMsg()
  -- CH("PARTNER"):DirTo(CH("BURAKKII"), Speed(200), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("HERO"):DirTo(CH("BURAKKII"), Speed(200), ROT_TYPE.NEAR)
  -- WINDOW:DrawFace(72, 16, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("BURAKKII"), 895055114)
  -- subEveCloseMsg()
  -- CH("BIRIJION"):DirTo(CH("EEFI"), Speed(200), ROT_TYPE.NEAR)
  -- CH("EEFI"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  -- WINDOW:DrawFaceF(226, 8, SymAct("EEFI"), FACE_TYPE.HAPPY)
  -- WINDOW:Talk(SymAct("EEFI"), 510928585)
  -- WINDOW:Talk(SymAct("EEFI"), 124721032)
  -- subEveCloseMsg()
  -- CH("EEFI"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  -- CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  -- TASK:Regist(subEveJump, {
  --   CH("PARTNER")
  -- })
  -- WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  -- WINDOW:SwitchTalk({PARTNER_0 = -2131293369, PARTNER_1 = -1712571898})
  -- WINDOW:KeyWait()
  -- CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  -- WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  -- WINDOW:SwitchTalk({PARTNER_0 = -880940229, PARTNER_1 = -765011334})
  -- WINDOW:SwitchTalk({PARTNER_0 = -112490055, PARTNER_1 = -531580680})
  -- WINDOW:SwitchTalk({PARTNER_0 = -1357828545, PARTNER_1 = -1240850562})
  -- subEveCloseMsg()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  -- CH("BURAKKII"):SetManpu("MP_NOTICE_R")
  -- CH("EEFI"):SetManpu("MP_NOTICE_R")
  -- WINDOW:DrawFace(72, 16, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("BURAKKII"), -1658368835)
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  -- WINDOW:SwitchTalk({PARTNER_0 = -2076410372, PARTNER_1 = 61104435})
  -- WINDOW:CloseMessage()
  -- CH("BURAKKII"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("EEFI"):DirTo(CH("BURAKKII"), Speed(350), ROT_TYPE.NEAR)
  -- CH("EEFI"):WaitRotate()
  -- TASK:Sleep(TimeSec(0.7))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  -- CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  -- CH("PARTNER"):WaitManpu()
  -- WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  -- WINDOW:SwitchTalk({PARTNER_0 = 448745586, PARTNER_1 = -641186603})
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  -- CAMERA:SetEye(SymCam("CAMERA_03"))
  -- CAMERA:SetTgt(SymCam("CAMERA_03"))
  -- CH("BURAKKII"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("EEFI"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  -- CH("EEFI"):WaitRotate()
  -- WINDOW:DrawFace(20, 20, SymAct("BURAKKII"), FACE_TYPE.SPECIAL01)
  -- WINDOW:Talk(SymAct("BURAKKII"), -1059883628)
  -- WINDOW:Talk(SymAct("BURAKKII"), -335665577)
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.THINK)
  -- WINDOW:SwitchTalk({PARTNER_0 = -219867370, PARTNER_1 = -1113292335})
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(272, 16, SymAct("EEFI"), FACE_TYPE.THINK)
  -- WINDOW:Talk(SymAct("EEFI"), -1530941296)
  -- WINDOW:Talk(SymAct("EEFI"), -1886198957)
  -- subEveCloseMsg()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  -- CH("PARTNER"):SetManpu("MP_QUESTION")
  -- CH("PARTNER"):WaitManpu()
  -- WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.THINK)
  -- WINDOW:SwitchTalk({PARTNER_0 = -1769352686, PARTNER_1 = 286379741})
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(20, 20, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("BURAKKII"), 134938524)
  -- WINDOW:Talk(SymAct("BURAKKII"), 1635001264)
  -- WINDOW:Talk(SymAct("BURAKKII"), 2020545265)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_01"))
  -- CAMERA:SetTgt(SymCam("CAMERA_01"))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  -- CH("HERO"):SetManpu("MP_EXCLAMATION")
  -- CH("BIRIJION"):SetManpu("MP_NOTICE_R")
  -- CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  -- CH("PARTNER"):WaitManpu()
  -- WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  -- WINDOW:SwitchTalk({PARTNER_0 = 1396850994, PARTNER_1 = 1247375475})
  -- subEveCloseMsg()
  -- WINDOW:DrawFaceF(226, 8, SymAct("EEFI"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("EEFI"), 85518004)
  -- WINDOW:Talk(SymAct("EEFI"), 470013941)
  -- WINDOW:Talk(SymAct("EEFI"), 925795382)
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(72, 16, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("BURAKKII"), 775271799)
  -- WINDOW:Talk(SymAct("BURAKKII"), -1448236616)
  -- WINDOW:Talk(SymAct("BURAKKII"), -1330210567)
  -- WINDOW:Talk(SymAct("BURAKKII"), -56419575)
  -- subEveCloseMsg()
  -- SOUND:FadeOutBgm(TimeSec(0.5))
  -- CAMERA:MoveFollow2(SymCam("CAMERA_10"), Speed(20, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  -- EFFECT:Create("effectExclamation01", SymEff("MP_EXCLAMATION"))
  -- EFFECT:SetPosition("effectExclamation01", SymPos("EFF_EX_01"))
  -- EFFECT:Play("effectExclamation01")
  -- EFFECT:Create("effectExclamation02", SymEff("MP_EXCLAMATION"))
  -- EFFECT:SetPosition("effectExclamation02", SymPos("EFF_EX_02"))
  -- EFFECT:Play("effectExclamation02")
  -- EFFECT:Create("effectExclamation03", SymEff("MP_EXCLAMATION"))
  -- EFFECT:SetPosition("effectExclamation03", SymPos("EFF_EX_03"))
  -- EFFECT:Play("effectExclamation03")
  -- EFFECT:Create("effectExclamation04", SymEff("MP_EXCLAMATION"))
  -- EFFECT:SetPosition("effectExclamation04", SymPos("EFF_EX_04"))
  -- EFFECT:Play("effectExclamation04")
  -- WINDOW:Talk(SymWord(-181286456), -440915384)
  -- CAMERA:WaitMove()
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(3.5))
  -- CH("EMONGA"):SetVisible(true)
  -- CAMERA:SetEye(SymCam("CAMERA_05"))
  -- CAMERA:SetTgt(SymCam("CAMERA_05"))
  -- CH("EMONGA"):WalkTo(SymPos("P00_EMONGA"), Speed(2))
  -- CH("EMONGA"):WaitMove()
  -- SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  -- TASK:Regist(subEveDoubleJump, {
  --   CH("EMONGA")
  -- })
  -- CH("PARTNER"):DirTo(CH("EMONGA"), Speed(500), ROT_TYPE.NEAR)
  -- CH("HERO"):DirTo(CH("EMONGA"), Speed(500), ROT_TYPE.NEAR)
  -- CH("EEFI"):DirTo(CH("EMONGA"), Speed(500), ROT_TYPE.NEAR)
  -- WINDOW:Talk(SymAct("EMONGA"), -829064821)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  -- CAMERA:SetEye(SymCam("CAMERA_06"))
  -- CAMERA:SetTgt(SymCam("CAMERA_06"))
  -- TASK:Sleep(TimeSec(0.3))
  -- EFFECT:Create("effectSmoke", SymEff("EV_SMOKE_BROWN"))
  -- EFFECT:SetPosition("effectSmoke", SymPos("P_EFF_SMOKE"))
  -- EFFECT:Play("effectSmoke")
  -- SOUND:PlaySe(SymSnd("SE_EVT_NOKOTCHI_RISE"), Volume(256))
  -- CH("NOKOTCHI"):SetVisible(true)
  -- CH("NOKOTCHI"):SetMotion(SymMot("EV009_APPEAR"), LOOP.OFF, TimeSec(0))
  -- TASK:Sleep(TimeSec(0.2))
  -- CH("BIRIJION"):DirTo(CH("NOKOTCHI"), Speed(500), ROT_TYPE.NEAR)
  -- CH("BURAKKII"):DirTo(CH("NOKOTCHI"), Speed(500), ROT_TYPE.NEAR)
  -- CH("NOKOTCHI"):WaitPlayMotion()
  -- CH("NOKOTCHI"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  -- WINDOW:Talk(SymAct("NOKOTCHI"), -678541110)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  -- CH("DOTEKKOTSU"):SetVisible(true)
  -- CAMERA:SetEye(SymCam("CAMERA_07"))
  -- CAMERA:SetTgt(SymCam("CAMERA_07"))
  -- local taskSe01 = function()
  --   SOUND:PlaySe(SymSnd("SE_EVT_PUSH_GRASS"), Volume(256))
  --   TASK:Sleep(TimeSec(0.2))
  --   SOUND:PlaySe(SymSnd("SE_EVT_PUSH_GRASS"), Volume(256))
  -- end
  -- TASK:Regist(taskSe01)
  -- CH("DOTEKKOTSU"):MoveHeightTo(Height(0), Speed(2.5))
  -- CH("DOTEKKOTSU"):SetMotion(SymMot("EV009_APPEAR"), LOOP.OFF)
  -- CH("DOTEKKOTSU"):WaitPlayMotion()
  -- CH("DOTEKKOTSU"):WaitMoveHeight()
  -- CH("DOTEKKOTSU"):RunTo(SymPos("P00_DOTEKKOTSU"), Speed(2.5))
  -- CH("DOTEKKOTSU"):WaitMove()
  -- SOUND:PlaySe(SymSnd("SE_EVT_DOTEKKOTSU"), Volume(256))
  -- WINDOW:Talk(SymAct("DOTEKKOTSU"), -1731207667)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  -- CAMERA:SetEye(SymCam("CAMERA_08"))
  -- CAMERA:SetTgt(SymCam("CAMERA_08"))
  -- TASK:Sleep(TimeSec(0.3))
  -- CH("NUOO"):SetVisible(true)
  -- CH("NUOO"):MoveHeightTo(Height(-0.42), Speed(2))
  -- TASK:Sleep(TimeSec(0.1))
  -- SOUND:PlaySe(SymSnd("SE_EVT_NUOO_RISE"), Volume(256))
  -- EFFECT:Create("effectWater", SymEff("EV_WATER_SPRAY"))
  -- EFFECT:SetPosition("effectWater", SymPos("P_EFF_WATER_SPRAY"))
  -- EFFECT:Play("effectWater")
  -- WINDOW:Talk(SymAct("NUOO"), -2116751540)
  -- CH("NUOO"):WaitMoveHeight()
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_10"))
  -- CAMERA:SetTgt(SymCam("CAMERA_10"))
  -- SOUND:PlayBgm(SymSnd("BGM_EVE_COMICAL"), Volume(256))
  -- CH("DOKKORAA_1"):SetVisible(true)
  -- CH("DOKKORAA_2"):SetVisible(true)
  -- CH("WASHIBON"):SetVisible(true)
  -- CH("MINEZUMI"):SetVisible(true)
  -- CH("ZURUGGU"):SetVisible(true)
  -- CH("EMONGA"):SetPosition(SymPos("P00_05_EMONGA"))
  -- CH("EMONGA"):SetDir(CH("BIRIJION"))
  -- CH("NUOO"):MoveHeightTo(Height(0), Speed(10))
  -- CH("NUOO"):SetPosition(SymPos("P00_NUOO"))
  -- TASK:Regist(subEveMoveDir, {
  --   CH("DOTEKKOTSU"),
  --   SymPos("P01_DOTEKKOTSU"),
  --   Speed(1.5),
  --   CH("BURAKKII")
  -- })
  -- TASK:Regist(subEveMoveDir, {
  --   CH("DOKKORAA_1"),
  --   SymPos("P00_DOKKORAA_1"),
  --   Speed(1.5),
  --   CH("BURAKKII")
  -- })
  -- TASK:Regist(subEveMoveDir, {
  --   CH("WASHIBON"),
  --   SymPos("P00_WASHIBON"),
  --   Speed(1.5),
  --   CH("BURAKKII")
  -- })
  -- TASK:Regist(subEveMoveDir, {
  --   CH("DOKKORAA_2"),
  --   SymPos("P00_DOKKORAA_2"),
  --   Speed(1.5),
  --   CH("BURAKKII")
  -- })
  -- TASK:Regist(subEveMoveDir, {
  --   CH("MINEZUMI"),
  --   SymPos("P00_MINEZUMI"),
  --   Speed(1.5),
  --   CH("BURAKKII")
  -- })
  -- TASK:Regist(subEveMoveDir, {
  --   CH("ZURUGGU"),
  --   SymPos("P00_ZURUGGU"),
  --   Speed(1.5),
  --   CH("BURAKKII")
  -- })
  -- TASK:Regist(subEveMoveDir, {
  --   CH("NUOO"),
  --   SymPos("P01_NUOO"),
  --   Speed(1.5),
  --   CH("BURAKKII")
  -- })
  -- CH("PARTNER"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.NEAR)
  -- CH("PARTNER"):WaitRotate()
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("PARTNER"):DirTo(RotateTarget(90), Speed(350), ROT_TYPE.RIGHT)
  -- CH("PARTNER"):WaitRotate()
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("PARTNER"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.RIGHT)
  -- CH("PARTNER"):WaitRotate()
  -- WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.THINK)
  -- WINDOW:SwitchTalk({PARTNER_0 = -1426473841, PARTNER_1 = -1276998194})
  -- WINDOW:SwitchTalk({PARTNER_0 = 880447745, PARTNER_1 = 761372736})
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_01"))
  -- CAMERA:SetTgt(SymCam("CAMERA_01"))
  -- TASK:Sleep(TimeSec(0.2))
  -- CH("BURAKKII"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  -- CH("BIRIJION"):DirTo(CH("BURAKKII"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("EEFI"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  -- CH("PARTNER"):DirTo(CH("BURAKKII"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("HERO"):DirTo(CH("BURAKKII"), Speed(350), ROT_TYPE.NEAR)
  -- CH("BURAKKII"):WaitRotate()
  -- WINDOW:DrawFace(72, 16, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("BURAKKII"), 1142914156)
  -- subEveCloseMsg()
  -- WINDOW:DrawFaceF(226, 8, SymAct("EEFI"), FACE_TYPE.THINK)
  -- WINDOW:Talk(SymAct("EEFI"), 1560562989)
  -- WINDOW:Talk(SymAct("EEFI"), 1982406382)
  -- WINDOW:DrawFaceF(226, 8, SymAct("EEFI"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("EEFI"), 1865559983)
  -- WINDOW:Talk(SymAct("EEFI"), 544455016)
  -- WINDOW:DrawFaceF(226, 8, SymAct("EEFI"), FACE_TYPE.THINK)
  -- WINDOW:Talk(SymAct("EEFI"), 963151913)
  -- subEveCloseMsg()
  -- CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  -- TASK:Regist(subEveDoubleJump, {
  --   CH("PARTNER")
  -- })
  -- WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  -- WINDOW:SwitchTalk({PARTNER_0 = 306568170, PARTNER_1 = 190769835})
  -- WINDOW:CloseMessage()
  -- CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  -- CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  -- WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  -- WINDOW:SwitchTalk({PARTNER_0 = -1933117852, PARTNER_1 = -1780627675})
  -- WINDOW:CloseMessage()
  -- TASK:Sleep(TimeSec(0.3))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(8))
  -- CAMERA:SetEye(SymCam("CAMERA_10"))
  -- CAMERA:SetTgt(SymCam("CAMERA_10"))
  -- local taskZuruggu00 = function()
  --   function TaskL.Loop()
  --     CH("EMONGA"):SetManpu("MP_SPREE_LP")
  --     TASK:Sleep(TimeSec(0.7))
  --     TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
  --     CH("EMONGA"):ResetManpu()
  --     TASK:Sleep(TimeSec(0.2))
  --     TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
  --     CH("ZURUGGU"):SetManpu("MP_LAUGH_LP")
  --     TASK:Sleep(TimeSec(0.3))
  --     TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
  --     TASK:Sleep(TimeSec(0.4))
  --     TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
  --     CH("ZURUGGU"):ResetManpu()
  --     TASK:Sleep(TimeSec(0.3))
  --     TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
  --   end
  --   function TaskL.Finish()
  --     CH("EMONGA"):ResetManpu()
  --     CH("ZURUGGU"):ResetManpu()
  --     return
  --   end
  -- end
  -- local taskMinezumi00 = function()
  --   function TaskL.Loop()
  --     CH("MINEZUMI"):SetManpu("MP_SPREE_LP")
  --     TASK:Sleep(TimeSec(0.5))
  --     TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
  --     CH("MINEZUMI"):ResetManpu()
  --     TASK:Sleep(TimeSec(0.3))
  --     TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
  --   end
  --   function TaskL.Finish()
  --     CH("MINEZUMI"):ResetManpu()
  --     return
  --   end
  -- end
  -- local taskDokkoraa00 = function()
  --   function TaskL.Loop()
  --     CH("DOKKORAA_2"):SetManpu("MP_LAUGH_LP")
  --     TASK:Sleep(TimeSec(0.3))
  --     TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
  --     CH("DOKKORAA_2"):ResetManpu()
  --     TASK:Sleep(TimeSec(0.3))
  --     TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
  --   end
  --   function TaskL.Finish()
  --     CH("DOKKORAA_2"):ResetManpu()
  --     return
  --   end
  -- end
  -- local taskWashibon00 = function()
  --   function TaskL.Loop()
  --     TASK:Sleep(TimeSec(0.3))
  --     TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
  --     CH("WASHIBON"):SetManpu("MP_SPREE_LP")
  --     TASK:Sleep(TimeSec(0.25))
  --     TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
  --     TASK:Sleep(TimeSec(0.25))
  --     TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
  --     CH("WASHIBON"):ResetManpu()
  --     TASK:Sleep(TimeSec(0.25))
  --     TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
  --   end
  --   function TaskL.Finish()
  --     CH("WASHIBON"):ResetManpu()
  --     return
  --   end
  -- end
  -- local taskDotekkotsu00 = function()
  --   function TaskL.Loop()
  --     TASK:Sleep(TimeSec(0.25))
  --     TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
  --     TASK:Sleep(TimeSec(0.25))
  --     TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
  --     CH("DOTEKKOTSU"):SetManpu("MP_SPREE_LP")
  --     TASK:Sleep(TimeSec(0.25))
  --     TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
  --     TASK:Sleep(TimeSec(0.25))
  --     TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
  --     CH("DOTEKKOTSU"):ResetManpu()
  --   end
  --   function TaskL.Finish()
  --     CH("DOTEKKOTSU"):ResetManpu()
  --     return
  --   end
  -- end
  -- TASK:Regist(Group("grpZuruggu"), taskZuruggu00)
  -- TASK:Regist(Group("grpDokkoraa"), taskDokkoraa00)
  -- TASK:Regist(Group("grpMinezumi"), taskMinezumi00)
  -- TASK:Regist(Group("grpWashibon"), taskWashibon00)
  -- TASK:Regist(Group("grpDotekkotsu"), taskDotekkotsu00)
  -- WINDOW:DrawFace(20, 88, SymAct("WASHIBON"), FACE_TYPE.EMOTION)
  -- WINDOW:Talk(SymAct("WASHIBON"), 1454035842)
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(272, 88, SymAct("MINEZUMI"), FACE_TYPE.EMOTION)
  -- WINDOW:Talk(SymAct("MINEZUMI"), 1337057987)
  -- subEveCloseMsg()
  -- CH("ZURUGGU"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  -- WINDOW:DrawFace(20, 88, SymAct("ZURUGGU"), FACE_TYPE.GLADNESS)
  -- WINDOW:Talk(SymAct("ZURUGGU"), 1687990528)
  -- subEveCloseMsg()
  -- CH("ZURUGGU"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  -- WINDOW:DrawFace(20, 20, SymAct("DOTEKKOTSU"), FACE_TYPE.EMOTION)
  -- WINDOW:DrawFaceOffset(10, 0)
  -- WINDOW:Talk(SymAct("DOTEKKOTSU"), 2106032193)
  -- TASK:ExitNotifyTasks(Group("grpDokkoraa"))
  -- WINDOW:Talk(SymAct("DOTEKKOTSU"), 851842694)
  -- WINDOW:Talk(SymAct("DOTEKKOTSU"), 735913927)
  -- WINDOW:CloseMessage()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  -- CH("DOKKORAA_1"):SetManpu("MP_FLY_SWEAT")
  -- CH("DOKKORAA_1"):WaitManpu()
  -- WINDOW:DrawFace(324, 88, SymAct("DOKKORAA_1"), FACE_TYPE.SAD)
  -- WINDOW:Talk(SymAct("DOKKORAA_1"), 15758340)
  -- WINDOW:KeyWait()
  -- SOUND:FadeOutBgm(TimeSec(2.5))
  -- WINDOW:Talk(SymAct("DOKKORAA_1"), 434849093)
  -- TASK:ExitNotifyTasks(Group("grpZuruggu"))
  -- TASK:ExitNotifyTasks(Group("grpMinezumi"))
  -- TASK:ExitNotifyTasks(Group("grpWashibon"))
  -- TASK:ExitNotifyTasks(Group("grpDotekkotsu"))
  -- WINDOW:CloseMessage()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  -- CH("DOTEKKOTSU"):SetManpu("MP_EXCLAMATION")
  -- CH("DOTEKKOTSU"):WaitManpu()
  -- WINDOW:DrawFace(20, 20, SymAct("DOTEKKOTSU"), FACE_TYPE.NORMAL)
  -- WINDOW:DrawFaceOffset(10, 0)
  -- WINDOW:Talk(SymAct("DOTEKKOTSU"), -1636607606)
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(324, 88, SymAct("DOKKORAA_2"), FACE_TYPE.THINK)
  -- WINDOW:Talk(SymAct("DOKKORAA_2"), -2023200565)
  -- WINDOW:CloseMessage()
  -- CH("EMONGA"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  -- CH("DOKKORAA_2"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  -- CH("NOKOTCHI"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  -- CH("NUOO"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  -- CH("DOKKORAA_1"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  -- CH("BIRIJION"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  -- CH("BURAKKII"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  -- CH("EEFI"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  -- CH("MINEZUMI"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.75))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_09"))
  -- CAMERA:SetTgt(SymCam("CAMERA_09"))
  -- subEveMoveDir(CH("NOKOTCHI"), SymPos("P00_NOKOTCHI"), Speed(1.5), CH("HERO"))
  -- CH("HERO"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:WaitTask()
  -- CH("PARTNER"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  -- WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.HAPPY)
  -- WINDOW:Talk(SymAct("NOKOTCHI"), -300501785)
  -- WINDOW:CloseMessage()
  -- CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  -- CH("PARTNER"):WaitRotate()
  -- TASK:Sleep(TimeSec(0.8))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(3.5))
  -- CAMERA:SetEye(SymCam("CAMERA_09_4"))
  -- CAMERA:SetTgt(SymCam("CAMERA_09_4"))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  -- CH("EMONGA"):SetManpu("MP_EXCLAMATION")
  -- CH("EMONGA"):WaitManpu()
  -- WINDOW:DrawFace(118, 8, SymAct("EMONGA"), FACE_TYPE.SURPRISE)
  -- WINDOW:Talk(SymAct("EMONGA"), -150108762)
  -- CH("HERO"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  -- WINDOW:Talk(SymAct("EMONGA"), -601827739)
  -- WINDOW:CloseMessage()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  -- CH("EMONGA"):SetManpu("MP_FLY_SWEAT")
  -- CH("EMONGA"):WaitManpu()
  -- CH("EMONGA"):DirTo(CH("BURAKKII"), Speed(350), ROT_TYPE.NEAR)
  -- CH("EMONGA"):WaitRotate()
  -- CH("PARTNER"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  -- CH("EEFI"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("BURAKKII"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  -- CH("EMONGA"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  -- WINDOW:DrawFace(272, 16, SymAct("EMONGA"), FACE_TYPE.SPECIAL03)
  -- WINDOW:Talk(SymAct("EMONGA"), -985929948)
  -- WINDOW:Talk(SymAct("EMONGA"), -1971686941)
  -- WINDOW:Talk(SymAct("EMONGA"), -1822343006)
  -- WINDOW:Talk(SymAct("EMONGA"), -1202973855)
  -- WINDOW:CloseMessage()
  -- CH("EMONGA"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  -- CAMERA:MoveFollow2(SymCam("CAMERA_09_5"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- CH("HERO"):DirLockToChara(CH("EMONGA"))
  -- CH("PARTNER"):DirLockToChara(CH("EMONGA"))
  -- CH("BURAKKII"):DirLockToChara(CH("EMONGA"))
  -- CH("EEFI"):DirTo(CH("HERO"), Speed(200), ROT_TYPE.NEAR)
  -- local taskNaisho = function()
  --   subEveMoveDir(CH("EMONGA"), SymPos("P01_EMONGA"), Speed(2), CH("HERO"))
  --   CH("HERO"):DirLockOff()
  --   TASK:Sleep(TimeSec(0.2))
  --   CH("DOKKORAA_1"):DirTo(SymPos("P02_HERO"), Speed(200), ROT_TYPE.NEAR)
  --   CH("EMONGA"):WalkTo(SymPos("P02_EMONGA"), Speed(1.5))
  --   CH("HERO"):WalkTo(SymPos("P02_HERO"), Speed(1.5), LINK_DIR.OFF)
  --   CH("HERO"):WaitMove()
  -- end
  -- TASK:Regist(taskNaisho)
  -- TASK:WaitTask()
  -- CH("PARTNER"):DirLockOff()
  -- CH("BURAKKII"):DirLockOff()
  -- CAMERA:WaitMove()
  -- WINDOW:DrawFace(20, 88, SymAct("EMONGA"), FACE_TYPE.SPECIAL02)
  -- WINDOW:Talk(SymAct("EMONGA"), -1588125152)
  -- WINDOW:Talk(SymAct("EMONGA"), 651116271)
  -- WINDOW:Talk(SymAct("EMONGA"), 1070862254)
  -- WINDOW:Talk(SymAct("EMONGA"), -1233804111)
  -- TASK:Regist(subEveJump, {
  --   CH("EMONGA")
  -- })
  -- WINDOW:Talk(SymAct("EMONGA"), -1351707152)
  -- WINDOW:CloseMessage()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  -- CH("HERO"):SetManpu("MP_FLY_SWEAT")
  -- CH("HERO"):WaitManpu()
  -- CH("PARTNER"):DirTo(CH("HERO"), Speed(200), ROT_TYPE.NEAR)
  -- WINDOW:DrawFace(272, 16, SymAct("HERO"), FACE_TYPE.CATCHBREATH)
  -- WINDOW:Monologue(-2075933133)
  -- WINDOW:Monologue(-1655113870)
  -- WINDOW:Monologue(-770088523)
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  -- WINDOW:SwitchTalk({PARTNER_0 = -889040652, PARTNER_1 = -533789897})
  -- WINDOW:SwitchTalk({PARTNER_0 = -114019722, PARTNER_1 = 2125213369})
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(272, 16, SymAct("HERO"), FACE_TYPE.THINK)
  -- WINDOW:Monologue(1740054520)
  -- WINDOW:CloseMessage()
  do
    local __LB_SCOPE = function()
      local __scopeFuncTbl = {}
      function __scopeFuncTbl.__LB_FIRST()
      end
      function __scopeFuncTbl.CELECT_EVENT01()
        WINDOW:SysMsg(248103892)
        local __labelCnt = 0
        local __labelTbl = {}
        WINDOW:SelectStart()
        WINDOW:SelectChain(399700629, __labelCnt)
        __labelTbl[__labelCnt] = __scopeFuncTbl.LABEL_YES
        __labelCnt = __labelCnt + 1
        WINDOW:SelectChain(1023385942, __labelCnt)
        __labelTbl[__labelCnt] = __scopeFuncTbl.LABEL_NO
        __labelCnt = __labelCnt + 1
        local __res = WINDOW:SelectEnd(MENU_SELECT_MODE.DISABLE_CANCEL)
        return __labelTbl[__res]
      end
      function __scopeFuncTbl.LABEL_YES()
        return __scopeFuncTbl.LABEL_END
      end
      function __scopeFuncTbl.LABEL_NO()
        WINDOW:DrawFace(272, 16, SymAct("HERO"), FACE_TYPE.THINK)
        WINDOW:Monologue(635736087)
        WINDOW:Monologue(1789200080)
        WINDOW:Monologue(1941845905)
        WINDOW:CloseMessage()
        CH("HERO"):DirTo(CH("DOKKORAA_2"), Speed(200), ROT_TYPE.NEAR)
        CH("HERO"):WaitRotate()
        TASK:Sleep(TimeSec(0.5))
        CH("HERO"):DirTo(CH("EEFI"), Speed(200), ROT_TYPE.NEAR)
        CH("HERO"):WaitRotate()
        TASK:Sleep(TimeSec(0.5))
        CH("HERO"):DirTo(CH("EMONGA"), Speed(200), ROT_TYPE.NEAR)
        CH("HERO"):WaitRotate()
        TASK:Sleep(TimeSec(0.5))
        SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
        CH("HERO"):SetManpu("MP_FLY_SWEAT")
        CH("HERO"):WaitManpu()
        WINDOW:DrawFace(272, 16, SymAct("HERO"), FACE_TYPE.THINK)
        WINDOW:Monologue(1486054482)
        WINDOW:Monologue(1099453715)
        WINDOW:Monologue(-972011044)
        WINDOW:CloseMessage()
        TASK:Sleep(TimeSec(0.2))
        WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
        WINDOW:SwitchTalk({PARTNER_0 = -552896355, PARTNER_1 = -1779090503})
        WINDOW:SwitchTalk({PARTNER_0 = -1930556680, PARTNER_1 = -1480369861})
        WINDOW:CloseMessage()
        return __scopeFuncTbl.LABEL_END
      end
      function __scopeFuncTbl.LABEL_END()
      end
      local __next = __scopeFuncTbl.CELECT_EVENT01
      while __next ~= nil do
        __next = __next()
      end
    end
    __LB_SCOPE()
  end
  -- CH("HERO"):DirTo(CH("PARTNER"), Speed(200), ROT_TYPE.NEAR)
  -- CH("HERO"):WaitRotate()
  -- CH("HERO"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  -- TASK:Regist(subEveNod, {
  --   CH("HERO")
  -- })
  -- WINDOW:DrawFace(272, 16, SymAct("HERO"), FACE_TYPE.HAPPY)
  -- WINDOW:Monologue(-1093113734)
  -- subEveCloseMsg()
  -- CH("HERO"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  -- SOUND:PlayBgm(SymSnd("BGM_EVE_HAPPY"), Volume(256))
  -- CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  -- TASK:Regist(subEveDoubleJump, {
  --   CH("PARTNER")
  -- })
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  -- WINDOW:SwitchTalk({PARTNER_0 = -241566019, PARTNER_1 = -394080260})
  -- WINDOW:SwitchTalk({PARTNER_0 = -1011901377, PARTNER_1 = -625693314})
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_01"))
  -- CAMERA:SetTgt(SymCam("CAMERA_01"))
  -- CH("ZURUGGU"):SetPosition(SymPos("P01_ZURUGGU"))
  -- CH("ZURUGGU"):SetDir(CH("PARTNER"))
  -- CH("PARTNER"):DirTo(CH("BURAKKII"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("HERO"):DirTo(CH("BURAKKII"), Speed(350), ROT_TYPE.NEAR)
  -- CH("NOKOTCHI"):DirTo(CH("BURAKKII"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("EEFI"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  -- CH("EMONGA"):DirTo(CH("BURAKKII"), Speed(350), ROT_TYPE.NEAR)
  -- CH("DOKKORAA_1"):DirTo(CH("BURAKKII"), Speed(350), ROT_TYPE.NEAR)
  -- CH("DOKKORAA_2"):DirTo(CH("BURAKKII"), Speed(350), ROT_TYPE.NEAR)
  -- CH("NUOO"):DirTo(CH("BURAKKII"), Speed(350), ROT_TYPE.NEAR)
  -- CH("MINEZUMI"):DirTo(CH("BURAKKII"), Speed(350), ROT_TYPE.NEAR)
  -- CH("PARTNER"):WaitRotate()
  -- WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  -- WINDOW:SwitchTalk({PARTNER_0 = 1563210161, PARTNER_1 = 1144488176})
  -- WINDOW:SwitchTalk({PARTNER_0 = 759782620, PARTNER_1 = 877817245})
  -- WINDOW:CloseMessage()
  -- CAMERA:MoveFollow2(SymCam("CAMERA_10"), Speed(15, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- TASK:Regist(Group("grpDokkoraa"), taskDokkoraa00)
  -- TASK:Regist(Group("grpMinezumi"), taskMinezumi00)
  -- TASK:Regist(Group("grpWashibon"), taskWashibon00)
  -- TASK:Regist(Group("grpDotekkotsu"), taskDotekkotsu00)
  -- TASK:Regist(Group("grpZuruggu"), taskZuruggu00)
  -- CAMERA:WaitMove()
  -- TASK:Regist(subEveDoubleJump, {
  --   CH("NOKOTCHI")
  -- })
  -- WINDOW:DrawFace(72, 16, SymAct("NOKOTCHI"), FACE_TYPE.EMOTION)
  -- WINDOW:Talk(SymAct("NOKOTCHI"), 528432734)
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.HAPPY)
  -- WINDOW:Talk(SymAct("BIRIJION"), 107220767)
  -- WINDOW:Talk(SymAct("BIRIJION"), 1227200984)
  -- subEveCloseMsg()
  -- CH("EMONGA"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  -- WINDOW:DrawFace(324, 88, SymAct("EMONGA"), FACE_TYPE.HAPPY)
  -- WINDOW:Talk(SymAct("EMONGA"), 1346283673)
  -- WINDOW:Talk(SymAct("EMONGA"), 2064907098)
  -- WINDOW:CloseMessage()
  -- CH("EMONGA"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  -- CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  -- CAMERA:SetEye(SymCam("CAMERA_11"))
  -- CAMERA:SetTgt(SymCam("CAMERA_11"))
  -- TASK:Sleep(TimeSec(0.3))
  -- CH("EMONGA"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  -- WINDOW:DrawFace(72, 16, SymAct("EEFI"), FACE_TYPE.EMOTION)
  -- WINDOW:Talk(SymAct("EEFI"), 1644743195)
  -- subEveCloseMsg()
  -- CH("EMONGA"):DirTo(CH("BURAKKII"), Speed(350), ROT_TYPE.NEAR)
  -- WINDOW:DrawFace(20, 88, SymAct("BURAKKII"), FACE_TYPE.EMOTION)
  -- WINDOW:Talk(SymAct("BURAKKII"), -443492652)
  -- WINDOW:DrawFace(20, 88, SymAct("BURAKKII"), FACE_TYPE.THINK)
  -- WINDOW:Talk(SymAct("BURAKKII"), -57940075)
  -- TASK:ExitNotifyTasks(Group("grpDokkoraa"))
  -- TASK:ExitNotifyTasks(Group("grpMinezumi"))
  -- TASK:ExitNotifyTasks(Group("grpWashibon"))
  -- TASK:ExitNotifyTasks(Group("grpDotekkotsu"))
  -- TASK:ExitNotifyTasks(Group("grpZuruggu"))
  -- WINDOW:Talk(SymAct("BURAKKII"), 1073541938)
  -- WINDOW:Talk(SymAct("BURAKKII"), 652722803)
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  -- WINDOW:SwitchTalk({PARTNER_0 = 231379376, PARTNER_1 = 349282545})
  -- WINDOW:SwitchTalk({PARTNER_0 = 1536177718, PARTNER_1 = 1116407671})
  -- WINDOW:SwitchTalk({PARTNER_0 = 1772508340, PARTNER_1 = 1891460597})
  -- WINDOW:SwitchTalk({PARTNER_0 = -148539078, PARTNER_1 = -297908101})
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(20, 88, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("BURAKKII"), -2025810857)
  -- subEveCloseMsg()
  -- CH("EMONGA"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  -- CH("PARTNER"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  -- WINDOW:DrawFace(72, 16, SymAct("EEFI"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("EEFI"), -1638161130)
  -- WINDOW:Talk(SymAct("EEFI"), -1250494763)
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(324, 20, SymAct("NUOO"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("NUOO"), -1402091628)
  -- WINDOW:Talk(SymAct("NUOO"), -483634861)
  -- subEveCloseMsg()
  -- TASK:Regist(subEveDoubleJump, {
  --   CH("ZURUGGU")
  -- })
  -- WINDOW:DrawFace(20, 20, SymAct("ZURUGGU"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("ZURUGGU"), -97034222)
  -- subEveCloseMsg()
  -- CH("EEFI"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  -- TASK:Regist(subEveNod, {
  --   CH("EEFI")
  -- })
  -- WINDOW:DrawFace(72, 16, SymAct("EEFI"), FACE_TYPE.HAPPY)
  -- WINDOW:Talk(SymAct("EEFI"), -786811951)
  -- WINDOW:CloseMessage()
  -- CH("EEFI"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_01"))
  -- CAMERA:SetTgt(SymCam("CAMERA_01"))
  -- CH("EMONGA"):SetDir(CH("PARTNER"))
  -- TASK:Sleep(TimeSec(0.3))
  -- TASK:Regist(subEveJump, {
  --   CH("PARTNER")
  -- })
  -- WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  -- WINDOW:SwitchTalk({PARTNER_0 = -939457904, PARTNER_1 = 1335434847})
  -- WINDOW:CloseMessage()
  -- CH("BIRIJION"):DirTo(CH("PARTNER"), Speed(200), ROT_TYPE.NEAR)
  -- CH("WASHIBON"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("NUOO"):DirTo(CH("PARTNER"), Speed(200), ROT_TYPE.NEAR)
  -- CH("NOKOTCHI"):DirTo(CH("PARTNER"), Speed(200), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("DOKKORAA_1"):DirTo(CH("PARTNER"), Speed(200), ROT_TYPE.NEAR)
  -- CH("HERO"):DirTo(CH("PARTNER"), Speed(200), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("EEFI"):DirTo(CH("PARTNER"), Speed(200), ROT_TYPE.NEAR)
  -- CH("ZURUGGU"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("MINEZUMI"):DirTo(CH("PARTNER"), Speed(200), ROT_TYPE.NEAR)
  -- CH("DOKKORAA_2"):DirTo(CH("PARTNER"), Speed(200), ROT_TYPE.NEAR)
  -- CH("BURAKKII"):DirTo(CH("PARTNER"), Speed(200), ROT_TYPE.NEAR)
  -- CH("BURAKKII"):WaitRotate()
  -- WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  -- WINDOW:SwitchTalk({PARTNER_0 = 1451372318, PARTNER_1 = 446147822})
  -- WINDOW:SwitchTalk({PARTNER_0 = 59547055, PARTNER_1 = 681692780})
  -- WINDOW:SwitchTalk({PARTNER_0 = 834338605, PARTNER_1 = 2130405866})
  -- WINDOW:KeyWait()
  -- CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  -- TASK:Regist(subEveJump, {
  --   CH("PARTNER")
  -- })
  -- WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  -- WINDOW:SwitchTalk({PARTNER_0 = 1742756011, PARTNER_1 = 1288506216})
  -- WINDOW:CloseMessage()
  -- CH("HERO"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  -- CH("PARTNER"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  -- CH("DOTEKKOTSU"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  -- CH("DOKKORAA_2"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  -- CH("DOKKORAA_1"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  -- CH("EMONGA"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  -- CH("BIRIJION"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  -- CH("NOKOTCHI"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  -- CH("MINEZUMI"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  -- CH("ZURUGGU"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  -- CH("DOTEKKOTSU"):SetManpu("MP_SPREE_LP")
  -- CH("HERO"):SetManpu("MP_SPREE_LP")
  -- CH("WASHIBON"):SetManpu("MP_SPREE_LP")
  -- CH("NUOO"):SetManpu("MP_SPREE_LP")
  -- CH("EMONGA"):SetManpu("MP_SPREE_LP")
  -- CAMERA:MoveFollow2(SymCam("CAMERA_12"), Speed(20, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- WINDOW:Talk(SymAct(""), 1440102953)
  -- WINDOW:CloseMessage()
  -- CAMERA:WaitMove()
  -- SOUND:FadeOutBgm(TimeSec(2.5))
  -- SCREEN_A:FadeOut(TimeSec(1), true)
  -- SOUND:WaitBgm()
  -- TASK:Sleep(TimeSec(0.5))
  -- CAMERA:ResetAzimuthDifferenceVolume()
  SOUND:FadeOutBgm(TimeSec(0.5))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  SOUND:WaitBgm()
  CAMERA:ResetAzimuthDifferenceVolume()
  FLAG.SceneFlag = CONST.FL_SC_01_FIRST
  FLAG.SCENARIOFLAG = CONST.M09_ARATANANAKAMA_END
  FLAG.MapFlags = CONST.MAP_EVENT
  FLAG.FreePlay = CONST.FLAG_TRUE
  FLAG.TrigNextEvent = CONST.FLAG_FALSE
  SYSTEM:NextEntry()
end
function main09_aratananakama01_end()
end
function groundEnd()
end

