function main02_kouzannodoukutsuretry01_start()
  subEveFromProgFadeSetDunBf()
  CH("HERO"):SetPosition(SymPos("D_HERO_P"))
  CH("PARTNER"):SetPosition(SymPos("D_PARTNER_P"))
  CH("HERO"):SetMotionRaito(Raito(1))
  CH("HERO"):SetMotionRaito(Raito(1))
  CH("PARTNER"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("PARTNER"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CAMERA:SetAzimuthDifferenceVolume(Volume(3.5))
  CAMERA:SetEye(SymCam("CAMERA_INTO_DUNGEON"))
  CAMERA:SetTgt(SymCam("CAMERA_INTO_DUNGEON"))
  CH("PARTNER"):SetDir(CH("HERO"))
  CH("HERO"):SetDir(CH("PARTNER"))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1112027816, PARTNER_1 = -1532167143})
  WINDOW:SwitchTalk({PARTNER_0 = -1887326246, PARTNER_1 = -1768251749})
  WINDOW:SwitchTalk({PARTNER_0 = -639956900, PARTNER_1 = -1061144291})
  WINDOW:CloseMessage()
  subEveNod(CH("HERO"))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -336762146, PARTNER_1 = -218735713})
  WINDOW:SwitchTalk({PARTNER_0 = 1970161488, PARTNER_1 = 1819637265})
  WINDOW:CloseMessage()
  subUseDunEnterBeforEvent()
  FLAG.DungeonHitMode = CONST.FLAG_NONE
  CAMERA:ResetAzimuthDifferenceVolume()
  FLAG.SceneFlag = CONST.FL_SC_01_FIRST
  SYSTEM:EnterDungeon(Dg(2))
end

