dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main03_arehatedaniboss2nd01_init()
end
function main03_arehatedaniboss2nd01_start()
  subEveFromProgFadeSet()
  TASK:Sleep(TimeSec(1))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = 1027752085, PARTNER_1 = 609841620})
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("DOTEKKOTSU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), 259269143)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("NOKOTCHI"), 376378198)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("KOMATANA_1"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("DENCHURA_2"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("FUSHIDE_1"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("KOMATANA_2"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("DENCHURA_1"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("FUSHIDE_2"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("PARTNER"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("HERO"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("NOKOTCHI"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("EMONGA"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("DOTEKKOTSU"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("DOKKORAA_1"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("DOKKORAA_2"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("BIRIJION"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CAMERA:MoveFollow2(SymCam("CAMERA_00_05"), Speed(3, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SOUND:PlayBgm(SymSnd("BGM_EVE_FEAR_01"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), false)
  CAMERA:WaitMove()
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFaceF(118, 8, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = 1496221073, PARTNER_1 = 1077261520})
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("DOTEKKOTSU"), FACE_TYPE.SPECIAL04)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), 1796794131)
  subEveCloseMsg()
  WINDOW:DrawFace(226, 8, SymAct("EMONGA"), FACE_TYPE.SPECIAL01)
  WINDOW:Talk(SymAct("EMONGA"), 1912854098)
  subEveCloseMsg()
  WINDOW:DrawFaceF(118, 8, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = -174339427, PARTNER_1 = -327091236})
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  CH("KOMATANA_2"):SetManpu("MP_ANGRY_LP")
  WINDOW:DrawFace(272, 16, SymAct("KOMATANA_2"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("KOMATANA_2"), 1556693476)
  CH("KOMATANA_2"):ResetManpu()
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(1.5))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  SOUND:PlaySe(SymSnd("SE_EVT_DOSU"), Volume(256))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  WINDOW:Talk(SymAct("KOMATANA_2"), 1171419301)
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  WINDOW:CloseMessage()
  CAMERA:SetFovy(SymCam("CAMERA_00_05"))
  CAMERA:SetEye(SymCam("CAMERA_00_05"))
  CAMERA:SetTgt(SymCam("CAMERA_00_05"))
  CAMERA:MoveFollow2(SymCam("CAMERA_02_5"), Speed(10, ACCEL_TYPE.HIGH, DECEL_TYPE.LOW))
  WINDOW:Talk(SymWord(-955798710), 1862214502)
  TASK:Sleep(TimeSec(0.5))
  WINDOW:ForceCloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_BOSS_WIPE"), Volume(256))
  EFFECT:BossWipe(TimeSec(60, TIME_TYPE.FRAME), true)
  CAMERA:ResetAzimuthDifferenceVolume()
  FLAG.Boss1stMeet = CONST.FLAG_TRUE
  FLAG.SceneFlag = CONST.FL_SC_01_FIRST
  FLAG.SCENARIOFLAG = CONST.M03_AREHATEDANIBOSS2ND_END
  SYSTEM:SetNextDungeonBanner(false)
  SYSTEM:EnterDungeon(Dg(5), DG_WAYPOINT.BOSS00)
end
function main03_arehatedaniboss2nd01_end()
end
function groundEnd()
end

