dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main13_yoakenosangakubosswin01_init()
  if FLAG.NowResumeFlag == CONST.FLAG_TRUE then
    subEveFromProgFadeSet()
    subSaveflagM13_130_01()
  end
end
function main13_yoakenosangakubosswin01_start()
  -- CH("DORYUUZU_1"):SetVisible(false)
  -- CH("DORYUUZU_2"):SetVisible(false)
  -- CH("SAZANDORA_H"):SetVisible(false)
  -- CH("BOOMANDA_H"):SetVisible(false)
  -- local ShanderDir = CH("SHANDERA_ZERO_1"):GetDir()
  -- local GigaiasuDir = CH("GIGAIASU_1"):GetDir()
  -- local DogurogguDir = CH("DOKUROGGU"):GetDir()
  -- local BoomandaDir = CH("BOOMANDA_H"):GetDir()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2.5))
  -- CAMERA:SetFovy(SymCam("CAMERA_00"))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- CH("HERO"):SetMotion(SymMot("EV013_TIRED"), LOOP.ON, TimeSec(0))
  -- CH("DOKUROGGU"):SetMotion(SymMot("EV013_FALL"), LOOP.ON, TimeSec(0))
  -- CH("SHANDERA_ZERO_1"):SetMotion(SymMot("EV013_FALL"), LOOP.ON, TimeSec(0))
  -- CH("GIGAIASU_1"):SetMotion(SymMot("EV013_FALL"), LOOP.ON, TimeSec(0))
  subEveFromProgFadeSet()
  -- CAMERA:SetFovy(SymCam("CAMERA_01"))
  -- CAMERA:MoveFollow(SymCam("CAMERA_01"), Speed(0.25, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- SOUND:FadeInEnv(SymSnd("SE_ENV_CLIFF_LP"), TimeSec(0.5), Volume(256))
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- WINDOW:Talk(SymAct("DOKUROGGU"), 1779850275)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  -- CAMERA:SetFovy(SymCam("CAMERA_02"))
  -- CAMERA:SetEye(SymCam("CAMERA_02"))
  -- CAMERA:SetTgt(SymCam("CAMERA_02"))
  -- WINDOW:Monologue(1930259810)
  -- WINDOW:Monologue(1478508193)
  -- subEveCloseMsg()
  -- CH("HERO"):DirTo(RotateTarget(180), Speed(200), ROT_TYPE.NEAR)
  -- WINDOW:Monologue(1094389728)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1.5))
  -- CAMERA:SetFovy(SymCam("CAMERA_03"))
  -- CAMERA:SetEye(SymCam("CAMERA_03"))
  -- CAMERA:SetTgt(SymCam("CAMERA_03"))
  -- CH("HERO"):WaitRotate()
  -- CAMERA:MoveFollow2(SymCam("CAMERA_04"), Speed(0.2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- CH("HERO"):WalkTo(SymPos("P00_HERO"), Speed(0.3))
  -- WINDOW:Monologue(242915623)
  -- WINDOW:Monologue(392276070)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetFovy(SymCam("CAMERA_05"))
  -- CAMERA:SetEye(SymCam("CAMERA_05"))
  -- CAMERA:SetTgt(SymCam("CAMERA_05"))
  -- WINDOW:Talk(SymAct("DOKUROGGU"), 1011678117)
  -- WINDOW:CloseMessage()
  -- CH("DOKUROGGU"):SetNeckRot(RotateTarget(-80), RotateTarget(0), RotateTarget(0), TimeSec(0.2))
  -- CH("DOKUROGGU"):WaitNeckRot()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  -- CH("DOKUROGGU"):SetManpu("MP_FLY_SWEAT")
  -- WINDOW:Talk(SymAct("DOKUROGGU"), 626510564)
  -- WINDOW:Talk(SymAct("DOKUROGGU"), -1563437525)
  -- WINDOW:Talk(SymAct("DOKUROGGU"), -1143675030)
  -- WINDOW:CloseMessage()
  -- SOUND:FadeOutEnv(TimeSec(1))
  -- CAMERA:MoveFollow(SymCam("CAMERA_06"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- SCREEN_A:FadeOut(TimeSec(0.5), true)
  -- CH("DORYUUZU_1"):SetVisible(true)
  -- CH("DORYUUZU_2"):SetVisible(true)
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CUT:Load(SymCut("CUT_M13_130_01"))
  -- SOUND:PlayBgm(SymSnd("BGM_EVE_FEAR_01"), Volume(256))
  -- CUT:Play()
  -- CUT:Wait()
  -- CUT:Destroy()
  -- CAMERA:SetDefaultGroundFovy()
  -- CAMERA:ResetAzimuthDifferenceVolume()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  -- CAMERA:SetFovy(SymCam("CAMERA_10"))
  -- CAMERA:SetEye(SymCam("CAMERA_10"))
  -- CAMERA:SetTgt(SymCam("CAMERA_10"))
  -- TASK:Regist(subEveRunDir, {
  --   CH("DORYUUZU_1"),
  --   SymPos("P00_DORYUUZU_1"),
  --   Speed(3),
  --   CH("HERO")
  -- })
  -- TASK:Regist(subEveRunDir, {
  --   CH("DORYUUZU_2"),
  --   SymPos("P00_DORYUUZU_2"),
  --   Speed(3),
  --   CH("HERO")
  -- })
  -- CH("DORYUUZU_1"):SetHeight(Height(0))
  -- CH("DORYUUZU_2"):SetHeight(Height(0))
  -- SCREEN_A:FadeIn(TimeSec(0.3), true)
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  -- CH("HERO"):SetManpu("MP_EXCLAMATION")
  -- CH("HERO"):WaitManpu()
  -- CH("HERO"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  -- CH("HERO"):WaitRotate()
  -- WINDOW:Monologue(-94944319)
  -- WINDOW:CloseMessage()
  -- CH("DOKUROGGU"):ResetNeckRot(TimeSec(0.1))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetFovy(SymCam("CAMERA_11"))
  -- CAMERA:SetEye(SymCam("CAMERA_11"))
  -- CAMERA:SetTgt(SymCam("CAMERA_11"))
  -- CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  -- SOUND:PlaySe(SymSnd("SE_EVT_BOMANDA_GROWL"), Volume(128))
  -- WINDOW:SysMsg(-481529216)
  -- CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  -- TASK:Sleep(TimeSec(1))
  -- WINDOW:ForceCloseMessage()
  -- CH("DOKUROGGU"):SetNeckRot(RotateTarget(0), RotateTarget(40), RotateTarget(0), TimeSec(0.2))
  -- TASK:Sleep(TimeSec(0.2))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  -- CH("DORYUUZU_2"):SetManpu("MP_EXCLAMATION")
  -- CH("HERO"):SetManpu("MP_SHOCK_L")
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("GIGAIASU_1"):SetNeckRot(RotateTarget(0), RotateTarget(40), RotateTarget(0), TimeSec(0.2))
  -- TASK:Sleep(TimeSec(0.2))
  -- CH("SHANDERA_ZERO_1"):SetManpu("MP_EXCLAMATION")
  -- TASK:Sleep(TimeSec(0.2))
  -- CH("DORYUUZU_1"):SetManpu("MP_EXCLAMATION")
  -- CH("HERO"):SetNeckRot(RotateTarget(0), RotateTarget(40), RotateTarget(0), TimeSec(0.2))
  -- WINDOW:Monologue(-933158589)
  -- WINDOW:CloseMessage()
  -- CAMERA:MoveFollow(SymCam("CAMERA_11_5"), Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- SCREEN_A:FadeOut(TimeSec(0.5), true)
  -- TASK:Sleep(TimeSec(0.8))
  -- CH("DOKUROGGU"):ResetNeckRot(TimeSec(0.1))
  -- CH("GIGAIASU_1"):ResetNeckRot(TimeSec(0.1))
  -- CH("HERO"):ResetNeckRot(TimeSec(0.1))
  -- CH("BOOMANDA_H"):SetVisible(true)
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CUT:Load(SymCut("CUT_M13_130_02"))
  -- CUT:Play()
  -- CUT:Wait()
  -- CUT:Destroy()
  -- CAMERA:SetDefaultGroundFovy()
  -- CAMERA:ResetAzimuthDifferenceVolume()
  -- TASK:Sleep(TimeSec(1))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1.5))
  -- CAMERA:SetFovy(SymCam("CAMERA_20"))
  -- CAMERA:SetEye(SymCam("CAMERA_20"))
  -- CAMERA:SetTgt(SymCam("CAMERA_20"))
  -- CH("DORYUUZU_1"):SetMotion(SymMot("WAIT00"), LOOP.ON, TimeSec(0))
  -- CH("DORYUUZU_2"):SetMotion(SymMot("WAIT00"), LOOP.ON, TimeSec(0))
  -- CH("DOKUROGGU"):SetMotion(SymMot("EV013_FALL"), LOOP.ON, TimeSec(0))
  -- CH("SHANDERA_ZERO_1"):SetMotion(SymMot("EV013_FALL"), LOOP.ON, TimeSec(0))
  -- CH("GIGAIASU_1"):SetMotion(SymMot("EV013_FALL"), LOOP.ON, TimeSec(0))
  -- CH("BOOMANDA_H"):SetMotion(SymMot("EV013_ROARING01_END"), LOOP.OFF, TimeSec(0))
  -- CH("BOOMANDA_H"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0))
  -- CH("BOOMANDA_H"):ResetFacialMotion()
  -- CH("HERO"):SetDir(RotateTarget(0))
  -- CH("HERO"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  -- CH("HERO"):SetMotion(SymMot("EV013_TIRED"), LOOP.ON, TimeSec(0))
  -- CH("DOKUROGGU"):SetNeckRot(RotateTarget(-80), RotateTarget(0), RotateTarget(0), TimeSec(0))
  -- CH("BOOMANDA_H"):MoveHeightTo(Height(0), Speed(999))
  -- SCREEN_A:FadeIn(TimeSec(0.5), false)
  -- SCREEN_A:FadeInAll(TimeSec(0.5), true)
  -- WINDOW:Talk(SymAct("DOKUROGGU"), -780529662)
  -- WINDOW:Talk(SymAct("DOKUROGGU"), -1640266043)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetFovy(SymCam("CAMERA_21"))
  -- CAMERA:SetEye(SymCam("CAMERA_21"))
  -- CAMERA:SetTgt(SymCam("CAMERA_21"))
  -- CH("BOOMANDA_H"):SetMotionRaito(Raito(2))
  -- CH("BOOMANDA_H"):SetMotion(SymMot("EV013_ROARING02"), LOOP.OFF, TimeSec(0))
  -- CH("BOOMANDA_H"):WaitPlayMotion()
  -- SOUND:PlaySe(SymSnd("SE_EVT_BOOMANDA_ROAR"), Volume(256))
  -- CH("BOOMANDA_H"):SetMotionRaito(Raito(1))
  -- EFFECT:StartMotionBlur(0, 0, 0)
  -- EFFECT:ChangeMotionBlurLevel(0.04, TimeSec(0.05))
  -- EFFECT:ChangeMotionBlurAlpha(0.9, TimeSec(0.05))
  -- CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  -- WINDOW:SysMsg(-2027899004)
  -- TASK:Sleep(TimeSec(2))
  -- WINDOW:ForceCloseMessage()
  -- CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  -- EFFECT:EndMotionBlur()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetFovy(SymCam("CAMERA_22"))
  -- CAMERA:SetEye(SymCam("CAMERA_22"))
  -- CAMERA:SetTgt(SymCam("CAMERA_22"))
  -- CH("BOOMANDA_H"):SetMotion(SymMot("EV013_ROARING03"), LOOP.OFF, TimeSec(0))
  -- CH("BOOMANDA_H"):SetMotion(SymMot("EV013_ROARING03_END"), LOOP.OFF, TimeSec(0))
  -- CH("BOOMANDA_H"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0))
  -- CAMERA:MoveFollow(SymCam("CAMERA_23"), Speed(0.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- TASK:Sleep(TimeSec(0.2))
  -- WINDOW:Monologue(-1408375737)
  -- WINDOW:Monologue(-1256794874)
  -- WINDOW:Monologue(848218569)
  -- WINDOW:CloseMessage()
  -- CH("DORYUUZU_1"):SetPosition(SymPos("P01_DORYUUZU_1"))
  -- CH("DORYUUZU_2"):SetPosition(SymPos("P01_DORYUUZU_2"))
  -- CH("BOOMANDA_H"):SetMouthMotion(MOUTH_MOTION.ANGRY)
  -- SOUND:FadeOutBgm(TimeSec(2))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetFovy(SymCam("CAMERA_24"))
  -- CAMERA:SetEye(SymCam("CAMERA_24"))
  -- CAMERA:SetTgt(SymCam("CAMERA_24"))
  -- TASK:Sleep(TimeSec(0.3))
  -- CH("DOKUROGGU"):SetNeckRot(RotateTarget(0), RotateTarget(60), RotateTarget(0), TimeSec(0.5))
  -- WINDOW:Talk(SymAct("DOKUROGGU"), 731248776)
  -- WINDOW:CloseMessage()
  -- SOUND:PlaySe(SymSnd("SE_EVT_DORYUUZU_KAMAE"), Volume(256))
  -- CH("DORYUUZU_1"):SetMotion(SymMot("EV013_ATTACK01"), LOOP.OFF)
  -- CH("DORYUUZU_2"):SetMotion(SymMot("EV013_ATTACK01"), LOOP.OFF)
  -- WINDOW:Talk(SymAct("DORYUUZU_1"), -387781585)
  -- WINDOW:CloseMessage()
  -- CH("DORYUUZU_1"):RunTo(SymPos("P02_DORYUUZU_1"), Speed(2.5))
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("DORYUUZU_2"):RunTo(SymPos("P02_DORYUUZU_2"), Speed(2.5))
  -- TASK:Sleep(TimeSec(0.9))
  -- CH("DOKUROGGU"):SetVisible(false)
  -- CH("SHANDERA_ZERO_1"):SetVisible(false)
  -- CH("BOOMANDA_H"):SetVisible(false)
  -- CH("GIGAIASU_1"):SetVisible(false)
  -- CUT:Load(SymCut("CUT_M13_130_03_01"))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(0.5))
  -- SOUND:PlayBgm(SymSnd("BGM_EVE_TENSION_01"), Volume(256))
  -- CUT:Play()
  -- CUT:Wait2()
  -- CH("DOKUROGGU"):SetVisible(true)
  -- CH("GIGAIASU_1"):SetVisible(true)
  -- CH("DORYUUZU_1"):SetVisible(false)
  -- CH("DORYUUZU_2"):SetVisible(false)
  -- CH("BOOMANDA_H"):SetVisible(true)
  -- TASK:Sleep(TimeSec(0.1))
  -- CUT:Load(SymCut("CUT_M13_130_03_02"))
  -- CUT:Play()
  -- CUT:Wait()
  -- CUT:Destroy()
  -- CAMERA:SetDefaultGroundFovy()
  -- CAMERA:ResetAzimuthDifferenceVolume()
  -- CH("HERO"):SetFacialMotion(FACIAL_MOTION.PAIN)
  -- CH("HERO"):SetMotion(SymMot("EV013_AVOID04"), LOOP.OFF, TimeSec(0))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1.5))
  -- CAMERA:SetFovy(SymCam("CAMERA_30"))
  -- CAMERA:SetEye(SymCam("CAMERA_30"))
  -- CAMERA:SetTgt(SymCam("CAMERA_30"))
  -- CH("HERO"):SetMotion(SymMot("EV011_KNEEATTACHE01"), LOOP.ON, TimeSec(0.4))
  -- CH("HERO"):SetMotionRaito(Raito(1.6))
  -- CH("HERO"):SetNeckRot(RotateTarget(0), RotateTarget(15), RotateTarget(0), TimeSec(0.2))
  -- SCREEN_A:FadeIn(TimeSec(0.3), true)
  -- WINDOW:Monologue(-235283090)
  -- WINDOW:Monologue(-623604051)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CUT:Load(SymCut("CUT_M13_130_03_03"))
  -- CH("HERO"):SetMotionRaito(Raito(1))
  -- CUT:Play()
  -- CUT:Wait()
  -- CUT:Destroy()
  -- CAMERA:SetDefaultGroundFovy()
  -- CAMERA:ResetAzimuthDifferenceVolume()
  -- CH("HERO"):SetFacialMotion(EYE_MOTION.CLOSE)
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetFovy(SymCam("CAMERA_31"))
  -- CAMERA:SetEye(SymCam("CAMERA_31"))
  -- CAMERA:SetTgt(SymCam("CAMERA_31"))
  -- CH("HERO"):SetMotion(SymMot("EV011_KNEEATTACHE01"), LOOP.ON)
  -- CH("HERO"):SetMotionRaito(Raito(1.6))
  -- CH("HERO"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
  -- SCREEN_A:WhiteIn(TimeSec(0.1), true)
  -- WINDOW:Monologue(-1009795092)
  -- TASK:Sleep(TimeSec(0.5))
  -- WINDOW:ForceCloseMessage()
  -- SCREEN_A:WhiteOut(TimeSec(0.1), true)
  -- SOUND:FadeOutEnv(TimeSec(0.5))
  -- SOUND:FadeOutBgm(TimeSec(0.5))
  -- WINDOW:Talk(SymAct("???"), -1936840405)
  -- WINDOW:CloseMessage()
  -- CH("HERO"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  -- SCREEN_A:WhiteIn(TimeSec(0.1), true)
  -- WINDOW:Monologue(-1785390998)
  -- WINDOW:CloseMessage()
  -- SCREEN_A:FadeOut(TimeSec(0.3), true)
  -- CH("SHANDERA_ZERO_1"):SetVisible(true)
  -- TASK:Sleep(TimeSec(0.8))
  -- CH("HERO"):ResetNeckRot(TimeSec(0.1))
  -- CHARA:SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  -- CH("DORYUUZU_1"):SetMotion(SymMot("WAIT00"), LOOP.ON)
  -- CH("DORYUUZU_2"):SetMotion(SymMot("WAIT00"), LOOP.ON)
  -- CH("DORYUUZU_1"):SetVisible(true)
  -- CH("DORYUUZU_2"):SetVisible(true)
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- SOUND:PlayBgm(SymSnd("BGM_EVE_SAZANDORA_01"), Volume(256))
  -- CUT:Load(SymCut("CUT_M13_130_04"))
  -- CUT:Play()
  -- CUT:Wait()
  -- CUT:Destroy()
  -- CAMERA:SetDefaultGroundFovy()
  -- CAMERA:ResetAzimuthDifferenceVolume()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CH("SAZANDORA_H"):SetVisible(true)
  -- CH("SAZANDORA_H"):SetMotion(SymMot("WAIT00"), LOOP.ON)
  -- CH("BOOMANDA_H"):SetDir(RotateTarget(180))
  -- CH("BOOMANDA_H"):SetMotion(SymMot("EV013_ROARING01_END"), LOOP.OFF, TimeSec(0))
  -- CH("BOOMANDA_H"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0))
  -- CH("BOOMANDA_H"):ResetFacialMotion()
  -- CH("SAZANDORA_H"):SetMotion(SymMot("EV013_ROARING01_END"), LOOP.OFF, TimeSec(0))
  -- CH("SAZANDORA_H"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0))
  -- CAMERA:SetFovy(SymCam("CAMERA_41"))
  -- CAMERA:SetEye(SymCam("CAMERA_41"))
  -- CAMERA:SetTgt(SymCam("CAMERA_41"))
  -- CH("HERO"):SetFacialMotion(FACIAL_MOTION.PAIN)
  -- CH("HERO"):SetMotion(SymMot("EV011_KNEEATTACHE03"), LOOP.OFF)
  -- CH("HERO"):SetNextMotion(SymMot("EV000_CSWAIT"), LOOP.ON, TimeSec(0.3))
  -- CH("HERO"):SetMotionRaito(Raito(0.8))
  -- TASK:Sleep(TimeSec(0.8))
  -- CAMERA:MoveFollow2(SymCam("CAMERA_42"), Speed(0.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- SCREEN_A:WhiteIn(TimeSec(0.3), true)
  -- WINDOW:Monologue(-1095218263)
  -- subEveCloseMsg()
  -- WINDOW:Talk(SymAct("SAZANDORA"), -1482458392)
  -- WINDOW:CloseMessage()
  -- CH("HERO"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  -- WINDOW:Monologue(540763687)
  -- WINDOW:CloseMessage()
  -- SCREEN_A:FadeOut(TimeSec(0.3), true)
  -- TASK:Sleep(TimeSec(0.8))
  -- CH("BOOMANDA_H"):SetMotion(SymMot("WAIT00"), LOOP.ON, TimeSec(0))
  -- CH("HERO"):SetMotionRaito(Raito(1))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CUT:Load(SymCut("CUT_M13_130_06"))
  -- CUT:Play()
  -- CUT:Wait()
  -- CUT:Destroy()
  -- CAMERA:SetDefaultGroundFovy()
  -- CAMERA:ResetAzimuthDifferenceVolume()
  -- SOUND:WaitBgm()
  -- TASK:Sleep(TimeSec(0.5))
  -- TASK:Sleep(TimeSec(0.2))
  -- if Ground_Save(ground) then
  --   return
  -- end
  subSaveflagM13_130_01()
end
function main13_yoakenosangakubosswin01_end()
end
function subSaveflagM13_130_01()
  FLAG.SceneFlag = CONST.FL_SC_01_FIRST
  FLAG.SCENARIOFLAG = CONST.M13_YOAKENOSANGAKUBOSSWIN_END
  SYSTEM:NextEntry()
end
function main13_yoakenosangakubosswin02_talk_01()
  -- WINDOW:Monologue(958420838)
  -- TASK:Sleep(TimeSec(0.5))
  -- WINDOW:ForceCloseMessage()
end
function main13_yoakenosangakubosswin03_talk_01()
  -- WINDOW:SetWaitMode(TimeSec(0.6), TimeSec(0.1))
  -- WINDOW:Monologue(1348373322)
  -- WINDOW:Monologue(1229306379)
  -- TASK:Sleep(TimeSec(0.8))
  -- WINDOW:ForceCloseMessage()
  -- WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main13_yoakenosangakubosswin03_script_01()
  -- SOUND:PlayEnv(SymSnd("SE_EVT_BOOMANDA_CHARGE_LP"), Volume(256))
end
function main13_yoakenosangakubosswin04_talk_01()
  -- WINDOW:SysMsg(1651042760)
  -- TASK:Sleep(TimeSec(1))
  -- WINDOW:ForceCloseMessage()
end
function main13_yoakenosangakubosswin06_talk_01()
  -- WINDOW:Monologue(2071189641)
  -- TASK:Sleep(TimeSec(0.9))
  -- WINDOW:ForceCloseMessage()
end
function main13_yoakenosangakubosswin06_talk_02()
  -- WINDOW:Talk(SymAct("DOKUROGGU"), 875712078)
  -- TASK:Sleep(TimeSec(1))
  -- WINDOW:ForceCloseMessage()
end
function main13_yoakenosangakubosswin01_end()
end
function groundEnd()
end

