function ev_tontonyama_boto()
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_boto_00"))
  CAMERA:SetTgt(SymCam("CAMERA_boto_00"))
  CH("PLAYER"):SetPosition(SymPos("P99_PLAYER"))
  if CHARA:IsExist("BUDDY1") then
    CH("BUDDY1"):SetPosition(SymPos("P99_BUDDY1"))
  end
  if CHARA:IsExist("BUDDY2") then
    CH("BUDDY2"):SetPosition(SymPos("P99_BUDDY2"))
  end
  if CHARA:IsExist("BUDDY3") then
    CH("BUDDY3"):SetPosition(SymPos("P99_BUDDY3"))
  end
  -- CH("PLAYER"):WalkTo(SymPos("P99_PLAYER"), Speed(1.5))
  -- if CHARA:IsExist("BUDDY1") then
  --   CH("BUDDY1"):WalkTo(SymPos("P99_BUDDY1"), Speed(1.5))
  -- end
  -- if CHARA:IsExist("BUDDY2") then
  --   CH("BUDDY2"):WalkTo(SymPos("P99_BUDDY2"), Speed(1.5))
  -- end
  -- if CHARA:IsExist("BUDDY3") then
  --   CH("BUDDY3"):WalkTo(SymPos("P99_BUDDY3"), Speed(1.5))
  -- end
  SCREEN_A:FadeInAll(TimeSec(0), false)
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- CH("PLAYER"):WaitMove()
  -- TASK:Sleep(TimeSec(0.3))
  -- CAMERA:MoveFollow2(SymCam("CAMERA_boto_01"), Speed(6, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- CAMERA:WaitMove()
  -- SCREEN_A:FadeOut(TimeSec(0.5), true)
  -- TASK:Sleep(TimeSec(0.3))
  -- CAMERA:SetEye(SymCam("CAMERA_boto_02"))
  -- CAMERA:SetTgt(SymCam("CAMERA_boto_02"))
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- TASK:Sleep(TimeSec(0.3))
  -- CAMERA:MoveFollow2(SymCam("CAMERA_boto_05"), Speed(6, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- CAMERA:WaitMove()
  -- SCREEN_A:FadeOut(TimeSec(0.5), true)
  -- TASK:Sleep(TimeSec(0.3))
  -- CAMERA:SetEye(SymCam("CAMERA_boto_04"))
  -- CAMERA:SetTgt(SymCam("CAMERA_boto_04"))
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- TASK:Sleep(TimeSec(0.3))
  -- CAMERA:MoveFollow2(SymCam("CAMERA_boto_05"), Speed(6, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- CAMERA:WaitMove()
  -- SCREEN_A:FadeOut(TimeSec(0.5), true)
  -- TASK:Sleep(TimeSec(0.3))
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_boto_03"))
  CAMERA:SetTgt(SymCam("CAMERA_boto_03"))
  CAMERA:MoveFollow2(SymCam("CAMERA_boto_03_5"), Speed(4, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CAMERA:WaitMove()
  TASK:Sleep(TimeSec(0.5))
  CAMERA:MoveToPlayer(Speed(6, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  subEveEncStartFadeSet_sub()
end
function ev_tontonyama_boto_cut()
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_boto_00"))
  CAMERA:SetTgt(SymCam("CAMERA_boto_00"))
  CAMERA:SetTgtAndFreeMoveEye(SymPos("P99_PLAYER"))
  CH("PLAYER"):WalkTo(SymPos("P99_PLAYER"), Speed(1.5))
  if CHARA:IsExist("BUDDY1") then
    CH("BUDDY1"):WalkTo(SymPos("P99_BUDDY1"), Speed(1.5))
  end
  if CHARA:IsExist("BUDDY2") then
    CH("BUDDY2"):WalkTo(SymPos("P99_BUDDY2"), Speed(1.5))
  end
  if CHARA:IsExist("BUDDY3") then
    CH("BUDDY3"):WalkTo(SymPos("P99_BUDDY3"), Speed(1.5))
  end
  SCREEN_A:FadeInAll(TimeSec(0), false)
  SCREEN_A:FadeIn(TimeSec(0.5), false)
  CH("PLAYER"):WaitMove()
  subEveEncStartFadeSet_sub()
  CAMERA:MoveToPlayer(TimeSec(0), ACCEL_TYPE.NONE, DECEL_TYPE.HIGH)
end
function ev_tontonyama_left_in()
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_boto_00"))
  CAMERA:SetTgt(SymCam("CAMERA_boto_00"))
  CAMERA:SetTgtAndFreeMoveEye(SymPos("P03_PLAYER"))
  CH("PLAYER"):WalkTo(SymPos("P03_PLAYER"), Speed(1.5))
  if CHARA:IsExist("BUDDY1") then
    CH("BUDDY1"):WalkTo(SymPos("P02_BUDDY1"), Speed(1.5))
  end
  if CHARA:IsExist("BUDDY2") then
    CH("BUDDY2"):WalkTo(SymPos("P02_BUDDY2"), Speed(1.5))
  end
  if CHARA:IsExist("BUDDY3") then
    CH("BUDDY3"):WalkTo(SymPos("P02_BUDDY3"), Speed(1.5))
  end
  SCREEN_A:FadeInAll(TimeSec(0), false)
  SCREEN_A:FadeIn(TimeSec(0.5), false)
  CH("PLAYER"):WaitMove()
  subEveEncStartFadeSet_sub()
  CAMERA:MoveToPlayer(TimeSec(0), ACCEL_TYPE.NONE, DECEL_TYPE.HIGH)
end
function ev_tontonyama_left_river()
  CH("PLAYER"):RunTo(SymPos("P04_PLAYER"), Speed(1.7))
  CH("PLAYER"):WaitMove()
  CH("PLAYER"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  CH("PLAYER"):WaitRotate()
  -- SYSTEM:SetStatusViewVisible(false)
  -- TASK:Sleep(TimeSec(0.3))
  -- CAMERA:MoveFollow2(SymCam("CAMERA_04_02"), Speed(6, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- CAMERA:WaitMove()
  -- TASK:Sleep(TimeSec(0.5))
  -- CH("PLAYER"):RunTo(SymPos("P05_PLAYER"), Speed(1.5))
  -- CH("PLAYER"):WaitMove()
  -- CH("PLAYER"):SetMotion(SymMot("ATTACK"), LOOP.OFF)
  -- TASK:Sleep(TimeSec(0.1))
  -- SOUND:PlaySe(SymSnd("SE_EVT_DOGA"), Volume(256))
  -- TASK:Sleep(TimeSec(0.1))
  -- EFFECT:Remove("effectglitter_left")
  -- EFFECT:Create("effectattace01", SymEff("NM_WAZAHIT_BIG_YELLOW"))
  -- EFFECT:SetScale("effectattace01", Scale(0.8))
  -- EFFECT:SetPosition("effectattace01", SymPos("P01_EFFECT_ATTACE"))
  -- EFFECT:Play("effectattace01")
  -- CAMERA:SetShake(Vector2(0.01, 0.01), TimeSec(1, TIME_TYPE.FRAME))
  -- GM("DE03_MARUTA_2"):SetMotion(SymMot("MOVE"), LOOP.OFF)
  -- TASK:Sleep(TimeSec(0.3))
  -- CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  -- CH("PLAYER"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  -- SOUND:PlaySe(SymSnd("SE_EVT_NUOO_RISE"), Volume(256))
  -- TASK:Sleep(TimeSec(0.2))
  -- SOUND:PlaySe(SymSnd("SE_EVT_NUOO_RISE"), Volume(256))
  -- TASK:Sleep(TimeSec(0.1))
  -- EFFECT:Create("effectspray1", SymEff("EV_WATER_SPRAY"))
  -- EFFECT:Create("effectspray2", SymEff("EV_WATER_SPRAY"))
  -- EFFECT:Create("effectspray3", SymEff("EV_WATER_SPRAY"))
  -- EFFECT:SetScale("effectspray1", Scale(1.5))
  -- EFFECT:SetScale("effectspray2", Scale(1.5))
  -- EFFECT:SetScale("effectspray3", Scale(1.5))
  -- EFFECT:SetPosition("effectspray1", SymPos("P01_EFFECT_SPRAY"))
  -- EFFECT:SetPosition("effectspray2", SymPos("P02_EFFECT_SPRAY"))
  -- EFFECT:SetPosition("effectspray3", SymPos("P03_EFFECT_SPRAY"))
  -- EFFECT:Play("effectspray1")
  -- EFFECT:Play("effectspray2")
  -- EFFECT:Play("effectspray3")
  -- TASK:Sleep(TimeSec(1.5))
  -- CH("PLAYER"):DirTo(SymPos("P04_maruta"), Speed(350), ROT_TYPE.NEAR)
  -- if CHARA:IsExist("BUDDY1") then
  --   CH("BUDDY1"):DirTo(SymPos("P04_maruta"), Speed(350), ROT_TYPE.NEAR)
  -- end
  -- if CHARA:IsExist("BUDDY2") then
  --   CH("BUDDY2"):DirTo(SymPos("P04_maruta"), Speed(350), ROT_TYPE.NEAR)
  -- end
  -- if CHARA:IsExist("BUDDY3") then
  --   CH("BUDDY3"):DirTo(SymPos("P04_maruta"), Speed(350), ROT_TYPE.NEAR)
  -- end
  -- CAMERA:MoveFollow2(SymCam("CAMERA_04_03"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- TASK:Sleep(TimeSec(5))
  -- SCREEN_A:FadeOut(TimeSec(1), true)
  -- TASK:Sleep(TimeSec(0.5))
  -- SOUND:PlaySe(SymSnd("SE_EVT_NUOO_RISE"), Volume(256))
  -- TASK:Sleep(TimeSec(0.5))
  -- SOUND:PlaySe(SymSnd("SE_EVT_NUOO_RISE"), Volume(256))
  -- TASK:Sleep(TimeSec(0.2))
  -- SOUND:PlaySe(SymSnd("SE_EVT_NUOO_RISE"), Volume(256))
  -- TASK:Sleep(TimeSec(1))
  -- GM("DE03_MARUTA_2"):SetVisible(false)
  -- GM("DE03_MARUTA_4"):SetVisible(true)
  -- GM("DE03_MARUTA_4"):SetMotion(SymMot("MOVE"), LOOP.OFF)
  -- CAMERA:SetEye(SymCam("CAMERA_04_04"))
  -- CAMERA:SetTgt(SymCam("CAMERA_04_04"))
  -- TASK:Sleep(TimeSec(0.5))
  -- CAMERA:MoveFollow2(SymCam("CAMERA_04_05"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  EFFECT:Remove("effectglitter_left")
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  GM("DE03_MARUTA_2"):SetVisible(false)
end
function ev_tontonyama_left_river_rightNG()
  -- SCREEN_A:FadeIn(TimeSec(1), true)
  -- GM("DE03_MARUTA_4"):WaitPlayMotion()
  -- GM("DE03_MARUTA_4"):SetMotion(SymMot("END"), LOOP.OFF)
  -- TASK:Sleep(TimeSec(0.8))
  -- SCREEN_A:FadeOut(TimeSec(0.5), true)
  -- TASK:Sleep(TimeSec(0.3))
  CAMERA:MoveToPlayer(TimeSec(0), ACCEL_TYPE.NONE, DECEL_TYPE.HIGH)
  SCREEN_A:FadeIn(TimeSec(0.5), true)
end
function ev_tontonyama_left_river_rightclear()
  -- SCREEN_A:FadeIn(TimeSec(1), true)
  -- GM("DE03_MARUTA_4"):WaitPlayMotion()
  -- SOUND:PlayMe(SymSnd("SE_ENC_GIMMICK_CLEAR"))
  -- GM("DE03_MARUTA_4"):SetMotion(SymMot("END"), LOOP.OFF)
  -- TASK:Sleep(TimeSec(0.8))
  -- SCREEN_A:FadeOut(TimeSec(0.5), true)
  -- TASK:Sleep(TimeSec(0.3))
  CAMERA:MoveToPlayer(TimeSec(0), ACCEL_TYPE.NONE, DECEL_TYPE.HIGH)
  SCREEN_A:FadeIn(TimeSec(0.5), true)
end
function ev_tontonyama_right_in()
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_boto_00"))
  CAMERA:SetTgt(SymCam("CAMERA_boto_00"))
  CAMERA:SetTgtAndFreeMoveEye(SymPos("P00_PLAYER"))
  CH("PLAYER"):WalkTo(SymPos("P00_PLAYER"), Speed(1.5))
  if CHARA:IsExist("BUDDY1") then
    CH("BUDDY1"):WalkTo(SymPos("P00_BUDDY1"), Speed(1.5))
  end
  if CHARA:IsExist("BUDDY2") then
    CH("BUDDY2"):WalkTo(SymPos("P00_BUDDY2"), Speed(1.5))
  end
  if CHARA:IsExist("BUDDY3") then
    CH("BUDDY3"):WalkTo(SymPos("P00_BUDDY3"), Speed(1.5))
  end
  SCREEN_A:FadeInAll(TimeSec(0), false)
  SCREEN_A:FadeIn(TimeSec(0.5), false)
  CH("PLAYER"):WaitMove()
  subEveEncStartFadeSet_sub()
  CAMERA:MoveToPlayer(TimeSec(0), ACCEL_TYPE.NONE, DECEL_TYPE.HIGH)
end
function ev_tontonyama_right_river()
  CH("PLAYER"):RunTo(SymPos("P01_PLAYER"), Speed(1.7))
  CH("PLAYER"):WaitMove()
  CH("PLAYER"):DirTo(RotateTarget(90), Speed(350), ROT_TYPE.NEAR)
  CH("PLAYER"):WaitRotate()
  -- SYSTEM:SetStatusViewVisible(false)
  -- TASK:Sleep(TimeSec(0.3))
  -- CAMERA:MoveFollow2(SymCam("CAMERA_02_02"), Speed(6, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- CAMERA:WaitMove()
  -- TASK:Sleep(TimeSec(0.5))
  -- CH("PLAYER"):RunTo(SymPos("P02_PLAYER"), Speed(1.5))
  -- CH("PLAYER"):WaitMove()
  -- CH("PLAYER"):SetMotion(SymMot("ATTACK"), LOOP.OFF)
  -- TASK:Sleep(TimeSec(0.1))
  -- SOUND:PlaySe(SymSnd("SE_EVT_DOGA"), Volume(256))
  -- TASK:Sleep(TimeSec(0.1))
  -- EFFECT:Remove("effectglitter_right")
  -- EFFECT:Create("effectattace02", SymEff("NM_WAZAHIT_BIG_YELLOW"))
  -- EFFECT:SetScale("effectattace02", Scale(0.8))
  -- EFFECT:SetPosition("effectattace02", SymPos("P02_EFFECT_ATTACE"))
  -- EFFECT:Play("effectattace02")
  -- CAMERA:SetShake(Vector2(0.01, 0.01), TimeSec(1, TIME_TYPE.FRAME))
  -- GM("DE03_MARUTA_1"):SetMotion(SymMot("MOVE"), LOOP.OFF)
  -- TASK:Sleep(TimeSec(0.3))
  -- CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  -- CH("PLAYER"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  -- SOUND:PlaySe(SymSnd("SE_EVT_NUOO_RISE"), Volume(256))
  -- TASK:Sleep(TimeSec(0.2))
  -- SOUND:PlaySe(SymSnd("SE_EVT_NUOO_RISE"), Volume(256))
  -- TASK:Sleep(TimeSec(0.1))
  -- EFFECT:Create("effectspray4", SymEff("EV_WATER_SPRAY"))
  -- EFFECT:Create("effectspray5", SymEff("EV_WATER_SPRAY"))
  -- EFFECT:Create("effectspray6", SymEff("EV_WATER_SPRAY"))
  -- EFFECT:SetScale("effectspray4", Scale(1.5))
  -- EFFECT:SetScale("effectspray5", Scale(1.5))
  -- EFFECT:SetScale("effectspray6", Scale(1.5))
  -- EFFECT:SetPosition("effectspray4", SymPos("P04_EFFECT_SPRAY"))
  -- EFFECT:SetPosition("effectspray5", SymPos("P05_EFFECT_SPRAY"))
  -- EFFECT:SetPosition("effectspray6", SymPos("P06_EFFECT_SPRAY"))
  -- EFFECT:Play("effectspray4")
  -- EFFECT:Play("effectspray5")
  -- EFFECT:Play("effectspray6")
  -- TASK:Sleep(TimeSec(1.5))
  -- CH("PLAYER"):DirTo(SymPos("P02_maruta"), Speed(350), ROT_TYPE.NEAR)
  -- if CHARA:IsExist("BUDDY1") then
  --   CH("BUDDY1"):DirTo(SymPos("P02_maruta"), Speed(350), ROT_TYPE.NEAR)
  -- end
  -- if CHARA:IsExist("BUDDY2") then
  --   CH("BUDDY2"):DirTo(SymPos("P02_maruta"), Speed(350), ROT_TYPE.NEAR)
  -- end
  -- if CHARA:IsExist("BUDDY3") then
  --   CH("BUDDY3"):DirTo(SymPos("P02_maruta"), Speed(350), ROT_TYPE.NEAR)
  -- end
  -- CAMERA:MoveFollow2(SymCam("CAMERA_02_03"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- TASK:Sleep(TimeSec(5))
  -- SCREEN_A:FadeOut(TimeSec(1), true)
  -- TASK:Sleep(TimeSec(0.5))
  -- SOUND:PlaySe(SymSnd("SE_EVT_NUOO_RISE"), Volume(256))
  -- TASK:Sleep(TimeSec(0.5))
  -- SOUND:PlaySe(SymSnd("SE_EVT_NUOO_RISE"), Volume(256))
  -- TASK:Sleep(TimeSec(0.2))
  -- SOUND:PlaySe(SymSnd("SE_EVT_NUOO_RISE"), Volume(256))
  -- TASK:Sleep(TimeSec(1))
  -- GM("DE03_MARUTA_1"):SetVisible(false)
  -- GM("DE03_MARUTA_3"):SetVisible(true)
  -- GM("DE03_MARUTA_3"):SetMotion(SymMot("MOVE"), LOOP.OFF)
  -- CAMERA:SetEye(SymCam("CAMERA_02_04"))
  -- CAMERA:SetTgt(SymCam("CAMERA_02_04"))
  -- TASK:Sleep(TimeSec(0.5))
  -- CAMERA:MoveFollow2(SymCam("CAMERA_02_05"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  EFFECT:Remove("effectglitter_right")
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  GM("DE03_MARUTA_1"):SetVisible(false)
end
function ev_tontonyama_right_river_leftNG()
  -- SCREEN_A:FadeIn(TimeSec(1), true)
  -- GM("DE03_MARUTA_3"):WaitPlayMotion()
  -- GM("DE03_MARUTA_3"):SetMotion(SymMot("END"), LOOP.OFF)
  -- TASK:Sleep(TimeSec(0.8))
  -- SCREEN_A:FadeOut(TimeSec(0.5), true)
  -- TASK:Sleep(TimeSec(0.3))
  CAMERA:MoveToPlayer(TimeSec(0), ACCEL_TYPE.NONE, DECEL_TYPE.HIGH)
  SCREEN_A:FadeIn(TimeSec(0.5), true)
end
function ev_tontonyama_right_river_leftclear()
  -- SCREEN_A:FadeIn(TimeSec(1), true)
  -- GM("DE03_MARUTA_3"):WaitPlayMotion()
  -- SOUND:PlayMe(SymSnd("SE_ENC_GIMMICK_CLEAR"))
  -- GM("DE03_MARUTA_3"):SetMotion(SymMot("END"), LOOP.OFF)
  -- TASK:Sleep(TimeSec(0.8))
  -- SCREEN_A:FadeOut(TimeSec(0.5), true)
  -- TASK:Sleep(TimeSec(0.3))
  CAMERA:MoveToPlayer(TimeSec(0), ACCEL_TYPE.NONE, DECEL_TYPE.HIGH)
  SCREEN_A:FadeIn(TimeSec(0.5), true)
end
function ev_tontonyama_leftdown_1st()
  SCREEN_B:FadeOutAll(TimeSec(0.5), false)
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  SCREEN_B:FadeOut(TimeSec(0), false)
  SOUND:PlaySe(SymSnd("SE_ENC_LADDER_DOWN"), Volume(256))
  TASK:Sleep(TimeSec(0.7))
  SOUND:PlaySe(SymSnd("SE_ENC_LADDER_DOWN"), Volume(256))
  TASK:Sleep(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_ENC_LADDER_DOWN_MISS"), Volume(256))
  TASK:Sleep(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_ENC_LADDER_FALL"), Volume(256))
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(765552517)
  TASK:Sleep(TimeSec(1))
  WINDOW:ForceCloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_POYON"), Volume(256))
  subEncountFromProgFadeOutSet()
end
function ev_tontonyama_leftdown_2st()
  subEncountFromProgFadeOutSet2()
end
function ev_tontonyama_leftdown_1st_02()
  subEveFromProgFadeSet()
  CAMERA:SetEye(SymCam("CAMERA_08_01"))
  CAMERA:SetTgt(SymCam("CAMERA_08_01"))
  SYSTEM:DebugPrint("down3")
  CH("PLAYER"):SetMotion(SymMot("EV001_DOWN01"), LOOP.ON, TimeSec(0))
  CH("BUDDY1"):SetMotion(SymMot("EV001_DOWN01"), LOOP.ON, TimeSec(0))
  TASK:Sleep(TimeSec(0.2))
  SYSTEM:DebugPrint("down4")
  subEveEncStartFadeSet_main()
  TASK:Sleep(TimeSec(0.8))
  CH("PLAYER"):SetMotion(SymMot("EV001_DOWN02"), LOOP.OFF)
  TASK:Sleep(TimeSec(0.1))
  CH("BUDDY1"):SetMotion(SymMot("EV001_DOWN02"), LOOP.OFF)
  CH("BUDDY1"):WaitPlayMotion()
  CH("PLAYER"):WaitPlayMotion()
  CH("PLAYER"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("BUDDY1"):WaitPlayMotion()
  CH("BUDDY1"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("PLAYER"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("BUDDY1"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.NEAR)
  CH("BUDDY1"):WaitRotate()
  CH("PLAYER"):SetNeckRot(RotateTarget(0), RotateTarget(35), RotateTarget(0), TimeSec(0.3))
  CH("BUDDY1"):SetNeckRot(RotateTarget(0), RotateTarget(35), RotateTarget(0), TimeSec(0.3))
  CH("BUDDY1"):WaitNeckRot()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.FAINT)
  WINDOW:Monologue(884627140)
  WINDOW:CloseMessage()
  CH("PLAYER"):ResetNeckRot(TimeSec(0.3))
  TASK:Sleep(TimeSec(0.2))
  CH("BUDDY1"):ResetNeckRot(TimeSec(0.3))
  CAMERA:MoveToPlayer(Speed(5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  subEveEncStartFadeSet_sub()
end
function ev_tontonyama_leftdown_1st_02_cut()
  CAMERA:SetEye(SymCam("CAMERA_08_01"))
  CAMERA:SetTgt(SymCam("CAMERA_08_01"))
  CAMERA:SetTgtAndFreeMoveEye(SymPos("P98_PLAYER"))
  subEncountFromProgFadeSet()
  CAMERA:MoveToPlayer(TimeSec(0), ACCEL_TYPE.NONE, DECEL_TYPE.HIGH)
end
function ev_tontonyama_rightdown_1st()
  SCREEN_B:FadeOutAll(TimeSec(0.5), false)
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  SCREEN_B:FadeOut(TimeSec(0), false)
  SOUND:PlaySe(SymSnd("SE_ENC_LADDER_DOWN"), Volume(256))
  TASK:Sleep(TimeSec(0.7))
  SOUND:PlaySe(SymSnd("SE_ENC_LADDER_DOWN"), Volume(256))
  TASK:Sleep(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_ENC_LADDER_DOWN_MISS"), Volume(256))
  TASK:Sleep(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_ENC_LADDER_FALL"), Volume(256))
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(529990919)
  TASK:Sleep(TimeSec(1))
  WINDOW:ForceCloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_POYON"), Volume(256))
  subEncountFromProgFadeOutSet()
end
function ev_tontonyama_rightdown_2st()
  subEncountFromProgFadeOutSet2()
end
function ev_tontonyama_rightdown_1st_02()
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_06_01"))
  CAMERA:SetTgt(SymCam("CAMERA_06_01"))
  CH("PLAYER"):SetMotion(SymMot("EV001_DOWN01"), LOOP.ON, TimeSec(0))
  CH("BUDDY1"):SetMotion(SymMot("EV001_DOWN01"), LOOP.ON, TimeSec(0))
  TASK:Sleep(TimeSec(0.2))
  subEveEncStartFadeSet_main()
  TASK:Sleep(TimeSec(0.8))
  CH("PLAYER"):SetMotion(SymMot("EV001_DOWN02"), LOOP.OFF)
  TASK:Sleep(TimeSec(0.1))
  CH("BUDDY1"):SetMotion(SymMot("EV001_DOWN02"), LOOP.OFF)
  CH("PLAYER"):WaitPlayMotion()
  CH("PLAYER"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("BUDDY1"):WaitPlayMotion()
  CH("BUDDY1"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("PLAYER"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("BUDDY1"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  CH("BUDDY1"):WaitRotate()
  CH("PLAYER"):SetNeckRot(RotateTarget(0), RotateTarget(35), RotateTarget(0), TimeSec(0.3))
  CH("BUDDY1"):SetNeckRot(RotateTarget(0), RotateTarget(35), RotateTarget(0), TimeSec(0.3))
  CH("BUDDY1"):WaitNeckRot()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.FAINT)
  WINDOW:Monologue(109851718)
  WINDOW:CloseMessage()
  CH("PLAYER"):ResetNeckRot(TimeSec(0.3))
  TASK:Sleep(TimeSec(0.2))
  CH("BUDDY1"):ResetNeckRot(TimeSec(0.3))
  CAMERA:MoveToPlayer(Speed(5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  subEveEncStartFadeSet_sub()
end
function ev_tontonyama_rightdown_1st_02_cut()
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_06_01"))
  CAMERA:SetTgt(SymCam("CAMERA_06_01"))
  CAMERA:SetTgtAndFreeMoveEye(SymPos("P97_PLAYER"))
  subEncountFromProgFadeSet()
  CAMERA:MoveToPlayer(TimeSec(0), ACCEL_TYPE.NONE, DECEL_TYPE.HIGH)
end
function ev_tontonyama_leftup()
  SYSTEM:ClearEncountDungeonLog()
  CH("PLAYER"):DirTo(SymPos("POINT_LOOK_HASHIGO02"), Speed(350), ROT_TYPE.NEAR)
  CH("PLAYER"):WaitRotate()
  CH("PLAYER"):SetNeckRot(RotateTarget(0), RotateTarget(35), RotateTarget(0), TimeSec(0.3))
  CH("PLAYER"):WaitNeckRot()
  WINDOW:SysMsg(1238213249)
  WINDOW:SysMsg(1356239808)
  WINDOW:CloseMessage()
  CH("PLAYER"):ResetNeckRot(TimeSec(0.3))
end
function ev_tontonyama_rightup()
  SYSTEM:ClearEncountDungeonLog()
  CH("PLAYER"):DirTo(SymPos("POINT_LOOK_HASHIGO01"), Speed(350), ROT_TYPE.NEAR)
  CH("PLAYER"):WaitRotate()
  CH("PLAYER"):SetNeckRot(RotateTarget(0), RotateTarget(35), RotateTarget(0), TimeSec(0.3))
  CH("PLAYER"):WaitNeckRot()
  WINDOW:SysMsg(2080096259)
  WINDOW:SysMsg(1658908994)
  WINDOW:CloseMessage()
  CH("PLAYER"):ResetNeckRot(TimeSec(0.3))
end
function ev_tontonyama01()
  subEveEncNotBackMsg()
end
function ev_tontonyama02()
  subEveEncNotBackMsg()
end
function ev_tontonyama_kanban()
  SYSTEM:ClearEncountDungeonLog()
  CH("PLAYER"):DirTo(SymPos("POINT_KANBAN"), Speed(350), ROT_TYPE.NEAR)
  CH("PLAYER"):WaitRotate()
  WINDOW:SysMsg(-445059699)
  WINDOW:CloseMessage()
end

