dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main11_palaceboss1st01_init()
end
function main11_palaceboss1st01_start()
  subEveFromProgFadeSet()
  TASK:Sleep(TimeSec(1))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.THINK)
  WINDOW:SwitchTalk({PARTNER_0 = 967207634, PARTNER_1 = 549280659})
  WINDOW:SwitchTalk({PARTNER_0 = 193988688, PARTNER_1 = 311114001})
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BURAKKII"), 1573564374)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("BIRIJION"), FACE_TYPE.SPECIAL05)
  WINDOW:Talk(SymAct("BIRIJION"), 1154588311)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_GORIGORI"), Volume(256))
  WINDOW:SysMsg(1878838612)
  TASK:Sleep(TimeSec(2))
  WINDOW:ForceCloseMessage()
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 1994914837, PARTNER_1 = -243277606})
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_GORIGORI"), Volume(256))
  WINDOW:SysMsg(-396045925)
  TASK:Sleep(TimeSec(2))
  WINDOW:ForceCloseMessage()
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("EEFI"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("EEFI"), 944395540)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("BURAKKII"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("BURAKKII"), 558982229)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_GORUUGU_ROAR"), Volume(256))
  WINDOW:SysMsg(175912854)
  SCREEN_A:WhiteOutAll(TimeSec(0.5), true)
  WINDOW:ForceCloseMessage()
  TASK:Sleep(TimeSec(1))
  SCREEN_A:FadeInAll(TimeSec(0), true)
  CH("FURIIJIO_1"):SetVisible(false)
  CH("FURIIJIO_2"):SetVisible(false)
  CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:MoveFollow2(SymCam("CAMERA_00_5"), Speed(15, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SCREEN_A:WhiteIn(TimeSec(0.5), false)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("NOKOTCHI"):SetManpu("MP_SHOCK_L")
  CH("NOKOTCHI"):WalkTo(SymPos("P01_NOKOTCHI"), Speed(1.5), LINK_DIR.OFF)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):WalkTo(SymPos("P01_HERO"), Speed(1.5), LINK_DIR.OFF)
  CH("BURAKKII"):SetManpu("MP_EXCLAMATION")
  CH("BURAKKII"):WalkTo(SymPos("P01_BURAKKII"), Speed(1.5), LINK_DIR.OFF)
  TASK:Sleep(TimeSec(0.1))
  CH("BIRIJION"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  CH("PARTNER"):WalkTo(SymPos("P01_PARTNER"), Speed(1.5), LINK_DIR.OFF)
  CH("BIRIJION"):WalkTo(SymPos("P01_BIRIJION"), Speed(1.5), LINK_DIR.OFF)
  TASK:Sleep(TimeSec(0.1))
  CH("EEFI"):SetManpu("MP_NOTICE_R")
  CH("EEFI"):WalkTo(SymPos("P01_EEFI"), Speed(1.5), LINK_DIR.OFF)
  CH("NOKOTCHI"):WaitManpu()
  TASK:Regist(subEveJumpSurprise, {
    CH("NOKOTCHI")
  })
  WINDOW:DrawFace(324, 88, SymAct("NOKOTCHI"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("NOKOTCHI"), 325519063)
  SOUND:PlayBgm(SymSnd("BGM_EVE_FEAR_01"), Volume(256))
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetFovy(SymCam("CAMERA_10"))
  CAMERA:SetEye(SymCam("CAMERA_10"))
  CAMERA:SetTgt(SymCam("CAMERA_10"))
  CAMERA:MoveFollow2(SymCam("CAMERA_10_5"), Speed(0.2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("EEFI"):SetVisible(false)
  WINDOW:DrawFace(20, 88, SymAct("BURAKKII"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("BURAKKII"), 1546031120)
  WINDOW:Talk(SymAct("BURAKKII"), 1161666897)
  CAMERA:WaitMove()
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetFovy(SymCam("CAMERA_00_5"))
  CAMERA:SetEye(SymCam("CAMERA_00_5"))
  CAMERA:SetTgt(SymCam("CAMERA_00_5"))
  CH("EEFI"):SetVisible(true)
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(1846604434)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetDefaultGroundFovy()
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CH("FURIIJIO_1"):SetVisible(true)
  CH("FURIIJIO_2"):SetVisible(true)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("EEFI"):SetManpu("MP_EXCLAMATION")
  CH("EEFI"):WaitManpu()
  CH("FURIIJIO_1"):RunTo(SymPos("P01_ZAKO_1"), Speed(2))
  CH("FURIIJIO_2"):RunTo(SymPos("P01_ZAKO_2"), Speed(2))
  CH("EEFI"):DirTo(SymPos("P01_ZAKO_1"), Speed(500), ROT_TYPE.NEAR)
  CH("EEFI"):WaitRotate()
  WINDOW:DrawFace(272, 16, SymAct("EEFI"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("EEFI"), 1997259731)
  WINDOW:CloseMessage()
  CH("FURIIJIO_2"):WaitMove()
  CH("FURIIJIO_1"):WaitMove()
  SOUND:FadeOutBgm(TimeSec(2.5))
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  CH("BIRIJION"):DirTo(RotateTarget(0), Speed(500), ROT_TYPE.NEAR)
  CH("PARTNER"):DirTo(RotateTarget(-45), Speed(500), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("BURAKKII"):DirTo(RotateTarget(0), Speed(500), ROT_TYPE.NEAR)
  CH("HERO"):DirTo(RotateTarget(45), Speed(500), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("NOKOTCHI"):DirTo(RotateTarget(0), Speed(500), ROT_TYPE.NEAR)
  CH("FURIIJIO_1"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
  CH("FURIIJIO_2"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
  TASK:Sleep(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_FLUSH"), Volume(256))
  subEveFlash()
  CH("NOKOTCHI"):DirTo(CH("GORUUGU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("BURAKKII"):DirTo(CH("GORUUGU"), Speed(350), ROT_TYPE.NEAR)
  CH("BURAKKII"):WaitRotate()
  CH("HERO"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
  CH("BIRIJION"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
  TASK:Sleep(TimeSec(0.1))
  CH("BURAKKII"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
  CH("EEFI"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
  CH("NOKOTCHI"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetFovy(SymCam("CAMERA_04"))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  WINDOW:DrawFaceF(20, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = -258744548, PARTNER_1 = -376902051})
  WINDOW:CloseMessage()
  subEveFlash2()
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetFovy(SymCam("CAMERA_05"))
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  EFFECT:StartMotionBlur(0.04, 0.9, 0)
  CH("GORUUGU"):SetMotion(SymMot("EV011_MEANCE"), LOOP.OFF)
  CH("GORUUGU"):SetNextMotion(SymMot("EV011_MEANCELOOP"), LOOP.ON, TimeSec(0))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  SOUND:PlaySe(SymSnd("SE_EVT_GORUUGU_ROAR"), Volume(256))
  WINDOW:SysMsg(721419002)
  TASK:Sleep(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_BOSS_WIPE"), Volume(256))
  EFFECT:BossWipe(TimeSec(60, TIME_TYPE.FRAME), true)
  WINDOW:ForceCloseMessage()
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  CAMERA:SetDefaultGroundFovy()
  CAMERA:ResetAzimuthDifferenceVolume()
  EFFECT:EndMotionBlur()
  FLAG.SceneFlag = CONST.FL_SC_01_FIRST
  FLAG.SCENARIOFLAG = CONST.M11_PALACEBOSS1ST_END
  SYSTEM:SetDungeonWaypointStat(Dg(11), DG_WAYPOINT.DUNGEONEND, DG_WAYPOINT_STAT.AFTER)
  SYSTEM:SetNextDungeonBanner(false)
  SYSTEM:EnterDungeon(Dg(11), DG_WAYPOINT.BOSS00)
end
function main11_palaceboss1st01_end()
end
function groundEnd()
end

