dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main14_fuuketsunookafurizumu01_init()
end
function main14_fuuketsunookafurizumu01_start()
  subEveFromProgFadeSet()
  TASK:Sleep(TimeSec(1))
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  GM("FURIZUMU_AFTER"):SetMotion(SymMot("B"), LOOP.OFF)
  GM("FURIZUMU_BEFORE"):SetVisible(false)
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("HERO"):WalkTo(SymPos("P01_HERO"), Speed(2))
  CH("SAZANDORA_LARGE"):WalkTo(SymPos("P01_SAZANDORA"), Speed(2.5))
  CH("HERO"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("SAZANDORA_LARGE"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("SAZANDORA_LARGE"):SetManpu("MP_EXCLAMATION")
  CH("SAZANDORA_LARGE"):WaitManpu()
  CAMERA:MoveFollow(SymCam("CAMERA_01"), Speed(3, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Regist(subEveRunDir, {
    CH("HERO"),
    SymPos("P02_HERO"),
    Speed(3),
    GM("FURIZUMU_AFTER")
  })
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(subEveRunDir, {
    CH("SAZANDORA_LARGE"),
    SymPos("P02_SAZANDORA"),
    Speed(3),
    GM("FURIZUMU_AFTER")
  })
  CAMERA:WaitMove()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CH("SAZANDORA_LARGE"):WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), 1125278782)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.THINK)
  WINDOW:Monologue(1510561151)
  WINDOW:Monologue(1898186428)
  WINDOW:Monologue(1748973565)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), 662610234)
  WINDOW:Talk(SymAct("SAZANDORA"), 1046843515)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.THINK)
  WINDOW:Monologue(357090232)
  WINDOW:Monologue(206828281)
  WINDOW:CloseMessage()
  CH("HERO"):WalkTo(SymPos("P03_HERO"), Speed(1.2))
  CH("HERO"):WaitMove()
  TASK:Sleep(TimeSec(0.3))
  WINDOW:SysMsg(-1949569482)
  WINDOW:CloseMessage()
  CH("HERO"):WalkTo(SymPos("P02_HERO"), Speed(1.2), LINK_DIR.OFF)
  CH("HERO"):WaitMove()
  TASK:Sleep(TimeSec(0.3))
  EFFECT:Create("effectSmokeWhite", SymEff("EV_SMOKE_WHITE"))
  EFFECT:SetPosition("effectSmokeWhite", SymPos("P_EFF_SMOKE_WHITE"))
  EFFECT:Play("effectSmokeWhite")
  SOUND:PlaySe(SymSnd("SE_EVT_FRIZM_KAITOU"), Volume(256))
  TASK:Sleep(TimeSec(0.2))
  GM("FURIZUMU_AFTER"):SetVisible(false)
  GM("FURIZUMU_BEFORE"):SetVisible(true)
  GM("FURIZUMU_BEFORE"):SetMotion(SymMot("B"), LOOP.OFF)
  TASK:Sleep(TimeSec(0.5))
  WINDOW:SysMsg(-1831805065)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.3))
  CAMERA:MoveFollow2(SymCam("CAMERA_03_5"), Speed(0.05, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  WINDOW:SwitchTalk({PARTNER_0 = 758758983, PARTNER_1 = 874680070})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("HERO"):SetManpu("MP_SHOCK_L")
  CH("SAZANDORA_LARGE"):SetManpu("MP_EXCLAMATION")
  CH("SAZANDORA_LARGE"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(521133253)
  subEveCloseMsg()
  SOUND:PlayBgm(SymSnd("BGM_EVE_FUON_01"), Volume(256))
  WINDOW:SwitchTalk({PARTNER_0 = 102034820, PARTNER_1 = 1230338883})
  WINDOW:SwitchTalk({PARTNER_0 = 1347308034, PARTNER_1 = 2070092225})
  subEveCloseMsg()
  WINDOW:Talk(SymAct("MUNNA"), 1652041856)
  WINDOW:Talk(SymAct("MUNNA"), -438291377)
  WINDOW:Talk(SymAct("MUNNA"), -50658034)
  subEveCloseMsg()
  WINDOW:SwitchTalk({PARTNER_0 = 1066144169, PARTNER_1 = 647438568})
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_HIT_DOKKORAA"), Volume(256))
  SOUND:WaitSe(SymSnd("SE_EVT_HIT_DOKKORAA"))
  WINDOW:SwitchTalk({PARTNER_0 = 230322987, PARTNER_1 = 346112618})
  subEveCloseMsg()
  WINDOW:Talk(SymAct("DOKUROGGU"), 1541461165)
  WINDOW:Talk(SymAct("DOKUROGGU"), 1123804652)
  subEveCloseMsg()
  WINDOW:SwitchTalk({PARTNER_0 = 1775679023, PARTNER_1 = 1892517742})
  subEveCloseMsg()
  WINDOW:SysMsg(-145384543)
  subEveCloseMsg()
  TASK:Sleep(TimeSec(0.7))
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), -296834336)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("SAZANDORA_LARGE"):SetManpu("MP_FLY_SWEAT")
  CH("SAZANDORA_LARGE"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), -2026866996)
  WINDOW:Talk(SymAct("SAZANDORA"), -1641330803)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.THINK)
  WINDOW:Monologue(-1257892786)
  WINDOW:Monologue(-1407376113)
  WINDOW:Monologue(-480463928)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(2.5))
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:Monologue(-95976823)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  TASK:Sleep(TimeSec(0.3))
  CH("SAZANDORA_LARGE"):DirTo(CH("HERO"), Speed(200), ROT_TYPE.NEAR)
  CH("SAZANDORA_LARGE"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), -781528758)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("HERO"):SetManpu("MP_NOTICE_L")
  CH("HERO"):WaitManpu()
  CH("HERO"):DirTo(CH("SAZANDORA_LARGE"), Speed(200), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), -932061173)
  WINDOW:Talk(SymAct("SAZANDORA"), 1340734660)
  WINDOW:Talk(SymAct("SAZANDORA"), 1458752901)
  WINDOW:Talk(SymAct("SAZANDORA"), 451366517)
  WINDOW:Talk(SymAct("SAZANDORA"), 66879284)
  WINDOW:Talk(SymAct("SAZANDORA"), 684797175)
  WINDOW:CloseMessage()
  subEveNod(CH("HERO"))
  TASK:Sleep(TimeSec(0.2))
  subEveToEvProgFadeSet()
  CAMERA:ResetAzimuthDifferenceVolume()
  FLAG.SceneFlag = CONST.FL_SC_01_FIRST
  FLAG.SCENARIOFLAG = CONST.M14_FUUKETSUNOOKAFURIZUMU_END
  SYSTEM:SetDungeonWaypointStat(Dg(17), DG_WAYPOINT.POINT01, DG_WAYPOINT_STAT.AFTER)
  SYSTEM:EnterDungeon(Dg(17), DG_WAYPOINT.POINT01)
end
function main14_fuuketsunookafurizumu01_end()
end
function groundEnd()
end

