dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main04_zairyoutottekitayo01_init()
end
function main04_zairyoutottekitayo01_start()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  -- CH("DOTEKKOTSU"):SetManpu("MP_EXCLAMATION")
  -- CH("DOTEKKOTSU"):WaitManpu()
  -- WINDOW:DrawFace(72, 16, SymAct("DOTEKKOTSU"), FACE_TYPE.SURPRISE)
  -- WINDOW:Talk(SymAct("DOTEKKOTSU"), 1822282385)
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  -- WINDOW:SwitchTalk({PARTNER_0 = 1971774416, PARTNER_1 = 1588310035})
  -- WINDOW:SwitchTalk({PARTNER_0 = 1202749778, PARTNER_1 = 150017941})
  -- WINDOW:CloseMessage()
  -- CH("PARTNER"):WalkTo(SymPos("P01_PARTNER"), Speed(1.5))
  -- CH("PARTNER"):WaitMove()
  -- SOUND:PlaySe(SymSnd("SE_EVT_HAND"), Volume(256))
  -- TASK:Sleep(TimeSec(0.3))
  -- WINDOW:SysMsg(300558036)
  -- WINDOW:CloseMessage()
  -- LUA_SYSTEM:ConsumePayKenzai_DotekkotsuFirst()
  -- CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(1.5), LINK_DIR.OFF)
  -- CH("PARTNER"):WaitMove()
  -- TASK:Sleep(TimeSec(0.3))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  -- CAMERA:SetEye(SymCam("CAMERA_01"))
  -- CAMERA:SetTgt(SymCam("CAMERA_01"))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  -- CH("DOTEKKOTSU"):SetManpu("MP_SHOCK_R")
  -- CH("DOTEKKOTSU"):WaitManpu()
  -- WINDOW:Talk(SymAct("DOTEKKOTSU"), 986150167)
  -- WINDOW:CloseMessage()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  -- CH("DOTEKKOTSU"):SetManpu("MP_FLY_SWEAT")
  -- CH("DOTEKKOTSU"):SetMotion(SymMot("EV002_CRY00"), LOOP.ON, TimeSec(0.2))
  -- CH("DOTEKKOTSU"):WaitManpu()
  -- WINDOW:Talk(SymAct("DOTEKKOTSU"), 601637974)
  -- WINDOW:Talk(SymAct("DOTEKKOTSU"), -1539024743)
  -- WINDOW:Talk(SymAct("DOTEKKOTSU"), -1117820456)
  -- WINDOW:KeyWait()
  -- CH("DOTEKKOTSU"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.2))
  -- WINDOW:Talk(SymAct("DOTEKKOTSU"), 648292183)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- subEveDoubleJump(CH("PARTNER"))
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  -- WINDOW:SwitchTalk({PARTNER_0 = 1069487638, PARTNER_1 = 345130453})
  -- WINDOW:SwitchTalk({PARTNER_0 = 227112084, PARTNER_1 = 1120461395})
  -- WINDOW:CloseMessage()
  CAMERA:MoveToHero(Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  FLAG.SceneFlag = CONST.FL_SC_01_FIRST
  FLAG.SCENARIOFLAG = CONST.M04_ZAIRYOUTOTTEKITAYO_END
  FLAG.MapFlags = CONST.MAP_EVENT
  FLAG.FreePlay = CONST.FLAG_TRUE
  FLAG.TrigNextEvent = CONST.FLAG_FALSE
  SYSTEM:NextEntry(KEEP_PLACEMENT.ON)
end
function main04_zairyoutottekitayo01_end()
end
function groundEnd()
end

