dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main06_kyoukaikaranoshirase01_init()
end
function main06_kyoukaikaranoshirase01_start()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  GM("GOUGAI_S"):SetVisible(false)
  GM("GOUGAI_S02"):SetVisible(false)
  GM("GOUGAI_S03"):SetVisible(false)
  GM("GOUGAI_S04"):SetVisible(false)
  GM("GOUGAI_S05"):SetVisible(false)
  CH("HERO"):WalkTo(SymPos("P01_HERO"), Speed(1.5))
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):WalkTo(SymPos("P01_PARTNER"), Speed(1.5))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("HERO"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitMove()
  CH("PARTNER"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  CH("HERO"):SetNeckRot(RotateTarget(0), RotateTarget(20), RotateTarget(0), TimeSec(0.2))
  CH("HERO"):WaitRotate()
  CH("PARTNER"):SetNeckRot(RotateTarget(0), RotateTarget(20), RotateTarget(0), TimeSec(0.2))
  CH("HERO"):WaitNeckRot()
  CH("HERO"):DirLockToChara(CH("PERIPPAA"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitNeckRot()
  CH("PARTNER"):DirLockToChara(CH("PERIPPAA"))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 1925584824, PARTNER_1 = 1809655545})
  SOUND:PlaySe(SymSnd("SE_EVT_PERIPPAA_FLY_02_LP"), Volume(256))
  CH("PERIPPAA"):RunTo(SymPos("P00_PERIPPAA"), Speed(2.5))
  TASK:Sleep(TimeSec(2))
  SOUND:FadeOutSe(SymSnd("SE_EVT_PERIPPAA_FLY_02_LP"), TimeSec(1))
  WINDOW:CloseMessage()
  CH("PERIPPAA"):WaitMove()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CUT:Load(SymCut("CUT_M06_030_01"))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
  CAMERA:ResetAzimuthDifferenceVolume()
  CH("PERIPPAA"):SetPosition(SymPos("P03_PERIPPAA"))
  CH("PERIPPAA"):RunTo(SymPos("P04_PERIPPAA"), Speed(2.5))
  GM("GOUGAI_S"):SetVisible(true)
  GM("GOUGAI_S02"):SetVisible(true)
  GM("GOUGAI_S03"):SetVisible(true)
  GM("GOUGAI_S04"):SetVisible(true)
  GM("GOUGAI_S05"):SetVisible(true)
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SOUND:PlaySe(SymSnd("SE_EVT_PERIPPAA_FLY_02_LP"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  TASK:Sleep(TimeSec(2))
  SOUND:FadeOutSe(SymSnd("SE_EVT_PERIPPAA_FLY_02_LP"), TimeSec(1.5))
  CH("PERIPPAA"):WaitMove()
  CH("PERIPPAA"):SetVisible(false)
  CH("HERO"):DirLockOff()
  CH("PARTNER"):DirLockOff()
  TASK:Sleep(TimeSec(0.5))
  CH("PARTNER"):ResetNeckRot(TimeSec(0.2))
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):ResetNeckRot(TimeSec(0.2))
  CH("PARTNER"):WaitNeckRot()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 1089500474, PARTNER_1 = 1508590715})
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Regist(subEveMoveDir, {
    CH("PARTNER"),
    SymPos("P02_PARTNER"),
    Speed(1.5),
    RotateTarget(90)
  })
  TASK:Sleep(TimeSec(0.3))
  subEveMoveDir(CH("HERO"), SymPos("P02_HERO"), Speed(1.5), RotateTarget(-90))
  TASK:Sleep(TimeSec(0.3))
  CH("PARTNER"):MoveTo(SymPos("P03_PARTNER"), Speed(1.5), LINK_DIR.OFF)
  CH("PARTNER"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_HAND"), Volume(256))
  GM("GOUGAI_S"):SetVisible(false)
  TASK:Sleep(TimeSec(0.3))
  CH("PARTNER"):MoveTo(SymPos("P04_PARTNER"), Speed(1.5), LINK_DIR.OFF)
  CH("PARTNER"):WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 380293820, PARTNER_1 = 263316477})
  subEveCloseMsg()
  WINDOW:SysMsg(614248510)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:SwitchTalk({PARTNER_0 = 1032290687, PARTNER_1 = -1172333136})
  WINDOW:SwitchTalk({PARTNER_0 = -1559974671, PARTNER_1 = -1980985128})
  WINDOW:SwitchTalk({PARTNER_0 = -1862819431, PARTNER_1 = -1143279014})
  WINDOW:SwitchTalk({PARTNER_0 = -1564359909, PARTNER_1 = -310356516})
  WINDOW:SwitchTalk({PARTNER_0 = -191142755, PARTNER_1 = -541706402})
  WINDOW:SwitchTalk({PARTNER_0 = -961739233, PARTNER_1 = 1093999312})
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.THINK)
  WINDOW:SwitchTalk({PARTNER_0 = 1479420817, PARTNER_1 = -1688649930})
  WINDOW:SwitchTalk({PARTNER_0 = -2109600137, PARTNER_1 = -1452319308})
  WINDOW:SwitchTalk({PARTNER_0 = -1334547211, PARTNER_1 = -13239758})
  WINDOW:SwitchTalk({PARTNER_0 = -433140877, PARTNER_1 = -855402320})
  WINDOW:SwitchTalk({PARTNER_0 = -736581135, PARTNER_1 = 1400943934})
  WINDOW:SwitchTalk({PARTNER_0 = 1251705983, PARTNER_1 = 602232915})
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  CAMERA:ResetAzimuthDifferenceVolume()
  FLAG.SceneFlag = CONST.FL_SC_01_FIRST
  FLAG.SCENARIOFLAG = CONST.M06_KYOUKAIKARANOSHIRASE_END
  FLAG.MapFlags = CONST.MAP_EVENT
  FLAG.FreePlay = CONST.FLAG_TRUE
  FLAG.TrigNextEvent = CONST.FLAG_FALSE
  SYSTEM:NextEntry()
end
function main06_kyoukaikaranoshirase01_end()
end
function groundEnd()
end

