dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main13_genoueakandouclear1st01_init()
  subEveFromProgFadeSet()
  if FLAG.NowResumeFlag == CONST.FLAG_FALSE then
    subComResultClear()
  end
  SYSTEM:UpdateNextDayParameter()
  FLAG.SceneFlag = CONST.FL_SC_03_END
  FLAG.SCENARIOFLAG = CONST.M13_GENOUEAKANDOUCLEAR1ST_START
  SYSTEM:NextEntry()
end
function main13_genoueakandouclear1st01_start()
  -- subEveFromProgFadeSet()
  -- FLAG.SCENARIOFLAG = CONST.M13_GENOUEAKANDOUCLEAR1ST_START
  -- if FLAG.NowResumeFlag == CONST.FLAG_FALSE then
  --   subComResultClear()
    -- TASK:Sleep(TimeSec(0.2))
    -- if Ground_Save(ground) then
    --   return
    -- end
  -- end
  -- SYSTEM:UpdateNextDayParameter()
  -- TASK:Sleep(TimeSec(1))
  -- TASK:Sleep(TimeSec(0.5))
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.THINK)
  -- WINDOW:SwitchTalk({PARTNER_0 = -724393664, PARTNER_1 = -842428415})
  -- WINDOW:SwitchTalk({PARTNER_0 = -421215294, PARTNER_1 = -3453})
  -- WINDOW:SwitchTalk({PARTNER_0 = -1329699772, PARTNER_1 = -1448782587})
  -- WINDOW:SwitchTalk({PARTNER_0 = -2105014586, PARTNER_1 = -1684850809})
  -- WINDOW:CloseMessage()
  -- SOUND:PlaySe(SymSnd("SE_EVT_FOOT_STEP_01_LP"), Volume(256))
  -- TASK:Sleep(TimeSec(1.5))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- GM("WARABED_NIGHT_01"):SetVisible(false)
  -- GM("WARABED_NIGHT_02"):SetVisible(false)
  -- GM("TAKIBI_ON"):SetVisible(false)
  -- SOUND:FadeInEnv(SymSnd("SE_ENV_FOREST_NIGHT_LP"), TimeSec(0.5), Volume(256))
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- CH("HERO"):RunTo(SplinePath(SymPos("P00_5_HERO"), SymPos("P01_HERO")), Speed(2))
  -- CH("PARTNER"):RunTo(SplinePath(SymPos("P00_5_PARTNER"), SymPos("P01_PARTNER")), Speed(2))
  -- SOUND:FadeOutSe(SymSnd("SE_EVT_FOOT_STEP_01_LP"), TimeSec(1.5))
  -- TASK:Sleep(TimeSec(1.5))
  -- CAMERA:MoveFollow(SymCam("CAMERA_01"), Speed(2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- CH("PARTNER"):WaitMove()
  -- CAMERA:WaitMove()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_01"), Volume(256))
  -- CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  -- CH("PARTNER"):WaitManpu()
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  -- WINDOW:SwitchTalk({PARTNER_0 = 470494024, PARTNER_1 = 84941321})
  -- WINDOW:CloseMessage()
  -- subEveLookAround(CH("PARTNER"), Speed(500))
  -- TASK:Sleep(TimeSec(0.2))
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  -- WINDOW:SwitchTalk({PARTNER_0 = 2005617600, PARTNER_1 = 1854962305})
  -- WINDOW:CloseMessage()
  -- CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.3))
  -- CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  -- CH("PARTNER"):WaitRotate()
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.THINK)
  -- WINDOW:SwitchTalk({PARTNER_0 = 1170024770, PARTNER_1 = 1554388995})
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(3.5))
  -- CAMERA:SetEye(SymCam("CAMERA_02"))
  -- CAMERA:SetTgt(SymCam("CAMERA_02"))
  -- CH("HERO"):DirTo(RotateTarget(-60), Speed(200), ROT_TYPE.NEAR)
  -- CH("HERO"):WaitRotate()
  -- WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.NORMAL)
  -- WINDOW:Monologue(333942468)
  -- WINDOW:Monologue(184336261)
  -- WINDOW:Monologue(567405638)
  -- WINDOW:Monologue(952818951)
  -- WINDOW:Monologue(-1085095480)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_01"))
  -- CAMERA:SetTgt(SymCam("CAMERA_01"))
  -- TASK:Sleep(TimeSec(0.3))
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  -- WINDOW:SwitchTalk({PARTNER_0 = -1505103735, PARTNER_1 = 1698620462})
  -- CH("HERO"):DirTo(CH("PARTNER"), Speed(200), ROT_TYPE.NEAR)
  -- WINDOW:SwitchTalk({PARTNER_0 = 2082854255, PARTNER_1 = 1460176556})
  -- WINDOW:CloseMessage()
  -- subEveLookAround02(CH("PARTNER"), Speed(500))
  -- TASK:Sleep(TimeSec(0.2))
  -- CH("PARTNER"):DirTo(RotateTarget(90), Speed(350), ROT_TYPE.NEAR)
  -- CH("PARTNER"):WaitRotate()
  -- TASK:Sleep(TimeSec(0.5))
  -- CAMERA:SetEye(SymCam("CAMERA_02_5"))
  -- CAMERA:SetTgt(SymCam("CAMERA_02_5"))
  -- CH("HERO"):DirTo(RotateTarget(90), Speed(350), ROT_TYPE.NEAR)
  -- CH("HERO"):WaitRotate()
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  -- WINDOW:SwitchTalk({PARTNER_0 = 1309915117, PARTNER_1 = 22159658})
  -- WINDOW:CloseMessage()
  -- CAMERA:SetEye(SymCam("CAMERA_01"))
  -- CAMERA:SetTgt(SymCam("CAMERA_01"))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  -- CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  -- CH("PARTNER"):WaitManpu()
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SAD)
  -- WINDOW:SwitchTalk({PARTNER_0 = 407441515, PARTNER_1 = 862208936})
  -- WINDOW:KeyWait()
  -- CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  -- WINDOW:SwitchTalk({PARTNER_0 = 712995561, PARTNER_1 = -1377341914})
  -- WINDOW:CloseMessage()
  -- CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  -- CH("PARTNER"):WaitRotate()
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  -- WINDOW:SwitchTalk({PARTNER_0 = -1258528921, PARTNER_1 = -578649269})
  -- WINDOW:CloseMessage()
  -- SOUND:FadeOutEnv(TimeSec(2))
  -- subEveNod(CH("HERO"))
  -- SCREEN_A:FadeOut(TimeSec(1), true)
  -- GM("WARABED_NIGHT_01"):SetVisible(true)
  -- GM("WARABED_NIGHT_02"):SetVisible(true)
  -- GM("TAKIBI_ON"):SetVisible(true)
  -- EFFECT:Create("effectFire", SymEff("EV_FIRE_LP"))
  -- EFFECT:SetPosition("effectFire", SymPos("P_EFF_FIRE"))
  -- EFFECT:Play("effectFire")
  -- CH("HERO"):SetPosition(SymPos("P02_HERO"))
  -- CH("PARTNER"):SetPosition(SymPos("P02_PARTNER"))
  -- CH("HERO"):SetDir(RotateTarget(45))
  -- CH("PARTNER"):SetDir(RotateTarget(-135))
  -- TASK:Sleep(TimeSec(2))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_03"))
  -- CAMERA:SetTgt(SymCam("CAMERA_03"))
  -- SOUND:PlayBgm(SymSnd("BGM_EVE_NAZO_02"), Volume(256))
  -- SOUND:FadeInEnv(SymSnd("SE_EVT_BONFIRE_LP"), TimeSec(0.5), Volume(64))
  -- SCREEN_A:FadeIn(TimeSec(1), true)
  -- TASK:Regist(subEveLookAround02, {
  --   CH("PARTNER"),
  --   Speed(500)
  -- })
  -- TASK:Sleep(TimeSec(0.3))
  -- CH("HERO"):SetMotion(SymMot("EV001_CONFIRMS"), LOOP.OFF)
  -- CH("HERO"):WaitPlayMotion()
  -- CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  -- TASK:WaitTask()
  -- WINDOW:DrawFaceF(20, 88, SymAct("PARTNER"), FACE_TYPE.SAD)
  -- WINDOW:SwitchTalk({PARTNER_0 = -996560374, PARTNER_1 = -273358391})
  -- WINDOW:CloseMessage()
  -- CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.2))
  -- CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  -- CH("PARTNER"):WaitRotate()
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.THINK)
  -- WINDOW:SwitchTalk({PARTNER_0 = -156249976, PARTNER_1 = -1175566769})
  -- WINDOW:SwitchTalk({PARTNER_0 = -1594525938, PARTNER_1 = -1948769075})
  -- WINDOW:SwitchTalk({PARTNER_0 = -1832708724, PARTNER_1 = 358287683})
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.THINK)
  -- WINDOW:Monologue(205535234)
  -- WINDOW:Monologue(1079360498)
  -- WINDOW:Monologue(1498319539)
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SAD)
  -- WINDOW:SwitchTalk({PARTNER_0 = 1919146352, PARTNER_1 = 1803085873})
  -- WINDOW:CloseMessage()
  -- CH("PARTNER"):DirTo(RotateTarget(45), Speed(350), ROT_TYPE.NEAR)
  -- CH("PARTNER"):WaitRotate()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  -- CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  -- CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.PAIN)
  -- WINDOW:SwitchTalk({PARTNER_0 = 607747830, PARTNER_1 = 1025658807})
  -- WINDOW:KeyWait()
  -- CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SAD)
  -- WINDOW:SwitchTalk({PARTNER_0 = 370089076, PARTNER_1 = 252980533})
  -- WINDOW:CloseMessage()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  -- CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  -- CH("PARTNER"):WaitManpu()
  -- CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  -- CH("PARTNER"):WaitRotate()
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  -- WINDOW:SwitchTalk({PARTNER_0 = -2004078086, PARTNER_1 = -1852374853})
  -- WINDOW:SwitchTalk({PARTNER_0 = -118891369, PARTNER_1 = -504173098})
  -- WINDOW:CloseMessage()
  -- CH("PARTNER"):DirTo(RotateTarget(45), Speed(350), ROT_TYPE.NEAR)
  -- CH("PARTNER"):WaitRotate()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  -- CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  -- CH("PARTNER"):WaitManpu()
  -- CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.PAIN)
  -- WINDOW:SwitchTalk({PARTNER_0 = -891306475, PARTNER_1 = -742092972})
  -- WINDOW:CloseMessage()
  -- CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  -- CH("PARTNER"):WaitRotate()
  -- CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SAD)
  -- WINDOW:SwitchTalk({PARTNER_0 = -1668998765, PARTNER_1 = -2053232430})
  -- WINDOW:CloseMessage()
  -- SOUND:FadeOutBgm(TimeSec(2.5))
  -- SOUND:FadeOutEnv(TimeSec(2.5))
  -- subEveNod(CH("HERO"))
  -- SCREEN_A:FadeOut(TimeSec(1.5), true)
  -- TASK:Sleep(TimeSec(1))
  -- MAP:SetBG(SymMap("IM05_03_SKY_NIGHT"))
  -- MAP:SetVisible(false)
  -- MAP:SetVisibleBG(true)
  -- CH("HERO"):SetVisible(false)
  -- CH("PARTNER"):SetVisible(false)
  -- GM("WARABED_NIGHT_01"):SetVisible(false)
  -- GM("WARABED_NIGHT_02"):SetVisible(false)
  -- GM("TAKIBI_ON"):SetVisible(false)
  -- EFFECT:Remove("effectFire")
  -- SCREEN_A:FadeIn(TimeSec(1), true)
  -- TASK:Sleep(TimeSec(2))
  -- SCREEN_A:FadeOut(TimeSec(1), true)
  -- MAP:SetVisible(true)
  -- MAP:SetVisibleBG(false)
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(3.5))
  -- CAMERA:SetEye(SymCam("CAMERA_04"))
  -- CAMERA:SetTgt(SymCam("CAMERA_04"))
  -- CH("HERO"):SetDir(RotateTarget(-45))
  -- CH("PARTNER"):SetDir(RotateTarget(45))
  -- CH("HERO"):SetMotion(SymMot("EV001_SLEEP01"), LOOP.ON, TimeSec(0))
  -- CH("PARTNER"):SetMotion(SymMot("EV001_SLEEP01"), LOOP.ON, TimeSec(0))
  -- CH("HERO"):SetVisible(true)
  -- CH("PARTNER"):SetVisible(true)
  -- GM("WARABED_NIGHT_01"):SetVisible(true)
  -- GM("WARABED_NIGHT_02"):SetVisible(true)
  -- GM("TAKIBI_ON"):SetVisible(true)
  -- CH("PARTNER"):SetEyeMotion(EYE_MOTION.CLOSE)
  -- CH("HERO"):SetEyeMotion(EYE_MOTION.CLOSE)
  -- TASK:Sleep(TimeSec(0.5))
  -- SOUND:FadeInEnv(SymSnd("SE_ENV_FOREST_NIGHT_LP"), TimeSec(0.5), Volume(256))
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- TASK:Sleep(TimeSec(1))
  -- CH("HERO"):SetShake(Vector(0.005, 0, 0), TimeSec(0.1, TIME_TYPE.FRAME))
  -- TASK:Sleep(TimeSec(0.5))
  -- CH("HERO"):ResetShake()
  -- WINDOW:Monologue(-1363969263)
  -- WINDOW:CloseMessage()
  -- SOUND:FadeOutEnv(TimeSec(1.5))
  -- SCREEN_A:FadeOut(TimeSec(1), true)
  -- FLAG.SceneFlag = CONST.FL_SC_01_END
  -- FLAG.SCENARIOFLAG = CONST.M13_GENOUEAKANDOUCLEAR1ST_START
  -- SYSTEM:NextEntry()
end
function main13_genoueakandouclear1st01_end()
end
function main13_genoueakandouclear1st02_init()
end
function main13_genoueakandouclear1st02_start()
  -- SYSTEM:UpdateNextDayParameter()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- EFFECT:StartMotionBlur(0.04, 0.9, 0)
  -- CH("MUNNA"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  -- SOUND:FadeInBgm(SymSnd("SE_EVT_KOWASUGINAI_LP"), TimeSec(0.5), Volume(256))
  -- SCREEN_A:FadeIn(TimeSec(1.5), true)
  -- SOUND:PlayEnv(SymSnd("SE_EVT_VOICEWAVE_M_LP"), Volume(64))
  -- EFFECT:Create("effectWaveSmall", SymEff("EV_WAVE_SMALL"))
  -- EFFECT:SetPosition("effectWaveSmall", SymPos("P_EFFECT_WAVE_SMALL"))
  -- EFFECT:Play("effectWaveSmall")
  -- WINDOW:Talk(SymAct("???"), -1213707696)
  -- EFFECT:Wait("effectWaveSmall")
  -- WINDOW:KeyWait()
  -- SOUND:VolumeEnv(Volume(256), TimeSec(1))
  -- EFFECT:Create("effectWaveLp", SymEff("EV_WAVE_LP"))
  -- EFFECT:SetPosition("effectWaveLp", SymPos("P_EFFECT_WAVE_LP"))
  -- EFFECT:Play("effectWaveLp")
  -- WINDOW:Talk(SymAct("???"), 808474271)
  -- WINDOW:Talk(SymAct("???"), 690710494)
  -- WINDOW:CloseMessage()
  -- EFFECT:Remove("effectWaveLp")
  -- SOUND:FadeOutEnv(TimeSec(1))
  -- SOUND:PlaySe(SymSnd("SE_EVT_MUNNA_APPEAR"), Volume(256))
  -- CH("MUNNA"):ChangeColor(Color(1, 1, 1, 1), TimeSec(15, TIME_TYPE.FRAME))
  -- TASK:Sleep(TimeSec(0.5))
  -- WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  -- WINDOW:Monologue(-363039879)
  -- WINDOW:Monologue(-213433800)
  -- WINDOW:Monologue(-664137221)
  -- subEveCloseMsg()
  -- SOUND:PlayEnv(SymSnd("SE_EVT_VOICEWAVE_M_LP"), Volume(128))
  -- EFFECT:Create("effectWaveLp", SymEff("EV_WAVE_LP"))
  -- EFFECT:SetPosition("effectWaveLp", SymPos("P_EFFECT_WAVE_LP"))
  -- EFFECT:Play("effectWaveLp")
  -- WINDOW:Talk(SymAct("MUNNA"), -1049550662)
  -- WINDOW:KeyWait()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  -- CH("MUNNA"):SetManpu("MP_FLY_SWEAT")
  -- CH("MUNNA"):SetFacialMotion(FACIAL_MOTION.TEARS)
  -- WINDOW:Talk(SymAct("MUNNA"), -1909410179)
  -- WINDOW:CloseMessage()
  -- SOUND:VolumeEnv(Volume(64), TimeSec(1))
  -- EFFECT:Remove("effectWaveLp")
  -- TASK:Sleep(TimeSec(0.2))
  -- WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.NORMAL)
  -- WINDOW:Monologue(-1758755012)
  -- subEveCloseMsg()
  -- SOUND:VolumeEnv(Volume(128), TimeSec(0.5))
  -- EFFECT:Create("effectWaveLp", SymEff("EV_WAVE_LP"))
  -- EFFECT:SetPosition("effectWaveLp", SymPos("P_EFFECT_WAVE_LP"))
  -- EFFECT:Play("effectWaveLp")
  -- CH("MUNNA"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  -- WINDOW:Talk(SymAct("MUNNA"), -1140402945)
  -- WINDOW:Talk(SymAct("MUNNA"), -1524767298)
  -- WINDOW:KeyWait()
  -- CH("MUNNA"):SetFacialMotion(FACIAL_MOTION.PAIN)
  -- WINDOW:Talk(SymAct("MUNNA"), 579205489)
  -- WINDOW:Talk(SymAct("MUNNA"), 1000261680)
  -- WINDOW:Talk(SymAct("MUNNA"), 1390416924)
  -- WINDOW:KeyWait()
  -- SOUND:FadeOutEnv(TimeSec(0.5))
  -- WINDOW:Talk(SymAct("MUNNA"), 1274750301)
  -- TASK:Sleep(TimeSec(0.3))
  -- WINDOW:ForceCloseMessage()
  -- EFFECT:Remove("effectWaveLp")
  -- CH("MUNNA"):SetVisible(false)
  -- EFFECT:Create("effectWaveEnd", SymEff("EV_WAVE_END"))
  -- EFFECT:SetPosition("effectWaveEnd", SymPos("P_EFFECT_WAVE_END"))
  -- EFFECT:Play("effectWaveEnd")
  -- TASK:Sleep(TimeSec(0.25))
  -- SOUND:PlaySe(SymSnd("SE_EVT_VOICEWAVE_STOP"))
  -- TASK:Sleep(TimeSec(1.5))
  -- WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  -- WINDOW:Monologue(1624667806)
  -- WINDOW:Monologue(2043496415)
  -- WINDOW:CloseMessage()
  -- SOUND:FadeOutBgm(TimeSec(0.2))
  -- SCREEN_A:FadeOut(TimeSec(0.05), true)
  -- EFFECT:EndMotionBlur()
  FLAG.SceneFlag = CONST.FL_SC_02_END
  FLAG.SCENARIOFLAG = CONST.M13_GENOUEAKANDOUCLEAR1ST_START
  SYSTEM:NextEntry()
end
function main13_genoueakandouclear1st02_end()
end
function main13_genoueakandouclear1st03_init()
end
function main13_genoueakandouclear1st03_start()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- CH("HERO"):SetDir(RotateTarget(-45))
  -- CH("PARTNER"):SetDir(RotateTarget(45))
  -- CH("HERO"):SetMotion(SymMot("EV001_SLEEP01"), LOOP.ON, TimeSec(0))
  -- CH("PARTNER"):SetMotion(SymMot("EV001_SLEEP01"), LOOP.ON, TimeSec(0))
  -- SOUND:PlaySe(SymSnd("SE_EVT_DOSU"), Volume(256))
  -- SOUND:PlayEnv(SymSnd("SE_ENV_FOREST_NIGHT_LP"), Volume(256))
  -- SCREEN_A:FadeIn(TimeSec(0), true)
  -- CAMERA:SetShake(Vector2(0.05, 0.05), TimeSec(3, TIME_TYPE.FRAME))
  -- CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(10, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- CH("HERO"):SetMotion(SymMot("EV013_WAKEUP"), LOOP.OFF)
  -- TASK:Sleep(TimeSec(0.3))
  -- CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  -- CH("HERO"):WaitPlayMotion()
  -- CH("HERO"):SetMotion(SymMot("EV013_TIRED"), LOOP.ON)
  -- WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  -- WINDOW:Monologue(915198232)
  -- WINDOW:CloseMessage()
  -- CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.3))
  -- TASK:Sleep(TimeSec(1))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_02"))
  -- CAMERA:SetTgt(SymCam("CAMERA_02"))
  -- CH("HERO"):DirTo(CH("PARTNER"), Speed(200), ROT_TYPE.NEAR)
  -- CH("HERO"):WaitRotate()
  -- TASK:Sleep(TimeSec(0.3))
  -- CH("HERO"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  -- WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.DECIDE)
  -- WINDOW:Monologue(798482521)
  -- WINDOW:CloseMessage()
  -- CH("HERO"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  -- CAMERA:MoveFollow(SymCam("CAMERA_03"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- local pokemonIndexHero = SymAct("HERO"):GetIndex()
  -- if pokemonIndexHero == 42 then
  --   CH("HERO"):WalkTo(SymPos("P01_HERO_POKABU"), Speed(1.5))
  -- else
  --   CH("HERO"):WalkTo(SymPos("P01_HERO"), Speed(1.5))
  -- end
  -- CH("HERO"):WaitMove()
  -- CH("HERO"):SetMotion(SymMot("EV013_START"), LOOP.ON)
  -- TASK:Sleep(TimeSec(1))
  -- CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  -- TASK:Sleep(TimeSec(0.3))
  -- CH("HERO"):WalkTo(SymPos("P02_HERO"), Speed(1.5), LINK_DIR.OFF)
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2.5))
  -- CAMERA:SetEye(SymCam("CAMERA_04"))
  -- CAMERA:SetTgt(SymCam("CAMERA_04"))
  -- CAMERA:SetShake(Vector2(0.05, 0.05), TimeSec(3, TIME_TYPE.FRAME))
  -- CAMERA:MoveFollow2(SymCam("CAMERA_05"), Speed(10, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- SOUND:PlaySe(SymSnd("SE_EVT_DOSU"), Volume(256))
  -- CH("PARTNER"):SetMotion(SymMot("EV013_WAKEUP"), LOOP.OFF)
  -- CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  -- WINDOW:SwitchTalk({PARTNER_0 = 79344538, PARTNER_1 = 497124059})
  -- CH("PARTNER"):WaitPlayMotion()
  -- CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  -- CH("PARTNER"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  -- WINDOW:CloseMessage()
  -- local taskPartner00 = function()
  --   SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  --   CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  --   CH("PARTNER"):DirTo(RotateTarget(135), Speed(600), ROT_TYPE.NEAR)
  --   CH("PARTNER"):WaitRotate()
  --   CH("PARTNER"):DirTo(RotateTarget(0), Speed(600), ROT_TYPE.NEAR)
  --   CH("PARTNER"):WaitRotate()
  --   CH("PARTNER"):DirTo(CH("HERO"), Speed(600), ROT_TYPE.NEAR)
  --   CH("PARTNER"):WaitRotate()
  -- end
  -- taskPartner00()
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  -- WINDOW:SwitchTalk({PARTNER_0 = -1707500012, PARTNER_1 = -2094878891})
  -- WINDOW:KeyWait()
  -- CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  -- SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  -- TASK:Regist(subEveDoubleJump, {
  --   CH("PARTNER")
  -- })
  -- WINDOW:SwitchTalk({PARTNER_0 = 176358474, PARTNER_1 = 328742155})
  -- TASK:WaitTask()
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_06"))
  -- CAMERA:SetTgt(SymCam("CAMERA_06"))
  -- TASK:Sleep(TimeSec(0.5))
  -- CH("PARTNER"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  -- CH("PARTNER"):WaitRotate()
  -- TASK:Sleep(TimeSec(0.5))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  -- CH("PARTNER"):SetMotion(SymMot("EV001_CONFIRMS"), LOOP.OFF)
  -- TASK:Sleep(TimeSec(0.5))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  -- CH("PARTNER"):WaitPlayMotion()
  -- CH("PARTNER"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  -- TASK:Sleep(TimeSec(0.5))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  -- CH("PARTNER"):SetManpu("MP_QUESTION")
  -- CH("PARTNER"):WaitManpu()
  -- WINDOW:DrawFaceF(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  -- WINDOW:SwitchTalk({PARTNER_0 = 951412424, PARTNER_1 = 565073801})
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_02"))
  -- CAMERA:SetTgt(SymCam("CAMERA_02"))
  -- CH("PARTNER"):DirTo(CH("HERO"), Speed(500), ROT_TYPE.NEAR)
  -- CH("PARTNER"):WaitRotate()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  -- CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  -- WINDOW:SwitchTalk({PARTNER_0 = 1861206350, PARTNER_1 = 2012540943})
  -- WINDOW:KeyWait()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  -- CH("PARTNER"):SetManpu("MP_QUESTION")
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.THINK)
  -- WINDOW:SwitchTalk({PARTNER_0 = 1557767116, PARTNER_1 = 1170379405})
  -- WINDOW:SwitchTalk({PARTNER_0 = -1034252734, PARTNER_1 = -616448253})
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(3.5))
  -- CAMERA:SetEye(SymCam("CAMERA_07"))
  -- CAMERA:SetTgt(SymCam("CAMERA_07"))
  -- TASK:Sleep(TimeSec(0.3))
  -- CH("HERO"):SetMotion(SymMot("SPEAK"), LOOP.OFF)
  -- CH("HERO"):WaitPlayMotion()
  -- CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  -- TASK:Sleep(TimeSec(0.3))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  -- CAMERA:SetEye(SymCam("CAMERA_07_5"))
  -- CAMERA:SetTgt(SymCam("CAMERA_07_5"))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  -- CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  -- CH("PARTNER"):WaitManpu()
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  -- WINDOW:SwitchTalk({PARTNER_0 = -1304468689, PARTNER_1 = -1423682962})
  -- WINDOW:SwitchTalk({PARTNER_0 = -2146893395, PARTNER_1 = -1726861076})
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(3.5))
  -- CAMERA:SetEye(SymCam("CAMERA_07"))
  -- CAMERA:SetTgt(SymCam("CAMERA_07"))
  -- TASK:Sleep(TimeSec(0.3))
  -- CH("HERO"):SetMotion(SymMot("SPEAK"), LOOP.OFF)
  -- CH("HERO"):WaitPlayMotion()
  -- CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  -- TASK:Sleep(TimeSec(0.3))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  -- CAMERA:SetEye(SymCam("CAMERA_07_5"))
  -- CAMERA:SetTgt(SymCam("CAMERA_07_5"))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  -- CH("PARTNER"):SetManpu("MP_SHOCK_R")
  -- CH("PARTNER"):WaitManpu()
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  -- WINDOW:SwitchTalk({PARTNER_0 = -699161045, PARTNER_1 = -817326230})
  -- WINDOW:SwitchTalk({PARTNER_0 = -463092567, PARTNER_1 = -42011160})
  -- WINDOW:KeyWait()
  -- CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  -- TASK:Regist(subEveNod, {
  --   CH("PARTNER")
  -- })
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  -- WINDOW:SwitchTalk({PARTNER_0 = 2061953319, PARTNER_1 = 1677580390})
  -- WINDOW:SwitchTalk({PARTNER_0 = -1268048687, PARTNER_1 = -1385157232})
  -- WINDOW:SwitchTalk({PARTNER_0 = -2040693165, PARTNER_1 = -1622782190})
  -- WINDOW:CloseMessage()
  -- SOUND:FadeOutEnv(TimeSec(3))
  -- subEveNod(CH("HERO"))
  -- SCREEN_A:FadeOut(TimeSec(1), true)
  -- subEveFadeAfterTime()
  -- CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  FLAG.SceneFlag = CONST.FL_SC_03_END
  FLAG.SCENARIOFLAG = CONST.M13_GENOUEAKANDOUCLEAR1ST_START
  SYSTEM:NextEntry()
end
function main13_genoueakandouclear1st03_end()
end
function main13_genoueakandouclear1st04_init()
end
function main13_genoueakandouclear1st04_start()
  -- yep, UpdateNextDayParameter() gets called twice. that is what the original game does, so i'm keeping it
  SYSTEM:UpdateNextDayParameter()
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HERO"):SetPosition(SymPos("P01_HERO"))
  CH("PARTNER"):SetPosition(SymPos("P01_PARTNER"))
  CH("HERO"):SetDir(CH("PARTNER"))
  CH("PARTNER"):SetDir(CH("HERO"))
  SOUND:PlayBgm(SymSnd("BGM_DUN_08"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- TASK:Regist(subEveMoveDir, {
  --   CH("PARTNER"),
  --   SymPos("P01_PARTNER"),
  --   Speed(2),
  --   CH("HERO")
  -- })
  -- TASK:Regist(subEveMoveDir, {
  --   CH("HERO"),
  --   SymPos("P01_HERO"),
  --   Speed(2),
  --   CH("PARTNER")
  -- })
  -- TASK:WaitTask()
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  -- WINDOW:SwitchTalk({PARTNER_0 = -804791851, PARTNER_1 = -920852332})
  -- WINDOW:SwitchTalk({PARTNER_0 = -500057257, PARTNER_1 = -81098218})
  -- WINDOW:SwitchTalk({PARTNER_0 = 2092078809, PARTNER_1 = 1705617304})
  -- WINDOW:CloseMessage()
  -- subEveNod(CH("HERO"))
  -- CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  -- WINDOW:SwitchTalk({PARTNER_0 = 215448500, PARTNER_1 = 365710069})
  -- WINDOW:SwitchTalk({PARTNER_0 = 1054939446, PARTNER_1 = 670705783})
  -- WINDOW:CloseMessage()
  -- CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  CAMERA:MoveToHero(Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  FLAG.SceneFlag = CONST.FL_SC_01_FIRST
  FLAG.SCENARIOFLAG = CONST.M13_GENOUEAKANDOUCLEAR1ST_END
  FLAG.MapFlags = CONST.MAP_EVENT
  FLAG.FreePlay = CONST.FLAG_TRUE
  FLAG.TrigNextEvent = CONST.FLAG_FALSE
  SYSTEM:NextEntry(KEEP_PLACEMENT.ON)
end
function main13_genoueakandouclear1st04_end()
end
function groundEnd()
end

