dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main12_yumenonakanomunna01_init()
end
function main12_yumenonakanomunna01_start()
  subEveFromProgFadeSet()
  if FLAG.NowResumeFlag == CONST.FLAG_FALSE then
    -- TASK:Sleep(TimeSec(0.2))
    -- if Ground_Save(ground) then
    --   return
    -- end
    -- TASK:Sleep(TimeSec(0.2))
  end
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- MAP:SetBG(SymMap("IM05_03_SKY_NIGHT02"))
  -- MAP:SetVisible(false)
  -- MAP:SetVisibleBG(true)
  -- CH("HERO"):SetVisible(false)
  -- CH("PARTNER"):SetVisible(false)
  -- GM("WARABED_NIGHT_01"):SetVisible(false)
  -- GM("WARABED_NIGHT_02"):SetVisible(false)
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- TASK:Sleep(TimeSec(2))
  -- SCREEN_A:FadeOut(TimeSec(1), true)
  -- MAP:SetVisible(true)
  -- MAP:SetVisibleBG(false)
  -- CH("HERO"):SetDir(RotateTarget(-45))
  -- CH("PARTNER"):SetDir(RotateTarget(45))
  -- CH("HERO"):SetMotion(SymMot("EV001_SLEEP01"), LOOP.ON, TimeSec(0))
  -- CH("PARTNER"):SetMotion(SymMot("EV001_SLEEP01"), LOOP.ON, TimeSec(0))
  -- CH("HERO"):SetVisible(true)
  -- CH("PARTNER"):SetVisible(true)
  -- GM("WARABED_NIGHT_01"):SetVisible(true)
  -- GM("WARABED_NIGHT_02"):SetVisible(true)
  -- TASK:Sleep(TimeSec(0.5))
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- TASK:Sleep(TimeSec(2))
  -- SCREEN_A:FadeOut(TimeSec(1), true)
  FLAG.SceneFlag = CONST.FL_SC_01_END
  FLAG.SCENARIOFLAG = CONST.M12_YUMENONAKANOMUNNA_START
  SYSTEM:NextEntry()
end
function main12_yumenonakanomunna01_end()
end
function main12_yumenonakanomunna02_init()
end
function main12_yumenonakanomunna02_start()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- EFFECT:StartMotionBlur(0.04, 0.9, 0)
  -- CH("MUNNA"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  -- SOUND:FadeInBgm(SymSnd("SE_EVT_KOWASUGINAI_LP"), TimeSec(0.5), Volume(256))
  -- SCREEN_A:FadeIn(TimeSec(1.5), true)
  -- local taskHakei01 = function()
  --   SOUND:PlaySe(SymSnd("SE_EVT_VOICEWAVE_S"))
  --   EFFECT:Create("effectWaveSmall", SymEff("EV_WAVE_SMALL"))
  --   EFFECT:SetPosition("effectWaveSmall", SymPos("P_EFFECT_WAVE_SMALL"))
  --   EFFECT:Play("effectWaveSmall")
  --   EFFECT:Wait("effectWaveSmall")
  --   TASK:Sleep(TimeSec(1))
  --   EFFECT:Create("effectWaveSmall", SymEff("EV_WAVE_SMALL"))
  --   EFFECT:SetPosition("effectWaveSmall", SymPos("P_EFFECT_WAVE_SMALL"))
  --   EFFECT:Play("effectWaveSmall")
  --   EFFECT:Wait("effectWaveSmall")
  --   EFFECT:Create("effectWaveSmall", SymEff("EV_WAVE_SMALL"))
  --   EFFECT:SetPosition("effectWaveSmall", SymPos("P_EFFECT_WAVE_SMALL"))
  --   EFFECT:Play("effectWaveSmall")
  --   EFFECT:Wait("effectWaveSmall")
  -- end
  -- TASK:Regist(taskHakei01)
  -- WINDOW:ExplanationB(-408068759)
  -- WINDOW:ExplanationB(-21599192)
  -- TASK:WaitTask()
  -- subEveCloseMsg()
  -- TASK:Sleep(TimeSec(1))
  -- EFFECT:Create("effectWaveLp", SymEff("EV_WAVE_LP"))
  -- EFFECT:SetPosition("effectWaveLp", SymPos("P_EFFECT_WAVE_LP"))
  -- EFFECT:Play("effectWaveLp")
  -- SOUND:FadeInEnv(SymSnd("SE_EVT_VOICEWAVE_M_LP"), TimeSec(0.5), Volume(128))
  -- WINDOW:Talk(SymAct("???"), -711245845)
  -- WINDOW:Talk(SymAct("???"), -864022870)
  -- WINDOW:CloseMessage()
  -- SOUND:VolumeEnv(Volume(64), TimeSec(1))
  -- EFFECT:Wait("effectWaveLp")
  -- EFFECT:Remove("effectWaveLp")
  -- WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  -- WINDOW:Monologue(-2084464531)
  -- WINDOW:Monologue(-1696945876)
  -- subEveCloseMsg()
  -- SOUND:VolumeEnv(Volume(128), TimeSec(0.5))
  -- EFFECT:Create("effectWaveLp", SymEff("EV_WAVE_LP"))
  -- EFFECT:SetPosition("effectWaveLp", SymPos("P_EFFECT_WAVE_LP"))
  -- EFFECT:Play("effectWaveLp")
  -- WINDOW:Talk(SymAct("???"), -1309148433)
  -- WINDOW:Talk(SymAct("???"), -1460876370)
  -- WINDOW:Talk(SymAct("???"), 796186465)
  -- WINDOW:CloseMessage()
  -- SOUND:FadeOutEnv(TimeSec(1))
  -- EFFECT:Wait("effectWaveLp")
  -- EFFECT:Remove("effectWaveLp")
  -- TASK:Sleep(TimeSec(0.5))
  -- SOUND:PlaySe(SymSnd("SE_EVT_MUNNA_APPEAR"), Volume(256))
  -- CH("MUNNA"):ChangeColor(Color(1, 1, 1, 1), TimeSec(15, TIME_TYPE.FRAME))
  -- TASK:Sleep(TimeSec(0.5))
  -- WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  -- WINDOW:Monologue(913303072)
  -- WINDOW:Monologue(-2017044125)
  -- WINDOW:CloseMessage()
  -- SOUND:VolumeBgm(Volume(128), TimeSec(0.5))
  -- SCREEN_A:WhiteOut(TimeSec(0.3), true)
  -- EFFECT:EndMotionBlur()
  FLAG.SceneFlag = CONST.FL_SC_02_END
  FLAG.SCENARIOFLAG = CONST.M12_YUMENONAKANOMUNNA_START
  SYSTEM:NextEntry()
end
function main12_yumenonakanomunna02_end()
end
function main12_yumenonakanomunna03_init()
end
function main12_yumenonakanomunna03_start()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- EFFECT:CreateRecollectionFilter()
  -- CUT:Load(SymCut("CUT_M12_060_03"))
  -- CH("MUNNA"):SetShadow(false)
  -- CH("SAZANDORA_H"):SetShadow(false)
  -- CUT:Play()
  -- CUT:Wait()
  -- CUT:Destroy()
  -- CAMERA:SetDefaultGroundFovy()
  -- EFFECT:DestroyRecollectionFilter()
  -- CAMERA:ResetAzimuthDifferenceVolume()
  FLAG.SceneFlag = CONST.FL_SC_03_END
  FLAG.SCENARIOFLAG = CONST.M12_YUMENONAKANOMUNNA_START
  SYSTEM:NextEntry()
end
function main12_yumenonakanomunna03_end()
end
function main12_yumenonakanomunna03_ADV_01()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
end
function main12_yumenonakanomunna04_init()
end
function main12_yumenonakanomunna04_start()
  -- SOUND:PlayBgm(SymSnd("SE_EVT_KOWASUGINAI_LP"), Volume(128))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- SOUND:VolumeBgm(Volume(256), TimeSec(0.5))
  -- EFFECT:StartMotionBlur(0.04, 0.9, 0)
  -- SCREEN_A:WhiteIn(TimeSec(0.5), true)
  -- subEveFadeAfterTime()
  -- WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.NORMAL)
  -- WINDOW:Monologue(-1629657054)
  -- subEveCloseMsg()
  -- SOUND:PlayEnv(SymSnd("SE_EVT_VOICEWAVE_M_LP"), Volume(128))
  -- EFFECT:Create("effectWaveLp", SymEff("EV_WAVE_LP"))
  -- EFFECT:SetPosition("effectWaveLp", SymPos("P_EFFECT_WAVE_LP"))
  -- EFFECT:Play("effectWaveLp")
  -- WINDOW:Talk(SymAct("???"), -1242547231)
  -- WINDOW:CloseMessage()
  -- SOUND:VolumeEnv(Volume(64), TimeSec(1))
  -- EFFECT:Wait("effectWaveLp")
  -- EFFECT:Remove("effectWaveLp")
  -- WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.THINK)
  -- WINDOW:Monologue(-1393882464)
  -- WINDOW:Monologue(-475358105)
  -- subEveCloseMsg()
  -- SOUND:VolumeEnv(Volume(128), TimeSec(0.5))
  -- EFFECT:Create("effectWaveLp", SymEff("EV_WAVE_LP"))
  -- EFFECT:SetPosition("effectWaveLp", SymPos("P_EFFECT_WAVE_LP"))
  -- EFFECT:Play("effectWaveLp")
  -- CH("MUNNA"):SetFacialMotion(FACIAL_MOTION.PAIN)
  -- WINDOW:Talk(SymAct("MUNNA"), -89019098)
  -- WINDOW:CloseMessage()
  -- EFFECT:Wait("effectWaveLp")
  -- EFFECT:Remove("effectWaveLp")
  -- SOUND:VolumeEnv(Volume(64), TimeSec(1))
  -- WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.NORMAL)
  -- WINDOW:Monologue(-778240283)
  -- WINDOW:Monologue(-930623580)
  -- subEveCloseMsg()
  -- SOUND:VolumeEnv(Volume(128), TimeSec(0.5))
  -- EFFECT:Create("effectWaveLp", SymEff("EV_WAVE_LP"))
  -- EFFECT:SetPosition("effectWaveLp", SymPos("P_EFFECT_WAVE_LP"))
  -- EFFECT:Play("effectWaveLp")
  -- WINDOW:Talk(SymAct("MUNNA"), 1327485803)
  -- WINDOW:Talk(SymAct("MUNNA"), 1443160618)
  -- WINDOW:CloseMessage()
  -- EFFECT:Wait("effectWaveLp")
  -- EFFECT:Remove("effectWaveLp")
  -- SOUND:VolumeEnv(Volume(64), TimeSec(1))
  -- WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.THINK)
  -- WINDOW:Monologue(-1787562355)
  -- WINDOW:Monologue(-1939290164)
  -- subEveCloseMsg()
  -- SOUND:VolumeEnv(Volume(128), TimeSec(0.5))
  -- EFFECT:Create("effectWaveLp", SymEff("EV_WAVE_LP"))
  -- EFFECT:SetPosition("effectWaveLp", SymPos("P_EFFECT_WAVE_LP"))
  -- EFFECT:Play("effectWaveLp")
  -- WINDOW:Talk(SymAct("MUNNA"), -1488612337)
  -- WINDOW:Talk(SymAct("MUNNA"), -1101093554)
  -- WINDOW:Talk(SymAct("MUNNA"), -249613431)
  -- WINDOW:Talk(SymAct("MUNNA"), -402390328)
  -- WINDOW:Talk(SymAct("MUNNA"), -1020702453)
  -- WINDOW:Talk(SymAct("MUNNA"), -634232758)
  -- WINDOW:Talk(SymAct("MUNNA"), 1571454085)
  -- WINDOW:Talk(SymAct("MUNNA"), 1152470468)
  -- WINDOW:Talk(SymAct("MUNNA"), 768578024)
  -- WINDOW:Talk(SymAct("MUNNA"), 886349993)
  -- WINDOW:Talk(SymAct("MUNNA"), 536474474)
  -- WINDOW:Talk(SymAct("MUNNA"), 115524139)
  -- WINDOW:Talk(SymAct("MUNNA"), 1235440876)
  -- WINDOW:Talk(SymAct("MUNNA"), 1354261933)
  -- WINDOW:CloseMessage()
  -- SOUND:FadeOutEnv(TimeSec(0.5))
  -- SCREEN_A:FadeOut(TimeSec(0.5), true)
  -- EFFECT:Remove("effectWaveLp")
  -- EFFECT:EndMotionBlur()
  FLAG.SceneFlag = CONST.FL_SC_04_END
  FLAG.SCENARIOFLAG = CONST.M12_YUMENONAKANOMUNNA_START
  SYSTEM:NextEntry()
end
function main12_yumenonakanomunna04_end()
end
function main12_yumenonakanomunna05_init()
end
function main12_yumenonakanomunna05_start()
  -- SOUND:PlayBgm(SymSnd("SE_EVT_KOWASUGINAI_LP"), Volume(256))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- EFFECT:StartMotionBlur(0.04, 0.9, 0)
  -- EFFECT:CreateRecollectionFilter()
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- subEveFadeAfterTime()
  -- SOUND:PlaySe(SymSnd("SE_EVT_VOICEWAVE_M_LP"))
  -- EFFECT:Create("effectWaveLp", SymEff("EV_WAVE_LP"))
  -- EFFECT:SetPosition("effectWaveLp", SymPos("P_EFFECT_WAVE_LP"))
  -- EFFECT:Play("effectWaveLp")
  -- WINDOW:ExplanationB(2073376366)
  -- WINDOW:ExplanationB(1653475119)
  -- WINDOW:ExplanationB(-451535904)
  -- WINDOW:CloseMessage()
  -- SOUND:FadeOutSe(SymSnd("SE_EVT_VOICEWAVE_M_LP"), TimeSec(0.5))
  -- SCREEN_A:FadeOut(TimeSec(0.5), true)
  -- EFFECT:DestroyRecollectionFilter()
  -- EFFECT:Remove("effectWaveLp")
  -- EFFECT:EndMotionBlur()
  FLAG.SceneFlag = CONST.FL_SC_05_END
  FLAG.SCENARIOFLAG = CONST.M12_YUMENONAKANOMUNNA_START
  SYSTEM:NextEntry()
end
function main12_yumenonakanomunna05_end()
end
function main12_yumenonakanomunna06_init()
end
function main12_yumenonakanomunna06_start()
  -- SOUND:PlayBgm(SymSnd("SE_EVT_KOWASUGINAI_LP"), Volume(256))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- EFFECT:StartMotionBlur(0.04, 0.9, 0)
  -- CH("MUNNA"):SetFacialMotion(FACIAL_MOTION.PAIN)
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- subEveFadeAfterTime()
  -- SOUND:PlayEnv(SymSnd("SE_EVT_VOICEWAVE_M_LP"), Volume(128))
  -- EFFECT:Create("effectWaveLp", SymEff("EV_WAVE_LP"))
  -- EFFECT:SetPosition("effectWaveLp", SymPos("P_EFFECT_WAVE_LP"))
  -- EFFECT:Play("effectWaveLp")
  -- WINDOW:Talk(SymAct("MUNNA"), -66245983)
  -- WINDOW:Talk(SymAct("MUNNA"), -1340561071)
  -- WINDOW:Talk(SymAct("MUNNA"), -1459382256)
  -- WINDOW:CloseMessage()
  -- SOUND:VolumeEnv(Volume(64), TimeSec(1))
  -- EFFECT:Wait("effectWaveLp")
  -- EFFECT:Remove("effectWaveLp")
  -- WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.THINK)
  -- WINDOW:Monologue(-2110862381)
  -- subEveCloseMsg()
  -- SOUND:VolumeEnv(Volume(128), TimeSec(0.5))
  -- EFFECT:Create("effectWaveLp", SymEff("EV_WAVE_LP"))
  -- EFFECT:SetPosition("effectWaveLp", SymPos("P_EFFECT_WAVE_LP"))
  -- EFFECT:Play("effectWaveLp")
  -- WINDOW:Talk(SymAct("MUNNA"), -1690961262)
  -- WINDOW:Talk(SymAct("MUNNA"), -730567595)
  -- WINDOW:Talk(SymAct("MUNNA"), -848339692)
  -- WINDOW:CloseMessage()
  -- SOUND:VolumeEnv(Volume(64), TimeSec(1))
  -- EFFECT:Wait("effectWaveLp")
  -- EFFECT:Remove("effectWaveLp")
  -- WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.NORMAL)
  -- WINDOW:Monologue(-431878441)
  -- WINDOW:Monologue(-10928234)
  -- subEveCloseMsg()
  -- CH("MUNNA"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  -- CH("MUNNA"):SetManpu("MP_NOTICE_L")
  -- CH("MUNNA"):WaitManpu()
  -- SOUND:VolumeEnv(Volume(128), TimeSec(0.5))
  -- EFFECT:Create("effectWaveLp", SymEff("EV_WAVE_LP"))
  -- EFFECT:SetPosition("effectWaveLp", SymPos("P_EFFECT_WAVE_LP"))
  -- EFFECT:Play("effectWaveLp")
  -- WINDOW:Talk(SymAct("MUNNA"), 2025923417)
  -- WINDOW:Talk(SymAct("MUNNA"), 1641681432)
  -- WINDOW:CloseMessage()
  -- SOUND:VolumeEnv(Volume(64), TimeSec(1))
  -- EFFECT:Wait("effectWaveLp")
  -- EFFECT:Remove("effectWaveLp")
  -- TASK:Sleep(TimeSec(0.2))
  -- WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.NORMAL)
  -- WINDOW:Monologue(145018420)
  -- subEveCloseMsg()
  -- SOUND:VolumeEnv(Volume(128), TimeSec(0.5))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  -- CH("MUNNA"):SetManpu("MP_FLY_SWEAT")
  -- CH("MUNNA"):SetFacialMotion(FACIAL_MOTION.TEARS)
  -- EFFECT:Create("effectWaveLp", SymEff("EV_WAVE_LP"))
  -- EFFECT:SetPosition("effectWaveLp", SymPos("P_EFFECT_WAVE_LP"))
  -- EFFECT:Play("effectWaveLp")
  -- WINDOW:Talk(SymAct("MUNNA"), 297795445)
  -- WINDOW:Talk(SymAct("MUNNA"), 982690998)
  -- WINDOW:Talk(SymAct("MUNNA"), 596221431)
  -- WINDOW:CloseMessage()
  -- SOUND:VolumeEnv(Volume(64), TimeSec(1))
  -- EFFECT:Wait("effectWaveLp")
  -- EFFECT:Remove("effectWaveLp")
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  -- CH("MUNNA"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  -- CH("MUNNA"):SetManpu("MP_SHOCK_L")
  -- CH("MUNNA"):MoveHeightTo(Height(-0.2345), Speed(1.5))
  -- CH("MUNNA"):WaitMoveHeight()
  -- CH("MUNNA"):MoveHeightTo(Height(-0.3345), Speed(1.5))
  -- CH("MUNNA"):WaitMoveHeight()
  -- CH("MUNNA"):WaitManpu()
  -- SOUND:VolumeEnv(Volume(128), TimeSec(0.5))
  -- EFFECT:Create("effectWaveLp", SymEff("EV_WAVE_LP"))
  -- EFFECT:SetPosition("effectWaveLp", SymPos("P_EFFECT_WAVE_LP"))
  -- EFFECT:Play("effectWaveLp")
  -- WINDOW:Talk(SymAct("MUNNA"), 1825049392)
  -- WINDOW:Talk(SymAct("MUNNA"), 1976777329)
  -- WINDOW:CloseMessage()
  -- SOUND:FadeOutBgm(TimeSec(0.5))
  -- SOUND:FadeOutEnv(TimeSec(0.5))
  -- EFFECT:Remove("effectWaveLp")
  -- CH("MUNNA"):SetVisible(false)
  -- EFFECT:Create("effectWaveEnd", SymEff("EV_WAVE_END"))
  -- EFFECT:SetPosition("effectWaveEnd", SymPos("P_EFFECT_WAVE_END"))
  -- EFFECT:Play("effectWaveEnd")
  -- TASK:Sleep(TimeSec(0.25))
  -- SOUND:PlaySe(SymSnd("SE_EVT_VOICEWAVE_STOP"))
  -- TASK:Sleep(TimeSec(1))
  -- SCREEN_A:FadeOut(TimeSec(0.05), true)
  -- EFFECT:EndMotionBlur()
  FLAG.SceneFlag = CONST.FL_SC_06_END
  FLAG.SCENARIOFLAG = CONST.M12_YUMENONAKANOMUNNA_START
  SYSTEM:NextEntry()
end
function main12_yumenonakanomunna06_end()
end
function main12_yumenonakanomunna07_init()
end
function main12_yumenonakanomunna07_start()
  -- WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  -- WINDOW:Monologue(1593731506)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- CH("HERO"):SetDir(RotateTarget(-45))
  -- CH("PARTNER"):SetDir(RotateTarget(45))
  -- CH("HERO"):SetMotion(SymMot("EV001_SLEEP01"), LOOP.ON, TimeSec(0))
  -- CH("PARTNER"):SetMotion(SymMot("EV001_SLEEP01"), LOOP.ON, TimeSec(0))
  -- SOUND:PlaySe(SymSnd("SE_EVT_DOSU"), Volume(256))
  -- SCREEN_A:FadeIn(TimeSec(0), true)
  -- CAMERA:SetShake(Vector2(0.05, 0.05), TimeSec(3, TIME_TYPE.FRAME))
  -- CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(10, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- CH("HERO"):SetMotion(SymMot("EV013_WAKEUP"), LOOP.OFF)
  -- TASK:Sleep(TimeSec(0.3))
  -- CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  -- CH("HERO"):WaitPlayMotion()
  -- CH("HERO"):SetMotion(SymMot("EV013_TIRED"), LOOP.ON)
  -- WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  -- WINDOW:Monologue(1206212851)
  -- WINDOW:CloseMessage()
  -- CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.5))
  -- TASK:Sleep(TimeSec(1.3))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_02"))
  -- CAMERA:SetTgt(SymCam("CAMERA_02"))
  -- CH("HERO"):DirTo(CH("PARTNER"), Speed(200), ROT_TYPE.NEAR)
  -- CH("HERO"):WaitRotate()
  -- TASK:Sleep(TimeSec(0.3))
  -- WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.NORMAL)
  -- WINDOW:Monologue(-1065532356)
  -- WINDOW:Monologue(-647596675)
  -- WINDOW:CloseMessage()
  -- TASK:Sleep(TimeSec(0.5))
  -- CH("HERO"):DirTo(RotateTarget(-45), Speed(200), ROT_TYPE.NEAR)
  -- CH("HERO"):WaitRotate()
  -- WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.THINK)
  -- WINDOW:Monologue(437346778)
  -- WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SPECIAL02)
  -- WINDOW:Monologue(51007643)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  -- CAMERA:SetEye(SymCam("CAMERA_01"))
  -- CAMERA:SetTgt(SymCam("CAMERA_01"))
  -- TASK:Sleep(TimeSec(0.3))
  -- WINDOW:Monologue(673645400)
  -- WINDOW:KeyWait()
  -- SOUND:PlayBgm(SymSnd("BGM_EVE_NAZO_01"), Volume(256))
  -- WINDOW:Monologue(826028569)
  -- WINDOW:Monologue(2122163422)
  -- WINDOW:Monologue(1734776223)
  -- WINDOW:Monologue(1280034396)
  -- WINDOW:Monologue(1431369501)
  -- WINDOW:Monologue(-758584366)
  -- WINDOW:Monologue(-875308397)
  -- WINDOW:Monologue(-1565718849)
  -- WINDOW:Monologue(-1145686018)
  -- WINDOW:CloseMessage()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  -- CH("HERO"):SetManpu("MP_FLY_SWEAT")
  -- CH("HERO"):WaitManpu()
  -- WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.THINK)
  -- WINDOW:Monologue(-1868864451)
  -- WINDOW:Monologue(-1988078212)
  -- WINDOW:Monologue(-960379973)
  -- WINDOW:Monologue(-539299078)
  -- WINDOW:Monologue(-185097927)
  -- WINDOW:Monologue(-303263624)
  -- WINDOW:Monologue(1786023095)
  -- WINDOW:CloseMessage()
  -- SOUND:FadeOutBgm(TimeSec(2.5))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_02"))
  -- CAMERA:SetTgt(SymCam("CAMERA_02"))
  -- CH("HERO"):DirTo(CH("PARTNER"), Speed(200), ROT_TYPE.NEAR)
  -- CH("HERO"):WaitRotate()
  -- TASK:Sleep(TimeSec(0.3))
  -- WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.THINK)
  -- WINDOW:Monologue(1936702966)
  -- WINDOW:Monologue(-87157015)
  -- WINDOW:CloseMessage()
  -- SCREEN_A:FadeOut(TimeSec(1), true)
  -- TASK:Sleep(TimeSec(0.5))
  subSaveflagM12_060_07()
end
function main12_yumenonakanomunna07_end()
end
function subSaveflagM12_060_07()
  FLAG.SceneFlag = CONST.FL_SC_01_FIRST
  FLAG.SCENARIOFLAG = CONST.M12_YUMENONAKANOMUNNA_END
  FLAG.MapFlags = CONST.EV_START_MAP
  FLAG.FreePlay = CONST.FLAG_FALSE
  FLAG.TrigNextEvent = CONST.FLAG_TRUE
  SYSTEM:NextEntry()
end
function groundEnd()
end

