outlineTbl = {}
function FreePlayoutline()
  CommonSys:OpenBasicMenu(nil, 1588845443)
  SCREEN_A:FadeOut(TimeSec(0), false)
  SCREEN_B:FadeOut(TimeSec(0), false)
  SCREEN_A:FadeInAll(TimeSec(0), false)
  SCREEN_B:FadeInAll(TimeSec(0), false)
  FreeOutlineManageTable("outline", outlineTbl)
  SCREEN_A:FadeOutAll(TimeSec(0), false)
  SCREEN_B:FadeOutAll(TimeSec(0), false)
  SCREEN_A:FadeOut(TimeSec(0), false)
  SCREEN_B:FadeOut(TimeSec(0), false)
  CommonSys:CloseBasicMenu()
  TASK:Sleep(TimeSec(0))
end
function outlineTbl.PARADISE_MODE_outline()
end
function outlineTbl.NO_MESSAGE_outline()
  WINDOW:SysMsg(-582114056)
  WINDOW:CloseMessage()
end
function FreeOutlineManageTable(basename, labelTbl)
  local tbl = {
    {
      CONST.M02_SHUKUBAMACHIHE_END,
      "M02_010_",
      "_FREE_START",
      1
    },
    {
      CONST.M02_DAIKUNITANOMU_END,
      "M02_030_",
      "_FREE_START",
      1
    },
    {
      CONST.M02_KOUZANNODOUKUTSUYARARETA_START,
      "M02_050_",
      "_FREE_START",
      1
    },
    {
      CONST.M02_KOUZANNODOUKUTSUYARARETA_END,
      "M02_050_",
      "_FREE_START",
      1
    },
    {
      CONST.M02_ZURUKKUWOOE_END,
      "M02_080_",
      "_FREE_START",
      1
    },
    {
      CONST.M02_KAGEROUTOUGE1ST_END,
      "M02_090_",
      "_FREE_START",
      1
    },
    {
      CONST.M02_KAGEROUTOUGEYARARETA_END,
      "M02_100_",
      "_FREE_START",
      1
    },
    {
      CONST.M02_KAGEROUTOUGECHUKEIYARARE1_END,
      "M02_115_",
      "_FREE_START",
      1
    },
    {
      CONST.M02_KAGEROUTOUGEBOSSYARARETA_END,
      "M02_130_",
      "_FREE_START",
      1
    },
    {
      CONST.M02_KAGEROUTOUGECLEARGOYARARE_END,
      "M02_160_",
      "_FREE_START",
      1
    },
    {
      CONST.M03_TSUGINOASA_END,
      "M03_010_",
      "_FREE_START",
      1
    },
    {
      CONST.M03_NUONOOKURIMONO_END,
      "M03_020_",
      "_FREE_START",
      1
    },
    {
      CONST.M03_BIRIJION_END,
      "M03_090_",
      "_FREE_START",
      1
    },
    {
      CONST.M03_NUONOHANASHI_END,
      "M03_110_",
      "_FREE_START",
      1
    },
    {
      CONST.M03_AREHATEDANIYARARETA_END,
      "M03_130_",
      "_FREE_START",
      1
    },
    {
      CONST.M03_AREHATEDANIBOSSYARARETA_END,
      "M03_150_",
      "_FREE_START",
      1
    },
    {
      CONST.M04_TEAMNONAMAE_END,
      "M04_020_",
      "_FREE_START",
      1
    },
    {
      CONST.M04_HANYOU_FREE_START_FLAG,
      "M04_HANYOU_",
      "_FREE_START",
      1
    },
    {
      CONST.M04_DOTEKKOTSUNOHANASHI_END,
      "M04_040_",
      "_FREE_START",
      1
    },
    {
      CONST.M04_ZAIRYOUCLEARTSUGINOASA_END,
      "M04_060_",
      "_FREE_START",
      1
    },
    {
      CONST.M04_ZAIRYOUTOTTEKITAYO_END,
      "M04_070_",
      "_FREE_START",
      1
    },
    {
      CONST.M04_HANYOU_FREE2_START_FLAG,
      "M04_HANYOU_",
      "_FREE_START2",
      1
    },
    {
      CONST.M04_DOTEKKOTSUGUMI_END,
      "M05_000_",
      "_FREE_START",
      1
    },
    {
      CONST.M05_TSUGINOASA_START,
      "M05_010_",
      "_FREE_START",
      1
    },
    {
      CONST.M05_TSUGINOASA_END,
      "M05_010_",
      "_FREE_START",
      1
    },
    {
      CONST.M05_VWAVETOURAI_END,
      "M05_020_",
      "_FREE_START",
      1
    },
    {
      CONST.M05_YUMENONAKADE_END,
      "M05_030_",
      "_FREE_START",
      1
    },
    {
      CONST.M06_HANYOU_FREE_START_FLAG,
      "M06_HANYOU_",
      "_FREE_START",
      1
    },
    {
      CONST.M06_OKANOUENOSHINKIROU_END,
      "M06_010_",
      "_FREE_START",
      1
    },
    {
      CONST.M06_OSHIRASEKISYOU_END,
      "M06_015_",
      "_FREE_START",
      1
    },
    {
      CONST.M06_NAZONOKAGE_END,
      "M06_020_",
      "_FREE_START",
      1
    },
    {
      CONST.M06_KYOUKAIKARANOSHIRASE_END,
      "M06_030_",
      "_FREE_START",
      1
    },
    {
      CONST.M06_NUONOTANOMIGOTO_END,
      "M06_040_",
      "_FREE_START",
      1
    },
    {
      CONST.M06_SHUKUBAMACHINOYOUSU_END,
      "M06_060_",
      "_FREE_START",
      1
    },
    {
      CONST.M06_TSUNORUFUAN_END,
      "M07_000_",
      "_FREE_START",
      1
    },
    {
      CONST.M07_NAZONOKAGESONONI_END,
      "M07_010_",
      "_FREE_START",
      1
    },
    {
      CONST.M07_HAHAKOMORIKARANOTANOMI_END,
      "M07_020_",
      "_FREE_START",
      1
    },
    {
      CONST.M07_SHIKISAINOMORIYARARETA_END,
      "M07_045_",
      "_FREE_START",
      1
    },
    {
      CONST.M07_HANYOU_FREE_START_FLAG,
      "M07_HANYOU_",
      "_FREE_START",
      1
    },
    {
      CONST.M07_AYASHIIPOKEMON_END,
      "M07_080_",
      "_FREE_START",
      1
    },
    {
      CONST.M08_HAKOBIKOMARETAHOUMONSHA_END,
      "M08_010_",
      "_FREE_START",
      1
    },
    {
      CONST.M08_HANYOU_FREE_START_FLAG,
      "M08_HANYOU_",
      "_FREE_START",
      1
    },
    {
      CONST.M08_BURAKKII_END,
      "M08_020_",
      "_FREE_START",
      1
    },
    {
      CONST.M08_DOUKOKUNOTANIOWARERUEEFI_END,
      "M08_040_",
      "_FREE_START",
      1
    },
    {
      CONST.M08_DOUKOKUNOTANIYARARETA_END,
      "M08_050_",
      "_FREE_START",
      1
    },
    {
      CONST.M08_DOUKOKUNOTANICHUKEIYARARETA_END,
      "M08_055_",
      "_FREE_START",
      1
    },
    {
      CONST.M08_DOUKOKUNOTANIBOSSYARARETA_END,
      "M08_070_",
      "_FREE_START",
      1
    },
    {
      CONST.M09_ARATANANAKAMA_END,
      "M09_040_",
      "_FREE_START",
      1
    },
    {
      CONST.M09_HANYOU_FREE2_START_FLAG,
      "M09_HANYOU_",
      "_FREE_START2",
      1
    },
    {
      CONST.M09_NUOONOHANASHI_END,
      "M09_060_",
      "_FREE_START",
      1
    },
    {
      CONST.M09_BIRIJIONNOKAKOSONONI_END,
      "M09_080_",
      "_FREE_START",
      1
    },
    {
      CONST.M09_ENSEINOHI_END,
      "M09_100_",
      "_FREE_START",
      1
    },
    {
      CONST.M09_KUJIBIKI_END,
      "M09_110_",
      "_FREE_START",
      1
    },
    {
      CONST.M09_ENTERCARDKANSEI_END,
      "M09_120_",
      "_FREE_START",
      1
    },
    {
      CONST.M09_DAIHYOUGAHE_START,
      "M09_120_",
      "_FREE_START",
      1
    },
    {
      CONST.M10_CHIMYAKUKANDOUENTER_END,
      "M10_010_",
      "_FREE_START",
      1
    },
    {
      CONST.M10_CHIMYAKUKANDOUYARARETA_END,
      "M10_030_",
      "_FREE_START",
      1
    },
    {
      CONST.M10_CHIMYAKUKANDOUCLEAR1ST_START,
      "M10_040_",
      "_FREE_START",
      1
    },
    {
      CONST.M10_CHIMYAKUKANDOUCLEAR1ST_END,
      "M10_040_",
      "_FREE_START",
      1
    },
    {
      CONST.M10_CHIMYAKUKANDOUTOTSUNYUU_END,
      "M10_060_",
      "_FREE_START",
      1
    },
    {
      CONST.M10_DAIHYOUGAYARARETA_END,
      "M10_060_",
      "_FREE_START",
      1
    },
    {
      CONST.M10_DAIHYOUGACLEAR1ST_END,
      "M10_060_",
      "_FREE_START",
      1
    },
    {
      CONST.M11_NANROENTER_END,
      "M11_010_",
      "_FREE_START",
      1
    },
    {
      CONST.M11_NANROYARARETA_END,
      "M11_030_",
      "_FREE_START",
      1
    },
    {
      CONST.M11_NANROCLEAR1ST_END,
      "M11_040_",
      "_FREE_START",
      1
    },
    {
      CONST.M11_PALACETOTSUNYUU_END,
      "M11_050_",
      "_FREE_START",
      1
    },
    {
      CONST.M11_PALACEYARARETA_END,
      "M11_060_",
      "_FREE_START",
      1
    },
    {
      CONST.M11_PALACECHUKEIYARARETA_END,
      "M11_075_",
      "_FREE_START",
      1
    },
    {
      CONST.M11_PALACEBOSSYARARETA_END,
      "M11_090_",
      "_FREE_START",
      1
    },
    {
      CONST.M12_TSUGINOHIRU_END,
      "M12_010_",
      "_FREE_START",
      2
    },
    {
      CONST.M12_EMONGANOITAZURA_END,
      "M12_020_",
      "_FREE_START",
      2
    },
    {
      CONST.M12_HISASHIBURINOYUME_END,
      "M12_030_",
      "_FREE_START",
      2
    },
    {
      CONST.M12_YAKUSOKU_END,
      "M12_040_",
      "_FREE_START",
      2
    },
    {
      CONST.M12_HANYOU_FREE_START_FLAG,
      "M12_HANYOU_",
      "_FREE_START",
      2
    },
    {
      CONST.M12_TENNINOBORUHIKARI_END,
      "M12_050_",
      "_FREE_START",
      2
    },
    {
      CONST.M12_SHUJINKOUNOHANASHI_END,
      "M12_070_",
      "_FREE_START",
      2
    },
    {
      CONST.M12_MUNNAKYUUSHUTSUHE_START,
      "M12_070_",
      "_FREE_START",
      2
    },
    {
      CONST.M13_GENOUEAKANDOUENTER_END,
      "M13_010_",
      "_FREE_START",
      2
    },
    {
      CONST.M13_GENOUEAKANDOUYARARETA_END,
      "M13_030_",
      "_FREE_START",
      2
    },
    {
      CONST.M13_GENOUEAKANDOUCLEAR1ST_START,
      "M13_040_",
      "_FREE_START",
      2
    },
    {
      CONST.M13_GENOUEAKANDOUCLEAR1ST_END,
      "M13_040_",
      "_FREE_START",
      2
    },
    {
      CONST.M13_YAMIYONOMORIYARARETA_END,
      "M13_060_",
      "_FREE_START",
      2
    },
    {
      CONST.M13_YAMIYONOMORICLEAR1ST_END,
      "M13_070_",
      "_FREE_START",
      2
    },
    {
      CONST.M13_YOAKENOSANGAKUTOTSUNYUU_END,
      "M13_080_",
      "_FREE_START",
      2
    },
    {
      CONST.M13_YOAKENOSANGAKUYARARETA_END,
      "M13_090_",
      "_FREE_START",
      2
    },
    {
      CONST.M13_YOAKENOSANGAKUTOTSUNYUU_END,
      "M13_095_",
      "_FREE_START",
      2
    },
    {
      CONST.M13_YOAKENOSANGAKUBOSSYARARETA_END,
      "M13_110_",
      "_FREE_START",
      2
    },
    {
      CONST.M13_YOAKENOSANGAKUBOSSWIN_START,
      "M13_110_",
      "_FREE_START",
      2
    },
    {
      CONST.M14_SHINSOU_END,
      "M14_010_",
      "_FREE_START",
      2
    },
    {
      CONST.M14_SHIROIWANOKOUYAYARARETA_END,
      "M14_030_",
      "_FREE_START",
      2
    },
    {
      CONST.M14_SHIROIWANOKOUYACLEAR1ST_START,
      "M14_040_",
      "_FREE_START",
      2
    },
    {
      CONST.M14_SHIROIWANOKOUYACLEAR1ST_END,
      "M14_040_",
      "_FREE_START",
      2
    },
    {
      CONST.M14_AOMIDORINUMAYARARETA_END,
      "M14_060_",
      "_FREE_START",
      2
    },
    {
      CONST.M14_AOMIDORINUMACLEAR1ST_END,
      "M14_070_",
      "_FREE_START",
      2
    },
    {
      CONST.M14_FUUKETSUNOOKAYARARETA_END,
      "M14_090_",
      "_FREE_START",
      2
    },
    {
      CONST.M15_PARADISEHE_END,
      "M15_010_",
      "_FREE_START",
      2
    },
    {
      CONST.M15_ENTENNOSABAKUTOTSUNYUU_END,
      "M15_020_",
      "_FREE_START",
      2
    },
    {
      CONST.M15_ENTENNOSABAKUYARARETA_END,
      "M15_030_",
      "_FREE_START",
      2
    },
    {
      CONST.M16_SONOYORU_START,
      "M16_010_",
      "_FREE_START",
      2
    },
    {
      CONST.M16_SHUPPATSUNOASA_END,
      "M16_040_",
      "_FREE_START",
      2
    },
    {
      CONST.M16_DAIHYOUGAHEFUTATABI_START,
      "M16_040_",
      "_FREE_START",
      2
    },
    {
      CONST.M16_CHIMYAKUAIROENTER_END,
      "M16_080_",
      "_FREE_START",
      2
    },
    {
      CONST.M16_CHIMYAKUAIROTOTSUNYUU_END,
      "M16_090_",
      "_FREE_START",
      2
    },
    {
      CONST.M16_CHIMYAKUAIROYARARETA_END,
      "M16_100_",
      "_FREE_START",
      2
    },
    {
      CONST.M16_CHIMYAKUAIROCHUKEIYARARETA_END,
      "M16_105_",
      "_FREE_START",
      2
    },
    {
      CONST.M16_CHIMYAKUAIROBOSSYARARETA_END,
      "M16_120_",
      "_FREE_START",
      2
    },
    {
      CONST.M16_SORAWOWATARUHOUHOU_START,
      "M16_120_",
      "_FREE_START",
      2
    },
    {
      CONST.M17_SORATOBUGREPALACEHE_END,
      "M17_020_",
      "_FREE_START",
      2
    },
    {
      CONST.M17_GREPALACEEASTYARARETA_END,
      "M17_040_",
      "_FREE_START",
      2
    },
    {
      CONST.M17_BIRIJIONTOEMONGA_END,
      "M17_060_",
      "_FREE_START",
      2
    },
    {
      CONST.M17_GREPALACEEASTCHUKEIYARARETA_END,
      "M17_065_",
      "_FREE_START",
      2
    },
    {
      CONST.M17_GREPALACEEASTBOSSYARARETA_END,
      "M17_090_",
      "_FREE_START",
      2
    },
    {
      CONST.M17_SHITSUBOUNOARASHI_END,
      "M17_120_",
      "_FREE_START",
      2
    },
    {
      CONST.M17_GREPALACEWESTYARARETA_END,
      "M17_140_",
      "_FREE_START",
      2
    },
    {
      CONST.M17_YUUHEINOTOU_END,
      "M17_150_",
      "_FREE_START",
      2
    },
    {
      CONST.M17_GREPALACEWESTCHUKEIYARARETA_END,
      "M17_155_",
      "_FREE_START",
      2
    },
    {
      CONST.M17_GREPALACEWESTBOSSYARARETA_END,
      "M17_170_",
      "_FREE_START",
      2
    },
    {
      CONST.M17_DAIKESSHOUNOTOU_END,
      "M17_200_",
      "_FREE_START",
      2
    },
    {
      CONST.M17_DAIKESSHOUNOTOUTOTSUNYUU_END,
      "M17_210_",
      "_FREE_START",
      2
    },
    {
      CONST.M17_DAIKESSHOUNOTOUYARARETA_END,
      "M17_220_",
      "_FREE_START",
      2
    },
    {
      CONST.M17_DAIKESSHOUNOTOUCHUKEIYARARETA_END,
      "M17_225_",
      "_FREE_START",
      2
    },
    {
      CONST.M17_DAIKESSHOUNOTOUBOSSYARARETA_END,
      "M17_240_",
      "_FREE_START",
      2
    },
    {
      CONST.S1_SONOGO_END,
      "S01_010_",
      "_FREE_START",
      2
    },
    {
      CONST.S1_SHUKUBAMACHINOYORU_END,
      "S01_020_",
      "_FREE_START",
      2
    },
    {
      CONST.S1_NANIKANOKEHAI_END,
      "S01_030_",
      "_FREE_START",
      2
    },
    {
      CONST.S1_SAZANDORAINAKUNARU_END,
      "S01_040_",
      "_FREE_START",
      2
    },
    {
      CONST.S1_SAZANDORANOHANASHI_END,
      "S01_050_",
      "_FREE_START",
      2
    },
    {
      CONST.S1_SEKAINOHESOYARARETA_END,
      "S01_060_",
      "_FREE_START",
      2
    },
    {
      CONST.S1_UCHUURITSUNOOKA_END,
      "S01_080_",
      "_FREE_START",
      2
    },
    {
      CONST.S1_SEKAINOHESOCLEAR1ST_END,
      "S01_080_",
      "_FREE_START",
      2
    },
    {
      CONST.SENARIO_ALL_CLEAR,
      "ALL_CLEAR_",
      "_FREE_START",
      2
    }
  }
  for i, v in ipairs(tbl) do
    if FLAG.ScenarioFlag == v[1] then
      local backUpTbl = {}
      for k, v in pairs(labelTbl) do
        backUpTbl[k] = v
      end
      if v[4] == 1 then
        dofile("script/usual/other/outline/" .. string.lower(basename) .. "_1.lua")
      elseif v[4] == 2 then
        dofile("script/usual/other/outline/" .. string.lower(basename) .. "_2.lua")
      end
      local func_name = v[2] .. basename .. v[3]
      local func = labelTbl[func_name]
      while true do
        func = func()
        if func == nil then
          break
        end
      end
      labelTbl = {}
      for k, v in pairs(backUpTbl) do
        labelTbl[k] = v
      end
      break
    end
    local func_name = "NO_MESSAGE_" .. basename
    local func = labelTbl[func_name]
  end
end

