dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main08_takusaretaentercard01_init()
end
function main08_takusaretaentercard01_start()
  if FLAG.NowResumeFlag == CONST.FLAG_FALSE then
    TASK:Sleep(TimeSec(0.2))
    if Ground_Save(ground) then
      return
    end
  else
    subEveFromProgFadeSet()
  end
  GIMMICK:SetVisible(SymLayer("SHOP_CHEST"), false)
  local taskJump = function(chara)
    chara:MoveHeightTo(Height(0.1), Speed(1.5))
    chara:WaitMoveHeight()
    chara:MoveHeightTo(Height(0), Speed(1.5))
    chara:WaitMoveHeight()
    chara:SetManpu("MP_FLY_SWEAT")
    chara:WaitManpu()
  end
  CAMERA:SetAzimuthDifferenceVolume(Volume(3.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("DOTEKKOTSU"):SetMotionBlendMode(BlendMode.NONE)
  CH("BIRIJION"):SetMotionBlendMode(BlendMode.NONE)
  CH("HAADERIA"):SetMotionBlendMode(BlendMode.NONE)
  CH("MINEZUMI"):SetMotionBlendMode(BlendMode.NONE)
  CH("SUWANNA"):SetMotionBlendMode(BlendMode.NONE)
  CH("EEFI"):SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  CH("BURAKKII"):SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  CH("HERO"):SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  CH("PARTNER"):SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  CH("EMONGA"):SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  CH("NOKOTCHI"):SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  SOUND:PlayBgm(SymSnd("BGM_EVE_CALM_01"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("BURAKKII"):WalkTo(SymPos("P01_BURAKKII"), Speed(1))
  CH("BURAKKII"):WaitMove()
  WINDOW:DrawFace(20, 20, SymAct("BURAKKII"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("BURAKKII"), -244118206)
  WINDOW:CloseMessage()
  CH("EEFI"):WalkTo(SymPos("P01_EEFI"), Speed(1))
  CH("EEFI"):WaitMove()
  WINDOW:DrawFace(324, 88, SymAct("EEFI"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("EEFI"), -395822077)
  WINDOW:KeyWait()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("EEFI"):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFace(324, 88, SymAct("EEFI"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("EEFI"), -1018859584)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 20, SymAct("BURAKKII"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("BURAKKII"), -631349631)
  subEveCloseMsg()
  CH("EEFI"):SetNeckRot(RotateTarget(0), RotateTarget(-35), RotateTarget(0), TimeSec(0.3))
  WINDOW:DrawFace(324, 88, SymAct("EEFI"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("EEFI"), -1793079226)
  WINDOW:Talk(SymAct("EEFI"), -1945831161)
  WINDOW:CloseMessage()
  CH("EEFI"):ResetNeckRot(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("EEFI"):SetManpu("MP_FLY_SWEAT")
  CH("EEFI"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("EEFI"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("EEFI"), -1490441532)
  WINDOW:Talk(SymAct("EEFI"), -1103979643)
  WINDOW:CloseMessage()
  subEveNod(CH("BURAKKII"))
  WINDOW:DrawFace(20, 20, SymAct("BURAKKII"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("BURAKKII"), 967477066)
  WINDOW:Talk(SymAct("BURAKKII"), 548517387)
  WINDOW:CloseMessage()
  subEveNod(CH("EEFI"))
  WINDOW:DrawFace(324, 88, SymAct("EEFI"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("EEFI"), -1696734432)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_00_5"))
  CAMERA:SetTgt(SymCam("CAMERA_00_5"))
  TASK:Regist(subEveMoveDir, {
    CH("BURAKKII"),
    SymPos("P02_BURAKKII"),
    Speed(1.5),
    CH("HERO")
  })
  TASK:Sleep(TimeSec(0.1))
  TASK:Regist(subEveMoveDir, {
    CH("EEFI"),
    SymPos("P02_EEFI"),
    Speed(1.5),
    CH("HERO")
  })
  TASK:WaitTask()
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(72, 16, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BURAKKII"), -2084122015)
  WINDOW:CloseMessage()
  CH("EEFI"):DirTo(RotateTarget(-135), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("BURAKKII"):DirTo(RotateTarget(-135), Speed(350), ROT_TYPE.NEAR)
  CH("BURAKKII"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BURAKKII"), -1460960862)
  WINDOW:Talk(SymAct("BURAKKII"), -1309626141)
  WINDOW:CloseMessage()
  subEveNod(CH("PARTNER"))
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -21944796, PARTNER_1 = -408283291})
  WINDOW:CloseMessage()
  CH("EEFI"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("BURAKKII"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("BURAKKII"):WaitRotate()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.THINK)
  WINDOW:SwitchTalk({PARTNER_0 = -863550298, PARTNER_1 = -711166489})
  WINDOW:SwitchTalk({PARTNER_0 = 1376020776, PARTNER_1 = 1260345449})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("BURAKKII"):SetManpu("MP_FLY_SWEAT")
  CH("BURAKKII"):WaitManpu()
  WINDOW:DrawFace(20, 20, SymAct("BURAKKII"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("BURAKKII"), -2006430514)
  WINDOW:CloseMessage()
  CH("EEFI"):DirTo(CH("BURAKKII"), Speed(350), ROT_TYPE.NEAR)
  CH("EEFI"):WaitRotate()
  WINDOW:DrawFace(226, 8, SymAct("EEFI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EEFI"), -1854702193)
  WINDOW:CloseMessage()
  CH("BURAKKII"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  CH("BURAKKII"):WaitRotate()
  WINDOW:DrawFace(226, 8, SymAct("EEFI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EEFI"), -1168232884)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 20, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BURAKKII"), -1555751155)
  WINDOW:Talk(SymAct("BURAKKII"), -335246902)
  WINDOW:Talk(SymAct("BURAKKII"), -182470517)
  WINDOW:Talk(SymAct("BURAKKII"), -567088312)
  WINDOW:Talk(SymAct("BURAKKII"), -953558519)
  WINDOW:Talk(SymAct("BURAKKII"), 1085392582)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("NOKOTCHI"):SetManpu("MP_FLY_SWEAT")
  TASK:Regist(subEveJump, {
    CH("NOKOTCHI")
  })
  CH("EMONGA"):SetManpu("MP_SHOCK_L")
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_SHOCK_L")
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 1504376711, PARTNER_1 = 819211179})
  WINDOW:CloseMessage()
  subEveDoubleJump(CH("EMONGA"))
  CH("BURAKKII"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("EEFI"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(324, 88, SymAct("EMONGA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("EMONGA"), 701438698)
  WINDOW:Talk(SymAct("EMONGA"), 48384297)
  WINDOW:Talk(SymAct("EMONGA"), 469334120)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("BURAKKII"):SetManpu("MP_QUESTION")
  CH("BURAKKII"):WaitManpu()
  WINDOW:DrawFace(20, 20, SymAct("BURAKKII"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("BURAKKII"), 1421405871)
  WINDOW:Talk(SymAct("BURAKKII"), 1302585326)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_00_5"))
  CAMERA:SetTgt(SymCam("CAMERA_00_5"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_SHOCK_L")
  CH("SUWANNA"):SetManpu("MP_SHOCK_R")
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("EMONGA"):SetManpu("MP_SHOCK_L")
  TASK:Sleep(TimeSec(0.1))
  CH("MINEZUMI"):SetManpu("MP_EXCLAMATION")
  CH("HAADERIA"):SetManpu("MP_EXCLAMATION")
  TASK:Regist(taskJump, {
    CH("NOKOTCHI")
  })
  CH("DOTEKKOTSU"):SetManpu("MP_SHOCK_R")
  TASK:Sleep(TimeSec(1))
  CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetEye(SymCam("CAMERA_NOKOTCHI"))
  CAMERA:SetTgt(SymCam("CAMERA_NOKOTCHI"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("NOKOTCHI"):SetManpu("MP_SHOCK_L")
  CH("NOKOTCHI"):WaitManpu()
  WINDOW:Talk(SymAct("NOKOTCHI"), 1720618029)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3.5))
  CAMERA:SetEye(SymCam("CAMERA_MINEZUMI"))
  CAMERA:SetTgt(SymCam("CAMERA_MINEZUMI"))
  subEveDoubleJump(CH("MINEZUMI"))
  WINDOW:Talk(SymAct("MINEZUMI"), 2140519788)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_HAADERIA"))
  CAMERA:SetTgt(SymCam("CAMERA_HAADERIA"))
  CH("BURAKKII"):SetDir(CH("HAADERIA"))
  CH("EEFI"):SetDir(CH("HAADERIA"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:Talk(SymAct("HAADERIA"), -133324381)
  WINDOW:Talk(SymAct("HAADERIA"), -518614814)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_00_5"))
  CAMERA:SetTgt(SymCam("CAMERA_00_5"))
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("BURAKKII"):SetManpu("MP_FLY_SWEAT")
  CH("BURAKKII"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("BURAKKII"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("BURAKKII"), -1392307438)
  WINDOW:Talk(SymAct("BURAKKII"), -1273486765)
  WINDOW:CloseMessage()
  CH("BURAKKII"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("EEFI"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_DAIHYOUGA_02"), Volume(256))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 20, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BURAKKII"), -1623887472)
  subEveCloseMsg()
  WINDOW:DrawFaceF(226, 8, SymAct("EEFI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EEFI"), -2043789103)
  WINDOW:Talk(SymAct("EEFI"), -915417578)
  WINDOW:Talk(SymAct("EEFI"), -797644969)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("HERO"):SetManpu("MP_QUESTION")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.THINK)
  WINDOW:Monologue(-78007148)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 20, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BURAKKII"), -498956843)
  WINDOW:Talk(SymAct("BURAKKII"), 1708824858)
  WINDOW:Talk(SymAct("BURAKKII"), 2093066331)
  WINDOW:Talk(SymAct("BURAKKII"), 364868727)
  WINDOW:Talk(SymAct("BURAKKII"), 212092214)
  WINDOW:Talk(SymAct("BURAKKII"), 663295733)
  WINDOW:CloseMessage()
  subEveDoubleJump(CH("PARTNER"))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 1049765812, PARTNER_1 = 1909698931})
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  WINDOW:SwitchTalk({PARTNER_0 = 1757970482, PARTNER_1 = 1139135473})
  WINDOW:SwitchTalk({PARTNER_0 = 1526653616, PARTNER_1 = -580452737})
  WINDOW:CloseMessage()
  subEveNod(CH("BURAKKII"))
  WINDOW:DrawFace(20, 20, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BURAKKII"), -998387906)
  WINDOW:Talk(SymAct("BURAKKII"), 118152089)
  WINDOW:CloseMessage()
  CH("BURAKKII"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  CH("BURAKKII"):WaitRotate()
  WINDOW:DrawFace(20, 20, SymAct("BURAKKII"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("BURAKKII"), 504490712)
  WINDOW:KeyWait()
  CH("EEFI"):DirTo(CH("BURAKKII"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:Talk(SymAct("BURAKKII"), 893171995)
  WINDOW:Talk(SymAct("BURAKKII"), 740788314)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("BURAKKII"):DirTo(RotateTarget(90), Speed(200), ROT_TYPE.NEAR)
  CH("BURAKKII"):WaitRotate()
  CH("BURAKKII"):SetNeckRot(RotateTarget(0), RotateTarget(-35), RotateTarget(0), TimeSec(0.3))
  WINDOW:DrawFace(20, 88, SymAct("BURAKKII"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("BURAKKII"), 1667636893)
  WINDOW:Talk(SymAct("BURAKKII"), 2055024604)
  WINDOW:KeyWait()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("BURAKKII"):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFace(20, 88, SymAct("BURAKKII"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("BURAKKII"), 1364229151)
  WINDOW:Talk(SymAct("BURAKKII"), 1212894558)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(1.5))
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  TASK:Regist(subEveDoubleJump, {
    CH("EEFI")
  })
  WINDOW:DrawFace(272, 16, SymAct("EEFI"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("EEFI"), -808234607)
  WINDOW:Talk(SymAct("EEFI"), -691511088)
  WINDOW:CloseMessage()
  CH("BURAKKII"):ResetNeckRot(TimeSec(0.2))
  CH("BURAKKII"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  CH("BURAKKII"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("BURAKKII"):SetManpu("MP_EXCLAMATION")
  CH("BURAKKII"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("BURAKKII"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("BURAKKII"), -1078543108)
  subEveCloseMsg()
  WINDOW:DrawFace(272, 16, SymAct("EEFI"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("EEFI"), -1498575427)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("EEFI"):SetManpu("MP_FLY_SWEAT")
  CH("EEFI"):WaitManpu()
  CH("EEFI"):SetNeckRot(RotateTarget(0), RotateTarget(-35), RotateTarget(0), TimeSec(0.3))
  WINDOW:DrawFace(272, 16, SymAct("EEFI"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("EEFI"), -1920934274)
  CH("EEFI"):WaitNeckRot()
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("KURUMAYU"):WalkTo(SymPos("P00_KURUMAYU"), Speed(1.5))
  TASK:Sleep(TimeSec(0.5))
  CH("HAHAKOMORI"):WalkTo(SymPos("P00_HAHAKOMORI"), Speed(1.5))
  CH("HAHAKOMORI"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("MINEZUMI"):SetManpu("MP_NOTICE_R")
  TASK:Sleep(TimeSec(0.1))
  CH("EMONGA"):SetManpu("MP_NOTICE_L")
  TASK:Sleep(TimeSec(0.1))
  CH("EMONGA"):DirTo(CH("KURUMAYU"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):SetManpu("MP_NOTICE_L")
  TASK:Sleep(TimeSec(0.2))
  CH("EEFI"):ResetNeckRot(TimeSec(0.2))
  CH("EEFI"):WaitNeckRot()
  CH("PARTNER"):DirTo(CH("KURUMAYU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("KURUMAYU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("NOKOTCHI"):DirTo(CH("KURUMAYU"), Speed(350), ROT_TYPE.NEAR)
  CH("NOKOTCHI"):WaitRotate()
  CH("EEFI"):DirTo(CH("KURUMAYU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("BURAKKII"):DirTo(CH("KURUMAYU"), Speed(350), ROT_TYPE.NEAR)
  CH("BURAKKII"):WaitRotate()
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  TASK:Sleep(TimeSec(0.8))
  CAMERA:MoveFollow(SymCam("CAMERA_05"), Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Regist(subEveMoveDir, {
    CH("KURUMAYU"),
    SymPos("P01_KURUMAYU"),
    Speed(1.5),
    CH("EEFI")
  })
  TASK:Regist(subEveMoveDir, {
    CH("HERO"),
    SymPos("P01_HERO"),
    Speed(1.5),
    SymPos("P01_KURUMAYU")
  })
  TASK:Regist(subEveMoveDir, {
    CH("PARTNER"),
    SymPos("P01_PARTNER"),
    Speed(1.5),
    SymPos("P01_KURUMAYU")
  })
  TASK:Sleep(TimeSec(0.2))
  CH("HAHAKOMORI"):WalkTo(SymPos("P01_HAHAKOMORI"), Speed(1.5))
  TASK:Regist(subEveMoveDir, {
    CH("EMONGA"),
    SymPos("P01_EMONGA"),
    Speed(1.5),
    SymPos("P01_KURUMAYU")
  })
  CH("NOKOTCHI"):DirTo(SymPos("P01_KURUMAYU"), Speed(350), ROT_TYPE.NEAR)
  TASK:WaitTask()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("EEFI"):SetManpu("MP_EXCLAMATION")
  CH("EEFI"):WaitManpu()
  WINDOW:DrawFace(20, 20, SymAct("EEFI"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("EEFI"), -1801720001)
  WINDOW:CloseMessage()
  CH("EEFI"):RunTo(SymPos("P03_EEFI"), Speed(2))
  CH("EEFI"):WaitMove()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3.5))
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("EEFI"):SetManpu("MP_FLY_SWEAT")
  CH("EEFI"):WaitManpu()
  WINDOW:DrawFace(72, 16, SymAct("EEFI"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("EEFI"), -606438920)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("KURUMAYU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KURUMAYU"), -1027520327)
  subEveCloseMsg()
  CH("KURUMAYU"):WalkTo(PosOffs(-0.15, -0.15), Speed(1), LINK_DIR.OFF)
  CH("KURUMAYU"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_HAND"), Volume(256))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:SysMsg(-370402438)
  WINDOW:CloseMessage()
  CH("KURUMAYU"):WalkTo(PosOffs(0.15, 0.15), Speed(1), LINK_DIR.OFF)
  CH("KURUMAYU"):WaitMove()
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("NOKOTCHI"):SetManpu("MP_EXCLAMATION")
  CH("NOKOTCHI"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("NOKOTCHI"), -252237253)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("EMONGA"):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFace(272, 16, SymAct("EMONGA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("EMONGA"), 2003777268)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3.5))
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  subEveDoubleJump(CH("KURUMAYU"))
  WINDOW:DrawFace(324, 88, SymAct("KURUMAYU"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("KURUMAYU"), 1853097909)
  subEveCloseMsg()
  CH("EEFI"):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFace(72, 16, SymAct("EEFI"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("EEFI"), -405427030)
  WINDOW:Talk(SymAct("EEFI"), -20013589)
  WINDOW:CloseMessage()
  CH("KURUMAYU"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  subEveDoubleJump(CH("KURUMAYU"))
  WINDOW:DrawFace(324, 88, SymAct("KURUMAYU"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("KURUMAYU"), -706490840)
  WINDOW:CloseMessage()
  CH("KURUMAYU"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  subEveNod(CH("EEFI"))
  WINDOW:DrawFace(72, 16, SymAct("EEFI"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("EEFI"), -856096919)
  WINDOW:Talk(SymAct("EEFI"), -2085000786)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("EEFI"):SetManpu("MP_FLY_SWEAT_LP")
  CH("EEFI"):SetMotionRaito(Raito(0.5))
  CH("EEFI"):SetMotion(SymMot("EV008_CRY00"), LOOP.OFF)
  CH("EEFI"):WaitPlayMotion()
  CH("EEFI"):SetMotionRaito(Raito(1))
  CH("EEFI"):SetMotion(SymMot("EV008_CRY01"), LOOP.ON)
  CH("PARTNER"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  CH("NOKOTCHI"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  CH("EMONGA"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  CH("BURAKKII"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(72, 16, SymAct("EEFI"), FACE_TYPE.WEEP)
  WINDOW:Talk(SymAct("EEFI"), -1700636433)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  CH("EMONGA"):SetManpu("MP_SHOCK_L")
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("BURAKKII"):SetManpu("MP_EXCLAMATION")
  CH("BURAKKII"):WaitManpu()
  subEveCloseMsg()
  CH("KURUMAYU"):SetManpu("MP_FLY_SWEAT")
  TASK:Regist(subEveDoubleJump, {
    CH("KURUMAYU")
  })
  WINDOW:DrawFace(324, 88, SymAct("KURUMAYU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("KURUMAYU"), -1316025556)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  CH("DOTEKKOTSU"):SetManpu("MP_FLY_SWEAT")
  CH("DOTEKKOTSU"):WaitManpu()
  WINDOW:DrawFace(72, 16, SymAct("DOTEKKOTSU"), FACE_TYPE.SURPRISE)
  WINDOW:DrawFaceOffset(-10, 0)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), -1466680723)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("MINEZUMI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MINEZUMI"), 789325474)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CH("HAHAKOMORI"):WalkTo(SymPos("P02_HAHAKOMORI"), Speed(1))
  CH("HAHAKOMORI"):WaitMove()
  CH("PARTNER"):DirTo(CH("HAHAKOMORI"), Speed(350), ROT_TYPE.NEAR)
  CH("NOKOTCHI"):DirTo(CH("HAHAKOMORI"), Speed(350), ROT_TYPE.NEAR)
  CH("EMONGA"):DirTo(CH("HAHAKOMORI"), Speed(350), ROT_TYPE.NEAR)
  CH("BURAKKII"):DirTo(CH("HAHAKOMORI"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):DirTo(CH("HAHAKOMORI"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(324, 88, SymAct("HAHAKOMORI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HAHAKOMORI"), 907483107)
  WINDOW:Talk(SymAct("HAHAKOMORI"), 1600768975)
  WINDOW:CloseMessage()
  CH("EEFI"):ResetManpu()
  CH("EEFI"):SetMotion(SymMot("EV011_TIRED03"), LOOP.OFF)
  CH("EEFI"):WaitPlayMotion()
  CH("EEFI"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("EEFI"):DirTo(CH("HAHAKOMORI"), Speed(200), ROT_TYPE.NEAR)
  CH("EEFI"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("EEFI"):SetManpu("MP_FLY_SWEAT")
  CH("EEFI"):WaitManpu()
  WINDOW:DrawFace(72, 16, SymAct("EEFI"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("EEFI"), 1181940366)
  WINDOW:KeyWait()
  CH("EEFI"):SetManpu("MP_FLY_SWEAT")
  WINDOW:Talk(SymAct("EEFI"), 1834985805)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("HAHAKOMORI"):SetManpu("MP_QUESTION")
  CH("HAHAKOMORI"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("HAHAKOMORI"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("HAHAKOMORI"), 1950652428)
  WINDOW:Talk(SymAct("HAHAKOMORI"), 990187211)
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  CH("NOKOTCHI"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("EMONGA"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  CH("BURAKKII"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  CH("EEFI"):SetNeckRot(RotateTarget(0), RotateTarget(-35), RotateTarget(0), TimeSec(0.3))
  WINDOW:DrawFace(72, 16, SymAct("EEFI"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("EEFI"), 572407690)
  WINDOW:CloseMessage()
  TASK:Sleep(TimeSec(0.5))
  CH("EEFI"):ResetNeckRot(TimeSec(0.3))
  CH("EEFI"):WaitNeckRot()
  SOUND:PlayEnv(SymSnd("BGM_EVE_NAZO_01"), Volume(256))
  WINDOW:DrawFace(72, 16, SymAct("EEFI"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("EEFI"), 154365001)
  WINDOW:Talk(SymAct("EEFI"), 271080712)
  WINDOW:Talk(SymAct("EEFI"), -1750056505)
  WINDOW:Talk(SymAct("EEFI"), -1901367162)
  WINDOW:Talk(SymAct("EEFI"), 840444337)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(1), true)
  CAMERA:ResetAzimuthDifferenceVolume()
  FLAG.SceneFlag = CONST.FL_SC_01_END
  FLAG.SCENARIOFLAG = CONST.M08_TAKUSARETAENTERCARD_START
  SYSTEM:NextEntry()
end
function main08_takusaretaentercard01_end()
end
function main08_takusaretaentercard02_init()
end
function main08_takusaretaentercard02_start()
  SOUND:PlayEnv(SymSnd("BGM_EVE_NAZO_01"), Volume(256))
  CUT:Load(SymCut("CUT_M08_100_02_01"))
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  EFFECT:CreateRecollectionFilter()
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
  CAMERA:SetDefaultGroundFovy()
  EFFECT:CreateRecollectionFilter()
  WINDOW:SysMsg(721623280)
  WINDOW:SysMsg(3033907)
  WINDOW:CloseMessage()
  CUT:Load(SymCut("CUT_M08_100_02_02"))
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
  CAMERA:SetDefaultGroundFovy()
  WINDOW:SysMsg(422935154)
  WINDOW:CloseMessage()
  CUT:Load(SymCut("CUT_M08_100_02_03"))
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
  CAMERA:SetDefaultGroundFovy()
  CAMERA:ResetAzimuthDifferenceVolume()
  EFFECT:DestroyRecollectionFilter()
  FLAG.SceneFlag = CONST.FL_SC_02_END
  FLAG.SCENARIOFLAG = CONST.M08_TAKUSARETAENTERCARD_START
  SYSTEM:NextEntry()
end
function main08_takusaretaentercard02_end()
end
function main08_takusaretaentercard02_talk_01()
  WINDOW:Talk(SymAct("EEFI"), 1450503349)
  TASK:Sleep(TimeSec(0.6))
  WINDOW:ForceCloseMessage()
end
function main08_takusaretaentercard02_talk_02()
  WINDOW:SetWaitMode(TimeSec(1), TimeSec(0.1))
  WINDOW:SysMsg(1332731380)
  WINDOW:SysMsg(1682083383)
  TASK:Sleep(TimeSec(1))
  WINDOW:ForceCloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main08_takusaretaentercard02_talk_03()
  WINDOW:SysMsg(2103033718)
  TASK:Sleep(TimeSec(0.6))
  WINDOW:ForceCloseMessage()
end
function main08_takusaretaentercard02_talk_04()
  WINDOW:SysMsg(-87972935)
  TASK:Sleep(TimeSec(1.2))
  WINDOW:ForceCloseMessage()
end
function main08_takusaretaentercard03_init()
end
function main08_takusaretaentercard03_start()
  SOUND:PlayEnv(SymSnd("BGM_EVE_NAZO_01"), Volume(256))
  CAMERA:SetAzimuthDifferenceVolume(Volume(3.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  WINDOW:DrawFace(324, 88, SymAct("EEFI"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("EEFI"), -472214792)
  WINDOW:Talk(SymAct("EEFI"), -1968943404)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(10, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  EFFECT:CreateRecollectionFilter()
  SCREEN_A:FadeIn(TimeSec(0.3), false)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("EEFI"):SetManpu("MP_SHOCK_L")
  WINDOW:DrawFace(324, 20, SymAct("EEFI"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("EEFI"), -1816166507)
  WINDOW:CloseMessage()
  CAMERA:WaitMove()
  SYSTEM:SetForceSyncStop(true)
  TASK:Sleep(TimeSec(0.3))
  WINDOW:SysMsg(-1198379946)
  WINDOW:SysMsg(-1584849641)
  WINDOW:CloseMessage()
  SYSTEM:SetForceSyncStop(false)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("KURUMAYU"):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFace(20, 88, SymAct("KURUMAYU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("KURUMAYU"), -288846896)
  WINDOW:CloseMessage()
  CH("KURUMAYU"):DirTo(RotateTarget(180), Speed(500), ROT_TYPE.NEAR)
  CH("KURUMAYU"):WaitRotate()
  CH("KURUMAYU"):DirTo(RotateTarget(45), Speed(500), ROT_TYPE.NEAR)
  CH("KURUMAYU"):WaitRotate()
  TASK:Sleep(TimeSec(0.1))
  CH("KURUMAYU"):DirTo(RotateTarget(180), Speed(500), ROT_TYPE.NEAR)
  CH("KURUMAYU"):WaitRotate()
  TASK:Sleep(TimeSec(0.1))
  CH("KURUMAYU"):DirTo(RotateTarget(100), Speed(500), ROT_TYPE.NEAR)
  CH("KURUMAYU"):WaitRotate()
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  CH("KURUMAYU"):SetManpu("MP_FLY_SWEAT")
  TASK:Regist(subEveDoubleJump, {
    CH("KURUMAYU")
  })
  WINDOW:DrawFace(20, 88, SymAct("KURUMAYU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("KURUMAYU"), -137119087)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(2.5))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("EEFI"):SetManpu("MP_FLY_SWEAT")
  CH("EEFI"):WaitManpu()
  SYSTEM:SetForceSyncStop(true)
  TASK:Sleep(TimeSec(0.3))
  WINDOW:SysMsg(-587273902)
  WINDOW:SysMsg(-974792685)
  WINDOW:SysMsg(1115538652)
  WINDOW:SysMsg(1533474205)
  WINDOW:SysMsg(-1743658694)
  WINDOW:SysMsg(-2129997701)
  WINDOW:CloseMessage()
  SYSTEM:SetForceSyncStop(false)
  CAMERA:SetAzimuthDifferenceVolume(Volume(3.5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(324, 20, SymAct("EEFI"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("EEFI"), -1440250952)
  WINDOW:Talk(SymAct("EEFI"), -1287867655)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("KURUMAYU"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("KURUMAYU"), -58907586)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(2.5))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.3))
  CH("EEFI"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.NEAR)
  CH("EEFI"):WaitRotate()
  WINDOW:Talk(SymAct("EEFI"), -446294657)
  WINDOW:Talk(SymAct("EEFI"), -833927492)
  WINDOW:CloseMessage()
  subEveNod(CH("EEFI"))
  WINDOW:Talk(SymAct("EEFI"), -682592259)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3.5))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("EEFI"):WalkTo(SymPos("P01_EEFI"), Speed(1))
  CH("EEFI"):WaitMove()
  CH("EEFI"):DirTo(CH("KURUMAYU"), Speed(350), ROT_TYPE.NEAR)
  CH("EEFI"):WaitRotate()
  WINDOW:DrawFace(272, 16, SymAct("EEFI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EEFI"), 1355311922)
  WINDOW:Talk(SymAct("EEFI"), 1238588019)
  WINDOW:CloseMessage()
  CH("KURUMAYU"):DirTo(SymPos("P_TAKARA"), Speed(200), ROT_TYPE.NEAR)
  CH("KURUMAYU"):WaitRotate()
  TASK:Sleep(TimeSec(1))
  CH("KURUMAYU"):DirTo(CH("EEFI"), Speed(200), ROT_TYPE.NEAR)
  CH("KURUMAYU"):WaitRotate()
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 88, SymAct("KURUMAYU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KURUMAYU"), 548243039)
  subEveCloseMsg()
  CH("EEFI"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  TASK:Regist(subEveJump, {
    CH("EEFI")
  })
  WINDOW:DrawFace(272, 16, SymAct("EEFI"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("EEFI"), 968275742)
  WINDOW:Talk(SymAct("EEFI"), 312206557)
  subEveCloseMsg()
  CH("EEFI"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  TASK:Regist(subEveDoubleJump, {
    CH("KURUMAYU")
  })
  WINDOW:DrawFace(20, 88, SymAct("KURUMAYU"), FACE_TYPE.EMOTION)
  WINDOW:Talk(SymAct("KURUMAYU"), 192992668)
  WINDOW:CloseMessage()
  TASK:Regist(subEveNod, {
    CH("EEFI")
  })
  WINDOW:DrawFace(272, 16, SymAct("EEFI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EEFI"), 1153516379)
  WINDOW:CloseMessage()
  CH("EEFI"):DirTo(SymPos("P_TAKARA"), Speed(350), ROT_TYPE.NEAR)
  CH("EEFI"):WaitRotate()
  WINDOW:DrawFace(272, 16, SymAct("EEFI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EEFI"), 1574597146)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CH("KURUMAYU"):DirTo(SymPos("P_TAKARA"), Speed(200), ROT_TYPE.NEAR)
  CH("KURUMAYU"):WaitRotate()
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 88, SymAct("KURUMAYU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KURUMAYU"), 1995907545)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3.5))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("EEFI"):DirTo(CH("KURUMAYU"), Speed(200), ROT_TYPE.NEAR)
  CH("EEFI"):WaitRotate()
  CH("KURUMAYU"):DirTo(CH("EEFI"), Speed(200), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.3))
  TASK:Regist(subEveNod, {
    CH("EEFI")
  })
  WINDOW:DrawFace(272, 16, SymAct("EEFI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EEFI"), 1877741720)
  WINDOW:Talk(SymAct("EEFI"), -395047849)
  WINDOW:Talk(SymAct("EEFI"), -244368106)
  WINDOW:KeyWait()
  CH("EEFI"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(272, 16, SymAct("EEFI"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("EEFI"), -1116029210)
  subEveCloseMsg()
  CH("EEFI"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  TASK:Regist(subEveJump, {
    CH("KURUMAYU")
  })
  WINDOW:DrawFace(20, 88, SymAct("KURUMAYU"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("KURUMAYU"), -1537110105)
  WINDOW:Talk(SymAct("KURUMAYU"), -1890788252)
  WINDOW:Talk(SymAct("KURUMAYU"), -1772622555)
  subEveCloseMsg()
  CH("EEFI"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  TASK:Regist(subEveNod, {
    CH("EEFI")
  })
  WINDOW:DrawFace(272, 16, SymAct("EEFI"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("EEFI"), -652837918)
  subEveCloseMsg()
  CH("EEFI"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  SOUND:PlaySe(SymSnd("SE_EVT_GASAGASA"), Volume(256))
  WINDOW:SetWaitMode(TimeSec(1), TimeSec(0.5))
  WINDOW:SysMsg(-1072870749)
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("EEFI"):SetManpu("MP_EXCLAMATION")
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CH("EEFI"):DirTo(RotateTarget(-135), Speed(500), ROT_TYPE.NEAR)
  CH("EEFI"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("EEFI"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("EEFI"), -350217888)
  WINDOW:Talk(SymAct("EEFI"), -231004127)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3.5))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("EEFI"):DirTo(CH("KURUMAYU"), Speed(500), ROT_TYPE.NEAR)
  CH("EEFI"):WaitRotate()
  WINDOW:DrawFace(272, 16, SymAct("EEFI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EEFI"), 1973630190)
  WINDOW:Talk(SymAct("EEFI"), 1823999407)
  subEveCloseMsg()
  TASK:Regist(subEveJump, {
    CH("KURUMAYU")
  })
  WINDOW:DrawFace(20, 88, SymAct("KURUMAYU"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("KURUMAYU"), 96917891)
  WINDOW:CloseMessage()
  CH("EEFI"):DirTo(RotateTarget(100), Speed(500), ROT_TYPE.NEAR)
  CH("EEFI"):WaitRotate()
  CAMERA:MoveFollow(SymCam("CAMERA_01"), Speed(0.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("EEFI"):WalkTo(SymPos("P02_EEFI"), Speed(1.5))
  CH("EEFI"):WaitMove()
  TASK:Sleep(TimeSec(0.8))
  CH("EEFI"):DirTo(CH("KURUMAYU"), Speed(500), ROT_TYPE.NEAR)
  CH("EEFI"):WaitRotate()
  WINDOW:DrawFace(324, 20, SymAct("EEFI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EEFI"), 484305090)
  WINDOW:CloseMessage()
  CH("EEFI"):RunTo(SymPos("P03_EEFI"), Speed(3))
  CH("EEFI"):WaitMove()
  CH("EEFI"):SetVisible(false)
  TASK:Sleep(TimeSec(1))
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CH("KURUMAYU"):DirTo(SymPos("P_TAKARA"), Speed(350), ROT_TYPE.NEAR)
  CH("KURUMAYU"):WaitRotate()
  CH("KURUMAYU"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  CH("KURUMAYU"):SetManpu("MP_SPREE_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("KURUMAYU")
  })
  WINDOW:Talk(SymAct("KURUMAYU"), 938523393)
  WINDOW:CloseMessage()
  CH("KURUMAYU"):ResetManpu()
  subEveDoubleJump(CH("KURUMAYU"))
  TASK:Sleep(TimeSec(0.5))
  CH("KURUMAYU"):SetMotionRaito(Raito(1.5))
  CH("KURUMAYU"):SetMotion(SymMot("VICTORY"), LOOP.OFF)
  CH("KURUMAYU"):WaitPlayMotion()
  CH("KURUMAYU"):SetMotionRaito(Raito(1))
  SYSTEM:SetForceSyncStop(true)
  TASK:Sleep(TimeSec(0.3))
  WINDOW:SysMsg(787188288)
  WINDOW:SysMsg(1638538375)
  WINDOW:CloseMessage()
  SOUND:FadeOutEnv(TimeSec(2.5))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  SYSTEM:SetForceSyncStop(false)
  CAMERA:ResetAzimuthDifferenceVolume()
  EFFECT:DestroyRecollectionFilter()
  FLAG.SceneFlag = CONST.FL_SC_03_END
  FLAG.SCENARIOFLAG = CONST.M08_TAKUSARETAENTERCARD_START
  SYSTEM:NextEntry()
end
function main08_takusaretaentercard03_end()
end
function main08_takusaretaentercard04_init()
  if FLAG.NowResumeFlag == CONST.FLAG_TRUE then
    subEveFromProgFadeSet()
    subSaveflagM08_100_04()
  end
end
function main08_takusaretaentercard04_start()
  GIMMICK:SetVisible(SymLayer("SHOP_CHEST"), false)
  CH("DOTEKKOTSU"):SetMotionBlendMode(BlendMode.NONE)
  CH("BIRIJION"):SetMotionBlendMode(BlendMode.NONE)
  CH("HAADERIA"):SetMotionBlendMode(BlendMode.NONE)
  CH("MINEZUMI"):SetMotionBlendMode(BlendMode.NONE)
  CH("SUWANNA"):SetMotionBlendMode(BlendMode.NONE)
  CH("EEFI"):SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  CH("BURAKKII"):SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  CH("HERO"):SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  CH("PARTNER"):SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  CH("EMONGA"):SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  CH("NOKOTCHI"):SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  CH("HAHAKOMORI"):SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  CH("KURUMAYU"):SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  subEveFadeAfterTime()
  WINDOW:DrawFace(72, 16, SymAct("EEFI"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("EEFI"), 2024877510)
  WINDOW:Talk(SymAct("EEFI"), 1402764805)
  WINDOW:Talk(SymAct("EEFI"), 1250381636)
  WINDOW:Talk(SymAct("EEFI"), -853585013)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("EMONGA"):SetManpu("MP_SHOCK_L")
  CH("HAADERIA"):SetManpu("MP_SHOCK_R")
  CH("KURUMAYU"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("HAHAKOMORI"):SetManpu("MP_SHOCK_L")
  CH("NOKOTCHI"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFaceF(272, 16, SymAct("HAADERIA"), FACE_TYPE.CATCHBREATH)
  WINDOW:DrawFaceOffset(20, 0)
  WINDOW:Talk(SymAct("HAADERIA"), -737910070)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("EEFI"):SetManpu("MP_FLY_SWEAT")
  CH("EEFI"):WaitManpu()
  WINDOW:DrawFace(72, 16, SymAct("EEFI"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("EEFI"), 393442925)
  WINDOW:Talk(SymAct("EEFI"), 241714988)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:SwitchTalk({PARTNER_0 = 625284335, PARTNER_1 = 1012802990})
  WINDOW:SwitchTalk({PARTNER_0 = 1931457385, PARTNER_1 = 1778680360})
  WINDOW:SwitchTalk({PARTNER_0 = 1093259755, PARTNER_1 = 1479729322})
  subEveCloseMsg()
  WINDOW:DrawFace(72, 16, SymAct("EEFI"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("EEFI"), -542442395)
  WINDOW:Talk(SymAct("EEFI"), -961426140)
  WINDOW:Talk(SymAct("EEFI"), -1345384184)
  WINDOW:Talk(SymAct("EEFI"), -1227612087)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("EEFI"):SetManpu("MP_FLY_SWEAT")
  CH("EEFI"):SetNeckRot(RotateTarget(0), RotateTarget(-35), RotateTarget(0), TimeSec(0.2))
  CH("EEFI"):WaitNeckRot()
  WINDOW:DrawFace(72, 16, SymAct("EEFI"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("EEFI"), -1644596342)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_00_5"))
  CAMERA:SetTgt(SymCam("CAMERA_00_5"))
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_HOPE_L1"), Volume(256))
  TASK:Regist(subEveMoveDir, {
    CH("KURUMAYU"),
    SymPos("P01_KURUMAYU"),
    Speed(1.5),
    CH("EEFI")
  })
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(subEveMoveDir, {
    CH("HAHAKOMORI"),
    SymPos("P01_HAHAKOMORI"),
    Speed(1.5),
    CH("EEFI")
  })
  TASK:WaitTask()
  WINDOW:DrawFace(324, 88, SymAct("HAHAKOMORI"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("HAHAKOMORI"), -2065546549)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH("KURUMAYU"))
  WINDOW:DrawFace(226, 8, SymAct("KURUMAYU"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("KURUMAYU"), -878455796)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("HAHAKOMORI"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("HAHAKOMORI"), -759634611)
  WINDOW:Talk(SymAct("HAHAKOMORI"), -107628914)
  WINDOW:Talk(SymAct("HAHAKOMORI"), -527530033)
  WINDOW:Talk(SymAct("HAHAKOMORI"), 1729534720)
  WINDOW:Talk(SymAct("HAHAKOMORI"), 2114824769)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("EEFI"):SetManpu("MP_FLY_SWEAT_LP")
  CH("EEFI"):SetMotionRaito(Raito(0.5))
  CH("EEFI"):SetMotion(SymMot("EV008_CRY00"), LOOP.OFF)
  CH("EEFI"):WaitPlayMotion()
  CH("EEFI"):SetMotionRaito(Raito(1))
  CH("EEFI"):SetMotion(SymMot("EV008_CRY01"), LOOP.ON)
  WINDOW:DrawFace(20, 20, SymAct("EEFI"), FACE_TYPE.WEEP)
  WINDOW:Talk(SymAct("EEFI"), -139722402)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 88, SymAct("BURAKKII"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("BURAKKII"), -289984481)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.TEARS)
  WINDOW:SwitchTalk({PARTNER_0 = -979737636, PARTNER_1 = -595504483})
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.5))
  WINDOW:DrawFace(118, 8, SymAct("SUWANNA"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("SUWANNA"), -1816083366)
  WINDOW:CloseMessage()
  CH("SUWANNA"):DirTo(CH("BURAKKII"), Speed(200), ROT_TYPE.NEAR)
  CH("SUWANNA"):WaitRotate()
  WINDOW:DrawFace(118, 8, SymAct("SUWANNA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SUWANNA"), -1965296357)
  WINDOW:CloseMessage()
  CH("BURAKKII"):DirTo(CH("SUWANNA"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HAADERIA"):DirTo(CH("BURAKKII"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("DOTEKKOTSU"):DirTo(CH("BURAKKII"), Speed(200), ROT_TYPE.NEAR)
  CH("BURAKKII"):WaitRotate()
  WINDOW:DrawFace(118, 8, SymAct("SUWANNA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SUWANNA"), -1577670952)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BURAKKII"), -1192388711)
  WINDOW:Talk(SymAct("BURAKKII"), 1064667990)
  WINDOW:Talk(SymAct("BURAKKII"), 644790807)
  WINDOW:Talk(SymAct("BURAKKII"), 1326474811)
  WINDOW:CloseMessage()
  subEveNod(CH("DOTEKKOTSU"))
  WINDOW:DrawFace(72, 16, SymAct("DOTEKKOTSU"), FACE_TYPE.NORMAL)
  WINDOW:DrawFaceOffset(-10, 0)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), 1443583866)
  subEveCloseMsg()
  WINDOW:DrawFace(118, 8, SymAct("SUWANNA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SUWANNA"), 2099643577)
  WINDOW:CloseMessage()
  subEveJump(CH("BURAKKII"))
  WINDOW:DrawFace(324, 88, SymAct("BURAKKII"), FACE_TYPE.EMOTION)
  WINDOW:Talk(SymAct("BURAKKII"), 1681733112)
  WINDOW:Talk(SymAct("BURAKKII"), 729588543)
  subEveCloseMsg()
  WINDOW:DrawFace(118, 8, SymAct("SUWANNA"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("SUWANNA"), 845648510)
  WINDOW:CloseMessage()
  subEveNod(CH("BURAKKII"))
  WINDOW:DrawFace(324, 88, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BURAKKII"), 424329661)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(2.5))
  SCREEN_A:FadeOut(TimeSec(1.5), true)
  SOUND:WaitBgm()
  TASK:Sleep(TimeSec(0.5))
  CAMERA:ResetAzimuthDifferenceVolume()
  subSaveflagM08_100_04()
end
function main08_takusaretaentercard04_end()
end
function subSaveflagM08_100_04()
  FLAG.SceneFlag = CONST.FL_SC_01_FIRST
  FLAG.SCENARIOFLAG = CONST.M08_TAKUSARETAENTERCARD_END
  SYSTEM:NextEntry()
end
function groundEnd()
end

