dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main16_chimyakuairobosswin01_init()
  if FLAG.NowResumeFlag == CONST.FLAG_TRUE then
    subEveFromProgFadeSet()
    subSaveflagM16_140_01()
  end
end
function main16_chimyakuairobosswin01_start()
  subEveFromProgFadeSet()
  TASK:Sleep(TimeSec(1))
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("EEFI"):SetVisible(false)
  CH("PARTNER"):SetVisible(false)
  CH("SHANDERA_1"):SetVisible(false)
  CH("BOOMANDA_H"):SetMotion(SymMot("EV013_BREATH01"), LOOP.ON, TimeSec(0))
  CH("SHANDERA_1"):SetMotion(SymMot("ENDURE"), LOOP.ON, TimeSec(0))
  CH("SHANDERA_2"):SetMotion(SymMot("ENDURE"), LOOP.ON, TimeSec(0))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  CAMERA:MoveFollow2(SymCam("CAMERA_00_5"), Speed(8, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  EFFECT:StartMotionBlur(0.01, 0.5, 0)
  SCREEN_A:FadeIn(TimeSec(0.5), false)
  SOUND:PlaySe(SymSnd("SE_EVT_BOOMANDA_PAIN"), Volume(256))
  WINDOW:SysMsg(177059129)
  TASK:Sleep(TimeSec(1.5))
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  CAMERA:WaitMove()
  WINDOW:ForceCloseMessage()
  EFFECT:EndMotionBlur()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("SHANDERA_1"):SetVisible(true)
  CH("PARTNER"):SetVisible(true)
  WINDOW:Talk(SymAct("SHANDERA_1"), 328631416)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CH("BOOMANDA_H"):SetMotionRaito(Raito(0.5))
  CH("BOOMANDA_H"):SetMotion(SymMot("FALL"), LOOP.OFF, TimeSec(0.5))
  TASK:Sleep(TimeSec(0.2))
  CH("SHANDERA_1"):SetMotion(SymMot("FALL"), LOOP.OFF)
  TASK:Sleep(TimeSec(0.1))
  CH("SHANDERA_2"):SetMotion(SymMot("FALL"), LOOP.OFF)
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_KOMATANA_DOWN"), Volume(256))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_KOMATANA_DOWN"), Volume(256))
  TASK:Sleep(TimeSec(0.6))
  CH("BOOMANDA_H"):SetMotion(SymMot("EV016_FALLLOOP"), LOOP.ON, TimeSec(0))
  CH("SHANDERA_1"):SetMotion(SymMot("EV016_FALLLOOP"), LOOP.ON, TimeSec(0.3))
  CH("SHANDERA_2"):SetMotion(SymMot("EV016_FALLLOOP"), LOOP.ON, TimeSec(0.3))
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  TASK:Sleep(TimeSec(0.8))
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 951834555, PARTNER_1 = 564193018})
  WINDOW:SwitchTalk({PARTNER_0 = 1860268093, PARTNER_1 = 2012889468})
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 88, SymAct("EMONGA"), FACE_TYPE.SPECIAL01)
  WINDOW:Talk(SymAct("EMONGA"), 1557598911)
  WINDOW:Talk(SymAct("EMONGA"), 1171006462)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow(SymCam("CAMERA_04"), Speed(3, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("EMONGA"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("EMONGA"):WaitRotate()
  CH("HERO"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  CH("BIRIJION"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  CAMERA:WaitMove()
  TASK:Regist(subEveDoubleJump, {
    CH("EMONGA")
  })
  WINDOW:DrawFace(324, 88, SymAct("EMONGA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EMONGA"), -1034666191)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CH("SHANDERA_2"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.5))
  TASK:Sleep(TimeSec(0.5))
  CH("SHANDERA_2"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  CH("SHANDERA_2"):WaitRotate()
  CH("SHANDERA_2"):WalkTo(SymPos("P01_SHANDERA_2"), Speed(1))
  TASK:Sleep(TimeSec(0.3))
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_03_5"))
  CAMERA:SetTgt(SymCam("CAMERA_03_5"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_01"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  CH("BIRIJION"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  WINDOW:Talk(SymAct("BIRIJION"), -615575952)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CH("EMONGA"):DirTo(RotateTarget(160), Speed(500), ROT_TYPE.NEAR)
  EFFECT:StartMotionBlur(0, 0, 0)
  EFFECT:ChangeMotionBlurLevel(0.04, TimeSec(0.05))
  EFFECT:ChangeMotionBlurAlpha(0.9, TimeSec(0.05))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  CH("SHANDERA_2"):SetMotion(SymMot("CHARGE"), LOOP.ON)
  SOUND:PlaySe(SymSnd("SE_EVT_SHANDERA_THREAT"), Volume(256))
  WINDOW:SysMsg(-1817410723)
  TASK:Sleep(TimeSec(0.3))
  WINDOW:ForceCloseMessage()
  CH("EMONGA"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("EMONGA"):SetManpu("MP_SHOCK_R")
  CH("EMONGA"):WalkTo(SymPos("P01_EMONGA"), Speed(2), LINK_DIR.OFF)
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("EMONGA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("EMONGA"), -1967672804)
  TASK:Sleep(TimeSec(0.3))
  WINDOW:ForceCloseMessage()
  SCREEN_A:WhiteOut(TimeSec(0.1), true)
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  EFFECT:EndMotionBlur()
  SOUND:PlaySe(SymSnd("SE_EVT_DOSHU"), Volume(256))
  WINDOW:SysMsg(-1583685153)
  TASK:Sleep(TimeSec(0.7))
  WINDOW:ForceCloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CH("SHANDERA_2"):SetMotion(SymMot("ENDURE"), LOOP.ON, TimeSec(0))
  CH("EEFI"):SetVisible(true)
  CH("SHANDERA_2"):SetMotion(SymMot("FALL"), LOOP.OFF)
  SCREEN_A:WhiteIn(TimeSec(0.1), true)
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_KOMATANA_DOWN"), Volume(128))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  CH("SHANDERA_2"):SetManpu("MP_SHOCK_L")
  WINDOW:Talk(SymAct("SHANDERA_1"), -1199452002)
  TASK:Sleep(TimeSec(0.2))
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(1.5))
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:Talk(SymAct("EEFI"), -138394023)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("HERO"):SetDir(CH("EEFI"))
  CH("PARTNER"):SetDir(CH("EEFI"))
  CH("BIRIJION"):SetDir(CH("EEFI"))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -287607016, PARTNER_1 = -973724453})
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  SOUND:PlayBgm(SymSnd("BGM_EVE_OKUSOKO_01"), Volume(256))
  CH("EEFI"):WalkTo(SplinePath(SymPos("P01_EEFI"), SymPos("P02_EEFI"), SymPos("P03_EEFI")), Speed(1.5))
  TASK:Sleep(TimeSec(0.3))
  CH("EMONGA"):DirTo(SymPos("P03_EEFI"), Speed(60), ROT_TYPE.NEAR)
  CH("HERO"):DirTo(SymPos("P03_EEFI"), Speed(60), ROT_TYPE.NEAR)
  CH("PARTNER"):DirTo(SymPos("P03_EEFI"), Speed(60), ROT_TYPE.NEAR)
  CH("BIRIJION"):DirTo(SymPos("P03_EEFI"), Speed(60), ROT_TYPE.NEAR)
  CH("EMONGA"):WaitRotate()
  TASK:Regist(subEveDoubleJump, {
    CH("EMONGA")
  })
  WINDOW:DrawFace(324, 88, SymAct("EMONGA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("EMONGA"), -588442214)
  WINDOW:CloseMessage()
  CH("EMONGA"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.NEAR)
  CH("EMONGA"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("EMONGA"):SetManpu("MP_FLY_SWEAT")
  CH("EMONGA"):WaitManpu()
  CH("EMONGA"):SetFacialMotion(FACIAL_MOTION.RELIEF)
  WINDOW:DrawFace(324, 88, SymAct("EMONGA"), FACE_TYPE.RELIEF)
  WINDOW:Talk(SymAct("EMONGA"), 1534396757)
  WINDOW:CloseMessage()
  CH("EEFI"):WaitMove()
  CH("EMONGA"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  CH("EMONGA"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(272, 16, SymAct("EEFI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EEFI"), 1114519572)
  WINDOW:Talk(SymAct("EEFI"), -2129056589)
  WINDOW:Talk(SymAct("EEFI"), -1744691726)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CH("EEFI"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_NOTICE_R")
  TASK:Sleep(TimeSec(0.1))
  CH("BIRIJION"):SetManpu("MP_NOTICE_R")
  CH("EEFI"):WaitRotate()
  CH("EEFI"):WalkTo(PosOffs(0, -0.2), Speed(1.5))
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.THINK)
  WINDOW:SwitchTalk({PARTNER_0 = -1288745423, PARTNER_1 = -1439400080})
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  TASK:Sleep(TimeSec(0.3))
  CH("EEFI"):WaitMove()
  CH("EEFI"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("EEFI"):WaitRotate()
  WINDOW:DrawFace(272, 16, SymAct("EEFI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EEFI"), -445257289)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  CH("EMONGA"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("BIRIJION"):SetManpu("MP_EXCLAMATION")
  CH("BIRIJION"):WaitManpu()
  WINDOW:DrawFace(20, 20, SymAct("BIRIJION"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("BIRIJION"), -59844362)
  subEveCloseMsg()
  TASK:Regist(subEveDoubleJump, {
    CH("EMONGA")
  })
  WINDOW:DrawFace(324, 88, SymAct("EMONGA"), FACE_TYPE.EMOTION)
  WINDOW:Talk(SymAct("EMONGA"), -683439307)
  WINDOW:Talk(SymAct("EMONGA"), -833045900)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("EEFI"):SetManpu("MP_FLY_SWEAT")
  CH("EEFI"):WaitManpu()
  WINDOW:DrawFace(272, 16, SymAct("EEFI"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("EEFI"), 1237362363)
  WINDOW:DrawFace(272, 16, SymAct("EEFI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EEFI"), 1356568570)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  TASK:Regist(subEveMoveDir2, {
    CH("EEFI"),
    SymPos("P04_EEFI"),
    Speed(1.5),
    RotateTarget(180)
  })
  TASK:Sleep(TimeSec(1))
  CH("PARTNER"):DirTo(CH("HERO"), Speed(200), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("PARTNER"), Speed(200), ROT_TYPE.NEAR)
  CH("BIRIJION"):DirTo(CH("HERO"), Speed(200), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("EMONGA"):DirTo(CH("PARTNER"), Speed(200), ROT_TYPE.NEAR)
  CH("EMONGA"):WaitRotate()
  TASK:Sleep(TimeSec(1))
  CH("EMONGA"):WalkTo(SplinePath(SymPos("P02_EMONGA"), SymPos("P03_EMONGA")), Speed(1.5))
  TASK:Sleep(TimeSec(0.3))
  CH("HERO"):WalkTo(SplinePath(SymPos("P01_HERO"), SymPos("P02_HERO")), Speed(1.5))
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):WalkTo(SplinePath(SymPos("P01_PARTNER"), SymPos("P02_PARTNER")), Speed(1.5))
  TASK:Regist(subEveMoveDir2, {
    CH("BIRIJION"),
    SymPos("P01_BIRIJION"),
    Speed(1.5),
    RotateTarget(180)
  })
  SOUND:FadeOutBgm(TimeSec(2.5))
  TASK:Sleep(TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(1), true)
  TASK:Sleep(TimeSec(0.5))
  SYSTEM:UpdateNextDayParameter()
  subSaveflagM16_140_01()
end
function main16_chimyakuairobosswin01_end()
end
function subSaveflagM16_140_01()
  FLAG.SceneFlag = CONST.FL_SC_01_FIRST
  FLAG.SCENARIOFLAG = CONST.M16_CHIMYAKUAIROBOSSWIN_END
  SYSTEM:NextEntry()
end
function groundEnd()
end

