dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main03_arehatedaniclear1st01_init()
end
function main03_arehatedaniclear1st01_start()
  CHARA:SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  subEveFromProgFadeSet()
  TASK:Sleep(TimeSec(1))
  CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("KOMATANA_1"):SetMotion(SymMot("ENDURE"), LOOP.ON)
  CH("FUSHIDE_2"):SetMotion(SymMot("ENDURE"), LOOP.ON)
  CH("DENCHURA_1"):SetMotion(SymMot("ENDURE"), LOOP.ON)
  TASK:Sleep(TimeSec(0.1))
  CH("KOMATANA_2"):SetMotion(SymMot("ENDURE"), LOOP.ON)
  CH("FUSHIDE_1"):SetMotion(SymMot("ENDURE"), LOOP.ON)
  CH("DENCHURA_2"):SetMotion(SymMot("ENDURE"), LOOP.ON)
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  subEveFadeAfterTime()
  WINDOW:DrawFace(20, 88, SymAct("KOMATANA_1"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("KOMATANA_1"), 171974989)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("KOMATANA_2"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("KOMATANA_2"), 324734988)
  WINDOW:KeyWait()
  local taskGubaa = function()
    CH("KOMATANA_1"):SetMotion(SymMot("FALL"), LOOP.OFF)
    TASK:Sleep(TimeSec(0.2))
    CH("KOMATANA_2"):SetMotion(SymMot("FALL"), LOOP.OFF)
    CH("KOMATANA_1"):WaitPlayMotion()
    SOUND:PlaySe(SymSnd("SE_EVT_KOMATANA_DOWN"), Volume(190))
    CH("KOMATANA_2"):WaitPlayMotion()
    SOUND:PlaySe(SymSnd("SE_EVT_KOMATANA_DOWN"), Volume(190))
    CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
    TASK:Sleep(TimeSec(0.5))
    CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  end
  TASK:Regist(taskGubaa)
  WINDOW:DrawFace(324, 88, SymAct("KOMATANA_2"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("KOMATANA_2"), 947274703)
  TASK:Sleep(TimeSec(0.7))
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  CH("FUSHIDE_1"):DirTo(CH("DENCHURA_2"), Speed(350), ROT_TYPE.NEAR)
  CH("FUSHIDE_2"):DirTo(CH("DENCHURA_1"), Speed(350), ROT_TYPE.NEAR)
  CH("DENCHURA_1"):DirTo(CH("FUSHIDE_2"), Speed(350), ROT_TYPE.NEAR)
  CH("DENCHURA_2"):DirTo(CH("FUSHIDE_1"), Speed(350), ROT_TYPE.NEAR)
  CH("DENCHURA_2"):WaitRotate()
  TASK:Sleep(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("FUSHIDE_1"):SetManpu("MP_FLY_SWEAT")
  CH("FUSHIDE_2"):SetManpu("MP_FLY_SWEAT")
  CH("DENCHURA_1"):SetManpu("MP_FLY_SWEAT")
  CH("DENCHURA_2"):SetManpu("MP_FLY_SWEAT")
  CH("DENCHURA_2"):WaitManpu()
  WINDOW:Talk(SymWord(-332728183), 560820878)
  WINDOW:Talk(SymWord(-332728183), 1848435785)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_RUN_ESCAPE_02"), Volume(256))
  CH("DENCHURA_1"):RunTo(SymPos("P00_EXIT"), Speed(6))
  CH("DENCHURA_2"):RunTo(SymPos("P01_EXIT"), Speed(6))
  CH("FUSHIDE_1"):RunTo(SymPos("P00_EXIT"), Speed(6))
  CH("FUSHIDE_2"):RunTo(SymPos("P01_EXIT"), Speed(6))
  CH("FUSHIDE_2"):WaitMove()
  CH("DENCHURA_1"):SetVisible(false)
  CH("DENCHURA_2"):SetVisible(false)
  CH("FUSHIDE_1"):SetVisible(false)
  CH("FUSHIDE_2"):SetVisible(false)
  CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  TASK:Sleep(TimeSec(0.3))
  CH("KOMATANA_2"):SetMotion(SymMot("PAIN"), LOOP.ON, TimeSec(0.4))
  TASK:Sleep(TimeSec(0.5))
  WINDOW:DrawFace(324, 88, SymAct("KOMATANA_2"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("KOMATANA_2"), 2000147720)
  WINDOW:CloseMessage()
  CH("KOMATANA_1"):SetMotion(SymMot("PAIN"), LOOP.ON, TimeSec(0.4))
  WINDOW:DrawFace(20, 88, SymAct("KOMATANA_1"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("KOMATANA_1"), 1545242315)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  TASK:Regist(subEveJumpSurprise, {
    CH("KOMATANA_1")
  })
  TASK:Regist(subEveJumpSurprise, {
    CH("KOMATANA_2")
  })
  WINDOW:DrawFace(324, 88, SymAct("KOMATANA_2"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("KOMATANA_2"), 1157740426)
  TASK:WaitTask()
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("KOMATANA_1"):SetManpu("MP_FLY_SWEAT")
  subEveJumpSurprise(CH("KOMATANA_1"))
  WINDOW:DrawFace(20, 88, SymAct("KOMATANA_1"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("KOMATANA_1"), -1030116539)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_RUN_ESCAPE_02"), Volume(256))
  CH("KOMATANA_1"):RunTo(SymPos("P00_EXIT"), Speed(6))
  CH("KOMATANA_2"):RunTo(SymPos("P01_EXIT"), Speed(6))
  CH("KOMATANA_2"):WaitMove()
  CH("KOMATANA_1"):SetVisible(false)
  CH("KOMATANA_2"):SetVisible(false)
  TASK:Sleep(TimeSec(0.5))
  local taskAllAttention = function(who)
    CH("PARTNER"):DirTo(who, Speed(350), ROT_TYPE.NEAR)
    CH("NOKOTCHI"):DirTo(who, Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("HERO"):DirTo(who, Speed(350), ROT_TYPE.NEAR)
    CH("DOTEKKOTSU"):DirTo(who, Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("BIRIJION"):DirTo(who, Speed(350), ROT_TYPE.NEAR)
    CH("DOKKORAA_1"):DirTo(who, Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("EMONGA"):DirTo(who, Speed(350), ROT_TYPE.NEAR)
    CH("DOKKORAA_2"):DirTo(who, Speed(350), ROT_TYPE.NEAR)
  end
  CAMERA:SetAzimuthDifferenceVolume(Volume(2.5))
  CAMERA:SetEye(SymCam("CAMERA_10"))
  CAMERA:SetTgt(SymCam("CAMERA_10"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(324, 88, SymAct("EMONGA"), FACE_TYPE.EMOTION)
  WINDOW:Talk(SymAct("EMONGA"), -612197884)
  WINDOW:Talk(SymAct("EMONGA"), 798844991)
  WINDOW:KeyWait()
  SOUND:PlayBgm(SymSnd("BGM_EVE_CLEAR"), Volume(256))
  CH("EMONGA"):SetFacialMotion(FACIAL_MOTION.GLADNESS)
  CH("EMONGA"):SetManpu("MP_SPREE_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("EMONGA")
  })
  WINDOW:DrawFace(324, 88, SymAct("EMONGA"), FACE_TYPE.GLADNESS)
  WINDOW:Talk(SymAct("EMONGA"), 914774398)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.3))
  CH("HERO"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  CH("EMONGA"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("NOKOTCHI"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("BIRIJION"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("DOTEKKOTSU"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("DOKKORAA_1"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("DOKKORAA_2"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  CH("PARTNER"):SetManpu("MP_SPREE_LP")
  CH("PARTNER"):SetMotion(SymMot("WAIT00"), LOOP.ON)
  CH("PARTNER"):SetMotionRaito(Raito(2))
  CH("DOKKORAA_2"):SetManpu("MP_SPREE_LP")
  CH("NOKOTCHI"):SetMotion(SymMot("WALK"), LOOP.ON)
  CH("NOKOTCHI"):SetMotionRaito(Raito(2))
  CH("EMONGA"):SetMotion(SymMot("WAIT00"), LOOP.ON)
  CH("EMONGA"):SetMotionRaito(Raito(2))
  CH("HERO"):SetMotion(SymMot("WAIT00"), LOOP.ON)
  CH("HERO"):SetMotionRaito(Raito(2))
  CH("DOTEKKOTSU"):SetMotion(SymMot("VICTORY"), LOOP.OFF)
  CH("DOTEKKOTSU"):WaitPlayMotion()
  CH("DOTEKKOTSU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("DOTEKKOTSU"):SetManpu("MP_LAUGH_LP")
  TASK:Sleep(TimeSec(3))
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  CH("PARTNER"):ResetManpu()
  CH("PARTNER"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("PARTNER"):SetMotionRaito(Raito(1))
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("HERO"):SetMotionRaito(Raito(1))
  CH("DOKKORAA_2"):ResetManpu()
  TASK:Sleep(TimeSec(0.2))
  CH("DOTEKKOTSU"):ResetManpu()
  CH("NOKOTCHI"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("NOKOTCHI"):SetMotionRaito(Raito(1))
  TASK:Sleep(TimeSec(0.1))
  CH("EMONGA"):ResetManpu()
  CH("EMONGA"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("EMONGA"):SetMotionRaito(Raito(1))
  CH("EMONGA"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CH("PARTNER"):DirTo(CH("DOTEKKOTSU"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("HERO"):DirTo(CH("DOTEKKOTSU"), Speed(350), ROT_TYPE.NEAR)
  CH("EMONGA"):DirTo(CH("BIRIJION"), Speed(350), ROT_TYPE.NEAR)
  CH("NOKOTCHI"):DirTo(CH("DOTEKKOTSU"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(324, 20, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 497748669, PARTNER_1 = 78658556})
  WINDOW:CloseMessage()
  local taskLookAround01 = function()
    CH("PARTNER"):DirTo(CH("BIRIJION"), Speed(350), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    CH("PARTNER"):DirTo(CH("DOTEKKOTSU"), Speed(350), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
  end
  taskLookAround01()
  WINDOW:DrawFace(324, 20, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 1274129723, PARTNER_1 = 1391107194})
  subEveCloseMsg()
  CH("DOTEKKOTSU"):DirTo(CH("BIRIJION"), Speed(350), ROT_TYPE.NEAR)
  CH("DOTEKKOTSU"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("DOTEKKOTSU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), 2043137977)
  WINDOW:KeyWait()
  CH("HERO"):DirTo(CH("BIRIJION"), Speed(200), ROT_TYPE.NEAR)
  CH("PARTNER"):DirTo(CH("BIRIJION"), Speed(200), ROT_TYPE.NEAR)
  CH("NOKOTCHI"):DirTo(CH("BIRIJION"), Speed(200), ROT_TYPE.NEAR)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), 1625095928)
  WINDOW:CloseMessage()
  WINDOW:DrawFace(324, 20, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -414916041, PARTNER_1 = -27274378})
  subEveCloseMsg()
  WINDOW:DrawFace(72, 16, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), 1026082769)
  WINDOW:Talk(SymAct("BIRIJION"), 607385232)
  WINDOW:Talk(SymAct("BIRIJION"), 253666643)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 20, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 369464338, PARTNER_1 = 1497629397})
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3.5))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("NOKOTCHI"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  CH("NOKOTCHI"):WaitRotate()
  CH("NOKOTCHI"):SetMotion(SymMot("FALL"), LOOP.OFF)
  CH("NOKOTCHI"):SetNextMotion(SymMot("EV000_FALLLOOP"), LOOP.ON, TimeSec(0))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("NOKOTCHI"):SetManpu("MP_FLY_SWEAT")
  CH("NOKOTCHI"):WaitManpu()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("EMONGA"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):SetManpu("MP_NOTICE_L")
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("NOKOTCHI"), 1079980948)
  taskAllAttention(CH("NOKOTCHI"))
  CH("EMONGA"):WalkTo(SymPos("P01_EMONGA"), Speed(2))
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):WalkTo(SymPos("P01_PARTNER"), Speed(1.5))
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):WalkTo(SymPos("P01_HERO"), Speed(1.5))
  CH("HERO"):WaitMove()
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("EMONGA"):SetManpu("MP_FLY_SWEAT")
  CH("EMONGA"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("EMONGA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("EMONGA"), 1802657879)
  subEveCloseMsg()
  CH("NOKOTCHI"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("NOKOTCHI"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  CH("NOKOTCHI"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("NOKOTCHI"), 1919504662)
  WINDOW:Talk(SymAct("NOKOTCHI"), -168735271)
  WINDOW:Talk(SymAct("NOKOTCHI"), -320177000)
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("NOKOTCHI"), -2053857100)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("EMONGA"):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFace(324, 88, SymAct("EMONGA"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("EMONGA"), -1668312587)
  WINDOW:Talk(SymAct("EMONGA"), -1214070218)
  WINDOW:Talk(SymAct("EMONGA"), -1363545225)
  WINDOW:Talk(SymAct("EMONGA"), -503814736)
  WINDOW:Talk(SymAct("EMONGA"), -119319311)
  WINDOW:Talk(SymAct("EMONGA"), -741472462)
  WINDOW:Talk(SymAct("EMONGA"), -891996557)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("NOKOTCHI"), 1296902844)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(2.5))
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CH("BIRIJION"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  CH("BIRIJION"):WaitRotate()
  CH("NOKOTCHI"):DirTo(CH("BIRIJION"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):DirTo(CH("BIRIJION"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):DirTo(CH("BIRIJION"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("EMONGA"):DirTo(CH("BIRIJION"), Speed(350), ROT_TYPE.NEAR)
  CH("DOTEKKOTSU"):DirTo(CH("BIRIJION"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(72, 16, SymAct("BIRIJION"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("BIRIJION"), 1414929405)
  WINDOW:Talk(SymAct("BIRIJION"), 407083021)
  WINDOW:Talk(SymAct("BIRIJION"), 22587724)
  WINDOW:Talk(SymAct("BIRIJION"), 712374927)
  WINDOW:Talk(SymAct("BIRIJION"), 862899150)
  WINDOW:Talk(SymAct("BIRIJION"), 2083478793)
  WINDOW:Talk(SymAct("BIRIJION"), 1697934408)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:SwitchTalk({PARTNER_0 = 1310277515, PARTNER_1 = 1459752650})
  WINDOW:CloseMessage()
  CH("BIRIJION"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("NOKOTCHI"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):DirTo(CH("PARTNER"), Speed(200), ROT_TYPE.NEAR)
  CH("EMONGA"):DirTo(CH("PARTNER"), Speed(200), ROT_TYPE.NEAR)
  CH("DOTEKKOTSU"):DirTo(CH("PARTNER"), Speed(200), ROT_TYPE.NEAR)
  CH("DOTEKKOTSU"):WaitRotate()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_12"))
  CAMERA:SetTgt(SymCam("CAMERA_12"))
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_HOPE"), Volume(256))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:SwitchTalk({PARTNER_0 = -795209211, PARTNER_1 = -914283708})
  WINDOW:SwitchTalk({PARTNER_0 = -1593835672, PARTNER_1 = -1176187351})
  WINDOW:SwitchTalk({PARTNER_0 = -1832280598, PARTNER_1 = -1949127509})
  WINDOW:SwitchTalk({PARTNER_0 = -996984212, PARTNER_1 = -578286803})
  WINDOW:SwitchTalk({PARTNER_0 = -156935954, PARTNER_1 = -272733777})
  WINDOW:SwitchTalk({PARTNER_0 = 1747350880, PARTNER_1 = 1899840545})
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3.5))
  CAMERA:SetEye(SymCam("CAMERA_11"))
  CAMERA:SetTgt(SymCam("CAMERA_11"))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("BIRIJION"), -1303752570)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CH("PARTNER"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1420729913, PARTNER_1 = -2139344380})
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(CH("BIRIJION"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1721302203, PARTNER_1 = -702114430})
  WINDOW:SwitchTalk({PARTNER_0 = -818043709, PARTNER_1 = -468650240})
  WINDOW:SwitchTalk({PARTNER_0 = -49559999, PARTNER_1 = 2056510094})
  WINDOW:SwitchTalk({PARTNER_0 = 1669917647, PARTNER_1 = 183908323})
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_14"))
  CAMERA:SetTgt(SymCam("CAMERA_14"))
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.NORMAL)
  WINDOW:Monologue(334300834)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CH("PARTNER"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("HERO"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 952128865, PARTNER_1 = 568026144})
  CH("PARTNER"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:CloseMessage()
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 1855648487, PARTNER_1 = 2004992934})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("NOKOTCHI"):SetManpu("MP_NOTICE_L")
  CH("EMONGA"):SetManpu("MP_EXCLAMATION")
  CH("EMONGA"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("NOKOTCHI"), 1554813029)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("EMONGA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("EMONGA"), 1169662244)
  subEveCloseMsg()
  TASK:Regist(subEveNod, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1037058581, PARTNER_1 = -617313110})
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3.5))
  CAMERA:SetEye(SymCam("CAMERA_11"))
  CAMERA:SetTgt(SymCam("CAMERA_11"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("BIRIJION"), 1385506741)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(72, 8, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  WINDOW:SwitchTalk({PARTNER_0 = 1267603188, PARTNER_1 = 1621312823})
  WINDOW:SwitchTalk({PARTNER_0 = 2042131574, PARTNER_1 = 922346161})
  WINDOW:KeyWait()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:SwitchTalk({PARTNER_0 = 803394544, PARTNER_1 = 80707635})
  subEveCloseMsg()
  TASK:Regist(subEveJump, {
    CH("NOKOTCHI")
  })
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.EMOTION)
  WINDOW:Talk(SymAct("NOKOTCHI"), 500478322)
  subEveCloseMsg()
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1706250819, PARTNER_1 = -2091410180})
  WINDOW:SwitchTalk({PARTNER_0 = -366395184, PARTNER_1 = -214797935})
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -669048238, PARTNER_1 = -1056697581})
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  subEveCloseMsg()
  TASK:Regist(subEveNod, {
    CH("HERO")
  })
  WINDOW:DrawFace(324, 20, SymAct("HERO"), FACE_TYPE.NORMAL)
  WINDOW:Monologue(-1908046380)
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("HERO"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NOKOTCHI"), -1755401067)
  subEveCloseMsg()
  TASK:Regist(subEveNod, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1133254826, PARTNER_1 = -1519856105})
  subEveCloseMsg()
  TASK:Regist(subEveDoubleJump, {
    CH("NOKOTCHI")
  })
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.EMOTION)
  WINDOW:Talk(SymAct("NOKOTCHI"), 586205912)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("EMONGA"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("EMONGA"), 1005321113)
  subEveCloseMsg()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.GLADNESS)
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.GLADNESS)
  WINDOW:SwitchTalk({PARTNER_0 = -2060924729, PARTNER_1 = -1674315386})
  WINDOW:CloseMessage()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  WINDOW:SwitchTalk({PARTNER_0 = -1222727099, PARTNER_1 = -1375364348})
  WINDOW:SwitchTalk({PARTNER_0 = -515633725, PARTNER_1 = -127976318})
  subEveCloseMsg()
  TASK:Regist(subEveJump, {
    CH("NOKOTCHI")
  })
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.EMOTION)
  WINDOW:Talk(SymAct("NOKOTCHI"), -747475135)
  CH("PARTNER"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:Talk(SymAct("NOKOTCHI"), -899064320)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("EMONGA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EMONGA"), 1307656911)
  WINDOW:DrawFace(324, 88, SymAct("EMONGA"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("EMONGA"), 1424651150)
  WINDOW:CloseMessage()
  if SYSTEM:IsDebugMode() then
    CAMERA:SetEye(SymCam("CAMERA_05"))
    CAMERA:SetTgt(SymCam("CAMERA_05"))
    CH("DOKKORAA_1"):SetDir(CH("PARTNER"))
    CH("DOKKORAA_2"):SetDir(CH("PARTNER"))
    CH("HERO"):SetPosition(SymPos("P01_HERO"))
    CH("PARTNER"):SetPosition(SymPos("P01_PARTNER"))
    CH("EMONGA"):SetPosition(SymPos("P01_EMONGA"))
  end
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.GLADNESS)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.GLADNESS)
  CH("EMONGA"):SetFacialMotion(FACIAL_MOTION.GLADNESS)
  CH("NOKOTCHI"):SetFacialMotion(FACIAL_MOTION.GLADNESS)
  CH("PARTNER"):SetManpu("MP_SPREE_LP")
  CH("PARTNER"):SetMotion(SymMot("WAIT00"), LOOP.ON)
  CH("PARTNER"):SetMotionRaito(Raito(2))
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):SetMotion(SymMot("WAIT00"), LOOP.ON)
  CH("HERO"):SetMotionRaito(Raito(2))
  CH("NOKOTCHI"):SetMotion(SymMot("WALK"), LOOP.ON)
  CH("NOKOTCHI"):SetMotionRaito(Raito(2))
  TASK:Sleep(TimeSec(0.1))
  CH("EMONGA"):SetManpu("MP_LAUGH_LP")
  CH("EMONGA"):SetMotion(SymMot("WAIT00"), LOOP.ON)
  CH("EMONGA"):SetMotionRaito(Raito(2))
  TASK:Sleep(TimeSec(3))
  SOUND:FadeOutBgm(TimeSec(3.5))
  CH("BIRIJION"):WalkTo(SymPos("P01_BIRIJION"), Speed(1))
  CH("BIRIJION"):WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), 1033154466)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CH("PARTNER"):ResetManpu()
  CH("PARTNER"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("PARTNER"):SetMotionRaito(Raito(1))
  CH("NOKOTCHI"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("NOKOTCHI"):SetMotionRaito(Raito(1))
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("HERO"):SetMotionRaito(Raito(1))
  CH("EMONGA"):ResetManpu()
  CH("EMONGA"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("EMONGA"):SetMotionRaito(Raito(1))
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  CH("EMONGA"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  CH("NOKOTCHI"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  CH("NOKOTCHI"):DirTo(CH("BIRIJION"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):DirTo(CH("BIRIJION"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):DirTo(CH("BIRIJION"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("EMONGA"):DirTo(CH("BIRIJION"), Speed(350), ROT_TYPE.NEAR)
  CH("DOTEKKOTSU"):DirTo(CH("BIRIJION"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(72, 16, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), 613392099)
  WINDOW:Talk(SymAct("BIRIJION"), 262327584)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("EMONGA"):SetManpu("MP_SHOCK_L")
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("NOKOTCHI"):SetManpu("MP_FLY_SWEAT")
  CH("DOTEKKOTSU"):SetManpu("MP_SHOCK_R")
  CH("DOTEKKOTSU"):WalkTo(PosOffs(0, 0.15), Speed(2), LINK_DIR.OFF)
  CH("DOKKORAA_2"):SetManpu("MP_FLY_SWEAT")
  TASK:Regist(subEveJump, {
    CH("DOKKORAA_1")
  })
  TASK:Regist(subEveJump, {
    CH("NOKOTCHI")
  })
  CH("NOKOTCHI"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 381287521, PARTNER_1 = 1509452454})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("DOKKORAA_2"):SetManpu("MP_FLY_SWEAT")
  CH("DOKKORAA_2"):WaitManpu()
  WINDOW:DrawFace(20, 20, SymAct("DOKKORAA_2"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("DOKKORAA_2"), 1088642023)
  subEveCloseMsg()
  WINDOW:DrawFace(72, 16, SymAct("DOKKORAA_1"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("DOKKORAA_1"), 1808664612)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  CH("EMONGA"):SetManpu("MP_ANGRY_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("EMONGA")
  })
  WINDOW:DrawFace(324, 88, SymAct("EMONGA"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("EMONGA"), 1926576485)
  WINDOW:Talk(SymAct("EMONGA"), -179493462)
  WINDOW:CloseMessage()
  CH("EMONGA"):ResetManpu()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3.5))
  CAMERA:SetEye(SymCam("CAMERA_11_5"))
  CAMERA:SetTgt(SymCam("CAMERA_11_5"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("BIRIJION"), -329902869)
  WINDOW:Talk(SymAct("BIRIJION"), 790691916)
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), 909783309)
  WINDOW:Talk(SymAct("BIRIJION"), 488071886)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  TASK:Regist(subEveDoubleJump, {
    CH("EMONGA")
  })
  CH("EMONGA"):SetManpu("MP_ANGRY_LP")
  WINDOW:DrawFace(324, 88, SymAct("EMONGA"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("EMONGA"), 67916687)
  WINDOW:CloseMessage()
  CH("EMONGA"):ResetManpu()
  CH("EMONGA"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("EMONGA"):WaitRotate()
  TASK:Regist(subEveJump, {
    CH("EMONGA")
  })
  WINDOW:DrawFace(324, 88, SymAct("EMONGA"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("EMONGA"), 1263387976)
  subEveCloseMsg()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3.5))
  CAMERA:SetEye(SymCam("CAMERA_12"))
  CAMERA:SetTgt(SymCam("CAMERA_12"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 1381430281, PARTNER_1 = 2038147018})
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_HOPE_MARCH"), Volume(256))
  CH("EMONGA"):SetManpu("MP_SHOCK_L")
  CH("NOKOTCHI"):SetManpu("MP_FLY_SWEAT")
  CH("DOKKORAA_2"):SetManpu("MP_EXCLAMATION")
  CH("DOKKORAA_1"):SetManpu("MP_SHOCK_R")
  TASK:Regist(subEveJump, {
    CH("DOKKORAA_1")
  })
  TASK:Regist(subEveJump, {
    CH("EMONGA")
  })
  CH("NOKOTCHI"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("EMONGA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("EMONGA"), 1616942731)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("EMONGA"):SetManpu("MP_FLY_SWEAT")
  CH("EMONGA"):WaitManpu()
  CH("EMONGA"):SetFacialMotion(FACIAL_MOTION.ANGRY)
  WINDOW:DrawFace(324, 88, SymAct("EMONGA"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("EMONGA"), -403142076)
  WINDOW:Talk(SymAct("EMONGA"), -18629883)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3.5))
  CAMERA:SetEye(SymCam("CAMERA_13"))
  CAMERA:SetTgt(SymCam("CAMERA_13"))
  TASK:Sleep(TimeSec(0.3))
  CH("EMONGA"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  CH("EMONGA"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("EMONGA"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("EMONGA"), -1751292119)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NOKOTCHI"), -1903798680)
  WINDOW:KeyWait()
  SOUND:PlaySe(SymSnd("SE_EVT_PO"), Volume(256))
  CH("NOKOTCHI"):SetManpu("MP_HEART")
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.SPECIAL01)
  WINDOW:Talk(SymAct("NOKOTCHI"), -1515518549)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("EMONGA"):SetManpu("MP_SHOCK_L")
  CH("EMONGA"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("EMONGA"):WalkTo(PosOffs(0.1, -0.1), Speed(2), LINK_DIR.OFF)
  WINDOW:DrawFace(324, 88, SymAct("EMONGA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("EMONGA"), -1129302806)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -202268115, PARTNER_1 = -353725588})
  CH("EMONGA"):SetFacialMotion(FACIAL_MOTION.ANGRY)
  CH("EMONGA"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("EMONGA"):WaitRotate()
  WINDOW:SwitchTalk({PARTNER_0 = -1043873617, PARTNER_1 = -656608786})
  subEveCloseMsg()
  WINDOW:DrawFace(72, 16, SymAct("BIRIJION"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("BIRIJION"), 1598352673)
  subEveCloseMsg()
  WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 1180687456, PARTNER_1 = 172646288})
  WINDOW:KeyWait()
  TASK:Regist(subEveJump, {
    CH("PARTNER")
  })
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  WINDOW:SwitchTalk({PARTNER_0 = 324103889, PARTNER_1 = 947666194})
  subEveCloseMsg()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  CH("BIRIJION"):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(72, 16, SymAct("BIRIJION"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("BIRIJION"), 560401491)
  subEveCloseMsg()
  CH("BIRIJION"):ResetManpu()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CH("DOTEKKOTSU"):SetPosition(SymPos("P01_DOTEKKOTSU"))
  CH("DOTEKKOTSU"):SetDir(CH("PARTNER"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  CH("EMONGA"):SetManpu("MP_ANGRY_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("EMONGA")
  })
  WINDOW:DrawFace(324, 20, SymAct("EMONGA"), FACE_TYPE.ANGRY)
  WINDOW:DrawFaceOffset(10, 0)
  WINDOW:Talk(SymAct("EMONGA"), 1848023700)
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  CH("NOKOTCHI"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  CH("DOTEKKOTSU"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 2000530389, PARTNER_1 = 1544615958})
  subEveCloseMsg()
  TASK:Regist(subEveJump, {
    CH("EMONGA")
  })
  WINDOW:DrawFace(324, 20, SymAct("EMONGA"), FACE_TYPE.ANGRY)
  WINDOW:DrawFaceOffset(10, 0)
  WINDOW:Talk(SymAct("EMONGA"), 1158400343)
  WINDOW:CloseMessage()
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1030498920, PARTNER_1 = -611785511})
  WINDOW:SwitchTalk({PARTNER_0 = -1292486411, PARTNER_1 = -1410528844})
  WINDOW:SwitchTalk({PARTNER_0 = -2134877577, PARTNER_1 = -1713673418})
  WINDOW:CloseMessage()
  CH("EMONGA"):ResetManpu()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("EMONGA"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("EMONGA"):SetManpu("MP_SHOCK_L")
  CH("EMONGA"):WalkTo(SymPos("P02_EMONGA"), Speed(2), LINK_DIR.OFF)
  WINDOW:DrawFace(324, 20, SymAct("EMONGA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("EMONGA"), -694485519)
  WINDOW:CloseMessage()
  local taskPartnerHero00 = function()
    function TaskL.Loop()
      CH("PARTNER"):SetManpu("MP_SPREE_LP")
      CH("PARTNER"):SetMotion(SymMot("SPEAK"), LOOP.OFF)
      CH("PARTNER"):WaitPlayMotion()
      CH("PARTNER"):SetMotion(SymMot("WAIT02"), LOOP.ON)
      TASK:Sleep(TimeSec(1))
      CH("PARTNER"):ResetManpu()
      TASK:Sleep(TimeSec(0.5))
      subEveNodDouble(CH("HERO"))
      TASK:Sleep(TimeSec(2))
    end
  end
  local taskEmonga00 = function()
    function TaskL.Loop()
      CH("EMONGA"):SetFacialMotion(FACIAL_MOTION.NORMAL)
      CH("EMONGA"):SetMotion(SymMot("SPEAK"), LOOP.OFF)
      CH("EMONGA"):WaitPlayMotion()
      CH("EMONGA"):SetMotion(SymMot("WAIT02"), LOOP.ON)
      TASK:Sleep(TimeSec(0.75))
      CH("EMONGA"):SetManpu("MP_ANGRY_LP")
      CH("EMONGA"):SetFacialMotion(FACIAL_MOTION.ANGRY)
      subEveDoubleJump(CH("EMONGA"))
      TASK:Sleep(TimeSec(2))
      CH("EMONGA"):ResetManpu()
      TASK:Sleep(TimeSec(1.5))
    end
  end
  local taskNokotchi00 = function()
    function TaskL.Loop()
      CH("NOKOTCHI"):SetManpu("MP_LAUGH_LP")
      CH("NOKOTCHI"):SetMotion(SymMot("WALK"), LOOP.ON)
      CH("NOKOTCHI"):SetMotionRaito(Raito(2))
      TASK:Sleep(TimeSec(2))
      CH("NOKOTCHI"):ResetManpu()
      CH("NOKOTCHI"):SetMotion(SymMot("WAIT02"), LOOP.ON)
      TASK:Sleep(TimeSec(1.5))
    end
  end
  SOUND:PlaySe(SymSnd("SE_EVT_WAIWAI_LP"), Volume(256))
  TASK:Regist(Group("grp01"), taskPartnerHero00)
  TASK:Regist(Group("grp02"), taskEmonga00)
  TASK:Regist(Group("grp03"), taskNokotchi00)
  TASK:Sleep(TimeSec(2))
  CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  subEveFadeAfterTime()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("BIRIJION"):SetManpu("MP_FLY_SWEAT")
  CH("BIRIJION"):WaitManpu()
  WINDOW:DrawFace(72, 16, SymAct("BIRIJION"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("BIRIJION"), -813577040)
  WINDOW:DrawFace(72, 16, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), -458449037)
  WINDOW:Talk(SymAct("BIRIJION"), -38293966)
  WINDOW:CloseMessage()
  SOUND:FadeOutSe(SymSnd("SE_EVT_WAIWAI_LP"), TimeSec(2.5))
  CH("DOKKORAA_1"):DirTo(RotateTarget(45), Speed(200), ROT_TYPE.NEAR)
  CH("DOKKORAA_2"):DirTo(RotateTarget(45), Speed(200), ROT_TYPE.NEAR)
  CAMERA:MoveFollow(SymCam("CAMERA_08"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("BIRIJION"):WalkTo(SplinePath(SymPos("P02_BIRIJION"), SymPos("P03_BIRIJION")), Speed(1))
  CH("BIRIJION"):WaitMove()
  CAMERA:WaitMove()
  WINDOW:DrawFace(324, 88, SymAct("BIRIJION"), FACE_TYPE.SPECIAL03)
  WINDOW:Talk(SymAct("BIRIJION"), 2049946365)
  WINDOW:CloseMessage()
  CH("DOTEKKOTSU"):DirTo(CH("BIRIJION"), Speed(350), ROT_TYPE.NEAR)
  CH("DOTEKKOTSU"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_HOWAWAN"), Volume(256))
  CH("DOTEKKOTSU"):SetManpu("MP_HEART")
  WINDOW:DrawFace(20, 88, SymAct("DOTEKKOTSU"), FACE_TYPE.SPECIAL01)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), 1664385980)
  CH("DOTEKKOTSU"):WaitManpu()
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("BIRIJION"), FACE_TYPE.SPECIAL03)
  WINDOW:Talk(SymAct("BIRIJION"), -1606183141)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.5))
  WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), -1185372582)
  WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), -1837763175)
  WINDOW:CloseMessage()
  FLAG.SceneFlag = CONST.FL_SC_01_END
  FLAG.SCENARIOFLAG = CONST.M03_AREHATEDANICLEAR1ST_START
  SYSTEM:NextEntry()
end
function main03_arehatedaniclear1st01_end()
end
function main03_arehatedaniclear1st02_init()
end
function main03_arehatedaniclear1st02_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_HOPE_MARCH"), Volume(256))
  CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  subEveFadeAfterTime()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("DOTEKKOTSU"):SetManpu("MP_EXCLAMATION")
  CH("DOTEKKOTSU"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("DOTEKKOTSU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), -1955674920)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), -1003531745)
  WINDOW:CloseMessage()
  CH("DOKKORAA_2"):DirTo(CH("DOTEKKOTSU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("DOKKORAA_1"):DirTo(CH("DOTEKKOTSU"), Speed(350), ROT_TYPE.NEAR)
  CH("DOKKORAA_1"):WaitRotate()
  TASK:Regist(subEveDoubleJump, {
    CH("DOKKORAA_2")
  })
  WINDOW:DrawFace(272, 16, SymAct("DOKKORAA_2"), FACE_TYPE.SPECIAL04)
  WINDOW:Talk(SymAct("DOKKORAA_2"), -583769250)
  WINDOW:CloseMessage()
  CH("BIRIJION"):DirTo(RotateTarget(45), Speed(350), ROT_TYPE.NEAR)
  CH("BIRIJION"):WaitRotate()
  CH("DOKKORAA_2"):DirTo(CH("BIRIJION"), Speed(200), ROT_TYPE.NEAR)
  CH("DOKKORAA_1"):DirTo(CH("BIRIJION"), Speed(200), ROT_TYPE.NEAR)
  WINDOW:DrawFaceF(324, 88, SymAct("BIRIJION"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("BIRIJION"), -166121315)
  WINDOW:CloseMessage()
  CH("BIRIJION"):DirTo(CH("DOTEKKOTSU"), Speed(350), ROT_TYPE.LEFT)
  CH("BIRIJION"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), -285081124)
  WINDOW:CloseMessage()
  CH("BIRIJION"):DirTo(RotateTarget(45), Speed(500), ROT_TYPE.NEAR)
  CH("BIRIJION"):WaitRotate()
  CAMERA:MoveFollow(SymCam("CAMERA_01"), Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.NONE))
  CH("BIRIJION"):WalkTo(SymPos("P01_BIRIJION"), Speed(1.5))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 88, SymAct("DOTEKKOTSU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), 1754930451)
  CH("BIRIJION"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("BIRIJION"):SetManpu("MP_NOTICE_R")
  WINDOW:CloseMessage()
  CH("BIRIJION"):DirTo(CH("DOTEKKOTSU"), Speed(350), ROT_TYPE.LEFT)
  CH("BIRIJION"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("DOTEKKOTSU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), 1904290898)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), 419426430)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), 31768895)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), 717853436)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("BIRIJION"), FACE_TYPE.SPECIAL05)
  WINDOW:Talk(SymAct("BIRIJION"), 869442493)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("DOTEKKOTSU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), 2090022266)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), 1703412795)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), 1319458808)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), 1472095929)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), -802784650)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), -918729929)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), 1084022824)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), 1502073193)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("BIRIJION"), FACE_TYPE.SPECIAL05)
  WINDOW:Talk(SymAct("BIRIJION"), 1923777194)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(1), true)
  CAMERA:ResetAzimuthDifferenceVolume()
  FLAG.SceneFlag = CONST.FL_SC_02_END
  FLAG.SCENARIOFLAG = CONST.M03_AREHATEDANICLEAR1ST_START
  SYSTEM:NextEntry()
end
function main03_arehatedaniclear1st02_end()
end
function main03_arehatedaniclear1st03_init()
  if FLAG.NowResumeFlag == CONST.FLAG_TRUE then
    subEveFromProgFadeSet()
    subSaveflagM03_170_03()
  end
end
function main03_arehatedaniclear1st03_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_HOPE_MARCH"), Volume(256))
  CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  local taskPartnerHero00 = function()
    function TaskL.Loop()
      CH("PARTNER"):SetManpu("MP_SPREE_LP")
      CH("PARTNER"):SetMotion(SymMot("SPEAK"), LOOP.OFF)
      CH("PARTNER"):WaitPlayMotion()
      CH("PARTNER"):SetMotion(SymMot("WAIT02"), LOOP.ON)
      TASK:Sleep(TimeSec(1))
      CH("PARTNER"):ResetManpu()
      TASK:Sleep(TimeSec(0.5))
      subEveNodDouble(CH("HERO"))
      TASK:Sleep(TimeSec(2))
    end
  end
  local taskEmonga00 = function()
    function TaskL.Loop()
      CH("EMONGA"):SetFacialMotion(FACIAL_MOTION.NORMAL)
      CH("EMONGA"):SetMotion(SymMot("SPEAK"), LOOP.OFF)
      CH("EMONGA"):WaitPlayMotion()
      CH("EMONGA"):SetMotion(SymMot("WAIT02"), LOOP.ON)
      TASK:Sleep(TimeSec(0.75))
      CH("EMONGA"):SetManpu("MP_ANGRY_LP")
      CH("EMONGA"):SetFacialMotion(FACIAL_MOTION.ANGRY)
      subEveDoubleJump(CH("EMONGA"))
      TASK:Sleep(TimeSec(2))
      CH("EMONGA"):ResetManpu()
      TASK:Sleep(TimeSec(1.5))
    end
  end
  local taskNokotchi00 = function()
    function TaskL.Loop()
      CH("NOKOTCHI"):SetManpu("MP_LAUGH_LP")
      CH("NOKOTCHI"):SetMotion(SymMot("WALK"), LOOP.ON)
      CH("NOKOTCHI"):SetMotionRaito(Raito(2))
      TASK:Sleep(TimeSec(2))
      CH("NOKOTCHI"):ResetManpu()
      CH("NOKOTCHI"):SetMotion(SymMot("WAIT02"), LOOP.ON)
      TASK:Sleep(TimeSec(1.5))
    end
  end
  TASK:Regist(Group("grp01"), taskPartnerHero00)
  TASK:Regist(Group("grp02"), taskEmonga00)
  TASK:Regist(Group("grp03"), taskNokotchi00)
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  subEveFadeAfterTime()
  WINDOW:DrawFace(324, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), 1806808043)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("DOTEKKOTSU"), FACE_TYPE.SPECIAL04)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), 619717932)
  WINDOW:CloseMessage()
  CH("BIRIJION"):DirTo(CH("DOTEKKOTSU"), Speed(350), ROT_TYPE.NEAR)
  CH("BIRIJION"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("BIRIJION"), FACE_TYPE.SPECIAL01)
  WINDOW:Talk(SymAct("BIRIJION"), 1038816365)
  WINDOW:DrawFace(324, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), 382093230)
  WINDOW:CloseMessage()
  CH("BIRIJION"):DirTo(CH("HERO"), Speed(200), ROT_TYPE.NEAR)
  CH("BIRIJION"):WaitRotate()
  TASK:Sleep(TimeSec(0.7))
  WINDOW:DrawFace(324, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), 266172143)
  WINDOW:Talk(SymAct("BIRIJION"), -2008716768)
  CH("DOTEKKOTSU"):DirTo(CH("HERO"), Speed(200), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("DOKKORAA_1"):DirTo(CH("HERO"), Speed(200), ROT_TYPE.NEAR)
  CH("DOKKORAA_2"):DirTo(CH("HERO"), Speed(200), ROT_TYPE.NEAR)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3.5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.7))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), -1856087199)
  WINDOW:Talk(SymAct("BIRIJION"), -132085939)
  WINDOW:Talk(SymAct("BIRIJION"), -516180468)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(3))
  SCREEN_A:FadeOut(TimeSec(2), true)
  TASK:Sleep(TimeSec(1))
  CAMERA:ResetAzimuthDifferenceVolume()
  SOUND:WaitBgm()
  TASK:Sleep(TimeSec(0.2))
  if Ground_Save(ground) then
    return
  end
  subSaveflagM03_170_03()
end
function main03_arehatedaniclear1st03_end()
end
function subSaveflagM03_170_03()
  FLAG.SceneFlag = CONST.FL_SC_01_FIRST
  FLAG.SCENARIOFLAG = CONST.M03_AREHATEDANICLEAR1ST_END
  SYSTEM:NextEntry()
end
function groundEnd()
end

