dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main07_ayashiipokemon01_init()
end
function main07_ayashiipokemon01_start()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("HERO"):SetPosition(SymPos("P01_HERO"))
  CH("PARTNER"):SetPosition(SymPos("P01_PARTNER"))
  CH("EMONGA"):SetVisible(false)
  CH("HERO"):SetDir(CH("PARTNER"))
  CH("PARTNER"):SetDir(CH("HERO"))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- CAMERA:MoveFollow(SymCam("CAMERA_01"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- CH("HERO"):WalkTo(SplinePath(SymPos("P00_HERO"), SymPos("P01_HERO")), Speed(1.5))
  -- TASK:Sleep(TimeSec(0.2))
  -- CH("PARTNER"):WalkTo(SplinePath(SymPos("P00_PARTNER"), SymPos("P01_PARTNER")), Speed(1.5))
  -- CH("HERO"):WaitMove()
  -- CH("HERO"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  -- CH("HERO"):WaitRotate()
  -- CH("PARTNER"):WaitMove()
  -- CH("PARTNER"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  -- CH("PARTNER"):WaitRotate()
  -- CAMERA:WaitMove()
  -- WINDOW:DrawFace(20, 88, SymAct("EMONGA"), FACE_TYPE.SHOUT)
  -- WINDOW:Talk(SymAct("EMONGA"), -1241342039)
  -- WINDOW:CloseMessage()
  -- CH("EMONGA"):RunTo(SymPos("P01_EMONGA"), Speed(3))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  -- CH("HERO"):SetManpu("MP_NOTICE_R")
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  -- CH("PARTNER"):WaitManpu()
  -- CH("EMONGA"):WaitMove()
  -- WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  -- WINDOW:SwitchTalk({PARTNER_0 = -1357271320, PARTNER_1 = -2076902101})
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_02"))
  -- CAMERA:SetTgt(SymCam("CAMERA_02"))
  -- SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  -- subEveDoubleJump(CH("EMONGA"))
  -- WINDOW:DrawFace(324, 88, SymAct("EMONGA"), FACE_TYPE.SURPRISE)
  -- WINDOW:Talk(SymAct("EMONGA"), -1657811862)
  -- WINDOW:Talk(SymAct("EMONGA"), -764519763)
  -- WINDOW:CloseMessage()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  -- CH("HERO"):SetManpu("MP_SHOCK_R")
  -- CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  -- TASK:Regist(subEveJump, {
  --   CH("PARTNER")
  -- })
  -- CH("PARTNER"):WaitManpu()
  -- WINDOW:DrawFace(20, 20, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  -- WINDOW:SwitchTalk({PARTNER_0 = -881497108, PARTNER_1 = -531089361})
  -- WINDOW:KeyWait()
  -- SOUND:PlayBgm(SymSnd("BGM_EVE_NAZO_02"), Volume(256))
  -- WINDOW:SwitchTalk({PARTNER_0 = -113047186, PARTNER_1 = 2128287137})
  -- WINDOW:SwitchTalk({PARTNER_0 = 1740645600, PARTNER_1 = 961969182})
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(324, 88, SymAct("EMONGA"), FACE_TYPE.PAIN)
  -- WINDOW:Talk(SymAct("EMONGA"), 541936991)
  -- WINDOW:Talk(SymAct("EMONGA"), 190848668)
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(20, 20, SymAct("PARTNER"), FACE_TYPE.CATCHBREATH)
  -- WINDOW:SwitchTalk({PARTNER_0 = 310063069, PARTNER_1 = 1564129562})
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(324, 88, SymAct("EMONGA"), FACE_TYPE.PAIN)
  -- WINDOW:Talk(SymAct("EMONGA"), 1143048283)
  -- WINDOW:Talk(SymAct("EMONGA"), 1863113624)
  -- WINDOW:Talk(SymAct("EMONGA"), 1981278937)
  -- subEveCloseMsg()
  -- CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.RELIEF)
  -- WINDOW:DrawFace(20, 20, SymAct("PARTNER"), FACE_TYPE.RELIEF)
  -- WINDOW:SwitchTalk({PARTNER_0 = -242223594, PARTNER_1 = -392902825})
  -- subEveCloseMsg()
  -- CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  -- WINDOW:DrawFace(324, 88, SymAct("EMONGA"), FACE_TYPE.THINK)
  -- WINDOW:Talk(SymAct("EMONGA"), 736351216)
  -- WINDOW:Talk(SymAct("EMONGA"), 855171761)
  -- WINDOW:Talk(SymAct("EMONGA"), 433434994)
  -- WINDOW:Talk(SymAct("EMONGA"), 13533235)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_01"))
  -- CAMERA:SetTgt(SymCam("CAMERA_01"))
  -- subEveNod(CH("PARTNER"))
  -- WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  -- WINDOW:SwitchTalk({PARTNER_0 = 1334777588, PARTNER_1 = 1452550069})
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(20, 88, SymAct("EMONGA"), FACE_TYPE.DECIDE)
  -- WINDOW:Talk(SymAct("EMONGA"), 2109305974)
  -- WINDOW:CloseMessage()
  -- SOUND:FadeOutBgm(TimeSec(2.5))
  -- CH("EMONGA"):DirTo(RotateTarget(0), Speed(500), ROT_TYPE.NEAR)
  -- CH("EMONGA"):WaitRotate()
  -- CH("EMONGA"):RunTo(SymPos("P02_EMONGA"), Speed(2.5))
  -- TASK:Sleep(TimeSec(1.5))
  -- CAMERA:MoveFollow(SymCam("CAMERA_03"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.3))
  -- CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  -- CH("PARTNER"):WaitRotate()
  -- CAMERA:WaitMove()
  -- CH("EMONGA"):SetVisible(false)
  -- WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  -- WINDOW:SwitchTalk({PARTNER_0 = 1688356151, PARTNER_1 = -482715144})
  -- WINDOW:CloseMessage()
  -- subEveNod(CH("HERO"))
  -- TASK:Sleep(TimeSec(0.2))
  CAMERA:MoveToHero(Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  FLAG.SceneFlag = CONST.FL_SC_01_FIRST
  FLAG.SCENARIOFLAG = CONST.M07_AYASHIIPOKEMON_END
  FLAG.MapFlags = CONST.MAP_EVENT
  FLAG.FreePlay = CONST.FLAG_TRUE
  FLAG.TrigNextEvent = CONST.FLAG_FALSE
  SYSTEM:NextEntry(KEEP_PLACEMENT.ON)
end
function main07_ayashiipokemon01_end()
end
function groundEnd()
end

