dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main02_kageroutougeboss2nd01_init()
end
function main02_kageroutougeboss2nd01_start()
  subEveFromProgFadeSet()
  TASK:Sleep(TimeSec(1))
  CAMERA:SetAzimuthDifferenceVolume(Volume(3.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HERO"):SetVisible(false)
  CH("PARTNER"):SetVisible(false)
  local taskPartnerZuruggu00 = function()
    function TaskL.Loop()
      SOUND:PlaySe(SymSnd("SE_EVT_GOSOGOSO"), Volume(256))
      CH("ZURUGGU"):SetMotion(SymMot("EV001_GASAGASA"), LOOP.OFF)
      CH("ZURUGGU"):WaitPlayMotion()
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("ZURUGGU"):SetMotion(SymMot("EV001_GASAGASA"), LOOP.OFF)
      CH("ZURUGGU"):WaitPlayMotion()
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.3))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
      CH("ZURUGGU"):SetManpu("MP_QUESTION")
      CH("ZURUGGU"):WaitManpu()
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.5))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      SOUND:PlaySe(SymSnd("SE_EVT_GOSOGOSO"), Volume(256))
      CH("ZURUGGU"):SetMotion(SymMot("EV001_GASAGASA"), LOOP.OFF)
      CH("ZURUGGU"):WaitPlayMotion()
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("ZURUGGU"):SetMotion(SymMot("EV001_GASAGASA"), LOOP.OFF)
      CH("ZURUGGU"):WaitPlayMotion()
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("ZURUGGU"):SetMotion(SymMot("EV001_GASAGASA"), LOOP.OFF)
      CH("ZURUGGU"):WaitPlayMotion()
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
      CH("ZURUGGU"):SetManpu("MP_FLY_SWEAT")
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("ZURUGGU"):SetMotion(SymMot("EV001_GASAGASA"), LOOP.OFF)
      CH("ZURUGGU"):WaitPlayMotion()
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("ZURUGGU"):SetMotion(SymMot("EV001_GASAGASA"), LOOP.OFF)
      CH("ZURUGGU"):WaitPlayMotion()
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
    end
    function TaskL.Finish()
      CH("ZURUGGU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
      TASK:Sleep(TimeSec(0.1))
      return
    end
  end
  TASK:Regist(Group("grpZuruggu"), taskPartnerZuruggu00)
  TASK:Sleep(TimeSec(0.1))
  CAMERA:MoveFollow2(SymCam("CAMERA_00_5"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SOUND:FadeInEnv(SymSnd("SE_ENV_BREEZE_LP"), TimeSec(0.5), Volume(128))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  subEveFadeAfterTime()
  TASK:Sleep(TimeSec(1.2))
  CAMERA:WaitMove()
  WINDOW:DrawFace(324, 88, SymAct("DOTEKKOTSU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), -747180830)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), -898769501)
  WINDOW:CloseMessage()
  TASK:ExitNotifyTasks(Group("grpZuruggu"))
  TASK:WaitTask(Group("grpZuruggu"))
  CH("ZURUGGU"):DirTo(CH("DOTEKKOTSU"), Speed(500), ROT_TYPE.LEFT)
  CH("ZURUGGU"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("ZURUGGU"):SetManpu("MP_FLY_SWEAT")
  CH("ZURUGGU"):WaitManpu()
  WINDOW:DrawFace(20, 20, SymAct("ZURUGGU"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("ZURUGGU"), -515862944)
  WINDOW:Talk(SymAct("ZURUGGU"), -128205023)
  WINDOW:CloseMessage()
  CH("ZURUGGU"):DirTo(RotateTarget(-150), Speed(500), ROT_TYPE.RIGHT)
  CH("ZURUGGU"):WaitRotate()
  TASK:Regist(Group("grpZuruggu"), taskPartnerZuruggu00)
  WINDOW:DrawFaceF(172, 8, SymAct("ZURUGGU"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("ZURUGGU"), -1223022106)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("DOTEKKOTSU"):SetManpu("MP_EXCLAMATION")
  CH("DOTEKKOTSU"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("DOTEKKOTSU"), FACE_TYPE.SPECIAL03)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), -1375659865)
  WINDOW:CloseMessage()
  TASK:ExitNotifyTasks(Group("grpZuruggu"))
  TASK:WaitTask(Group("grpZuruggu"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("ZURUGGU"):SetManpu("MP_EXCLAMATION")
  CH("ZURUGGU"):WaitManpu()
  CH("ZURUGGU"):DirTo(CH("DOTEKKOTSU"), Speed(500), ROT_TYPE.LEFT)
  CH("ZURUGGU"):WaitRotate()
  WINDOW:DrawFace(20, 20, SymAct("ZURUGGU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("ZURUGGU"), -2060694684)
  WINDOW:Talk(SymAct("ZURUGGU"), -1674085851)
  subEveCloseMsg()
  WINDOW:SwitchTalk({PARTNER_0 = 464479978, PARTNER_1 = 45373355})
  SOUND:FadeOutEnv(TimeSec(1.5))
  CH("DOTEKKOTSU"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  CH("ZURUGGU"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  CH("DOTEKKOTSU"):ResetManpu()
  CH("ZURUGGU"):ResetManpu()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_01"), Volume(256))
  CH("DOTEKKOTSU"):SetManpu("MP_EXCLAMATION")
  CH("ZURUGGU"):SetManpu("MP_EXCLAMATION")
  CH("ZURUGGU"):WaitManpu()
  WINDOW:CloseMessage()
  CH("DOTEKKOTSU"):DirTo(RotateTarget(90), Speed(500), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("ZURUGGU"):DirTo(RotateTarget(90), Speed(500), ROT_TYPE.NEAR)
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CH("HERO"):SetVisible(true)
  CH("PARTNER"):SetVisible(true)
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.ANGRY)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.ANGRY)
  TASK:Regist(Group("grpHero"), subEveRunDir, {
    CH("HERO"),
    SymPos("P01_HERO"),
    Speed(2.5),
    RotateTarget(-90)
  })
  TASK:Regist(Group("grpPartner"), subEveRunDir, {
    CH("PARTNER"),
    SymPos("P01_PARTNER"),
    Speed(2.5),
    RotateTarget(-90)
  })
  TASK:Sleep(TimeSec(0.3))
  TASK:Regist(subEveMoveDir, {
    CH("ZURUGGU"),
    SymPos("P01_ZURUGGU"),
    Speed(1.5),
    RotateTarget(90)
  })
  TASK:WaitTask()
  WINDOW:DrawFace(20, 88, SymAct("ZURUGGU"), FACE_TYPE.SPECIAL01)
  WINDOW:Talk(SymAct("ZURUGGU"), -472404190)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  SOUND:PlayBgm(SymSnd("BGM_EVE_FEAR_01"), Volume(256))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 88, SymAct("DOTEKKOTSU"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), -87253405)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), -773730912)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.ANGRY)
  WINDOW:SwitchTalk({PARTNER_0 = -923075359, PARTNER_1 = -2017760730})
  subEveCloseMsg()
  CH("ZURUGGU"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
  WINDOW:DrawFace(72, 16, SymAct("ZURUGGU"), FACE_TYPE.SPECIAL01)
  WINDOW:Talk(SymAct("ZURUGGU"), -1633658009)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_FLUSH"), Volume(256))
  subEveFlash()
  CH("DOTEKKOTSU"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("DOTEKKOTSU"), FACE_TYPE.SPECIAL03)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), -1249048412)
  WINDOW:CloseMessage()
  subEveFlash2()
  CH("HERO"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
  WINDOW:DrawFace(72, 16, SymAct("ZURUGGU"), FACE_TYPE.SPECIAL01)
  WINDOW:Talk(SymAct("ZURUGGU"), -1399440923)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_BOSS_WIPE"), Volume(256))
  EFFECT:BossWipe(TimeSec(60, TIME_TYPE.FRAME), true)
  CAMERA:ResetAzimuthDifferenceVolume()
  FLAG.SceneFlag = CONST.FL_SC_01_FIRST
  FLAG.SCENARIOFLAG = CONST.M02_KAGEROUTOUGEBOSS2ND_END
  SYSTEM:SetNextDungeonBanner(false)
  SYSTEM:EnterDungeon(Dg(3), DG_WAYPOINT.BOSS00)
end
function main02_kageroutougeboss2nd01_end()
end
function groundEnd()
end

