dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main03_crystal01_init()
end
function main03_crystal01_start()
  subEveFromProgFadeSet()
  TASK:Sleep(TimeSec(1))
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HERO"):WalkTo(SymPos("P01_HERO"), Speed(2))
  CH("PARTNER"):WalkTo(SymPos("P01_PARTNER"), Speed(2))
  EFFECT:Create("effectTwinkle_00", SymEff("EV_GLITTER_RANDOM"))
  EFFECT:SetPosition("effectTwinkle_00", SymPos("P00_EFF_GLITTER_RANDOM"))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("HERO"):WaitMove()
  CH("HERO"):DirTo(RotateTarget(45), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  TASK:Regist(subEveLookAround, {
    CH("HERO"),
    Speed(600)
  })
  CH("PARTNER"):WaitMove()
  CH("PARTNER"):DirTo(RotateTarget(0), Speed(500), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  TASK:Regist(subEveLookAround02, {
    CH("PARTNER"),
    Speed(600)
  })
  TASK:WaitTask()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:SwitchTalk({PARTNER_0 = -265939673, PARTNER_1 = -381868954})
  WINDOW:CloseMessage()
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1039108187, PARTNER_1 = -620017948})
  WINDOW:CloseMessage()
  subEveNod(CH("HERO"))
  CAMERA:MoveFollow(SymCam("CAMERA_01"), Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Regist(subEveMoveDir2, {
    CH("HERO"),
    SymPos("P02_HERO"),
    Speed(1.5),
    SymPos("P02_HERO")
  })
  CH("PARTNER"):WalkTo(SymPos("P02_PARTNER"), Speed(1.5))
  TASK:Sleep(TimeSec(0.8))
  SOUND:PlaySe(SymSnd("SE_EVT_KIRAN"), Volume(64))
  EFFECT:Play("effectTwinkle_00")
  CH("PARTNER"):WaitMove()
  CH("PARTNER"):SetManpu("MP_NOTICE_R")
  CH("PARTNER"):WaitManpu()
  CH("PARTNER"):DirTo(SymPos("P00_EFF_GLITTER_RANDOM"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1807036381, PARTNER_1 = -1924013726})
  CH("HERO"):DirTo(SymPos("P00_EFF_GLITTER_RANDOM"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:CloseMessage()
  EFFECT:Create("effectTwinkle_00", SymEff("EV_GLITTER_RANDOM"))
  EFFECT:SetPosition("effectTwinkle_00", SymPos("P00_EFF_GLITTER_RANDOM"))
  SOUND:PlaySe(SymSnd("SE_EVT_KIRAN"), Volume(64))
  EFFECT:Play("effectTwinkle_00")
  EFFECT:Wait("effectTwinkle_00")
  TASK:Regist(subEveJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  WINDOW:SwitchTalk({PARTNER_0 = -1501777247, PARTNER_1 = -1083735072})
  WINDOW:CloseMessage()
  local taskEffTwinkle00 = function()
    function TaskL.Loop()
      EFFECT:Create("effectTwinkle_01", SymEff("EV_GLITTER_RANDOM"))
      EFFECT:SetPosition("effectTwinkle_01", SymPos("P01_EFF_GLITTER_RANDOM"))
      EFFECT:Play("effectTwinkle_01")
      TASK:Sleep(TimeSec(0.5))
      EFFECT:Create("effectTwinkle_02", SymEff("EV_GLITTER_RANDOM"))
      EFFECT:SetPosition("effectTwinkle_02", SymPos("P02_EFF_GLITTER_RANDOM"))
      EFFECT:Play("effectTwinkle_02")
      TASK:Sleep(TimeSec(0.3))
      EFFECT:Create("effectTwinkle_03", SymEff("EV_GLITTER_RANDOM"))
      EFFECT:SetPosition("effectTwinkle_03", SymPos("P03_EFF_GLITTER_RANDOM"))
      EFFECT:Play("effectTwinkle_03")
      TASK:Sleep(TimeSec(1.5))
    end
  end
  local taskEffTwinkle01 = function()
    function TaskL.Loop()
      EFFECT:Create("effectTwinkle_01", SymEff("EV_GLITTER"))
      EFFECT:SetPosition("effectTwinkle_01", SymPos("P00_EFF_GLITTER"))
      EFFECT:Play("effectTwinkle_01")
      TASK:Sleep(TimeSec(1.8))
    end
  end
  TASK:Regist(Group("kabe"), taskEffTwinkle00)
  TASK:Regist(Group("yuka"), taskEffTwinkle01)
  TASK:Sleep(TimeSec(0.1))
  SOUND:FadeInEnv(SymSnd("SE_EVT_CRYSTAL_SHINE_LP"), TimeSec(1.5), Volume(128))
  CAMERA:MoveFollow(SymCam("CAMERA_02"), Speed(4, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  CH("PARTNER"):RunTo(SymPos("P00_CRYSTAL"), Speed(2))
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):WalkTo(SymPos("P03_HERO"), Speed(2))
  CH("PARTNER"):WaitMove()
  CH("PARTNER"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("HERO"):WaitMove()
  CH("HERO"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  WINDOW:SwitchTalk({PARTNER_0 = 956276527, PARTNER_1 = 568634990})
  WINDOW:SwitchTalk({PARTNER_0 = -1858345535, PARTNER_1 = -2011114368})
  WINDOW:SwitchTalk({PARTNER_0 = -1559394493, PARTNER_1 = -1172916734})
  WINDOW:SwitchTalk({PARTNER_0 = -178839355, PARTNER_1 = -330559100})
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -949927353, PARTNER_1 = -562400506})
  WINDOW:CloseMessage()
  TASK:Regist(subEveMoveDir, {
    CH("PARTNER"),
    SymPos("P03_PARTNER"),
    Speed(1.5),
    RotateTarget(180)
  })
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(subEveMoveDir, {
    CH("HERO"),
    SymPos("P00_CRYSTAL"),
    Speed(1.5),
    RotateTarget(180)
  })
  TASK:WaitTask()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.EMOTION)
  WINDOW:Monologue(1508011977)
  WINDOW:Monologue(1090084488)
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.THINK)
  WINDOW:Monologue(-2087826897)
  WINDOW:Monologue(-1701479570)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_NOTICE_L")
  CH("PARTNER"):WaitManpu()
  CH("PARTNER"):DirTo(RotateTarget(-160), Speed(200), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  TASK:Sleep(TimeSec(0.2))
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1313331027, PARTNER_1 = -1465706004})
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:SwitchTalk({PARTNER_0 = -404582613, PARTNER_1 = -17187222})
  WINDOW:CloseMessage()
  TASK:ExitNotifyTasks(Group("yuka"))
  CH("HERO"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WalkTo(SymPos("P00_CRYSTAL_GET"), Speed(2))
  CH("PARTNER"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_HAND"), Volume(256))
  GM("CRYSTAL_BIG"):SetVisible(false)
  WINDOW:SysMsg(-707465815)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -858792728, PARTNER_1 = 1264042023})
  WINDOW:CloseMessage()
  subEveNod(CH("HERO"))
  TASK:Regist(subEveMoveDir2, {
    CH("HERO"),
    SymPos("P00_EXIT"),
    Speed(2),
    RotateTarget(-60)
  })
  TASK:Sleep(TimeSec(0.5))
  TASK:Regist(subEveMoveDir2, {
    CH("PARTNER"),
    SymPos("P00_EXIT"),
    Speed(2),
    RotateTarget(-60)
  })
  SOUND:FadeOutEnv(TimeSec(1.5))
  TASK:Sleep(TimeSec(1))
  CAMERA:ResetAzimuthDifferenceVolume()
  SCREEN_A:FadeOutAll(TimeSec(0.5), true)
  SCREEN_A:FadeOut(TimeSec(0), true)
  SYSTEM:SetDungeonWaypointStat(Dg(4), DG_WAYPOINT.POINT02, DG_WAYPOINT_STAT.AFTER)
  SYSTEM:EnterDungeon(Dg(4), DG_WAYPOINT.POINT02)
  FLAG.SceneFlag = CONST.FL_SC_01_FIRST
  FLAG.SCENARIOFLAG = CONST.M03_NUONOOKURIMONO_END
  SYSTEM:NextEntry()
end
function main03_crystal01_end()
end
function groundEnd()
end

