dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main08_doukokunotaniboss1st01_init()
end
function main08_doukokunotaniboss1st01_start()
  subEveFromProgFadeSet()
  TASK:Sleep(TimeSec(1))
  CH("DOKUROGGU"):SetVisible(false)
  CH("BUNYATTO"):SetVisible(false)
  CH("HERO"):SetVisible(false)
  CH("PARTNER"):SetVisible(false)
  SOUND:PlaySe(SymSnd("SE_EVT_EEFI_RUN_LP"), Volume(256))
  TASK:Sleep(TimeSec(0.5))
  WINDOW:DrawFace(20, 88, SymAct("EEFI"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("EEFI"), 1808552121)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("EEFI"):RunTo(SymPos("P01_EEFI"), Speed(3))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.5))
  CAMERA:MoveFollow(SymCam("CAMERA_01"), Speed(3, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("EEFI"):WaitMove()
  SOUND:FadeOutSe(SymSnd("SE_EVT_EEFI_RUN_LP"), TimeSec(0.2))
  CAMERA:WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("EEFI"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("EEFI"), 1926717944)
  subEveCloseMsg()
  WINDOW:Talk(SymAct("???"), 1509569083)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_01"), Volume(256))
  CH("EEFI"):SetManpu("MP_EXCLAMATION")
  CH("EEFI"):WaitManpu()
  WINDOW:CloseMessage()
  CH("EEFI"):DirTo(CH("BUNYATTO"), Speed(500), ROT_TYPE.RIGHT)
  CH("EEFI"):WaitRotate()
  TASK:Sleep(TimeSec(0.1))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("EEFI"):SetManpu("MP_SHOCK_R")
  CH("EEFI"):WaitManpu()
  TASK:Sleep(TimeSec(0.2))
  CH("DOKUROGGU"):SetVisible(true)
  CH("DOKUROGGU"):SetShadow(false)
  CH("BUNYATTO"):SetVisible(true)
  CH("HERO"):SetVisible(true)
  CH("PARTNER"):SetVisible(true)
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  CH("BUNYATTO"):WalkTo(SymPos("P01_BUNYATTO"), Speed(1.5))
  SOUND:PlayBgm(SymSnd("BGM_EVE_FEAR_01"), Volume(256))
  TASK:Sleep(TimeSec(0.5))
  CH("EEFI"):WalkTo(SymPos("P02_EEFI"), Speed(1.2), LINK_DIR.OFF)
  TASK:Sleep(TimeSec(0.5))
  CAMERA:MoveFollow(SymCam("CAMERA_02"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("BUNYATTO"):WaitMove()
  CAMERA:WaitMove()
  WINDOW:DrawFace(324, 88, SymAct("BUNYATTO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("???"), 1088488314)
  WINDOW:Talk(SymAct("???"), 262182333)
  subEveCloseMsg()
  WINDOW:DrawFace(72, 16, SymAct("EEFI"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("EEFI"), 381396220)
  subEveCloseMsg()
  CH("EEFI"):WalkTo(SymPos("P06_EEFI"), Speed(1.2), LINK_DIR.OFF)
  CH("EEFI"):WaitMove()
  WINDOW:Talk(SymAct("???"), 1033303871)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("EEFI"):SetManpu("MP_SHOCK_R")
  CH("EEFI"):WaitManpu()
  CH("EEFI"):DirTo(RotateTarget(-135), Speed(500), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.3))
  CH("BUNYATTO"):DirTo(CH("DOKUROGGU"), Speed(350), ROT_TYPE.NEAR)
  CH("BUNYATTO"):WaitRotate()
  CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:Talk(SymAct("???"), 613271166)
  WINDOW:Talk(SymAct("???"), -1558848847)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_DOKUROGGU_JUMP"), Volume(256))
  CH("DOKUROGGU"):SetMotion(SymMot("JUMP"), LOOP.OFF)
  CH("DOKUROGGU"):WaitPlayMotion()
  CH("DOKUROGGU"):MoveHeightTo(Height(1.5), Speed(5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("DOKUROGGU"):WaitMoveHeight()
  CH("DOKUROGGU"):MoveTo(SymPos("P05_DOKUROGGU"), Speed(4))
  CH("DOKUROGGU"):SetMotion(SymMot("JUMPLOOP"), LOOP.ON)
  CAMERA:MoveFollow2(SymCam("CAMERA_07"), Speed(10, ACCEL_TYPE.NONE, DECEL_TYPE.NONE))
  CH("DOKUROGGU"):MoveHeightTo(Height(0), Speed(5, ACCEL_TYPE.HIGH, DECEL_TYPE.NONE))
  CH("DOKUROGGU"):WaitMoveHeight()
  CH("DOKUROGGU"):SetShadow(true)
  CH("DOKUROGGU"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  TASK:Sleep(TimeSec(0.1))
  SOUND:PlaySe(SymSnd("SE_EVT_DOKUROGGU_LAND"), Volume(256))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  WINDOW:Talk(SymAct("???"), -1173427216)
  WINDOW:CloseMessage()
  CH("DOKUROGGU"):WalkTo(SymPos("P01_DOKUROGGU"), Speed(1.7))
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.3))
  CH("EEFI"):RunTo(SymPos("P03_EEFI"), Speed(2))
  CH("EEFI"):WaitMove()
  CH("EEFI"):DirTo(RotateTarget(-45), Speed(350), ROT_TYPE.NEAR)
  CH("EEFI"):WaitRotate()
  CH("EEFI"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
  CH("DOKUROGGU"):WaitMove()
  CH("DOKUROGGU"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  CH("DOKUROGGU"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("BUNYATTO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BUNYATTO"), 2018471072)
  WINDOW:CloseMessage()
  CH("DOKUROGGU"):DirTo(CH("BUNYATTO"), Speed(350), ROT_TYPE.NEAR)
  CH("DOKUROGGU"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("DOKUROGGU"):SetManpu("MP_FLY_SWEAT")
  CH("DOKUROGGU"):WaitManpu()
  WINDOW:DrawFace(20, 20, SymAct("DOKUROGGU"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("DOKUROGGU"), 1632919009)
  WINDOW:CloseMessage()
  CH("DOKUROGGU"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.3))
  CH("BUNYATTO"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  CH("BUNYATTO"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("EEFI"):SetManpu("MP_SHOCK_L")
  CH("EEFI"):WalkTo(PosOffs(0.2, -0.2), Speed(1.5), LINK_DIR.OFF)
  CH("EEFI"):WaitManpu()
  TASK:Sleep(TimeSec(0.5))
  CAMERA:MoveFollow(SymCam("CAMERA_03"), Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("BUNYATTO"):WalkTo(SymPos("P02_BUNYATTO"), Speed(1.5))
  TASK:Sleep(TimeSec(0.3))
  CH("DOKUROGGU"):WalkTo(SymPos("P02_DOKUROGGU"), Speed(1.5))
  CH("EEFI"):WalkTo(SymPos("P04_EEFI"), Speed(1), LINK_DIR.OFF)
  CH("EEFI"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("EEFI"):SetManpu("MP_FLY_SWEAT")
  CH("EEFI"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("DOKUROGGU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DOKUROGGU"), 1249447458)
  WINDOW:Talk(SymAct("DOKUROGGU"), 1398947683)
  subEveCloseMsg()
  CAMERA:MoveFollow(SymCam("CAMERA_04"), Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("BUNYATTO"):WalkTo(SymPos("P03_BUNYATTO"), Speed(1))
  CH("DOKUROGGU"):WalkTo(SymPos("P03_DOKUROGGU"), Speed(1))
  CH("EEFI"):WalkTo(SymPos("P05_EEFI"), Speed(1), LINK_DIR.OFF)
  CH("DOKUROGGU"):WaitMove()
  CH("DOKUROGGU"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  CH("BUNYATTO"):WaitMove()
  CH("BUNYATTO"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  CH("DOKUROGGU"):WaitRotate()
  CAMERA:WaitMove()
  CH("EEFI"):WaitMove()
  WINDOW:DrawFace(324, 88, SymAct("BUNYATTO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BUNYATTO"), 472099236)
  WINDOW:Talk(SymAct("BUNYATTO"), 87595237)
  WINDOW:CloseMessage()
  CH("BUNYATTO"):RunTo(SymPos("P04_BUNYATTO"), Speed(2))
  CH("BUNYATTO"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_HAND"), Volume(256))
  CH("EEFI"):WalkTo(PosOffs(0, -0.1), Speed(1.5), LINK_DIR.OFF)
  CH("EEFI"):WaitMove()
  WINDOW:DrawFace(272, 16, SymAct("EEFI"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("EEFI"), 773180198)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_GOSOGOSO"), Volume(256))
  WINDOW:SysMsg(923728487)
  SOUND:WaitSe(SymSnd("SE_EVT_GOSOGOSO"))
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("BUNYATTO"):SetManpu("MP_EXCLAMATION")
  TASK:Regist(subEveJumpSurprise, {
    CH("BUNYATTO")
  })
  CH("BUNYATTO"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("BUNYATTO"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("BUNYATTO"), -1332287832)
  WINDOW:CloseMessage()
  CH("BUNYATTO"):WalkTo(SymPos("P03_BUNYATTO"), Speed(2.5), LINK_DIR.OFF)
  CH("BUNYATTO"):WaitMove()
  CH("DOKUROGGU"):DirTo(CH("BUNYATTO"), Speed(350), ROT_TYPE.NEAR)
  CH("DOKUROGGU"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("DOKUROGGU"):SetManpu("MP_QUESTION")
  CH("DOKUROGGU"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("DOKUROGGU"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("DOKUROGGU"), -1450321943)
  WINDOW:CloseMessage()
  CH("BUNYATTO"):DirTo(CH("DOKUROGGU"), Speed(350), ROT_TYPE.NEAR)
  CH("BUNYATTO"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("BUNYATTO"):SetManpu("MP_FLY_SWEAT")
  TASK:Regist(subEveJump, {
    CH("BUNYATTO")
  })
  WINDOW:DrawFace(324, 88, SymAct("BUNYATTO"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("BUNYATTO"), 1794818894)
  WINDOW:Talk(SymAct("BUNYATTO"), 1944187407)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("DOKUROGGU"):SetManpu("MP_SHOCK_R")
  TASK:Regist(subEveJumpSurprise, {
    CH("DOKUROGGU")
  })
  WINDOW:DrawFace(20, 88, SymAct("DOKUROGGU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("DOKUROGGU"), 1489805772)
  WINDOW:CloseMessage()
  CH("DOKUROGGU"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("BUNYATTO"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  CH("BUNYATTO"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_01"), Volume(256))
  CH("DOKUROGGU"):SetManpu("MP_ANGRY_LP")
  CH("DOKUROGGU"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  WINDOW:DrawFace(20, 88, SymAct("DOKUROGGU"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("DOKUROGGU"), 1104646285)
  WINDOW:Talk(SymAct("DOKUROGGU"), 244713034)
  WINDOW:CloseMessage()
  CH("DOKUROGGU"):ResetManpu()
  CH("EEFI"):WalkTo(PosOffs(0.1, -0.1), Speed(0.8), LINK_DIR.OFF)
  CH("EEFI"):WaitMove()
  CH("EEFI"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
  WINDOW:DrawFace(272, 16, SymAct("EEFI"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("EEFI"), 395130635)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  CH("BUNYATTO"):SetManpu("MP_ANGRY_LP")
  CH("BUNYATTO"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  WINDOW:DrawFace(324, 88, SymAct("BUNYATTO"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("BUNYATTO"), 1017144520)
  WINDOW:Talk(SymAct("BUNYATTO"), 633034121)
  subEveCloseMsg()
  CH("BUNYATTO"):ResetManpu()
  WINDOW:DrawFace(272, 16, SymAct("EEFI"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("EEFI"), -1574745786)
  subEveCloseMsg()
  SOUND:FadeOutBgm(TimeSec(0.5))
  SOUND:FadeInEnv(SymSnd("SE_ENV_CLIFF_LP"), TimeSec(1.5), Volume(256))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SHOUT)
  WINDOW:SwitchTalk({PARTNER_0 = -1153927161, PARTNER_1 = -767122389})
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_01"), Volume(256))
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  CH("DOKUROGGU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("BUNYATTO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("DOKUROGGU"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.3))
  CH("BUNYATTO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("BUNYATTO"):WaitRotate()
  CH("PARTNER"):RunTo(SymPos("P01_PARTNER"), Speed(2.5))
  CH("HERO"):RunTo(SymPos("P01_HERO"), Speed(2.5))
  TASK:Sleep(TimeSec(1))
  CAMERA:MoveFollow(SymCam("CAMERA_05"), Speed(2.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("PARTNER"):WaitMove()
  CH("PARTNER"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitMove()
  CH("HERO"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  CAMERA:WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = -883059350, PARTNER_1 = -529480023})
  WINDOW:SwitchTalk({PARTNER_0 = -110364696, PARTNER_1 = -1238736593})
  WINDOW:CloseMessage()
  CH("DOKUROGGU"):WalkTo(SymPos("P04_DOKUROGGU"), Speed(1.5))
  CH("BUNYATTO"):WalkTo(SymPos("P05_BUNYATTO"), Speed(1.5))
  TASK:Sleep(TimeSec(0.3))
  CH("PARTNER"):DirTo(RotateTarget(180), Speed(60), ROT_TYPE.NEAR)
  CH("HERO"):DirTo(RotateTarget(180), Speed(60), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.6))
  local taskEefi00 = function()
    CH("EEFI"):WalkTo(SplinePath(SymPos("P07_EEFI"), SymPos("P08_EEFI")), Speed(1.5))
    CH("EEFI"):WaitMove()
    CH("EEFI"):SetVisible(false)
  end
  TASK:Regist(taskEefi00)
  CH("BUNYATTO"):WaitMove()
  CH("BUNYATTO"):DirTo(RotateTarget(-10), Speed(350), ROT_TYPE.NEAR)
  CH("DOKUROGGU"):WaitMove()
  CH("DOKUROGGU"):DirTo(RotateTarget(10), Speed(350), ROT_TYPE.NEAR)
  CH("DOKUROGGU"):WaitRotate()
  WINDOW:DrawFace(272, 16, SymAct("BUNYATTO"), FACE_TYPE.THINK)
  WINDOW:DrawFaceOffset(15, 0)
  WINDOW:Talk(SymAct("BUNYATTO"), -1355722642)
  WINDOW:CloseMessage()
  subEveJump(CH("PARTNER"))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = -2078538835, PARTNER_1 = -1660472596})
  WINDOW:SwitchTalk({PARTNER_0 = 446639651, PARTNER_1 = 58990434})
  WINDOW:CloseMessage()
  CH("DOKUROGGU"):DirTo(CH("BUNYATTO"), Speed(350), ROT_TYPE.NEAR)
  CH("BUNYATTO"):DirTo(CH("DOKUROGGU"), Speed(350), ROT_TYPE.NEAR)
  CH("BUNYATTO"):WaitRotate()
  TASK:Sleep(TimeSec(0.5))
  CH("BUNYATTO"):DirTo(RotateTarget(-10), Speed(350), ROT_TYPE.NEAR)
  CH("DOKUROGGU"):DirTo(RotateTarget(10), Speed(350), ROT_TYPE.NEAR)
  CH("DOKUROGGU"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("DOKUROGGU"):SetManpu("MP_QUESTION")
  CH("DOKUROGGU"):WaitManpu()
  WINDOW:DrawFace(72, 16, SymAct("DOKUROGGU"), FACE_TYPE.THINK)
  WINDOW:DrawFaceOffset(-10, 0)
  WINDOW:Talk(SymAct("DOKUROGGU"), 1334942866)
  subEveCloseMsg()
  WINDOW:DrawFace(272, 16, SymAct("BUNYATTO"), FACE_TYPE.THINK)
  WINDOW:DrawFaceOffset(15, 0)
  WINDOW:Talk(SymAct("BUNYATTO"), 1451929043)
  WINDOW:CloseMessage()
  CH("DOKUROGGU"):DirTo(CH("BUNYATTO"), Speed(350), ROT_TYPE.NEAR)
  CH("DOKUROGGU"):WaitRotate()
  WINDOW:DrawFace(72, 16, SymAct("DOKUROGGU"), FACE_TYPE.NORMAL)
  WINDOW:DrawFaceOffset(-10, 0)
  WINDOW:Talk(SymAct("DOKUROGGU"), 2108161552)
  WINDOW:Talk(SymAct("DOKUROGGU"), 1690095441)
  WINDOW:CloseMessage()
  CH("BUNYATTO"):DirTo(CH("DOKUROGGU"), Speed(350), ROT_TYPE.NEAR)
  CH("BUNYATTO"):WaitRotate()
  WINDOW:DrawFace(272, 16, SymAct("BUNYATTO"), FACE_TYPE.NORMAL)
  WINDOW:DrawFaceOffset(15, 0)
  WINDOW:Talk(SymAct("BUNYATTO"), 738023830)
  WINDOW:CloseMessage()
  TASK:Sleep(TimeSec(0.5))
  CH("BUNYATTO"):DirTo(RotateTarget(-10), Speed(350), ROT_TYPE.NEAR)
  CH("DOKUROGGU"):DirTo(RotateTarget(10), Speed(350), ROT_TYPE.NEAR)
  CH("DOKUROGGU"):WaitRotate()
  CH("DOKUROGGU"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
  CH("BUNYATTO"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
  TASK:Sleep(TimeSec(0.5))
  SOUND:FadeOutEnv(TimeSec(1))
  SOUND:PlaySe(SymSnd("SE_EVT_FLUSH"), Volume(256))
  subEveFlash()
  CH("HERO"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
  CH("PARTNER"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = 853960919, PARTNER_1 = 432749332})
  subEveCloseMsg()
  WINDOW:DrawFace(72, 16, SymAct("DOKUROGGU"), FACE_TYPE.NORMAL)
  WINDOW:DrawFaceOffset(-10, 0)
  WINDOW:Talk(SymAct("DOKUROGGU"), 13634133)
  WINDOW:CloseMessage()
  subEveFlash2()
  WINDOW:DrawFace(72, 16, SymAct("DOKUROGGU"), FACE_TYPE.ANGRY)
  WINDOW:DrawFaceOffset(-10, 0)
  WINDOW:Talk(SymAct("DOKUROGGU"), -2025318758)
  subEveCloseMsg()
  WINDOW:DrawFace(272, 16, SymAct("BUNYATTO"), FACE_TYPE.ANGRY)
  WINDOW:DrawFaceOffset(15, 0)
  WINDOW:Talk(SymAct("BUNYATTO"), -1638717477)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_BOSS_WIPE"), Volume(256))
  EFFECT:BossWipe(TimeSec(60, TIME_TYPE.FRAME), true)
  CAMERA:ResetAzimuthDifferenceVolume()
  FLAG.SceneFlag = CONST.FL_SC_01_FIRST
  FLAG.SCENARIOFLAG = CONST.M08_DOUKOKUNOTANIBOSS1ST_END
  SYSTEM:SetDungeonWaypointStat(Dg(7), DG_WAYPOINT.DUNGEONEND, DG_WAYPOINT_STAT.AFTER)
  SYSTEM:SetNextDungeonBanner(false)
  SYSTEM:EnterDungeon(Dg(7), DG_WAYPOINT.BOSS00)
end
function main08_doukokunotaniboss1st01_end()
end
function groundEnd()
end

