dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main17_grepalacewestboss2nd01_init()
end
function main17_grepalacewestboss2nd01_start()
  subEveFromProgFadeSet()
  TASK:Sleep(TimeSec(1))
  CHARA:SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  CAMERA:SetAzimuthDifferenceVolume(Volume(6))
  CAMERA:SetEye(SymCam("CAMERA_00_5"))
  CAMERA:SetTgt(SymCam("CAMERA_00_5"))
  CH("DOKUROGGU"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("SHANDERA_1"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("GIGAIASU_1"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("GIGAIASU_2"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("GIGAIASU_3"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("GIGAIASU_4"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("MUNNA"):SetFacialMotion(FACIAL_MOTION.ANGRY)
  SOUND:PlayBgm(SymSnd("BGM_EVE_FEAR_01"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetEye(SymCam("CAMERA_00_6"))
  CAMERA:SetTgt(SymCam("CAMERA_00_6"))
  local taskScreenShake01 = function()
    CAMERA:SetShake(Vector2(0.01, 0.01), TimeSec(1, TIME_TYPE.FRAME))
    TASK:Sleep(TimeSec(0.3))
    CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  end
  TASK:Regist(taskScreenShake01)
  WINDOW:Talk(SymAct("MUNNA"), -295939003)
  WINDOW:Talk(SymAct("MUNNA"), -146316028)
  WINDOW:Talk(SymAct("MUNNA"), -597018937)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(1.5))
  CAMERA:SetAzimuthDifferenceVolume(Volume(6))
  CAMERA:SetEye(SymCam("CAMERA_00_5"))
  CAMERA:SetTgt(SymCam("CAMERA_00_5"))
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_FLUSH"), Volume(256))
  subEveFlash()
  CH("HERO"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.3))
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.3))
  TASK:Sleep(TimeSec(0.1))
  CH("EMONGA"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.3))
  CH("BIRIJION"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.3))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = -982448250, PARTNER_1 = -1976528575})
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetEye(SymCam("CAMERA_00_6"))
  CAMERA:SetTgt(SymCam("CAMERA_00_6"))
  CH("MUNNA"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.3))
  subEveFlash2()
  WINDOW:Talk(SymAct("MUNNA"), -1825857536)
  WINDOW:Talk(SymAct("MUNNA"), -1207503933)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(6))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  EFFECT:StartMotionBlur(0.04, 0.9, 0)
  CAMERA:MoveFollow2(SymCam("CAMERA_00_5"), Speed(15, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  WINDOW:Talk(SymAct("GIGAIASU_1"), -1591885182)
  TASK:Sleep(TimeSec(0.3))
  WINDOW:ForceCloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_BOSS_WIPE"), Volume(256))
  EFFECT:BossWipe(TimeSec(60, TIME_TYPE.FRAME), true)
  EFFECT:EndMotionBlur()
  CAMERA:ResetAzimuthDifferenceVolume()
  FLAG.SceneFlag = CONST.FL_SC_01_FIRST
  FLAG.SCENARIOFLAG = CONST.M17_GREPALACEWESTBOSS2ND_END
  SYSTEM:SetNextDungeonBanner(false)
  SYSTEM:EnterDungeon(Dg(21), DG_WAYPOINT.BOSS00)
end
function main17_grepalacewestboss2nd01_end()
end
function groundEnd()
end

