dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main10_chimyakukandouclear1st01_init()
end
function main10_chimyakukandouclear1st01_start()
  subEveFromProgFadeSet()
  if FLAG.NowResumeFlag == CONST.FLAG_FALSE then
    subComResultClear()
    -- TASK:Sleep(TimeSec(0.2))
    -- if Ground_Save(ground) then
    --   return
    -- end
  end
  -- TASK:Sleep(TimeSec(1))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- CAMERA:MoveFollow(SymCam("CAMERA_01"), Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.NONE))
  -- SOUND:FadeInEnv(SymSnd("SE_EVT_COLD_LP"), TimeSec(0.5), Volume(256))
  -- SCREEN_A:FadeIn(TimeSec(1), true)
  -- TASK:Sleep(TimeSec(2.5))
  -- SOUND:VolumeEnv(Volume(128), TimeSec(1))
  -- SCREEN_A:FadeOut(TimeSec(0.5), true)
  FLAG.SceneFlag = CONST.FL_SC_01_END
  FLAG.SCENARIOFLAG = CONST.M10_CHIMYAKUKANDOUCLEAR1ST_START
  SYSTEM:NextEntry()
end
function main10_chimyakukandouclear1st01_end()
end
function main10_chimyakukandouclear1st02_init()
end
function main10_chimyakukandouclear1st02_start()
  -- SOUND:PlayEnv(SymSnd("SE_EVT_COLD_LP"), Volume(128))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- GM("MAGNAGATE_CIRCLE1"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  -- GM("MAGNAGATE_CIRCLE2"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  -- GM("MAGNAGATE_CIRCLE3"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  -- GM("MAGNAGATE_TUBE"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  -- CH("HERO"):SetScale(Scale(0, 4, 0))
  -- CH("PARTNER"):SetScale(Scale(0, 4, 0))
  -- CH("NOKOTCHI"):SetScale(Scale(0, 4, 0))
  -- CH("BIRIJION"):SetScale(Scale(0, 4, 0))
  -- CH("BURAKKII"):SetScale(Scale(0, 4, 0))
  -- CH("EEFI"):SetScale(Scale(0, 4, 0))
  -- CH("HERO"):SetShadow(false)
  -- CH("PARTNER"):SetShadow(false)
  -- CH("NOKOTCHI"):SetShadow(false)
  -- CH("BIRIJION"):SetShadow(false)
  -- CH("BURAKKII"):SetShadow(false)
  -- CH("EEFI"):SetShadow(false)
  -- GM("MAGNAGATE"):SetVisible(false)
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- TASK:Sleep(TimeSec(0.5))
  -- MAP:ChangeLightColor(Color(0.2, 0.2, 0.2, 1), TimeSec(30, TIME_TYPE.FRAME))
  -- MAP:ChangeProjectionShadowAlpha(0, TimeSec(30, TIME_TYPE.FRAME))
  -- EFFECT:Create("effectGatebaseOkEnd", SymEff("EV_GATEBASE_OK_END"))
  -- EFFECT:SetPosition("effectGatebaseOkEnd", SymPos("P_EFF_EV_GATEBASE_START"))
  -- EFFECT:Create("effectGatebaseOkExpandS", SymEff("EV_GATEBASE_OK_EXPANDED_S"))
  -- EFFECT:SetPosition("effectGatebaseOkExpandS", SymPos("P_EFF_EV_GATEBASE_START"))
  -- EFFECT:Play("effectGatebaseOkExpandS")
  -- TASK:Sleep(TimeSec(30, TIME_TYPE.FRAME))
  -- GM("MAGNAGATE_CIRCLE1"):ChangeColor(Color(1, 1, 1, 1), TimeSec(10, TIME_TYPE.FRAME))
  -- GM("MAGNAGATE_CIRCLE2"):ChangeColor(Color(1, 1, 1, 1), TimeSec(10, TIME_TYPE.FRAME))
  -- GM("MAGNAGATE_CIRCLE3"):ChangeColor(Color(1, 1, 1, 1), TimeSec(10, TIME_TYPE.FRAME))
  -- SOUND:PlaySe(SymSnd("SE_EVT_MAGNAGATE_EXIT"), Volume(256))
  -- TASK:Sleep(TimeSec(50, TIME_TYPE.FRAME))
  -- CAMERA:SetShake(Vector2(0.04, 0.04), TimeSec(1, TIME_TYPE.FRAME))
  -- GM("MAGNAGATE_TUBE"):ChangeColor(Color(1, 1, 1, 1), TimeSec(10, TIME_TYPE.FRAME))
  -- GM("MAGNAGATE"):SetVisible(true)
  -- TASK:Sleep(TimeSec(20, TIME_TYPE.FRAME))
  -- CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  -- EFFECT:Create("effectGatebaseOkLp", SymEff("EV_GATEBASE_OK_LP"))
  -- EFFECT:SetPosition("effectGatebaseOkLp", SymPos("P_EFF_EV_GATEBASE_START"))
  -- EFFECT:Play("effectGatebaseOkLp")
  -- TASK:Sleep(TimeSec(0.5))
  -- CH("HERO"):ChangeScale(Scale(1, 1, 1), TimeSec(5, TIME_TYPE.FRAME))
  -- CH("PARTNER"):ChangeScale(Scale(1, 1, 1), TimeSec(5, TIME_TYPE.FRAME))
  -- CH("NOKOTCHI"):ChangeScale(Scale(1, 1, 1), TimeSec(5, TIME_TYPE.FRAME))
  -- CH("BIRIJION"):ChangeScale(Scale(1, 1, 1), TimeSec(5, TIME_TYPE.FRAME))
  -- CH("BURAKKII"):ChangeScale(Scale(1, 1, 1), TimeSec(5, TIME_TYPE.FRAME))
  -- CH("EEFI"):ChangeScale(Scale(1, 1, 1), TimeSec(5, TIME_TYPE.FRAME))
  -- CH("HERO"):SetShadow(true)
  -- CH("PARTNER"):SetShadow(true)
  -- CH("NOKOTCHI"):SetShadow(true)
  -- CH("BIRIJION"):SetShadow(true)
  -- CH("BURAKKII"):SetShadow(true)
  -- CH("EEFI"):SetShadow(true)
  -- TASK:Sleep(TimeSec(0.5))
  -- GM("MAGNAGATE_CIRCLE1"):SetMotion(SymMot("VANISH"), LOOP.OFF)
  -- GM("MAGNAGATE_CIRCLE2"):SetMotion(SymMot("VANISH"), LOOP.OFF)
  -- GM("MAGNAGATE_CIRCLE3"):SetMotion(SymMot("VANISH"), LOOP.OFF)
  -- GM("MAGNAGATE_TUBE"):SetVisible(false)
  -- GM("MAGNAGATE_CIRCLE3"):WaitPlayMotion()
  -- GM("MAGNAGATE_CIRCLE1"):SetVisible(false)
  -- GM("MAGNAGATE_CIRCLE2"):SetVisible(false)
  -- GM("MAGNAGATE_CIRCLE3"):SetVisible(false)
  -- TASK:Sleep(TimeSec(0.1))
  -- CAMERA:SetShake(Vector2(0.04, 0.04), TimeSec(1, TIME_TYPE.FRAME))
  -- EFFECT:Remove("effectGatebaseOkLp")
  -- EFFECT:Play("effectGatebaseOkEnd")
  -- TASK:Sleep(TimeSec(20, TIME_TYPE.FRAME))
  -- CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  -- TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
  -- MAP:ReturnLightColor(TimeSec(20, TIME_TYPE.FRAME))
  -- MAP:ChangeProjectionShadowAlpha(1, TimeSec(20, TIME_TYPE.FRAME))
  -- GM("MAGNAGATE"):SetMotion(SymMot("VANISH"), LOOP.OFF)
  -- TASK:Sleep(TimeSec(5, TIME_TYPE.FRAME))
  -- CAMERA:SetShake(Vector2(0.01, 0.01), TimeSec(0.5, TIME_TYPE.FRAME))
  -- GM("MAGNAGATE"):WaitPlayMotion()
  -- GM("MAGNAGATE"):SetVisible(false)
  -- EFFECT:Remove("effectGatebaseOkExpandS")
  -- TASK:Sleep(TimeSec(0.5))
  -- CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  -- TASK:Sleep(TimeSec(1.5))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_01"))
  -- CAMERA:SetTgt(SymCam("CAMERA_01"))
  -- local taskHeroLookAround = function()
  --   CH("HERO"):DirTo(RotateTarget(-45), Speed(350), ROT_TYPE.NEAR)
  --   CH("HERO"):WaitRotate()
  --   TASK:Sleep(TimeSec(0.2))
  --   CH("HERO"):DirTo(RotateTarget(160), Speed(350), ROT_TYPE.NEAR)
  --   CH("HERO"):WaitRotate()
  --   TASK:Sleep(TimeSec(0.4))
  --   CH("HERO"):DirTo(RotateTarget(35), Speed(350), ROT_TYPE.NEAR)
  --   CH("HERO"):WaitRotate()
  -- end
  -- local taskPartnerLookAround = function()
  --   CH("PARTNER"):DirTo(RotateTarget(30), Speed(350), ROT_TYPE.NEAR)
  --   CH("PARTNER"):WaitRotate()
  --   TASK:Sleep(TimeSec(0.2))
  --   CH("PARTNER"):DirTo(RotateTarget(-120), Speed(350), ROT_TYPE.NEAR)
  --   CH("PARTNER"):WaitRotate()
  --   TASK:Sleep(TimeSec(0.3))
  --   CH("PARTNER"):DirTo(RotateTarget(-40), Speed(350), ROT_TYPE.NEAR)
  --   CH("PARTNER"):WaitRotate()
  -- end
  -- local taskNokotchiLookAround = function()
  --   CH("NOKOTCHI"):DirTo(RotateTarget(40), Speed(350), ROT_TYPE.NEAR)
  --   CH("NOKOTCHI"):WaitRotate()
  --   TASK:Sleep(TimeSec(0.2))
  --   CH("NOKOTCHI"):DirTo(RotateTarget(-45), Speed(350), ROT_TYPE.NEAR)
  --   CH("NOKOTCHI"):WaitRotate()
  --   TASK:Sleep(TimeSec(0.2))
  --   CH("NOKOTCHI"):DirTo(RotateTarget(45), Speed(350), ROT_TYPE.NEAR)
  --   CH("NOKOTCHI"):WaitRotate()
  -- end
  -- local taskBurakkiiLookAround = function()
  --   CH("BURAKKII"):DirTo(RotateTarget(100), Speed(350), ROT_TYPE.NEAR)
  --   CH("BURAKKII"):WaitRotate()
  --   TASK:Sleep(TimeSec(0.35))
  --   CH("BURAKKII"):DirTo(RotateTarget(-80), Speed(350), ROT_TYPE.LEFT)
  --   CH("BURAKKII"):WaitRotate()
  --   TASK:Sleep(TimeSec(0.3))
  --   CH("BURAKKII"):DirTo(RotateTarget(-120), Speed(350), ROT_TYPE.NEAR)
  --   CH("BURAKKII"):WaitRotate()
  -- end
  -- local taskEefiLookAround = function()
  --   CH("EEFI"):DirTo(RotateTarget(-10), Speed(350), ROT_TYPE.NEAR)
  --   CH("EEFI"):WaitRotate()
  --   TASK:Sleep(TimeSec(0.3))
  --   CH("EEFI"):DirTo(RotateTarget(50), Speed(350), ROT_TYPE.NEAR)
  --   CH("EEFI"):WaitRotate()
  --   TASK:Sleep(TimeSec(0.2))
  --   CH("EEFI"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.NEAR)
  --   CH("EEFI"):WaitRotate()
  -- end
  -- local taskBirijionLookAround = function()
  --   CH("BIRIJION"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.NEAR)
  --   CH("BIRIJION"):WaitRotate()
  --   TASK:Sleep(TimeSec(0.2))
  --   CH("BIRIJION"):DirTo(RotateTarget(30), Speed(350), ROT_TYPE.NEAR)
  --   CH("BIRIJION"):WaitRotate()
  --   TASK:Sleep(TimeSec(0.3))
  --   CH("BIRIJION"):DirTo(RotateTarget(-40), Speed(350), ROT_TYPE.NEAR)
  --   CH("BIRIJION"):WaitRotate()
  -- end
  -- TASK:Sleep(TimeSec(0.3))
  -- TASK:Regist(Group("hero"), taskHeroLookAround)
  -- TASK:Sleep(TimeSec(0.2))
  -- TASK:Regist(Group("grpBura"), taskBurakkiiLookAround)
  -- TASK:Sleep(TimeSec(0.2))
  -- TASK:Regist(Group("grpBiri"), taskBirijionLookAround)
  -- TASK:Sleep(TimeSec(0.3))
  -- TASK:Regist(Group("partner"), taskPartnerLookAround)
  -- TASK:Sleep(TimeSec(0.2))
  -- TASK:Regist(Group("grpEefi"), taskEefiLookAround)
  -- TASK:Sleep(TimeSec(0.1))
  -- TASK:Regist(Group("grpNoko"), taskNokotchiLookAround)
  -- TASK:WaitTask(Group("grpNoko"))
  -- TASK:Sleep(TimeSec(0.2))
  -- WINDOW:DrawFaceF(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  -- WINDOW:SwitchTalk({PARTNER_0 = -1070187035, PARTNER_1 = -651359068})
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_02"))
  -- CAMERA:SetTgt(SymCam("CAMERA_02"))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  -- TASK:Sleep(TimeSec(0.3))
  -- WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.SURPRISE)
  -- WINDOW:Talk(SymAct("NOKOTCHI"), -234856601)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_01"))
  -- CAMERA:SetTgt(SymCam("CAMERA_01"))
  -- TASK:Sleep(TimeSec(0.3))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  -- CH("BURAKKII"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  -- CH("BURAKKII"):WaitRotate()
  -- CH("BURAKKII"):SetManpu("MP_EXCLAMATION")
  -- CH("BURAKKII"):WaitManpu()
  -- WINDOW:DrawFace(72, 16, SymAct("BURAKKII"), FACE_TYPE.SURPRISE)
  -- WINDOW:Talk(SymAct("BURAKKII"), -350523866)
  -- SOUND:FadeOutEnv(TimeSec(2.5))
  -- CH("EEFI"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  -- CH("BIRIJION"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.2))
  -- CH("HERO"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  -- CH("NOKOTCHI"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("PARTNER"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  -- WINDOW:CloseMessage()
  -- CAMERA:MoveFollow(SymCam("CAMERA_03"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- CH("BURAKKII"):WalkTo(SymPos("P01_BURAKKII"), Speed(2))
  -- TASK:Sleep(TimeSec(0.5))
  -- CH("EEFI"):WalkTo(SymPos("P01_EEFI"), Speed(1.7))
  -- CH("NOKOTCHI"):WalkTo(SymPos("P01_NOKOTCHI"), Speed(1.7))
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("BIRIJION"):WalkTo(SymPos("P01_BIRIJION"), Speed(1.7))
  -- CH("PARTNER"):WalkTo(SymPos("P01_PARTNER"), Speed(1.7))
  -- TASK:Sleep(TimeSec(0.2))
  -- CH("HERO"):WalkTo(SymPos("P01_HERO"), Speed(1.7))
  -- SCREEN_A:FadeOut(TimeSec(0.5), true)
  FLAG.SceneFlag = CONST.FL_SC_02_END
  FLAG.SCENARIOFLAG = CONST.M10_CHIMYAKUKANDOUCLEAR1ST_START
  SYSTEM:NextEntry()
end
function main10_chimyakukandouclear1st02_end()
end
function main10_chimyakukandouclear1st03_init()
end
function main10_chimyakukandouclear1st03_start()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_DAIHYOUGA_01"), Volume(256))
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- CAMERA:WaitMove()
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  -- WINDOW:SwitchTalk({PARTNER_0 = -1537541919, PARTNER_1 = -1119762016})
  -- WINDOW:SwitchTalk({PARTNER_0 = -1771267485, PARTNER_1 = -1887982814})
  -- WINDOW:SwitchTalk({PARTNER_0 = 149927917, PARTNER_1 = 301237932})
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(324, 88, SymAct("NOKOTCHI"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("NOKOTCHI"), 1564657895)
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(324, 88, SymAct("BURAKKII"), FACE_TYPE.EMOTION)
  -- WINDOW:Talk(SymAct("BURAKKII"), 1146747302)
  -- WINDOW:Talk(SymAct("BURAKKII"), 1869916773)
  -- WINDOW:Talk(SymAct("BURAKKII"), 1987025700)
  -- WINDOW:Talk(SymAct("BURAKKII"), 959319523)
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  -- WINDOW:SwitchTalk({PARTNER_0 = 540359842, PARTNER_1 = 186150753})
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(324, 88, SymAct("BURAKKII"), FACE_TYPE.EMOTION)
  -- WINDOW:Talk(SymAct("BURAKKII"), 302210592)
  -- WINDOW:Talk(SymAct("BURAKKII"), -1784986897)
  -- WINDOW:CloseMessage()
  -- SCREEN_A:FadeOut(TimeSec(0.5), true)
  -- CAMERA:ResetAzimuthDifferenceVolume()
  FLAG.SceneFlag = CONST.FL_SC_03_END
  FLAG.SCENARIOFLAG = CONST.M10_CHIMYAKUKANDOUCLEAR1ST_START
  SYSTEM:NextEntry()
end
function main10_chimyakukandouclear1st03_end()
end
function main10_chimyakukandouclear1st04_init()
end
function main10_chimyakukandouclear1st04_start()
  -- SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_DAIHYOUGA_01"), Volume(256))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- CH("EEFI"):DirTo(RotateTarget(-45), Speed(350), ROT_TYPE.LEFT)
  -- CH("EEFI"):WaitRotate()
  -- TASK:Sleep(TimeSec(0.5))
  -- CH("EEFI"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.LEFT)
  -- CH("EEFI"):WaitRotate()
  -- TASK:Sleep(TimeSec(0.5))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  -- CH("EEFI"):SetManpu("MP_EXCLAMATION")
  -- CH("EEFI"):WaitManpu()
  -- CAMERA:MoveFollow(SymCam("CAMERA_01"), Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- CH("EEFI"):WalkTo(SymPos("P01_EEFI"), Speed(2))
  -- CAMERA:WaitMove()
  -- WINDOW:DrawFace(20, 88, SymAct("EEFI"), FACE_TYPE.EMOTION)
  -- WINDOW:Talk(SymAct("EEFI"), -1937738834)
  -- WINDOW:CloseMessage()
  -- CH("BURAKKII"):DirTo(RotateTarget(0), Speed(500), ROT_TYPE.LEFT)
  -- CH("BIRIJION"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.LEFT)
  -- TASK:Sleep(TimeSec(0.2))
  -- CH("HERO"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.RIGHT)
  -- CH("NOKOTCHI"):DirTo(RotateTarget(0), Speed(500), ROT_TYPE.RIGHT)
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("PARTNER"):DirTo(RotateTarget(0), Speed(500), ROT_TYPE.LEFT)
  -- TASK:Sleep(TimeSec(0.5))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  -- CH("BURAKKII"):SetManpu("MP_EXCLAMATION")
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  -- CH("NOKOTCHI"):SetManpu("MP_EXCLAMATION")
  -- TASK:Regist(subEveJump, {
  --   CH("NOKOTCHI")
  -- })
  -- TASK:Sleep(TimeSec(0.5))
  -- CH("HERO"):WalkTo(SymPos("P01_HERO"), Speed(1.7))
  -- CH("NOKOTCHI"):WalkTo(SymPos("P01_NOKOTCHI"), Speed(1.7))
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("BURAKKII"):WalkTo(SymPos("P01_BURAKKII"), Speed(1.7))
  -- CH("PARTNER"):WalkTo(SymPos("P01_PARTNER"), Speed(1.7))
  -- TASK:Sleep(TimeSec(0.2))
  -- CH("BIRIJION"):WalkTo(SymPos("P01_BIRIJION"), Speed(1.7))
  -- TASK:Sleep(TimeSec(0.7))
  -- SCREEN_A:FadeOut(TimeSec(0.5), true)
  FLAG.SceneFlag = CONST.FL_SC_04_END
  FLAG.SCENARIOFLAG = CONST.M10_CHIMYAKUKANDOUCLEAR1ST_START
  SYSTEM:NextEntry()
end
function main10_chimyakukandouclear1st04_end()
end
function main10_chimyakukandouclear1st05_init()
end
function main10_chimyakukandouclear1st05_start()
  -- SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_DAIHYOUGA_01"), Volume(256))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(7, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- CAMERA:WaitMove()
  -- WINDOW:DrawFace(20, 88, SymAct("EEFI"), FACE_TYPE.EMOTION)
  -- WINDOW:Talk(SymAct("EEFI"), 1341613833)
  -- WINDOW:Talk(SymAct("EEFI"), 1458329160)
  -- WINDOW:Talk(SymAct("EEFI"), 2109801867)
  -- WINDOW:Talk(SymAct("EEFI"), 1692021962)
  -- WINDOW:CloseMessage()
  -- SCREEN_A:FadeOut(TimeSec(0.5), true)
  FLAG.SceneFlag = CONST.FL_SC_05_END
  FLAG.SCENARIOFLAG = CONST.M10_CHIMYAKUKANDOUCLEAR1ST_START
  SYSTEM:NextEntry()
end
function main10_chimyakukandouclear1st05_end()
end
function main10_chimyakukandouclear1st06_init()
end
function main10_chimyakukandouclear1st06_start()
  -- SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_DAIHYOUGA_01"), Volume(256))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- TASK:Sleep(TimeSec(0.5))
  -- CH("EEFI"):DirTo(CH("BURAKKII"), Speed(350), ROT_TYPE.NEAR)
  -- CH("EEFI"):WaitRotate()
  -- CH("BURAKKII"):DirTo(CH("EEFI"), Speed(200), ROT_TYPE.NEAR)
  -- CH("BURAKKII"):WaitRotate()
  -- TASK:Sleep(TimeSec(0.5))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  -- CAMERA:SetEye(SymCam("CAMERA_01"))
  -- CAMERA:SetTgt(SymCam("CAMERA_01"))
  -- CH("HERO"):DirTo(CH("BURAKKII"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.2))
  -- CH("PARTNER"):DirTo(CH("BURAKKII"), Speed(350), ROT_TYPE.NEAR)
  -- CH("BIRIJION"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("NOKOTCHI"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  -- CH("BURAKKII"):SetManpu("MP_SPREE_LP")
  -- TASK:Regist(subEveDoubleJump, {
  --   CH("BURAKKII")
  -- })
  -- WINDOW:DrawFace(272, 16, SymAct("BURAKKII"), FACE_TYPE.EMOTION)
  -- WINDOW:Talk(SymAct("BURAKKII"), 731619853)
  -- CH("BURAKKII"):ResetManpu()
  -- subEveCloseMsg()
  -- CH("EEFI"):SetManpu("MP_SPREE_LP")
  -- WINDOW:DrawFace(20, 88, SymAct("EEFI"), FACE_TYPE.EMOTION)
  -- WINDOW:Talk(SymAct("EEFI"), 847287116)
  -- WINDOW:KeyWait()
  -- CH("EEFI"):ResetManpu()
  -- WINDOW:Talk(SymAct("EEFI"), 430817423)
  -- subEveCloseMsg()
  -- TASK:Regist(subEveNod, {
  --   CH("BURAKKII")
  -- })
  -- WINDOW:DrawFace(272, 16, SymAct("BURAKKII"), FACE_TYPE.EMOTION)
  -- WINDOW:Talk(SymAct("BURAKKII"), 11989454)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(6))
  -- CAMERA:SetEye(SymCam("CAMERA_03"))
  -- CAMERA:SetTgt(SymCam("CAMERA_03"))
  -- TASK:Sleep(TimeSec(0.3))
  -- CH("BURAKKII"):SetDir(RotateTarget(180))
  -- CH("BIRIJION"):SetDir(CH("BURAKKII"))
  -- CH("BURAKKII"):SetDir(CH("BURAKKII"))
  -- WINDOW:DrawFace(20, 88, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("BURAKKII"), -2026967807)
  -- WINDOW:Talk(SymAct("BURAKKII"), -1640637376)
  -- WINDOW:Talk(SymAct("BURAKKII"), -146079636)
  -- WINDOW:Talk(SymAct("BURAKKII"), -296734419)
  -- WINDOW:Talk(SymAct("BURAKKII"), -981638418)
  -- WINDOW:Talk(SymAct("BURAKKII"), -597273681)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  -- CAMERA:SetEye(SymCam("CAMERA_02"))
  -- CAMERA:SetTgt(SymCam("CAMERA_02"))
  -- TASK:Sleep(TimeSec(0.2))
  -- TASK:Regist(subEveDoubleJump, {
  --   CH("PARTNER")
  -- })
  -- WINDOW:DrawFace(272, 88, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  -- WINDOW:DrawFaceOffset(-30, 0)
  -- WINDOW:SwitchTalk({PARTNER_0 = -1826110104, PARTNER_1 = -1975716823})
  -- CH("EEFI"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  -- CH("NOKOTCHI"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.2))
  -- CH("BURAKKII"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  -- CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  -- CH("BIRIJION"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  -- WINDOW:SwitchTalk({PARTNER_0 = -1592678422, PARTNER_1 = -1207265621})
  -- WINDOW:CloseMessage()
  -- CH("EEFI"):SetManpu("MP_LAUGH_LP")
  -- TASK:Sleep(TimeSec(0.3))
  -- CH("PARTNER"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("NOKOTCHI"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  -- CH("BURAKKII"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("HERO"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  -- CH("BIRIJION"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  -- CH("EEFI"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  -- WINDOW:DrawFace(20, 88, SymAct("EEFI"), FACE_TYPE.GLADNESS)
  -- WINDOW:Talk(SymAct("EEFI"), 1066568292)
  -- WINDOW:Talk(SymAct("EEFI"), 646560549)
  -- WINDOW:CloseMessage()
  -- CH("EEFI"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  -- CH("EEFI"):ResetManpu()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  -- CH("BURAKKII"):SetManpu("MP_ANGRY_LP")
  -- TASK:Regist(subEveDoubleJump, {
  --   CH("BURAKKII")
  -- })
  -- CH("PARTNER"):DirTo(CH("BURAKKII"), Speed(350), ROT_TYPE.NEAR)
  -- WINDOW:DrawFace(226, 8, SymAct("BURAKKII"), FACE_TYPE.ANGRY)
  -- WINDOW:DrawFaceOffset(15, 0)
  -- WINDOW:Talk(SymAct("BURAKKII"), 1788623061)
  -- CH("BURAKKII"):ResetManpu()
  -- WINDOW:CloseMessage()
  -- CH("EEFI"):DirTo(CH("BURAKKII"), Speed(350), ROT_TYPE.NEAR)
  -- CH("EEFI"):WaitRotate()
  -- CH("EEFI"):SetManpu("MP_LAUGH_LP")
  -- WINDOW:DrawFace(20, 88, SymAct("EEFI"), FACE_TYPE.GLADNESS)
  -- WINDOW:Talk(SymAct("EEFI"), 1938229652)
  -- WINDOW:CloseMessage()
  -- CH("EEFI"):ResetManpu()
  -- CH("EEFI"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  -- CH("EEFI"):WaitRotate()
  -- CH("PARTNER"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  -- WINDOW:DrawFace(20, 88, SymAct("EEFI"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("EEFI"), 1487559255)
  -- WINDOW:Talk(SymAct("EEFI"), 1102146326)
  -- WINDOW:Talk(SymAct("EEFI"), 250674641)
  -- WINDOW:CloseMessage()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  -- CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  -- CH("PARTNER"):WaitManpu()
  -- WINDOW:DrawFace(272, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  -- WINDOW:DrawFaceOffset(-30, 0)
  -- WINDOW:SwitchTalk({PARTNER_0 = 401329296, PARTNER_1 = 1019649875})
  -- subEveCloseMsg()
  -- CH("BURAKKII"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  -- CH("BURAKKII"):WaitRotate()
  -- WINDOW:DrawFace(226, 8, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  -- WINDOW:DrawFaceOffset(15, 0)
  -- WINDOW:Talk(SymAct("BURAKKII"), 635285010)
  -- WINDOW:CloseMessage()
  -- CH("PARTNER"):DirTo(CH("BURAKKII"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("HERO"):DirTo(CH("BURAKKII"), Speed(350), ROT_TYPE.NEAR)
  -- CH("NOKOTCHI"):DirTo(CH("BURAKKII"), Speed(350), ROT_TYPE.NEAR)
  -- CH("EEFI"):DirTo(CH("BURAKKII"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.2))
  -- CH("BURAKKII"):DirTo(CH("BURAKKII"), Speed(350), ROT_TYPE.NEAR)
  -- CH("BIRIJION"):DirTo(CH("BURAKKII"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.3))
  -- WINDOW:DrawFace(226, 8, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  -- WINDOW:DrawFaceOffset(15, 0)
  -- WINDOW:Talk(SymAct("BURAKKII"), -1572490531)
  -- WINDOW:Talk(SymAct("BURAKKII"), -1151433828)
  -- WINDOW:KeyWait()
  -- TASK:Regist(subEveDoubleJump, {
  --   CH("BURAKKII")
  -- })
  -- WINDOW:DrawFace(226, 8, SymAct("BURAKKII"), FACE_TYPE.EMOTION)
  -- WINDOW:DrawFaceOffset(15, 0)
  -- WINDOW:Talk(SymAct("BURAKKII"), -769630288)
  -- subEveCloseMsg()
  -- TASK:Regist(subEveJump, {
  --   CH("PARTNER")
  -- })
  -- WINDOW:DrawFace(272, 88, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  -- WINDOW:DrawFaceOffset(-30, 0)
  -- WINDOW:SwitchTalk({PARTNER_0 = -885297423, PARTNER_1 = -535413454})
  -- WINDOW:SwitchTalk({PARTNER_0 = -116585357, PARTNER_1 = -1236493644})
  -- WINDOW:KeyWait()
  -- CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  -- CH("PARTNER"):SetManpu("MP_LAUGH_LP")
  -- TASK:Regist(subEveDoubleJump, {
  --   CH("PARTNER")
  -- })
  -- WINDOW:DrawFace(272, 88, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  -- WINDOW:DrawFaceOffset(-30, 0)
  -- WINDOW:SwitchTalk({PARTNER_0 = -1353208843, PARTNER_1 = -2072315850})
  -- WINDOW:CloseMessage()
  -- CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  -- CH("PARTNER"):ResetManpu()
  -- CH("NOKOTCHI"):SetManpu("MP_SPREE_LP")
  -- subEveDoubleJump(CH("NOKOTCHI"))
  -- WINDOW:DrawFace(324, 20, SymAct("NOKOTCHI"), FACE_TYPE.HAPPY)
  -- WINDOW:Talk(SymAct("NOKOTCHI"), -1654535817)
  -- WINDOW:CloseMessage()
  -- CH("NOKOTCHI"):ResetManpu()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- TASK:Sleep(TimeSec(0.3))
  -- CH("PARTNER"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  -- CH("PARTNER"):WaitRotate()
  -- TASK:Regist(subEveDoubleJump, {
  --   CH("PARTNER")
  -- })
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  -- WINDOW:SwitchTalk({PARTNER_0 = 452580792, PARTNER_1 = 65201401})
  -- WINDOW:CloseMessage()
  -- CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("BIRIJION"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.2))
  -- CH("BURAKKII"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  -- CH("NOKOTCHI"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  -- CH("EEFI"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  -- CH("EEFI"):WaitRotate()
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  -- WINDOW:SwitchTalk({PARTNER_0 = -1063915426, PARTNER_1 = -644955873})
  -- WINDOW:SwitchTalk({PARTNER_0 = -224161060, PARTNER_1 = -340221027})
  -- WINDOW:SwitchTalk({PARTNER_0 = -1527171750, PARTNER_1 = -1109261285})
  -- WINDOW:SwitchTalk({PARTNER_0 = -1764796456, PARTNER_1 = -1881905511})
  -- subEveDoubleJump(CH("PARTNER"))
  -- WINDOW:CloseMessage()
  -- TASK:Sleep(TimeSec(0.3))
  -- CH("HERO"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  -- CH("PARTNER"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  -- CH("BIRIJION"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  -- CH("NOKOTCHI"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  -- CH("BURAKKII"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  -- CH("EEFI"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
  -- CH("PARTNER"):SetManpu("MP_SPREE_LP")
  -- CH("NOKOTCHI"):SetManpu("MP_SPREE_LP")
  -- CH("BURAKKII"):SetManpu("MP_SPREE_LP")
  -- CH("EEFI"):SetManpu("MP_SPREE_LP")
  -- CAMERA:MoveFollow2(SymCam("CAMERA_03"), Speed(3.25, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- WINDOW:Talk(SymAct(""), 139229782)
  -- CH("PARTNER"):ResetManpu()
  -- CH("NOKOTCHI"):ResetManpu()
  -- CH("BURAKKII"):ResetManpu()
  -- CH("EEFI"):ResetManpu()
  -- WINDOW:CloseMessage()
  -- CAMERA:WaitMove()
  -- SOUND:FadeOutBgm(TimeSec(3))
  -- SCREEN_A:FadeOut(TimeSec(1.5), true)
  -- SOUND:WaitBgm()
  -- TASK:Sleep(TimeSec(0.5))
  -- CAMERA:ResetAzimuthDifferenceVolume()
  SYSTEM:UpdateNextDayParameter()
  FLAG.SceneFlag = CONST.FL_SC_01_FIRST
  FLAG.SCENARIOFLAG = CONST.M10_CHIMYAKUKANDOUCLEAR1ST_END
  FLAG.MapFlags = CONST.MAP_EVENT
  FLAG.FreePlay = CONST.FLAG_TRUE
  FLAG.TrigNextEvent = CONST.FLAG_FALSE
  SYSTEM:NextEntry()
end
function main10_chimyakukandouclear1st06_end()
end
function groundEnd()
end

