dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main17_grepalacewestbosswin01_init()
end
function main17_grepalacewestbosswin01_start()
  SYSTEM:UpdateNextDayParameter()
  subEveFromProgFadeSet()
  CHARA:SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  CH("MUNNA"):SetMotion(SymMot("EV013_FALL"), LOOP.ON, TimeSec(0))
  CH("DOKUROGGU"):SetMotion(SymMot("EV013_FALL"), LOOP.ON, TimeSec(0))
  CH("SHANDERA_1"):SetMotion(SymMot("EV013_FALL"), LOOP.ON, TimeSec(0))
  CH("GIGAIASU_1"):SetMotion(SymMot("EV013_FALL"), LOOP.ON, TimeSec(0))
  TASK:Sleep(TimeSec(0.1))
  CH("GIGAIASU_2"):SetMotion(SymMot("EV013_FALL"), LOOP.ON, TimeSec(0))
  CH("GIGAIASU_3"):SetMotion(SymMot("EV013_FALL"), LOOP.ON, TimeSec(0))
  TASK:Sleep(TimeSec(0.2))
  CH("GIGAIASU_4"):SetMotion(SymMot("EV013_FALL"), LOOP.ON, TimeSec(0))
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CAMERA:MoveFollow2(SymCam("CAMERA_06_5"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SOUND:PlaySe(SymSnd("SE_EVT_EARTHQUAKE_M_LP"), Volume(32))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CAMERA:WaitMove()
  CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CH("MUNNA"):SetShake(Vector(0.005, 0, 0), TimeSec(0.1, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.5))
  CH("MUNNA"):ResetShake()
  WINDOW:Talk(SymAct("MUNNA"), 1619050319)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_00_1"))
  CAMERA:SetTgt(SymCam("CAMERA_00_1"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 88, SymAct("DOKUROGGU"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("DOKUROGGU"), 2040237582)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 20, SymAct("GIGAIASU_1"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("GIGAIASU_1"), 1387716045)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:MoveFollow(SymCam("CAMERA_01_1"), Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  TASK:Sleep(TimeSec(0.3))
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  subEveDoubleJump(CH("PARTNER"))
  WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 1269689484, PARTNER_1 = 82606667})
  WINDOW:SwitchTalk({PARTNER_0 = 502745866, PARTNER_1 = 920262857})
  WINDOW:CloseMessage()
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_GREPALACE_COLLAPSE_01"), Volume(128))
  CAMERA:SetShake(Vector2(0.005, 0.01), TimeSec(1, TIME_TYPE.FRAME))
  CH("BIRIJION"):SetManpu("MP_NOTICE_L")
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):SetManpu("MP_NOTICE_L")
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):SetManpu("MP_NOTICE_L")
  CH("EMONGA"):SetManpu("MP_NOTICE_L")
  CH("EMONGA"):WaitManpu()
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  TASK:Sleep(TimeSec(0.3))
  CH("EMONGA"):DirTo(RotateTarget(45), Speed(350), ROT_TYPE.NEAR)
  CH("EMONGA"):WaitRotate()
  TASK:Sleep(TimeSec(0.2))
  CH("EMONGA"):DirTo(RotateTarget(-45), Speed(350), ROT_TYPE.NEAR)
  CH("EMONGA"):WaitRotate()
  TASK:Sleep(TimeSec(0.2))
  CH("EMONGA"):DirTo(CH("BIRIJION"), Speed(350), ROT_TYPE.RIGHT)
  CH("EMONGA"):WaitRotate()
  subEveJump(CH("EMONGA"))
  WINDOW:DrawFace(324, 88, SymAct("EMONGA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("EMONGA"), 801188232)
  WINDOW:CloseMessage()
  CH("BIRIJION"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("BIRIJION"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):DirTo(CH("BIRIJION"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(20, 20, SymAct("BIRIJION"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("BIRIJION"), -1470548665)
  WINDOW:Talk(SymAct("BIRIJION"), -1321073658)
  WINDOW:Talk(SymAct("BIRIJION"), 169664062)
  WINDOW:CloseMessage()
  SOUND:PlayEnv(SymSnd("SE_EVT_KUZURERU_FAR_LP"), Volume(256))
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("BIRIJION"):DirTo(RotateTarget(135), Speed(350), ROT_TYPE.NEAR)
  CH("BIRIJION"):WaitRotate()
  local taskLookAt01 = function()
    TASK:Sleep(TimeSec(0.4))
    CH("PARTNER"):DirTo(RotateTarget(135), Speed(350), ROT_TYPE.LEFT)
    CH("HERO"):DirTo(RotateTarget(135), Speed(350), ROT_TYPE.LEFT)
    TASK:Sleep(TimeSec(0.2))
    CH("EMONGA"):DirTo(RotateTarget(135), Speed(350), ROT_TYPE.RIGHT)
    CH("EMONGA"):WaitRotate()
  end
  TASK:Regist(taskLookAt01)
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("BIRIJION"), 319287167)
  WINDOW:CloseMessage()
  subEveDoubleJump(CH("PARTNER"))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = 942324924, PARTNER_1 = 556895741})
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:Talk(SymAct("MUNNA"), 1852840762)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_01_1"))
  CAMERA:SetTgt(SymCam("CAMERA_01_1"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("BIRIJION"):SetManpu("MP_EXCLAMATION")
  CH("EMONGA"):SetManpu("MP_EXCLAMATION")
  CH("EMONGA"):WaitManpu()
  CH("HERO"):DirTo(CH("MUNNA"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):DirTo(CH("MUNNA"), Speed(350), ROT_TYPE.NEAR)
  CH("BIRIJION"):DirTo(CH("MUNNA"), Speed(350), ROT_TYPE.NEAR)
  CH("EMONGA"):DirTo(CH("MUNNA"), Speed(350), ROT_TYPE.NEAR)
  CH("EMONGA"):WaitRotate()
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CH("MUNNA"):SetMotion(SymMot("EV013_DOWN01"), LOOP.OFF)
  CH("MUNNA"):WaitPlayMotion()
  CH("MUNNA"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("MUNNA"):SetFacialMotion(FACIAL_MOTION.ANGRY)
  SOUND:FadeOutSe(SymSnd("SE_EVT_EARTHQUAKE_M_LP"), TimeSec(1.5))
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_DESPAIR_HV1"), Volume(256))
  WINDOW:Talk(SymAct("MUNNA"), 2003511931)
  WINDOW:Talk(SymAct("MUNNA"), 1548122552)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow(SymCam("CAMERA_07_5"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("MUNNA"):WalkTo(SymPos("P01_MUNNA"), Speed(1))
  CH("MUNNA"):WaitMove()
  CAMERA:WaitMove()
  WINDOW:Talk(SymAct("MUNNA"), 1163741433)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_04_1"))
  CAMERA:SetTgt(SymCam("CAMERA_04_1"))
  local StandUpDokuroggu = function()
    CH("DOKUROGGU"):SetMotion(SymMot("EV017_STAND"), LOOP.OFF)
    CH("DOKUROGGU"):WaitPlayMotion()
    CH("DOKUROGGU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
  local StandUpShandera = function()
    CH("SHANDERA_1"):SetMotion(SymMot("EV017_STAND"), LOOP.OFF)
    CH("SHANDERA_1"):WaitPlayMotion()
    CH("SHANDERA_1"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
  local StandUpGigaiasu1 = function()
    CH("GIGAIASU_1"):SetMotion(SymMot("EV017_STAND"), LOOP.OFF)
    CH("GIGAIASU_1"):WaitPlayMotion()
    CH("GIGAIASU_1"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
  local StandUpGigaiasu2 = function()
    CH("GIGAIASU_2"):SetMotion(SymMot("EV017_STAND"), LOOP.OFF)
    CH("GIGAIASU_2"):WaitPlayMotion()
    CH("GIGAIASU_2"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
  local StandUpGigaiasu3 = function()
    CH("GIGAIASU_3"):SetMotion(SymMot("EV017_STAND"), LOOP.OFF)
    CH("GIGAIASU_3"):WaitPlayMotion()
    CH("GIGAIASU_3"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
  local StandUpGigaiasu4 = function()
    CH("GIGAIASU_4"):SetMotion(SymMot("EV017_STAND"), LOOP.OFF)
    CH("GIGAIASU_4"):WaitPlayMotion()
    CH("GIGAIASU_4"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
  TASK:Regist(Group("Dokuroggu"), StandUpDokuroggu)
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(Group("Shandera"), StandUpShandera)
  TASK:Regist(Group("Gigaiasu1"), StandUpGigaiasu1)
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(Group("Gigaiasu2"), StandUpGigaiasu2)
  TASK:Regist(Group("Gigaiasu3"), StandUpGigaiasu3)
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(Group("Gigaiasu4"), StandUpGigaiasu4)
  TASK:WaitTask()
  SOUND:PlaySe(SymSnd("SE_EVT_GREPALACE_COLLAPSE_01"), Volume(128))
  CAMERA:SetShake(Vector2(0.01, 0.01), TimeSec(1, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.8))
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  TASK:Sleep(TimeSec(0.3))
  CAMERA:SetAzimuthDifferenceVolume(Volume(2.5))
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:Monologue(-1027255242)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CH("PARTNER"):RunTo(SymPos("P02_PARTNER"), Speed(2))
  CH("PARTNER"):WaitMove()
  WINDOW:DrawFace(20, 20, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -606182025, PARTNER_1 = 413757904})
  WINDOW:SwitchTalk({PARTNER_0 = 28459153, PARTNER_1 = 715068242})
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("MUNNA"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("MUNNA"), 864297491)
  WINDOW:Talk(SymAct("MUNNA"), 2093331668)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_10"))
  CAMERA:SetTgt(SymCam("CAMERA_10"))
  TASK:Sleep(TimeSec(0.3))
  CH("DOKUROGGU"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
  WINDOW:DrawFace(226, 8, SymAct("DOKUROGGU"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("DOKUROGGU"), 1709082005)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 20, SymAct("GIGAIASU_1"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("GIGAIASU_1"), 1324602966)
  WINDOW:CloseMessage()
  CH("DOKUROGGU"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(324, 88, SymAct("MUNNA"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("MUNNA"), 1474881303)
  WINDOW:Talk(SymAct("MUNNA"), -797901864)
  WINDOW:Talk(SymAct("MUNNA"), -915682663)
  WINDOW:Talk(SymAct("MUNNA"), -1609230667)
  WINDOW:Talk(SymAct("MUNNA"), -1190254604)
  WINDOW:Talk(SymAct("MUNNA"), -1843170249)
  WINDOW:Talk(SymAct("MUNNA"), -1959246474)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_07_6"))
  CAMERA:SetTgt(SymCam("CAMERA_07_6"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:Talk(SymAct("MUNNA"), -998648911)
  WINDOW:Talk(SymAct("MUNNA"), -580721936)
  WINDOW:Talk(SymAct("MUNNA"), -162549453)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_GREPALACE_COLLAPSE_02"), Volume(128))
  CAMERA:SetShake(Vector2(0.005, 0.01), TimeSec(1, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.8))
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 20, SymAct("PARTNER"), FACE_TYPE.SAD)
  WINDOW:SwitchTalk({PARTNER_0 = -279674766, PARTNER_1 = 1758239933})
  WINDOW:SwitchTalk({PARTNER_0 = 1909960188, PARTNER_1 = 1036135948})
  WINDOW:SwitchTalk({PARTNER_0 = 618209101, PARTNER_1 = 267668622})
  WINDOW:SwitchTalk({PARTNER_0 = 384794063, PARTNER_1 = 1504635656})
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_07_6"))
  CAMERA:SetTgt(SymCam("CAMERA_07_6"))
  CH("MUNNA"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("MUNNA"):SetManpu("MP_SHOCK_L")
  CH("MUNNA"):WaitManpu()
  WINDOW:Talk(SymAct("MUNNA"), 1085659721)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  subEveDoubleJump(CH("PARTNER"))
  WINDOW:DrawFace(20, 20, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = 1805158794, PARTNER_1 = 1921235147})
  WINDOW:SwitchTalk({PARTNER_0 = -182737916, PARTNER_1 = -335506107})
  WINDOW:SwitchTalk({PARTNER_0 = -2055321239, PARTNER_1 = -1671071704})
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_07_6"))
  CAMERA:SetTgt(SymCam("CAMERA_07_6"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("MUNNA"):SetManpu("MP_FLY_SWEAT")
  CH("MUNNA"):WaitManpu()
  CH("MUNNA"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
  WINDOW:Talk(SymAct("MUNNA"), -1220006933)
  WINDOW:Talk(SymAct("MUNNA"), -1370285398)
  WINDOW:Talk(SymAct("MUNNA"), -518878099)
  WINDOW:KeyWait()
  CH("MUNNA"):SetFacialMotion(FACIAL_MOTION.TEARS)
  WINDOW:Talk(SymAct("MUNNA"), -133579476)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_10"))
  CAMERA:SetTgt(SymCam("CAMERA_10"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(226, 8, SymAct("DOKUROGGU"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("DOKUROGGU"), -752554257)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_07_6"))
  CAMERA:SetTgt(SymCam("CAMERA_07_6"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:Talk(SymAct("MUNNA"), -901783634)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_00_2"))
  CAMERA:SetTgt(SymCam("CAMERA_00_2"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(324, 88, SymAct("SHANDERA_1"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("SHANDERA_1"), 1302840161)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_07_6"))
  CAMERA:SetTgt(SymCam("CAMERA_07_6"))
  SOUND:FadeOutBgm(TimeSec(3.5))
  SOUND:FadeOutEnv(TimeSec(1))
  CH("MUNNA"):SetShake(Vector(0.005, 0, 0), TimeSec(0.1, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.5))
  CH("MUNNA"):ResetShake()
  CH("MUNNA"):SetFacialMotion(FACIAL_MOTION.SHOUT)
  WINDOW:Talk(SymAct("MUNNA"), 1421668896)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_10"))
  CAMERA:SetTgt(SymCam("CAMERA_10"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(324, 20, SymAct("GIGAIASU_1"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("GIGAIASU_1"), -1748244857)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_04_1"))
  CAMERA:SetTgt(SymCam("CAMERA_04_1"))
  TASK:Sleep(TimeSec(0.3))
  CH("MUNNA"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  CH("MUNNA"):WaitRotate()
  subEveDoubleJump(CH("MUNNA"))
  WINDOW:DrawFace(20, 88, SymAct("MUNNA"), FACE_TYPE.SHOUT)
  WINDOW:Talk(SymAct("MUNNA"), -1898915898)
  WINDOW:CloseMessage()
  local taskJump = function(chara)
    chara:MoveHeightTo(Height(0.1), Speed(1.5))
    chara:WaitMoveHeight()
    chara:MoveHeightTo(Height(0), Speed(1.5))
    chara:WaitMoveHeight()
  end
  TASK:Regist(taskJump, {
    CH("DOKUROGGU")
  })
  TASK:Regist(taskJump, {
    CH("SHANDERA_1")
  })
  TASK:Sleep(TimeSec(0.1))
  TASK:Regist(taskJump, {
    CH("GIGAIASU_2")
  })
  TASK:Regist(taskJump, {
    CH("GIGAIASU_3")
  })
  TASK:Sleep(TimeSec(0.1))
  TASK:Regist(taskJump, {
    CH("GIGAIASU_1")
  })
  TASK:Regist(taskJump, {
    CH("GIGAIASU_4")
  })
  WINDOW:Talk(SymWord(-181286456), -1510112251)
  WINDOW:CloseMessage()
  CH("MUNNA"):DirTo(RotateTarget(180), Speed(500), ROT_TYPE.LEFT)
  CH("MUNNA"):WaitRotate()
  CAMERA:MoveFollow(SymCam("CAMERA_05"), Speed(4, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("MUNNA"):RunTo(SymPos("POINT_ENEMY_MOVE"), Speed(0.8))
  CH("DOKUROGGU"):RunTo(SymPos("POINT_ENEMY_MOVE"), Speed(1.5))
  CH("SHANDERA_1"):RunTo(SymPos("POINT_ENEMY_MOVE"), Speed(1.5))
  CH("GIGAIASU_1"):RunTo(SymPos("POINT_ENEMY_MOVE"), Speed(1.5))
  CH("GIGAIASU_2"):RunTo(SymPos("POINT_ENEMY_MOVE"), Speed(1.5))
  CH("GIGAIASU_3"):RunTo(SymPos("POINT_ENEMY_MOVE"), Speed(1.5))
  CH("GIGAIASU_4"):RunTo(SymPos("POINT_ENEMY_MOVE"), Speed(1.5))
  TASK:Sleep(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_MAGNAGATE_OPNE_B"), Volume(256))
  SCREEN_A:WhiteOut(TimeSec(0.1), true)
  TASK:Sleep(TimeSec(1))
  WINDOW:NarrationB(TimeSec(0), TimeSec(0), -1125731004)
  TASK:Sleep(TimeSec(1))
  WINDOW:ForceCloseMessage()
  FLAG.SceneFlag = CONST.FL_SC_01_END
  FLAG.SCENARIOFLAG = CONST.M17_GREPALACEWESTBOSSWIN_START
  SYSTEM:NextEntry()
end
function main17_grepalacewestbosswin01_end()
end
function main17_grepalacewestbosswin02_init()
end
function main17_grepalacewestbosswin02_start()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  GM("PILLAR_SHADOW"):SetVisible(false)
  CHARA:SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  MAP:ChangeLightColor(Color(0.2, 0.2, 0.2, 1), TimeSec(0))
  EFFECT:Create("effectGatebaseOkLp", SymEff("EV_GATEBASE_OK_LP"))
  EFFECT:SetPosition("effectGatebaseOkLp", SymPos("P_EFF_EV_GATEBASE_START"))
  EFFECT:Play("effectGatebaseOkLp")
  SOUND:PlayBgm(SymSnd("BGM_EVE_MAGNAGATE"), Volume(256))
  SOUND:PlaySe(SymSnd("SE_EVT_MAGNAGATE_LP"), Volume(64))
  SCREEN_A:WhiteIn(TimeSec(0.5), true)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("EMONGA"):SetManpu("MP_SHOCK_L")
  CH("BIRIJION"):SetManpu("MP_EXCLAMATION")
  CH("MUNNA"):SetManpu("MP_SHOCK_R")
  CH("DOKUROGGU"):SetManpu("MP_SHOCK_R")
  CH("SHANDERA_1"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_SHOCK_L")
  CH("GIGAIASU_1"):SetManpu("MP_EXCLAMATION")
  CH("GIGAIASU_2"):SetManpu("MP_EXCLAMATION")
  CH("GIGAIASU_3"):SetManpu("MP_SHOCK_R")
  CH("GIGAIASU_4"):SetManpu("MP_SHOCK_R")
  CH("GIGAIASU_4"):WaitManpu()
  CH("HERO"):WalkTo(SymPos("P01_HERO"), Speed(1.5), LINK_DIR.OFF)
  CH("PARTNER"):WalkTo(SymPos("P01_PARTNER"), Speed(1.5), LINK_DIR.OFF)
  CH("EMONGA"):WalkTo(SymPos("P01_EMONGA"), Speed(1.5), LINK_DIR.OFF)
  CH("BIRIJION"):WalkTo(SymPos("P01_BIRIJION"), Speed(1.5), LINK_DIR.OFF)
  CH("MUNNA"):WalkTo(SymPos("P01_MUNNA"), Speed(1.5), LINK_DIR.OFF)
  CH("DOKUROGGU"):WalkTo(SymPos("P01_DOKUROGGU"), Speed(1.5), LINK_DIR.OFF)
  CH("SHANDERA_1"):WalkTo(SymPos("P01_SHANDERA_1"), Speed(1.5), LINK_DIR.OFF)
  TASK:Sleep(TimeSec(0.1))
  CH("GIGAIASU_1"):WalkTo(SymPos("P01_GIGAIASU_1"), Speed(1.5), LINK_DIR.OFF)
  CH("GIGAIASU_2"):WalkTo(SymPos("P01_GIGAIASU_2"), Speed(1.5), LINK_DIR.OFF)
  CH("GIGAIASU_3"):WalkTo(SymPos("P01_GIGAIASU_3"), Speed(1.5), LINK_DIR.OFF)
  CH("GIGAIASU_4"):WalkTo(SymPos("P01_GIGAIASU_4"), Speed(1.5), LINK_DIR.OFF)
  CH("GIGAIASU_4"):WaitMove()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:MoveFollow2(SymCam("CAMERA_01_1"), Speed(2.5, ACCEL_TYPE.HIGH, DECEL_TYPE.HIGH))
  CH("EMONGA"):DirTo(RotateTarget(-45), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):DirTo(CH("KERUDYIO"), Speed(350), ROT_TYPE.NEAR)
  CH("BIRIJION"):DirTo(RotateTarget(45), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):DirTo(CH("KERUDYIO"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.3))
  CAMERA:WaitMove()
  subEveDoubleJump(CH("EMONGA"))
  WINDOW:DrawFace(324, 20, SymAct("EMONGA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("EMONGA"), -207150205)
  WINDOW:CloseMessage()
  CH("EEFI"):DirTo(RotateTarget(45), Speed(500), ROT_TYPE.NEAR)
  CH("EEFI"):WaitRotate()
  TASK:Sleep(TimeSec(0.2))
  CH("EEFI"):DirTo(RotateTarget(-45), Speed(500), ROT_TYPE.NEAR)
  CH("EEFI"):WaitRotate()
  TASK:Sleep(TimeSec(0.2))
  CH("EEFI"):DirTo(RotateTarget(0), Speed(500), ROT_TYPE.NEAR)
  CH("EEFI"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("EEFI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EEFI"), -356773182)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(1.5))
  CAMERA:SetEye(SymCam("CAMERA_11"))
  CAMERA:SetTgt(SymCam("CAMERA_11"))
  TASK:Sleep(TimeSec(0.3))
  CH("BIRIJION"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("BIRIJION"):SetManpu("MP_SHOCK_R")
  CH("BIRIJION"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("BIRIJION"), -1047445247)
  WINDOW:CloseMessage()
  CH("BIRIJION"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("MUNNA"):SetManpu("MP_SHOCK_R")
  CH("MUNNA"):WaitManpu()
  CH("MUNNA"):WalkTo(SymPos("P02_MUNNA"), Speed(1.5))
  CH("MUNNA"):WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("MUNNA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("MUNNA"), -662015936)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("EMONGA"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_02_1"))
  CAMERA:SetTgt(SymCam("CAMERA_02_1"))
  subEveDoubleJump(CH("PARTNER"))
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 1595042959, PARTNER_1 = 1175018958})
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  EFFECT:Create("effectGatebaseOkEnd", SymEff("EV_GATEBASE_OK_END"))
  EFFECT:SetPosition("effectGatebaseOkEnd", SymPos("P_EFF_EV_GATEBASE_START"))
  SOUND:FadeOutSe(SymSnd("SE_EVT_MAGNAGATE_LP"), TimeSec(1))
  SOUND:PlaySe(SymSnd("SE_EVT_MAGNACIRCLE_BANISH"), Volume(256))
  TASK:Sleep(TimeSec(5, TIME_TYPE.FRAME))
  GM("MAGNAGATE_CIRCLE1"):SetMotion(SymMot("VANISH"), LOOP.OFF)
  GM("MAGNAGATE_CIRCLE2"):SetMotion(SymMot("VANISH"), LOOP.OFF)
  GM("MAGNAGATE_CIRCLE3"):SetMotion(SymMot("VANISH"), LOOP.OFF)
  GM("MAGNAGATE_TUBE"):SetVisible(false)
  GM("MAGNAGATE_CIRCLE3"):WaitPlayMotion()
  GM("MAGNAGATE_CIRCLE1"):SetVisible(false)
  GM("MAGNAGATE_CIRCLE2"):SetVisible(false)
  GM("MAGNAGATE_CIRCLE3"):SetVisible(false)
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_MAGNAGATE_CLOSE"), Volume(256))
  TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.2))
  CAMERA:SetShake(Vector2(0.04, 0.04), TimeSec(1, TIME_TYPE.FRAME))
  EFFECT:Remove("effectGatebaseOkLp")
  EFFECT:Play("effectGatebaseOkEnd")
  TASK:Sleep(TimeSec(20, TIME_TYPE.FRAME))
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
  MAP:ReturnLightColor(TimeSec(20, TIME_TYPE.FRAME))
  GM("MAGNAGATE"):SetMotion(SymMot("VANISH"), LOOP.OFF)
  TASK:Sleep(TimeSec(5, TIME_TYPE.FRAME))
  CAMERA:SetShake(Vector2(0.01, 0.01), TimeSec(0.5, TIME_TYPE.FRAME))
  GM("MAGNAGATE"):WaitPlayMotion()
  GM("MAGNAGATE"):SetVisible(false)
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  TASK:Sleep(TimeSec(1))
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 88, SymAct("MUNNA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("MUNNA"), 796361186)
  WINDOW:CloseMessage()
  CH("MUNNA"):DirTo(CH("BURAKKII"), Speed(350), ROT_TYPE.NEAR)
  CH("MUNNA"):WaitRotate()
  TASK:Sleep(TimeSec(0.2))
  CH("MUNNA"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  CH("MUNNA"):WaitRotate()
  TASK:Sleep(TimeSec(0.2))
  CH("MUNNA"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  CH("MUNNA"):WaitRotate()
  subEveJump(CH("MUNNA"))
  WINDOW:DrawFace(20, 88, SymAct("MUNNA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("MUNNA"), 913092771)
  WINDOW:CloseMessage()
  CH("KERUDYIO"):RunTo(SymPos("P01_KERUDYIO"), Speed(1.5))
  TASK:Sleep(TimeSec(0.1))
  local taskStepBack = function()
    CH("EEFI"):SetMotionRaito(Raito(2))
    CH("BURAKKII"):SetMotionRaito(Raito(2))
    CH("EEFI"):WalkTo(SymPos("P01_EEFI"), Speed(1.5), LINK_DIR.OFF)
    TASK:Sleep(TimeSec(0.1))
    CH("BURAKKII"):WalkTo(SymPos("P01_BURAKKII"), Speed(1.5), LINK_DIR.OFF)
    CH("EEFI"):WaitMove()
    CH("EEFI"):SetMotionRaito(Raito(1))
    CH("BURAKKII"):WaitMove()
    CH("BURAKKII"):SetMotionRaito(Raito(1))
  end
  TASK:Regist(taskStepBack)
  CH("HERO"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  CH("EMONGA"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  CH("BIRIJION"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  CH("KERUDYIO"):WaitMove()
  WINDOW:DrawFace(324, 20, SymAct("KERUDYIO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KERUDYIO"), 490857312)
  WINDOW:DrawFace(324, 20, SymAct("KERUDYIO"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("KERUDYIO"), 73060897)
  WINDOW:Talk(SymAct("KERUDYIO"), 1260078310)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("MUNNA"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("MUNNA"), 1375761831)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CH("PARTNER"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  subEveDoubleJump(CH("PARTNER"))
  local taskLookAt02 = function()
    TASK:Sleep(TimeSec(0.4))
    CH("BIRIJION"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("EMONGA"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt02)
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 2033002084, PARTNER_1 = 1614157605})
  WINDOW:CloseMessage()
  CH("EEFI"):SetNeckRot(RotateTarget(-30), RotateTarget(0), RotateTarget(0), TimeSec(0.2))
  CH("EEFI"):WaitNeckRot()
  WINDOW:DrawFace(324, 88, SymAct("EEFI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EEFI"), -408024086)
  WINDOW:Talk(SymAct("EEFI"), -21677397)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  TASK:Sleep(TimeSec(0.3))
  CH("PARTNER"):DirTo(CH("MUNNA"), Speed(350), ROT_TYPE.NEAR)
  CH("BIRIJION"):DirTo(CH("MUNNA"), Speed(200), ROT_TYPE.NEAR)
  CH("EMONGA"):DirTo(CH("MUNNA"), Speed(200), ROT_TYPE.NEAR)
  CH("MUNNA"):SetFacialMotion(FACIAL_MOTION.ANGRY)
  WINDOW:DrawFace(324, 88, SymAct("MUNNA"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("MUNNA"), 1997836724)
  CH("EEFI"):ResetNeckRot(TimeSec(0.2))
  CH("EEFI"):WaitNeckRot()
  WINDOW:Talk(SymAct("MUNNA"), 1846518005)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("HERO"):SetManpu("MP_SHOCK_R")
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("EMONGA"):SetManpu("MP_SHOCK_L")
  CH("BIRIJION"):SetManpu("MP_SHOCK_R")
  CH("BURAKKII"):SetManpu("MP_EXCLAMATION")
  CH("EEFI"):SetManpu("MP_SHOCK_R")
  CH("EEFI"):WaitManpu()
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 1159918390, PARTNER_1 = 1547289207})
  WINDOW:CloseMessage()
  SOUND:FadeInEnv(SymSnd("SE_EVT_EARTHQUAKE_M_LP"), TimeSec(1.5), Volume(32))
  SOUND:FadeOutBgm(TimeSec(2.5))
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(324, 88, SymAct("MUNNA"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("MUNNA"), 326653104)
  WINDOW:Talk(SymAct("MUNNA"), 174286321)
  WINDOW:Talk(SymAct("MUNNA"), 558773810)
  WINDOW:Talk(SymAct("MUNNA"), 945096563)
  WINDOW:Talk(SymAct("MUNNA"), -1077077060)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetEye(SymCam("CAMERA_12"))
  CAMERA:SetTgt(SymCam("CAMERA_12"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 88, SymAct("KERUDYIO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KERUDYIO"), -1495913731)
  WINDOW:Talk(SymAct("KERUDYIO"), -811010351)
  WINDOW:Talk(SymAct("KERUDYIO"), -692861040)
  WINDOW:Talk(SymAct("KERUDYIO"), -39938989)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_GREPALACE_COLLAPSE_01"), Volume(128))
  CAMERA:SetShake(Vector2(0.005, 0.01), TimeSec(1, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.8))
  CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  TASK:Sleep(TimeSec(0.3))
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  WINDOW:DrawFace(20, 88, SymAct("KERUDYIO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KERUDYIO"), -461003502)
  WINDOW:Talk(SymAct("KERUDYIO"), -1413205035)
  WINDOW:Talk(SymAct("KERUDYIO"), -1294007660)
  WINDOW:Talk(SymAct("KERUDYIO"), -1712172713)
  WINDOW:Talk(SymAct("KERUDYIO"), -2132189162)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_KUZURERU_FAR_LP"), Volume(256))
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  subEveJump(CH("MUNNA"))
  WINDOW:DrawFace(324, 88, SymAct("MUNNA"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("MUNNA"), 124878041)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_GREPALACE_COLLAPSE_01"), Volume(128))
  CAMERA:SetShake(Vector2(0.005, 0.01), TimeSec(1, TIME_TYPE.FRAME))
  CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetEye(SymCam("CAMERA_12"))
  CAMERA:SetTgt(SymCam("CAMERA_12"))
  TASK:Sleep(TimeSec(0.3))
  TASK:Sleep(TimeSec(0.3))
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  WINDOW:DrawFace(20, 88, SymAct("KERUDYIO"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("KERUDYIO"), 510283160)
  WINDOW:Talk(SymAct("KERUDYIO"), -1104033090)
  WINDOW:CloseMessage()
  SOUND:FadeOutEnv(TimeSec(1.5))
  CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetEye(SymCam("CAMERA_04_1"))
  CAMERA:SetTgt(SymCam("CAMERA_04_1"))
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_DESPAIR_L3"), Volume(256))
  CH("MUNNA"):SetFacialMotion(FACIAL_MOTION.SHOUT)
  subEveDoubleJump(CH("MUNNA"))
  WINDOW:Talk(SymAct("MUNNA"), -1490355201)
  WINDOW:KeyWait()
  CH("MUNNA"):SetFacialMotion(FACIAL_MOTION.ANGRY)
  WINDOW:Talk(SymAct("MUNNA"), -1945655236)
  WINDOW:KeyWait()
  CH("MUNNA"):SetFacialMotion(FACIAL_MOTION.SHOUT)
  TASK:Regist(subEveDoubleJump, {
    CH("MUNNA")
  })
  WINDOW:Talk(SymAct("MUNNA"), -1793287811)
  WINDOW:Talk(SymAct("MUNNA"), -631435334)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_GREPALACE_COLLAPSE_01"), Volume(128))
  CAMERA:SetShake(Vector2(0.008, 0.01), TimeSec(1, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.3))
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_04_2"))
  CAMERA:SetTgt(SymCam("CAMERA_04_2"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(324, 20, SymAct("SHANDERA_1"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("SHANDERA_1"), -1018806533)
  TASK:Sleep(TimeSec(0.3))
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_04_3"))
  CAMERA:SetTgt(SymCam("CAMERA_04_3"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 88, SymAct("GIGAIASU_1"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("GIGAIASU_1"), -395612872)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetEye(SymCam("CAMERA_04_1"))
  CAMERA:SetTgt(SymCam("CAMERA_04_1"))
  TASK:Sleep(TimeSec(0.3))
  TASK:Regist(subEveDoubleJump, {
    CH("MUNNA")
  })
  WINDOW:Talk(SymAct("MUNNA"), -244294535)
  WINDOW:Talk(SymAct("MUNNA"), 1994932406)
  WINDOW:CloseMessage()
  CH("MUNNA"):ResetManpu()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  subEveJump(CH("PARTNER"))
  WINDOW:DrawFace(20, 20, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = 1878225399, PARTNER_1 = 109948379})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_GREPALACE_COLLAPSE_03"), Volume(128))
  CAMERA:SetShake(Vector2(0.008, 0.01), TimeSec(1, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.3))
  CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetEye(SymCam("CAMERA_04_1"))
  CAMERA:SetTgt(SymCam("CAMERA_04_1"))
  TASK:Sleep(TimeSec(0.3))
  CH("MUNNA"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("MUNNA"):SetManpu("MP_EXCLAMATION")
  CH("MUNNA"):WaitManpu()
  TASK:Sleep(TimeSec(1))
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_02_1"))
  CAMERA:SetTgt(SymCam("CAMERA_02_1"))
  TASK:Sleep(TimeSec(0.3))
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  subEveDoubleJump(CH("PARTNER"))
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = 529964186, PARTNER_1 = 884723545})
  WINDOW:SwitchTalk({PARTNER_0 = 765525528, PARTNER_1 = 1658939615})
  WINDOW:SwitchTalk({PARTNER_0 = 2080004510, PARTNER_1 = 1356270173})
  WINDOW:SwitchTalk({PARTNER_0 = 1238121244, PARTNER_1 = -833345581})
  WINDOW:KeyWait()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.TEARS)
  WINDOW:SwitchTalk({PARTNER_0 = -682682734, PARTNER_1 = 339214901})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_GREPALACE_COLLAPSE_01"), Volume(128))
  CAMERA:SetShake(Vector2(0.008, 0.01), TimeSec(1, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.3))
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_04_4"))
  CAMERA:SetTgt(SymCam("CAMERA_04_4"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(226, 8, SymAct("DOKUROGGU"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("DOKUROGGU"), 220410740)
  TASK:Sleep(TimeSec(0.3))
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(2.5))
  CAMERA:SetEye(SymCam("CAMERA_02_2"))
  CAMERA:SetTgt(SymCam("CAMERA_02_2"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(324, 88, SymAct("EMONGA"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("EMONGA"), 638476471)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_04_2"))
  CAMERA:SetTgt(SymCam("CAMERA_04_2"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(324, 20, SymAct("SHANDERA_1"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("SHANDERA_1"), 1058361846)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_02_3"))
  CAMERA:SetTgt(SymCam("CAMERA_02_3"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("BIRIJION"), 1884604209)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_04_3"))
  CAMERA:SetTgt(SymCam("CAMERA_04_3"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 88, SymAct("GIGAIASU_1"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("GIGAIASU_1"), 1766848112)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_02_1"))
  CAMERA:SetTgt(SymCam("CAMERA_02_1"))
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = 1113761203, PARTNER_1 = 1534694642})
  WINDOW:SwitchTalk({PARTNER_0 = -589199299, PARTNER_1 = -973424260})
  WINDOW:SwitchTalk({PARTNER_0 = -1400609456, PARTNER_1 = -1247849455})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_GREPALACE_COLLAPSE_01"), Volume(128))
  CAMERA:SetShake(Vector2(0.011, 0.01), TimeSec(1, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.3))
  CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetEye(SymCam("CAMERA_04_1"))
  CAMERA:SetTgt(SymCam("CAMERA_04_1"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("MUNNA"):SetManpu("MP_EXCLAMATION")
  CH("MUNNA"):WaitManpu()
  TASK:Sleep(TimeSec(0.3))
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  CH("MUNNA"):SetFacialMotion(FACIAL_MOTION.TEARS)
  WINDOW:Talk(SymAct("MUNNA"), -1632499758)
  WINDOW:Talk(SymAct("MUNNA"), -2018953581)
  WINDOW:Talk(SymAct("MUNNA"), -924278700)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(1.5))
  CAMERA:SetEye(SymCam("CAMERA_13"))
  CAMERA:SetTgt(SymCam("CAMERA_13"))
  CH("PARTNER"):SetDir(SymPos("P02_PARTNER"))
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  CAMERA:MoveFollow2(SymCam("CAMERA_13_5"), Speed(10, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SOUND:FadeOutBgm(TimeSec(1.5))
  SOUND:FadeOutSe(SymSnd("SE_EVT_KUZURERU_FAR_LP"), TimeSec(0.5))
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):WalkTo(SymPos("P02_PARTNER"), Speed(1.5))
  CH("PARTNER"):WaitMove()
  WINDOW:SwitchTalk({PARTNER_0 = -772566763, PARTNER_1 = -86064426})
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  TASK:Sleep(TimeSec(0.3))
  CAMERA:SetShake(Vector2(0.016, 0.01), TimeSec(1, TIME_TYPE.FRAME))
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  CH("MUNNA"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  SOUND:FadeInEnv(SymSnd("SE_EVT_EARTHQUAKE_L_LP"), TimeSec(0.5), Volume(256))
  TASK:Sleep(TimeSec(0.8))
  local taskHeroLookAround = function()
    CH("HERO"):DirTo(RotateTarget(-60), Speed(350), ROT_TYPE.NEAR)
    CH("HERO"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    CH("HERO"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.NEAR)
    CH("HERO"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    CH("HERO"):DirTo(RotateTarget(30), Speed(350), ROT_TYPE.NEAR)
    CH("HERO"):WaitRotate()
  end
  local taskPartnerLookAround = function()
    CH("PARTNER"):DirTo(RotateTarget(-40), Speed(350), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    CH("PARTNER"):DirTo(RotateTarget(60), Speed(350), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    CH("PARTNER"):DirTo(RotateTarget(-30), Speed(350), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
  end
  local taskKerudyioLookAround = function()
    CH("KERUDYIO"):DirTo(RotateTarget(-60), Speed(350), ROT_TYPE.NEAR)
    CH("KERUDYIO"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    CH("KERUDYIO"):DirTo(RotateTarget(60), Speed(350), ROT_TYPE.NEAR)
    CH("KERUDYIO"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    CH("KERUDYIO"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
    CH("KERUDYIO"):WaitRotate()
  end
  local taskBurakkiiLookAround = function()
    CH("BURAKKII"):DirTo(RotateTarget(50), Speed(350), ROT_TYPE.NEAR)
    CH("BURAKKII"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    CH("BURAKKII"):DirTo(RotateTarget(-40), Speed(350), ROT_TYPE.NEAR)
    CH("BURAKKII"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    CH("BURAKKII"):DirTo(RotateTarget(-70), Speed(350), ROT_TYPE.NEAR)
    CH("BURAKKII"):WaitRotate()
  end
  local taskEefiLookAround = function()
    CH("EEFI"):DirTo(RotateTarget(-30), Speed(350), ROT_TYPE.NEAR)
    CH("EEFI"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    CH("EEFI"):DirTo(RotateTarget(60), Speed(350), ROT_TYPE.NEAR)
    CH("EEFI"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    CH("EEFI"):DirTo(RotateTarget(-30), Speed(350), ROT_TYPE.NEAR)
    CH("EEFI"):WaitRotate()
  end
  local taskEmongaLookAround = function()
    CH("EMONGA"):WalkTo(SymPos("P10_EMONGA"), Speed(1.5))
    CH("EMONGA"):WaitMove()
    CH("EMONGA"):DirTo(RotateTarget(-30), Speed(350), ROT_TYPE.NEAR)
    CH("EMONGA"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    CH("EMONGA"):DirTo(RotateTarget(40), Speed(350), ROT_TYPE.NEAR)
    CH("EMONGA"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    CH("EMONGA"):DirTo(RotateTarget(-40), Speed(350), ROT_TYPE.NEAR)
    CH("EMONGA"):WaitRotate()
  end
  local taskBirijionLookAround = function()
    CH("BIRIJION"):DirTo(RotateTarget(60), Speed(350), ROT_TYPE.NEAR)
    CH("BIRIJION"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    CH("BIRIJION"):DirTo(RotateTarget(20), Speed(350), ROT_TYPE.NEAR)
    CH("BIRIJION"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    CH("BIRIJION"):DirTo(RotateTarget(-30), Speed(350), ROT_TYPE.NEAR)
    CH("BIRIJION"):WaitRotate()
  end
  local taskMunnaLookAround = function()
    CH("MUNNA"):DirTo(RotateTarget(-60), Speed(350), ROT_TYPE.NEAR)
    CH("MUNNA"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    CH("MUNNA"):DirTo(RotateTarget(60), Speed(350), ROT_TYPE.NEAR)
    CH("MUNNA"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    CH("MUNNA"):DirTo(RotateTarget(-30), Speed(350), ROT_TYPE.NEAR)
    CH("MUNNA"):WaitRotate()
  end
  local taskDokurogguLookAround = function()
    CH("DOKUROGGU"):DirTo(RotateTarget(-60), Speed(350), ROT_TYPE.NEAR)
    CH("DOKUROGGU"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    CH("DOKUROGGU"):DirTo(RotateTarget(60), Speed(350), ROT_TYPE.NEAR)
    CH("DOKUROGGU"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    CH("DOKUROGGU"):DirTo(RotateTarget(-30), Speed(350), ROT_TYPE.NEAR)
    CH("DOKUROGGU"):WaitRotate()
  end
  local taskShanderaLookAround = function()
    CH("SHANDERA_1"):DirTo(RotateTarget(-60), Speed(350), ROT_TYPE.NEAR)
    CH("SHANDERA_1"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    CH("SHANDERA_1"):DirTo(RotateTarget(60), Speed(350), ROT_TYPE.NEAR)
    CH("SHANDERA_1"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    CH("SHANDERA_1"):DirTo(RotateTarget(-30), Speed(350), ROT_TYPE.NEAR)
    CH("SHANDERA_1"):WaitRotate()
  end
  local taskGigaiasu1LookAround = function()
    CH("GIGAIASU_1"):DirTo(RotateTarget(-60), Speed(350), ROT_TYPE.NEAR)
    CH("GIGAIASU_1"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    CH("GIGAIASU_1"):DirTo(RotateTarget(60), Speed(350), ROT_TYPE.NEAR)
    CH("GIGAIASU_1"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    CH("GIGAIASU_1"):DirTo(RotateTarget(-30), Speed(350), ROT_TYPE.NEAR)
    CH("GIGAIASU_1"):WaitRotate()
  end
  local taskGigaiasu2LookAround = function()
    CH("GIGAIASU_2"):DirTo(RotateTarget(-40), Speed(350), ROT_TYPE.NEAR)
    CH("GIGAIASU_2"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    CH("GIGAIASU_2"):DirTo(RotateTarget(60), Speed(350), ROT_TYPE.NEAR)
    CH("GIGAIASU_2"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    CH("GIGAIASU_2"):DirTo(RotateTarget(-30), Speed(350), ROT_TYPE.NEAR)
    CH("GIGAIASU_2"):WaitRotate()
  end
  local taskGigaiasu3LookAround = function()
    CH("GIGAIASU_3"):DirTo(RotateTarget(-60), Speed(350), ROT_TYPE.NEAR)
    CH("GIGAIASU_3"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    CH("GIGAIASU_3"):DirTo(RotateTarget(60), Speed(350), ROT_TYPE.NEAR)
    CH("GIGAIASU_3"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    CH("GIGAIASU_3"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
    CH("GIGAIASU_3"):WaitRotate()
  end
  local taskGigaiasu4LookAround = function()
    CH("GIGAIASU_4"):DirTo(RotateTarget(60), Speed(350), ROT_TYPE.NEAR)
    CH("GIGAIASU_4"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    CH("GIGAIASU_4"):DirTo(RotateTarget(20), Speed(350), ROT_TYPE.NEAR)
    CH("GIGAIASU_4"):WaitRotate()
    TASK:Sleep(TimeSec(0.2))
    CH("GIGAIASU_4"):DirTo(RotateTarget(-60), Speed(350), ROT_TYPE.NEAR)
    CH("GIGAIASU_4"):WaitRotate()
  end
  TASK:Regist(Group("hero"), taskHeroLookAround)
  TASK:Regist(Group("grpKerd"), taskKerudyioLookAround)
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(Group("grpmunn"), taskMunnaLookAround)
  TASK:Regist(Group("grpdoku"), taskDokurogguLookAround)
  TASK:Regist(Group("grpshan"), taskShanderaLookAround)
  TASK:Regist(Group("grpEmon"), taskEmongaLookAround)
  TASK:Regist(Group("grpBiri"), taskBirijionLookAround)
  TASK:Regist(Group("partner"), taskPartnerLookAround)
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(Group("grpBura"), taskBurakkiiLookAround)
  TASK:Regist(Group("grpEefi"), taskEefiLookAround)
  TASK:Regist(Group("grpgiga1"), taskGigaiasu1LookAround)
  TASK:Regist(Group("grpgiga2"), taskGigaiasu2LookAround)
  TASK:Regist(Group("grpgiga3"), taskGigaiasu3LookAround)
  TASK:Regist(Group("grpgiga4"), taskGigaiasu4LookAround)
  TASK:WaitTask(Group("grpgiga4"))
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_02_2"))
  CAMERA:SetTgt(SymCam("CAMERA_02_2"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("EMONGA"):SetManpu("MP_FLY_SWEAT")
  CH("EMONGA"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("EMONGA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("EMONGA"), -473566313)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  CH("GIGAIASU_3"):DirTo(SymPos("POINT_HYOUTYUU"), Speed(500), ROT_TYPE.NEAR)
  CH("GIGAIASU_3"):WaitRotate()
  CH("GIGAIASU_3"):SetNeckRot(RotateTarget(0), RotateTarget(35), RotateTarget(0), TimeSec(0.3))
  CH("GIGAIASU_3"):WaitNeckRot()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("GIGAIASU_3"):SetManpu("MP_FLY_SWEAT")
  CH("GIGAIASU_3"):WaitManpu()
  WINDOW:DrawFace(324, 20, SymAct("GIGAIASU_1"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("GIGAIASU_1"), 1683877720)
  WINDOW:CloseMessage()
  CH("DOKUROGGU"):DirTo(SymPos("POINT_HYOUTYUU"), Speed(500), ROT_TYPE.NEAR)
  CH("DOKUROGGU"):WaitRotate()
  CH("DOKUROGGU"):SetNeckRot(RotateTarget(0), RotateTarget(35), RotateTarget(0), TimeSec(0.3))
  CH("DOKUROGGU"):WaitNeckRot()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_01"), Volume(256))
  CH("DOKUROGGU"):SetManpu("MP_EXCLAMATION")
  CH("DOKUROGGU"):WaitManpu()
  subEveDoubleJump(CH("DOKUROGGU"))
  WINDOW:DrawFace(20, 88, SymAct("DOKUROGGU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("DOKUROGGU"), 2101796377)
  CH("MUNNA"):DirTo(SymPos("POINT_HYOUTYUU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("SHANDERA_1"):DirTo(SymPos("POINT_HYOUTYUU"), Speed(350), ROT_TYPE.NEAR)
  CH("GIGAIASU_1"):DirTo(SymPos("POINT_HYOUTYUU"), Speed(350), ROT_TYPE.NEAR)
  CH("GIGAIASU_2"):DirTo(SymPos("POINT_HYOUTYUU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("GIGAIASU_4"):DirTo(SymPos("POINT_HYOUTYUU"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:Talk(SymAct("DOKUROGGU"), 827547113)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_08_1"))
  CAMERA:SetTgt(SymCam("CAMERA_08_1"))
  CH("PARTNER"):DirTo(SymPos("POINT_HYOUTYUU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):SetNeckRot(RotateTarget(0), RotateTarget(35), RotateTarget(0), TimeSec(0.3))
  CH("HERO"):DirTo(SymPos("POINT_HYOUTYUU"), Speed(350), ROT_TYPE.NEAR)
  CH("BIRIJION"):DirTo(SymPos("POINT_HYOUTYUU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("EMONGA"):DirTo(SymPos("POINT_HYOUTYUU"), Speed(350), ROT_TYPE.NEAR)
  CH("BURAKKII"):DirTo(SymPos("POINT_HYOUTYUU"), Speed(350), ROT_TYPE.NEAR)
  CH("EEFI"):DirTo(SymPos("POINT_HYOUTYUU"), Speed(350), ROT_TYPE.NEAR)
  CH("KERUDYIO"):DirTo(SymPos("POINT_HYOUTYUU"), Speed(350), ROT_TYPE.NEAR)
  CH("EMONGA"):SetNeckRot(RotateTarget(0), RotateTarget(35), RotateTarget(0), TimeSec(0.3))
  CH("BIRIJION"):SetNeckRot(RotateTarget(0), RotateTarget(35), RotateTarget(0), TimeSec(0.3))
  CH("HERO"):SetNeckRot(RotateTarget(0), RotateTarget(35), RotateTarget(0), TimeSec(0.3))
  TASK:Sleep(TimeSec(0.2))
  CH("BURAKKII"):SetNeckRot(RotateTarget(0), RotateTarget(35), RotateTarget(0), TimeSec(0.3))
  CH("EEFI"):SetNeckRot(RotateTarget(0), RotateTarget(35), RotateTarget(0), TimeSec(0.3))
  CH("KERUDYIO"):SetNeckRot(RotateTarget(0), RotateTarget(35), RotateTarget(0), TimeSec(0.3))
  CH("KERUDYIO"):WaitRotate()
  CH("KERUDYIO"):WaitNeckRot()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFaceF(172, 8, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 675835048, PARTNER_1 = 56967019})
  WINDOW:CloseMessage()
  subEveDoubleJump(CH("EMONGA"))
  WINDOW:DrawFace(324, 20, SymAct("EMONGA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("EMONGA"), 444468778)
  TASK:Sleep(TimeSec(0.8))
  WINDOW:ForceCloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  WINDOW:DrawFace(324, 88, SymAct("EEFI"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("EEFI"), 1430231277)
  TASK:Sleep(TimeSec(0.7))
  WINDOW:ForceCloseMessage()
  CH("HERO"):SetNeckRot(RotateTarget(0), RotateTarget(35), RotateTarget(0), TimeSec(0.3))
  CAMERA:MoveFollow2(SymCam("CAMERA_10"), Speed(4, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Sleep(TimeSec(0.3))
  CAMERA:MoveFollow2(SymCam("CAMERA_10"), Speed(8, ACCEL_TYPE.NONE, DECEL_TYPE.NONE))
  GM("PILLAR_SHADOW"):SetVisible(true)
  GM("PILLAR_SHADOW"):SetMotion(SymMot("FALL"), LOOP.OFF)
  CH("HERO"):ChangeColor(Color(0.2, 0.2, 0.2, 1), TimeSec(0.9))
  CH("PARTNER"):ChangeColor(Color(0.2, 0.2, 0.2, 1), TimeSec(0.9))
  CH("EMONGA"):ChangeColor(Color(0.2, 0.2, 0.2, 1), TimeSec(0.9))
  TASK:Sleep(TimeSec(0.5))
  SCREEN_A:WhiteOut(TimeSec(0.5), true)
  SOUND:PlaySe(SymSnd("SE_EVT_HYOUCHU_CRUSH"), Volume(256))
  SOUND:FadeOutEnv(TimeSec(1))
  WINDOW:SwitchTalk({PARTNER_0 = 1277471148, PARTNER_1 = 1728707183})
  TASK:Sleep(TimeSec(1))
  WINDOW:ForceCloseMessage()
  SOUND:WaitSe(SymSnd("SE_EVT_HYOUCHU_CRUSH"))
  FLAG.SceneFlag = CONST.FL_SC_02_END
  FLAG.SCENARIOFLAG = CONST.M17_GREPALACEWESTBOSSWIN_START
  SYSTEM:NextEntry()
end
function main17_grepalacewestbosswin02_end()
end
function main17_grepalacewestbosswin03_init()
  if FLAG.NowResumeFlag == CONST.FLAG_TRUE then
    subEveFromProgFadeSet()
    subSaveflagM17_190_03()
  end
end
function main17_grepalacewestbosswin03_start()
  CHARA:SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  CAMERA:SetAzimuthDifferenceVolume(Volume(6))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HERO"):SetMotion(SymMot("EV001_DOWN01"), LOOP.ON)
  CH("PARTNER"):SetMotion(SymMot("EV001_DOWN01"), LOOP.ON)
  CH("MUNNA_ZERO"):SetMotion(SymMot("EV013_DOWN00"), LOOP.ON)
  CAMERA:MoveFollow2(SymCam("CAMERA_00_5"), Speed(2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Sleep(TimeSec(0.5))
  SCREEN_A:WhiteIn(TimeSec(0.5), true)
  CAMERA:WaitMove()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:MoveFollow2(SymCam("CAMERA_01_5"), Speed(2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Sleep(TimeSec(0.5))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CAMERA:WaitMove()
  TASK:Sleep(TimeSec(0.8))
  CAMERA:SetAzimuthDifferenceVolume(Volume(2.5))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("BURAKKII"):SetManpu("MP_EXCLAMATION")
  CH("BURAKKII"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("BURAKKII"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("BURAKKII"), 2115160878)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(2.5))
  CAMERA:SetEye(SymCam("CAMERA_02_1"))
  CAMERA:SetTgt(SymCam("CAMERA_02_1"))
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  subEveDoubleJump(CH("DOKUROGGU"))
  WINDOW:DrawFace(20, 88, SymAct("DOKUROGGU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("DOKUROGGU"), -108341279)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetEye(SymCam("CAMERA_02_2"))
  CAMERA:SetTgt(SymCam("CAMERA_02_2"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(324, 88, SymAct("EEFI"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("EEFI"), -527309152)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3.5))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.8))
  CH("HERO"):SetMotionRaito(Raito(0.6))
  CH("HERO"):SetMotion(SymMot("EV001_DOWN02"), LOOP.OFF)
  TASK:Sleep(TimeSec(0.3))
  CH("PARTNER"):SetMotionRaito(Raito(0.6))
  CH("PARTNER"):SetMotion(SymMot("EV001_DOWN02"), LOOP.OFF)
  CH("HERO"):WaitPlayMotion()
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):SetMotionRaito(Raito(1))
  CH("PARTNER"):SetMotionRaito(Raito(1))
  CH("HERO"):DirTo(CH("MUNNA_ZERO"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitPlayMotion()
  CH("PARTNER"):DirTo(CH("MUNNA_ZERO"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("HERO"):SetManpu("MP_SHOCK_L")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(-1980810612)
  WINDOW:CloseMessage()
  subEveDoubleJump(CH("PARTNER"))
  WINDOW:DrawFace(226, 8, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:DrawFaceOffset(15, 0)
  WINDOW:SwitchTalk({PARTNER_0 = -1863054387, PARTNER_1 = -1143384050})
  WINDOW:KeyWait()
  CH("PARTNER"):RunTo(SymPos("P01_PARTNER"), Speed(1.7))
  CH("PARTNER"):WaitMove()
  WINDOW:SwitchTalk({PARTNER_0 = -1564317361, PARTNER_1 = -310116472})
  WINDOW:CloseMessage()
  CH("MUNNA_ZERO"):SetShake(Vector(0.005, 0, 0), TimeSec(0.1, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.5))
  CH("MUNNA_ZERO"):ResetShake()
  WINDOW:DrawFace(20, 88, SymAct("MUNNA"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("MUNNA"), -191312183)
  WINDOW:Talk(SymAct("MUNNA"), -541745910)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(226, 8, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -961631157, PARTNER_1 = 1094103172})
  WINDOW:CloseMessage()
  CH("MUNNA_ZERO"):SetShake(Vector(0.005, 0, 0), TimeSec(0.1, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.5))
  CH("MUNNA_ZERO"):ResetShake()
  WINDOW:DrawFace(20, 88, SymAct("MUNNA"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("MUNNA"), 1479377349)
  WINDOW:Talk(SymAct("MUNNA"), -1688562334)
  WINDOW:DrawFace(20, 88, SymAct("MUNNA"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("MUNNA"), -2109627357)
  SOUND:PlayBgm(SymSnd("BGM_EVE_SEND_OFF"), Volume(256))
  WINDOW:CloseMessage()
  CH("HERO"):RunTo(SymPos("P01_HERO"), Speed(1.7))
  CH("HERO"):WaitMove()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(-1452476448)
  subEveCloseMsg()
  local taskLookAt03 = function()
    TASK:Sleep(TimeSec(0.3))
    CH("HERO"):DirTo(CH("KERUDYIO"), Speed(200), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.2))
    CH("PARTNER"):DirTo(CH("KERUDYIO"), Speed(200), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt03)
  WINDOW:DrawFace(20, 88, SymAct("KERUDYIO"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("KERUDYIO"), -1334327647)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow2(SymCam("CAMERA_06"), Speed(4, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Sleep(TimeSec(0.5))
  CH("KERUDYIO"):RunTo(SymPos("P01_KERUDYIO"), Speed(1.5))
  CAMERA:WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("KERUDYIO"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("KERUDYIO"), -13217690)
  WINDOW:Talk(SymAct("KERUDYIO"), -433233625)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(2.5))
  CAMERA:SetEye(SymCam("CAMERA_02_1"))
  CAMERA:SetTgt(SymCam("CAMERA_02_1"))
  TASK:Sleep(TimeSec(0.15))
  WINDOW:DrawFace(20, 88, SymAct("DOKUROGGU"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("DOKUROGGU"), -855624988)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(2.5))
  CAMERA:SetEye(SymCam("CAMERA_02_3"))
  CAMERA:SetTgt(SymCam("CAMERA_02_3"))
  TASK:Sleep(TimeSec(0.15))
  WINDOW:DrawFace(20, 88, SymAct("GIGAIASU_1"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("GIGAIASU_1"), -736427099)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(2.5))
  CAMERA:SetEye(SymCam("CAMERA_02_4"))
  CAMERA:SetTgt(SymCam("CAMERA_02_4"))
  TASK:Sleep(TimeSec(0.15))
  WINDOW:DrawFace(20, 88, SymAct("SHANDERA_1"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("SHANDERA_1"), 1401102186)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  subEveJump(CH("BURAKKII"))
  WINDOW:DrawFace(20, 88, SymAct("BURAKKII"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("BURAKKII"), 1251487275)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetEye(SymCam("CAMERA_02_2"))
  CAMERA:SetTgt(SymCam("CAMERA_02_2"))
  TASK:Sleep(TimeSec(0.15))
  WINDOW:DrawFace(324, 88, SymAct("EEFI"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("EEFI"), 602337799)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetEye(SymCam("CAMERA_02_5"))
  CAMERA:SetTgt(SymCam("CAMERA_02_5"))
  TASK:Sleep(TimeSec(0.15))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("BIRIJION"), 989709126)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetEye(SymCam("CAMERA_02_6"))
  CAMERA:SetTgt(SymCam("CAMERA_02_6"))
  subEveDoubleJump(CH("EMONGA"))
  WINDOW:DrawFace(324, 88, SymAct("EMONGA"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("EMONGA"), 298881157)
  WINDOW:Talk(SymAct("EMONGA"), 147562948)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  TASK:Sleep(TimeSec(0.15))
  CH("EMONGA"):SetManpu("MP_SPREE_LP")
  WINDOW:DrawFace(324, 88, SymAct("EMONGA"), FACE_TYPE.SHOUT)
  WINDOW:Talk(SymAct("EMONGA"), 1200240387)
  WINDOW:CloseMessage()
  CH("EMONGA"):ResetManpu()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3.5))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.3))
  TASK:Regist(subEveNod, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(226, 8, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = 1586562626, PARTNER_1 = 1975276929})
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(CH("MUNNA_ZERO"), Speed(60), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(226, 8, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = 1822909632, PARTNER_1 = -348162033})
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3.5))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CH("PARTNER"):DirTo(CH("KERUDYIO"), Speed(200), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = -232502962, PARTNER_1 = 2072371793})
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = 1654575888, PARTNER_1 = 1236500691})
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3.5))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = 1353232786, PARTNER_1 = 535373653})
  WINDOW:CloseMessage()
  TASK:Regist(subEveNod, {
    CH("HERO")
  })
  TASK:Sleep(TimeSec(0.6))
  CH("PARTNER"):DirTo(CH("BIRIJION"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  WINDOW:DrawFace(226, 8, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = 116528660, PARTNER_1 = 769607127})
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(RotateTarget(135), Speed(500), ROT_TYPE.LEFT)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(RotateTarget(135), Speed(500), ROT_TYPE.RIGHT)
  CH("HERO"):WaitRotate()
  CH("PARTNER"):RunTo(SymPos("P02_PARTNER"), Speed(1.7))
  CH("HERO"):RunTo(SymPos("P02_HERO"), Speed(1.7))
  CAMERA:MoveFollow(SymCam("CAMERA_03_1"), Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  TASK:Sleep(TimeSec(0.5))
  WINDOW:DrawFace(20, 88, SymAct("EMONGA"), FACE_TYPE.SHOUT)
  WINDOW:Talk(SymAct("EMONGA"), 885290134)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(4))
  TASK:Sleep(TimeSec(1))
  CH("HERO"):SetVisible(false)
  CH("PARTNER"):SetVisible(false)
  SCREEN_A:FadeOut(TimeSec(1), true)
  TASK:Sleep(TimeSec(3))
  CAMERA:SetAzimuthDifferenceVolume(Volume(2.5))
  CAMERA:SetEye(SymCam("CAMERA_02_3"))
  CAMERA:SetTgt(SymCam("CAMERA_02_3"))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.5))
  WINDOW:DrawFace(20, 88, SymAct("GIGAIASU_1"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("GIGAIASU_1"), -1285789607)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(2.5))
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("DOKUROGGU"):SetManpu("MP_EXCLAMATION")
  CH("DOKUROGGU"):WaitManpu()
  subEveDoubleJump(CH("DOKUROGGU"))
  CH("BURAKKII"):DirTo(CH("DOKUROGGU"), Speed(500), ROT_TYPE.RIGHT)
  CH("EMONGA"):DirTo(CH("DOKUROGGU"), Speed(500), ROT_TYPE.RIGHT)
  CH("EEFI"):DirTo(CH("DOKUROGGU"), Speed(500), ROT_TYPE.LEFT)
  CH("EEFI"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("DOKUROGGU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("DOKUROGGU"), -1438164712)
  WINDOW:CloseMessage()
  CH("DOKUROGGU"):RunTo(SymPos("P01_DOKUROGGU"), Speed(3))
  TASK:Sleep(TimeSec(0.3))
  CH("BURAKKII"):DirTo(CH("MUNNA_ZERO"), Speed(350), ROT_TYPE.LEFT)
  CH("EMONGA"):DirTo(CH("MUNNA_ZERO"), Speed(350), ROT_TYPE.LEFT)
  CH("EEFI"):DirTo(CH("MUNNA_ZERO"), Speed(350), ROT_TYPE.RIGHT)
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_05_1"))
  CAMERA:SetTgt(SymCam("CAMERA_05_1"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("SHANDERA_1"):SetManpu("MP_FLY_SWEAT")
  CH("SHANDERA_1"):WaitManpu()
  CH("EMONGA"):DirTo(CH("SHANDERA_1"), Speed(500), ROT_TYPE.RIGHT)
  CH("BIRIJION"):DirTo(CH("SHANDERA_1"), Speed(500), ROT_TYPE.RIGHT)
  CH("BURAKKII"):DirTo(CH("SHANDERA_1"), Speed(500), ROT_TYPE.RIGHT)
  CH("BURAKKII"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("SHANDERA_1"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("SHANDERA_1"), -1019640524)
  WINDOW:CloseMessage()
  CH("SHANDERA_1"):RunTo(SplinePath(SymPos("P00_SHANDERA_1"), SymPos("P01_SHANDERA_1")), Speed(3))
  TASK:Sleep(TimeSec(0.3))
  CH("EMONGA"):DirTo(CH("MUNNA_ZERO"), Speed(200), ROT_TYPE.RIGHT)
  CH("BIRIJION"):DirTo(CH("MUNNA_ZERO"), Speed(200), ROT_TYPE.RIGHT)
  CH("BURAKKII"):DirTo(CH("MUNNA_ZERO"), Speed(200), ROT_TYPE.RIGHT)
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_05_2"))
  CAMERA:SetTgt(SymCam("CAMERA_05_2"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 88, SymAct("GIGAIASU_1"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("GIGAIASU_1"), -635259787)
  WINDOW:CloseMessage()
  CH("GIGAIASU_1"):RunTo(SymPos("P01_GIGAIASU_1"), Speed(2))
  TASK:Sleep(TimeSec(0.1))
  CH("GIGAIASU_2"):RunTo(SymPos("P01_GIGAIASU_2"), Speed(2))
  CH("GIGAIASU_3"):RunTo(SymPos("P01_GIGAIASU_3"), Speed(2))
  TASK:Sleep(TimeSec(0.1))
  CH("GIGAIASU_4"):RunTo(SymPos("P01_GIGAIASU_4"), Speed(2))
  CH("GIGAIASU_4"):WaitMove()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CH("MUNNA_ZERO"):SetShake(Vector(0.005, 0, 0), TimeSec(0.1, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.5))
  CH("MUNNA_ZERO"):ResetShake()
  TASK:Sleep(TimeSec(0.3))
  CH("MUNNA_ZERO"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
  WINDOW:DrawFaceF(226, 8, SymAct("MUNNA"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("MUNNA"), -250615882)
  WINDOW:Talk(SymAct("MUNNA"), -401287433)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow(SymCam("CAMERA_06_1"), Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("KERUDYIO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KERUDYIO"), -1487585232)
  CH("MUNNA_ZERO"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  WINDOW:Talk(SymAct("KERUDYIO"), -1102155407)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("KERUDYIO"):SetManpu("MP_SHOCK_R")
  CH("KERUDYIO"):SetMotion(SymMot("EV011_TIRED00"), LOOP.OFF)
  CH("KERUDYIO"):WaitPlayMotion()
  CH("KERUDYIO"):SetMotion(SymMot("EV011_TIRED01"), LOOP.ON)
  WINDOW:DrawFace(20, 88, SymAct("KERUDYIO"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("KERUDYIO"), -1788665166)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  CH("SHANDERA_1"):DirTo(CH("KERUDYIO"), Speed(500), ROT_TYPE.NEAR)
  CH("DOKUROGGU"):DirTo(CH("KERUDYIO"), Speed(500), ROT_TYPE.NEAR)
  CH("BIRIJION"):DirTo(CH("KERUDYIO"), Speed(500), ROT_TYPE.NEAR)
  CH("BURAKKII"):DirTo(CH("KERUDYIO"), Speed(500), ROT_TYPE.NEAR)
  CH("EMONGA"):DirTo(CH("KERUDYIO"), Speed(500), ROT_TYPE.NEAR)
  CH("EEFI"):DirTo(CH("KERUDYIO"), Speed(500), ROT_TYPE.NEAR)
  CH("EEFI"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_01"), Volume(256))
  CH("BIRIJION"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("BURAKKII"):SetManpu("MP_EXCLAMATION")
  CH("EMONGA"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("EEFI"):SetManpu("MP_EXCLAMATION")
  CH("EEFI"):WaitManpu()
  CH("BIRIJION"):RunTo(SymPos("P01_BIRIJION"), Speed(2))
  CH("BIRIJION"):WaitMove()
  WINDOW:DrawFace(20, 20, SymAct("BIRIJION"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("BIRIJION"), -1938287629)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("BURAKKII"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("BURAKKII"), 199233340)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  CH("EEFI"):WalkTo(SymPos("P01_EEFI"), Speed(1.5))
  CH("EEFI"):WaitMove()
  WINDOW:DrawFace(324, 88, SymAct("EEFI"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("EEFI"), 318455421)
  WINDOW:Talk(SymAct("EEFI"), 950384656)
  subEveCloseMsg()
  WINDOW:DrawFaceF(272, 16, SymAct("KERUDYIO"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("KERUDYIO"), 566135121)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 20, SymAct("BIRIJION"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("BIRIJION"), 177461906)
  subEveCloseMsg()
  CAMERA:SetAzimuthDifferenceVolume(Volume(2.5))
  CAMERA:SetEye(SymCam("CAMERA_11"))
  CAMERA:SetTgt(SymCam("CAMERA_11"))
  SOUND:PlayBgm(SymSnd("BGM_EVE_REFORM"), Volume(256))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFaceF(324, 88, SymAct("KERUDYIO"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("KERUDYIO"), 327740371)
  WINDOW:Talk(SymAct("KERUDYIO"), 1556708628)
  WINDOW:Talk(SymAct("KERUDYIO"), 1171410005)
  WINDOW:Talk(SymAct("KERUDYIO"), 1862213526)
  WINDOW:Talk(SymAct("KERUDYIO"), 2011442903)
  WINDOW:Talk(SymAct("KERUDYIO"), -260296168)
  WINDOW:Talk(SymAct("KERUDYIO"), -379124903)
  WINDOW:Talk(SymAct("KERUDYIO"), -2145788043)
  WINDOW:Talk(SymAct("KERUDYIO"), -1727861196)
  WINDOW:Talk(SymAct("KERUDYIO"), -1305494025)
  WINDOW:Talk(SymAct("KERUDYIO"), -1422619466)
  subEveCloseMsg()
  CH("BIRIJION"):SetNeckRot(RotateTarget(0), RotateTarget(-20), RotateTarget(0), TimeSec(0.35))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("BIRIJION"), -462087567)
  subEveCloseMsg()
  WINDOW:DrawFaceF(324, 88, SymAct("KERUDYIO"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("KERUDYIO"), -43111632)
  WINDOW:Talk(SymAct("KERUDYIO"), -700221197)
  WINDOW:Talk(SymAct("KERUDYIO"), -816297550)
  WINDOW:CloseMessage()
  CH("BIRIJION"):ResetNeckRot(TimeSec(0.2))
  CH("BIRIJION"):WaitNeckRot()
  CH("BIRIJION"):WalkTo(SymPos("P02_BIRIJION"), Speed(1.5))
  CH("BIRIJION"):WaitMove()
  TASK:Sleep(TimeSec(0.3))
  subEveNoNoNo(CH("BIRIJION"))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.SPECIAL04)
  WINDOW:Talk(SymAct("BIRIJION"), 1220564349)
  WINDOW:Talk(SymAct("BIRIJION"), 1373332540)
  WINDOW:Talk(SymAct("BIRIJION"), -1834192741)
  WINDOW:Talk(SymAct("BIRIJION"), -1950924326)
  WINDOW:Talk(SymAct("BIRIJION"), -1600515559)
  WINDOW:Talk(SymAct("BIRIJION"), -1182719144)
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("BIRIJION"), -155142753)
  WINDOW:Talk(SymAct("BIRIJION"), -270826274)
  WINDOW:KeyWait()
  CH("BIRIJION"):SetManpu("MP_FLY_SWEAT")
  CH("BIRIJION"):SetMotion(SymMot("EV017_CRY"), LOOP.ON, TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.WEEP)
  WINDOW:Talk(SymAct("BIRIJION"), -990456035)
  TASK:Sleep(TimeSec(0.3))
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  CH("EEFI"):WalkTo(SymPos("P02_EEFI"), Speed(1.2))
  CH("EEFI"):WaitMove()
  WINDOW:DrawFace(324, 20, SymAct("EEFI"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("EEFI"), -571611556)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("EMONGA"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("EMONGA"), 1517681299)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_12"))
  CAMERA:SetTgt(SymCam("CAMERA_12"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:Talk(SymAct("KERUDYIO"), 1131334610)
  WINDOW:Talk(SymAct("KERUDYIO"), 705697790)
  WINDOW:Talk(SymAct("KERUDYIO"), 856368831)
  WINDOW:Talk(SymAct("KERUDYIO"), 405173628)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(3.5))
  SCREEN_A:FadeOut(TimeSec(1.5), true)
  SOUND:WaitBgm()
  TASK:Sleep(TimeSec(0.5))
  TASK:Sleep(TimeSec(0.2))
  if Ground_Save(ground) then
    return
  end
  subSaveflagM17_190_03()
end
function main17_grepalacewestbosswin03_end()
end
function subSaveflagM17_190_03()
  FLAG.SceneFlag = CONST.FL_SC_01_FIRST
  FLAG.SCENARIOFLAG = CONST.M17_GREPALACEWESTBOSSWIN_END
  SYSTEM:NextEntry()
end
function groundEnd()
end

