dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main06_nuonotanomigoto01_init()
end
function main06_nuonotanomigoto01_start()
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HERO"):WalkTo(SymPos("P00_HERO"), Speed(1.5))
  CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(1.5))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("NUOO"):SetManpu("MP_NOTICE_R")
  CH("NUOO"):WaitManpu()
  CH("NUOO"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  CH("NUOO"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("NUOO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NUOO"), -1002726587)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("HERO"):WalkTo(SymPos("P01_HERO"), Speed(1.5))
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):WalkTo(SymPos("P01_PARTNER"), Speed(1.5))
  CH("HERO"):WaitMove()
  CH("HERO"):DirTo(CH("NUOO"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitMove()
  WINDOW:DrawFace(324, 88, SymAct("NUOO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NUOO"), -585061884)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -166856249, PARTNER_1 = -283719546})
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("NUOO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NUOO"), -1604886975)
  subEveCloseMsg()
  local lastPosNuoo = CH("NUOO"):GetPosition2d()
  CH("NUOO"):WalkTo(SymPos("P01_NUOO"), Speed(1.2))
  CH("PARTNER"):DirTo(CH("HERO"), Speed(200), ROT_TYPE.NEAR)
  CH("NUOO"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_ACT_MONEY"), Volume(256))
  WINDOW:SysMsg(-1186173184)
  WINDOW:CloseMessage()
  CH("NUOO"):WalkTo(lastPosNuoo, Speed(1.2), LINK_DIR.OFF)
  CH("NUOO"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_QUESTION")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1839121213, PARTNER_1 = -1954935422})
  subEveCloseMsg()
  CH("NUOO"):DirTo(CH("PARTNER"), Speed(200), ROT_TYPE.NEAR)
  CH("NUOO"):WaitRotate()
  CH("PARTNER"):DirTo(CH("NUOO"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(324, 88, SymAct("NUOO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NUOO"), 216142157)
  WINDOW:Talk(SymAct("NUOO"), 368648204)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("NUOO"):SetManpu("MP_FLY_SWEAT")
  CH("NUOO"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("NUOO"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("NUOO"), -856656162)
  WINDOW:Talk(SymAct("NUOO"), -706000993)
  WINDOW:Talk(SymAct("NUOO"), -20573092)
  WINDOW:Talk(SymAct("NUOO"), -404937443)
  WINDOW:DrawFace(324, 88, SymAct("NUOO"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("NUOO"), -1466125350)
  WINDOW:Talk(SymAct("NUOO"), -1316519269)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HERO"):SetDir(RotateTarget(0))
  CH("PARTNER"):SetDir(RotateTarget(0))
  CH("NUOO"):SetDir(RotateTarget(180))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1700081320, PARTNER_1 = -2085494759})
  WINDOW:SwitchTalk({PARTNER_0 = 69860566, PARTNER_1 = 489868695})
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("NUOO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NUOO"), -565847760)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  FLAG.SceneFlag = CONST.FL_SC_01_FIRST
  FLAG.SCENARIOFLAG = CONST.M06_NUONOTANOMIGOTO_END
  FLAG.MapFlags = CONST.MAP_EVENT
  FLAG.FreePlay = CONST.FLAG_TRUE
  FLAG.TrigNextEvent = CONST.FLAG_FALSE
  SYSTEM:NextEntry()
end
function main06_nuonotanomigoto01_end()
end
function groundEnd()
end

