function BIRIJIONTbl.M12_010_BIRIJION_FREE_START()
  return BIRIJIONTbl.M11_090_BIRIJION_FREE_START
end
function BIRIJIONTbl.M12_020_BIRIJION_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BIRIJION"))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), -306916336)
  WINDOW:Talk(SymAct("BIRIJION"), -189799087)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BIRIJION"), result)
end
function BIRIJIONTbl.M12_030_BIRIJION_FREE_START()
  return BIRIJIONTbl.M12_020_BIRIJION_FREE_START
end
function BIRIJIONTbl.M12_040_BIRIJION_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BIRIJION"))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), -545081710)
  WINDOW:Talk(SymAct("BIRIJION"), -963016749)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BIRIJION"), result)
end
function BIRIJIONTbl.M12_050_BIRIJION_FREE_START()
  return BIRIJIONTbl.M12_040_BIRIJION_FREE_START
end
function BIRIJIONTbl.M12_070_BIRIJION_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BIRIJION"))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), -1982328556)
  WINDOW:Talk(SymAct("BIRIJION"), -1866260395)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BIRIJION"), result)
end
function BIRIJIONTbl.M13_010_BIRIJION_FREE_START()
  return BIRIJIONTbl.M12_070_BIRIJION_FREE_START
end
function BIRIJIONTbl.M13_030_BIRIJION_FREE_START()
  return BIRIJIONTbl.M13_010_BIRIJION_FREE_START
end
function BIRIJIONTbl.M13_040_BIRIJION_FREE_START()
  return BIRIJIONTbl.M13_030_BIRIJION_FREE_START
end
function BIRIJIONTbl.M13_060_BIRIJION_FREE_START()
  return BIRIJIONTbl.M13_040_BIRIJION_FREE_START
end
function BIRIJIONTbl.M13_070_BIRIJION_FREE_START()
  return BIRIJIONTbl.M13_060_BIRIJION_FREE_START
end
function BIRIJIONTbl.M13_080_BIRIJION_FREE_START()
  return BIRIJIONTbl.M13_070_BIRIJION_FREE_START
end
function BIRIJIONTbl.M13_090_BIRIJION_FREE_START()
  return BIRIJIONTbl.M13_080_BIRIJION_FREE_START
end
function BIRIJIONTbl.M13_110_BIRIJION_FREE_START()
  return BIRIJIONTbl.M13_090_BIRIJION_FREE_START
end
function BIRIJIONTbl.M14_010_BIRIJION_FREE_START()
  return BIRIJIONTbl.M13_110_BIRIJION_FREE_START
end
function BIRIJIONTbl.M14_030_BIRIJION_FREE_START()
  return BIRIJIONTbl.M14_010_BIRIJION_FREE_START
end
function BIRIJIONTbl.M14_040_BIRIJION_FREE_START()
  return BIRIJIONTbl.M14_030_BIRIJION_FREE_START
end
function BIRIJIONTbl.M14_060_BIRIJION_FREE_START()
  return BIRIJIONTbl.M14_040_BIRIJION_FREE_START
end
function BIRIJIONTbl.M14_070_BIRIJION_FREE_START()
  return BIRIJIONTbl.M14_060_BIRIJION_FREE_START
end
function BIRIJIONTbl.M14_090_BIRIJION_FREE_START()
  return BIRIJIONTbl.M14_070_BIRIJION_FREE_START
end
function BIRIJIONTbl.M15_010_BIRIJION_FREE_START()
  return BIRIJIONTbl.M14_090_BIRIJION_FREE_START
end
function BIRIJIONTbl.M15_020_BIRIJION_FREE_START()
  return BIRIJIONTbl.M15_010_BIRIJION_FREE_START
end
function BIRIJIONTbl.M15_030_BIRIJION_FREE_START()
  return BIRIJIONTbl.M15_020_BIRIJION_FREE_START
end
function BIRIJIONTbl.M16_010_BIRIJION_FREE_START()
  return BIRIJIONTbl.M15_030_BIRIJION_FREE_START
end
function BIRIJIONTbl.M16_040_BIRIJION_FREE_START()
  return BIRIJIONTbl.M16_010_BIRIJION_FREE_START
end
function BIRIJIONTbl.M16_080_BIRIJION_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BIRIJION"))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), -1142000746)
  WINDOW:Talk(SymAct("BIRIJION"), -1560984873)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BIRIJION"), result)
end
function BIRIJIONTbl.M16_090_BIRIJION_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BIRIJION"))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), 627924504)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BIRIJION"), result)
end
function BIRIJIONTbl.M16_100_BIRIJION_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BIRIJION"))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), 1014394713)
  WINDOW:Talk(SymAct("BIRIJION"), -312497599)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BIRIJION"), result)
end
function BIRIJIONTbl.M16_105_BIRIJION_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BIRIJION"))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), -196830464)
  WINDOW:Talk(SymAct("BIRIJION"), -546715453)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BIRIJION"), result)
end
function BIRIJIONTbl.M16_120_BIRIJION_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BIRIJION"))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), -965543550)
  WINDOW:Talk(SymAct("BIRIJION"), -1993117883)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BIRIJION"), result)
end
function BIRIJIONTbl.M17_020_BIRIJION_FREE_START()
  return BIRIJIONTbl.M16_120_BIRIJION_FREE_START
end
function BIRIJIONTbl.M17_040_BIRIJION_FREE_START()
  return BIRIJIONTbl.M17_020_BIRIJION_FREE_START
end
function BIRIJIONTbl.M17_060_BIRIJION_FREE_START()
  return BIRIJIONTbl.M17_040_BIRIJION_FREE_START
end
function BIRIJIONTbl.M17_065_BIRIJION_FREE_START()
  return BIRIJIONTbl.M17_060_BIRIJION_FREE_START
end
function BIRIJIONTbl.M17_090_BIRIJION_FREE_START()
  return BIRIJIONTbl.M17_065_BIRIJION_FREE_START
end
function BIRIJIONTbl.M17_120_BIRIJION_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BIRIJION"))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), -1876402684)
  WINDOW:Talk(SymAct("BIRIJION"), -1157296697)
  WINDOW:Talk(SymAct("BIRIJION"), -1575076730)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BIRIJION"), result)
end
function BIRIJIONTbl.M17_140_BIRIJION_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BIRIJION"))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), 629547081)
  WINDOW:Talk(SymAct("BIRIJION"), 1016926472)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BIRIJION"), result)
end
function BIRIJIONTbl.M17_150_BIRIJION_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BIRIJION"))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), -1440337)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BIRIJION"), result)
end
function BIRIJIONTbl.M17_155_BIRIJION_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BIRIJION"))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), -420399890)
  WINDOW:Talk(SymAct("BIRIJION"), -841193683)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BIRIJION"), result)
end
function BIRIJIONTbl.M17_170_BIRIJION_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BIRIJION"))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("BIRIJION"), -725133716)
  WINDOW:Talk(SymAct("BIRIJION"), -1685667669)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BIRIJION"), result)
end
function BIRIJIONTbl.M17_200_BIRIJION_FREE_START()
  return BIRIJIONTbl.M17_170_BIRIJION_FREE_START
end
function BIRIJIONTbl.M17_210_BIRIJION_FREE_START()
  return BIRIJIONTbl.M17_200_BIRIJION_FREE_START
end
function BIRIJIONTbl.M17_220_BIRIJION_FREE_START()
  return BIRIJIONTbl.M17_210_BIRIJION_FREE_START
end
function BIRIJIONTbl.M17_225_BIRIJION_FREE_START()
  return BIRIJIONTbl.M17_220_BIRIJION_FREE_START
end
function BIRIJIONTbl.M17_240_BIRIJION_FREE_START()
  return BIRIJIONTbl.M17_225_BIRIJION_FREE_START
end
function BIRIJIONTbl.M18_020_BIRIJION_FREE_START()
  return BIRIJIONTbl.M17_240_BIRIJION_FREE_START
end
function BIRIJIONTbl.M18_030_BIRIJION_FREE_START()
  return BIRIJIONTbl.M18_020_BIRIJION_FREE_START
end
function BIRIJIONTbl.S01_010_BIRIJION_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BIRIJION"))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), -2103578134)
  WINDOW:Talk(SymAct("BIRIJION"), -1448041943)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BIRIJION"), result)
end
function BIRIJIONTbl.S01_020_BIRIJION_FREE_START()
  return BIRIJIONTbl.S01_010_BIRIJION_FREE_START
end
function BIRIJIONTbl.S01_030_BIRIJION_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BIRIJION"))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), -1330932888)
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("BIRIJION"), 926125991)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BIRIJION"), result)
end
function BIRIJIONTbl.S01_040_BIRIJION_FREE_START()
  return BIRIJIONTbl.S01_030_BIRIJION_FREE_START
end
function BIRIJIONTbl.S01_050_BIRIJION_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BIRIJION"))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), 774422246)
  WINDOW:Talk(SymAct("BIRIJION"), 1196843722)
  WINDOW:Talk(SymAct("BIRIJION"), 1582125963)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BIRIJION"), result)
end
function BIRIJIONTbl.S01_060_BIRIJION_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BIRIJION"))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), 1969225800)
  WINDOW:Talk(SymAct("BIRIJION"), 1820012809)
  WINDOW:Talk(SymAct("BIRIJION"), 591046606)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BIRIJION"), result)
end
function BIRIJIONTbl.S01_080_BIRIJION_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BIRIJION"))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("BIRIJION"), 975279759)
  WINDOW:Talk(SymAct("BIRIJION"), 286049612)
  WINDOW:Talk(SymAct("BIRIJION"), 135787533)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BIRIJION"), result)
end
function BIRIJIONTbl.ALL_CLEAR_BIRIJION_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BIRIJION"))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), -1886394174)
  WINDOW:Talk(SymAct("BIRIJION"), -1768629885)
  WINDOW:Talk(SymAct("BIRIJION"), -629056909)
  WINDOW:Talk(SymAct("BIRIJION"), -1013290190)
  WINDOW:Talk(SymAct("BIRIJION"), -390645519)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BIRIJION"), result)
end

