function BIRIJIONTbl.M02_010_BIRIJION_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BIRIJION"))
  WINDOW:SysMsg(-1986764667)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BIRIJION"), result)
end
function BIRIJIONTbl.M02_030_BIRIJION_FREE_START()
  return BIRIJIONTbl.M02_010_BIRIJION_FREE_START
end
function BIRIJIONTbl.M02_050_BIRIJION_FREE_START()
  return BIRIJIONTbl.M02_030_BIRIJION_FREE_START
end
function BIRIJIONTbl.M02_070_BIRIJION_FREE_START()
  return BIRIJIONTbl.M02_050_BIRIJION_FREE_START
end
function BIRIJIONTbl.M02_080_BIRIJION_FREE_START()
  return BIRIJIONTbl.M02_070_BIRIJION_FREE_START
end
function BIRIJIONTbl.M02_090_BIRIJION_FREE_START()
  return BIRIJIONTbl.M02_080_BIRIJION_FREE_START
end
function BIRIJIONTbl.M02_100_BIRIJION_FREE_START()
  return BIRIJIONTbl.M02_090_BIRIJION_FREE_START
end
function BIRIJIONTbl.M02_115_BIRIJION_FREE_START()
  return BIRIJIONTbl.M02_100_BIRIJION_FREE_START
end
function BIRIJIONTbl.M02_130_BIRIJION_FREE_START()
  return BIRIJIONTbl.M02_115_BIRIJION_FREE_START
end
function BIRIJIONTbl.M02_160_BIRIJION_FREE_START()
  return BIRIJIONTbl.M02_130_BIRIJION_FREE_START
end
function BIRIJIONTbl.M03_010_BIRIJION_FREE_START()
  return BIRIJIONTbl.M02_160_BIRIJION_FREE_START
end
function BIRIJIONTbl.M03_020_BIRIJION_FREE_START()
  return BIRIJIONTbl.M03_010_BIRIJION_FREE_START
end
function BIRIJIONTbl.M03_045_BIRIJION_FREE_START()
  return BIRIJIONTbl.M03_020_BIRIJION_FREE_START
end
function BIRIJIONTbl.M03_090_BIRIJION_FREE_START()
  return BIRIJIONTbl.M03_045_BIRIJION_FREE_START
end
function BIRIJIONTbl.M03_110_BIRIJION_FREE_START()
  return BIRIJIONTbl.M03_090_BIRIJION_FREE_START
end
function BIRIJIONTbl.M03_130_BIRIJION_FREE_START()
  return BIRIJIONTbl.M03_110_BIRIJION_FREE_START
end
function BIRIJIONTbl.M03_150_BIRIJION_FREE_START()
  return BIRIJIONTbl.M03_130_BIRIJION_FREE_START
end
function BIRIJIONTbl.M04_010_BIRIJION_FREE_START()
  return BIRIJIONTbl.M03_150_BIRIJION_FREE_START
end
function BIRIJIONTbl.M04_020_BIRIJION_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BIRIJION"))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), -1869655612)
  WINDOW:Talk(SymAct("BIRIJION"), -1147010553)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BIRIJION"), result)
end
function BIRIJIONTbl.M04_HANYOU_BIRIJION_FREE_START()
  return BIRIJIONTbl.M04_020_BIRIJION_FREE_START
end
function BIRIJIONTbl.M04_040_BIRIJION_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BIRIJION"))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), -1564921018)
  WINDOW:Talk(SymAct("BIRIJION"), -302471807)
  WINDOW:Talk(SymAct("BIRIJION"), -186411840)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BIRIJION"), result)
end
function BIRIJIONTbl.M04_060_BIRIJION_FREE_START()
  return BIRIJIONTbl.M04_040_BIRIJION_FREE_START
end
function BIRIJIONTbl.M04_070_BIRIJION_FREE_START()
  return BIRIJIONTbl.M04_060_BIRIJION_FREE_START
end
function BIRIJIONTbl.M04_HANYOU_BIRIJION_FREE_START2()
  return BIRIJIONTbl.M04_070_BIRIJION_FREE_START
end
function BIRIJIONTbl.M05_000_BIRIJION_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BIRIJION"))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), -540096765)
  WINDOW:Talk(SymAct("BIRIJION"), -959056318)
  WINDOW:Talk(SymAct("BIRIJION"), 1095625357)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BIRIJION"), result)
end
function BIRIJIONTbl.M05_010_BIRIJION_FREE_START()
  return BIRIJIONTbl.M05_000_BIRIJION_FREE_START
end
function BIRIJIONTbl.M05_020_BIRIJION_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BIRIJION"))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), 1482087372)
  WINDOW:Talk(SymAct("BIRIJION"), 761644971)
  WINDOW:Talk(SymAct("BIRIJION"), 880735978)
  WINDOW:Talk(SymAct("BIRIJION"), 525575465)
  WINDOW:Talk(SymAct("BIRIJION"), 105419880)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BIRIJION"), result)
end
function BIRIJIONTbl.M05_030_BIRIJION_FREE_START()
  return BIRIJIONTbl.M05_020_BIRIJION_FREE_START
end
function BIRIJIONTbl.M06_HANYOU_BIRIJION_FREE_START()
  return BIRIJIONTbl.M05_030_BIRIJION_FREE_START
end
function BIRIJIONTbl.M06_010_BIRIJION_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BIRIJION"))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), 1225327279)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BIRIJION"), result)
end
function BIRIJIONTbl.M06_015_BIRIJION_FREE_START()
  return BIRIJIONTbl.M06_010_BIRIJION_FREE_START
end
function BIRIJIONTbl.M06_020_BIRIJION_FREE_START()
  return BIRIJIONTbl.M06_015_BIRIJION_FREE_START
end
function BIRIJIONTbl.M06_030_BIRIJION_FREE_START()
  return BIRIJIONTbl.M06_020_BIRIJION_FREE_START
end
function BIRIJIONTbl.M06_040_BIRIJION_FREE_START()
  return BIRIJIONTbl.M06_030_BIRIJION_FREE_START
end
function BIRIJIONTbl.M06_060_BIRIJION_FREE_START()
  return BIRIJIONTbl.M06_040_BIRIJION_FREE_START
end
function BIRIJIONTbl.M07_000_BIRIJION_FREE_START()
  return BIRIJIONTbl.M06_060_BIRIJION_FREE_START
end
function BIRIJIONTbl.M07_010_BIRIJION_FREE_START()
  return BIRIJIONTbl.M07_000_BIRIJION_FREE_START
end
function BIRIJIONTbl.M07_020_BIRIJION_FREE_START()
  return BIRIJIONTbl.M07_010_BIRIJION_FREE_START
end
function BIRIJIONTbl.M07_045_BIRIJION_FREE_START()
  return BIRIJIONTbl.M07_020_BIRIJION_FREE_START
end
function BIRIJIONTbl.M07_HANYOU_BIRIJION_FREE_START()
  return BIRIJIONTbl.M07_045_BIRIJION_FREE_START
end
function BIRIJIONTbl.M07_080_BIRIJION_FREE_START()
  return BIRIJIONTbl.M07_HANYOU_BIRIJION_FREE_START
end
function BIRIJIONTbl.M08_010_BIRIJION_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BIRIJION"))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), 1343370222)
  WINDOW:Talk(SymAct("BIRIJION"), 2067750957)
  WINDOW:Talk(SymAct("BIRIJION"), 1646547308)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BIRIJION"), result)
end
function BIRIJIONTbl.M08_HANYOU_BIRIJION_FREE_START()
  return BIRIJIONTbl.M08_010_BIRIJION_FREE_START
end
function BIRIJIONTbl.M08_020_BIRIJION_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BIRIJION"))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), -440644189)
  WINDOW:Talk(SymAct("BIRIJION"), -56132382)
  WINDOW:Talk(SymAct("BIRIJION"), 1070622789)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BIRIJION"), result)
end
function BIRIJIONTbl.M08_040_BIRIJION_FREE_START()
  return BIRIJIONTbl.M08_020_BIRIJION_FREE_START
end
function BIRIJIONTbl.M08_050_BIRIJION_FREE_START()
  return BIRIJIONTbl.M08_040_BIRIJION_FREE_START
end
function BIRIJIONTbl.M08_055_BIRIJION_FREE_START()
  return BIRIJIONTbl.M08_050_BIRIJION_FREE_START
end
function BIRIJIONTbl.M08_070_BIRIJION_FREE_START()
  return BIRIJIONTbl.M08_055_BIRIJION_FREE_START
end
function BIRIJIONTbl.M09_HANYOU_BIRIJION_FREE_START1()
  return BIRIJIONTbl.M08_070_BIRIJION_FREE_START
end
function BIRIJIONTbl.M09_010_BIRIJION_FREE_START()
  return BIRIJIONTbl.M09_HANYOU_BIRIJION_FREE_START1
end
function BIRIJIONTbl.M09_020_BIRIJION_FREE_START()
  return BIRIJIONTbl.M09_010_BIRIJION_FREE_START
end
function BIRIJIONTbl.M09_040_BIRIJION_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BIRIJION"))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), 650860804)
  WINDOW:Talk(SymAct("BIRIJION"), 233179847)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BIRIJION"), result)
end
function BIRIJIONTbl.M09_HANYOU_BIRIJION_FREE_START2()
  return BIRIJIONTbl.M09_040_BIRIJION_FREE_START
end
function BIRIJIONTbl.M09_060_BIRIJION_FREE_START()
  return BIRIJIONTbl.M09_HANYOU_BIRIJION_FREE_START2
end
function BIRIJIONTbl.M09_080_BIRIJION_FREE_START()
  return BIRIJIONTbl.M09_060_BIRIJION_FREE_START
end
function BIRIJIONTbl.M09_100_BIRIJION_FREE_START()
  return BIRIJIONTbl.M09_080_BIRIJION_FREE_START
end
function BIRIJIONTbl.M09_110_BIRIJION_FREE_START()
  return BIRIJIONTbl.M09_100_BIRIJION_FREE_START
end
function BIRIJIONTbl.M09_120_BIRIJION_FREE_START()
  return BIRIJIONTbl.M09_110_BIRIJION_FREE_START
end
function BIRIJIONTbl.M10_010_BIRIJION_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BIRIJION"))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), 352140166)
  WINDOW:Talk(SymAct("BIRIJION"), 1539091777)
  WINDOW:Talk(SymAct("BIRIJION"), 1118280704)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BIRIJION"), result)
end
function BIRIJIONTbl.M10_030_BIRIJION_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BIRIJION"))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), 1770704835)
  WINDOW:Talk(SymAct("BIRIJION"), 1888616066)
  WINDOW:Talk(SymAct("BIRIJION"), -150347187)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BIRIJION"), result)
end
function BIRIJIONTbl.M10_040_BIRIJION_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BIRIJION"))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), -300756212)
  WINDOW:Talk(SymAct("BIRIJION"), -2022961376)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BIRIJION"), result)
end
function BIRIJIONTbl.M10_060_BIRIJION_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BIRIJION"))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), -1636352415)
  WINDOW:Talk(SymAct("BIRIJION"), -1252364894)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BIRIJION"), result)
end
function BIRIJIONTbl.M11_010_BIRIJION_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BIRIJION"))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), -1405002525)
  WINDOW:Talk(SymAct("BIRIJION"), -486487516)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BIRIJION"), result)
end
function BIRIJIONTbl.M11_030_BIRIJION_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BIRIJION"))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), -98829467)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BIRIJION"), result)
end
function BIRIJIONTbl.M11_040_BIRIJION_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BIRIJION"))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), -784947034)
  WINDOW:Talk(SymAct("BIRIJION"), -936535577)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BIRIJION"), result)
end
function BIRIJIONTbl.M11_050_BIRIJION_FREE_START()
  local result = subUsuComFuncTalkInBase02(CH("BIRIJION"))
  WINDOW:DrawFaceF(20, 88, SymAct("BIRIJION"), FACE_TYPE.SPECIAL03)
  WINDOW:Talk(SymAct("BIRIJION"), 1337296168)
  WINDOW:Talk(SymAct("BIRIJION"), 1454290025)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase02(CH("BIRIJION"), result)
end
function BIRIJIONTbl.M11_060_BIRIJION_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BIRIJION"))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), 448477081)
  WINDOW:Talk(SymAct("BIRIJION"), 60819160)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BIRIJION"), result)
end
function BIRIJIONTbl.M11_075_BIRIJION_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BIRIJION"))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), 680351003)
  WINDOW:Talk(SymAct("BIRIJION"), 831939674)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BIRIJION"), result)
end
function BIRIJIONTbl.M11_090_BIRIJION_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BIRIJION"))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), 2128081565)
  WINDOW:Talk(SymAct("BIRIJION"), 1741472732)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BIRIJION"), result)
end

