function BURAKKIITbl.M02_010_BURAKKII_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BURAKKII"))
  WINDOW:SysMsg(-1564726071)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BURAKKII"), result)
end
function BURAKKIITbl.M02_030_BURAKKII_FREE_START()
  return BURAKKIITbl.M02_010_BURAKKII_FREE_START
end
function BURAKKIITbl.M02_050_BURAKKII_FREE_START()
  return BURAKKIITbl.M02_030_BURAKKII_FREE_START
end
function BURAKKIITbl.M02_070_BURAKKII_FREE_START()
  return BURAKKIITbl.M02_050_BURAKKII_FREE_START
end
function BURAKKIITbl.M02_080_BURAKKII_FREE_START()
  return BURAKKIITbl.M02_070_BURAKKII_FREE_START
end
function BURAKKIITbl.M02_090_BURAKKII_FREE_START()
  return BURAKKIITbl.M02_080_BURAKKII_FREE_START
end
function BURAKKIITbl.M02_100_BURAKKII_FREE_START()
  return BURAKKIITbl.M02_090_BURAKKII_FREE_START
end
function BURAKKIITbl.M02_115_BURAKKII_FREE_START()
  return BURAKKIITbl.M02_100_BURAKKII_FREE_START
end
function BURAKKIITbl.M02_130_BURAKKII_FREE_START()
  return BURAKKIITbl.M02_115_BURAKKII_FREE_START
end
function BURAKKIITbl.M02_160_BURAKKII_FREE_START()
  return BURAKKIITbl.M02_130_BURAKKII_FREE_START
end
function BURAKKIITbl.M03_010_BURAKKII_FREE_START()
  return BURAKKIITbl.M02_160_BURAKKII_FREE_START
end
function BURAKKIITbl.M03_020_BURAKKII_FREE_START()
  return BURAKKIITbl.M03_010_BURAKKII_FREE_START
end
function BURAKKIITbl.M03_045_BURAKKII_FREE_START()
  return BURAKKIITbl.M03_020_BURAKKII_FREE_START
end
function BURAKKIITbl.M03_090_BURAKKII_FREE_START()
  return BURAKKIITbl.M03_045_BURAKKII_FREE_START
end
function BURAKKIITbl.M03_110_BURAKKII_FREE_START()
  return BURAKKIITbl.M03_090_BURAKKII_FREE_START
end
function BURAKKIITbl.M03_130_BURAKKII_FREE_START()
  return BURAKKIITbl.M03_110_BURAKKII_FREE_START
end
function BURAKKIITbl.M03_150_BURAKKII_FREE_START()
  return BURAKKIITbl.M03_130_BURAKKII_FREE_START
end
function BURAKKIITbl.M04_010_BURAKKII_FREE_START()
  return BURAKKIITbl.M03_150_BURAKKII_FREE_START
end
function BURAKKIITbl.M04_020_BURAKKII_FREE_START()
  return BURAKKIITbl.M04_010_BURAKKII_FREE_START
end
function BURAKKIITbl.M04_HANYOU_BURAKKII_FREE_START()
  return BURAKKIITbl.M04_020_BURAKKII_FREE_START
end
function BURAKKIITbl.M04_040_BURAKKII_FREE_START()
  return BURAKKIITbl.M04_HANYOU_BURAKKII_FREE_START
end
function BURAKKIITbl.M04_060_BURAKKII_FREE_START()
  return BURAKKIITbl.M04_040_BURAKKII_FREE_START
end
function BURAKKIITbl.M04_070_BURAKKII_FREE_START()
  return BURAKKIITbl.M04_060_BURAKKII_FREE_START
end
function BURAKKIITbl.M04_HANYOU_BURAKKII_FREE_START2()
  return BURAKKIITbl.M04_070_BURAKKII_FREE_START
end
function BURAKKIITbl.M05_000_BURAKKII_FREE_START()
  return BURAKKIITbl.M04_HANYOU_BURAKKII_FREE_START2
end
function BURAKKIITbl.M05_010_BURAKKII_FREE_START()
  return BURAKKIITbl.M05_000_BURAKKII_FREE_START
end
function BURAKKIITbl.M05_020_BURAKKII_FREE_START()
  return BURAKKIITbl.M05_010_BURAKKII_FREE_START
end
function BURAKKIITbl.M05_030_BURAKKII_FREE_START()
  return BURAKKIITbl.M05_020_BURAKKII_FREE_START
end
function BURAKKIITbl.M06_HANYOU_BURAKKII_FREE_START()
  return BURAKKIITbl.M05_030_BURAKKII_FREE_START
end
function BURAKKIITbl.M06_010_BURAKKII_FREE_START()
  return BURAKKIITbl.M06_HANYOU_BURAKKII_FREE_START
end
function BURAKKIITbl.M06_015_BURAKKII_FREE_START()
  return BURAKKIITbl.M06_010_BURAKKII_FREE_START
end
function BURAKKIITbl.M06_020_BURAKKII_FREE_START()
  return BURAKKIITbl.M06_015_BURAKKII_FREE_START
end
function BURAKKIITbl.M06_030_BURAKKII_FREE_START()
  return BURAKKIITbl.M06_020_BURAKKII_FREE_START
end
function BURAKKIITbl.M06_040_BURAKKII_FREE_START()
  return BURAKKIITbl.M06_030_BURAKKII_FREE_START
end
function BURAKKIITbl.M06_060_BURAKKII_FREE_START()
  return BURAKKIITbl.M06_040_BURAKKII_FREE_START
end
function BURAKKIITbl.M07_000_BURAKKII_FREE_START()
  return BURAKKIITbl.M06_060_BURAKKII_FREE_START
end
function BURAKKIITbl.M07_010_BURAKKII_FREE_START()
  return BURAKKIITbl.M07_000_BURAKKII_FREE_START
end
function BURAKKIITbl.M07_020_BURAKKII_FREE_START()
  return BURAKKIITbl.M07_010_BURAKKII_FREE_START
end
function BURAKKIITbl.M07_045_BURAKKII_FREE_START()
  return BURAKKIITbl.M07_020_BURAKKII_FREE_START
end
function BURAKKIITbl.M07_HANYOU_BURAKKII_FREE_START()
  return BURAKKIITbl.M07_045_BURAKKII_FREE_START
end
function BURAKKIITbl.M07_080_BURAKKII_FREE_START()
  return BURAKKIITbl.M07_HANYOU_BURAKKII_FREE_START
end
function BURAKKIITbl.M08_010_BURAKKII_FREE_START()
  local result = subUsuComFuncTalkInBase02(CH("BURAKKII"))
  CH("BURAKKII"):SetShake(Vector(0.005, 0, 0), TimeSec(0.4, TIME_TYPE.FRAME))
  WINDOW:DrawFace(20, 88, SymAct("BURAKKII"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("BURAKKII"), -1146675832)
  CH("BURAKKII"):ResetShake()
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase02(CH("BURAKKII"), result)
end
function BURAKKIITbl.M08_HANYOU_BURAKKII_FREE_START()
  return BURAKKIITbl.M08_010_BURAKKII_FREE_START
end
function BURAKKIITbl.M08_020_BURAKKII_FREE_START()
  local result = subUsuComFuncTalkInBase02(CH("BURAKKII"))
  WINDOW:DrawFace(20, 88, SymAct("BURAKKII"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("BURAKKII"), -1869984181)
  WINDOW:Talk(SymAct("BURAKKII"), -1986953462)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase02(CH("BURAKKII"), result)
end
function BURAKKIITbl.M08_040_BURAKKII_FREE_START()
  return BURAKKIITbl.M08_020_BURAKKII_FREE_START
end
function BURAKKIITbl.M08_050_BURAKKII_FREE_START()
  return BURAKKIITbl.M08_040_BURAKKII_FREE_START
end
function BURAKKIITbl.M08_055_BURAKKII_FREE_START()
  return BURAKKIITbl.M08_050_BURAKKII_FREE_START
end
function BURAKKIITbl.M08_070_BURAKKII_FREE_START()
  return BURAKKIITbl.M08_055_BURAKKII_FREE_START
end
function BURAKKIITbl.M09_HANYOU_BURAKKII_FREE_START1()
  return BURAKKIITbl.M08_070_BURAKKII_FREE_START
end
function BURAKKIITbl.M09_010_BURAKKII_FREE_START()
  return BURAKKIITbl.M09_HANYOU_BURAKKII_FREE_START1
end
function BURAKKIITbl.M09_020_BURAKKII_FREE_START()
  return BURAKKIITbl.M09_010_BURAKKII_FREE_START
end
function BURAKKIITbl.M09_040_BURAKKII_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BURAKKII"))
  WINDOW:DrawFace(20, 88, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BURAKKII"), -959387187)
  WINDOW:Talk(SymAct("BURAKKII"), -540288884)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BURAKKII"), result)
end
function BURAKKIITbl.M09_HANYOU_BURAKKII_FREE_START2()
  return BURAKKIITbl.M09_040_BURAKKII_FREE_START
end
function BURAKKIITbl.M09_060_BURAKKII_FREE_START()
  return BURAKKIITbl.M09_HANYOU_BURAKKII_FREE_START2
end
function BURAKKIITbl.M09_080_BURAKKII_FREE_START()
  return BURAKKIITbl.M09_060_BURAKKII_FREE_START
end
function BURAKKIITbl.M09_100_BURAKKII_FREE_START()
  return BURAKKIITbl.M09_080_BURAKKII_FREE_START
end
function BURAKKIITbl.M09_110_BURAKKII_FREE_START()
  return BURAKKIITbl.M09_100_BURAKKII_FREE_START
end
function BURAKKIITbl.M09_120_BURAKKII_FREE_START()
  return BURAKKIITbl.M09_110_BURAKKII_FREE_START
end
function BURAKKIITbl.M10_010_BURAKKII_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BURAKKII"))
  WINDOW:DrawFace(20, 88, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BURAKKII"), -186217649)
  WINDOW:Talk(SymAct("BURAKKII"), -302138866)
  WINDOW:Talk(SymAct("BURAKKII"), 1785046721)
  WINDOW:Talk(SymAct("BURAKKII"), 1937676160)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BURAKKII"), result)
end
function BURAKKIITbl.M10_030_BURAKKII_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BURAKKII"))
  WINDOW:DrawFace(20, 88, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BURAKKII"), 247718193)
  WINDOW:Talk(SymAct("BURAKKII"), 400085104)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BURAKKII"), result)
end
function BURAKKIITbl.M10_040_BURAKKII_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BURAKKII"))
  WINDOW:DrawFace(20, 88, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BURAKKII"), 1022722995)
  WINDOW:Talk(SymAct("BURAKKII"), 636400370)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BURAKKII"), result)
end
function BURAKKIITbl.M10_060_BURAKKII_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BURAKKII"))
  WINDOW:DrawFace(20, 88, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BURAKKII"), 1789862965)
  WINDOW:Talk(SymAct("BURAKKII"), 1941181812)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BURAKKII"), result)
end
function BURAKKIITbl.M11_010_BURAKKII_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BURAKKII"))
  WINDOW:DrawFace(20, 88, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BURAKKII"), 1486440119)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BURAKKII"), result)
end
function BURAKKIITbl.M11_030_BURAKKII_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BURAKKII"))
  WINDOW:DrawFace(20, 88, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BURAKKII"), 1099069430)
  WINDOW:Talk(SymAct("BURAKKII"), -971347143)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BURAKKII"), result)
end
function BURAKKIITbl.M11_040_BURAKKII_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BURAKKII"))
  WINDOW:DrawFace(20, 88, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BURAKKII"), -553559432)
  WINDOW:Talk(SymAct("BURAKKII"), 477515487)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BURAKKII"), result)
end
function BURAKKIITbl.M11_050_BURAKKII_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BURAKKII"))
  WINDOW:DrawFace(20, 88, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BURAKKII"), 91062174)
  WINDOW:Talk(SymAct("BURAKKII"), 775957597)
  WINDOW:Talk(SymAct("BURAKKII"), 928718108)
  WINDOW:Talk(SymAct("BURAKKII"), 2015005659)
  WINDOW:Talk(SymAct("BURAKKII"), 1627503258)
  WINDOW:Talk(SymAct("BURAKKII"), 1244457305)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BURAKKII"), result)
end
function BURAKKIITbl.M11_060_BURAKKII_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BURAKKII"))
  WINDOW:DrawFace(20, 88, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BURAKKII"), 1396168728)
  WINDOW:Talk(SymAct("BURAKKII"), -726678313)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BURAKKII"), result)
end
function BURAKKIITbl.M11_075_BURAKKII_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BURAKKII"))
  WINDOW:DrawFace(20, 88, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BURAKKII"), -843778666)
  WINDOW:Talk(SymAct("BURAKKII"), -1530254918)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BURAKKII"), result)
end
function BURAKKIITbl.M11_090_BURAKKII_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("BURAKKII"))
  WINDOW:DrawFace(20, 88, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BURAKKII"), -1110370053)
  WINDOW:Talk(SymAct("BURAKKII"), -1761850568)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("BURAKKII"), result)
end

