function CHIRACHIINOTbl.M02_010_CHIRACHIINO_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("CHIRACHIINO"))
  WINDOW:DrawFace(20, 88, SymAct("CHIRACHIINO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("CHIRACHIINO"), -809117157)
  WINDOW:Talk(SymAct("CHIRACHIINO"), -690033830)
  WINDOW:KeyWait()
  CH("CHIRACHIINO"):SetFacialMotion(FACIAL_MOTION.SAD)
  WINDOW:DrawFace(20, 88, SymAct("CHIRACHIINO"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("CHIRACHIINO"), -34359143)
  WINDOW:KeyWait()
  CH("CHIRACHIINO"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  WINDOW:DrawFace(20, 88, SymAct("CHIRACHIINO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("CHIRACHIINO"), -454522408)
  WINDOW:Talk(SymAct("CHIRACHIINO"), -1414979809)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("CHIRACHIINO"), result)
end
function CHIRACHIINOTbl.M02_030_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M02_010_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M02_050_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M02_030_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M02_070_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M02_050_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M02_080_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M02_070_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M02_090_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M02_080_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M02_100_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M02_090_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M02_115_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M02_100_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M02_130_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M02_115_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M02_160_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M02_130_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M03_010_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M02_160_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M03_020_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M03_010_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M03_045_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M03_020_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M03_090_CHIRACHIINO_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("CHIRACHIINO"))
  CH("CHIRACHIINO"):SetFacialMotion(FACIAL_MOTION.SAD)
  WINDOW:DrawFace(20, 88, SymAct("CHIRACHIINO"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("CHIRACHIINO"), -1296945570)
  WINDOW:KeyWait()
  CH("CHIRACHIINO"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  WINDOW:DrawFace(20, 88, SymAct("CHIRACHIINO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("CHIRACHIINO"), -1717600867)
  WINDOW:Talk(SymAct("CHIRACHIINO"), -2138813220)
  WINDOW:Talk(SymAct("CHIRACHIINO"), 119296019)
  WINDOW:KeyWait()
  CH("CHIRACHIINO"):SetManpu("MP_LAUGH_LP")
  CH("CHIRACHIINO"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(20, 88, SymAct("CHIRACHIINO"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("CHIRACHIINO"), 503800146)
  WINDOW:Talk(SymAct("CHIRACHIINO"), -384598788)
  WINDOW:CloseMessage()
  CH("CHIRACHIINO"):ResetManpu()
  CH("CHIRACHIINO"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  subUsuComFuncTalkOutBase01(CH("CHIRACHIINO"), result)
end
function CHIRACHIINOTbl.M03_110_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M03_090_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M03_130_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M03_110_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M03_150_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M03_130_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M04_010_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M03_150_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M04_020_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M04_010_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M04_HANYOU_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M04_020_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M04_040_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M04_HANYOU_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M04_060_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M04_040_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M04_070_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M04_060_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M04_HANYOU_CHIRACHIINO_FREE_START2()
  return CHIRACHIINOTbl.M04_070_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M05_000_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M04_HANYOU_CHIRACHIINO_FREE_START2
end
function CHIRACHIINOTbl.M05_010_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M05_000_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M05_020_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M05_010_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M05_030_CHIRACHIINO_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("CHIRACHIINO"))
  if FLAG.ChirachiinoCounter == CONST.CNT_1 then
    WINDOW:DrawFace(20, 88, SymAct("CHIRACHIINO"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("CHIRACHIINO"), -267891267)
    WINDOW:Talk(SymAct("CHIRACHIINO"), -618324354)
    WINDOW:CloseMessage()
    FLAG.ChirachiinoCounter = CONST.CNT_2
  end
  OpenGiftShopMenu()
  subUsuComFuncTalkOutBase01(CH("CHIRACHIINO"), result)
end
function CHIRACHIINOTbl.M06_HANYOU_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M05_030_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M06_010_CHIRACHIINO_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("CHIRACHIINO"))
  if FLAG.ChirachiinoCounter == CONST.CNT_1 then
    WINDOW:DrawFace(20, 88, SymAct("CHIRACHIINO"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("CHIRACHIINO"), -1036112065)
    WINDOW:Talk(SymAct("CHIRACHIINO"), -1921009160)
    WINDOW:Talk(SymAct("CHIRACHIINO"), -1805350727)
    WINDOW:Talk(SymAct("CHIRACHIINO"), -1085678726)
    WINDOW:Talk(SymAct("CHIRACHIINO"), -1504515525)
    WINDOW:CloseMessage()
    FLAG.ChirachiinoCounter = CONST.CNT_2
  end
  OpenGiftShopMenu()
  subUsuComFuncTalkOutBase01(CH("CHIRACHIINO"), result)
end
function CHIRACHIINOTbl.M06_015_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M06_010_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M06_015_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M06_010_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M06_020_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M06_015_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M06_030_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M06_020_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M06_040_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M06_030_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M06_060_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M06_040_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M07_000_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M06_060_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M07_010_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M07_000_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M07_020_CHIRACHIINO_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("CHIRACHIINO"))
  if FLAG.ChirachiinoCounter == CONST.CNT_1 then
    CH("CHIRACHIINO"):SetFacialMotion(FACIAL_MOTION.SAD)
    WINDOW:DrawFace(20, 88, SymAct("CHIRACHIINO"), FACE_TYPE.SAD)
    WINDOW:Talk(SymAct("CHIRACHIINO"), 566949620)
    WINDOW:Talk(SymAct("CHIRACHIINO"), 953272245)
    WINDOW:KeyWait()
    CH("CHIRACHIINO"):SetFacialMotion(FACIAL_MOTION.HAPPY)
    WINDOW:DrawFace(20, 88, SymAct("CHIRACHIINO"), FACE_TYPE.HAPPY)
    WINDOW:Talk(SymAct("CHIRACHIINO"), -72953070)
    WINDOW:CloseMessage()
    CH("CHIRACHIINO"):SetFacialMotion(FACIAL_MOTION.NORMAL)
    FLAG.ChirachiinoCounter = CONST.CNT_2
  end
  OpenGiftShopMenu()
  subUsuComFuncTalkOutBase01(CH("CHIRACHIINO"), result)
end
function CHIRACHIINOTbl.M07_045_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M07_020_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M07_HANYOU_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M07_045_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M07_080_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M07_HANYOU_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M08_010_CHIRACHIINO_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("CHIRACHIINO"))
  if FLAG.ChirachiinoCounter == CONST.CNT_1 then
    WINDOW:DrawFace(20, 88, SymAct("CHIRACHIINO"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("CHIRACHIINO"), -490872237)
    WINDOW:KeyWait()
    CH("CHIRACHIINO"):SetFacialMotion(FACIAL_MOTION.HAPPY)
    WINDOW:DrawFace(20, 88, SymAct("CHIRACHIINO"), FACE_TYPE.HAPPY)
    WINDOW:Talk(SymAct("CHIRACHIINO"), -913264240)
    WINDOW:CloseMessage()
    CH("CHIRACHIINO"):SetFacialMotion(FACIAL_MOTION.NORMAL)
    FLAG.ChirachiinoCounter = CONST.CNT_2
  end
  OpenGiftShopMenu()
  subUsuComFuncTalkOutBase01(CH("CHIRACHIINO"), result)
end
function CHIRACHIINOTbl.M08_HANYOU_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M08_010_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M08_020_CHIRACHIINO_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("CHIRACHIINO"))
  OpenGiftShopMenu()
  subUsuComFuncTalkOutBase01(CH("CHIRACHIINO"), result)
end
function CHIRACHIINOTbl.M08_040_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M08_020_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M08_050_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M08_040_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M08_055_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M08_050_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M08_070_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M08_055_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M09_HANYOU_CHIRACHIINO_FREE_START1()
  return CHIRACHIINOTbl.M08_070_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M09_010_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M09_HANYOU_CHIRACHIINO_FREE_START1
end
function CHIRACHIINOTbl.M09_020_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M09_010_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M09_040_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M09_020_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M09_HANYOU_CHIRACHIINO_FREE_START2()
  return CHIRACHIINOTbl.M09_040_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M09_060_CHIRACHIINO_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("CHIRACHIINO"))
  if FLAG.ChirachiinoCounter == CONST.CNT_1 then
    WINDOW:DrawFace(20, 88, SymAct("CHIRACHIINO"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("CHIRACHIINO"), -796163887)
    WINDOW:KeyWait()
    CH("CHIRACHIINO"):SetFacialMotion(FACIAL_MOTION.HAPPY)
    WINDOW:DrawFace(20, 88, SymAct("CHIRACHIINO"), FACE_TYPE.HAPPY)
    WINDOW:Talk(SymAct("CHIRACHIINO"), -1614146026)
    WINDOW:CloseMessage()
    CH("CHIRACHIINO"):SetFacialMotion(FACIAL_MOTION.NORMAL)
    FLAG.ChirachiinoCounter = CONST.CNT_2
  end
  OpenGiftShopMenu()
  subUsuComFuncTalkOutBase01(CH("CHIRACHIINO"), result)
end
function CHIRACHIINOTbl.M09_080_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M09_060_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M09_100_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M09_080_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M09_110_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M09_100_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M09_120_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M09_110_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M10_010_CHIRACHIINO_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("CHIRACHIINO"))
  OpenGiftShopMenu()
  subUsuComFuncTalkOutBase01(CH("CHIRACHIINO"), result)
end
function CHIRACHIINOTbl.M10_030_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M10_010_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M10_040_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M10_030_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M10_060_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M10_040_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M11_010_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M10_060_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M11_030_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M11_010_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M11_040_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M11_030_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M11_050_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M11_040_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M11_060_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M11_050_CHIRACHIINO_FREE_START
end
function CHIRACHIINOTbl.M11_090_CHIRACHIINO_FREE_START()
  return CHIRACHIINOTbl.M11_060_CHIRACHIINO_FREE_START
end

