function CHONCHIITbl.M02_010_CHONCHII_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("CHONCHII"))
  WINDOW:SysMsg(-720089369)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("CHONCHII"), result)
end
function CHONCHIITbl.M02_030_CHONCHII_FREE_START()
  return CHONCHIITbl.M02_010_CHONCHII_FREE_START
end
function CHONCHIITbl.M02_050_CHONCHII_FREE_START()
  return CHONCHIITbl.M02_030_CHONCHII_FREE_START
end
function CHONCHIITbl.M02_070_CHONCHII_FREE_START()
  return CHONCHIITbl.M02_050_CHONCHII_FREE_START
end
function CHONCHIITbl.M02_080_CHONCHII_FREE_START()
  return CHONCHIITbl.M02_070_CHONCHII_FREE_START
end
function CHONCHIITbl.M02_090_CHONCHII_FREE_START()
  return CHONCHIITbl.M02_080_CHONCHII_FREE_START
end
function CHONCHIITbl.M02_100_CHONCHII_FREE_START()
  return CHONCHIITbl.M02_090_CHONCHII_FREE_START
end
function CHONCHIITbl.M02_115_CHONCHII_FREE_START()
  return CHONCHIITbl.M02_100_CHONCHII_FREE_START
end
function CHONCHIITbl.M02_130_CHONCHII_FREE_START()
  return CHONCHIITbl.M02_115_CHONCHII_FREE_START
end
function CHONCHIITbl.M02_160_CHONCHII_FREE_START()
  return CHONCHIITbl.M02_130_CHONCHII_FREE_START
end
function CHONCHIITbl.M03_010_CHONCHII_FREE_START()
  return CHONCHIITbl.M02_160_CHONCHII_FREE_START
end
function CHONCHIITbl.M03_020_CHONCHII_FREE_START()
  return CHONCHIITbl.M03_010_CHONCHII_FREE_START
end
function CHONCHIITbl.M03_045_CHONCHII_FREE_START()
  return CHONCHIITbl.M03_020_CHONCHII_FREE_START
end
function CHONCHIITbl.M03_090_CHONCHII_FREE_START()
  return CHONCHIITbl.M03_045_CHONCHII_FREE_START
end
function CHONCHIITbl.M03_110_CHONCHII_FREE_START()
  return CHONCHIITbl.M03_090_CHONCHII_FREE_START
end
function CHONCHIITbl.M03_130_CHONCHII_FREE_START()
  return CHONCHIITbl.M03_110_CHONCHII_FREE_START
end
function CHONCHIITbl.M03_150_CHONCHII_FREE_START()
  return CHONCHIITbl.M03_130_CHONCHII_FREE_START
end
function CHONCHIITbl.M04_010_CHONCHII_FREE_START()
  return CHONCHIITbl.M03_150_CHONCHII_FREE_START
end
function CHONCHIITbl.M04_020_CHONCHII_FREE_START()
  return CHONCHIITbl.M04_010_CHONCHII_FREE_START
end
function CHONCHIITbl.M04_HANYOU_CHONCHII_FREE_START()
  return CHONCHIITbl.M04_020_CHONCHII_FREE_START
end
function CHONCHIITbl.M04_040_CHONCHII_FREE_START()
  return CHONCHIITbl.M04_HANYOU_CHONCHII_FREE_START
end
function CHONCHIITbl.M04_060_CHONCHII_FREE_START()
  return CHONCHIITbl.M04_040_CHONCHII_FREE_START
end
function CHONCHIITbl.M04_070_CHONCHII_FREE_START()
  return CHONCHIITbl.M04_060_CHONCHII_FREE_START
end
function CHONCHIITbl.M04_HANYOU_CHONCHII_FREE_START2()
  return CHONCHIITbl.M04_070_CHONCHII_FREE_START
end
function CHONCHIITbl.M05_000_CHONCHII_FREE_START()
  return CHONCHIITbl.M04_HANYOU_CHONCHII_FREE_START2
end
function CHONCHIITbl.M05_010_CHONCHII_FREE_START()
  return CHONCHIITbl.M05_000_CHONCHII_FREE_START
end
function CHONCHIITbl.M05_020_CHONCHII_FREE_START()
  return CHONCHIITbl.M05_010_CHONCHII_FREE_START
end
function CHONCHIITbl.M05_030_CHONCHII_FREE_START()
  return CHONCHIITbl.M05_020_CHONCHII_FREE_START
end
function CHONCHIITbl.M06_HANYOU_CHONCHII_FREE_START()
  return CHONCHIITbl.M05_030_CHONCHII_FREE_START
end
function CHONCHIITbl.M06_010_CHONCHII_FREE_START()
  return CHONCHIITbl.M06_HANYOU_CHONCHII_FREE_START
end
function CHONCHIITbl.M06_015_CHONCHII_FREE_START()
  return CHONCHIITbl.M06_010_CHONCHII_FREE_START
end
function CHONCHIITbl.M06_020_CHONCHII_FREE_START()
  return CHONCHIITbl.M06_015_CHONCHII_FREE_START
end
function CHONCHIITbl.M06_030_CHONCHII_FREE_START()
  return CHONCHIITbl.M06_020_CHONCHII_FREE_START
end
function CHONCHIITbl.M06_040_CHONCHII_FREE_START()
  return CHONCHIITbl.M06_030_CHONCHII_FREE_START
end
function CHONCHIITbl.M06_060_CHONCHII_FREE_START()
  return CHONCHIITbl.M06_040_CHONCHII_FREE_START
end
function CHONCHIITbl.M07_000_CHONCHII_FREE_START()
  return CHONCHIITbl.M06_060_CHONCHII_FREE_START
end
function CHONCHIITbl.M07_010_CHONCHII_FREE_START()
  return CHONCHIITbl.M07_000_CHONCHII_FREE_START
end
function CHONCHIITbl.M07_020_CHONCHII_FREE_START()
  return CHONCHIITbl.M07_010_CHONCHII_FREE_START
end
function CHONCHIITbl.M07_045_CHONCHII_FREE_START()
  return CHONCHIITbl.M07_020_CHONCHII_FREE_START
end
function CHONCHIITbl.M07_HANYOU_CHONCHII_FREE_START()
  return CHONCHIITbl.M07_045_CHONCHII_FREE_START
end
function CHONCHIITbl.M07_080_CHONCHII_FREE_START()
  return CHONCHIITbl.M07_HANYOU_CHONCHII_FREE_START
end
function CHONCHIITbl.M08_010_CHONCHII_FREE_START()
  return CHONCHIITbl.M07_080_CHONCHII_FREE_START
end
function CHONCHIITbl.M08_HANYOU_CHONCHII_FREE_START()
  return CHONCHIITbl.M08_010_CHONCHII_FREE_START
end
function CHONCHIITbl.M08_020_CHONCHII_FREE_START()
  return CHONCHIITbl.M08_HANYOU_CHONCHII_FREE_START
end
function CHONCHIITbl.M08_040_CHONCHII_FREE_START()
  return CHONCHIITbl.M08_020_CHONCHII_FREE_START
end
function CHONCHIITbl.M08_050_CHONCHII_FREE_START()
  return CHONCHIITbl.M08_040_CHONCHII_FREE_START
end
function CHONCHIITbl.M08_055_CHONCHII_FREE_START()
  return CHONCHIITbl.M08_050_CHONCHII_FREE_START
end
function CHONCHIITbl.M08_070_CHONCHII_FREE_START()
  return CHONCHIITbl.M08_055_CHONCHII_FREE_START
end
function CHONCHIITbl.M09_HANYOU_CHONCHII_FREE_START1()
  return CHONCHIITbl.M08_070_CHONCHII_FREE_START
end
function CHONCHIITbl.M09_010_CHONCHII_FREE_START()
  return CHONCHIITbl.M09_HANYOU_CHONCHII_FREE_START1
end
function CHONCHIITbl.M09_020_CHONCHII_FREE_START()
  return CHONCHIITbl.M09_010_CHONCHII_FREE_START
end
function CHONCHIITbl.M09_040_CHONCHII_FREE_START()
  return CHONCHIITbl.M09_020_CHONCHII_FREE_START
end
function CHONCHIITbl.M09_HANYOU_CHONCHII_FREE_START2()
  return CHONCHIITbl.M09_040_CHONCHII_FREE_START
end
function CHONCHIITbl.M09_060_CHONCHII_FREE_START()
  return CHONCHIITbl.M09_HANYOU_CHONCHII_FREE_START2
end
function CHONCHIITbl.M09_080_CHONCHII_FREE_START()
  return CHONCHIITbl.M09_060_CHONCHII_FREE_START
end
function CHONCHIITbl.M09_100_CHONCHII_FREE_START()
  return CHONCHIITbl.M09_080_CHONCHII_FREE_START
end
function CHONCHIITbl.M09_110_CHONCHII_FREE_START()
  return CHONCHIITbl.M09_100_CHONCHII_FREE_START
end
function CHONCHIITbl.M09_120_CHONCHII_FREE_START()
  return CHONCHIITbl.M09_110_CHONCHII_FREE_START
end
function CHONCHIITbl.M10_010_CHONCHII_FREE_START()
  return CHONCHIITbl.M09_120_CHONCHII_FREE_START
end
function CHONCHIITbl.M10_030_CHONCHII_FREE_START()
  return CHONCHIITbl.M10_010_CHONCHII_FREE_START
end
function CHONCHIITbl.M10_040_CHONCHII_FREE_START()
  return CHONCHIITbl.M10_030_CHONCHII_FREE_START
end
function CHONCHIITbl.M10_060_CHONCHII_FREE_START()
  return CHONCHIITbl.M10_040_CHONCHII_FREE_START
end
function CHONCHIITbl.M11_010_CHONCHII_FREE_START()
  return CHONCHIITbl.M10_060_CHONCHII_FREE_START
end
function CHONCHIITbl.M11_030_CHONCHII_FREE_START()
  return CHONCHIITbl.M11_010_CHONCHII_FREE_START
end
function CHONCHIITbl.M11_040_CHONCHII_FREE_START()
  return CHONCHIITbl.M11_030_CHONCHII_FREE_START
end
function CHONCHIITbl.M11_050_CHONCHII_FREE_START()
  return CHONCHIITbl.M11_040_CHONCHII_FREE_START
end
function CHONCHIITbl.M11_060_CHONCHII_FREE_START()
  return CHONCHIITbl.M11_050_CHONCHII_FREE_START
end
function CHONCHIITbl.M11_090_CHONCHII_FREE_START()
  return CHONCHIITbl.M11_060_CHONCHII_FREE_START
end

