function DANGOROTbl.M12_010_DANGORO_FREE_START()
  return DANGOROTbl.M11_090_DANGORO_FREE_START
end
function DANGOROTbl.M12_020_DANGORO_FREE_START()
  local result = subUsuComFuncTalkInBase02(CH("DANGORO"))
  SOUND:PlaySe(SymSnd("SE_EVT_ZZZ"), Volume(256))
  CH("DANGORO"):SetManpu("MP_SLEEP_LP")
  WINDOW:Talk(SymAct("DANGORO"), 228214363)
  WINDOW:Talk(SymAct("DANGORO"), 344028954)
  WINDOW:Talk(SymAct("DANGORO"), 1068246233)
  WINDOW:CloseMessage()
  CH("DANGORO"):ResetManpu()
  SOUND:FadeOutSe(SymSnd("SE_EVT_ZZZ"), TimeSec(0.2))
  subUsuComFuncTalkOutBase02(CH("DANGORO"), result)
end
function DANGOROTbl.M12_030_DANGORO_FREE_START()
  return DANGOROTbl.M12_020_DANGORO_FREE_START
end
function DANGOROTbl.M12_040_DANGORO_FREE_START()
  return DANGOROTbl.M12_030_DANGORO_FREE_START
end
function DANGOROTbl.M12_050_DANGORO_FREE_START()
  return DANGOROTbl.M12_040_DANGORO_FREE_START
end
function DANGOROTbl.M12_070_DANGORO_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("DANGORO"))
  WINDOW:DrawFace(20, 88, SymAct("DANGORO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DANGORO"), 649532824)
  WINDOW:Talk(SymAct("DANGORO"), 1777763167)
  WINDOW:Talk(SymAct("DANGORO"), 1894625822)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("DANGORO"), result)
end
function DANGOROTbl.M13_010_DANGORO_FREE_START()
  return DANGOROTbl.M12_070_DANGORO_FREE_START
end
function DANGOROTbl.M13_030_DANGORO_FREE_START()
  return DANGOROTbl.M13_010_DANGORO_FREE_START
end
function DANGOROTbl.M13_040_DANGORO_FREE_START()
  return DANGOROTbl.M13_030_DANGORO_FREE_START
end
function DANGOROTbl.M13_060_DANGORO_FREE_START()
  return DANGOROTbl.M13_040_DANGORO_FREE_START
end
function DANGOROTbl.M13_070_DANGORO_FREE_START()
  return DANGOROTbl.M13_060_DANGORO_FREE_START
end
function DANGOROTbl.M13_080_DANGORO_FREE_START()
  return DANGOROTbl.M13_070_DANGORO_FREE_START
end
function DANGOROTbl.M13_090_DANGORO_FREE_START()
  return DANGOROTbl.M13_080_DANGORO_FREE_START
end
function DANGOROTbl.M13_095_DANGORO_FREE_START()
  return DANGOROTbl.M13_090_DANGORO_FREE_START
end
function DANGOROTbl.M13_110_DANGORO_FREE_START()
  return DANGOROTbl.M13_095_DANGORO_FREE_START
end
function DANGOROTbl.M14_010_DANGORO_FREE_START()
  return DANGOROTbl.M13_110_DANGORO_FREE_START
end
function DANGOROTbl.M14_030_DANGORO_FREE_START()
  return DANGOROTbl.M14_010_DANGORO_FREE_START
end
function DANGOROTbl.M14_040_DANGORO_FREE_START()
  return DANGOROTbl.M14_030_DANGORO_FREE_START
end
function DANGOROTbl.M14_060_DANGORO_FREE_START()
  return DANGOROTbl.M14_040_DANGORO_FREE_START
end
function DANGOROTbl.M14_070_DANGORO_FREE_START()
  return DANGOROTbl.M14_060_DANGORO_FREE_START
end
function DANGOROTbl.M14_090_DANGORO_FREE_START()
  return DANGOROTbl.M14_070_DANGORO_FREE_START
end
function DANGOROTbl.M15_010_DANGORO_FREE_START()
  return DANGOROTbl.M14_090_DANGORO_FREE_START
end
function DANGOROTbl.M15_020_DANGORO_FREE_START()
  return DANGOROTbl.M15_010_DANGORO_FREE_START
end
function DANGOROTbl.M15_030_DANGORO_FREE_START()
  return DANGOROTbl.M15_020_DANGORO_FREE_START
end
function DANGOROTbl.M16_010_DANGORO_FREE_START()
  return DANGOROTbl.M15_030_DANGORO_FREE_START
end
function DANGOROTbl.M16_040_DANGORO_FREE_START()
  return DANGOROTbl.M16_010_DANGORO_FREE_START
end
function DANGOROTbl.M16_080_DANGORO_FREE_START()
  return DANGOROTbl.M16_040_DANGORO_FREE_START
end
function DANGOROTbl.M16_090_DANGORO_FREE_START()
  return DANGOROTbl.M16_080_DANGORO_FREE_START
end
function DANGOROTbl.M16_100_DANGORO_FREE_START()
  return DANGOROTbl.M16_090_DANGORO_FREE_START
end
function DANGOROTbl.M16_105_DANGORO_FREE_START()
  return DANGOROTbl.M16_100_DANGORO_FREE_START
end
function DANGOROTbl.M16_120_DANGORO_FREE_START()
  return DANGOROTbl.M16_105_DANGORO_FREE_START
end
function DANGOROTbl.M17_020_DANGORO_FREE_START()
  return DANGOROTbl.M16_120_DANGORO_FREE_START
end
function DANGOROTbl.M17_040_DANGORO_FREE_START()
  return DANGOROTbl.M17_020_DANGORO_FREE_START
end
function DANGOROTbl.M17_060_DANGORO_FREE_START()
  return DANGOROTbl.M17_040_DANGORO_FREE_START
end
function DANGOROTbl.M17_065_DANGORO_FREE_START()
  return DANGOROTbl.M17_060_DANGORO_FREE_START
end
function DANGOROTbl.M17_090_DANGORO_FREE_START()
  return DANGOROTbl.M17_065_DANGORO_FREE_START
end
function DANGOROTbl.M17_120_DANGORO_FREE_START()
  return DANGOROTbl.M17_090_DANGORO_FREE_START
end
function DANGOROTbl.M17_140_DANGORO_FREE_START()
  return DANGOROTbl.M17_120_DANGORO_FREE_START
end
function DANGOROTbl.M17_150_DANGORO_FREE_START()
  return DANGOROTbl.M17_140_DANGORO_FREE_START
end
function DANGOROTbl.M17_155_DANGORO_FREE_START()
  return DANGOROTbl.M17_150_DANGORO_FREE_START
end
function DANGOROTbl.M17_170_DANGORO_FREE_START()
  return DANGOROTbl.M17_155_DANGORO_FREE_START
end
function DANGOROTbl.M17_200_DANGORO_FREE_START()
  return DANGOROTbl.M17_170_DANGORO_FREE_START
end
function DANGOROTbl.M17_210_DANGORO_FREE_START()
  return DANGOROTbl.M17_200_DANGORO_FREE_START
end
function DANGOROTbl.M17_220_DANGORO_FREE_START()
  return DANGOROTbl.M17_210_DANGORO_FREE_START
end
function DANGOROTbl.M17_225_DANGORO_FREE_START()
  return DANGOROTbl.M17_220_DANGORO_FREE_START
end
function DANGOROTbl.M17_240_DANGORO_FREE_START()
  return DANGOROTbl.M17_225_DANGORO_FREE_START
end
function DANGOROTbl.M18_020_DANGORO_FREE_START()
  return DANGOROTbl.M17_240_DANGORO_FREE_START
end
function DANGOROTbl.M18_030_DANGORO_FREE_START()
  return DANGOROTbl.M18_020_DANGORO_FREE_START
end
function DANGOROTbl.S01_010_DANGORO_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("DANGORO"))
  WINDOW:DrawFace(20, 88, SymAct("DANGORO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DANGORO"), 1539367389)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("DANGORO"), result)
end
function DANGOROTbl.S01_020_DANGORO_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("DANGORO"))
  WINDOW:DrawFace(20, 88, SymAct("DANGORO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DANGORO"), 1121702044)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("DANGORO"), result)
end
function DANGOROTbl.S01_030_DANGORO_FREE_START()
  return DANGOROTbl.S01_020_DANGORO_FREE_START
end
function DANGOROTbl.S01_040_DANGORO_FREE_START()
  return DANGOROTbl.S01_030_DANGORO_FREE_START
end
function DANGOROTbl.S01_050_DANGORO_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("DANGORO"))
  WINDOW:DrawFace(20, 88, SymAct("DANGORO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DANGORO"), -985412525)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("DANGORO"), result)
end
function DANGOROTbl.S01_060_DANGORO_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("DANGORO"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("DANGORO"):SetManpu("MP_EXCLAMATION")
  CH("DANGORO"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("DANGORO"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("DANGORO"), -598147822)
  WINDOW:Talk(SymAct("DANGORO"), -523030839)
  WINDOW:KeyWait()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("DANGORO"):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFace(20, 88, SymAct("DANGORO"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("DANGORO"), -104325240)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("DANGORO"), result)
end
function DANGOROTbl.S01_080_DANGORO_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("DANGORO"))
  if FLAG.DangoroCounter == CONST.CNT_1 then
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
    CH("DANGORO"):SetManpu("MP_EXCLAMATION")
    CH("DANGORO"):WaitManpu()
    WINDOW:DrawFace(20, 88, SymAct("DANGORO"), FACE_TYPE.SURPRISE)
    WINDOW:Talk(SymAct("DANGORO"), -756724661)
    WINDOW:Talk(SymAct("DANGORO"), -872514294)
    WINDOW:KeyWait()
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
    CH("DANGORO"):SetManpu("MP_FLY_SWEAT")
    WINDOW:DrawFace(20, 88, SymAct("DANGORO"), FACE_TYPE.TEARS)
    WINDOW:Talk(SymAct("DANGORO"), -2067797043)
    WINDOW:CloseMessage()
    FLAG.DangoroCounter = CONST.CNT_2
  else
    WINDOW:DrawFace(20, 88, SymAct("DANGORO"), FACE_TYPE.TEARS)
    WINDOW:Talk(SymAct("DANGORO"), -1650140532)
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
    CH("DANGORO"):SetManpu("MP_FLY_SWEAT")
    WINDOW:CloseMessage()
  end
  subUsuComFuncTalkOutBase01(CH("DANGORO"), result)
end
function DANGOROTbl.ALL_CLEAR_DANGORO_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("DANGORO"))
  WINDOW:DrawFace(20, 88, SymAct("DANGORO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DANGORO"), -1232500401)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("DANGORO"), result)
end

