function DOTEKKOTSUTbl.M12_010_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.M11_090_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.M12_020_DOTEKKOTSU_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("DOTEKKOTSU"))
  if FLAG.DotekkotsuCounter == CONST.CNT_1 then
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
    CH("DOTEKKOTSU"):SetManpu("MP_FLY_SWEAT")
    WINDOW:DrawFace(20, 88, SymAct("DOTEKKOTSU"), FACE_TYPE.PAIN)
    WINDOW:Talk(SymAct("DOTEKKOTSU"), -1004832970)
    WINDOW:Talk(SymAct("DOTEKKOTSU"), -587184521)
    WINDOW:Talk(SymAct("DOTEKKOTSU"), -164817484)
    WINDOW:Talk(SymAct("DOTEKKOTSU"), -281664267)
    WINDOW:Talk(SymAct("DOTEKKOTSU"), -1602768334)
    WINDOW:Talk(SymAct("DOTEKKOTSU"), -1184070797)
    WINDOW:CloseMessage()
    FLAG.DotekkotsuCounter = CONST.CNT_2
  end
  OpenCarpenterShopMenu()
  subUsuComFuncTalkOutBase01(CH("DOTEKKOTSU"), result)
end
function DOTEKKOTSUTbl.M12_030_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.M12_020_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.M12_040_DOTEKKOTSU_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("DOTEKKOTSU"))
  if FLAG.DotekkotsuCounter == CONST.CNT_1 then
    WINDOW:DrawFace(20, 88, SymAct("DOTEKKOTSU"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("DOTEKKOTSU"), -1841180496)
    WINDOW:CloseMessage()
    FLAG.DotekkotsuCounter = CONST.CNT_2
  end
  OpenCarpenterShopMenu()
  subUsuComFuncTalkOutBase01(CH("DOTEKKOTSU"), result)
end
function DOTEKKOTSUTbl.M12_050_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.M12_040_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.M12_070_DOTEKKOTSU_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("DOTEKKOTSU"))
  if FLAG.DotekkotsuCounter == CONST.CNT_1 then
    WINDOW:DrawFace(20, 88, SymAct("DOTEKKOTSU"), FACE_TYPE.SPECIAL04)
    WINDOW:Talk(SymAct("DOTEKKOTSU"), -1956978191)
    WINDOW:Talk(SymAct("DOTEKKOTSU"), 214105406)
    WINDOW:KeyWait()
    CH("DOTEKKOTSU"):SetManpu("MP_LAUGH_LP")
    CH("DOTEKKOTSU"):SetEyeMotion(EYE_MOTION.HAPPY)
    CH("DOTEKKOTSU"):SetMotion(SymMot("EV002_DAMAGESTAND02"), LOOP.OFF)
    CH("DOTEKKOTSU"):SetNextMotion(SymMot("EV002_DAMAGESTAND02LOOP"), LOOP.ON, TimeSec(0))
    WINDOW:DrawFace(20, 88, SymAct("DOTEKKOTSU"), FACE_TYPE.GLADNESS)
    WINDOW:Talk(SymAct("DOTEKKOTSU"), 366595199)
    WINDOW:CloseMessage()
    CH("DOTEKKOTSU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    CH("DOTEKKOTSU"):SetEyeMotion(EYE_MOTION.NORMAL)
    CH("DOTEKKOTSU"):ResetManpu()
    FLAG.DotekkotsuCounter = CONST.CNT_2
  end
  OpenCarpenterShopMenu()
  subUsuComFuncTalkOutBase01(CH("DOTEKKOTSU"), result)
end
function DOTEKKOTSUTbl.M13_010_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.M12_070_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.M13_030_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.M13_010_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.M13_040_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.M13_030_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.M13_060_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.M13_040_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.M13_070_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.M13_060_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.M13_080_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.M13_070_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.M13_090_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.M13_080_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.M13_095_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.M13_090_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.M13_110_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.M13_095_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.M14_010_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.M13_110_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.M14_030_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.M14_010_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.M14_040_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.M14_030_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.M14_060_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.M14_040_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.M14_070_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.M14_060_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.M14_090_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.M14_070_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.M15_010_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.M14_090_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.M15_020_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.M15_010_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.M15_030_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.M15_020_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.M16_010_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.M15_030_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.M16_040_DOTEKKOTSU_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("DOTEKKOTSU"))
  if FLAG.DotekkotsuCounter == CONST.CNT_1 then
    CH("DOTEKKOTSU"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
    WINDOW:DrawFace(20, 88, SymAct("DOTEKKOTSU"), FACE_TYPE.TEARS)
    WINDOW:Talk(SymAct("DOTEKKOTSU"), 1633612440)
    WINDOW:Talk(SymAct("DOTEKKOTSU"), 2017838041)
    WINDOW:Talk(SymAct("DOTEKKOTSU"), 1399361562)
    WINDOW:CloseMessage()
    CH("DOTEKKOTSU"):SetFacialMotion(FACIAL_MOTION.NORMAL)
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
    CH("DOTEKKOTSU"):SetManpu("MP_FLY_SWEAT")
    CH("DOTEKKOTSU"):WaitManpu()
    WINDOW:DrawFace(20, 88, SymAct("DOTEKKOTSU"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("DOTEKKOTSU"), 1249091931)
    WINDOW:Talk(SymAct("DOTEKKOTSU"), 87177116)
    WINDOW:CloseMessage()
    FLAG.DotekkotsuCounter = CONST.CNT_2
  end
  OpenCarpenterShopMenu()
  subUsuComFuncTalkOutBase01(CH("DOTEKKOTSU"), result)
end
function DOTEKKOTSUTbl.M16_080_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.M16_040_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.M16_090_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.M16_080_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.M16_100_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.M16_090_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.M16_105_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.M16_100_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.M16_120_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.M16_105_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.M17_020_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.M16_120_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.M17_040_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.M17_020_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.M17_060_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.M17_040_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.M17_065_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.M17_060_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.M17_090_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.M17_065_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.M17_120_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.M17_090_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.M17_140_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.M17_120_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.M17_150_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.M17_140_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.M17_155_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.M17_150_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.M17_170_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.M17_155_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.M17_200_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.M17_170_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.M17_210_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.M17_200_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.M17_220_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.M17_210_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.M17_225_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.M17_220_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.M17_240_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.M17_225_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.M18_020_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.M17_240_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.M18_030_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.M18_020_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.S01_010_DOTEKKOTSU_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("DOTEKKOTSU"))
  if FLAG.DotekkotsuCounter == CONST.CNT_1 then
    WINDOW:DrawFace(20, 88, SymAct("DOTEKKOTSU"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("DOTEKKOTSU"), 472450781)
    WINDOW:Talk(SymAct("DOTEKKOTSU"), 923030814)
    WINDOW:CloseMessage()
    FLAG.DotekkotsuCounter = CONST.CNT_2
  end
  OpenCarpenterShopMenu()
  subUsuComFuncTalkOutBase01(CH("DOTEKKOTSU"), result)
end
function DOTEKKOTSUTbl.S01_020_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.S01_010_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.S01_030_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.S01_020_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.S01_040_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.S01_030_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.S01_050_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.S01_040_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.S01_060_DOTEKKOTSU_FREE_START()
  return DOTEKKOTSUTbl.S01_050_DOTEKKOTSU_FREE_START
end
function DOTEKKOTSUTbl.S01_080_DOTEKKOTSU_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("DOTEKKOTSU"))
  if FLAG.DotekkotsuCounter == CONST.CNT_1 then
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
    CH("DOTEKKOTSU"):SetManpu("MP_SHOCK_R")
    CH("DOTEKKOTSU"):WaitManpu()
    WINDOW:DrawFace(20, 88, SymAct("DOTEKKOTSU"), FACE_TYPE.SURPRISE)
    WINDOW:Talk(SymAct("DOTEKKOTSU"), 773809247)
    WINDOW:Talk(SymAct("DOTEKKOTSU"), -1450739568)
    WINDOW:Talk(SymAct("DOTEKKOTSU"), -1331934767)
    WINDOW:KeyWait()
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
    CH("DOTEKKOTSU"):SetManpu("MP_FLY_SWEAT")
    CH("DOTEKKOTSU"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
    WINDOW:DrawFace(20, 88, SymAct("DOTEKKOTSU"), FACE_TYPE.TEARS)
    WINDOW:Talk(SymAct("DOTEKKOTSU"), 1944804726)
    WINDOW:Talk(SymAct("DOTEKKOTSU"), 1794141239)
    WINDOW:Talk(SymAct("DOTEKKOTSU"), 1105018868)
    WINDOW:Talk(SymAct("DOTEKKOTSU"), 1489374901)
    WINDOW:Talk(SymAct("DOTEKKOTSU"), 394762354)
    WINDOW:CloseMessage()
    CH("DOTEKKOTSU"):SetManpu("MP_FLY_SWEAT")
    CH("DOTEKKOTSU"):SetMotion(SymMot("EV002_CRY01"), LOOP.OFF)
    CH("DOTEKKOTSU"):WaitPlayMotion()
    CH("DOTEKKOTSU"):SetMotion(SymMot("EV002_CRY02"), LOOP.ON)
    TASK:Sleep(TimeSec(0.25))
    SCREEN_A:FadeOut(TimeSec(1.5), true)
    subUsuComFuncTalkOutBase01(CH("DOTEKKOTSU"), result)
    FLAG.DotekkotsuCounter = CONST.CNT_2
    TASK:Sleep(TimeSec(1))
    CH("DOTEKKOTSU"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0))
    CH("DOTEKKOTSU"):SetFacialMotion(FACIAL_MOTION.NORMAL)
    SCREEN_A:FadeIn(TimeSec(0.5), true)
  else
    OpenCarpenterShopMenu()
    subUsuComFuncTalkOutBase01(CH("DOTEKKOTSU"), result)
  end
end
function DOTEKKOTSUTbl.ALL_CLEAR_DOTEKKOTSU_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("DOTEKKOTSU"))
  HeroBackTalkDOTEKKOTSU()
  OpenCarpenterShopMenu()
  subUsuComFuncTalkOutBase01(CH("DOTEKKOTSU"), result)
end

