function EMONGATbl.M02_010_EMONGA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("EMONGA"))
  WINDOW:SysMsg(-1045870231)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("EMONGA"), result)
end
function EMONGATbl.M02_030_EMONGA_FREE_START()
  return EMONGATbl.M02_010_EMONGA_FREE_START
end
function EMONGATbl.M02_050_EMONGA_FREE_START()
  return EMONGATbl.M02_030_EMONGA_FREE_START
end
function EMONGATbl.M02_070_EMONGA_FREE_START()
  return EMONGATbl.M02_050_EMONGA_FREE_START
end
function EMONGATbl.M02_080_EMONGA_FREE_START()
  return EMONGATbl.M02_070_EMONGA_FREE_START
end
function EMONGATbl.M02_090_EMONGA_FREE_START()
  return EMONGATbl.M02_080_EMONGA_FREE_START
end
function EMONGATbl.M02_100_EMONGA_FREE_START()
  return EMONGATbl.M02_090_EMONGA_FREE_START
end
function EMONGATbl.M02_115_EMONGA_FREE_START()
  return EMONGATbl.M02_100_EMONGA_FREE_START
end
function EMONGATbl.M02_130_EMONGA_FREE_START()
  return EMONGATbl.M02_115_EMONGA_FREE_START
end
function EMONGATbl.M02_160_EMONGA_FREE_START()
  return EMONGATbl.M02_130_EMONGA_FREE_START
end
function EMONGATbl.M03_010_EMONGA_FREE_START()
  return EMONGATbl.M02_160_EMONGA_FREE_START
end
function EMONGATbl.M03_020_EMONGA_FREE_START()
  return EMONGATbl.M03_010_EMONGA_FREE_START
end
function EMONGATbl.M03_045_EMONGA_FREE_START()
  return EMONGATbl.M03_020_EMONGA_FREE_START
end
function EMONGATbl.M03_090_EMONGA_FREE_START()
  return EMONGATbl.M03_045_EMONGA_FREE_START
end
function EMONGATbl.M03_110_EMONGA_FREE_START()
  return EMONGATbl.M03_090_EMONGA_FREE_START
end
function EMONGATbl.M03_130_EMONGA_FREE_START()
  return EMONGATbl.M03_110_EMONGA_FREE_START
end
function EMONGATbl.M03_150_EMONGA_FREE_START()
  return EMONGATbl.M03_130_EMONGA_FREE_START
end
function EMONGATbl.M04_010_EMONGA_FREE_START()
  return EMONGATbl.M03_150_EMONGA_FREE_START
end
function EMONGATbl.M04_020_EMONGA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("EMONGA"))
  WINDOW:DrawFace(20, 88, SymAct("EMONGA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EMONGA"), -659392472)
  WINDOW:Talk(SymAct("EMONGA"), -207672341)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("EMONGA"), result)
end
function EMONGATbl.M04_HANYOU_EMONGA_FREE_START()
  return EMONGATbl.M04_020_EMONGA_FREE_START
end
function EMONGATbl.M04_040_EMONGA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("EMONGA"))
  WINDOW:DrawFace(20, 88, SymAct("EMONGA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EMONGA"), -360441174)
  WINDOW:Talk(SymAct("EMONGA"), -1513780115)
  WINDOW:Talk(SymAct("EMONGA"), -1126253268)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("EMONGA"), result)
end
function EMONGATbl.M04_060_EMONGA_FREE_START()
  return EMONGATbl.M04_040_EMONGA_FREE_START
end
function EMONGATbl.M04_070_EMONGA_FREE_START()
  return EMONGATbl.M04_060_EMONGA_FREE_START
end
function EMONGATbl.M04_HANYOU_EMONGA_FREE_START2()
  return EMONGATbl.M04_070_EMONGA_FREE_START
end
function EMONGATbl.M05_000_EMONGA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("EMONGA"))
  WINDOW:DrawFace(20, 88, SymAct("EMONGA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EMONGA"), -1745621265)
  WINDOW:Talk(SymAct("EMONGA"), -1897341010)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("EMONGA"), result)
end
function EMONGATbl.M05_010_EMONGA_FREE_START()
  return EMONGATbl.M05_000_EMONGA_FREE_START
end
function EMONGATbl.M05_020_EMONGA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("EMONGA"))
  WINDOW:DrawFace(20, 88, SymAct("EMONGA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EMONGA"), 158384993)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("EMONGA"), result)
end
function EMONGATbl.M05_030_EMONGA_FREE_START()
  return EMONGATbl.M05_020_EMONGA_FREE_START
end
function EMONGATbl.M06_HANYOU_EMONGA_FREE_START()
  return EMONGATbl.M05_030_EMONGA_FREE_START
end
function EMONGATbl.M06_010_EMONGA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("EMONGA"))
  WINDOW:DrawFace(20, 88, SymAct("EMONGA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EMONGA"), 275509792)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("EMONGA"), result)
end
function EMONGATbl.M06_015_EMONGA_FREE_START()
  return EMONGATbl.M06_010_EMONGA_FREE_START
end
function EMONGATbl.M06_020_EMONGA_FREE_START()
  return EMONGATbl.M06_015_EMONGA_FREE_START
end
function EMONGATbl.M06_030_EMONGA_FREE_START()
  return EMONGATbl.M06_020_EMONGA_FREE_START
end
function EMONGATbl.M06_040_EMONGA_FREE_START()
  return EMONGATbl.M06_030_EMONGA_FREE_START
end
function EMONGATbl.M06_060_EMONGA_FREE_START()
  return EMONGATbl.M06_040_EMONGA_FREE_START
end
function EMONGATbl.M07_000_EMONGA_FREE_START()
  return EMONGATbl.M06_060_EMONGA_FREE_START
end
function EMONGATbl.M07_010_EMONGA_FREE_START()
  return EMONGATbl.M07_000_EMONGA_FREE_START
end
function EMONGATbl.M07_020_EMONGA_FREE_START()
  return EMONGATbl.M07_010_EMONGA_FREE_START
end
function EMONGATbl.M07_045_EMONGA_FREE_START()
  return EMONGATbl.M07_020_EMONGA_FREE_START
end
function EMONGATbl.M07_HANYOU_EMONGA_FREE_START()
  return EMONGATbl.M07_045_EMONGA_FREE_START
end
function EMONGATbl.M07_080_EMONGA_FREE_START()
  return EMONGATbl.M07_HANYOU_EMONGA_FREE_START
end
function EMONGATbl.M08_010_EMONGA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("EMONGA"))
  WINDOW:DrawFace(20, 88, SymAct("EMONGA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EMONGA"), -1659065574)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("EMONGA"), result)
end
function EMONGATbl.M08_HANYOU_EMONGA_FREE_START()
  return EMONGATbl.M08_010_EMONGA_FREE_START
end
function EMONGATbl.M08_020_EMONGA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("EMONGA"))
  WINDOW:DrawFace(20, 88, SymAct("EMONGA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EMONGA"), -2079876517)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("EMONGA"), result)
end
function EMONGATbl.M08_040_EMONGA_FREE_START()
  return EMONGATbl.M08_020_EMONGA_FREE_START
end
function EMONGATbl.M08_050_EMONGA_FREE_START()
  return EMONGATbl.M08_040_EMONGA_FREE_START
end
function EMONGATbl.M08_055_EMONGA_FREE_START()
  return EMONGATbl.M08_050_EMONGA_FREE_START
end
function EMONGATbl.M08_070_EMONGA_FREE_START()
  return EMONGATbl.M08_055_EMONGA_FREE_START
end
function EMONGATbl.M09_HANYOU_EMONGA_FREE_START1()
  return EMONGATbl.M08_070_EMONGA_FREE_START
end
function EMONGATbl.M09_010_EMONGA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("EMONGA"))
  WINDOW:DrawFace(20, 88, SymAct("EMONGA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EMONGA"), -1356150376)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("EMONGA"), result)
end
function EMONGATbl.M09_020_EMONGA_FREE_START()
  return EMONGATbl.M09_010_EMONGA_FREE_START
end
function EMONGATbl.M09_040_EMONGA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("EMONGA"))
  WINDOW:DrawFace(20, 88, SymAct("EMONGA"), FACE_TYPE.EMOTION)
  WINDOW:Talk(SymAct("EMONGA"), -1238239015)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("EMONGA"), result)
end
function EMONGATbl.M09_HANYOU_EMONGA_FREE_START2()
  return EMONGATbl.M09_040_EMONGA_FREE_START
end
function EMONGATbl.M09_060_EMONGA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("EMONGA"))
  WINDOW:DrawFace(20, 88, SymAct("EMONGA"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("EMONGA"), -110072290)
  WINDOW:Talk(SymAct("EMONGA"), -529834145)
  WINDOW:Talk(SymAct("EMONGA"), -884601700)
  WINDOW:Talk(SymAct("EMONGA"), -765641251)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("EMONGA"), result)
end
function EMONGATbl.M09_080_EMONGA_FREE_START()
  return EMONGATbl.M09_060_EMONGA_FREE_START
end
function EMONGATbl.M09_100_EMONGA_FREE_START()
  return EMONGATbl.M09_080_EMONGA_FREE_START
end
function EMONGATbl.M09_110_EMONGA_FREE_START()
  return EMONGATbl.M09_100_EMONGA_FREE_START
end
function EMONGATbl.M09_120_EMONGA_FREE_START()
  return EMONGATbl.M09_110_EMONGA_FREE_START
end
function EMONGATbl.M10_010_EMONGA_FREE_START()
  return EMONGATbl.M09_120_EMONGA_FREE_START
end
function EMONGATbl.M10_030_EMONGA_FREE_START()
  return EMONGATbl.M10_010_EMONGA_FREE_START
end
function EMONGATbl.M10_040_EMONGA_FREE_START()
  return EMONGATbl.M10_030_EMONGA_FREE_START
end
function EMONGATbl.M10_060_EMONGA_FREE_START()
  return EMONGATbl.M10_040_EMONGA_FREE_START
end
function EMONGATbl.M11_010_EMONGA_FREE_START()
  return EMONGATbl.M10_060_EMONGA_FREE_START
end
function EMONGATbl.M11_030_EMONGA_FREE_START()
  return EMONGATbl.M11_010_EMONGA_FREE_START
end
function EMONGATbl.M11_040_EMONGA_FREE_START()
  return EMONGATbl.M11_030_EMONGA_FREE_START
end
function EMONGATbl.M11_050_EMONGA_FREE_START()
  return EMONGATbl.M11_040_EMONGA_FREE_START
end
function EMONGATbl.M11_060_EMONGA_FREE_START()
  return EMONGATbl.M11_050_EMONGA_FREE_START
end
function EMONGATbl.M11_090_EMONGA_FREE_START()
  return EMONGATbl.M11_060_EMONGA_FREE_START
end

