function HAADERIATbl.M02_010_HAADERIA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("HAADERIA"))
  WINDOW:DrawFace(20, 88, SymAct("HAADERIA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HAADERIA"), 649370438)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("HAADERIA"), result)
end
function HAADERIATbl.M02_030_HAADERIA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("HAADERIA"))
  WINDOW:DrawFace(20, 88, SymAct("HAADERIA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HAADERIA"), 1068476935)
  WINDOW:Talk(SymAct("HAADERIA"), 344127940)
  WINDOW:Talk(SymAct("HAADERIA"), 228182149)
  WINDOW:Talk(SymAct("HAADERIA"), 1121476162)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("HAADERIA"), result)
end
function HAADERIATbl.M02_050_HAADERIA_FREE_START()
  return HAADERIATbl.M02_030_HAADERIA_FREE_START
end
function HAADERIATbl.M02_070_HAADERIA_FREE_START()
  return HAADERIATbl.M02_050_HAADERIA_FREE_START
end
function HAADERIATbl.M02_080_HAADERIA_FREE_START()
  return HAADERIATbl.M02_070_HAADERIA_FREE_START
end
function HAADERIATbl.M02_090_HAADERIA_FREE_START()
  return HAADERIATbl.M02_080_HAADERIA_FREE_START
end
function HAADERIATbl.M02_100_HAADERIA_FREE_START()
  return HAADERIATbl.M02_090_HAADERIA_FREE_START
end
function HAADERIATbl.M02_115_HAADERIA_FREE_START()
  return HAADERIATbl.M02_100_HAADERIA_FREE_START
end
function HAADERIATbl.M02_130_HAADERIA_FREE_START()
  return HAADERIATbl.M02_115_HAADERIA_FREE_START
end
function HAADERIATbl.M02_160_HAADERIA_FREE_START()
  return HAADERIATbl.M02_130_HAADERIA_FREE_START
end
function HAADERIATbl.M03_010_HAADERIA_FREE_START()
  return HAADERIATbl.M02_160_HAADERIA_FREE_START
end
function HAADERIATbl.M03_020_HAADERIA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("HAADERIA"))
  WINDOW:DrawFace(20, 88, SymAct("HAADERIA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HAADERIA"), 1539534595)
  WINDOW:Talk(SymAct("HAADERIA"), 1894661312)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("HAADERIA"), result)
end
function HAADERIATbl.M03_045_HAADERIA_FREE_START()
  return HAADERIATbl.M03_020_HAADERIA_FREE_START
end
function HAADERIATbl.M03_090_HAADERIA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("HAADERIA"))
  WINDOW:DrawFace(20, 88, SymAct("HAADERIA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("HAADERIA"), 1777667457)
  WINDOW:Talk(SymAct("HAADERIA"), -294842034)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("HAADERIA"), result)
end
function HAADERIATbl.M03_110_HAADERIA_FREE_START()
  return HAADERIATbl.M03_090_HAADERIA_FREE_START
end
function HAADERIATbl.M03_130_HAADERIA_FREE_START()
  return HAADERIATbl.M03_110_HAADERIA_FREE_START
end
function HAADERIATbl.M03_150_HAADERIA_FREE_START()
  return HAADERIATbl.M03_130_HAADERIA_FREE_START
end
function HAADERIATbl.M04_010_HAADERIA_FREE_START()
  return HAADERIATbl.M03_150_HAADERIA_FREE_START
end
function HAADERIATbl.M04_020_HAADERIA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("HAADERIA"))
  WINDOW:DrawFace(20, 88, SymAct("HAADERIA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HAADERIA"), -143253489)
  WINDOW:Talk(SymAct("HAADERIA"), -404895854)
  WINDOW:Talk(SymAct("HAADERIA"), -20515117)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("HAADERIA"), result)
end
function HAADERIATbl.M04_HANYOU_HAADERIA_FREE_START()
  return HAADERIATbl.M04_020_HAADERIA_FREE_START
end
function HAADERIATbl.M04_040_HAADERIA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("HAADERIA"))
  WINDOW:DrawFace(20, 88, SymAct("HAADERIA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HAADERIA"), -705977072)
  WINDOW:Talk(SymAct("HAADERIA"), -856648623)
  WINDOW:DrawFace(20, 88, SymAct("HAADERIA"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("HAADERIA"), -2085551466)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("HAADERIA"), result)
end
function HAADERIATbl.M04_060_HAADERIA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("HAADERIA"))
  CH("HAADERIA"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(20, 88, SymAct("HAADERIA"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("HAADERIA"), -1700121641)
  WINDOW:Talk(SymAct("HAADERIA"), -1316528108)
  WINDOW:CloseMessage()
  CH("HAADERIA"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  subUsuComFuncTalkOutBase01(CH("HAADERIA"), result)
end
function HAADERIATbl.M04_070_HAADERIA_FREE_START()
  return HAADERIATbl.M04_060_HAADERIA_FREE_START
end
function HAADERIATbl.M04_HANYOU_HAADERIA_FREE_START2()
  return HAADERIATbl.M04_070_HAADERIA_FREE_START
end
function HAADERIATbl.M05_000_HAADERIA_FREE_START()
  return HAADERIATbl.M04_HANYOU_HAADERIA_FREE_START2
end
function HAADERIATbl.M05_010_HAADERIA_FREE_START()
  return HAADERIATbl.M05_000_HAADERIA_FREE_START
end
function HAADERIATbl.M05_020_HAADERIA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("HAADERIA"))
  WINDOW:DrawFace(20, 88, SymAct("HAADERIA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HAADERIA"), -1466150571)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("HAADERIA"), result)
end
function HAADERIATbl.M05_030_HAADERIA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("HAADERIA"))
  WINDOW:DrawFace(20, 88, SymAct("HAADERIA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HAADERIA"), 788811162)
  WINDOW:Talk(SymAct("HAADERIA"), 908033243)
  WINDOW:Talk(SymAct("HAADERIA"), -177706884)
  WINDOW:Talk(SymAct("HAADERIA"), -327984835)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("HAADERIA"), result)
end
function HAADERIATbl.M06_HANYOU_HAADERIA_FREE_START()
  return HAADERIATbl.M05_030_HAADERIA_FREE_START
end
function HAADERIATbl.M06_010_HAADERIA_FREE_START()
  local result = subUsuComFuncTalkInBase02(CH("HAADERIA"))
  WINDOW:DrawFace(20, 88, SymAct("HAADERIA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HAADERIA"), -950138114)
  WINDOW:Talk(SymAct("HAADERIA"), -565888065)
  WINDOW:Talk(SymAct("HAADERIA"), -1861964424)
  WINDOW:Talk(SymAct("HAADERIA"), -2011194311)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase02(CH("HAADERIA"), result)
end
function HAADERIATbl.M06_015_HAADERIA_FREE_START()
  return HAADERIATbl.M06_010_HAADERIA_FREE_START
end
function HAADERIATbl.M06_020_HAADERIA_FREE_START()
  return HAADERIATbl.M06_015_HAADERIA_FREE_START
end
function HAADERIATbl.M06_030_HAADERIA_FREE_START()
  return HAADERIATbl.M06_020_HAADERIA_FREE_START
end
function HAADERIATbl.M06_040_HAADERIA_FREE_START()
  return HAADERIATbl.M06_030_HAADERIA_FREE_START
end
function HAADERIATbl.M06_060_HAADERIA_FREE_START()
  return HAADERIATbl.M06_040_HAADERIA_FREE_START
end
function HAADERIATbl.M07_000_HAADERIA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("HAADERIA"))
  WINDOW:DrawFace(20, 88, SymAct("HAADERIA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HAADERIA"), -1556951046)
  WINDOW:Talk(SymAct("HAADERIA"), -1171652933)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("HAADERIA"), result)
end
function HAADERIATbl.M07_010_HAADERIA_FREE_START()
  return HAADERIATbl.M07_000_HAADERIA_FREE_START
end
function HAADERIATbl.M07_020_HAADERIA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("HAADERIA"))
  WINDOW:DrawFace(20, 88, SymAct("HAADERIA"), FACE_TYPE.CATCHBREATH)
  WINDOW:Talk(SymAct("HAADERIA"), 1035068020)
  WINDOW:Talk(SymAct("HAADERIA"), 615174965)
  WINDOW:Talk(SymAct("HAADERIA"), 1305743129)
  WINDOW:Talk(SymAct("HAADERIA"), 1422868056)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("HAADERIA"), result)
end
function HAADERIATbl.M07_045_HAADERIA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("HAADERIA"))
  WINDOW:DrawFace(20, 88, SymAct("HAADERIA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HAADERIA"), 2145545627)
  WINDOW:Talk(SymAct("HAADERIA"), 1727618266)
  WINDOW:Talk(SymAct("HAADERIA"), 699976221)
  WINDOW:Talk(SymAct("HAADERIA"), 816053084)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("HAADERIA"), result)
end
function HAADERIATbl.M07_HANYOU_HAADERIA_FREE_START()
  return HAADERIATbl.M07_045_HAADERIA_FREE_START
end
function HAADERIATbl.M07_080_HAADERIA_FREE_START()
  return HAADERIATbl.M07_HANYOU_HAADERIA_FREE_START
end
function HAADERIATbl.M08_010_HAADERIA_FREE_START()
  return HAADERIATbl.M07_080_HAADERIA_FREE_START
end
function HAADERIATbl.M08_HANYOU_HAADERIA_FREE_START()
  return HAADERIATbl.M08_010_HAADERIA_FREE_START
end
function HAADERIATbl.M08_020_HAADERIA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("HAADERIA"))
  WINDOW:DrawFace(20, 88, SymAct("HAADERIA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HAADERIA"), 462334111)
  WINDOW:Talk(SymAct("HAADERIA"), 43358686)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("HAADERIA"), result)
end
function HAADERIATbl.M08_040_HAADERIA_FREE_START()
  return HAADERIATbl.M08_020_HAADERIA_FREE_START
end
function HAADERIATbl.M08_050_HAADERIA_FREE_START()
  return HAADERIATbl.M08_040_HAADERIA_FREE_START
end
function HAADERIATbl.M08_055_HAADERIA_FREE_START()
  return HAADERIATbl.M08_050_HAADERIA_FREE_START
end
function HAADERIATbl.M08_070_HAADERIA_FREE_START()
  return HAADERIATbl.M08_055_HAADERIA_FREE_START
end
function HAADERIATbl.M09_HANYOU_HAADERIA_FREE_START1()
  return HAADERIATbl.M08_070_HAADERIA_FREE_START
end
function HAADERIATbl.M09_010_HAADERIA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("HAADERIA"))
  WINDOW:DrawFace(20, 88, SymAct("HAADERIA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HAADERIA"), -2062711535)
  WINDOW:Talk(SymAct("HAADERIA"), -1676233648)
  WINDOW:Talk(SymAct("HAADERIA"), -805095520)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("HAADERIA"), result)
end
function HAADERIATbl.M09_020_HAADERIA_FREE_START()
  return HAADERIATbl.M09_010_HAADERIA_FREE_START
end
function HAADERIATbl.M09_040_HAADERIA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("HAADERIA"))
  WINDOW:DrawFace(20, 88, SymAct("HAADERIA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HAADERIA"), -921172255)
  WINDOW:Talk(SymAct("HAADERIA"), -499821278)
  WINDOW:Talk(SymAct("HAADERIA"), -80845725)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("HAADERIA"), result)
end
function HAADERIATbl.M09_HANYOU_HAADERIA_FREE_START2()
  return HAADERIATbl.M09_040_HAADERIA_FREE_START
end
function HAADERIATbl.M09_060_HAADERIA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("HAADERIA"))
  CH("HAADERIA"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(20, 88, SymAct("HAADERIA"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("HAADERIA"), -1267731804)
  WINDOW:Talk(SymAct("HAADERIA"), -1384856603)
  WINDOW:CloseMessage()
  CH("HAADERIA"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  subUsuComFuncTalkOutBase01(CH("HAADERIA"), result)
end
function HAADERIATbl.M09_080_HAADERIA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("HAADERIA"))
  CH("HAADERIA"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(20, 88, SymAct("HAADERIA"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("HAADERIA"), -2040950746)
  WINDOW:CloseMessage()
  CH("HAADERIA"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("HAADERIA"):SetManpu("MP_EXCLAMATION")
  CH("HAADERIA"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("HAADERIA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("HAADERIA"), -1623023257)
  WINDOW:Talk(SymAct("HAADERIA"), 416988584)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("HAADERIA"), result)
end
function HAADERIATbl.M09_100_HAADERIA_FREE_START()
  return HAADERIATbl.M09_080_HAADERIA_FREE_START
end
function HAADERIATbl.M09_110_HAADERIA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("HAADERIA"))
  WINDOW:DrawFace(20, 88, SymAct("HAADERIA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HAADERIA"), 29461737)
  WINDOW:Talk(SymAct("HAADERIA"), 1757368517)
  WINDOW:Talk(SymAct("HAADERIA"), 1906598276)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("HAADERIA"), result)
end
function HAADERIATbl.M09_120_HAADERIA_FREE_START()
  return HAADERIATbl.M09_110_HAADERIA_FREE_START
end
function HAADERIATbl.M10_010_HAADERIA_FREE_START()
  return HAADERIATbl.M09_120_HAADERIA_FREE_START
end
function HAADERIATbl.M10_030_HAADERIA_FREE_START()
  return HAADERIATbl.M10_010_HAADERIA_FREE_START
end
function HAADERIATbl.M10_040_HAADERIA_FREE_START()
  return HAADERIATbl.M10_030_HAADERIA_FREE_START
end
function HAADERIATbl.M10_060_HAADERIA_FREE_START()
  return HAADERIATbl.M10_040_HAADERIA_FREE_START
end
function HAADERIATbl.M11_010_HAADERIA_FREE_START()
  return HAADERIATbl.M10_060_HAADERIA_FREE_START
end
function HAADERIATbl.M11_030_HAADERIA_FREE_START()
  return HAADERIATbl.M11_010_HAADERIA_FREE_START
end
function HAADERIATbl.M11_040_HAADERIA_FREE_START()
  return HAADERIATbl.M11_030_HAADERIA_FREE_START
end
function HAADERIATbl.M11_050_HAADERIA_FREE_START()
  return HAADERIATbl.M11_040_HAADERIA_FREE_START
end
function HAADERIATbl.M11_060_HAADERIA_FREE_START()
  return HAADERIATbl.M11_050_HAADERIA_FREE_START
end
function HAADERIATbl.M11_090_HAADERIA_FREE_START()
  return HAADERIATbl.M11_060_HAADERIA_FREE_START
end

