function HAADERIATbl.M12_010_HAADERIA_FREE_START()
  return HAADERIATbl.M11_090_HAADERIA_FREE_START
end
function HAADERIATbl.M12_020_HAADERIA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("HAADERIA"))
  WINDOW:DrawFace(20, 88, SymAct("HAADERIA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HAADERIA"), 1117007827)
  WINDOW:Talk(SymAct("HAADERIA"), 1536106130)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("HAADERIA"), result)
end
function HAADERIATbl.M12_030_HAADERIA_FREE_START()
end
function HAADERIATbl.M12_040_HAADERIA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("HAADERIA"))
  WINDOW:DrawFace(20, 88, SymAct("HAADERIA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HAADERIA"), 1889684817)
  WINDOW:Talk(SymAct("HAADERIA"), 1773763600)
  WINDOW:Talk(SymAct("HAADERIA"), 653847255)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("HAADERIA"), result)
end
function HAADERIATbl.M12_050_HAADERIA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("HAADERIA"))
  WINDOW:DrawFace(20, 88, SymAct("HAADERIA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HAADERIA"), 1071897494)
  WINDOW:Talk(SymAct("HAADERIA"), 349079637)
  WINDOW:Talk(SymAct("HAADERIA"), 232110356)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("HAADERIA"), result)
end
function HAADERIATbl.M12_070_HAADERIA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("HAADERIA"))
  WINDOW:DrawFace(20, 88, SymAct("HAADERIA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HAADERIA"), -1974622757)
  WINDOW:Talk(SymAct("HAADERIA"), -1823042406)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("HAADERIA"), result)
end
function HAADERIATbl.M13_010_HAADERIA_FREE_START()
  return HAADERIATbl.M12_070_HAADERIA_FREE_START
end
function HAADERIATbl.M13_030_HAADERIA_FREE_START()
  return HAADERIATbl.M13_010_HAADERIA_FREE_START
end
function HAADERIATbl.M13_040_HAADERIA_FREE_START()
  return HAADERIATbl.M13_030_HAADERIA_FREE_START
end
function HAADERIATbl.M13_060_HAADERIA_FREE_START()
  return HAADERIATbl.M13_040_HAADERIA_FREE_START
end
function HAADERIATbl.M13_070_HAADERIA_FREE_START()
  return HAADERIATbl.M13_060_HAADERIA_FREE_START
end
function HAADERIATbl.M13_080_HAADERIA_FREE_START()
  return HAADERIATbl.M13_070_HAADERIA_FREE_START
end
function HAADERIATbl.M13_090_HAADERIA_FREE_START()
  return HAADERIATbl.M13_080_HAADERIA_FREE_START
end
function HAADERIATbl.M13_095_HAADERIA_FREE_START()
  return HAADERIATbl.M13_090_HAADERIA_FREE_START
end
function HAADERIATbl.M13_110_HAADERIA_FREE_START()
  return HAADERIATbl.M13_095_HAADERIA_FREE_START
end
function HAADERIATbl.M14_010_HAADERIA_FREE_START()
  return HAADERIATbl.M13_110_HAADERIA_FREE_START
end
function HAADERIATbl.M14_030_HAADERIA_FREE_START()
  return HAADERIATbl.M14_010_HAADERIA_FREE_START
end
function HAADERIATbl.M14_040_HAADERIA_FREE_START()
  return HAADERIATbl.M14_030_HAADERIA_FREE_START
end
function HAADERIATbl.M14_060_HAADERIA_FREE_START()
  return HAADERIATbl.M14_040_HAADERIA_FREE_START
end
function HAADERIATbl.M14_070_HAADERIA_FREE_START()
  return HAADERIATbl.M14_060_HAADERIA_FREE_START
end
function HAADERIATbl.M14_090_HAADERIA_FREE_START()
  return HAADERIATbl.M14_070_HAADERIA_FREE_START
end
function HAADERIATbl.M15_010_HAADERIA_FREE_START()
  return HAADERIATbl.M14_090_HAADERIA_FREE_START
end
function HAADERIATbl.M15_020_HAADERIA_FREE_START()
  return HAADERIATbl.M15_010_HAADERIA_FREE_START
end
function HAADERIATbl.M15_030_HAADERIA_FREE_START()
  return HAADERIATbl.M15_020_HAADERIA_FREE_START
end
function HAADERIATbl.M16_010_HAADERIA_FREE_START()
  return HAADERIATbl.M15_030_HAADERIA_FREE_START
end
function HAADERIATbl.M16_040_HAADERIA_FREE_START()
  return HAADERIATbl.M16_010_HAADERIA_FREE_START
end
function HAADERIATbl.M16_080_HAADERIA_FREE_START()
  return HAADERIATbl.M16_040_HAADERIA_FREE_START
end
function HAADERIATbl.M16_090_HAADERIA_FREE_START()
  return HAADERIATbl.M16_080_HAADERIA_FREE_START
end
function HAADERIATbl.M16_100_HAADERIA_FREE_START()
  return HAADERIATbl.M16_090_HAADERIA_FREE_START
end
function HAADERIATbl.M16_105_HAADERIA_FREE_START()
  return HAADERIATbl.M16_100_HAADERIA_FREE_START
end
function HAADERIATbl.M16_120_HAADERIA_FREE_START()
  return HAADERIATbl.M16_105_HAADERIA_FREE_START
end
function HAADERIATbl.M17_020_HAADERIA_FREE_START()
  return HAADERIATbl.M16_120_HAADERIA_FREE_START
end
function HAADERIATbl.M17_040_HAADERIA_FREE_START()
  return HAADERIATbl.M17_020_HAADERIA_FREE_START
end
function HAADERIATbl.M17_060_HAADERIA_FREE_START()
  return HAADERIATbl.M17_040_HAADERIA_FREE_START
end
function HAADERIATbl.M17_065_HAADERIA_FREE_START()
  return HAADERIATbl.M17_060_HAADERIA_FREE_START
end
function HAADERIATbl.M17_090_HAADERIA_FREE_START()
  return HAADERIATbl.M17_065_HAADERIA_FREE_START
end
function HAADERIATbl.M17_120_HAADERIA_FREE_START()
  return HAADERIATbl.M17_090_HAADERIA_FREE_START
end
function HAADERIATbl.M17_140_HAADERIA_FREE_START()
  return HAADERIATbl.M17_120_HAADERIA_FREE_START
end
function HAADERIATbl.M17_150_HAADERIA_FREE_START()
  return HAADERIATbl.M17_140_HAADERIA_FREE_START
end
function HAADERIATbl.M17_155_HAADERIA_FREE_START()
  return HAADERIATbl.M17_150_HAADERIA_FREE_START
end
function HAADERIATbl.M17_170_HAADERIA_FREE_START()
  return HAADERIATbl.M17_155_HAADERIA_FREE_START
end
function HAADERIATbl.M17_200_HAADERIA_FREE_START()
  return HAADERIATbl.M17_170_HAADERIA_FREE_START
end
function HAADERIATbl.M17_210_HAADERIA_FREE_START()
  return HAADERIATbl.M17_200_HAADERIA_FREE_START
end
function HAADERIATbl.M17_220_HAADERIA_FREE_START()
  return HAADERIATbl.M17_210_HAADERIA_FREE_START
end
function HAADERIATbl.M17_225_HAADERIA_FREE_START()
  return HAADERIATbl.M17_220_HAADERIA_FREE_START
end
function HAADERIATbl.M17_240_HAADERIA_FREE_START()
  return HAADERIATbl.M17_225_HAADERIA_FREE_START
end
function HAADERIATbl.M18_020_HAADERIA_FREE_START()
  return HAADERIATbl.M17_240_HAADERIA_FREE_START
end
function HAADERIATbl.M18_030_HAADERIA_FREE_START()
  return HAADERIATbl.M18_020_HAADERIA_FREE_START
end
function HAADERIATbl.S01_010_HAADERIA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("HAADERIA"))
  WINDOW:DrawFace(20, 88, SymAct("HAADERIA"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("HAADERIA"), 669493880)
  WINDOW:Talk(SymAct("HAADERIA"), 1056742201)
  WINDOW:Talk(SymAct("HAADERIA"), 366070010)
  WINDOW:Talk(SymAct("HAADERIA"), 214628795)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("HAADERIA"), result)
end
function HAADERIATbl.S01_020_HAADERIA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("HAADERIA"))
  WINDOW:DrawFace(20, 88, SymAct("HAADERIA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HAADERIA"), 1133211516)
  WINDOW:Talk(SymAct("HAADERIA"), 1519410749)
  WINDOW:Talk(SymAct("HAADERIA"), 1908215294)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("HAADERIA"), result)
end
function HAADERIATbl.S01_030_HAADERIA_FREE_START()
  return HAADERIATbl.S01_020_HAADERIA_FREE_START
end
function HAADERIATbl.S01_040_HAADERIA_FREE_START()
  return HAADERIATbl.S01_030_HAADERIA_FREE_START
end
function HAADERIATbl.S01_050_HAADERIA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("HAADERIA"))
  WINDOW:DrawFace(20, 88, SymAct("HAADERIA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HAADERIA"), 1755724991)
  WINDOW:Talk(SymAct("HAADERIA"), -281141136)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("HAADERIA"), result)
end
function HAADERIATbl.S01_060_HAADERIA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("HAADERIA"))
  WINDOW:DrawFace(20, 88, SymAct("HAADERIA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HAADERIA"), -165342927)
  WINDOW:DrawFace(20, 88, SymAct("HAADERIA"), FACE_TYPE.EMOTION)
  WINDOW:Talk(SymAct("HAADERIA"), 894567830)
  WINDOW:Talk(SymAct("HAADERIA"), 742995159)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("HAADERIA"), result)
end
function HAADERIATbl.S01_080_HAADERIA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("HAADERIA"))
  WINDOW:DrawFace(20, 88, SymAct("HAADERIA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HAADERIA"), 124020500)
  WINDOW:Talk(SymAct("HAADERIA"), 511661653)
  WINDOW:Talk(SymAct("HAADERIA"), 1363067026)
  WINDOW:Talk(SymAct("HAADERIA"), 1210446291)
  WINDOW:Talk(SymAct("HAADERIA"), 1661510160)
  WINDOW:KeyWait()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("HAADERIA"):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFace(20, 88, SymAct("HAADERIA"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("HAADERIA"), 2048103249)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("HAADERIA"), result)
end
function HAADERIATbl.ALL_CLEAR_HAADERIA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("HAADERIA"))
  WINDOW:DrawFace(20, 88, SymAct("HAADERIA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HAADERIA"), -41185378)
  WINDOW:Talk(SymAct("HAADERIA"), -460276001)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("HAADERIA"), result)
end

