function HIMANATTSUTbl.M02_010_HIMANATTSU_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("HIMANATTSU"))
  WINDOW:SysMsg(-1931185218)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("HIMANATTSU"), result)
end
function HIMANATTSUTbl.M02_030_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M02_010_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M02_050_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M02_030_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M02_070_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M02_050_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M02_080_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M02_070_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M02_090_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M02_080_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M02_100_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M02_090_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M02_115_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M02_100_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M02_130_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M02_115_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M02_160_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M02_130_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M03_010_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M02_160_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M03_020_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M03_010_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M03_045_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M03_020_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M03_090_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M03_045_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M03_110_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M03_090_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M03_130_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M03_110_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M03_150_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M03_130_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M04_010_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M03_150_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M04_020_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M04_010_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M04_HANYOU_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M04_020_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M04_040_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M04_HANYOU_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M04_060_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M04_040_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M04_070_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M04_060_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M04_HANYOU_HIMANATTSU_FREE_START2()
  return HIMANATTSUTbl.M04_070_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M05_000_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M04_HANYOU_HIMANATTSU_FREE_START2
end
function HIMANATTSUTbl.M05_010_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M05_000_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M05_020_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M05_010_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M05_030_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M05_020_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M06_HANYOU_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M05_030_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M06_010_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M06_HANYOU_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M06_015_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M06_010_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M06_020_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M06_015_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M06_030_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M06_020_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M06_040_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M06_030_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M06_060_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M06_040_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M07_000_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M06_060_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M07_010_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M07_000_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M07_020_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M07_010_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M07_045_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M07_020_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M07_HANYOU_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M07_045_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M07_080_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M07_HANYOU_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M08_010_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M07_080_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M08_HANYOU_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M08_010_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M08_020_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M08_HANYOU_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M08_040_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M08_020_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M08_050_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M08_040_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M08_055_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M08_050_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M08_070_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M08_055_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M09_HANYOU_HIMANATTSU_FREE_START1()
  return HIMANATTSUTbl.M08_070_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M09_010_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M09_HANYOU_HIMANATTSU_FREE_START1
end
function HIMANATTSUTbl.M09_020_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M09_010_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M09_040_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M09_020_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M09_HANYOU_HIMANATTSU_FREE_START2()
  return HIMANATTSUTbl.M09_040_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M09_060_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M09_HANYOU_HIMANATTSU_FREE_START2
end
function HIMANATTSUTbl.M09_080_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M09_060_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M09_100_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M09_080_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M09_110_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M09_100_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M09_120_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M09_110_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M10_010_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M09_120_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M10_030_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M10_010_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M10_040_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M10_030_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M10_060_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M10_040_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M11_010_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M10_060_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M11_030_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M11_010_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M11_040_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M11_030_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M11_050_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M11_040_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M11_060_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M11_050_HIMANATTSU_FREE_START
end
function HIMANATTSUTbl.M11_090_HIMANATTSU_FREE_START()
  return HIMANATTSUTbl.M11_060_HIMANATTSU_FREE_START
end

