function HIYAPPUTbl.M02_010_HIYAPPU_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("HIYAPPU"))
  WINDOW:SysMsg(-1224906922)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("HIYAPPU"), result)
end
function HIYAPPUTbl.M02_030_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M02_010_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M02_050_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M02_030_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M02_070_HIYAPPU_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("HIYAPPU"))
  WINDOW:DrawFace(20, 88, SymAct("HIYAPPU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HIYAPPU"), -1343859177)
  WINDOW:Talk(SymAct("HIYAPPU"), -2067069484)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("HIYAPPU"), result)
end
function HIYAPPUTbl.M02_080_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M02_070_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M02_090_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M02_080_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M02_100_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M02_090_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M02_115_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M02_100_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M02_130_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M02_115_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M02_160_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M02_130_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M03_010_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M02_160_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M03_020_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M03_010_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M03_045_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M03_020_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M03_090_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M03_045_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M03_110_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M03_090_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M03_130_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M03_110_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M03_150_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M03_130_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M04_010_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M03_150_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M04_020_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M04_010_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M04_HANYOU_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M04_020_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M04_040_HIYAPPU_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("HIYAPPU"))
  WINDOW:DrawFace(20, 88, SymAct("HIYAPPU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HIYAPPU"), -1647299435)
  WINDOW:Talk(SymAct("HIYAPPU"), -762207662)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("HIYAPPU"), result)
end
function HIYAPPUTbl.M04_060_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M04_040_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M04_070_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M04_060_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M04_HANYOU_HIYAPPU_FREE_START2()
  return HIYAPPUTbl.M04_070_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M05_000_HIYAPPU_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("HIYAPPU"))
  WINDOW:DrawFace(20, 88, SymAct("HIYAPPU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HIYAPPU"), -880110829)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("HIYAPPU"), result)
end
function HIYAPPUTbl.M05_010_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M05_000_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M05_020_HIYAPPU_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("HIYAPPU"))
  WINDOW:DrawFace(20, 88, SymAct("HIYAPPU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HIYAPPU"), -525877040)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("HIYAPPU"), result)
end
function HIYAPPUTbl.M05_030_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M05_020_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M06_HANYOU_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M05_030_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M06_010_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M06_HANYOU_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M06_015_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M06_010_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M06_020_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M06_015_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M06_030_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M06_020_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M06_040_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M06_030_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M06_060_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M06_040_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M07_000_HIYAPPU_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("HIYAPPU"))
  WINDOW:DrawFace(20, 88, SymAct("HIYAPPU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HIYAPPU"), -105057903)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("HIYAPPU"), result)
end
function HIYAPPUTbl.M07_010_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M07_000_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M07_020_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M07_010_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M07_045_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M07_020_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M07_HANYOU_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M07_045_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M07_080_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M07_HANYOU_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M08_010_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M07_080_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M08_HANYOU_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M08_010_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M08_020_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M08_HANYOU_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M08_040_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M08_020_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M08_050_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M08_040_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M08_055_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M08_050_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M08_070_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M08_055_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M09_HANYOU_HIYAPPU_FREE_START1()
  return HIYAPPUTbl.M08_070_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M09_010_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M09_HANYOU_HIYAPPU_FREE_START1
end
function HIYAPPUTbl.M09_020_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M09_010_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M09_040_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M09_020_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M09_HANYOU_HIYAPPU_FREE_START2()
  return HIYAPPUTbl.M09_040_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M09_060_HIYAPPU_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("HIYAPPU"))
  WINDOW:DrawFace(20, 88, SymAct("HIYAPPU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HIYAPPU"), 2116349278)
  WINDOW:Talk(SymAct("HIYAPPU"), 1732238367)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("HIYAPPU"), result)
end
function HIYAPPUTbl.M09_080_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M09_060_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M09_100_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M09_080_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M09_110_HIYAPPU_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("HIYAPPU"))
  WINDOW:DrawFace(20, 88, SymAct("HIYAPPU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HIYAPPU"), 420805565)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("HIYAPPU"), result)
end
function HIYAPPUTbl.M09_120_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M09_110_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M10_010_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M09_120_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M10_030_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M10_010_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M10_040_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M10_030_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M10_060_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M10_040_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M11_010_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M10_060_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M11_030_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M11_010_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M11_040_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M11_030_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M11_050_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M11_040_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M11_060_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M11_050_HIYAPPU_FREE_START
end
function HIYAPPUTbl.M11_090_HIYAPPU_FREE_START()
  return HIYAPPUTbl.M11_060_HIYAPPU_FREE_START
end

