function ISHIZUMAITbl.M02_010_ISHIZUMAI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("ISHIZUMAI"))
  WINDOW:SysMsg(1882432555)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("ISHIZUMAI"), result)
end
function ISHIZUMAITbl.M02_030_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M02_010_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M02_050_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M02_030_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M02_070_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M02_050_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M02_080_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M02_070_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M02_090_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M02_080_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M02_100_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M02_090_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M02_115_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M02_100_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M02_130_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M02_115_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M02_160_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M02_130_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M03_010_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M02_160_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M03_020_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M03_010_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M03_045_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M03_020_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M03_090_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M03_045_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M03_110_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M03_090_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M03_130_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M03_110_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M03_150_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M03_130_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M04_010_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M03_150_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M04_020_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M04_010_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M04_HANYOU_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M04_020_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M04_040_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M04_HANYOU_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M04_060_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M04_040_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M04_070_ISHIZUMAI_FREE_START()
  local result = subUsuComFuncTalkInBase02(CH("ISHIZUMAI"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("ISHIZUMAI"):SetManpu("MP_EXCLAMATION")
  CH("ISHIZUMAI"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("ISHIZUMAI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("ISHIZUMAI"), 1764267370)
  WINDOW:Talk(SymAct("ISHIZUMAI"), 1107674793)
  WINDOW:Talk(SymAct("ISHIZUMAI"), 1528756200)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase02(CH("ISHIZUMAI"), result)
end
function ISHIZUMAITbl.M04_HANYOU_ISHIZUMAI_FREE_START2()
  return ISHIZUMAITbl.M04_070_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M05_000_ISHIZUMAI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("ISHIZUMAI"))
  WINDOW:DrawFace(20, 88, SymAct("ISHIZUMAI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("ISHIZUMAI"), 341795119)
  WINDOW:Talk(SymAct("ISHIZUMAI"), 222580846)
  WINDOW:Talk(SymAct("ISHIZUMAI"), 644416429)
  WINDOW:Talk(SymAct("ISHIZUMAI"), 1064448748)
  WINDOW:Talk(SymAct("ISHIZUMAI"), -1192612317)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("ISHIZUMAI"), result)
end
function ISHIZUMAITbl.M05_010_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M05_000_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M05_020_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M05_010_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M05_030_ISHIZUMAI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("ISHIZUMAI"))
  WINDOW:DrawFace(20, 88, SymAct("ISHIZUMAI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("ISHIZUMAI"), -1578033310)
  WINDOW:Talk(SymAct("ISHIZUMAI"), -2115458622)
  WINDOW:Talk(SymAct("ISHIZUMAI"), -1728866173)
  WINDOW:Talk(SymAct("ISHIZUMAI"), -1277244608)
  WINDOW:Talk(SymAct("ISHIZUMAI"), -1429865983)
  WINDOW:Talk(SymAct("ISHIZUMAI"), -444306234)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("ISHIZUMAI"), result)
end
function ISHIZUMAITbl.M06_HANYOU_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M05_030_FREE_START
end
function ISHIZUMAITbl.M06_010_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M06_HANYOU_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M06_015_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M06_010_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M06_020_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M06_015_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M06_030_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M06_020_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M06_040_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M06_030_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M06_060_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M06_040_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M07_000_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M06_060_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M07_010_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M07_000_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M07_020_ISHIZUMAI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("ISHIZUMAI"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("ISHIZUMAI"):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFace(20, 88, SymAct("ISHIZUMAI"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("ISHIZUMAI"), -56664697)
  WINDOW:Talk(SymAct("ISHIZUMAI"), -676196796)
  WINDOW:Talk(SymAct("ISHIZUMAI"), -827769083)
  WINDOW:Talk(SymAct("ISHIZUMAI"), 1227957194)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("ISHIZUMAI"), result)
end
function ISHIZUMAITbl.M07_045_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M07_020_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M07_HANYOU_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M07_045_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M07_080_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M07_HANYOU_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M08_010_ISHIZUMAI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("ISHIZUMAI"))
  WINDOW:DrawFace(20, 88, SymAct("ISHIZUMAI"), FACE_TYPE.EMOTION)
  WINDOW:Talk(SymAct("ISHIZUMAI"), 1344934539)
  WINDOW:Talk(SymAct("ISHIZUMAI"), -1822620116)
  WINDOW:CloseMessage()
  CH("ISHIZUMAI"):DirTo(RotateTarget(-45), Speed(350), ROT_TYPE.NEAR)
  CH("ISHIZUMAI"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("ISHIZUMAI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("ISHIZUMAI"), -1975109779)
  WINDOW:KeyWait()
  CH("ISHIZUMAI"):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFace(20, 88, SymAct("ISHIZUMAI"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("ISHIZUMAI"), -1586797394)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("ISHIZUMAI"):SetManpu("MP_FLY_SWEAT")
  CH("ISHIZUMAI"):WaitManpu()
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("ISHIZUMAI"), result)
end
function ISHIZUMAITbl.M08_HANYOU_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M08_010_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M08_020_ISHIZUMAI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("ISHIZUMAI"))
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  TASK:Regist(subEveDoubleJump, {
    CH("ISHIZUMAI")
  })
  WINDOW:DrawFace(20, 88, SymAct("ISHIZUMAI"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("ISHIZUMAI"), -1200597521)
  WINDOW:Talk(SymAct("ISHIZUMAI"), -147733720)
  WINDOW:Talk(SymAct("ISHIZUMAI"), -299175319)
  WINDOW:Talk(SymAct("ISHIZUMAI"), -989355606)
  WINDOW:Talk(SymAct("ISHIZUMAI"), -602107669)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("ISHIZUMAI"):SetManpu("MP_FLY_SWEAT")
  CH("ISHIZUMAI"):WaitManpu()
  CH("ISHIZUMAI"):DirTo(RotateTarget(-45), Speed(350), ROT_TYPE.NEAR)
  CH("ISHIZUMAI"):WaitRotate()
  TASK:Regist(subEveDoubleJump, {
    CH("ISHIZUMAI")
  })
  WINDOW:DrawFace(324, 88, SymAct("ISHIZUMAI"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("ISHIZUMAI"), 1535413284)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("ISHIZUMAI"), result)
end
function ISHIZUMAITbl.M08_040_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M08_020_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M08_050_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M08_040_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M08_055_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M08_050_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M08_070_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M08_055_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M09_HANYOU_ISHIZUMAI_FREE_START1()
  return ISHIZUMAITbl.M08_070_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M09_010_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M09_HANYOU_ISHIZUMAI_FREE_START1
end
function ISHIZUMAITbl.M09_020_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M09_010_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M09_040_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M09_020_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M09_HANYOU_ISHIZUMAI_FREE_START2()
  return ISHIZUMAITbl.M09_040_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M09_060_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M09_HANYOU_ISHIZUMAI_FREE_START2
end
function ISHIZUMAITbl.M09_080_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M09_060_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M09_100_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M09_080_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M09_110_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M09_100_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M09_120_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M09_110_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M10_010_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M09_120_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M10_030_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M10_010_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M10_040_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M10_030_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M10_060_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M10_040_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M11_010_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M10_060_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M11_030_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M11_010_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M11_040_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M11_030_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M11_050_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M11_040_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M11_060_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M11_050_ISHIZUMAI_FREE_START
end
function ISHIZUMAITbl.M11_090_ISHIZUMAI_FREE_START()
  return ISHIZUMAITbl.M11_060_ISHIZUMAI_FREE_START
end

