function IWAPARESUTbl.M02_010_IWAPARESU_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("IWAPARESU"))
  WINDOW:SysMsg(-833315010)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("IWAPARESU"), result)
end
function IWAPARESUTbl.M02_030_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M02_010_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M02_050_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M02_030_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M02_070_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M02_050_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M02_080_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M02_070_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M02_090_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M02_080_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M02_100_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M02_090_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M02_115_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M02_100_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M02_130_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M02_115_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M02_160_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M02_130_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M03_010_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M02_160_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M03_020_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M03_010_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M03_045_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M03_020_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M03_090_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M03_045_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M03_110_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M03_090_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M03_130_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M03_110_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M03_150_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M03_130_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M04_010_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M03_150_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M04_020_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M04_010_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M04_HANYOU_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M04_020_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M04_040_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M04_HANYOU_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M04_060_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M04_040_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M04_070_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M04_060_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M04_HANYOU_IWAPARESU_FREE_START2()
  return IWAPARESUTbl.M04_070_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M05_000_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M04_HANYOU_IWAPARESU_FREE_START2
end
function IWAPARESUTbl.M05_010_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M05_000_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M05_020_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M05_010_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M05_030_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M05_020_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M06_HANYOU_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M05_030_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M06_010_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M06_HANYOU_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M06_015_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M06_010_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M06_020_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M06_015_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M06_030_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M06_020_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M06_040_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M06_030_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M06_060_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M06_040_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M07_000_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M06_060_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M07_010_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M07_000_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M07_020_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M07_010_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M07_045_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M07_020_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M07_HANYOU_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M07_045_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M07_080_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M07_HANYOU_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M08_010_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M07_080_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M08_HANYOU_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M08_010_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M08_020_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M08_HANYOU_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M08_040_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M08_020_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M08_050_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M08_040_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M08_055_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M08_050_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M08_070_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M08_055_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M09_HANYOU_IWAPARESU_FREE_START1()
  return IWAPARESUTbl.M08_070_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M09_010_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M09_HANYOU_IWAPARESU_FREE_START1
end
function IWAPARESUTbl.M09_020_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M09_010_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M09_040_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M09_020_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M09_HANYOU_IWAPARESU_FREE_START2()
  return IWAPARESUTbl.M09_040_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M09_060_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M09_HANYOU_IWAPARESU_FREE_START2
end
function IWAPARESUTbl.M09_080_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M09_060_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M09_100_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M09_080_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M09_110_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M09_100_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M09_120_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M09_110_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M10_010_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M09_120_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M10_030_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M10_010_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M10_040_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M10_030_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M10_060_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M10_040_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M11_010_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M10_060_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M11_030_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M11_010_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M11_040_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M11_030_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M11_050_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M11_040_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M11_060_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M11_050_IWAPARESU_FREE_START
end
function IWAPARESUTbl.M11_090_IWAPARESU_FREE_START()
  return IWAPARESUTbl.M11_060_IWAPARESU_FREE_START
end

