function KAKUREONTbl.M12_010_KAKUREON_FREE_START()
  return KAKUREONTbl.M11_090_KAKUREON_FREE_START
end
function KAKUREONTbl.M12_020_KAKUREON_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("KAKUREON"))
  if FLAG.KakureonCounter == CONST.CNT_1 then
    WINDOW:DrawFace(20, 88, SymAct("KAKUREON"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("KAKUREON"), 753006060)
    WINDOW:Talk(SymAct("KAKUREON"), 905626797)
    WINDOW:Talk(SymAct("KAKUREON"), 517445486)
    WINDOW:Talk(SymAct("KAKUREON"), 130852399)
    WINDOW:Talk(SymAct("KAKUREON"), 1217212648)
    WINDOW:Talk(SymAct("KAKUREON"), 1368785321)
    WINDOW:CloseMessage()
    FLAG.KakureonCounter = CONST.CNT_2
  end
  OpenShopMerchantMenu()
  subUsuComFuncTalkOutBase01(CH("KAKUREON"), result)
end
function KAKUREONTbl.M12_030_KAKUREON_FREE_START()
  return KAKUREONTbl.M12_020_KAKUREON_FREE_START
end
function KAKUREONTbl.M12_040_KAKUREON_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("KAKUREON"))
  if FLAG.KakureonCounter == CONST.CNT_1 then
    CH("KAKUREON"):SetFacialMotion(FACIAL_MOTION.HAPPY)
    WINDOW:DrawFace(20, 88, SymAct("KAKUREON"), FACE_TYPE.HAPPY)
    WINDOW:Talk(SymAct("KAKUREON"), 2059096682)
    WINDOW:Talk(SymAct("KAKUREON"), 1671455531)
    WINDOW:CloseMessage()
    CH("KAKUREON"):SetFacialMotion(FACIAL_MOTION.NORMAL)
    FLAG.KakureonCounter = CONST.CNT_2
  end
  OpenShopMerchantMenu()
  subUsuComFuncTalkOutBase01(CH("KAKUREON"), result)
end
function KAKUREONTbl.M12_050_KAKUREON_FREE_START()
  return KAKUREONTbl.M12_040_KAKUREON_FREE_START
end
function KAKUREONTbl.M12_070_KAKUREON_FREE_START()
  return KAKUREONTbl.M12_050_KAKUREON_FREE_START
end
function KAKUREONTbl.M13_010_KAKUREON_FREE_START()
  return KAKUREONTbl.M12_070_KAKUREON_FREE_START
end
function KAKUREONTbl.M13_030_KAKUREON_FREE_START()
  return KAKUREONTbl.M13_010_KAKUREON_FREE_START
end
function KAKUREONTbl.M13_040_KAKUREON_FREE_START()
  return KAKUREONTbl.M13_030_KAKUREON_FREE_START
end
function KAKUREONTbl.M13_060_KAKUREON_FREE_START()
  return KAKUREONTbl.M13_040_KAKUREON_FREE_START
end
function KAKUREONTbl.M13_070_KAKUREON_FREE_START()
  return KAKUREONTbl.M13_060_KAKUREON_FREE_START
end
function KAKUREONTbl.M13_080_KAKUREON_FREE_START()
  return KAKUREONTbl.M13_070_KAKUREON_FREE_START
end
function KAKUREONTbl.M13_090_KAKUREON_FREE_START()
  return KAKUREONTbl.M13_080_KAKUREON_FREE_START
end
function KAKUREONTbl.M13_095_KAKUREON_FREE_START()
  return KAKUREONTbl.M13_090_KAKUREON_FREE_START
end
function KAKUREONTbl.M13_110_KAKUREON_FREE_START()
  return KAKUREONTbl.M13_095_KAKUREON_FREE_START
end
function KAKUREONTbl.M14_010_KAKUREON_FREE_START()
  return KAKUREONTbl.M13_110_KAKUREON_FREE_START
end
function KAKUREONTbl.M14_030_KAKUREON_FREE_START()
  return KAKUREONTbl.M14_010_KAKUREON_FREE_START
end
function KAKUREONTbl.M14_040_KAKUREON_FREE_START()
  return KAKUREONTbl.M14_030_KAKUREON_FREE_START
end
function KAKUREONTbl.M14_060_KAKUREON_FREE_START()
  return KAKUREONTbl.M14_040_KAKUREON_FREE_START
end
function KAKUREONTbl.M14_070_KAKUREON_FREE_START()
  return KAKUREONTbl.M14_060_KAKUREON_FREE_START
end
function KAKUREONTbl.M14_090_KAKUREON_FREE_START()
  return KAKUREONTbl.M14_070_KAKUREON_FREE_START
end
function KAKUREONTbl.M15_010_KAKUREON_FREE_START()
  return KAKUREONTbl.M14_090_KAKUREON_FREE_START
end
function KAKUREONTbl.M15_020_KAKUREON_FREE_START()
  return KAKUREONTbl.M15_010_KAKUREON_FREE_START
end
function KAKUREONTbl.M15_030_KAKUREON_FREE_START()
  return KAKUREONTbl.M15_020_KAKUREON_FREE_START
end
function KAKUREONTbl.M16_010_KAKUREON_FREE_START()
  return KAKUREONTbl.M15_030_KAKUREON_FREE_START
end
function KAKUREONTbl.M16_040_KAKUREON_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("KAKUREON"))
  if FLAG.KakureonCounter == CONST.CNT_1 then
    CH("KAKUREON"):SetFacialMotion(FACIAL_MOTION.SAD)
    WINDOW:DrawFace(20, 88, SymAct("KAKUREON"), FACE_TYPE.SAD)
    WINDOW:Talk(SymAct("KAKUREON"), -466059292)
    WINDOW:Talk(SymAct("KAKUREON"), -48017755)
    WINDOW:Talk(SymAct("KAKUREON"), 423613947)
    WINDOW:Talk(SymAct("KAKUREON"), 2417850)
    WINDOW:KeyWait()
    CH("KAKUREON"):SetFacialMotion(FACIAL_MOTION.NORMAL)
    WINDOW:DrawFace(20, 88, SymAct("KAKUREON"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("KAKUREON"), 722057081)
    WINDOW:CloseMessage()
    FLAG.KakureonCounter = CONST.CNT_2
  end
  OpenShopMerchantMenu()
  subUsuComFuncTalkOutBase01(CH("KAKUREON"), result)
end
function KAKUREONTbl.M16_080_KAKUREON_FREE_START()
  return KAKUREONTbl.M16_040_KAKUREON_FREE_START
end
function KAKUREONTbl.M16_090_KAKUREON_FREE_START()
  return KAKUREONTbl.M16_080_KAKUREON_FREE_START
end
function KAKUREONTbl.M16_100_KAKUREON_FREE_START()
  return KAKUREONTbl.M16_090_KAKUREON_FREE_START
end
function KAKUREONTbl.M16_105_KAKUREON_FREE_START()
  return KAKUREONTbl.M16_100_KAKUREON_FREE_START
end
function KAKUREONTbl.M16_120_KAKUREON_FREE_START()
  return KAKUREONTbl.M16_105_KAKUREON_FREE_START
end
function KAKUREONTbl.M17_020_KAKUREON_FREE_START()
  return KAKUREONTbl.M16_120_KAKUREON_FREE_START
end
function KAKUREONTbl.M17_040_KAKUREON_FREE_START()
  return KAKUREONTbl.M17_020_KAKUREON_FREE_START
end
function KAKUREONTbl.M17_060_KAKUREON_FREE_START()
  return KAKUREONTbl.M17_040_KAKUREON_FREE_START
end
function KAKUREONTbl.M17_065_KAKUREON_FREE_START()
  return KAKUREONTbl.M17_060_KAKUREON_FREE_START
end
function KAKUREONTbl.M17_090_KAKUREON_FREE_START()
  return KAKUREONTbl.M17_065_KAKUREON_FREE_START
end
function KAKUREONTbl.M17_120_KAKUREON_FREE_START()
  return KAKUREONTbl.M17_090_KAKUREON_FREE_START
end
function KAKUREONTbl.M17_140_KAKUREON_FREE_START()
  return KAKUREONTbl.M17_120_KAKUREON_FREE_START
end
function KAKUREONTbl.M17_150_KAKUREON_FREE_START()
  return KAKUREONTbl.M17_140_KAKUREON_FREE_START
end
function KAKUREONTbl.M17_155_KAKUREON_FREE_START()
  return KAKUREONTbl.M17_150_KAKUREON_FREE_START
end
function KAKUREONTbl.M17_170_KAKUREON_FREE_START()
  return KAKUREONTbl.M17_155_KAKUREON_FREE_START
end
function KAKUREONTbl.M17_200_KAKUREON_FREE_START()
  return KAKUREONTbl.M17_170_KAKUREON_FREE_START
end
function KAKUREONTbl.M17_210_KAKUREON_FREE_START()
  return KAKUREONTbl.M17_200_KAKUREON_FREE_START
end
function KAKUREONTbl.M17_220_KAKUREON_FREE_START()
  return KAKUREONTbl.M17_210_KAKUREON_FREE_START
end
function KAKUREONTbl.M17_225_KAKUREON_FREE_START()
  return KAKUREONTbl.M17_220_KAKUREON_FREE_START
end
function KAKUREONTbl.M17_240_KAKUREON_FREE_START()
  return KAKUREONTbl.M17_225_KAKUREON_FREE_START
end
function KAKUREONTbl.M18_020_KAKUREON_FREE_START()
  return KAKUREONTbl.M17_240_KAKUREON_FREE_START
end
function KAKUREONTbl.M18_030_KAKUREON_FREE_START()
  return KAKUREONTbl.M18_020_KAKUREON_FREE_START
end
function KAKUREONTbl.S01_010_KAKUREON_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("KAKUREON"))
  if FLAG.KakureonCounter == CONST.CNT_1 then
    CH("KAKUREON"):SetFacialMotion(FACIAL_MOTION.HAPPY)
    WINDOW:DrawFace(20, 88, SymAct("KAKUREON"), FACE_TYPE.HAPPY)
    WINDOW:Talk(SymAct("KAKUREON"), 840074808)
    WINDOW:Talk(SymAct("KAKUREON"), 2102595839)
    WINDOW:CloseMessage()
    CH("KAKUREON"):SetFacialMotion(FACIAL_MOTION.NORMAL)
    FLAG.KakureonCounter = CONST.CNT_2
  end
  OpenShopMerchantMenu()
  subUsuComFuncTalkOutBase01(CH("KAKUREON"), result)
end
function KAKUREONTbl.S01_020_KAKUREON_FREE_START()
  return KAKUREONTbl.S01_010_KAKUREON_FREE_START
end
function KAKUREONTbl.S01_030_KAKUREON_FREE_START()
  return KAKUREONTbl.S01_020_KAKUREON_FREE_START
end
function KAKUREONTbl.S01_040_KAKUREON_FREE_START()
  return KAKUREONTbl.S01_030_KAKUREON_FREE_START
end
function KAKUREONTbl.S01_050_KAKUREON_FREE_START()
  return KAKUREONTbl.S01_040_KAKUREON_FREE_START
end
function KAKUREONTbl.S01_060_KAKUREON_FREE_START()
  return KAKUREONTbl.S01_050_KAKUREON_FREE_START
end
function KAKUREONTbl.S01_080_KAKUREON_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("KAKUREON"))
  if FLAG.KakureonCounter == CONST.CNT_1 then
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
    CH("KAKUREON"):SetManpu("MP_SHOCK_L")
    CH("KAKUREON"):WaitManpu()
    WINDOW:DrawFace(20, 88, SymAct("KAKUREON"), FACE_TYPE.SURPRISE)
    WINDOW:Talk(SymAct("KAKUREON"), 1682448830)
    WINDOW:Talk(SymAct("KAKUREON"), 1332048509)
    WINDOW:Talk(SymAct("KAKUREON"), 1451115324)
    WINDOW:KeyWait()
    TASK:Regist(subEveDoubleJump, {
      CH("KAKUREON")
    })
    CH("KAKUREON"):SetFacialMotion(FACIAL_MOTION.HAPPY)
    WINDOW:DrawFace(20, 88, SymAct("KAKUREON"), FACE_TYPE.HAPPY)
    WINDOW:Talk(SymAct("KAKUREON"), -773431309)
    WINDOW:Talk(SymAct("KAKUREON"), -922915150)
    WINDOW:Talk(SymAct("KAKUREON"), 193624597)
    WINDOW:CloseMessage()
    CH("KAKUREON"):SetFacialMotion(FACIAL_MOTION.NORMAL)
    FLAG.KakureonCounter = CONST.CNT_2
  end
  OpenShopMerchantMenu()
  subUsuComFuncTalkOutBase01(CH("KAKUREON"), result)
end
function KAKUREONTbl.ALL_CLEAR_KAKUREON_FREE_START()
  return KAKUREONTbl.S01_080_KAKUREON_FREE_START
end

