function KERUDYIOTbl.M12_010_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M11_090_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M12_020_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M12_010_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M12_030_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M12_020_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M12_040_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M12_030_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M12_050_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M12_040_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M12_070_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M12_050_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M13_010_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M12_070_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M13_030_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M13_010_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M13_040_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M13_030_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M13_060_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M13_040_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M13_070_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M13_060_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M13_080_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M13_070_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M13_090_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M13_080_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M13_095_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M13_090_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M13_110_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M13_095_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M14_010_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M13_110_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M14_030_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M14_010_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M14_040_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M14_030_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M14_060_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M14_040_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M14_070_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M14_060_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M14_090_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M14_070_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M15_010_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M14_090_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M15_020_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M15_010_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M15_030_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M15_020_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M16_010_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M15_030_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M16_040_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M16_010_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M16_080_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M16_040_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M16_090_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M16_080_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M16_100_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M16_090_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M16_105_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M16_100_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M16_120_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M16_105_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M17_020_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M16_120_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M17_040_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M17_020_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M17_060_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M17_040_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M17_065_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M17_060_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M17_090_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M17_065_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M17_120_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M17_090_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M17_140_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M17_120_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M17_150_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M17_140_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M17_155_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M17_150_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M17_170_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M17_155_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M17_200_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M17_170_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M17_210_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M17_200_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M17_220_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M17_210_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M17_225_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M17_220_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M17_240_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M17_225_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M18_020_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M17_240_KERUDYIO_FREE_START
end
function KERUDYIOTbl.M18_030_KERUDYIO_FREE_START()
  return KERUDYIOTbl.M18_020_KERUDYIO_FREE_START
end
function KERUDYIOTbl.S01_010_KERUDYIO_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("KERUDYIO"))
  WINDOW:DrawFace(20, 88, SymAct("KERUDYIO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KERUDYIO"), -1837376577)
  WINDOW:Talk(SymAct("KERUDYIO"), -1956582658)
  WINDOW:Talk(SymAct("KERUDYIO"), -1605519043)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("KERUDYIO"), result)
end
function KERUDYIOTbl.S01_020_KERUDYIO_FREE_START()
  return KERUDYIOTbl.S01_010_KERUDYIO_FREE_START
end
function KERUDYIOTbl.S01_030_KERUDYIO_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("KERUDYIO"))
  WINDOW:DrawFace(20, 88, SymAct("KERUDYIO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KERUDYIO"), -1185511300)
  WINDOW:Talk(SymAct("KERUDYIO"), -166256965)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("KERUDYIO"), result)
end
function KERUDYIOTbl.S01_040_KERUDYIO_FREE_START()
  return KERUDYIOTbl.S01_030_KERUDYIO_FREE_START
end
function KERUDYIOTbl.S01_050_KERUDYIO_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("KERUDYIO"))
  WINDOW:DrawFace(20, 88, SymAct("KERUDYIO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KERUDYIO"), -284413958)
  WINDOW:Talk(SymAct("KERUDYIO"), -1004438471)
  WINDOW:Talk(SymAct("KERUDYIO"), -583381640)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("KERUDYIO"), result)
end
function KERUDYIOTbl.S01_060_KERUDYIO_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("KERUDYIO"))
  WINDOW:DrawFace(20, 88, SymAct("KERUDYIO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KERUDYIO"), 1520587191)
  WINDOW:Talk(SymAct("KERUDYIO"), 1136222454)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("KERUDYIO"), result)
end
function KERUDYIOTbl.S01_080_KERUDYIO_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("KERUDYIO"))
  CH("KERUDYIO"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(20, 88, SymAct("KERUDYIO"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("KERUDYIO"), 1417635897)
  WINDOW:Talk(SymAct("KERUDYIO"), 1298422136)
  WINDOW:Talk(SymAct("KERUDYIO"), 1716062907)
  WINDOW:CloseMessage()
  CH("KERUDYIO"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  subUsuComFuncTalkOutBase01(CH("KERUDYIO"), result)
end
function KERUDYIOTbl.ALL_CLEAR_KERUDYIO_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("KERUDYIO"))
  WINDOW:DrawFace(20, 88, SymAct("KERUDYIO"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("KERUDYIO"), 2136095738)
  WINDOW:Talk(SymAct("KERUDYIO"), 806595901)
  WINDOW:Talk(SymAct("KERUDYIO"), 688430204)
  WINDOW:Talk(SymAct("KERUDYIO"), 36032447)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("KERUDYIO"), result)
end

