function KOARUHIITbl.M12_010_KOARUHII_FREE_START()
  return KOARUHIITbl.M11_090_KOARUHII_FREE_START
end
function KOARUHIITbl.M12_020_KOARUHII_FREE_START()
  local result = subUsuComFuncTalkInBase02(CH("KOARUHII"))
  SOUND:PlaySe(SymSnd("SE_EVT_ZZZ"), Volume(256))
  CH("KOARUHII"):SetManpu("MP_SLEEP_LP")
  WINDOW:Talk(SymAct("KOARUHII"), 878638659)
  WINDOW:Talk(SymAct("KOARUHII"), 759547650)
  WINDOW:Talk(SymAct("KOARUHII"), 107517121)
  WINDOW:Talk(SymAct("KOARUHII"), 527672704)
  WINDOW:Talk(SymAct("KOARUHII"), 1345467207)
  WINDOW:CloseMessage()
  CH("KOARUHII"):ResetManpu()
  SOUND:FadeOutSe(SymSnd("SE_EVT_ZZZ"), TimeSec(0.2))
  subUsuComFuncTalkOutBase02(CH("KOARUHII"), result)
end
function KOARUHIITbl.M12_030_KOARUHII_FREE_START()
  return KOARUHIITbl.M12_020_KOARUHII_FREE_START
end
function KOARUHIITbl.M12_040_KOARUHII_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("KOARUHII"))
  WINDOW:DrawFace(20, 88, SymAct("KOARUHII"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("KOARUHII"), 1227424262)
  WINDOW:Talk(SymAct("KOARUHII"), 1644450245)
  WINDOW:Talk(SymAct("KOARUHII"), 2065653892)
  WINDOW:Talk(SymAct("KOARUHII"), -58229685)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("KOARUHII"), result)
end
function KOARUHIITbl.M12_050_KOARUHII_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("KOARUHII"))
  WINDOW:DrawFace(20, 88, SymAct("KOARUHII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KOARUHII"), -442741494)
  WINDOW:Talk(SymAct("KOARUHII"), -1448526632)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("KOARUHII"), result)
end
function KOARUHIITbl.M12_070_KOARUHII_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("KOARUHII"))
  WINDOW:DrawFace(20, 88, SymAct("KOARUHII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KOARUHII"), -1330508391)
  WINDOW:DrawFace(20, 88, SymAct("KOARUHII"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("KOARUHII"), -1684054438)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("KOARUHII"), result)
end
function KOARUHIITbl.M13_010_KOARUHII_FREE_START()
  return KOARUHIITbl.M12_070_KOARUHII_FREE_START
end
function KOARUHIITbl.M13_030_KOARUHII_FREE_START()
  return KOARUHIITbl.M13_010_KOARUHII_FREE_START
end
function KOARUHIITbl.M13_040_KOARUHII_FREE_START()
  return KOARUHIITbl.M13_030_KOARUHII_FREE_START
end
function KOARUHIITbl.M13_060_KOARUHII_FREE_START()
  return KOARUHIITbl.M13_040_KOARUHII_FREE_START
end
function KOARUHIITbl.M13_070_KOARUHII_FREE_START()
  return KOARUHIITbl.M13_060_KOARUHII_FREE_START
end
function KOARUHIITbl.M13_080_KOARUHII_FREE_START()
  return KOARUHIITbl.M13_070_KOARUHII_FREE_START
end
function KOARUHIITbl.M13_090_KOARUHII_FREE_START()
  return KOARUHIITbl.M13_080_KOARUHII_FREE_START
end
function KOARUHIITbl.M13_095_KOARUHII_FREE_START()
  return KOARUHIITbl.M13_090_KOARUHII_FREE_START
end
function KOARUHIITbl.M13_110_KOARUHII_FREE_START()
  return KOARUHIITbl.M13_095_KOARUHII_FREE_START
end
function KOARUHIITbl.M14_010_KOARUHII_FREE_START()
  return KOARUHIITbl.M13_110_KOARUHII_FREE_START
end
function KOARUHIITbl.M14_030_KOARUHII_FREE_START()
  return KOARUHIITbl.M14_010_KOARUHII_FREE_START
end
function KOARUHIITbl.M14_040_KOARUHII_FREE_START()
  return KOARUHIITbl.M14_030_KOARUHII_FREE_START
end
function KOARUHIITbl.M14_060_KOARUHII_FREE_START()
  return KOARUHIITbl.M14_040_KOARUHII_FREE_START
end
function KOARUHIITbl.M14_070_KOARUHII_FREE_START()
  return KOARUHIITbl.M14_060_KOARUHII_FREE_START
end
function KOARUHIITbl.M14_090_KOARUHII_FREE_START()
  return KOARUHIITbl.M14_070_KOARUHII_FREE_START
end
function KOARUHIITbl.M15_010_KOARUHII_FREE_START()
  return KOARUHIITbl.M14_090_KOARUHII_FREE_START
end
function KOARUHIITbl.M15_020_KOARUHII_FREE_START()
  return KOARUHIITbl.M15_010_KOARUHII_FREE_START
end
function KOARUHIITbl.M15_030_KOARUHII_FREE_START()
  return KOARUHIITbl.M15_020_KOARUHII_FREE_START
end
function KOARUHIITbl.M16_010_KOARUHII_FREE_START()
  return KOARUHIITbl.M15_030_KOARUHII_FREE_START
end
function KOARUHIITbl.M16_040_KOARUHII_FREE_START()
  return KOARUHIITbl.M16_010_KOARUHII_FREE_START
end
function KOARUHIITbl.M16_080_KOARUHII_FREE_START()
  return KOARUHIITbl.M16_040_KOARUHII_FREE_START
end
function KOARUHIITbl.M16_090_KOARUHII_FREE_START()
  return KOARUHIITbl.M16_080_KOARUHII_FREE_START
end
function KOARUHIITbl.M16_100_KOARUHII_FREE_START()
  return KOARUHIITbl.M16_090_KOARUHII_FREE_START
end
function KOARUHIITbl.M16_105_KOARUHII_FREE_START()
  return KOARUHIITbl.M16_100_KOARUHII_FREE_START
end
function KOARUHIITbl.M16_120_KOARUHII_FREE_START()
  return KOARUHIITbl.M16_105_KOARUHII_FREE_START
end
function KOARUHIITbl.M17_020_KOARUHII_FREE_START()
  return KOARUHIITbl.M16_120_KOARUHII_FREE_START
end
function KOARUHIITbl.M17_040_KOARUHII_FREE_START()
  return KOARUHIITbl.M17_020_KOARUHII_FREE_START
end
function KOARUHIITbl.M17_060_KOARUHII_FREE_START()
  return KOARUHIITbl.M17_040_KOARUHII_FREE_START
end
function KOARUHIITbl.M17_065_KOARUHII_FREE_START()
  return KOARUHIITbl.M17_060_KOARUHII_FREE_START
end
function KOARUHIITbl.M17_090_KOARUHII_FREE_START()
  return KOARUHIITbl.M17_065_KOARUHII_FREE_START
end
function KOARUHIITbl.M17_120_KOARUHII_FREE_START()
  return KOARUHIITbl.M17_090_KOARUHII_FREE_START
end
function KOARUHIITbl.M17_140_KOARUHII_FREE_START()
  return KOARUHIITbl.M17_120_KOARUHII_FREE_START
end
function KOARUHIITbl.M17_150_KOARUHII_FREE_START()
  return KOARUHIITbl.M17_140_KOARUHII_FREE_START
end
function KOARUHIITbl.M17_155_KOARUHII_FREE_START()
  return KOARUHIITbl.M17_150_KOARUHII_FREE_START
end
function KOARUHIITbl.M17_170_KOARUHII_FREE_START()
  return KOARUHIITbl.M17_155_KOARUHII_FREE_START
end
function KOARUHIITbl.M17_200_KOARUHII_FREE_START()
  return KOARUHIITbl.M17_170_KOARUHII_FREE_START
end
function KOARUHIITbl.M17_210_KOARUHII_FREE_START()
  return KOARUHIITbl.M17_200_KOARUHII_FREE_START
end
function KOARUHIITbl.M17_220_KOARUHII_FREE_START()
  return KOARUHIITbl.M17_210_KOARUHII_FREE_START
end
function KOARUHIITbl.M17_225_KOARUHII_FREE_START()
  return KOARUHIITbl.M17_220_KOARUHII_FREE_START
end
function KOARUHIITbl.M17_240_KOARUHII_FREE_START()
  return KOARUHIITbl.M17_225_KOARUHII_FREE_START
end
function KOARUHIITbl.M18_020_KOARUHII_FREE_START()
  return KOARUHIITbl.M17_240_KOARUHII_FREE_START
end
function KOARUHIITbl.M18_030_KOARUHII_FREE_START()
  return KOARUHIITbl.M18_020_KOARUHII_FREE_START
end
function KOARUHIITbl.S01_010_KOARUHII_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("KOARUHII"))
  WINDOW:DrawFace(20, 88, SymAct("KOARUHII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KOARUHII"), -2105250021)
  WINDOW:Talk(SymAct("KOARUHII"), -842663460)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("KOARUHII"), result)
end
function KOARUHIITbl.S01_020_KOARUHII_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("KOARUHII"))
  WINDOW:DrawFace(20, 88, SymAct("KOARUHII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KOARUHII"), -723597155)
  WINDOW:Talk(SymAct("KOARUHII"), -812194)
  WINDOW:Talk(SymAct("KOARUHII"), -420959713)
  WINDOW:Talk(SymAct("KOARUHII"), 1634776784)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("KOARUHII"), result)
end
function KOARUHIITbl.S01_030_KOARUHII_FREE_START()
  return KOARUHIITbl.S01_020_KOARUHII_FREE_START
end
function KOARUHIITbl.S01_040_KOARUHII_FREE_START()
  return KOARUHIITbl.S01_030_KOARUHII_FREE_START
end
function KOARUHIITbl.S01_050_KOARUHII_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("KOARUHII"))
  WINDOW:DrawFace(20, 88, SymAct("KOARUHII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KOARUHII"), 2020312977)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("KOARUHII"), result)
end
function KOARUHIITbl.S01_060_KOARUHII_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("KOARUHII"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("KOARUHII"):SetManpu("MP_EXCLAMATION")
  CH("KOARUHII"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("KOARUHII"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("KOARUHII"), -1155755210)
  WINDOW:Talk(SymAct("KOARUHII"), -1576557961)
  WINDOW:Talk(SymAct("KOARUHII"), -1993674316)
  WINDOW:KeyWait()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("KOARUHII"):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFace(20, 88, SymAct("KOARUHII"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("KOARUHII"), -1875787531)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("KOARUHII"), result)
end
function KOARUHIITbl.S01_080_KOARUHII_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("KOARUHII"))
  if FLAG.KoaruhiiCounter == CONST.CNT_1 then
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
    CH("KOARUHII"):SetManpu("MP_EXCLAMATION")
    CH("KOARUHII"):WaitManpu()
    WINDOW:DrawFace(20, 88, SymAct("KOARUHII"), FACE_TYPE.SURPRISE)
    WINDOW:Talk(SymAct("KOARUHII"), -546286030)
    WINDOW:Talk(SymAct("KOARUHII"), -966039693)
    WINDOW:DrawFace(20, 88, SymAct("KOARUHII"), FACE_TYPE.SAD)
    WINDOW:Talk(SymAct("KOARUHII"), -314166096)
    WINDOW:Talk(SymAct("KOARUHII"), -195230223)
    WINDOW:Talk(SymAct("KOARUHII"), 1942296894)
    WINDOW:Talk(SymAct("KOARUHII"), 1792944255)
    WINDOW:Talk(SymAct("KOARUHII"), 60879955)
    WINDOW:KeyWait()
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
    CH("KOARUHII"):SetManpu("MP_FLY_SWEAT")
    WINDOW:DrawFace(20, 88, SymAct("KOARUHII"), FACE_TYPE.TEARS)
    WINDOW:Talk(SymAct("KOARUHII"), 448513298)
    WINDOW:Talk(SymAct("KOARUHII"), 831952593)
    WINDOW:CloseMessage()
    FLAG.KoaruhiiCounter = CONST.CNT_2
    subUsuComFuncTalkOutBase01(CH("KOARUHII"), result)
  else
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
    CH("KOARUHII"):SetManpu("MP_FLY_SWEAT")
    WINDOW:DrawFace(20, 88, SymAct("KOARUHII"), FACE_TYPE.TEARS)
    WINDOW:Talk(SymAct("KOARUHII"), 680372112)
    WINDOW:CloseMessage()
    subUsuComFuncTalkOutBase01(CH("KOARUHII"), result)
  end
end
function KOARUHIITbl.ALL_CLEAR_KOARUHII_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("KOARUHII"))
  WINDOW:DrawFace(20, 88, SymAct("KOARUHII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KOARUHII"), 1741435223)
  WINDOW:Talk(SymAct("KOARUHII"), 2128019478)
  WINDOW:Talk(SymAct("KOARUHII"), 1442468821)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("KOARUHII"), result)
end

