function KOJOFUUTbl.M12_010_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M11_090_KOJOFUU_FREE_START
end
function KOJOFUUTbl.M12_020_KOJOFUU_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("KOJOFUU"))
  WINDOW:DrawFace(20, 88, SymAct("KOJOFUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KOJOFUU"), -1680297700)
  WINDOW:Talk(SymAct("KOJOFUU"), -2101116835)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("KOJOFUU"), result)
end
function KOJOFUUTbl.M12_030_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M12_020_KOJOFUU_FREE_START
end
function KOJOFUUTbl.M12_040_KOJOFUU_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("KOJOFUU"))
  WINDOW:DrawFace(20, 88, SymAct("KOJOFUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KOJOFUU"), -1443966050)
  WINDOW:Talk(SymAct("KOJOFUU"), -1326062881)
  WINDOW:Talk(SymAct("KOJOFUU"), -4951016)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("KOJOFUU"), result)
end
function KOJOFUUTbl.M12_050_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M12_040_KOJOFUU_FREE_START
end
function KOJOFUUTbl.M12_070_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M12_050_KOJOFUU_FREE_START
end
function KOJOFUUTbl.M13_010_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M12_070_KOJOFUU_FREE_START
end
function KOJOFUUTbl.M13_030_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M13_010_KOJOFUU_FREE_START
end
function KOJOFUUTbl.M13_040_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M13_030_KOJOFUU_FREE_START
end
function KOJOFUUTbl.M13_060_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M13_040_KOJOFUU_FREE_START
end
function KOJOFUUTbl.M13_070_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M13_060_KOJOFUU_FREE_START
end
function KOJOFUUTbl.M13_080_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M13_070_KOJOFUU_FREE_START
end
function KOJOFUUTbl.M13_090_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M13_080_KOJOFUU_FREE_START
end
function KOJOFUUTbl.M13_095_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M13_090_KOJOFUU_FREE_START
end
function KOJOFUUTbl.M13_110_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M13_095_KOJOFUU_FREE_START
end
function KOJOFUUTbl.M14_010_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M13_110_KOJOFUU_FREE_START
end
function KOJOFUUTbl.M14_030_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M14_010_KOJOFUU_FREE_START
end
function KOJOFUUTbl.M14_040_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M14_030_KOJOFUU_FREE_START
end
function KOJOFUUTbl.M14_060_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M14_040_KOJOFUU_FREE_START
end
function KOJOFUUTbl.M14_070_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M14_060_KOJOFUU_FREE_START
end
function KOJOFUUTbl.M14_090_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M14_070_KOJOFUU_FREE_START
end
function KOJOFUUTbl.M15_010_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M14_090_KOJOFUU_FREE_START
end
function KOJOFUUTbl.M15_020_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M15_010_KOJOFUU_FREE_START
end
function KOJOFUUTbl.M15_030_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M15_020_KOJOFUU_FREE_START
end
function KOJOFUUTbl.M16_010_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M15_030_KOJOFUU_FREE_START
end
function KOJOFUUTbl.M16_040_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M16_010_KOJOFUU_FREE_START
end
function KOJOFUUTbl.M16_080_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M16_040_KOJOFUU_FREE_START
end
function KOJOFUUTbl.M16_090_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M16_080_KOJOFUU_FREE_START
end
function KOJOFUUTbl.M16_100_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M16_090_KOJOFUU_FREE_START
end
function KOJOFUUTbl.M16_105_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M16_100_KOJOFUU_FREE_START
end
function KOJOFUUTbl.M16_120_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M16_105_KOJOFUU_FREE_START
end
function KOJOFUUTbl.M17_020_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M16_120_KOJOFUU_FREE_START
end
function KOJOFUUTbl.M17_040_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M17_020_KOJOFUU_FREE_START
end
function KOJOFUUTbl.M17_060_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M17_040_KOJOFUU_FREE_START
end
function KOJOFUUTbl.M17_065_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M17_060_KOJOFUU_FREE_START
end
function KOJOFUUTbl.M17_090_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M17_065_KOJOFUU_FREE_START
end
function KOJOFUUTbl.M17_120_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M17_090_KOJOFUU_FREE_START
end
function KOJOFUUTbl.M17_140_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M17_120_KOJOFUU_FREE_START
end
function KOJOFUUTbl.M17_150_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M17_140_KOJOFUU_FREE_START
end
function KOJOFUUTbl.M17_155_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M17_150_KOJOFUU_FREE_START
end
function KOJOFUUTbl.M17_170_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M17_155_KOJOFUU_FREE_START
end
function KOJOFUUTbl.M17_200_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M17_170_KOJOFUU_FREE_START
end
function KOJOFUUTbl.M17_210_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M17_200_KOJOFUU_FREE_START
end
function KOJOFUUTbl.M17_220_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M17_210_KOJOFUU_FREE_START
end
function KOJOFUUTbl.M17_225_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M17_220_KOJOFUU_FREE_START
end
function KOJOFUUTbl.M17_240_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M17_225_KOJOFUU_FREE_START
end
function KOJOFUUTbl.M18_020_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M17_240_KOJOFUU_FREE_START
end
function KOJOFUUTbl.M18_030_KOJOFUU_FREE_START()
  return KOJOFUUTbl.M18_020_KOJOFUU_FREE_START
end
function KOJOFUUTbl.S01_010_KOJOFUU_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("KOJOFUU"))
  WINDOW:DrawFace(20, 88, SymAct("KOJOFUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KOJOFUU"), -424721063)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("KOJOFUU"), result)
end
function KOJOFUUTbl.S01_020_KOJOFUU_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("KOJOFUU"))
  WINDOW:DrawFace(20, 88, SymAct("KOJOFUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KOJOFUU"), -847112550)
  WINDOW:Talk(SymAct("KOJOFUU"), -728160293)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("KOJOFUU"), result)
end
function KOJOFUUTbl.S01_030_KOJOFUU_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("KOJOFUU"))
  WINDOW:DrawFace(20, 88, SymAct("KOJOFUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KOJOFUU"), 1392589588)
  WINDOW:Talk(SymAct("KOJOFUU"), 1243220565)
  WINDOW:Talk(SymAct("KOJOFUU"), 2083653366)
  WINDOW:Talk(SymAct("KOJOFUU"), 1697200055)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("KOJOFUU"):SetManpu("MP_QUESTION")
  CH("KOJOFUU"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("KOJOFUU"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("KOJOFUU"), 1308910708)
  WINDOW:KeyWait()
  CH("KOJOFUU"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(20, 88, SymAct("KOJOFUU"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("KOJOFUU"), 1461671221)
  WINDOW:CloseMessage()
  CH("KOJOFUU"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  subUsuComFuncTalkOutBase01(CH("KOJOFUU"), result)
end
function KOJOFUUTbl.S01_040_KOJOFUU_FREE_START()
  return KOJOFUUTbl.S01_030_KOJOFUU_FREE_START
end
function KOJOFUUTbl.S01_050_KOJOFUU_FREE_START()
  return KOJOFUUTbl.S01_040_KOJOFUU_FREE_START
end
function KOJOFUUTbl.S01_060_KOJOFUU_FREE_START()
  return KOJOFUUTbl.S01_050_KOJOFUU_FREE_START
end
function KOJOFUUTbl.S01_080_KOJOFUU_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("KOJOFUU"))
  CH("KOJOFUU"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(20, 88, SymAct("KOJOFUU"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("KOJOFUU"), 408863730)
  WINDOW:Talk(SymAct("KOJOFUU"), 21361331)
  WINDOW:Talk(SymAct("KOJOFUU"), 711500144)
  WINDOW:Talk(SymAct("KOJOFUU"), 863211569)
  WINDOW:CloseMessage()
  CH("KOJOFUU"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  subUsuComFuncTalkOutBase01(CH("KOJOFUU"), result)
end
function KOJOFUUTbl.ALL_CLEAR_KOJOFUU_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("KOJOFUU"))
  WINDOW:DrawFace(20, 88, SymAct("KOJOFUU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KOJOFUU"), -1259631362)
  WINDOW:Talk(SymAct("KOJOFUU"), -1376731713)
  WINDOW:KeyWait()
  CH("KOJOFUU"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(20, 88, SymAct("KOJOFUU"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("KOJOFUU"), 1854384408)
  WINDOW:CloseMessage()
  CH("KOJOFUU"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  subUsuComFuncTalkOutBase01(CH("KOJOFUU"), result)
end

