function KUMASHUNTbl.M12_010_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M11_090_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M12_020_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M12_010_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M12_030_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M12_020_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M12_040_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M12_030_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M12_050_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M12_040_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M12_070_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M12_050_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M13_010_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M12_070_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M13_030_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M13_010_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M13_040_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M13_030_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M13_060_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M13_040_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M13_070_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M13_060_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M13_080_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M13_070_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M13_090_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M13_080_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M13_095_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M13_090_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M13_110_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M13_095_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M14_010_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M13_110_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M14_030_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M14_010_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M14_040_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M14_030_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M14_060_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M14_040_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M14_070_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M14_060_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M14_090_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M14_070_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M15_010_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M14_090_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M15_020_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M15_010_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M15_030_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M15_020_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M16_010_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M15_030_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M16_040_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M16_010_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M16_080_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M16_040_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M16_090_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M16_080_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M16_100_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M16_090_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M16_105_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M16_100_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M16_120_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M16_105_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M17_020_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M16_120_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M17_040_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M17_020_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M17_060_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M17_040_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M17_065_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M17_060_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M17_090_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M17_065_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M17_120_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M17_090_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M17_140_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M17_120_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M17_150_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M17_140_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M17_155_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M17_150_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M17_170_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M17_155_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M17_200_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M17_170_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M17_210_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M17_200_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M17_220_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M17_210_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M17_225_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M17_220_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M17_240_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M17_225_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M18_020_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M17_240_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M18_030_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M18_020_KUMASHUN_FREE_START
end
function KUMASHUNTbl.S01_010_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M18_030_KUMASHUN_FREE_START
end
function KUMASHUNTbl.S01_020_KUMASHUN_FREE_START()
  return KUMASHUNTbl.S01_010_KUMASHUN_FREE_START
end
function KUMASHUNTbl.S01_030_KUMASHUN_FREE_START()
  return KUMASHUNTbl.S01_020_KUMASHUN_FREE_START
end
function KUMASHUNTbl.S01_040_KUMASHUN_FREE_START()
  return KUMASHUNTbl.S01_030_KUMASHUN_FREE_START
end
function KUMASHUNTbl.S01_050_KUMASHUN_FREE_START()
  return KUMASHUNTbl.S01_040_KUMASHUN_FREE_START
end
function KUMASHUNTbl.S01_060_KUMASHUN_FREE_START()
  return KUMASHUNTbl.S01_050_KUMASHUN_FREE_START
end
function KUMASHUNTbl.S01_080_KUMASHUN_FREE_START()
  return KUMASHUNTbl.S01_060_KUMASHUN_FREE_START
end
function KUMASHUNTbl.ALL_CLEAR_KUMASHUN_FREE_START()
  return KUMASHUNTbl.S01_080_KUMASHUN_FREE_START
end

