function KUMASHUNTbl.M02_010_KUMASHUN_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("KUMASHUN"))
  WINDOW:SysMsg(-1936554979)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("KUMASHUN"), result)
end
function KUMASHUNTbl.M02_030_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M02_010_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M02_050_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M02_030_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M02_070_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M02_050_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M02_080_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M02_070_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M02_090_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M02_080_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M02_100_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M02_090_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M02_115_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M02_100_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M02_130_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M02_115_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M02_160_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M02_130_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M03_010_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M02_160_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M03_020_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M03_010_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M03_045_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M03_020_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M03_090_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M03_045_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M03_110_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M03_090_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M03_130_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M03_110_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M03_150_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M03_130_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M04_010_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M03_150_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M04_020_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M04_010_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M04_HANYOU_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M04_020_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M04_040_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M04_HANYOU_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M04_060_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M04_040_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M04_070_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M04_060_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M04_HANYOU_KUMASHUN_FREE_START2()
  return KUMASHUNTbl.M04_070_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M05_000_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M04_HANYOU_KUMASHUN_FREE_START2
end
function KUMASHUNTbl.M05_010_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M05_000_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M05_020_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M05_010_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M05_030_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M05_020_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M06_HANYOU_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M05_030_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M06_010_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M06_HANYOU_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M06_015_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M06_010_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M06_020_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M06_015_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M06_030_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M06_020_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M06_040_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M06_030_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M06_060_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M06_040_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M07_000_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M06_060_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M07_010_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M07_000_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M07_020_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M07_010_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M07_045_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M07_020_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M07_HANYOU_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M07_045_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M07_080_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M07_HANYOU_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M08_010_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M07_080_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M08_HANYOU_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M08_010_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M08_020_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M08_HANYOU_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M08_040_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M08_020_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M08_050_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M08_040_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M08_055_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M08_050_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M08_070_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M08_055_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M09_HANYOU_KUMASHUN_FREE_START1()
  return KUMASHUNTbl.M08_070_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M09_010_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M09_HANYOU_KUMASHUN_FREE_START1
end
function KUMASHUNTbl.M09_020_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M09_010_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M09_040_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M09_020_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M09_HANYOU_KUMASHUN_FREE_START2()
  return KUMASHUNTbl.M09_040_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M09_060_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M09_HANYOU_KUMASHUN_FREE_START2
end
function KUMASHUNTbl.M09_080_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M09_060_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M09_100_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M09_080_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M09_110_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M09_100_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M09_120_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M09_110_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M10_010_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M09_120_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M10_030_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M10_010_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M10_040_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M10_030_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M10_060_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M10_040_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M11_010_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M10_060_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M11_030_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M11_010_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M11_040_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M11_030_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M11_050_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M11_040_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M11_060_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M11_050_KUMASHUN_FREE_START
end
function KUMASHUNTbl.M11_090_KUMASHUN_FREE_START()
  return KUMASHUNTbl.M11_060_KUMASHUN_FREE_START
end

