function MARIRURITbl.M12_010_MARIRURI_FREE_START()
  return MARIRURITbl.M11_090_MARIRURI_FREE_START
end
function MARIRURITbl.M12_020_MARIRURI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MARIRURI"))
  if FLAG.MariruriCounter == CONST.CNT_1 then
    WINDOW:DrawFace(20, 88, SymAct("MARIRURI"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("MARIRURI"), -1912578688)
    WINDOW:Talk(SymAct("MARIRURI"), -1759810367)
    WINDOW:CloseMessage()
    FLAG.MariruriCounter = CONST.CNT_2
  end
  OpenQuestCounterMenu()
  subUsuComFuncTalkOutBase01(CH("MARIRURI"), result)
end
function MARIRURITbl.M12_030_MARIRURI_FREE_START()
  return MARIRURITbl.M12_020_MARIRURI_FREE_START
end
function MARIRURITbl.M12_040_MARIRURI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MARIRURI"))
  if FLAG.MariruriCounter == CONST.CNT_1 then
    WINDOW:DrawFace(20, 88, SymAct("MARIRURI"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("MARIRURI"), -1137295614)
    WINDOW:CloseMessage()
    FLAG.MariruriCounter = CONST.CNT_2
  end
  OpenQuestCounterMenu()
  subUsuComFuncTalkOutBase01(CH("MARIRURI"), result)
end
function MARIRURITbl.M12_050_MARIRURI_FREE_START()
  return MARIRURITbl.M12_040_MARIRURI_FREE_START
end
function MARIRURITbl.M12_070_MARIRURI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MARIRURI"))
  WINDOW:DrawFace(20, 88, SymAct("MARIRURI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MARIRURI"), -1523773885)
  WINDOW:Talk(SymAct("MARIRURI"), -361981820)
  WINDOW:Talk(SymAct("MARIRURI"), -210261563)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("MARIRURI"), result)
end
function MARIRURITbl.M13_010_MARIRURI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MARIRURI"))
  OpenQuestCounterMenu()
  subUsuComFuncTalkOutBase01(CH("MARIRURI"), result)
end
function MARIRURITbl.M13_030_MARIRURI_FREE_START()
  return MARIRURITbl.M13_010_MARIRURI_FREE_START
end
function MARIRURITbl.M13_040_MARIRURI_FREE_START()
  return MARIRURITbl.M13_030_MARIRURI_FREE_START
end
function MARIRURITbl.M13_060_MARIRURI_FREE_START()
  return MARIRURITbl.M13_040_MARIRURI_FREE_START
end
function MARIRURITbl.M13_070_MARIRURI_FREE_START()
  return MARIRURITbl.M13_060_MARIRURI_FREE_START
end
function MARIRURITbl.M13_080_MARIRURI_FREE_START()
  return MARIRURITbl.M13_070_MARIRURI_FREE_START
end
function MARIRURITbl.M13_090_MARIRURI_FREE_START()
  return MARIRURITbl.M13_080_MARIRURI_FREE_START
end
function MARIRURITbl.M13_095_MARIRURI_FREE_START()
  return MARIRURITbl.M13_090_MARIRURI_FREE_START
end
function MARIRURITbl.M13_110_MARIRURI_FREE_START()
  return MARIRURITbl.M13_095_MARIRURI_FREE_START
end
function MARIRURITbl.M14_010_MARIRURI_FREE_START()
  return MARIRURITbl.M13_110_MARIRURI_FREE_START
end
function MARIRURITbl.M14_030_MARIRURI_FREE_START()
  return MARIRURITbl.M14_010_MARIRURI_FREE_START
end
function MARIRURITbl.M14_040_MARIRURI_FREE_START()
  return MARIRURITbl.M14_030_MARIRURI_FREE_START
end
function MARIRURITbl.M14_060_MARIRURI_FREE_START()
  return MARIRURITbl.M14_040_MARIRURI_FREE_START
end
function MARIRURITbl.M14_070_MARIRURI_FREE_START()
  return MARIRURITbl.M14_060_MARIRURI_FREE_START
end
function MARIRURITbl.M14_090_MARIRURI_FREE_START()
  return MARIRURITbl.M14_070_MARIRURI_FREE_START
end
function MARIRURITbl.M15_010_MARIRURI_FREE_START()
  return MARIRURITbl.M14_090_MARIRURI_FREE_START
end
function MARIRURITbl.M15_020_MARIRURI_FREE_START()
  return MARIRURITbl.M15_010_MARIRURI_FREE_START
end
function MARIRURITbl.M15_030_MARIRURI_FREE_START()
  return MARIRURITbl.M15_020_MARIRURI_FREE_START
end
function MARIRURITbl.M16_010_MARIRURI_FREE_START()
  return MARIRURITbl.M15_030_MARIRURI_FREE_START
end
function MARIRURITbl.M16_040_MARIRURI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MARIRURI"))
  WINDOW:DrawFace(20, 88, SymAct("MARIRURI"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("MARIRURI"), -665126394)
  WINDOW:Talk(SymAct("MARIRURI"), -1052652729)
  WINDOW:Talk(SymAct("MARIRURI"), 1188681608)
  WINDOW:DrawFace(20, 88, SymAct("MARIRURI"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("MARIRURI"), 1606608585)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("MARIRURI"), result)
end
function MARIRURITbl.M16_080_MARIRURI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MARIRURI"))
  OpenQuestCounterMenu()
  subUsuComFuncTalkOutBase01(CH("MARIRURI"), result)
end
function MARIRURITbl.M16_090_MARIRURI_FREE_START()
  return MARIRURITbl.M16_080_MARIRURI_FREE_START
end
function MARIRURITbl.M16_100_MARIRURI_FREE_START()
  return MARIRURITbl.M16_090_MARIRURI_FREE_START
end
function MARIRURITbl.M16_105_MARIRURI_FREE_START()
  return MARIRURITbl.M16_100_MARIRURI_FREE_START
end
function MARIRURITbl.M16_120_MARIRURI_FREE_START()
  return MARIRURITbl.M16_105_MARIRURI_FREE_START
end
function MARIRURITbl.M17_020_MARIRURI_FREE_START()
  return MARIRURITbl.M16_120_MARIRURI_FREE_START
end
function MARIRURITbl.M17_040_MARIRURI_FREE_START()
  return MARIRURITbl.M17_020_MARIRURI_FREE_START
end
function MARIRURITbl.M17_060_MARIRURI_FREE_START()
  return MARIRURITbl.M17_040_MARIRURI_FREE_START
end
function MARIRURITbl.M17_065_MARIRURI_FREE_START()
  return MARIRURITbl.M17_060_MARIRURI_FREE_START
end
function MARIRURITbl.M17_090_MARIRURI_FREE_START()
  return MARIRURITbl.M17_065_MARIRURI_FREE_START
end
function MARIRURITbl.M17_120_MARIRURI_FREE_START()
  return MARIRURITbl.M17_090_MARIRURI_FREE_START
end
function MARIRURITbl.M17_140_MARIRURI_FREE_START()
  return MARIRURITbl.M17_120_MARIRURI_FREE_START
end
function MARIRURITbl.M17_150_MARIRURI_FREE_START()
  return MARIRURITbl.M17_140_MARIRURI_FREE_START
end
function MARIRURITbl.M17_155_MARIRURI_FREE_START()
  return MARIRURITbl.M17_150_MARIRURI_FREE_START
end
function MARIRURITbl.M17_170_MARIRURI_FREE_START()
  return MARIRURITbl.M17_155_MARIRURI_FREE_START
end
function MARIRURITbl.M17_200_MARIRURI_FREE_START()
  return MARIRURITbl.M17_170_MARIRURI_FREE_START
end
function MARIRURITbl.M17_210_MARIRURI_FREE_START()
  return MARIRURITbl.M17_200_MARIRURI_FREE_START
end
function MARIRURITbl.M17_220_MARIRURI_FREE_START()
  return MARIRURITbl.M17_210_MARIRURI_FREE_START
end
function MARIRURITbl.M17_225_MARIRURI_FREE_START()
  return MARIRURITbl.M17_220_MARIRURI_FREE_START
end
function MARIRURITbl.M17_240_MARIRURI_FREE_START()
  return MARIRURITbl.M17_225_MARIRURI_FREE_START
end
function MARIRURITbl.M18_020_MARIRURI_FREE_START()
  return MARIRURITbl.M17_240_MARIRURI_FREE_START
end
function MARIRURITbl.M18_030_MARIRURI_FREE_START()
  return MARIRURITbl.M18_020_MARIRURI_FREE_START
end
function MARIRURITbl.S01_010_MARIRURI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MARIRURI"))
  if FLAG.MariruriCounter == CONST.CNT_1 then
    WINDOW:DrawFace(20, 88, SymAct("MARIRURI"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("MARIRURI"), 142243947)
    WINDOW:CloseMessage()
    FLAG.MariruriCounter = CONST.CNT_2
  end
  OpenQuestCounterMenu()
  subUsuComFuncTalkOutBase01(CH("MARIRURI"), result)
end
function MARIRURITbl.S01_020_MARIRURI_FREE_START()
  return MARIRURITbl.S01_010_MARIRURI_FREE_START
end
function MARIRURITbl.S01_020_MARIRURI_FREE_START()
  return MARIRURITbl.S01_010_MARIRURI_FREE_START
end
function MARIRURITbl.S01_030_MARIRURI_FREE_START()
  return MARIRURITbl.S01_020_MARIRURI_FREE_START
end
function MARIRURITbl.S01_040_MARIRURI_FREE_START()
  return MARIRURITbl.S01_030_MARIRURI_FREE_START
end
function MARIRURITbl.S01_050_MARIRURI_FREE_START()
  return MARIRURITbl.S01_040_MARIRURI_FREE_START
end
function MARIRURITbl.S01_060_MARIRURI_FREE_START()
  return MARIRURITbl.S01_050_MARIRURI_FREE_START
end
function MARIRURITbl.S01_080_MARIRURI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MARIRURI"))
  HeroBackTalkMariruri()
  OpenQuestCounterMenu()
  subUsuComFuncTalkOutBase01(CH("MARIRURI"), result)
end
function MARIRURITbl.ALL_CLEAR_MARIRURI_FREE_START()
  return MARIRURITbl.S01_080_MARIRURI_FREE_START
end

