function MARIRURITbl.M02_010_MARIRURI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MARIRURI"))
  WINDOW:SysMsg(-366941931)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("MARIRURI"), result)
end
function MARIRURITbl.M02_030_MARIRURI_FREE_START()
  return M02_010_MARIRURI_FREE_START
end
function MARIRURITbl.M02_050_MARIRURI_FREE_START()
  return MARIRURITbl.M02_030_MARIRURI_FREE_START
end
function MARIRURITbl.M02_070_MARIRURI_FREE_START()
  return MARIRURITbl.M02_050_MARIRURI_FREE_START
end
function MARIRURITbl.M02_080_MARIRURI_FREE_START()
  return MARIRURITbl.M02_070_MARIRURI_FREE_START
end
function MARIRURITbl.M02_090_MARIRURI_FREE_START()
  return MARIRURITbl.M02_080_MARIRURI_FREE_START
end
function MARIRURITbl.M02_100_MARIRURI_FREE_START()
  return MARIRURITbl.M02_090_MARIRURI_FREE_START
end
function MARIRURITbl.M02_115_MARIRURI_FREE_START()
  return MARIRURITbl.M02_100_MARIRURI_FREE_START
end
function MARIRURITbl.M02_130_MARIRURI_FREE_START()
  return MARIRURITbl.M02_115_MARIRURI_FREE_START
end
function MARIRURITbl.M02_160_MARIRURI_FREE_START()
  return MARIRURITbl.M02_130_MARIRURI_FREE_START
end
function MARIRURITbl.M03_010_MARIRURI_FREE_START()
  return MARIRURITbl.M02_160_MARIRURI_FREE_START
end
function MARIRURITbl.M03_020_MARIRURI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MARIRURI"))
  OpenQuestCounterMenu()
  subUsuComFuncTalkOutBase01(CH("MARIRURI"), result)
end
function MARIRURITbl.M03_045_MARIRURI_FREE_START()
  return MARIRURITbl.M03_020_MARIRURI_FREE_START
end
function MARIRURITbl.M03_090_MARIRURI_FREE_START()
  return MARIRURITbl.M03_045_MARIRURI_FREE_START
end
function MARIRURITbl.M03_110_MARIRURI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MARIRURI"))
  WINDOW:DrawFace(20, 88, SymAct("MARIRURI"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("MARIRURI"), -214181804)
  WINDOW:DrawFace(20, 88, SymAct("MARIRURI"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("MARIRURI"), -669611113)
  WINDOW:Talk(SymAct("MARIRURI"), -1056064810)
  WINDOW:Talk(SymAct("MARIRURI"), -1907610607)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("MARIRURI"), result)
end
function MARIRURITbl.M03_130_MARIRURI_FREE_START()
  return MARIRURITbl.M03_110_MARIRURI_FREE_START
end
function MARIRURITbl.M03_150_MARIRURI_FREE_START()
  return MARIRURITbl.M03_130_MARIRURI_FREE_START
end
function MARIRURITbl.M04_010_MARIRURI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MARIRURI"))
  OpenQuestCounterMenu()
  subUsuComFuncTalkOutBase01(CH("MARIRURI"), result)
end
function MARIRURITbl.M04_020_MARIRURI_FREE_START()
  return MARIRURITbl.M04_010_MARIRURI_FREE_START
end
function MARIRURITbl.M04_HANYOU_MARIRURI_FREE_START()
  return MARIRURITbl.M04_020_MARIRURI_FREE_START
end
function MARIRURITbl.M04_040_MARIRURI_FREE_START()
  return MARIRURITbl.M04_HANYOU_MARIRURI_FREE_START
end
function MARIRURITbl.M04_060_MARIRURI_FREE_START()
  return MARIRURITbl.M04_040_MARIRURI_FREE_START
end
function MARIRURITbl.M04_070_MARIRURI_FREE_START()
  return MARIRURITbl.M04_060_MARIRURI_FREE_START
end
function MARIRURITbl.M04_HANYOU_MARIRURI_FREE_START2()
  return MARIRURITbl.M04_070_MARIRURI_FREE_START
end
function MARIRURITbl.M05_000_MARIRURI_FREE_START()
  return MARIRURITbl.M04_HANYOU_MARIRURI_FREE_START2
end
function MARIRURITbl.M05_010_MARIRURI_FREE_START()
  return MARIRURITbl.M05_000_MARIRURI_FREE_START
end
function MARIRURITbl.M05_020_MARIRURI_FREE_START()
  return MARIRURITbl.M05_010_MARIRURI_FREE_START
end
function MARIRURITbl.M05_030_MARIRURI_FREE_START()
  return MARIRURITbl.M05_020_MARIRURI_FREE_START
end
function MARIRURITbl.M06_HANYOU_MARIRURI_FREE_START()
  return MARIRURITbl.M05_030_MARIRURI_FREE_START
end
function MARIRURITbl.M06_010_MARIRURI_FREE_START()
  return MARIRURITbl.M06_HANYOU_MARIRURI_FREE_START
end
function MARIRURITbl.M06_015_MARIRURI_FREE_START()
  return MARIRURITbl.M06_010_MARIRURI_FREE_START
end
function MARIRURITbl.M06_020_MARIRURI_FREE_START()
  return MARIRURITbl.M06_015_MARIRURI_FREE_START
end
function MARIRURITbl.M06_030_MARIRURI_FREE_START()
  return MARIRURITbl.M06_020_MARIRURI_FREE_START
end
function MARIRURITbl.M06_040_MARIRURI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MARIRURI"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("MARIRURI"):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFace(20, 88, SymAct("MARIRURI"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("MARIRURI"), -1755898544)
  WINDOW:DrawFace(20, 88, SymAct("MARIRURI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MARIRURI"), -1132835181)
  WINDOW:Talk(SymAct("MARIRURI"), -1520336942)
  WINDOW:Talk(SymAct("MARIRURI"), 586769181)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("MARIRURI"), result)
end
function MARIRURITbl.M06_060_MARIRURI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MARIRURI"))
  OpenQuestCounterMenu()
  subUsuComFuncTalkOutBase01(CH("MARIRURI"), result)
end
function MARIRURITbl.M07_000_MARIRURI_FREE_START()
  return MARIRURITbl.M06_060_MARIRURI_FREE_START
end
function MARIRURITbl.M07_010_MARIRURI_FREE_START()
  return MARIRURITbl.M07_000_MARIRURI_FREE_START
end
function MARIRURITbl.M07_020_MARIRURI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MARIRURI"))
  CH("MARIRURI"):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFace(20, 88, SymAct("MARIRURI"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("MARIRURI"), 1004687964)
  WINDOW:Talk(SymAct("MARIRURI"), -935324287)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("MARIRURI"), result)
end
function MARIRURITbl.M07_045_MARIRURI_FREE_START()
  return MARIRURITbl.M07_020_MARIRURI_FREE_START
end
function MARIRURITbl.M07_HANYOU_MARIRURI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MARIRURI"))
  OpenQuestCounterMenu()
  subUsuComFuncTalkOutBase01(CH("MARIRURI"), result)
end
function MARIRURITbl.M07_080_MARIRURI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MARIRURI"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("MARIRURI"):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFace(20, 88, SymAct("MARIRURI"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("MARIRURI"), -782555968)
  WINDOW:Talk(SymAct("MARIRURI"), -92899581)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("MARIRURI"), result)
end
function MARIRURITbl.M08_010_MARIRURI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MARIRURI"))
  OpenQuestCounterMenu()
  subUsuComFuncTalkOutBase01(CH("MARIRURI"), result)
end
function MARIRURITbl.M08_HANYOU_MARIRURI_FREE_START()
  return MARIRURITbl.M08_010_MARIRURI_FREE_START
end
function MARIRURITbl.M08_020_MARIRURI_FREE_START()
  return MARIRURITbl.M08_HANYOU_MARIRURI_FREE_START
end
function MARIRURITbl.M08_040_MARIRURI_FREE_START()
  return MARIRURITbl.M08_020_MARIRURI_FREE_START
end
function MARIRURITbl.M08_050_MARIRURI_FREE_START()
  return MARIRURITbl.M08_040_MARIRURI_FREE_START
end
function MARIRURITbl.M08_055_MARIRURI_FREE_START()
  return MARIRURITbl.M08_050_MARIRURI_FREE_START
end
function MARIRURITbl.M08_070_MARIRURI_FREE_START()
  return MARIRURITbl.M08_055_MARIRURI_FREE_START
end
function MARIRURITbl.M09_HANYOU_MARIRURI_FREE_START1()
  return MARIRURITbl.M08_070_MARIRURI_FREE_START
end
function MARIRURITbl.M09_010_MARIRURI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MARIRURI"))
  WINDOW:DrawFace(20, 88, SymAct("MARIRURI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MARIRURI"), -479377854)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("MARIRURI"):SetManpu("MP_NOTICE_L")
  CH("MARIRURI"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("MARIRURI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MARIRURI"), -1406349179)
  WINDOW:KeyWait()
  CH("MARIRURI"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(20, 88, SymAct("MARIRURI"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("MARIRURI"), -1254628924)
  WINDOW:CloseMessage()
  CH("MARIRURI"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  subUsuComFuncTalkOutBase01(CH("MARIRURI"), result)
end
function MARIRURITbl.M09_020_MARIRURI_FREE_START()
  return MARIRURITbl.M09_010_MARIRURI_FREE_START
end
function MARIRURITbl.M09_040_MARIRURI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MARIRURI"))
  if FLAG.MariruriCounter == CONST.CNT_1 then
    WINDOW:DrawFace(20, 88, SymAct("MARIRURI"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("MARIRURI"), -1642417657)
    WINDOW:Talk(SymAct("MARIRURI"), -2029943994)
    WINDOW:Talk(SymAct("MARIRURI"), 10067849)
    WINDOW:CloseMessage()
    FLAG.MariruriCounter = CONST.CNT_2
  end
  OpenQuestCounterMenu()
  subUsuComFuncTalkOutBase01(CH("MARIRURI"), result)
end
function MARIRURITbl.M09_HANYOU_MARIRURI_FREE_START2()
  return MARIRURITbl.M09_040_MARIRURI_FREE_START
end
function MARIRURITbl.M09_060_MARIRURI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MARIRURI"))
  WINDOW:DrawFace(20, 88, SymAct("MARIRURI"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("MARIRURI"), 427994824)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("MARIRURI"), result)
end
function MARIRURITbl.M09_080_MARIRURI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MARIRURI"))
  OpenQuestCounterMenu()
  subUsuComFuncTalkOutBase01(CH("MARIRURI"), result)
end
function MARIRURITbl.M09_100_MARIRURI_FREE_START()
  return MARIRURITbl.M09_080_MARIRURI_FREE_START
end
function MARIRURITbl.M09_110_MARIRURI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MARIRURI"))
  WINDOW:DrawFace(20, 88, SymAct("MARIRURI"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("MARIRURI"), -621430161)
  WINDOW:Talk(SymAct("MARIRURI"), -1007776978)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("MARIRURI"), result)
end
function MARIRURITbl.M09_120_MARIRURI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MARIRURI"))
  OpenQuestCounterMenu()
  subUsuComFuncTalkOutBase01(CH("MARIRURI"), result)
end
function MARIRURITbl.M10_010_MARIRURI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MARIRURI"))
  OpenQuestCounterMenu()
  subUsuComFuncTalkOutBase01(CH("MARIRURI"), result)
end
function MARIRURITbl.M10_030_MARIRURI_FREE_START()
  return MARIRURITbl.M10_010_MARIRURI_FREE_START
end
function MARIRURITbl.M10_040_MARIRURI_FREE_START()
  return MARIRURITbl.M10_030_MARIRURI_FREE_START
end
function MARIRURITbl.M10_060_MARIRURI_FREE_START()
  return MARIRURITbl.M10_040_MARIRURI_FREE_START
end
function MARIRURITbl.M11_010_MARIRURI_FREE_START()
  return MARIRURITbl.M10_060_MARIRURI_FREE_START
end
function MARIRURITbl.M11_030_MARIRURI_FREE_START()
  return MARIRURITbl.M11_010_MARIRURI_FREE_START
end
function MARIRURITbl.M11_040_MARIRURI_FREE_START()
  return MARIRURITbl.M11_030_MARIRURI_FREE_START
end
function MARIRURITbl.M11_050_MARIRURI_FREE_START()
  return MARIRURITbl.M11_040_MARIRURI_FREE_START
end
function MARIRURITbl.M11_060_MARIRURI_FREE_START()
  return MARIRURITbl.M11_050_MARIRURI_FREE_START
end
function MARIRURITbl.M11_090_MARIRURI_FREE_START()
  return MARIRURITbl.M11_060_MARIRURI_FREE_START
end

