function MEGUROKOTbl.M02_010_MEGUROKO_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MEGUROKO"))
  WINDOW:SysMsg(1757946334)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("MEGUROKO"), result)
end
function MEGUROKOTbl.M02_030_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M02_010_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M02_050_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M02_030_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M02_070_MEGUROKO_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MEGUROKO"))
  WINDOW:DrawFace(20, 88, SymAct("MEGUROKO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MEGUROKO"), 1909657759)
  WINDOW:Talk(SymAct("MEGUROKO"), 1526612828)
  WINDOW:Talk(SymAct("MEGUROKO"), 1139110429)
  WINDOW:Talk(SymAct("MEGUROKO"), 212133082)
  WINDOW:Talk(SymAct("MEGUROKO"), 364893595)
  WINDOW:Talk(SymAct("MEGUROKO"), 1049790040)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("MEGUROKO"), result)
end
function MEGUROKOTbl.M02_080_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M02_070_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M02_090_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M02_080_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M02_100_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M02_090_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M02_115_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M02_100_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M02_130_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M02_115_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M02_160_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M02_130_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M03_010_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M02_160_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M03_020_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M03_010_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M03_045_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M03_020_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M03_090_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M03_045_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M03_110_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M03_090_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M03_130_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M03_110_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M03_150_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M03_130_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M04_010_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M03_150_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M04_020_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M04_010_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M04_HANYOU_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M04_020_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M04_040_MEGUROKO_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MEGUROKO"))
  WINDOW:DrawFace(20, 88, SymAct("MEGUROKO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MEGUROKO"), 663336729)
  WINDOW:Talk(SymAct("MEGUROKO"), -1609454634)
  WINDOW:Talk(SymAct("MEGUROKO"), -1190487401)
  WINDOW:KeyWait()
  TASK:Regist(subEveJump, {
    CH("MEGUROKO")
  })
  WINDOW:DrawFace(20, 88, SymAct("MEGUROKO"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("MEGUROKO"), 1978782574)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("MEGUROKO"), result)
end
function MEGUROKOTbl.M04_060_MEGUROKO_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MEGUROKO"))
  WINDOW:DrawFace(20, 88, SymAct("MEGUROKO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MEGUROKO"), 1827332655)
  WINDOW:Talk(SymAct("MEGUROKO"), 1204269548)
  WINDOW:Talk(SymAct("MEGUROKO"), 1591509165)
  WINDOW:Talk(SymAct("MEGUROKO"), 295507562)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("MEGUROKO"):SetManpu("MP_EXCLAMATION")
  CH("MEGUROKO"):ResetManpu()
  WINDOW:DrawFace(20, 88, SymAct("MEGUROKO"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("MEGUROKO"), 143009579)
  WINDOW:DrawFace(20, 88, SymAct("MEGUROKO"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("MEGUROKO"), 598439144)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("MEGUROKO"), result)
end
function MEGUROKOTbl.M04_070_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M04_060_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M04_HANYOU_MEGUROKO_FREE_START2()
  return MEGUROKOTbl.M04_070_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M05_000_MEGUROKO_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MEGUROKO"))
  WINDOW:DrawFace(20, 88, SymAct("MEGUROKO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MEGUROKO"), 984630697)
  WINDOW:Talk(SymAct("MEGUROKO"), -1121429146)
  WINDOW:Talk(SymAct("MEGUROKO"), -1540134873)
  WINDOW:Talk(SymAct("MEGUROKO"), 1732541568)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("MEGUROKO"), result)
end
function MEGUROKOTbl.M05_010_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M05_000_FREE_START
end
function MEGUROKOTbl.M05_020_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M05_010_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M05_030_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M05_020_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M06_HANYOU_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M05_030_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M06_010_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M06_HANYOU_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M06_015_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M06_010_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M06_020_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M06_015_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M06_030_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M06_020_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M06_040_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M06_030_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M06_060_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M06_040_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M07_000_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M06_060_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M07_010_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M07_000_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M07_020_MEGUROKO_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MEGUROKO"))
  WINDOW:DrawFace(20, 88, SymAct("MEGUROKO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MEGUROKO"), 2120175041)
  WINDOW:DrawFace(20, 88, SymAct("MEGUROKO"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("MEGUROKO"), 1433542146)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("MEGUROKO"), result)
end
function MEGUROKOTbl.M07_045_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M07_020_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M07_HANYOU_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M07_045_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M07_080_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M07_HANYOU_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M08_010_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M07_080_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M08_HANYOU_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M08_010_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M08_020_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M08_HANYOU_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M08_040_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M08_020_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M08_050_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M08_040_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M08_055_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M08_050_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M08_070_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M08_055_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M09_HANYOU_MEGUROKO_FREE_START1()
  return MEGUROKOTbl.M08_070_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M09_010_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M09_HANYOU_MEGUROKO_FREE_START1
end
function MEGUROKOTbl.M09_020_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M09_010_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M09_040_MEGUROKO_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MEGUROKO"))
  WINDOW:DrawFace(20, 88, SymAct("MEGUROKO"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("MEGUROKO"), 1281961795)
  WINDOW:Talk(SymAct("MEGUROKO"), 53000580)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("MEGUROKO"), result)
end
function MEGUROKOTbl.M09_HANYOU_MEGUROKO_FREE_START2()
  return MEGUROKOTbl.M09_040_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M09_060_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M09_HANYOU_MEGUROKO_FREE_START2
end
function MEGUROKOTbl.M09_080_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M09_060_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M09_100_MEGUROKO_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MEGUROKO"))
  WINDOW:DrawFace(20, 88, SymAct("MEGUROKO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MEGUROKO"), 439584965)
  WINDOW:DrawFace(20, 88, SymAct("MEGUROKO"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("MEGUROKO"), 824105734)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("MEGUROKO"), result)
end
function MEGUROKOTbl.M09_110_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M09_100_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M09_120_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M09_110_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M10_010_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M09_120_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M10_030_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M10_010_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M10_040_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M10_030_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M10_060_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M10_040_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M11_010_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M10_060_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M11_030_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M11_010_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M11_040_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M11_030_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M11_050_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M11_040_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M11_060_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M11_050_MEGUROKO_FREE_START
end
function MEGUROKOTbl.M11_090_MEGUROKO_FREE_START()
  return MEGUROKOTbl.M11_060_MEGUROKO_FREE_START
end

