dofile("script/event/sub/sub02/sub02_meroetta.lua")
function MEROETTATbl.M12_010_MEROETTA_FREE_START()
  local result = subUseParadiseMeroettaTalkIn(CH("MEROETTA_VOICE"))
  WINDOW:SysMsg(422643693)
  WINDOW:CloseMessage()
  subUseParadiseMeroettaTalkOut(CH("EROETTA_VOICE"), result)
end
function MEROETTATbl.M12_020_MEROETTA_FREE_START()
  return MEROETTATbl.M12_010_MEROETTA_FREE_START
end
function MEROETTATbl.M12_030_MEROETTA_FREE_START()
  return MEROETTATbl.M12_020_MEROETTA_FREE_START
end
function MEROETTATbl.M12_040_MEROETTA_FREE_START()
  return MEROETTATbl.M12_030_MEROETTA_FREE_START
end
function MEROETTATbl.M12_050_MEROETTA_FREE_START()
  return MEROETTATbl.M12_040_MEROETTA_FREE_START
end
function MEROETTATbl.M12_070_MEROETTA_FREE_START()
  return MEROETTATbl.M12_050_MEROETTA_FREE_START
end
function MEROETTATbl.M13_010_MEROETTA_FREE_START()
  return MEROETTATbl.M12_070_MEROETTA_FREE_START
end
function MEROETTATbl.M13_030_MEROETTA_FREE_START()
  return MEROETTATbl.M13_010_MEROETTA_FREE_START
end
function MEROETTATbl.M13_040_MEROETTA_FREE_START()
  return MEROETTATbl.M13_030_MEROETTA_FREE_START
end
function MEROETTATbl.M13_060_MEROETTA_FREE_START()
  return MEROETTATbl.M13_040_MEROETTA_FREE_START
end
function MEROETTATbl.M13_070_MEROETTA_FREE_START()
  return MEROETTATbl.M13_060_MEROETTA_FREE_START
end
function MEROETTATbl.M13_080_MEROETTA_FREE_START()
  return MEROETTATbl.M13_070_MEROETTA_FREE_START
end
function MEROETTATbl.M13_090_MEROETTA_FREE_START()
  return MEROETTATbl.M13_080_MEROETTA_FREE_START
end
function MEROETTATbl.M13_095_MEROETTA_FREE_START()
  return MEROETTATbl.M13_090_MEROETTA_FREE_START
end
function MEROETTATbl.M13_110_MEROETTA_FREE_START()
  return MEROETTATbl.M13_095_MEROETTA_FREE_START
end
function MEROETTATbl.M14_010_MEROETTA_FREE_START()
  return MEROETTATbl.M13_110_MEROETTA_FREE_START
end
function MEROETTATbl.M14_030_MEROETTA_FREE_START()
  return MEROETTATbl.M14_010_MEROETTA_FREE_START
end
function MEROETTATbl.M14_040_MEROETTA_FREE_START()
  return MEROETTATbl.M14_030_MEROETTA_FREE_START
end
function MEROETTATbl.M14_060_MEROETTA_FREE_START()
  return MEROETTATbl.M14_040_MEROETTA_FREE_START
end
function MEROETTATbl.M14_070_MEROETTA_FREE_START()
  return MEROETTATbl.M14_060_MEROETTA_FREE_START
end
function MEROETTATbl.M14_090_MEROETTA_FREE_START()
  return MEROETTATbl.M14_070_MEROETTA_FREE_START
end
function MEROETTATbl.M15_010_MEROETTA_FREE_START()
  return MEROETTATbl.M14_090_MEROETTA_FREE_START
end
function MEROETTATbl.M15_020_MEROETTA_FREE_START()
  return MEROETTATbl.M15_010_MEROETTA_FREE_START
end
function MEROETTATbl.M15_030_MEROETTA_FREE_START()
  return MEROETTATbl.M15_020_MEROETTA_FREE_START
end
function MEROETTATbl.M16_010_MEROETTA_FREE_START()
  return MEROETTATbl.M15_030_MEROETTA_FREE_START
end
function MEROETTATbl.M16_040_MEROETTA_FREE_START()
  return MEROETTATbl.M16_010_MEROETTA_FREE_START
end
function MEROETTATbl.M16_080_MEROETTA_FREE_START()
  return MEROETTATbl.M16_040_MEROETTA_FREE_START
end
function MEROETTATbl.M16_090_MEROETTA_FREE_START()
  return MEROETTATbl.M16_080_MEROETTA_FREE_START
end
function MEROETTATbl.M16_100_MEROETTA_FREE_START()
  return MEROETTATbl.M16_090_MEROETTA_FREE_START
end
function MEROETTATbl.M16_105_MEROETTA_FREE_START()
  return MEROETTATbl.M16_100_MEROETTA_FREE_START
end
function MEROETTATbl.M16_120_MEROETTA_FREE_START()
  return MEROETTATbl.M16_105_MEROETTA_FREE_START
end
function MEROETTATbl.M17_020_MEROETTA_FREE_START()
  return MEROETTATbl.M16_120_MEROETTA_FREE_START
end
function MEROETTATbl.M17_040_MEROETTA_FREE_START()
  return MEROETTATbl.M17_020_MEROETTA_FREE_START
end
function MEROETTATbl.M17_060_MEROETTA_FREE_START()
  return MEROETTATbl.M17_040_MEROETTA_FREE_START
end
function MEROETTATbl.M17_065_MEROETTA_FREE_START()
  return MEROETTATbl.M17_060_MEROETTA_FREE_START
end
function MEROETTATbl.M17_090_MEROETTA_FREE_START()
  return MEROETTATbl.M17_065_MEROETTA_FREE_START
end
function MEROETTATbl.M17_120_MEROETTA_FREE_START()
  return MEROETTATbl.M17_090_MEROETTA_FREE_START
end
function MEROETTATbl.M17_140_MEROETTA_FREE_START()
  return MEROETTATbl.M17_120_MEROETTA_FREE_START
end
function MEROETTATbl.M17_150_MEROETTA_FREE_START()
  return MEROETTATbl.M17_140_MEROETTA_FREE_START
end
function MEROETTATbl.M17_155_MEROETTA_FREE_START()
  return MEROETTATbl.M17_150_MEROETTA_FREE_START
end
function MEROETTATbl.M17_170_MEROETTA_FREE_START()
  return MEROETTATbl.M17_155_MEROETTA_FREE_START
end
function MEROETTATbl.M17_200_MEROETTA_FREE_START()
  return MEROETTATbl.M17_170_MEROETTA_FREE_START
end
function MEROETTATbl.M17_210_MEROETTA_FREE_START()
  return MEROETTATbl.M17_200_MEROETTA_FREE_START
end
function MEROETTATbl.M17_220_MEROETTA_FREE_START()
  return MEROETTATbl.M17_210_MEROETTA_FREE_START
end
function MEROETTATbl.M17_225_MEROETTA_FREE_START()
  return MEROETTATbl.M17_220_MEROETTA_FREE_START
end
function MEROETTATbl.M17_240_MEROETTA_FREE_START()
  return MEROETTATbl.M17_225_MEROETTA_FREE_START
end
function MEROETTATbl.M18_020_MEROETTA_FREE_START()
  return MEROETTATbl.M17_240_MEROETTA_FREE_START
end
function MEROETTATbl.M18_030_MEROETTA_FREE_START()
  return MEROETTATbl.M18_020_MEROETTA_FREE_START
end
function MEROETTATbl.S01_010_MEROETTA_FREE_START()
  sub02_meroetta()
end
function MEROETTATbl.S01_020_MEROETTA_FREE_START()
  return MEROETTATbl.S01_010_MEROETTA_FREE_START
end
function MEROETTATbl.S01_030_MEROETTA_FREE_START()
  return MEROETTATbl.S01_020_MEROETTA_FREE_START
end
function MEROETTATbl.S01_040_MEROETTA_FREE_START()
  return MEROETTATbl.S01_030_MEROETTA_FREE_START
end
function MEROETTATbl.S01_050_MEROETTA_FREE_START()
  return MEROETTATbl.S01_040_MEROETTA_FREE_START
end
function MEROETTATbl.S01_060_MEROETTA_FREE_START()
  return MEROETTATbl.S01_050_MEROETTA_FREE_START
end
function MEROETTATbl.S01_080_MEROETTA_FREE_START()
  return MEROETTATbl.S01_050_MEROETTA_FREE_START
end
function MEROETTATbl.ALL_CLEAR_MEROETTA_FREE_START()
  return MEROETTATbl.S01_080_MEROETTA_FREE_START
end

