function MINEZUMITbl.M02_010_MINEZUMI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MINEZUMI"))
  WINDOW:DrawFace(20, 88, SymAct("MINEZUMI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MINEZUMI"), 444510157)
  WINDOW:Talk(SymAct("MINEZUMI"), 56991372)
  WINDOW:Talk(SymAct("MINEZUMI"), 675859791)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("MINEZUMI"), result)
end
function MINEZUMITbl.M02_030_MINEZUMI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MINEZUMI"))
  WINDOW:DrawFace(20, 88, SymAct("MINEZUMI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MINEZUMI"), 827587598)
  WINDOW:Talk(SymAct("MINEZUMI"), 2115136201)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("MINEZUMI"), result)
end
function MINEZUMITbl.M02_050_MINEZUMI_FREE_START()
  return MINEZUMITbl.M02_030_MINEZUMI_FREE_START
end
function MINEZUMITbl.M02_070_MINEZUMI_FREE_START()
  return MINEZUMITbl.M02_050_MINEZUMI_FREE_START
end
function MINEZUMITbl.M02_080_MINEZUMI_FREE_START()
  return MINEZUMITbl.M02_070_MINEZUMI_FREE_START
end
function MINEZUMITbl.M02_090_MINEZUMI_FREE_START()
  return MINEZUMITbl.M02_080_MINEZUMI_FREE_START
end
function MINEZUMITbl.M02_100_MINEZUMI_FREE_START()
  return MINEZUMITbl.M02_090_MINEZUMI_FREE_START
end
function MINEZUMITbl.M02_115_MINEZUMI_FREE_START()
  return MINEZUMITbl.M02_100_MINEZUMI_FREE_START
end
function MINEZUMITbl.M02_130_MINEZUMI_FREE_START()
  return MINEZUMITbl.M02_115_MINEZUMI_FREE_START
end
function MINEZUMITbl.M02_160_MINEZUMI_FREE_START()
  return MINEZUMITbl.M02_130_MINEZUMI_FREE_START
end
function MINEZUMITbl.M03_010_MINEZUMI_FREE_START()
  return MINEZUMITbl.M02_160_MINEZUMI_FREE_START
end
function MINEZUMITbl.M03_020_MINEZUMI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MINEZUMI"))
  WINDOW:DrawFace(20, 88, SymAct("MINEZUMI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MINEZUMI"), 1728666504)
  WINDOW:Talk(SymAct("MINEZUMI"), 1277429835)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("MINEZUMI"), result)
end
function MINEZUMITbl.M03_045_MINEZUMI_FREE_START()
  return MINEZUMITbl.M03_020_MINEZUMI_FREE_START
end
function MINEZUMITbl.M03_090_MINEZUMI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MINEZUMI"))
  WINDOW:DrawFace(20, 88, SymAct("MINEZUMI"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("MINEZUMI"), 1430206730)
  WINDOW:Talk(SymAct("MINEZUMI"), -760797755)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("MINEZUMI"), result)
end
function MINEZUMITbl.M03_110_MINEZUMI_FREE_START()
  return MINEZUMITbl.M03_090_MINEZUMI_FREE_START
end
function MINEZUMITbl.M03_130_MINEZUMI_FREE_START()
  return MINEZUMITbl.M03_110_MINEZUMI_FREE_START
end
function MINEZUMITbl.M03_150_MINEZUMI_FREE_START()
  return MINEZUMITbl.M03_130_MINEZUMI_FREE_START
end
function MINEZUMITbl.M04_010_MINEZUMI_FREE_START()
  return MINEZUMITbl.M03_150_MINEZUMI_FREE_START
end
function MINEZUMITbl.M04_020_MINEZUMI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MINEZUMI"))
  WINDOW:DrawFace(20, 88, SymAct("MINEZUMI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MINEZUMI"), -876866428)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("MINEZUMI"), result)
end
function MINEZUMITbl.M04_HANYOU_MINEZUMI_FREE_START()
  return MINEZUMITbl.M04_020_MINEZUMI_FREE_START
end
function MINEZUMITbl.M04_040_MINEZUMI_FREE_START()
  return MINEZUMITbl.M04_HANYOU_MINEZUMI_FREE_START
end
function MINEZUMITbl.M04_060_MINEZUMI_FREE_START()
  return MINEZUMITbl.M04_040_MINEZUMI_FREE_START
end
function MINEZUMITbl.M04_070_MINEZUMI_FREE_START()
  return MINEZUMITbl.M04_060_MINEZUMI_FREE_START
end
function MINEZUMITbl.M04_HANYOU_MINEZUMI_FREE_START2()
  return MINEZUMITbl.M04_070_MINEZUMI_FREE_START
end
function MINEZUMITbl.M05_000_MINEZUMI_FREE_START()
  return MINEZUMITbl.M04_HANYOU_MINEZUMI_FREE_START2
end
function MINEZUMITbl.M05_010_MINEZUMI_FREE_START()
  return MINEZUMITbl.M05_000_MINEZUMI_FREE_START
end
function MINEZUMITbl.M05_020_MINEZUMI_FREE_START()
  return MINEZUMITbl.M05_010_MINEZUMI_FREE_START
end
function MINEZUMITbl.M05_030_MINEZUMI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MINEZUMI"))
  WINDOW:DrawFace(20, 88, SymAct("MINEZUMI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MINEZUMI"), 505302637)
  WINDOW:Talk(SymAct("MINEZUMI"), 117800748)
  WINDOW:Talk(SymAct("MINEZUMI"), 740830447)
  WINDOW:Talk(SymAct("MINEZUMI"), 892542382)
  WINDOW:Talk(SymAct("MINEZUMI"), 2054327145)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("MINEZUMI"):SetManpu("MP_EXCLAMATION")
  CH("MINEZUMI"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("MINEZUMI"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("MINEZUMI"), 1667873320)
  WINDOW:Talk(SymAct("MINEZUMI"), 1212475883)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("MINEZUMI"), result)
end
function MINEZUMITbl.M06_HANYOU_MINEZUMI_FREE_START()
  return MINEZUMITbl.M05_030_MINEZUMI_FREE_START
end
function MINEZUMITbl.M06_010_MINEZUMI_FREE_START()
  local result = subUsuComFuncTalkInBase02(CH("MINEZUMI"))
  WINDOW:DrawFace(20, 88, SymAct("MINEZUMI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MINEZUMI"), 1365235882)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase02(CH("MINEZUMI"), result)
end
function MINEZUMITbl.M06_015_MINEZUMI_FREE_START()
  return MINEZUMITbl.M06_010_MINEZUMI_FREE_START
end
function MINEZUMITbl.M06_020_MINEZUMI_FREE_START()
  return MINEZUMITbl.M06_015_MINEZUMI_FREE_START
end
function MINEZUMITbl.M06_030_MINEZUMI_FREE_START()
  return MINEZUMITbl.M06_020_MINEZUMI_FREE_START
end
function MINEZUMITbl.M06_040_MINEZUMI_FREE_START()
  return MINEZUMITbl.M06_030_MINEZUMI_FREE_START
end
function MINEZUMITbl.M06_060_MINEZUMI_FREE_START()
  return MINEZUMITbl.M06_040_MINEZUMI_FREE_START
end
function MINEZUMITbl.M07_000_MINEZUMI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MINEZUMI"))
  WINDOW:DrawFace(20, 88, SymAct("MINEZUMI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MINEZUMI"), -691551131)
  WINDOW:Talk(SymAct("MINEZUMI"), -807602908)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("MINEZUMI"), result)
end
function MINEZUMITbl.M07_010_MINEZUMI_FREE_START()
  return MINEZUMITbl.M07_000_MINEZUMI_FREE_START
end
function MINEZUMITbl.M07_020_MINEZUMI_FREE_START()
  return MINEZUMITbl.M07_010_MINEZUMI_FREE_START
end
function MINEZUMITbl.M07_045_MINEZUMI_FREE_START()
  return MINEZUMITbl.M07_020_MINEZUMI_FREE_START
end
function MINEZUMITbl.M07_HANYOU_MINEZUMI_FREE_START()
  return MINEZUMITbl.M07_045_MINEZUMI_FREE_START
end
function MINEZUMITbl.M07_080_MINEZUMI_FREE_START()
  return MINEZUMITbl.M07_HANYOU_MINEZUMI_FREE_START
end
function MINEZUMITbl.M08_010_MINEZUMI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MINEZUMI"))
  WINDOW:DrawFace(20, 88, SymAct("MINEZUMI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MINEZUMI"), 212590979)
  WINDOW:Talk(SymAct("MINEZUMI"), 363909314)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("MINEZUMI"), result)
end
function MINEZUMITbl.M08_HANYOU_MINEZUMI_FREE_START()
  return MINEZUMITbl.M08_010_MINEZUMI_FREE_START
end
function MINEZUMITbl.M08_020_MINEZUMI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MINEZUMI"))
  WINDOW:DrawFace(20, 88, SymAct("MINEZUMI"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("MINEZUMI"), 1050510081)
  WINDOW:Talk(SymAct("MINEZUMI"), 663138880)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("MINEZUMI"), result)
end
function MINEZUMITbl.M08_040_MINEZUMI_FREE_START()
  return MINEZUMITbl.M08_020_MINEZUMI_FREE_START
end
function MINEZUMITbl.M08_050_MINEZUMI_FREE_START()
  return MINEZUMITbl.M08_040_MINEZUMI_FREE_START
end
function MINEZUMITbl.M08_055_MINEZUMI_FREE_START()
  return MINEZUMITbl.M08_050_MINEZUMI_FREE_START
end
function MINEZUMITbl.M08_070_MINEZUMI_FREE_START()
  return MINEZUMITbl.M08_055_MINEZUMI_FREE_START
end
function MINEZUMITbl.M09_HANYOU_MINEZUMI_FREE_START1()
  return MINEZUMITbl.M08_070_MINEZUMI_FREE_START
end
function MINEZUMITbl.M09_010_MINEZUMI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MINEZUMI"))
  WINDOW:DrawFace(20, 88, SymAct("MINEZUMI"), FACE_TYPE.EMOTION)
  WINDOW:Talk(SymAct("MINEZUMI"), 1757881479)
  WINDOW:Talk(SymAct("MINEZUMI"), 1910248902)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("MINEZUMI"), result)
end
function MINEZUMITbl.M09_020_MINEZUMI_FREE_START()
  return MINEZUMITbl.M09_010_MINEZUMI_FREE_START
end
function MINEZUMITbl.M09_040_MINEZUMI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MINEZUMI"))
  WINDOW:DrawFace(20, 88, SymAct("MINEZUMI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MINEZUMI"), 1525761541)
  WINDOW:Talk(SymAct("MINEZUMI"), 1139439428)
  WINDOW:Talk(SymAct("MINEZUMI"), -999134325)
  WINDOW:Talk(SymAct("MINEZUMI"), -580298038)
  WINDOW:Talk(SymAct("MINEZUMI"), -1273526554)
  WINDOW:Talk(SymAct("MINEZUMI"), -1391675481)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("MINEZUMI"), result)
end
function MINEZUMITbl.M09_HANYOU_MINEZUMI_FREE_START2()
  return MINEZUMITbl.M09_040_MINEZUMI_FREE_START
end
function MINEZUMITbl.M09_060_MINEZUMI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MINEZUMI"))
  WINDOW:DrawFace(20, 88, SymAct("MINEZUMI"), FACE_TYPE.EMOTION)
  WINDOW:Talk(SymAct("MINEZUMI"), -2044599196)
  WINDOW:Talk(SymAct("MINEZUMI"), -1623534299)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("MINEZUMI"), result)
end
function MINEZUMITbl.M09_080_MINEZUMI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MINEZUMI"))
  WINDOW:DrawFace(20, 88, SymAct("MINEZUMI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("MINEZUMI"), -797228062)
  WINDOW:Talk(SymAct("MINEZUMI"), -916426077)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("MINEZUMI"):SetManpu("MP_EXCLAMATION")
  CH("MINEZUMI"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("MINEZUMI"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("MINEZUMI"), -498261664)
  WINDOW:KeyWait()
  TASK:Regist(subEveDoubleJump, {
    CH("MINEZUMI")
  })
  WINDOW:DrawFace(20, 88, SymAct("MINEZUMI"), FACE_TYPE.EMOTION)
  WINDOW:Talk(SymAct("MINEZUMI"), -78245855)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("MINEZUMI"), result)
end
function MINEZUMITbl.M09_100_MINEZUMI_FREE_START()
  return MINEZUMITbl.M09_080_MINEZUMI_FREE_START
end
function MINEZUMITbl.M09_110_MINEZUMI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MINEZUMI"))
  WINDOW:DrawFace(20, 88, SymAct("MINEZUMI"), FACE_TYPE.EMOTION)
  WINDOW:Talk(SymAct("MINEZUMI"), 2093878510)
  WINDOW:KeyWait()
  TASK:Regist(subEveDoubleJump, {
    CH("MINEZUMI")
  })
  WINDOW:Talk(SymAct("MINEZUMI"), 1708473775)
  WINDOW:Talk(SymAct("MINEZUMI"), 700497503)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("MINEZUMI"), result)
end
function MINEZUMITbl.M09_120_MINEZUMI_FREE_START()
  return MINEZUMITbl.M09_110_MINEZUMI_FREE_START
end
function MINEZUMITbl.M10_010_MINEZUMI_FREE_START()
  return MINEZUMITbl.M09_120_MINEZUMI_FREE_START
end
function MINEZUMITbl.M10_030_MINEZUMI_FREE_START()
  return MINEZUMITbl.M10_010_MINEZUMI_FREE_START
end
function MINEZUMITbl.M10_040_MINEZUMI_FREE_START()
  return MINEZUMITbl.M10_030_MINEZUMI_FREE_START
end
function MINEZUMITbl.M10_060_MINEZUMI_FREE_START()
  return MINEZUMITbl.M10_040_MINEZUMI_FREE_START
end
function MINEZUMITbl.M11_010_MINEZUMI_FREE_START()
  return MINEZUMITbl.M10_060_MINEZUMI_FREE_START
end
function MINEZUMITbl.M11_030_MINEZUMI_FREE_START()
  return MINEZUMITbl.M11_010_MINEZUMI_FREE_START
end
function MINEZUMITbl.M11_040_MINEZUMI_FREE_START()
  return MINEZUMITbl.M11_030_MINEZUMI_FREE_START
end
function MINEZUMITbl.M11_050_MINEZUMI_FREE_START()
  return MINEZUMITbl.M11_040_MINEZUMI_FREE_START
end
function MINEZUMITbl.M11_060_MINEZUMI_FREE_START()
  return MINEZUMITbl.M11_050_MINEZUMI_FREE_START
end
function MINEZUMITbl.M11_090_MINEZUMI_FREE_START()
  return MINEZUMITbl.M11_060_MINEZUMI_FREE_START
end

