function MOGURYUUTbl.M02_010_MOGURYUU_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("MOGURYUU"))
  WINDOW:SysMsg(-682007727)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("MOGURYUU"), result)
end
function MOGURYUUTbl.M02_030_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M02_010_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M02_050_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M02_030_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M02_070_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M02_050_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M02_080_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M02_070_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M02_090_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M02_080_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M02_100_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M02_090_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M02_115_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M02_100_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M02_130_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M02_115_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M02_160_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M02_130_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M03_010_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M02_160_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M03_020_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M03_010_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M03_045_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M03_020_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M03_090_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M03_045_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M03_110_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M03_090_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M03_130_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M03_110_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M03_150_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M03_130_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M04_010_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M03_150_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M04_020_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M04_010_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M04_HANYOU_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M04_020_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M04_040_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M04_HANYOU_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M04_060_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M04_040_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M04_070_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M04_060_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M04_HANYOU_MOGURYUU_FREE_START2()
  return MOGURYUUTbl.M04_070_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M05_000_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M04_HANYOU_MOGURYUU_FREE_START2
end
function MOGURYUUTbl.M05_010_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M05_000_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M05_020_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M05_010_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M05_030_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M05_020_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M06_HANYOU_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M05_030_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M06_010_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M06_HANYOU_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M06_015_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M06_010_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M06_020_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M06_015_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M06_030_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M06_020_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M06_040_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M06_030_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M06_060_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M06_040_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M07_000_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M06_060_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M07_010_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M07_000_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M07_020_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M07_010_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M07_045_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M07_020_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M07_HANYOU_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M07_045_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M07_080_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M07_HANYOU_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M08_010_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M07_080_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M08_HANYOU_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M08_010_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M08_020_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M08_HANYOU_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M08_040_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M08_020_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M08_050_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M08_040_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M08_055_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M08_050_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M08_070_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M08_055_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M09_HANYOU_MOGURYUU_FREE_START1()
  return MOGURYUUTbl.M08_070_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M09_010_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M09_HANYOU_MOGURYUU_FREE_START1
end
function MOGURYUUTbl.M09_020_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M09_010_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M09_040_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M09_020_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M09_HANYOU_MOGURYUU_FREE_START2()
  return MOGURYUUTbl.M09_040_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M09_060_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M09_HANYOU_MOGURYUU_FREE_START2
end
function MOGURYUUTbl.M09_080_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M09_060_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M09_100_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M09_080_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M09_110_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M09_100_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M09_120_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M09_110_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M10_010_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M09_120_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M10_030_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M10_010_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M10_040_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M10_030_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M10_060_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M10_040_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M11_010_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M10_060_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M11_030_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M11_010_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M11_040_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M11_030_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M11_050_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M11_040_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M11_060_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M11_050_MOGURYUU_FREE_START
end
function MOGURYUUTbl.M11_090_MOGURYUU_FREE_START()
  return MOGURYUUTbl.M11_060_MOGURYUU_FREE_START
end

