function NOKOTCHITbl.M02_010_NOKOTCHI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("NOKOTCHI"))
  WINDOW:SysMsg(2141328502)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("NOKOTCHI"), result)
end
function NOKOTCHITbl.M02_030_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M02_010_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M02_050_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M02_030_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M02_070_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M02_050_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M02_080_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M02_070_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M02_090_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M02_080_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M02_100_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M02_090_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M02_115_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M02_100_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M02_130_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M02_115_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M02_160_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M02_130_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M03_010_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M02_160_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M03_020_NOKOTCHI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("NOKOTCHI"))
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NOKOTCHI"), 1723409719)
  WINDOW:Talk(SymAct("NOKOTCHI"), 1301575412)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("NOKOTCHI"), result)
end
function NOKOTCHITbl.M03_045_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M03_020_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M03_090_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M03_045_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M03_110_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M03_090_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M03_130_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M03_110_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M03_150_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M03_130_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M04_010_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M03_150_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M04_020_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M04_010_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M04_HANYOU_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M04_020_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M04_040_NOKOTCHI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("NOKOTCHI"))
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NOKOTCHI"), 1418676149)
  WINDOW:Talk(SymAct("NOKOTCHI"), 466538866)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("NOKOTCHI"), result)
end
function NOKOTCHITbl.M04_060_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M04_040_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M04_070_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M04_060_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M04_HANYOU_NOKOTCHI_FREE_START2()
  return NOKOTCHITbl.M04_070_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M05_000_NOKOTCHI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("NOKOTCHI"))
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NOKOTCHI"), 47570995)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("NOKOTCHI"), result)
end
function NOKOTCHITbl.M05_010_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M05_000_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M05_020_NOKOTCHI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("NOKOTCHI"))
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NOKOTCHI"), 704164848)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("NOKOTCHI"), result)
end
function NOKOTCHITbl.M05_030_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M05_020_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M06_HANYOU_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M05_030_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M06_010_NOKOTCHI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("NOKOTCHI"))
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NOKOTCHI"), 820216497)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("NOKOTCHI"), result)
end
function NOKOTCHITbl.M06_015_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M06_010_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M06_020_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M06_015_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M06_030_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M06_020_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M06_040_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M06_030_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M06_060_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M06_040_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M07_000_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M06_060_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M07_010_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M07_000_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M07_020_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M07_010_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M07_045_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M07_020_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M07_HANYOU_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M07_045_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M07_080_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M07_HANYOU_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M08_010_NOKOTCHI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("NOKOTCHI"))
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NOKOTCHI"), -1216635266)
  WINDOW:Talk(SymAct("NOKOTCHI"), -1369395393)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("NOKOTCHI"), result)
end
function NOKOTCHITbl.M08_HANYOU_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M08_010_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M08_020_NOKOTCHI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("NOKOTCHI"))
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NOKOTCHI"), 1167865542)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("NOKOTCHI"), result)
end
function NOKOTCHITbl.M08_040_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M08_020_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M08_050_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M08_040_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M08_055_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M08_050_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M08_070_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M08_055_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M09_HANYOU_NOKOTCHI_FREE_START1()
  return NOKOTCHITbl.M08_070_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M09_010_NOKOTCHI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("NOKOTCHI"))
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NOKOTCHI"), 1552353159)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("NOKOTCHI"), result)
end
function NOKOTCHITbl.M09_020_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M09_010_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M09_040_NOKOTCHI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("NOKOTCHI"))
  TASK:Regist(subEveDoubleJump, {
    CH("NOKOTCHI")
  })
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.EMOTION)
  WINDOW:Talk(SymAct("NOKOTCHI"), 2007651396)
  WINDOW:Talk(SymAct("NOKOTCHI"), 1857119493)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("NOKOTCHI"), result)
end
function NOKOTCHITbl.M09_HANYOU_NOKOTCHI_FREE_START2()
  return NOKOTCHITbl.M09_040_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M09_060_NOKOTCHI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("NOKOTCHI"))
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("NOKOTCHI"), 569439170)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("NOKOTCHI"), result)
end
function NOKOTCHITbl.M09_080_NOKOTCHI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("NOKOTCHI"))
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("NOKOTCHI"), 954974851)
  WINDOW:Talk(SymAct("NOKOTCHI"), 331780416)
  WINDOW:Talk(SymAct("NOKOTCHI"), 182296577)
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("NOKOTCHI"), -1924809522)
  WINDOW:Talk(SymAct("NOKOTCHI"), -1805742705)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("NOKOTCHI"), result)
end
function NOKOTCHITbl.M09_100_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M09_080_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M09_110_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M09_100_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M09_120_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M09_110_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M10_010_NOKOTCHI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("NOKOTCHI"))
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NOKOTCHI"), 1462343976)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("NOKOTCHI"), result)
end
function NOKOTCHITbl.M10_030_NOKOTCHI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("NOKOTCHI"))
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NOKOTCHI"), 1311942761)
  WINDOW:Talk(SymAct("NOKOTCHI"), 1696594858)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("NOKOTCHI"), result)
end
function NOKOTCHITbl.M10_040_NOKOTCHI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("NOKOTCHI"))
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NOKOTCHI"), 2080688875)
  WINDOW:Talk(SymAct("NOKOTCHI"), 860183596)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("NOKOTCHI"), result)
end
function NOKOTCHITbl.M10_060_NOKOTCHI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("NOKOTCHI"))
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("NOKOTCHI"), 710831469)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("NOKOTCHI"):SetManpu("MP_FLY_SWEAT")
  CH("NOKOTCHI"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NOKOTCHI"), 24329902)
  WINDOW:Talk(SymAct("NOKOTCHI"), 409473007)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("NOKOTCHI"), result)
end
function NOKOTCHITbl.M11_010_NOKOTCHI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("NOKOTCHI"))
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NOKOTCHI"), -1611656416)
  WINDOW:Talk(SymAct("NOKOTCHI"), -2031410591)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("NOKOTCHI"), result)
end
function NOKOTCHITbl.M11_030_NOKOTCHI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("NOKOTCHI"))
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NOKOTCHI"), -275382707)
  WINDOW:Talk(SymAct("NOKOTCHI"), -158413044)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("NOKOTCHI"), result)
end
function NOKOTCHITbl.M11_040_NOKOTCHI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("NOKOTCHI"))
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.EMOTION)
  WINDOW:Talk(SymAct("NOKOTCHI"), -576480049)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("NOKOTCHI"), result)
end
function NOKOTCHITbl.M11_050_NOKOTCHI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("NOKOTCHI"))
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NOKOTCHI"), -994529906)
  WINDOW:Talk(SymAct("NOKOTCHI"), -1946600631)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("NOKOTCHI"), result)
end
function NOKOTCHITbl.M11_060_NOKOTCHI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("NOKOTCHI"))
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NOKOTCHI"), -1830680056)
  WINDOW:Talk(SymAct("NOKOTCHI"), -1177593397)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("NOKOTCHI"), result)
end
function NOKOTCHITbl.M11_075_NOKOTCHI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("NOKOTCHI"))
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NOKOTCHI"), -1596692342)
  WINDOW:Talk(SymAct("NOKOTCHI"), 659321925)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("NOKOTCHI"), result)
end
function NOKOTCHITbl.M11_090_NOKOTCHI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("NOKOTCHI"))
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("NOKOTCHI"), 1045906692)
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("NOKOTCHI"), 1916978932)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("NOKOTCHI"), result)
end

