function NOKOTCHITbl.M12_010_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M11_090_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M12_020_NOKOTCHI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("NOKOTCHI"))
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NOKOTCHI"), 461545699)
  WINDOW:Talk(SymAct("NOKOTCHI"), 43618722)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("NOKOTCHI"), result)
end
function NOKOTCHITbl.M12_030_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M12_020_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M12_040_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M12_030_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M12_050_NOKOTCHI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("NOKOTCHI"))
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NOKOTCHI"), 699712097)
  WINDOW:Talk(SymAct("NOKOTCHI"), 816837408)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("NOKOTCHI"), result)
end
function NOKOTCHITbl.M12_070_NOKOTCHI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("NOKOTCHI"))
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NOKOTCHI"), 2146330087)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("NOKOTCHI"), result)
end
function NOKOTCHITbl.M13_010_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M12_070_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M13_030_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M13_010_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M13_040_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M13_030_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M13_060_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M13_040_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M13_070_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M13_060_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M13_080_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M13_070_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M13_090_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M13_080_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M13_095_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M13_090_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M13_110_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M13_095_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M14_010_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M13_110_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M14_030_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M14_010_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M14_040_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M14_030_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M14_060_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M14_040_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M14_070_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M14_060_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M14_090_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M14_070_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M15_010_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M14_090_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M15_020_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M15_010_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M15_030_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M15_020_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M16_010_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M15_030_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M16_040_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M16_010_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M16_080_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M16_040_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M16_090_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M16_080_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M16_100_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M16_090_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M16_105_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M16_100_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M16_120_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M16_105_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M17_020_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M16_120_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M17_040_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M17_020_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M17_060_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M17_040_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M17_065_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M17_060_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M17_090_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M17_065_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M17_120_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M17_090_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M17_140_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M17_120_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M17_150_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M17_140_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M17_155_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M17_150_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M17_170_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M17_155_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M17_200_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M17_170_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M17_210_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M17_200_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M17_220_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M17_210_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M17_225_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M17_220_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M17_240_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M17_225_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M18_020_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M17_240_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.M18_030_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.M18_020_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.S01_010_NOKOTCHI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("NOKOTCHI"))
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NOKOTCHI"), 1727354022)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("NOKOTCHI"), result)
end
function NOKOTCHITbl.S01_020_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.S01_010_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.S01_030_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.S01_020_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.S01_040_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.S01_030_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.S01_050_NOKOTCHI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("NOKOTCHI"))
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NOKOTCHI"), 1306003301)
  WINDOW:Talk(SymAct("NOKOTCHI"), 1422079524)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("NOKOTCHI"), result)
end
function NOKOTCHITbl.S01_060_NOKOTCHI_FREE_START()
  return NOKOTCHITbl.S01_050_NOKOTCHI_FREE_START
end
function NOKOTCHITbl.S01_080_NOKOTCHI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("NOKOTCHI"))
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("NOKOTCHI"), -748999957)
  WINDOW:Talk(SymAct("NOKOTCHI"), -901768278)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("NOKOTCHI"), result)
end
function NOKOTCHITbl.ALL_CLEAR_NOKOTCHI_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("NOKOTCHI"))
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NOKOTCHI"), -2052695252)
  WINDOW:Talk(SymAct("NOKOTCHI"), -1665308051)
  WINDOW:Talk(SymAct("NOKOTCHI"), -1215284818)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("NOKOTCHI"), result)
end

