function PERIPPAATbl.M02_010_PERIPPAA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("PERIPPAA"))
  WINDOW:SysMsg(471364649)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("PERIPPAA"), result)
end
function PERIPPAATbl.M02_030_PERIPPAA_FREE_START()
  return PERIPPAATbl.M02_010_PERIPPAA_FREE_START
end
function PERIPPAATbl.M02_050_PERIPPAA_FREE_START()
  return PERIPPAATbl.M02_030_PERIPPAA_FREE_START
end
function PERIPPAATbl.M02_070_PERIPPAA_FREE_START()
  return PERIPPAATbl.M02_050_PERIPPAA_FREE_START
end
function PERIPPAATbl.M02_080_PERIPPAA_FREE_START()
  return PERIPPAATbl.M02_070_PERIPPAA_FREE_START
end
function PERIPPAATbl.M02_090_PERIPPAA_FREE_START()
  return PERIPPAATbl.M02_080_PERIPPAA_FREE_START
end
function PERIPPAATbl.M02_100_PERIPPAA_FREE_START()
  return PERIPPAATbl.M02_090_PERIPPAA_FREE_START
end
function PERIPPAATbl.M02_115_PERIPPAA_FREE_START()
  return PERIPPAATbl.M02_100_PERIPPAA_FREE_START
end
function PERIPPAATbl.M02_130_PERIPPAA_FREE_START()
  return PERIPPAATbl.M02_115_PERIPPAA_FREE_START
end
function PERIPPAATbl.M02_160_PERIPPAA_FREE_START()
  return PERIPPAATbl.M02_130_PERIPPAA_FREE_START
end
function PERIPPAATbl.M03_010_PERIPPAA_FREE_START()
  return PERIPPAATbl.M02_160_PERIPPAA_FREE_START
end
function PERIPPAATbl.M03_020_PERIPPAA_FREE_START()
  return PERIPPAATbl.M03_010_PERIPPAA_FREE_START
end
function PERIPPAATbl.M03_045_PERIPPAA_FREE_START()
  return PERIPPAATbl.M03_020_PERIPPAA_FREE_START
end
function PERIPPAATbl.M03_090_PERIPPAA_FREE_START()
  return PERIPPAATbl.M03_045_PERIPPAA_FREE_START
end
function PERIPPAATbl.M03_110_PERIPPAA_FREE_START()
  return PERIPPAATbl.M03_090_PERIPPAA_FREE_START
end
function PERIPPAATbl.M03_130_PERIPPAA_FREE_START()
  return PERIPPAATbl.M03_110_PERIPPAA_FREE_START
end
function PERIPPAATbl.M03_150_PERIPPAA_FREE_START()
  return PERIPPAATbl.M03_130_PERIPPAA_FREE_START
end
function PERIPPAATbl.M04_010_PERIPPAA_FREE_START()
  return PERIPPAATbl.M03_150_PERIPPAA_FREE_START
end
function PERIPPAATbl.M04_020_PERIPPAA_FREE_START()
  return PERIPPAATbl.M04_010_PERIPPAA_FREE_START
end
function PERIPPAATbl.M04_HANYOU_PERIPPAA_FREE_START()
  return PERIPPAATbl.M04_020_PERIPPAA_FREE_START
end
function PERIPPAATbl.M04_040_PERIPPAA_FREE_START()
  return PERIPPAATbl.M04_HANYOU_PERIPPAA_FREE_START
end
function PERIPPAATbl.M04_060_PERIPPAA_FREE_START()
  return PERIPPAATbl.M04_040_PERIPPAA_FREE_START
end
function PERIPPAATbl.M04_070_PERIPPAA_FREE_START()
  return PERIPPAATbl.M04_060_PERIPPAA_FREE_START
end
function PERIPPAATbl.M04_HANYOU_PERIPPAA_FREE_START2()
  return PERIPPAATbl.M04_070_PERIPPAA_FREE_START
end
function PERIPPAATbl.M05_000_PERIPPAA_FREE_START()
  return PERIPPAATbl.M04_HANYOU_PERIPPAA_FREE_START2
end
function PERIPPAATbl.M05_010_PERIPPAA_FREE_START()
  return PERIPPAATbl.M05_000_PERIPPAA_FREE_START
end
function PERIPPAATbl.M05_020_PERIPPAA_FREE_START()
  return PERIPPAATbl.M05_010_PERIPPAA_FREE_START
end
function PERIPPAATbl.M05_030_PERIPPAA_FREE_START()
  return PERIPPAATbl.M05_020_PERIPPAA_FREE_START
end
function PERIPPAATbl.M06_HANYOU_PERIPPAA_FREE_START()
  return PERIPPAATbl.M05_030_PERIPPAA_FREE_START
end
function PERIPPAATbl.M06_010_PERIPPAA_FREE_START()
  return PERIPPAATbl.M06_HANYOU_PERIPPAA_FREE_START
end
function PERIPPAATbl.M06_015_PERIPPAA_FREE_START()
  return PERIPPAATbl.M06_010_PERIPPAA_FREE_START
end
function PERIPPAATbl.M06_020_PERIPPAA_FREE_START()
  return PERIPPAATbl.M06_015_PERIPPAA_FREE_START
end
function PERIPPAATbl.M06_030_PERIPPAA_FREE_START()
  return PERIPPAATbl.M06_020_PERIPPAA_FREE_START
end
function PERIPPAATbl.M06_040_PERIPPAA_FREE_START()
  return PERIPPAATbl.M06_030_PERIPPAA_FREE_START
end
function PERIPPAATbl.M06_060_PERIPPAA_FREE_START()
  return PERIPPAATbl.M06_040_PERIPPAA_FREE_START
end
function PERIPPAATbl.M07_000_PERIPPAA_FREE_START()
  return PERIPPAATbl.M06_060_PERIPPAA_FREE_START
end
function PERIPPAATbl.M07_010_PERIPPAA_FREE_START()
  return PERIPPAATbl.M07_000_PERIPPAA_FREE_START
end
function PERIPPAATbl.M07_020_PERIPPAA_FREE_START()
  return PERIPPAATbl.M07_010_PERIPPAA_FREE_START
end
function PERIPPAATbl.M07_045_PERIPPAA_FREE_START()
  return PERIPPAATbl.M07_020_PERIPPAA_FREE_START
end
function PERIPPAATbl.M07_HANYOU_PERIPPAA_FREE_START()
  return PERIPPAATbl.M07_045_PERIPPAA_FREE_START
end
function PERIPPAATbl.M07_080_PERIPPAA_FREE_START()
  return PERIPPAATbl.M07_HANYOU_PERIPPAA_FREE_START
end
function PERIPPAATbl.M08_010_PERIPPAA_FREE_START()
  return PERIPPAATbl.M07_080_PERIPPAA_FREE_START
end
function PERIPPAATbl.M08_HANYOU_PERIPPAA_FREE_START()
  return PERIPPAATbl.M08_010_PERIPPAA_FREE_START
end
function PERIPPAATbl.M08_020_PERIPPAA_FREE_START()
  return PERIPPAATbl.M08_HANYOU_PERIPPAA_FREE_START
end
function PERIPPAATbl.M08_040_PERIPPAA_FREE_START()
  return PERIPPAATbl.M08_020_PERIPPAA_FREE_START
end
function PERIPPAATbl.M08_050_PERIPPAA_FREE_START()
  return PERIPPAATbl.M08_040_PERIPPAA_FREE_START
end
function PERIPPAATbl.M08_055_PERIPPAA_FREE_START()
  return PERIPPAATbl.M08_050_PERIPPAA_FREE_START
end
function PERIPPAATbl.M08_070_PERIPPAA_FREE_START()
  return PERIPPAATbl.M08_055_PERIPPAA_FREE_START
end
function PERIPPAATbl.M09_HANYOU_PERIPPAA_FREE_START1()
  return PERIPPAATbl.M08_070_PERIPPAA_FREE_START
end
function PERIPPAATbl.M09_010_PERIPPAA_FREE_START()
  return PERIPPAATbl.M09_HANYOU_PERIPPAA_FREE_START1
end
function PERIPPAATbl.M09_020_PERIPPAA_FREE_START()
  return PERIPPAATbl.M09_010_PERIPPAA_FREE_START
end
function PERIPPAATbl.M09_040_PERIPPAA_FREE_START()
  return PERIPPAATbl.M09_020_PERIPPAA_FREE_START
end
function PERIPPAATbl.M09_HANYOU_PERIPPAA_FREE_START2()
  return PERIPPAATbl.M09_040_PERIPPAA_FREE_START
end
function PERIPPAATbl.M09_060_PERIPPAA_FREE_START()
  return PERIPPAATbl.M09_HANYOU_PERIPPAA_FREE_START2
end
function PERIPPAATbl.M09_080_PERIPPAA_FREE_START()
  return PERIPPAATbl.M09_060_PERIPPAA_FREE_START
end
function PERIPPAATbl.M09_100_PERIPPAA_FREE_START()
  return PERIPPAATbl.M09_080_PERIPPAA_FREE_START
end
function PERIPPAATbl.M09_110_PERIPPAA_FREE_START()
  return PERIPPAATbl.M09_100_PERIPPAA_FREE_START
end
function PERIPPAATbl.M09_120_PERIPPAA_FREE_START()
  return PERIPPAATbl.M09_110_PERIPPAA_FREE_START
end
function PERIPPAATbl.M10_010_PERIPPAA_FREE_START()
  return PERIPPAATbl.M09_120_PERIPPAA_FREE_START
end
function PERIPPAATbl.M10_030_PERIPPAA_FREE_START()
  return PERIPPAATbl.M10_010_PERIPPAA_FREE_START
end
function PERIPPAATbl.M10_040_PERIPPAA_FREE_START()
  return PERIPPAATbl.M10_030_PERIPPAA_FREE_START
end
function PERIPPAATbl.M10_060_PERIPPAA_FREE_START()
  return PERIPPAATbl.M10_040_PERIPPAA_FREE_START
end
function PERIPPAATbl.M11_010_PERIPPAA_FREE_START()
  return PERIPPAATbl.M10_060_PERIPPAA_FREE_START
end
function PERIPPAATbl.M11_030_PERIPPAA_FREE_START()
  return PERIPPAATbl.M11_010_PERIPPAA_FREE_START
end
function PERIPPAATbl.M11_040_PERIPPAA_FREE_START()
  return PERIPPAATbl.M11_030_PERIPPAA_FREE_START
end
function PERIPPAATbl.M11_050_PERIPPAA_FREE_START()
  return PERIPPAATbl.M11_040_PERIPPAA_FREE_START
end
function PERIPPAATbl.M11_060_PERIPPAA_FREE_START()
  return PERIPPAATbl.M11_050_PERIPPAA_FREE_START
end
function PERIPPAATbl.M11_090_PERIPPAA_FREE_START()
  return PERIPPAATbl.M11_060_PERIPPAA_FREE_START
end

