function PERIPPAATbl.M12_010_PERIPPAA_FREE_START()
  return PERIPPAATbl.M11_090_PERIPPAA_FREE_START
end
function PERIPPAATbl.M12_020_PERIPPAA_FREE_START()
  return PERIPPAATbl.M12_010_PERIPPAA_FREE_START
end
function PERIPPAATbl.M12_030_PERIPPAA_FREE_START()
  return PERIPPAATbl.M12_020_PERIPPAA_FREE_START
end
function PERIPPAATbl.M12_040_PERIPPAA_FREE_START()
  return PERIPPAATbl.M12_030_PERIPPAA_FREE_START
end
function PERIPPAATbl.M12_050_PERIPPAA_FREE_START()
  return PERIPPAATbl.M12_040_PERIPPAA_FREE_START
end
function PERIPPAATbl.M12_070_PERIPPAA_FREE_START()
  return PERIPPAATbl.M12_050_PERIPPAA_FREE_START
end
function PERIPPAATbl.M13_010_PERIPPAA_FREE_START()
  return PERIPPAATbl.M12_070_PERIPPAA_FREE_START
end
function PERIPPAATbl.M13_030_PERIPPAA_FREE_START()
  return PERIPPAATbl.M13_010_PERIPPAA_FREE_START
end
function PERIPPAATbl.M13_040_PERIPPAA_FREE_START()
  return PERIPPAATbl.M13_030_PERIPPAA_FREE_START
end
function PERIPPAATbl.M13_060_PERIPPAA_FREE_START()
  return PERIPPAATbl.M13_040_PERIPPAA_FREE_START
end
function PERIPPAATbl.M13_070_PERIPPAA_FREE_START()
  return PERIPPAATbl.M13_060_PERIPPAA_FREE_START
end
function PERIPPAATbl.M13_080_PERIPPAA_FREE_START()
  return PERIPPAATbl.M13_070_PERIPPAA_FREE_START
end
function PERIPPAATbl.M13_090_PERIPPAA_FREE_START()
  return PERIPPAATbl.M13_080_PERIPPAA_FREE_START
end
function PERIPPAATbl.M13_095_PERIPPAA_FREE_START()
  return PERIPPAATbl.M13_090_PERIPPAA_FREE_START
end
function PERIPPAATbl.M13_110_PERIPPAA_FREE_START()
  return PERIPPAATbl.M13_095_PERIPPAA_FREE_START
end
function PERIPPAATbl.M14_010_PERIPPAA_FREE_START()
  return PERIPPAATbl.M13_110_PERIPPAA_FREE_START
end
function PERIPPAATbl.M14_030_PERIPPAA_FREE_START()
  return PERIPPAATbl.M14_010_PERIPPAA_FREE_START
end
function PERIPPAATbl.M14_040_PERIPPAA_FREE_START()
  return PERIPPAATbl.M14_030_PERIPPAA_FREE_START
end
function PERIPPAATbl.M14_060_PERIPPAA_FREE_START()
  return PERIPPAATbl.M14_040_PERIPPAA_FREE_START
end
function PERIPPAATbl.M14_070_PERIPPAA_FREE_START()
  return PERIPPAATbl.M14_060_PERIPPAA_FREE_START
end
function PERIPPAATbl.M14_090_PERIPPAA_FREE_START()
  return PERIPPAATbl.M14_070_PERIPPAA_FREE_START
end
function PERIPPAATbl.M15_010_PERIPPAA_FREE_START()
  return PERIPPAATbl.M14_090_PERIPPAA_FREE_START
end
function PERIPPAATbl.M15_020_PERIPPAA_FREE_START()
  return PERIPPAATbl.M15_010_PERIPPAA_FREE_START
end
function PERIPPAATbl.M15_030_PERIPPAA_FREE_START()
  return PERIPPAATbl.M15_020_PERIPPAA_FREE_START
end
function PERIPPAATbl.M16_010_PERIPPAA_FREE_START()
  return PERIPPAATbl.M15_030_PERIPPAA_FREE_START
end
function PERIPPAATbl.M16_040_PERIPPAA_FREE_START()
  return PERIPPAATbl.M16_010_PERIPPAA_FREE_START
end
function PERIPPAATbl.M16_080_PERIPPAA_FREE_START()
  return PERIPPAATbl.M16_040_PERIPPAA_FREE_START
end
function PERIPPAATbl.M16_090_PERIPPAA_FREE_START()
  return PERIPPAATbl.M16_080_PERIPPAA_FREE_START
end
function PERIPPAATbl.M16_100_PERIPPAA_FREE_START()
  return PERIPPAATbl.M16_090_PERIPPAA_FREE_START
end
function PERIPPAATbl.M16_105_PERIPPAA_FREE_START()
  return PERIPPAATbl.M16_100_PERIPPAA_FREE_START
end
function PERIPPAATbl.M16_120_PERIPPAA_FREE_START()
  return PERIPPAATbl.M16_105_PERIPPAA_FREE_START
end
function PERIPPAATbl.M17_020_PERIPPAA_FREE_START()
  return PERIPPAATbl.M16_120_PERIPPAA_FREE_START
end
function PERIPPAATbl.M17_040_PERIPPAA_FREE_START()
  return PERIPPAATbl.M17_020_PERIPPAA_FREE_START
end
function PERIPPAATbl.M17_060_PERIPPAA_FREE_START()
  return PERIPPAATbl.M17_040_PERIPPAA_FREE_START
end
function PERIPPAATbl.M17_065_PERIPPAA_FREE_START()
  return PERIPPAATbl.M17_060_PERIPPAA_FREE_START
end
function PERIPPAATbl.M17_090_PERIPPAA_FREE_START()
  return PERIPPAATbl.M17_065_PERIPPAA_FREE_START
end
function PERIPPAATbl.M17_120_PERIPPAA_FREE_START()
  return PERIPPAATbl.M17_090_PERIPPAA_FREE_START
end
function PERIPPAATbl.M17_140_PERIPPAA_FREE_START()
  return PERIPPAATbl.M17_120_PERIPPAA_FREE_START
end
function PERIPPAATbl.M17_150_PERIPPAA_FREE_START()
  return PERIPPAATbl.M17_140_PERIPPAA_FREE_START
end
function PERIPPAATbl.M17_155_PERIPPAA_FREE_START()
  return PERIPPAATbl.M17_150_PERIPPAA_FREE_START
end
function PERIPPAATbl.M17_170_PERIPPAA_FREE_START()
  return PERIPPAATbl.M17_155_PERIPPAA_FREE_START
end
function PERIPPAATbl.M17_200_PERIPPAA_FREE_START()
  return PERIPPAATbl.M17_170_PERIPPAA_FREE_START
end
function PERIPPAATbl.M17_210_PERIPPAA_FREE_START()
  return PERIPPAATbl.M17_200_PERIPPAA_FREE_START
end
function PERIPPAATbl.M17_220_PERIPPAA_FREE_START()
  return PERIPPAATbl.M17_210_PERIPPAA_FREE_START
end
function PERIPPAATbl.M17_225_PERIPPAA_FREE_START()
  return PERIPPAATbl.M17_220_PERIPPAA_FREE_START
end
function PERIPPAATbl.M17_240_PERIPPAA_FREE_START()
  return PERIPPAATbl.M17_225_PERIPPAA_FREE_START
end
function PERIPPAATbl.M18_020_PERIPPAA_FREE_START()
  return PERIPPAATbl.M17_240_PERIPPAA_FREE_START
end
function PERIPPAATbl.M18_030_PERIPPAA_FREE_START()
  return PERIPPAATbl.M18_020_PERIPPAA_FREE_START
end
function PERIPPAATbl.S01_010_PERIPPAA_FREE_START()
  return PERIPPAATbl.M18_030_PERIPPAA_FREE_START
end
function PERIPPAATbl.S01_020_PERIPPAA_FREE_START()
  return PERIPPAATbl.S01_010_PERIPPAA_FREE_START
end
function PERIPPAATbl.S01_030_PERIPPAA_FREE_START()
  return PERIPPAATbl.S01_020_PERIPPAA_FREE_START
end
function PERIPPAATbl.S01_040_PERIPPAA_FREE_START()
  return PERIPPAATbl.S01_030_PERIPPAA_FREE_START
end
function PERIPPAATbl.S01_050_PERIPPAA_FREE_START()
  return PERIPPAATbl.S01_040_PERIPPAA_FREE_START
end
function PERIPPAATbl.S01_060_PERIPPAA_FREE_START()
  return PERIPPAATbl.S01_050_PERIPPAA_FREE_START
end
function PERIPPAATbl.S01_080_PERIPPAA_FREE_START()
  return PERIPPAATbl.S01_060_PERIPPAA_FREE_START
end
function PERIPPAATbl.ALL_CLEAR_PERIPPAA_FREE_START()
  return PERIPPAATbl.S01_080_PERIPPAA_FREE_START
end

