function RAMUPARUDOTbl.M02_010_RAMUPARUDO_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("RAMUPARUDO"))
  WINDOW:DrawFace(20, 88, SymAct("RAMUPARUDO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("RAMUPARUDO"), -349756531)
  WINDOW:Talk(SymAct("RAMUPARUDO"), -230944052)
  WINDOW:Talk(SymAct("RAMUPARUDO"), -653180657)
  WINDOW:KeyWait()
  CH("RAMUPARUDO"):SetManpu("MP_SHOCK_L")
  WINDOW:Talk(SymAct("RAMUPARUDO"), -1073057714)
  WINDOW:Talk(SymAct("RAMUPARUDO"), -1890851191)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("RAMUPARUDO"), result)
end
function RAMUPARUDOTbl.M02_030_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M02_010_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M02_050_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M02_030_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M02_070_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M02_050_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M02_080_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M02_070_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M02_090_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M02_080_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M02_100_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M02_090_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M02_115_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M02_100_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M02_130_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M02_115_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M02_160_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M02_130_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M03_010_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M02_160_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M03_020_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M03_010_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M03_045_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M03_020_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M03_090_RAMUPARUDO_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("RAMUPARUDO"))
  WINDOW:DrawFace(20, 88, SymAct("RAMUPARUDO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("RAMUPARUDO"), -1773086776)
  WINDOW:Talk(SymAct("RAMUPARUDO"), -1115847669)
  WINDOW:Talk(SymAct("RAMUPARUDO"), -1536772790)
  WINDOW:Talk(SymAct("RAMUPARUDO"), 603892101)
  WINDOW:Talk(SymAct("RAMUPARUDO"), 988125380)
  WINDOW:CloseMessage()
  CH("RAMUPARUDO"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  CH("RAMUPARUDO"):WaitRotate()
  CH("RAMUPARUDO"):SetManpu("MP_SPREE_LP")
  subEveDoubleJump(CH("RAMUPARUDO"))
  WINDOW:DrawFace(20, 88, SymAct("RAMUPARUDO"), FACE_TYPE.SHOUT)
  WINDOW:Talk(SymAct("RAMUPARUDO"), 174669626)
  WINDOW:CloseMessage()
  CH("RAMUPARUDO"):ResetManpu()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("RAMUPARUDO"):SetManpu("MP_EXCLAMATION")
  CH("RAMUPARUDO"):WaitManpu()
  CH("RAMUPARUDO"):DirTo(CH("PLAYER"), Speed(350), ROT_TYPE.NEAR)
  CH("RAMUPARUDO"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("RAMUPARUDO"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("RAMUPARUDO"), 326241915)
  WINDOW:Talk(SymAct("RAMUPARUDO"), 945774008)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("RAMUPARUDO"):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFace(20, 88, SymAct("RAMUPARUDO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("RAMUPARUDO"), 558132473)
  WINDOW:Talk(SymAct("RAMUPARUDO"), 1845885502)
  WINDOW:Talk(SymAct("RAMUPARUDO"), 1998506879)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("RAMUPARUDO"), result)
end
function RAMUPARUDOTbl.M03_110_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M03_090_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M03_130_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M03_110_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M03_150_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M03_130_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M04_010_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M03_150_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M04_020_RAMUPARUDO_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("RAMUPARUDO"))
  if FLAG.RamuparudoCounter == CONST.CNT_1 then
    WINDOW:DrawFace(20, 88, SymAct("RAMUPARUDO"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("RAMUPARUDO"), 1546885308)
    WINDOW:Talk(SymAct("RAMUPARUDO"), 1160292861)
    WINDOW:Talk(SymAct("RAMUPARUDO"), -1028606670)
    WINDOW:KeyWait()
    CH("RAMUPARUDO"):SetManpu("MP_SPREE_LP")
    subEveDoubleJump(CH("RAMUPARUDO"))
    WINDOW:DrawFace(20, 88, SymAct("RAMUPARUDO"), FACE_TYPE.SHOUT)
    WINDOW:Talk(SymAct("RAMUPARUDO"), -609516429)
    WINDOW:CloseMessage()
    CH("RAMUPARUDO"):ResetManpu()
    FLAG.RamuparudoCounter = CONST.CNT_2
  end
  OpenJudgmentShopMenu()
  subUsuComFuncTalkOutBase01(CH("RAMUPARUDO"), result)
end
function RAMUPARUDOTbl.M04_HANYOU_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M04_020_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M04_040_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M04_HANYOU_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M04_060_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M04_040_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M04_070_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M04_060_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M04_HANYOU_RAMUPARUDO_FREE_START2()
  return RAMUPARUDOTbl.M04_070_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M05_000_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M04_HANYOU_RAMUPARUDO_FREE_START2
end
function RAMUPARUDOTbl.M05_010_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M05_000_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M05_020_RAMUPARUDO_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("RAMUPARUDO"))
  if FLAG.RamuparudoCounter == CONST.CNT_1 then
    WINDOW:DrawFace(20, 88, SymAct("RAMUPARUDO"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("RAMUPARUDO"), 417108180)
    WINDOW:CloseMessage()
    FLAG.RamuparudoCounter = CONST.CNT_2
  end
  OpenJudgmentShopMenu()
  subUsuComFuncTalkOutBase01(CH("RAMUPARUDO"), result)
end
function RAMUPARUDOTbl.M05_030_RAMUPARUDO_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("RAMUPARUDO"))
  if FLAG.RamuparudoCounter == CONST.CNT_1 then
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
    CH("RAMUPARUDO"):SetManpu("MP_EXCLAMATION")
    WINDOW:DrawFace(20, 88, SymAct("RAMUPARUDO"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("RAMUPARUDO"), 29860245)
    WINDOW:Talk(SymAct("RAMUPARUDO"), 720040534)
    WINDOW:CloseMessage()
    FLAG.RamuparudoCounter = CONST.CNT_2
  end
  OpenJudgmentShopMenu()
  subUsuComFuncTalkOutBase01(CH("RAMUPARUDO"), result)
end
function RAMUPARUDOTbl.M06_HANYOU_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M05_030_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M06_010_RAMUPARUDO_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("RAMUPARUDO"))
  if FLAG.RamuparudoCounter == CONST.CNT_1 then
    WINDOW:DrawFace(20, 88, SymAct("RAMUPARUDO"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("RAMUPARUDO"), 871482135)
    WINDOW:Talk(SymAct("RAMUPARUDO"), 2091931088)
    WINDOW:CloseMessage()
    FLAG.RamuparudoCounter = CONST.CNT_2
  end
  OpenJudgmentShopMenu()
  subUsuComFuncTalkOutBase01(CH("RAMUPARUDO"), result)
end
function RAMUPARUDOTbl.M06_015_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M06_010_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M06_020_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M06_015_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M06_030_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M06_020_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M06_040_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M06_030_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M06_060_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M06_040_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M07_000_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M06_060_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M07_010_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M07_000_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M07_020_RAMUPARUDO_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("RAMUPARUDO"))
  if FLAG.RamuparudoCounter == CONST.CNT_1 then
    CH("RAMUPARUDO"):SetManpu("MP_SPREE_LP")
    TASK:Regist(subEveDoubleJump, {
      CH("RAMUPARUDO")
    })
    WINDOW:DrawFace(20, 88, SymAct("RAMUPARUDO"), FACE_TYPE.SHOUT)
    WINDOW:Talk(SymAct("RAMUPARUDO"), 1705731217)
    WINDOW:CloseMessage()
    CH("RAMUPARUDO"):ResetManpu()
    FLAG.RamuparudoCounter = CONST.CNT_2
  end
  OpenJudgmentShopMenu()
  subUsuComFuncTalkOutBase01(CH("RAMUPARUDO"), result)
end
function RAMUPARUDOTbl.M07_045_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M07_020_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M07_HANYOU_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M07_045_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M07_080_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M07_HANYOU_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M08_010_RAMUPARUDO_FREE_START()
  if FLAG.RamuparudoCounter == CONST.CNT_1 then
    local result = subUsuComFuncTalkInBase02(CH("RAMUPARUDO"))
    CH("RAMUPARUDO"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.NEAR)
    CH("RAMUPARUDO"):WaitRotate()
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
    CH("RAMUPARUDO"):SetManpu("MP_NOTICE_L")
    CH("RAMUPARUDO"):WaitManpu()
    WINDOW:DrawFace(20, 88, SymAct("RAMUPARUDO"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("RAMUPARUDO"), 1317418834)
    WINDOW:Talk(SymAct("RAMUPARUDO"), 1469908499)
    WINDOW:Talk(SymAct("RAMUPARUDO"), -804971812)
    WINDOW:CloseMessage()
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
    CH("RAMUPARUDO"):SetManpu("MP_EXCLAMATION")
    CH("RAMUPARUDO"):WaitManpu()
    local result = subUsuComFuncTalkInBase01(CH("RAMUPARUDO"))
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
    CH("RAMUPARUDO"):SetManpu("MP_ANGRY_LP")
    WINDOW:DrawFace(20, 88, SymAct("RAMUPARUDO"), FACE_TYPE.SHOUT)
    WINDOW:Talk(SymAct("RAMUPARUDO"), -920769635)
    WINDOW:KeyWait()
    CH("RAMUPARUDO"):ResetManpu()
    WINDOW:Talk(SymAct("RAMUPARUDO"), -1604257871)
    WINDOW:CloseMessage()
    FLAG.RamuparudoCounter = CONST.CNT_2
    OpenJudgmentShopMenu()
    subUsuComFuncTalkOutBase01(CH("RAMUPARUDO"), result)
  else
    local result2 = subUsuComFuncTalkInBase01(CH("RAMUPARUDO"))
    OpenJudgmentShopMenu()
    subUsuComFuncTalkOutBase01(CH("RAMUPARUDO"), result2)
  end
end
function RAMUPARUDOTbl.M08_HANYOU_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M08_010_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M08_020_RAMUPARUDO_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("RAMUPARUDO"))
  OpenJudgmentShopMenu()
  subUsuComFuncTalkOutBase01(CH("RAMUPARUDO"), result)
end
function RAMUPARUDOTbl.M08_040_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M08_020_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M08_050_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M08_040_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M08_055_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M08_050_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M08_070_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M08_055_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M09_HANYOU_RAMUPARUDO_FREE_START1()
  return RAMUPARUDOTbl.M08_070_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M09_010_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M09_HANYOU_RAMUPARUDO_FREE_START1
end
function RAMUPARUDOTbl.M09_020_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M09_010_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M09_040_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M09_020_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M09_HANYOU_RAMUPARUDO_FREE_START2()
  return RAMUPARUDOTbl.M09_040_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M09_060_RAMUPARUDO_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("RAMUPARUDO"))
  if FLAG.RamuparudoCounter == CONST.CNT_1 then
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
    CH("RAMUPARUDO"):SetManpu("MP_EXCLAMATION")
    CH("RAMUPARUDO"):WaitManpu()
    WINDOW:DrawFace(20, 88, SymAct("RAMUPARUDO"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("RAMUPARUDO"), -1183070480)
    WINDOW:Talk(SymAct("RAMUPARUDO"), -1839819469)
    WINDOW:KeyWait()
    CH("RAMUPARUDO"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
    WINDOW:DrawFace(20, 88, SymAct("RAMUPARUDO"), FACE_TYPE.PAIN)
    WINDOW:Talk(SymAct("RAMUPARUDO"), -1957845902)
    WINDOW:CloseMessage()
    CH("RAMUPARUDO"):SetFacialMotion(FACIAL_MOTION.NORMAL)
    FLAG.RamuparudoCounter = CONST.CNT_2
  end
  OpenJudgmentShopMenu()
  subUsuComFuncTalkOutBase01(CH("RAMUPARUDO"), result)
end
function RAMUPARUDOTbl.M09_080_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M09_060_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M09_100_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M09_080_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M09_110_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M09_100_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M09_120_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M09_110_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M10_010_RAMUPARUDO_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("RAMUPARUDO"))
  OpenJudgmentShopMenu()
  subUsuComFuncTalkOutBase01(CH("RAMUPARUDO"), result)
end
function RAMUPARUDOTbl.M10_030_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M10_010_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M10_040_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M10_030_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M10_060_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M10_040_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M11_010_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M10_060_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M11_030_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M11_010_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M11_040_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M11_030_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M11_050_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M11_040_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M11_060_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M11_050_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M11_090_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M11_060_RAMUPARUDO_FREE_START
end

