function RAMUPARUDOTbl.M12_010_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M11_090_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M12_020_RAMUPARUDO_FREE_START()
  if FLAG.RamuparudoCounter == CONST.CNT_1 then
    local result = subUsuComFuncTalkInBase02(CH("RAMUPARUDO"))
    CH("RAMUPARUDO"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.NEAR)
    CH("RAMUPARUDO"):WaitRotate()
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
    CH("RAMUPARUDO"):SetManpu("MP_FLY_SWEAT")
    CH("RAMUPARUDO"):WaitManpu()
    CH("RAMUPARUDO"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
    WINDOW:DrawFace(20, 88, SymAct("RAMUPARUDO"), FACE_TYPE.PAIN)
    WINDOW:Talk(SymAct("RAMUPARUDO"), -86762484)
    WINDOW:Talk(SymAct("RAMUPARUDO"), -472961715)
    WINDOW:Talk(SymAct("RAMUPARUDO"), -924680562)
    WINDOW:Talk(SymAct("RAMUPARUDO"), -772190257)
    WINDOW:Talk(SymAct("RAMUPARUDO"), -1632052984)
    WINDOW:CloseMessage()
    CH("RAMUPARUDO"):SetFacialMotion(FACIAL_MOTION.NORMAL)
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
    CH("RAMUPARUDO"):SetManpu("MP_EXCLAMATION")
    CH("RAMUPARUDO"):WaitManpu()
    local result = subUsuComFuncTalkInBase01(CH("RAMUPARUDO"))
    WINDOW:DrawFace(20, 88, SymAct("RAMUPARUDO"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("RAMUPARUDO"), -2019301303)
    WINDOW:CloseMessage()
    FLAG.RamuparudoCounter = CONST.CNT_2
    OpenJudgmentShopMenu()
    subUsuComFuncTalkOutBase01(CH("RAMUPARUDO"), result)
  else
    local result2 = subUsuComFuncTalkInBase01(CH("RAMUPARUDO"))
    OpenJudgmentShopMenu()
    subUsuComFuncTalkOutBase01(CH("RAMUPARUDO"), result2)
  end
end
function RAMUPARUDOTbl.M12_030_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M12_020_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M12_040_RAMUPARUDO_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("RAMUPARUDO"))
  if FLAG.RamuparudoCounter == CONST.CNT_1 then
    WINDOW:DrawFace(20, 88, SymAct("RAMUPARUDO"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("RAMUPARUDO"), -1399932022)
    WINDOW:CloseMessage()
    FLAG.RamuparudoCounter = CONST.CNT_2
  end
  OpenJudgmentShopMenu()
  subUsuComFuncTalkOutBase01(CH("RAMUPARUDO"), result)
end
function RAMUPARUDOTbl.M12_050_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M12_040_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M12_070_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M12_050_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M13_010_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M12_070_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M13_030_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M13_010_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M13_040_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M13_030_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M13_060_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M13_040_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M13_070_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M13_060_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M13_080_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M13_070_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M13_090_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M13_080_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M13_095_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M13_090_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M13_110_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M13_095_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M14_010_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M13_110_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M14_030_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M14_010_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M14_040_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M14_030_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M14_060_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M14_040_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M14_070_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M14_060_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M14_090_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M14_070_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M15_010_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M14_090_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M15_020_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M15_010_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M15_030_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M15_020_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M16_010_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M15_030_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M16_040_RAMUPARUDO_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("RAMUPARUDO"))
  if FLAG.RamuparudoCounter == CONST.CNT_1 then
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
    CH("RAMUPARUDO"):SetManpu("MP_SHOCK_L")
    CH("RAMUPARUDO"):WaitManpu()
    WINDOW:DrawFace(20, 88, SymAct("RAMUPARUDO"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("RAMUPARUDO"), -1248490805)
    WINDOW:Talk(SymAct("RAMUPARUDO"), 839751172)
    WINDOW:Talk(SymAct("RAMUPARUDO"), 722904901)
    WINDOW:Talk(SymAct("RAMUPARUDO"), -1634227458)
    WINDOW:Talk(SymAct("RAMUPARUDO"), -2020828225)
    WINDOW:KeyWait()
    CH("RAMUPARUDO"):SetManpu("MP_SHOCK_L")
    WINDOW:Talk(SymAct("RAMUPARUDO"), -1398683524)
    WINDOW:Talk(SymAct("RAMUPARUDO"), -1246037699)
    WINDOW:CloseMessage()
    FLAG.RamuparudoCounter = CONST.CNT_2
  end
  OpenJudgmentShopMenu()
  subUsuComFuncTalkOutBase01(CH("RAMUPARUDO"), result)
end
function RAMUPARUDOTbl.M16_080_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M16_040_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M16_090_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M16_080_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M16_100_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M16_090_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M16_105_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M16_100_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M16_120_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M16_105_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M17_020_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M16_120_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M17_040_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M17_020_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M17_060_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M17_040_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M17_065_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M17_060_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M17_090_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M17_065_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M17_120_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M17_090_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M17_140_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M17_120_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M17_150_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M17_140_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M17_155_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M17_150_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M17_170_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M17_155_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M17_200_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M17_170_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M17_210_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M17_200_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M17_220_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M17_210_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M17_225_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M17_220_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M17_240_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M17_225_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M18_020_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M17_240_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.M18_030_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.M18_020_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.S01_010_RAMUPARUDO_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("RAMUPARUDO"))
  if FLAG.RamuparudoCounter == CONST.CNT_1 then
    WINDOW:DrawFace(20, 88, SymAct("RAMUPARUDO"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("RAMUPARUDO"), -84185094)
    WINDOW:Talk(SymAct("RAMUPARUDO"), -471834949)
    WINDOW:Talk(SymAct("RAMUPARUDO"), -926085768)
    WINDOW:Talk(SymAct("RAMUPARUDO"), -774489031)
    WINDOW:KeyWait()
    CH("RAMUPARUDO"):SetManpu("MP_SHOCK_L")
    WINDOW:Talk(SymAct("RAMUPARUDO"), 1447960822)
    WINDOW:KeyWait()
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
    CH("RAMUPARUDO"):SetManpu("MP_FLY_SWEAT")
    WINDOW:Talk(SymAct("RAMUPARUDO"), 1330975159)
    WINDOW:KeyWait()
    CH("RAMUPARUDO"):SetManpu("MP_SHOCK_L")
    WINDOW:Talk(SymAct("RAMUPARUDO"), -1943927536)
    WINDOW:CloseMessage()
    FLAG.RamuparudoCounter = CONST.CNT_2
  end
  OpenJudgmentShopMenu()
  subUsuComFuncTalkOutBase01(CH("RAMUPARUDO"), result)
end
function RAMUPARUDOTbl.S01_020_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.S01_010_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.S01_030_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.S01_020_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.S01_040_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.S01_030_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.S01_050_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.S01_040_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.S01_060_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.S01_050_RAMUPARUDO_FREE_START
end
function RAMUPARUDOTbl.S01_080_RAMUPARUDO_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("RAMUPARUDO"))
  HeroBackTalkRAMUPARUDO()
  OpenJudgmentShopMenu()
  subUsuComFuncTalkOutBase01(CH("RAMUPARUDO"), result)
end
function RAMUPARUDOTbl.ALL_CLEAR_RAMUPARUDO_FREE_START()
  return RAMUPARUDOTbl.S01_080_RAMUPARUDO_FREE_START
end

