function SAZANDORATbl.M12_010_SAZANDORA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("SAZANDORA_LARGE"))
  WINDOW:SysMsg(-1718309041)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("SAZANDORA_LARGE"), result)
end
function SAZANDORATbl.M12_020_SAZANDORA_FREE_START()
  return SAZANDORATbl.M12_010_SAZANDORA_FREE_START
end
function SAZANDORATbl.M12_030_SAZANDORA_FREE_START()
  return SAZANDORATbl.M12_020_SAZANDORA_FREE_START
end
function SAZANDORATbl.M12_040_SAZANDORA_FREE_START()
  return SAZANDORATbl.M12_030_SAZANDORA_FREE_START
end
function SAZANDORATbl.M12_050_SAZANDORA_FREE_START()
  return SAZANDORATbl.M12_040_SAZANDORA_FREE_START
end
function SAZANDORATbl.M12_070_SAZANDORA_FREE_START()
  return SAZANDORATbl.M12_050_SAZANDORA_FREE_START
end
function SAZANDORATbl.M13_010_SAZANDORA_FREE_START()
  return SAZANDORATbl.M12_070_SAZANDORA_FREE_START
end
function SAZANDORATbl.M13_030_SAZANDORA_FREE_START()
  return SAZANDORATbl.M13_010_SAZANDORA_FREE_START
end
function SAZANDORATbl.M13_040_SAZANDORA_FREE_START()
  return SAZANDORATbl.M13_030_SAZANDORA_FREE_START
end
function SAZANDORATbl.M13_060_SAZANDORA_FREE_START()
  return SAZANDORATbl.M13_040_SAZANDORA_FREE_START
end
function SAZANDORATbl.M13_070_SAZANDORA_FREE_START()
  return SAZANDORATbl.M13_060_SAZANDORA_FREE_START
end
function SAZANDORATbl.M13_080_SAZANDORA_FREE_START()
  return SAZANDORATbl.M13_070_SAZANDORA_FREE_START
end
function SAZANDORATbl.M13_090_SAZANDORA_FREE_START()
  return SAZANDORATbl.M13_080_SAZANDORA_FREE_START
end
function SAZANDORATbl.M13_095_SAZANDORA_FREE_START()
  return SAZANDORATbl.M13_090_SAZANDORA_FREE_START
end
function SAZANDORATbl.M13_110_SAZANDORA_FREE_START()
  return SAZANDORATbl.M13_095_SAZANDORA_FREE_START
end
function SAZANDORATbl.M14_010_SAZANDORA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("SAZANDORA_LARGE"))
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), -2138071538)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("SAZANDORA_LARGE"), result)
end
function SAZANDORATbl.M14_030_SAZANDORA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("SAZANDORA_LARGE"))
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), -1415393843)
  WINDOW:Talk(SymAct("SAZANDORA"), -1296434036)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("SAZANDORA_LARGE"), result)
end
function SAZANDORATbl.M14_040_SAZANDORA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("SAZANDORA_LARGE"))
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), -34051509)
  WINDOW:Talk(SymAct("SAZANDORA"), -454862070)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("SAZANDORA_LARGE"), result)
end
function SAZANDORATbl.M14_060_SAZANDORA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("SAZANDORA_LARGE"))
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), -808580919)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("SAZANDORA_LARGE"), result)
end
function SAZANDORATbl.M14_070_SAZANDORA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("SAZANDORA_LARGE"))
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), -690669176)
  WINDOW:Talk(SymAct("SAZANDORA"), 1364010311)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("SAZANDORA_LARGE"), result)
end
function SAZANDORATbl.M14_090_SAZANDORA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("SAZANDORA_LARGE"))
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), 1213600774)
  WINDOW:Talk(SymAct("SAZANDORA"), 397096782)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("SAZANDORA_LARGE"), result)
end
function SAZANDORATbl.M15_010_SAZANDORA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("SAZANDORA_LARGE"))
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), 246416911)
  WINDOW:Talk(SymAct("SAZANDORA"), 631068108)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("SAZANDORA_LARGE"), result)
end
function SAZANDORATbl.M15_020_SAZANDORA_FREE_START()
  return SAZANDORATbl.M15_010_SAZANDORA_FREE_START
end
function SAZANDORATbl.M15_030_SAZANDORA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("SAZANDORA_LARGE"))
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), 1015440525)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("SAZANDORA_LARGE"), result)
end
function SAZANDORATbl.M16_010_SAZANDORA_FREE_START()
  return SAZANDORATbl.M15_030_SAZANDORA_FREE_START
end
function SAZANDORATbl.M16_040_SAZANDORA_FREE_START()
  return SAZANDORATbl.M16_010_SAZANDORA_FREE_START
end
function SAZANDORATbl.M16_080_SAZANDORA_FREE_START()
  return SAZANDORATbl.M16_040_SAZANDORA_FREE_START
end
function SAZANDORATbl.M16_090_SAZANDORA_FREE_START()
  return SAZANDORATbl.M16_080_SAZANDORA_FREE_START
end
function SAZANDORATbl.M16_100_SAZANDORA_FREE_START()
  return SAZANDORATbl.M16_090_SAZANDORA_FREE_START
end
function SAZANDORATbl.M16_105_SAZANDORA_FREE_START()
  return SAZANDORATbl.M16_100_SAZANDORA_FREE_START
end
function SAZANDORATbl.M16_120_SAZANDORA_FREE_START()
  return SAZANDORATbl.M16_105_SAZANDORA_FREE_START
end
function SAZANDORATbl.M17_020_SAZANDORA_FREE_START()
  return SAZANDORATbl.M16_120_SAZANDORA_FREE_START
end
function SAZANDORATbl.M17_040_SAZANDORA_FREE_START()
  return SAZANDORATbl.M17_020_SAZANDORA_FREE_START
end
function SAZANDORATbl.M17_060_SAZANDORA_FREE_START()
  return SAZANDORATbl.M17_040_SAZANDORA_FREE_START
end
function SAZANDORATbl.M17_065_SAZANDORA_FREE_START()
  return SAZANDORATbl.M17_060_SAZANDORA_FREE_START
end
function SAZANDORATbl.M17_090_SAZANDORA_FREE_START()
  return SAZANDORATbl.M17_065_SAZANDORA_FREE_START
end
function SAZANDORATbl.M17_120_SAZANDORA_FREE_START()
  return SAZANDORATbl.M17_090_SAZANDORA_FREE_START
end
function SAZANDORATbl.M17_140_SAZANDORA_FREE_START()
  return SAZANDORATbl.M17_120_SAZANDORA_FREE_START
end
function SAZANDORATbl.M17_150_SAZANDORA_FREE_START()
  return SAZANDORATbl.M17_140_SAZANDORA_FREE_START
end
function SAZANDORATbl.M17_155_SAZANDORA_FREE_START()
  return SAZANDORATbl.M17_150_SAZANDORA_FREE_START
end
function SAZANDORATbl.M17_170_SAZANDORA_FREE_START()
  return SAZANDORATbl.M17_155_SAZANDORA_FREE_START
end
function SAZANDORATbl.M17_200_SAZANDORA_FREE_START()
  return SAZANDORATbl.M17_170_SAZANDORA_FREE_START
end
function SAZANDORATbl.M17_210_SAZANDORA_FREE_START()
  return SAZANDORATbl.M17_200_SAZANDORA_FREE_START
end
function SAZANDORATbl.M17_220_SAZANDORA_FREE_START()
  return SAZANDORATbl.M17_210_SAZANDORA_FREE_START
end
function SAZANDORATbl.M17_225_SAZANDORA_FREE_START()
  return SAZANDORATbl.M17_220_SAZANDORA_FREE_START
end
function SAZANDORATbl.M17_240_SAZANDORA_FREE_START()
  return SAZANDORATbl.M17_225_SAZANDORA_FREE_START
end
function SAZANDORATbl.M18_020_SAZANDORA_FREE_START()
  return SAZANDORATbl.M17_240_SAZANDORA_FREE_START
end
function SAZANDORATbl.M18_030_SAZANDORA_FREE_START()
  return SAZANDORATbl.M18_020_SAZANDORA_FREE_START
end
function SAZANDORATbl.S01_010_SAZANDORA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("SAZANDORA_LARGE"))
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), 1942483530)
  WINDOW:Talk(SymAct("SAZANDORA"), 1792852747)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("SAZANDORA_LARGE"), result)
end
function SAZANDORATbl.S01_020_SAZANDORA_FREE_START()
  local result = subUsuComFuncTalkInBase02(CH("SAZANDORA_LARGE"))
  CH("SAZANDORA_LARGE"):SetMotionRaito(Raito(2))
  CH("SAZANDORA_LARGE"):SetMotion(SymMot("SPEAK"), LOOP.ON)
  CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("SAZANDORA"), 1106350280)
  WINDOW:CloseMessage()
  CH("SAZANDORA_LARGE"):SetMotionRaito(Raito(1))
  CH("SAZANDORA_LARGE"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  local result = subUsuComFuncTalkInBase01(CH("SAZANDORA_LARGE"))
  CH("SAZANDORA_LARGE"):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.GLADNESS)
  WINDOW:Talk(SymAct("SAZANDORA"), 1491771785)
  WINDOW:Talk(SymAct("SAZANDORA"), -546128570)
  WINDOW:CloseMessage()
  CH("SAZANDORA_LARGE"):ResetManpu()
  subUsuComFuncTalkOutBase01(CH("SAZANDORA_LARGE"), result)
  CH("SAZANDORA_LARGE"):SetMotionRaito(Raito(2))
  CH("SAZANDORA_LARGE"):SetMotion(SymMot("SPEAK"), LOOP.ON)
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("SAZANDORA"), -966161401)
  WINDOW:CloseMessage()
end
function SAZANDORATbl.S01_030_SAZANDORA_FREE_START()
  return SAZANDORATbl.S01_020_SAZANDORA_FREE_START
end
function SAZANDORATbl.S01_040_SAZANDORA_FREE_START()
  return SAZANDORATbl.S01_030_SAZANDORA_FREE_START
end
function SAZANDORATbl.S01_050_SAZANDORA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("SAZANDORA_LARGE"))
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), 85891232)
  WINDOW:Talk(SymAct("SAZANDORA"), 470133217)
  WINDOW:Talk(SymAct("SAZANDORA"), 925432354)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("SAZANDORA_LARGE"), result)
end
function SAZANDORATbl.S01_060_SAZANDORA_FREE_START()
  return SAZANDORATbl.S01_050_SAZANDORA_FREE_START
end
function SAZANDORATbl.S01_080_SAZANDORA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("SAZANDORA_LARGE"))
  if FLAG.SazandoraCounter == CONST.CNT_1 then
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
    CH("SAZANDORA_LARGE"):SetManpu("MP_EXCLAMATION")
    CH("SAZANDORA_LARGE"):WaitManpu()
    CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
    WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.SURPRISE)
    WINDOW:Talk(SymAct("SAZANDORA"), 775146339)
    WINDOW:Talk(SymAct("SAZANDORA"), 1634885028)
    WINDOW:Talk(SymAct("SAZANDORA"), 2020175077)
    WINDOW:CloseMessage()
    CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
    CH("SAZANDORA_LARGE"):SetManpu("MP_FLY_SWEAT")
    CH("SAZANDORA_LARGE"):WaitManpu()
    WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.PAIN)
    WINDOW:Talk(SymAct("SAZANDORA"), 1396981542)
    WINDOW:KeyWait()
    CH("SAZANDORA_LARGE"):SetManpu("MP_LAUGH_LP")
    CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.GLADNESS)
    WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.GLADNESS)
    WINDOW:Talk(SymAct("SAZANDORA"), 1247743591)
    WINDOW:KeyWait()
    CH("SAZANDORA_LARGE"):ResetManpu()
    CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
    CH("SAZANDORA_LARGE"):SetManpu("MP_FLY_SWEAT")
    WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.PAIN)
    WINDOW:Talk(SymAct("SAZANDORA"), -842591576)
    WINDOW:Talk(SymAct("SAZANDORA"), -723770391)
    WINDOW:CloseMessage()
    CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.NORMAL)
    FLAG.SazandoraCounter = CONST.CNT_2
  else
    CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
    CH("SAZANDORA_LARGE"):SetManpu("MP_FLY_SWEAT")
    WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.PAIN)
    WINDOW:Talk(SymAct("SAZANDORA"), -1113391163)
    WINDOW:CloseMessage()
    CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  end
  subUsuComFuncTalkOutBase01(CH("SAZANDORA_LARGE"), result)
end
function SAZANDORATbl.ALL_CLEAR_SAZANDORA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("SAZANDORA_LARGE"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("SAZANDORA_LARGE"):SetManpu("MP_EXCLAMATION")
  CH("SAZANDORA_LARGE"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("SAZANDORA"), -1531326844)
  WINDOW:CloseMessage()
  CH("SAZANDORA_LARGE"):DirTo(RotateTarget(45), Speed(350), ROT_TYPE.NEAR)
  CH("SAZANDORA_LARGE"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("SAZANDORA"), -1886085817)
  WINDOW:KeyWait()
  TASK:Regist(subEveDoubleJump, {
    CH("SAZANDORA_LARGE")
  })
  WINDOW:Talk(SymAct("SAZANDORA"), -1768969210)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("SAZANDORA_LARGE"), result)
end

