function SAZANDORATbl.M02_010_SAZANDORA_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("SAZANDORA_LARGE"))
  WINDOW:SysMsg(-1696552139)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("SAZANDORA_LARGE"), result)
end
function SAZANDORATbl.M02_030_SAZANDORA_FREE_START()
  return SAZANDORATbl.M02_010_SAZANDORA_FREE_START
end
function SAZANDORATbl.M02_050_SAZANDORA_FREE_START()
  return SAZANDORATbl.M02_030_SAZANDORA_FREE_START
end
function SAZANDORATbl.M02_070_SAZANDORA_FREE_START()
  return SAZANDORATbl.M02_050_SAZANDORA_FREE_START
end
function SAZANDORATbl.M02_080_SAZANDORA_FREE_START()
  return SAZANDORATbl.M02_070_SAZANDORA_FREE_START
end
function SAZANDORATbl.M02_090_SAZANDORA_FREE_START()
  return SAZANDORATbl.M02_080_SAZANDORA_FREE_START
end
function SAZANDORATbl.M02_100_SAZANDORA_FREE_START()
  return SAZANDORATbl.M02_090_SAZANDORA_FREE_START
end
function SAZANDORATbl.M02_115_SAZANDORA_FREE_START()
  return SAZANDORATbl.M02_100_SAZANDORA_FREE_START
end
function SAZANDORATbl.M02_130_SAZANDORA_FREE_START()
  return SAZANDORATbl.M02_115_SAZANDORA_FREE_START
end
function SAZANDORATbl.M02_160_SAZANDORA_FREE_START()
  return SAZANDORATbl.M02_130_SAZANDORA_FREE_START
end
function SAZANDORATbl.M03_010_SAZANDORA_FREE_START()
  return SAZANDORATbl.M02_160_SAZANDORA_FREE_START
end
function SAZANDORATbl.M03_020_SAZANDORA_FREE_START()
  return SAZANDORATbl.M03_010_SAZANDORA_FREE_START
end
function SAZANDORATbl.M03_045_SAZANDORA_FREE_START()
  return SAZANDORATbl.M03_020_SAZANDORA_FREE_START
end
function SAZANDORATbl.M03_090_SAZANDORA_FREE_START()
  return SAZANDORATbl.M03_045_SAZANDORA_FREE_START
end
function SAZANDORATbl.M03_110_SAZANDORA_FREE_START()
  return SAZANDORATbl.M03_090_SAZANDORA_FREE_START
end
function SAZANDORATbl.M03_130_SAZANDORA_FREE_START()
  return SAZANDORATbl.M03_110_SAZANDORA_FREE_START
end
function SAZANDORATbl.M03_150_SAZANDORA_FREE_START()
  return SAZANDORATbl.M03_130_SAZANDORA_FREE_START
end
function SAZANDORATbl.M04_010_SAZANDORA_FREE_START()
  return SAZANDORATbl.M03_150_SAZANDORA_FREE_START
end
function SAZANDORATbl.M04_020_SAZANDORA_FREE_START()
  return SAZANDORATbl.M04_010_SAZANDORA_FREE_START
end
function SAZANDORATbl.M04_HANYOU_SAZANDORA_FREE_START()
  return SAZANDORATbl.M04_020_SAZANDORA_FREE_START
end
function SAZANDORATbl.M04_040_SAZANDORA_FREE_START()
  return SAZANDORATbl.M04_HANYOU_SAZANDORA_FREE_START
end
function SAZANDORATbl.M04_060_SAZANDORA_FREE_START()
  return SAZANDORATbl.M04_040_SAZANDORA_FREE_START
end
function SAZANDORATbl.M04_070_SAZANDORA_FREE_START()
  return SAZANDORATbl.M04_060_SAZANDORA_FREE_START
end
function SAZANDORATbl.M04_HANYOU_SAZANDORA_FREE_START2()
  return SAZANDORATbl.M04_070_SAZANDORA_FREE_START
end
function SAZANDORATbl.M05_000_SAZANDORA_FREE_START()
  return SAZANDORATbl.M04_HANYOU_SAZANDORA_FREE_START2
end
function SAZANDORATbl.M05_010_SAZANDORA_FREE_START()
  return SAZANDORATbl.M05_000_SAZANDORA_FREE_START
end
function SAZANDORATbl.M05_020_SAZANDORA_FREE_START()
  return SAZANDORATbl.M05_010_SAZANDORA_FREE_START
end
function SAZANDORATbl.M05_030_SAZANDORA_FREE_START()
  return SAZANDORATbl.M05_020_SAZANDORA_FREE_START
end
function SAZANDORATbl.M06_HANYOU_SAZANDORA_FREE_START()
  return SAZANDORATbl.M05_030_SAZANDORA_FREE_START
end
function SAZANDORATbl.M06_010_SAZANDORA_FREE_START()
  return SAZANDORATbl.M06_HANYOU_SAZANDORA_FREE_START
end
function SAZANDORATbl.M06_015_SAZANDORA_FREE_START()
  return SAZANDORATbl.M06_010_SAZANDORA_FREE_START
end
function SAZANDORATbl.M06_020_SAZANDORA_FREE_START()
  return SAZANDORATbl.M06_015_SAZANDORA_FREE_START
end
function SAZANDORATbl.M06_030_SAZANDORA_FREE_START()
  return SAZANDORATbl.M06_020_SAZANDORA_FREE_START
end
function SAZANDORATbl.M06_040_SAZANDORA_FREE_START()
  return SAZANDORATbl.M06_030_SAZANDORA_FREE_START
end
function SAZANDORATbl.M06_060_SAZANDORA_FREE_START()
  return SAZANDORATbl.M06_040_SAZANDORA_FREE_START
end
function SAZANDORATbl.M07_000_SAZANDORA_FREE_START()
  return SAZANDORATbl.M06_060_SAZANDORA_FREE_START
end
function SAZANDORATbl.M07_010_SAZANDORA_FREE_START()
  return SAZANDORATbl.M07_000_SAZANDORA_FREE_START
end
function SAZANDORATbl.M07_020_SAZANDORA_FREE_START()
  return SAZANDORATbl.M07_010_SAZANDORA_FREE_START
end
function SAZANDORATbl.M07_045_SAZANDORA_FREE_START()
  return SAZANDORATbl.M07_020_SAZANDORA_FREE_START
end
function SAZANDORATbl.M07_HANYOU_SAZANDORA_FREE_START()
  return SAZANDORATbl.M07_045_SAZANDORA_FREE_START
end
function SAZANDORATbl.M07_080_SAZANDORA_FREE_START()
  return SAZANDORATbl.M07_HANYOU_SAZANDORA_FREE_START
end
function SAZANDORATbl.M08_010_SAZANDORA_FREE_START()
  return SAZANDORATbl.M07_080_SAZANDORA_FREE_START
end
function SAZANDORATbl.M08_HANYOU_SAZANDORA_FREE_START()
  return SAZANDORATbl.M08_010_SAZANDORA_FREE_START
end
function SAZANDORATbl.M08_020_SAZANDORA_FREE_START()
  return SAZANDORATbl.M08_HANYOU_SAZANDORA_FREE_START
end
function SAZANDORATbl.M08_040_SAZANDORA_FREE_START()
  return SAZANDORATbl.M08_020_SAZANDORA_FREE_START
end
function SAZANDORATbl.M08_050_SAZANDORA_FREE_START()
  return SAZANDORATbl.M08_040_SAZANDORA_FREE_START
end
function SAZANDORATbl.M08_055_SAZANDORA_FREE_START()
  return SAZANDORATbl.M08_050_SAZANDORA_FREE_START
end
function SAZANDORATbl.M08_070_SAZANDORA_FREE_START()
  return SAZANDORATbl.M08_055_SAZANDORA_FREE_START
end
function SAZANDORATbl.M09_HANYOU_SAZANDORA_FREE_START1()
  return SAZANDORATbl.M08_070_SAZANDORA_FREE_START
end
function SAZANDORATbl.M09_010_SAZANDORA_FREE_START()
  return SAZANDORATbl.M09_HANYOU_SAZANDORA_FREE_START1
end
function SAZANDORATbl.M09_020_SAZANDORA_FREE_START()
  return SAZANDORATbl.M09_010_SAZANDORA_FREE_START
end
function SAZANDORATbl.M09_040_SAZANDORA_FREE_START()
  return SAZANDORATbl.M09_020_SAZANDORA_FREE_START
end
function SAZANDORATbl.M09_HANYOU_SAZANDORA_FREE_START2()
  return SAZANDORATbl.M09_040_SAZANDORA_FREE_START
end
function SAZANDORATbl.M09_060_SAZANDORA_FREE_START()
  return SAZANDORATbl.M09_HANYOU_SAZANDORA_FREE_START2
end
function SAZANDORATbl.M09_080_SAZANDORA_FREE_START()
  return SAZANDORATbl.M09_060_SAZANDORA_FREE_START
end
function SAZANDORATbl.M09_100_SAZANDORA_FREE_START()
  return SAZANDORATbl.M09_080_SAZANDORA_FREE_START
end
function SAZANDORATbl.M09_110_SAZANDORA_FREE_START()
  return SAZANDORATbl.M09_100_SAZANDORA_FREE_START
end
function SAZANDORATbl.M09_120_SAZANDORA_FREE_START()
  return SAZANDORATbl.M09_110_SAZANDORA_FREE_START
end
function SAZANDORATbl.M10_010_SAZANDORA_FREE_START()
  return SAZANDORATbl.M09_120_SAZANDORA_FREE_START
end
function SAZANDORATbl.M10_030_SAZANDORA_FREE_START()
  return SAZANDORATbl.M10_010_SAZANDORA_FREE_START
end
function SAZANDORATbl.M10_040_SAZANDORA_FREE_START()
  return SAZANDORATbl.M10_030_SAZANDORA_FREE_START
end
function SAZANDORATbl.M10_060_SAZANDORA_FREE_START()
  return SAZANDORATbl.M10_040_SAZANDORA_FREE_START
end
function SAZANDORATbl.M11_010_SAZANDORA_FREE_START()
  return SAZANDORATbl.M10_060_SAZANDORA_FREE_START
end
function SAZANDORATbl.M11_030_SAZANDORA_FREE_START()
  return SAZANDORATbl.M11_010_SAZANDORA_FREE_START
end
function SAZANDORATbl.M11_040_SAZANDORA_FREE_START()
  return SAZANDORATbl.M11_030_SAZANDORA_FREE_START
end
function SAZANDORATbl.M11_050_SAZANDORA_FREE_START()
  return SAZANDORATbl.M11_040_SAZANDORA_FREE_START
end
function SAZANDORATbl.M11_060_SAZANDORA_FREE_START()
  return SAZANDORATbl.M11_050_SAZANDORA_FREE_START
end
function SAZANDORATbl.M11_090_SAZANDORA_FREE_START()
  return SAZANDORATbl.M11_060_SAZANDORA_FREE_START
end

