function SUTAAMIITbl.M02_010_SUTAAMII_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("SUTAAMII"))
  WINDOW:SysMsg(-56370604)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("SUTAAMII"), result)
end
function SUTAAMIITbl.M02_030_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M02_010_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M02_050_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M02_030_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M02_070_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M02_050_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M02_080_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M02_070_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M02_090_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M02_080_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M02_100_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M02_090_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M02_115_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M02_100_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M02_130_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M02_115_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M02_160_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M02_130_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M03_010_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M02_160_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M03_020_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M03_010_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M03_045_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M03_020_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M03_090_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M03_045_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M03_110_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M03_090_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M03_130_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M03_110_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M03_150_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M03_130_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M04_010_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M03_150_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M04_020_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M04_010_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M04_HANYOU_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M04_020_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M04_040_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M04_HANYOU_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M04_060_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M04_040_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M04_070_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M04_060_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M04_HANYOU_SUTAAMII_FREE_START2()
  return SUTAAMIITbl.M04_070_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M05_000_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M04_HANYOU_SUTAAMII_FREE_START2
end
function SUTAAMIITbl.M05_010_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M05_000_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M05_020_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M05_010_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M05_030_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M05_020_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M06_HANYOU_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M05_030_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M06_010_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M06_HANYOU_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M06_015_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M06_010_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M06_020_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M06_015_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M06_030_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M06_020_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M06_040_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M06_030_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M06_060_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M06_040_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M07_000_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M06_060_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M07_010_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M07_000_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M07_020_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M07_010_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M07_045_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M07_020_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M07_HANYOU_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M07_045_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M07_080_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M07_HANYOU_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M08_010_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M07_080_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M08_HANYOU_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M08_010_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M08_020_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M08_HANYOU_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M08_040_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M08_020_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M08_050_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M08_040_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M08_055_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M08_050_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M08_070_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M08_055_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M09_HANYOU_SUTAAMII_FREE_START1()
  return SUTAAMIITbl.M08_070_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M09_010_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M09_HANYOU_SUTAAMII_FREE_START1
end
function SUTAAMIITbl.M09_020_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M09_010_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M09_040_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M09_020_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M09_HANYOU_SUTAAMII_FREE_START2()
  return SUTAAMIITbl.M09_040_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M09_060_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M09_HANYOU_SUTAAMII_FREE_START2
end
function SUTAAMIITbl.M09_080_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M09_060_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M09_100_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M09_080_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M09_110_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M09_100_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M09_120_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M09_110_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M10_010_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M09_120_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M10_030_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M10_010_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M10_040_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M10_030_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M10_060_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M10_040_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M11_010_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M10_060_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M11_030_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M11_010_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M11_040_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M11_030_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M11_050_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M11_040_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M11_060_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M11_050_SUTAAMII_FREE_START
end
function SUTAAMIITbl.M11_090_SUTAAMII_FREE_START()
  return SUTAAMIITbl.M11_060_SUTAAMII_FREE_START
end

