function TAMAGETAKETbl.M02_010_TAMAGETAKE_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("TAMAGETAKE"))
  WINDOW:SysMsg(-145903276)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("TAMAGETAKE"), result)
end
function TAMAGETAKETbl.M02_030_TAMAGETAKE_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("TAMAGETAKE"))
  WINDOW:DrawFace(20, 88, SymAct("TAMAGETAKE"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("TAMAGETAKE"), -296321003)
  do
    local __LB_SCOPE = function()
      local __scopeFuncTbl = {}
      function __scopeFuncTbl.__LB_FIRST()
      end
      function __scopeFuncTbl.CELECT_EVENT01()
        WINDOW:DrawFace(20, 88, SymAct("TAMAGETAKE"), FACE_TYPE.NORMAL)
        WINDOW:Talk(SymAct("TAMAGETAKE"), -981740586)
        local __labelCnt = 0
        local __labelTbl = {}
        WINDOW:SelectStart()
        WINDOW:SelectChain(-597630313, __labelCnt)
        __labelTbl[__labelCnt] = __scopeFuncTbl.LABEL_YES
        __labelCnt = __labelCnt + 1
        WINDOW:SelectChain(-1826524080, __labelCnt)
        WINDOW:DefaultCursor(__labelCnt)
        __labelTbl[__labelCnt] = __scopeFuncTbl.LABEL_NO
        __labelCnt = __labelCnt + 1
        WINDOW:SelectChain(-1975892719, __labelCnt)
        __labelTbl[__labelCnt] = __scopeFuncTbl.LABEL_HELP
        __labelCnt = __labelCnt + 1
        local __res = WINDOW:SelectEndTalk(MENU_SELECT_MODE.ENABLE_CANCEL)
        return __labelTbl[__res]
      end
      function __scopeFuncTbl.LABEL_YES()
        WINDOW:CloseMessage()
        WINDOW:DrawFace(20, 88, SymAct("TAMAGETAKE"), FACE_TYPE.NORMAL)
        WINDOW:Talk(SymAct("TAMAGETAKE"), -1592322350)
        subEveCloseMsg()
        Ground_Save("normal")
        SOUND:FadeOutBgm(TimeSec(1))
        subEveToProgFadeSet()
        SOUND:WaitBgm()
        SYSTEM:SetAddContentsMode(true)
        SYSTEM:ReturnTopMenu()
      end
      function __scopeFuncTbl.LABEL_NO()
        WINDOW:CloseMessage()
        return __scopeFuncTbl.LABEL_END
      end
      function __scopeFuncTbl.LABEL_HELP()
        WINDOW:CloseMessage()
        WINDOW:DrawFace(20, 88, SymAct("TAMAGETAKE"), FACE_TYPE.NORMAL)
        WINDOW:Talk(SymAct("TAMAGETAKE"), -1207162989)
        WINDOW:Talk(SymAct("TAMAGETAKE"), 1066679132)
        WINDOW:CloseMessage()
        return __scopeFuncTbl.CELECT_EVENT01
      end
      function __scopeFuncTbl.LABEL_END()
      end
      local __next = __scopeFuncTbl.CELECT_EVENT01
      while __next ~= nil do
        __next = __next()
      end
    end
    __LB_SCOPE()
  end
  subUsuComFuncTalkOutBase01(CH("TAMAGETAKE"), result)
end
function TAMAGETAKETbl.M02_050_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M02_030_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M02_070_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M02_050_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M02_080_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M02_070_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M02_090_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M02_080_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M02_100_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M02_090_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M02_115_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M02_100_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M02_130_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M02_115_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M02_160_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M02_130_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M03_010_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M02_160_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M03_020_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M03_010_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M03_045_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M03_020_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M03_090_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M03_045_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M03_110_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M03_090_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M03_130_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M03_110_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M03_150_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M03_130_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M04_010_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M03_150_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M04_020_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M04_010_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M04_HANYOU_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M04_020_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M04_040_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M04_HANYOU_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M04_060_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M04_040_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M04_070_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M04_060_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M04_HANYOU_TAMAGETAKE_FREE_START2()
  return TAMAGETAKETbl.M04_070_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M05_000_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M04_HANYOU_TAMAGETAKE_FREE_START2
end
function TAMAGETAKETbl.M05_010_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M05_000_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M05_020_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M05_010_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M05_030_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M05_020_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M06_HANYOU_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M05_030_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M06_010_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M06_HANYOU_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M06_015_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M06_010_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M06_020_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M06_015_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M06_030_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M06_020_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M06_040_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M06_030_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M06_060_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M06_040_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M07_000_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M06_060_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M07_010_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M07_000_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M07_020_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M07_010_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M07_045_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M07_020_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M07_HANYOU_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M07_045_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M07_080_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M07_HANYOU_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M08_010_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M07_080_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M08_HANYOU_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M08_010_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M08_020_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M08_HANYOU_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M08_040_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M08_020_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M08_050_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M08_040_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M08_055_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M08_050_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M08_070_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M08_055_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M09_HANYOU_TAMAGETAKE_FREE_START1()
  return TAMAGETAKETbl.M08_070_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M09_010_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M09_HANYOU_TAMAGETAKE_FREE_START1
end
function TAMAGETAKETbl.M09_020_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M09_010_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M09_040_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M09_020_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M09_HANYOU_TAMAGETAKE_FREE_START2()
  return TAMAGETAKETbl.M09_040_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M09_060_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M09_HANYOU_TAMAGETAKE_FREE_START2
end
function TAMAGETAKETbl.M09_080_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M09_060_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M09_100_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M09_080_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M09_110_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M09_100_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M09_120_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M09_110_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M10_010_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M09_120_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M10_030_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M10_010_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M10_040_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M10_030_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M10_060_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M10_040_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M11_010_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M10_060_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M11_030_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M11_010_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M11_040_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M11_030_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M11_050_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M11_040_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M11_060_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M11_050_TAMAGETAKE_FREE_START
end
function TAMAGETAKETbl.M11_090_TAMAGETAKE_FREE_START()
  return TAMAGETAKETbl.M11_060_TAMAGETAKE_FREE_START
end

