function YABUKURONTbl.M02_010_YABUKURON_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("YABUKURON"))
  WINDOW:SysMsg(-505307083)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("YABUKURON"), result)
end
function YABUKURONTbl.M02_030_YABUKURON_FREE_START()
  return YABUKURONTbl.M02_010_YABUKURON_FREE_START
end
function YABUKURONTbl.M02_050_YABUKURON_FREE_START()
  return YABUKURONTbl.M02_030_YABUKURON_FREE_START
end
function YABUKURONTbl.M02_070_YABUKURON_FREE_START()
  return YABUKURONTbl.M02_050_YABUKURON_FREE_START
end
function YABUKURONTbl.M02_080_YABUKURON_FREE_START()
  return YABUKURONTbl.M02_070_YABUKURON_FREE_START
end
function YABUKURONTbl.M02_090_YABUKURON_FREE_START()
  return YABUKURONTbl.M02_080_YABUKURON_FREE_START
end
function YABUKURONTbl.M02_100_YABUKURON_FREE_START()
  return YABUKURONTbl.M02_090_YABUKURON_FREE_START
end
function YABUKURONTbl.M02_115_YABUKURON_FREE_START()
  return YABUKURONTbl.M02_100_YABUKURON_FREE_START
end
function YABUKURONTbl.M02_130_YABUKURON_FREE_START()
  return YABUKURONTbl.M02_115_YABUKURON_FREE_START
end
function YABUKURONTbl.M02_160_YABUKURON_FREE_START()
  return YABUKURONTbl.M02_130_YABUKURON_FREE_START
end
function YABUKURONTbl.M03_010_YABUKURON_FREE_START()
  return YABUKURONTbl.M02_160_YABUKURON_FREE_START
end
function YABUKURONTbl.M03_020_YABUKURON_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("YABUKURON"))
  WINDOW:DrawFace(20, 88, SymAct("YABUKURON"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YABUKURON"), -117796492)
  WINDOW:Talk(SymAct("YABUKURON"), -740834633)
  WINDOW:Talk(SymAct("YABUKURON"), -892537866)
  WINDOW:Talk(SymAct("YABUKURON"), -2054331087)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("YABUKURON"), result)
end
function YABUKURONTbl.M03_045_YABUKURON_FREE_START()
  return YABUKURONTbl.M03_020_YABUKURON_FREE_START
end
function YABUKURONTbl.M03_090_YABUKURON_FREE_START()
  return YABUKURONTbl.M03_045_YABUKURON_FREE_START
end
function YABUKURONTbl.M03_110_YABUKURON_FREE_START()
  return YABUKURONTbl.M03_090_YABUKURON_FREE_START
end
function YABUKURONTbl.M03_130_YABUKURON_FREE_START()
  return YABUKURONTbl.M03_110_YABUKURON_FREE_START
end
function YABUKURONTbl.M03_150_YABUKURON_FREE_START()
  return YABUKURONTbl.M03_130_YABUKURON_FREE_START
end
function YABUKURONTbl.M04_010_YABUKURON_FREE_START()
  return YABUKURONTbl.M03_150_YABUKURON_FREE_START
end
function YABUKURONTbl.M04_020_YABUKURON_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("YABUKURON"))
  WINDOW:DrawFace(20, 88, SymAct("YABUKURON"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YABUKURON"), -1667869584)
  WINDOW:Talk(SymAct("YABUKURON"), -1212479565)
  WINDOW:Talk(SymAct("YABUKURON"), -1365231886)
  WINDOW:Talk(SymAct("YABUKURON"), 691546685)
  WINDOW:Talk(SymAct("YABUKURON"), 807607164)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("YABUKURON"), result)
end
function YABUKURONTbl.M04_HANYOU_YABUKURON_FREE_START()
  return YABUKURONTbl.M04_020_YABUKURON_FREE_START
end
function YABUKURONTbl.M04_040_YABUKURON_FREE_START()
  return YABUKURONTbl.M04_HANYOU_YABUKURON_FREE_START
end
function YABUKURONTbl.M04_060_YABUKURON_FREE_START()
  return YABUKURONTbl.M04_040_YABUKURON_FREE_START
end
function YABUKURONTbl.M04_070_YABUKURON_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("YABUKURON"))
  WINDOW:DrawFace(20, 88, SymAct("YABUKURON"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YABUKURON"), 1388626902)
  WINDOW:KeyWait()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("YABUKURON"):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFace(20, 88, SymAct("YABUKURON"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("YABUKURON"), 1272967831)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("YABUKURON"), result)
end
function YABUKURONTbl.M04_HANYOU_YABUKURON_FREE_START2()
  return YABUKURONTbl.M04_070_YABUKURON_FREE_START
end
function YABUKURONTbl.M05_000_YABUKURON_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("YABUKURON"))
  WINDOW:DrawFace(20, 88, SymAct("YABUKURON"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YABUKURON"), 1626513748)
  WINDOW:Talk(SymAct("YABUKURON"), 2045349909)
  WINDOW:Talk(SymAct("YABUKURON"), 916981458)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("YABUKURON"), result)
end
function YABUKURONTbl.M05_010_YABUKURON_FREE_START()
  return YABUKURONTbl.M05_000_YABUKURON_FREE_START
end
function YABUKURONTbl.M05_020_YABUKURON_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("YABUKURON"))
  WINDOW:DrawFace(20, 88, SymAct("YABUKURON"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YABUKURON"), 800274323)
  WINDOW:Talk(SymAct("YABUKURON"), 77489232)
  WINDOW:Talk(SymAct("YABUKURON"), 495277329)
  WINDOW:Talk(SymAct("YABUKURON"), -1709356578)
  WINDOW:Talk(SymAct("YABUKURON"), -2096727905)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("YABUKURON"), result)
end
function YABUKURONTbl.M05_030_YABUKURON_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("YABUKURON"))
  WINDOW:DrawFace(20, 88, SymAct("YABUKURON"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("YABUKURON"), 1081175096)
  WINDOW:Talk(SymAct("YABUKURON"), 1500142969)
  WINDOW:Talk(SymAct("YABUKURON"), 1917259450)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("YABUKURON"), result)
end
function YABUKURONTbl.M06_HANYOU_YABUKURON_FREE_START()
  return YABUKURONTbl.M05_030_YABUKURON_FREE_START
end
function YABUKURONTbl.M06_010_YABUKURON_FREE_START()
  return YABUKURONTbl.M06_HANYOU_YABUKURON_FREE_START
end
function YABUKURONTbl.M06_015_YABUKURON_FREE_START()
  return YABUKURONTbl.M06_010_YABUKURON_FREE_START
end
function YABUKURONTbl.M06_020_YABUKURON_FREE_START()
  return YABUKURONTbl.M06_015_YABUKURON_FREE_START
end
function YABUKURONTbl.M06_030_YABUKURON_FREE_START()
  return YABUKURONTbl.M06_020_YABUKURON_FREE_START
end
function YABUKURONTbl.M06_040_YABUKURON_FREE_START()
  return YABUKURONTbl.M06_030_YABUKURON_FREE_START
end
function YABUKURONTbl.M06_060_YABUKURON_FREE_START()
  return YABUKURONTbl.M06_040_YABUKURON_FREE_START
end
function YABUKURONTbl.M07_000_YABUKURON_FREE_START()
  return YABUKURONTbl.M06_060_YABUKURON_FREE_START
end
function YABUKURONTbl.M07_010_YABUKURON_FREE_START()
  return YABUKURONTbl.M07_000_YABUKURON_FREE_START
end
function YABUKURONTbl.M07_020_YABUKURON_FREE_START()
  return YABUKURONTbl.M07_010_YABUKURON_FREE_START
end
function YABUKURONTbl.M07_045_YABUKURON_FREE_START()
  return YABUKURONTbl.M07_020_YABUKURON_FREE_START
end
function YABUKURONTbl.M07_HANYOU_YABUKURON_FREE_START()
  return YABUKURONTbl.M07_045_YABUKURON_FREE_START
end
function YABUKURONTbl.M07_080_YABUKURON_FREE_START()
  return YABUKURONTbl.M07_HANYOU_YABUKURON_FREE_START
end
function YABUKURONTbl.M08_010_YABUKURON_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("YABUKURON"))
  WINDOW:DrawFace(20, 88, SymAct("YABUKURON"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YABUKURON"), 1801207803)
  WINDOW:Talk(SymAct("YABUKURON"), 605923644)
  WINDOW:Talk(SymAct("YABUKURON"), 1023842429)
  WINDOW:CloseMessage()
  CH("YABUKURON"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.NEAR)
  CH("YABUKURON"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("YABUKURON"):SetManpu("MP_FLY_SWEAT")
  CH("YABUKURON"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("YABUKURON"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("YABUKURON"), 371968958)
  WINDOW:Talk(SymAct("YABUKURON"), 254868223)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("YABUKURON"), result)
end
function YABUKURONTbl.M08_HANYOU_YABUKURON_FREE_START()
  return YABUKURONTbl.M08_010_YABUKURON_FREE_START
end
function YABUKURONTbl.M08_020_YABUKURON_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("YABUKURON"))
  WINDOW:DrawFace(20, 88, SymAct("YABUKURON"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YABUKURON"), -2002196944)
  WINDOW:Talk(SymAct("YABUKURON"), -1850484879)
  WINDOW:Talk(SymAct("YABUKURON"), -120779939)
  WINDOW:Talk(SymAct("YABUKURON"), -506054116)
  WINDOW:Talk(SymAct("YABUKURON"), -889493025)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("YABUKURON"):SetManpu("MP_FLY_SWEAT")
  CH("YABUKURON"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("YABUKURON"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("YABUKURON"), -740271970)
  WINDOW:Talk(SymAct("YABUKURON"), -1667117479)
  WINDOW:Talk(SymAct("YABUKURON"), -2051342568)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("YABUKURON"), result)
end
function YABUKURONTbl.M08_040_YABUKURON_FREE_START()
  return YABUKURONTbl.M08_020_YABUKURON_FREE_START
end
function YABUKURONTbl.M08_050_YABUKURON_FREE_START()
  return YABUKURONTbl.M08_040_YABUKURON_FREE_START
end
function YABUKURONTbl.M08_055_YABUKURON_FREE_START()
  return YABUKURONTbl.M08_050_YABUKURON_FREE_START
end
function YABUKURONTbl.M08_070_YABUKURON_FREE_START()
  return YABUKURONTbl.M08_055_YABUKURON_FREE_START
end
function YABUKURONTbl.M09_HANYOU_YABUKURON_FREE_START1()
  return YABUKURONTbl.M08_070_YABUKURON_FREE_START
end
function YABUKURONTbl.M09_010_YABUKURON_FREE_START()
  return YABUKURONTbl.M09_HANYOU_YABUKURON_FREE_START1
end
function YABUKURONTbl.M09_020_YABUKURON_FREE_START()
  return YABUKURONTbl.M09_010_YABUKURON_FREE_START
end
function YABUKURONTbl.M09_040_YABUKURON_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("YABUKURON"))
  WINDOW:DrawFace(20, 88, SymAct("YABUKURON"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YABUKURON"), -1365791525)
  WINDOW:Talk(SymAct("YABUKURON"), -1215521382)
  WINDOW:Talk(SymAct("YABUKURON"), 806650197)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("YABUKURON"), result)
end
function YABUKURONTbl.M09_HANYOU_YABUKURON_FREE_START2()
  return YABUKURONTbl.M09_040_YABUKURON_FREE_START
end
function YABUKURONTbl.M09_060_YABUKURON_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("YABUKURON"))
  WINDOW:DrawFace(20, 88, SymAct("YABUKURON"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YABUKURON"), 688893972)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("YABUKURON"), result)
end
function YABUKURONTbl.M09_080_YABUKURON_FREE_START()
  return YABUKURONTbl.M09_060_YABUKURON_FREE_START
end
function YABUKURONTbl.M09_100_YABUKURON_FREE_START()
  return YABUKURONTbl.M09_080_YABUKURON_FREE_START
end
function YABUKURONTbl.M09_110_YABUKURON_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("YABUKURON"))
  WINDOW:DrawFace(20, 88, SymAct("YABUKURON"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YABUKURON"), 1696216036)
  WINDOW:Talk(SymAct("YABUKURON"), 2080440997)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("YABUKURON"), result)
end
function YABUKURONTbl.M09_120_YABUKURON_FREE_START()
  return YABUKURONTbl.M09_110_YABUKURON_FREE_START
end
function YABUKURONTbl.M10_010_YABUKURON_FREE_START()
  return YABUKURONTbl.M09_120_YABUKURON_FREE_START
end
function YABUKURONTbl.M10_030_YABUKURON_FREE_START()
  return YABUKURONTbl.M10_010_YABUKURON_FREE_START
end
function YABUKURONTbl.M10_040_YABUKURON_FREE_START()
  return YABUKURONTbl.M10_030_YABUKURON_FREE_START
end
function YABUKURONTbl.M10_060_YABUKURON_FREE_START()
  return YABUKURONTbl.M10_040_YABUKURON_FREE_START
end
function YABUKURONTbl.M11_010_YABUKURON_FREE_START()
  return YABUKURONTbl.M10_060_YABUKURON_FREE_START
end
function YABUKURONTbl.M11_030_YABUKURON_FREE_START()
  return YABUKURONTbl.M11_010_YABUKURON_FREE_START
end
function YABUKURONTbl.M11_040_YABUKURON_FREE_START()
  return YABUKURONTbl.M11_030_YABUKURON_FREE_START
end
function YABUKURONTbl.M11_050_YABUKURON_FREE_START()
  return YABUKURONTbl.M11_040_YABUKURON_FREE_START
end
function YABUKURONTbl.M11_060_YABUKURON_FREE_START()
  return YABUKURONTbl.M11_050_YABUKURON_FREE_START
end
function YABUKURONTbl.M11_090_YABUKURON_FREE_START()
  return YABUKURONTbl.M11_060_YABUKURON_FREE_START
end

