function YABUKURONTbl.M12_010_YABUKURON_FREE_START()
  return YABUKURONTbl.M11_090_YABUKURON_FREE_START
end
function YABUKURONTbl.M12_020_YABUKURON_FREE_START()
  return YABUKURONTbl.M12_010_YABUKURON_FREE_START
end
function YABUKURONTbl.M12_030_YABUKURON_FREE_START()
  return YABUKURONTbl.M12_020_YABUKURON_FREE_START
end
function YABUKURONTbl.M12_040_YABUKURON_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("YABUKURON"))
  WINDOW:DrawFace(20, 88, SymAct("YABUKURON"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YABUKURON"), -493509553)
  WINDOW:Talk(SymAct("YABUKURON"), -74541810)
  WINDOW:Talk(SymAct("YABUKURON"), -794573107)
  WINDOW:Talk(SymAct("YABUKURON"), -910624884)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("YABUKURON"), result)
end
function YABUKURONTbl.M12_050_YABUKURON_FREE_START()
  return YABUKURONTbl.M12_040_YABUKURON_FREE_START
end
function YABUKURONTbl.M12_070_YABUKURON_FREE_START()
  return YABUKURONTbl.M12_050_YABUKURON_FREE_START
end
function YABUKURONTbl.M13_010_YABUKURON_FREE_START()
  return YABUKURONTbl.M12_070_YABUKURON_FREE_START
end
function YABUKURONTbl.M13_030_YABUKURON_FREE_START()
  return YABUKURONTbl.M13_010_YABUKURON_FREE_START
end
function YABUKURONTbl.M13_040_YABUKURON_FREE_START()
  return YABUKURONTbl.M13_030_YABUKURON_FREE_START
end
function YABUKURONTbl.M13_060_YABUKURON_FREE_START()
  return YABUKURONTbl.M13_040_YABUKURON_FREE_START
end
function YABUKURONTbl.M13_070_YABUKURON_FREE_START()
  return YABUKURONTbl.M13_060_YABUKURON_FREE_START
end
function YABUKURONTbl.M13_080_YABUKURON_FREE_START()
  return YABUKURONTbl.M13_070_YABUKURON_FREE_START
end
function YABUKURONTbl.M13_090_YABUKURON_FREE_START()
  return YABUKURONTbl.M13_080_YABUKURON_FREE_START
end
function YABUKURONTbl.M13_095_YABUKURON_FREE_START()
  return YABUKURONTbl.M13_090_YABUKURON_FREE_START
end
function YABUKURONTbl.M13_110_YABUKURON_FREE_START()
  return YABUKURONTbl.M13_095_YABUKURON_FREE_START
end
function YABUKURONTbl.M14_010_YABUKURON_FREE_START()
  return YABUKURONTbl.M13_110_YABUKURON_FREE_START
end
function YABUKURONTbl.M14_030_YABUKURON_FREE_START()
  return YABUKURONTbl.M14_010_YABUKURON_FREE_START
end
function YABUKURONTbl.M14_040_YABUKURON_FREE_START()
  return YABUKURONTbl.M14_030_YABUKURON_FREE_START
end
function YABUKURONTbl.M14_060_YABUKURON_FREE_START()
  return YABUKURONTbl.M14_040_YABUKURON_FREE_START
end
function YABUKURONTbl.M14_070_YABUKURON_FREE_START()
  return YABUKURONTbl.M14_060_YABUKURON_FREE_START
end
function YABUKURONTbl.M14_090_YABUKURON_FREE_START()
  return YABUKURONTbl.M14_070_YABUKURON_FREE_START
end
function YABUKURONTbl.M15_010_YABUKURON_FREE_START()
  return YABUKURONTbl.M14_090_YABUKURON_FREE_START
end
function YABUKURONTbl.M15_020_YABUKURON_FREE_START()
  return YABUKURONTbl.M15_010_YABUKURON_FREE_START
end
function YABUKURONTbl.M15_030_YABUKURON_FREE_START()
  return YABUKURONTbl.M15_020_YABUKURON_FREE_START
end
function YABUKURONTbl.M16_010_YABUKURON_FREE_START()
  return YABUKURONTbl.M15_030_YABUKURON_FREE_START
end
function YABUKURONTbl.M16_040_YABUKURON_FREE_START()
  return YABUKURONTbl.M16_010_YABUKURON_FREE_START
end
function YABUKURONTbl.M16_080_YABUKURON_FREE_START()
  return YABUKURONTbl.M16_040_YABUKURON_FREE_START
end
function YABUKURONTbl.M16_090_YABUKURON_FREE_START()
  return YABUKURONTbl.M16_080_YABUKURON_FREE_START
end
function YABUKURONTbl.M16_100_YABUKURON_FREE_START()
  return YABUKURONTbl.M16_090_YABUKURON_FREE_START
end
function YABUKURONTbl.M16_105_YABUKURON_FREE_START()
  return YABUKURONTbl.M16_100_YABUKURON_FREE_START
end
function YABUKURONTbl.M16_120_YABUKURON_FREE_START()
  return YABUKURONTbl.M16_105_YABUKURON_FREE_START
end
function YABUKURONTbl.M17_020_YABUKURON_FREE_START()
  return YABUKURONTbl.M16_120_YABUKURON_FREE_START
end
function YABUKURONTbl.M17_040_YABUKURON_FREE_START()
  return YABUKURONTbl.M17_020_YABUKURON_FREE_START
end
function YABUKURONTbl.M17_060_YABUKURON_FREE_START()
  return YABUKURONTbl.M17_040_YABUKURON_FREE_START
end
function YABUKURONTbl.M17_065_YABUKURON_FREE_START()
  return YABUKURONTbl.M17_060_YABUKURON_FREE_START
end
function YABUKURONTbl.M17_090_YABUKURON_FREE_START()
  return YABUKURONTbl.M17_065_YABUKURON_FREE_START
end
function YABUKURONTbl.M17_120_YABUKURON_FREE_START()
  return YABUKURONTbl.M17_090_YABUKURON_FREE_START
end
function YABUKURONTbl.M17_140_YABUKURON_FREE_START()
  return YABUKURONTbl.M17_120_YABUKURON_FREE_START
end
function YABUKURONTbl.M17_150_YABUKURON_FREE_START()
  return YABUKURONTbl.M17_140_YABUKURON_FREE_START
end
function YABUKURONTbl.M17_155_YABUKURON_FREE_START()
  return YABUKURONTbl.M17_150_YABUKURON_FREE_START
end
function YABUKURONTbl.M17_170_YABUKURON_FREE_START()
  return YABUKURONTbl.M17_155_YABUKURON_FREE_START
end
function YABUKURONTbl.M17_200_YABUKURON_FREE_START()
  return YABUKURONTbl.M17_170_YABUKURON_FREE_START
end
function YABUKURONTbl.M17_210_YABUKURON_FREE_START()
  return YABUKURONTbl.M17_200_YABUKURON_FREE_START
end
function YABUKURONTbl.M17_220_YABUKURON_FREE_START()
  return YABUKURONTbl.M17_210_YABUKURON_FREE_START
end
function YABUKURONTbl.M17_225_YABUKURON_FREE_START()
  return YABUKURONTbl.M17_220_YABUKURON_FREE_START
end
function YABUKURONTbl.M17_240_YABUKURON_FREE_START()
  return YABUKURONTbl.M17_225_YABUKURON_FREE_START
end
function YABUKURONTbl.M18_020_YABUKURON_FREE_START()
  return YABUKURONTbl.M17_240_YABUKURON_FREE_START
end
function YABUKURONTbl.M18_030_YABUKURON_FREE_START()
  return YABUKURONTbl.M18_020_YABUKURON_FREE_START
end
function YABUKURONTbl.S01_010_YABUKURON_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("YABUKURON"))
  WINDOW:DrawFace(20, 88, SymAct("YABUKURON"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YABUKURON"), -2030476981)
  WINDOW:Talk(SymAct("YABUKURON"), -1612558326)
  WINDOW:Talk(SymAct("YABUKURON"), -1261501495)
  WINDOW:Talk(SymAct("YABUKURON"), -1378602360)
  WINDOW:Talk(SymAct("YABUKURON"), 709635655)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("YABUKURON"), result)
end
function YABUKURONTbl.S01_020_YABUKURON_FREE_START()
  return YABUKURONTbl.S01_010_YABUKURON_FREE_START
end
function YABUKURONTbl.S01_030_YABUKURON_FREE_START()
  return YABUKURONTbl.S01_020_YABUKURON_FREE_START
end
function YABUKURONTbl.S01_040_YABUKURON_FREE_START()
  return YABUKURONTbl.S01_030_YABUKURON_FREE_START
end
function YABUKURONTbl.S01_050_YABUKURON_FREE_START()
  return YABUKURONTbl.S01_040_YABUKURON_FREE_START
end
function YABUKURONTbl.S01_060_YABUKURON_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("YABUKURON"))
  WINDOW:DrawFace(20, 88, SymAct("YABUKURON"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YABUKURON"), 861347590)
  WINDOW:Talk(SymAct("YABUKURON"), -2139515449)
  WINDOW:KeyWait()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("YABUKURON"):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFace(20, 88, SymAct("YABUKURON"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("YABUKURON"), -1721588602)
  WINDOW:Talk(SymAct("YABUKURON"), -1303382203)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("YABUKURON"), result)
end
function YABUKURONTbl.S01_080_YABUKURON_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("YABUKURON"))
  if FLAG.YabukuronCounter == CONST.CNT_1 then
    WINDOW:DrawFace(20, 88, SymAct("YABUKURON"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("YABUKURON"), -1420507644)
    WINDOW:Talk(SymAct("YABUKURON"), -468365117)
    WINDOW:Talk(SymAct("YABUKURON"), -49389182)
    WINDOW:Talk(SymAct("YABUKURON"), -702336447)
    WINDOW:Talk(SymAct("YABUKURON"), -818412800)
    WINDOW:KeyWait()
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
    CH("YABUKURON"):SetManpu("MP_FLY_SWEAT")
    WINDOW:DrawFace(20, 88, SymAct("YABUKURON"), FACE_TYPE.TEARS)
    WINDOW:Talk(SymAct("YABUKURON"), 1218453455)
    WINDOW:Talk(SymAct("YABUKURON"), 1371221646)
    WINDOW:CloseMessage()
    subUsuComFuncTalkOutBase01(CH("YABUKURON"), result)
    FLAG.YabukuronCounter = CONST.CNT_2
  else
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
    CH("YABUKURON"):SetManpu("MP_FLY_SWEAT")
    WINDOW:DrawFace(20, 88, SymAct("YABUKURON"), FACE_TYPE.TEARS)
    WINDOW:Talk(SymAct("YABUKURON"), -1832109527)
    WINDOW:Talk(SymAct("YABUKURON"), -1948841112)
    WINDOW:CloseMessage()
    subUsuComFuncTalkOutBase01(CH("YABUKURON"), result)
  end
end
function YABUKURONTbl.ALL_CLEAR_YABUKURON_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("YABUKURON"))
  WINDOW:DrawFace(20, 88, SymAct("YABUKURON"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YABUKURON"), -1594206037)
  WINDOW:Talk(SymAct("YABUKURON"), -1176409622)
  WINDOW:Talk(SymAct("YABUKURON"), -157221075)
  WINDOW:Talk(SymAct("YABUKURON"), -272904596)
  WINDOW:Talk(SymAct("YABUKURON"), -996762193)
  WINDOW:Talk(SymAct("YABUKURON"), -577917714)
  WINDOW:KeyWait()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("YABUKURON"):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFace(20, 88, SymAct("YABUKURON"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("YABUKURON"), 1511370785)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("YABUKURON"), result)
end

