function YANAPPUTbl.M02_010_YANAPPU_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("YANAPPU"))
  WINDOW:SysMsg(430935639)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("YANAPPU"), result)
end
function YANAPPUTbl.M02_030_YANAPPU_FREE_START()
  return YANAPPUTbl.M02_010_YANAPPU_FREE_START
end
function YANAPPUTbl.M02_050_YANAPPU_FREE_START()
  return YANAPPUTbl.M02_030_YANAPPU_FREE_START
end
function YANAPPUTbl.M02_070_YANAPPU_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("YANAPPU"))
  WINDOW:DrawFace(20, 88, SymAct("YANAPPU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YANAPPU"), 11845398)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("YANAPPU"), result)
end
function YANAPPUTbl.M02_080_YANAPPU_FREE_START()
  return YANAPPUTbl.M02_070_YANAPPU_FREE_START
end
function YANAPPUTbl.M02_090_YANAPPU_FREE_START()
  return YANAPPUTbl.M02_080_YANAPPU_FREE_START
end
function YANAPPUTbl.M02_100_YANAPPU_FREE_START()
  return YANAPPUTbl.M02_090_YANAPPU_FREE_START
end
function YANAPPUTbl.M02_115_YANAPPU_FREE_START()
  return YANAPPUTbl.M02_100_YANAPPU_FREE_START
end
function YANAPPUTbl.M02_130_YANAPPU_FREE_START()
  return YANAPPUTbl.M02_115_YANAPPU_FREE_START
end
function YANAPPUTbl.M02_160_YANAPPU_FREE_START()
  return YANAPPUTbl.M02_130_YANAPPU_FREE_START
end
function YANAPPUTbl.M03_010_YANAPPU_FREE_START()
  return YANAPPUTbl.M02_160_YANAPPU_FREE_START
end
function YANAPPUTbl.M03_020_YANAPPU_FREE_START()
  return YANAPPUTbl.M03_010_YANAPPU_FREE_START
end
function YANAPPUTbl.M03_045_YANAPPU_FREE_START()
  return YANAPPUTbl.M03_020_YANAPPU_FREE_START
end
function YANAPPUTbl.M03_090_YANAPPU_FREE_START()
  return YANAPPUTbl.M03_045_YANAPPU_FREE_START
end
function YANAPPUTbl.M03_110_YANAPPU_FREE_START()
  return YANAPPUTbl.M03_090_YANAPPU_FREE_START
end
function YANAPPUTbl.M03_130_YANAPPU_FREE_START()
  return YANAPPUTbl.M03_110_YANAPPU_FREE_START
end
function YANAPPUTbl.M03_150_YANAPPU_FREE_START()
  return YANAPPUTbl.M03_130_YANAPPU_FREE_START
end
function YANAPPUTbl.M04_010_YANAPPU_FREE_START()
  return YANAPPUTbl.M03_150_YANAPPU_FREE_START
end
function YANAPPUTbl.M04_020_YANAPPU_FREE_START()
  return YANAPPUTbl.M04_010_YANAPPU_FREE_START
end
function YANAPPUTbl.M04_HANYOU_YANAPPU_FREE_START()
  return YANAPPUTbl.M04_020_YANAPPU_FREE_START
end
function YANAPPUTbl.M04_040_YANAPPU_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("YANAPPU"))
  WINDOW:DrawFace(20, 88, SymAct("YANAPPU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YANAPPU"), 731507925)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("YANAPPU"), result)
end
function YANAPPUTbl.M04_060_YANAPPU_FREE_START()
  return YANAPPUTbl.M04_040_YANAPPU_FREE_START
end
function YANAPPUTbl.M04_070_YANAPPU_FREE_START()
  return YANAPPUTbl.M04_060_YANAPPU_FREE_START
end
function YANAPPUTbl.M04_HANYOU_YANAPPU_FREE_START2()
  return YANAPPUTbl.M04_070_YANAPPU_FREE_START
end
function YANAPPUTbl.M05_000_YANAPPU_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("YANAPPU"))
  WINDOW:DrawFace(20, 88, SymAct("YANAPPU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YANAPPU"), 847437204)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("YANAPPU"), result)
end
function YANAPPUTbl.M05_010_YANAPPU_FREE_START()
  return YANAPPUTbl.M05_000_YANAPPU_FREE_START
end
function YANAPPUTbl.M05_020_YANAPPU_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("YANAPPU"))
  WINDOW:DrawFace(20, 88, SymAct("YANAPPU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YANAPPU"), 2109950803)
  WINDOW:Talk(SymAct("YANAPPU"), 1691908626)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("YANAPPU"), result)
end
function YANAPPUTbl.M05_030_YANAPPU_FREE_START()
  return YANAPPUTbl.M05_020_YANAPPU_FREE_START
end
function YANAPPUTbl.M06_HANYOU_YANAPPU_FREE_START()
  return YANAPPUTbl.M05_030_YANAPPU_FREE_START
end
function YANAPPUTbl.M06_010_YANAPPU_FREE_START()
  return YANAPPUTbl.M06_HANYOU_YANAPPU_FREE_START
end
function YANAPPUTbl.M06_015_YANAPPU_FREE_START()
  return YANAPPUTbl.M06_010_YANAPPU_FREE_START
end
function YANAPPUTbl.M06_020_YANAPPU_FREE_START()
  return YANAPPUTbl.M06_015_YANAPPU_FREE_START
end
function YANAPPUTbl.M06_030_YANAPPU_FREE_START()
  return YANAPPUTbl.M06_020_YANAPPU_FREE_START
end
function YANAPPUTbl.M06_040_YANAPPU_FREE_START()
  return YANAPPUTbl.M06_030_YANAPPU_FREE_START
end
function YANAPPUTbl.M06_060_YANAPPU_FREE_START()
  return YANAPPUTbl.M06_040_YANAPPU_FREE_START
end
function YANAPPUTbl.M07_000_YANAPPU_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("YANAPPU"))
  WINDOW:DrawFace(20, 88, SymAct("YANAPPU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YANAPPU"), 1341467089)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("YANAPPU"), result)
end
function YANAPPUTbl.M07_010_YANAPPU_FREE_START()
  return YANAPPUTbl.M07_000_YANAPPU_FREE_START
end
function YANAPPUTbl.M07_020_YANAPPU_FREE_START()
  return YANAPPUTbl.M07_010_YANAPPU_FREE_START
end
function YANAPPUTbl.M07_045_YANAPPU_FREE_START()
  return YANAPPUTbl.M07_020_YANAPPU_FREE_START
end
function YANAPPUTbl.M07_HANYOU_YANAPPU_FREE_START()
  return YANAPPUTbl.M07_045_YANAPPU_FREE_START
end
function YANAPPUTbl.M07_080_YANAPPU_FREE_START()
  return YANAPPUTbl.M07_HANYOU_YANAPPU_FREE_START
end
function YANAPPUTbl.M08_010_YANAPPU_FREE_START()
  return YANAPPUTbl.M07_080_YANAPPU_FREE_START
end
function YANAPPUTbl.M08_HANYOU_YANAPPU_FREE_START()
  return YANAPPUTbl.M08_010_YANAPPU_FREE_START
end
function YANAPPUTbl.M08_020_YANAPPU_FREE_START()
  return YANAPPUTbl.M08_HANYOU_YANAPPU_FREE_START
end
function YANAPPUTbl.M08_040_YANAPPU_FREE_START()
  return YANAPPUTbl.M08_020_YANAPPU_FREE_START
end
function YANAPPUTbl.M08_050_YANAPPU_FREE_START()
  return YANAPPUTbl.M08_040_YANAPPU_FREE_START
end
function YANAPPUTbl.M08_055_YANAPPU_FREE_START()
  return YANAPPUTbl.M08_050_YANAPPU_FREE_START
end
function YANAPPUTbl.M08_070_YANAPPU_FREE_START()
  return YANAPPUTbl.M08_055_YANAPPU_FREE_START
end
function YANAPPUTbl.M09_HANYOU_YANAPPU_FREE_START1()
  return YANAPPUTbl.M08_070_YANAPPU_FREE_START
end
function YANAPPUTbl.M09_010_YANAPPU_FREE_START()
  return YANAPPUTbl.M09_HANYOU_YANAPPU_FREE_START1
end
function YANAPPUTbl.M09_020_YANAPPU_FREE_START()
  return YANAPPUTbl.M09_010_YANAPPU_FREE_START
end
function YANAPPUTbl.M09_040_YANAPPU_FREE_START()
  return YANAPPUTbl.M09_020_YANAPPU_FREE_START
end
function YANAPPUTbl.M09_HANYOU_YANAPPU_FREE_START2()
  return YANAPPUTbl.M09_040_YANAPPU_FREE_START
end
function YANAPPUTbl.M09_060_YANAPPU_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("YANAPPU"))
  WINDOW:DrawFace(20, 88, SymAct("YANAPPU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YANAPPU"), 1458444432)
  WINDOW:Talk(SymAct("YANAPPU"), -780794785)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("YANAPPU"), result)
end
function YANAPPUTbl.M09_080_YANAPPU_FREE_START()
  return YANAPPUTbl.M09_060_YANAPPU_FREE_START
end
function YANAPPUTbl.M09_100_YANAPPU_FREE_START()
  return YANAPPUTbl.M09_080_YANAPPU_FREE_START
end
function YANAPPUTbl.M09_110_YANAPPU_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("YANAPPU"))
  WINDOW:DrawFace(20, 88, SymAct("YANAPPU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YANAPPU"), -932367074)
  WINDOW:Talk(SymAct("YANAPPU"), -640073870)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("YANAPPU"), result)
end
function YANAPPUTbl.M09_120_YANAPPU_FREE_START()
  return YANAPPUTbl.M09_110_YANAPPU_FREE_START
end
function YANAPPUTbl.M10_010_YANAPPU_FREE_START()
  return YANAPPUTbl.M09_120_YANAPPU_FREE_START
end
function YANAPPUTbl.M10_030_YANAPPU_FREE_START()
  return YANAPPUTbl.M10_010_YANAPPU_FREE_START
end
function YANAPPUTbl.M10_040_YANAPPU_FREE_START()
  return YANAPPUTbl.M10_030_YANAPPU_FREE_START
end
function YANAPPUTbl.M10_060_YANAPPU_FREE_START()
  return YANAPPUTbl.M10_040_YANAPPU_FREE_START
end
function YANAPPUTbl.M11_010_YANAPPU_FREE_START()
  return YANAPPUTbl.M10_060_YANAPPU_FREE_START
end
function YANAPPUTbl.M11_030_YANAPPU_FREE_START()
  return YANAPPUTbl.M11_010_YANAPPU_FREE_START
end
function YANAPPUTbl.M11_040_YANAPPU_FREE_START()
  return YANAPPUTbl.M11_030_YANAPPU_FREE_START
end
function YANAPPUTbl.M11_050_YANAPPU_FREE_START()
  return YANAPPUTbl.M11_040_YANAPPU_FREE_START
end
function YANAPPUTbl.M11_060_YANAPPU_FREE_START()
  return YANAPPUTbl.M11_050_YANAPPU_FREE_START
end
function YANAPPUTbl.M11_090_YANAPPU_FREE_START()
  return YANAPPUTbl.M11_060_YANAPPU_FREE_START
end

