function YOOTERIITbl.M02_010_YOOTERII_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("YOOTERII"))
  WINDOW:DrawFace(20, 88, SymAct("YOOTERII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YOOTERII"), -574138522)
  WINDOW:Talk(SymAct("YOOTERII"), -992188889)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("YOOTERII"), result)
end
function YOOTERIITbl.M02_030_YOOTERII_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("YOOTERII"))
  WINDOW:DrawFace(20, 88, SymAct("YOOTERII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YOOTERII"), -269404700)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("YOOTERII"), result)
end
function YOOTERIITbl.M02_050_YOOTERII_FREE_START()
  return YOOTERIITbl.M02_030_YOOTERII_FREE_START
end
function YOOTERIITbl.M02_070_YOOTERII_FREE_START()
  return YOOTERIITbl.M02_050_YOOTERII_FREE_START
end
function YOOTERIITbl.M02_080_YOOTERII_FREE_START()
  return YOOTERIITbl.M02_070_YOOTERII_FREE_START
end
function YOOTERIITbl.M02_090_YOOTERII_FREE_START()
  return YOOTERIITbl.M02_080_YOOTERII_FREE_START
end
function YOOTERIITbl.M02_100_YOOTERII_FREE_START()
  return YOOTERIITbl.M02_090_YOOTERII_FREE_START
end
function YOOTERIITbl.M02_115_YOOTERII_FREE_START()
  return YOOTERIITbl.M02_100_YOOTERII_FREE_START
end
function YOOTERIITbl.M02_130_YOOTERII_FREE_START()
  return YOOTERIITbl.M02_115_YOOTERII_FREE_START
end
function YOOTERIITbl.M02_160_YOOTERII_FREE_START()
  return YOOTERIITbl.M02_130_YOOTERII_FREE_START
end
function YOOTERIITbl.M03_010_YOOTERII_FREE_START()
  return YOOTERIITbl.M02_160_YOOTERII_FREE_START
end
function YOOTERIITbl.M03_020_YOOTERII_FREE_START()
  dofile("script/usual/citizen/citizen/kurumayu_1.lua")
  KURUMAYUTbl.M03_020_KURUMAYU_FREE_START()
end
function YOOTERIITbl.M03_045_YOOTERII_FREE_START()
  return YOOTERIITbl.M03_020_YOOTERII_FREE_START
end
function YOOTERIITbl.M03_090_YOOTERII_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("YOOTERII"))
  WINDOW:DrawFace(20, 88, SymAct("YOOTERII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YOOTERII"), -152435547)
  WINDOW:Talk(SymAct("YOOTERII"), -1179938206)
  WINDOW:Talk(SymAct("YOOTERII"), -1599036637)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("YOOTERII"), result)
end
function YOOTERIITbl.M03_110_YOOTERII_FREE_START()
  dofile("script/usual/citizen/citizen/kurumayu_1.lua")
  KURUMAYUTbl.M03_110_KURUMAYU_FREE_START()
end
function YOOTERIITbl.M03_130_YOOTERII_FREE_START()
  return YOOTERIITbl.M03_110_YOOTERII_FREE_START
end
function YOOTERIITbl.M03_150_YOOTERII_FREE_START()
  return YOOTERIITbl.M03_130_YOOTERII_FREE_START
end
function YOOTERIITbl.M04_010_YOOTERII_FREE_START()
  return YOOTERIITbl.M03_150_YOOTERII_FREE_START
end
function YOOTERIITbl.M04_020_YOOTERII_FREE_START()
  return YOOTERIITbl.M04_010_YOOTERII_FREE_START
end
function YOOTERIITbl.M04_HANYOU_YOOTERII_FREE_START()
  return YOOTERIITbl.M04_020_YOOTERII_FREE_START
end
function YOOTERIITbl.M04_040_YOOTERII_FREE_START()
  return YOOTERIITbl.M04_HANYOU_YOOTERII_FREE_START
end
function YOOTERIITbl.M04_060_YOOTERII_FREE_START()
  return YOOTERIITbl.M04_040_YOOTERII_FREE_START
end
function YOOTERIITbl.M04_070_YOOTERII_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("YOOTERII"))
  WINDOW:DrawFace(20, 88, SymAct("YOOTERII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YOOTERII"), -1952583456)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("YOOTERII"), result)
end
function YOOTERIITbl.M04_HANYOU_YOOTERII_FREE_START2()
  return YOOTERIITbl.M04_070_YOOTERII_FREE_START
end
function YOOTERIITbl.M05_000_YOOTERII_FREE_START()
  return YOOTERIITbl.M04_HANYOU_YOOTERII_FREE_START2
end
function YOOTERIITbl.M05_010_YOOTERII_FREE_START()
  return YOOTERIITbl.M05_000_YOOTERII_FREE_START
end
function YOOTERIITbl.M05_020_YOOTERII_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("YOOTERII"))
  WINDOW:DrawFace(20, 88, SymAct("YOOTERII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YOOTERII"), -1836662367)
  WINDOW:Talk(SymAct("YOOTERII"), 354344302)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("YOOTERII"), result)
end
function YOOTERIITbl.M05_030_YOOTERII_FREE_START()
  dofile("script/usual/citizen/citizen/kurumayu_1.lua")
  KURUMAYUTbl.M05_030_KURUMAYU_FREE_START()
end
function YOOTERIITbl.M06_HANYOU_YOOTERII_FREE_START()
  return YOOTERIITbl.M05_030_YOOTERII_FREE_START
end
function YOOTERIITbl.M06_010_YOOTERII_FREE_START()
  local result = subUsuComFuncTalkInBase02(CH("YOOTERII"))
  WINDOW:DrawFace(20, 88, SymAct("YOOTERII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YOOTERII"), 201714735)
  WINDOW:Talk(SymAct("YOOTERII"), -527722792)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase02(CH("YOOTERII"), result)
end
function YOOTERIITbl.M06_015_YOOTERII_FREE_START()
  return YOOTERIITbl.M06_010_YOOTERII_FREE_START
end
function YOOTERIITbl.M06_020_YOOTERII_FREE_START()
  return YOOTERIITbl.M06_015_YOOTERII_FREE_START
end
function YOOTERIITbl.M06_030_YOOTERII_FREE_START()
  return YOOTERIITbl.M06_020_YOOTERII_FREE_START
end
function YOOTERIITbl.M06_040_YOOTERII_FREE_START()
  return YOOTERIITbl.M06_030_YOOTERII_FREE_START
end
function YOOTERIITbl.M06_060_YOOTERII_FREE_START()
  return YOOTERIITbl.M06_040_YOOTERII_FREE_START
end
function YOOTERIITbl.M07_000_YOOTERII_FREE_START()
  return YOOTERIITbl.M06_060_YOOTERII_FREE_START
end
function YOOTERIITbl.M07_010_YOOTERII_FREE_START()
  return YOOTERIITbl.M07_000_YOOTERII_FREE_START
end
function YOOTERIITbl.M07_020_YOOTERII_FREE_START()
  return YOOTERIITbl.M07_010_YOOTERII_FREE_START
end
function YOOTERIITbl.M07_045_YOOTERII_FREE_START()
  return YOOTERIITbl.M07_020_YOOTERII_FREE_START
end
function YOOTERIITbl.M07_HANYOU_YOOTERII_FREE_START()
  return YOOTERIITbl.M07_045_YOOTERII_FREE_START
end
function YOOTERIITbl.M07_080_YOOTERII_FREE_START()
  return YOOTERIITbl.M07_HANYOU_YOOTERII_FREE_START
end
function YOOTERIITbl.M08_010_YOOTERII_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("YOOTERII"))
  subEveDoubleJump(CH("YOOTERII"))
  WINDOW:DrawFace(20, 88, SymAct("YOOTERII"), FACE_TYPE.EMOTION)
  WINDOW:Talk(SymAct("YOOTERII"), -107960423)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("YOOTERII"), result)
end
function YOOTERIITbl.M08_HANYOU_YOOTERII_FREE_START()
  return YOOTERIITbl.M08_010_YOOTERII_FREE_START
end
function YOOTERIITbl.M08_020_YOOTERII_FREE_START()
  return YOOTERIITbl.M08_HANYOU_YOOTERII_FREE_START
end
function YOOTERIITbl.M08_040_YOOTERII_FREE_START()
  return YOOTERIITbl.M08_020_YOOTERII_FREE_START
end
function YOOTERIITbl.M08_050_YOOTERII_FREE_START()
  return YOOTERIITbl.M08_040_YOOTERII_FREE_START
end
function YOOTERIITbl.M08_055_YOOTERII_FREE_START()
  return YOOTERIITbl.M08_050_YOOTERII_FREE_START
end
function YOOTERIITbl.M08_070_YOOTERII_FREE_START()
  return YOOTERIITbl.M08_055_YOOTERII_FREE_START
end
function YOOTERIITbl.M09_HANYOU_YOOTERII_FREE_START1()
  return YOOTERIITbl.M08_070_YOOTERII_FREE_START
end
function YOOTERIITbl.M09_010_YOOTERII_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("YOOTERII"))
  WINDOW:DrawFace(20, 88, SymAct("YOOTERII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("YOOTERII"), -759303078)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("YOOTERII"), result)
end
function YOOTERIITbl.M09_020_YOOTERII_FREE_START()
  return YOOTERIITbl.M09_010_YOOTERII_FREE_START
end
function YOOTERIITbl.M09_040_YOOTERII_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("YOOTERII"))
  WINDOW:DrawFace(20, 88, SymAct("YOOTERII"), FACE_TYPE.EMOTION)
  WINDOW:Talk(SymAct("YOOTERII"), -878263013)
  WINDOW:Talk(SymAct("YOOTERII"), -2065214500)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("YOOTERII"), result)
end
function YOOTERIITbl.M09_HANYOU_YOOTERII_FREE_START2()
  return YOOTERIITbl.M09_040_YOOTERII_FREE_START
end
function YOOTERIITbl.M09_060_YOOTERII_FREE_START()
  return YOOTERIITbl.M09_HANYOU_YOOTERII_FREE_START2
end
function YOOTERIITbl.M09_080_YOOTERII_FREE_START()
  return YOOTERIITbl.M09_060_YOOTERII_FREE_START
end
function YOOTERIITbl.M09_100_YOOTERII_FREE_START()
  return YOOTERIITbl.M09_080_YOOTERII_FREE_START
end
function YOOTERIITbl.M09_110_YOOTERII_FREE_START()
  return YOOTERIITbl.M09_100_YOOTERII_FREE_START
end
function YOOTERIITbl.M09_120_YOOTERII_FREE_START()
  return YOOTERIITbl.M09_110_YOOTERII_FREE_START
end
function YOOTERIITbl.M10_010_YOOTERII_FREE_START()
  return YOOTERIITbl.M09_120_YOOTERII_FREE_START
end
function YOOTERIITbl.M10_030_YOOTERII_FREE_START()
  return YOOTERIITbl.M10_010_YOOTERII_FREE_START
end
function YOOTERIITbl.M10_040_YOOTERII_FREE_START()
  return YOOTERIITbl.M10_030_YOOTERII_FREE_START
end
function YOOTERIITbl.M10_060_YOOTERII_FREE_START()
  return YOOTERIITbl.M10_040_YOOTERII_FREE_START
end
function YOOTERIITbl.M11_010_YOOTERII_FREE_START()
  return YOOTERIITbl.M10_060_YOOTERII_FREE_START
end
function YOOTERIITbl.M11_030_YOOTERII_FREE_START()
  return YOOTERIITbl.M11_010_YOOTERII_FREE_START
end
function YOOTERIITbl.M11_040_YOOTERII_FREE_START()
  return YOOTERIITbl.M11_030_YOOTERII_FREE_START
end
function YOOTERIITbl.M11_050_YOOTERII_FREE_START()
  return YOOTERIITbl.M11_040_YOOTERII_FREE_START
end
function YOOTERIITbl.M11_060_YOOTERII_FREE_START()
  return YOOTERIITbl.M11_050_YOOTERII_FREE_START
end
function YOOTERIITbl.M11_090_YOOTERII_FREE_START()
  return YOOTERIITbl.M11_060_YOOTERII_FREE_START
end

