function ZURUGGUTbl.M02_010_ZURUGGU_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("ZURUGGU"))
  WINDOW:SysMsg(1764939047)
  WINDOW:CloseMessage()
  subUsuComFuncTalkOutBase01(CH("ZURUGGU"), result)
end
function ZURUGGUTbl.M02_030_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M02_010_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M02_050_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M02_030_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M02_070_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M02_050_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M02_080_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M02_070_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M02_090_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M02_080_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M02_100_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M02_090_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M02_115_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M02_100_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M02_130_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M02_115_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M02_160_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M02_130_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M03_010_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M02_160_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M03_020_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M03_010_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M03_045_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M03_020_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M03_090_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M03_045_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M03_110_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M03_090_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M03_130_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M03_110_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M03_150_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M03_130_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M04_010_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M03_150_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M04_020_ZURUGGU_FREE_START()
  if FLAG.ZurugguCounter == CONST.CNT_1 then
    subFreePlayReachCommonIgnoreCollision()
    SCREEN_A:FadeOut(TimeSec(0.5), false)
    SCREEN_B:FadeOutAll(TimeSec(0.5), true)
    SCREEN_B:FadeOut(TimeSec(0), true)
    subEveFadeAfterTime()
    dofile("script/event/main/main04/030_zuruggunohanashi/zuruggunohanashi.lua")
    main04_zuruggunohanashi01_start()
    FLAG.ZurugguCounter = CONST.CNT_2
    SCREEN_B:FadeIn(TimeSec(0), false)
    SCREEN_A:FadeIn(TimeSec(0.5), false)
    SCREEN_B:FadeInAll(TimeSec(0.5), true)
  else
    local result = subUsuComFuncTalkInBase01(CH("ZURUGGU"))
    OpenWAZAShopMenu()
    subUsuComFuncTalkOutBase01(CH("ZURUGGU"), result)
  end
end
function ZURUGGUTbl.M04_HANYOU_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M04_020_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M04_040_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M04_HANYOU_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M04_060_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M04_040_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M04_070_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M04_060_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M04_HANYOU_ZURUGGU_FREE_START2()
  return ZURUGGUTbl.M04_070_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M05_000_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M04_HANYOU_ZURUGGU_FREE_START2
end
function ZURUGGUTbl.M05_010_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M05_000_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M05_020_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M05_010_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M05_030_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M05_020_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M06_HANYOU_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M05_030_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M06_010_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M06_HANYOU_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M06_015_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M06_010_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M06_020_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M06_015_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M06_030_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M06_020_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M06_040_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M06_030_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M06_060_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M06_040_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M07_000_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M06_060_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M07_010_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M07_000_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M07_020_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M07_010_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M07_045_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M07_020_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M07_HANYOU_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M07_045_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M07_080_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M07_HANYOU_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M08_010_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M07_080_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M08_HANYOU_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M08_010_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M08_020_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M08_HANYOU_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M08_040_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M08_020_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M08_050_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M08_040_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M08_055_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M08_050_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M08_070_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M08_055_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M09_HANYOU_ZURUGGU_FREE_START1()
  return ZURUGGUTbl.M08_070_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M09_010_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M09_HANYOU_ZURUGGU_FREE_START1
end
function ZURUGGUTbl.M09_020_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M09_010_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M09_040_ZURUGGU_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("ZURUGGU"))
  if FLAG.ZurugguCounter == CONST.CNT_1 then
    WINDOW:DrawFace(20, 88, SymAct("ZURUGGU"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("ZURUGGU"), 1881793638)
    WINDOW:Talk(SymAct("ZURUGGU"), 1527035813)
    WINDOW:CloseMessage()
    FLAG.ZurugguCounter = CONST.CNT_2
  end
  OpenWAZAShopMenu()
  subUsuComFuncTalkOutBase01(CH("ZURUGGU"), result)
end
function ZURUGGUTbl.M09_HANYOU_ZURUGGU_FREE_START2()
  return ZURUGGUTbl.M09_040_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M09_060_ZURUGGU_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("ZURUGGU"))
  if FLAG.ZurugguCounter == CONST.CNT_1 then
    WINDOW:DrawFace(20, 88, SymAct("ZURUGGU"), FACE_TYPE.THINK)
    WINDOW:Talk(SymAct("ZURUGGU"), 1109362404)
    WINDOW:Talk(SymAct("ZURUGGU"), 224268323)
    WINDOW:CloseMessage()
    FLAG.ZurugguCounter = CONST.CNT_2
  end
  OpenWAZAShopMenu()
  subUsuComFuncTalkOutBase01(CH("ZURUGGU"), result)
end
function ZURUGGUTbl.M09_080_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M09_060_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M09_100_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M09_080_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M09_110_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M09_100_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M09_120_ZURUGGU_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("ZURUGGU"))
  if FLAG.ZurugguCounter == CONST.CNT_1 then
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
    CH("ZURUGGU"):SetManpu("MP_EXCLAMATION")
    CH("ZURUGGU"):WaitManpu()
    WINDOW:DrawFace(20, 88, SymAct("ZURUGGU"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("ZURUGGU"), 340074850)
    WINDOW:Talk(SymAct("ZURUGGU"), 1063809697)
    WINDOW:CloseMessage()
    FLAG.ZurugguCounter = CONST.CNT_2
  end
  OpenWAZAShopMenu()
  subUsuComFuncTalkOutBase01(CH("ZURUGGU"), result)
end
function ZURUGGUTbl.M10_010_ZURUGGU_FREE_START()
  local result = subUsuComFuncTalkInBase01(CH("ZURUGGU"))
  OpenWAZAShopMenu()
  subUsuComFuncTalkOutBase01(CH("ZURUGGU"), result)
end
function ZURUGGUTbl.M10_030_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M10_010_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M10_040_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M10_030_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M10_060_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M10_040_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M11_010_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M10_060_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M11_030_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M11_010_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M11_040_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M11_030_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M11_050_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M11_040_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M11_060_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M11_050_ZURUGGU_FREE_START
end
function ZURUGGUTbl.M11_090_ZURUGGU_FREE_START()
  return ZURUGGUTbl.M11_060_ZURUGGU_FREE_START
end

