dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main11_furizumu01_init()
end
function main11_furizumu01_start()
  subEveFromProgFadeSet()
  TASK:Sleep(TimeSec(1))
  CHARA:SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  GM("FURIZUMU_AFTER_02"):SetVisible(false)
  GM("FURIZUMU_AFTER"):SetMotion(SymMot("A"), LOOP.OFF)
  GM("FURIZUMU_BEFORE"):SetMotion(SymMot("B"), LOOP.OFF)
  GM("FURIZUMU_BEFORE_02"):SetMotion(SymMot("A"), LOOP.OFF)
  GM("FURIZUMU_BEFORE_03"):SetMotion(SymMot("A"), LOOP.OFF)
  GM("FURIZUMU_BEFORE_04"):SetMotion(SymMot("B"), LOOP.OFF)
  GM("FURIZUMU_AFTER_02"):SetMotion(SymMot("B"), LOOP.OFF)
  GM("FURIZUMU_BEFORE_05"):SetMotion(SymMot("A"), LOOP.OFF)
  GM("FURIZUMU_BEFORE_06"):SetMotion(SymMot("C"), LOOP.OFF)
  GM("FURIZUMU_BEFORE_07"):SetMotion(SymMot("A"), LOOP.OFF)
  GM("FURIZUMU_BEFORE_08"):SetMotion(SymMot("C"), LOOP.OFF)
  GM("FURIZUMU_BEFORE_09"):SetMotion(SymMot("C"), LOOP.OFF)
  GM("FURIZUMU_BEFORE_10"):SetMotion(SymMot("A"), LOOP.OFF)
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("BURAKKII"):WalkTo(SplinePath(SymPos("P00_5_BURAKKII"), SymPos("P01_BURAKKII")), Speed(1.7))
  CH("EEFI"):WalkTo(SplinePath(SymPos("P00_5_EEFI"), SymPos("P01_EEFI")), Speed(1.7))
  CH("HERO"):WalkTo(SplinePath(SymPos("P00_5_HERO"), SymPos("P01_HERO")), Speed(1.7))
  CH("PARTNER"):WalkTo(SplinePath(SymPos("P00_5_PARTNER"), SymPos("P01_PARTNER")), Speed(1.7))
  CH("BIRIJION"):WalkTo(SplinePath(SymPos("P00_5_BIRIJION"), SymPos("P01_BIRIJION")), Speed(1.7))
  CH("NOKOTCHI"):SetMotionRaito(Raito(1.5))
  CH("NOKOTCHI"):SetMotion(SymMot("RUN"), LOOP.ON)
  CH("NOKOTCHI"):MoveTo(SplinePath(SymPos("P00_5_NOKOTCHI"), SymPos("P01_NOKOTCHI")), Speed(1.5))
  CH("NOKOTCHI"):WaitMove()
  CH("NOKOTCHI"):SetMotion(SymMot("WAIT00"), LOOP.ON)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("NOKOTCHI"):SetManpu("MP_FLY_SWEAT_LP")
  WINDOW:DrawFace(324, 88, SymAct("NOKOTCHI"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("NOKOTCHI"), 1794887509)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3.5))
  CAMERA:SetEye(SymCam("CAMERA_00_5"))
  CAMERA:SetTgt(SymCam("CAMERA_00_5"))
  CH("BIRIJION"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.4))
  CH("PARTNER"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  CH("EEFI"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  CH("BIRIJION"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.SPECIAL05)
  WINDOW:Talk(SymAct("BIRIJION"), 1944124948)
  WINDOW:CloseMessage()
  CH("NOKOTCHI"):SetMotionRaito(Raito(1))
  CH("NOKOTCHI"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("NOKOTCHI"):ResetManpu()
  CH("NOKOTCHI"):DirTo(CH("BIRIJION"), Speed(200), ROT_TYPE.NEAR)
  CH("NOKOTCHI"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("NOKOTCHI"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("NOKOTCHI"), 1489874391)
  WINDOW:Talk(SymAct("NOKOTCHI"), 1104583830)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_NOTICE_R")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(324, 20, SymAct("PARTNER"), FACE_TYPE.THINK)
  WINDOW:SwitchTalk({PARTNER_0 = 244779601, PARTNER_1 = 395066128})
  WINDOW:SwitchTalk({PARTNER_0 = 1017211091, PARTNER_1 = 632969618})
  subEveCloseMsg()
  WINDOW:DrawFace(20, 20, SymAct("EEFI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EEFI"), -1574812323)
  WINDOW:Talk(SymAct("EEFI"), -1153862628)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("BURAKKII"):DirTo(CH("NOKOTCHI"), Speed(500), ROT_TYPE.NEAR)
  CH("BURAKKII"):WaitRotate()
  CH("EEFI"):DirTo(CH("BURAKKII"), Speed(200), ROT_TYPE.NEAR)
  CH("HERO"):DirTo(CH("BURAKKII"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):DirTo(CH("BURAKKII"), Speed(350), ROT_TYPE.NEAR)
  CH("BIRIJION"):DirTo(CH("BURAKKII"), Speed(350), ROT_TYPE.NEAR)
  CH("NOKOTCHI"):DirTo(CH("BURAKKII"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(20, 20, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BURAKKII"), -365666398)
  WINDOW:CloseMessage()
  TASK:Regist(subEveMoveDir2, {
    CH("BURAKKII"),
    SymPos("P02_BURAKKII"),
    Speed(2),
    RotateTarget(180)
  })
  TASK:Sleep(TimeSec(0.8))
  CAMERA:MoveFollow(SymCam("CAMERA_01"), Speed(2.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Regist(subEveMoveDir, {
    CH("EEFI"),
    SymPos("P02_EEFI"),
    Speed(2),
    RotateTarget(180)
  })
  CH("HERO"):WalkTo(SymPos("P02_HERO"), Speed(2))
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):WalkTo(SymPos("P02_PARTNER"), Speed(2))
  CH("BIRIJION"):WalkTo(SymPos("P02_BIRIJION"), Speed(2))
  TASK:Sleep(TimeSec(0.1))
  TASK:Regist(subEveMoveDir, {
    CH("NOKOTCHI"),
    SymPos("P02_NOKOTCHI"),
    Speed(2),
    RotateTarget(180)
  })
  TASK:WaitTask()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_01"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  TASK:Regist(subEveJump, {
    CH("NOKOTCHI")
  })
  CH("NOKOTCHI"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  TASK:Sleep(TimeSec(0.1))
  CH("BIRIJION"):SetManpu("MP_EXCLAMATION")
  TASK:Regist(subEveJump, {
    CH("PARTNER")
  })
  TASK:Sleep(TimeSec(0.1))
  CH("EEFI"):SetManpu("MP_SHOCK_R")
  CH("EEFI"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("EEFI"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("EEFI"), -214995229)
  subEveCloseMsg()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetAzimuthDifferenceVolume(Volume(2.5))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:MoveFollow(SymCam("CAMERA_02_5"), Speed(0.2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_DAIHYOUGA_02"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  subEveFadeAfterTime()
  WINDOW:DrawFace(324, 88, SymAct("NOKOTCHI"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("NOKOTCHI"), -670941920)
  WINDOW:Talk(SymAct("NOKOTCHI"), -1055323039)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BURAKKII"), -1906795866)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("EEFI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EEFI"), -1757172761)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BURAKKII"), -1133578204)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SPECIAL02)
  WINDOW:Monologue(-1519007387)
  WINDOW:Monologue(586012074)
  WINDOW:Monologue(1006036203)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_KIRAN"), Volume(128))
  SOUND:WaitSe(SymSnd("SE_EVT_KIRAN"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_NOTICE_L")
  CH("PARTNER"):WaitManpu()
  TASK:Sleep(TimeSec(0.3))
  CH("PARTNER"):DirTo(RotateTarget(135), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3.5))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_QUESTION")
  CH("PARTNER"):WaitManpu()
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -125702068, PARTNER_1 = -509951731})
  WINDOW:CloseMessage()
  EFFECT:Create("effectTwinkle_00", SymEff("EV_GLITTER_RANDOM"))
  EFFECT:SetPosition("effectTwinkle_00", SymPos("P00_EFF_GLITTER_RANDOM"))
  EFFECT:Play("effectTwinkle_00")
  SOUND:PlaySe(SymSnd("SE_EVT_KIRAN"), Volume(128))
  CAMERA:MoveFollow(SymCam("CAMERA_04"), Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("PARTNER"):WalkTo(SymPos("P03_PARTNER"), Speed(1.5))
  CH("PARTNER"):WaitMove()
  CAMERA:WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -893938994, PARTNER_1 = -743660657})
  WINDOW:SwitchTalk({PARTNER_0 = -1662175928, PARTNER_1 = -2047474679})
  WINDOW:CloseMessage()
  CH("NOKOTCHI"):WalkTo(SymPos("P03_NOKOTCHI"), Speed(2))
  CH("NOKOTCHI"):WaitMove()
  WINDOW:DrawFaceF(324, 88, SymAct("NOKOTCHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NOKOTCHI"), -1361356854)
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(RotateTarget(90), Speed(350), ROT_TYPE.NEAR)
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_04_5"))
  CAMERA:SetTgt(SymCam("CAMERA_04_5"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(324, 88, SymAct("NOKOTCHI"), FACE_TYPE.EMOTION)
  WINDOW:Talk(SymAct("NOKOTCHI"), -1212127605)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CH("HERO"):SetPosition(SymPos("VIA03_HERO"))
  CH("BIRIJION"):SetPosition(SymPos("VIA03_BIRIJION"))
  CH("BURAKKII"):SetPosition(SymPos("VIA03_BURAKKII"))
  CH("EEFI"):SetPosition(SymPos("VIA03_EEFI"))
  CH("EEFI"):WalkTo(SymPos("P03_EEFI"), Speed(1.5))
  CH("BURAKKII"):WalkTo(SymPos("P03_BURAKKII"), Speed(1.5))
  CH("BIRIJION"):WalkTo(SymPos("P03_BIRIJION"), Speed(1.5))
  CH("HERO"):WalkTo(SymPos("P03_HERO"), Speed(1.5))
  CH("EEFI"):WaitMove()
  WINDOW:DrawFace(324, 88, SymAct("EEFI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EEFI"), 811104836)
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  CH("NOKOTCHI"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  CH("NOKOTCHI"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_QUESTION")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(118, 8, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 692275973, PARTNER_1 = 1077778217})
  subEveCloseMsg()
  CH("EEFI"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("EEFI"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("EEFI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EEFI"), 1495705192)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CAMERA:MoveFollow2(SymCam("CAMERA_06_5"), Speed(10, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  TASK:Regist(subEveJumpSurprise, {
    CH("NOKOTCHI")
  })
  CH("NOKOTCHI"):SetManpu("MP_SHOCK_L")
  CH("NOKOTCHI"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("NOKOTCHI"), 1913386411)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CH("EEFI"):DirTo(CH("NOKOTCHI"), Speed(200), ROT_TYPE.NEAR)
  CH("EEFI"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("EEFI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EEFI"), 1796261098)
  subEveCloseMsg()
  WINDOW:DrawFace(72, 16, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BURAKKII"), 609309229)
  WINDOW:Talk(SymAct("BURAKKII"), 1028285292)
  subEveCloseMsg()
  CH("EEFI"):DirTo(CH("BURAKKII"), Speed(350), ROT_TYPE.NEAR)
  CH("EEFI"):WaitRotate()
  CH("EEFI"):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(324, 88, SymAct("EEFI"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("EEFI"), 375861423)
  CH("EEFI"):ResetManpu()
  WINDOW:CloseMessage()
  CH("NOKOTCHI"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("NOKOTCHI"):WaitRotate()
  CH("PARTNER"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  CH("EEFI"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("NOKOTCHI"):SetManpu("MP_SPREE_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("NOKOTCHI")
  })
  WINDOW:DrawFace(324, 20, SymAct("NOKOTCHI"), FACE_TYPE.EMOTION)
  WINDOW:Talk(SymAct("NOKOTCHI"), 259785198)
  CH("NOKOTCHI"):ResetManpu()
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("EEFI"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("EEFI"), -1998316255)
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  CH("NOKOTCHI"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("EEFI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EEFI"), -1845547936)
  WINDOW:Talk(SymAct("EEFI"), -571822192)
  WINDOW:Talk(SymAct("EEFI"), -990798127)
  subEveCloseMsg()
  WINDOW:DrawFace(118, 8, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -270742254, PARTNER_1 = -154665901})
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(2.5))
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CH("PARTNER"):DirTo(GM("FURIZUMU_BEFORE_04"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("NOKOTCHI"):DirTo(GM("FURIZUMU_BEFORE_04"), Speed(500), ROT_TYPE.NEAR)
  CH("BURAKKII"):DirTo(CH("PARTNER"), Speed(200), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  TASK:Sleep(TimeSec(0.3))
  WINDOW:SysMsg(-1182373228)
  subEveCloseMsg()
  CH("PARTNER"):SetManpu("MP_SPREE_LP")
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1600300075, PARTNER_1 = -1951397866})
  CH("PARTNER"):ResetManpu()
  WINDOW:KeyWait()
  CH("PARTNER"):SetManpu("MP_SPREE_LP")
  WINDOW:SwitchTalk({PARTNER_0 = -1834272425, PARTNER_1 = 355673496})
  CH("PARTNER"):ResetManpu()
  subEveCloseMsg()
  WINDOW:SysMsg(203953369)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("NOKOTCHI"):SetManpu("MP_SHOCK_L")
  CH("PARTNER"):WalkTo(SymPos("P04_PARTNER"), Speed(2), LINK_DIR.OFF)
  CH("NOKOTCHI"):WalkTo(SymPos("P04_NOKOTCHI"), Speed(2), LINK_DIR.OFF)
  WINDOW:SysMsg(1700186357)
  WINDOW:SysMsg(2085484980)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 1465952887, PARTNER_1 = 1316723510})
  WINDOW:CloseMessage()
  EFFECT:Create("effectSmokeWhite", SymEff("EV_SMOKE_WHITE"))
  EFFECT:SetPosition("effectSmokeWhite", SymPos("P_EFF_SMOKE_WHITE"))
  EFFECT:Play("effectSmokeWhite")
  SOUND:PlaySe(SymSnd("SE_EVT_FRIZM_FREEZE"), Volume(256))
  TASK:Sleep(TimeSec(0.2))
  GM("FURIZUMU_BEFORE_04"):SetVisible(false)
  GM("FURIZUMU_AFTER_02"):SetVisible(true)
  TASK:Sleep(TimeSec(0.5))
  CH("NOKOTCHI"):SetManpu("MP_FLY_SWEAT")
  CH("NOKOTCHI"):SetMotionRaito(Raito(1.5))
  CH("NOKOTCHI"):SetMotion(SymMot("RUN"), LOOP.ON)
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("NOKOTCHI"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("NOKOTCHI"), 20581873)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  TASK:Sleep(TimeSec(0.3))
  CAMERA:ResetAzimuthDifferenceVolume()
  CHARA:SetVisible(SymLayer("LAYER_00"), false)
  GIMMICK:SetVisible(SymLayer("LAYER_00"), false)
  FLAG.SceneFlag = CONST.FL_SC_01_END
  FLAG.SCENARIOFLAG = CONST.M11_FURIZUMU_START
  SYSTEM:NextEntry()
end
function main11_furizumu01_end()
end
function main11_furizumu01_05_init()
end
function main11_furizumu01_05_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_DAIHYOUGA_02"), Volume(256))
  CAMERA:SetAzimuthDifferenceVolume(Volume(8))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  EFFECT:Create("effectIceLp", SymEff("EV_GLITTER_FURIZUMU_ICE_LP"))
  EFFECT:SetPosition("effectIceLp", SymPos("P_EFF"))
  EFFECT:Play("effectIceLp")
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  subEveFadeAfterTime()
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NOKOTCHI"), 404831408)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("EEFI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EEFI"), 856452979)
  WINDOW:Talk(SymAct("EEFI"), 706174514)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -1383120131, PARTNER_1 = -1265339460})
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("EEFI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EEFI"), 2011391771)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:SwitchTalk({PARTNER_0 = 1861768794, PARTNER_1 = 1171588505})
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("EEFI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EEFI"), 1557017816)
  WINDOW:Talk(SymAct("EEFI"), 328180255)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 177509214, PARTNER_1 = 565821597})
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  FLAG.SceneFlag = CONST.FL_SC_01_05_END
  FLAG.SCENARIOFLAG = CONST.M11_FURIZUMU_START
  SYSTEM:NextEntry()
end
function main11_furizumu01_05_end()
end
function main11_furizumu02_init()
end
function main11_furizumu02_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_DAIHYOUGA_02"), Volume(256))
  CHARA:SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  CAMERA:SetAzimuthDifferenceVolume(Volume(2.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  GM("FURIZUMU_AFTER"):SetMotion(SymMot("A"), LOOP.OFF)
  GM("FURIZUMU_BEFORE_11"):SetMotion(SymMot("A"), LOOP.OFF)
  GM("FURIZUMU_BEFORE"):SetMotion(SymMot("B"), LOOP.OFF)
  GM("FURIZUMU_BEFORE_02"):SetMotion(SymMot("A"), LOOP.OFF)
  GM("FURIZUMU_BEFORE_03"):SetMotion(SymMot("A"), LOOP.OFF)
  GM("FURIZUMU_BEFORE_04"):SetMotion(SymMot("B"), LOOP.OFF)
  GM("FURIZUMU_AFTER_02"):SetMotion(SymMot("B"), LOOP.OFF)
  GM("FURIZUMU_BEFORE_05"):SetMotion(SymMot("A"), LOOP.OFF)
  GM("FURIZUMU_BEFORE_06"):SetMotion(SymMot("C"), LOOP.OFF)
  GM("FURIZUMU_BEFORE_07"):SetMotion(SymMot("A"), LOOP.OFF)
  GM("FURIZUMU_BEFORE_08"):SetMotion(SymMot("C"), LOOP.OFF)
  GM("FURIZUMU_BEFORE_09"):SetMotion(SymMot("C"), LOOP.OFF)
  GM("FURIZUMU_BEFORE_10"):SetMotion(SymMot("A"), LOOP.OFF)
  GM("FURIZUMU_BEFORE_04"):SetVisible(false)
  GM("FURIZUMU_BEFORE_11"):SetVisible(false)
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  local lastPosPartner = CH("PARTNER"):GetPosition2d()
  CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(1.5))
  CH("PARTNER"):WaitMove()
  TASK:Sleep(TimeSec(0.3))
  WINDOW:SysMsg(950202844)
  WINDOW:CloseMessage()
  CH("PARTNER"):WalkTo(lastPosPartner, Speed(1.5), LINK_DIR.OFF)
  CH("PARTNER"):WaitMove()
  TASK:Sleep(TimeSec(0.3))
  EFFECT:Create("effectSmokeWhite", SymEff("EV_SMOKE_WHITE"))
  EFFECT:SetPosition("effectSmokeWhite", SymPos("P_EFF_SMOKE_WHITE"))
  EFFECT:Play("effectSmokeWhite")
  SOUND:PlaySe(SymSnd("SE_EVT_FRIZM_KAITOU"), Volume(256))
  TASK:Sleep(TimeSec(0.2))
  GM("FURIZUMU_AFTER_02"):SetVisible(false)
  GM("FURIZUMU_BEFORE_04"):SetVisible(true)
  TASK:Sleep(TimeSec(0.5))
  WINDOW:SysMsg(-1086657261)
  subEveCloseMsg()
  WINDOW:SwitchSysMsg({PARTNER_0 = -1507730350, PARTNER_1 = -815857538})
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_01"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("NOKOTCHI"):SetManpu("MP_SHOCK_L")
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  CH("NOKOTCHI"):SetManpu("MP_SPREE_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("NOKOTCHI")
  })
  WINDOW:DrawFace(324, 20, SymAct("NOKOTCHI"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("NOKOTCHI"), -700174017)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.EMOTION)
  WINDOW:Monologue(-43425028)
  WINDOW:Monologue(-462269507)
  subEveCloseMsg()
  CH("NOKOTCHI"):ResetManpu()
  WINDOW:DrawFace(118, 8, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1422670470, PARTNER_1 = -1305938885})
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("NOKOTCHI"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  CH("PARTNER"):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(118, 8, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  WINDOW:SwitchTalk({PARTNER_0 = -1727682568, PARTNER_1 = -2145478983})
  WINDOW:CloseMessage()
  CH("PARTNER"):ResetManpu()
  WINDOW:DrawFace(324, 88, SymAct("EEFI"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("EEFI"), 126257782)
  WINDOW:Talk(SymAct("EEFI"), 513653559)
  subEveCloseMsg()
  TASK:Regist(subEveNod, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(118, 8, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  WINDOW:SwitchTalk({PARTNER_0 = -1757671384, PARTNER_1 = -1910038167})
  subEveCloseMsg()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  CH("NOKOTCHI"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("NOKOTCHI"):WaitRotate()
  TASK:Regist(subEveDoubleJump, {
    CH("NOKOTCHI")
  })
  WINDOW:DrawFace(324, 20, SymAct("NOKOTCHI"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("NOKOTCHI"), -1526041942)
  CH("PARTNER"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:Talk(SymAct("NOKOTCHI"), -1139719189)
  WINDOW:CloseMessage()
  TASK:Regist(subEveNod, {
    CH("PARTNER")
  })
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(118, 8, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  WINDOW:SwitchTalk({PARTNER_0 = -212806356, PARTNER_1 = -364125075})
  WINDOW:SwitchTalk({PARTNER_0 = -1050232914, PARTNER_1 = -662862097})
  WINDOW:KeyWait()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  WINDOW:DrawFace(118, 8, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 1608882720, PARTNER_1 = 1191095137})
  WINDOW:SwitchTalk({PARTNER_0 = 796948301, PARTNER_1 = 916145676})
  subEveCloseMsg()
  CH("NOKOTCHI"):DirTo(CH("EEFI"), Speed(200), ROT_TYPE.NEAR)
  CH("PARTNER"):DirTo(CH("EEFI"), Speed(200), ROT_TYPE.NEAR)
  CH("BURAKKII"):DirTo(CH("EEFI"), Speed(200), ROT_TYPE.NEAR)
  WINDOW:DrawFace(324, 88, SymAct("EEFI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EEFI"), 498472399)
  WINDOW:CloseMessage()
  TASK:Regist(subEveNod, {
    CH("HERO")
  })
  TASK:Regist(subEveNod, {
    CH("PARTNER")
  })
  TASK:Regist(subEveNod, {
    CH("BIRIJION")
  })
  TASK:Regist(subEveJump, {
    CH("NOKOTCHI")
  })
  TASK:Regist(subEveNod, {
    CH("BURAKKII")
  })
  TASK:Regist(subEveNod, {
    CH("EEFI")
  })
  TASK:Sleep(TimeSec(1))
  local taskNokotchi00 = function()
    CH("NOKOTCHI"):DirTo(RotateTarget(90), Speed(350), ROT_TYPE.NEAR)
    CH("NOKOTCHI"):WaitRotate()
    TASK:Sleep(TimeSec(0.5))
    CH("NOKOTCHI"):WalkTo(SymPos("P01_NOKOTCHI"), Speed(1.5))
    CH("NOKOTCHI"):WaitMove()
    TASK:Sleep(TimeSec(0.5))
    function TaskL.Loop()
      CH("NOKOTCHI"):SetManpu("MP_LAUGH_LP")
      CH("NOKOTCHI"):SetMotion(SymMot("WALK"), LOOP.ON)
      CH("NOKOTCHI"):SetMotionRaito(Raito(2))
      TASK:Sleep(TimeSec(0.5))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.5))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.5))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.5))
      CH("NOKOTCHI"):ResetManpu()
      CH("NOKOTCHI"):SetMotion(SymMot("WAIT02"), LOOP.ON)
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.5))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.5))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.5))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
    end
    function TaskL.Finish()
      CH("NOKOTCHI"):ResetManpu()
      CH("NOKOTCHI"):SetMotion(SymMot("WAIT02"), LOOP.ON)
      CH("NOKOTCHI"):DirTo(GM("FURIZUMU_AFTER"), Speed(350), ROT_TYPE.NEAR)
      return
    end
  end
  local taskPartner00 = function()
    CH("PARTNER"):DirTo(RotateTarget(90), Speed(350), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
    TASK:Sleep(TimeSec(0.6))
    CH("PARTNER"):WalkTo(SymPos("P01_PARTNER"), Speed(1.5))
    CH("PARTNER"):WaitMove()
    TASK:Sleep(TimeSec(0.3))
    function TaskL.Loop()
      CH("PARTNER"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
      CH("PARTNER"):WaitRotate()
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.5))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("PARTNER"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
      CH("PARTNER"):WaitRotate()
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.3))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("PARTNER"):SetManpu("MP_SPREE_LP")
      TASK:Sleep(TimeSec(0.5))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.5))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.5))
      CH("PARTNER"):ResetManpu()
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.5))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.5))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
    end
    function TaskL.Finish()
      CH("PARTNER"):ResetManpu()
      CH("PARTNER"):DirTo(GM("FURIZUMU_AFTER"), Speed(350), ROT_TYPE.NEAR)
      return
    end
  end
  local taskPartner00 = function()
    TASK:Sleep(TimeSec(0.5))
    CH("PARTNER"):DirTo(RotateTarget(90), Speed(350), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
    TASK:Sleep(TimeSec(0.6))
    CH("PARTNER"):WalkTo(SymPos("P01_PARTNER"), Speed(1.5))
    CH("PARTNER"):WaitMove()
    TASK:Sleep(TimeSec(0.3))
    function TaskL.Loop()
      CH("PARTNER"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
      CH("PARTNER"):WaitRotate()
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.5))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.5))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
      CH("PARTNER"):WaitRotate()
      CH("PARTNER"):SetManpu("MP_SPREE_LP")
      TASK:Sleep(TimeSec(0.5))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.5))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.5))
      CH("PARTNER"):ResetManpu()
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.5))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.5))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
    end
    function TaskL.Finish()
      CH("PARTNER"):ResetManpu()
      CH("PARTNER"):DirTo(GM("FURIZUMU_AFTER"), Speed(350), ROT_TYPE.NEAR)
      return
    end
  end
  local taskHero00 = function()
    TASK:Sleep(TimeSec(0.7))
    CH("HERO"):WalkTo(SymPos("P01_HERO"), Speed(1.5))
    CH("HERO"):WaitMove()
    CH("HERO"):DirTo(RotateTarget(135), Speed(350), ROT_TYPE.NEAR)
    CH("HERO"):WaitRotate()
    TASK:Sleep(TimeSec(0.75))
    CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    CH("HERO"):WaitRotate()
  end
  local taskEefi00 = function()
    CH("EEFI"):DirTo(RotateTarget(135), Speed(350), ROT_TYPE.NEAR)
    CH("EEFI"):WaitRotate()
    TASK:Sleep(TimeSec(0.5))
    CH("EEFI"):DirTo(RotateTarget(-135), Speed(350), ROT_TYPE.NEAR)
    CH("EEFI"):WaitRotate()
    TASK:Sleep(TimeSec(0.7))
    CH("EEFI"):DirTo(SymPos("P01_EEFI"), Speed(350), ROT_TYPE.NEAR)
    CH("EEFI"):WaitRotate()
    CH("EEFI"):WalkTo(SymPos("P01_EEFI"), Speed(1.5))
    CH("EEFI"):WaitMove()
    CH("EEFI"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
    CH("EEFI"):WaitRotate()
  end
  local taskBura00 = function()
    TASK:Sleep(TimeSec(0.3))
    CH("BURAKKII"):DirTo(RotateTarget(45), Speed(350), ROT_TYPE.NEAR)
    CH("BURAKKII"):WaitRotate()
    TASK:Sleep(TimeSec(0.7))
    CH("BURAKKII"):DirTo(SymPos("P01_BURAKKII"), Speed(350), ROT_TYPE.NEAR)
    CH("BURAKKII"):WaitRotate()
    CH("BURAKKII"):WalkTo(SymPos("P01_BURAKKII"), Speed(1.5))
    CH("BURAKKII"):WaitMove()
    CH("BURAKKII"):DirTo(GM("FURIZUMU_BEFORE_04"), Speed(350), ROT_TYPE.NEAR)
    CH("BURAKKII"):WaitRotate()
  end
  TASK:Regist(Group("grpNoko"), taskNokotchi00)
  TASK:Regist(Group("grpPartner"), taskPartner00)
  TASK:Regist(Group("grpHero"), taskHero00)
  TASK:Sleep(TimeSec(0.5))
  CH("BIRIJION"):DirTo(RotateTarget(90), Speed(200), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.5))
  TASK:Regist(Group("grpEefi"), taskEefi00)
  TASK:Sleep(TimeSec(0.1))
  TASK:Regist(Group("grpBura"), taskBura00)
  TASK:Sleep(TimeSec(1))
  CH("BIRIJION"):DirTo(RotateTarget(0), Speed(200), ROT_TYPE.NEAR)
  CH("BIRIJION"):WaitRotate()
  TASK:Sleep(TimeSec(0.8))
  CH("BIRIJION"):DirTo(RotateTarget(90), Speed(200), ROT_TYPE.NEAR)
  CH("BIRIJION"):WaitRotate()
  TASK:Sleep(TimeSec(0.5))
  CH("BIRIJION"):DirTo(GM("FURIZUMU_AFTER"), Speed(200), ROT_TYPE.NEAR)
  CH("BIRIJION"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("BIRIJION"):SetManpu("MP_NOTICE_R")
  CH("BIRIJION"):WaitManpu()
  TASK:Sleep(TimeSec(0.3))
  SOUND:FadeOutBgm(TimeSec(3))
  CAMERA:MoveFollow(SymCam("CAMERA_02"), Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Regist(Group("grpBirijion"), subEveMoveDir, {
    CH("BIRIJION"),
    SymPos("P01_BIRIJION"),
    Speed(1.5),
    GM("FURIZUMU_AFTER")
  })
  TASK:WaitTask(Group("grpBirijion"))
  CAMERA:WaitMove()
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("BIRIJION"):SetManpu("MP_QUESTION")
  CH("BIRIJION"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("BIRIJION"), 78455950)
  subEveCloseMsg()
  TASK:ExitNotifyTasks(Group("grpNoko"))
  TASK:ExitNotifyTasks(Group("grpPartner"))
  CH("BURAKKII"):DirTo(CH("BIRIJION"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(GM("FURIZUMU_AFTER"), Speed(350), ROT_TYPE.NEAR)
  CH("EEFI"):DirTo(CH("BIRIJION"), Speed(350), ROT_TYPE.NEAR)
  CH("BURAKKII"):WaitRotate()
  TASK:WaitTask()
  WINDOW:DrawFace(20, 88, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  WINDOW:DrawFaceOffset(0, -50)
  WINDOW:Talk(SymAct("BURAKKII"), 1273803337)
  WINDOW:CloseMessage()
  TASK:Regist(subEveMoveDir, {
    CH("BURAKKII"),
    SymPos("P02_BURAKKII"),
    Speed(1.5),
    GM("FURIZUMU_AFTER")
  })
  TASK:Regist(subEveMoveDir, {
    CH("NOKOTCHI"),
    SymPos("P02_NOKOTCHI"),
    Speed(1.5),
    GM("FURIZUMU_AFTER")
  })
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(subEveMoveDir, {
    CH("PARTNER"),
    SymPos("P02_PARTNER"),
    Speed(1.5),
    GM("FURIZUMU_AFTER")
  })
  TASK:Regist(subEveMoveDir, {
    CH("HERO"),
    SymPos("P02_HERO"),
    Speed(1.5),
    GM("FURIZUMU_AFTER")
  })
  TASK:Regist(subEveMoveDir, {
    CH("EEFI"),
    SymPos("P02_EEFI"),
    Speed(1.5),
    GM("FURIZUMU_AFTER")
  })
  TASK:WaitTask()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  TASK:Sleep(TimeSec(0.3))
  FLAG.SceneFlag = CONST.FL_SC_02_END
  FLAG.SCENARIOFLAG = CONST.M11_FURIZUMU_START
  SYSTEM:NextEntry()
end
function main11_furizumu02_end()
end
function main11_furizumu02_05_init()
end
function main11_furizumu02_05_start()
  CAMERA:SetAzimuthDifferenceVolume(Volume(8))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  EFFECT:Create("effectIceLp", SymEff("EV_GLITTER_FURIZUMU_ICE_LP"))
  EFFECT:SetPosition("effectIceLp", SymPos("P_EFF"))
  EFFECT:Play("effectIceLp")
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  subEveFadeAfterTime()
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), 1391952648)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("EEFI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EEFI"), 2044383435)
  WINDOW:Talk(SymAct("EEFI"), 1623318922)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BURAKKII"), -413532859)
  WINDOW:Talk(SymAct("BURAKKII"), -29176828)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  FLAG.SceneFlag = CONST.FL_SC_02_05_END
  FLAG.SCENARIOFLAG = CONST.M11_FURIZUMU_START
  SYSTEM:NextEntry()
end
function main11_furizumu02_05_end()
end
function main11_furizumu03_init()
end
function main11_furizumu03_start()
  CHARA:SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  CH("BIRIJION"):SetPosition(SymPos("P01_BIRIJION"))
  CH("BURAKKII"):SetPosition(SymPos("P02_BURAKKII"))
  CH("NOKOTCHI"):SetPosition(SymPos("P02_NOKOTCHI"))
  CH("PARTNER"):SetPosition(SymPos("P02_PARTNER"))
  CH("HERO"):SetPosition(SymPos("P02_HERO"))
  CH("EEFI"):SetPosition(SymPos("P02_EEFI"))
  CH("BIRIJION"):SetDir(SymPos("P_FURIZUMU"))
  CH("BURAKKII"):SetDir(SymPos("P_FURIZUMU"))
  CH("NOKOTCHI"):SetDir(SymPos("P_FURIZUMU"))
  CH("PARTNER"):SetDir(SymPos("P_FURIZUMU"))
  CH("HERO"):SetDir(SymPos("P_FURIZUMU"))
  CH("EEFI"):SetDir(SymPos("P_FURIZUMU"))
  GM("FURIZUMU_AFTER"):SetMotion(SymMot("A"), LOOP.OFF)
  GM("FURIZUMU_BEFORE_11"):SetMotion(SymMot("A"), LOOP.OFF)
  GM("FURIZUMU_BEFORE"):SetMotion(SymMot("B"), LOOP.OFF)
  GM("FURIZUMU_BEFORE_02"):SetMotion(SymMot("A"), LOOP.OFF)
  GM("FURIZUMU_BEFORE_03"):SetMotion(SymMot("A"), LOOP.OFF)
  GM("FURIZUMU_BEFORE_04"):SetMotion(SymMot("B"), LOOP.OFF)
  GM("FURIZUMU_AFTER_02"):SetMotion(SymMot("B"), LOOP.OFF)
  GM("FURIZUMU_BEFORE_05"):SetMotion(SymMot("A"), LOOP.OFF)
  GM("FURIZUMU_BEFORE_06"):SetMotion(SymMot("C"), LOOP.OFF)
  GM("FURIZUMU_BEFORE_07"):SetMotion(SymMot("A"), LOOP.OFF)
  GM("FURIZUMU_BEFORE_08"):SetMotion(SymMot("C"), LOOP.OFF)
  GM("FURIZUMU_BEFORE_09"):SetMotion(SymMot("C"), LOOP.OFF)
  GM("FURIZUMU_BEFORE_10"):SetMotion(SymMot("A"), LOOP.OFF)
  GM("FURIZUMU_AFTER_02"):SetVisible(false)
  GM("FURIZUMU_BEFORE_11"):SetVisible(false)
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Regist(subEveDoubleJump, {
    CH("NOKOTCHI")
  })
  WINDOW:DrawFace(324, 88, SymAct("NOKOTCHI"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("NOKOTCHI"), -109421514)
  subEveCloseMsg()
  CH("EEFI"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(72, 16, SymAct("EEFI"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("EEFI"), -530485897)
  subEveCloseMsg()
  CH("EEFI"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  CH("NOKOTCHI"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  CH("NOKOTCHI"):WaitRotate()
  TASK:Regist(subEveJump, {
    CH("NOKOTCHI")
  })
  WINDOW:DrawFace(324, 88, SymAct("NOKOTCHI"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("NOKOTCHI"), -884195660)
  WINDOW:CloseMessage()
  CH("NOKOTCHI"):DirTo(GM("FURIZUMU_AFTER"), Speed(350), ROT_TYPE.NEAR)
  CH("NOKOTCHI"):WaitRotate()
  TASK:Sleep(TimeSec(0.2))
  CH("NOKOTCHI"):WalkTo(SymPos("P03_NOKOTCHI"), Speed(1.5))
  CH("NOKOTCHI"):WaitMove()
  CH("NOKOTCHI"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  TASK:Sleep(TimeSec(0.3))
  WINDOW:SysMsg(-766046219)
  WINDOW:CloseMessage()
  CH("NOKOTCHI"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  TASK:Sleep(TimeSec(0.2))
  CH("NOKOTCHI"):WalkTo(SymPos("P02_NOKOTCHI"), Speed(1.5), LINK_DIR.OFF)
  CH("NOKOTCHI"):WaitMove()
  TASK:Sleep(TimeSec(0.3))
  EFFECT:Create("effectSmokeWhite", SymEff("EV_SMOKE_WHITE"))
  EFFECT:SetPosition("effectSmokeWhite", SymPos("P02_EFF_SMOKE_WHITE"))
  EFFECT:Play("effectSmokeWhite")
  SOUND:PlaySe(SymSnd("SE_EVT_FRIZM_KAITOU"), Volume(256))
  TASK:Sleep(TimeSec(0.2))
  GM("FURIZUMU_AFTER"):SetVisible(false)
  GM("FURIZUMU_BEFORE_11"):SetMotion(SymMot("A"), LOOP.OFF)
  GM("FURIZUMU_BEFORE_11"):SetVisible(true)
  TASK:Sleep(TimeSec(1))
  WINDOW:SysMsg(-1659463374)
  WINDOW:CloseMessage()
  TASK:Sleep(TimeSec(0.3))
  WINDOW:SysMsg(-2079479693)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("BIRIJION"):SetManpu("MP_EXCLAMATION")
  WINDOW:SysMsg(-1356792912)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("NOKOTCHI"):SetManpu("MP_SHOCK_L")
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("BURAKKII"):SetManpu("MP_NOTICE_R")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(72, 16, SymAct("EEFI"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("EEFI"), -1237595407)
  subEveCloseMsg()
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_03_2"))
  CAMERA:SetTgt(SymCam("CAMERA_03_2"))
  SOUND:PlayBgm(SymSnd("BGM_EVE_METAMORPHOSIS_02"), Volume(256))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:SysMsg(832820798)
  WINDOW:SysMsg(683206527)
  WINDOW:SysMsg(1103510355)
  WINDOW:SysMsg(1490881042)
  WINDOW:SysMsg(1945131473)
  WINDOW:SysMsg(1793812624)
  WINDOW:SysMsg(631963223)
  WINDOW:SysMsg(1018285846)
  WINDOW:SysMsg(396139733)
  WINDOW:SysMsg(243772820)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(72, 16, SymAct("EEFI"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("EEFI"), -1994411685)
  WINDOW:Talk(SymAct("EEFI"), -1878753254)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  TASK:Sleep(TimeSec(0.3))
  CH("BIRIJION"):SetNeckRot(RotateTarget(0), RotateTarget(-30), RotateTarget(0), TimeSec(0.5))
  TASK:Sleep(TimeSec(1.8))
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_NOTICE_L")
  CH("PARTNER"):WaitManpu()
  CH("PARTNER"):DirTo(CH("BIRIJION"), Speed(200), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_QUESTION")
  WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.THINK)
  WINDOW:SwitchTalk({PARTNER_0 = 1400083645, PARTNER_1 = 1248372220})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("HERO"):SetManpu("MP_NOTICE_L")
  TASK:Sleep(TimeSec(0.1))
  CH("NOKOTCHI"):SetManpu("MP_NOTICE_L")
  CH("EEFI"):SetManpu("MP_NOTICE_R")
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("BIRIJION"), Speed(200), ROT_TYPE.NEAR)
  CH("NOKOTCHI"):DirTo(CH("BIRIJION"), Speed(200), ROT_TYPE.NEAR)
  CH("EEFI"):DirTo(RotateTarget(30), Speed(200), ROT_TYPE.NEAR)
  CH("EEFI"):WaitRotate()
  TASK:Sleep(TimeSec(0.7))
  CAMERA:SetAzimuthDifferenceVolume(Volume(2.5))
  CAMERA:SetEye(SymCam("CAMERA_03_5"))
  CAMERA:SetTgt(SymCam("CAMERA_03_5"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("BURAKKII"):SetManpu("MP_SHOCK_R")
  CH("BURAKKII"):WaitManpu()
  WINDOW:DrawFace(20, 20, SymAct("BURAKKII"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("BURAKKII"), 1631974975)
  WINDOW:Talk(SymAct("BURAKKII"), 2019477374)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(1.5))
  CAMERA:SetEye(SymCam("CAMERA_03_6"))
  CAMERA:SetTgt(SymCam("CAMERA_03_6"))
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_01"), Volume(256))
  subEveJumpSurprise(CH("NOKOTCHI"))
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("NOKOTCHI"):SetMotionRaito(Raito(1.5))
  CH("NOKOTCHI"):SetMotion(SymMot("RUN"), LOOP.ON)
  WINDOW:Talk(SymAct("NOKOTCHI"), 924799417)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3.5))
  CAMERA:SetEye(SymCam("CAMERA_03_7"))
  CAMERA:SetTgt(SymCam("CAMERA_03_7"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):WaitManpu()
  WINDOW:Monologue(772038904)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.5))
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("BIRIJION"), 86586171)
  CH("NOKOTCHI"):SetMotionRaito(Raito(1))
  CH("NOKOTCHI"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  WINDOW:Talk(SymAct("BIRIJION"), 473039482)
  WINDOW:Talk(SymAct("BIRIJION"), -1683349835)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("NOKOTCHI"):SetManpu("MP_SHOCK_L")
  TASK:Regist(subEveJumpSurprise, {
    CH("NOKOTCHI")
  })
  CH("PARTNER"):SetManpu("MP_SHOCK_L")
  CH("EEFI"):SetManpu("MP_EXCLAMATION")
  CH("EEFI"):WaitManpu()
  WINDOW:DrawFaceF(172, 8, SymAct("EEFI"), FACE_TYPE.SURPRISE)
  WINDOW:DrawFaceOffset(30, 0)
  WINDOW:Talk(SymAct("EEFI"), -2102317068)
  subEveCloseMsg()
  WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -338693160, PARTNER_1 = -220937575})
  WINDOW:SwitchTalk({PARTNER_0 = -637955750, PARTNER_1 = -1058889701})
  WINDOW:SwitchTalk({PARTNER_0 = -1885128996, PARTNER_1 = -1766324323})
  WINDOW:SwitchTalk({PARTNER_0 = -1114287010, PARTNER_1 = -1534171873})
  subEveCloseMsg()
  WINDOW:DrawFaceF(172, 8, SymAct("EEFI"), FACE_TYPE.THINK)
  WINDOW:DrawFaceOffset(30, 0)
  WINDOW:Talk(SymAct("EEFI"), 588675536)
  WINDOW:KeyWait()
  CH("EEFI"):DirTo(GM("FURIZUMU_BEFORE_11"), Speed(200), ROT_TYPE.NEAR)
  WINDOW:Talk(SymAct("EEFI"), 973949073)
  subEveCloseMsg()
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  CH("HERO"):DirTo(GM("FURIZUMU_BEFORE_11"), Speed(200), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):DirTo(GM("FURIZUMU_BEFORE_11"), Speed(200), ROT_TYPE.NEAR)
  CH("NOKOTCHI"):DirTo(GM("FURIZUMU_BEFORE_11"), Speed(200), ROT_TYPE.NEAR)
  CH("NOKOTCHI"):WaitRotate()
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_03_2"))
  CAMERA:SetTgt(SymCam("CAMERA_03_2"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:SysMsg(1981336417)
  WINDOW:SysMsg(1862531616)
  WINDOW:SysMsg(1143908835)
  WINDOW:SysMsg(1563793570)
  WINDOW:SysMsg(309595749)
  WINDOW:SysMsg(191840036)
  WINDOW:SysMsg(541224167)
  WINDOW:SysMsg(962157990)
  WINDOW:SysMsg(-1094631063)
  WINDOW:SysMsg(-1478856664)
  WINDOW:SysMsg(-828068860)
  WINDOW:SysMsg(-675308219)
  WINDOW:SysMsg(-57487738)
  WINDOW:SysMsg(-443940921)
  WINDOW:SysMsg(-1429706496)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(1))
  WINDOW:DrawFace(72, 16, SymAct("EEFI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EEFI"), -1277994943)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("BIRIJION"), -1728181374)
  subEveCloseMsg()
  CH("PARTNER"):DirTo(CH("BIRIJION"), Speed(200), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("BIRIJION"), Speed(200), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("NOKOTCHI"):DirTo(CH("BIRIJION"), Speed(200), ROT_TYPE.NEAR)
  CH("EEFI"):DirTo(RotateTarget(30), Speed(200), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("BIRIJION"), -2115683645)
  WINDOW:Talk(SymAct("BIRIJION"), 108865036)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 20, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BURAKKII"), 526784333)
  WINDOW:Talk(SymAct("BURAKKII"), -602864662)
  WINDOW:Talk(SymAct("BURAKKII"), -989187413)
  WINDOW:Talk(SymAct("BURAKKII"), -299409048)
  WINDOW:Talk(SymAct("BURAKKII"), -147042263)
  WINDOW:Talk(SymAct("BURAKKII"), -1199716626)
  WINDOW:Talk(SymAct("BURAKKII"), -1587087441)
  WINDOW:Talk(SymAct("BURAKKII"), -1974754196)
  WINDOW:Talk(SymAct("BURAKKII"), -1823435475)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  TASK:Sleep(TimeSec(0.3))
  CH("BIRIJION"):ResetNeckRot(TimeSec(0.5))
  CH("BIRIJION"):WaitNeckRot()
  WINDOW:Talk(SymAct("BIRIJION"), 348686818)
  WINDOW:Talk(SymAct("BIRIJION"), 231979171)
  WINDOW:Talk(SymAct("BIRIJION"), 1689085071)
  WINDOW:Talk(SymAct("BIRIJION"), 2109101518)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.SAD)
  WINDOW:SwitchTalk({PARTNER_0 = 1453000205, PARTNER_1 = 1333802828})
  WINDOW:SwitchTalk({PARTNER_0 = 12689803, PARTNER_1 = 433754314})
  WINDOW:SwitchTalk({PARTNER_0 = 855098121, PARTNER_1 = 736948808})
  WINDOW:SwitchTalk({PARTNER_0 = -1401622905, PARTNER_1 = -1250959418})
  WINDOW:SwitchTalk({PARTNER_0 = 1020163289, PARTNER_1 = 634733976})
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(RotateTarget(45), Speed(200), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("EEFI"):DirTo(RotateTarget(70), Speed(200), ROT_TYPE.NEAR)
  CH("HERO"):DirTo(RotateTarget(45), Speed(200), ROT_TYPE.NEAR)
  CH("BURAKKII"):DirTo(RotateTarget(90), Speed(200), ROT_TYPE.NEAR)
  CH("NOKOTCHI"):DirTo(RotateTarget(90), Speed(350), ROT_TYPE.NEAR)
  CH("NOKOTCHI"):WaitRotate()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  WINDOW:SwitchTalk({PARTNER_0 = 251139675, PARTNER_1 = 400762650})
  subEveCloseMsg()
  WINDOW:DrawFace(20, 20, SymAct("HERO"), FACE_TYPE.SPECIAL02)
  WINDOW:Monologue(1487057373)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(72, 16, SymAct("EEFI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EEFI"), 1102676124)
  WINDOW:CloseMessage()
  CH("EEFI"):DirTo(CH("BIRIJION"), Speed(200), ROT_TYPE.NEAR)
  CH("EEFI"):WaitRotate()
  CH("HERO"):DirTo(CH("BIRIJION"), Speed(200), ROT_TYPE.NEAR)
  CH("PARTNER"):DirTo(CH("BIRIJION"), Speed(200), ROT_TYPE.NEAR)
  CH("NOKOTCHI"):DirTo(CH("BIRIJION"), Speed(200), ROT_TYPE.NEAR)
  CH("BURAKKII"):DirTo(CH("BIRIJION"), Speed(200), ROT_TYPE.NEAR)
  WINDOW:DrawFace(226, 8, SymAct("EEFI"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("EEFI"), 1788138335)
  subEveCloseMsg()
  CH("BIRIJION"):DirTo(CH("EEFI"), Speed(200), ROT_TYPE.NEAR)
  CH("BIRIJION"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.SPECIAL03)
  WINDOW:Talk(SymAct("BIRIJION"), 1938809374)
  WINDOW:CloseMessage()
  CH("BIRIJION"):DirTo(CH("HERO"), Speed(200), ROT_TYPE.NEAR)
  CH("BIRIJION"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.SPECIAL05)
  WINDOW:Talk(SymAct("BIRIJION"), -199754031)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CH("BIRIJION"):DirTo(RotateTarget(90), Speed(200), ROT_TYPE.NEAR)
  CH("BIRIJION"):WaitRotate()
  CH("PARTNER"):DirTo(RotateTarget(45), Speed(200), ROT_TYPE.NEAR)
  CH("EEFI"):DirTo(RotateTarget(70), Speed(200), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(RotateTarget(45), Speed(200), ROT_TYPE.NEAR)
  CH("BURAKKII"):DirTo(RotateTarget(90), Speed(200), ROT_TYPE.NEAR)
  CH("NOKOTCHI"):DirTo(RotateTarget(90), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.SPECIAL05)
  WINDOW:Talk(SymAct("BIRIJION"), -317927536)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(2.5))
  SCREEN_A:FadeOutAll(TimeSec(1.5), true)
  SCREEN_A:FadeOut(TimeSec(0), false)
  SOUND:WaitBgm()
  subEveFadeAfterTime()
  CAMERA:ResetAzimuthDifferenceVolume()
  FLAG.SceneFlag = CONST.FL_SC_01_FIRST
  FLAG.SCENARIOFLAG = CONST.M11_FURIZUMU_END
  SYSTEM:SetDungeonWaypointStat(Dg(11), DG_WAYPOINT.POINT01, DG_WAYPOINT_STAT.AFTER)
  SYSTEM:EnterDungeon(Dg(11), DG_WAYPOINT.POINT01)
end
function main11_furizumu03_end()
end
function groundEnd()
end

