dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main02_zurukkuwooe01_init()
end
function main02_zurukkuwooe01_start()
  FLAG.TrigNextEvent = CONST.FLAG_FALSE
  CH("HERO"):SetPosition(SymPos("P00_HERO"))
  CH("PARTNER"):SetPosition(SymPos("P01_PARTNER"))
  CH("HERO"):SetDir(CH("PARTNER"))
  CH("PARTNER"):SetDir(CH("HERO"))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  GIMMICK:SetVisible(SymLayer("SHOP_CHEST"), false)
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CH("ZURUGGU"):SetVisible(false)
  CH("DOKKORAA_1"):SetVisible(false)
  CH("DOKKORAA_2"):SetVisible(false)
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- CH("HERO"):SetDir(CH("ZURUGGU"))
  -- CH("PARTNER"):SetDir(CH("ZURUGGU"))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  -- CH("HERO"):SetManpu("MP_NOTICE_R")
  -- CH("PARTNER"):WaitRotate()
  -- CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  -- CH("PARTNER"):WaitManpu()
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  -- WINDOW:SwitchTalk({PARTNER_0 = -688246873, PARTNER_1 = -807330074})
  -- WINDOW:SwitchTalk({PARTNER_0 = -456372955, PARTNER_1 = -36209564})
  -- WINDOW:CloseMessage()
  -- CAMERA:MoveFollow(SymCam("CAMERA_01"), Speed(3, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- subEveLookAround(CH("ZURUGGU"), Speed(600))
  -- CAMERA:WaitMove()
  -- CH("ZURUGGU"):DirTo(RotateTarget(-45), Speed(600), ROT_TYPE.NEAR)
  -- CH("ZURUGGU"):WaitRotate()
  -- TASK:Sleep(TimeSec(0.3))
  -- CH("ZURUGGU"):DirTo(SymPos("P00_ZURUGGU"), Speed(600), ROT_TYPE.NEAR)
  -- CH("ZURUGGU"):WaitRotate()
  -- CH("ZURUGGU"):WalkTo(SymPos("P00_ZURUGGU"), Speed(2))
  -- CH("ZURUGGU"):WaitMove()
  -- CAMERA:MoveFollow(CH("HERO"), Height(0), Speed(3, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- CAMERA:WaitMove()
  -- WINDOW:DrawFace(118, 8, SymAct("HERO"), FACE_TYPE.THINK)
  -- WINDOW:Monologue(-1298732381)
  -- WINDOW:CloseMessage()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  -- CH("HERO"):SetManpu("MP_EXCLAMATION")
  -- CH("HERO"):WaitManpu()
  -- WINDOW:DrawFace(118, 8, SymAct("HERO"), FACE_TYPE.NORMAL)
  -- WINDOW:Monologue(-1416766494)
  -- WINDOW:Monologue(-2136963039)
  -- WINDOW:Monologue(-1715750560)
  -- WINDOW:CloseMessage()
  -- CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  -- CH("HERO"):WaitRotate()
  -- CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  -- CH("PARTNER"):WaitRotate()
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  -- WINDOW:SwitchTalk({PARTNER_0 = 505652655, PARTNER_1 = 121148654})
  -- WINDOW:CloseMessage()
  -- CH("HERO"):SetMotion(SymMot("SPEAK"), LOOP.OFF)
  -- CH("HERO"):WaitPlayMotion()
  -- CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  -- TASK:Sleep(TimeSec(0.3))
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  -- WINDOW:SwitchTalk({PARTNER_0 = 1823769316, PARTNER_1 = 1974449061})
  -- WINDOW:KeyWait()
  -- TASK:Regist(subEveJump, {
  --   CH("PARTNER")
  -- })
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  -- WINDOW:SwitchTalk({PARTNER_0 = 1585635430, PARTNER_1 = 1201262887})
  -- WINDOW:SwitchTalk({PARTNER_0 = 148391904, PARTNER_1 = 298022561})
  -- WINDOW:SwitchTalk({PARTNER_0 = 988685666, PARTNER_1 = 603264035})
  -- WINDOW:CloseMessage()
  -- CH("PARTNER"):DirTo(RotateTarget(90), Speed(350), ROT_TYPE.NEAR)
  -- CH("PARTNER"):WaitRotate()
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  -- WINDOW:SwitchTalk({PARTNER_0 = -1536358164, PARTNER_1 = -1116325459})
  -- WINDOW:CloseMessage()
  -- CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  -- CH("PARTNER"):WaitRotate()
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  -- WINDOW:SwitchTalk({PARTNER_0 = 2114006282, PARTNER_1 = 1729764427})
  -- WINDOW:CloseMessage()
  -- CH("HERO"):DirTo(RotateTarget(90), Speed(500), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.2))
  -- CH("PARTNER"):DirTo(RotateTarget(90), Speed(500), ROT_TYPE.NEAR)
  -- CH("HERO"):WaitRotate()
  -- CH("HERO"):WalkTo(SymPos("P00_HERO"), Speed(2))
  -- CH("PARTNER"):WaitRotate()
  -- CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(2))
  -- WINDOW:Talk(SymAct("???"), 1278693256)
  -- WINDOW:CloseMessage()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  -- CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  -- CH("HERO"):SetManpu("MP_EXCLAMATION")
  -- CH("PARTNER"):WaitManpu()
  -- CH("PARTNER"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.NEAR)
  -- CH("HERO"):WaitRotate()
  -- CH("HERO"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.NEAR)
  -- CH("HERO"):WaitRotate()
  -- CAMERA:MoveFollow(SymCam("CAMERA_02"), Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- TASK:Regist(subEveMoveDir, {
  --   CH("DOKKORAA_1"),
  --   SymPos("P00_DOKKORAA_1"),
  --   Speed(2),
  --   RotateTarget(55)
  -- })
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("DOKKORAA_2"):WalkTo(SymPos("P00_DOKKORAA_2"), Speed(2))
  -- CH("DOKKORAA_2"):WaitMove()
  -- CAMERA:WaitMove()
  -- WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  -- WINDOW:SwitchTalk({PARTNER_0 = 1428979401, PARTNER_1 = 443410446})
  -- WINDOW:SwitchTalk({PARTNER_0 = 58120527, PARTNER_1 = 677087884})
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(72, 16, SymAct("DOKKORAA_1"), FACE_TYPE.SAD)
  -- WINDOW:Talk(SymAct("DOKKORAA_1"), 826325965)
  -- WINDOW:Talk(SymAct("DOKKORAA_1"), -1227315454)
  -- WINDOW:CloseMessage()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  -- CH("PARTNER"):SetManpu("MP_QUESTION")
  -- CH("PARTNER"):WaitManpu()
  -- SOUND:PlayBgm(SymSnd("BGM_EVE_NAZO_02"), Volume(256))
  -- WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.THINK)
  -- WINDOW:SwitchTalk({PARTNER_0 = -1346136509, PARTNER_1 = -960673169})
  -- WINDOW:CloseMessage()
  -- CH("PARTNER"):DirTo(RotateTarget(90), Speed(500), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.2))
  -- CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  -- CH("PARTNER"):WaitRotate()
  -- TASK:Sleep(TimeSec(0.75))
  -- CH("PARTNER"):DirTo(RotateTarget(-90), Speed(500), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.2))
  -- CH("HERO"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.NEAR)
  -- CH("PARTNER"):WaitRotate()
  -- WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  -- WINDOW:SwitchTalk({PARTNER_0 = -542737618, PARTNER_1 = -192206611})
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(20, 88, SymAct("DOKKORAA_2"), FACE_TYPE.THINK)
  -- WINDOW:Talk(SymAct("DOKKORAA_2"), -309323348)
  -- WINDOW:CloseMessage()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  -- CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  -- CH("HERO"):SetManpu("MP_EXCLAMATION")
  -- WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  -- WINDOW:SwitchTalk({PARTNER_0 = -1563324565, PARTNER_1 = -1144340950})
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(72, 16, SymAct("DOKKORAA_1"), FACE_TYPE.SAD)
  -- WINDOW:Talk(SymAct("DOKKORAA_1"), -1863848471)
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(20, 88, SymAct("DOKKORAA_2"), FACE_TYPE.SAD)
  -- WINDOW:Talk(SymAct("DOKKORAA_2"), -1979917144)
  -- WINDOW:Talk(SymAct("DOKKORAA_2"), 241483879)
  -- WINDOW:Talk(SymAct("DOKKORAA_2"), 394260774)
  -- WINDOW:CloseMessage()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  -- CH("HERO"):SetManpu("MP_SHOCK_L")
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("PARTNER"):SetManpu("MP_SHOCK_L")
  -- TASK:Regist(subEveJump, {
  --   CH("PARTNER")
  -- })
  -- CH("PARTNER"):WaitManpu()
  -- WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  -- WINDOW:SwitchTalk({PARTNER_0 = 1533702870, PARTNER_1 = 1114719127})
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(72, 16, SymAct("DOKKORAA_1"), FACE_TYPE.SAD)
  -- WINDOW:Talk(SymAct("DOKKORAA_1"), 1767641172)
  -- WINDOW:Talk(SymAct("DOKKORAA_1"), 1883709717)
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(20, 88, SymAct("DOKKORAA_2"), FACE_TYPE.PAIN)
  -- WINDOW:Talk(SymAct("DOKKORAA_2"), 1057404882)
  -- subEveCloseMsg()
  -- TASK:Regist(subEveJump, {
  --   CH("PARTNER")
  -- })
  -- WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  -- WINDOW:SwitchTalk({PARTNER_0 = 639469203, PARTNER_1 = 221304144})
  -- WINDOW:CloseMessage()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  -- CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  -- CH("PARTNER"):WaitManpu()
  -- WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  -- WINDOW:SwitchTalk({PARTNER_0 = 338420753, PARTNER_1 = -1816921890})
  -- WINDOW:CloseMessage()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  -- CH("DOKKORAA_1"):SetManpu("MP_FLY_SWEAT")
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("DOKKORAA_2"):SetManpu("MP_FLY_SWEAT")
  -- CH("DOKKORAA_2"):WaitManpu()
  -- CH("DOKKORAA_1"):DirTo(CH("DOKKORAA_2"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("DOKKORAA_2"):DirTo(CH("DOKKORAA_1"), Speed(350), ROT_TYPE.NEAR)
  -- CH("PARTNER"):WaitRotate()
  -- TASK:Sleep(TimeSec(1))
  -- CH("DOKKORAA_1"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("DOKKORAA_2"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  -- CH("DOKKORAA_2"):WaitRotate()
  -- WINDOW:DrawFace(72, 16, SymAct("DOKKORAA_1"), FACE_TYPE.SAD)
  -- WINDOW:Talk(SymAct("DOKKORAA_1"), -1968649825)
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(20, 88, SymAct("DOKKORAA_2"), FACE_TYPE.PAIN)
  -- WINDOW:Talk(SymAct("DOKKORAA_2"), -472509005)
  -- WINDOW:CloseMessage()
  -- SOUND:FadeOutBgm(TimeSec(3.5))
  -- CH("DOKKORAA_1"):RunTo(SymPos("P01_DOKKORAA_1"), Speed(2.5))
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("DOKKORAA_2"):RunTo(SymPos("P01_DOKKORAA_2"), Speed(2.5))
  -- TASK:Sleep(TimeSec(0.5))
  -- CH("PARTNER"):RunTo(SymPos("P01_PARTNER"), Speed(2))
  -- CH("PARTNER"):WaitMove()
  -- WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  -- WINDOW:SwitchTalk({PARTNER_0 = -87218958, PARTNER_1 = -773818575})
  -- subEveDoubleJump(CH("PARTNER"))
  -- WINDOW:CloseMessage()
  -- TASK:Sleep(TimeSec(0.5))
  -- WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SAD)
  -- WINDOW:SwitchTalk({PARTNER_0 = -923056528, PARTNER_1 = -2017800009})
  -- WINDOW:CloseMessage()
  -- CAMERA:MoveFollow(SymCam("CAMERA_03"), Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- CAMERA:WaitMove()
  -- CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.2))
  -- CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  -- CH("HERO"):WaitRotate()
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.THINK)
  -- WINDOW:SwitchTalk({PARTNER_0 = -1633558026, PARTNER_1 = -1249070539})
  -- WINDOW:SwitchTalk({PARTNER_0 = -1399356556, PARTNER_1 = 722444219})
  -- WINDOW:SwitchTalk({PARTNER_0 = 840216314, PARTNER_1 = -245122467})
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(272, 16, SymAct("HERO"), FACE_TYPE.THINK)
  -- WINDOW:Monologue(-394753252)
  -- WINDOW:Monologue(-1017784097)
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.THINK)
  -- WINDOW:SwitchTalk({PARTNER_0 = -632362594, PARTNER_1 = -1794146471})
  -- WINDOW:CloseMessage()
  -- subEveDoubleJump(CH("PARTNER"))
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  -- WINDOW:SwitchTalk({PARTNER_0 = -1944826344, PARTNER_1 = -1489429029})
  -- WINDOW:SwitchTalk({PARTNER_0 = -1105056614, PARTNER_1 = 968503381})
  -- WINDOW:SwitchTalk({PARTNER_0 = 547422484, PARTNER_1 = 1239407928})
  -- WINDOW:SwitchTalk({PARTNER_0 = 1355082873, PARTNER_1 = 2078916538})
  -- WINDOW:CloseMessage()
  -- subEveNod(CH("HERO"))
  CAMERA:MoveToHero(Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  FLAG.SceneFlag = CONST.FL_SC_01_FIRST
  FLAG.SCENARIOFLAG = CONST.M02_ZURUKKUWOOE_END
  FLAG.MapFlags = CONST.MAP_EVENT
  FLAG.FreePlay = CONST.FLAG_TRUE
  FLAG.TrigNextEvent = CONST.FLAG_FALSE
  SYSTEM:NextEntry(KEEP_PLACEMENT.ON)
end
function main02_zurukkuwooe01_end()
end
function groundEnd()
end

