dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function para_mode_tutorial01_init()
end
function para_mode_tutorial01_start()
  subEveFromProgFadeSet()
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SOUND:PlayMe(SymSnd("ME_INFORMATION"), Volume(256))
  WINDOW:Explanation(494800258)
  SOUND:WaitMe()
  WINDOW:CloseMessage()
  local taskHero01 = function()
    CH("HERO"):WalkTo(SymPos("P01_HERO"), Speed(1.5))
    CH("HERO"):WaitMove()
    CH("HERO"):WalkTo(SymPos("P02_HERO"), Speed(1.5))
  end
  local taskPartner01 = function()
    CH("PARTNER"):WalkTo(SymPos("P01_PARTNER"), Speed(1.5))
    CH("PARTNER"):WaitMove()
    CH("PARTNER"):WalkTo(SymPos("P02_PARTNER"), Speed(1.5))
  end
  TASK:Regist(taskHero01)
  TASK:Regist(taskPartner01)
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(2))
  SYSTEM:SetForceSyncStop(true)
  TASK:Sleep(TimeSec(0.3))
  WINDOW:SysMsg(73743555)
  WINDOW:SysMsg(793276160)
  WINDOW:SysMsg(911433281)
  WINDOW:SysMsg(2031274118)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  SYSTEM:SetForceSyncStop(false)
  CAMERA:SetDefaultGroundFovy()
  SYSTEM:NextSpecialEntry(SymSpecialEntry("PARA_MODE_TUTORIAL_01"))
end
function para_mode_tutorial01_end()
end
function para_mode_tutorial02_init()
end
function para_mode_tutorial02_start()
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  local taskNakama01 = function()
    CH("EMONGA"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.3))
    CH("BIRIJION"):DirTo(RotateTarget(25), Speed(200), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("NOKOTCHI"):DirTo(RotateTarget(-25), Speed(350), ROT_TYPE.NEAR)
    CH("EMONGA"):WaitRotate()
    CH("EMONGA"):SetNeckRot(RotateTarget(0), RotateTarget(20), RotateTarget(0), TimeSec(0.2))
    CH("BIRIJION"):WaitRotate()
    CH("BIRIJION"):SetNeckRot(RotateTarget(0), RotateTarget(20), RotateTarget(0), TimeSec(0.2))
    CH("NOKOTCHI"):WaitRotate()
    CH("NOKOTCHI"):SetNeckRot(RotateTarget(0), RotateTarget(20), RotateTarget(0), TimeSec(0.2))
    CH("EMONGA"):WaitNeckRot()
    CH("EMONGA"):SetManpu("MP_SPREE_LP")
    subEveDoubleJump(CH("EMONGA"))
    CH("NOKOTCHI"):SetManpu("MP_LAUGH_LP")
    subEveDoubleJump(CH("NOKOTCHI"))
  end
  WINDOW:SysMsg(1611266503)
  WINDOW:KeyWait()
  TASK:Regist(taskNakama01)
  WINDOW:SysMsg(1260694020)
  WINDOW:SysMsg(1379900229)
  WINDOW:SysMsg(-710441078)
  WINDOW:CloseMessage()
  CAMERA:SetDefaultGroundFovy()
  SYSTEM:ResumeOnlyFlags_FromTemporary(false)
  if OpenGroundToParadiseFlow(false) then
    SYSTEM:NextEntryAndChangeParadiseMode(true)
  else
    LOWER_SCREEN:SetVisible(false)
    subEveStartFadeSet()
    SYSTEM:ResumeEntry_FromTemporary()
  end
end
function para_mode_tutorial02_end()
end
function groundEnd()
end

