dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main14_shiroiwanokouyaclear1st01_init()
end
function main14_shiroiwanokouyaclear1st01_start()
  subEveFromProgFadeSet()
  subComResultClear()
  TASK:Sleep(TimeSec(1))
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.PAIN)
  WINDOW:Monologue(178391453)
  WINDOW:Monologue(330905820)
  WINDOW:Monologue(949250847)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), 563042910)
  WINDOW:Talk(SymAct("SAZANDORA"), 1859046553)
  WINDOW:CloseMessage()
  TASK:Sleep(TimeSec(0.5))
  subSaveflagM14_040_01()
end
function main14_shiroiwanokouyaclear1st01_end()
end
function subSaveflagM14_040_01()
  FLAG.SceneFlag = CONST.FL_SC_01_END
  FLAG.SCENARIOFLAG = CONST.M14_SHIROIWANOKOUYACLEAR1ST_START
  SYSTEM:NextEntry()
end
function main14_shiroiwanokouyaclear1st01_05_init()
end
function main14_shiroiwanokouyaclear1st01_05_start()
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  MAP:SetBG(SymMap("IM05_03_SKY_NIGHT"))
  MAP:SetVisible(false)
  MAP:SetVisibleBG(true)
  CH("HERO"):SetVisible(false)
  CH("SAZANDORA_LARGE"):SetVisible(false)
  GM("TAKIBI_ON"):SetVisible(false)
  SCREEN_A:FadeIn(TimeSec(1), true)
  TASK:Sleep(TimeSec(2.5))
  SCREEN_A:FadeOut(TimeSec(1), true)
  MAP:SetVisible(true)
  MAP:SetVisibleBG(false)
  CH("HERO"):SetVisible(true)
  CH("SAZANDORA_LARGE"):SetVisible(true)
  GM("TAKIBI_ON"):SetVisible(true)
  EFFECT:Create("effectFire", SymEff("EV_FIRE_LP"))
  EFFECT:SetPosition("effectFire", SymPos("P_EFF_FIRE"))
  EFFECT:Play("effectFire")
  CH("HERO"):SetNeckRot(RotateTarget(0), RotateTarget(20), RotateTarget(0), TimeSec(0))
  TASK:Sleep(TimeSec(0.5))
  SOUND:FadeInEnv(SymSnd("SE_ENV_FOREST_NIGHT_LP"), TimeSec(0.5), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  SOUND:PlaySe(SymSnd("SE_EVT_BONFIRE_LP"), Volume(128))
  TASK:Sleep(TimeSec(2.5))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.3))
  CAMERA:SetAzimuthDifferenceVolume(Volume(1.5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  subEveFadeAfterTime()
  WINDOW:Monologue(2010512856)
  WINDOW:Monologue(1559801371)
  WINDOW:Monologue(1172545370)
  WINDOW:Monologue(-1032092779)
  WINDOW:Monologue(-614419756)
  WINDOW:Monologue(-1693448904)
  WINDOW:Monologue(-2113194887)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(324, 20, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), -1457100870)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("HERO"):SetManpu("MP_NOTICE_L")
  CH("HERO"):WaitManpu()
  CH("HERO"):ResetNeckRot(TimeSec(0.2))
  CH("HERO"):WaitNeckRot()
  CH("HERO"):DirTo(CH("SAZANDORA_LARGE"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  WINDOW:DrawFace(324, 20, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), -1338157317)
  WINDOW:Talk(SymAct("SAZANDORA"), -8601540)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.THINK)
  WINDOW:Monologue(-429395587)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 20, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), -850746690)
  WINDOW:Talk(SymAct("SAZANDORA"), -732851201)
  WINDOW:Talk(SymAct("SAZANDORA"), 1405718320)
  WINDOW:Talk(SymAct("SAZANDORA"), 1255325297)
  WINDOW:Talk(SymAct("SAZANDORA"), -1985631530)
  WINDOW:CloseMessage()
  SOUND:FadeOutEnv(TimeSec(1.5))
  SOUND:FadeOutSe(SymSnd("SE_EVT_BONFIRE_LP"), TimeSec(1.5))
  subEveNod(CH("HERO"))
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_DAIHYOUGA_03"), Volume(256))
  WINDOW:DrawFace(324, 20, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), -1866556521)
  WINDOW:Talk(SymAct("SAZANDORA"), -1147942828)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("HERO"):SetManpu("MP_SHOCK_R")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(-1568081643)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("SAZANDORA_LARGE"):SetManpu("MP_NOTICE_L")
  CH("SAZANDORA_LARGE"):WaitManpu()
  WINDOW:DrawFace(324, 20, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), -305565742)
  WINDOW:Talk(SymAct("SAZANDORA"), -187539821)
  WINDOW:Talk(SymAct("SAZANDORA"), -536933040)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("HERO"):SetManpu("MP_QUESTION")
  CH("HERO"):WaitManpu()
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.THINK)
  WINDOW:Monologue(-958120943)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CH("SAZANDORA_LARGE"):DirTo(RotateTarget(-135), Speed(200), ROT_TYPE.NEAR)
  CH("SAZANDORA_LARGE"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), 1098653918)
  WINDOW:Talk(SymAct("SAZANDORA"), 1483149727)
  WINDOW:Talk(SymAct("SAZANDORA"), 823774643)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CH("SAZANDORA_LARGE"):DirTo(CH("HERO"), Speed(200), ROT_TYPE.NEAR)
  CH("SAZANDORA_LARGE"):WaitRotate()
  WINDOW:DrawFace(324, 20, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), 671284466)
  WINDOW:Talk(SymAct("SAZANDORA"), 53456689)
  WINDOW:Talk(SymAct("SAZANDORA"), 439656048)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(1433733303)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 20, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), 1282292214)
  WINDOW:Talk(SymAct("SAZANDORA"), 1732471349)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(2119719796)
  WINDOW:Monologue(-104839237)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 20, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), -522488070)
  WINDOW:Talk(SymAct("SAZANDORA"), -1395722998)
  WINDOW:Talk(SymAct("SAZANDORA"), -1244281781)
  WINDOW:Talk(SymAct("SAZANDORA"), -1627875448)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(-2015123767)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 20, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), -928894962)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.THINK)
  WINDOW:Monologue(-776404657)
  WINDOW:Monologue(-90942836)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_01"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(-477142067)
  WINDOW:Monologue(1679261442)
  WINDOW:Monologue(2097958467)
  WINDOW:CloseMessage()
  SOUND:VolumeBgm(Volume(128), TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  FLAG.SceneFlag = CONST.FL_SC_02_END
  FLAG.SCENARIOFLAG = CONST.M14_SHIROIWANOKOUYACLEAR1ST_START
  SYSTEM:NextEntry()
end
function main14_shiroiwanokouyaclear1st01_05_end()
end
function main14_shiroiwanokouyaclear1st03_init()
end
function main14_shiroiwanokouyaclear1st03_start()
  CHARA:SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  CAMERA:SetAzimuthDifferenceVolume(Volume(2.5))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:MoveFollow(SymCam("CAMERA_02_5"), Speed(0.2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  GM("FURIZUMU_AFTER_02"):SetVisible(false)
  GM("FURIZUMU_AFTER"):SetMotion(SymMot("A"), LOOP.OFF)
  GM("FURIZUMU_BEFORE"):SetMotion(SymMot("B"), LOOP.OFF)
  GM("FURIZUMU_BEFORE_02"):SetMotion(SymMot("A"), LOOP.OFF)
  GM("FURIZUMU_BEFORE_03"):SetMotion(SymMot("A"), LOOP.OFF)
  GM("FURIZUMU_BEFORE_04"):SetMotion(SymMot("B"), LOOP.OFF)
  GM("FURIZUMU_AFTER_02"):SetMotion(SymMot("B"), LOOP.OFF)
  GM("FURIZUMU_BEFORE_05"):SetMotion(SymMot("A"), LOOP.OFF)
  GM("FURIZUMU_BEFORE_06"):SetMotion(SymMot("C"), LOOP.OFF)
  GM("FURIZUMU_BEFORE_07"):SetMotion(SymMot("A"), LOOP.OFF)
  GM("FURIZUMU_BEFORE_08"):SetMotion(SymMot("C"), LOOP.OFF)
  GM("FURIZUMU_BEFORE_09"):SetMotion(SymMot("C"), LOOP.OFF)
  GM("FURIZUMU_BEFORE_10"):SetMotion(SymMot("A"), LOOP.OFF)
  CH("HERO"):SetPosition(SymPos("P02_HERO"))
  CH("PARTNER"):SetPosition(SymPos("P02_PARTNER"))
  CH("BIRIJION"):SetPosition(SymPos("P02_BIRIJION"))
  CH("NOKOTCHI"):SetPosition(SymPos("P02_NOKOTCHI"))
  CH("EEFI"):SetPosition(SymPos("P02_EEFI"))
  CH("BURAKKII"):SetPosition(SymPos("P02_BURAKKII"))
  CH("HERO"):SetDir(RotateTarget(-140))
  CH("PARTNER"):SetDir(RotateTarget(-155))
  CH("BIRIJION"):SetDir(RotateTarget(-140))
  CH("NOKOTCHI"):SetDir(RotateTarget(180))
  CH("EEFI"):SetDir(RotateTarget(180))
  CH("BURAKKII"):SetDir(RotateTarget(180))
  EFFECT:CreateRecollectionFilter()
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  WINDOW:DrawFace(324, 88, SymAct("NOKOTCHI"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("NOKOTCHI"), 343052911)
  WINDOW:Talk(SymAct("NOKOTCHI"), 225026862)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BURAKKII"), 642052333)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("EEFI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EEFI"), 1063240108)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BURAKKII"), 1881036651)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SPECIAL02)
  WINDOW:Monologue(1761961514)
  WINDOW:Monologue(1109931497)
  WINDOW:Monologue(1530070184)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  EFFECT:DestroyRecollectionFilter()
  FLAG.SceneFlag = CONST.FL_SC_03_END
  FLAG.SCENARIOFLAG = CONST.M14_SHIROIWANOKOUYACLEAR1ST_START
  SYSTEM:NextEntry()
end
function main14_shiroiwanokouyaclear1st03_end()
end
function main14_shiroiwanokouyaclear1st04_init()
end
function main14_shiroiwanokouyaclear1st04_start()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  EFFECT:Create("effectFire", SymEff("EV_FIRE_LP"))
  EFFECT:SetPosition("effectFire", SymPos("P_EFF_FIRE"))
  EFFECT:Play("effectFire")
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  SOUND:VolumeBgm(Volume(256), TimeSec(1))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(-592766873)
  WINDOW:Monologue(-978310874)
  WINDOW:Monologue(113720705)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(324, 20, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), 534514880)
  WINDOW:Talk(SymAct("SAZANDORA"), 888233731)
  WINDOW:Talk(SymAct("SAZANDORA"), 770338370)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("HERO"):SetManpu("MP_SHOCK_R")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(1655437445)
  WINDOW:Monologue(2075183556)
  WINDOW:CloseMessage()
  SOUND:VolumeBgm(Volume(128), TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  FLAG.SceneFlag = CONST.FL_SC_04_END
  FLAG.SCENARIOFLAG = CONST.M14_SHIROIWANOKOUYACLEAR1ST_START
  SYSTEM:NextEntry()
end
function main14_shiroiwanokouyaclear1st04_end()
end
function main14_shiroiwanokouyaclear1st05_init()
end
function main14_shiroiwanokouyaclear1st05_start()
  EFFECT:CreateRecollectionFilter()
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CUT:Load(SymCut("CUT_M14_040_05"))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
  CAMERA:SetDefaultGroundFovy()
  EFFECT:DestroyRecollectionFilter()
  CAMERA:ResetAzimuthDifferenceVolume()
  FLAG.SceneFlag = CONST.FL_SC_05_END
  FLAG.SCENARIOFLAG = CONST.M14_SHIROIWANOKOUYACLEAR1ST_START
  SYSTEM:NextEntry()
end
function main14_shiroiwanokouyaclear1st05_end()
end
function main14_shiroiwanokouyaclear1st05_end_talk_01()
  WINDOW:SetWaitMode(TimeSec(1.2), TimeSec(0.1))
  WINDOW:Monologue(1352505863)
  WINDOW:Monologue(1233562438)
  TASK:Sleep(TimeSec(1.5))
  WINDOW:ForceCloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
end
function main14_shiroiwanokouyaclear1st06_init()
end
function main14_shiroiwanokouyaclear1st06_start()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  EFFECT:Create("effectFire", SymEff("EV_FIRE_LP"))
  EFFECT:SetPosition("effectFire", SymPos("P_EFF_FIRE"))
  EFFECT:Play("effectFire")
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  SOUND:VolumeBgm(Volume(256), TimeSec(1))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  subEveFadeAfterTime()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(-836847735)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 20, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), -687503672)
  WINDOW:Talk(SymAct("SAZANDORA"), -1099212060)
  WINDOW:Talk(SymAct("SAZANDORA"), -1486853211)
  WINDOW:Talk(SymAct("SAZANDORA"), -1941096346)
  subEveCloseMsg()
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SPECIAL02)
  WINDOW:Monologue(-1789523673)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(-635985952)
  WINDOW:Monologue(-1022579039)
  WINDOW:Monologue(-400425630)
  WINDOW:Monologue(-247804893)
  WINDOW:Monologue(1990381804)
  WINDOW:Monologue(1874452909)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(324, 20, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), -434615630)
  WINDOW:Talk(SymAct("SAZANDORA"), -16548877)
  WINDOW:Talk(SymAct("SAZANDORA"), -735172560)
  WINDOW:Talk(SymAct("SAZANDORA"), -852158095)
  WINDOW:Talk(SymAct("SAZANDORA"), -2106290250)
  WINDOW:Talk(SymAct("SAZANDORA"), -1687175433)
  WINDOW:Talk(SymAct("SAZANDORA"), -1337791180)
  WINDOW:Talk(SymAct("SAZANDORA"), -1453728651)
  WINDOW:Talk(SymAct("SAZANDORA"), 784449722)
  WINDOW:Talk(SymAct("SAZANDORA"), 937095675)
  WINDOW:Talk(SymAct("SAZANDORA"), 1587817943)
  WINDOW:Talk(SymAct("SAZANDORA"), 1203707030)
  WINDOW:Talk(SymAct("SAZANDORA"), 1821527893)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(1971944980)
  WINDOW:Monologue(986245331)
  WINDOW:CloseMessage()
  SOUND:VolumeBgm(Volume(128), TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  FLAG.SceneFlag = CONST.FL_SC_08_END
  FLAG.SCENARIOFLAG = CONST.M14_SHIROIWANOKOUYACLEAR1ST_START
  SYSTEM:NextEntry()
end
function main14_shiroiwanokouyaclear1st06_end()
end
function main14_shiroiwanokouyaclear1st09_init()
end
function main14_shiroiwanokouyaclear1st09_start()
  GIMMICK:SetupLoopPlaced(SymGA("EV_390_G_PALACE_OBJ"), 0, 20)
  GIMMICK:MoveLoopPlaced(Speed(0.5))
  CAMERA:SetAzimuthDifferenceVolume(Volume(6))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HERO"):SetPosition(SymPos("P02_HERO"))
  CH("PARTNER"):SetPosition(SymPos("P02_PARTNER"))
  CH("BURAKKII"):SetPosition(SymPos("P02_BURAKKII"))
  CH("EEFI"):SetPosition(SymPos("P02_EEFI"))
  CH("BIRIJION"):SetPosition(SymPos("P02_BIRIJION"))
  CH("NOKOTCHI"):SetPosition(SymPos("P02_NOKOTCHI"))
  CH("HERO"):SetMotion(SymMot("DWALK"), LOOP.ON)
  CH("PARTNER"):SetMotion(SymMot("DWALK"), LOOP.ON)
  CH("BURAKKII"):SetMotion(SymMot("DWALK"), LOOP.ON)
  CH("EEFI"):SetMotion(SymMot("DWALK"), LOOP.ON)
  CH("BIRIJION"):SetMotion(SymMot("DWALK"), LOOP.ON)
  CH("NOKOTCHI"):SetMotion(SymMot("DWALK"), LOOP.ON)
  EFFECT:CreateRecollectionFilter()
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  WINDOW:DrawFace(20, 88, SymAct("EEFI"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("EEFI"), 601086354)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 20, SymAct("PARTNER"), FACE_TYPE.PAIN)
  WINDOW:SwitchTalk({PARTNER_0 = 150899281, PARTNER_1 = 300268304})
  subEveCloseMsg()
  WINDOW:DrawFace(324, 20, SymAct("BURAKKII"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("BURAKKII"), -1770149921)
  WINDOW:Talk(SymAct("BURAKKII"), -1889102178)
  subEveCloseMsg()
  WINDOW:DrawFace(72, 16, SymAct("HERO"), FACE_TYPE.THINK)
  WINDOW:Monologue(-110430360)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  EFFECT:DestroyRecollectionFilter()
  FLAG.SceneFlag = CONST.FL_SC_09_END
  FLAG.SCENARIOFLAG = CONST.M14_SHIROIWANOKOUYACLEAR1ST_START
  SYSTEM:NextEntry()
end
function main14_shiroiwanokouyaclear1st09_end()
end
function main14_shiroiwanokouyaclear1st10_init()
  if FLAG.NowResumeFlag == CONST.FLAG_TRUE then
    subEveFromProgFadeSet()
    subSaveflagM14_040_10()
  end
end
function main14_shiroiwanokouyaclear1st10_start()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  EFFECT:Create("effectFire", SymEff("EV_FIRE_LP"))
  EFFECT:SetPosition("effectFire", SymPos("P_EFF_FIRE"))
  EFFECT:Play("effectFire")
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  SOUND:VolumeBgm(Volume(256), TimeSec(1))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  subEveFadeAfterTime()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(-529414615)
  WINDOW:Monologue(-883124758)
  subEveCloseMsg()
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  WINDOW:DrawFace(324, 20, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), -767056725)
  WINDOW:Talk(SymAct("SAZANDORA"), -1660538260)
  WINDOW:Talk(SymAct("SAZANDORA"), -2078473427)
  WINDOW:Talk(SymAct("SAZANDORA"), -1355788050)
  WINDOW:Talk(SymAct("SAZANDORA"), -1238670929)
  WINDOW:Talk(SymAct("SAZANDORA"), 833846624)
  WINDOW:Talk(SymAct("SAZANDORA"), 682118177)
  WINDOW:Talk(SymAct("SAZANDORA"), 1104580621)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SAD)
  WINDOW:Monologue(1489871180)
  WINDOW:Monologue(1944121999)
  WINDOW:Monologue(1794884558)
  CH("HERO"):SetManpu("MP_NOTICE_R")
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.THINK)
  WINDOW:Monologue(632968457)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(324, 20, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), 1017209928)
  WINDOW:Talk(SymAct("SAZANDORA"), 395065227)
  WINDOW:Talk(SymAct("SAZANDORA"), 244778698)
  WINDOW:Talk(SymAct("SAZANDORA"), -1995499003)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("HERO"):SetManpu("MP_SHOCK_R")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(-1877726396)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 20, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), 1399013347)
  WINDOW:KeyWait()
  CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
  WINDOW:DrawFace(324, 20, SymAct("SAZANDORA"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("SAZANDORA"), 1249382050)
  WINDOW:Talk(SymAct("SAZANDORA"), 1632984417)
  WINDOW:Talk(SymAct("SAZANDORA"), 2018405408)
  WINDOW:Talk(SymAct("SAZANDORA"), 923794151)
  WINDOW:CloseMessage()
  CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("SAZANDORA_LARGE"):SetManpu("MP_FLY_SWEAT")
  CH("SAZANDORA_LARGE"):WaitManpu()
  WINDOW:DrawFace(324, 20, SymAct("SAZANDORA"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("SAZANDORA"), 773114790)
  WINDOW:KeyWait()
  TASK:Regist(subEveJump, {
    CH("SAZANDORA_LARGE")
  })
  WINDOW:Talk(SymAct("SAZANDORA"), 87660645)
  WINDOW:Talk(SymAct("SAZANDORA"), 472033572)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(3))
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HERO"):DirTo(RotateTarget(90), Speed(200), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.THINK)
  WINDOW:Monologue(-1682262549)
  WINDOW:Monologue(-2103343958)
  WINDOW:Monologue(-337684346)
  WINDOW:Monologue(-222008889)
  WINDOW:Monologue(-639026684)
  WINDOW:Monologue(-1057879227)
  WINDOW:KeyWait()
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.DECIDE)
  WINDOW:Monologue(-1884054142)
  WINDOW:Monologue(-1767330621)
  WINDOW:Monologue(-1115291904)
  WINDOW:CloseMessage()
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("HERO"):DirTo(CH("SAZANDORA_LARGE"), Speed(200), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  TASK:Sleep(TimeSec(0.3))
  subEveNod(CH("HERO"))
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("SAZANDORA_LARGE"):SetManpu("MP_FLY_SWEAT")
  TASK:Regist(subEveDoubleJump, {
    CH("SAZANDORA_LARGE")
  })
  WINDOW:DrawFace(324, 20, SymAct("SAZANDORA"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("SAZANDORA"), -1533096383)
  WINDOW:Talk(SymAct("SAZANDORA"), 587649678)
  subEveJump(CH("SAZANDORA_LARGE"))
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(1), true)
  TASK:Sleep(TimeSec(0.5))
  TASK:Sleep(TimeSec(0.2))
  if Ground_Save(ground) then
    return
  end
  subSaveflagM14_040_10()
end
function main14_shiroiwanokouyaclear1st10_end()
end
function subSaveflagM14_040_10()
  FLAG.SceneFlag = CONST.FL_SC_10_END
  FLAG.SCENARIOFLAG = CONST.M14_SHIROIWANOKOUYACLEAR1ST_START
  SYSTEM:NextEntry()
end
function main14_shiroiwanokouyaclear1st11_init()
end
function main14_shiroiwanokouyaclear1st11_start()
  SYSTEM:UpdateNextDayParameter()
  WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), 975037391)
  WINDOW:CloseMessage()
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HERO"):RunTo(SymPos("P01_HERO"), Speed(2))
  CH("SAZANDORA_LARGE"):WalkTo(SymPos("P01_SAZANDORA"), Speed(2))
  SOUND:PlayEnv(SymSnd("SE_ENV_BREEZE_LP"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(2))
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("SAZANDORA_LARGE"):WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), 1980260415)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("SAZANDORA_LARGE"):SetManpu("MP_FLY_SWEAT")
  CH("SAZANDORA_LARGE"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("SAZANDORA"), 1863537022)
  WINDOW:CloseMessage()
  CH("SAZANDORA_LARGE"):DirTo(CH("HERO"), Speed(200), ROT_TYPE.NEAR)
  CH("SAZANDORA_LARGE"):WaitRotate()
  CH("HERO"):DirTo(CH("SAZANDORA_LARGE"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), 1144914621)
  WINDOW:Talk(SymAct("SAZANDORA"), 1562719228)
  WINDOW:CloseMessage()
  subEveNod(CH("HERO"))
  TASK:Sleep(TimeSec(0.3))
  CH("HERO"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.DECIDE)
  WINDOW:Monologue(308585787)
  WINDOW:Monologue(192910458)
  WINDOW:Monologue(542295993)
  WINDOW:Monologue(961148664)
  WINDOW:Monologue(-1093539273)
  WINDOW:Monologue(-1479877770)
  WINDOW:Monologue(-827062438)
  WINDOW:Monologue(-676383205)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), -58563112)
  WINDOW:CloseMessage()
  CH("HERO"):DirTo(CH("SAZANDORA_LARGE"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  TASK:Sleep(TimeSec(0.2))
  subEveNod(CH("HERO"))
  SOUND:FadeOutEnv(TimeSec(1.5))
  CAMERA:MoveToHero(Speed(4, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  FLAG.SceneFlag = CONST.FL_SC_01_FIRST
  FLAG.SCENARIOFLAG = CONST.M14_SHIROIWANOKOUYACLEAR1ST_END
  FLAG.MapFlags = CONST.MAP_EVENT
  FLAG.FreePlay = CONST.FLAG_TRUE
  FLAG.TrigNextEvent = CONST.FLAG_FALSE
  SYSTEM:NextEntry(KEEP_PLACEMENT.ON)
end
function main14_shiroiwanokouyaclear1st11_end()
end
function groundEnd()
end

