dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main17_daikesshounotouboss1st01_init()
end
function main17_daikesshounotouboss1st01_start()
  subEveFromProgFadeSet()
  TASK:Sleep(TimeSec(1))
  EFFECT:Create("effect01", SymEff("EV_EDDY_BIG_LP"))
  EFFECT:SetPosition("effect01", SymPos("P01_EFFECT"))
  EFFECT:Play("effect01")
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetFovy(SymCam("CAMERA_06"))
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CAMERA:MoveFollow2(SymCam("CAMERA_07"), Speed(3, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SOUND:PlaySe(SymSnd("SE_EVT_EARTHQUAKE_L_LP"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CAMERA:WaitMove()
  TASK:Sleep(TimeSec(1))
  SOUND:FadeOutSe(SymSnd("SE_EVT_EARTHQUAKE_L_LP"), TimeSec(1.5))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  CAMERA:SetDefaultGroundFovy()
  FLAG.SceneFlag = CONST.FL_SC_01_END
  FLAG.SCENARIOFLAG = CONST.M17_DAIKESSHOUNOTOUBOSS1ST_START
  SYSTEM:NextEntry()
end
function main17_daikesshounotouboss1st01_end()
end
function main17_daikesshounotouboss1st02_init()
end
function main17_daikesshounotouboss1st02_start()
  CH("KYUREMU"):SetVisible(false)
  GM("KYUREMU_SHADOW2"):SetVisible(false)
  CH("KYUREMU"):SetShadow(false)
  CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SOUND:FadeInEnv(SymSnd("SE_EVT_ENTRANCE_STREAM_LP"), TimeSec(0.5), Volume(64))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("HERO"):RunTo(SymPos("P01_HERO"), Speed(2))
  CH("PARTNER"):RunTo(SymPos("P01_PARTNER"), Speed(2))
  local taskHeroLookAround = function()
    CH("HERO"):DirTo(RotateTarget(60), Speed(350), ROT_TYPE.NEAR)
    CH("HERO"):WaitRotate()
    TASK:Sleep(TimeSec(0.1))
    CH("HERO"):DirTo(RotateTarget(-60), Speed(350), ROT_TYPE.NEAR)
    CH("HERO"):WaitRotate()
    TASK:Sleep(TimeSec(0.3))
    CH("HERO"):DirTo(RotateTarget(60), Speed(350), ROT_TYPE.NEAR)
    CH("HERO"):WaitRotate()
  end
  local taskPartnerLookAround = function()
    CH("PARTNER"):DirTo(RotateTarget(-60), Speed(350), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
    TASK:Sleep(TimeSec(0.1))
    CH("PARTNER"):DirTo(RotateTarget(60), Speed(350), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
    TASK:Sleep(TimeSec(0.1))
    CH("PARTNER"):DirTo(RotateTarget(-60), Speed(350), ROT_TYPE.NEAR)
    CH("PARTNER"):WaitRotate()
  end
  CH("HERO"):WaitMove()
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(Group("hero"), taskHeroLookAround)
  CH("PARTNER"):WaitMove()
  TASK:Sleep(TimeSec(0.3))
  TASK:Regist(Group("part"), taskPartnerLookAround)
  TASK:WaitTask(Group("part"))
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
  CH("PARTNER"):SetMotion(SymMot("EV013_TIRED"), LOOP.ON, TimeSec(0.2))
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFaceF(20, 88, SymAct("PARTNER"), FACE_TYPE.PAIN)
  WINDOW:SwitchTalk({PARTNER_0 = -2107353238, PARTNER_1 = -1686149589})
  WINDOW:CloseMessage()
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:Monologue(-1336789528)
  WINDOW:Monologue(-1454832471)
  WINDOW:Monologue(-435645842)
  WINDOW:Monologue(-15490257)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("PARTNER"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.5))
  TASK:Sleep(TimeSec(0.5))
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  CH("PARTNER"):DirTo(RotateTarget(-135), Speed(200), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
  WINDOW:DrawFaceF(20, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL03)
  WINDOW:SwitchTalk({PARTNER_0 = -734072596, PARTNER_1 = -853163603})
  WINDOW:SwitchTalk({PARTNER_0 = 1253956962, PARTNER_1 = 1403448355})
  WINDOW:CloseMessage()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  CH("PARTNER"):DirTo(RotateTarget(180), Speed(200), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  CH("PARTNER"):WalkTo(SymPos("P02_PARTNER"), Speed(1.5))
  CH("HERO"):DirTo(SymPos("P02_PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 1279166071, PARTNER_1 = 1428535094})
  WINDOW:CloseMessage()
  CH("HERO"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.3))
  CAMERA:MoveFollow(SymCam("CAMERA_02_5"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SOUND:VolumeEnv(Volume(256), TimeSec(0.5))
  SCREEN_A:FadeIn(TimeSec(0.3), true)
  CAMERA:WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 2114512117, PARTNER_1 = 1729353140})
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  subEveDoubleJump(CH("PARTNER"))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = 676479859, PARTNER_1 = 826896946})
  WINDOW:SwitchTalk({PARTNER_0 = 442769905, PARTNER_1 = 58658992})
  WINDOW:CloseMessage()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  CH("HERO"):RunTo(SymPos("P02_HERO"), Speed(2))
  CH("PARTNER"):RunTo(SymPos("P03_PARTNER"), Speed(1.5))
  CAMERA:MoveFollow(SymCam("CAMERA_01_5"), Speed(2.5, ACCEL_TYPE.NONE, DECEL_TYPE.NONE))
  CH("PARTNER"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_01"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  WINDOW:Talk(SymAct("KYUREMU"), -2065232769)
  WINDOW:CloseMessage()
  CH("HERO"):WaitMove()
  TASK:Regist(Group("grpHero"), subEveLookAround, {
    CH("HERO"),
    Speed(600)
  })
  TASK:Sleep(TimeSec(0.3))
  TASK:Regist(subEveLookAround02, {
    CH("PARTNER"),
    Speed(600)
  })
  TASK:WaitTask()
  TASK:WaitTask(Group("grpHero"))
  CH("HERO"):DirTo(RotateTarget(135), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  WINDOW:DrawFaceF(324, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(-1644413634)
  subEveCloseMsg()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
  WINDOW:DrawFaceF(20, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL03)
  WINDOW:SwitchTalk({PARTNER_0 = 1586178457, PARTNER_1 = 1200625880})
  WINDOW:SwitchTalk({PARTNER_0 = 1824344859, PARTNER_1 = 1973844570})
  WINDOW:CloseMessage()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_02_5"))
  CAMERA:SetTgt(SymCam("CAMERA_02_5"))
  CAMERA:MoveFollow2(SymCam("CAMERA_02"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  local taskTurn01 = function()
    TASK:Sleep(TimeSec(0.4))
    CH("HERO"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.3))
    CH("PARTNER"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskTurn01)
  WINDOW:Talk(SymAct("KYUREMU"), 988277917)
  WINDOW:Talk(SymAct("KYUREMU"), 603774428)
  WINDOW:Talk(SymAct("KYUREMU"), 147951135)
  WINDOW:CloseMessage()
  SOUND:FadeOutEnv(TimeSec(1.5))
  SOUND:PlaySe(SymSnd("SE_EVT_KYUREMU_APPEAR"), Volume(256))
  TASK:Sleep(TimeSec(0.3))
  SCREEN_A:WhiteOutAll(TimeSec(0.5), true)
  WINDOW:ForceCloseMessage()
  TASK:Sleep(TimeSec(1.5))
  CH("KYUREMU"):SetVisible(true)
  GM("KYUREMU_SHADOW2"):SetVisible(true)
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CAMERA:MoveFollow2(SymCam("CAMERA_03_5"), Speed(4, ACCEL_TYPE.NONE, DECEL_TYPE.NONE))
  CH("KYUREMU"):SetMotion(SymMot("LANDING"), LOOP.OFF)
  SCREEN_A:WhiteInAll(TimeSec(0.5), false)
  TASK:Sleep(TimeSec(0.1))
  SOUND:PlaySe(SymSnd("SE_EVT_KYUREMU_LAND"), Volume(256))
  CAMERA:SetShake(Vector2(0.03, 0.03), TimeSec(1, TIME_TYPE.FRAME))
  CH("HERO"):SetMotion(SymMot("EV018_LIES00"), LOOP.OFF)
  CH("HERO"):MoveTo(SymPos("P03_HERO"), Speed(1.5), LINK_DIR.OFF)
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):SetMotion(SymMot("EV018_LIES00"), LOOP.OFF)
  CH("PARTNER"):MoveTo(SymPos("P04_PARTNER"), Speed(1.5), LINK_DIR.OFF)
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  CH("KYUREMU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CAMERA:WaitMove()
  CH("HERO"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
  CH("PARTNER"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
  TASK:Sleep(TimeSec(0.5))
  CH("KYUREMU"):SetMotion(SymMot("EV011_ROAR00"), LOOP.OFF)
  TASK:Sleep(TimeSec(0.6))
  SOUND:PlaySe(SymSnd("SE_EVT_KYUREMU_ROAR"), Volume(256))
  CAMERA:MoveFollow2(SymCam("CAMERA_04"), Speed(15, ACCEL_TYPE.NONE, DECEL_TYPE.NONE))
  CH("KYUREMU"):WaitPlayMotion()
  CAMERA:SetShake(Vector2(0.03, 0.03), TimeSec(1, TIME_TYPE.FRAME))
  EFFECT:StartMotionBlur(0, 0, 0)
  EFFECT:ChangeMotionBlurLevel(0.04, TimeSec(0.05))
  EFFECT:ChangeMotionBlurAlpha(0.9, TimeSec(0.05))
  CH("KYUREMU"):SetMotion(SymMot("EV011_ROAR01"), LOOP.ON)
  TASK:Sleep(TimeSec(2))
  SCREEN_A:WhiteOutAll(TimeSec(0.3), true)
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  WINDOW:ForceCloseMessage()
  TASK:Sleep(TimeSec(0.5))
  EFFECT:EndMotionBlur()
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetFovy(SymCam("CAMERA_08"))
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  CH("KYUREMU"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.5))
  SOUND:PlayBgm(SymSnd("BGM_EVE_BOSSAPPEAR"), Volume(256))
  SCREEN_A:WhiteInAll(TimeSec(0.3), true)
  subEveFadeAfterTime()
  WINDOW:Monologue(298499934)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetFovy(SymCam("CAMERA_05"))
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:Talk(SymAct("KYUREMU"), -1772969071)
  WINDOW:Talk(SymAct("KYUREMU"), -1891003696)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetFovy(SymCam("CAMERA_05_5"))
  CAMERA:SetEye(SymCam("CAMERA_05_5"))
  CAMERA:SetTgt(SymCam("CAMERA_05_5"))
  CH("HERO"):SetVisible(false)
  CH("PARTNER"):SetVisible(false)
  WINDOW:Talk(SymAct("KYUREMU"), -432582916)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetFovy(SymCam("CAMERA_05"))
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CH("HERO"):SetVisible(true)
  CH("PARTNER"):SetVisible(true)
  TASK:Sleep(TimeSec(0.1))
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.DECIDE)
  WINDOW:Monologue(-13860931)
  WINDOW:Monologue(-738120578)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetFovy(SymCam("CAMERA_06"))
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  CAMERA:MoveFollow2(SymCam("CAMERA_06_5"), Speed(4, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  WINDOW:Talk(SymAct("KYUREMU"), -853926593)
  CAMERA:WaitMove()
  WINDOW:Talk(SymAct("KYUREMU"), -2107929608)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(1.5))
  CAMERA:SetFovy(SymCam("CAMERA_07"))
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  CH("KYUREMU"):SetVisible(false)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = -1690256711, PARTNER_1 = -1334974086})
  WINDOW:SwitchTalk({PARTNER_0 = -1451829189, PARTNER_1 = 787399924})
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetFovy(SymCam("CAMERA_08"))
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  CH("KYUREMU"):SetVisible(true)
  TASK:Sleep(TimeSec(0.1))
  WINDOW:Talk(SymAct("KYUREMU"), 938866101)
  WINDOW:Talk(SymAct("KYUREMU"), 2078307909)
  WINDOW:Talk(SymAct("KYUREMU"), 1660634884)
  WINDOW:Talk(SymAct("KYUREMU"), 1238766791)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(2.5))
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetFovy(SymCam("CAMERA_09"))
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  TASK:Sleep(TimeSec(0.1))
  WINDOW:SwitchTalk({PARTNER_0 = 1355621766, PARTNER_1 = 529314625})
  WINDOW:SwitchTalk({PARTNER_0 = 110592512, PARTNER_1 = 767218115})
  WINDOW:SwitchTalk({PARTNER_0 = 883024002, PARTNER_1 = -1288045491})
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetFovy(SymCam("CAMERA_10"))
  CAMERA:SetEye(SymCam("CAMERA_10"))
  CAMERA:SetTgt(SymCam("CAMERA_10"))
  CH("HERO"):SetVisible(false)
  CH("PARTNER"):SetVisible(false)
  TASK:Sleep(TimeSec(0.1))
  SOUND:PlayBgm(SymSnd("BGM_EVE_BOSS_KYUREMU"), Volume(256))
  WINDOW:Talk(SymAct("KYUREMU"), -1440559860)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_FLUSH"), Volume(256))
  subEveFlash()
  WINDOW:Talk(SymAct("KYUREMU"), -1017376480)
  WINDOW:CloseMessage()
  subEveFlash2()
  CH("KYUREMU"):SetMotion(SymMot("EV011_ROAR00"), LOOP.OFF)
  TASK:Sleep(TimeSec(0.6))
  SOUND:PlaySe(SymSnd("SE_EVT_KYUREMU_ROAR"), Volume(256))
  CAMERA:MoveFollow2(SymCam("CAMERA_10_5"), Speed(5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Sleep(TimeSec(0.15))
  EFFECT:StartMotionBlur(0, 0, 0)
  EFFECT:ChangeMotionBlurLevel(0.04, TimeSec(0.05))
  EFFECT:ChangeMotionBlurAlpha(0.9, TimeSec(0.05))
  CH("KYUREMU"):WaitPlayMotion()
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  CH("KYUREMU"):SetMotion(SymMot("EV011_ROAR01"), LOOP.ON)
  TASK:Sleep(TimeSec(1.5))
  SOUND:PlaySe(SymSnd("SE_EVT_BOSS_WIPE"), Volume(256))
  EFFECT:BossWipe(TimeSec(60, TIME_TYPE.FRAME), true)
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  EFFECT:EndMotionBlur()
  CAMERA:ResetAzimuthDifferenceVolume()
  FLAG.SceneFlag = CONST.FL_SC_01_FIRST
  FLAG.SCENARIOFLAG = CONST.M17_DAIKESSHOUNOTOUBOSS1ST_END
  SYSTEM:SetNextDungeonBanner(false)
  SYSTEM:SetDungeonWaypointStat(Dg(22), DG_WAYPOINT.DUNGEONEND, DG_WAYPOINT_STAT.AFTER)
  SYSTEM:EnterDungeon(Dg(22), DG_WAYPOINT.BOSS00)
end
function main17_daikesshounotouboss1st02_end()
end
function groundEnd()
end

