dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main16_daihyougahefutatabi01_init()
end
function main16_daihyougahefutatabi01_start()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CUT:Load(SymCut("CUT_M16_070_01"))
  -- CUT:Play()
  -- CUT:Wait()
  -- CUT:Destroy()
  -- CAMERA:SetDefaultGroundFovy()
  -- CAMERA:ResetAzimuthDifferenceVolume()
  -- MAP:ReturnLightColor(TimeSec(0))
  FLAG.SceneFlag = CONST.FL_SC_01_END
  FLAG.SCENARIOFLAG = CONST.M16_DAIHYOUGAHEFUTATABI_START
  SYSTEM:NextEntry()
end
function main16_daihyougahefutatabi01_end()
end
function main16_daihyougahefutatabi01_BGBlack()
  -- MAP:ChangeLightColor(Color(0.2, 0.2, 0.2, 1), TimeSec(80, TIME_TYPE.FRAME))
end
function main16_daihyougahefutatabi02_init()
  if FLAG.NowResumeFlag == CONST.FLAG_TRUE then
    subEveFromProgFadeSet()
    subSaveflagM16_070_02()
  end
end
function main16_daihyougahefutatabi02_start()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- CAMERA:MoveFollow2(SymCam("CAMERA_00_5"), Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- CHARA:SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  -- MAP:ChangeLightColor(Color(0.2, 0.2, 0.2, 1), TimeSec(0))
  -- MAP:ChangeProjectionShadowAlpha(0, TimeSec(0, TIME_TYPE.FRAME))
  -- GM("MAGNAGATEMARK"):SetVisible(false)
  -- EFFECT:Create("effectGatebaseOkLp", SymEff("EV_GATEBASE_OK_LP"))
  -- EFFECT:SetPosition("effectGatebaseOkLp", SymPos("P_EFF_EV_GATEBASE_START"))
  -- EFFECT:Play("effectGatebaseOkLp")
  -- SOUND:PlayBgm(SymSnd("BGM_EVE_MAGNAGATE"), Volume(256))
  -- SOUND:PlaySe(SymSnd("SE_EVT_MAGNAGATE_LP"), Volume(64))
  -- SCREEN_A:WhiteIn(TimeSec(0.5), true)
  -- CAMERA:WaitMove()
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.CATCHBREATH)
  -- WINDOW:SwitchTalk({PARTNER_0 = 925237535, PARTNER_1 = 775762014})
  -- WINDOW:SwitchTalk({PARTNER_0 = 84960157, PARTNER_1 = 470504156})
  -- subEveCloseMsg()
  -- TASK:Regist(subEveDoubleJump, {
  --   CH("EMONGA")
  -- })
  -- WINDOW:DrawFace(324, 88, SymAct("EMONGA"), FACE_TYPE.SURPRISE)
  -- WINDOW:Talk(SymAct("EMONGA"), 1397408795)
  -- WINDOW:Talk(SymAct("EMONGA"), 1246885210)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  -- CAMERA:SetEye(SymCam("CAMERA_01"))
  -- CAMERA:SetTgt(SymCam("CAMERA_01"))
  -- CH("PARTNER"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  -- CH("PARTNER"):WaitRotate()
  -- CH("EMONGA"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  -- CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  -- WINDOW:DrawFace(20, 20, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  -- WINDOW:SwitchTalk({PARTNER_0 = 1635559065, PARTNER_1 = 2020055000})
  -- WINDOW:CloseMessage()
  -- CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  -- CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  -- CH("PARTNER"):WaitRotate()
  -- CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  -- WINDOW:DrawFace(20, 20, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  -- WINDOW:SwitchTalk({PARTNER_0 = -29929, PARTNER_1 = -421217706})
  -- WINDOW:SwitchTalk({PARTNER_0 = -1669445049, PARTNER_1 = -2056946938})
  -- subEveDoubleJump(CH("PARTNER"))
  -- WINDOW:CloseMessage()
  -- subEveNod(CH("HERO"))
  -- TASK:Sleep(TimeSec(0.3))
  -- TASK:Regist(subEveDoubleJump, {
  --   CH("NOKOTCHI")
  -- })
  -- WINDOW:DrawFace(324, 88, SymAct("NOKOTCHI"), FACE_TYPE.HAPPY)
  -- WINDOW:Talk(SymAct("NOKOTCHI"), -1371002683)
  -- WINDOW:CloseMessage()
  -- CH("PARTNER"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  -- CH("EMONGA"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("HERO"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  -- CH("BIRIJION"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  -- CH("BIRIJION"):WaitRotate()
  -- WINDOW:DrawFace(324, 88, SymAct("NOKOTCHI"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("NOKOTCHI"), -1219290748)
  -- WINDOW:KeyWait()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  -- CH("NOKOTCHI"):SetManpu("MP_FLY_SWEAT")
  -- WINDOW:DrawFace(324, 88, SymAct("NOKOTCHI"), FACE_TYPE.TEARS)
  -- WINDOW:Talk(SymAct("NOKOTCHI"), -133001405)
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(118, 8, SymAct("EMONGA"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("EMONGA"), -519455230)
  -- WINDOW:Talk(SymAct("EMONGA"), -903549503)
  -- WINDOW:KeyWait()
  -- TASK:Regist(subEveDoubleJump, {
  --   CH("EMONGA")
  -- })
  -- WINDOW:Talk(SymAct("EMONGA"), -750789504)
  -- subEveCloseMsg()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  -- CH("NOKOTCHI"):SetManpu("MP_FLY_SWEAT")
  -- CH("NOKOTCHI"):WaitManpu()
  -- WINDOW:DrawFace(324, 88, SymAct("NOKOTCHI"), FACE_TYPE.TEARS)
  -- WINDOW:Talk(SymAct("NOKOTCHI"), 1420279887)
  -- subEveCloseMsg()
  -- TASK:Regist(subEveDoubleJump, {
  --   CH("EMONGA")
  -- })
  -- WINDOW:DrawFace(118, 8, SymAct("EMONGA"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("EMONGA"), 1304228110)
  -- subEveCloseMsg()
  -- TASK:Regist(subEveJump, {
  --   CH("NOKOTCHI")
  -- })
  -- WINDOW:DrawFace(324, 88, SymAct("NOKOTCHI"), FACE_TYPE.TEARS)
  -- WINDOW:Talk(SymAct("NOKOTCHI"), -1899240023)
  -- WINDOW:Talk(SymAct("NOKOTCHI"), -1747921688)
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(324, 20, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("BIRIJION"), -1124235477)
  -- CH("NOKOTCHI"):DirTo(CH("BIRIJION"), Speed(350), ROT_TYPE.NEAR)
  -- WINDOW:Talk(SymAct("BIRIJION"), -1511606678)
  -- WINDOW:Talk(SymAct("BIRIJION"), -358145875)
  -- subEveCloseMsg()
  -- TASK:Regist(subEveJump, {
  --   CH("NOKOTCHI")
  -- })
  -- WINDOW:DrawFace(72, 88, SymAct("NOKOTCHI"), FACE_TYPE.TEARS)
  -- WINDOW:DrawFaceOffset(60, 0)
  -- WINDOW:Talk(SymAct("NOKOTCHI"), -205778452)
  -- WINDOW:Talk(SymAct("NOKOTCHI"), -661568977)
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(20, 20, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  -- WINDOW:SwitchTalk({PARTNER_0 = -1047891090, PARTNER_1 = 1175613345})
  -- CH("NOKOTCHI"):DirTo(RotateTarget(-165), Speed(350), ROT_TYPE.NEAR)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_03"))
  -- CAMERA:SetTgt(SymCam("CAMERA_03"))
  -- TASK:Regist(subEveMoveDir2, {
  --   CH("EMONGA"),
  --   SymPos("P01_EMONGA"),
  --   Speed(1.5),
  --   CH("NOKOTCHI")
  -- })
  -- TASK:Sleep(TimeSec(0.2))
  -- TASK:Regist(subEveMoveDir2, {
  --   CH("PARTNER"),
  --   SymPos("P01_PARTNER"),
  --   Speed(1.5),
  --   CH("NOKOTCHI")
  -- })
  -- TASK:Sleep(TimeSec(0.2))
  -- TASK:Regist(subEveMoveDir2, {
  --   CH("HERO"),
  --   SymPos("P01_HERO"),
  --   Speed(1.5),
  --   CH("NOKOTCHI")
  -- })
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("BIRIJION"):DirTo(SymPos("VIA01_BIRIJION"), Speed(350), ROT_TYPE.NEAR)
  -- CH("BIRIJION"):WaitRotate()
  -- CH("BIRIJION"):WalkTo(SplinePath(SymPos("VIA01_BIRIJION"), SymPos("VIA02_BIRIJION"), SymPos("P01_BIRIJION")), Speed(1.5))
  -- CH("BIRIJION"):WaitMove()
  -- CH("BIRIJION"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  -- CH("BIRIJION"):WaitRotate()
  -- WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  -- WINDOW:DrawFaceOffset(-15, 0)
  -- WINDOW:SwitchTalk({PARTNER_0 = 1594449632, PARTNER_1 = 913801932})
  -- WINDOW:CloseMessage()
  -- SOUND:FadeOutBgm(TimeSec(2.5))
  -- CAMERA:SetEye(SymCam("CAMERA_04"))
  -- CAMERA:SetTgt(SymCam("CAMERA_04"))
  -- TASK:Sleep(TimeSec(0.5))
  -- EFFECT:Create("effectGatebaseOkEnd", SymEff("EV_GATEBASE_OK_END"))
  -- EFFECT:SetPosition("effectGatebaseOkEnd", SymPos("P_EFF_EV_GATEBASE_START"))
  -- SOUND:PlaySe(SymSnd("SE_EVT_WARP"), Volume(256))
  -- TASK:Sleep(TimeSec(5, TIME_TYPE.FRAME))
  -- CH("HERO"):ChangeScale(Scale(0, 4, 0), TimeSec(5, TIME_TYPE.FRAME))
  -- CH("PARTNER"):ChangeScale(Scale(0, 4, 0), TimeSec(5, TIME_TYPE.FRAME))
  -- CH("EMONGA"):ChangeScale(Scale(0, 4, 0), TimeSec(5, TIME_TYPE.FRAME))
  -- CH("BIRIJION"):ChangeScale(Scale(0, 4, 0), TimeSec(5, TIME_TYPE.FRAME))
  -- TASK:Sleep(TimeSec(5, TIME_TYPE.FRAME))
  -- CH("HERO"):SetVisible(false)
  -- CH("PARTNER"):SetVisible(false)
  -- CH("EMONGA"):SetVisible(false)
  -- CH("BIRIJION"):SetVisible(false)
  -- TASK:Sleep(TimeSec(1))
  -- SOUND:FadeOutSe(SymSnd("SE_EVT_MAGNAGATE_LP"), TimeSec(1))
  -- SOUND:PlaySe(SymSnd("SE_EVT_MAGNACIRCLE_BANISH_02"), Volume(256))
  -- TASK:Sleep(TimeSec(5, TIME_TYPE.FRAME))
  -- GM("MAGNAGATE_CIRCLE1"):SetMotion(SymMot("VANISH"), LOOP.OFF)
  -- GM("MAGNAGATE_CIRCLE2"):SetMotion(SymMot("VANISH"), LOOP.OFF)
  -- GM("MAGNAGATE_CIRCLE3"):SetMotion(SymMot("VANISH"), LOOP.OFF)
  -- GM("MAGNAGATE_TUBE"):SetVisible(false)
  -- GM("MAGNAGATE_CIRCLE3"):WaitPlayMotion()
  -- GM("MAGNAGATE_CIRCLE1"):SetVisible(false)
  -- GM("MAGNAGATE_CIRCLE2"):SetVisible(false)
  -- GM("MAGNAGATE_CIRCLE3"):SetVisible(false)
  -- TASK:Sleep(TimeSec(0.3))
  -- SOUND:PlaySe(SymSnd("SE_EVT_MAGNAGATE_CLOSE"), Volume(256))
  -- TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
  -- TASK:Sleep(TimeSec(0.2))
  -- CAMERA:SetShake(Vector2(0.04, 0.04), TimeSec(1, TIME_TYPE.FRAME))
  -- EFFECT:Remove("effectGatebaseOkLp")
  -- EFFECT:Play("effectGatebaseOkEnd")
  -- TASK:Sleep(TimeSec(20, TIME_TYPE.FRAME))
  -- CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  -- TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
  -- GM("MAGNAGATEMARK"):SetVisible(true)
  -- MAP:ReturnLightColor(TimeSec(20, TIME_TYPE.FRAME))
  -- MAP:ChangeProjectionShadowAlpha(1, TimeSec(20, TIME_TYPE.FRAME))
  -- GM("MAGNAGATE"):SetMotion(SymMot("VANISH"), LOOP.OFF)
  -- TASK:Sleep(TimeSec(5, TIME_TYPE.FRAME))
  -- CAMERA:SetShake(Vector2(0.01, 0.01), TimeSec(0.5, TIME_TYPE.FRAME))
  -- GM("MAGNAGATE"):WaitPlayMotion()
  -- GM("MAGNAGATE"):SetVisible(false)
  -- TASK:Sleep(TimeSec(0.5))
  -- CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  -- TASK:Sleep(TimeSec(1))
  -- CH("NOKOTCHI"):WalkTo(SymPos("P01_NOKOTCHI"), Speed(2))
  -- CH("NOKOTCHI"):WaitMove()
  -- CH("NOKOTCHI"):SetManpu("MP_SPREE_LP")
  -- TASK:Regist(subEveDoubleJump, {
  --   CH("NOKOTCHI")
  -- })
  -- WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.SHOUT)
  -- WINDOW:Talk(SymAct("NOKOTCHI"), 795653005)
  -- WINDOW:CloseMessage()
  -- CH("NOKOTCHI"):ResetManpu()
  -- SCREEN_A:FadeOut(TimeSec(1.5), true)
  -- TASK:Sleep(TimeSec(0.5))
  subMapCameraDefMode()
  -- TASK:Sleep(TimeSec(0.2))
  -- if Ground_Save(ground) then
  --   return
  -- end
  subSaveflagM16_070_02()
end
function main16_daihyougahefutatabi02_end()
end
function subSaveflagM16_070_02()
  FLAG.SceneFlag = CONST.FL_SC_01_FIRST
  FLAG.SCENARIOFLAG = CONST.M16_DAIHYOUGAHEFUTATABI_END
  SYSTEM:NextEntry()
end
function groundEnd()
end

