function sub02_meroetta()
  SYSTEM:DebugPrint("---------------------------MEROETTA_EVENT_MAIN")
  SYSTEM:DebugPrint("---------------------------MeroettaCounter ... " .. FLAG.MeroettaCounter:getDebugValueName())
  SYSTEM:DebugPrint("---------------------------ParaMusicParadiseBuild ... " .. FLAG.ParaMusicParadiseBuild:getDebugValueName())
  SYSTEM:DebugPrint("---------------------------StoryPlayerMode ... " .. FLAG.StoryPlayerMode:getDebugValueName())
  if FLAG.MeroettaCounter == CONST.CNT_1 then
    SYSTEM:DebugPrint("---------------------------MEROETTA_EVENT_1")
    subFreePlayReachCommonAll()
    SOUND:VolumeBgm(Volume(64), TimeSec(0.5))
    CAMERA:MoveFollowZoom(CH("MEROETTA_VOICE"), Height(0.3), Distance(7), TimeSec(0.3), ACCEL_TYPE.NONE, DECEL_TYPE.HIGH)
    local result = subUseParadiseMeroettaTalkIn(CH("MEROETTA_VOICE"))
    CAMERA:WaitMove()
    EFFECT:Create("effectOnpu", SymEff("BL_VOICE_PINK_LP"))
    EFFECT:SetPosition("effectOnpu", CH("MEROETTA_VOICE"), BODY_POINT.HEAD)
    EFFECT:Play("effectOnpu")
    SOUND:PlaySe(SymSnd("SE_EF_WEATHER_SUN"), Volume(128))
    CH("MEROETTA_VOICE"):SetMotion(SymMot("ROUND"), LOOP.OFF)
    CH("MEROETTA_VOICE"):SetNextMotion(SymMot("ROUND"), LOOP.OFF, TimeSec(0.2))
    CH("MEROETTA_VOICE"):SetFacialMotion(FACIAL_MOTION.HAPPY)
    WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.HAPPY)
    WINDOW:Talk(SymAct("???"), -262668083)
    CH("MEROETTA_VOICE"):WaitPlayMotion()
    CH("MEROETTA_VOICE"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.2))
    WINDOW:KeyWait()
    CH("MEROETTA_VOICE"):SetFacialMotion(FACIAL_MOTION.HAPPY)
    EFFECT:Remove("effectOnpu")
    TASK:Regist(subEveDoubleJump, {
      CH("MEROETTA_VOICE")
    })
    WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.EMOTION)
    WINDOW:Talk(SymAct("???"), -381472372)
    subEveCloseMsg()
    CH("MEROETTA_VOICE"):DirTo(RotateTarget(-45), Speed(350))
    CH("MEROETTA_VOICE"):WaitRotate()
    SOUND:PlaySe(SymSnd("SE_EVT_DEDEEN"), Volume(256))
    CH("MEROETTA_VOICE"):SetManpu("MP_EXCLAMATION")
    CH("MEROETTA_VOICE"):SetFacialMotion(FACIAL_MOTION.NORMAL)
    CH("MEROETTA_VOICE"):SetMotion(SymMot("SPECIAL"), LOOP.OFF, TimeSec(0.2))
    WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.SAD)
    WINDOW:Talk(SymAct("???"), -1032953265)
    CH("MEROETTA_VOICE"):WaitPlayMotion()
    WINDOW:KeyWait()
    CH("MEROETTA_VOICE"):DirTo(RotateTarget(45), Speed(350))
    CH("MEROETTA_VOICE"):WaitRotate()
    CH("MEROETTA_VOICE"):SetMotion(SymMot("CHARGE"), LOOP.OFF, TimeSec(0.2))
    WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.SURPRISE)
    WINDOW:Talk(SymAct("???"), -613068018)
    CH("MEROETTA_VOICE"):WaitPlayMotion()
    WINDOW:KeyWait()
    TASK:Regist(subEveDoubleJump, {
      CH("MEROETTA_VOICE")
    })
    WINDOW:Talk(SymAct("???"), -1808480823)
    TASK:WaitTask()
    WINDOW:KeyWait()
    CH("MEROETTA_VOICE"):SetMotion(SymMot("SLEEP"), LOOP.OFF, TimeSec(0.1))
    WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.SAD)
    WINDOW:Talk(SymAct("???"), -1926237048)
    CH("MEROETTA_VOICE"):WaitPlayMotion()
    CH("MEROETTA_VOICE"):SetMotion(SymMot("SLEEPLOOP"), LOOP.ON)
    WINDOW:KeyWait()
    SOUND:PlaySe(SymSnd("ME_EVOLUTION"), Volume(256))
    CH("MEROETTA_VOICE"):SetManpu("MP_SPREE_LP")
    CH("MEROETTA_VOICE"):SetMotion(SymMot("VICTORY"), LOOP.OFF, TimeSec(0.3))
    WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.EMOTION)
    WINDOW:Talk(SymAct("???"), -1509775541)
    CH("MEROETTA_VOICE"):WaitPlayMotion()
    TASK:Sleep(TimeSec(0.5))
    subEveCloseMsg()
    CH("MEROETTA_VOICE"):ResetManpu()
    CH("MEROETTA_VOICE"):DirTo(RotateTarget(-45), Speed(350))
    CH("MEROETTA_VOICE"):WaitRotate()
    CH("MEROETTA_VOICE"):SetMotion(SymMot("WAIT02"), LOOP.OFF, TimeSec(0.3))
    TASK:Sleep(TimeSec(0.3))
    WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.EMOTION)
    WINDOW:Talk(SymAct("???"), -1088842230)
    SOUND:PlaySe(SymSnd("ME_EVT_DAN_01"), Volume(256))
    WINDOW:KeyWait()
    CH("MEROETTA_VOICE"):DirTo(RotateTarget(45), Speed(350))
    CH("MEROETTA_VOICE"):WaitRotate()
    CH("MEROETTA_VOICE"):SetMotion(SymMot("FALL"), LOOP.OFF, TimeSec(0.3))
    TASK:Regist(subEveJump, {
      CH("MEROETTA_VOICE")
    })
    WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.PAIN)
    WINDOW:Talk(SymAct("???"), 948013765)
    SOUND:PlaySe(SymSnd("ME_EVT_DAN_02"), Volume(256))
    CH("MEROETTA_VOICE"):WaitPlayMotion()
    WINDOW:KeyWait()
    CH("MEROETTA_VOICE"):SetMotion(SymMot("LETSGO"), LOOP.OFF, TimeSec(0.2))
    TASK:Regist(subEveJump, {
      CH("MEROETTA_VOICE")
    })
    WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.EMOTION)
    WINDOW:Talk(SymAct("???"), 563788676)
    SOUND:PlaySe(SymSnd("ME_EVT_TA_DAH"), Volume(256))
    CH("MEROETTA_VOICE"):WaitPlayMotion()
    WINDOW:KeyWait()
    CH("MEROETTA_VOICE"):DirTo(RotateTarget(0), Speed(350))
    CH("MEROETTA_VOICE"):WaitRotate()
    CH("MEROETTA_VOICE"):SetMotion(SymMot("VICTORY"), LOOP.OFF, TimeSec(0.2))
    WINDOW:Talk(SymAct("???"), 1484200498)
    CH("MEROETTA_VOICE"):WaitPlayMotion()
    CH("MEROETTA_VOICE"):SetManpu("MP_SPREE_LP")
    WINDOW:KeyWait()
    TASK:Regist(subEveDoubleJump, {
      CH("MEROETTA_VOICE")
    })
    WINDOW:Talk(SymAct("???"), 1097608051)
    TASK:WaitTask()
    subEveCloseMsg()
    CH("MEROETTA_VOICE"):ResetManpu()
    CH("MEROETTA_VOICE"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.2))
    CH("MEROETTA_VOICE"):DirTo(CH("PLAYER"), Speed(350))
    CH("MEROETTA_VOICE"):WaitRotate()
    WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("???"), 1782675632)
    do
      local __LB_SCOPE = function()
        local __scopeFuncTbl = {}
        function __scopeFuncTbl.__LB_FIRST()
        end
        function __scopeFuncTbl.CELECT_EVENT01()
          local __labelCnt = 0
          local __labelTbl = {}
          WINDOW:SelectStart()
          WINDOW:SelectChain(1935297009, __labelCnt)
          WINDOW:DefaultCursor(__labelCnt)
          __labelTbl[__labelCnt] = __scopeFuncTbl.LABEL_YES
          __labelCnt = __labelCnt + 1
          WINDOW:SelectChain(1008459574, __labelCnt)
          __labelTbl[__labelCnt] = __scopeFuncTbl.LABEL_NO
          __labelCnt = __labelCnt + 1
          local __res = WINDOW:SelectEndTalk(MENU_SELECT_MODE.DISABLE_CANCEL)
          return __labelTbl[__res]
        end
        function __scopeFuncTbl.LABEL_NO()
          subEveCloseMsg()
          SOUND:PlaySe(SymSnd("ME_GAMEOVER"), Volume(256))
          CH("MEROETTA_VOICE"):SetNeckRot(RotateTarget(0), RotateTarget(-20), RotateTarget(0), TimeSec(0.35))
          CH("MEROETTA_VOICE"):WaitNeckRot()
          WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.SAD)
          WINDOW:Talk(SymAct("???"), 620818039)
          TASK:Sleep(TimeSec(1))
          subEveCloseMsg()
          CH("MEROETTA_VOICE"):ResetNeckRot(TimeSec(0.2))
          CH("MEROETTA_VOICE"):WaitNeckRot()
          CH("MEROETTA_VOICE"):DirTo(RotateOffs(45), Speed(350))
          CH("MEROETTA_VOICE"):WaitRotate()
          TASK:Regist(subEveDoubleJump, {
            CH("MEROETTA_VOICE")
          })
          WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.EMOTION)
          WINDOW:Talk(SymAct("???"), 237878708)
          WINDOW:Talk(SymAct("???"), 389450997)
          TASK:WaitTask()
          subEveCloseMsg()
          CH("MEROETTA_VOICE"):DirTo(CH("PLAYER"), Speed(350))
          CH("MEROETTA_VOICE"):WaitRotate()
          WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.NORMAL)
          WINDOW:Talk(SymAct("???"), -1867608006)
          WINDOW:Talk(SymAct("???"), -1984585349)
          WINDOW:CloseMessage()
          SOUND:VolumeBgm(Volume(256), TimeSec(0.5))
          CAMERA:MoveToPlayer(TimeSec(0.3), ACCEL_TYPE.NONE, DECEL_TYPE.HIGH)
          CAMERA:WaitMove()
          FLAG.MeroettaCounter = CONST.CNT_2
          return __scopeFuncTbl.LABEL_END
        end
        function __scopeFuncTbl.LABEL_YES()
          subEveCloseMsg()
          CH("MEROETTA_VOICE"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
          CH("MEROETTA_VOICE"):WaitRotate()
          SOUND:PlaySe(SymSnd("ME_EVT_V_FANFARE"), Volume(256))
          CH("MEROETTA_VOICE"):SetManpu("MP_SPREE_LP")
          CH("MEROETTA_VOICE"):SetMotion(SymMot("ROUND"), LOOP.OFF)
          CH("MEROETTA_VOICE"):SetFacialMotion(FACIAL_MOTION.HAPPY)
          WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.HAPPY)
          WINDOW:Talk(SymAct("???"), 1254274524)
          CH("MEROETTA_VOICE"):WaitPlayMotion()
          CH("MEROETTA_VOICE"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
          CH("MEROETTA_VOICE"):WaitPlayMotion()
          subEveCloseMsg()
          CH("MEROETTA_VOICE"):SetFacialMotion(FACIAL_MOTION.NORMAL)
          CH("MEROETTA_VOICE"):ResetManpu()
          CH("MEROETTA_VOICE"):DirTo(CH("PLAYER"), Speed(350))
          CH("MEROETTA_VOICE"):WaitRotate()
          WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.EMOTION)
          WINDOW:Talk(SymAct("???"), 1406764189)
          subEveCloseMsg()
          WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.NORMAL)
          WINDOW:Talk(SymAct("MEROETTA_VOICE"), 2029311838)
          WINDOW:KeyWait()
          CH("MEROETTA_VOICE"):SetFacialMotion(FACIAL_MOTION.HAPPY)
          WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.HAPPY)
          WINDOW:Talk(SymAct("MEROETTA_VOICE"), 1643111967)
          WINDOW:KeyWait()
          CH("MEROETTA_VOICE"):SetFacialMotion(FACIAL_MOTION.NORMAL)
          WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.NORMAL)
          WINDOW:Talk(SymAct("MEROETTA_VOICE"), 783184088)
          WINDOW:Talk(SymAct("MEROETTA_VOICE"), 934625689)
          WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.SAD)
          WINDOW:Talk(SymAct("MEROETTA_VOICE"), 479728218)
          WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.NORMAL)
          WINDOW:Talk(SymAct("MEROETTA_VOICE"), 92480283)
          subEveCloseMsg()
          CH("MEROETTA_VOICE"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
          CH("MEROETTA_VOICE"):WaitRotate()
          CH("MEROETTA_STEP"):SetDir(RotateTarget(0))
          CH("MEROETTA_VOICE"):SetMotion(SymMot("ROUND"), LOOP.OFF)
          CH("MEROETTA_VOICE"):SetManpu("MP_SPREE_LP")
          CH("MEROETTA_VOICE"):SetNextMotion(SymMot("LETSGO"), LOOP.OFF, TimeSec(0.2))
          CH("MEROETTA_VOICE"):WaitPlayMotion()
          WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.EMOTION)
          WINDOW:Talk(SymAct("MEROETTA_VOICE"), -2112143404)
          CH("MEROETTA_VOICE"):ResetManpu()
          WINDOW:KeyWait()
          EFFECT:Create("effectOnpu", SymEff("BL_VOICE_PINK_LP"))
          EFFECT:SetPosition("effectOnpu", CH("MEROETTA_VOICE"), BODY_POINT.HEAD)
          EFFECT:Play("effectOnpu")
          SOUND:PlaySe(SymSnd("SE_EF_WEATHER_SUN"), Volume(128))
          WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.EMOTION)
          WINDOW:Talk(SymAct("MEROETTA_VOICE"), -1694495083)
          WINDOW:Talk(SymAct("MEROETTA_VOICE"), -226569543)
          WINDOW:CloseMessage()
          CH("MEROETTA_VOICE"):SetMotion(SymMot("ROUND"), LOOP.OFF)
          TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
          EFFECT:Remove("effectOnpu")
          EFFECT:Create("effectSmokeShortWhite", SymEff("NM_SMOKE_SHORT_WHITE"))
          EFFECT:SetPosition("effectSmokeShortWhite", CH("MEROETTA_VOICE"), BODY_POINT.CENTER)
          EFFECT:Play("effectSmokeShortWhite")
          SOUND:PlaySe(SymSnd("SE_EVT_BUNI"), Volume(256))
          TASK:Sleep(TimeSec(0.1))
          CH("MEROETTA_VOICE"):SetVisible(false)
          CH("MEROETTA_STEP"):SetVisible(true)
          CH("MEROETTA_STEP"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
          CH("MEROETTA_STEP"):WaitPlayMotion()
          WINDOW:DrawFace(324, 88, SymAct("MEROETTA_STEP"), FACE_TYPE.NORMAL)
          WINDOW:Talk(SymAct("MEROETTA_STEP"), -345644040)
          subEveCloseMsg()
          CH("MEROETTA_STEP"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.2))
          CH("MEROETTA_STEP"):DirTo(CH("PLAYER"), Speed(350), ROT_TYPE.NEAR)
          CH("MEROETTA_STEP"):WaitRotate()
          WINDOW:DrawFace(324, 88, SymAct("MEROETTA_STEP"), FACE_TYPE.NORMAL)
          WINDOW:Talk(SymAct("MEROETTA_STEP"), -1068978117)
          WINDOW:KeyWait()
          CH("MEROETTA_VOICE"):SetMotion(SymMot("ROUND"), LOOP.OFF)
          CH("MEROETTA_VOICE"):SetNextMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.2))
          WINDOW:Talk(SymAct("MEROETTA_STEP"), -648838790)
          WINDOW:Talk(SymAct("MEROETTA_STEP"), -1777199171)
          WINDOW:Talk(SymAct("MEROETTA_STEP"), -1895225604)
          subEveCloseMsg()
          CH("MEROETTA_STEP"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
          CH("MEROETTA_STEP"):WaitRotate()
          CH("MEROETTA_STEP"):SetMotion(SymMot("VICTORY"), LOOP.OFF)
          WINDOW:Talk(SymAct("MEROETTA_STEP"), -1541114561)
          CH("MEROETTA_STEP"):WaitPlayMotion()
          CH("MEROETTA_STEP"):SetManpu("MP_SPREE_LP")
          subEveCloseMsg()
          CH("MEROETTA_STEP"):ResetManpu()
          SCREEN_A:FadeOutAll(TimeSec(0.3), false)
          SCREEN_B:FadeOutAll(TimeSec(0.3), true)
          TASK:Sleep(TimeSec(0))
          SOUND:PlayMe(SymSnd("ME_INFORMATION"), Volume(256))
          SCREEN_A:FadeInAll(TimeSec(0.3), false)
          SCREEN_B:FadeInAll(TimeSec(0.3), false)
          ShopSys:DispMeroettaMaterialMenu(-891426040, function()
          end, function()
          end)
          LOWER_SCREEN:SetCaptionAndPadHelpVisible(false)
          CH("MEROETTA_STEP"):SetMotion(SymMot("WAIT02"), LOOP.ON)
          CH("MEROETTA_STEP"):DirTo(CH("PLAYER"), Speed(350), ROT_TYPE.NEAR)
          CH("MEROETTA_STEP"):WaitRotate()
          WINDOW:DrawFace(324, 88, SymAct("MEROETTA_STEP"), FACE_TYPE.NORMAL)
          WINDOW:Talk(SymAct("MEROETTA_STEP"), -1119927170)
          WINDOW:Talk(SymAct("MEROETTA_STEP"), 984045745)
          WINDOW:Talk(SymAct("MEROETTA_STEP"), 599550448)
          WINDOW:CloseMessage()
          CH("MEROETTA_STEP"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
          CH("MEROETTA_STEP"):WaitRotate()
          CH("MEROETTA_VOICE"):SetDir(RotateTarget(0))
          EFFECT:Create("effectOnpu", SymEff("BL_VOICE_PINK_LP"))
          EFFECT:SetPosition("effectOnpu", CH("MEROETTA_STEP"), BODY_POINT.HEAD)
          EFFECT:Play("effectOnpu")
          SOUND:PlaySe(SymSnd("SE_EF_WEATHER_SUN"), Volume(128))
          WINDOW:Talk(SymAct("MEROETTA_STEP"), 1873406464)
          WINDOW:CloseMessage()
          CH("MEROETTA_STEP"):SetMotion(SymMot("ROUND"), LOOP.OFF)
          TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
          EFFECT:Remove("effectOnpu")
          EFFECT:Create("effectSmokeShortWhite02", SymEff("NM_SMOKE_SHORT_WHITE"))
          EFFECT:SetPosition("effectSmokeShortWhite02", CH("MEROETTA_STEP"), BODY_POINT.CENTER)
          EFFECT:Play("effectSmokeShortWhite02")
          SOUND:PlaySe(SymSnd("SE_EVT_BUNI"), Volume(256))
          TASK:Sleep(TimeSec(0.1))
          CH("MEROETTA_STEP"):SetVisible(false)
          CH("MEROETTA_VOICE"):SetVisible(true)
          CH("MEROETTA_VOICE"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
          CH("MEROETTA_VOICE"):WaitPlayMotion()
          CH("MEROETTA_VOICE"):SetFacialMotion(FACIAL_MOTION.HAPPY)
          WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.HAPPY)
          WINDOW:Talk(SymAct("MEROETTA_VOICE"), 1991433025)
          subEveCloseMsg()
          CH("MEROETTA_VOICE"):SetFacialMotion(FACIAL_MOTION.NORMAL)
          CH("MEROETTA_VOICE"):SetMotion(SymMot("WAIT02"), LOOP.ON)
          CH("MEROETTA_VOICE"):DirTo(CH("PLAYER"), Speed(350), ROT_TYPE.NEAR)
          CH("MEROETTA_VOICE"):WaitRotate()
          WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.NORMAL)
          WINDOW:Talk(SymAct("MEROETTA_VOICE"), 1570736258)
          WINDOW:KeyWait()
          TASK:Regist(subEveDoubleJump, {
            CH("MEROETTA_VOICE")
          })
          WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.EMOTION)
          WINDOW:Talk(SymAct("MEROETTA_VOICE"), 1149548995)
          WINDOW:Talk(SymAct("MEROETTA_VOICE"), 197472004)
          TASK:WaitTask()
          WINDOW:CloseMessage()
          SOUND:VolumeBgm(Volume(256), TimeSec(0.5))
          CAMERA:MoveToPlayer(TimeSec(0.3), ACCEL_TYPE.NONE, DECEL_TYPE.HIGH)
          CAMERA:WaitMove()
          FLAG.MeroettaCounter = CONST.CNT_3
        end
        function __scopeFuncTbl.LABEL_END()
        end
        local __next = __scopeFuncTbl.CELECT_EVENT01
        while __next ~= nil do
          __next = __next()
        end
      end
      __LB_SCOPE()
    end
    subUseParadiseMeroettaTalkOut(CH("MEROETTA_VOICE"), result)
  elseif FLAG.MeroettaCounter == CONST.CNT_2 then
    SYSTEM:DebugPrint("---------------------------MEROETTA_EVENT_1_2")
    subFreePlayReachCommonAll()
    SOUND:VolumeBgm(Volume(64), TimeSec(0.5))
    CAMERA:MoveFollowZoom(CH("MEROETTA_VOICE"), Height(0.3), Distance(7), TimeSec(0.3), ACCEL_TYPE.NONE, DECEL_TYPE.HIGH)
    local result = subUseParadiseMeroettaTalkIn(CH("MEROETTA_VOICE"))
    CAMERA:WaitMove()
    EFFECT:Create("effectOnpu", SymEff("BL_VOICE_PINK_LP"))
    EFFECT:SetPosition("effectOnpu", CH("MEROETTA_VOICE"), BODY_POINT.HEAD)
    EFFECT:Play("effectOnpu")
    SOUND:PlaySe(SymSnd("SE_EF_WEATHER_SUN"), Volume(128))
    WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.EMOTION)
    WINDOW:Talk(SymAct("???"), 316546629)
    WINDOW:KeyWait()
    EFFECT:Remove("effectOnpu")
    WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("???"), 972246406)
    WINDOW:Talk(SymAct("???"), 552107207)
    do
      local __LB_SCOPE = function()
        local __scopeFuncTbl = {}
        function __scopeFuncTbl.__LB_FIRST()
        end
        function __scopeFuncTbl.CELECT_EVENT02()
          local __labelCnt = 0
          local __labelTbl = {}
          WINDOW:SelectStart()
          WINDOW:SelectChain(-1485807608, __labelCnt)
          WINDOW:DefaultCursor(__labelCnt)
          __labelTbl[__labelCnt] = __scopeFuncTbl.LABEL_YES
          __labelCnt = __labelCnt + 1
          WINDOW:SelectChain(-1100263095, __labelCnt)
          __labelTbl[__labelCnt] = __scopeFuncTbl.LABEL_NO
          __labelCnt = __labelCnt + 1
          local __res = WINDOW:SelectEndTalk(MENU_SELECT_MODE.DISABLE_CANCEL)
          return __labelTbl[__res]
        end
        function __scopeFuncTbl.LABEL_NO()
          subEveCloseMsg()
          SOUND:PlaySe(SymSnd("ME_GAMEOVER"), Volume(256))
          CH("MEROETTA_VOICE"):SetNeckRot(RotateTarget(0), RotateTarget(-20), RotateTarget(0), TimeSec(0.35))
          CH("MEROETTA_VOICE"):WaitNeckRot()
          WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.SAD)
          WINDOW:Talk(SymAct("???"), -686453403)
          TASK:Sleep(TimeSec(1))
          subEveCloseMsg()
          CH("MEROETTA_VOICE"):ResetNeckRot(TimeSec(0.2))
          CH("MEROETTA_VOICE"):WaitNeckRot()
          CH("MEROETTA_VOICE"):DirTo(RotateOffs(45), Speed(350))
          CH("MEROETTA_VOICE"):WaitRotate()
          TASK:Regist(subEveDoubleJump, {
            CH("MEROETTA_VOICE")
          })
          WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.EMOTION)
          WINDOW:Talk(SymAct("???"), -837895132)
          WINDOW:Talk(SymAct("???"), -450629657)
          TASK:WaitTask()
          subEveCloseMsg()
          CH("MEROETTA_VOICE"):DirTo(CH("PLAYER"), Speed(350))
          CH("MEROETTA_VOICE"):WaitRotate()
          WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.NORMAL)
          WINDOW:Talk(SymAct("???"), -63381850)
          WINDOW:Talk(SymAct("???"), -1283897247)
          WINDOW:CloseMessage()
          SOUND:VolumeBgm(Volume(256), TimeSec(0.5))
          CAMERA:MoveToPlayer(TimeSec(0.3), ACCEL_TYPE.NONE, DECEL_TYPE.HIGH)
          CAMERA:WaitMove()
          FLAG.MeroettaCounter = CONST.CNT_2
          return __scopeFuncTbl.LABEL_END
        end
        function __scopeFuncTbl.LABEL_YES()
          subEveCloseMsg()
          CH("MEROETTA_VOICE"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
          CH("MEROETTA_VOICE"):WaitRotate()
          SOUND:PlaySe(SymSnd("ME_EVT_V_FANFARE"), Volume(256))
          CH("MEROETTA_VOICE"):SetManpu("MP_SPREE_LP")
          CH("MEROETTA_VOICE"):SetMotion(SymMot("ROUND"), LOOP.OFF)
          CH("MEROETTA_VOICE"):SetFacialMotion(FACIAL_MOTION.HAPPY)
          WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.HAPPY)
          WINDOW:Talk(SymAct("???"), -1436387040)
          CH("MEROETTA_VOICE"):WaitPlayMotion()
          CH("MEROETTA_VOICE"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
          CH("MEROETTA_VOICE"):WaitPlayMotion()
          subEveCloseMsg()
          CH("MEROETTA_VOICE"):SetFacialMotion(FACIAL_MOTION.NORMAL)
          CH("MEROETTA_VOICE"):ResetManpu()
          CH("MEROETTA_VOICE"):DirTo(CH("PLAYER"), Speed(350))
          CH("MEROETTA_VOICE"):WaitRotate()
          WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.EMOTION)
          WINDOW:Talk(SymAct("???"), -2125518109)
          subEveCloseMsg()
          WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.NORMAL)
          WINDOW:Talk(SymAct("MEROETTA_VOICE"), -1739318366)
          WINDOW:KeyWait()
          CH("MEROETTA_VOICE"):SetFacialMotion(FACIAL_MOTION.HAPPY)
          WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.HAPPY)
          WINDOW:Talk(SymAct("MEROETTA_VOICE"), 533464941)
          WINDOW:KeyWait()
          CH("MEROETTA_VOICE"):SetFacialMotion(FACIAL_MOTION.NORMAL)
          WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.NORMAL)
          WINDOW:Talk(SymAct("MEROETTA_VOICE"), 114767404)
          WINDOW:Talk(SymAct("MEROETTA_VOICE"), -979361141)
          WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.SAD)
          WINDOW:Talk(SymAct("MEROETTA_VOICE"), -591719478)
          WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.NORMAL)
          WINDOW:Talk(SymAct("MEROETTA_VOICE"), -141148151)
          subEveCloseMsg()
          CH("MEROETTA_VOICE"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
          CH("MEROETTA_VOICE"):WaitRotate()
          CH("MEROETTA_STEP"):SetDir(RotateTarget(0))
          CH("MEROETTA_VOICE"):SetMotion(SymMot("ROUND"), LOOP.OFF)
          CH("MEROETTA_VOICE"):SetManpu("MP_SPREE_LP")
          CH("MEROETTA_VOICE"):SetNextMotion(SymMot("LETSGO"), LOOP.OFF, TimeSec(0.2))
          CH("MEROETTA_VOICE"):WaitPlayMotion()
          WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.EMOTION)
          WINDOW:Talk(SymAct("MEROETTA_VOICE"), -292720312)
          CH("MEROETTA_VOICE"):ResetManpu()
          WINDOW:KeyWait()
          EFFECT:Create("effectOnpu", SymEff("BL_VOICE_PINK_LP"))
          EFFECT:SetPosition("effectOnpu", CH("MEROETTA_VOICE"), BODY_POINT.HEAD)
          EFFECT:Play("effectOnpu")
          SOUND:PlaySe(SymSnd("SE_EF_WEATHER_SUN"), Volume(128))
          WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.EMOTION)
          WINDOW:Talk(SymAct("MEROETTA_VOICE"), -1580406897)
          WINDOW:Talk(SymAct("MEROETTA_VOICE"), -1193814322)
          WINDOW:CloseMessage()
          CH("MEROETTA_VOICE"):SetMotion(SymMot("ROUND"), LOOP.OFF)
          TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
          EFFECT:Remove("effectOnpu")
          EFFECT:Create("effectSmokeShortWhite", SymEff("NM_SMOKE_SHORT_WHITE"))
          EFFECT:SetPosition("effectSmokeShortWhite", CH("MEROETTA_VOICE"), BODY_POINT.CENTER)
          EFFECT:Play("effectSmokeShortWhite")
          SOUND:PlaySe(SymSnd("SE_EVT_BUNI"), Volume(256))
          TASK:Sleep(TimeSec(0.1))
          CH("MEROETTA_VOICE"):SetVisible(false)
          CH("MEROETTA_STEP"):SetVisible(true)
          CH("MEROETTA_STEP"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
          CH("MEROETTA_STEP"):WaitPlayMotion()
          WINDOW:DrawFace(324, 88, SymAct("MEROETTA_STEP"), FACE_TYPE.NORMAL)
          WINDOW:Talk(SymAct("MEROETTA_STEP"), -1812298483)
          subEveCloseMsg()
          CH("MEROETTA_STEP"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.2))
          CH("MEROETTA_STEP"):DirTo(CH("PLAYER"), Speed(350), ROT_TYPE.NEAR)
          CH("MEROETTA_STEP"):WaitRotate()
          WINDOW:DrawFace(324, 88, SymAct("MEROETTA_STEP"), FACE_TYPE.NORMAL)
          WINDOW:Talk(SymAct("MEROETTA_STEP"), -1964919732)
          WINDOW:KeyWait()
          CH("MEROETTA_VOICE"):SetMotion(SymMot("ROUND"), LOOP.OFF)
          CH("MEROETTA_VOICE"):SetNextMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.2))
          WINDOW:Talk(SymAct("MEROETTA_STEP"), 226076803)
          WINDOW:Talk(SymAct("MEROETTA_STEP"), 342006210)
          WINDOW:Talk(SymAct("MEROETTA_STEP"), 2099004910)
          subEveCloseMsg()
          CH("MEROETTA_STEP"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
          CH("MEROETTA_STEP"):WaitRotate()
          CH("MEROETTA_STEP"):SetMotion(SymMot("VICTORY"), LOOP.OFF)
          WINDOW:Talk(SymAct("MEROETTA_STEP"), 1678210223)
          CH("MEROETTA_STEP"):WaitPlayMotion()
          CH("MEROETTA_STEP"):SetManpu("MP_SPREE_LP")
          subEveCloseMsg()
          CH("MEROETTA_STEP"):ResetManpu()
          SCREEN_A:FadeOutAll(TimeSec(0.3), false)
          SCREEN_B:FadeOutAll(TimeSec(0.3), true)
          TASK:Sleep(TimeSec(0))
          SOUND:PlayMe(SymSnd("ME_INFORMATION"), Volume(256))
          SCREEN_A:FadeInAll(TimeSec(0.3), false)
          SCREEN_B:FadeInAll(TimeSec(0.3), false)
          ShopSys:DispMeroettaMaterialMenu(-891426040, function()
          end, function()
          end)
          LOWER_SCREEN:SetCaptionAndPadHelpVisible(false)
          CH("MEROETTA_STEP"):SetMotion(SymMot("WAIT02"), LOOP.ON)
          CH("MEROETTA_STEP"):DirTo(CH("PLAYER"), Speed(350), ROT_TYPE.NEAR)
          CH("MEROETTA_STEP"):WaitRotate()
          WINDOW:DrawFace(324, 88, SymAct("MEROETTA_STEP"), FACE_TYPE.NORMAL)
          WINDOW:Talk(SymAct("MEROETTA_STEP"), 1328162668)
          WINDOW:Talk(SymAct("MEROETTA_STEP"), 1446057517)
          WINDOW:Talk(SymAct("MEROETTA_STEP"), 426803434)
          WINDOW:CloseMessage()
          CH("MEROETTA_STEP"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
          CH("MEROETTA_STEP"):WaitRotate()
          CH("MEROETTA_VOICE"):SetDir(RotateTarget(0))
          EFFECT:Create("effectOnpu", SymEff("BL_VOICE_PINK_LP"))
          EFFECT:SetPosition("effectOnpu", CH("MEROETTA_STEP"), BODY_POINT.HEAD)
          EFFECT:Play("effectOnpu")
          SOUND:PlaySe(SymSnd("SE_EF_WEATHER_SUN"), Volume(128))
          WINDOW:Talk(SymAct("MEROETTA_STEP"), 7057835)
          WINDOW:CloseMessage()
          CH("MEROETTA_STEP"):SetMotion(SymMot("ROUND"), LOOP.OFF)
          TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
          EFFECT:Remove("effectOnpu")
          EFFECT:Create("effectSmokeShortWhite02", SymEff("NM_SMOKE_SHORT_WHITE"))
          EFFECT:SetPosition("effectSmokeShortWhite02", CH("MEROETTA_STEP"), BODY_POINT.CENTER)
          EFFECT:Play("effectSmokeShortWhite02")
          SOUND:PlaySe(SymSnd("SE_EVT_BUNI"), Volume(256))
          TASK:Sleep(TimeSec(0.1))
          CH("MEROETTA_STEP"):SetVisible(false)
          CH("MEROETTA_VOICE"):SetVisible(true)
          CH("MEROETTA_VOICE"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
          CH("MEROETTA_VOICE"):WaitPlayMotion()
          CH("MEROETTA_VOICE"):SetFacialMotion(FACIAL_MOTION.HAPPY)
          WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.HAPPY)
          WINDOW:Talk(SymAct("MEROETTA_VOICE"), 726065768)
          subEveCloseMsg()
          CH("MEROETTA_VOICE"):SetFacialMotion(FACIAL_MOTION.NORMAL)
          CH("MEROETTA_VOICE"):SetMotion(SymMot("WAIT02"), LOOP.ON)
          CH("MEROETTA_VOICE"):DirTo(CH("PLAYER"), Speed(350), ROT_TYPE.NEAR)
          CH("MEROETTA_VOICE"):WaitRotate()
          WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.NORMAL)
          WINDOW:Talk(SymAct("MEROETTA_VOICE"), 845009705)
          WINDOW:KeyWait()
          TASK:Regist(subEveDoubleJump, {
            CH("MEROETTA_VOICE")
          })
          WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.EMOTION)
          WINDOW:Talk(SymAct("MEROETTA_VOICE"), -1245327386)
          WINDOW:Talk(SymAct("MEROETTA_VOICE"), -1394671961)
          TASK:WaitTask()
          WINDOW:CloseMessage()
          SOUND:VolumeBgm(Volume(256), TimeSec(0.5))
          CAMERA:MoveToPlayer(TimeSec(0.3), ACCEL_TYPE.NONE, DECEL_TYPE.HIGH)
          CAMERA:WaitMove()
          FLAG.MeroettaCounter = CONST.CNT_3
        end
        function __scopeFuncTbl.LABEL_END()
        end
        local __next = __scopeFuncTbl.CELECT_EVENT02
        while __next ~= nil do
          __next = __next()
        end
      end
      __LB_SCOPE()
    end
    subUseParadiseMeroettaTalkOut(CH("MEROETTA_VOICE"), result)
  elseif (FLAG.MeroettaCounter == CONST.CNT_3 or FLAG.MeroettaCounter == CONST.CNT_4) and LUA_SYSTEM:CheckKenzai_MusicParadise() == false and FLAG.ParaMusicParadiseBuild == CONST.FLAG_FALSE then
    SYSTEM:DebugPrint("---------------------------MEROETTA_EVENT_2")
    subFreePlayReachCommonAll()
    SOUND:VolumeBgm(Volume(64), TimeSec(1))
    CAMERA:MoveFollowZoom(CH("MEROETTA_VOICE"), Height(0.3), Distance(7), TimeSec(0.3), ACCEL_TYPE.NONE, DECEL_TYPE.HIGH)
    local result = subUseParadiseMeroettaTalkIn(CH("MEROETTA_VOICE"))
    CAMERA:WaitMove()
    WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("MEROETTA_VOICE"), 629102008)
    WINDOW:Talk(SymAct("MEROETTA_VOICE"), 1013212409)
    WINDOW:CloseMessage()
    CH("MEROETTA_VOICE"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
    CH("MEROETTA_VOICE"):WaitRotate()
    CH("MEROETTA_STEP"):SetDir(RotateTarget(0))
    CH("MEROETTA_VOICE"):SetMotion(SymMot("ROUND"), LOOP.OFF)
    CH("MEROETTA_VOICE"):SetManpu("MP_SPREE_LP")
    CH("MEROETTA_VOICE"):SetNextMotion(SymMot("LETSGO"), LOOP.OFF, TimeSec(0.2))
    CH("MEROETTA_VOICE"):WaitPlayMotion()
    WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("MEROETTA_VOICE"), 390674234)
    CH("MEROETTA_VOICE"):ResetManpu()
    subEveCloseMsg()
    EFFECT:Create("effectOnpu", SymEff("BL_VOICE_PINK_LP"))
    EFFECT:SetPosition("effectOnpu", CH("MEROETTA_VOICE"), BODY_POINT.HEAD)
    EFFECT:Play("effectOnpu")
    SOUND:PlaySe(SymSnd("SE_EF_WEATHER_SUN"), Volume(128))
    WINDOW:Talk(SymAct("MEROETTA_VOICE"), 240256635)
    WINDOW:CloseMessage()
    CH("MEROETTA_VOICE"):SetMotion(SymMot("ROUND"), LOOP.OFF)
    TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
    EFFECT:Remove("effectOnpu")
    EFFECT:Create("effectSmokeShortWhite", SymEff("NM_SMOKE_SHORT_WHITE"))
    EFFECT:SetPosition("effectSmokeShortWhite", CH("MEROETTA_VOICE"), BODY_POINT.CENTER)
    EFFECT:Play("effectSmokeShortWhite")
    SOUND:PlaySe(SymSnd("SE_EVT_BUNI"), Volume(256))
    TASK:Sleep(TimeSec(0.1))
    CH("MEROETTA_VOICE"):SetVisible(false)
    CH("MEROETTA_STEP"):SetVisible(true)
    CH("MEROETTA_STEP"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
    CH("MEROETTA_STEP"):WaitPlayMotion()
    SCREEN_A:FadeOutAll(TimeSec(0.3), false)
    SCREEN_B:FadeOutAll(TimeSec(0.3), true)
    TASK:Sleep(TimeSec(0))
    SOUND:PlayMe(SymSnd("ME_INFORMATION"), Volume(256))
    SCREEN_A:FadeInAll(TimeSec(0.3), false)
    SCREEN_B:FadeInAll(TimeSec(0.3), false)
    ShopSys:DispMeroettaMaterialMenu(-891426040, function()
    end, function()
    end)
    LOWER_SCREEN:SetCaptionAndPadHelpVisible(false)
    CH("MEROETTA_STEP"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    CH("MEROETTA_STEP"):DirTo(CH("PLAYER"), Speed(350), ROT_TYPE.NEAR)
    CH("MEROETTA_STEP"):WaitRotate()
    WINDOW:DrawFace(324, 88, SymAct("MEROETTA_STEP"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("MEROETTA_STEP"), 1091801276)
    WINDOW:Talk(SymAct("MEROETTA_STEP"), 1476960765)
    WINDOW:CloseMessage()
    CH("MEROETTA_STEP"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
    CH("MEROETTA_STEP"):WaitRotate()
    CH("MEROETTA_VOICE"):SetDir(RotateTarget(0))
    EFFECT:Create("effectOnpu", SymEff("BL_VOICE_PINK_LP"))
    EFFECT:SetPosition("effectOnpu", CH("MEROETTA_STEP"), BODY_POINT.HEAD)
    EFFECT:Play("effectOnpu")
    SOUND:PlaySe(SymSnd("SE_EF_WEATHER_SUN"), Volume(128))
    WINDOW:Talk(SymAct("MEROETTA_STEP"), 1931866686)
    WINDOW:CloseMessage()
    CH("MEROETTA_STEP"):SetMotion(SymMot("ROUND"), LOOP.OFF)
    TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
    EFFECT:Remove("effectOnpu")
    EFFECT:Create("effectSmokeShortWhite02", SymEff("NM_SMOKE_SHORT_WHITE"))
    EFFECT:SetPosition("effectSmokeShortWhite02", CH("MEROETTA_STEP"), BODY_POINT.CENTER)
    EFFECT:Play("effectSmokeShortWhite02")
    SOUND:PlaySe(SymSnd("SE_EVT_BUNI"), Volume(256))
    TASK:Sleep(TimeSec(0.1))
    CH("MEROETTA_STEP"):SetVisible(false)
    CH("MEROETTA_VOICE"):SetVisible(true)
    CH("MEROETTA_VOICE"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
    CH("MEROETTA_VOICE"):WaitPlayMotion()
    WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.EMOTION)
    WINDOW:Talk(SymAct("MEROETTA_VOICE"), 1782498175)
    WINDOW:Talk(SymAct("MEROETTA_VOICE"), -307830864)
    WINDOW:CloseMessage()
    SOUND:VolumeBgm(Volume(256), TimeSec(0.5))
    CAMERA:MoveToPlayer(TimeSec(0.3), ACCEL_TYPE.NONE, DECEL_TYPE.HIGH)
    CAMERA:WaitMove()
    subUseParadiseMeroettaTalkOut(CH("MEROETTA_VOICE"), result)
  elseif FLAG.MeroettaCounter == CONST.CNT_3 and LUA_SYSTEM:CheckKenzai_MusicParadise() == true and GROUND__2:JukeboxIsBuildPlace() == true and FLAG.ParaMusicParadiseBuild == CONST.FLAG_FALSE then
    SYSTEM:DebugPrint("---------------------------MEROETTA_EVENT_3")
    subFreePlayReachCommonAll()
    SOUND:VolumeBgm(Volume(0), TimeSec(1))
    CAMERA:MoveFollowZoom(CH("MEROETTA_VOICE"), Height(0.3), Distance(7), TimeSec(0.3), ACCEL_TYPE.NONE, DECEL_TYPE.HIGH)
    local result = subUseParadiseMeroettaTalkIn(CH("MEROETTA_VOICE"))
    CAMERA:WaitMove()
    SOUND:PlaySe(SymSnd("ME_EVT_DAN_01"), Volume(256))
    CH("MEROETTA_VOICE"):SetManpu("MP_EXCLAMATION")
    CH("MEROETTA_VOICE"):WaitManpu()
    WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.EMOTION)
    WINDOW:Talk(SymAct("MEROETTA_VOICE"), -188879119)
    WINDOW:CloseMessage()
    CH("MEROETTA_VOICE"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
    CH("MEROETTA_VOICE"):WaitRotate()
    CH("MEROETTA_STEP"):SetDir(RotateTarget(0))
    CH("MEROETTA_VOICE"):SetMotion(SymMot("ROUND"), LOOP.OFF)
    TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
    EFFECT:Create("effectSmokeShortWhite", SymEff("NM_SMOKE_SHORT_WHITE"))
    EFFECT:SetPosition("effectSmokeShortWhite", CH("MEROETTA_VOICE"), BODY_POINT.CENTER)
    EFFECT:Play("effectSmokeShortWhite")
    SOUND:PlaySe(SymSnd("ME_EVT_DAN_02"), Volume(256))
    TASK:Sleep(TimeSec(0.1))
    CH("MEROETTA_VOICE"):SetVisible(false)
    CH("MEROETTA_STEP"):SetVisible(true)
    CH("MEROETTA_STEP"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
    CH("MEROETTA_STEP"):WaitPlayMotion()
    WINDOW:DrawFace(324, 88, SymAct("MEROETTA_STEP"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("MEROETTA_STEP"), -1648151843)
    WINDOW:CloseMessage()
    CH("MEROETTA_STEP"):SetMotion(SymMot("ROUND"), LOOP.OFF)
    TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
    EFFECT:Create("effectSmokeShortWhite02", SymEff("NM_SMOKE_SHORT_WHITE"))
    EFFECT:SetPosition("effectSmokeShortWhite02", CH("MEROETTA_STEP"), BODY_POINT.CENTER)
    EFFECT:Play("effectSmokeShortWhite02")
    SOUND:PlaySe(SymSnd("ME_EVT_TA_DAH"), Volume(256))
    TASK:Sleep(TimeSec(0.1))
    CH("MEROETTA_STEP"):SetVisible(false)
    CH("MEROETTA_VOICE"):SetVisible(true)
    CH("MEROETTA_VOICE"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
    CH("MEROETTA_VOICE"):WaitPlayMotion()
    CH("MEROETTA_VOICE"):SetManpu("MP_SPREE_LP")
    WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.EMOTION)
    WINDOW:Talk(SymAct("MEROETTA_VOICE"), -2066218084)
    subEveCloseMsg()
    CH("MEROETTA_VOICE"):ResetManpu()
    CH("MEROETTA_VOICE"):DirTo(CH("PLAYER"), Speed(350), ROT_TYPE.NEAR)
    CH("MEROETTA_VOICE"):WaitRotate()
    TASK:Regist(subEveDoubleJump, {
      CH("MEROETTA_VOICE")
    })
    CH("MEROETTA_VOICE"):SetFacialMotion(FACIAL_MOTION.HAPPY)
    WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.HAPPY)
    WINDOW:Talk(SymAct("MEROETTA_VOICE"), -1342877601)
    TASK:WaitTask()
    subEveCloseMsg()
    CH("MEROETTA_VOICE"):SetFacialMotion(FACIAL_MOTION.NORMAL)
    CH("MEROETTA_VOICE"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
    CH("MEROETTA_VOICE"):WaitRotate()
    CH("MEROETTA_STEP"):SetDir(RotateTarget(0))
    WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("MEROETTA_VOICE"), -1225891554)
    WINDOW:CloseMessage()
    CH("MEROETTA_VOICE"):SetMotion(SymMot("ROUND"), LOOP.OFF)
    CH("MEROETTA_VOICE"):SetManpu("MP_SPREE_LP")
    CH("MEROETTA_VOICE"):SetNextMotion(SymMot("LETSGO"), LOOP.OFF, TimeSec(0.2))
    CH("MEROETTA_VOICE"):WaitPlayMotion()
    WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("MEROETTA_VOICE"), -105908263)
    WINDOW:CloseMessage()
    CH("MEROETTA_VOICE"):ResetManpu()
    EFFECT:Create("effectOnpu", SymEff("BL_VOICE_PINK_LP"))
    EFFECT:SetPosition("effectOnpu", CH("MEROETTA_VOICE"), BODY_POINT.HEAD)
    EFFECT:Play("effectOnpu")
    SOUND:PlaySe(SymSnd("SE_EF_WEATHER_SUN"), Volume(128))
    WINDOW:Talk(SymAct("MEROETTA_VOICE"), -525023592)
    WINDOW:CloseMessage()
    CH("MEROETTA_VOICE"):SetMotion(SymMot("ROUND"), LOOP.OFF)
    TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
    EFFECT:Remove("effectOnpu")
    EFFECT:Create("effectSmokeShortWhite", SymEff("NM_SMOKE_SHORT_WHITE"))
    EFFECT:SetPosition("effectSmokeShortWhite", CH("MEROETTA_VOICE"), BODY_POINT.CENTER)
    EFFECT:Play("effectSmokeShortWhite")
    SOUND:PlaySe(SymSnd("SE_EVT_BUNI"), Volume(256))
    TASK:Sleep(TimeSec(0.1))
    CH("MEROETTA_VOICE"):SetVisible(false)
    CH("MEROETTA_STEP"):SetVisible(true)
    CH("MEROETTA_STEP"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
    CH("MEROETTA_STEP"):WaitPlayMotion()
    WINDOW:DrawFace(324, 88, SymAct("MEROETTA_STEP"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("MEROETTA_STEP"), -879127205)
    subEveCloseMsg()
    CH("MEROETTA_STEP"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.2))
    CH("MEROETTA_STEP"):DirTo(CH("PLAYER"), Speed(350), ROT_TYPE.NEAR)
    CH("MEROETTA_STEP"):WaitRotate()
    WINDOW:DrawFace(324, 88, SymAct("MEROETTA_STEP"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("MEROETTA_STEP"), -763190246)
    subEveCloseMsg()
    CH("MEROETTA_STEP"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
    CH("MEROETTA_STEP"):WaitRotate()
    CH("MEROETTA_VOICE"):SetDir(RotateTarget(0))
    WINDOW:DrawFace(324, 88, SymAct("MEROETTA_STEP"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("MEROETTA_STEP"), 1427814613)
    WINDOW:KeyWait()
    CH("MEROETTA_STEP"):SetManpu("MP_SPREE_LP")
    CH("MEROETTA_STEP"):SetMotion(SymMot("VICTORY"), LOOP.OFF)
    WINDOW:Talk(SymAct("MEROETTA_STEP"), 1275169172)
    CH("MEROETTA_STEP"):WaitPlayMotion()
    WINDOW:CloseMessage()
    CH("MEROETTA_STEP"):ResetManpu()
    CH("MEROETTA_STEP"):SetMotion(SymMot("ROUND"), LOOP.OFF)
    TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
    EFFECT:Create("effectSmokeShortWhite02", SymEff("NM_SMOKE_SHORT_WHITE"))
    EFFECT:SetPosition("effectSmokeShortWhite02", CH("MEROETTA_STEP"), BODY_POINT.CENTER)
    EFFECT:Play("effectSmokeShortWhite02")
    SOUND:PlaySe(SymSnd("SE_EVT_BUNI"), Volume(256))
    TASK:Sleep(TimeSec(0.1))
    CH("MEROETTA_STEP"):SetVisible(false)
    CH("MEROETTA_VOICE"):SetVisible(true)
    CH("MEROETTA_VOICE"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
    CH("MEROETTA_VOICE"):WaitPlayMotion()
    CH("MEROETTA_VOICE"):SetManpu("MP_EXCLAMATION")
    WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("MEROETTA_VOICE"), -1903308432)
    WINDOW:CloseMessage()
    CH("MEROETTA_VOICE"):DirTo(CH("PLAYER"), Speed(350), ROT_TYPE.NEAR)
    CH("MEROETTA_VOICE"):WaitRotate()
    WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.SAD)
    WINDOW:Talk(SymAct("MEROETTA_VOICE"), -1751719887)
    WINDOW:Talk(SymAct("MEROETTA_VOICE"), -1128549390)
    WINDOW:CloseMessage()
    SOUND:VolumeBgm(Volume(256), TimeSec(0.5))
    CAMERA:MoveToPlayer(TimeSec(0.3), ACCEL_TYPE.NONE, DECEL_TYPE.HIGH)
    CAMERA:WaitMove()
    FLAG.MeroettaCounter = CONST.CNT_4
    subUseParadiseMeroettaTalkOut(CH("MEROETTA_VOICE"), result)
  elseif FLAG.MeroettaCounter == CONST.CNT_4 and LUA_SYSTEM:CheckKenzai_MusicParadise() == true and GROUND__2:JukeboxIsBuildPlace() == true and FLAG.ParaMusicParadiseBuild == CONST.FLAG_FALSE then
    SYSTEM:DebugPrint("---------------------------MEROETTA_EVENT_4")
    subFreePlayReachCommonAll()
    CAMERA:MoveFollowZoom(CH("MEROETTA_VOICE"), Height(0.3), Distance(7), TimeSec(0.3), ACCEL_TYPE.NONE, DECEL_TYPE.HIGH)
    local result = subUseParadiseMeroettaTalkIn(CH("MEROETTA_VOICE"))
    CAMERA:WaitMove()
    WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.SAD)
    WINDOW:Talk(SymAct("MEROETTA_VOICE"), -1516207437)
    WINDOW:Talk(SymAct("MEROETTA_VOICE"), -354347916)
    WINDOW:CloseMessage()
    CAMERA:MoveToPlayer(TimeSec(0.3), ACCEL_TYPE.NONE, DECEL_TYPE.HIGH)
    CAMERA:WaitMove()
    subUseParadiseMeroettaTalkOut(CH("MEROETTA_VOICE"), result)
  elseif (FLAG.MeroettaCounter == CONST.CNT_3 or FLAG.MeroettaCounter == CONST.CNT_4) and LUA_SYSTEM:CheckKenzai_MusicParadise() == true and GROUND__2:JukeboxIsBuildPlace() == false and FLAG.ParaMusicParadiseBuild == CONST.FLAG_FALSE then
    SYSTEM:DebugPrint("---------------------------MEROETTA_EVENT_5")
    subFreePlayReachCommonAll()
    SOUND:VolumeBgm(Volume(0), TimeSec(1))
    CH("MEROETTA_VOICE"):DirTo(CH("PLAYER"), Speed(350), ROT_TYPE.NEAR)
    CH("MEROETTA_STEP"):DirTo(CH("PLAYER"), Speed(350), ROT_TYPE.NEAR)
    CH("PARTY0"):DirTo(CH("MEROETTA_VOICE"), Speed(350), ROT_TYPE.NEAR)
    CH("PARTY1"):DirTo(CH("MEROETTA_VOICE"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.3))
    local spaceIndex = GROUND:GetMeroettaAppearSpaceIndex()
    local POINT_CENTER = SymPos(string.format("@SHOP_CENTER%02d", spaceIndex))
    local POINT_MEROETTA = SymPos(string.format("@DOTEKKOTSU_POINT%02d", spaceIndex))
    SCREEN_A:FadeOutAll(TimeSec(0.3), false)
    SCREEN_B:FadeOutAll(TimeSec(0.3), true)
    CHARA:DynamicRemoveLandNpc()
    if CHARA:IsExist("DIG_SHOP_OWNER") then
      CH("DIG_SHOP_OWNER"):SetVisible(false)
    end
    CH("MEROETTA_VOICE"):SetPosition(POINT_MEROETTA)
    CH("MEROETTA_STEP"):SetPosition(POINT_MEROETTA)
    CH("MEROETTA_VOICE"):SetDir(RotateTarget(0))
    CH("MEROETTA_STEP"):SetDir(RotateTarget(0))
    if FLAG.ParaMode == CONST.PARA_MODE_PARADISE or FLAG.StoryPlayerMode == CONST.ST_MODE_PARTNER or FLAG.StoryPlayerMode == CONST.ST_MODE_HERO then
      local POINT_PARTY0 = SymPos(string.format("@DOTEKKOTSU_POINT%02d", spaceIndex), PosOffs(0, 1.3))
      CH("PARTY0"):SetPosition(POINT_PARTY0)
      CH("PARTY0"):SetDir(CH("MEROETTA_VOICE"))
    else
      local POINT_PARTY0 = SymPos(string.format("@DOTEKKOTSU_POINT%02d", spaceIndex), PosOffs(-0.6, 1.3))
      local POINT_PARTY1 = SymPos(string.format("@DOTEKKOTSU_POINT%02d", spaceIndex), PosOffs(0.6, 1.3))
      CH("PARTY0"):SetPosition(POINT_PARTY0)
      CH("PARTY1"):SetPosition(POINT_PARTY1)
      CH("PARTY0"):SetDir(CH("MEROETTA_VOICE"))
      CH("PARTY1"):SetDir(CH("MEROETTA_VOICE"))
    end
    CAMERA:SetEye(SymPos(string.format("@DOTEKKOTSU_POINT%02d", spaceIndex), PosOffs(0, 4, 9)))
    CAMERA:SetTgt(SymPos(string.format("@DOTEKKOTSU_POINT%02d", spaceIndex)))
    TASK:Sleep(TimeSec(0.4))
    SCREEN_A:FadeInAll(TimeSec(0.5), true)
    SOUND:PlaySe(SymSnd("ME_EVT_DAN_01"), Volume(256))
    CH("MEROETTA_VOICE"):SetManpu("MP_EXCLAMATION")
    CH("MEROETTA_VOICE"):WaitManpu()
    WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.EMOTION)
    WINDOW:Talk(SymAct("MEROETTA_VOICE"), -201710283)
    WINDOW:CloseMessage()
    CH("MEROETTA_VOICE"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
    CH("MEROETTA_VOICE"):WaitRotate()
    CH("MEROETTA_STEP"):SetDir(RotateTarget(0))
    CH("MEROETTA_VOICE"):SetMotion(SymMot("ROUND"), LOOP.OFF)
    TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
    EFFECT:Create("effectSmokeShortWhite", SymEff("NM_SMOKE_SHORT_WHITE"))
    EFFECT:SetPosition("effectSmokeShortWhite", CH("MEROETTA_VOICE"), BODY_POINT.CENTER)
    EFFECT:Play("effectSmokeShortWhite")
    SOUND:PlaySe(SymSnd("ME_EVT_DAN_02"), Volume(256))
    TASK:Sleep(TimeSec(0.1))
    CH("MEROETTA_VOICE"):SetVisible(false)
    CH("MEROETTA_STEP"):SetVisible(true)
    CH("MEROETTA_STEP"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
    CH("MEROETTA_STEP"):WaitPlayMotion()
    WINDOW:DrawFace(324, 88, SymAct("MEROETTA_STEP"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("MEROETTA_STEP"), -656967946)
    WINDOW:CloseMessage()
    CH("MEROETTA_STEP"):SetMotion(SymMot("ROUND"), LOOP.OFF)
    TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
    EFFECT:Create("effectSmokeShortWhite02", SymEff("NM_SMOKE_SHORT_WHITE"))
    EFFECT:SetPosition("effectSmokeShortWhite02", CH("MEROETTA_STEP"), BODY_POINT.CENTER)
    EFFECT:Play("effectSmokeShortWhite02")
    SOUND:PlaySe(SymSnd("ME_EVT_TA_DAH"), Volume(256))
    TASK:Sleep(TimeSec(0.1))
    CH("MEROETTA_STEP"):SetVisible(false)
    CH("MEROETTA_VOICE"):SetVisible(true)
    CH("MEROETTA_VOICE"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
    CH("MEROETTA_VOICE"):WaitPlayMotion()
    CH("MEROETTA_VOICE"):SetManpu("MP_SPREE_LP")
    WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.EMOTION)
    WINDOW:Talk(SymAct("MEROETTA_VOICE"), -1043576905)
    subEveCloseMsg()
    CH("MEROETTA_VOICE"):ResetManpu()
    CH("MEROETTA_VOICE"):DirTo(CH("PLAYER"), Speed(350), ROT_TYPE.NEAR)
    CH("MEROETTA_VOICE"):WaitRotate()
    TASK:Regist(subEveDoubleJump, {
      CH("MEROETTA_VOICE")
    })
    CH("MEROETTA_VOICE"):SetFacialMotion(FACIAL_MOTION.HAPPY)
    WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.HAPPY)
    WINDOW:Talk(SymAct("MEROETTA_VOICE"), 1179933560)
    TASK:WaitTask()
    subEveCloseMsg()
    CH("MEROETTA_VOICE"):SetFacialMotion(FACIAL_MOTION.NORMAL)
    CH("MEROETTA_VOICE"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
    CH("MEROETTA_VOICE"):WaitRotate()
    CH("MEROETTA_STEP"):SetDir(RotateTarget(0))
    WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("MEROETTA_VOICE"), 1599040057)
    WINDOW:CloseMessage()
    CH("MEROETTA_VOICE"):SetMotion(SymMot("ROUND"), LOOP.OFF)
    CH("MEROETTA_VOICE"):SetManpu("MP_SPREE_LP")
    CH("MEROETTA_VOICE"):SetNextMotion(SymMot("LETSGO"), LOOP.OFF, TimeSec(0.2))
    CH("MEROETTA_VOICE"):WaitPlayMotion()
    WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("MEROETTA_VOICE"), 909227541)
    CH("MEROETTA_VOICE"):ResetManpu()
    subEveCloseMsg()
    EFFECT:Create("effectOnpu", SymEff("BL_VOICE_PINK_LP"))
    EFFECT:SetPosition("effectOnpu", CH("MEROETTA_VOICE"), BODY_POINT.HEAD)
    EFFECT:Play("effectOnpu")
    SOUND:PlaySe(SymSnd("SE_EF_WEATHER_SUN"), Volume(128))
    WINDOW:Talk(SymAct("MEROETTA_VOICE"), 791316308)
    WINDOW:CloseMessage()
    CH("MEROETTA_VOICE"):SetMotion(SymMot("ROUND"), LOOP.OFF)
    TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
    EFFECT:Remove("effectOnpu")
    EFFECT:Create("effectSmokeShortWhite", SymEff("NM_SMOKE_SHORT_WHITE"))
    EFFECT:SetPosition("effectSmokeShortWhite", CH("MEROETTA_VOICE"), BODY_POINT.CENTER)
    EFFECT:Play("effectSmokeShortWhite")
    SOUND:PlaySe(SymSnd("SE_EVT_BUNI"), Volume(256))
    TASK:Sleep(TimeSec(0.1))
    CH("MEROETTA_VOICE"):SetVisible(false)
    CH("MEROETTA_STEP"):SetVisible(true)
    CH("MEROETTA_STEP"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
    CH("MEROETTA_STEP"):WaitPlayMotion()
    WINDOW:DrawFace(324, 88, SymAct("MEROETTA_STEP"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("MEROETTA_STEP"), 67622039)
    subEveCloseMsg()
    CH("MEROETTA_STEP"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.2))
    CH("MEROETTA_STEP"):DirTo(CH("PLAYER"), Speed(350), ROT_TYPE.NEAR)
    CH("MEROETTA_STEP"):WaitRotate()
    WINDOW:DrawFace(324, 88, SymAct("MEROETTA_STEP"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("MEROETTA_STEP"), 488433110)
    subEveCloseMsg()
    CH("MEROETTA_VOICE"):DirTo(POINT_CENTER, Speed(500), ROT_TYPE.NEAR)
    CH("MEROETTA_STEP"):DirTo(POINT_CENTER, Speed(500), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("PARTY0"):DirTo(POINT_CENTER, Speed(500), ROT_TYPE.NEAR)
    CH("PARTY1"):DirTo(POINT_CENTER, Speed(500), ROT_TYPE.NEAR)
    CAMERA:MoveFollow(POINT_CENTER, Speed(3.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
    CAMERA:WaitMove()
    WINDOW:DrawFace(324, 88, SymAct("MEROETTA_STEP"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("MEROETTA_STEP"), 1381856017)
    WINDOW:KeyWait()
    CH("MEROETTA_STEP"):SetManpu("MP_SPREE_LP")
    CH("MEROETTA_STEP"):SetMotion(SymMot("VICTORY"), LOOP.OFF)
    WINDOW:Talk(SymAct("MEROETTA_STEP"), 1262895696)
    CH("MEROETTA_STEP"):WaitPlayMotion()
    WINDOW:CloseMessage()
    CH("MEROETTA_STEP"):ResetManpu()
    SCREEN_A:FadeOut(TimeSec(0.5), true)
    MAP:SetBG(SymMap("IMSB_02_MUSIC01"))
    MAP:SetVisible(false)
    MAP:SetVisibleBG(true)
    CH("MEROETTA_VOICE"):SetVisible(false)
    CH("MEROETTA_STEP"):SetVisible(false)
    CH("HERO"):SetVisible(false)
    CH("PARTNER"):SetVisible(false)
    TASK:Sleep(TimeSec(0.5))
    SOUND:PlaySe(SymSnd("ME_EVT_MEROETTA"), Volume(256))
    SCREEN_A:FadeIn(TimeSec(0.5), true)
    TASK:Sleep(TimeSec(13))
    SCREEN_A:FadeOut(TimeSec(0.5), true)
    MAP:SetVisible(true)
    MAP:SetVisibleBG(false)
    CH("MEROETTA_VOICE"):SetVisible(true)
    CH("MEROETTA_STEP"):SetVisible(true)
    CH("PARTY0"):SetVisible(true)
    CH("PARTY1"):SetVisible(true)
    TASK:Sleep(TimeSec(0.3))
    FLAG.ParaMusicParadiseBuild = CONST.FLAG_TRUE
    LUA_SYSTEM:BuildMeroetta_MusicParadise()
    FLAG.MapMoveNoFade = CONST.FLAG_TRUE
    SYSTEM:ReloadLandEntry()
  elseif (FLAG.MeroettaCounter == CONST.CNT_3 or FLAG.MeroettaCounter == CONST.CNT_4) and FLAG.ParaMusicParadiseBuild == CONST.FLAG_TRUE then
    local spaceIndex = GROUND:GetMeroettaAppearSpaceIndex()
    local POINT_CENTER = SymPos(string.format("@SHOP_CENTER%02d", spaceIndex))
    local POINT_MEROETTA = SymPos(string.format("@DOTEKKOTSU_POINT%02d", spaceIndex))
    local POINT_MEROETTA_FAST = SymPos(string.format("@HORIATE_POINT%02d", spaceIndex))
    CHARA:DynamicRemoveLandNpc()
    if CHARA:IsExist("DIG_SHOP_OWNER") then
      CH("DIG_SHOP_OWNER"):SetVisible(false)
    end
    subFreePlayReachCommonAll()
    CH("MEROETTA_STEP"):SetVisible(false)
    CH("MEROETTA_VOICE"):SetVisible(true)
    CH("MEROETTA_VOICE"):SetPosition(POINT_MEROETTA)
    CH("MEROETTA_STEP"):SetPosition(POINT_MEROETTA)
    CH("MEROETTA_VOICE"):SetDir(RotateTarget(0))
    CH("MEROETTA_STEP"):SetDir(RotateTarget(0))
    CH("PARTY0"):SetDir(POINT_CENTER)
    CH("PARTY1"):SetDir(POINT_CENTER)
    CH("MEROETTA_STEP"):SetMotion(SymMot("WAIT02"), LOOP.OFF)
    CAMERA:SetEye(SymPos(string.format("@SHOP_COUNTER%02d", spaceIndex), PosOffs(0, 5, 10)))
    CAMERA:SetTgt(SymPos(string.format("@SHOP_COUNTER%02d", spaceIndex)))
    SCREEN_A:FadeIn(TimeSec(0.5), true)
    SOUND:PlaySe(SymSnd("SE_EVT_BIRIJION"), Volume(256))
    CH("MEROETTA_VOICE"):SetMotion(SymMot("ROUND"), LOOP.OFF)
    CH("MEROETTA_VOICE"):SetNextMotion(SymMot("LETSGO"), LOOP.OFF, TimeSec(0.2))
    CH("MEROETTA_VOICE"):WaitPlayMotion()
    WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("MEROETTA_VOICE"), 1617629587)
    TASK:Sleep(TimeSec(1))
    WINDOW:CloseMessage()
    CAMERA:MoveFollow(POINT_MEROETTA, Speed(3.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
    CH("MEROETTA_VOICE"):DirTo(RotateTarget(0), Speed(500), ROT_TYPE.NEAR)
    CH("MEROETTA_STEP"):DirTo(RotateTarget(0), Speed(500), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("PARTY0"):DirTo(CH("MEROETTA_VOICE"), Speed(500), ROT_TYPE.NEAR)
    CH("PARTY1"):DirTo(CH("MEROETTA_VOICE"), Speed(500), ROT_TYPE.NEAR)
    SOUND:VolumeBgm(Volume(256), TimeSec(0.5))
    CAMERA:WaitMove()
    CH("MEROETTA_VOICE"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    CH("MEROETTA_VOICE"):SetManpu("MP_SPREE_LP")
    CH("MEROETTA_VOICE"):DirTo(RotateTarget(-45), Speed(350), ROT_TYPE.NEAR)
    CH("MEROETTA_VOICE"):WaitRotate()
    subEveJump(CH("MEROETTA_VOICE"))
    TASK:Sleep(TimeSec(0.3))
    CH("MEROETTA_VOICE"):DirTo(RotateTarget(45), Speed(350), ROT_TYPE.NEAR)
    CH("MEROETTA_VOICE"):WaitRotate()
    TASK:Regist(subEveDoubleJump, {
      CH("MEROETTA_VOICE")
    })
    CH("MEROETTA_VOICE"):SetFacialMotion(FACIAL_MOTION.HAPPY)
    WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.HAPPY)
    WINDOW:Talk(SymAct("MEROETTA_VOICE"), 2037391570)
    WINDOW:CloseMessage()
    CH("MEROETTA_VOICE"):SetFacialMotion(FACIAL_MOTION.NORMAL)
    CH("MEROETTA_VOICE"):ResetManpu()
    CH("MEROETTA_VOICE"):DirTo(CH("PLAYER"), Speed(350), ROT_TYPE.NEAR)
    CH("MEROETTA_VOICE"):WaitRotate()
    CH("MEROETTA_VOICE"):SetFacialMotion(FACIAL_MOTION.HAPPY)
    WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.HAPPY)
    WINDOW:Talk(SymAct("MEROETTA_VOICE"), -18334691)
    WINDOW:Talk(SymAct("MEROETTA_VOICE"), -403501732)
    WINDOW:KeyWait()
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
    CH("MEROETTA_VOICE"):SetManpu("MP_EXCLAMATION")
    WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.NORMAL)
    WINDOW:Talk(SymAct("MEROETTA_VOICE"), 612637179)
    WINDOW:Talk(SymAct("MEROETTA_VOICE"), 1033840826)
    WINDOW:KeyWait()
    CH("MEROETTA_VOICE"):SetFacialMotion(FACIAL_MOTION.NORMAL)
    TASK:Regist(subEveDoubleJump, {
      CH("MEROETTA_VOICE")
    })
    WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.EMOTION)
    WINDOW:Talk(SymAct("MEROETTA_VOICE"), 380795769)
    TASK:WaitTask()
    WINDOW:KeyWait()
    WINDOW:Talk(SymAct("MEROETTA_VOICE"), 262752824)
    CH("MEROETTA_VOICE"):SetMotion(SymMot("LETSGO"), LOOP.OFF, TimeSec(0.2))
    CH("MEROETTA_VOICE"):WaitPlayMotion()
    WINDOW:CloseMessage()
    SCREEN_A:FadeOut(TimeSec(0.5), true)
    CH("MEROETTA_VOICE"):SetPosition(POINT_MEROETTA_FAST)
    CH("MEROETTA_STEP"):SetPosition(POINT_MEROETTA_FAST)
    CH("PARTY0"):SetDir(POINT_CENTER)
    CH("PARTY1"):SetDir(POINT_CENTER)
    CH("MEROETTA_VOICE"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0))
    CAMERA:ResetPlayerFreeMoveCameraOffset()
    CAMERA:MoveToPlayer(TimeSec(0), ACCEL_TYPE.NONE, DECEL_TYPE.NONE)
    CHARA:DynamicLoadLandNpc()
    if CHARA:IsExist("DIG_SHOP_OWNER") then
      CH("DIG_SHOP_OWNER"):SetVisible(true)
    end
    FLAG.MeroettaCounter = CONST.CNT_5
    TASK:Sleep(TimeSec(0.5))
    SCREEN_A:FadeIn(TimeSec(0.5), false)
    SCREEN_B:FadeInAll(TimeSec(0.5), true)
  elseif FLAG.MeroettaCounter == CONST.CNT_5 or FLAG.MeroettaCounter == CONST.CNT_6 then
    SYSTEM:DebugPrint("---------------------------MEROETTA_EVENT_6")
    subFreePlayReachCommonAll()
    if GROUND:IsUseJukebox() == false then
      CAMERA:MoveFollowZoom(CH("MEROETTA_VOICE"), Height(0.3), Distance(7), TimeSec(0.3), ACCEL_TYPE.NONE, DECEL_TYPE.HIGH)
      local result = subUseParadiseMeroettaTalkIn(CH("MEROETTA_VOICE"))
      CAMERA:WaitMove()
      WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.NORMAL)
      WINDOW:Talk(SymAct("MEROETTA_VOICE"), 1089002751)
      WINDOW:Talk(SymAct("MEROETTA_VOICE"), 1509158334)
      WINDOW:KeyWait()
      SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
      CH("MEROETTA_VOICE"):SetManpu("MP_EXCLAMATION")
      WINDOW:Talk(SymAct("MEROETTA_VOICE"), 1927200381)
      WINDOW:Talk(SymAct("MEROETTA_VOICE"), 1808109372)
      WINDOW:KeyWait()
      TASK:Regist(subEveDoubleJump, {
        CH("MEROETTA_VOICE")
      })
      WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.EMOTION)
      WINDOW:Talk(SymAct("MEROETTA_VOICE"), -329411597)
      TASK:WaitTask()
      WINDOW:KeyWait()
      WINDOW:Talk(SymAct("MEROETTA_VOICE"), -179920206)
      CH("MEROETTA_VOICE"):SetMotion(SymMot("LETSGO"), LOOP.OFF, TimeSec(0.2))
      CH("MEROETTA_VOICE"):WaitPlayMotion()
      WINDOW:CloseMessage()
      CH("MEROETTA_VOICE"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.2))
      subUseParadiseMeroettaTalkOut(CH("MEROETTA_VOICE"), result)
      CAMERA:MoveToPlayer(TimeSec(0.3), ACCEL_TYPE.NONE, DECEL_TYPE.HIGH)
      CAMERA:WaitMove()
    elseif FLAG.MeroettaCounter == CONST.CNT_5 then
      SYSTEM:DebugPrint("---------------------------MEROETTA_EVENT_7")
      CAMERA:MoveFollowZoom(CH("MEROETTA_VOICE"), Height(0.3), Distance(7), TimeSec(0.3), ACCEL_TYPE.NONE, DECEL_TYPE.HIGH)
      do
        local result = subUseParadiseMeroettaTalkIn(CH("MEROETTA_VOICE"))
        CAMERA:WaitMove()
        SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
        CH("MEROETTA_VOICE"):SetManpu("MP_EXCLAMATION")
        CH("MEROETTA_VOICE"):WaitManpu()
        WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.SURPRISE)
        WINDOW:Talk(SymAct("MEROETTA_VOICE"), -1674019170)
        WINDOW:KeyWait()
        TASK:Regist(subEveDoubleJump, {
          CH("MEROETTA_VOICE")
        })
        WINDOW:Talk(SymAct("MEROETTA_VOICE"), -2061283361)
        TASK:WaitTask()
        WINDOW:CloseMessage()
        CH("MEROETTA_VOICE"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
        CH("MEROETTA_VOICE"):WaitRotate()
        CH("MEROETTA_VOICE"):SetMotion(SymMot("SLEEP"), LOOP.OFF, TimeSec(0.2))
        WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.PAIN)
        WINDOW:Talk(SymAct("MEROETTA_VOICE"), -1374807012)
        CH("MEROETTA_VOICE"):WaitPlayMotion()
        CH("MEROETTA_VOICE"):SetMotion(SymMot("SLEEPLOOP"), LOOP.ON)
        WINDOW:KeyWait()
        CH("MEROETTA_VOICE"):SetManpu("MP_SPREE_LP")
        CH("MEROETTA_VOICE"):SetMotion(SymMot("VICTORY"), LOOP.OFF)
        WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.EMOTION)
        WINDOW:Talk(SymAct("MEROETTA_VOICE"), -1223348899)
        CH("MEROETTA_VOICE"):WaitPlayMotion()
        WINDOW:CloseMessage()
        CH("MEROETTA_VOICE"):ResetManpu()
        CH("MEROETTA_VOICE"):DirTo(CH("PLAYER"), Speed(350), ROT_TYPE.NEAR)
        CH("MEROETTA_VOICE"):WaitRotate()
        WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.EMOTION)
        WINDOW:Talk(SymAct("MEROETTA_VOICE"), -128664678)
        WINDOW:KeyWait()
        TASK:Regist(subEveDoubleJump, {
          CH("MEROETTA_VOICE")
        })
        WINDOW:Talk(SymAct("MEROETTA_VOICE"), -514880805)
        WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.NORMAL)
        WINDOW:Talk(SymAct("MEROETTA_VOICE"), -899491560)
        local function __LB_SCOPE()
          local __scopeFuncTbl = {}
          function __scopeFuncTbl.__LB_FIRST()
          end
          function __scopeFuncTbl.CELECT_EVENT03()
            local __labelCnt = 0
            local __labelTbl = {}
            WINDOW:SelectStart()
            WINDOW:SelectChain(-746985383, __labelCnt)
            WINDOW:DefaultCursor(__labelCnt)
            __labelTbl[__labelCnt] = __scopeFuncTbl.LABEL_YES
            __labelCnt = __labelCnt + 1
            WINDOW:SelectChain(1424094358, __labelCnt)
            __labelTbl[__labelCnt] = __scopeFuncTbl.LABEL_NO
            __labelCnt = __labelCnt + 1
            local __res = WINDOW:SelectEndTalk(MENU_SELECT_MODE.DISABLE_CANCEL)
            return __labelTbl[__res]
          end
          function __scopeFuncTbl.LABEL_NO()
            WINDOW:CloseMessage()
            SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
            CH("MEROETTA_VOICE"):SetManpu("MP_EXCLAMATION")
            CH("MEROETTA_VOICE"):WaitManpu()
            WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.SURPRISE)
            WINDOW:Talk(SymAct("MEROETTA_VOICE"), 1308280279)
            WINDOW:Talk(SymAct("MEROETTA_VOICE"), 32458279)
            WINDOW:KeyWait()
            TASK:Regist(subEveDoubleJump, {
              CH("MEROETTA_VOICE")
            })
            WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.NORMAL)
            WINDOW:Talk(SymAct("MEROETTA_VOICE"), 418674534)
            WINDOW:Talk(SymAct("MEROETTA_VOICE"), 869868709)
            TASK:WaitTask()
            WINDOW:KeyWait()
            CH("MEROETTA_VOICE"):DirTo(RotateTarget(0), Speed(350))
            CH("MEROETTA_VOICE"):WaitRotate()
            CH("MEROETTA_VOICE"):SetMotion(SymMot("VICTORY"), LOOP.OFF, TimeSec(0.2))
            WINDOW:Talk(SymAct("MEROETTA_VOICE"), 717362660)
            CH("MEROETTA_VOICE"):WaitPlayMotion()
            WINDOW:CloseMessage()
            CH("MEROETTA_VOICE"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.2))
            FLAG.MeroettaCounter = CONST.CNT_6
            CAMERA:MoveToPlayer(TimeSec(0.3), ACCEL_TYPE.NONE, DECEL_TYPE.HIGH)
            CAMERA:WaitMove()
            subUseParadiseMeroettaTalkOut(CH("MEROETTA_VOICE"), result)
            return __scopeFuncTbl.LABEL_END
          end
          function __scopeFuncTbl.LABEL_YES()
            subEveCloseMsg()
            CH("MEROETTA_VOICE"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
            CH("MEROETTA_VOICE"):WaitRotate()
            CH("MEROETTA_STEP"):SetDir(RotateTarget(0))
            CH("MEROETTA_VOICE"):SetManpu("MP_SPREE_LP")
            CH("MEROETTA_VOICE"):SetMotion(SymMot("ROUND"), LOOP.OFF)
            CH("MEROETTA_VOICE"):SetFacialMotion(FACIAL_MOTION.HAPPY)
            WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.HAPPY)
            WINDOW:Talk(SymAct("MEROETTA_VOICE"), 1703117603)
            CH("MEROETTA_VOICE"):WaitPlayMotion()
            CH("MEROETTA_VOICE"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
            CH("MEROETTA_VOICE"):WaitPlayMotion()
            WINDOW:CloseMessage()
            CH("MEROETTA_VOICE"):ResetManpu()
            CH("MEROETTA_VOICE"):SetFacialMotion(FACIAL_MOTION.NORMAL)
            CH("MEROETTA_VOICE"):SetMotion(SymMot("ROUND"), LOOP.OFF)
            TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
            EFFECT:Create("effectSmokeShortWhite", SymEff("NM_SMOKE_SHORT_WHITE"))
            EFFECT:SetPosition("effectSmokeShortWhite", CH("MEROETTA_VOICE"), BODY_POINT.CENTER)
            EFFECT:Play("effectSmokeShortWhite")
            SOUND:PlaySe(SymSnd("SE_EVT_BUNI"), Volume(256))
            TASK:Sleep(TimeSec(0.1))
            CH("MEROETTA_VOICE"):SetVisible(false)
            CH("MEROETTA_STEP"):SetVisible(true)
            CH("MEROETTA_STEP"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
            CH("MEROETTA_STEP"):WaitPlayMotion()
            CH("MEROETTA_STEP"):SetManpu("MP_SPREE_LP")
            CH("MEROETTA_STEP"):SetFacialMotion(FACIAL_MOTION.HAPPY)
            WINDOW:DrawFace(324, 88, SymAct("MEROETTA_STEP"), FACE_TYPE.HAPPY)
            WINDOW:Talk(SymAct("MEROETTA_STEP"), 2090381922)
            WINDOW:CloseMessage()
            CH("MEROETTA_STEP"):SetFacialMotion(FACIAL_MOTION.NORMAL)
            CH("MEROETTA_STEP"):ResetManpu()
            CH("MEROETTA_STEP"):SetMotion(SymMot("ROUND"), LOOP.OFF)
            TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
            EFFECT:Create("effectSmokeShortWhite02", SymEff("NM_SMOKE_SHORT_WHITE"))
            EFFECT:SetPosition("effectSmokeShortWhite02", CH("MEROETTA_STEP"), BODY_POINT.CENTER)
            EFFECT:Play("effectSmokeShortWhite02")
            SOUND:PlaySe(SymSnd("SE_EVT_BUNI"), Volume(256))
            TASK:Sleep(TimeSec(0.1))
            CH("MEROETTA_STEP"):SetVisible(false)
            CH("MEROETTA_VOICE"):SetVisible(true)
            CH("MEROETTA_VOICE"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
            CH("MEROETTA_VOICE"):WaitPlayMotion()
            WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.EMOTION)
            WINDOW:Talk(SymAct("MEROETTA_VOICE"), 1471537569)
            subEveCloseMsg()
            GROUND:SetPokemonWarehouseMeroetta()
            SOUND:PlayMe(SymSnd("ME_PARTY"), Volume(256))
            WINDOW:SysMsg(1320079584)
            SOUND:WaitMe()
            subEveCloseMsg()
            CH("MEROETTA_VOICE"):DirTo(CH("PLAYER"), Speed(350), ROT_TYPE.NEAR)
            CH("MEROETTA_VOICE"):WaitRotate()
            TASK:Regist(subEveDoubleJump, {
              CH("MEROETTA_VOICE")
            })
            CH("MEROETTA_VOICE"):SetFacialMotion(FACIAL_MOTION.HAPPY)
            WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.HAPPY)
            WINDOW:Talk(SymAct("MEROETTA_VOICE"), -919155665)
            WINDOW:Talk(SymAct("MEROETTA_VOICE"), -802292370)
            WINDOW:Talk(SymAct("MEROETTA_VOICE"), -1185734334)
            WINDOW:Talk(SymAct("MEROETTA_VOICE"), -1605890045)
            TASK:WaitTask()
            WINDOW:CloseMessage()
            CH("MEROETTA_VOICE"):SetFacialMotion(FACIAL_MOTION.NORMAL)
            SCREEN_B:FadeOutAll(TimeSec(0.5), false)
            SCREEN_A:FadeOut(TimeSec(0.5), true)
            CAMERA:MoveToPlayer(TimeSec(0), ACCEL_TYPE.NONE, DECEL_TYPE.HIGH)
            subUseParadiseMeroettaTalkOut(CH("MEROETTA_VOICE"), result)
            CH("MEROETTA_STEP"):SetVisible(false)
            CH("MEROETTA_VOICE"):SetVisible(false)
            FLAG.MeroettaCounter = CONST.CNT_7
            TASK:Sleep(TimeSec(0.5))
            SCREEN_B:FadeInAll(TimeSec(0.5), false)
            SCREEN_A:FadeIn(TimeSec(0.5), true)
          end
          function __scopeFuncTbl.LABEL_END()
          end
          local __next = __scopeFuncTbl.CELECT_EVENT03
          while __next ~= nil do
            __next = __next()
          end
        end
        __LB_SCOPE()
      end
    elseif FLAG.MeroettaCounter == CONST.CNT_6 then
      SYSTEM:DebugPrint("---------------------------MEROETTA_EVENT_8")
      CAMERA:MoveFollowZoom(CH("MEROETTA_VOICE"), Height(0.3), Distance(7), TimeSec(0.3), ACCEL_TYPE.NONE, DECEL_TYPE.HIGH)
      do
        local result = subUseParadiseMeroettaTalkIn(CH("MEROETTA_VOICE"))
        CAMERA:WaitMove()
        WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.NORMAL)
        WINDOW:Talk(SymAct("MEROETTA_VOICE"), -1956297792)
        WINDOW:KeyWait()
        TASK:Regist(subEveDoubleJump, {
          CH("MEROETTA_VOICE")
        })
        WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.EMOTION)
        WINDOW:Talk(SymAct("MEROETTA_VOICE"), -1837206911)
        WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.NORMAL)
        WINDOW:Talk(SymAct("MEROETTA_VOICE"), -583015354)
        local function __LB_SCOPE()
          local __scopeFuncTbl = {}
          function __scopeFuncTbl.__LB_FIRST()
          end
          function __scopeFuncTbl.CELECT_EVENT04()
            local __labelCnt = 0
            local __labelTbl = {}
            WINDOW:SelectStart()
            WINDOW:SelectChain(-1004219129, __labelCnt)
            WINDOW:DefaultCursor(__labelCnt)
            __labelTbl[__labelCnt] = __scopeFuncTbl.LABEL_YES
            __labelCnt = __labelCnt + 1
            WINDOW:SelectChain(-284588348, __labelCnt)
            __labelTbl[__labelCnt] = __scopeFuncTbl.LABEL_NO
            __labelCnt = __labelCnt + 1
            local __res = WINDOW:SelectEndTalk(MENU_SELECT_MODE.DISABLE_CANCEL)
            return __labelTbl[__res]
          end
          function __scopeFuncTbl.LABEL_NO()
            WINDOW:CloseMessage()
            SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
            CH("MEROETTA_VOICE"):SetManpu("MP_EXCLAMATION")
            CH("MEROETTA_VOICE"):WaitManpu()
            WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.SURPRISE)
            WINDOW:Talk(SymAct("MEROETTA_VOICE"), -166545531)
            WINDOW:Talk(SymAct("MEROETTA_VOICE"), 1904913226)
            WINDOW:KeyWait()
            TASK:Regist(subEveDoubleJump, {
              CH("MEROETTA_VOICE")
            })
            WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.NORMAL)
            WINDOW:Talk(SymAct("MEROETTA_VOICE"), 1754372619)
            WINDOW:Talk(SymAct("MEROETTA_VOICE"), -1410953556)
            TASK:WaitTask()
            WINDOW:KeyWait()
            CH("MEROETTA_VOICE"):DirTo(RotateTarget(0), Speed(350))
            CH("MEROETTA_VOICE"):WaitRotate()
            CH("MEROETTA_VOICE"):SetMotion(SymMot("VICTORY"), LOOP.OFF, TimeSec(0.2))
            WINDOW:Talk(SymAct("MEROETTA_VOICE"), -1291993107)
            CH("MEROETTA_VOICE"):WaitPlayMotion()
            WINDOW:CloseMessage()
            CH("MEROETTA_VOICE"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.2))
            CAMERA:MoveToPlayer(TimeSec(0.3), ACCEL_TYPE.NONE, DECEL_TYPE.HIGH)
            CAMERA:WaitMove()
            subUseParadiseMeroettaTalkOut(CH("MEROETTA_VOICE"), result)
          end
          function __scopeFuncTbl.LABEL_YES()
            subEveCloseMsg()
            CH("MEROETTA_VOICE"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
            CH("MEROETTA_VOICE"):WaitRotate()
            CH("MEROETTA_STEP"):SetDir(RotateTarget(0))
            CH("MEROETTA_VOICE"):SetManpu("MP_SPREE_LP")
            CH("MEROETTA_VOICE"):SetMotion(SymMot("ROUND"), LOOP.OFF)
            CH("MEROETTA_VOICE"):SetFacialMotion(FACIAL_MOTION.HAPPY)
            WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.HAPPY)
            WINDOW:Talk(SymAct("MEROETTA_VOICE"), -1714361298)
            CH("MEROETTA_VOICE"):WaitPlayMotion()
            CH("MEROETTA_VOICE"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
            CH("MEROETTA_VOICE"):WaitPlayMotion()
            WINDOW:CloseMessage()
            CH("MEROETTA_VOICE"):SetFacialMotion(FACIAL_MOTION.NORMAL)
            CH("MEROETTA_VOICE"):ResetManpu()
            CH("MEROETTA_VOICE"):SetMotion(SymMot("ROUND"), LOOP.OFF)
            TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
            EFFECT:Create("effectSmokeShortWhite", SymEff("NM_SMOKE_SHORT_WHITE"))
            EFFECT:SetPosition("effectSmokeShortWhite", CH("MEROETTA_VOICE"), BODY_POINT.CENTER)
            EFFECT:Play("effectSmokeShortWhite")
            SOUND:PlaySe(SymSnd("SE_EVT_BUNI"), Volume(256))
            TASK:Sleep(TimeSec(0.1))
            CH("MEROETTA_VOICE"):SetVisible(false)
            CH("MEROETTA_STEP"):SetVisible(true)
            CH("MEROETTA_STEP"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
            CH("MEROETTA_STEP"):WaitPlayMotion()
            CH("MEROETTA_STEP"):SetFacialMotion(FACIAL_MOTION.HAPPY)
            WINDOW:DrawFace(324, 88, SymAct("MEROETTA_STEP"), FACE_TYPE.HAPPY)
            WINDOW:Talk(SymAct("MEROETTA_STEP"), -2134123153)
            WINDOW:CloseMessage()
            CH("MEROETTA_STEP"):SetFacialMotion(FACIAL_MOTION.NORMAL)
            CH("MEROETTA_STEP"):SetMotion(SymMot("ROUND"), LOOP.OFF)
            TASK:Sleep(TimeSec(10, TIME_TYPE.FRAME))
            EFFECT:Create("effectSmokeShortWhite02", SymEff("NM_SMOKE_SHORT_WHITE"))
            EFFECT:SetPosition("effectSmokeShortWhite02", CH("MEROETTA_STEP"), BODY_POINT.CENTER)
            EFFECT:Play("effectSmokeShortWhite02")
            SOUND:PlaySe(SymSnd("SE_EVT_BUNI"), Volume(256))
            TASK:Sleep(TimeSec(0.1))
            CH("MEROETTA_STEP"):SetVisible(false)
            CH("MEROETTA_VOICE"):SetVisible(true)
            CH("MEROETTA_VOICE"):SetMotion(SymMot("LETSGO"), LOOP.OFF)
            CH("MEROETTA_VOICE"):WaitPlayMotion()
            WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.EMOTION)
            WINDOW:Talk(SymAct("MEROETTA_VOICE"), -813020248)
            subEveCloseMsg()
            GROUND:SetPokemonWarehouseMeroetta()
            SOUND:PlayMe(SymSnd("ME_PARTY"), Volume(256))
            WINDOW:SysMsg(-695108887)
            SOUND:WaitMe()
            subEveCloseMsg()
            CH("MEROETTA_VOICE"):DirTo(CH("PLAYER"), Speed(350), ROT_TYPE.NEAR)
            CH("MEROETTA_VOICE"):WaitRotate()
            TASK:Regist(subEveDoubleJump, {
              CH("MEROETTA_VOICE")
            })
            CH("MEROETTA_VOICE"):SetFacialMotion(FACIAL_MOTION.HAPPY)
            WINDOW:DrawFace(20, 88, SymAct("MEROETTA_VOICE"), FACE_TYPE.HAPPY)
            WINDOW:Talk(SymAct("MEROETTA_VOICE"), -38000342)
            WINDOW:Talk(SymAct("MEROETTA_VOICE"), -458811285)
            WINDOW:Talk(SymAct("MEROETTA_VOICE"), 1665074340)
            WINDOW:Talk(SymAct("MEROETTA_VOICE"), 2049193445)
            TASK:WaitTask()
            WINDOW:CloseMessage()
            CH("MEROETTA_VOICE"):SetFacialMotion(FACIAL_MOTION.NORMAL)
            SCREEN_B:FadeOutAll(TimeSec(0.5), false)
            SCREEN_A:FadeOut(TimeSec(0.5), true)
            CAMERA:MoveToPlayer(TimeSec(0), ACCEL_TYPE.NONE, DECEL_TYPE.HIGH)
            subUseParadiseMeroettaTalkOut(CH("MEROETTA_VOICE"), result)
            CH("MEROETTA_STEP"):SetVisible(false)
            CH("MEROETTA_VOICE"):SetVisible(false)
            FLAG.MeroettaCounter = CONST.CNT_7
            TASK:Sleep(TimeSec(0.5))
            SCREEN_B:FadeInAll(TimeSec(0.5), false)
            SCREEN_A:FadeIn(TimeSec(0.5), true)
          end
          function __scopeFuncTbl.LABEL_END()
          end
          local __next = __scopeFuncTbl.CELECT_EVENT04
          while __next ~= nil do
            __next = __next()
          end
        end
        __LB_SCOPE()
      end
    end
  end
end
function subUseParadiseMeroettaTalkIn(char_name)
  SYSTEM:DebugPrint("---------------------------MEROETTA_EVENT_MUKIAI")
  LOWER_SCREEN:SetVisible(false)
  subFreePlayReachCommon()
  local degree = char_name:GetDir()
  if FLAG.ParaMode == CONST.PARA_MODE_PARADISE or FLAG.StoryPlayerMode == CONST.ST_MODE_PARTNER or FLAG.StoryPlayerMode == CONST.ST_MODE_HERO then
    if CHARA:IsExist("HERO") then
      char_name:DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
      CH("HERO"):DirTo(char_name, Speed(350), ROT_TYPE.NEAR)
      char_name:WaitRotate()
      CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    else
      char_name:DirTo(CH("PLAYER"), Speed(350), ROT_TYPE.NEAR)
      CH("PLAYER"):DirTo(char_name, Speed(350), ROT_TYPE.NEAR)
      char_name:WaitRotate()
      CH("PLAYER"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    end
  else
    char_name:DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
    CH("HERO"):DirTo(char_name, Speed(350), ROT_TYPE.NEAR)
    CH("PARTNER"):DirTo(char_name, Speed(350), ROT_TYPE.NEAR)
    char_name:WaitRotate()
    CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    CH("PARTNER"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
  return degree
end
function subUseParadiseMeroettaTalkOut(char_name, degree)
  SYSTEM:DebugPrint("---------------------------MEROETTA_EVENT_MODORI")
  if degree ~= nil then
    char_name:DirTo(RotateTarget(degree), Speed(350), ROT_TYPE.NEAR)
  end
  char_name:WaitRotate()
  subFreePlayReachCommon()
  subMapCameraSet()
  LOWER_SCREEN:SetVisible(true)
  return PROC.OK
end

