dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main03_birijion01_init()
end
function main03_birijion01_start()
  CHARA:SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("WASHIBON"):DirLockToChara(CH("BIRIJION"))
  CH("HAADERIA"):DirLockToChara(CH("BIRIJION"))
  CH("KOARUHII"):DirLockToChara(CH("BIRIJION"))
  CH("MINEZUMI"):DirLockToChara(CH("BIRIJION"))
  CH("DANGORO"):DirLockToChara(CH("BIRIJION"))
  CH("KAKUREON"):DirLockToChara(CH("BIRIJION"))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("BIRIJION"):WalkTo(SymPos("P00_BIRIJION"), Speed(1))
  CH("BIRIJION"):WaitMove()
  TASK:Sleep(TimeSec(0.75))
  SCREEN_A:WhiteOut(TimeSec(0.5), true)
  MAP:SetVisible(false)
  MAP:SetBG(SymMap("IM03_02_BEAUTY"))
  MAP:SetVisibleBG(true)
  CH("KAKUREON"):SetVisible(false)
  CH("WASHIBON"):SetVisible(false)
  CH("HAADERIA"):SetVisible(false)
  CH("KOARUHII"):SetVisible(false)
  GM("AZUKARI_BOX"):SetVisible(false)
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.3))
  local taskEffTwinkle00 = function()
    function TaskL.Loop()
      EFFECT:Create("effectTwinkle_01", SymEff("EV_GLITTER_RANDOM"))
      EFFECT:SetPosition("effectTwinkle_01", SymPos("P01_EFF_GLITTER_RANDOM"))
      EFFECT:Play("effectTwinkle_01")
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      EFFECT:Create("effectTwinkle_02", SymEff("EV_GLITTER_RANDOM"))
      EFFECT:SetPosition("effectTwinkle_02", SymPos("P02_EFF_GLITTER_RANDOM"))
      EFFECT:Play("effectTwinkle_02")
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      EFFECT:Create("effectTwinkle_03", SymEff("EV_GLITTER_RANDOM"))
      EFFECT:SetPosition("effectTwinkle_03", SymPos("P03_EFF_GLITTER_RANDOM"))
      EFFECT:Play("effectTwinkle_03")
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
    end
    function TaskL.Finish()
      return
    end
  end
  TASK:Regist(Group("grpKiraKira"), taskEffTwinkle00)
  SOUND:PlaySe(SymSnd("SE_EVT_BIRIJION"), Volume(256))
  SCREEN_A:WhiteIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(2.5))
  SCREEN_A:WhiteOut(TimeSec(0.5), true)
  TASK:ExitNotifyTasks(Group("grpKiraKira"))
  MAP:SetVisible(true)
  MAP:SetVisibleBG(false)
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CH("KAKUREON"):SetVisible(true)
  CH("WASHIBON"):SetVisible(true)
  CH("HAADERIA"):SetVisible(true)
  CH("KOARUHII"):SetVisible(true)
  GM("AZUKARI_BOX"):SetVisible(true)
  TASK:Sleep(TimeSec(0.3))
  SCREEN_A:WhiteIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_HOWAWAN"), Volume(256))
  CH("WASHIBON"):SetManpu("MP_HEART")
  TASK:Sleep(TimeSec(0.5))
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_HOWAWAN"), Volume(256))
  CH("KOARUHII"):SetManpu("MP_HEART")
  TASK:Sleep(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_HOWAWAN"), Volume(256))
  CH("DANGORO"):SetManpu("MP_HEART")
  TASK:Sleep(TimeSec(1.5))
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  local taskBirijion00 = function()
    CH("BIRIJION"):WalkTo(SplinePath(SymPos("P01_BIRIJION"), SymPos("P02_BIRIJION"), SymPos("P03_BIRIJION")), Speed(1))
    CH("BIRIJION"):WaitMove()
    CH("BIRIJION"):SetVisible(false)
  end
  TASK:Regist(taskBirijion00)
  WINDOW:SetWaitMode(TimeSec(1.5), TimeSec(1))
  SOUND:PlaySe(SymSnd("SE_EVT_HOWAWAN"), Volume(256))
  CH("WASHIBON"):SetManpu("MP_HEART")
  WINDOW:DrawFace(72, 16, SymAct("WASHIBON"), FACE_TYPE.EMOTION)
  WINDOW:Talk(SymAct("WASHIBON"), 2117262721)
  subEveCloseMsg()
  CH("KAKUREON"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(324, 20, SymAct("KAKUREON"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("KAKUREON"), 1730800832)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_HOWAWAN"), Volume(256))
  CH("KOARUHII"):SetManpu("MP_HEART")
  WINDOW:DrawFace(324, 88, SymAct("KOARUHII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KOARUHII"), 1275379459)
  subEveCloseMsg()
  WINDOW:DrawFaceF(20, 88, SymAct("MINEZUMI"), FACE_TYPE.EMOTION)
  WINDOW:Talk(SymAct("MINEZUMI"), 1428131394)
  WINDOW:CloseMessage()
  WINDOW:SetWaitMode(TimeSec(-1), TimeSec(-1))
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_HOWAWAN"), Volume(256))
  CH("WASHIBON"):SetManpu("MP_HEART")
  WINDOW:DrawFaceF(20, 88, SymAct("WASHIBON"), FACE_TYPE.SPECIAL01)
  WINDOW:Talk(SymAct("WASHIBON"), 442374277)
  WINDOW:Talk(SymAct("WASHIBON"), 54864324)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("HAADERIA"):SetManpu("MP_NOTICE_L")
  CH("HAADERIA"):WaitManpu()
  CH("KAKUREON"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  WINDOW:DrawFace(324, 88, SymAct("HAADERIA"), FACE_TYPE.EMOTION)
  WINDOW:Talk(SymAct("HAADERIA"), 677935623)
  WINDOW:CloseMessage()
  CH("WASHIBON"):DirLockOff()
  CH("HAADERIA"):DirLockOff()
  CH("KOARUHII"):DirLockOff()
  CH("MINEZUMI"):DirLockOff()
  CH("DANGORO"):DirLockOff()
  CH("KAKUREON"):DirLockOff()
  CH("WASHIBON"):WalkTo(SplinePath(SymPos("P00_WASHIBON"), SymPos("P01_WASHIBON")), Speed(2))
  TASK:Sleep(TimeSec(0.3))
  CH("HAADERIA"):WalkTo(SplinePath(SymPos("P00_HAADERIA"), SymPos("P01_HAADERIA")), Speed(2))
  TASK:Regist(subEveMoveDir, {
    CH("KOARUHII"),
    SymPos("P00_KOARUHII"),
    Speed(2),
    RotateTarget(-160)
  })
  TASK:Regist(subEveMoveDir, {
    CH("MINEZUMI"),
    SymPos("P00_MINEZUMI"),
    Speed(2),
    RotateTarget(-160)
  })
  TASK:Regist(subEveMoveDir, {
    CH("DANGORO"),
    SymPos("P00_DANGORO"),
    Speed(2),
    RotateTarget(-170)
  })
  TASK:Sleep(TimeSec(1))
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  CH("WASHIBON"):WaitMove()
  CH("WASHIBON"):DirTo(RotateTarget(-100), Speed(350), ROT_TYPE.NEAR)
  CH("HAADERIA"):WaitMove()
  CH("HAADERIA"):DirTo(RotateTarget(-135), Speed(350), ROT_TYPE.NEAR)
  CH("HAADERIA"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("SUWANNA"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("SUWANNA"), 829639494)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("DOTEKKOTSU"), FACE_TYPE.SPECIAL01)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), -1226090615)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 20, SymAct("DOKKORAA_2"), FACE_TYPE.SPECIAL01)
  WINDOW:Talk(SymAct("DOKKORAA_2"), -1343199544)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 20, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), -52872648)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("DOTEKKOTSU"), FACE_TYPE.SPECIAL01)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), -440267911)
  WINDOW:CloseMessage()
  CH("HAADERIA"):DirTo(CH("MINEZUMI"), Speed(350), ROT_TYPE.NEAR)
  CH("DANGORO"):DirTo(CH("MINEZUMI"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("KOARUHII"):DirTo(CH("MINEZUMI"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("MINEZUMI"):DirTo(CH("KOARUHII"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("WASHIBON"):DirTo(CH("MINEZUMI"), Speed(350), ROT_TYPE.NEAR)
  CH("WASHIBON"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("KOARUHII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KOARUHII"), -823174982)
  WINDOW:CloseMessage()
  CH("MINEZUMI"):WalkTo(SymPos("P01_MINEZUMI"), Speed(1.5))
  TASK:Sleep(TimeSec(0.3))
  CH("WASHIBON"):WalkTo(SymPos("P02_WASHIBON"), Speed(1.5))
  TASK:Sleep(TimeSec(0.1))
  CH("KOARUHII"):WalkTo(SymPos("P01_KOARUHII"), Speed(1.5))
  CH("DANGORO"):WalkTo(SymPos("P01_DANGORO"), Speed(1.5))
  TASK:Sleep(TimeSec(0.2))
  CH("HAADERIA"):WalkTo(SymPos("P02_HAADERIA"), Speed(1.5))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  FLAG.SceneFlag = CONST.FL_SC_01_END
  FLAG.SCENARIOFLAG = CONST.M03_BIRIJION_START
  SYSTEM:NextEntry()
end
function main03_birijion01_end()
end
function main03_birijion02_init()
end
function main03_birijion02_start()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  local taskDokkoraaS00 = function()
    function TaskL.Loop()
      CH("DOKKORAA_1"):SetManpu("MP_SPREE_LP")
      TASK:Sleep(TimeSec(0.7))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("DOKKORAA_1"):ResetManpu()
      TASK:Sleep(TimeSec(0.2))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("DOKKORAA_2"):SetManpu("MP_LAUGH_LP")
      TASK:Sleep(TimeSec(0.3))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.4))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("DOKKORAA_1"):ResetManpu()
      TASK:Sleep(TimeSec(0.3))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
    end
    function TaskL.Finish()
      CH("DOKKORAA_1"):ResetManpu()
      CH("DOKKORAA_2"):ResetManpu()
      return
    end
  end
  local taskMinezumi00 = function()
    function TaskL.Loop()
      CH("MINEZUMI"):SetManpu("MP_SPREE_LP")
      TASK:Sleep(TimeSec(0.5))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("MINEZUMI"):ResetManpu()
      TASK:Sleep(TimeSec(0.3))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
    end
    function TaskL.Finish()
      CH("MINEZUMI"):ResetManpu()
      return
    end
  end
  local taskDangoro00 = function()
    function TaskL.Loop()
      TASK:Sleep(TimeSec(0.3))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("DANGORO"):SetManpu("MP_SPREE_LP")
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("DANGORO"):ResetManpu()
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
    end
    function TaskL.Finish()
      CH("DANGORO"):ResetManpu()
      return
    end
  end
  local taskKoaruhii00 = function()
    function TaskL.Loop()
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("KOARUHII"):SetManpu("MP_LAUGH_LP")
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("KOARUHII"):ResetManpu()
    end
    function TaskL.Finish()
      CH("KOARUHII"):ResetManpu()
      return
    end
  end
  TASK:Regist(Group("grpDokkoraaS"), taskDokkoraaS00)
  TASK:Regist(Group("grpMinezumi"), taskMinezumi00)
  TASK:Regist(Group("grpDangoro"), taskDangoro00)
  TASK:Regist(Group("grpKoaruhii"), taskKoaruhii00)
  CH("SUWANNA"):SetMotionBlendMode(BlendMode.NONE)
  CH("DANGORO"):SetMotionBlendMode(BlendMode.NONE)
  CH("KOARUHII"):SetMotionBlendMode(BlendMode.NONE)
  CH("HAADERIA"):SetMotionBlendMode(BlendMode.NONE)
  CH("MINEZUMI"):SetMotionBlendMode(BlendMode.NONE)
  CH("WASHIBON"):SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  CH("DOTEKKOTSU"):SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  CH("DOKKORAA_1"):SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  CH("DOKKORAA_2"):SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  CH("BIRIJION"):SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(0.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SOUND:PlayBgm(SymSnd("BGM_MAP_TOWN_01"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_HOWAWAN"), Volume(256))
  CH("DOTEKKOTSU"):SetManpu("MP_HEART")
  TASK:Sleep(TimeSec(1.5))
  SOUND:PlaySe(SymSnd("SE_EVT_HOWAWAN"), Volume(256))
  CH("WASHIBON"):SetManpu("MP_HEART")
  TASK:Sleep(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_HOWAWAN"), Volume(256))
  CH("DOTEKKOTSU"):SetManpu("MP_HEART")
  CH("DOTEKKOTSU"):WaitManpu()
  TASK:ExitNotifyTasks(Group("grpDokkoraaS"))
  TASK:ExitNotifyTasks(Group("grpMinezumi"))
  TASK:ExitNotifyTasks(Group("grpDangoro"))
  TASK:ExitNotifyTasks(Group("grpKoaruhii"))
  TASK:WaitTask()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3.5))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_HOWAWAN"), Volume(256))
  CH("DOKKORAA_1"):SetManpu("MP_HEART")
  WINDOW:DrawFace(324, 20, SymAct("DOKKORAA_1"), FACE_TYPE.SPECIAL01)
  WINDOW:Talk(SymAct("DOKKORAA_1"), -671847941)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("BIRIJION"), -1732903108)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_HOWAWAN"), Volume(256))
  CH("DOTEKKOTSU"):SetManpu("MP_HEART")
  WINDOW:DrawFace(20, 20, SymAct("DOTEKKOTSU"), FACE_TYPE.SPECIAL01)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), -2119250307)
  subEveCloseMsg()
  CH("BIRIJION"):DirTo(CH("DOTEKKOTSU"), Speed(200), ROT_TYPE.NEAR)
  CH("BIRIJION"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.SPECIAL01)
  WINDOW:Talk(SymAct("BIRIJION"), -1434214978)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow(SymCam("CAMERA_03"), Speed(2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  CH("WASHIBON"):WalkTo(SymPos("P01_WASHIBON"), Speed(1.5))
  CH("WASHIBON"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_HOWAWAN"), Volume(256))
  CH("WASHIBON"):SetManpu("MP_HEART")
  WINDOW:DrawFace(324, 88, SymAct("WASHIBON"), FACE_TYPE.SPECIAL01)
  WINDOW:Talk(SymAct("WASHIBON"), -1281839873)
  WINDOW:CloseMessage()
  CH("BIRIJION"):DirTo(CH("WASHIBON"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("DOTEKKOTSU"):DirTo(CH("WASHIBON"), Speed(350), ROT_TYPE.NEAR)
  CH("DOKKORAA_1"):DirTo(CH("WASHIBON"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("DOKKORAA_2"):DirTo(CH("WASHIBON"), Speed(350), ROT_TYPE.NEAR)
  CH("BIRIJION"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.SPECIAL01)
  WINDOW:Talk(SymAct("BIRIJION"), 872460336)
  WINDOW:Talk(SymAct("BIRIJION"), 756777329)
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("BIRIJION"), -294873642)
  subEveCloseMsg()
  TASK:Regist(subEveDoubleJump, {
    CH("WASHIBON")
  })
  WINDOW:DrawFace(324, 88, SymAct("WASHIBON"), FACE_TYPE.SPECIAL01)
  WINDOW:Talk(SymAct("WASHIBON"), -143154025)
  WINDOW:Talk(SymAct("WASHIBON"), -598018220)
  WINDOW:Talk(SymAct("WASHIBON"), -985545195)
  WINDOW:KeyWait()
  TASK:Regist(subEveJump, {
    CH("WASHIBON")
  })
  WINDOW:Talk(SymAct("WASHIBON"), -1979690798)
  SOUND:PlaySe(SymSnd("SE_EVT_HOWAWAN"), Volume(256))
  CH("WASHIBON"):SetManpu("MP_HEART")
  WINDOW:CloseMessage()
  CH("DOKKORAA_1"):SetManpu("MP_SPREE_LP")
  TASK:Sleep(TimeSec(0.2))
  CH("KOARUHII"):SetManpu("MP_LAUGH_LP")
  TASK:Sleep(TimeSec(0.3))
  CH("DOKKORAA_2"):SetManpu("MP_LAUGH_LP")
  TASK:Sleep(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_HOWAWAN"), Volume(256))
  CH("WASHIBON"):SetManpu("MP_HEART")
  TASK:Sleep(TimeSec(0.4))
  SOUND:PlaySe(SymSnd("SE_EVT_HOWAWAN"), Volume(256))
  CH("DOTEKKOTSU"):SetManpu("MP_HEART")
  TASK:Sleep(TimeSec(0.5))
  SOUND:VolumeBgm(Volume(128), TimeSec(3))
  CAMERA:MoveFollow(SymCam("CAMERA_04"), Speed(0.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Sleep(TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  subEveFadeAfterTime()
  CAMERA:ResetAzimuthDifferenceVolume()
  FLAG.SceneFlag = CONST.FL_SC_02_END
  FLAG.SCENARIOFLAG = CONST.M03_BIRIJION_START
  SYSTEM:NextEntry()
end
function main03_birijion02_end()
end
function main03_birijion03_init()
end
function main03_birijion03_start()
  SOUND:PlayBgm(SymSnd("BGM_MAP_TOWN_01"), Volume(128))
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  subEveFadeAfterTime()
  WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1826922093, PARTNER_1 = -1204407728})
  WINDOW:SwitchTalk({PARTNER_0 = -1590885615, PARTNER_1 = 649404382})
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("EMONGA"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  CH("EMONGA"):WaitRotate()
  CH("NOKOTCHI"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(118, 8, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 1068379807, PARTNER_1 = 1456534195})
  WINDOW:CloseMessage()
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NOKOTCHI"), 1338754034)
  WINDOW:KeyWait()
  SOUND:PlaySe(SymSnd("SE_EVT_PO"), Volume(256))
  CH("NOKOTCHI"):SetManpu("MP_HEART")
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.SPECIAL01)
  WINDOW:Talk(SymAct("NOKOTCHI"), 1692831793)
  CH("NOKOTCHI"):WaitManpu()
  WINDOW:CloseMessage()
  CH("EMONGA"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("NOKOTCHI"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(324, 88, SymAct("EMONGA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EMONGA"), 2113773936)
  WINDOW:Talk(SymAct("EMONGA"), 851195831)
  subEveCloseMsg()
  WINDOW:DrawFace(72, 16, SymAct("HERO"), FACE_TYPE.NORMAL)
  WINDOW:Monologue(732366582)
  WINDOW:Monologue(9065781)
  subEveCloseMsg()
  CH("EMONGA"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  CH("EMONGA"):WaitRotate()
  subEveDoubleJump(CH("EMONGA"))
  CH("EMONGA"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(324, 88, SymAct("EMONGA"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("EMONGA"), 428958836)
  WINDOW:Talk(SymAct("EMONGA"), -1643546437)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("NOKOTCHI"):SetManpu("MP_SHOCK_R")
  TASK:Regist(subEveJumpSurprise, {
    CH("NOKOTCHI")
  })
  CH("PARTNER"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  CH("NOKOTCHI"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("NOKOTCHI"), -2028844550)
  WINDOW:KeyWait()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("NOKOTCHI"):SetManpu("MP_FLY_SWEAT")
  WINDOW:Talk(SymAct("NOKOTCHI"), -888681974)
  WINDOW:Talk(SymAct("NOKOTCHI"), -769852597)
  CH("NOKOTCHI"):SetFacialMotion(FACIAL_MOTION.SAD)
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("NOKOTCHI"), -114186104)
  WINDOW:Talk(SymAct("NOKOTCHI"), -534079031)
  subEveCloseMsg()
  CH("NOKOTCHI"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("EMONGA"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  WINDOW:DrawFace(118, 8, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1351938290, PARTNER_1 = -1234158001})
  WINDOW:SwitchTalk({PARTNER_0 = -1654821492, PARTNER_1 = -2075763507})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("NOKOTCHI"):SetManpu("MP_SHOCK_L")
  CH("NOKOTCHI"):WaitManpu()
  TASK:Regist(subEveJumpSurprise, {
    CH("NOKOTCHI")
  })
  CH("NOKOTCHI"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("NOKOTCHI"), 64897026)
  subEveCloseMsg()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(118, 8, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  WINDOW:SwitchTalk({PARTNER_0 = 449147203, PARTNER_1 = 1941679471})
  WINDOW:CloseMessage()
  CH("NOKOTCHI"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.7))
  CH("PARTNER"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("EMONGA"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.8))
  CH("PARTNER"):DirTo(RotateTarget(-135), Speed(350), ROT_TYPE.RIGHT)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 1788910638, PARTNER_1 = 1099812845})
  WINDOW:CloseMessage()
  CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(1.5))
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(SymPos("P00_PARTNER"), Speed(200), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.6))
  CH("NOKOTCHI"):DirTo(RotateTarget(-135), Speed(60), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.5))
  CH("HERO"):WalkTo(SymPos("P00_HERO"), Speed(1.5))
  TASK:Sleep(TimeSec(0.2))
  CH("EMONGA"):WalkTo(SymPos("P00_PARTNER"), Speed(1.5))
  TASK:Sleep(TimeSec(1))
  TASK:Regist(subEveJump, {
    CH("NOKOTCHI")
  })
  WINDOW:DrawFace(324, 88, SymAct("NOKOTCHI"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("NOKOTCHI"), 1486290604)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("NOKOTCHI"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  CH("NOKOTCHI"):SetManpu("MP_FLY_SWEAT")
  CH("NOKOTCHI"):WaitManpu()
  CH("NOKOTCHI"):DirTo(RotateTarget(-45), Speed(500), ROT_TYPE.NEAR)
  CH("NOKOTCHI"):WaitRotate()
  TASK:Sleep(TimeSec(0.2))
  CH("NOKOTCHI"):DirTo(RotateTarget(135), Speed(500), ROT_TYPE.NEAR)
  CH("NOKOTCHI"):WaitRotate()
  TASK:Sleep(TimeSec(0.2))
  CH("NOKOTCHI"):DirTo(RotateTarget(-135), Speed(500), ROT_TYPE.NEAR)
  CH("NOKOTCHI"):WaitRotate()
  TASK:Sleep(TimeSec(0.4))
  CH("NOKOTCHI"):WalkTo(SymPos("P00_HERO"), Speed(2))
  TASK:Sleep(TimeSec(0.5))
  SOUND:FadeOutBgm(TimeSec(2))
  SCREEN_A:FadeOut(TimeSec(1), true)
  TASK:Sleep(TimeSec(1))
  SOUND:WaitBgm()
  FLAG.SceneFlag = CONST.FL_SC_03_END
  FLAG.SCENARIOFLAG = CONST.M03_BIRIJION_START
  SYSTEM:NextEntry()
end
function main03_birijion03_end()
end
function main03_birijion04_init()
end
function main03_birijion04_start()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("KOMATANA_1"):SetVisible(false)
  CH("KOMATANA_2"):SetVisible(false)
  CH("DANGORO"):SetMotionBlendMode(BlendMode.NONE)
  CH("KOARUHII"):SetMotionBlendMode(BlendMode.NONE)
  CH("HAADERIA"):SetMotionBlendMode(BlendMode.NONE)
  CH("MINEZUMI"):SetMotionBlendMode(BlendMode.NONE)
  CH("WASHIBON"):SetMotionBlendMode(BlendMode.NONE)
  CH("SUWANNA"):SetMotionBlendMode(BlendMode.NONE)
  CH("DOTEKKOTSU"):SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  CH("DOKKORAA_1"):SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  CH("DOKKORAA_2"):SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  CH("BIRIJION"):SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  CH("HERO"):SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  CH("PARTNER"):SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  CH("EMONGA"):SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  CH("NOKOTCHI"):SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  subEveFadeAfterTime()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 399992939, PARTNER_1 = 248273194})
  WINDOW:SwitchTalk({PARTNER_0 = 635505385, PARTNER_1 = 1023032232})
  WINDOW:SwitchTalk({PARTNER_0 = -1151195289, PARTNER_1 = -1569122778})
  subEveCloseMsg()
  WINDOW:DrawFace(272, 16, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), 1628308097)
  WINDOW:Talk(SymAct("BIRIJION"), 2014655424)
  WINDOW:Talk(SymAct("BIRIJION"), 1396203523)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_QUESTION")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 1243828546, PARTNER_1 = 90359685})
  subEveCloseMsg()
  WINDOW:DrawFace(272, 16, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), 477755076)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.NORMAL)
  WINDOW:Monologue(928294151)
  WINDOW:CloseMessage()
  CH("EMONGA"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("EMONGA"):WaitRotate()
  CH("HERO"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  CH("NOKOTCHI"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  CH("WASHIBON"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  CH("DOTEKKOTSU"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  CH("BIRIJION"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("DOKKORAA_2"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  CH("DOKKORAA_1"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(20, 20, SymAct("EMONGA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EMONGA"), 776967238)
  WINDOW:CloseMessage()
  CH("EMONGA"):DirTo(CH("HAADERIA"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):DirTo(CH("HAADERIA"), Speed(350), ROT_TYPE.NEAR)
  CH("BIRIJION"):DirTo(CH("HAADERIA"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):DirTo(CH("HAADERIA"), Speed(350), ROT_TYPE.NEAR)
  CH("NOKOTCHI"):DirTo(CH("HAADERIA"), Speed(350), ROT_TYPE.NEAR)
  CH("WASHIBON"):DirTo(CH("HAADERIA"), Speed(350), ROT_TYPE.NEAR)
  CH("DOTEKKOTSU"):DirTo(CH("HAADERIA"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("DOKKORAA_2"):DirTo(CH("HAADERIA"), Speed(350), ROT_TYPE.NEAR)
  CH("DOKKORAA_1"):DirTo(CH("HAADERIA"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(324, 88, SymAct("HAADERIA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("HAADERIA"), -1445492599)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  CAMERA:ResetAzimuthDifferenceVolume()
  FLAG.SceneFlag = CONST.FL_SC_04_END
  FLAG.SCENARIOFLAG = CONST.M03_BIRIJION_START
  SYSTEM:NextEntry()
end
function main03_birijion04_end()
end
function main03_birijion05_init()
end
function main03_birijion05_start()
  MAP:SetVisible(false)
  MAP:SetBG(SymMap("IM03_01_RAINBOW"))
  SOUND:PlayBgm(SymSnd("BGM_EVE_METAMORPHOSIS_02"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  subEveFadeAfterTime()
  WINDOW:DrawFace(324, 88, SymAct("HAADERIA"), FACE_TYPE.EMOTION)
  WINDOW:Talk(SymAct("HAADERIA"), -1328760376)
  WINDOW:Talk(SymAct("HAADERIA"), -642619932)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("WASHIBON"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("WASHIBON"), -1062644571)
  WINDOW:Talk(SymAct("WASHIBON"), -343668890)
  WINDOW:Talk(SymAct("WASHIBON"), -224446937)
  WINDOW:Talk(SymAct("WASHIBON"), -1109483296)
  WINDOW:Talk(SymAct("WASHIBON"), -1530555999)
  WINDOW:Talk(SymAct("WASHIBON"), -1880571294)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  MAP:SetVisible(true)
  MAP:SetVisibleBG(false)
  FLAG.SceneFlag = CONST.FL_SC_05_END
  FLAG.SCENARIOFLAG = CONST.M03_BIRIJION_START
  SYSTEM:NextEntry()
end
function main03_birijion05_end()
end
function main03_birijion06_init()
end
function main03_birijion06_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_METAMORPHOSIS_02"), Volume(256))
  CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("KOMATANA_1"):SetVisible(false)
  CH("KOMATANA_2"):SetVisible(false)
  CH("DANGORO"):SetMotionBlendMode(BlendMode.NONE)
  CH("KOARUHII"):SetMotionBlendMode(BlendMode.NONE)
  CH("HAADERIA"):SetMotionBlendMode(BlendMode.NONE)
  CH("MINEZUMI"):SetMotionBlendMode(BlendMode.NONE)
  CH("WASHIBON"):SetMotionBlendMode(BlendMode.NONE)
  CH("SUWANNA"):SetMotionBlendMode(BlendMode.NONE)
  CH("DOTEKKOTSU"):SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  CH("DOKKORAA_1"):SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  CH("DOKKORAA_2"):SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  CH("BIRIJION"):SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  CH("HERO"):SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  CH("PARTNER"):SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  CH("EMONGA"):SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  CH("NOKOTCHI"):SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  GM("CRYSTAL_BIG"):SetVisible(false)
  local taskEffTwinkle = function()
    function TaskL.Loop()
      EFFECT:Create("effectTwinkle_00", SymEff("EV_GLITTER"))
      EFFECT:SetPosition("effectTwinkle_00", SymPos("P_EFF_GLITTER"))
      EFFECT:Play("effectTwinkle_00")
      TASK:Sleep(TimeSec(2.5))
    end
  end
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  subEveFadeAfterTime()
  WINDOW:DrawFace(324, 88, SymAct("HAADERIA"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("HAADERIA"), -1762397405)
  WINDOW:Talk(SymAct("HAADERIA"), 292286444)
  WINDOW:Talk(SymAct("HAADERIA"), 141614765)
  subEveCloseMsg()
  WINDOW:DrawFace(118, 8, SymAct("BIRIJION"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("BIRIJION"), -2116979278)
  WINDOW:Talk(SymAct("BIRIJION"), -1731574541)
  WINDOW:Talk(SymAct("BIRIJION"), -1276700880)
  WINDOW:Talk(SymAct("BIRIJION"), -1426315663)
  subEveCloseMsg()
  SOUND:FadeOutBgm(TimeSec(2))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SAD)
  WINDOW:SwitchTalk({PARTNER_0 = -440553290, PARTNER_1 = -56196617})
  WINDOW:SwitchTalk({PARTNER_0 = -678702540, PARTNER_1 = -829365387})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  CH("PARTNER"):DirTo(CH("BIRIJION"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("BIRIJION"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("EMONGA"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("HAADERIA"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("NOKOTCHI"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("WASHIBON"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("DOTEKKOTSU"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("DOKKORAA_2"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("DOKKORAA_1"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Regist(subEveJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 1225326522, PARTNER_1 = 1343475451})
  WINDOW:SwitchTalk({PARTNER_0 = 963449559, PARTNER_1 = 544613270})
  WINDOW:SwitchTalk({PARTNER_0 = 190541909, PARTNER_1 = 306200852})
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  subEveJumpSurprise(CH("NOKOTCHI"))
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("NOKOTCHI"):SetManpu("MP_FLY_SWEAT")
  CH("BIRIJION"):SetManpu("MP_QUESTION")
  CH("BIRIJION"):WaitManpu()
  WINDOW:DrawFace(272, 16, SymAct("BIRIJION"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("BIRIJION"), 1560401875)
  subEveCloseMsg()
  TASK:Regist(subEveNod, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 1142613650, PARTNER_1 = 1865921873})
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("BIRIJION"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  CH("EMONGA"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  CH("DOKKORAA_1"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  CH("DOKKORAA_2"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("DOTEKKOTSU"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  CH("NOKOTCHI"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  CH("WASHIBON"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  CH("KOARUHII"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  CH("HAADERIA"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  CH("KOARUHII"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.7))
  CH("NOKOTCHI"):DirTo(CH("BIRIJION"), Speed(350), ROT_TYPE.NEAR)
  CH("NOKOTCHI"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("NOKOTCHI"):SetManpu("MP_FLY_SWEAT")
  CH("NOKOTCHI"):WaitManpu()
  TASK:Sleep(TimeSec(0.2))
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("NOKOTCHI"):SetPosition(SymPos("P01_NOKOTCHI"))
  CH("HERO"):DirLockToChara(CH("NOKOTCHI"))
  CH("PARTNER"):DirLockToChara(CH("NOKOTCHI"))
  CH("EMONGA"):DirLockToChara(CH("NOKOTCHI"))
  CH("WASHIBON"):DirLockToChara(CH("NOKOTCHI"))
  CH("HAADERIA"):DirLockToChara(CH("NOKOTCHI"))
  CH("KOARUHII"):DirLockToChara(CH("NOKOTCHI"))
  CH("NOKOTCHI"):WalkTo(SymPos("P02_NOKOTCHI"), Speed(1.5))
  CH("NOKOTCHI"):WaitMove()
  CH("HERO"):DirLockOff()
  CH("PARTNER"):DirLockOff()
  CH("EMONGA"):DirLockOff()
  CH("WASHIBON"):DirLockOff()
  CH("HAADERIA"):DirLockOff()
  CH("KOARUHII"):DirLockOff()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("NOKOTCHI"):SetManpu("MP_FLY_SWEAT")
  CH("NOKOTCHI"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.SPECIAL01)
  WINDOW:Talk(SymAct("NOKOTCHI"), 1982628880)
  WINDOW:Talk(SymAct("NOKOTCHI"), -239822625)
  WINDOW:CloseMessage()
  CH("NOKOTCHI"):WalkTo(SymPos("P03_NOKOTCHI"), Speed(1.5))
  CH("EMONGA"):DirTo(RotateTarget(80), Speed(200), ROT_TYPE.NEAR)
  CH("NOKOTCHI"):WaitMove()
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_HAND"), Volume(256))
  GM("CRYSTAL_BIG"):SetVisible(true)
  TASK:Sleep(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_KIRAN"), Volume(256))
  TASK:Regist(Group("yuka"), taskEffTwinkle)
  CH("NOKOTCHI"):WalkTo(SymPos("P02_NOKOTCHI"), Speed(1.5), LINK_DIR.OFF)
  CH("NOKOTCHI"):WaitMove()
  CH("NOKOTCHI"):SetMotionRaito(Raito(1.5))
  CH("NOKOTCHI"):SetMotion(SymMot("ENDURE"), LOOP.OFF)
  CH("NOKOTCHI"):WaitPlayMotion()
  CH("NOKOTCHI"):SetManpu("MP_FLY_SWEAT")
  CH("NOKOTCHI"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("NOKOTCHI"):SetMotionRaito(Raito(1))
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.SHOUT)
  WINDOW:Talk(SymAct("NOKOTCHI"), -391140962)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("BIRIJION"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("BIRIJION"), 1326235036)
  WINDOW:CloseMessage()
  TASK:Regist(subEveJump, {
    CH("NOKOTCHI")
  })
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.SHOUT)
  WINDOW:Talk(SymAct("NOKOTCHI"), 1444383965)
  WINDOW:KeyWait()
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  TASK:Regist(subEveDoubleJump, {
    CH("NOKOTCHI")
  })
  WINDOW:Talk(SymAct("NOKOTCHI"), 2101010206)
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(CH("BIRIJION"), Speed(350), ROT_TYPE.NEAR)
  CH("KOARUHII"):DirTo(CH("BIRIJION"), Speed(350), ROT_TYPE.NEAR)
  CH("MINEZUMI"):DirTo(CH("BIRIJION"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("BIRIJION"), Speed(350), ROT_TYPE.NEAR)
  CH("EMONGA"):DirTo(CH("BIRIJION"), Speed(350), ROT_TYPE.NEAR)
  CH("HAADERIA"):DirTo(CH("BIRIJION"), Speed(350), ROT_TYPE.NEAR)
  CH("KOARUHII"):DirTo(CH("BIRIJION"), Speed(350), ROT_TYPE.NEAR)
  CH("WASHIBON"):DirTo(CH("BIRIJION"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  TASK:Sleep(TimeSec(1))
  WINDOW:DrawFace(324, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), 1679945311)
  WINDOW:DrawFace(324, 88, SymAct("BIRIJION"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("BIRIJION"), 727742616)
  WINDOW:Talk(SymAct("BIRIJION"), 846940633)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CAMERA:MoveFollow2(SymCam("CAMERA_00"), Speed(15, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  TASK:Regist(subEveJumpSurprise, {
    CH("NOKOTCHI")
  })
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  CH("HAADERIA"):SetManpu("MP_SHOCK_L")
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("EMONGA"):SetManpu("MP_SHOCK_R")
  TASK:Regist(subEveJumpSurprise, {
    CH("DOKKORAA_1")
  })
  CH("WASHIBON"):SetManpu("MP_EXCLAMATION")
  CH("MINEZUMI"):SetManpu("MP_SHOCK_R")
  CH("HAADERIA"):SetManpu("MP_SHOCK_L")
  CH("DOTEKKOTSU"):SetManpu("MP_EXCLAMATION")
  CAMERA:WaitMove()
  CH("EMONGA"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 425073178, PARTNER_1 = 5057371})
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("NOKOTCHI"):SetShake(Vector(0.005, 0, 0), TimeSec(0.2, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(324, 88, SymAct("BIRIJION"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("BIRIJION"), -2016069740)
  WINDOW:CloseMessage()
  local taskNokotchi00 = function()
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
    CH("NOKOTCHI"):SetManpu("MP_FLY_SWEAT")
    CH("NOKOTCHI"):WaitManpu()
    CH("NOKOTCHI"):DirTo(RotateTarget(-160), Speed(600), ROT_TYPE.NEAR)
    CH("NOKOTCHI"):WaitRotate()
    CH("NOKOTCHI"):DirTo(RotateTarget(110), Speed(600), ROT_TYPE.NEAR)
    CH("NOKOTCHI"):WaitRotate()
    CH("NOKOTCHI"):DirTo(CH("BIRIJION"), Speed(600), ROT_TYPE.NEAR)
    CH("NOKOTCHI"):WaitRotate()
    SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
    CH("NOKOTCHI"):SetManpu("MP_FLY_SWEAT")
    CH("NOKOTCHI"):WaitManpu()
  end
  TASK:Regist(taskNokotchi00)
  CH("NOKOTCHI"):SetFacialMotion(FACIAL_MOTION.SAD)
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("NOKOTCHI"), -1630665003)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("BIRIJION"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("BIRIJION"), -139404551)
  WINDOW:Talk(SymAct("BIRIJION"), -290722888)
  WINDOW:Talk(SymAct("BIRIJION"), -981026693)
  WINDOW:Talk(SymAct("BIRIJION"), -593655494)
  WINDOW:CloseMessage()
  CH("EMONGA"):SetFacialMotion(FACIAL_MOTION.SAD)
  CH("EMONGA"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  CH("KOARUHII"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("NOKOTCHI"):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("NOKOTCHI"), -1814290435)
  CH("NOKOTCHI"):WaitManpu()
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("EMONGA"):SetManpu("MP_FLY_SWEAT")
  CH("EMONGA"):WaitManpu()
  WINDOW:DrawFace(226, 8, SymAct("EMONGA"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("EMONGA"), -1966657860)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("NOKOTCHI"):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("NOKOTCHI"), -1578467969)
  WINDOW:CloseMessage()
  CH("NOKOTCHI"):ResetShake()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("MINEZUMI"):SetDir(CH("NOKOTCHI"))
  CH("DOKKORAA_1"):SetDir(CH("NOKOTCHI"))
  CH("DOKKORAA_2"):SetDir(CH("NOKOTCHI"))
  CH("DOTEKKOTSU"):SetDir(CH("NOKOTCHI"))
  CH("HAADERIA"):SetDir(CH("NOKOTCHI"))
  CH("WASHIBON"):SetDir(CH("NOKOTCHI"))
  CH("HERO"):DirLockToChara(CH("NOKOTCHI"))
  CH("PARTNER"):DirLockToChara(CH("NOKOTCHI"))
  CH("EMONGA"):DirLockToChara(CH("NOKOTCHI"))
  CH("KOARUHII"):DirLockToChara(CH("NOKOTCHI"))
  CH("MINEZUMI"):DirLockToChara(CH("NOKOTCHI"))
  CH("BIRIJION"):DirLockToChara(CH("NOKOTCHI"))
  CH("HAADERIA"):DirLockToChara(CH("NOKOTCHI"))
  CH("DOKKORAA_1"):DirLockToChara(CH("NOKOTCHI"))
  CH("DOKKORAA_2"):DirLockToChara(CH("NOKOTCHI"))
  CH("DOTEKKOTSU"):DirLockToChara(CH("NOKOTCHI"))
  CH("WASHIBON"):DirLockToChara(CH("NOKOTCHI"))
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_01"), Volume(256))
  CH("NOKOTCHI"):SetManpu("MP_FLY_SWEAT_LP")
  CH("NOKOTCHI"):SetFacialMotion(FACIAL_MOTION.SHOUT)
  TASK:Regist(subEveJumpSurprise, {
    CH("NOKOTCHI")
  })
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.WEEP)
  WINDOW:Talk(SymAct("NOKOTCHI"), -1192145858)
  WINDOW:CloseMessage()
  CH("EMONGA"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  SOUND:PlaySe(SymSnd("SE_EVT_RUN_ESCAPE"), Volume(256))
  CH("NOKOTCHI"):RunTo(SymPos("P04_NOKOTCHI"), Speed(4))
  CH("HERO"):WalkTo(SymPos("P01_HERO"), Speed(1.5), LINK_DIR.OFF)
  CH("PARTNER"):WalkTo(SymPos("P01_PARTNER"), Speed(1.5), LINK_DIR.OFF)
  TASK:Sleep(TimeSec(0.7))
  CH("EMONGA"):WalkTo(SymPos("P01_EMONGA"), Speed(2))
  CH("EMONGA"):WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("EMONGA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("EMONGA"), 1063866609)
  WINDOW:CloseMessage()
  CH("NOKOTCHI"):WaitMove()
  CH("NOKOTCHI"):ResetManpu()
  CH("NOKOTCHI"):SetVisible(false)
  CH("HERO"):DirLockOff()
  CH("PARTNER"):DirLockOff()
  CH("EMONGA"):DirLockOff()
  CH("KOARUHII"):DirLockOff()
  CH("MINEZUMI"):DirLockOff()
  CH("BIRIJION"):DirLockOff()
  CH("HAADERIA"):DirLockOff()
  CH("DOKKORAA_1"):DirLockOff()
  CH("DOKKORAA_2"):DirLockOff()
  CH("DOTEKKOTSU"):DirLockOff()
  CH("WASHIBON"):DirLockOff()
  CH("EMONGA"):SetFacialMotion(FACIAL_MOTION.ANGRY)
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  CH("EMONGA"):DirTo(CH("BIRIJION"), Speed(350), ROT_TYPE.NEAR)
  CH("EMONGA"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  CH("EMONGA"):SetManpu("MP_ANGRY_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("EMONGA")
  })
  WINDOW:DrawFace(20, 88, SymAct("EMONGA"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("EMONGA"), 645030320)
  CH("HERO"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  CH("NOKOTCHI"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  CH("WASHIBON"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  CH("DOTEKKOTSU"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  CH("BIRIJION"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("DOKKORAA_2"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  CH("DOKKORAA_1"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  CH("HAADERIA"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:Talk(SymAct("EMONGA"), -452627177)
  WINDOW:CloseMessage()
  CH("EMONGA"):ResetManpu()
  CH("EMONGA"):DirTo(CH("NOKOTCHI"), Speed(500), ROT_TYPE.NEAR)
  CH("EMONGA"):WaitRotate()
  TASK:Sleep(TimeSec(0.5))
  CH("EMONGA"):DirTo(CH("BIRIJION"), Speed(500), ROT_TYPE.NEAR)
  CH("EMONGA"):WaitRotate()
  TASK:Sleep(TimeSec(0.5))
  CH("EMONGA"):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFace(20, 88, SymAct("EMONGA"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("EMONGA"), -65125290)
  CH("EMONGA"):WaitManpu()
  WINDOW:CloseMessage()
  CH("EMONGA"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  CH("HERO"):DirLockToChara(CH("EMONGA"))
  CH("PARTNER"):DirLockToChara(CH("EMONGA"))
  CH("KOARUHII"):DirLockToChara(CH("EMONGA"))
  CH("MINEZUMI"):DirLockToChara(CH("EMONGA"))
  CH("BIRIJION"):DirLockToChara(CH("EMONGA"))
  CH("HAADERIA"):DirLockToChara(CH("EMONGA"))
  CH("DOKKORAA_1"):DirLockToChara(CH("EMONGA"))
  CH("DOKKORAA_2"):DirLockToChara(CH("EMONGA"))
  CH("DOTEKKOTSU"):DirLockToChara(CH("EMONGA"))
  CH("WASHIBON"):DirLockToChara(CH("EMONGA"))
  TASK:Regist(subEveRunDir2, {
    CH("EMONGA"),
    SymPos("P04_NOKOTCHI"),
    Speed(4),
    RotateTarget(45)
  })
  TASK:WaitTask()
  CH("EMONGA"):SetVisible(false)
  CH("HERO"):DirLockOff()
  CH("PARTNER"):DirLockOff()
  CH("KOARUHII"):DirLockOff()
  CH("MINEZUMI"):DirLockOff()
  CH("BIRIJION"):DirLockOff()
  CH("HAADERIA"):DirLockOff()
  CH("DOKKORAA_1"):DirLockOff()
  CH("DOKKORAA_2"):DirLockOff()
  CH("DOTEKKOTSU"):DirLockOff()
  CH("WASHIBON"):DirLockOff()
  TASK:Sleep(TimeSec(1.5))
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.ANGRY)
  CH("PARTNER"):WalkTo(SymPos("P02_PARTNER"), Speed(1.5))
  TASK:Sleep(TimeSec(0.3))
  CH("HERO"):DirTo(CH("BIRIJION"), Speed(350), ROT_TYPE.NEAR)
  CH("KOARUHII"):DirTo(CH("BIRIJION"), Speed(350), ROT_TYPE.NEAR)
  CH("MINEZUMI"):DirTo(CH("BIRIJION"), Speed(350), ROT_TYPE.NEAR)
  CH("DOKKORAA_1"):DirTo(CH("BIRIJION"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HAADERIA"):DirTo(CH("BIRIJION"), Speed(350), ROT_TYPE.NEAR)
  CH("KOARUHII"):DirTo(CH("BIRIJION"), Speed(350), ROT_TYPE.NEAR)
  CH("WASHIBON"):DirTo(CH("BIRIJION"), Speed(350), ROT_TYPE.NEAR)
  CH("DOTEKKOTSU"):DirTo(CH("BIRIJION"), Speed(350), ROT_TYPE.NEAR)
  CH("DOKKORAA_2"):DirTo(CH("BIRIJION"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.ANGRY)
  WINDOW:SwitchTalk({PARTNER_0 = -684517483, PARTNER_1 = -836229420})
  WINDOW:SwitchTalk({PARTNER_0 = -2123780077, PARTNER_1 = -1737326254})
  WINDOW:CloseMessage()
  CH("BIRIJION"):DirTo(CH("PARTNER"), Speed(200), ROT_TYPE.NEAR)
  CH("BIRIJION"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("BIRIJION"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("BIRIJION"), -1285565807)
  WINDOW:Talk(SymAct("BIRIJION"), -1438325808)
  WINDOW:Talk(SymAct("BIRIJION"), 769457951)
  WINDOW:Talk(SymAct("BIRIJION"), 885509726)
  WINDOW:Talk(SymAct("BIRIJION"), 1572409970)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SAD)
  WINDOW:SwitchTalk({PARTNER_0 = 1151476531, PARTNER_1 = 1871671536})
  WINDOW:CloseMessage()
  WINDOW:DrawFace(324, 88, SymAct("BIRIJION"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("BIRIJION"), 1989427633)
  WINDOW:CloseMessage()
  CH("HERO"):DirLockToChara(CH("BIRIJION"))
  CH("PARTNER"):DirLockToChara(CH("BIRIJION"))
  CH("KOARUHII"):DirLockToChara(CH("BIRIJION"))
  CH("MINEZUMI"):DirLockToChara(CH("BIRIJION"))
  CH("HAADERIA"):DirLockToChara(CH("BIRIJION"))
  CH("DOKKORAA_1"):DirLockToChara(CH("BIRIJION"))
  CH("DOKKORAA_2"):DirLockToChara(CH("BIRIJION"))
  CH("DOTEKKOTSU"):DirLockToChara(CH("BIRIJION"))
  CH("WASHIBON"):DirLockToChara(CH("BIRIJION"))
  CH("BIRIJION"):WalkTo(SplinePath(SymPos("P01_BIRIJION"), SymPos("P02_BIRIJION")), Speed(1.2))
  CH("BIRIJION"):WaitMove()
  CH("HERO"):DirLockOff()
  CH("PARTNER"):DirLockOff()
  CH("KOARUHII"):DirLockOff()
  CH("MINEZUMI"):DirLockOff()
  CH("HAADERIA"):DirLockOff()
  CH("DOKKORAA_1"):DirLockOff()
  CH("DOKKORAA_2"):DirLockOff()
  CH("DOTEKKOTSU"):DirLockOff()
  CH("WASHIBON"):DirLockOff()
  TASK:Sleep(TimeSec(1))
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CH("KOMATANA_1"):SetVisible(true)
  CH("KOMATANA_2"):SetVisible(true)
  CH("DOTEKKOTSU"):WalkTo(SymPos("P01_DOTEKKOTSU"), Speed(4))
  CH("DOTEKKOTSU"):WaitMove()
  CH("DOTEKKOTSU"):DirTo(RotateTarget(20), Speed(500), ROT_TYPE.NEAR)
  CH("DOTEKKOTSU"):WaitRotate()
  CH("DOTEKKOTSU"):SetMotionRaito(Raito(2))
  CH("DOTEKKOTSU"):SetMotion(SymMot("VICTORY"), LOOP.OFF)
  CAMERA:MoveFollow2(SymCam("CAMERA_00"), Speed(12, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SOUND:PlaySe(SymSnd("SE_EVT_PARTY_02"), Volume(256))
  TASK:Regist(subEveDoubleJump, {
    CH("DOKKORAA_1")
  })
  CH("DOKKORAA_1"):SetManpu("MP_SPREE_LP")
  local task3hikiWaiwai = function()
    function TaskL.Loop()
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      subEveDoubleJump(CH("WASHIBON"))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.1))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("KOARUHII"):SetManpu("MP_SPREE_LP")
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.2))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("MINEZUMI"):SetManpu("MP_LAUGH_LP")
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("WASHIBON"):SetManpu("MP_LAUGH_LP")
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("KOARUHII"):ResetManpu()
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.2))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.2))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("WASHIBON"):ResetManpu()
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      subEveNodDouble(CH("MINEZUMI"))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.2))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("MINEZUMI"):ResetManpu()
    end
    function TaskL.Finish()
      CH("WASHIBON"):ResetManpu()
      CH("KOARUHII"):ResetManpu()
      CH("MINEZUMI"):ResetManpu()
      return
    end
  end
  TASK:Regist(Group("grp3hiki"), task3hikiWaiwai)
  WINDOW:DrawFace(118, 8, SymAct("DOTEKKOTSU"), FACE_TYPE.GLADNESS)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), 970315638)
  CH("DOTEKKOTSU"):WaitPlayMotion()
  CH("DOTEKKOTSU"):SetManpu("MP_SPREE_LP")
  WINDOW:CloseMessage()
  CAMERA:WaitMove()
  SOUND:PlayBgm(SymSnd("BGM_EVE_COMICAL"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):SetManpu("MP_SHOCK_R")
  CH("PARTNER"):WaitManpu()
  CH("PARTNER"):DirTo(CH("DOTEKKOTSU"), Speed(500), ROT_TYPE.NEAR)
  CH("HERO"):DirTo(CH("DOTEKKOTSU"), Speed(500), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  TASK:Regist(subEveDoubleJump, {
    CH("WASHIBON")
  })
  WINDOW:DrawFace(20, 20, SymAct("WASHIBON"), FACE_TYPE.SHOUT)
  WINDOW:Talk(SymAct("WASHIBON"), 550430263)
  WINDOW:CloseMessage()
  CH("WASHIBON"):DirTo(CH("KOARUHII"), Speed(350), ROT_TYPE.NEAR)
  CH("KOARUHII"):DirTo(CH("WASHIBON"), Speed(350), ROT_TYPE.NEAR)
  CH("DANGORO"):DirTo(CH("WASHIBON"), Speed(350), ROT_TYPE.NEAR)
  CH("MINEZUMI"):DirTo(CH("KOARUHII"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(1))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SWEAT"), Volume(256))
  CH("HERO"):SetManpu("MP_SWEAT_L_AL")
  CH("PARTNER"):SetManpu("MP_SWEAT_L_AL")
  CH("PARTNER"):WaitManpu()
  TASK:Sleep(TimeSec(0.5))
  CH("DOTEKKOTSU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("DOTEKKOTSU"):SetMotionRaito(Raito(1))
  CAMERA:MoveFollow2(SymCam("CAMERA_04"), Speed(2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  CH("KOMATANA_2"):DirTo(CH("KOMATANA_1"), Speed(350), ROT_TYPE.NEAR)
  CH("KOMATANA_2"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("KOMATANA_2"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("???"), 199472628)
  WINDOW:CloseMessage()
  CH("KOMATANA_1"):DirTo(CH("KOMATANA_2"), Speed(350), ROT_TYPE.NEAR)
  CH("KOMATANA_1"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("KOMATANA_1"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("???"), 318276789)
  WINDOW:DrawFace(324, 88, SymAct("KOMATANA_1"), FACE_TYPE.SPECIAL01)
  WINDOW:Talk(SymAct("???"), -1788831622)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("KOMATANA_2"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("???"), -1938052805)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("KOMATANA_1"), FACE_TYPE.SPECIAL01)
  WINDOW:Talk(SymAct("???"), -1066521909)
  WINDOW:CloseMessage()
  CH("KOMATANA_1"):DirTo(SymPos("P01_KOMATANA_1"), Speed(500), ROT_TYPE.RIGHT)
  CH("KOMATANA_1"):WaitRotate()
  CH("KOMATANA_1"):WalkTo(SplinePath(SymPos("P01_KOMATANA_1"), SymPos("P02_KOMATANA_1")), Speed(1.5))
  TASK:Sleep(TimeSec(0.2))
  CH("KOMATANA_2"):WalkTo(SplinePath(SymPos("P01_KOMATANA_2"), SymPos("P02_KOMATANA_2")), Speed(1.5))
  TASK:Sleep(TimeSec(2.5))
  CAMERA:MoveFollow2(SymCam("CAMERA_00"), Speed(2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  CH("KOMATANA_1"):SetVisible(false)
  CH("KOMATANA_2"):SetVisible(false)
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):DirTo(CH("MINEZUMI"), Speed(500), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):DirTo(CH("HAADERIA"), Speed(500), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):DirTo(CH("DOTEKKOTSU"), Speed(500), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  CH("HAADERIA"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -646636662, PARTNER_1 = -229095351})
  WINDOW:SwitchTalk({PARTNER_0 = -347899640, PARTNER_1 = -1543311409})
  WINDOW:CloseMessage()
  CH("DOKKORAA_1"):ResetManpu()
  CH("DOKKORAA_2"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("DOKKORAA_2"):WaitRotate()
  CH("HERO"):DirTo(CH("DOKKORAA_2"), Speed(350), ROT_TYPE.NEAR)
  CH("DOTEKKOTSU"):ResetManpu()
  CH("DOTEKKOTSU"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("DOKKORAA_1"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(324, 20, SymAct("DOKKORAA_2"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DOKKORAA_2"), -1122378098)
  WINDOW:Talk(SymAct("DOKKORAA_2"), -1774940851)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  TASK:Regist(subEveJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -1892697076, PARTNER_1 = 146251971})
  WINDOW:SwitchTalk({PARTNER_0 = 296522114, PARTNER_1 = 2027048366})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  CH("PARTNER"):DirTo(CH("SUWANNA"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("HERO"):DirTo(CH("SUWANNA"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 1640594671, PARTNER_1 = 1256468268})
  WINDOW:CloseMessage()
  CAMERA:MoveFollow2(SymCam("CAMERA_05"), Speed(4, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("DOTEKKOTSU"):DirTo(CH("SUWANNA"), Speed(350), ROT_TYPE.NEAR)
  CH("DOKKORAA_1"):DirTo(CH("SUWANNA"), Speed(350), ROT_TYPE.NEAR)
  CH("DOKKORAA_2"):DirTo(CH("SUWANNA"), Speed(350), ROT_TYPE.NEAR)
  CH("HAADERIA"):DirTo(CH("SUWANNA"), Speed(350), ROT_TYPE.NEAR)
  CAMERA:WaitMove()
  WINDOW:DrawFace(72, 16, SymAct("SUWANNA"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("SUWANNA"), 1409228397)
  WINDOW:Talk(SymAct("SUWANNA"), 482248874)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow2(SymCam("CAMERA_00"), Speed(4, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("HERO"):SetManpu("MP_SHOCK_L")
  CH("PARTNER"):SetManpu("MP_SHOCK_L")
  TASK:Regist(subEveJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 94747115, PARTNER_1 = 780724776})
  WINDOW:CloseMessage()
  CH("DOTEKKOTSU"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("DOKKORAA_1"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("DOKKORAA_2"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("HAADERIA"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("DOTEKKOTSU"):WaitRotate()
  WINDOW:DrawFace(272, 16, SymAct("DOTEKKOTSU"), FACE_TYPE.SPECIAL04)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), 932436841)
  CH("PARTNER"):DirTo(CH("DOTEKKOTSU"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), -1341405274)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), -1458506009)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), 1785193024)
  WINDOW:KeyWait()
  CH("DOTEKKOTSU"):SetManpu("MP_SPREE_LP")
  CH("DOTEKKOTSU"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(272, 16, SymAct("DOTEKKOTSU"), FACE_TYPE.GLADNESS)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), 1937560321)
  WINDOW:KeyWait()
  SOUND:FadeOutSe(SymSnd("SE_EVT_PARTY_02"), TimeSec(1))
  TASK:ExitNotifyTasks(Group("grp3hiki"))
  CH("DOTEKKOTSU"):ResetManpu()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("DOTEKKOTSU"):SetManpu("MP_FLY_SWEAT_LP")
  CH("DOTEKKOTSU"):SetMotion(SymMot("EV002_CRY01"), LOOP.OFF)
  CH("DOTEKKOTSU"):SetFacialMotion(FACIAL_MOTION.SHOUT)
  WINDOW:DrawFace(272, 16, SymAct("DOTEKKOTSU"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), 1481736386)
  WINDOW:CloseMessage()
  CH("DOTEKKOTSU"):WaitPlayMotion()
  CH("DOTEKKOTSU"):SetMotion(SymMot("EV002_CRY02"), LOOP.ON)
  CH("DOKKORAA_1"):DirTo(CH("DOTEKKOTSU"), Speed(350), ROT_TYPE.NEAR)
  CH("DOKKORAA_2"):DirTo(CH("DOTEKKOTSU"), Speed(350), ROT_TYPE.NEAR)
  CH("WASHIBON"):DirTo(CH("DOTEKKOTSU"), Speed(350), ROT_TYPE.NEAR)
  CH("KOARUHII"):DirTo(CH("DOTEKKOTSU"), Speed(350), ROT_TYPE.NEAR)
  CH("DANGORO"):DirTo(CH("DOTEKKOTSU"), Speed(350), ROT_TYPE.NEAR)
  CH("MINEZUMI"):DirTo(CH("DOTEKKOTSU"), Speed(350), ROT_TYPE.NEAR)
  CH("DOKKORAA_1"):WaitRotate()
  CH("DOKKORAA_1"):RunTo(SplinePath(SymPos("P01_DOKKORAA_1"), SymPos("P02_DOKKORAA_1")), Speed(2))
  CH("DOKKORAA_1"):WaitMove()
  TASK:Sleep(TimeSec(0.7))
  CH("MINEZUMI"):SetMotionRaito(Raito(2))
  CH("WASHIBON"):SetMotionRaito(Raito(2))
  CH("DANGORO"):SetMotionRaito(Raito(2))
  CH("KOARUHII"):SetMotionRaito(Raito(2))
  CH("MINEZUMI"):SetMotion(SymMot("SLEEP"), LOOP.OFF)
  CH("WASHIBON"):SetMotion(SymMot("SLEEP"), LOOP.OFF)
  CH("DANGORO"):SetMotion(SymMot("SLEEP"), LOOP.OFF)
  CH("KOARUHII"):SetMotion(SymMot("SLEEP"), LOOP.OFF)
  CH("DOKKORAA_1"):SetMotion(SymMot("FALL"), LOOP.OFF)
  CH("DOKKORAA_2"):SetMotion(SymMot("FALL"), LOOP.OFF)
  WINDOW:Talk(SymWord(-181286456), 1095414147)
  CH("DOKKORAA_2"):WaitPlayMotion()
  CH("MINEZUMI"):SetMotion(SymMot("SLEEPLOOP"), LOOP.ON)
  CH("WASHIBON"):SetMotion(SymMot("SLEEPLOOP"), LOOP.ON)
  CH("DANGORO"):SetMotion(SymMot("SLEEPLOOP"), LOOP.ON)
  CH("KOARUHII"):SetMotion(SymMot("SLEEPLOOP"), LOOP.ON)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("WASHIBON"):SetManpu("MP_FLY_SWEAT_LP")
  TASK:Sleep(TimeSec(0.1))
  CH("DANGORO"):SetManpu("MP_FLY_SWEAT_LP")
  CH("DOKKORAA_1"):SetManpu("MP_FLY_SWEAT_LP")
  WINDOW:CloseMessage()
  TASK:Sleep(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SWEAT"), Volume(256))
  CH("HERO"):SetManpu("MP_SWEAT_L_AL")
  CH("PARTNER"):SetManpu("MP_SWEAT_L_AL")
  CH("PARTNER"):WaitManpu()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.CATCHBREATH)
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.CATCHBREATH)
  WINDOW:SwitchTalk({PARTNER_0 = 235611972, PARTNER_1 = 386930181})
  WINDOW:CloseMessage()
  CAMERA:MoveFollow2(SymCam("CAMERA_06"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CAMERA:WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.THINK)
  WINDOW:SwitchTalk({PARTNER_0 = 1010648518, PARTNER_1 = 623277191})
  WINDOW:SwitchTalk({PARTNER_0 = -1564579768, PARTNER_1 = -1146791671})
  WINDOW:SwitchTalk({PARTNER_0 = -757365467, PARTNER_1 = -876563356})
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(RotateTarget(35), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SAD)
  WINDOW:SwitchTalk({PARTNER_0 = -521279577, PARTNER_1 = -101263642})
  WINDOW:CloseMessage()
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  TASK:Sleep(TimeSec(0.1))
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SAD)
  WINDOW:SwitchTalk({PARTNER_0 = -1229504479, PARTNER_1 = -1347653280})
  WINDOW:SwitchTalk({PARTNER_0 = -2071911773, PARTNER_1 = -1650846750})
  WINDOW:CloseMessage()
  subEveNod(CH("HERO"))
  SOUND:FadeOutBgm(TimeSec(1.5))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  SOUND:WaitBgm()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  subEveFadeAfterTime()
  FLAG.SceneFlag = CONST.FL_SC_01_FIRST
  FLAG.SCENARIOFLAG = CONST.M03_BIRIJION_END
  FLAG.MapFlags = CONST.MAP_EVENT
  FLAG.FreePlay = CONST.FLAG_TRUE
  FLAG.TrigNextEvent = CONST.FLAG_FALSE
  SYSTEM:NextEntry()
end
function main03_birijion06_end()
end
function groundEnd()
end

