function BAOPPUMovTbl.M12_010_BAOPPU_FREE_START()
end
function BAOPPUMovTbl.M12_020_BAOPPU_FREE_START()
  subUseFreeActTalkNormalTrio(CH("BAOPPU"), CH("HIYAPPU"), CH("YANAPPU"))
end
function BAOPPUMovTbl.M12_030_BAOPPU_FREE_START()
  return BAOPPUMovTbl.M12_020_BAOPPU_FREE_START
end
function BAOPPUMovTbl.M12_040_BAOPPU_FREE_START()
end
function BAOPPUMovTbl.M12_050_BAOPPU_FREE_START()
  return BAOPPUMovTbl.M12_040_BAOPPU_FREE_START
end
function BAOPPUMovTbl.M12_070_BAOPPU_FREE_START()
  subUseFreeActTalkNormalTrio(CH("BAOPPU"), CH("HIYAPPU"), CH("YANAPPU"))
end
function BAOPPUMovTbl.M13_010_BAOPPU_FREE_START()
end
function BAOPPUMovTbl.M13_030_BAOPPU_FREE_START()
  return BAOPPUMovTbl.M13_010_BAOPPU_FREE_START
end
function BAOPPUMovTbl.M13_040_BAOPPU_FREE_START()
  return BAOPPUMovTbl.M13_030_BAOPPU_FREE_START
end
function BAOPPUMovTbl.M13_060_BAOPPU_FREE_START()
  return BAOPPUMovTbl.M13_040_BAOPPU_FREE_START
end
function BAOPPUMovTbl.M13_070_BAOPPU_FREE_START()
  return BAOPPUMovTbl.M13_060_BAOPPU_FREE_START
end
function BAOPPUMovTbl.M13_080_BAOPPU_FREE_START()
  return BAOPPUMovTbl.M13_070_BAOPPU_FREE_START
end
function BAOPPUMovTbl.M13_090_BAOPPU_FREE_START()
  return BAOPPUMovTbl.M13_080_BAOPPU_FREE_START
end
function BAOPPUMovTbl.M13_095_BAOPPU_FREE_START()
  return BAOPPUMovTbl.M13_090_BAOPPU_FREE_START
end
function BAOPPUMovTbl.M13_110_BAOPPU_FREE_START()
  return BAOPPUMovTbl.M13_095_BAOPPU_FREE_START
end
function BAOPPUMovTbl.M14_010_BAOPPU_FREE_START()
  return BAOPPUMovTbl.M13_110_BAOPPU_FREE_START
end
function BAOPPUMovTbl.M14_030_BAOPPU_FREE_START()
  return BAOPPUMovTbl.M14_010_BAOPPU_FREE_START
end
function BAOPPUMovTbl.M14_040_BAOPPU_FREE_START()
  return BAOPPUMovTbl.M14_030_BAOPPU_FREE_START
end
function BAOPPUMovTbl.M14_060_BAOPPU_FREE_START()
  return BAOPPUMovTbl.M14_040_BAOPPU_FREE_START
end
function BAOPPUMovTbl.M14_070_BAOPPU_FREE_START()
  return BAOPPUMovTbl.M14_060_BAOPPU_FREE_START
end
function BAOPPUMovTbl.M14_090_BAOPPU_FREE_START()
  return BAOPPUMovTbl.M14_070_BAOPPU_FREE_START
end
function BAOPPUMovTbl.M15_010_BAOPPU_FREE_START()
  return BAOPPUMovTbl.M14_090_BAOPPU_FREE_START
end
function BAOPPUMovTbl.M15_020_BAOPPU_FREE_START()
  return BAOPPUMovTbl.M15_010_BAOPPU_FREE_START
end
function BAOPPUMovTbl.M15_030_BAOPPU_FREE_START()
  return BAOPPUMovTbl.M15_020_BAOPPU_FREE_START
end
function BAOPPUMovTbl.M16_010_BAOPPU_FREE_START()
  return BAOPPUMovTbl.M15_030_BAOPPU_FREE_START
end
function BAOPPUMovTbl.M16_040_BAOPPU_FREE_START()
  return BAOPPUMovTbl.M16_010_BAOPPU_FREE_START
end
function BAOPPUMovTbl.M16_080_BAOPPU_FREE_START()
  return BAOPPUMovTbl.M16_040_BAOPPU_FREE_START
end
function BAOPPUMovTbl.M16_090_BAOPPU_FREE_START()
  return BAOPPUMovTbl.M16_080_BAOPPU_FREE_START
end
function BAOPPUMovTbl.M16_100_BAOPPU_FREE_START()
  return BAOPPUMovTbl.M16_090_BAOPPU_FREE_START
end
function BAOPPUMovTbl.M16_105_BAOPPU_FREE_START()
  return BAOPPUMovTbl.M16_100_BAOPPU_FREE_START
end
function BAOPPUMovTbl.M16_120_BAOPPU_FREE_START()
  return BAOPPUMovTbl.M16_105_BAOPPU_FREE_START
end
function BAOPPUMovTbl.M17_020_BAOPPU_FREE_START()
  return BAOPPUMovTbl.M16_120_BAOPPU_FREE_START
end
function BAOPPUMovTbl.M17_040_BAOPPU_FREE_START()
  return BAOPPUMovTbl.M17_020_BAOPPU_FREE_START
end
function BAOPPUMovTbl.M17_060_BAOPPU_FREE_START()
  return BAOPPUMovTbl.M17_040_BAOPPU_FREE_START
end
function BAOPPUMovTbl.M17_065_BAOPPU_FREE_START()
  return BAOPPUMovTbl.M17_060_BAOPPU_FREE_START
end
function BAOPPUMovTbl.M17_090_BAOPPU_FREE_START()
  return BAOPPUMovTbl.M17_065_BAOPPU_FREE_START
end
function BAOPPUMovTbl.M17_120_BAOPPU_FREE_START()
  return BAOPPUMovTbl.M17_090_BAOPPU_FREE_START
end
function BAOPPUMovTbl.M17_140_BAOPPU_FREE_START()
  return BAOPPUMovTbl.M17_120_BAOPPU_FREE_START
end
function BAOPPUMovTbl.M17_150_BAOPPU_FREE_START()
  return BAOPPUMovTbl.M17_140_BAOPPU_FREE_START
end
function BAOPPUMovTbl.M17_155_BAOPPU_FREE_START()
  return BAOPPUMovTbl.M17_150_BAOPPU_FREE_START
end
function BAOPPUMovTbl.M17_170_BAOPPU_FREE_START()
  return BAOPPUMovTbl.M17_155_BAOPPU_FREE_START
end
function BAOPPUMovTbl.M17_200_BAOPPU_FREE_START()
  return BAOPPUMovTbl.M17_170_BAOPPU_FREE_START
end
function BAOPPUMovTbl.M17_210_BAOPPU_FREE_START()
  return BAOPPUMovTbl.M17_200_BAOPPU_FREE_START
end
function BAOPPUMovTbl.M17_220_BAOPPU_FREE_START()
  return BAOPPUMovTbl.M17_210_BAOPPU_FREE_START
end
function BAOPPUMovTbl.M17_225_BAOPPU_FREE_START()
  return BAOPPUMovTbl.M17_220_BAOPPU_FREE_START
end
function BAOPPUMovTbl.M17_240_BAOPPU_FREE_START()
  return BAOPPUMovTbl.M17_225_BAOPPU_FREE_START
end
function BAOPPUMovTbl.M18_020_BAOPPU_FREE_START()
  return BAOPPUMovTbl.M17_240_BAOPPU_FREE_START
end
function BAOPPUMovTbl.M18_030_BAOPPU_FREE_START()
  return BAOPPUMovTbl.M18_020_BAOPPU_FREE_START
end
function BAOPPUMovTbl.S01_010_BAOPPU_FREE_START()
  subUseFreeActTalkNormalTrio(CH("BAOPPU"), CH("HIYAPPU"), CH("YANAPPU"))
end
function BAOPPUMovTbl.S01_020_BAOPPU_FREE_START()
end
function BAOPPUMovTbl.S01_030_BAOPPU_FREE_START()
  subUseFreeActTalkNormalTrio(CH("BAOPPU"), CH("HIYAPPU"), CH("YANAPPU"))
end
function BAOPPUMovTbl.S01_040_BAOPPU_FREE_START()
end
function BAOPPUMovTbl.S01_050_BAOPPU_FREE_START()
  subUseFreeActTalkNormalTrio(CH("BAOPPU"), CH("HIYAPPU"), CH("YANAPPU"))
end
function BAOPPUMovTbl.S01_060_BAOPPU_FREE_START()
end
function BAOPPUMovTbl.S01_080_BAOPPU_FREE_START()
  subUseFreeActTalkNormalTrio(CH("BAOPPU"), CH("HIYAPPU"), CH("YANAPPU"))
end
function BAOPPUMovTbl.ALL_CLEAR_BAOPPU_FREE_START()
  subUseFreeActTalkNormalTrio(CH("BAOPPU"), CH("HIYAPPU"), CH("YANAPPU"))
end

