BIKUTYINIMovTbl = {}
function FreeCharMoveBIKUTYINI()
  FREE_MOVE_SYSTEM:CreateFmcCtrl_ForShopStaff(CH("BIKUTYINI"))
end
function BIKUTYINIMovTbl.CLEAR_DUNREST_BIKUTYINI()
end
function BIKUTYINIMovTbl.PARADISE_MODE_BIKUTYINI()
  FREE_MOVE_SYSTEM:CreateFmcCtrl_ForShopStaff(CH("BIKUTYINI"))
end
function BIKUTYINIMovTbl.NO_MESSAGE_BIKUTYINI()
end

