function BIRIJIONMovTbl.M12_010_BIRIJION_FREE_START()
end
function BIRIJIONMovTbl.M12_020_BIRIJION_FREE_START()
  local fmcCtrlObj = FREE_MOVE_SYSTEM:CreateFmcCtrl_Taikis({
    CH("NOKOTCHI"),
    CH("BIRIJION")
  })
  function fmcCtrlObj:TaikiActLoop()
    CH("NOKOTCHI"):SetMotionRaito(Raito(1.5))
    CH("NOKOTCHI"):SetMotion(SymMot("WALK"), LOOP.ON)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    CH("NOKOTCHI"):SetMotionRaito(Raito(1))
    CH("NOKOTCHI"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    CH("BIRIJION"):SetManpu("MP_LAUGH_LP")
    CH("BIRIJION"):SetFacialMotion(FACIAL_MOTION.HAPPY)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    CH("BIRIJION"):ResetManpu()
    CH("BIRIJION"):SetFacialMotion(FACIAL_MOTION.NORMAL)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
  end
  function fmcCtrlObj:TaikiActFinish()
    CH("BIRIJION"):ResetManpu()
    CH("BIRIJION"):SetFacialMotion(FACIAL_MOTION.NORMAL)
    CH("NOKOTCHI"):SetMotionRaito(Raito(1))
    CH("NOKOTCHI"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
end
function BIRIJIONMovTbl.M12_030_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.M12_020_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.M12_040_BIRIJION_FREE_START()
end
function BIRIJIONMovTbl.M12_050_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.M12_040_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.M12_070_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.M12_050_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.M13_010_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.M12_070_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.M13_030_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.M13_010_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.M13_040_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.M13_030_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.M13_060_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.M13_040_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.M13_070_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.M13_060_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.M13_080_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.M13_070_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.M13_090_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.M13_080_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.M13_095_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.M13_090_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.M13_110_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.M13_095_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.M14_010_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.M13_110_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.M14_030_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.M14_010_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.M14_040_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.M14_030_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.M14_060_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.M14_040_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.M14_070_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.M14_060_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.M14_090_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.M14_070_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.M15_010_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.M14_090_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.M15_020_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.M15_010_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.M15_030_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.M15_020_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.M16_010_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.M15_030_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.M16_040_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.M16_010_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.M16_080_BIRIJION_FREE_START()
  FREE_MOVE_SYSTEM:CreateFmcCtrl_TaikisWithPush({
    CH("BIRIJION")
  })
end
function BIRIJIONMovTbl.M16_090_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.M16_080_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.M16_100_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.M16_090_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.M16_105_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.M16_100_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.M16_120_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.M16_105_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.M17_020_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.M16_120_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.M17_040_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.M17_020_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.M17_060_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.M17_040_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.M17_065_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.M17_060_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.M17_090_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.M17_065_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.M17_120_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.M17_090_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.M17_140_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.M17_120_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.M17_150_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.M17_140_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.M17_155_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.M17_150_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.M17_170_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.M17_155_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.M17_200_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.M17_170_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.M17_210_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.M17_200_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.M17_220_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.M17_210_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.M17_225_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.M17_220_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.M17_240_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.M17_225_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.M18_020_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.M17_240_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.M18_030_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.M18_020_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.S01_010_BIRIJION_FREE_START()
end
function BIRIJIONMovTbl.S01_020_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.S01_010_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.S01_030_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.S01_020_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.S01_040_BIRIJION_FREE_START()
  return BIRIJIONMovTbl.S01_030_BIRIJION_FREE_START
end
function BIRIJIONMovTbl.S01_050_BIRIJION_FREE_START()
  subUseFreeAct2men02(CH("KERUDYIO"), CH("BIRIJION"))
end
function BIRIJIONMovTbl.S01_060_BIRIJION_FREE_START()
  subUseFreeActTalkNormalTrio(CH("KERUDYIO"), CH("NOKOTCHI"), CH("BIRIJION"))
end
function BIRIJIONMovTbl.S01_080_BIRIJION_FREE_START()
  subUseFreeAct2men01(CH("KERUDYIO"), CH("BIRIJION"))
end
function BIRIJIONMovTbl.ALL_CLEAR_BIRIJION_FREE_START()
end

