function BURAKKIIMovTbl.M12_010_BURAKKII_FREE_START()
end
function BURAKKIIMovTbl.M12_020_BURAKKII_FREE_START()
  subUseFreeActTalkPair(CH("BURAKKII"), CH("EEFI"))
end
function BURAKKIIMovTbl.M12_030_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M12_020_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M12_040_BURAKKII_FREE_START()
  subUseFreeActTalkNormalTrio(CH("BURAKKII"), CH("EEFI"), CH("BIRIJION"))
end
function BURAKKIIMovTbl.M12_050_BURAKKII_FREE_START()
end
function BURAKKIIMovTbl.M12_070_BURAKKII_FREE_START()
  subUseFreeAct2men02(CH("BURAKKII"), CH("EEFI"))
end
function BURAKKIIMovTbl.M13_010_BURAKKII_FREE_START()
end
function BURAKKIIMovTbl.M13_030_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M13_010_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M13_040_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M13_030_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M13_060_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M13_040_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M13_070_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M13_060_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M13_080_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M13_070_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M13_090_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M13_080_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M13_095_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M13_090_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M13_110_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M13_095_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M14_010_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M13_110_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M14_030_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M14_010_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M14_040_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M14_030_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M14_060_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M14_040_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M14_070_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M14_060_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M14_090_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M14_070_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M15_010_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M14_090_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M15_020_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M15_010_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M15_030_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M15_020_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M16_010_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M15_030_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M16_040_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M16_010_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M16_080_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M16_040_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M16_090_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M16_080_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M16_100_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M16_090_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M16_105_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M16_100_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M16_120_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M16_105_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M17_020_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M16_120_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M17_040_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M17_020_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M17_060_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M17_040_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M17_065_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M17_060_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M17_090_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M17_065_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M17_120_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M17_090_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M17_140_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M17_120_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M17_150_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M17_140_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M17_155_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M17_150_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M17_170_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M17_155_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M17_200_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M17_170_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M17_210_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M17_200_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M17_220_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M17_210_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M17_225_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M17_220_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M17_240_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M17_225_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M18_020_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M17_240_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M18_030_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M18_020_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.S01_010_BURAKKII_FREE_START()
  subUseFreeAct2men02(CH("BURAKKII"), CH("EEFI"))
end
function BURAKKIIMovTbl.S01_020_BURAKKII_FREE_START()
end
function BURAKKIIMovTbl.S01_030_BURAKKII_FREE_START()
  FREE_MOVE_SYSTEM:CreateFmcCtrl_TaikisWithPush({
    CH("BURAKKII")
  })
end
function BURAKKIIMovTbl.S01_040_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.S01_030_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.S01_050_BURAKKII_FREE_START()
  subUseFreeAct2men02(CH("BURAKKII"), CH("EEFI"))
end
function BURAKKIIMovTbl.S01_060_BURAKKII_FREE_START()
  subUseFreeActTalkNormalTrio(CH("BURAKKII"), CH("EEFI"), CH("EMONGA"))
end
function BURAKKIIMovTbl.S01_080_BURAKKII_FREE_START()
  subUseFreeAct2men01(CH("BURAKKII"), CH("EEFI"))
end
function BURAKKIIMovTbl.ALL_CLEAR_BURAKKII_FREE_START()
  subUseFreeActTalkNormalTrio(CH("BURAKKII"), CH("EEFI"), CH("KERUDYIO"))
end

