function BURAKKIIMovTbl.M02_010_BURAKKII_FREE_START()
end
function BURAKKIIMovTbl.M02_030_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M02_010_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M02_050_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M02_030_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M02_070_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M02_050_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M02_080_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M02_070_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M02_090_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M02_080_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M02_100_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M02_090_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M02_115_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M02_100_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M02_130_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M02_115_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M02_160_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M02_130_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M03_010_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M02_160_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M03_020_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M03_010_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M03_045_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M03_020_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M03_090_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M03_045_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M03_110_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M03_090_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M03_130_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M03_110_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M03_150_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M03_130_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M04_010_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M03_150_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M04_020_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M04_010_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M04_HANYOU_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M04_020_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M04_040_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M04_HANYOU_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M04_060_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M04_040_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M04_070_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M04_060_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M04_HANYOU_BURAKKII_FREE_START2()
  return BURAKKIIMovTbl.M04_070_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M05_000_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M04_HANYOU_BURAKKII_FREE_START2
end
function BURAKKIIMovTbl.M05_010_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M05_000_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M05_020_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M05_010_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M05_030_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M05_020_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M06_HANYOU_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M05_030_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M06_010_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M06_HANYOU_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M06_015_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M06_010_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M06_020_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M06_015_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M06_030_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M06_020_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M06_040_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M06_030_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M06_060_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M06_040_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M07_000_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M06_060_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M07_010_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M07_000_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M07_020_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M07_010_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M07_045_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M07_020_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M07_HANYOU_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M07_045_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M07_080_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M07_HANYOU_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M08_010_BURAKKII_FREE_START()
  local fmcCtrlObj = FREE_MOVE_SYSTEM:CreateFmcCtrl_Taikis({
    CH("BURAKKII")
  })
  CH("BURAKKII"):SetMotion(SymMot("EV008_SLEEP"), LOOP.ON, TimeSec(0))
end
function BURAKKIIMovTbl.M08_HANYOU_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M08_010_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M08_020_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M08_HANYOU_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M08_040_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M08_020_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M08_050_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M08_040_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M08_055_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M08_050_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M08_070_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M08_055_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M09_HANYOU_BURAKKII_FREE_START1()
end
function BURAKKIIMovTbl.M09_010_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M09_HANYOU_BURAKKII_FREE_START1
end
function BURAKKIIMovTbl.M09_020_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M09_010_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M09_040_BURAKKII_FREE_START()
  local fmcCtrlObj = FREE_MOVE_SYSTEM:CreateFmcCtrl_Taikis({
    CH("BURAKKII"),
    CH("EEFI")
  })
  function fmcCtrlObj:TaikiActLoop()
    CH("BURAKKII"):SetManpu("MP_SPREE_LP")
    CH("BURAKKII"):SetMotion(SymMot("SPEAK"), LOOP.ON)
    TASK:Sleep(TimeSec(1), TASK_EXIT.QUICK)
    CH("BURAKKII"):ResetManpu()
    CH("BURAKKII"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
    subEveNodDouble(CH("EEFI"))
    TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
    CH("BURAKKII"):SetManpu("MP_SPREE_LP")
    CH("BURAKKII"):SetMotion(SymMot("SPEAK"), LOOP.ON)
    TASK:Sleep(TimeSec(1), TASK_EXIT.QUICK)
    CH("BURAKKII"):ResetManpu()
    CH("BURAKKII"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(1), TASK_EXIT.QUICK)
    CH("EEFI"):SetManpu("MP_LAUGH_LP")
    TASK:Sleep(TimeSec(1), TASK_EXIT.QUICK)
    CH("EEFI"):ResetManpu()
    TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(1), TASK_EXIT.QUICK)
  end
  function fmcCtrlObj:TaikiActFinish()
    CH("BURAKKII"):ResetManpu()
    CH("BURAKKII"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    CH("EEFI"):ResetManpu()
  end
end
function BURAKKIIMovTbl.M09_HANYOU_BURAKKII_FREE_START2()
  return BURAKKIIMovTbl.M09_040_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M09_060_BURAKKII_FREE_START()
end
function BURAKKIIMovTbl.M09_080_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M09_060_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M09_100_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M09_080_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M09_110_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M09_100_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M09_120_BURAKKII_FREE_START()
  subUseFreeAct2men02(CH("BURAKKII"), CH("EEFI"))
end
function BURAKKIIMovTbl.M10_010_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M09_120_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M10_030_BURAKKII_FREE_START()
  FREE_MOVE_SYSTEM:CreateFmcCtrl_TaikisWithPush({
    CH("BURAKKII")
  })
end
function BURAKKIIMovTbl.M10_040_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M10_030_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M10_060_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M10_040_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M11_010_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M10_060_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M11_030_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M11_010_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M11_040_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M11_030_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M11_050_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M11_040_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M11_060_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M11_050_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M11_075_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M11_060_BURAKKII_FREE_START
end
function BURAKKIIMovTbl.M11_090_BURAKKII_FREE_START()
  return BURAKKIIMovTbl.M11_075_BURAKKII_FREE_START
end

