function CHONCHIIMovTbl.M12_010_CHONCHII_FREE_START()
end
function CHONCHIIMovTbl.M12_020_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M12_010_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M12_030_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M12_020_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M12_040_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M12_030_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M12_050_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M12_040_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M12_070_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M12_050_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M13_010_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M12_070_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M13_030_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M13_010_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M13_040_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M13_030_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M13_060_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M13_040_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M13_070_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M13_060_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M13_080_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M13_070_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M13_090_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M13_080_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M13_095_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M13_090_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M13_110_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M13_095_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M14_010_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M13_110_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M14_030_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M14_010_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M14_040_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M14_030_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M14_060_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M14_040_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M14_070_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M14_060_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M14_090_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M14_070_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M15_010_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M14_090_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M15_020_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M15_010_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M15_030_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M15_020_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M16_010_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M15_030_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M16_040_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M16_010_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M16_080_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M16_040_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M16_090_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M16_080_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M16_100_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M16_090_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M16_105_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M16_100_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M16_120_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M16_105_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M17_020_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M16_120_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M17_040_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M17_020_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M17_060_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M17_040_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M17_065_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M17_060_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M17_090_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M17_065_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M17_120_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M17_090_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M17_140_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M17_120_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M17_150_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M17_140_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M17_155_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M17_150_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M17_170_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M17_155_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M17_200_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M17_170_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M17_210_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M17_200_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M17_220_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M17_210_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M17_225_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M17_220_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M17_240_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M17_225_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M18_020_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M17_240_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.M18_030_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M18_020_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.S01_010_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.M18_030_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.S01_020_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.S01_010_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.S01_030_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.S01_020_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.S01_040_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.S01_030_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.S01_050_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.S01_040_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.S01_060_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.S01_050_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.S01_080_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.S01_060_CHONCHII_FREE_START
end
function CHONCHIIMovTbl.ALL_CLEAR_CHONCHII_FREE_START()
  return CHONCHIIMovTbl.S01_080_CHONCHII_FREE_START
end

