function DANGOROMovTbl.M02_010_DANGORO_FREE_START()
end
function DANGOROMovTbl.M02_030_DANGORO_FREE_START()
  local fmcCtrlObj = FREE_MOVE_SYSTEM:CreateFmcCtrl_Taikis({
    CH("DANGORO")
  })
  function fmcCtrlObj:TaikiActLoop()
    CH("DANGORO"):SetManpu("MP_FLY_SWEAT")
    CH("DANGORO"):SetMotion(SymMot("PULL"), LOOP.ON)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    CH("DANGORO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    CH("DANGORO"):SetMotion(SymMot("PUSH"), LOOP.ON)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    CH("DANGORO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
  end
  function fmcCtrlObj:TaikiActFinish()
    CH("DANGORO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    CH("DANGORO"):ResetManpu()
  end
end
function DANGOROMovTbl.M02_050_DANGORO_FREE_START()
  return DANGOROMovTbl.M02_030_DANGORO_FREE_START
end
function DANGOROMovTbl.M02_070_DANGORO_FREE_START()
  FREE_MOVE_SYSTEM:CreateFmcCtrl_TaikisWithPush({
    CH("DANGORO")
  })
end
function DANGOROMovTbl.M02_080_DANGORO_FREE_START()
  return DANGOROMovTbl.M02_070_DANGORO_FREE_START
end
function DANGOROMovTbl.M02_090_DANGORO_FREE_START()
  return DANGOROMovTbl.M02_080_DANGORO_FREE_START
end
function DANGOROMovTbl.M02_100_DANGORO_FREE_START()
  return DANGOROMovTbl.M02_090_DANGORO_FREE_START
end
function DANGOROMovTbl.M02_115_DANGORO_FREE_START()
  return DANGOROMovTbl.M02_100_DANGORO_FREE_START
end
function DANGOROMovTbl.M02_130_DANGORO_FREE_START()
  return DANGOROMovTbl.M02_115_DANGORO_FREE_START
end
function DANGOROMovTbl.M02_160_DANGORO_FREE_START()
  return DANGOROMovTbl.M02_130_DANGORO_FREE_START
end
function DANGOROMovTbl.M03_010_DANGORO_FREE_START()
  return DANGOROMovTbl.M02_160_DANGORO_FREE_START
end
function DANGOROMovTbl.M03_020_DANGORO_FREE_START()
  return DANGOROMovTbl.M03_010_DANGORO_FREE_START
end
function DANGOROMovTbl.M03_045_DANGORO_FREE_START()
  return DANGOROMovTbl.M03_020_DANGORO_FREE_START
end
function DANGOROMovTbl.M03_090_DANGORO_FREE_START()
end
function DANGOROMovTbl.M03_110_DANGORO_FREE_START()
  return DANGOROMovTbl.M03_090_DANGORO_FREE_START
end
function DANGOROMovTbl.M03_130_DANGORO_FREE_START()
  return DANGOROMovTbl.M03_110_DANGORO_FREE_START
end
function DANGOROMovTbl.M03_150_DANGORO_FREE_START()
  return DANGOROMovTbl.M03_130_DANGORO_FREE_START
end
function DANGOROMovTbl.M04_010_DANGORO_FREE_START()
  return DANGOROMovTbl.M03_150_DANGORO_FREE_START
end
function DANGOROMovTbl.M04_020_DANGORO_FREE_START()
  return DANGOROMovTbl.M04_010_DANGORO_FREE_START
end
function DANGOROMovTbl.M04_HANYOU_DANGORO_FREE_START()
  return DANGOROMovTbl.M04_020_DANGORO_FREE_START
end
function DANGOROMovTbl.M04_040_DANGORO_FREE_START()
  FREE_MOVE_SYSTEM:CreateFmcCtrl_TaikisWithPush({
    CH("DANGORO")
  })
end
function DANGOROMovTbl.M04_060_DANGORO_FREE_START()
  return DANGOROMovTbl.M04_040_DANGORO_FREE_START
end
function DANGOROMovTbl.M04_070_DANGORO_FREE_START()
  return DANGOROMovTbl.M04_060_DANGORO_FREE_START
end
function DANGOROMovTbl.M04_HANYOU_DANGORO_FREE_START2()
  return DANGOROMovTbl.M04_070_DANGORO_FREE_START
end
function DANGOROMovTbl.M05_000_DANGORO_FREE_START()
  return DANGOROMovTbl.M04_HANYOU_DANGORO_FREE_START2
end
function DANGOROMovTbl.M05_010_DANGORO_FREE_START()
  return DANGOROMovTbl.M05_000_DANGORO_FREE_START
end
function DANGOROMovTbl.M05_020_DANGORO_FREE_START()
  return DANGOROMovTbl.M05_010_DANGORO_FREE_START
end
function DANGOROMovTbl.M05_030_DANGORO_FREE_START()
  return DANGOROMovTbl.M05_020_DANGORO_FREE_START
end
function DANGOROMovTbl.M06_HANYOU_DANGORO_FREE_START()
  return DANGOROMovTbl.M05_030_DANGORO_FREE_START
end
function DANGOROMovTbl.M06_010_DANGORO_FREE_START()
  return DANGOROMovTbl.M06_HANYOU_DANGORO_FREE_START
end
function DANGOROMovTbl.M06_015_DANGORO_FREE_START()
  return DANGOROMovTbl.M06_010_DANGORO_FREE_START
end
function DANGOROMovTbl.M06_020_DANGORO_FREE_START()
  return DANGOROMovTbl.M06_015_DANGORO_FREE_START
end
function DANGOROMovTbl.M06_030_DANGORO_FREE_START()
  return DANGOROMovTbl.M06_020_DANGORO_FREE_START
end
function DANGOROMovTbl.M06_040_DANGORO_FREE_START()
  return DANGOROMovTbl.M06_030_DANGORO_FREE_START
end
function DANGOROMovTbl.M06_060_DANGORO_FREE_START()
  return DANGOROMovTbl.M06_040_DANGORO_FREE_START
end
function DANGOROMovTbl.M07_000_DANGORO_FREE_START()
  return DANGOROMovTbl.M06_060_DANGORO_FREE_START
end
function DANGOROMovTbl.M07_010_DANGORO_FREE_START()
  return DANGOROMovTbl.M07_000_DANGORO_FREE_START
end
function DANGOROMovTbl.M07_020_DANGORO_FREE_START()
  return DANGOROMovTbl.M07_010_DANGORO_FREE_START
end
function DANGOROMovTbl.M07_045_DANGORO_FREE_START()
  return DANGOROMovTbl.M07_020_DANGORO_FREE_START
end
function DANGOROMovTbl.M07_HANYOU_DANGORO_FREE_START()
  return DANGOROMovTbl.M07_045_DANGORO_FREE_START
end
function DANGOROMovTbl.M07_080_DANGORO_FREE_START()
  return DANGOROMovTbl.M07_HANYOU_DANGORO_FREE_START
end
function DANGOROMovTbl.M08_010_DANGORO_FREE_START()
end
function DANGOROMovTbl.M08_HANYOU_DANGORO_FREE_START()
  return DANGOROMovTbl.M08_010_DANGORO_FREE_START
end
function DANGOROMovTbl.M08_020_DANGORO_FREE_START()
end
function DANGOROMovTbl.M08_040_DANGORO_FREE_START()
  return DANGOROMovTbl.M08_020_DANGORO_FREE_START
end
function DANGOROMovTbl.M08_050_DANGORO_FREE_START()
  return DANGOROMovTbl.M08_040_DANGORO_FREE_START
end
function DANGOROMovTbl.M08_055_DANGORO_FREE_START()
  return DANGOROMovTbl.M08_050_DANGORO_FREE_START
end
function DANGOROMovTbl.M08_070_DANGORO_FREE_START()
  return DANGOROMovTbl.M08_055_DANGORO_FREE_START
end
function DANGOROMovTbl.M09_HANYOU_DANGORO_FREE_START1()
  return DANGOROMovTbl.M08_070_DANGORO_FREE_START
end
function DANGOROMovTbl.M09_010_DANGORO_FREE_START()
  return DANGOROMovTbl.M09_HANYOU_DANGORO_FREE_START1
end
function DANGOROMovTbl.M09_020_DANGORO_FREE_START()
  return DANGOROMovTbl.M09_010_DANGORO_FREE_START
end
function DANGOROMovTbl.M09_040_DANGORO_FREE_START()
  return DANGOROMovTbl.M09_020_DANGORO_FREE_START
end
function DANGOROMovTbl.M09_HANYOU_DANGORO_FREE_START2()
  return DANGOROMovTbl.M09_040_DANGORO_FREE_START
end
function DANGOROMovTbl.M09_060_DANGORO_FREE_START()
  return DANGOROMovTbl.M09_HANYOU_DANGORO_FREE_START2
end
function DANGOROMovTbl.M09_080_DANGORO_FREE_START()
  return DANGOROMovTbl.M09_060_DANGORO_FREE_START
end
function DANGOROMovTbl.M09_100_DANGORO_FREE_START()
  return DANGOROMovTbl.M09_080_DANGORO_FREE_START
end
function DANGOROMovTbl.M09_110_DANGORO_FREE_START()
  FREE_MOVE_SYSTEM:CreateFmcCtrl_TaikisWithPush({
    CH("DANGORO")
  })
end
function DANGOROMovTbl.M09_120_DANGORO_FREE_START()
  return DANGOROMovTbl.M09_110_DANGORO_FREE_START
end
function DANGOROMovTbl.M10_010_DANGORO_FREE_START()
  return DANGOROMovTbl.M09_120_DANGORO_FREE_START
end
function DANGOROMovTbl.M10_030_DANGORO_FREE_START()
  return DANGOROMovTbl.M10_010_DANGORO_FREE_START
end
function DANGOROMovTbl.M10_040_DANGORO_FREE_START()
  return DANGOROMovTbl.M10_030_DANGORO_FREE_START
end
function DANGOROMovTbl.M10_060_DANGORO_FREE_START()
  return DANGOROMovTbl.M10_040_DANGORO_FREE_START
end
function DANGOROMovTbl.M11_010_DANGORO_FREE_START()
  return DANGOROMovTbl.M10_060_DANGORO_FREE_START
end
function DANGOROMovTbl.M11_030_DANGORO_FREE_START()
  return DANGOROMovTbl.M11_010_DANGORO_FREE_START
end
function DANGOROMovTbl.M11_040_DANGORO_FREE_START()
  return DANGOROMovTbl.M11_030_DANGORO_FREE_START
end
function DANGOROMovTbl.M11_050_DANGORO_FREE_START()
  return DANGOROMovTbl.M11_040_DANGORO_FREE_START
end
function DANGOROMovTbl.M11_060_DANGORO_FREE_START()
  return DANGOROMovTbl.M11_050_DANGORO_FREE_START
end
function DANGOROMovTbl.M11_075_DANGORO_FREE_START()
  return DANGOROMovTbl.M11_060_DANGORO_FREE_START
end
function DANGOROMovTbl.M11_090_DANGORO_FREE_START()
  return DANGOROMovTbl.M11_075_DANGORO_FREE_START
end

