function DANGOROMovTbl.M12_010_DANGORO_FREE_START()
end
function DANGOROMovTbl.M12_020_DANGORO_FREE_START()
  local fmcCtrlObj = FREE_MOVE_SYSTEM:CreateFmcCtrl_Taikis({
    CH("DANGORO")
  })
  CH("DANGORO"):SetManpu("MP_SLEEP_LP")
  CH("DANGORO"):SetMotion(SymMot("SLEEPLOOP"), LOOP.ON, TimeSec(0))
end
function DANGOROMovTbl.M12_030_DANGORO_FREE_START()
  return DANGOROMovTbl.M12_020_DANGORO_FREE_START
end
function DANGOROMovTbl.M12_040_DANGORO_FREE_START()
end
function DANGOROMovTbl.M12_050_DANGORO_FREE_START()
  return DANGOROMovTbl.M12_040_DANGORO_FREE_START
end
function DANGOROMovTbl.M12_070_DANGORO_FREE_START()
  FREE_MOVE_SYSTEM:CreateFmcCtrl_TaikisWithPush({
    CH("DANGORO")
  })
end
function DANGOROMovTbl.M13_010_DANGORO_FREE_START()
  return DANGOROMovTbl.M12_070_DANGORO_FREE_START
end
function DANGOROMovTbl.M13_030_DANGORO_FREE_START()
  return DANGOROMovTbl.M13_010_DANGORO_FREE_START
end
function DANGOROMovTbl.M13_040_DANGORO_FREE_START()
  return DANGOROMovTbl.M13_030_DANGORO_FREE_START
end
function DANGOROMovTbl.M13_060_DANGORO_FREE_START()
  return DANGOROMovTbl.M13_040_DANGORO_FREE_START
end
function DANGOROMovTbl.M13_070_DANGORO_FREE_START()
  return DANGOROMovTbl.M13_060_DANGORO_FREE_START
end
function DANGOROMovTbl.M13_080_DANGORO_FREE_START()
  return DANGOROMovTbl.M13_070_DANGORO_FREE_START
end
function DANGOROMovTbl.M13_090_DANGORO_FREE_START()
  return DANGOROMovTbl.M13_080_DANGORO_FREE_START
end
function DANGOROMovTbl.M13_095_DANGORO_FREE_START()
  return DANGOROMovTbl.M13_090_DANGORO_FREE_START
end
function DANGOROMovTbl.M13_110_DANGORO_FREE_START()
  return DANGOROMovTbl.M13_095_DANGORO_FREE_START
end
function DANGOROMovTbl.M14_010_DANGORO_FREE_START()
  return DANGOROMovTbl.M13_110_DANGORO_FREE_START
end
function DANGOROMovTbl.M14_030_DANGORO_FREE_START()
  return DANGOROMovTbl.M14_010_DANGORO_FREE_START
end
function DANGOROMovTbl.M14_040_DANGORO_FREE_START()
  return DANGOROMovTbl.M14_030_DANGORO_FREE_START
end
function DANGOROMovTbl.M14_060_DANGORO_FREE_START()
  return DANGOROMovTbl.M14_040_DANGORO_FREE_START
end
function DANGOROMovTbl.M14_070_DANGORO_FREE_START()
  return DANGOROMovTbl.M14_060_DANGORO_FREE_START
end
function DANGOROMovTbl.M14_090_DANGORO_FREE_START()
  return DANGOROMovTbl.M14_070_DANGORO_FREE_START
end
function DANGOROMovTbl.M15_010_DANGORO_FREE_START()
  return DANGOROMovTbl.M14_090_DANGORO_FREE_START
end
function DANGOROMovTbl.M15_020_DANGORO_FREE_START()
  return DANGOROMovTbl.M15_010_DANGORO_FREE_START
end
function DANGOROMovTbl.M15_030_DANGORO_FREE_START()
  return DANGOROMovTbl.M15_020_DANGORO_FREE_START
end
function DANGOROMovTbl.M16_010_DANGORO_FREE_START()
  return DANGOROMovTbl.M15_030_DANGORO_FREE_START
end
function DANGOROMovTbl.M16_040_DANGORO_FREE_START()
  return DANGOROMovTbl.M16_010_DANGORO_FREE_START
end
function DANGOROMovTbl.M16_080_DANGORO_FREE_START()
  return DANGOROMovTbl.M16_040_DANGORO_FREE_START
end
function DANGOROMovTbl.M16_090_DANGORO_FREE_START()
  return DANGOROMovTbl.M16_080_DANGORO_FREE_START
end
function DANGOROMovTbl.M16_100_DANGORO_FREE_START()
  return DANGOROMovTbl.M16_090_DANGORO_FREE_START
end
function DANGOROMovTbl.M16_105_DANGORO_FREE_START()
  return DANGOROMovTbl.M16_100_DANGORO_FREE_START
end
function DANGOROMovTbl.M16_120_DANGORO_FREE_START()
  return DANGOROMovTbl.M16_105_DANGORO_FREE_START
end
function DANGOROMovTbl.M17_020_DANGORO_FREE_START()
  return DANGOROMovTbl.M16_120_DANGORO_FREE_START
end
function DANGOROMovTbl.M17_040_DANGORO_FREE_START()
  return DANGOROMovTbl.M17_020_DANGORO_FREE_START
end
function DANGOROMovTbl.M17_060_DANGORO_FREE_START()
  return DANGOROMovTbl.M17_040_DANGORO_FREE_START
end
function DANGOROMovTbl.M17_065_DANGORO_FREE_START()
  return DANGOROMovTbl.M17_060_DANGORO_FREE_START
end
function DANGOROMovTbl.M17_090_DANGORO_FREE_START()
  return DANGOROMovTbl.M17_065_DANGORO_FREE_START
end
function DANGOROMovTbl.M17_120_DANGORO_FREE_START()
  return DANGOROMovTbl.M17_090_DANGORO_FREE_START
end
function DANGOROMovTbl.M17_140_DANGORO_FREE_START()
  return DANGOROMovTbl.M17_120_DANGORO_FREE_START
end
function DANGOROMovTbl.M17_150_DANGORO_FREE_START()
  return DANGOROMovTbl.M17_140_DANGORO_FREE_START
end
function DANGOROMovTbl.M17_155_DANGORO_FREE_START()
  return DANGOROMovTbl.M17_150_DANGORO_FREE_START
end
function DANGOROMovTbl.M17_170_DANGORO_FREE_START()
  return DANGOROMovTbl.M17_155_DANGORO_FREE_START
end
function DANGOROMovTbl.M17_200_DANGORO_FREE_START()
  return DANGOROMovTbl.M17_170_DANGORO_FREE_START
end
function DANGOROMovTbl.M17_210_DANGORO_FREE_START()
  return DANGOROMovTbl.M17_200_DANGORO_FREE_START
end
function DANGOROMovTbl.M17_220_DANGORO_FREE_START()
  return DANGOROMovTbl.M17_210_DANGORO_FREE_START
end
function DANGOROMovTbl.M17_225_DANGORO_FREE_START()
  return DANGOROMovTbl.M17_220_DANGORO_FREE_START
end
function DANGOROMovTbl.M17_240_DANGORO_FREE_START()
  return DANGOROMovTbl.M17_225_DANGORO_FREE_START
end
function DANGOROMovTbl.M18_020_DANGORO_FREE_START()
  return DANGOROMovTbl.M17_240_DANGORO_FREE_START
end
function DANGOROMovTbl.M18_030_DANGORO_FREE_START()
  return DANGOROMovTbl.M18_020_DANGORO_FREE_START
end
function DANGOROMovTbl.S01_010_DANGORO_FREE_START()
  FREE_MOVE_SYSTEM:CreateFmcCtrl_TaikisWithPush({
    CH("DANGORO")
  })
end
function DANGOROMovTbl.S01_020_DANGORO_FREE_START()
  subUseFreeMoveAct02(CH("DANGORO"), "$FREE_MOVE_RANGE_03")
end
function DANGOROMovTbl.S01_030_DANGORO_FREE_START()
end
function DANGOROMovTbl.S01_040_DANGORO_FREE_START()
  return DANGOROMovTbl.S01_030_DANGORO_FREE_START
end
function DANGOROMovTbl.S01_050_DANGORO_FREE_START()
  return DANGOROMovTbl.S01_040_DANGORO_FREE_START
end
function DANGOROMovTbl.S01_060_DANGORO_FREE_START()
  FREE_MOVE_SYSTEM:CreateFmcCtrl_TaikisWithPush({
    CH("DANGORO")
  })
end
function DANGOROMovTbl.S01_080_DANGORO_FREE_START()
end
function DANGOROMovTbl.ALL_CLEAR_DANGORO_FREE_START()
  FREE_MOVE_SYSTEM:CreateFmcCtrl_TaikisWithPush({
    CH("DANGORO")
  })
end

