function DESUKAANMovTbl.M12_010_DESUKAAN_FREE_START()
  FREE_MOVE_SYSTEM:CreateFmcCtrl_ForShopStaff(CH("DESUKAAN"))
end
function DESUKAANMovTbl.M12_020_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M12_010_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M12_030_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M12_020_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M12_040_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M12_030_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M12_050_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M12_040_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M12_070_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M12_050_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M13_010_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M12_070_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M13_030_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M13_010_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M13_040_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M13_030_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M13_060_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M13_040_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M13_070_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M13_060_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M13_080_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M13_070_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M13_090_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M13_080_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M13_095_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M13_090_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M13_110_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M13_095_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M14_010_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M13_110_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M14_030_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M14_010_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M14_040_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M14_030_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M14_060_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M14_040_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M14_070_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M14_060_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M14_090_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M14_070_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M15_010_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M14_090_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M15_020_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M15_010_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M15_030_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M15_020_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M16_010_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M15_030_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M16_040_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M16_010_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M16_080_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M16_040_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M16_090_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M16_080_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M16_100_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M16_090_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M16_105_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M16_100_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M16_120_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M16_105_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M17_020_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M16_120_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M17_040_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M17_020_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M17_060_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M17_040_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M17_065_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M17_060_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M17_090_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M17_065_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M17_120_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M17_090_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M17_140_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M17_120_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M17_150_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M17_140_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M17_155_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M17_150_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M17_170_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M17_155_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M17_200_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M17_170_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M17_210_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M17_200_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M17_220_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M17_210_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M17_225_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M17_220_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M17_240_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M17_225_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M18_020_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M17_240_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.M18_030_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M18_020_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.S01_010_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.M18_030_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.S01_020_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.S01_010_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.S01_030_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.S01_020_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.S01_040_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.S01_030_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.S01_050_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.S01_040_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.S01_060_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.S01_050_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.S01_080_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.S01_060_DESUKAAN_FREE_START
end
function DESUKAANMovTbl.ALL_CLEAR_DESUKAAN_FREE_START()
  return DESUKAANMovTbl.S01_080_DESUKAAN_FREE_START
end

