function DOKKORAA_1MovTbl.M02_010_DOKKORAA_1_FREE_START()
end
function DOKKORAA_1MovTbl.M02_030_DOKKORAA_1_FREE_START()
  local fmcCtrlObj = FREE_MOVE_SYSTEM:CreateFmcCtrl_Taikis({
    CH("DOKKORAA_1"),
    CH("DOKKORAA_2")
  })
  function fmcCtrlObj:TaikiActLoop()
    CH("DOKKORAA_2"):SetMotion(SymMot("SPEAK"), LOOP.ON)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    CH("DOKKORAA_2"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    subEveNodDouble(CH("DOKKORAA_1"))
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
  end
  function fmcCtrlObj:TaikiActFinish()
    CH("DOKKORAA_2"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
end
function DOKKORAA_1MovTbl.M02_050_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M02_030_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M02_070_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M02_050_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M02_080_DOKKORAA_1_FREE_START()
end
function DOKKORAA_1MovTbl.M02_090_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M02_080_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M02_100_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M02_090_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M02_115_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M02_100_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M02_130_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M02_115_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M02_160_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M02_130_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M03_010_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M02_160_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M03_020_DOKKORAA_1_FREE_START()
  subUseFreeAct2men01(CH("DOKKORAA_1"), CH("DOKKORAA_2"))
end
function DOKKORAA_1MovTbl.M03_045_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M03_020_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M03_090_DOKKORAA_1_FREE_START()
  local fmcCtrlObj = FREE_MOVE_SYSTEM:CreateFmcCtrl_Taikis({
    CH("DOKKORAA_1"),
    CH("DOKKORAA_2")
  })
  function fmcCtrlObj:TaikiActLoop()
    CH("DOKKORAA_1"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
    CH("DOKKORAA_2"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
    CH("DOKKORAA_2"):SetManpu("MP_FLY_SWEAT")
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    CH("DOKKORAA_1"):SetManpu("MP_FLY_SWEAT")
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
  end
  function fmcCtrlObj:TaikiActFinish()
    CH("DOKKORAA_2"):ResetManpu()
    CH("DOKKORAA_1"):ResetManpu()
  end
end
function DOKKORAA_1MovTbl.M03_110_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M03_090_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M03_130_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M03_110_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M03_150_DOKKORAA_1_FREE_START()
end
function DOKKORAA_1MovTbl.M04_010_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M03_150_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M04_020_DOKKORAA_1_FREE_START()
  subUseFreeAct2men01(CH("DOKKORAA_1"), CH("DOKKORAA_2"))
end
function DOKKORAA_1MovTbl.M04_HANYOU_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M04_020_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M04_040_DOKKORAA_1_FREE_START()
  subUseFreeAct2men02(CH("DOKKORAA_1"), CH("DOKKORAA_2"))
end
function DOKKORAA_1MovTbl.M04_060_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M04_040_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M04_070_DOKKORAA_1_FREE_START()
end
function DOKKORAA_1MovTbl.M04_HANYOU_DOKKORAA_1_FREE_START2()
  return DOKKORAA_1MovTbl.M04_070_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M05_000_DOKKORAA_1_FREE_START()
  local fmcCtrlObj = FREE_MOVE_SYSTEM:CreateFmcCtrl_Taikis({
    CH("DOKKORAA_1")
  })
  function fmcCtrlObj:TaikiActLoop()
    CH("DOKKORAA_1"):SetMotion(SymMot("PULL"), LOOP.ON)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    CH("DOKKORAA_1"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    CH("DOKKORAA_1"):SetManpu("MP_FLY_SWEAT")
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
  end
  function fmcCtrlObj:TaikiActFinish()
    CH("DOKKORAA_1"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    CH("DOKKORAA_1"):ResetManpu()
  end
end
function DOKKORAA_1MovTbl.M05_010_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M05_000_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M05_020_DOKKORAA_1_FREE_START()
end
function DOKKORAA_1MovTbl.M05_030_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M05_020_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M06_HANYOU_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M05_030_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M06_010_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M06_HANYOU_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M06_015_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M06_010_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M06_020_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M06_015_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M06_030_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M06_020_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M06_040_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M06_030_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M06_060_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M06_040_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M07_000_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M06_060_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M07_010_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M07_000_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M07_020_DOKKORAA_1_FREE_START()
  subUseFreeAct2men02(CH("DOKKORAA_1"), CH("DOKKORAA_2"))
end
function DOKKORAA_1MovTbl.M07_045_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M07_020_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M07_HANYOU_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M07_045_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M07_080_DOKKORAA_1_FREE_START()
end
function DOKKORAA_1MovTbl.M08_010_DOKKORAA_1_FREE_START()
  subUseFreeAct2men02(CH("DOKKORAA_1"), CH("DOKKORAA_2"))
end
function DOKKORAA_1MovTbl.M08_HANYOU_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M08_010_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M08_020_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M08_HANYOU_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M08_040_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M08_020_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M08_050_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M08_040_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M08_055_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M08_050_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M08_070_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M08_055_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M09_HANYOU_DOKKORAA_1_FREE_START1()
  subUseFreeAct2men01(CH("DOKKORAA_1"), CH("DOKKORAA_2"))
end
function DOKKORAA_1MovTbl.M09_010_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M09_HANYOU_DOKKORAA_1_FREE_START1
end
function DOKKORAA_1MovTbl.M09_020_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M09_010_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M09_040_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M09_020_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M09_HANYOU_DOKKORAA_1_FREE_START2()
  return DOKKORAA_1MovTbl.M09_040_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M09_060_DOKKORAA_1_FREE_START()
  subUseFreeAct2men02(CH("DOKKORAA_1"), CH("DOKKORAA_2"))
end
function DOKKORAA_1MovTbl.M09_080_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M09_060_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M09_100_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M09_080_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M09_110_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M09_100_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M09_120_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M09_110_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M10_010_DOKKORAA_1_FREE_START()
end
function DOKKORAA_1MovTbl.M10_030_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M10_010_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M10_040_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M10_030_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M10_060_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M10_040_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M11_010_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M10_060_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M11_030_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M11_010_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M11_040_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M11_030_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M11_050_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M11_040_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M11_060_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M11_050_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M11_075_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M11_060_DOKKORAA_1_FREE_START
end
function DOKKORAA_1MovTbl.M11_090_DOKKORAA_1_FREE_START()
  return DOKKORAA_1MovTbl.M11_075_DOKKORAA_1_FREE_START
end

