function EMONGAMovTbl.M02_010_EMONGA_FREE_START()
end
function EMONGAMovTbl.M02_030_EMONGA_FREE_START()
  return EMONGAMovTbl.M02_010_EMONGA_FREE_START
end
function EMONGAMovTbl.M02_050_EMONGA_FREE_START()
  return EMONGAMovTbl.M02_030_EMONGA_FREE_START
end
function EMONGAMovTbl.M02_070_EMONGA_FREE_START()
  return EMONGAMovTbl.M02_050_EMONGA_FREE_START
end
function EMONGAMovTbl.M02_080_EMONGA_FREE_START()
  return EMONGAMovTbl.M02_070_EMONGA_FREE_START
end
function EMONGAMovTbl.M02_090_EMONGA_FREE_START()
  return EMONGAMovTbl.M02_080_EMONGA_FREE_START
end
function EMONGAMovTbl.M02_100_EMONGA_FREE_START()
  return EMONGAMovTbl.M02_090_EMONGA_FREE_START
end
function EMONGAMovTbl.M02_115_EMONGA_FREE_START()
  return EMONGAMovTbl.M02_100_EMONGA_FREE_START
end
function EMONGAMovTbl.M02_130_EMONGA_FREE_START()
  return EMONGAMovTbl.M02_115_EMONGA_FREE_START
end
function EMONGAMovTbl.M02_160_EMONGA_FREE_START()
  return EMONGAMovTbl.M02_130_EMONGA_FREE_START
end
function EMONGAMovTbl.M03_010_EMONGA_FREE_START()
  return EMONGAMovTbl.M02_160_EMONGA_FREE_START
end
function EMONGAMovTbl.M03_020_EMONGA_FREE_START()
  return EMONGAMovTbl.M03_010_EMONGA_FREE_START
end
function EMONGAMovTbl.M03_045_EMONGA_FREE_START()
  return EMONGAMovTbl.M03_020_EMONGA_FREE_START
end
function EMONGAMovTbl.M03_090_EMONGA_FREE_START()
  return EMONGAMovTbl.M03_045_EMONGA_FREE_START
end
function EMONGAMovTbl.M03_110_EMONGA_FREE_START()
  return EMONGAMovTbl.M03_090_EMONGA_FREE_START
end
function EMONGAMovTbl.M03_130_EMONGA_FREE_START()
  return EMONGAMovTbl.M03_110_EMONGA_FREE_START
end
function EMONGAMovTbl.M03_150_EMONGA_FREE_START()
  return EMONGAMovTbl.M03_130_EMONGA_FREE_START
end
function EMONGAMovTbl.M04_010_EMONGA_FREE_START()
  return EMONGAMovTbl.M03_150_EMONGA_FREE_START
end
function EMONGAMovTbl.M04_020_EMONGA_FREE_START()
  subUseFreeActTalkPair(CH("EMONGA"), CH("NOKOTCHI"))
end
function EMONGAMovTbl.M04_HANYOU_EMONGA_FREE_START()
  return EMONGAMovTbl.M04_020_EMONGA_FREE_START
end
function EMONGAMovTbl.M04_040_EMONGA_FREE_START()
  return EMONGAMovTbl.M04_HANYOU_EMONGA_FREE_START
end
function EMONGAMovTbl.M04_060_EMONGA_FREE_START()
  return EMONGAMovTbl.M04_040_EMONGA_FREE_START
end
function EMONGAMovTbl.M04_070_EMONGA_FREE_START()
end
function EMONGAMovTbl.M04_HANYOU_EMONGA_FREE_START2()
  return EMONGAMovTbl.M04_070_EMONGA_FREE_START
end
function EMONGAMovTbl.M05_000_EMONGA_FREE_START()
  local fmcCtrlObj = FREE_MOVE_SYSTEM:CreateFmcCtrl_TaikisWithPush({
    CH("NOKOTCHI"),
    CH("EMONGA")
  })
  function fmcCtrlObj:TaikiActLoop()
    CH("NOKOTCHI"):SetMotionRaito(Raito(1.5))
    CH("NOKOTCHI"):SetMotion(SymMot("WALK"), LOOP.ON)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    CH("NOKOTCHI"):SetMotionRaito(Raito(1))
    CH("NOKOTCHI"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    CH("EMONGA"):SetManpu("MP_LAUGH_LP")
    CH("EMONGA"):SetFacialMotion(FACIAL_MOTION.HAPPY)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    CH("EMONGA"):ResetManpu()
    CH("EMONGA"):SetFacialMotion(FACIAL_MOTION.NORMAL)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
  end
  function fmcCtrlObj:TaikiActFinish()
    CH("EMONGA"):ResetManpu()
    CH("EMONGA"):SetFacialMotion(FACIAL_MOTION.NORMAL)
    CH("NOKOTCHI"):SetMotionRaito(Raito(1))
    CH("NOKOTCHI"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
end
function EMONGAMovTbl.M05_010_EMONGA_FREE_START()
  return EMONGAMovTbl.M05_000_EMONGA_FREE_START
end
function EMONGAMovTbl.M05_020_EMONGA_FREE_START()
  return EMONGAMovTbl.M05_010_EMONGA_FREE_START
end
function EMONGAMovTbl.M05_030_EMONGA_FREE_START()
end
function EMONGAMovTbl.M06_HANYOU_EMONGA_FREE_START()
  return EMONGAMovTbl.M05_030_EMONGA_FREE_START
end
function EMONGAMovTbl.M06_010_EMONGA_FREE_START()
  return EMONGAMovTbl.M06_HANYOU_EMONGA_FREE_START
end
function EMONGAMovTbl.M06_015_EMONGA_FREE_START()
  return EMONGAMovTbl.M06_010_EMONGA_FREE_START
end
function EMONGAMovTbl.M06_020_EMONGA_FREE_START()
  return EMONGAMovTbl.M06_015_EMONGA_FREE_START
end
function EMONGAMovTbl.M06_030_EMONGA_FREE_START()
  return EMONGAMovTbl.M06_020_EMONGA_FREE_START
end
function EMONGAMovTbl.M06_040_EMONGA_FREE_START()
  return EMONGAMovTbl.M06_030_EMONGA_FREE_START
end
function EMONGAMovTbl.M06_060_EMONGA_FREE_START()
  return EMONGAMovTbl.M06_040_EMONGA_FREE_START
end
function EMONGAMovTbl.M07_000_EMONGA_FREE_START()
  return EMONGAMovTbl.M06_060_EMONGA_FREE_START
end
function EMONGAMovTbl.M07_010_EMONGA_FREE_START()
  return EMONGAMovTbl.M07_000_EMONGA_FREE_START
end
function EMONGAMovTbl.M07_020_EMONGA_FREE_START()
  return EMONGAMovTbl.M07_010_EMONGA_FREE_START
end
function EMONGAMovTbl.M07_045_EMONGA_FREE_START()
  return EMONGAMovTbl.M07_020_EMONGA_FREE_START
end
function EMONGAMovTbl.M07_HANYOU_EMONGA_FREE_START()
  return EMONGAMovTbl.M07_045_EMONGA_FREE_START
end
function EMONGAMovTbl.M07_080_EMONGA_FREE_START()
  return EMONGAMovTbl.M07_HANYOU_EMONGA_FREE_START
end
function EMONGAMovTbl.M08_010_EMONGA_FREE_START()
  local fmcCtrlObj = FREE_MOVE_SYSTEM:CreateFmcCtrl_TaikisWithPush({
    CH("NOKOTCHI"),
    CH("EMONGA")
  })
  function fmcCtrlObj:TaikiActLoop()
    CH("NOKOTCHI"):SetMotionRaito(Raito(1.5))
    CH("NOKOTCHI"):SetMotion(SymMot("WALK"), LOOP.ON)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    CH("NOKOTCHI"):SetMotionRaito(Raito(1))
    CH("NOKOTCHI"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    CH("EMONGA"):SetManpu("MP_LAUGH_LP")
    CH("EMONGA"):SetFacialMotion(FACIAL_MOTION.HAPPY)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    CH("EMONGA"):ResetManpu()
    CH("EMONGA"):SetFacialMotion(FACIAL_MOTION.NORMAL)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
  end
  function fmcCtrlObj:TaikiActFinish()
    CH("EMONGA"):ResetManpu()
    CH("EMONGA"):SetFacialMotion(FACIAL_MOTION.NORMAL)
    CH("NOKOTCHI"):SetMotionRaito(Raito(1))
    CH("NOKOTCHI"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
end
function EMONGAMovTbl.M08_HANYOU_EMONGA_FREE_START()
  return EMONGAMovTbl.M08_010_EMONGA_FREE_START
end
function EMONGAMovTbl.M08_020_EMONGA_FREE_START()
  subUseFreeActTalkNormalTrio03(CH("EMONGA"), CH("BIRIJION"), CH("NOKOTCHI"))
end
function EMONGAMovTbl.M08_040_EMONGA_FREE_START()
  return EMONGAMovTbl.M08_020_EMONGA_FREE_START
end
function EMONGAMovTbl.M08_050_EMONGA_FREE_START()
  return EMONGAMovTbl.M08_040_EMONGA_FREE_START
end
function EMONGAMovTbl.M08_055_EMONGA_FREE_START()
  return EMONGAMovTbl.M08_050_EMONGA_FREE_START
end
function EMONGAMovTbl.M08_070_EMONGA_FREE_START()
  return EMONGAMovTbl.M08_055_EMONGA_FREE_START
end
function EMONGAMovTbl.M09_HANYOU_EMONGA_FREE_START1()
  local fmcCtrlObj = FREE_MOVE_SYSTEM:CreateFmcCtrl_TaikisWithPush({
    CH("NOKOTCHI"),
    CH("EMONGA")
  })
  function fmcCtrlObj:TaikiActLoop()
    CH("NOKOTCHI"):SetMotionRaito(Raito(1.5))
    CH("NOKOTCHI"):SetMotion(SymMot("WALK"), LOOP.ON)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    CH("NOKOTCHI"):SetMotionRaito(Raito(1))
    CH("NOKOTCHI"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    CH("EMONGA"):SetManpu("MP_LAUGH_LP")
    CH("EMONGA"):SetFacialMotion(FACIAL_MOTION.HAPPY)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    CH("EMONGA"):ResetManpu()
    CH("EMONGA"):SetFacialMotion(FACIAL_MOTION.NORMAL)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
  end
  function fmcCtrlObj:TaikiActFinish()
    CH("EMONGA"):ResetManpu()
    CH("EMONGA"):SetFacialMotion(FACIAL_MOTION.NORMAL)
    CH("NOKOTCHI"):SetMotionRaito(Raito(1))
    CH("NOKOTCHI"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
end
function EMONGAMovTbl.M09_010_EMONGA_FREE_START()
  return EMONGAMovTbl.M09_HANYOU_EMONGA_FREE_START1
end
function EMONGAMovTbl.M09_020_EMONGA_FREE_START()
  return EMONGAMovTbl.M09_010_EMONGA_FREE_START
end
function EMONGAMovTbl.M09_040_EMONGA_FREE_START()
  return EMONGAMovTbl.M09_020_EMONGA_FREE_START
end
function EMONGAMovTbl.M09_HANYOU_EMONGA_FREE_START2()
  return EMONGAMovTbl.M09_040_EMONGA_FREE_START
end
function EMONGAMovTbl.M09_060_EMONGA_FREE_START()
  subUseFreeActGenkiganaiOnly(CH("EMONGA"))
end
function EMONGAMovTbl.M09_080_EMONGA_FREE_START()
end
function EMONGAMovTbl.M09_100_EMONGA_FREE_START()
  return EMONGAMovTbl.M09_080_EMONGA_FREE_START
end
function EMONGAMovTbl.M09_110_EMONGA_FREE_START()
  return EMONGAMovTbl.M09_100_EMONGA_FREE_START
end
function EMONGAMovTbl.M09_120_EMONGA_FREE_START()
  return EMONGAMovTbl.M09_110_EMONGA_FREE_START
end
function EMONGAMovTbl.M10_010_EMONGA_FREE_START()
  return EMONGAMovTbl.M09_120_EMONGA_FREE_START
end
function EMONGAMovTbl.M10_030_EMONGA_FREE_START()
  return EMONGAMovTbl.M10_010_EMONGA_FREE_START
end
function EMONGAMovTbl.M10_040_EMONGA_FREE_START()
  return EMONGAMovTbl.M10_030_EMONGA_FREE_START
end
function EMONGAMovTbl.M10_060_EMONGA_FREE_START()
  return EMONGAMovTbl.M10_040_EMONGA_FREE_START
end
function EMONGAMovTbl.M11_010_EMONGA_FREE_START()
  return EMONGAMovTbl.M10_060_EMONGA_FREE_START
end
function EMONGAMovTbl.M11_030_EMONGA_FREE_START()
  return EMONGAMovTbl.M11_010_EMONGA_FREE_START
end
function EMONGAMovTbl.M11_040_EMONGA_FREE_START()
  return EMONGAMovTbl.M11_030_EMONGA_FREE_START
end
function EMONGAMovTbl.M11_050_EMONGA_FREE_START()
  return EMONGAMovTbl.M11_040_EMONGA_FREE_START
end
function EMONGAMovTbl.M11_060_EMONGA_FREE_START()
  return EMONGAMovTbl.M11_050_EMONGA_FREE_START
end
function EMONGAMovTbl.M11_075_EMONGA_FREE_START()
  return EMONGAMovTbl.M11_060_EMONGA_FREE_START
end
function EMONGAMovTbl.M11_090_EMONGA_FREE_START()
  return EMONGAMovTbl.M11_075_EMONGA_FREE_START
end

