function EMONGAMovTbl.M12_010_EMONGA_FREE_START()
end
function EMONGAMovTbl.M12_020_EMONGA_FREE_START()
  return EMONGAMovTbl.M12_010_EMONGA_FREE_START
end
function EMONGAMovTbl.M12_030_EMONGA_FREE_START()
  return EMONGAMovTbl.M12_020_EMONGA_FREE_START
end
function EMONGAMovTbl.M12_040_EMONGA_FREE_START()
  return EMONGAMovTbl.M12_030_EMONGA_FREE_START
end
function EMONGAMovTbl.M12_050_EMONGA_FREE_START()
  subUseFreeActTalkPair(CH("EMONGA"), CH("NOKOTCHI"))
end
function EMONGAMovTbl.M12_070_EMONGA_FREE_START()
  subUseFreeActTalkNormalTrio03(CH("EMONGA"), CH("NOKOTCHI"), CH("BIRIJION"))
end
function EMONGAMovTbl.M13_010_EMONGA_FREE_START()
end
function EMONGAMovTbl.M13_030_EMONGA_FREE_START()
  return EMONGAMovTbl.M13_010_EMONGA_FREE_START
end
function EMONGAMovTbl.M13_040_EMONGA_FREE_START()
  return EMONGAMovTbl.M13_030_EMONGA_FREE_START
end
function EMONGAMovTbl.M13_060_EMONGA_FREE_START()
  return EMONGAMovTbl.M13_040_EMONGA_FREE_START
end
function EMONGAMovTbl.M13_070_EMONGA_FREE_START()
  return EMONGAMovTbl.M13_060_EMONGA_FREE_START
end
function EMONGAMovTbl.M13_080_EMONGA_FREE_START()
  return EMONGAMovTbl.M13_070_EMONGA_FREE_START
end
function EMONGAMovTbl.M13_090_EMONGA_FREE_START()
  return EMONGAMovTbl.M13_080_EMONGA_FREE_START
end
function EMONGAMovTbl.M13_095_EMONGA_FREE_START()
  return EMONGAMovTbl.M13_090_EMONGA_FREE_START
end
function EMONGAMovTbl.M13_110_EMONGA_FREE_START()
  return EMONGAMovTbl.M13_095_EMONGA_FREE_START
end
function EMONGAMovTbl.M14_010_EMONGA_FREE_START()
  return EMONGAMovTbl.M13_110_EMONGA_FREE_START
end
function EMONGAMovTbl.M14_030_EMONGA_FREE_START()
  return EMONGAMovTbl.M14_010_EMONGA_FREE_START
end
function EMONGAMovTbl.M14_040_EMONGA_FREE_START()
  return EMONGAMovTbl.M14_030_EMONGA_FREE_START
end
function EMONGAMovTbl.M14_060_EMONGA_FREE_START()
  return EMONGAMovTbl.M14_040_EMONGA_FREE_START
end
function EMONGAMovTbl.M14_070_EMONGA_FREE_START()
  return EMONGAMovTbl.M14_060_EMONGA_FREE_START
end
function EMONGAMovTbl.M14_090_EMONGA_FREE_START()
  return EMONGAMovTbl.M14_070_EMONGA_FREE_START
end
function EMONGAMovTbl.M15_010_EMONGA_FREE_START()
  return EMONGAMovTbl.M14_090_EMONGA_FREE_START
end
function EMONGAMovTbl.M15_020_EMONGA_FREE_START()
  return EMONGAMovTbl.M15_010_EMONGA_FREE_START
end
function EMONGAMovTbl.M15_030_EMONGA_FREE_START()
  return EMONGAMovTbl.M15_020_EMONGA_FREE_START
end
function EMONGAMovTbl.M16_010_EMONGA_FREE_START()
  return EMONGAMovTbl.M15_030_EMONGA_FREE_START
end
function EMONGAMovTbl.M16_040_EMONGA_FREE_START()
  local fmcCtrlObj = FREE_MOVE_SYSTEM:CreateFmcCtrl_Taikis({
    CH("EMONGA")
  })
  function fmcCtrlObj:TaikiActLoop()
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    CH("EMONGA"):SetManpu("MP_UPSET_LP")
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    CH("EMONGA"):ResetManpu()
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
  end
  function fmcCtrlObj:TaikiActFinish()
    CH("EMONGA"):ResetManpu()
  end
end
function EMONGAMovTbl.M16_080_EMONGA_FREE_START()
  FREE_MOVE_SYSTEM:CreateFmcCtrl_TaikisWithPush({
    CH("EMONGA")
  })
end
function EMONGAMovTbl.M16_090_EMONGA_FREE_START()
  return EMONGAMovTbl.M16_080_EMONGA_FREE_START
end
function EMONGAMovTbl.M16_100_EMONGA_FREE_START()
  return EMONGAMovTbl.M16_090_EMONGA_FREE_START
end
function EMONGAMovTbl.M16_105_EMONGA_FREE_START()
  return EMONGAMovTbl.M16_100_EMONGA_FREE_START
end
function EMONGAMovTbl.M16_120_EMONGA_FREE_START()
  return EMONGAMovTbl.M16_105_EMONGA_FREE_START
end
function EMONGAMovTbl.M17_020_EMONGA_FREE_START()
  return EMONGAMovTbl.M16_120_EMONGA_FREE_START
end
function EMONGAMovTbl.M17_040_EMONGA_FREE_START()
  return EMONGAMovTbl.M17_020_EMONGA_FREE_START
end
function EMONGAMovTbl.M17_060_EMONGA_FREE_START()
  return EMONGAMovTbl.M17_040_EMONGA_FREE_START
end
function EMONGAMovTbl.M17_065_EMONGA_FREE_START()
  return EMONGAMovTbl.M17_060_EMONGA_FREE_START
end
function EMONGAMovTbl.M17_090_EMONGA_FREE_START()
  return EMONGAMovTbl.M17_065_EMONGA_FREE_START
end
function EMONGAMovTbl.M17_120_EMONGA_FREE_START()
  return EMONGAMovTbl.M17_090_EMONGA_FREE_START
end
function EMONGAMovTbl.M17_140_EMONGA_FREE_START()
  return EMONGAMovTbl.M17_120_EMONGA_FREE_START
end
function EMONGAMovTbl.M17_150_EMONGA_FREE_START()
  return EMONGAMovTbl.M17_140_EMONGA_FREE_START
end
function EMONGAMovTbl.M17_155_EMONGA_FREE_START()
  return EMONGAMovTbl.M17_150_EMONGA_FREE_START
end
function EMONGAMovTbl.M17_170_EMONGA_FREE_START()
  return EMONGAMovTbl.M17_155_EMONGA_FREE_START
end
function EMONGAMovTbl.M17_200_EMONGA_FREE_START()
  return EMONGAMovTbl.M17_170_EMONGA_FREE_START
end
function EMONGAMovTbl.M17_210_EMONGA_FREE_START()
  return EMONGAMovTbl.M17_200_EMONGA_FREE_START
end
function EMONGAMovTbl.M17_220_EMONGA_FREE_START()
  return EMONGAMovTbl.M17_210_EMONGA_FREE_START
end
function EMONGAMovTbl.M17_225_EMONGA_FREE_START()
  return EMONGAMovTbl.M17_220_EMONGA_FREE_START
end
function EMONGAMovTbl.M17_240_EMONGA_FREE_START()
  return EMONGAMovTbl.M17_225_EMONGA_FREE_START
end
function EMONGAMovTbl.M18_020_EMONGA_FREE_START()
  return EMONGAMovTbl.M17_240_EMONGA_FREE_START
end
function EMONGAMovTbl.M18_030_EMONGA_FREE_START()
  return EMONGAMovTbl.M18_020_EMONGA_FREE_START
end
function EMONGAMovTbl.S01_010_EMONGA_FREE_START()
  subUseFreeActTalkNormalTrio03(CH("EMONGA"), CH("NOKOTCHI"), CH("BIRIJION"))
end
function EMONGAMovTbl.S01_020_EMONGA_FREE_START()
  FREE_MOVE_SYSTEM:CreateFmcCtrl_TaikisWithPush({
    CH("EMONGA")
  })
end
function EMONGAMovTbl.S01_030_EMONGA_FREE_START()
  subUseFreeAct2men01(CH("EMONGA"), CH("BIRIJION"))
end
function EMONGAMovTbl.S01_040_EMONGA_FREE_START()
end
function EMONGAMovTbl.S01_050_EMONGA_FREE_START()
  subUseFreeActTalkPair(CH("EMONGA"), CH("NOKOTCHI"))
end
function EMONGAMovTbl.S01_060_EMONGA_FREE_START()
end
function EMONGAMovTbl.S01_080_EMONGA_FREE_START()
  subUseFreeActTalkPair(CH("EMONGA"), CH("NOKOTCHI"))
end
function EMONGAMovTbl.ALL_CLEAR_EMONGA_FREE_START()
  subUseFreeActTalkNormalTrio03(CH("EMONGA"), CH("NOKOTCHI"), CH("BIRIJION"))
end

