function HAADERIAMovTbl.M12_010_HAADERIA_FREE_START()
end
function HAADERIAMovTbl.M12_020_HAADERIA_FREE_START()
  subUseFreeMoveAct01(CH("HAADERIA"), "$FREE_MOVE_RANGE_02")
end
function HAADERIAMovTbl.M12_030_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M12_020_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M12_040_HAADERIA_FREE_START()
end
function HAADERIAMovTbl.M12_050_HAADERIA_FREE_START()
  subUseFreeMoveAct01(CH("HAADERIA"), "$FREE_MOVE_RANGE_02")
end
function HAADERIAMovTbl.M12_070_HAADERIA_FREE_START()
  FREE_MOVE_SYSTEM:CreateFmcCtrl_TaikisWithPush({
    CH("HAADERIA")
  })
end
function HAADERIAMovTbl.M13_010_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M12_070_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M13_030_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M13_010_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M13_040_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M13_030_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M13_060_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M13_040_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M13_070_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M13_060_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M13_080_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M13_070_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M13_090_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M13_080_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M13_095_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M13_090_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M13_110_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M13_095_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M14_010_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M13_110_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M14_030_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M14_010_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M14_040_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M14_030_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M14_060_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M14_040_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M14_070_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M14_060_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M14_090_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M14_070_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M15_010_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M14_090_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M15_020_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M15_010_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M15_030_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M15_020_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M16_010_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M15_030_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M16_040_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M16_010_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M16_080_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M16_040_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M16_090_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M16_080_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M16_100_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M16_090_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M16_105_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M16_100_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M16_120_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M16_105_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M17_020_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M16_120_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M17_040_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M17_020_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M17_060_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M17_040_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M17_065_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M17_060_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M17_090_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M17_065_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M17_120_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M17_090_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M17_140_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M17_120_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M17_150_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M17_140_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M17_155_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M17_150_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M17_170_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M17_155_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M17_200_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M17_170_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M17_210_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M17_200_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M17_220_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M17_210_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M17_225_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M17_220_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M17_240_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M17_225_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M18_020_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M17_240_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M18_030_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M18_020_HAADERIA_FREE_START
end
function HAADERIAMovTbl.S01_010_HAADERIA_FREE_START()
  subUseFreeMoveAct02(CH("HAADERIA"), "$FREE_MOVE_RANGE_03")
end
function HAADERIAMovTbl.S01_020_HAADERIA_FREE_START()
end
function HAADERIAMovTbl.S01_030_HAADERIA_FREE_START()
  return HAADERIAMovTbl.S01_020_HAADERIA_FREE_START
end
function HAADERIAMovTbl.S01_040_HAADERIA_FREE_START()
  return HAADERIAMovTbl.S01_030_HAADERIA_FREE_START
end
function HAADERIAMovTbl.S01_050_HAADERIA_FREE_START()
  return HAADERIAMovTbl.S01_040_HAADERIA_FREE_START
end
function HAADERIAMovTbl.S01_060_HAADERIA_FREE_START()
  return HAADERIAMovTbl.S01_050_HAADERIA_FREE_START
end
function HAADERIAMovTbl.S01_080_HAADERIA_FREE_START()
  local fmcCtrlObj = FREE_MOVE_SYSTEM:CreateFmcCtrl_Taikis({
    CH("HAADERIA")
  })
  FREE_MOVE_SYSTEM:CreateFmcCtrl_ForShopStaff(CH("HAADERIA"))
  function fmcCtrlObj:TaikiActLoop()
    local char_a = self:GetTargetCharaObj(0)
    TASK:Sleep(TimeSec(0.75), TASK_EXIT.QUICK)
    char_a:SetManpu("MP_SPREE_LP")
    char_a:SetMotion(SymMot("SPEAK"), LOOP.ON)
    TASK:Sleep(TimeSec(1), TASK_EXIT.QUICK)
    char_a:ResetManpu()
    char_a:SetMotion(SymMot("WAIT02"), LOOP.ON)
    TASK:Sleep(TimeSec(1.75), TASK_EXIT.QUICK)
  end
  function fmcCtrlObj:TaikiActFinish()
    char_a:SetMotion(SymMot("WAIT02"), LOOP.ON)
    char_a:ResetManpu()
  end
end
function HAADERIAMovTbl.ALL_CLEAR_HAADERIA_FREE_START()
  FREE_MOVE_SYSTEM:CreateFmcCtrl_TaikisWithPush({
    CH("HAADERIA")
  })
end

