function HAADERIAMovTbl.M02_010_HAADERIA_FREE_START()
end
function HAADERIAMovTbl.M02_030_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M02_010_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M02_050_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M02_030_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M02_070_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M02_050_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M02_080_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M02_070_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M02_090_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M02_080_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M02_100_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M02_090_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M02_115_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M02_100_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M02_130_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M02_115_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M02_160_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M02_130_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M03_010_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M02_160_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M03_020_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M03_010_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M03_045_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M03_020_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M03_090_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M03_045_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M03_110_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M03_090_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M03_130_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M03_110_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M03_150_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M03_130_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M04_010_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M03_150_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M04_020_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M04_010_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M04_HANYOU_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M04_020_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M04_040_HAADERIA_FREE_START()
  subUseFreeMoveAct01(CH("HAADERIA"), "$FREE_MOVE_RANGE_01")
end
function HAADERIAMovTbl.M04_060_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M04_040_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M04_070_HAADERIA_FREE_START()
end
function HAADERIAMovTbl.M04_HANYOU_HAADERIA_FREE_START2()
  return HAADERIAMovTbl.M04_070_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M05_000_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M04_HANYOU_HAADERIA_FREE_START2
end
function HAADERIAMovTbl.M05_010_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M05_000_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M05_020_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M05_010_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M05_030_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M05_020_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M06_HANYOU_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M05_030_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M06_010_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M06_HANYOU_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M06_015_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M06_010_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M06_020_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M06_015_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M06_030_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M06_020_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M06_040_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M06_030_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M06_060_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M06_040_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M07_000_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M06_060_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M07_010_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M07_000_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M07_020_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M07_010_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M07_045_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M07_020_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M07_HANYOU_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M07_045_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M07_080_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M07_HANYOU_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M08_010_HAADERIA_FREE_START()
  FREE_MOVE_SYSTEM:CreateFmcCtrl_TaikisWithPush({
    CH("HAADERIA")
  })
end
function HAADERIAMovTbl.M08_HANYOU_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M08_010_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M08_020_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M08_HANYOU_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M08_040_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M08_020_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M08_050_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M08_040_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M08_055_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M08_050_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M08_070_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M08_055_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M09_HANYOU_HAADERIA_FREE_START1()
end
function HAADERIAMovTbl.M09_010_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M09_HANYOU_HAADERIA_FREE_START1
end
function HAADERIAMovTbl.M09_020_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M09_010_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M09_040_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M09_020_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M09_HANYOU_HAADERIA_FREE_START2()
  return HAADERIAMovTbl.M09_040_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M09_060_HAADERIA_FREE_START()
  FREE_MOVE_SYSTEM:CreateFmcCtrl_TaikisWithPush({
    CH("HAADERIA")
  })
end
function HAADERIAMovTbl.M09_080_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M09_060_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M09_100_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M09_080_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M09_110_HAADERIA_FREE_START()
end
function HAADERIAMovTbl.M09_120_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M09_110_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M10_010_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M09_120_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M10_030_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M10_010_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M10_040_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M10_030_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M10_060_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M10_040_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M11_010_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M10_060_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M11_030_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M11_010_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M11_040_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M11_030_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M11_050_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M11_040_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M11_060_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M11_050_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M11_075_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M11_060_HAADERIA_FREE_START
end
function HAADERIAMovTbl.M11_090_HAADERIA_FREE_START()
  return HAADERIAMovTbl.M11_075_HAADERIA_FREE_START
end

