function HAHAKOMORIMovTbl.M12_010_HAHAKOMORI_FREE_START()
end
function HAHAKOMORIMovTbl.M12_020_HAHAKOMORI_FREE_START()
  FREE_MOVE_SYSTEM:CreateFmcCtrl_TaikisWithPush({
    CH("HAHAKOMORI")
  })
end
function HAHAKOMORIMovTbl.M12_030_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M12_020_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M12_040_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M12_030_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M12_050_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M12_040_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M12_070_HAHAKOMORI_FREE_START()
end
function HAHAKOMORIMovTbl.M13_010_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M12_070_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M13_030_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M13_010_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M13_040_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M13_030_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M13_060_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M13_040_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M13_070_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M13_060_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M13_080_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M13_070_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M13_090_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M13_080_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M13_095_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M13_090_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M13_110_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M13_095_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M14_010_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M13_110_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M14_030_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M14_010_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M14_040_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M14_030_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M14_060_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M14_040_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M14_070_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M14_060_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M14_090_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M14_070_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M15_010_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M14_090_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M15_020_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M15_010_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M15_030_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M15_020_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M16_010_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M15_030_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M16_040_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M16_010_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M16_080_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M16_040_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M16_090_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M16_080_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M16_100_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M16_090_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M16_105_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M16_100_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M16_120_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M16_105_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M17_020_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M16_120_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M17_040_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M17_020_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M17_060_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M17_040_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M17_065_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M17_060_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M17_090_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M17_065_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M17_120_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M17_090_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M17_140_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M17_120_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M17_150_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M17_140_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M17_155_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M17_150_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M17_170_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M17_155_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M17_200_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M17_170_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M17_210_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M17_200_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M17_220_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M17_210_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M17_225_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M17_220_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M17_240_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M17_225_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M18_020_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M17_240_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M18_030_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M18_020_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.S01_010_HAHAKOMORI_FREE_START()
  subUseFreeActTalkNormalTrio(CH("YOOTERII"), CH("KURUMAYU"), CH("HAHAKOMORI"))
end
function HAHAKOMORIMovTbl.S01_020_HAHAKOMORI_FREE_START()
  subUseFreeAct2men02(CH("HAHAKOMORI"), CH("HAADERIA"))
end
function HAHAKOMORIMovTbl.S01_030_HAHAKOMORI_FREE_START()
  FREE_MOVE_SYSTEM:CreateFmcCtrl_TaikisWithPush({
    CH("HAHAKOMORI")
  })
end
function HAHAKOMORIMovTbl.S01_040_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.S01_030_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.S01_050_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.S01_040_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.S01_060_HAHAKOMORI_FREE_START()
  subUseFreeActTalkNormalPair(CH("KURUMAYU"), CH("HAHAKOMORI"))
end
function HAHAKOMORIMovTbl.S01_080_HAHAKOMORI_FREE_START()
  subUseFreeActTalkNormalTrio02(CH("YOOTERII"), CH("KURUMAYU"), CH("HAHAKOMORI"))
end
function HAHAKOMORIMovTbl.ALL_CLEAR_HAHAKOMORI_FREE_START()
  subUseFreeAct2men02(CH("HAHAKOMORI"), CH("KOJOFUU"))
end

