function HAHAKOMORIMovTbl.M02_010_HAHAKOMORI_FREE_START()
end
function HAHAKOMORIMovTbl.M02_030_HAHAKOMORI_FREE_START()
  subUseFreeMoveAct01(CH("HAHAKOMORI"), "$FREE_MOVE_RANGE_01")
end
function HAHAKOMORIMovTbl.M02_050_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M02_030_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M02_070_HAHAKOMORI_FREE_START()
end
function HAHAKOMORIMovTbl.M02_080_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M02_070_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M02_090_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M02_080_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M02_100_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M02_090_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M02_115_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M02_100_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M02_130_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M02_115_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M02_160_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M02_130_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M03_010_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M02_160_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M03_020_HAHAKOMORI_FREE_START()
  subUseFreeMoveAct01(CH("HAHAKOMORI"), "$FREE_MOVE_RANGE_02")
end
function HAHAKOMORIMovTbl.M03_045_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M03_020_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M03_090_HAHAKOMORI_FREE_START()
end
function HAHAKOMORIMovTbl.M03_110_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M03_090_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M03_130_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M03_110_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M03_150_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M03_130_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M04_010_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M03_150_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M04_020_HAHAKOMORI_FREE_START()
  FREE_MOVE_SYSTEM:CreateFmcCtrl_TaikisWithPush({
    CH("HAHAKOMORI")
  })
end
function HAHAKOMORIMovTbl.M04_HANYOU_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M04_020_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M04_040_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M04_HANYOU_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M04_060_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M04_040_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M04_070_HAHAKOMORI_FREE_START()
  subUseFreeMoveAct01(CH("HAHAKOMORI"), "$FREE_MOVE_RANGE_01")
end
function HAHAKOMORIMovTbl.M04_HANYOU_HAHAKOMORI_FREE_START2()
  return HAHAKOMORIMovTbl.M04_070_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M05_000_HAHAKOMORI_FREE_START()
end
function HAHAKOMORIMovTbl.M05_010_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M05_000_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M05_020_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M05_010_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M05_030_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M05_020_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M06_HANYOU_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M05_030_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M06_010_HAHAKOMORI_FREE_START()
  subUseFreeAct2men01(CH("KURUMAYU"), CH("HAHAKOMORI"))
end
function HAHAKOMORIMovTbl.M06_015_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M06_010_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M06_020_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M06_015_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M06_030_HAHAKOMORI_FREE_START()
end
function HAHAKOMORIMovTbl.M06_040_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M06_030_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M06_060_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M06_040_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M07_000_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M06_060_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M07_010_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M07_000_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M07_020_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M07_010_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M07_045_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M07_020_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M07_HANYOU_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M07_045_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M07_080_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M07_HANYOU_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M08_010_HAHAKOMORI_FREE_START()
  subUseFreeActTalkNormalTrio(CH("YOOTERII"), CH("KURUMAYU"), CH("HAHAKOMORI"))
end
function HAHAKOMORIMovTbl.M08_HANYOU_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M08_010_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M08_020_HAHAKOMORI_FREE_START()
end
function HAHAKOMORIMovTbl.M08_040_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M08_020_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M08_050_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M08_040_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M08_055_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M08_050_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M08_070_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M08_055_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M09_HANYOU_HAHAKOMORI_FREE_START1()
  return HAHAKOMORIMovTbl.M08_070_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M09_010_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M09_HANYOU_HAHAKOMORI_FREE_START1
end
function HAHAKOMORIMovTbl.M09_020_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M09_010_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M09_040_HAHAKOMORI_FREE_START()
  subUseFreeActTalkNormalTrio(CH("YOOTERII"), CH("KURUMAYU"), CH("HAHAKOMORI"))
end
function HAHAKOMORIMovTbl.M09_HANYOU_HAHAKOMORI_FREE_START2()
  return HAHAKOMORIMovTbl.M09_040_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M09_060_HAHAKOMORI_FREE_START()
end
function HAHAKOMORIMovTbl.M09_080_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M09_060_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M09_100_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M09_080_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M09_110_HAHAKOMORI_FREE_START()
  subUseFreeActTalkNormalTrio(CH("YOOTERII"), CH("KURUMAYU"), CH("HAHAKOMORI"))
end
function HAHAKOMORIMovTbl.M09_120_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M09_110_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M10_010_HAHAKOMORI_FREE_START()
end
function HAHAKOMORIMovTbl.M10_030_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M10_010_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M10_040_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M10_030_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M10_060_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M10_040_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M11_010_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M10_060_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M11_030_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M11_010_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M11_040_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M11_030_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M11_050_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M11_040_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M11_060_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M11_050_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M11_075_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M11_060_HAHAKOMORI_FREE_START
end
function HAHAKOMORIMovTbl.M11_090_HAHAKOMORI_FREE_START()
  return HAHAKOMORIMovTbl.M11_075_HAHAKOMORI_FREE_START
end

