function HIYAPPUMovTbl.M12_010_HIYAPPU_FREE_START()
end
function HIYAPPUMovTbl.M12_020_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M12_010_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M12_030_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M12_020_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M12_040_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M12_030_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M12_050_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M12_040_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M12_070_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M12_050_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M13_010_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M12_070_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M13_030_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M13_010_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M13_040_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M13_030_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M13_060_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M13_040_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M13_070_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M13_060_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M13_080_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M13_070_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M13_090_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M13_080_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M13_095_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M13_090_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M13_110_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M13_095_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M14_010_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M13_110_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M14_030_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M14_010_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M14_040_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M14_030_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M14_060_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M14_040_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M14_070_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M14_060_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M14_090_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M14_070_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M15_010_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M14_090_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M15_020_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M15_010_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M15_030_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M15_020_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M16_010_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M15_030_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M16_040_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M16_010_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M16_080_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M16_040_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M16_090_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M16_080_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M16_100_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M16_090_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M16_105_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M16_100_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M16_120_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M16_105_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M17_020_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M16_120_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M17_040_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M17_020_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M17_060_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M17_040_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M17_065_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M17_060_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M17_090_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M17_065_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M17_120_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M17_090_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M17_140_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M17_120_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M17_150_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M17_140_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M17_155_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M17_150_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M17_170_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M17_155_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M17_200_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M17_170_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M17_210_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M17_200_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M17_220_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M17_210_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M17_225_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M17_220_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M17_240_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M17_225_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M18_020_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M17_240_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M18_030_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M18_020_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.S01_010_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M18_030_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.S01_020_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.S01_010_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.S01_030_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.S01_020_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.S01_040_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.S01_030_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.S01_050_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.S01_040_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.S01_060_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.S01_050_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.S01_080_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.S01_060_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.ALL_CLEAR_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.S01_080_HIYAPPU_FREE_START
end

