function HIYAPPUMovTbl.M02_010_HIYAPPU_FREE_START()
end
function HIYAPPUMovTbl.M02_030_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M02_010_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M02_050_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M02_030_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M02_070_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M02_050_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M02_080_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M02_070_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M02_090_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M02_080_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M02_100_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M02_090_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M02_115_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M02_100_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M02_130_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M02_115_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M02_160_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M02_130_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M03_010_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M02_160_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M03_020_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M03_010_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M03_045_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M03_020_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M03_090_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M03_045_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M03_110_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M03_090_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M03_130_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M03_110_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M03_150_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M03_130_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M04_010_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M03_150_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M04_020_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M04_010_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M04_HANYOU_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M04_020_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M04_040_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M04_HANYOU_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M04_060_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M04_040_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M04_070_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M04_060_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M04_HANYOU_HIYAPPU_FREE_START2()
  return HIYAPPUMovTbl.M04_070_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M05_000_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M04_HANYOU_HIYAPPU_FREE_START2
end
function HIYAPPUMovTbl.M05_010_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M05_000_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M05_020_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M05_010_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M05_030_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M05_020_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M06_HANYOU_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M05_030_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M06_010_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M06_HANYOU_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M06_015_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M06_010_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M06_020_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M06_015_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M06_030_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M06_020_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M06_040_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M06_030_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M06_060_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M06_040_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M07_000_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M06_060_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M07_010_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M07_000_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M07_020_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M07_010_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M07_045_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M07_020_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M07_HANYOU_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M07_045_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M07_080_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M07_HANYOU_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M08_010_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M07_080_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M08_HANYOU_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M08_010_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M08_020_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M08_HANYOU_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M08_040_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M08_020_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M08_050_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M08_040_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M08_055_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M08_050_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M08_070_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M08_055_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M09_HANYOU_HIYAPPU_FREE_START1()
  return HIYAPPUMovTbl.M08_070_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M09_010_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M09_HANYOU_HIYAPPU_FREE_START1
end
function HIYAPPUMovTbl.M09_020_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M09_010_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M09_040_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M09_020_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M09_HANYOU_HIYAPPU_FREE_START2()
  return HIYAPPUMovTbl.M09_040_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M09_060_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M09_HANYOU_HIYAPPU_FREE_START2
end
function HIYAPPUMovTbl.M09_080_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M09_060_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M09_100_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M09_080_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M09_110_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M09_100_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M09_120_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M09_110_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M10_010_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M09_120_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M10_030_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M10_010_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M10_040_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M10_030_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M10_060_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M10_040_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M11_010_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M10_060_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M11_030_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M11_010_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M11_040_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M11_030_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M11_050_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M11_040_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M11_060_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M11_050_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M11_075_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M11_060_HIYAPPU_FREE_START
end
function HIYAPPUMovTbl.M11_090_HIYAPPU_FREE_START()
  return HIYAPPUMovTbl.M11_075_HIYAPPU_FREE_START
end

