function KERUDYIOMovTbl.M12_010_KERUDYIO_FREE_START()
end
function KERUDYIOMovTbl.M12_020_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M12_010_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M12_030_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M12_020_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M12_040_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M12_030_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M12_050_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M12_040_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M12_070_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M12_050_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M13_010_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M12_070_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M13_030_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M13_010_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M13_040_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M13_030_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M13_060_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M13_040_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M13_070_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M13_060_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M13_080_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M13_070_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M13_090_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M13_080_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M13_095_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M13_090_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M13_110_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M13_095_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M14_010_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M13_110_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M14_030_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M14_010_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M14_040_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M14_030_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M14_060_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M14_040_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M14_070_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M14_060_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M14_090_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M14_070_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M15_010_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M14_090_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M15_020_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M15_010_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M15_030_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M15_020_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M16_010_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M15_030_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M16_040_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M16_010_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M16_080_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M16_040_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M16_090_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M16_080_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M16_100_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M16_090_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M16_105_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M16_100_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M16_120_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M16_105_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M17_020_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M16_120_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M17_040_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M17_020_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M17_060_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M17_040_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M17_065_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M17_060_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M17_090_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M17_065_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M17_120_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M17_090_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M17_140_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M17_120_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M17_150_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M17_140_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M17_155_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M17_150_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M17_170_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M17_155_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M17_200_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M17_170_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M17_210_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M17_200_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M17_220_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M17_210_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M17_225_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M17_220_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M17_240_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M17_225_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M18_020_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M17_240_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.M18_030_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.M18_020_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.S01_010_KERUDYIO_FREE_START()
  FREE_MOVE_SYSTEM:CreateFmcCtrl_TaikisWithPush({
    CH("KERUDYIO")
  })
end
function KERUDYIOMovTbl.S01_020_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.S01_010_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.S01_030_KERUDYIO_FREE_START()
  subUseFreeActRunRunOnly(CH("KERUDYIO"))
end
function KERUDYIOMovTbl.S01_040_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.S01_030_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.S01_050_KERUDYIO_FREE_START()
end
function KERUDYIOMovTbl.S01_060_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.S01_050_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.S01_080_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.S01_060_KERUDYIO_FREE_START
end
function KERUDYIOMovTbl.ALL_CLEAR_KERUDYIO_FREE_START()
  return KERUDYIOMovTbl.S01_080_KERUDYIO_FREE_START
end

