function KOARUHIIMovTbl.M12_010_KOARUHII_FREE_START()
end
function KOARUHIIMovTbl.M12_020_KOARUHII_FREE_START()
  local fmcCtrlObj = FREE_MOVE_SYSTEM:CreateFmcCtrl_Taikis({
    CH("KOARUHII")
  })
  CH("KOARUHII"):SetManpu("MP_SLEEP_LP")
  CH("KOARUHII"):SetMotion(SymMot("SLEEPLOOP"), LOOP.ON, TimeSec(0))
end
function KOARUHIIMovTbl.M12_030_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M12_020_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M12_040_KOARUHII_FREE_START()
  FREE_MOVE_SYSTEM:CreateFmcCtrl_TaikisWithPush({
    CH("KOARUHII")
  })
end
function KOARUHIIMovTbl.M12_050_KOARUHII_FREE_START()
end
function KOARUHIIMovTbl.M12_070_KOARUHII_FREE_START()
  subUseFreeMoveAct02(CH("KOARUHII"), "$FREE_MOVE_RANGE_02")
end
function KOARUHIIMovTbl.M13_010_KOARUHII_FREE_START()
end
function KOARUHIIMovTbl.M13_030_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M13_010_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M13_040_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M13_030_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M13_060_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M13_040_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M13_070_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M13_060_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M13_080_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M13_070_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M13_090_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M13_080_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M13_095_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M13_090_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M13_110_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M13_095_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M14_010_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M13_110_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M14_030_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M14_010_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M14_040_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M14_030_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M14_060_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M14_040_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M14_070_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M14_060_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M14_090_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M14_070_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M15_010_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M14_090_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M15_020_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M15_010_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M15_030_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M15_020_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M16_010_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M15_030_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M16_040_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M16_010_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M16_080_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M16_040_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M16_090_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M16_080_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M16_100_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M16_090_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M16_105_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M16_100_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M16_120_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M16_105_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M17_020_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M16_120_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M17_040_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M17_020_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M17_060_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M17_040_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M17_065_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M17_060_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M17_090_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M17_065_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M17_120_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M17_090_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M17_140_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M17_120_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M17_150_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M17_140_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M17_155_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M17_150_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M17_170_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M17_155_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M17_200_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M17_170_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M17_210_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M17_200_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M17_220_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M17_210_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M17_225_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M17_220_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M17_240_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M17_225_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M18_020_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M17_240_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M18_030_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M18_020_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.S01_010_KOARUHII_FREE_START()
  FREE_MOVE_SYSTEM:CreateFmcCtrl_TaikisWithPush({
    CH("KOARUHII")
  })
end
function KOARUHIIMovTbl.S01_020_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.S01_010_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.S01_030_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.S01_020_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.S01_040_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.S01_030_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.S01_050_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.S01_040_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.S01_060_KOARUHII_FREE_START()
  subUseFreeActSpreeOnly(CH("KOARUHII"))
end
function KOARUHIIMovTbl.S01_080_KOARUHII_FREE_START()
  subUseFreeAct2men01(CH("KOARUHII"), CH("DANGORO"))
end
function KOARUHIIMovTbl.ALL_CLEAR_KOARUHII_FREE_START()
end

