function KOARUHIIMovTbl.M02_010_KOARUHII_FREE_START()
end
function KOARUHIIMovTbl.M02_030_KOARUHII_FREE_START()
  FREE_MOVE_SYSTEM:CreateFmcCtrl_TaikisWithPush({
    CH("KOARUHII")
  })
end
function KOARUHIIMovTbl.M02_050_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M02_030_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M02_070_KOARUHII_FREE_START()
  subUseFreeActSpreeOnly(CH("KOARUHII"))
end
function KOARUHIIMovTbl.M02_080_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M02_070_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M02_090_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M02_080_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M02_100_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M02_090_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M02_115_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M02_100_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M02_130_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M02_115_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M02_160_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M02_130_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M03_010_KOARUHII_FREE_START()
  FREE_MOVE_SYSTEM:CreateFmcCtrl_TaikisWithPush({
    CH("KOARUHII")
  })
end
function KOARUHIIMovTbl.M03_020_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M03_010_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M03_045_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M03_020_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M03_090_KOARUHII_FREE_START()
  local fmcCtrlObj = FREE_MOVE_SYSTEM:CreateFmcCtrl_Taikis({
    CH("KOARUHII")
  })
  function fmcCtrlObj:TaikiActLoop()
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    CH("KOARUHII"):SetManpu("MP_FLY_SWEAT")
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    CH("KOARUHII"):ResetManpu()
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
  end
  function fmcCtrlObj:TaikiActFinish()
    CH("KOARUHII"):ResetManpu()
  end
end
function KOARUHIIMovTbl.M03_110_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M03_090_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M03_130_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M03_110_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M03_150_KOARUHII_FREE_START()
end
function KOARUHIIMovTbl.M04_010_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M03_150_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M04_020_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M04_010_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M04_HANYOU_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M04_020_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M04_040_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M04_HANYOU_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M04_060_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M04_040_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M04_070_KOARUHII_FREE_START()
  subUseFreeActSpreeOnly(CH("KOARUHII"))
end
function KOARUHIIMovTbl.M04_HANYOU_KOARUHII_FREE_START2()
  return KOARUHIIMovTbl.M04_070_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M05_000_KOARUHII_FREE_START()
end
function KOARUHIIMovTbl.M05_010_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M05_000_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M05_020_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M05_010_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M05_030_KOARUHII_FREE_START()
  subUseFreeMoveAct01(CH("KOARUHII"), "$FREE_MOVE_RANGE_01")
end
function KOARUHIIMovTbl.M06_HANYOU_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M05_030_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M06_010_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M06_HANYOU_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M06_015_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M06_010_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M06_020_KOARUHII_FREE_START()
end
function KOARUHIIMovTbl.M06_030_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M06_020_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M06_040_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M06_030_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M06_060_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M06_040_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M07_000_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M06_060_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M07_010_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M07_000_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M07_020_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M07_010_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M07_045_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M07_020_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M07_HANYOU_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M07_045_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M07_080_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M07_HANYOU_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M08_010_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M07_080_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M08_HANYOU_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M08_010_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M08_020_KOARUHII_FREE_START()
  subUseFreeAct2men01(CH("KOARUHII"), CH("DANGORO"))
end
function KOARUHIIMovTbl.M08_040_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M08_020_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M08_050_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M08_040_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M08_055_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M08_050_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M08_070_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M08_055_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M09_HANYOU_KOARUHII_FREE_START1()
end
function KOARUHIIMovTbl.M09_010_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M09_HANYOU_KOARUHII_FREE_START1
end
function KOARUHIIMovTbl.M09_020_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M09_010_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M09_040_KOARUHII_FREE_START()
  subUseFreeMoveAct02(CH("KOARUHII"), "$FREE_MOVE_RANGE_02")
end
function KOARUHIIMovTbl.M09_HANYOU_KOARUHII_FREE_START2()
  return KOARUHIIMovTbl.M09_040_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M09_060_KOARUHII_FREE_START()
end
function KOARUHIIMovTbl.M09_080_KOARUHII_FREE_START()
  FREE_MOVE_SYSTEM:CreateFmcCtrl_TaikisWithPush({
    CH("KOARUHII")
  })
end
function KOARUHIIMovTbl.M09_100_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M09_080_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M09_110_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M09_100_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M09_120_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M09_110_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M10_010_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M09_120_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M10_030_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M10_010_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M10_040_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M10_030_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M10_060_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M10_040_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M11_010_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M10_060_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M11_030_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M11_010_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M11_040_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M11_030_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M11_050_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M11_040_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M11_060_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M11_050_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M11_075_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M11_060_KOARUHII_FREE_START
end
function KOARUHIIMovTbl.M11_090_KOARUHII_FREE_START()
  return KOARUHIIMovTbl.M11_075_KOARUHII_FREE_START
end

