function KOJOFUUMovTbl.M02_010_KOJOFUU_FREE_START()
end
function KOJOFUUMovTbl.M02_030_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M02_010_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M02_050_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M02_030_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M02_070_KOJOFUU_FREE_START()
  FREE_MOVE_SYSTEM:CreateFmcCtrl_TaikisWithPush({
    CH("KOJOFUU")
  })
end
function KOJOFUUMovTbl.M02_080_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M02_070_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M02_090_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M02_080_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M02_100_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M02_090_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M02_115_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M02_100_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M02_130_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M02_115_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M02_160_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M02_130_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M03_010_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M02_160_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M03_020_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M03_010_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M03_045_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M03_020_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M03_090_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M03_045_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M03_110_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M03_090_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M03_130_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M03_110_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M03_150_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M03_130_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M04_010_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M03_150_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M04_020_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M04_010_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M04_HANYOU_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M04_020_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M04_040_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M04_HANYOU_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M04_060_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M04_040_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M04_070_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M04_060_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M04_HANYOU_KOJOFUU_FREE_START2()
  return KOJOFUUMovTbl.M04_070_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M05_000_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M04_HANYOU_KOJOFUU_FREE_START2
end
function KOJOFUUMovTbl.M05_010_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M05_000_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M05_020_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M05_010_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M05_030_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M05_020_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M06_HANYOU_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M05_030_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M06_010_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M06_HANYOU_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M06_015_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M06_010_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M06_020_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M06_015_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M06_030_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M06_020_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M06_040_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M06_030_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M06_060_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M06_040_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M07_000_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M06_060_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M07_010_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M07_000_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M07_020_KOJOFUU_FREE_START()
  subUseFreeMoveAct01(CH("KOJOFUU"), "$FREE_MOVE_RANGE_01")
end
function KOJOFUUMovTbl.M07_045_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M07_020_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M07_HANYOU_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M07_045_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M07_080_KOJOFUU_FREE_START()
end
function KOJOFUUMovTbl.M08_010_KOJOFUU_FREE_START()
  FREE_MOVE_SYSTEM:CreateFmcCtrl_TaikisWithPush({
    CH("KOJOFUU")
  })
end
function KOJOFUUMovTbl.M08_HANYOU_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M08_010_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M08_020_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M08_HANYOU_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M08_040_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M08_020_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M08_050_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M08_040_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M08_055_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M08_050_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M08_070_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M08_055_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M09_HANYOU_KOJOFUU_FREE_START1()
  return KOJOFUUMovTbl.M08_070_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M09_010_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M09_HANYOU_KOJOFUU_FREE_START1
end
function KOJOFUUMovTbl.M09_020_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M09_010_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M09_040_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M09_020_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M09_HANYOU_KOJOFUU_FREE_START2()
  return KOJOFUUMovTbl.M09_040_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M09_060_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M09_HANYOU_KOJOFUU_FREE_START2
end
function KOJOFUUMovTbl.M09_080_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M09_060_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M09_100_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M09_080_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M09_110_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M09_100_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M09_120_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M09_110_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M10_010_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M09_120_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M10_030_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M10_010_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M10_040_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M10_030_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M10_060_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M10_040_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M11_010_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M10_060_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M11_030_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M11_010_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M11_040_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M11_030_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M11_050_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M11_040_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M11_060_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M11_050_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M11_075_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M11_060_KOJOFUU_FREE_START
end
function KOJOFUUMovTbl.M11_090_KOJOFUU_FREE_START()
  return KOJOFUUMovTbl.M11_075_KOJOFUU_FREE_START
end

