function KURUMAYUMovTbl.M02_010_KURUMAYU_FREE_START()
end
function KURUMAYUMovTbl.M02_030_KURUMAYU_FREE_START()
  subUseFreeActKangaetyuuOnly(CH("KURUMAYU"))
end
function KURUMAYUMovTbl.M02_050_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M02_030_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M02_070_KURUMAYU_FREE_START()
end
function KURUMAYUMovTbl.M02_080_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M02_070_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M02_090_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M02_080_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M02_100_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M02_090_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M02_115_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M02_100_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M02_130_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M02_115_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M02_160_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M02_130_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M03_010_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M02_160_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M03_020_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M03_010_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M03_045_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M03_020_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M03_090_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M03_045_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M03_110_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M03_090_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M03_130_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M03_110_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M03_150_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M03_130_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M04_010_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M03_150_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M04_020_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M04_010_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M04_HANYOU_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M04_020_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M04_040_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M04_HANYOU_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M04_060_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M04_040_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M04_070_KURUMAYU_FREE_START()
  subUseFreeActKangaetyuuOnly(CH("KURUMAYU"))
end
function KURUMAYUMovTbl.M04_HANYOU_KURUMAYU_FREE_START2()
  return KURUMAYUMovTbl.M04_070_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M05_000_KURUMAYU_FREE_START()
end
function KURUMAYUMovTbl.M05_010_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M05_000_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M05_020_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M05_010_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M05_030_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M05_020_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M06_HANYOU_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M05_030_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M06_010_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M06_HANYOU_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M06_015_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M06_010_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M06_020_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M06_015_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M06_030_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M06_020_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M06_040_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M06_030_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M06_060_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M06_040_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M07_000_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M06_060_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M07_010_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M07_000_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M07_020_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M07_010_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M07_045_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M07_020_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M07_HANYOU_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M07_045_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M07_080_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M07_HANYOU_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M08_010_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M07_080_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M08_HANYOU_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M08_010_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M08_020_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M08_HANYOU_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M08_040_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M08_020_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M08_050_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M08_040_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M08_055_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M08_050_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M08_070_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M08_055_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M09_HANYOU_KURUMAYU_FREE_START1()
  return KURUMAYUMovTbl.M08_070_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M09_010_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M09_HANYOU_KURUMAYU_FREE_START1
end
function KURUMAYUMovTbl.M09_020_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M09_010_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M09_040_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M09_020_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M09_HANYOU_KURUMAYU_FREE_START2()
  return KURUMAYUMovTbl.M09_040_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M09_060_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M09_HANYOU_KURUMAYU_FREE_START2
end
function KURUMAYUMovTbl.M09_080_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M09_060_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M09_100_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M09_080_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M09_110_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M09_100_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M09_120_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M09_110_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M10_010_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M09_120_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M10_030_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M10_010_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M10_040_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M10_030_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M10_060_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M10_040_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M11_010_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M10_060_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M11_030_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M11_010_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M11_040_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M11_030_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M11_050_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M11_040_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M11_060_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M11_050_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M11_075_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M11_060_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M11_090_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M11_075_KURUMAYU_FREE_START
end

