function KURUMAYUMovTbl.M12_010_KURUMAYU_FREE_START()
end
function KURUMAYUMovTbl.M12_020_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M12_010_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M12_030_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M12_020_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M12_040_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M12_030_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M12_050_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M12_040_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M12_070_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M12_050_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M13_010_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M12_070_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M13_030_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M13_010_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M13_040_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M13_030_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M13_060_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M13_040_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M13_070_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M13_060_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M13_080_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M13_070_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M13_090_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M13_080_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M13_095_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M13_090_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M13_110_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M13_095_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M14_010_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M13_110_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M14_030_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M14_010_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M14_040_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M14_030_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M14_060_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M14_040_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M14_070_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M14_060_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M14_090_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M14_070_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M15_010_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M14_090_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M15_020_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M15_010_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M15_030_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M15_020_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M16_010_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M15_030_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M16_040_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M16_010_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M16_080_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M16_040_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M16_090_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M16_080_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M16_100_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M16_090_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M16_105_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M16_100_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M16_120_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M16_105_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M17_020_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M16_120_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M17_040_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M17_020_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M17_060_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M17_040_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M17_065_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M17_060_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M17_090_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M17_065_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M17_120_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M17_090_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M17_140_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M17_120_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M17_150_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M17_140_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M17_155_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M17_150_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M17_170_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M17_155_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M17_200_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M17_170_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M17_210_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M17_200_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M17_220_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M17_210_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M17_225_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M17_220_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M17_240_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M17_225_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M18_020_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M17_240_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.M18_030_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M18_020_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.S01_010_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.M18_030_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.S01_020_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.S01_010_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.S01_030_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.S01_020_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.S01_040_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.S01_030_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.S01_050_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.S01_040_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.S01_060_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.S01_050_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.S01_080_KURUMAYU_FREE_START()
  return KURUMAYUMovTbl.S01_060_KURUMAYU_FREE_START
end
function KURUMAYUMovTbl.ALL_CLEAR_KURUMAYU_FREE_START()
  FREE_MOVE_SYSTEM:CreateFmcCtrl_TaikisWithPush({
    CH("KURUMAYU")
  })
end

