function MARIRURIMovTbl.M12_010_MARIRURI_FREE_START()
  FREE_MOVE_SYSTEM:CreateFmcCtrl_ForShopStaff(CH("MARIRURI"))
end
function MARIRURIMovTbl.M12_020_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M12_010_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M12_030_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M12_020_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M12_040_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M12_030_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M12_050_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M12_040_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M12_070_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M12_050_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M13_010_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M12_070_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M13_030_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M13_010_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M13_040_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M13_030_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M13_060_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M13_040_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M13_070_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M13_060_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M13_080_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M13_070_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M13_090_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M13_080_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M13_095_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M13_090_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M13_110_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M13_095_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M14_010_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M13_110_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M14_030_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M14_010_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M14_040_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M14_030_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M14_060_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M14_040_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M14_070_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M14_060_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M14_090_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M14_070_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M15_010_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M14_090_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M15_020_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M15_010_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M15_030_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M15_020_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M16_010_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M15_030_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M16_040_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M16_010_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M16_080_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M16_040_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M16_090_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M16_080_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M16_100_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M16_090_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M16_105_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M16_100_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M16_120_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M16_105_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M17_020_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M16_120_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M17_040_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M17_020_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M17_060_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M17_040_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M17_065_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M17_060_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M17_090_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M17_065_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M17_120_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M17_090_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M17_140_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M17_120_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M17_150_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M17_140_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M17_155_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M17_150_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M17_170_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M17_155_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M17_200_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M17_170_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M17_210_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M17_200_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M17_220_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M17_210_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M17_225_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M17_220_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M17_240_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M17_225_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M18_020_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M17_240_MARIRURI_FREE_START
end
function MARIRURIMovTbl.M18_030_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M18_020_MARIRURI_FREE_START
end
function MARIRURIMovTbl.S01_010_MARIRURI_FREE_START()
  return MARIRURIMovTbl.M18_030_MARIRURI_FREE_START
end
function MARIRURIMovTbl.S01_020_MARIRURI_FREE_START()
  return MARIRURIMovTbl.S01_010_MARIRURI_FREE_START
end
function MARIRURIMovTbl.S01_030_MARIRURI_FREE_START()
  return MARIRURIMovTbl.S01_020_MARIRURI_FREE_START
end
function MARIRURIMovTbl.S01_040_MARIRURI_FREE_START()
  return MARIRURIMovTbl.S01_030_MARIRURI_FREE_START
end
function MARIRURIMovTbl.S01_050_MARIRURI_FREE_START()
  return MARIRURIMovTbl.S01_040_MARIRURI_FREE_START
end
function MARIRURIMovTbl.S01_060_MARIRURI_FREE_START()
  return MARIRURIMovTbl.S01_050_MARIRURI_FREE_START
end
function MARIRURIMovTbl.S01_080_MARIRURI_FREE_START()
  return MARIRURIMovTbl.S01_060_MARIRURI_FREE_START
end
function MARIRURIMovTbl.ALL_CLEAR_MARIRURI_FREE_START()
  return MARIRURIMovTbl.S01_080_MARIRURI_FREE_START
end

