function MEGUROKOMovTbl.M02_010_MEGUROKO_FREE_START()
end
function MEGUROKOMovTbl.M02_030_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M02_010_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M02_050_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M02_030_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M02_070_MEGUROKO_FREE_START()
  FREE_MOVE_SYSTEM:CreateFmcCtrl_TaikisWithPush({
    CH("MEGUROKO")
  })
end
function MEGUROKOMovTbl.M02_080_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M02_070_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M02_090_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M02_080_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M02_100_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M02_090_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M02_115_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M02_100_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M02_130_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M02_115_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M02_160_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M02_130_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M03_010_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M02_160_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M03_020_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M03_010_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M03_045_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M03_020_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M03_090_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M03_045_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M03_110_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M03_090_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M03_130_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M03_110_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M03_150_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M03_130_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M04_010_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M03_150_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M04_020_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M04_010_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M04_HANYOU_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M04_020_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M04_040_MEGUROKO_FREE_START()
  subUseFreeMoveAct02(CH("MEGUROKO"), "$FREE_MOVE_RANGE_03")
end
function MEGUROKOMovTbl.M04_060_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M04_040_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M04_070_MEGUROKO_FREE_START()
  FREE_MOVE_SYSTEM:CreateFmcCtrl_TaikisWithPush({
    CH("MEGUROKO")
  })
end
function MEGUROKOMovTbl.M04_HANYOU_MEGUROKO_FREE_START2()
  return MEGUROKOMovTbl.M04_070_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M05_000_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M04_HANYOU_MEGUROKO_FREE_START2
end
function MEGUROKOMovTbl.M05_010_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M05_000_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M05_020_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M05_010_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M05_030_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M05_020_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M06_HANYOU_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M05_030_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M06_010_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M06_HANYOU_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M06_015_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M06_010_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M06_020_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M06_015_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M06_030_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M06_020_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M06_040_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M06_030_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M06_060_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M06_040_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M07_000_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M06_060_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M07_010_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M07_000_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M07_020_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M07_010_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M07_045_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M07_020_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M07_HANYOU_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M07_045_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M07_080_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M07_HANYOU_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M08_010_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M07_080_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M08_HANYOU_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M08_010_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M08_020_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M08_HANYOU_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M08_040_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M08_020_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M08_050_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M08_040_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M08_055_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M08_050_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M08_070_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M08_055_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M09_HANYOU_MEGUROKO_FREE_START1()
  return MEGUROKOMovTbl.M08_070_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M09_010_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M09_HANYOU_MEGUROKO_FREE_START1
end
function MEGUROKOMovTbl.M09_020_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M09_010_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M09_040_MEGUROKO_FREE_START()
  subUseFreeMoveAct01(CH("MEGUROKO"), "$FREE_MOVE_RANGE_03")
end
function MEGUROKOMovTbl.M09_HANYOU_MEGUROKO_FREE_START2()
  return MEGUROKOMovTbl.M09_040_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M09_060_MEGUROKO_FREE_START()
end
function MEGUROKOMovTbl.M09_080_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M09_060_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M09_100_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M09_080_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M09_110_MEGUROKO_FREE_START()
  FREE_MOVE_SYSTEM:CreateFmcCtrl_TaikisWithPush({
    CH("MEGUROKO")
  })
end
function MEGUROKOMovTbl.M09_120_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M09_110_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M10_010_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M09_120_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M10_030_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M10_010_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M10_040_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M10_030_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M10_060_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M10_040_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M11_010_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M10_060_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M11_030_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M11_010_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M11_040_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M11_030_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M11_050_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M11_040_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M11_060_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M11_050_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M11_075_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M11_060_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M11_090_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M11_075_MEGUROKO_FREE_START
end

