function MEGUROKOMovTbl.M12_010_MEGUROKO_FREE_START()
end
function MEGUROKOMovTbl.M12_020_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M12_010_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M12_030_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M12_020_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M12_040_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M12_030_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M12_050_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M12_040_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M12_070_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M12_050_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M13_010_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M12_070_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M13_030_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M13_010_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M13_040_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M13_030_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M13_060_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M13_040_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M13_070_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M13_060_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M13_080_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M13_070_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M13_090_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M13_080_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M13_095_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M13_090_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M13_110_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M13_095_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M14_010_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M13_110_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M14_030_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M14_010_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M14_040_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M14_030_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M14_060_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M14_040_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M14_070_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M14_060_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M14_090_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M14_070_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M15_010_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M14_090_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M15_020_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M15_010_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M15_030_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M15_020_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M16_010_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M15_030_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M16_040_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M16_010_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M16_080_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M16_040_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M16_090_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M16_080_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M16_100_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M16_090_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M16_105_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M16_100_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M16_120_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M16_105_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M17_020_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M16_120_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M17_040_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M17_020_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M17_060_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M17_040_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M17_065_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M17_060_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M17_090_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M17_065_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M17_120_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M17_090_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M17_140_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M17_120_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M17_150_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M17_140_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M17_155_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M17_150_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M17_170_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M17_155_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M17_200_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M17_170_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M17_210_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M17_200_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M17_220_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M17_210_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M17_225_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M17_220_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M17_240_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M17_225_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M18_020_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M17_240_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.M18_030_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.M18_020_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.S01_010_MEGUROKO_FREE_START()
  subUseFreeMoveAct01(CH("MEGUROKO"), "$FREE_MOVE_RANGE_01")
end
function MEGUROKOMovTbl.S01_020_MEGUROKO_FREE_START()
end
function MEGUROKOMovTbl.S01_030_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.S01_020_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.S01_040_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.S01_030_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.S01_050_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.S01_040_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.S01_060_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.S01_050_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.S01_080_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.S01_060_MEGUROKO_FREE_START
end
function MEGUROKOMovTbl.ALL_CLEAR_MEGUROKO_FREE_START()
  return MEGUROKOMovTbl.S01_080_MEGUROKO_FREE_START
end

