function MEROETTAMovTbl.M12_010_MEROETTA_FREE_START()
end
function MEROETTAMovTbl.M12_020_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M12_010_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M12_030_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M12_020_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M12_040_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M12_030_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M12_050_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M12_040_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M12_070_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M12_050_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M13_010_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M12_070_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M13_030_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M13_010_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M13_040_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M13_030_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M13_060_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M13_040_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M13_070_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M13_060_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M13_080_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M13_070_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M13_090_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M13_080_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M13_095_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M13_090_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M13_110_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M13_095_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M14_010_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M13_110_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M14_030_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M14_010_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M14_040_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M14_030_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M14_060_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M14_040_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M14_070_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M14_060_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M14_090_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M14_070_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M15_010_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M14_090_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M15_020_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M15_010_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M15_030_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M15_020_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M16_010_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M15_030_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M16_040_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M16_010_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M16_080_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M16_040_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M16_090_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M16_080_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M16_100_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M16_090_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M16_105_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M16_100_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M16_120_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M16_105_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M17_020_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M16_120_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M17_040_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M17_020_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M17_060_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M17_040_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M17_065_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M17_060_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M17_090_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M17_065_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M17_120_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M17_090_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M17_140_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M17_120_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M17_150_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M17_140_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M17_155_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M17_150_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M17_170_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M17_155_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M17_200_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M17_170_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M17_210_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M17_200_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M17_220_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M17_210_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M17_225_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M17_220_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M17_240_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M17_225_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M18_020_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M17_240_MEROETTA_FREE_START
end
function MEROETTAMovTbl.M18_030_MEROETTA_FREE_START()
  return MEROETTAMovTbl.M18_020_MEROETTA_FREE_START
end
function MEROETTAMovTbl.S01_010_MEROETTA_FREE_START()
  if FLAG.MeroettaCounter == CONST.CNT_7 then
    CH("MEROETTA_STEP"):SetVisible(false)
    CH("MEROETTA_VOICE"):SetVisible(false)
  else
    FREE_MOVE_SYSTEM:CreateFmcCtrl_TaikisWithPush({
      CH("MEROETTA_VOICE")
    })
    FREE_MOVE_SYSTEM:CreateFmcCtrl_TaikisWithPush({
      CH("MEROETTA_STEP")
    })
  end
end
function MEROETTAMovTbl.S01_020_MEROETTA_FREE_START()
  return MEROETTAMovTbl.S01_010_MEROETTA_FREE_START
end
function MEROETTAMovTbl.S01_030_MEROETTA_FREE_START()
  return MEROETTAMovTbl.S01_020_MEROETTA_FREE_START
end
function MEROETTAMovTbl.S01_040_MEROETTA_FREE_START()
  return MEROETTAMovTbl.S01_030_MEROETTA_FREE_START
end
function MEROETTAMovTbl.S01_050_MEROETTA_FREE_START()
  return MEROETTAMovTbl.S01_040_MEROETTA_FREE_START
end
function MEROETTAMovTbl.S01_060_MEROETTA_FREE_START()
  return MEROETTAMovTbl.S01_050_MEROETTA_FREE_START
end
function MEROETTAMovTbl.S01_080_MEROETTA_FREE_START()
  return MEROETTAMovTbl.S01_060_MEROETTA_FREE_START
end
function MEROETTAMovTbl.ALL_CLEAR_MEROETTA_FREE_START()
  return MEROETTAMovTbl.S01_080_MEROETTA_FREE_START
end

