function MOGURYUUMovTbl.M12_010_MOGURYUU_FREE_START()
end
function MOGURYUUMovTbl.M12_020_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M12_010_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M12_030_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M12_020_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M12_040_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M12_030_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M12_050_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M12_040_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M12_070_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M12_050_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M13_010_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M12_070_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M13_030_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M13_010_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M13_040_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M13_030_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M13_060_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M13_040_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M13_070_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M13_060_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M13_080_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M13_070_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M13_090_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M13_080_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M13_095_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M13_090_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M13_110_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M13_095_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M14_010_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M13_110_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M14_030_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M14_010_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M14_040_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M14_030_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M14_060_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M14_040_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M14_070_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M14_060_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M14_090_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M14_070_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M15_010_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M14_090_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M15_020_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M15_010_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M15_030_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M15_020_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M16_010_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M15_030_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M16_040_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M16_010_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M16_080_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M16_040_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M16_090_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M16_080_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M16_100_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M16_090_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M16_105_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M16_100_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M16_120_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M16_105_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M17_020_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M16_120_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M17_040_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M17_020_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M17_060_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M17_040_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M17_065_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M17_060_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M17_090_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M17_065_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M17_120_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M17_090_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M17_140_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M17_120_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M17_150_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M17_140_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M17_155_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M17_150_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M17_170_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M17_155_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M17_200_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M17_170_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M17_210_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M17_200_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M17_220_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M17_210_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M17_225_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M17_220_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M17_240_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M17_225_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M18_020_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M17_240_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.M18_030_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M18_020_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.S01_010_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.M18_030_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.S01_020_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.S01_010_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.S01_030_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.S01_020_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.S01_040_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.S01_030_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.S01_050_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.S01_040_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.S01_060_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.S01_050_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.S01_080_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.S01_060_MOGURYUU_FREE_START
end
function MOGURYUUMovTbl.ALL_CLEAR_MOGURYUU_FREE_START()
  return MOGURYUUMovTbl.S01_080_MOGURYUU_FREE_START
end

