function NOKOTCHIMovTbl.M12_010_NOKOTCHI_FREE_START()
end
function NOKOTCHIMovTbl.M12_020_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M12_010_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M12_030_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M12_020_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M12_040_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M12_030_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M12_050_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M12_040_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M12_070_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M12_050_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M13_010_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M12_070_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M13_030_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M13_010_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M13_040_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M13_030_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M13_060_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M13_040_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M13_070_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M13_060_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M13_080_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M13_070_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M13_090_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M13_080_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M13_095_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M13_090_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M13_110_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M13_095_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M14_010_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M13_110_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M14_030_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M14_010_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M14_040_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M14_030_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M14_060_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M14_040_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M14_070_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M14_060_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M14_090_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M14_070_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M15_010_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M14_090_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M15_020_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M15_010_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M15_030_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M15_020_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M16_010_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M15_030_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M16_040_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M16_010_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M16_080_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M16_040_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M16_090_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M16_080_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M16_100_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M16_090_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M16_105_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M16_100_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M16_120_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M16_105_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M17_020_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M16_120_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M17_040_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M17_020_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M17_060_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M17_040_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M17_065_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M17_060_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M17_090_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M17_065_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M17_120_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M17_090_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M17_140_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M17_120_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M17_150_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M17_140_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M17_155_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M17_150_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M17_170_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M17_155_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M17_200_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M17_170_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M17_210_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M17_200_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M17_220_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M17_210_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M17_225_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M17_220_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M17_240_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M17_225_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M18_020_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M17_240_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M18_030_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M18_020_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.S01_010_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M18_030_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.S01_020_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.S01_010_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.S01_030_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.S01_020_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.S01_040_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.S01_030_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.S01_050_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.S01_040_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.S01_060_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.S01_050_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.S01_080_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.S01_060_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.ALL_CLEAR_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.S01_080_NOKOTCHI_FREE_START
end

