function NOKOTCHIMovTbl.M02_010_NOKOTCHI_FREE_START()
end
function NOKOTCHIMovTbl.M02_030_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M02_010_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M02_050_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M02_030_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M02_070_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M02_050_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M02_080_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M02_070_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M02_090_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M02_080_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M02_100_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M02_090_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M02_115_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M02_100_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M02_130_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M02_115_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M02_160_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M02_130_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M03_010_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M02_160_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M03_020_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M03_010_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M03_045_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M03_020_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M03_090_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M03_045_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M03_110_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M03_090_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M03_130_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M03_110_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M03_150_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M03_130_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M04_010_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M03_150_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M04_020_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M04_010_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M04_HANYOU_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M04_020_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M04_040_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M04_HANYOU_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M04_060_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M04_040_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M04_070_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M04_060_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M04_HANYOU_NOKOTCHI_FREE_START2()
  return NOKOTCHIMovTbl.M04_070_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M05_000_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M04_HANYOU_NOKOTCHI_FREE_START2
end
function NOKOTCHIMovTbl.M05_010_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M05_000_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M05_020_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M05_010_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M05_030_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M05_020_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M06_HANYOU_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M05_030_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M06_010_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M06_HANYOU_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M06_015_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M06_010_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M06_020_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M06_015_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M06_030_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M06_020_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M06_040_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M06_030_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M06_060_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M06_040_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M07_000_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M06_060_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M07_010_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M07_000_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M07_020_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M07_010_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M07_045_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M07_020_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M07_HANYOU_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M07_045_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M07_080_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M07_HANYOU_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M08_010_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M07_080_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M08_HANYOU_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M08_010_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M08_020_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M08_HANYOU_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M08_040_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M08_020_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M08_050_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M08_040_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M08_055_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M08_050_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M08_070_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M08_055_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M09_HANYOU_NOKOTCHI_FREE_START1()
  return NOKOTCHIMovTbl.M08_070_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M09_010_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M09_HANYOU_NOKOTCHI_FREE_START1
end
function NOKOTCHIMovTbl.M09_020_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M09_010_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M09_040_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M09_020_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M09_HANYOU_NOKOTCHI_FREE_START2()
  return NOKOTCHIMovTbl.M09_040_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M09_060_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M09_HANYOU_NOKOTCHI_FREE_START2
end
function NOKOTCHIMovTbl.M09_080_NOKOTCHI_FREE_START()
  FREE_MOVE_SYSTEM:CreateFmcCtrl_TaikisWithPush({
    CH("NOKOTCHI")
  })
end
function NOKOTCHIMovTbl.M09_100_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M09_080_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M09_110_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M09_100_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M09_120_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M09_110_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M10_010_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M09_120_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M10_030_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M10_010_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M10_040_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M10_030_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M10_060_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M10_040_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M11_010_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M10_060_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M11_030_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M11_010_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M11_040_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M11_030_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M11_050_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M11_040_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M11_060_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M11_050_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M11_075_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M11_060_NOKOTCHI_FREE_START
end
function NOKOTCHIMovTbl.M11_090_NOKOTCHI_FREE_START()
  return NOKOTCHIMovTbl.M11_075_NOKOTCHI_FREE_START
end

