function NUOOMovTbl.M02_010_NUOO_FREE_START()
  FREE_MOVE_SYSTEM:CreateFmcCtrl_ForShopStaff(CH("NUOO"))
end
function NUOOMovTbl.M02_030_NUOO_FREE_START()
  return NUOOMovTbl.M02_010_NUOO_FREE_START
end
function NUOOMovTbl.M02_050_NUOO_FREE_START()
  return NUOOMovTbl.M02_030_NUOO_FREE_START
end
function NUOOMovTbl.M02_070_NUOO_FREE_START()
  return NUOOMovTbl.M02_050_NUOO_FREE_START
end
function NUOOMovTbl.M02_080_NUOO_FREE_START()
  return NUOOMovTbl.M02_070_NUOO_FREE_START
end
function NUOOMovTbl.M02_090_NUOO_FREE_START()
  return NUOOMovTbl.M02_080_NUOO_FREE_START
end
function NUOOMovTbl.M02_100_NUOO_FREE_START()
  return NUOOMovTbl.M02_090_NUOO_FREE_START
end
function NUOOMovTbl.M02_115_NUOO_FREE_START()
  return NUOOMovTbl.M02_100_NUOO_FREE_START
end
function NUOOMovTbl.M02_130_NUOO_FREE_START()
  return NUOOMovTbl.M02_115_NUOO_FREE_START
end
function NUOOMovTbl.M02_160_NUOO_FREE_START()
  return NUOOMovTbl.M02_130_NUOO_FREE_START
end
function NUOOMovTbl.M03_010_NUOO_FREE_START()
  return NUOOMovTbl.M02_160_NUOO_FREE_START
end
function NUOOMovTbl.M03_020_NUOO_FREE_START()
  return NUOOMovTbl.M03_010_NUOO_FREE_START
end
function NUOOMovTbl.M03_045_NUOO_FREE_START()
  return NUOOMovTbl.M03_020_NUOO_FREE_START
end
function NUOOMovTbl.M03_090_NUOO_FREE_START()
  return NUOOMovTbl.M03_045_NUOO_FREE_START
end
function NUOOMovTbl.M03_110_NUOO_FREE_START()
  return NUOOMovTbl.M03_090_NUOO_FREE_START
end
function NUOOMovTbl.M03_130_NUOO_FREE_START()
  return NUOOMovTbl.M03_110_NUOO_FREE_START
end
function NUOOMovTbl.M03_150_NUOO_FREE_START()
  return NUOOMovTbl.M03_130_NUOO_FREE_START
end
function NUOOMovTbl.M04_010_NUOO_FREE_START()
  return NUOOMovTbl.M03_150_NUOO_FREE_START
end
function NUOOMovTbl.M04_020_NUOO_FREE_START()
  return NUOOMovTbl.M04_010_NUOO_FREE_START
end
function NUOOMovTbl.M04_HANYOU_NUOO_FREE_START()
  return NUOOMovTbl.M04_020_NUOO_FREE_START
end
function NUOOMovTbl.M04_040_NUOO_FREE_START()
  return NUOOMovTbl.M04_HANYOU_NUOO_FREE_START
end
function NUOOMovTbl.M04_060_NUOO_FREE_START()
  return NUOOMovTbl.M04_040_NUOO_FREE_START
end
function NUOOMovTbl.M04_070_NUOO_FREE_START()
  return NUOOMovTbl.M04_060_NUOO_FREE_START
end
function NUOOMovTbl.M04_HANYOU_NUOO_FREE_START2()
  return NUOOMovTbl.M04_070_NUOO_FREE_START
end
function NUOOMovTbl.M05_000_NUOO_FREE_START()
  return NUOOMovTbl.M04_HANYOU_NUOO_FREE_START2
end
function NUOOMovTbl.M05_010_NUOO_FREE_START()
  return NUOOMovTbl.M05_000_NUOO_FREE_START
end
function NUOOMovTbl.M05_020_NUOO_FREE_START()
  return NUOOMovTbl.M05_010_NUOO_FREE_START
end
function NUOOMovTbl.M05_030_NUOO_FREE_START()
  return NUOOMovTbl.M05_020_NUOO_FREE_START
end
function NUOOMovTbl.M06_HANYOU_NUOO_FREE_START()
  return NUOOMovTbl.M05_030_NUOO_FREE_START
end
function NUOOMovTbl.M06_010_NUOO_FREE_START()
  return NUOOMovTbl.M06_HANYOU_NUOO_FREE_START
end
function NUOOMovTbl.M06_015_NUOO_FREE_START()
  return NUOOMovTbl.M06_010_NUOO_FREE_START
end
function NUOOMovTbl.M06_020_NUOO_FREE_START()
  return NUOOMovTbl.M06_015_NUOO_FREE_START
end
function NUOOMovTbl.M06_030_NUOO_FREE_START()
  return NUOOMovTbl.M06_020_NUOO_FREE_START
end
function NUOOMovTbl.M06_040_NUOO_FREE_START()
  return NUOOMovTbl.M06_030_NUOO_FREE_START
end
function NUOOMovTbl.M06_060_NUOO_FREE_START()
  return NUOOMovTbl.M06_040_NUOO_FREE_START
end
function NUOOMovTbl.M07_000_NUOO_FREE_START()
  return NUOOMovTbl.M06_060_NUOO_FREE_START
end
function NUOOMovTbl.M07_010_NUOO_FREE_START()
  return NUOOMovTbl.M07_000_NUOO_FREE_START
end
function NUOOMovTbl.M07_020_NUOO_FREE_START()
  return NUOOMovTbl.M07_010_NUOO_FREE_START
end
function NUOOMovTbl.M07_045_NUOO_FREE_START()
  return NUOOMovTbl.M07_020_NUOO_FREE_START
end
function NUOOMovTbl.M07_HANYOU_NUOO_FREE_START()
  return NUOOMovTbl.M07_045_NUOO_FREE_START
end
function NUOOMovTbl.M07_080_NUOO_FREE_START()
  return NUOOMovTbl.M07_HANYOU_NUOO_FREE_START
end
function NUOOMovTbl.M08_010_NUOO_FREE_START()
  return NUOOMovTbl.M07_080_NUOO_FREE_START
end
function NUOOMovTbl.M08_HANYOU_NUOO_FREE_START()
  return NUOOMovTbl.M08_010_NUOO_FREE_START
end
function NUOOMovTbl.M08_020_NUOO_FREE_START()
  return NUOOMovTbl.M08_HANYOU_NUOO_FREE_START
end
function NUOOMovTbl.M08_040_NUOO_FREE_START()
  return NUOOMovTbl.M08_020_NUOO_FREE_START
end
function NUOOMovTbl.M08_050_NUOO_FREE_START()
  return NUOOMovTbl.M08_040_NUOO_FREE_START
end
function NUOOMovTbl.M08_055_NUOO_FREE_START()
  return NUOOMovTbl.M08_050_NUOO_FREE_START
end
function NUOOMovTbl.M08_070_NUOO_FREE_START()
  return NUOOMovTbl.M08_055_NUOO_FREE_START
end
function NUOOMovTbl.M09_HANYOU_NUOO_FREE_START1()
  return NUOOMovTbl.M08_070_NUOO_FREE_START
end
function NUOOMovTbl.M09_010_NUOO_FREE_START()
  return NUOOMovTbl.M09_HANYOU_NUOO_FREE_START1
end
function NUOOMovTbl.M09_020_NUOO_FREE_START()
  return NUOOMovTbl.M09_010_NUOO_FREE_START
end
function NUOOMovTbl.M09_040_NUOO_FREE_START()
  return NUOOMovTbl.M09_020_NUOO_FREE_START
end
function NUOOMovTbl.M09_HANYOU_NUOO_FREE_START2()
  return NUOOMovTbl.M09_040_NUOO_FREE_START
end
function NUOOMovTbl.M09_060_NUOO_FREE_START()
  return NUOOMovTbl.M09_HANYOU_NUOO_FREE_START2
end
function NUOOMovTbl.M09_080_NUOO_FREE_START()
  return NUOOMovTbl.M09_060_NUOO_FREE_START
end
function NUOOMovTbl.M09_100_NUOO_FREE_START()
  return NUOOMovTbl.M09_080_NUOO_FREE_START
end
function NUOOMovTbl.M09_110_NUOO_FREE_START()
  return NUOOMovTbl.M09_100_NUOO_FREE_START
end
function NUOOMovTbl.M09_120_NUOO_FREE_START()
  return NUOOMovTbl.M09_110_NUOO_FREE_START
end
function NUOOMovTbl.M10_010_NUOO_FREE_START()
  return NUOOMovTbl.M09_120_NUOO_FREE_START
end
function NUOOMovTbl.M10_030_NUOO_FREE_START()
  return NUOOMovTbl.M10_010_NUOO_FREE_START
end
function NUOOMovTbl.M10_040_NUOO_FREE_START()
  return NUOOMovTbl.M10_030_NUOO_FREE_START
end
function NUOOMovTbl.M10_060_NUOO_FREE_START()
  return NUOOMovTbl.M10_040_NUOO_FREE_START
end
function NUOOMovTbl.M11_010_NUOO_FREE_START()
  return NUOOMovTbl.M10_060_NUOO_FREE_START
end
function NUOOMovTbl.M11_030_NUOO_FREE_START()
  return NUOOMovTbl.M11_010_NUOO_FREE_START
end
function NUOOMovTbl.M11_040_NUOO_FREE_START()
  return NUOOMovTbl.M11_030_NUOO_FREE_START
end
function NUOOMovTbl.M11_050_NUOO_FREE_START()
  return NUOOMovTbl.M11_040_NUOO_FREE_START
end
function NUOOMovTbl.M11_060_NUOO_FREE_START()
  return NUOOMovTbl.M11_050_NUOO_FREE_START
end
function NUOOMovTbl.M11_075_NUOO_FREE_START()
  return NUOOMovTbl.M11_060_NUOO_FREE_START
end
function NUOOMovTbl.M11_090_NUOO_FREE_START()
  return NUOOMovTbl.M11_075_NUOO_FREE_START
end

