function PARTNERMovTbl.M12_010_PARTNER_FREE_START()
end
function PARTNERMovTbl.M12_020_PARTNER_FREE_START()
  return PARTNERMovTbl.M12_010_PARTNER_FREE_START
end
function PARTNERMovTbl.M12_030_PARTNER_FREE_START()
  return PARTNERMovTbl.M12_020_PARTNER_FREE_START
end
function PARTNERMovTbl.M12_040_PARTNER_FREE_START()
  return PARTNERMovTbl.M12_030_PARTNER_FREE_START
end
function PARTNERMovTbl.M12_050_PARTNER_FREE_START()
  return PARTNERMovTbl.M12_040_PARTNER_FREE_START
end
function PARTNERMovTbl.M12_070_PARTNER_FREE_START()
  return PARTNERMovTbl.M12_050_PARTNER_FREE_START
end
function PARTNERMovTbl.M13_010_PARTNER_FREE_START()
  return PARTNERMovTbl.M12_070_PARTNER_FREE_START
end
function PARTNERMovTbl.M13_030_PARTNER_FREE_START()
  return PARTNERMovTbl.M13_010_PARTNER_FREE_START
end
function PARTNERMovTbl.M13_040_PARTNER_FREE_START()
  return PARTNERMovTbl.M13_030_PARTNER_FREE_START
end
function PARTNERMovTbl.M13_060_PARTNER_FREE_START()
  return PARTNERMovTbl.M13_040_PARTNER_FREE_START
end
function PARTNERMovTbl.M13_070_PARTNER_FREE_START()
  return PARTNERMovTbl.M13_060_PARTNER_FREE_START
end
function PARTNERMovTbl.M13_080_PARTNER_FREE_START()
  return PARTNERMovTbl.M13_070_PARTNER_FREE_START
end
function PARTNERMovTbl.M13_090_PARTNER_FREE_START()
  return PARTNERMovTbl.M13_080_PARTNER_FREE_START
end
function PARTNERMovTbl.M13_095_PARTNER_FREE_START()
  return PARTNERMovTbl.M13_090_PARTNER_FREE_START
end
function PARTNERMovTbl.M13_110_PARTNER_FREE_START()
  return PARTNERMovTbl.M13_095_PARTNER_FREE_START
end
function PARTNERMovTbl.M14_010_PARTNER_FREE_START()
  return PARTNERMovTbl.M13_110_PARTNER_FREE_START
end
function PARTNERMovTbl.M14_030_PARTNER_FREE_START()
  return PARTNERMovTbl.M14_010_PARTNER_FREE_START
end
function PARTNERMovTbl.M14_040_PARTNER_FREE_START()
  return PARTNERMovTbl.M14_030_PARTNER_FREE_START
end
function PARTNERMovTbl.M14_060_PARTNER_FREE_START()
  return PARTNERMovTbl.M14_040_PARTNER_FREE_START
end
function PARTNERMovTbl.M14_070_PARTNER_FREE_START()
  return PARTNERMovTbl.M14_060_PARTNER_FREE_START
end
function PARTNERMovTbl.M14_090_PARTNER_FREE_START()
  return PARTNERMovTbl.M14_070_PARTNER_FREE_START
end
function PARTNERMovTbl.M15_010_PARTNER_FREE_START()
  return PARTNERMovTbl.M14_090_PARTNER_FREE_START
end
function PARTNERMovTbl.M15_020_PARTNER_FREE_START()
  return PARTNERMovTbl.M15_010_PARTNER_FREE_START
end
function PARTNERMovTbl.M15_030_PARTNER_FREE_START()
  return PARTNERMovTbl.M15_020_PARTNER_FREE_START
end
function PARTNERMovTbl.M16_010_PARTNER_FREE_START()
  return PARTNERMovTbl.M15_030_PARTNER_FREE_START
end
function PARTNERMovTbl.M16_040_PARTNER_FREE_START()
  subUseFreeActSpreeOnly(CH("PARTNER"))
end
function PARTNERMovTbl.M16_080_PARTNER_FREE_START()
end
function PARTNERMovTbl.M16_090_PARTNER_FREE_START()
  return PARTNERMovTbl.M16_080_PARTNER_FREE_START
end
function PARTNERMovTbl.M16_100_PARTNER_FREE_START()
  return PARTNERMovTbl.M16_090_PARTNER_FREE_START
end
function PARTNERMovTbl.M16_105_PARTNER_FREE_START()
  return PARTNERMovTbl.M16_100_PARTNER_FREE_START
end
function PARTNERMovTbl.M16_120_PARTNER_FREE_START()
  return PARTNERMovTbl.M16_105_PARTNER_FREE_START
end
function PARTNERMovTbl.M17_020_PARTNER_FREE_START()
  return PARTNERMovTbl.M16_120_PARTNER_FREE_START
end
function PARTNERMovTbl.M17_040_PARTNER_FREE_START()
  return PARTNERMovTbl.M17_020_PARTNER_FREE_START
end
function PARTNERMovTbl.M17_060_PARTNER_FREE_START()
  return PARTNERMovTbl.M17_040_PARTNER_FREE_START
end
function PARTNERMovTbl.M17_065_PARTNER_FREE_START()
  return PARTNERMovTbl.M17_060_PARTNER_FREE_START
end
function PARTNERMovTbl.M17_090_PARTNER_FREE_START()
  return PARTNERMovTbl.M17_065_PARTNER_FREE_START
end
function PARTNERMovTbl.M17_120_PARTNER_FREE_START()
  return PARTNERMovTbl.M17_090_PARTNER_FREE_START
end
function PARTNERMovTbl.M17_140_PARTNER_FREE_START()
  return PARTNERMovTbl.M17_120_PARTNER_FREE_START
end
function PARTNERMovTbl.M17_150_PARTNER_FREE_START()
  return PARTNERMovTbl.M17_140_PARTNER_FREE_START
end
function PARTNERMovTbl.M17_155_PARTNER_FREE_START()
  return PARTNERMovTbl.M17_150_PARTNER_FREE_START
end
function PARTNERMovTbl.M17_170_PARTNER_FREE_START()
  return PARTNERMovTbl.M17_155_PARTNER_FREE_START
end
function PARTNERMovTbl.M17_200_PARTNER_FREE_START()
  return PARTNERMovTbl.M17_170_PARTNER_FREE_START
end
function PARTNERMovTbl.M17_210_PARTNER_FREE_START()
  return PARTNERMovTbl.M17_200_PARTNER_FREE_START
end
function PARTNERMovTbl.M17_220_PARTNER_FREE_START()
  return PARTNERMovTbl.M17_210_PARTNER_FREE_START
end
function PARTNERMovTbl.M17_225_PARTNER_FREE_START()
  return PARTNERMovTbl.M17_220_PARTNER_FREE_START
end
function PARTNERMovTbl.M17_240_PARTNER_FREE_START()
  return PARTNERMovTbl.M17_225_PARTNER_FREE_START
end
function PARTNERMovTbl.M18_020_PARTNER_FREE_START()
  return PARTNERMovTbl.M17_240_PARTNER_FREE_START
end
function PARTNERMovTbl.M18_030_PARTNER_FREE_START()
  return PARTNERMovTbl.M18_020_PARTNER_FREE_START
end
function PARTNERMovTbl.S01_010_PARTNER_FREE_START()
  return PARTNERMovTbl.M18_030_PARTNER_FREE_START
end
function PARTNERMovTbl.S01_020_PARTNER_FREE_START()
  return PARTNERMovTbl.S01_010_PARTNER_FREE_START
end
function PARTNERMovTbl.S01_030_PARTNER_FREE_START()
  return PARTNERMovTbl.S01_020_PARTNER_FREE_START
end
function PARTNERMovTbl.S01_040_PARTNER_FREE_START()
  return PARTNERMovTbl.S01_030_PARTNER_FREE_START
end
function PARTNERMovTbl.S01_050_PARTNER_FREE_START()
  return PARTNERMovTbl.S01_040_PARTNER_FREE_START
end
function PARTNERMovTbl.S01_060_PARTNER_FREE_START()
  return PARTNERMovTbl.S01_050_PARTNER_FREE_START
end
function PARTNERMovTbl.S01_080_PARTNER_FREE_START()
  return PARTNERMovTbl.S01_060_PARTNER_FREE_START
end
function PARTNERMovTbl.ALL_CLEAR_PARTNER_FREE_START()
  return PARTNERMovTbl.S01_080_PARTNER_FREE_START
end

