function PARTNERMovTbl.M02_010_PARTNER_FREE_START()
end
function PARTNERMovTbl.M02_030_PARTNER_FREE_START()
  return PARTNERMovTbl.M02_010_PARTNER_FREE_START
end
function PARTNERMovTbl.M02_050_PARTNER_FREE_START()
  return PARTNERMovTbl.M02_030_PARTNER_FREE_START
end
function PARTNERMovTbl.M02_070_PARTNER_FREE_START()
  return PARTNERMovTbl.M02_050_PARTNER_FREE_START
end
function PARTNERMovTbl.M02_080_PARTNER_FREE_START()
  return PARTNERMovTbl.M02_070_PARTNER_FREE_START
end
function PARTNERMovTbl.M02_090_PARTNER_FREE_START()
  return PARTNERMovTbl.M02_080_PARTNER_FREE_START
end
function PARTNERMovTbl.M02_100_PARTNER_FREE_START()
  return PARTNERMovTbl.M02_090_PARTNER_FREE_START
end
function PARTNERMovTbl.M02_115_PARTNER_FREE_START()
  return PARTNERMovTbl.M02_100_PARTNER_FREE_START
end
function PARTNERMovTbl.M02_130_PARTNER_FREE_START()
  return PARTNERMovTbl.M02_115_PARTNER_FREE_START
end
function PARTNERMovTbl.M02_160_PARTNER_FREE_START()
  return PARTNERMovTbl.M02_130_PARTNER_FREE_START
end
function PARTNERMovTbl.M03_010_PARTNER_FREE_START()
  return PARTNERMovTbl.M02_160_PARTNER_FREE_START
end
function PARTNERMovTbl.M03_020_PARTNER_FREE_START()
  return PARTNERMovTbl.M03_010_PARTNER_FREE_START
end
function PARTNERMovTbl.M03_045_PARTNER_FREE_START()
  return PARTNERMovTbl.M03_020_PARTNER_FREE_START
end
function PARTNERMovTbl.M03_090_PARTNER_FREE_START()
  return PARTNERMovTbl.M03_045_PARTNER_FREE_START
end
function PARTNERMovTbl.M03_110_PARTNER_FREE_START()
  return PARTNERMovTbl.M03_090_PARTNER_FREE_START
end
function PARTNERMovTbl.M03_130_PARTNER_FREE_START()
  return PARTNERMovTbl.M03_110_PARTNER_FREE_START
end
function PARTNERMovTbl.M03_150_PARTNER_FREE_START()
  return PARTNERMovTbl.M03_130_PARTNER_FREE_START
end
function PARTNERMovTbl.M04_010_PARTNER_FREE_START()
  return PARTNERMovTbl.M03_150_PARTNER_FREE_START
end
function PARTNERMovTbl.M04_020_PARTNER_FREE_START()
  return PARTNERMovTbl.M04_010_PARTNER_FREE_START
end
function PARTNERMovTbl.M04_HANYOU_PARTNER_FREE_START()
  return PARTNERMovTbl.M04_020_PARTNER_FREE_START
end
function PARTNERMovTbl.M04_040_PARTNER_FREE_START()
  return PARTNERMovTbl.M04_HANYOU_PARTNER_FREE_START
end
function PARTNERMovTbl.M04_060_PARTNER_FREE_START()
  return PARTNERMovTbl.M04_040_PARTNER_FREE_START
end
function PARTNERMovTbl.M04_070_PARTNER_FREE_START()
  return PARTNERMovTbl.M04_060_PARTNER_FREE_START
end
function PARTNERMovTbl.M04_HANYOU_PARTNER_FREE_START2()
  return PARTNERMovTbl.M04_070_PARTNER_FREE_START
end
function PARTNERMovTbl.M05_000_PARTNER_FREE_START()
  return PARTNERMovTbl.M04_HANYOU_PARTNER_FREE_START2
end
function PARTNERMovTbl.M05_010_PARTNER_FREE_START()
  return PARTNERMovTbl.M05_000_PARTNER_FREE_START
end
function PARTNERMovTbl.M05_020_PARTNER_FREE_START()
  return PARTNERMovTbl.M05_010_PARTNER_FREE_START
end
function PARTNERMovTbl.M05_030_PARTNER_FREE_START()
  return PARTNERMovTbl.M05_020_PARTNER_FREE_START
end
function PARTNERMovTbl.M06_HANYOU_PARTNER_FREE_START()
  return PARTNERMovTbl.M05_030_PARTNER_FREE_START
end
function PARTNERMovTbl.M06_010_PARTNER_FREE_START()
  return PARTNERMovTbl.M06_HANYOU_PARTNER_FREE_START
end
function PARTNERMovTbl.M06_015_PARTNER_FREE_START()
  return PARTNERMovTbl.M06_010_PARTNER_FREE_START
end
function PARTNERMovTbl.M06_020_PARTNER_FREE_START()
  return PARTNERMovTbl.M06_015_PARTNER_FREE_START
end
function PARTNERMovTbl.M06_030_PARTNER_FREE_START()
  return PARTNERMovTbl.M06_020_PARTNER_FREE_START
end
function PARTNERMovTbl.M06_040_PARTNER_FREE_START()
  return PARTNERMovTbl.M06_030_PARTNER_FREE_START
end
function PARTNERMovTbl.M06_060_PARTNER_FREE_START()
  return PARTNERMovTbl.M06_040_PARTNER_FREE_START
end
function PARTNERMovTbl.M07_000_PARTNER_FREE_START()
  return PARTNERMovTbl.M06_060_PARTNER_FREE_START
end
function PARTNERMovTbl.M07_010_PARTNER_FREE_START()
  return PARTNERMovTbl.M07_000_PARTNER_FREE_START
end
function PARTNERMovTbl.M07_020_PARTNER_FREE_START()
  return PARTNERMovTbl.M07_010_PARTNER_FREE_START
end
function PARTNERMovTbl.M07_045_PARTNER_FREE_START()
  return PARTNERMovTbl.M07_020_PARTNER_FREE_START
end
function PARTNERMovTbl.M07_HANYOU_PARTNER_FREE_START()
  return PARTNERMovTbl.M07_045_PARTNER_FREE_START
end
function PARTNERMovTbl.M07_080_PARTNER_FREE_START()
  return PARTNERMovTbl.M07_HANYOU_PARTNER_FREE_START
end
function PARTNERMovTbl.M08_010_PARTNER_FREE_START()
  return PARTNERMovTbl.M07_080_PARTNER_FREE_START
end
function PARTNERMovTbl.M08_HANYOU_PARTNER_FREE_START()
  return PARTNERMovTbl.M08_010_PARTNER_FREE_START
end
function PARTNERMovTbl.M08_020_PARTNER_FREE_START()
  return PARTNERMovTbl.M08_HANYOU_PARTNER_FREE_START
end
function PARTNERMovTbl.M08_040_PARTNER_FREE_START()
  return PARTNERMovTbl.M08_020_PARTNER_FREE_START
end
function PARTNERMovTbl.M08_050_PARTNER_FREE_START()
  return PARTNERMovTbl.M08_040_PARTNER_FREE_START
end
function PARTNERMovTbl.M08_055_PARTNER_FREE_START()
  return PARTNERMovTbl.M08_050_PARTNER_FREE_START
end
function PARTNERMovTbl.M08_070_PARTNER_FREE_START()
  return PARTNERMovTbl.M08_055_PARTNER_FREE_START
end
function PARTNERMovTbl.M09_HANYOU_PARTNER_FREE_START1()
  return PARTNERMovTbl.M08_070_PARTNER_FREE_START
end
function PARTNERMovTbl.M09_010_PARTNER_FREE_START()
  return PARTNERMovTbl.M09_HANYOU_PARTNER_FREE_START1
end
function PARTNERMovTbl.M09_020_PARTNER_FREE_START()
  return PARTNERMovTbl.M09_010_PARTNER_FREE_START
end
function PARTNERMovTbl.M09_040_PARTNER_FREE_START()
  return PARTNERMovTbl.M09_020_PARTNER_FREE_START
end
function PARTNERMovTbl.M09_HANYOU_PARTNER_FREE_START2()
  return PARTNERMovTbl.M09_040_PARTNER_FREE_START
end
function PARTNERMovTbl.M09_060_PARTNER_FREE_START()
  return PARTNERMovTbl.M09_HANYOU_PARTNER_FREE_START2
end
function PARTNERMovTbl.M09_080_PARTNER_FREE_START()
  return PARTNERMovTbl.M09_060_PARTNER_FREE_START
end
function PARTNERMovTbl.M09_100_PARTNER_FREE_START()
  return PARTNERMovTbl.M09_080_PARTNER_FREE_START
end
function PARTNERMovTbl.M09_110_PARTNER_FREE_START()
  return PARTNERMovTbl.M09_100_PARTNER_FREE_START
end
function PARTNERMovTbl.M09_120_PARTNER_FREE_START()
  return PARTNERMovTbl.M09_110_PARTNER_FREE_START
end
function PARTNERMovTbl.M10_010_PARTNER_FREE_START()
  return PARTNERMovTbl.M09_120_PARTNER_FREE_START
end
function PARTNERMovTbl.M10_030_PARTNER_FREE_START()
  return PARTNERMovTbl.M10_010_PARTNER_FREE_START
end
function PARTNERMovTbl.M10_040_PARTNER_FREE_START()
  return PARTNERMovTbl.M10_030_PARTNER_FREE_START
end
function PARTNERMovTbl.M10_060_PARTNER_FREE_START()
  return PARTNERMovTbl.M10_040_PARTNER_FREE_START
end
function PARTNERMovTbl.M11_010_PARTNER_FREE_START()
  return PARTNERMovTbl.M10_060_PARTNER_FREE_START
end
function PARTNERMovTbl.M11_030_PARTNER_FREE_START()
  return PARTNERMovTbl.M11_010_PARTNER_FREE_START
end
function PARTNERMovTbl.M11_040_PARTNER_FREE_START()
  return PARTNERMovTbl.M11_030_PARTNER_FREE_START
end
function PARTNERMovTbl.M11_050_PARTNER_FREE_START()
  return PARTNERMovTbl.M11_040_PARTNER_FREE_START
end
function PARTNERMovTbl.M11_060_PARTNER_FREE_START()
  return PARTNERMovTbl.M11_050_PARTNER_FREE_START
end
function PARTNERMovTbl.M11_075_PARTNER_FREE_START()
  return PARTNERMovTbl.M11_060_PARTNER_FREE_START
end
function PARTNERMovTbl.M11_090_PARTNER_FREE_START()
  return PARTNERMovTbl.M11_075_PARTNER_FREE_START
end

