RAMUPARUDOMovTbl = {}
function FreeCharMoveRAMUPARUDO()
  FREE_MOVE_SYSTEM:CreateFmcCtrl_ForShopStaff(CH("RAMUPARUDO"))
end
function RAMUPARUDOMovTbl.CLEAR_DUNREST_RAMUPARUDO()
end
function RAMUPARUDOMovTbl.PARADISE_MODE_RAMUPARUDO()
  FREE_MOVE_SYSTEM:CreateFmcCtrl_ForShopStaff(CH("RAMUPARUDO"))
end
function RAMUPARUDOMovTbl.NO_MESSAGE_RAMUPARUDO()
end

