function SAZANDORAMovTbl.M12_010_SAZANDORA_FREE_START()
end
function SAZANDORAMovTbl.M12_020_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M12_010_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M12_030_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M12_020_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M12_040_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M12_030_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M12_050_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M12_040_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M12_070_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M12_050_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M13_010_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M12_070_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M13_030_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M13_010_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M13_040_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M13_030_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M13_060_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M13_040_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M13_070_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M13_060_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M13_080_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M13_070_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M13_090_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M13_080_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M13_095_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M13_090_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M13_110_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M13_095_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M14_010_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M13_110_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M14_030_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M14_010_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M14_040_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M14_030_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M14_060_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M14_040_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M14_070_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M14_060_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M14_090_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M14_070_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M15_010_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M14_090_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M15_020_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M15_010_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M15_030_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M15_020_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M16_010_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M15_030_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M16_040_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M16_010_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M16_080_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M16_040_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M16_090_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M16_080_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M16_100_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M16_090_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M16_105_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M16_100_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M16_120_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M16_105_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M17_020_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M16_120_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M17_040_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M17_020_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M17_060_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M17_040_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M17_065_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M17_060_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M17_090_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M17_065_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M17_120_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M17_090_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M17_140_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M17_120_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M17_150_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M17_140_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M17_155_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M17_150_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M17_170_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M17_155_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M17_200_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M17_170_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M17_210_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M17_200_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M17_220_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M17_210_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M17_225_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M17_220_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M17_240_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M17_225_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M18_020_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M17_240_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.M18_030_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M18_020_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.S01_010_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.M18_030_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.S01_020_SAZANDORA_FREE_START()
  local fmcCtrlObj = FREE_MOVE_SYSTEM:CreateFmcCtrl_Taikis({
    CH("SAZANDORA_LARGE")
  })
  FREE_MOVE_SYSTEM:CreateFmcCtrl_ForShopStaff(CH("SAZANDORA_LARGE"))
  function fmcCtrlObj:TaikiActLoop()
    CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.HAPPY)
    CH("SAZANDORA_LARGE"):SetMotionRaito(Raito(2))
    CH("SAZANDORA_LARGE"):SetMotion(SymMot("SPEAK"), LOOP.ON, TimeSec(0))
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    CH("SAZANDORA_LARGE"):SetManpu("MP_LAUGH_LP")
    CH("SAZANDORA_LARGE"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.NORMAL)
    CH("SAZANDORA_LARGE"):ResetManpu()
  end
  function fmcCtrlObj:TaikiActFinish()
    CH("SAZANDORA_LARGE"):ResetManpu()
    CH("SAZANDORA_LARGE"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    CH("SAZANDORA_LARGE"):SetMotionRaito(Raito(1))
  end
end
function SAZANDORAMovTbl.S01_030_SAZANDORA_FREE_START()
end
function SAZANDORAMovTbl.S01_040_SAZANDORA_FREE_START()
  return SAZANDORAMovTbl.S01_030_SAZANDORA_FREE_START
end
function SAZANDORAMovTbl.S01_050_SAZANDORA_FREE_START()
  local fmcCtrlObj = FREE_MOVE_SYSTEM:CreateFmcCtrl_Taikis({
    CH("SAZANDORA_LARGE")
  })
  FREE_MOVE_SYSTEM:CreateFmcCtrl_ForShopStaff(CH("SAZANDORA_LARGE"))
  function fmcCtrlObj:TaikiActLoop()
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    CH("SAZANDORA_LARGE"):SetManpu("MP_SPREE_LP")
    CH("SAZANDORA_LARGE"):SetMotion(SymMot("SPEAK"), LOOP.ON)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    CH("SAZANDORA_LARGE"):ResetManpu()
    CH("SAZANDORA_LARGE"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
  end
  function fmcCtrlObj:TaikiActFinish()
    CH("SAZANDORA_LARGE"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    CH("SAZANDORA_LARGE"):ResetManpu()
  end
end
function SAZANDORAMovTbl.S01_060_SAZANDORA_FREE_START()
end
function SAZANDORAMovTbl.S01_080_SAZANDORA_FREE_START()
  local fmcCtrlObj = FREE_MOVE_SYSTEM:CreateFmcCtrl_Taikis({
    CH("SAZANDORA_LARGE"),
    CH("KOJOFUU")
  })
  function fmcCtrlObj:TaikiActLoop()
    local char_a = self:GetTargetCharaObj(0)
    local char_b = self:GetTargetCharaObj(1)
    char_a:SetMotion(SymMot("SPEAK"), LOOP.ON)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    char_a:SetMotion(SymMot("WAIT02"), LOOP.ON)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    subEveNodDouble(char_b)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
  end
  function fmcCtrlObj:TaikiActFinish()
    char_a:SetMotion(SymMot("WAIT02"), LOOP.ON)
  end
end
function SAZANDORAMovTbl.ALL_CLEAR_SAZANDORA_FREE_START()
  local fmcCtrlObj = FREE_MOVE_SYSTEM:CreateFmcCtrl_Taikis({
    CH("SAZANDORA_LARGE")
  })
  FREE_MOVE_SYSTEM:CreateFmcCtrl_ForShopStaff(CH("SAZANDORA_LARGE"))
  function fmcCtrlObj:TaikiActLoop()
    CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.HAPPY)
    CH("SAZANDORA_LARGE"):SetMotionRaito(Raito(2))
    CH("SAZANDORA_LARGE"):SetMotion(SymMot("SPEAK"), LOOP.ON, TimeSec(0))
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    CH("SAZANDORA_LARGE"):SetManpu("MP_LAUGH_LP")
    CH("SAZANDORA_LARGE"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.NORMAL)
    CH("SAZANDORA_LARGE"):ResetManpu()
  end
  function fmcCtrlObj:TaikiActFinish()
    CH("SAZANDORA_LARGE"):ResetManpu()
    CH("SAZANDORA_LARGE"):SetMotion(SymMot("WAIT02"), LOOP.ON)
    CH("SAZANDORA_LARGE"):SetMotionRaito(Raito(1))
    CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  end
end

