function SUWANNAMovTbl.M12_010_SUWANNA_FREE_START()
  FREE_MOVE_SYSTEM:CreateFmcCtrl_ForShopStaff(CH("SUWANNA"))
end
function SUWANNAMovTbl.M12_020_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M12_010_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M12_030_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M12_020_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M12_040_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M12_030_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M12_050_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M12_040_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M12_070_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M12_050_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M13_010_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M12_070_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M13_030_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M13_010_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M13_040_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M13_030_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M13_060_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M13_040_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M13_070_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M13_060_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M13_080_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M13_070_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M13_090_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M13_080_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M13_095_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M13_090_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M13_110_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M13_095_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M14_010_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M13_110_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M14_030_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M14_010_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M14_040_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M14_030_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M14_060_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M14_040_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M14_070_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M14_060_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M14_090_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M14_070_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M15_010_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M14_090_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M15_020_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M15_010_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M15_030_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M15_020_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M16_010_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M15_030_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M16_040_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M16_010_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M16_080_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M16_040_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M16_090_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M16_080_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M16_100_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M16_090_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M16_105_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M16_100_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M16_120_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M16_105_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M17_020_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M16_120_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M17_040_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M17_020_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M17_060_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M17_040_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M17_065_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M17_060_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M17_090_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M17_065_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M17_120_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M17_090_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M17_140_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M17_120_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M17_150_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M17_140_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M17_155_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M17_150_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M17_170_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M17_155_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M17_200_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M17_170_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M17_210_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M17_200_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M17_220_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M17_210_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M17_225_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M17_220_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M17_240_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M17_225_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M18_020_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M17_240_SUWANNA_FREE_START
end
function SUWANNAMovTbl.M18_030_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M18_020_SUWANNA_FREE_START
end
function SUWANNAMovTbl.S01_010_SUWANNA_FREE_START()
  return SUWANNAMovTbl.M18_030_SUWANNA_FREE_START
end
function SUWANNAMovTbl.S01_020_SUWANNA_FREE_START()
  return SUWANNAMovTbl.S01_010_SUWANNA_FREE_START
end
function SUWANNAMovTbl.S01_030_SUWANNA_FREE_START()
  return SUWANNAMovTbl.S01_020_SUWANNA_FREE_START
end
function SUWANNAMovTbl.S01_040_SUWANNA_FREE_START()
  return SUWANNAMovTbl.S01_030_SUWANNA_FREE_START
end
function SUWANNAMovTbl.S01_050_SUWANNA_FREE_START()
  return SUWANNAMovTbl.S01_040_SUWANNA_FREE_START
end
function SUWANNAMovTbl.S01_060_SUWANNA_FREE_START()
  return SUWANNAMovTbl.S01_050_SUWANNA_FREE_START
end
function SUWANNAMovTbl.S01_080_SUWANNA_FREE_START()
  return SUWANNAMovTbl.S01_060_SUWANNA_FREE_START
end
function SUWANNAMovTbl.ALL_CLEAR_SUWANNA_FREE_START()
  return SUWANNAMovTbl.S01_080_SUWANNA_FREE_START
end

