TAMAGETAKEMovTbl = {}
function FreeCharMoveTAMAGETAKE()
  FreeCharManageTable("TAMAGETAKE", TAMAGETAKEMovTbl, true)
end
function TAMAGETAKEMovTbl.CLEAR_DUNREST_TAMAGETAKE()
end
function TAMAGETAKEMovTbl.PARADISE_MODE_TAMAGETAKE()
end
function TAMAGETAKEMovTbl.NO_MESSAGE_TAMAGETAKE()
end

