function WASHIBONMovTbl.M12_010_WASHIBON_FREE_START()
end
function WASHIBONMovTbl.M12_020_WASHIBON_FREE_START()
  local fmcCtrlObj = FREE_MOVE_SYSTEM:CreateFmcCtrl_Taikis({
    CH("WASHIBON")
  })
  CH("WASHIBON"):SetMotion(SymMot("SLEEPLOOP"), LOOP.ON, TimeSec(0))
  CH("WASHIBON"):SetManpu("MP_SLEEP_LP")
end
function WASHIBONMovTbl.M12_030_WASHIBON_FREE_START()
  return WASHIBONMovTbl.M12_020_WASHIBON_FREE_START
end
function WASHIBONMovTbl.M12_040_WASHIBON_FREE_START()
  FREE_MOVE_SYSTEM:CreateFmcCtrl_TaikisWithPush({
    CH("WASHIBON")
  })
end
function WASHIBONMovTbl.M12_050_WASHIBON_FREE_START()
end
function WASHIBONMovTbl.M12_070_WASHIBON_FREE_START()
  return WASHIBONMovTbl.M12_050_WASHIBON_FREE_START
end
function WASHIBONMovTbl.M13_010_WASHIBON_FREE_START()
  return WASHIBONMovTbl.M12_070_WASHIBON_FREE_START
end
function WASHIBONMovTbl.M13_030_WASHIBON_FREE_START()
  return WASHIBONMovTbl.M13_010_WASHIBON_FREE_START
end
function WASHIBONMovTbl.M13_040_WASHIBON_FREE_START()
  return WASHIBONMovTbl.M13_030_WASHIBON_FREE_START
end
function WASHIBONMovTbl.M13_060_WASHIBON_FREE_START()
  return WASHIBONMovTbl.M13_040_WASHIBON_FREE_START
end
function WASHIBONMovTbl.M13_070_WASHIBON_FREE_START()
  return WASHIBONMovTbl.M13_060_WASHIBON_FREE_START
end
function WASHIBONMovTbl.M13_080_WASHIBON_FREE_START()
  return WASHIBONMovTbl.M13_070_WASHIBON_FREE_START
end
function WASHIBONMovTbl.M13_090_WASHIBON_FREE_START()
  return WASHIBONMovTbl.M13_080_WASHIBON_FREE_START
end
function WASHIBONMovTbl.M13_095_WASHIBON_FREE_START()
  return WASHIBONMovTbl.M13_090_WASHIBON_FREE_START
end
function WASHIBONMovTbl.M13_110_WASHIBON_FREE_START()
  return WASHIBONMovTbl.M13_095_WASHIBON_FREE_START
end
function WASHIBONMovTbl.M14_010_WASHIBON_FREE_START()
  return WASHIBONMovTbl.M13_110_WASHIBON_FREE_START
end
function WASHIBONMovTbl.M14_030_WASHIBON_FREE_START()
  return WASHIBONMovTbl.M14_010_WASHIBON_FREE_START
end
function WASHIBONMovTbl.M14_040_WASHIBON_FREE_START()
  return WASHIBONMovTbl.M14_030_WASHIBON_FREE_START
end
function WASHIBONMovTbl.M14_060_WASHIBON_FREE_START()
  return WASHIBONMovTbl.M14_040_WASHIBON_FREE_START
end
function WASHIBONMovTbl.M14_070_WASHIBON_FREE_START()
  return WASHIBONMovTbl.M14_060_WASHIBON_FREE_START
end
function WASHIBONMovTbl.M14_090_WASHIBON_FREE_START()
  return WASHIBONMovTbl.M14_070_WASHIBON_FREE_START
end
function WASHIBONMovTbl.M15_010_WASHIBON_FREE_START()
  return WASHIBONMovTbl.M14_090_WASHIBON_FREE_START
end
function WASHIBONMovTbl.M15_020_WASHIBON_FREE_START()
  return WASHIBONMovTbl.M15_010_WASHIBON_FREE_START
end
function WASHIBONMovTbl.M15_030_WASHIBON_FREE_START()
  return WASHIBONMovTbl.M15_020_WASHIBON_FREE_START
end
function WASHIBONMovTbl.M16_010_WASHIBON_FREE_START()
  return WASHIBONMovTbl.M15_030_WASHIBON_FREE_START
end
function WASHIBONMovTbl.M16_040_WASHIBON_FREE_START()
  return WASHIBONMovTbl.M16_010_WASHIBON_FREE_START
end
function WASHIBONMovTbl.M16_080_WASHIBON_FREE_START()
  return WASHIBONMovTbl.M16_040_WASHIBON_FREE_START
end
function WASHIBONMovTbl.M16_090_WASHIBON_FREE_START()
  return WASHIBONMovTbl.M16_080_WASHIBON_FREE_START
end
function WASHIBONMovTbl.M16_100_WASHIBON_FREE_START()
  return WASHIBONMovTbl.M16_090_WASHIBON_FREE_START
end
function WASHIBONMovTbl.M16_105_WASHIBON_FREE_START()
  return WASHIBONMovTbl.M16_100_WASHIBON_FREE_START
end
function WASHIBONMovTbl.M16_120_WASHIBON_FREE_START()
  return WASHIBONMovTbl.M16_105_WASHIBON_FREE_START
end
function WASHIBONMovTbl.M17_020_WASHIBON_FREE_START()
  return WASHIBONMovTbl.M16_120_WASHIBON_FREE_START
end
function WASHIBONMovTbl.M17_040_WASHIBON_FREE_START()
  return WASHIBONMovTbl.M17_020_WASHIBON_FREE_START
end
function WASHIBONMovTbl.M17_060_WASHIBON_FREE_START()
  return WASHIBONMovTbl.M17_040_WASHIBON_FREE_START
end
function WASHIBONMovTbl.M17_065_WASHIBON_FREE_START()
  return WASHIBONMovTbl.M17_060_WASHIBON_FREE_START
end
function WASHIBONMovTbl.M17_090_WASHIBON_FREE_START()
  return WASHIBONMovTbl.M17_065_WASHIBON_FREE_START
end
function WASHIBONMovTbl.M17_120_WASHIBON_FREE_START()
  return WASHIBONMovTbl.M17_090_WASHIBON_FREE_START
end
function WASHIBONMovTbl.M17_140_WASHIBON_FREE_START()
  return WASHIBONMovTbl.M17_120_WASHIBON_FREE_START
end
function WASHIBONMovTbl.M17_150_WASHIBON_FREE_START()
  return WASHIBONMovTbl.M17_140_WASHIBON_FREE_START
end
function WASHIBONMovTbl.M17_155_WASHIBON_FREE_START()
  return WASHIBONMovTbl.M17_150_WASHIBON_FREE_START
end
function WASHIBONMovTbl.M17_170_WASHIBON_FREE_START()
  return WASHIBONMovTbl.M17_155_WASHIBON_FREE_START
end
function WASHIBONMovTbl.M17_200_WASHIBON_FREE_START()
  return WASHIBONMovTbl.M17_170_WASHIBON_FREE_START
end
function WASHIBONMovTbl.M17_210_WASHIBON_FREE_START()
  return WASHIBONMovTbl.M17_200_WASHIBON_FREE_START
end
function WASHIBONMovTbl.M17_220_WASHIBON_FREE_START()
  return WASHIBONMovTbl.M17_210_WASHIBON_FREE_START
end
function WASHIBONMovTbl.M17_225_WASHIBON_FREE_START()
  return WASHIBONMovTbl.M17_220_WASHIBON_FREE_START
end
function WASHIBONMovTbl.M17_240_WASHIBON_FREE_START()
  return WASHIBONMovTbl.M17_225_WASHIBON_FREE_START
end
function WASHIBONMovTbl.M18_020_WASHIBON_FREE_START()
  return WASHIBONMovTbl.M17_240_WASHIBON_FREE_START
end
function WASHIBONMovTbl.M18_030_WASHIBON_FREE_START()
  return WASHIBONMovTbl.M18_020_WASHIBON_FREE_START
end
function WASHIBONMovTbl.S01_010_WASHIBON_FREE_START()
  subUseFreeActRunRunOnly(CH("WASHIBON"))
end
function WASHIBONMovTbl.S01_020_WASHIBON_FREE_START()
  return WASHIBONMovTbl.S01_010_WASHIBON_FREE_START
end
function WASHIBONMovTbl.S01_030_WASHIBON_FREE_START()
  return WASHIBONMovTbl.S01_020_WASHIBON_FREE_START
end
function WASHIBONMovTbl.S01_040_WASHIBON_FREE_START()
  return WASHIBONMovTbl.S01_030_WASHIBON_FREE_START
end
function WASHIBONMovTbl.S01_050_WASHIBON_FREE_START()
  subUseFreeAct2men01(CH("WASHIBON"), CH("DANGORO"))
end
function WASHIBONMovTbl.S01_060_WASHIBON_FREE_START()
end
function WASHIBONMovTbl.S01_080_WASHIBON_FREE_START()
  return WASHIBONMovTbl.S01_060_WASHIBON_FREE_START
end
function WASHIBONMovTbl.ALL_CLEAR_WASHIBON_FREE_START()
  subUseFreeAct2men01(CH("WASHIBON"), CH("MEGUROKO"))
end

