function YOOTERIIMovTbl.M02_010_YOOTERII_FREE_START()
end
function YOOTERIIMovTbl.M02_030_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M02_010_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M02_050_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M02_030_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M02_070_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M02_050_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M02_080_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M02_070_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M02_090_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M02_080_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M02_100_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M02_090_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M02_115_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M02_100_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M02_130_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M02_115_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M02_160_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M02_130_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M03_010_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M02_160_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M03_020_YOOTERII_FREE_START()
  subUseFreeActTalkPair(CH("YOOTERII"), CH("KURUMAYU"))
end
function YOOTERIIMovTbl.M03_045_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M03_020_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M03_090_YOOTERII_FREE_START()
  subUseFreeActTalkPair(CH("YOOTERII"), CH("KURUMAYU"))
end
function YOOTERIIMovTbl.M03_110_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M03_090_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M03_130_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M03_110_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M03_150_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M03_130_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M04_010_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M03_150_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M04_020_YOOTERII_FREE_START()
end
function YOOTERIIMovTbl.M04_HANYOU_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M04_020_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M04_040_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M04_HANYOU_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M04_060_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M04_040_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M04_070_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M04_060_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M04_HANYOU_YOOTERII_FREE_START2()
  return YOOTERIIMovTbl.M04_070_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M05_000_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M04_HANYOU_YOOTERII_FREE_START2
end
function YOOTERIIMovTbl.M05_010_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M05_000_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M05_020_YOOTERII_FREE_START()
  subUseFreeActTalkNormalPair(CH("YOOTERII"), CH("HAADERIA"))
end
function YOOTERIIMovTbl.M05_030_YOOTERII_FREE_START()
  subUseFreeActTalkPair(CH("YOOTERII"), CH("KURUMAYU"))
end
function YOOTERIIMovTbl.M06_HANYOU_YOOTERII_FREE_START()
end
function YOOTERIIMovTbl.M06_010_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M06_HANYOU_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M06_015_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M06_010_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M06_020_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M06_015_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M06_030_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M06_020_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M06_040_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M06_030_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M06_060_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M06_040_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M07_000_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M06_060_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M07_010_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M07_000_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M07_020_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M07_010_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M07_045_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M07_020_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M07_HANYOU_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M07_045_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M07_080_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M07_HANYOU_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M08_010_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M07_080_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M08_HANYOU_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M08_010_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M08_020_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M08_HANYOU_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M08_040_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M08_020_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M08_050_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M08_040_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M08_055_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M08_050_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M08_070_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M08_055_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M09_HANYOU_YOOTERII_FREE_START1()
  return YOOTERIIMovTbl.M08_070_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M09_010_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M09_HANYOU_YOOTERII_FREE_START1
end
function YOOTERIIMovTbl.M09_020_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M09_010_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M09_040_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M09_020_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M09_HANYOU_YOOTERII_FREE_START2()
  return YOOTERIIMovTbl.M09_040_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M09_060_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M09_HANYOU_YOOTERII_FREE_START2
end
function YOOTERIIMovTbl.M09_080_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M09_060_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M09_100_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M09_080_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M09_110_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M09_100_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M09_120_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M09_110_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M10_010_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M09_120_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M10_030_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M10_010_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M10_040_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M10_030_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M10_060_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M10_040_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M11_010_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M10_060_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M11_030_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M11_010_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M11_040_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M11_030_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M11_050_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M11_040_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M11_060_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M11_050_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M11_075_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M11_060_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M11_090_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M11_075_YOOTERII_FREE_START
end

