function YOOTERIIMovTbl.M12_010_YOOTERII_FREE_START()
end
function YOOTERIIMovTbl.M12_020_YOOTERII_FREE_START()
  subUseFreeActTalkPair(CH("YOOTERII"), CH("KURUMAYU"))
end
function YOOTERIIMovTbl.M12_030_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M12_020_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M12_040_YOOTERII_FREE_START()
end
function YOOTERIIMovTbl.M12_050_YOOTERII_FREE_START()
  subUseFreeActTalkPair(CH("YOOTERII"), CH("KURUMAYU"))
end
function YOOTERIIMovTbl.M12_070_YOOTERII_FREE_START()
end
function YOOTERIIMovTbl.M13_010_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M12_070_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M13_030_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M13_010_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M13_040_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M13_030_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M13_060_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M13_040_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M13_070_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M13_060_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M13_080_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M13_070_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M13_090_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M13_080_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M13_095_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M13_090_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M13_110_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M13_095_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M14_010_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M13_110_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M14_030_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M14_010_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M14_040_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M14_030_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M14_060_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M14_040_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M14_070_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M14_060_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M14_090_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M14_070_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M15_010_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M14_090_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M15_020_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M15_010_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M15_030_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M15_020_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M16_010_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M15_030_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M16_040_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M16_010_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M16_080_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M16_040_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M16_090_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M16_080_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M16_100_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M16_090_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M16_105_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M16_100_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M16_120_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M16_105_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M17_020_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M16_120_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M17_040_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M17_020_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M17_060_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M17_040_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M17_065_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M17_060_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M17_090_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M17_065_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M17_120_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M17_090_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M17_140_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M17_120_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M17_150_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M17_140_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M17_155_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M17_150_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M17_170_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M17_155_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M17_200_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M17_170_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M17_210_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M17_200_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M17_220_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M17_210_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M17_225_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M17_220_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M17_240_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M17_225_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M18_020_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M17_240_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.M18_030_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M18_020_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.S01_010_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.M18_030_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.S01_020_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.S01_010_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.S01_030_YOOTERII_FREE_START()
  local fmcCtrlObj = FREE_MOVE_SYSTEM:CreateFmcCtrl_TaikisWithPush({
    CH("YOOTERII"),
    CH("KURUMAYU")
  })
  function fmcCtrlObj:TaikiActLoop()
    CH("KURUMAYU"):SetManpu("MP_SPREE_LP")
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    CH("KURUMAYU"):ResetManpu()
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    subEveDoubleJump(CH("YOOTERII"))
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
    TASK:Sleep(TimeSec(0.25), TASK_EXIT.QUICK)
  end
  function fmcCtrlObj:TaikiActFinish()
    CH("KURUMAYU"):ResetManpu()
  end
end
function YOOTERIIMovTbl.S01_040_YOOTERII_FREE_START()
end
function YOOTERIIMovTbl.S01_050_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.S01_040_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.S01_060_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.S01_050_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.S01_080_YOOTERII_FREE_START()
  return YOOTERIIMovTbl.S01_060_YOOTERII_FREE_START
end
function YOOTERIIMovTbl.ALL_CLEAR_YOOTERII_FREE_START()
  FREE_MOVE_SYSTEM:CreateFmcCtrl_TaikisWithPush({
    CH("YOOTERII")
  })
end

