function ZURUGGUMovTbl.M02_010_ZURUGGU_FREE_START()
  FREE_MOVE_SYSTEM:CreateFmcCtrl_ForShopStaff(CH("ZURUGGU"))
end
function ZURUGGUMovTbl.M02_030_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M02_010_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M02_050_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M02_030_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M02_070_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M02_050_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M02_080_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M02_070_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M02_090_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M02_080_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M02_100_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M02_090_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M02_115_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M02_100_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M02_130_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M02_115_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M02_160_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M02_130_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M03_010_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M02_160_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M03_020_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M03_010_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M03_045_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M03_020_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M03_090_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M03_045_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M03_110_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M03_090_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M03_130_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M03_110_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M03_150_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M03_130_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M04_010_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M03_150_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M04_020_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M04_010_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M04_HANYOU_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M04_020_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M04_040_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M04_HANYOU_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M04_060_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M04_040_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M04_070_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M04_060_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M04_HANYOU_ZURUGGU_FREE_START2()
  return ZURUGGUMovTbl.M04_070_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M05_000_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M04_HANYOU_ZURUGGU_FREE_START2
end
function ZURUGGUMovTbl.M05_010_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M05_000_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M05_020_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M05_010_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M05_030_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M05_020_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M06_HANYOU_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M05_030_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M06_010_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M06_HANYOU_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M06_015_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M06_010_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M06_020_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M06_015_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M06_030_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M06_020_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M06_040_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M06_030_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M06_060_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M06_040_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M07_000_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M06_060_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M07_010_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M07_000_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M07_020_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M07_010_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M07_045_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M07_020_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M07_HANYOU_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M07_045_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M07_080_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M07_HANYOU_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M08_010_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M07_080_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M08_HANYOU_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M08_010_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M08_020_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M08_HANYOU_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M08_040_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M08_020_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M08_050_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M08_040_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M08_055_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M08_050_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M08_070_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M08_055_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M09_HANYOU_ZURUGGU_FREE_START1()
  return ZURUGGUMovTbl.M08_070_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M09_010_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M09_HANYOU_ZURUGGU_FREE_START1
end
function ZURUGGUMovTbl.M09_020_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M09_010_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M09_040_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M09_020_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M09_HANYOU_ZURUGGU_FREE_START2()
  return ZURUGGUMovTbl.M09_040_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M09_060_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M09_HANYOU_ZURUGGU_FREE_START2
end
function ZURUGGUMovTbl.M09_080_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M09_060_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M09_100_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M09_080_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M09_110_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M09_100_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M09_120_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M09_110_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M10_010_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M09_120_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M10_030_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M10_010_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M10_040_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M10_030_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M10_060_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M10_040_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M11_010_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M10_060_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M11_030_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M11_010_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M11_040_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M11_030_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M11_050_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M11_040_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M11_060_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M11_050_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M11_075_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M11_060_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M11_090_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M11_075_ZURUGGU_FREE_START
end

