function ZURUGGUMovTbl.M12_010_ZURUGGU_FREE_START()
  FREE_MOVE_SYSTEM:CreateFmcCtrl_ForShopStaff(CH("ZURUGGU"))
end
function ZURUGGUMovTbl.M12_020_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M12_010_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M12_030_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M12_020_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M12_040_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M12_030_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M12_050_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M12_040_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M12_070_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M12_050_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M13_010_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M12_070_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M13_030_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M13_010_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M13_040_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M13_030_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M13_060_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M13_040_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M13_070_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M13_060_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M13_080_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M13_070_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M13_090_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M13_080_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M13_095_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M13_090_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M13_110_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M13_095_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M14_010_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M13_110_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M14_030_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M14_010_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M14_040_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M14_030_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M14_060_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M14_040_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M14_070_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M14_060_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M14_090_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M14_070_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M15_010_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M14_090_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M15_020_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M15_010_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M15_030_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M15_020_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M16_010_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M15_030_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M16_040_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M16_010_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M16_080_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M16_040_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M16_090_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M16_080_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M16_100_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M16_090_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M16_105_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M16_100_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M16_120_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M16_105_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M17_020_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M16_120_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M17_040_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M17_020_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M17_060_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M17_040_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M17_065_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M17_060_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M17_090_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M17_065_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M17_120_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M17_090_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M17_140_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M17_120_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M17_150_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M17_140_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M17_155_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M17_150_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M17_170_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M17_155_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M17_200_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M17_170_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M17_210_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M17_200_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M17_220_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M17_210_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M17_225_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M17_220_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M17_240_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M17_225_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M18_020_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M17_240_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.M18_030_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M18_020_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.S01_010_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.M18_030_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.S01_020_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.S01_010_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.S01_030_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.S01_020_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.S01_040_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.S01_030_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.S01_050_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.S01_040_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.S01_060_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.S01_050_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.S01_080_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.S01_060_ZURUGGU_FREE_START
end
function ZURUGGUMovTbl.ALL_CLEAR_ZURUGGU_FREE_START()
  return ZURUGGUMovTbl.S01_080_ZURUGGU_FREE_START
end

