dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main14_shinsou01_init()
end
function main14_shinsou01_start()
  TASK:Sleep(TimeSec(0.5))
  WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.PAIN)
  WINDOW:Monologue(-36611958)
  WINDOW:Monologue(-456496693)
  WINDOW:Monologue(-806929912)
  WINDOW:Monologue(-688125111)
  WINDOW:Monologue(-1715626610)
  WINDOW:Monologue(-2136560433)
  WINDOW:Monologue(-1416888564)
  WINDOW:Monologue(-1299132851)
  WINDOW:KeyWait()
  SCREEN_A:FadeOutAll(TimeSec(0.5), true)
  WINDOW:ForceCloseMessage()
  TASK:Sleep(TimeSec(1))
  SCREEN_A:FadeInAll(TimeSec(0), true)
  CAMERA:SetAzimuthDifferenceVolume(Volume(1.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HERO"):SetMotion(SymMot("EV001_DOWN01"), LOOP.ON, TimeSec(0))
  CH("HERO"):SetShadow(false)
  SOUND:PlayEnv(SymSnd("SE_EVT_DROP_WATER_LP"), Volume(128))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("HERO"):SetShake(Vector(0.005, 0, 0), TimeSec(0.5, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.5))
  CH("HERO"):ResetShake()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("SAZANDORA_LARGE"):SetManpu("MP_NOTICE_R")
  CH("SAZANDORA_LARGE"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), 889770626)
  WINDOW:CloseMessage()
  CH("HERO"):SetMotion(SymMot("EV001_DOWN02"), LOOP.OFF)
  TASK:Sleep(TimeSec(0.2))
  CH("SAZANDORA_LARGE"):WalkTo(PosOffs(-0.3, 0), Speed(1.5), LINK_DIR.OFF)
  CH("HERO"):SetShadow(true)
  CH("HERO"):WaitPlayMotion()
  subEveLookAroundNeck(CH("HERO"), TimeSec(0.1))
  CH("HERO"):ResetFacialMotion()
  CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("HERO"):SetPosition(SymPos("P00_HERO"))
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
  subEveLookAroundNeck(CH("HERO"), TimeSec(0.1))
  CH("HERO"):ResetFacialMotion()
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("HERO"):SetManpu("MP_SHOCK_L")
  CH("HERO"):WalkTo(SymPos("P01_HERO"), Speed(3), LINK_DIR.OFF)
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(739500995)
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3.5))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(-2097211457)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("SAZANDORA_LARGE"):SetManpu("MP_FLY_SWEAT")
  TASK:Regist(subEveDoubleJump, {
    CH("SAZANDORA_LARGE")
  })
  WINDOW:DrawFace(20, 20, SymAct("SAZANDORA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("SAZANDORA"), -1679546626)
  WINDOW:Talk(SymAct("SAZANDORA"), -1328974531)
  WINDOW:Talk(SymAct("SAZANDORA"), -1445837700)
  WINDOW:Talk(SymAct("SAZANDORA"), -426519877)
  WINDOW:KeyWait()
  TASK:Regist(subEveDoubleJump, {
    CH("SAZANDORA_LARGE")
  })
  WINDOW:Talk(SymAct("SAZANDORA"), -7805958)
  TASK:WaitTask()
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("SAZANDORA_LARGE"):SetManpu("MP_FLY_SWEAT")
  CH("SAZANDORA_LARGE"):WaitManpu()
  TASK:Regist(subEveDoubleJump, {
    CH("SAZANDORA_LARGE")
  })
  WINDOW:DrawFace(20, 20, SymAct("SAZANDORA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("SAZANDORA"), -727338951)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("HERO"):DirTo(RotateTarget(-45), Speed(200), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  TASK:Sleep(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("HERO"):SetMotion(SymMot("EV001_CONFIRMS"), LOOP.OFF)
  TASK:Sleep(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("HERO"):WaitPlayMotion()
  CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  TASK:Sleep(TimeSec(1))
  CH("HERO"):DirTo(CH("SAZANDORA_LARGE"), Speed(200), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  TASK:Sleep(TimeSec(1.5))
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CH("HERO"):DirTo(RotateTarget(-45), Speed(200), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  WINDOW:Monologue(-843153032)
  WINDOW:Monologue(1244044727)
  WINDOW:Monologue(1396550902)
  WINDOW:CloseMessage()
  SOUND:FadeOutEnv(TimeSec(0.5))
  CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  SOUND:PlayBgm(SymSnd("BGM_EVE_NAZO_03"), Volume(256))
  CH("HERO"):DirTo(CH("SAZANDORA_LARGE"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  TASK:Regist(subEveDoubleJump, {
    CH("SAZANDORA_LARGE")
  })
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("SAZANDORA"), -1874151343)
  WINDOW:KeyWait()
  CH("SAZANDORA_LARGE"):SetManpu("MP_LAUGH_AL_LP")
  WINDOW:Talk(SymAct("SAZANDORA"), -1991145200)
  WINDOW:KeyWait()
  CH("SAZANDORA_LARGE"):ResetManpu()
  WINDOW:Talk(SymAct("SAZANDORA"), -1568875821)
  WINDOW:CloseMessage()
  CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("HERO"):SetManpu("MP_QUESTION")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.THINK)
  WINDOW:Monologue(-1150817390)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), -198804139)
  WINDOW:Talk(SymAct("SAZANDORA"), -314749932)
  WINDOW:Talk(SymAct("SAZANDORA"), -972021801)
  WINDOW:Talk(SymAct("SAZANDORA"), -552915306)
  WINDOW:CloseMessage()
  CH("SAZANDORA_LARGE"):DirTo(RotateTarget(45), Speed(200), ROT_TYPE.NEAR)
  CH("SAZANDORA_LARGE"):WaitRotate()
  CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("SAZANDORA"), 1486041689)
  WINDOW:CloseMessage()
  CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  CH("SAZANDORA_LARGE"):DirTo(CH("HERO"), Speed(200), ROT_TYPE.NEAR)
  CH("SAZANDORA_LARGE"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), 1099432728)
  WINDOW:Talk(SymAct("SAZANDORA"), 687267636)
  WINDOW:Talk(SymAct("SAZANDORA"), 837676661)
  WINDOW:Talk(SymAct("SAZANDORA"), 448839094)
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("SAZANDORA"), 64720119)
  WINDOW:KeyWait()
  CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.GLADNESS)
  WINDOW:Talk(SymAct("SAZANDORA"), 1285167664)
  CH("SAZANDORA_LARGE"):SetManpu("MP_SPREE_AL_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("SAZANDORA_LARGE")
  })
  WINDOW:CloseMessage()
  TASK:Sleep(TimeSec(0.8))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SWEAT"), Volume(256))
  CH("HERO"):SetManpu("MP_SWEAT_L_AL")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.CATCHBREATH)
  WINDOW:Monologue(1434528625)
  WINDOW:Monologue(2125232306)
  WINDOW:Monologue(1740065267)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CH("HERO"):DirTo(RotateTarget(-45), Speed(200), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  WINDOW:Monologue(-533768900)
  WINDOW:Monologue(-114006915)
  WINDOW:CloseMessage()
  SCREEN_A:WhiteOut(TimeSec(0.3), true)
  TASK:Sleep(TimeSec(0.2))
  CH("SAZANDORA_LARGE"):ResetManpu()
  FLAG.SceneFlag = CONST.FL_SC_01_END
  FLAG.SCENARIOFLAG = CONST.M14_SHINSOU_START
  SYSTEM:NextEntry()
end
function main14_shinsou01_end()
end
function main14_shinsou02_init()
end
function main14_shinsou02_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_NAZO_03"), Volume(256))
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  EFFECT:CreateRecollectionFilter()
  CUT:Load(SymCut("CUT_M14_010_02"))
  CH("MUNNA"):SetShadow(false)
  CH("SAZANDORA_H"):SetShadow(false)
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
  CAMERA:SetDefaultGroundFovy()
  EFFECT:DestroyRecollectionFilter()
  FLAG.SceneFlag = CONST.FL_SC_02_END
  FLAG.SCENARIOFLAG = CONST.M14_SHINSOU_START
  SYSTEM:NextEntry()
end
function main14_shinsou02_end()
end
function main14_shinsou02_ADV_01()
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
end
function main14_shinsou02_ADV_02()
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
end
function main14_shinsou03_init()
end
function main14_shinsou03_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_NAZO_03"), Volume(256))
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("SAZANDORA_LARGE"):SetManpu("MP_SPREE_AL_LP")
  CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  SCREEN_A:WhiteIn(TimeSec(0.3), true)
  subEveFadeAfterTime()
  WINDOW:Monologue(-1256069235)
  WINDOW:CloseMessage()
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("HERO"):DirTo(CH("SAZANDORA_LARGE"), Speed(200), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.THINK)
  WINDOW:Monologue(-1405430068)
  WINDOW:Monologue(-2028501745)
  WINDOW:Monologue(-1643334578)
  WINDOW:Monologue(-783474039)
  WINDOW:Monologue(-933882936)
  WINDOW:Monologue(-478461941)
  WINDOW:Monologue(-94342838)
  WINDOW:Monologue(2113432965)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("SAZANDORA_LARGE"):ResetManpu()
  TASK:Sleep(TimeSec(0.3))
  TASK:Regist(subEveDoubleJump, {
    CH("SAZANDORA_LARGE")
  })
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("SAZANDORA"), 1692622020)
  WINDOW:KeyWait()
  TASK:Regist(subEveJump, {
    CH("SAZANDORA_LARGE")
  })
  WINDOW:Talk(SymAct("SAZANDORA"), 228425960)
  subEveCloseMsg()
  CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("HERO"):SetManpu("MP_NOTICE_L")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.NORMAL)
  WINDOW:Monologue(344371625)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), 1068229226)
  WINDOW:KeyWait()
  CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  TASK:Regist(subEveJump, {
    CH("SAZANDORA_LARGE")
  })
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.GLADNESS)
  WINDOW:Talk(SymAct("SAZANDORA"), 649122603)
  CH("SAZANDORA_LARGE"):SetManpu("MP_LAUGH_AL_LP")
  subEveCloseMsg()
  SOUND:FadeOutBgm(TimeSec(1.5))
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.THINK)
  WINDOW:Monologue(1777419756)
  WINDOW:CloseMessage()
  TASK:Sleep(TimeSec(1))
  CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):WaitManpu()
  TASK:Sleep(TimeSec(0.2))
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HERO"):DirTo(RotateTarget(-45), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  WINDOW:Monologue(1894413485)
  WINDOW:Monologue(1539778414)
  WINDOW:Monologue(1121719855)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  CH("SAZANDORA_LARGE"):ResetManpu()
  FLAG.SceneFlag = CONST.FL_SC_03_END
  FLAG.SCENARIOFLAG = CONST.M14_SHINSOU_START
  SYSTEM:NextEntry()
end
function main14_shinsou03_end()
end
function main14_shinsou04_init()
end
function main14_shinsou04_start()
  CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  EFFECT:StartMotionBlur(0.04, 0.9, 0)
  EFFECT:CreateRecollectionFilter()
  SOUND:PlayBgm(SymSnd("BGM_EVE_NAZO_01"), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  subEveFadeAfterTime()
  SOUND:PlaySe(SymSnd("SE_EVT_VOICEWAVE_M_LP"))
  EFFECT:Create("effectWaveLp", SymEff("EV_WAVE_LP"))
  EFFECT:SetPosition("effectWaveLp", SymPos("P_EFFECT_WAVE_LP"))
  EFFECT:Play("effectWaveLp")
  WINDOW:ExplanationB(-985396512)
  WINDOW:ExplanationB(-597738591)
  WINDOW:ExplanationB(522727174)
  WINDOW:ExplanationB(104013383)
  WINDOW:ExplanationB(756960644)
  WINDOW:CloseMessage()
  SOUND:FadeOutSe(SymSnd("SE_EVT_VOICEWAVE_M_LP"), TimeSec(0.5))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  EFFECT:DestroyRecollectionFilter()
  EFFECT:Remove("effectWaveLp")
  EFFECT:EndMotionBlur()
  FLAG.SceneFlag = CONST.FL_SC_04_END
  FLAG.SCENARIOFLAG = CONST.M14_SHINSOU_START
  SYSTEM:NextEntry()
end
function main14_shinsou04_end()
end
function main14_shinsou05_init()
end
function main14_shinsou05_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_NAZO_01"), Volume(256))
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  subEveFadeAfterTime()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("HERO"):WaitManpu()
  WINDOW:Monologue(872774853)
  WINDOW:Monologue(2068113922)
  WINDOW:Monologue(1650449219)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.3))
  CH("SAZANDORA_LARGE"):SetManpu("MP_SPREE_AL_LP")
  CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  subEveDoubleJump(CH("SAZANDORA_LARGE"))
  CH("HERO"):DirTo(RotateTarget(-90), Speed(200), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("SAZANDORA"), 1232242816)
  WINDOW:KeyWait()
  CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  CH("SAZANDORA_LARGE"):ResetManpu()
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), 1349106113)
  WINDOW:Talk(SymAct("SAZANDORA"), -672029426)
  WINDOW:CloseMessage()
  CH("SAZANDORA_LARGE"):DirTo(RotateTarget(45), Speed(200), ROT_TYPE.NEAR)
  CH("SAZANDORA_LARGE"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), -823487409)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.ANGRY)
  CH("SAZANDORA_LARGE"):SetManpu("MP_ANGRY_LP")
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("SAZANDORA"), -1483454365)
  WINDOW:Talk(SymAct("SAZANDORA"), -1097893598)
  WINDOW:KeyWait()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  TASK:Regist(subEveDoubleJump, {
    CH("SAZANDORA_LARGE")
  })
  WINDOW:Talk(SymAct("SAZANDORA"), -1784534303)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("HERO"):SetManpu("MP_SHOCK_L")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(-1934025824)
  WINDOW:Monologue(-1007121049)
  WINDOW:Monologue(-622609370)
  WINDOW:Monologue(-238096411)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  CH("SAZANDORA_LARGE"):ResetManpu()
  FLAG.SceneFlag = CONST.FL_SC_05_END
  FLAG.SCENARIOFLAG = CONST.M14_SHINSOU_START
  SYSTEM:NextEntry()
end
function main14_shinsou05_end()
end
function main14_shinsou06_init()
end
function main14_shinsou06_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_NAZO_01"), Volume(256))
  CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  EFFECT:StartMotionBlur(0.04, 0.9, 0)
  EFFECT:CreateRecollectionFilter()
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  subEveFadeAfterTime()
  SYSTEM:SetForceSyncStop(true)
  TASK:Sleep(TimeSec(0.3))
  WINDOW:SysMsg(-388637020)
  WINDOW:SysMsg(1867367019)
  subEveCloseMsg()
  SYSTEM:SetForceSyncStop(false)
  SOUND:PlaySe(SymSnd("SE_EVT_VOICEWAVE_M_LP"))
  EFFECT:Create("effectWaveLp", SymEff("EV_WAVE_LP"))
  EFFECT:SetPosition("effectWaveLp", SymPos("P_EFFECT_WAVE_LP"))
  EFFECT:Play("effectWaveLp")
  WINDOW:ExplanationB(1985409834)
  WINDOW:ExplanationB(-567243)
  WINDOW:ExplanationB(-420714124)
  WINDOW:KeyWait()
  SOUND:FadeOutSe(SymSnd("SE_EVT_VOICEWAVE_M_LP"), TimeSec(0.5))
  EFFECT:Remove("effectWaveLp")
  WINDOW:ExplanationB(-842974537)
  WINDOW:CloseMessage()
  SYSTEM:SetForceSyncStop(true)
  TASK:Sleep(TimeSec(0.3))
  WINDOW:SysMsg(-723907594)
  WINDOW:CloseMessage()
  SYSTEM:SetForceSyncStop(false)
  EFFECT:Create("effectWaveEnd", SymEff("EV_WAVE_END"))
  EFFECT:SetPosition("effectWaveEnd", SymPos("P_EFFECT_WAVE_END"))
  EFFECT:Play("effectWaveEnd")
  TASK:Sleep(TimeSec(0.25))
  SOUND:PlaySe(SymSnd("SE_EVT_VOICEWAVE_STOP"))
  WINDOW:ForceCloseMessage()
  TASK:Sleep(TimeSec(1.5))
  SYSTEM:SetForceSyncStop(true)
  TASK:Sleep(TimeSec(0.3))
  WINDOW:SysMsg(-1684300495)
  WINDOW:SysMsg(-2105496464)
  WINDOW:SysMsg(-1448214605)
  WINDOW:CloseMessage()
  SYSTEM:SetForceSyncStop(false)
  SOUND:PlaySe(SymSnd("SE_EVT_VOICEWAVE_L"))
  CAMERA:SetShake(Vector2(0.05, 0.05), TimeSec(1, TIME_TYPE.FRAME))
  EFFECT:Create("effectWaveBig", SymEff("EV_WAVE_BIG"))
  EFFECT:SetPosition("effectWaveBig", SymPos("P_EFFECT_WAVE_BIG"))
  EFFECT:Play("effectWaveBig")
  MAP:ChangeLightColor(Color(0.62, 0.35, 0.92, 1), TimeSec(0))
  WINDOW:Narration(TimeSec(0), TimeSec(0), -1330196750)
  TASK:Sleep(TimeSec(1.3))
  WINDOW:ForceCloseMessage()
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  TASK:Sleep(TimeSec(0.5))
  SYSTEM:SetForceSyncStop(true)
  TASK:Sleep(TimeSec(0.3))
  WINDOW:SysMsg(925815357)
  WINDOW:SysMsg(775283580)
  WINDOW:SysMsg(1196113744)
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  SYSTEM:SetForceSyncStop(false)
  EFFECT:EndMotionBlur()
  MAP:ReturnLightColor(TimeSec(0))
  EFFECT:DestroyRecollectionFilter()
  FLAG.SceneFlag = CONST.FL_SC_06_END
  FLAG.SceneFlag = CONST.FL_SC_07_END
  FLAG.SCENARIOFLAG = CONST.M14_SHINSOU_START
  SYSTEM:NextEntry()
end
function main14_shinsou06_end()
end
function main14_shinsou08_init()
end
function main14_shinsou08_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_NAZO_01"), Volume(256))
  CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  subEveFadeAfterTime()
  CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  CH("SAZANDORA_LARGE"):SetManpu("MP_SPREE_AL_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("SAZANDORA_LARGE")
  })
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("SAZANDORA"), 1582304785)
  WINDOW:Talk(SymAct("SAZANDORA"), 1971150290)
  WINDOW:CloseMessage()
  CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.ANGRY)
  CH("SAZANDORA_LARGE"):ResetManpu()
  CH("SAZANDORA_LARGE"):DirTo(RotateTarget(45), Speed(200), ROT_TYPE.NEAR)
  CH("SAZANDORA_LARGE"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  CH("SAZANDORA_LARGE"):SetManpu("MP_ANGRY_LP")
  TASK:Regist(subEveJump, {
    CH("SAZANDORA_LARGE")
  })
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("SAZANDORA"), 1818651795)
  WINDOW:KeyWait()
  CH("SAZANDORA_LARGE"):ResetManpu()
  CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("SAZANDORA"), 589822548)
  WINDOW:Talk(SymAct("SAZANDORA"), 977062677)
  WINDOW:Talk(SymAct("SAZANDORA"), 286365910)
  WINDOW:KeyWait()
  CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), 134916503)
  WINDOW:CloseMessage()
  CH("SAZANDORA_LARGE"):DirTo(CH("HERO"), Speed(200), ROT_TYPE.NEAR)
  CH("SAZANDORA_LARGE"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), -1886210728)
  WINDOW:KeyWait()
  CH("SAZANDORA_LARGE"):SetManpu("MP_LAUGH_AL_LP")
  CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  TASK:Regist(subEveDoubleJump, {
    CH("SAZANDORA_LARGE")
  })
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("SAZANDORA"), -1769372647)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.THINK)
  WINDOW:Monologue(2115080515)
  WINDOW:Monologue(1728749570)
  WINDOW:Monologue(1277686721)
  WINDOW:Monologue(1430045312)
  WINDOW:Monologue(444421191)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("SAZANDORA_LARGE"):ResetManpu()
  CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), 57042182)
  WINDOW:Talk(SymAct("SAZANDORA"), 676017861)
  WINDOW:Talk(SymAct("SAZANDORA"), 827328388)
  WINDOW:Talk(SymAct("SAZANDORA"), -1228399797)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("SAZANDORA_LARGE"):DirTo(RotateTarget(45), Speed(200), ROT_TYPE.NEAR)
  CH("SAZANDORA_LARGE"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), -1345115638)
  subEveCloseMsg()
  SOUND:FadeOutBgm(TimeSec(0.5))
  SOUND:PlaySe(SymSnd("SE_EVT_BOMANDA_GROWL"), Volume(32))
  WINDOW:SysMsg(-961677786)
  TASK:Sleep(TimeSec(0.3))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("SAZANDORA_LARGE"):SetManpu("MP_SHOCK_R")
  CH("HERO"):WaitManpu()
  TASK:Sleep(TimeSec(0.5))
  WINDOW:ForceCloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CH("HERO"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("SAZANDORA_LARGE"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  CH("SAZANDORA_LARGE"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_01"), Volume(256))
  CH("SAZANDORA_LARGE"):SetManpu("MP_EXCLAMATION")
  CH("SAZANDORA_LARGE"):WaitManpu()
  WINDOW:DrawFace(20, 20, SymAct("SAZANDORA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("SAZANDORA"), -541669529)
  subEveCloseMsg()
  WINDOW:DrawFaceF(272, 16, SymAct("HERO"), FACE_TYPE.SURPRISE)
  WINDOW:Monologue(-191130460)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("SAZANDORA_LARGE"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("SAZANDORA_LARGE"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), -310336027)
  WINDOW:Talk(SymAct("SAZANDORA"), -1564396766)
  WINDOW:CloseMessage()
  CH("SAZANDORA_LARGE"):DirTo(SymPos("P01_EXIT"), Speed(500), ROT_TYPE.NEAR)
  CH("SAZANDORA_LARGE"):WaitRotate()
  CH("SAZANDORA_LARGE"):RunTo(SplinePath(SymPos("P01_EXIT"), SymPos("P02_EXIT")), Speed(2.5))
  TASK:Sleep(TimeSec(0.3))
  CH("HERO"):RunTo(SplinePath(SymPos("P01_EXIT"), SymPos("P02_EXIT")), Speed(2.5))
  TASK:Sleep(TimeSec(0.7))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  FLAG.SceneFlag = CONST.FL_SC_08_END
  FLAG.SCENARIOFLAG = CONST.M14_SHINSOU_START
  SYSTEM:NextEntry()
end
function main14_shinsou08_end()
end
function main14_shinsou09_init()
end
function main14_shinsou09_start()
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("SAZANDORA_LARGE"):RunTo(SymPos("P01_SAZANDORA"), Speed(2.5))
  CH("HERO"):RunTo(SymPos("P01_HERO"), Speed(2.5))
  SOUND:FadeInEnv(SymSnd("SE_ENV_BREEZE_LP"), TimeSec(0.5), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.3))
  CAMERA:MoveFollow(SymCam("CAMERA_01"), Speed(2.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("SAZANDORA_LARGE"):WaitMove()
  CH("SAZANDORA_LARGE"):DirTo(RotateTarget(90), Speed(500), ROT_TYPE.NEAR)
  CH("SAZANDORA_LARGE"):WaitRotate()
  CH("HERO"):WaitMove()
  CH("HERO"):DirTo(RotateTarget(90), Speed(500), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  CAMERA:WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), -1143340445)
  WINDOW:KeyWait()
  CH("HERO"):DirTo(CH("SAZANDORA_LARGE"), Speed(500), ROT_TYPE.LEFT)
  WINDOW:Talk(SymAct("SAZANDORA"), -1862839904)
  WINDOW:CloseMessage()
  CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("SAZANDORA_LARGE"):SetManpu("MP_FLY_SWEAT")
  CH("SAZANDORA_LARGE"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("SAZANDORA"), -1980997407)
  WINDOW:Talk(SymAct("SAZANDORA"), 242514990)
  WINDOW:Talk(SymAct("SAZANDORA"), 393170287)
  WINDOW:KeyWait()
  CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), -736601656)
  WINDOW:Talk(SymAct("SAZANDORA"), -855414647)
  WINDOW:Talk(SymAct("SAZANDORA"), -433177782)
  WINDOW:Talk(SymAct("SAZANDORA"), -13301237)
  WINDOW:Talk(SymAct("SAZANDORA"), -1334534964)
  WINDOW:Talk(SymAct("SAZANDORA"), -1452298867)
  WINDOW:Talk(SymAct("SAZANDORA"), -2109538738)
  WINDOW:Talk(SymAct("SAZANDORA"), -1688613105)
  WINDOW:Talk(SymAct("SAZANDORA"), 482464704)
  WINDOW:CloseMessage()
  SOUND:FadeOutEnv(TimeSec(1))
  CAMERA:MoveToHero(Speed(2.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  SYSTEM:UpdateNextDayParameter()
  FLAG.SceneFlag = CONST.FL_SC_01_FIRST
  FLAG.SCENARIOFLAG = CONST.M14_SHINSOU_END
  FLAG.MapFlags = CONST.MAP_EVENT
  FLAG.FreePlay = CONST.FLAG_TRUE
  FLAG.TrigNextEvent = CONST.FLAG_FALSE
  SYSTEM:NextEntry(KEEP_PLACEMENT.ON)
end
function main14_shinsou09_end()
end
function groundEnd()
end

