dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main18_hyoushokutai02boss1st01_init()
  FLAG.Boss1stClear = CONST.FLAG_TRUE
end
function main18_hyoushokutai02boss1st01_start()
  subEveFromProgFadeSet()
  -- CH("HERO"):SetShadow(false)
  -- CH("PARTNER"):SetShadow(false)
  -- CH("PARTNER"):SetMotion(SymMot("EV018_KNEEATTACHE00"), LOOP.ON, TimeSec(0))
  -- CH("HERO"):SetMotion(SymMot("EV011_KNEEATTACHE01"), LOOP.ON, TimeSec(0))
  -- EFFECT:Create("effect01", SymEff("EV_EDDY_WIND_BOSS_LP"))
  -- EFFECT:SetPosition("effect01", SymPos("P01_EFFECT"))
  -- EFFECT:Play("effect01")
  -- EFFECT:Create("effect04", SymEff("BG_FRAME_SMOKE_LP"))
  -- EFFECT:SetPosition("effect04", SymPos("P04_EFFECT"))
  -- EFFECT:Play("effect04")
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- CAMERA:MoveFollow(SymCam("CAMERA_00_5"), Speed(2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- TASK:Sleep(TimeSec(0.5))
  -- SOUND:FadeInEnv(SymSnd("SE_EVT_HYOUSHOKU_AURA_LP"), TimeSec(0.5), Volume(256))
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- TASK:Sleep(TimeSec(1.5))
  -- SCREEN_A:FadeOut(TimeSec(1), true)
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetEye(SymCam("CAMERA_01"))
  -- CAMERA:SetTgt(SymCam("CAMERA_01"))
  -- CAMERA:MoveFollow(SymCam("CAMERA_01_5"), Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- TASK:Sleep(TimeSec(0.5))
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- CAMERA:WaitMove()
  -- WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SPECIAL03)
  -- WINDOW:Monologue(841637527)
  -- WINDOW:Monologue(724660182)
  -- WINDOW:Monologue(1850389)
  -- WINDOW:Monologue(419892564)
  -- WINDOW:Monologue(1447467923)
  -- WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.PAIN)
  -- WINDOW:Monologue(1331538642)
  -- WINDOW:CloseMessage()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  -- CH("HERO"):SetManpu("MP_EXCLAMATION")
  -- CH("HERO"):WaitManpu()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetEye(SymCam("CAMERA_04"))
  -- CAMERA:SetTgt(SymCam("CAMERA_04"))
  -- EFFECT:Create("effect02", SymEff("EV_WIND_DESPAIR_LP"))
  -- EFFECT:SetPosition("effect02", SymPos("P02_EFFECT"))
  -- EFFECT:Play("effect02")
  -- SOUND:PlaySe(SymSnd("SE_EVT_HYOUSHOKU_WIND_01"), Volume(256))
  -- CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  -- CH("HERO"):SetMotion(SymMot("EV018_LIES00"), LOOP.OFF)
  -- CH("HERO"):WaitPlayMotion()
  -- CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  -- CAMERA:SetShake(Vector2(0.01, 0.01), TimeSec(1, TIME_TYPE.FRAME))
  -- CH("HERO"):SetMotion(SymMot("EV018_LIES00LOOP"), LOOP.ON)
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  -- CAMERA:SetEye(SymCam("CAMERA_02"))
  -- CAMERA:SetTgt(SymCam("CAMERA_02"))
  -- WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SPECIAL03)
  -- WINDOW:Monologue(1685125393)
  -- WINDOW:Monologue(2104215632)
  -- WINDOW:Monologue(-84683617)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  -- CAMERA:SetEye(SymCam("CAMERA_03"))
  -- CAMERA:SetTgt(SymCam("CAMERA_03"))
  -- CH("PARTNER"):SetShake(Vector(0.005, 0, 0), TimeSec(0.1, TIME_TYPE.FRAME))
  -- TASK:Sleep(TimeSec(0.5))
  -- CH("PARTNER"):ResetShake()
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.PAIN)
  -- WINDOW:SwitchTalk({PARTNER_0 = -471276066, PARTNER_1 = -1796206227})
  -- WINDOW:SwitchTalk({PARTNER_0 = -1913970644, PARTNER_1 = -1496943633})
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetEye(SymCam("CAMERA_01_5"))
  -- CAMERA:SetTgt(SymCam("CAMERA_01_5"))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  -- CH("HERO"):SetManpu("MP_SHOCK_R")
  -- CH("HERO"):WaitManpu()
  -- WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SPECIAL03)
  -- WINDOW:Monologue(-1076018514)
  -- WINDOW:Monologue(-258157463)
  -- WINDOW:CloseMessage()
  -- SOUND:PlaySe(SymSnd("SE_EVT_HYOUSHOKU_POWERUP"), Volume(256))
  -- CH("HYOUSHOKUTAI"):ChangeColor(Color(0.8, 0.2, 0.8, 1), TimeSec(0.5))
  -- TASK:Sleep(TimeSec(0.5))
  -- EFFECT:Create("effect03", SymEff("NM_FIRE_VR_PURPLE"))
  -- EFFECT:SetScale("effect03", Scale(5))
  -- EFFECT:SetPosition("effect03", SymPos("P03_EFFECT"))
  -- EFFECT:Play("effect03")
  -- CAMERA:MoveFollow2(SymCam("CAMERA_04"), Speed(6, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- TASK:Sleep(TimeSec(0.5))
  -- CH("HYOUSHOKUTAI"):ChangeColor(Color(1, 1, 1, 1), TimeSec(1.8))
  -- CAMERA:WaitMove()
  -- SOUND:FadeOutEnv(TimeSec(1.5))
  -- SCREEN_A:FadeOut(TimeSec(0.5), true)
  -- CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  FLAG.SceneFlag = CONST.FL_SC_01_END
  FLAG.SCENARIOFLAG = CONST.M18_HYOUSHOKUTAI02BOSS1ST_START
  SYSTEM:NextEntry()
end
function main18_hyoushokutai02boss1st01_end()
end
function main18_hyoushokutai02boss1st02_init()
end
function main18_hyoushokutai02boss1st02_start()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetFovy(SymCam("CAMERA_00"))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- CAMERA:SetShake(Vector2(0.01, 0.01), TimeSec(1, TIME_TYPE.FRAME))
  -- EFFECT:Create("effect01", SymEff("EV_EDDY_BIG_LP"))
  -- EFFECT:SetPosition("effect01", SymPos("P01_EFFECT"))
  -- EFFECT:Play("effect01")
  -- SOUND:PlayBgm(SymSnd("BGM_EVE_ZETSUBOU_RETURN"), Volume(256))
  -- SOUND:PlaySe(SymSnd("SE_EVT_EARTHQUAKE_L_LP"), Volume(128))
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- TASK:Sleep(TimeSec(2.5))
  -- SCREEN_A:FadeOut(TimeSec(0.5), true)
  -- CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  FLAG.SceneFlag = CONST.FL_SC_02_END
  FLAG.SCENARIOFLAG = CONST.M18_HYOUSHOKUTAI02BOSS1ST_START
  SYSTEM:NextEntry()
end
function main18_hyoushokutai02boss1st02_end()
end
function main18_hyoushokutai02boss1st03_init()
end
function main18_hyoushokutai02boss1st03_start()
  -- SOUND:PlayBgm(SymSnd("BGM_EVE_ZETSUBOU_RETURN"), Volume(256))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(6))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- CAMERA:SetShake(Vector2(0.03, 0.03), TimeSec(1, TIME_TYPE.FRAME))
  -- EFFECT:Create("effect01", SymEff("EV_EDDY_BIG_LP"))
  -- EFFECT:SetPosition("effect01", SymPos("P01_EFFECT"))
  -- EFFECT:Play("effect01")
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- TASK:Sleep(TimeSec(2.5))
  -- SOUND:FadeOutSe(SymSnd("SE_EVT_EARTHQUAKE_L_LP"), TimeSec(1))
  -- SCREEN_A:FadeOut(TimeSec(0.5), true)
  -- CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  FLAG.SceneFlag = CONST.FL_SC_03_END
  FLAG.SCENARIOFLAG = CONST.M18_HYOUSHOKUTAI02BOSS1ST_START
  SYSTEM:NextEntry()
end
function main18_hyoushokutai02boss1st03_end()
end
function main18_hyoushokutai02boss1st04_init()
end
function main18_hyoushokutai02boss1st04_start()
  -- CHARA:SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  -- SOUND:PlayBgm(SymSnd("BGM_EVE_ZETSUBOU_RETURN"), Volume(256))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- TASK:Sleep(TimeSec(0.8))
  -- subEveDoubleJump(CH("YOOTERII"))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  -- CH("YOOTERII"):SetManpu("MP_FLY_SWEAT")
  -- CH("YOOTERII"):WaitManpu()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetEye(SymCam("CAMERA_01"))
  -- CAMERA:SetTgt(SymCam("CAMERA_01"))
  -- TASK:Sleep(TimeSec(0.3))
  -- WINDOW:DrawFace(20, 88, SymAct("YOOTERII"), FACE_TYPE.SURPRISE)
  -- WINDOW:Talk(SymAct("YOOTERII"), -376969944)
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(324, 88, SymAct("HAADERIA"), FACE_TYPE.SURPRISE)
  -- WINDOW:Talk(SymAct("HAADERIA"), -1028999445)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  -- CAMERA:SetEye(SymCam("CAMERA_02"))
  -- CAMERA:SetTgt(SymCam("CAMERA_02"))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  -- CH("NUOO"):SetManpu("MP_FLY_SWEAT")
  -- CH("NUOO"):WaitManpu()
  -- WINDOW:DrawFace(20, 88, SymAct("NUOO"), FACE_TYPE.SAD)
  -- WINDOW:Talk(SymAct("NUOO"), -609122390)
  -- WINDOW:Talk(SymAct("NUOO"), 1546230629)
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(324, 88, SymAct("ZURUGGU"), FACE_TYPE.THINK)
  -- WINDOW:Talk(SymAct("ZURUGGU"), 1160948260)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetEye(SymCam("CAMERA_01"))
  -- CAMERA:SetTgt(SymCam("CAMERA_01"))
  -- CH("KOARUHII"):WalkTo(SymPos("P01_KOARUHII"), Speed(1.2))
  -- CH("KOARUHII"):WaitMove()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  -- CH("KOARUHII"):SetManpu("MP_FLY_SWEAT")
  -- CH("KOARUHII"):WaitManpu()
  -- WINDOW:DrawFace(324, 88, SymAct("KOARUHII"), FACE_TYPE.SAD)
  -- WINDOW:Talk(SymAct("KOARUHII"), -2042249597)
  -- WINDOW:Talk(SymAct("KOARUHII"), -1621192766)
  -- WINDOW:Talk(SymAct("KOARUHII"), -1267475455)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  -- CAMERA:SetEye(SymCam("CAMERA_02"))
  -- CAMERA:SetTgt(SymCam("CAMERA_02"))
  -- TASK:Sleep(TimeSec(0.3))
  -- WINDOW:DrawFace(20, 88, SymAct("MINEZUMI"), FACE_TYPE.SAD)
  -- WINDOW:Talk(SymAct("MINEZUMI"), -1385632448)
  -- WINDOW:Talk(SymAct("MINEZUMI"), -500597881)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- CH("NOKOTCHI"):DirTo(RotateOffs(-120), Speed(500))
  -- CH("NOKOTCHI"):WaitRotate()
  -- TASK:Sleep(TimeSec(0.2))
  -- CH("NOKOTCHI"):DirTo(RotateOffs(210), Speed(500))
  -- CH("NOKOTCHI"):WaitRotate()
  -- TASK:Sleep(TimeSec(0.2))
  -- CH("NOKOTCHI"):DirTo(RotateOffs(90), Speed(500))
  -- CH("NOKOTCHI"):WaitRotate()
  -- TASK:Sleep(TimeSec(0.2))
  -- subEveDoubleJump(CH("NOKOTCHI"))
  -- CH("WASHIBON"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  -- CH("MINEZUMI"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  -- CH("NUOO"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.2))
  -- CH("YOOTERII"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  -- CH("HAADERIA"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.2))
  -- CH("KOARUHII"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  -- CH("ZURUGGU"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  -- CH("ZURUGGU"):WaitRotate()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetEye(SymCam("CAMERA_03"))
  -- CAMERA:SetTgt(SymCam("CAMERA_03"))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  -- CH("NOKOTCHI"):SetManpu("MP_FLY_SWEAT")
  -- CH("NOKOTCHI"):WaitManpu()
  -- WINDOW:Talk(SymAct("NOKOTCHI"), -80590138)
  -- WINDOW:Talk(SymAct("NOKOTCHI"), -803268347)
  -- WINDOW:Talk(SymAct("NOKOTCHI"), -922474428)
  -- WINDOW:Talk(SymAct("NOKOTCHI"), 1318859915)
  -- WINDOW:Talk(SymAct("NOKOTCHI"), 1468466634)
  -- WINDOW:Talk(SymAct("NOKOTCHI"), 1056561638)
  -- WINDOW:Talk(SymAct("NOKOTCHI"), 669182119)
  -- WINDOW:Talk(SymAct("NOKOTCHI"), 214940516)
  -- WINDOW:CloseMessage()
  -- CH("WASHIBON"):DirTo(RotateTarget(180), Speed(500), ROT_TYPE.NEAR)
  -- CH("WASHIBON"):WaitRotate()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  -- CAMERA:SetEye(SymCam("CAMERA_04"))
  -- CAMERA:SetTgt(SymCam("CAMERA_04"))
  -- TASK:Sleep(TimeSec(0.3))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  -- CH("WASHIBON"):SetManpu("MP_SHOCK_R")
  -- CH("WASHIBON"):WaitManpu()
  -- CH("WASHIBON"):WalkTo(SymPos("P01_WASHIBON"), Speed(1.5))
  -- CH("WASHIBON"):WaitMove()
  -- WINDOW:DrawFace(20, 88, SymAct("WASHIBON"), FACE_TYPE.SURPRISE)
  -- WINDOW:Talk(SymAct("WASHIBON"), 366250533)
  -- WINDOW:KeyWait()
  -- CH("MINEZUMI"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.2))
  -- CH("NUOO"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  -- WINDOW:Talk(SymAct("WASHIBON"), 1519721698)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- CH("NOKOTCHI"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  -- CH("YOOTERII"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("HAADERIA"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("KOARUHII"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  -- CH("ZURUGGU"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  -- CH("ZURUGGU"):WaitRotate()
  -- TASK:Sleep(TimeSec(0.3))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  -- CH("ZURUGGU"):SetManpu("MP_SHOCK_R")
  -- CH("ZURUGGU"):WaitManpu()
  -- WINDOW:DrawFace(20, 88, SymAct("ZURUGGU"), FACE_TYPE.SURPRISE)
  -- WINDOW:Talk(SymAct("ZURUGGU"), 1133391267)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetEye(SymCam("CAMERA_01"))
  -- CAMERA:SetTgt(SymCam("CAMERA_01"))
  -- SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  -- subEveDoubleJump(CH("KOARUHII"))
  -- WINDOW:DrawFace(324, 88, SymAct("KOARUHII"), FACE_TYPE.SURPRISE)
  -- WINDOW:Talk(SymAct("KOARUHII"), 1755545184)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  -- CAMERA:SetEye(SymCam("CAMERA_02"))
  -- CAMERA:SetTgt(SymCam("CAMERA_02"))
  -- subEveDoubleJump(CH("MINEZUMI"))
  -- WINDOW:DrawFace(20, 88, SymAct("MINEZUMI"), FACE_TYPE.SURPRISE)
  -- WINDOW:Talk(SymAct("MINEZUMI"), 1907904289)
  -- WINDOW:Talk(SymAct("MINEZUMI"), -165653522)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetEye(SymCam("CAMERA_01"))
  -- CAMERA:SetTgt(SymCam("CAMERA_01"))
  -- CH("YOOTERII"):DirTo(CH("HAADERIA"), Speed(350), ROT_TYPE.NEAR)
  -- CH("YOOTERII"):WaitRotate()
  -- WINDOW:DrawFace(20, 88, SymAct("YOOTERII"), FACE_TYPE.SAD)
  -- WINDOW:Talk(SymAct("YOOTERII"), -281320785)
  -- WINDOW:CloseMessage()
  -- CH("HAADERIA"):DirTo(CH("YOOTERII"), Speed(350), ROT_TYPE.NEAR)
  -- CH("HAADERIA"):WaitRotate()
  -- WINDOW:DrawFace(324, 88, SymAct("HAADERIA"), FACE_TYPE.SAD)
  -- WINDOW:Talk(SymAct("HAADERIA"), -1557208737)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  -- CAMERA:SetEye(SymCam("CAMERA_05"))
  -- CAMERA:SetTgt(SymCam("CAMERA_05"))
  -- CH("HAADERIA"):DirTo(CH("NUOO"), Speed(350), ROT_TYPE.NEAR)
  -- CH("HAADERIA"):WaitRotate()
  -- WINDOW:DrawFace(324, 20, SymAct("HAADERIA"), FACE_TYPE.CATCHBREATH)
  -- WINDOW:Talk(SymAct("HAADERIA"), -1170878434)
  -- WINDOW:Talk(SymAct("HAADERIA"), -1860664355)
  -- WINDOW:KeyWait()
  -- CH("WASHIBON"):DirTo(CH("HAADERIA"), Speed(350), ROT_TYPE.NEAR)
  -- CH("MINEZUMI"):DirTo(CH("HAADERIA"), Speed(350), ROT_TYPE.NEAR)
  -- CH("NUOO"):DirTo(CH("HAADERIA"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.2))
  -- CH("NOKOTCHI"):DirTo(CH("HAADERIA"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.2))
  -- CH("KOARUHII"):DirTo(CH("HAADERIA"), Speed(350), ROT_TYPE.NEAR)
  -- CH("ZURUGGU"):DirTo(CH("HAADERIA"), Speed(350), ROT_TYPE.NEAR)
  -- CH("ZURUGGU"):WaitRotate()
  -- CH("HAADERIA"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
  -- WINDOW:DrawFace(324, 20, SymAct("HAADERIA"), FACE_TYPE.PAIN)
  -- WINDOW:Talk(SymAct("HAADERIA"), -2013023588)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1.5))
  -- CAMERA:SetEye(SymCam("CAMERA_05_5"))
  -- CAMERA:SetTgt(SymCam("CAMERA_05_5"))
  -- CH("HAADERIA"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  -- CH("HAADERIA"):SetManpu("MP_SHOCK_L")
  -- CH("HAADERIA"):WaitManpu()
  -- CH("HAADERIA"):SetNeckRot(RotateTarget(0), RotateTarget(-35), RotateTarget(0), TimeSec(0.3))
  -- CH("HAADERIA"):WaitNeckRot()
  -- WINDOW:DrawFace(324, 88, SymAct("HAADERIA"), FACE_TYPE.SURPRISE)
  -- WINDOW:Talk(SymAct("HAADERIA"), -951966629)
  -- WINDOW:Talk(SymAct("HAADERIA"), -564587238)
  -- WINDOW:Talk(SymAct("HAADERIA"), -176929063)
  -- WINDOW:KeyWait()
  -- CH("HAADERIA"):ResetNeckRot(TimeSec(0.3))
  -- CH("HAADERIA"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  -- CH("HAADERIA"):WaitRotate()
  -- WINDOW:DrawFace(324, 88, SymAct("HAADERIA"), FACE_TYPE.PAIN)
  -- WINDOW:Talk(SymAct("HAADERIA"), -328239208)
  -- WINDOW:Talk(SymAct("HAADERIA"), 1811376983)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_06"))
  -- CAMERA:SetTgt(SymCam("CAMERA_06"))
  -- CH("WASHIBON"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  -- CH("MINEZUMI"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  -- CH("NUOO"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.2))
  -- CH("YOOTERII"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  -- CH("NOKOTCHI"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.2))
  -- CH("KOARUHII"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  -- CH("ZURUGGU"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  -- CH("ZURUGGU"):WaitRotate()
  -- WINDOW:DrawFace(324, 88, SymAct("HAADERIA"), FACE_TYPE.SAD)
  -- WINDOW:Talk(SymAct("HAADERIA"), 1928092182)
  -- WINDOW:Talk(SymAct("HAADERIA"), 462587450)
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(324, 88, SymAct("HAADERIA"), FACE_TYPE.PAIN)
  -- WINDOW:Talk(SymAct("HAADERIA"), 42579835)
  -- WINDOW:CloseMessage()
  -- SCREEN_A:FadeOut(TimeSec(0.5), true)
  FLAG.SceneFlag = CONST.FL_SC_04_END
  FLAG.SCENARIOFLAG = CONST.M18_HYOUSHOKUTAI02BOSS1ST_START
  SYSTEM:NextEntry()
end
function main18_hyoushokutai02boss1st04_end()
end
function main18_hyoushokutai02boss1st05_init()
end
function main18_hyoushokutai02boss1st05_start()
  -- SOUND:PlayBgm(SymSnd("BGM_EVE_ZETSUBOU_RETURN"), Volume(256))
  -- SOUND:PlaySe(SymSnd("SE_EVT_EARTHQUAKE_L_LP"), Volume(128))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetFovy(SymCam("CAMERA_00"))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- EFFECT:Create("effect01", SymEff("EV_EDDY_MAX_LP"))
  -- EFFECT:SetPosition("effect01", SymPos("P01_EFFECT"))
  -- EFFECT:Play("effect01")
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- TASK:Sleep(TimeSec(2.5))
  -- SOUND:FadeOutSe(SymSnd("SE_EVT_EARTHQUAKE_L_LP"), TimeSec(1))
  -- SCREEN_A:FadeOut(TimeSec(0.5), true)
  FLAG.SceneFlag = CONST.FL_SC_05_END
  FLAG.SCENARIOFLAG = CONST.M18_HYOUSHOKUTAI02BOSS1ST_START
  SYSTEM:NextEntry()
end
function main18_hyoushokutai02boss1st05_end()
end
function main18_hyoushokutai02boss1st06_init()
end
function main18_hyoushokutai02boss1st06_start()
  -- SOUND:PlayBgm(SymSnd("BGM_EVE_ZETSUBOU_RETURN"), Volume(256))
  -- CH("HERO"):SetShadow(false)
  -- CH("PARTNER"):SetShadow(false)
  -- CH("HYOUSHOKUTAI1"):SetVisible(false)
  -- CH("HYOUSHOKUTAI2"):SetVisible(false)
  -- CH("PARTNER"):SetMotion(SymMot("EV018_KNEEATTACHE00"), LOOP.ON, TimeSec(0))
  -- CH("HERO"):SetMotion(SymMot("EV011_KNEEATTACHE01"), LOOP.ON, TimeSec(0))
  -- EFFECT:Create("effect01", SymEff("EV_EDDY_WIND_BOSS_LP"))
  -- EFFECT:SetPosition("effect01", SymPos("P01_EFFECT"))
  -- EFFECT:Play("effect01")
  -- EFFECT:Create("effect02", SymEff("EV_WIND_DESPAIR_LP"))
  -- EFFECT:SetPosition("effect02", SymPos("P02_EFFECT"))
  -- EFFECT:Play("effect02")
  -- EFFECT:Create("effect05", SymEff("BG_FRAME_SMOKE_LP"))
  -- EFFECT:SetPosition("effect05", SymPos("P05_EFFECT"))
  -- EFFECT:Play("effect05")
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- CAMERA:MoveFollow2(SymCam("CAMERA_00_5"), Speed(3, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- TASK:Sleep(TimeSec(0.5))
  -- SOUND:FadeInEnv(SymSnd("SE_EVT_HYOUSHOKU_AURA_LP"), TimeSec(0.5), Volume(128))
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- CAMERA:WaitMove()
  -- CH("PARTNER"):SetShake(Vector(0.005, 0, 0), TimeSec(0.1, TIME_TYPE.FRAME))
  -- TASK:Sleep(TimeSec(0.5))
  -- CH("PARTNER"):ResetShake()
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.PAIN)
  -- WINDOW:SwitchTalk({PARTNER_0 = 698672312, PARTNER_1 = 817878521})
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1.5))
  -- CAMERA:SetEye(SymCam("CAMERA_01"))
  -- CAMERA:SetTgt(SymCam("CAMERA_01"))
  -- CH("PARTNER"):SetMotion(SymMot("EV011_KNEEATTACHE03"), LOOP.OFF)
  -- CH("PARTNER"):WaitPlayMotion()
  -- CH("PARTNER"):SetMotion(SymMot("EV011_KNEEATTACHE01"), LOOP.ON)
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.PAIN)
  -- WINDOW:SwitchTalk({PARTNER_0 = 2147369790, PARTNER_1 = 1726313087})
  -- WINDOW:SwitchTalk({PARTNER_0 = 1304961468, PARTNER_1 = 1423118589})
  -- WINDOW:SwitchTalk({PARTNER_0 = -750056398, PARTNER_1 = -900711053})
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetEye(SymCam("CAMERA_02"))
  -- CAMERA:SetTgt(SymCam("CAMERA_02"))
  -- TASK:Sleep(TimeSec(0.3))
  -- WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SPECIAL03)
  -- WINDOW:Monologue(153561556)
  -- WINDOW:Monologue(272373909)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetEye(SymCam("CAMERA_03"))
  -- CAMERA:SetTgt(SymCam("CAMERA_03"))
  -- TASK:Sleep(TimeSec(0.3))
  -- WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SPECIAL03)
  -- WINDOW:Monologue(990989142)
  -- WINDOW:Monologue(571111959)
  -- WINDOW:CloseMessage()
  -- CH("HERO"):RunTo(SymPos("P01_HERO"), Speed(0.8))
  -- CH("HERO"):WaitMove()
  -- CH("HERO"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  -- CAMERA:MoveFollow2(SymCam("CAMERA_04"), Speed(6, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- CAMERA:WaitMove()
  -- WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SHOUT)
  -- WINDOW:Monologue(1833692368)
  -- WINDOW:CloseMessage()
  -- local pokemonIndexHero = SymAct("HERO"):GetIndex()
  -- if pokemonIndexHero == 45 then
  --   CH("HERO"):SetMotionRaito(Raito(2))
  --   CH("HERO"):WalkTo(SymPos("P02_HERO"), Speed(1.7))
  -- else
  --   CH("HERO"):RunTo(SymPos("P02_HERO"), Speed(1.7))
  -- end
  -- CAMERA:MoveFollow2(SymCam("CAMERA_04_1"), Speed(7, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- CH("HERO"):WaitMove()
  -- if pokemonIndexHero == 45 then
  --   CH("HERO"):SetMotionRaito(Raito(1))
  -- end
  -- CH("HERO"):SetMotion(SymMot("EV018_ATTACK00"), LOOP.OFF)
  -- TASK:Sleep(TimeSec(0.2))
  -- EFFECT:Create("effect04", SymEff("LG_BOSS_DAMAGE"))
  -- EFFECT:SetPosition("effect04", SymPos("P04_EFFECT"))
  -- EFFECT:Play("effect04")
  -- SOUND:PlaySe(SymSnd("SE_EVT_ATTACK_HYOUSHOKU"), Volume(256))
  -- CAMERA:SetShake(Vector2(0.03, 0.03), TimeSec(1, TIME_TYPE.FRAME))
  -- TASK:Sleep(TimeSec(0.3))
  -- CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  -- CH("HERO"):SetMotion(SymMot("EV013_AVOID03"), LOOP.OFF)
  -- CAMERA:MoveFollow2(SymCam("CAMERA_04_2"), Speed(10, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- CH("HERO"):MoveTo(SymPos("P03_HERO"), Speed(1.2))
  -- CH("HERO"):WaitMove()
  -- CH("HERO"):WaitPlayMotion()
  -- CH("HERO"):SetMotion(SymMot("EV013_AVOID04"), LOOP.ON)
  -- CH("HYOUSHOKUTAI"):SetShake(Vector(0.008, 0, 0), TimeSec(1, TIME_TYPE.FRAME))
  -- TASK:Sleep(TimeSec(0.5))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetEye(SymCam("CAMERA_04_2_1"))
  -- CAMERA:SetTgt(SymCam("CAMERA_04_2_1"))
  -- TASK:Sleep(TimeSec(0.8))
  -- SOUND:PlaySe(SymSnd("SE_EVT_CORE_CRACK"), Volume(256))
  -- CH("HYOUSHOKUTAI"):ResetShake()
  -- CH("HYOUSHOKUTAI"):SetVisible(false)
  -- CH("HYOUSHOKUTAI1"):SetVisible(true)
  -- TASK:Sleep(TimeSec(0.8))
  -- CAMERA:MoveFollow2(SymCam("CAMERA_04_2"), Speed(6, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- TASK:Sleep(TimeSec(0.5))
  -- CH("HERO"):SetMotion(SymMot("EV011_KNEEATTACHE03"), LOOP.OFF, TimeSec(0.3))
  -- CH("HERO"):WaitPlayMotion()
  -- CH("HERO"):SetMotion(SymMot("EV011_KNEEATTACHE00"), LOOP.OFF)
  -- CH("HERO"):WaitPlayMotion()
  -- CH("HERO"):SetMotion(SymMot("EV011_KNEEATTACHE01"), LOOP.ON)
  -- CAMERA:WaitMove()
  -- WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SHOUT)
  -- WINDOW:Monologue(1951456657)
  -- WINDOW:CloseMessage()
  -- if pokemonIndexHero == 45 then
  --   CH("HERO"):SetMotionRaito(Raito(2))
  --   CH("HERO"):WalkTo(SymPos("P02_HERO"), Speed(1.7))
  -- else
  --   CH("HERO"):RunTo(SymPos("P02_HERO"), Speed(1.7))
  -- end
  -- CAMERA:MoveFollow2(SymCam("CAMERA_04_3"), Speed(8, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- CH("HERO"):WaitMove()
  -- if pokemonIndexHero == 45 then
  --   CH("HERO"):SetMotionRaito(Raito(1))
  -- end
  -- CH("HERO"):SetMotion(SymMot("EV018_ATTACK00"), LOOP.OFF)
  -- TASK:Sleep(TimeSec(0.2))
  -- EFFECT:Create("effect04", SymEff("LG_BOSS_DAMAGE"))
  -- EFFECT:SetPosition("effect04", SymPos("P04_EFFECT"))
  -- EFFECT:Play("effect04")
  -- SOUND:PlaySe(SymSnd("SE_EVT_ATTACK_HYOUSHOKU"), Volume(256))
  -- CAMERA:SetShake(Vector2(0.03, 0.03), TimeSec(1, TIME_TYPE.FRAME))
  -- TASK:Sleep(TimeSec(0.3))
  -- CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  -- CH("HERO"):SetMotion(SymMot("EV013_AVOID03"), LOOP.OFF)
  -- CH("HERO"):MoveTo(SymPos("P03_HERO"), Speed(1.2))
  -- SOUND:FadeOutBgm(TimeSec(3.5))
  -- SOUND:VolumeEnv(Volume(256), TimeSec(2.5))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetEye(SymCam("CAMERA_05"))
  -- CAMERA:SetTgt(SymCam("CAMERA_05"))
  -- TASK:Sleep(TimeSec(0.2))
  -- CH("HERO"):WaitMove()
  -- CH("HERO"):WaitPlayMotion()
  -- CH("HERO"):SetMotion(SymMot("EV011_KNEEATTACHE03"), LOOP.OFF, TimeSec(0.3))
  -- CH("HERO"):WaitPlayMotion()
  -- CH("HERO"):SetMotion(SymMot("EV011_KNEEATTACHE00"), LOOP.OFF)
  -- CH("HERO"):WaitPlayMotion()
  -- CH("HERO"):SetMotion(SymMot("EV011_KNEEATTACHE01"), LOOP.ON)
  -- SOUND:VolumeEnv(Volume(128), TimeSec(1.5))
  -- SOUND:PlaySe(SymSnd("SE_EVT_HYOUSHOKU_ALMOST_01_LP"), Volume(256))
  -- CH("HYOUSHOKUTAI1"):SetShake(Vector(0.008, 0, 0), TimeSec(0.1, TIME_TYPE.FRAME))
  -- TASK:Sleep(TimeSec(1.2))
  -- CH("HYOUSHOKUTAI1"):ResetShake()
  -- CH("HERO"):SetManpu("MP_SHOCK_R")
  -- CH("HERO"):SetMotion(SymMot("EV011_KNEEATTACHE02"), LOOP.OFF, TimeSec(0.2))
  -- CH("HYOUSHOKUTAI1"):SetShake(Vector(0.015, 0, 0), TimeSec(0.1, TIME_TYPE.FRAME))
  -- TASK:Sleep(TimeSec(0.3))
  -- EFFECT:Create("effect03", SymEff("EV_BREAK_BOSS_UP"))
  -- EFFECT:SetPosition("effect03", SymPos("P03_EFFECT"))
  -- EFFECT:Play("effect03")
  -- TASK:Sleep(TimeSec(0.5))
  -- CH("HYOUSHOKUTAI1"):ResetShake()
  -- TASK:Sleep(TimeSec(1))
  -- SOUND:FadeOutSe(SymSnd("SE_EVT_HYOUSHOKU_ALMOST_01_LP"), TimeSec(1))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SHELL_SPLASH_01"), Volume(256))
  -- CAMERA:SetShake(Vector2(0.1, 0.1), TimeSec(0.5, TIME_TYPE.FRAME))
  -- CH("HYOUSHOKUTAI1"):SetVisible(false)
  -- CH("HYOUSHOKUTAI2"):SetVisible(true)
  -- TASK:Sleep(TimeSec(0.5))
  -- CAMERA:SetShake(Vector2(0.01, 0.01), TimeSec(0.5, TIME_TYPE.FRAME))
  -- SOUND:FadeOutEnv(TimeSec(2))
  -- TASK:Sleep(TimeSec(0.5))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SHELL_SPLASH_02_LP"), Volume(256))
  -- CAMERA:MoveFollow2(SymCam("CAMERA_05_1"), Speed(1.5, ACCEL_TYPE.HIGH, DECEL_TYPE.HIGH))
  -- TASK:Sleep(TimeSec(1))
  -- CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  -- TASK:Sleep(TimeSec(2.5))
  -- SOUND:FadeOutSe(SymSnd("SE_EVT_SHELL_SPLASH_02_LP"), TimeSec(1))
  -- SCREEN_A:WhiteOut(TimeSec(0.5), true)
  FLAG.SceneFlag = CONST.FL_SC_06_END
  FLAG.SCENARIOFLAG = CONST.M18_HYOUSHOKUTAI02BOSS1ST_START
  SYSTEM:NextEntry()
end
function main18_hyoushokutai02boss1st06_end()
end
function main18_hyoushokutai02boss1st07_init()
end
function main18_hyoushokutai02boss1st07_start()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetFovy(SymCam("CAMERA_00"))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- EFFECT:Create("effect01", SymEff("EV_EDDY_MAX_LP"))
  -- EFFECT:SetPosition("effect01", SymPos("P01_EFFECT"))
  -- EFFECT:Play("effect01")
  -- SCREEN_A:WhiteIn(TimeSec(0.5), true)
  -- SOUND:FadeOutEnv(TimeSec(1.5))
  -- EFFECT:Create("effect02", SymEff("EV_BREAK_BOSS_SKY"))
  -- EFFECT:SetPosition("effect02", SymPos("P02_EFFECT"))
  -- EFFECT:Play("effect02")
  -- SOUND:PlaySe(SymSnd("SE_EVT_SMOKE_SCATTER_01"), Volume(256))
  -- TASK:Sleep(TimeSec(0.3))
  -- EFFECT:ChangeColor("effect01", Color(1, 1, 1, 0), TimeSec(60, TIME_TYPE.FRAME))
  -- TASK:Sleep(TimeSec(1.5))
  -- SCREEN_A:FadeOut(TimeSec(0.5), true)
  FLAG.SceneFlag = CONST.FL_SC_07_END
  FLAG.SCENARIOFLAG = CONST.M18_HYOUSHOKUTAI02BOSS1ST_START
  SYSTEM:NextEntry()
end
function main18_hyoushokutai02boss1st07_end()
end
function main18_hyoushokutai02boss1st08_init()
end
function main18_hyoushokutai02boss1st08_start()
  -- GM("RAINBOW_NORMAL_OBJ"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(6))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- EFFECT:Create("effect01", SymEff("EV_GLITTER_RAINBOW_LP"))
  -- EFFECT:SetPosition("effect01", SymPos("P01_EFFECT"))
  -- EFFECT:Play("effect01")
  -- SOUND:PlaySe(SymSnd("SE_EVT_SMOKE_SCATTER_02"), Volume(256))
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- GM("RAINBOW_NORMAL_OBJ"):ChangeColor(Color(1, 1, 1, 1), TimeSec(30, TIME_TYPE.FRAME))
  -- TASK:Sleep(TimeSec(1))
  -- SOUND:PlaySe(SymSnd("SE_EVT_RAINBOW_APPEAR_01"), Volume(100))
  -- TASK:Sleep(TimeSec(2))
  -- SOUND:PlayEnv(SymSnd("SE_EVT_RAINBOW_SHINE_LP"), Volume(256))
  -- TASK:Sleep(TimeSec(1.5))
  -- SOUND:VolumeEnv(Volume(128), TimeSec(1.5))
  -- SCREEN_A:FadeOut(TimeSec(0.5), true)
  FLAG.SceneFlag = CONST.FL_SC_08_END
  FLAG.SCENARIOFLAG = CONST.M18_HYOUSHOKUTAI02BOSS1ST_START
  SYSTEM:NextEntry()
end
function main18_hyoushokutai02boss1st08_end()
end
function main18_hyoushokutai02boss1st09_init()
end
function main18_hyoushokutai02boss1st09_start()
  -- CHARA:SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- SOUND:PlayEnv(SymSnd("SE_EVT_RAINBOW_SHINE_LP"), Volume(128))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_01"), Volume(256))
  -- CH("NOKOTCHI"):SetManpu("MP_EXCLAMATION")
  -- CH("NOKOTCHI"):WaitManpu()
  -- subEveDoubleJump(CH("NOKOTCHI"))
  -- WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.SURPRISE)
  -- WINDOW:Talk(SymAct("NOKOTCHI"), 1602063954)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  -- CAMERA:SetEye(SymCam("CAMERA_01"))
  -- CAMERA:SetTgt(SymCam("CAMERA_01"))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  -- CH("WASHIBON"):SetManpu("MP_EXCLAMATION")
  -- CH("WASHIBON"):WaitManpu()
  -- WINDOW:DrawFace(20, 88, SymAct("WASHIBON"), FACE_TYPE.SURPRISE)
  -- WINDOW:Talk(SymAct("WASHIBON"), 1181138707)
  -- WINDOW:CloseMessage()
  -- subEveJump(CH("MINEZUMI"))
  -- WINDOW:DrawFace(20, 88, SymAct("MINEZUMI"), FACE_TYPE.SURPRISE)
  -- WINDOW:DrawFaceOffset(40, 0)
  -- WINDOW:Talk(SymAct("MINEZUMI"), -1040276516)
  -- WINDOW:CloseMessage()
  -- SCREEN_A:FadeOut(TimeSec(0.5), true)
  FLAG.SceneFlag = CONST.FL_SC_09_END
  FLAG.SCENARIOFLAG = CONST.M18_HYOUSHOKUTAI02BOSS1ST_START
  SYSTEM:NextEntry()
end
function main18_hyoushokutai02boss1st09_end()
end
function main18_hyoushokutai02boss1st10_init()
end
function main18_hyoushokutai02boss1st10_start()
  -- SOUND:PlayEnv(SymSnd("SE_EVT_RAINBOW_SHINE_LP"), Volume(128))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetFovy(SymCam("CAMERA_00"))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- WINDOW:Talk(SymAct("MINEZUMI"), -656043363)
  -- subEveCloseMsg()
  -- WINDOW:Talk(SymAct("HAADERIA"), -1315221839)
  -- WINDOW:Talk(SymAct("HAADERIA"), -1467973648)
  -- WINDOW:CloseMessage()
  -- SCREEN_A:FadeOut(TimeSec(0.5), true)
  FLAG.SceneFlag = CONST.FL_SC_10_END
  FLAG.SCENARIOFLAG = CONST.M18_HYOUSHOKUTAI02BOSS1ST_START
  SYSTEM:NextEntry()
end
function main18_hyoushokutai02boss1st10_end()
end
function main18_hyoushokutai02boss1st11_init()
end
function main18_hyoushokutai02boss1st11_start()
  -- SOUND:PlayEnv(SymSnd("SE_EVT_RAINBOW_SHINE_LP"), Volume(128))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(6))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- SOUND:FadeOutEnv(TimeSec(1))
  -- GM("RAINBOW_NORMAL_OBJ"):ChangeColor(Color(1, 1, 1, 0), TimeSec(80, TIME_TYPE.FRAME))
  -- TASK:Sleep(TimeSec(0.5))
  -- SOUND:PlaySe(SymSnd("SE_EVT_FIREBALL_COME_02_LP"), Volume(256))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SMOKE_AGAIN"), Volume(256))
  -- EFFECT:Create("effect01", SymEff("EV_EDDY_MAX_START_LP"))
  -- EFFECT:SetPosition("effect01", SymPos("P01_EFFECT"))
  -- EFFECT:Play("effect01")
  -- WINDOW:DrawFace(20, 88, SymAct("HAADERIA"), FACE_TYPE.SURPRISE)
  -- WINDOW:Talk(SymAct("HAADERIA"), -2085802957)
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(324, 88, SymAct("WASHIBON"), FACE_TYPE.SURPRISE)
  -- WINDOW:Talk(SymAct("WASHIBON"), -1699340942)
  -- WINDOW:CloseMessage()
  -- TASK:Sleep(TimeSec(1))
  -- SOUND:FadeOutSe(SymSnd("SE_EVT_FIREBALL_COME_02_LP"), TimeSec(1.2))
  -- TASK:Sleep(TimeSec(0.8))
  -- SCREEN_A:FadeOut(TimeSec(0.5), true)
  FLAG.SceneFlag = CONST.FL_SC_11_END
  FLAG.SCENARIOFLAG = CONST.M18_HYOUSHOKUTAI02BOSS1ST_START
  SYSTEM:NextEntry()
end
function main18_hyoushokutai02boss1st11_end()
end
function main18_hyoushokutai02boss1st12_init()
end
function main18_hyoushokutai02boss1st12_start()
  -- CHARA:SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- SOUND:PlayBgm(SymSnd("BGM_EVE_BOSS_HYOUSHOKU_02_INTRO"), Volume(256))
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- TASK:Sleep(TimeSec(0.8))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  -- CAMERA:SetEye(SymCam("CAMERA_01"))
  -- CAMERA:SetTgt(SymCam("CAMERA_01"))
  -- TASK:Regist(subEveDoubleJump, {
  --   CH("KOARUHII")
  -- })
  -- WINDOW:DrawFace(226, 8, SymAct("KOARUHII"), FACE_TYPE.SURPRISE)
  -- WINDOW:Talk(SymAct("KOARUHII"), -705197131)
  -- WINDOW:Talk(SymAct("KOARUHII"), -856900876)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2.5))
  -- CAMERA:SetEye(SymCam("CAMERA_02"))
  -- CAMERA:SetTgt(SymCam("CAMERA_02"))
  -- TASK:Sleep(TimeSec(0.3))
  -- WINDOW:DrawFace(118, 8, SymAct("MINEZUMI"), FACE_TYPE.SURPRISE)
  -- WINDOW:Talk(SymAct("MINEZUMI"), -406722249)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2.5))
  -- CAMERA:SetEye(SymCam("CAMERA_03"))
  -- CAMERA:SetTgt(SymCam("CAMERA_03"))
  -- TASK:Sleep(TimeSec(0.3))
  -- WINDOW:DrawFaceF(118, 8, SymAct("YOOTERII"), FACE_TYPE.EMOTION)
  -- WINDOW:Talk(SymAct("YOOTERII"), -19212170)
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(324, 88, SymAct("HAADERIA"), FACE_TYPE.EMOTION)
  -- WINDOW:Talk(SymAct("HAADERIA"), 2034418873)
  -- WINDOW:Talk(SymAct("HAADERIA"), 1616508408)
  -- WINDOW:DrawFace(324, 88, SymAct("HAADERIA"), FACE_TYPE.TEARS)
  -- WINDOW:Talk(SymAct("HAADERIA"), -369598745)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  -- CAMERA:SetEye(SymCam("CAMERA_04"))
  -- CAMERA:SetTgt(SymCam("CAMERA_04"))
  -- TASK:Sleep(TimeSec(0.3))
  -- WINDOW:DrawFace(20, 88, SymAct("WASHIBON"), FACE_TYPE.EMOTION)
  -- WINDOW:Talk(SymAct("WASHIBON"), -253530202)
  -- WINDOW:Talk(SymAct("WASHIBON"), -607241115)
  -- WINDOW:Talk(SymAct("WASHIBON"), -1026224860)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- subEveDoubleJump(CH("NOKOTCHI"))
  -- WINDOW:DrawFaceF(172, 8, SymAct("NOKOTCHI"), FACE_TYPE.EMOTION)
  -- WINDOW:DrawFaceOffset(10, 0)
  -- WINDOW:Talk(SymAct("NOKOTCHI"), -1919640605)
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(20, 20, SymAct("NUOO"), FACE_TYPE.EMOTION)
  -- WINDOW:Talk(SymAct("NUOO"), -1802523998)
  -- WINDOW:Talk(SymAct("NUOO"), -1079838367)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2.5))
  -- CAMERA:SetEye(SymCam("CAMERA_02"))
  -- CAMERA:SetTgt(SymCam("CAMERA_02"))
  -- subEveJump(CH("MINEZUMI"))
  -- CH("NOKOTCHI"):DirTo(CH("MINEZUMI"), Speed(350), ROT_TYPE.NEAR)
  -- CH("WASHIBON"):DirTo(CH("MINEZUMI"), Speed(350), ROT_TYPE.NEAR)
  -- CH("ZURUGGU"):DirTo(CH("MINEZUMI"), Speed(350), ROT_TYPE.NEAR)
  -- CH("NUOO"):DirTo(CH("MINEZUMI"), Speed(350), ROT_TYPE.NEAR)
  -- CH("NUOO"):WaitRotate()
  -- WINDOW:DrawFace(118, 8, SymAct("MINEZUMI"), FACE_TYPE.EMOTION)
  -- WINDOW:Talk(SymAct("MINEZUMI"), -1497774048)
  -- WINDOW:CloseMessage()
  -- CH("MINEZUMI"):RunTo(SymPos("P01_MINEZUMI"), Speed(2.5))
  -- TASK:Sleep(TimeSec(0.2))
  -- CH("WASHIBON"):DirTo(SymPos("P01_MINEZUMI"), Speed(200), ROT_TYPE.NEAR)
  -- CH("ZURUGGU"):DirTo(SymPos("P01_MINEZUMI"), Speed(200), ROT_TYPE.NEAR)
  -- CH("NUOO"):DirTo(SymPos("P01_MINEZUMI"), Speed(200), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.4))
  -- CH("NOKOTCHI"):DirTo(SymPos("P01_MINEZUMI"), Speed(200), ROT_TYPE.NEAR)
  -- CH("YOOTERII"):DirTo(SymPos("P01_MINEZUMI"), Speed(200), ROT_TYPE.NEAR)
  -- CH("HAADERIA"):DirTo(SymPos("P01_MINEZUMI"), Speed(200), ROT_TYPE.NEAR)
  -- CH("KOARUHII"):DirTo(SymPos("P01_MINEZUMI"), Speed(200), ROT_TYPE.NEAR)
  -- CH("MINEZUMI"):WaitMove()
  -- CH("MINEZUMI"):SetVisible(false)
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2.5))
  -- CAMERA:SetEye(SymCam("CAMERA_05"))
  -- CAMERA:SetTgt(SymCam("CAMERA_05"))
  -- CH("WASHIBON"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  -- CH("HAADERIA"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  -- CH("NUOO"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.2))
  -- CH("YOOTERII"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  -- CH("NOKOTCHI"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.2))
  -- CH("KOARUHII"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  -- CH("ZURUGGU"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  -- CH("ZURUGGU"):WaitRotate()
  -- TASK:Sleep(TimeSec(0.8))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  -- CAMERA:SetEye(SymCam("CAMERA_03"))
  -- CAMERA:SetTgt(SymCam("CAMERA_03"))
  -- CH("HAADERIA"):WalkTo(SymPos("P01_HAADERIA"), Speed(1.5))
  -- CH("HAADERIA"):WaitMove()
  -- WINDOW:DrawFace(324, 88, SymAct("HAADERIA"), FACE_TYPE.TEARS)
  -- WINDOW:Talk(SymAct("HAADERIA"), 555865327)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  -- CAMERA:SetEye(SymCam("CAMERA_04"))
  -- CAMERA:SetTgt(SymCam("CAMERA_04"))
  -- CH("WASHIBON"):WalkTo(SymPos("P01_WASHIBON"), Speed(1.5))
  -- CH("WASHIBON"):WaitMove()
  -- WINDOW:DrawFace(20, 88, SymAct("WASHIBON"), FACE_TYPE.SHOUT)
  -- WINDOW:Talk(SymAct("WASHIBON"), 943383982)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2.5))
  -- CAMERA:SetEye(SymCam("CAMERA_05"))
  -- CAMERA:SetTgt(SymCam("CAMERA_05"))
  -- CH("YOOTERII"):WalkTo(SymPos("P01_YOOTERII"), Speed(1.5))
  -- CH("YOOTERII"):WaitMove()
  -- WINDOW:DrawFace(324, 88, SymAct("YOOTERII"), FACE_TYPE.SHOUT)
  -- WINDOW:Talk(SymAct("YOOTERII"), 1363425666)
  -- WINDOW:CloseMessage()
  -- CH("NOKOTCHI"):WalkTo(SymPos("P01_NOKOTCHI"), Speed(1.5))
  -- CH("NOKOTCHI"):WaitMove()
  -- subEveDoubleJump(CH("NOKOTCHI"))
  -- WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.SHOUT)
  -- WINDOW:Talk(SymAct("NOKOTCHI"), 1214187715)
  -- WINDOW:Talk(SymAct("NOKOTCHI"), 1668438784)
  -- WINDOW:CloseMessage()
  -- SCREEN_A:FadeOut(TimeSec(0.5), true)
  FLAG.SceneFlag = CONST.FL_SC_12_END
  FLAG.SCENARIOFLAG = CONST.M18_HYOUSHOKUTAI02BOSS1ST_START
  SYSTEM:NextEntry()
end
function main18_hyoushokutai02boss1st12_end()
end
function main18_hyoushokutai02boss1st13_init()
end
function main18_hyoushokutai02boss1st13_start()
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_03_5"))
  CAMERA:SetTgt(SymCam("CAMERA_03_5"))
  CH("HERO"):SetShadow(false)
  CH("PARTNER"):SetShadow(false)
  CH("HERO"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  EFFECT:Create("effect01", SymEff("EV_EDDY_WIND_BOSS_LP"))
  EFFECT:SetPosition("effect01", SymPos("P01_EFFECT"))
  EFFECT:Play("effect01")
  EFFECT:Create("effect02", SymEff("EV_WIND_DESPAIR_LP"))
  EFFECT:SetPosition("effect02", SymPos("P02_EFFECT"))
  EFFECT:Play("effect02")
  EFFECT:Create("effect03", SymEff("BG_FRAME_SMOKE_LP"))
  EFFECT:SetPosition("effect03", SymPos("P03_EFFECT"))
  EFFECT:Play("effect03")
  -- SOUND:PlayBgm(SymSnd("BGM_EVE_BOSS_HYOUSHOKU_02_INTRO"), Volume(256))
  CH("HERO"):SetShadow(false)
  CH("PARTNER"):SetShadow(false)
  SCREEN_A:FadeIn(TimeSec(0.5), true)

  -- CH("PARTNER"):SetMotion(SymMot("EV018_KNEEATTACHE00"), LOOP.ON, TimeSec(0))
  -- CH("HERO"):SetMotion(SymMot("EV018_KNEEATTACHE00"), LOOP.ON, TimeSec(0))
  -- EFFECT:Create("effect01", SymEff("EV_EDDY_WIND_BOSS_LP"))
  -- EFFECT:SetPosition("effect01", SymPos("P01_EFFECT"))
  -- EFFECT:Play("effect01")
  -- EFFECT:Create("effect02", SymEff("EV_WIND_DESPAIR_LP"))
  -- EFFECT:SetPosition("effect02", SymPos("P02_EFFECT"))
  -- EFFECT:Play("effect02")
  -- EFFECT:Create("effect03", SymEff("BG_FRAME_SMOKE_LP"))
  -- EFFECT:SetPosition("effect03", SymPos("P03_EFFECT"))
  -- EFFECT:Play("effect03")
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- TASK:Sleep(TimeSec(0.8))
  -- CH("HERO"):SetMotion(SymMot("EV011_KNEEATTACHE03"), LOOP.OFF)
  -- CH("HERO"):WaitPlayMotion()
  -- CH("HERO"):SetMotion(SymMot("EV011_KNEEATTACHE00"), LOOP.OFF)
  -- CH("HERO"):WaitPlayMotion()
  -- CH("HERO"):SetMotion(SymMot("EV011_KNEEATTACHE01"), LOOP.ON)
  -- CH("HERO"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  -- WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.DECIDE)
  -- WINDOW:Monologue(2053728833)
  -- WINDOW:KeyWait()
  -- SOUND:FadeOutBgm(TimeSec(1.5))
  -- WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.DECIDE)
  -- WINDOW:Monologue(891878534)
  -- WINDOW:CloseMessage()
  -- SOUND:PlayBgm(SymSnd("BGM_EVE_BOSS_HYOUSHOKU_02"), Volume(256))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  -- CAMERA:SetEye(SymCam("CAMERA_01"))
  -- CAMERA:SetTgt(SymCam("CAMERA_01"))
  -- TASK:Sleep(TimeSec(0.3))
  -- WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.DECIDE)
  -- WINDOW:Monologue(741592519)
  -- WINDOW:Monologue(119447044)
  -- WINDOW:Monologue(503689029)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetEye(SymCam("CAMERA_02"))
  -- CAMERA:SetTgt(SymCam("CAMERA_02"))
  -- CH("PARTNER"):SetMotion(SymMot("EV011_KNEEATTACHE03"), LOOP.OFF)
  -- CH("PARTNER"):WaitPlayMotion()
  -- CH("PARTNER"):SetMotion(SymMot("EV011_KNEEATTACHE01"), LOOP.ON)
  -- CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SHOUT)
  -- CH("PARTNER"):RunTo(SymPos("P01_PARTNER"), Speed(1.5))
  -- CH("PARTNER"):WaitMove()
  -- SOUND:PlaySe(SymSnd("SE_EVT_FLUSH"), Volume(256))
  -- TASK:Regist(subEveFlash)
  -- WINDOW:SwitchTalk({PARTNER_0 = -1717718134, PARTNER_1 = -2138668341})
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetEye(SymCam("CAMERA_03"))
  -- CAMERA:SetTgt(SymCam("CAMERA_03"))
  -- CH("HERO"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  -- CAMERA:MoveFollow(SymCam("CAMERA_03_5"), Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- CAMERA:WaitMove()
  -- subEveFlash2()
  SOUND:PlaySe(SymSnd("SE_EVT_BOSS_WIPE_02"), Volume(256))
  EFFECT:BossWipe(TimeSec(60, TIME_TYPE.FRAME), true)
  CAMERA:ResetAzimuthDifferenceVolume()
  FLAG.SceneFlag = CONST.FL_SC_01_FIRST
  FLAG.SCENARIOFLAG = CONST.M18_HYOUSHOKUTAI02BOSS1ST_END
  FLAG.Boss1stClear = CONST.FLAG_TRUE
  SYSTEM:SetNextDungeonBanner(false)
  SYSTEM:EnterDungeon(Dg(23), DG_WAYPOINT.BOSS01)
end
function main18_hyoushokutai02boss1st13_end()
end
function groundEnd()
end

