dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main03_tontonyamaclear1st01_init()
  if FLAG.NowResumeFlag == CONST.FLAG_TRUE then
    subEveFromProgFadeSet()
    subSaveflagM03_070_01()
  end
end
function main03_tontonyamaclear1st01_start()
  FLAG.EncTontonEnter = CONST.ENT_NONE
  FLAG.EventIrai = CONST.FLAG_FALSE
  QUEST:ResultNokotchiQuest()
  subEveFromProgFadeSet()
  -- TASK:Sleep(TimeSec(1))
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  -- WINDOW:SwitchTalk({PARTNER_0 = 1001631125, PARTNER_1 = 581475540})
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  -- WINDOW:SwitchTalk({PARTNER_0 = 159764247, PARTNER_1 = 278855254})
  -- WINDOW:SwitchTalk({PARTNER_0 = 1608476817, PARTNER_1 = 1187273168})
  -- WINDOW:SwitchTalk({PARTNER_0 = 1843989011, PARTNER_1 = 1962031954})
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- CH("HERO"):SetVisible(false)
  -- CH("PARTNER"):SetVisible(false)
  -- CH("EMONGA"):SetVisible(false)
  -- SOUND:FadeInEnv(SymSnd("SE_EVT_WATERFALL_LP"), TimeSec(1), Volume(128))
  -- SCREEN_A:FadeIn(TimeSec(0.5), false)
  -- CH("NOKOTCHI"):SetManpu("MP_FLY_SWEAT")
  -- CH("NOKOTCHI"):WaitManpu()
  -- CH("NOKOTCHI"):WalkTo(SymPos("P01_NOKOTCHI"), Speed(2))
  -- CH("NOKOTCHI"):WaitMove()
  -- TASK:Sleep(TimeSec(0.2))
  -- subEveLookAround(CH("NOKOTCHI"), Speed(800))
  -- CH("NOKOTCHI"):SetManpu("MP_FLY_SWEAT")
  -- CH("NOKOTCHI"):WaitManpu()
  -- TASK:Sleep(TimeSec(0.2))
  -- SOUND:VolumeEnv(Volume(256), TimeSec(0.5))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_01"))
  -- CAMERA:SetTgt(SymCam("CAMERA_01"))
  -- TASK:Sleep(TimeSec(0.5))
  -- CH("NOKOTCHI"):DirTo(RotateTarget(-45), Speed(500), ROT_TYPE.NEAR)
  -- CH("NOKOTCHI"):WaitRotate()
  -- TASK:Sleep(TimeSec(0.1))
  -- subEveLookAround(CH("NOKOTCHI"), Speed(800))
  -- TASK:Sleep(TimeSec(0.25))
  -- CH("NOKOTCHI"):SetMotion(SymMot("ENDURE"), LOOP.OFF)
  -- CH("NOKOTCHI"):WaitPlayMotion()
  -- CH("NOKOTCHI"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  -- CH("NOKOTCHI"):SetManpu("MP_FLY_SWEAT")
  -- WINDOW:DrawFaceF(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.SPECIAL02)
  -- WINDOW:Talk(SymAct("???"), -211146851)
  -- WINDOW:CloseMessage()
  -- CH("NOKOTCHI"):DirTo(RotateTarget(-135), Speed(350), ROT_TYPE.NEAR)
  -- CH("NOKOTCHI"):WaitRotate()
  -- TASK:Sleep(TimeSec(0.5))
  -- CH("NOKOTCHI"):DirTo(RotateTarget(-45), Speed(350), ROT_TYPE.NEAR)
  -- CH("NOKOTCHI"):WaitRotate()
  -- TASK:Sleep(TimeSec(0.2))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  -- CH("NOKOTCHI"):DirTo(RotateTarget(0), Speed(500), ROT_TYPE.NEAR)
  -- CH("NOKOTCHI"):WaitRotate()
  -- CH("NOKOTCHI"):SetManpu("MP_EXCLAMATION")
  -- WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.SURPRISE)
  -- WINDOW:Talk(SymAct("???"), -361687332)
  -- CH("NOKOTCHI"):WaitManpu()
  -- WINDOW:CloseMessage()
  -- CH("NOKOTCHI"):WalkTo(SymPos("P02_NOKOTCHI"), Speed(2))
  -- CAMERA:MoveFollow(SymCam("CAMERA_02"), Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- CH("HERO"):SetVisible(true)
  -- CH("PARTNER"):SetVisible(true)
  -- TASK:Regist(subEveMoveDir, {
  --   CH("PARTNER"),
  --   SymPos("P01_PARTNER"),
  --   Speed(2),
  --   RotateTarget(160)
  -- })
  -- TASK:Regist(subEveMoveDir, {
  --   CH("HERO"),
  --   SymPos("P01_HERO"),
  --   Speed(2),
  --   RotateTarget(-160)
  -- })
  -- TASK:WaitTask()
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  -- WINDOW:SwitchTalk({PARTNER_0 = -2106402352, PARTNER_1 = -1687557999})
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  -- CAMERA:SetEye(SymCam("CAMERA_02_5"))
  -- CAMERA:SetTgt(SymCam("CAMERA_02_5"))
  -- SOUND:PlaySe(SymSnd("SE_EVT_JUMP_01"), Volume(256))
  -- TASK:Regist(subEveJump, {
  --   CH("NOKOTCHI")
  -- })
  -- WINDOW:DrawFace(272, 16, SymAct("NOKOTCHI"), FACE_TYPE.SURPRISE)
  -- WINDOW:Talk(SymAct("NOKOTCHI"), -1337672878)
  -- subEveCloseMsg()
  -- CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  -- WINDOW:SwitchTalk({PARTNER_0 = -1453356525, PARTNER_1 = -434234156})
  -- WINDOW:KeyWait()
  -- CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  -- WINDOW:SwitchTalk({PARTNER_0 = -16437867, PARTNER_1 = -735543722})
  -- WINDOW:SwitchTalk({PARTNER_0 = -852275433, PARTNER_1 = 1252742104})
  -- subEveCloseMsg()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  -- CH("NOKOTCHI"):SetManpu("MP_FLY_SWEAT")
  -- WINDOW:DrawFace(272, 16, SymAct("NOKOTCHI"), FACE_TYPE.SURPRISE)
  -- WINDOW:Talk(SymAct("NOKOTCHI"), 1404068505)
  -- WINDOW:Talk(SymAct("NOKOTCHI"), -1865976258)
  -- WINDOW:DrawFace(272, 16, SymAct("NOKOTCHI"), FACE_TYPE.TEARS)
  -- WINDOW:Talk(SymAct("NOKOTCHI"), -1982052481)
  -- WINDOW:KeyWait()
  -- CH("NOKOTCHI"):SetManpu("MP_FLY_SWEAT_LP")
  -- CH("NOKOTCHI"):SetMotion(SymMot("ENDURE"), LOOP.ON)
  -- WINDOW:DrawFace(272, 16, SymAct("NOKOTCHI"), FACE_TYPE.WEEP)
  -- WINDOW:Talk(SymAct("NOKOTCHI"), -1561258820)
  -- subEveCloseMsg()
  -- CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  -- WINDOW:SwitchTalk({PARTNER_0 = -1142282755, PARTNER_1 = -190074054})
  -- WINDOW:SwitchTalk({PARTNER_0 = -307199365, PARTNER_1 = -962735688})
  -- subEveCloseMsg()
  -- CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  -- WINDOW:Talk(SymAct("EMONGA"), -544808711)
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  -- CH("PARTNER"):SetManpu("MP_NOTICE_R")
  -- CH("HERO"):SetManpu("MP_NOTICE_R")
  -- CH("NOKOTCHI"):ResetManpu()
  -- CH("NOKOTCHI"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  -- CH("NOKOTCHI"):SetManpu("MP_EXCLAMATION")
  -- WINDOW:CloseMessage()
  -- CH("HERO"):DirTo(RotateTarget(-20), Speed(500), ROT_TYPE.LEFT)
  -- CH("PARTNER"):DirTo(RotateTarget(20), Speed(500), ROT_TYPE.NEAR)
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_03"))
  -- CAMERA:SetTgt(SymCam("CAMERA_03"))
  -- CH("EMONGA"):SetVisible(true)
  -- CH("EMONGA"):WalkTo(SymPos("P01_EMONGA"), Speed(2))
  -- TASK:Sleep(TimeSec(0.5))
  -- CH("NOKOTCHI"):WalkTo(SymPos("P03_NOKOTCHI"), Speed(2))
  -- CH("EMONGA"):WaitMove()
  -- CH("NOKOTCHI"):WaitMove()
  -- TASK:Regist(subEveJump, {
  --   CH("NOKOTCHI")
  -- })
  -- WINDOW:DrawFaceF(172, 8, SymAct("NOKOTCHI"), FACE_TYPE.TEARS)
  -- WINDOW:Talk(SymAct("NOKOTCHI"), 1478425654)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(3.5))
  -- CAMERA:SetEye(SymCam("CAMERA_04"))
  -- CAMERA:SetTgt(SymCam("CAMERA_04"))
  -- CH("EMONGA"):WalkTo(SymPos("P02_EMONGA"), Speed(1.5))
  -- CH("EMONGA"):WaitMove()
  -- WINDOW:DrawFace(20, 88, SymAct("EMONGA"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("EMONGA"), 1090899319)
  -- WINDOW:CloseMessage()
  -- CH("EMONGA"):DirTo(CH("PARTNER"), Speed(200), ROT_TYPE.NEAR)
  -- CH("EMONGA"):WaitRotate()
  -- TASK:Sleep(TimeSec(0.5))
  -- CH("EMONGA"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  -- CH("EMONGA"):WaitRotate()
  -- TASK:Sleep(TimeSec(0.5))
  -- WINDOW:DrawFace(20, 88, SymAct("EMONGA"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("EMONGA"), 679154011)
  -- WINDOW:Talk(SymAct("EMONGA"), 828383258)
  -- WINDOW:CloseMessage()
  -- SOUND:FadeOutEnv(TimeSec(1.5))
  -- SCREEN_A:FadeOut(TimeSec(1), true)
  -- SOUND:WaitEnv()
  -- subEveFadeAfterTime()
  -- CAMERA:ResetAzimuthDifferenceVolume()
  -- SCREEN_A:FadeOutAll(TimeSec(0), false)
  local resultMenu = CreateRescueResultWindow()
  resultMenu:Open()
  SCREEN_A:FadeInAll(TimeSec(0.3), true)
  SOUND:PlayMe(SymSnd("ME_GAMECLEAR"), Volume(256))
  function resultMenu:decideAction()
    resultMenu:ShowDownCursor(false)
    SCREEN_A:FadeOutAll(TimeSec(0.5), true)
    self:Close()
  end
  SOUND:WaitMe()
  resultMenu:ShowDownCursor(true)
  NestMenu_OpenAndCloseWait(resultMenu)
  SCREEN_A:FadeInAll(TimeSec(0), false)
  SYSTEM:UpdateNextDayParameter()
  TASK:Sleep(TimeSec(0.2))
  -- if Ground_Save(ground) then
  --   return
  -- end
  subSaveflagM03_070_01()
end
function main03_tontonyamaclear1st01_end()
end
function subSaveflagM03_070_01()
  FLAG.SceneFlag = CONST.FL_SC_01_FIRST
  FLAG.SCENARIOFLAG = CONST.M03_TONTONYAMACLEAR1ST_END
  SYSTEM:NextEntry()
end
function groundEnd()
end

