dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main03_orei01_init()
end
function main03_orei01_start()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("MARIRURI"):SetDir(CH("NOKOTCHI"))
  LOWER_SCREEN:SetVisible(false)
  SCREEN_B:FadeOut(TimeSec(0.5), true)
  SCREEN_B:FadeInAll(TimeSec(0), false)
  SCREEN_A:FadeIn(TimeSec(0), false)
  SOUND:PlayBgm(SymSnd("BGM_EVE_CLEAR"), Volume(256))
  subEveFadeAfterTime()
  TASK:Regist(subEveDoubleJump, {
    CH("NOKOTCHI")
  })
  WINDOW:DrawFace(172, 8, SymAct("NOKOTCHI"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("NOKOTCHI"), 987622279)
  WINDOW:Talk(SymAct("NOKOTCHI"), 600234694)
  subEveCloseMsg()
  SOUND:PlayMe(SymSnd("ME_REWARD"), Volume(256))
  OverFlow:AddOverflowCheckItem(LUA_SYSTEM:GetNokotchiQuest_ItemIndex1(), LUA_SYSTEM:GetNokotchiQuest_ItemCount1(), true)
  OverFlow:OpenOrderOverflowMenu(true)
  SOUND:WaitMe()
  SOUND:PlayMe(SymSnd("ME_REWARD"), Volume(256))
  OverFlow:AddOverflowCheckItem(LUA_SYSTEM:GetNokotchiQuest_ItemIndex2(), LUA_SYSTEM:GetNokotchiQuest_ItemCount2(), true)
  OverFlow:OpenOrderOverflowMenu(true)
  SOUND:WaitMe()
  SOUND:PlayMe(SymSnd("ME_ITEM_IMPORTANT"), Volume(256))
  OverFlow:AddOverflowCheckItem(298, LUA_SYSTEM:GetNokotchiQuest_Money(), true)
  OverFlow:OpenOrderOverflowMenu(true)
  SOUND:WaitMe()
  SCREEN_B:FadeOutAll(TimeSec(0), false)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 20, SymAct("NUOO"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("NUOO"), 149653765)
  CH("PARTNER"):DirTo(CH("NUOO"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("NUOO"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:Talk(SymAct("NUOO"), 300988484)
  subEveCloseMsg()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  TASK:Regist(subEveJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  WINDOW:SwitchTalk({PARTNER_0 = 1588670083, PARTNER_1 = 1202331586})
  WINDOW:CloseMessage()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  CAMERA:SetAzimuthDifferenceVolume(Volume(3.5))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CH("EMONGA"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  CH("EMONGA"):WaitRotate()
  CH("PARTNER"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("HERO"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("NUOO"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  CH("NOKOTCHI"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(20, 88, SymAct("EMONGA"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("EMONGA"), 1820806145)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("NOKOTCHI"):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFace(272, 16, SymAct("NOKOTCHI"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("NOKOTCHI"), 1973189952)
  WINDOW:Talk(SymAct("NOKOTCHI"), -234593905)
  WINDOW:Talk(SymAct("NOKOTCHI"), -350269234)
  WINDOW:Talk(SymAct("NOKOTCHI"), 1698254024)
  WINDOW:Talk(SymAct("NOKOTCHI"), 2082635145)
  WINDOW:Talk(SymAct("NOKOTCHI"), 1460612682)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("EMONGA"):SetManpu("MP_FLY_SWEAT")
  CH("EMONGA"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("EMONGA"), FACE_TYPE.SPECIAL02)
  WINDOW:Talk(SymAct("EMONGA"), 1309941515)
  WINDOW:Talk(SymAct("EMONGA"), 22383052)
  WINDOW:KeyWait()
  CH("EMONGA"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(20, 88, SymAct("EMONGA"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("EMONGA"), 407812237)
  WINDOW:Talk(SymAct("EMONGA"), 862186318)
  WINDOW:CloseMessage()
  CH("EMONGA"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 712563215, PARTNER_1 = -1377777984})
  subEveCloseMsg()
  CH("NOKOTCHI"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("EMONGA"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("NUOO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  CH("NOKOTCHI"):WaitRotate()
  TASK:Regist(subEveJump, {
    CH("NOKOTCHI")
  })
  WINDOW:DrawFace(118, 8, SymAct("NOKOTCHI"), FACE_TYPE.EMOTION)
  WINDOW:Talk(SymAct("NOKOTCHI"), -1258555519)
  WINDOW:Talk(SymAct("NOKOTCHI"), 2005721894)
  WINDOW:Talk(SymAct("NOKOTCHI"), 1855443559)
  WINDOW:KeyWait()
  TASK:Regist(subEveJump, {
    CH("NOKOTCHI")
  })
  WINDOW:Talk(SymAct("NOKOTCHI"), 1169850788)
  WINDOW:KeyWait()
  TASK:Regist(subEveDoubleJump, {
    CH("NOKOTCHI")
  })
  WINDOW:Talk(SymAct("NOKOTCHI"), 1554100453)
  WINDOW:Talk(SymAct("NOKOTCHI"), 333456930)
  WINDOW:DrawFace(118, 8, SymAct("NOKOTCHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NOKOTCHI"), 184227683)
  WINDOW:DrawFace(118, 8, SymAct("NOKOTCHI"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("NOKOTCHI"), 567690400)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 952989153, PARTNER_1 = -1084921554})
  WINDOW:SwitchTalk({PARTNER_0 = -1504814993, PARTNER_1 = -818903997})
  WINDOW:KeyWait()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  TASK:Regist(subEveJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  WINDOW:SwitchTalk({PARTNER_0 = -701778686, PARTNER_1 = -49879359})
  WINDOW:CloseMessage()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  CAMERA:SetAzimuthDifferenceVolume(Volume(3.5))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("EMONGA"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  CH("EMONGA"):WaitRotate()
  CH("NOKOTCHI"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("NUOO"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(20, 88, SymAct("EMONGA"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("EMONGA"), -467806336)
  subEveCloseMsg()
  WINDOW:DrawFace(226, 8, SymAct("NOKOTCHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NOKOTCHI"), -1420017337)
  WINDOW:Talk(SymAct("NOKOTCHI"), -1303941114)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_QUESTION")
  CH("PARTNER"):WaitManpu()
  local taskLookAt01 = function()
    TASK:Sleep(TimeSec(0.4))
    CH("NOKOTCHI"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    CH("EMONGA"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("NUOO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt01)
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1721097275, PARTNER_1 = -2140073340})
  WINDOW:KeyWait()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_NOTICE_L")
  WINDOW:SwitchTalk({PARTNER_0 = 132714059, PARTNER_1 = 519192330})
  WINDOW:CloseMessage()
  SOUND:VolumeBgm(Volume(128), TimeSec(0.5))
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  LOWER_SCREEN:SetVisible(true)
  FLAG.SceneFlag = CONST.FL_SC_01_END
  FLAG.SCENARIOFLAG = CONST.M03_OREI_START
  SYSTEM:NextEntry()
end
function main03_orei01_end()
end
function main03_orei02_init()
end
function main03_orei02_start()
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HERO"):SetPosition(SymPos("P01_HERO"))
  CH("PARTNER"):SetPosition(SymPos("P01_PARTNER"))
  CH("HERO"):SetDir(SymPos("P02_HERO"))
  CH("PARTNER"):SetDir(SymPos("P02_PARTNER"))
  EFFECT:CreateRecollectionFilter()
  SCREEN_A:FadeIn(TimeSec(0.5), false)
  CAMERA:MoveFollow(SymCam("CAMERA_01"), Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Regist(subEveMoveDir2, {
    CH("HERO"),
    SymPos("P02_HERO"),
    Speed(1.5),
    SymPos("P02_HERO")
  })
  CH("PARTNER"):WalkTo(SymPos("P02_PARTNER"), Speed(1.5))
  TASK:Sleep(TimeSec(0.8))
  SOUND:PlaySe(SymSnd("SE_EVT_KIRAN"), Volume(64))
  EFFECT:Play("effectTwinkle_00")
  CH("PARTNER"):WaitMove()
  CH("PARTNER"):SetManpu("MP_NOTICE_R")
  CH("PARTNER"):WaitManpu()
  CH("PARTNER"):DirTo(SymPos("P00_EFF_GLITTER_RANDOM"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 1390918906, PARTNER_1 = 1274842555})
  CH("HERO"):DirTo(SymPos("P00_EFF_GLITTER_RANDOM"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:CloseMessage()
  EFFECT:Create("effectTwinkle_00", SymEff("EV_GLITTER_RANDOM"))
  EFFECT:SetPosition("effectTwinkle_00", SymPos("P00_EFF_GLITTER_RANDOM"))
  SOUND:PlaySe(SymSnd("SE_EVT_KIRAN"), Volume(64))
  EFFECT:Play("effectTwinkle_00")
  EFFECT:Wait("effectTwinkle_00")
  TASK:Regist(subEveJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  WINDOW:SwitchTalk({PARTNER_0 = 1624366712, PARTNER_1 = 2043342649})
  WINDOW:CloseMessage()
  local taskEffTwinkle00 = function()
    function TaskL.Loop()
      EFFECT:Create("effectTwinkle_01", SymEff("EV_GLITTER_RANDOM"))
      EFFECT:SetPosition("effectTwinkle_01", SymPos("P01_EFF_GLITTER_RANDOM"))
      EFFECT:Play("effectTwinkle_01")
      TASK:Sleep(TimeSec(0.5))
      EFFECT:Create("effectTwinkle_02", SymEff("EV_GLITTER_RANDOM"))
      EFFECT:SetPosition("effectTwinkle_02", SymPos("P02_EFF_GLITTER_RANDOM"))
      EFFECT:Play("effectTwinkle_02")
      TASK:Sleep(TimeSec(0.3))
      EFFECT:Create("effectTwinkle_03", SymEff("EV_GLITTER_RANDOM"))
      EFFECT:SetPosition("effectTwinkle_03", SymPos("P03_EFF_GLITTER_RANDOM"))
      EFFECT:Play("effectTwinkle_03")
      TASK:Sleep(TimeSec(1.5))
    end
  end
  local taskEffTwinkle01 = function()
    function TaskL.Loop()
      EFFECT:Create("effectTwinkle_01", SymEff("EV_GLITTER"))
      EFFECT:SetPosition("effectTwinkle_01", SymPos("P00_EFF_GLITTER"))
      EFFECT:Play("effectTwinkle_01")
      TASK:Sleep(TimeSec(1.8))
    end
  end
  TASK:Regist(Group("kabe"), taskEffTwinkle00)
  TASK:Regist(Group("yuka"), taskEffTwinkle01)
  TASK:Sleep(TimeSec(0.1))
  CAMERA:MoveFollow(SymCam("CAMERA_02"), Speed(4, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  TASK:Sleep(TimeSec(0.8))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  EFFECT:DestroyRecollectionFilter()
  FLAG.SceneFlag = CONST.FL_SC_02_END
  FLAG.SCENARIOFLAG = CONST.M03_OREI_START
  SYSTEM:NextEntry()
end
function main03_orei02_end()
end
function main03_orei03_init()
  if FLAG.NowResumeFlag == CONST.FLAG_TRUE then
    subEveFromProgFadeSet()
    subSaveflagM03_080_03()
  end
end
function main03_orei03_start()
  SOUND:PlayBgm(SymSnd("BGM_EVE_CLEAR"), Volume(128))
  CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("MARIRURI"):SetDir(CH("NOKOTCHI"))
  GM("CRYSTAL_BIG"):SetVisible(false)
  SOUND:VolumeBgm(Volume(256), TimeSec(0.5))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  subEveFadeAfterTime()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_NOTICE_L")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 915110398, PARTNER_1 = 797984959})
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_GOSOGOSO"), Volume(256))
  CH("PARTNER"):SetMotion(SymMot("EV001_GASAGASA"), LOOP.ON)
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 79502204, PARTNER_1 = 497429053})
  SOUND:WaitSe(SymSnd("SE_EVT_GOSOGOSO"))
  WINDOW:CloseMessage()
  CH("PARTNER"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  WINDOW:SwitchTalk({PARTNER_0 = -1707198734, PARTNER_1 = -2094725197})
  WINDOW:CloseMessage()
  local taskEffTwinkle = function()
    function TaskL.Loop()
      EFFECT:Create("effectTwinkle_00", SymEff("EV_GLITTER"))
      EFFECT:SetPosition("effectTwinkle_00", SymPos("P00_EFF_GLITTER"))
      EFFECT:Play("effectTwinkle_00")
      TASK:Sleep(TimeSec(1.8))
    end
  end
  local lastPosPartner = CH("PARTNER"):GetPosition2d()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3.5))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(1.5))
  TASK:Sleep(TimeSec(0.1))
  CH("NUOO"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):DirTo(GM("CRYSTAL_BIG"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("EMONGA"):DirTo(RotateTarget(45), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitMove()
  GM("CRYSTAL_BIG"):SetVisible(true)
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):WalkTo(lastPosPartner, Speed(1.5), LINK_DIR.OFF)
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_KIRAN"), Volume(256))
  TASK:Regist(Group("yuka"), taskEffTwinkle)
  CH("PARTNER"):WaitMove()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -363078753, PARTNER_1 = -213849378})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("NOKOTCHI"):SetManpu("MP_EXCLAMATION")
  CH("NOKOTCHI"):WaitManpu()
  subEveJump(CH("NOKOTCHI"))
  WINDOW:DrawFace(72, 16, SymAct("NOKOTCHI"), FACE_TYPE.EMOTION)
  WINDOW:Talk(SymAct("NOKOTCHI"), -663897827)
  WINDOW:Talk(SymAct("NOKOTCHI"), -1049196452)
  WINDOW:Talk(SymAct("NOKOTCHI"), -1908990309)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1758711846, PARTNER_1 = -1140753383})
  WINDOW:SwitchTalk({PARTNER_0 = -1525002920, PARTNER_1 = 578965911})
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("EMONGA"):SetManpu("MP_EXCLAMATION")
  CH("NOKOTCHI"):SetManpu("MP_SHOCK_R")
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("NUOO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  TASK:Regist(subEveJump, {
    CH("NOKOTCHI")
  })
  WINDOW:DrawFace(72, 16, SymAct("NOKOTCHI"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("NOKOTCHI"), 999907542)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -118590351, PARTNER_1 = -504019664})
  WINDOW:SwitchTalk({PARTNER_0 = -891808013, PARTNER_1 = -742185038})
  WINDOW:SwitchTalk({PARTNER_0 = -1669156491, PARTNER_1 = -2053537740})
  WINDOW:CloseMessage()
  TASK:ExitNotifyTasks(Group("yuka"))
  CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(1.5))
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("EMONGA"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  CH("NUOO"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_HAND"), Volume(256))
  GM("CRYSTAL_BIG"):SetVisible(false)
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):WalkTo(SymPos("P01_PARTNER"), Speed(1.5))
  CH("PARTNER"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_HAND"), Volume(256))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:SysMsg(-1363880969)
  WINDOW:CloseMessage()
  CH("PARTNER"):WalkTo(lastPosPartner, Speed(1.5), LINK_DIR.OFF)
  CH("PARTNER"):WaitMove()
  TASK:Regist(subEveDoubleJump, {
    CH("NOKOTCHI")
  })
  WINDOW:DrawFace(72, 16, SymAct("NOKOTCHI"), FACE_TYPE.EMOTION)
  WINDOW:Talk(SymAct("NOKOTCHI"), -1213209930)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 808975993, PARTNER_1 = 690802488})
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("NOKOTCHI"):SetManpu("MP_SHOCK_R")
  TASK:Regist(subEveJump, {
    CH("NOKOTCHI")
  })
  WINDOW:DrawFace(72, 16, SymAct("NOKOTCHI"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("NOKOTCHI"), 1079120660)
  WINDOW:Talk(SymAct("NOKOTCHI"), 1497965141)
  WINDOW:CloseMessage()
  CH("NOKOTCHI"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  CH("NOKOTCHI"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_PO"), Volume(256))
  WINDOW:DrawFace(226, 8, SymAct("NOKOTCHI"), FACE_TYPE.SPECIAL01)
  WINDOW:Talk(SymAct("NOKOTCHI"), 1919185302)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("EMONGA"):SetManpu("MP_EXCLAMATION")
  CH("EMONGA"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("EMONGA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EMONGA"), 1803501783)
  WINDOW:KeyWait()
  CH("EMONGA"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  TASK:Regist(subEveJump, {
    CH("EMONGA")
  })
  WINDOW:DrawFace(20, 88, SymAct("EMONGA"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("EMONGA"), 608097808)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_02"), Volume(256))
  CH("PARTNER"):SetManpu("MP_QUESTION")
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):SetManpu("MP_QUESTION")
  CH("HERO"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.THINK)
  WINDOW:SwitchTalk({PARTNER_0 = 1025894225, PARTNER_1 = 369669266})
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(1.5))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  TASK:Sleep(TimeSec(2))
  SOUND:FadeOutBgm(TimeSec(2))
  SCREEN_A:FadeOut(TimeSec(1.5), true)
  TASK:Sleep(TimeSec(1))
  CAMERA:ResetAzimuthDifferenceVolume()
  SOUND:WaitBgm()
  subSaveflagM03_080_03()
end
function main03_orei03_end()
end
function subSaveflagM03_080_03()
  FLAG.SceneFlag = CONST.FL_SC_01_FIRST
  FLAG.SCENARIOFLAG = CONST.M03_OREI_END
  SYSTEM:NextEntry()
end
function groundEnd()
end

