dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function OpeningDemo00_init()
  SYSTEM:SetForceStereoRender(true)
end
function OpeningDemo00_start()
  FLAG.OpeningSceneFlag = CONST.FL_SC_01_FIRST
  SCREEN_B:FadeOut(TimeSec(0), true)
  SCREEN_B:FadeOutAll(TimeSec(0), true)
  FLAG.OpeningSceneFlag = CONST.FL_SC_00_END
  SYSTEM:NextSpecialEntry(SymSpecialEntry("OPENING_START"))
end
function OpeningDemo00_end()
end
function OpeningDemo01_init()
end
function OpeningDemo01_start()
  SYSTEM:CheckForceEndOpening()
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CUT:Load(SymCut("CUT_OPENING_DEMO_01"))
  CH("R_HERO"):SetVisible(false)
  CH("R_PARTNER"):SetVisible(false)
  CH("KOARUHII"):SetVisible(false)
  CH("CHIRACHIINO"):SetVisible(false)
  CH("RAMUPARUDO"):SetVisible(false)
  CH("KAKUREON"):SetVisible(false)
  CH("HAADERIA"):SetVisible(false)
  CH("YOOTERII"):SetVisible(false)
  CH("DOKKORAA_1"):SetVisible(false)
  CH("DOKKORAA_2"):SetVisible(false)
  CH("NOKOTCHI"):SetVisible(false)
  CH("EMONGA"):SetVisible(false)
  CH("NUOO"):SetVisible(false)
  CH("DOTEKKOTSU"):SetVisible(false)
  CH("ZURUGGU"):SetVisible(false)
  CH("PERIPPAA"):SetShadow(false)
  CH("PERIPPAA_2"):SetShadow(false)
  CH("PERIPPAA_3"):SetShadow(false)
  SOUND:FadeInBgm(SymSnd("BGM_SYS_OPENING"), TimeSec(0), Volume(256))
  SYSTEM:ResetTimer()
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
  CAMERA:SetDefaultGroundFovy()
  SYSTEM:CheckForceEndOpening()
  CAMERA:ResetAzimuthDifferenceVolume()
  FLAG.OpeningSceneFlag = CONST.FL_SC_01_END
  SYSTEM:NextSpecialEntry(SymSpecialEntry("OPENING_START"))
end
function OpeningDemo01_end()
end
function OpeningDemo02_init()
end
function OpeningDemo02_start()
  SYSTEM:CheckForceEndOpening()
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CUT:Load(SymCut("CUT_OPENING_DEMO_02"))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
  SYSTEM:CheckForceEndOpening()
  CAMERA:SetDefaultGroundFovy()
  CAMERA:ResetAzimuthDifferenceVolume()
  FLAG.OpeningSceneFlag = CONST.FL_SC_03_END
  SYSTEM:NextSpecialEntry(SymSpecialEntry("OPENING_START"))
end
function OpeningDemo02_end()
end
function OpeningDemo04_init()
end
function OpeningDemo04_start()
  CHARA:SetRandomHeroPartner()
  local taskWakeUpHero = function()
    CH("R_HERO"):SetMotion(SymMot("OP000_SLEEP00"), LOOP.OFF)
    CH("R_HERO"):WaitPlayMotion()
    CH("R_HERO"):SetMotion(SymMot("OP000_SLEEP00LOOP"), LOOP.ON)
  end
  local taskWakeUpPartner = function()
    CH("R_PARTNER"):SetMotion(SymMot("OP000_SLEEP01"), LOOP.OFF)
    CH("R_PARTNER"):WaitPlayMotion()
    CH("R_PARTNER"):SetMotion(SymMot("OP000_SLEEP01LOOP"), LOOP.ON)
  end
  CH("R_HERO"):SetDir(RotateTarget(-45))
  CH("R_PARTNER"):SetDir(RotateTarget(45))
  CH("R_HERO"):SetMotion(SymMot("EV001_SLEEP01"), LOOP.ON, TimeSec(0))
  CH("R_PARTNER"):SetMotion(SymMot("EV001_SLEEP01"), LOOP.ON, TimeSec(0))
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SYSTEM:SyncWaitFromTimer(TimeSec(22))
  SCREEN_A:WhiteIn(TimeSec(0.3), false)
  SYSTEM:CheckForceEndOpening()
  TASK:Sleep(TimeSec(1.4))
  TASK:Regist(Group("grpPartner"), taskWakeUpPartner)
  SYSTEM:CheckForceEndOpening()
  TASK:Sleep(TimeSec(0.5))
  TASK:Regist(Group("grpHero"), taskWakeUpHero)
  SYSTEM:CheckForceEndOpening()
  TASK:Sleep(TimeSec(1.3))
  SYSTEM:CheckForceEndOpening()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  CH("R_HERO"):SetMotionRaito(Raito(1))
  CH("R_PARTNER"):SetMotionRaito(Raito(1))
  FLAG.OpeningSceneFlag = CONST.FL_SC_04_END
  SYSTEM:NextSpecialEntry(SymSpecialEntry("OPENING_START"))
end
function OpeningDemo04_end()
end
function OpeningDemo05_init()
end
function OpeningDemo05_start()
  SYSTEM:CheckForceEndOpening()
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CUT:Load(SymCut("CUT_OPENING_DEMO_05"))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
  CAMERA:SetDefaultGroundFovy()
  SYSTEM:CheckForceEndOpening()
  CAMERA:ResetAzimuthDifferenceVolume()
  FLAG.OpeningSceneFlag = CONST.FL_SC_05_END
  SYSTEM:NextSpecialEntry(SymSpecialEntry("OPENING_START"))
end
function OpeningDemo05_end()
end
function OpeningDemo05_Neck()
  CUT:SetIgnoreForceEndArea(true)
  TASK:Regist(subEveNod, {
    CH("R_HERO")
  })
  TASK:Sleep(TimeSec(0.1))
  TASK:Regist(subEveNod, {
    CH("R_PARTNER")
  })
  CUT:SetIgnoreForceEndArea(false)
end
function OpeningDemo06_init()
end
function OpeningDemo06_start()
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("NOKOTCHI"):SetVisible(false)
  CH("EMONGA"):SetVisible(false)
  CH("BIRIJION"):SetVisible(false)
  CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("R_HERO"):WalkTo(SymPos("P00_HERO"), Speed(1))
  CH("R_PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(1))
  SCREEN_A:FadeIn(TimeSec(0.3), false)
  SYSTEM:CheckForceEndOpening()
  TASK:Sleep(TimeSec(3.2))
  SYSTEM:CheckForceEndOpening()
  CH("NOKOTCHI"):SetVisible(true)
  CH("EMONGA"):SetVisible(true)
  CH("NOKOTCHI"):RunTo(SymPos("P00_NOKOTCHI"), Speed(2))
  CH("EMONGA"):RunTo(SymPos("P00_EMONGA"), Speed(2))
  TASK:Sleep(TimeSec(1.5))
  SYSTEM:CheckForceEndOpening()
  CH("BIRIJION"):SetVisible(true)
  CH("BIRIJION"):RunTo(SymPos("P00_BIRIJION"), Speed(2))
  TASK:Sleep(TimeSec(1.5))
  SYSTEM:CheckForceEndOpening()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  FLAG.OpeningSceneFlag = CONST.FL_SC_06_END
  SYSTEM:NextSpecialEntry(SymSpecialEntry("OPENING_START"))
end
function OpeningDemo06_end()
end
function OpeningDemo07_init()
end
function OpeningDemo07_start()
  CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SCREEN_A:FadeIn(TimeSec(0.3), false)
  TASK:Sleep(TimeSec(0.3))
  EFFECT:Create("effectGlitter_00", SymEff("EV_DEEDBOX_GLITTER_LP"))
  EFFECT:SetPosition("effectGlitter_00", SymPos("P00_EFF_DEEDBOX_GLITTER"))
  GM("BIG_TAKARABAKO"):SetMotion(SymMot("OPEN"), LOOP.OFF)
  EFFECT:Play("effectGlitter_00")
  GM("BIG_TAKARABAKO"):WaitPlayMotion()
  SYSTEM:CheckForceEndOpening()
  CH("EEFI"):SetManpu("MP_SPREE_LP")
  TASK:Sleep(TimeSec(0.2))
  CH("R_PARTNER"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  TASK:Regist(subEveDoubleJump, {
    CH("R_PARTNER")
  })
  TASK:Sleep(TimeSec(0.1))
  CH("BURAKKII"):SetManpu("MP_LAUGH_LP")
  TASK:Sleep(TimeSec(0.3))
  subEveDoubleJump(CH("NOKOTCHI"))
  SYSTEM:CheckForceEndOpening()
  TASK:Sleep(TimeSec(0.4))
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  CH("EEFI"):ResetManpu()
  CH("BURAKKII"):ResetManpu()
  FLAG.OpeningSceneFlag = CONST.FL_SC_07_END
  SYSTEM:NextSpecialEntry(SymSpecialEntry("OPENING_START"))
end
function OpeningDemo07_end()
end
function OpeningDemo08_init()
end
function OpeningDemo08_start()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("R_HERO"):SetDir(CH("NOKOTCHI"))
  CH("R_PARTNER"):SetDir(CH("NOKOTCHI"))
  CH("EMONGA"):SetDir(CH("R_PARTNER"))
  CH("NOKOTCHI"):SetDir(CH("R_PARTNER"))
  CH("BIRIJION"):SetDir(CH("R_PARTNER"))
  CH("DOTEKKOTSU"):SetDir(CH("R_PARTNER"))
  CH("DOKKORAA_1"):SetDir(CH("R_PARTNER"))
  CH("DOKKORAA_2"):SetDir(CH("R_PARTNER"))
  CH("R_HERO"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  CH("R_PARTNER"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  CH("EMONGA"):SetFacialMotion(FACIAL_MOTION.GLADNESS)
  SCREEN_A:FadeIn(TimeSec(0.3), false)
  CH("EMONGA"):SetManpu("MP_SPREE_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("EMONGA")
  })
  SYSTEM:CheckForceEndOpening()
  CH("R_PARTNER"):SetManpu("MP_SPREE_LP")
  CH("DOKKORAA_2"):SetManpu("MP_SPREE_LP")
  CH("NOKOTCHI"):SetMotion(SymMot("WALK"), LOOP.ON)
  CH("NOKOTCHI"):SetMotionRaito(Raito(2))
  CH("EMONGA"):SetMotion(SymMot("WAIT00"), LOOP.ON)
  CH("EMONGA"):SetMotionRaito(Raito(2))
  CH("R_PARTNER"):SetMotion(SymMot("WAIT00"), LOOP.ON)
  CH("R_PARTNER"):SetMotionRaito(Raito(2))
  CH("R_HERO"):SetMotion(SymMot("WAIT00"), LOOP.ON)
  CH("R_HERO"):SetMotionRaito(Raito(2))
  CH("DOTEKKOTSU"):SetMotion(SymMot("VICTORY"), LOOP.OFF)
  CH("DOTEKKOTSU"):WaitPlayMotion()
  CH("DOTEKKOTSU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("DOTEKKOTSU"):SetManpu("MP_LAUGH_LP")
  TASK:Sleep(TimeSec(1.6))
  SYSTEM:CheckForceEndOpening()
  SCREEN_A:WhiteOut(TimeSec(0.3), true)
  CH("R_PARTNER"):ResetManpu()
  CH("DOKKORAA_2"):ResetManpu()
  CH("DOTEKKOTSU"):ResetManpu()
  FLAG.OpeningSceneFlag = CONST.FL_SC_08_END
  SYSTEM:NextSpecialEntry(SymSpecialEntry("OPENING_START"))
end
function OpeningDemo08_end()
end
function OpeningDemo09_init()
end
function OpeningDemo09_start()
  SYSTEM:CheckForceEndOpening()
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CUT:Load(SymCut("CUT_OPENING_DEMO_09"))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
  CAMERA:SetDefaultGroundFovy()
  SYSTEM:CheckForceEndOpening()
  CAMERA:ResetAzimuthDifferenceVolume()
  FLAG.OpeningSceneFlag = CONST.FL_SC_09_END
  SYSTEM:NextSpecialEntry(SymSpecialEntry("OPENING_START"))
end
function OpeningDemo09_end()
end
function OpeningDemo10_init()
end
function OpeningDemo10_start()
  SYSTEM:SyncWaitFromTimer(TimeSec(57.7))
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:MoveFollow(SymCam("CAMERA_01"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("R_HERO"):WalkTo(SymPos("P00_HERO"), Speed(1))
  CH("R_PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(1))
  CH("NOKOTCHI"):WalkTo(SymPos("P00_NOKOTCHI"), Speed(1))
  CH("EMONGA"):WalkTo(SymPos("P00_EMONGA"), Speed(1))
  CH("BIRIJION"):WalkTo(SymPos("P00_BIRIJION"), Speed(1))
  CH("EEFI"):SetVisible(false)
  CH("BURAKKII"):SetVisible(false)
  SCREEN_A:FadeIn(TimeSec(0.3), false)
  SYSTEM:CheckForceEndOpening()
  TASK:Sleep(TimeSec(2.7))
  SYSTEM:CheckForceEndOpening()
  CH("EEFI"):SetVisible(true)
  CH("EEFI"):RunTo(SymPos("P00_EEFI"), Speed(1.7))
  TASK:Sleep(TimeSec(1.2))
  SYSTEM:CheckForceEndOpening()
  CH("BURAKKII"):SetVisible(true)
  CH("BURAKKII"):RunTo(SymPos("P00_BURAKKII"), Speed(1.7))
  TASK:Sleep(TimeSec(2.3))
  SYSTEM:CheckForceEndOpening()
  SCREEN_A:WhiteOut(TimeSec(0.3), true)
  FLAG.OpeningSceneFlag = CONST.FL_SC_10_END
  SYSTEM:NextSpecialEntry(SymSpecialEntry("OPENING_START"))
end
function OpeningDemo10_end()
end
function OpeningDemo11_init()
end
function OpeningDemo11_start()
  SYSTEM:CheckForceEndOpening()
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CUT:Load(SymCut("CUT_OPENING_DEMO_11"))
  CHARA:SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
  CAMERA:SetDefaultGroundFovy()
  SYSTEM:CheckForceEndOpening()
  CAMERA:ResetAzimuthDifferenceVolume()
  MAP:ReturnLightColor(TimeSec(0))
  FLAG.OpeningSceneFlag = CONST.FL_SC_11_END
  SYSTEM:NextSpecialEntry(SymSpecialEntry("OPENING_START"))
end
function OpeningDemo11_end()
end
function OpeningDemo11_BGBlack()
  MAP:ChangeLightColor(Color(0.2, 0.2, 0.2, 1), TimeSec(80, TIME_TYPE.FRAME))
end
function OpeningDemo12_init()
end
function OpeningDemo12_start()
  SYSTEM:CheckForceEndOpening()
  CAMERA:SetAzimuthDifferenceVolume(Volume(0.5))
  CUT:Load(SymCut("CUT_OPENING_DEMO_12"))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
  CAMERA:SetDefaultGroundFovy()
  SYSTEM:CheckForceEndOpening()
  CAMERA:ResetAzimuthDifferenceVolume()
  FLAG.OpeningSceneFlag = CONST.FL_SC_12_END
  SYSTEM:NextSpecialEntry(SymSpecialEntry("OPENING_START"))
end
function OpeningDemo12_end()
end
function OpeningDemo13_init()
end
function OpeningDemo13_start()
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:MoveFollow(SymCam("CAMERA_01"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("R_HERO"):WalkTo(SymPos("P00_HERO"), Speed(1))
  CH("R_PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(1))
  CH("NOKOTCHI"):WalkTo(SymPos("P00_NOKOTCHI"), Speed(1))
  CH("EMONGA"):WalkTo(SymPos("P00_EMONGA"), Speed(1))
  CH("EEFI"):WalkTo(SymPos("P00_EEFI"), Speed(1))
  CH("BIRIJION"):WalkTo(SymPos("P00_BIRIJION"), Speed(1))
  CH("BURAKKII"):WalkTo(SymPos("P00_BURAKKII"), Speed(1))
  CH("NUOO"):SetVisible(false)
  CH("DOTEKKOTSU"):SetVisible(false)
  CH("ZURUGGU"):SetVisible(false)
  CH("DOKKORAA_1"):SetVisible(false)
  CH("DOKKORAA_2"):SetVisible(false)
  SYSTEM:SyncWaitFromTimer(TimeSec(75))
  SCREEN_A:FadeIn(TimeSec(0.3), false)
  SYSTEM:CheckForceEndOpening()
  TASK:Sleep(TimeSec(2))
  SYSTEM:CheckForceEndOpening()
  CH("NUOO"):SetVisible(true)
  CH("DOTEKKOTSU"):SetVisible(true)
  CH("ZURUGGU"):SetVisible(true)
  CH("NUOO"):RunTo(SymPos("P00_NUOO"), Speed(2))
  TASK:Sleep(TimeSec(0.2))
  CH("DOTEKKOTSU"):RunTo(SymPos("P00_DOTEKKOTSU"), Speed(2))
  CH("ZURUGGU"):RunTo(SymPos("P00_ZURUGGU"), Speed(2))
  TASK:Sleep(TimeSec(0.8))
  SYSTEM:CheckForceEndOpening()
  CH("DOKKORAA_1"):SetVisible(true)
  CH("DOKKORAA_2"):SetVisible(true)
  CH("DOKKORAA_1"):RunTo(SymPos("P00_DOKKORAA_1"), Speed(2))
  CH("DOKKORAA_2"):RunTo(SymPos("P00_DOKKORAA_2"), Speed(2))
  TASK:Sleep(TimeSec(1.7))
  SYSTEM:CheckForceEndOpening()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  FLAG.OpeningSceneFlag = CONST.FL_SC_13_END
  SYSTEM:NextSpecialEntry(SymSpecialEntry("OPENING_START"))
end
function OpeningDemo13_end()
end
function OpeningDemo14_init()
end
function OpeningDemo14_start()
  CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("R_HERO"):WalkTo(SymPos("P00_HERO"), Speed(1.5))
  CH("R_PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(1.5))
  CH("BURAKKII"):WalkTo(SymPos("P00_BURAKKII"), Speed(1.5))
  CH("BIRIJION"):WalkTo(SymPos("P00_BIRIJION"), Speed(1.5))
  CH("EEFI"):WalkTo(SymPos("P00_EEFI"), Speed(1.5))
  CH("NOKOTCHI"):WalkTo(SymPos("P00_NOKOTCHI"), Speed(1.5))
  TASK:Sleep(TimeSec(0.1))
  SCREEN_A:FadeIn(TimeSec(0.3), false)
  SYSTEM:CheckForceEndOpening()
  TASK:Sleep(TimeSec(1.3))
  CH("R_PARTNER"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  SYSTEM:CheckForceEndOpening()
  TASK:Sleep(TimeSec(0.5))
  SYSTEM:CheckForceEndOpening()
  SCREEN_A:FadeOut(TimeSec(0.3), true)
  FLAG.OpeningSceneFlag = CONST.FL_SC_14_END
  SYSTEM:NextSpecialEntry(SymSpecialEntry("OPENING_START"))
end
function OpeningDemo14_end()
end
function OpeningDemo15_init()
end
function OpeningDemo15_start()
  CAMERA:SetFovy(SymCam("CAMERA_00"))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(7, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  EFFECT:Create("effectGlitterGPalaceLp02", SymEff("EV_GLITTER_G_PALACE_LP"))
  EFFECT:SetPosition("effectGlitterGPalaceLp02", SymPos("P_EFF_GLITTER_G_PALACE_LP_02"))
  EFFECT:Create("effectGlitterGPalaceLp03", SymEff("EV_GLITTER_G_PALACE_LP"))
  EFFECT:SetPosition("effectGlitterGPalaceLp03", SymPos("P_EFF_GLITTER_G_PALACE_LP_03"))
  EFFECT:Create("effectGlitterGPalaceLp04", SymEff("EV_GLITTER_G_PALACE_LP"))
  EFFECT:SetPosition("effectGlitterGPalaceLp04", SymPos("P_EFF_GLITTER_G_PALACE_LP_04"))
  EFFECT:Play("effectGlitterGPalaceLp02")
  SCREEN_A:FadeIn(TimeSec(0.5), false)
  SYSTEM:CheckForceEndOpening()
  EFFECT:Play("effectGlitterGPalaceLp03")
  EFFECT:Play("effectGlitterGPalaceLp04")
  TASK:Sleep(TimeSec(3.7))
  SYSTEM:CheckForceEndOpening()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  CAMERA:SetDefaultGroundFovy()
  FLAG.OpeningSceneFlag = CONST.FL_SC_15_END
  SYSTEM:NextSpecialEntry(SymSpecialEntry("OPENING_START"))
end
function OpeningDemo15_end()
end
function OpeningDemo16_init()
end
function OpeningDemo16_start()
  SYSTEM:CheckForceEndOpening()
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CUT:Load(SymCut("CUT_OPENING_DEMO_16"))
  SYSTEM:SyncWaitFromTimer(TimeSec(88.5))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
  CAMERA:SetDefaultGroundFovy()
  SYSTEM:CheckForceEndOpening()
  TASK:Sleep(TimeSec(0.5))
  CAMERA:ResetAzimuthDifferenceVolume()
  FLAG.OpeningSceneFlag = CONST.FL_SC_16_END
  SYSTEM:NextSpecialEntry(SymSpecialEntry("OPENING_START"))
end
function OpeningDemo16_end()
  SYSTEM:SetForceStereoRender(false)
end
function OpeningDemo16_shadow_01()
  CH("R_HERO"):SetShadow(false)
  CH("R_PARTNER"):SetShadow(false)
  CH("NOKOTCHI"):SetShadow(false)
  CH("EMONGA"):SetShadow(false)
  CH("BIRIJION"):SetShadow(false)
  CH("BURAKKII"):SetShadow(false)
  CH("EEFI"):SetShadow(false)
  CH("NUOO"):SetShadow(false)
  CH("ZURUGGU"):SetShadow(false)
  CH("DOTEKKOTSU"):SetShadow(false)
  CH("DOKKORAA_1"):SetShadow(false)
  CH("DOKKORAA_2"):SetShadow(false)
end
function groundEnd()
end

