dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function sub01_sazandoranohanashi01_init()
end
function sub01_sazandoranohanashi01_start()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("SAZANDORA_LARGE"):ChangeColor(Color(1, 1, 1, 0), TimeSec(0, TIME_TYPE.FRAME))
  CH("PLAYER"):WalkTo(SymPos("P01_PLAYER"), Speed(1.5))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("PLAYER"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("PLAYER"):SetManpu("MP_NOTICE_R")
  WINDOW:DrawFace(226, 8, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1026501815, PARTNER_1 = -607395320})
  WINDOW:SwitchTalk({PARTNER_0 = -253316661, PARTNER_1 = -369262454})
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("EMONGA"):SetManpu("MP_FLY_SWEAT")
  CH("EMONGA"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("EMONGA"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("EMONGA"), -1497622963)
  WINDOW:Talk(SymAct("EMONGA"), -1079564532)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SAZANDORA_GHOST"), Volume(256))
  CH("SAZANDORA_LARGE"):ChangeColor(Color(1, 1, 1, 1), TimeSec(30, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.4))
  CH("PLAYER"):DirTo(CH("SAZANDORA_LARGE"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("PLAYER"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(1))
  CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 88, SymAct("EMONGA"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("EMONGA"), -1802865457)
  WINDOW:CloseMessage()
  CH("EMONGA"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.NEAR)
  CH("SAZANDORA_LARGE"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.NEAR)
  CH("EMONGA"):WaitRotate()
  WINDOW:DrawFaceF(20, 88, SymAct("EMONGA"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("EMONGA"), -1919859314)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), 168384833)
  WINDOW:CloseMessage()
  CH("EMONGA"):DirTo(RotateTarget(90), Speed(350), ROT_TYPE.NEAR)
  CH("SAZANDORA_LARGE"):DirTo(RotateTarget(90), Speed(350), ROT_TYPE.NEAR)
  CH("EMONGA"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("EMONGA"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("EMONGA"), 319973376)
  subEveCloseMsg()
  WINDOW:DrawFaceF(324, 88, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), 407041691)
  WINDOW:CloseMessage()
  CH("EMONGA"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  CH("SAZANDORA_LARGE"):DirTo(RotateTarget(-150), Speed(350), ROT_TYPE.NEAR)
  CH("EMONGA"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("EMONGA"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("EMONGA"), 22661082)
  WINDOW:DrawFace(20, 88, SymAct("EMONGA"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("EMONGA"), 712283161)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  TASK:Regist(subEveJump, {
    CH("SAZANDORA_LARGE")
  })
  CH("SAZANDORA_LARGE"):SetManpu("MP_EXCLAMATION")
  CH("SAZANDORA_LARGE"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("SAZANDORA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("SAZANDORA"), 862954840)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("EMONGA"):DirTo(RotateTarget(40), Speed(500), ROT_TYPE.NEAR)
  CH("EMONGA"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("EMONGA"):SetManpu("MP_SHOCK_R")
  CH("EMONGA"):WalkTo(SymPos("P01_EMONGA"), Speed(2.5), LINK_DIR.OFF)
  CH("EMONGA"):WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("EMONGA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("EMONGA"), 2083402655)
  subEveCloseMsg()
  SOUND:PlayBgm(SymSnd("BGM_EVE_COMICAL"), Volume(256))
  CH("SAZANDORA_LARGE"):WalkTo(SymPos("P01_SAZANDORA"), Speed(1.5))
  CH("SAZANDORA_LARGE"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_JUMP_02"), Volume(256))
  TASK:Regist(subEveDoubleJump, {
    CH("SAZANDORA_LARGE")
  })
  WINDOW:DrawFace(324, 88, SymAct("SAZANDORA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("SAZANDORA"), 1697972958)
  WINDOW:Talk(SymAct("SAZANDORA"), 1310216477)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("EMONGA"):SetManpu("MP_SHOCK_R")
  CH("EMONGA"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("EMONGA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("EMONGA"), 1459839068)
  WINDOW:KeyWait()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  CH("EMONGA"):SetManpu("MP_ANGRY_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("EMONGA")
  })
  WINDOW:DrawFace(20, 88, SymAct("EMONGA"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("EMONGA"), -795116397)
  WINDOW:Talk(SymAct("EMONGA"), -914338350)
  WINDOW:CloseMessage()
  CH("EMONGA"):ResetManpu()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("SAZANDORA_LARGE"):SetManpu("MP_QUESTION")
  CH("SAZANDORA_LARGE"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("SAZANDORA"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("SAZANDORA"), 183982453)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  CH("EMONGA"):SetManpu("MP_ANGRY_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("EMONGA")
  })
  WINDOW:DrawFace(20, 88, SymAct("EMONGA"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("EMONGA"), 334260276)
  WINDOW:Talk(SymAct("EMONGA"), 952187895)
  WINDOW:CloseMessage()
  CH("EMONGA"):ResetManpu()
  TASK:Sleep(TimeSec(0.2))
  CH("SAZANDORA_LARGE"):SetNeckRot(RotateTarget(0), RotateTarget(10), RotateTarget(0), TimeSec(0.3))
  TASK:Regist(subEveJump, {
    CH("SAZANDORA_LARGE")
  })
  WINDOW:DrawFace(324, 88, SymAct("SAZANDORA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("SAZANDORA"), 567937718)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  CH("EMONGA"):SetManpu("MP_ANGRY_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("EMONGA")
  })
  WINDOW:DrawFace(20, 88, SymAct("EMONGA"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("EMONGA"), 1855691889)
  WINDOW:KeyWait()
  CH("EMONGA"):ResetManpu()
  WINDOW:Talk(SymAct("EMONGA"), 2004921648)
  WINDOW:DrawFace(20, 88, SymAct("EMONGA"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("EMONGA"), 1554906867)
  WINDOW:KeyWait()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("EMONGA"):SetManpu("MP_FLY_SWEAT")
  WINDOW:Talk(SymAct("EMONGA"), 1169608626)
  WINDOW:CloseMessage()
  CH("SAZANDORA_LARGE"):ResetNeckRot(TimeSec(0.15))
  CH("SAZANDORA_LARGE"):WaitNeckRot()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("SAZANDORA_LARGE"):SetManpu("MP_SHOCK_L")
  CH("SAZANDORA_LARGE"):WaitManpu()
  TASK:Regist(subEveDoubleJump, {
    CH("SAZANDORA_LARGE")
  })
  WINDOW:DrawFace(324, 88, SymAct("SAZANDORA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("SAZANDORA"), -1037118595)
  WINDOW:Talk(SymAct("SAZANDORA"), -617225668)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("PLAYER"):SetManpu("MP_QUESTION")
  CH("PLAYER"):WaitManpu()
  WINDOW:DrawFace(20, 20, SymAct("PARTNER"), FACE_TYPE.THINK)
  WINDOW:SwitchTalk({PARTNER_0 = -1303691760, PARTNER_1 = -1420816559})
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), -2139267950)
  WINDOW:Talk(SymAct("SAZANDORA"), -1721340461)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  CH("EMONGA"):SetManpu("MP_ANGRY_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("EMONGA")
  })
  WINDOW:DrawFace(20, 88, SymAct("EMONGA"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("EMONGA"), -702022892)
  WINDOW:CloseMessage()
  CH("EMONGA"):ResetManpu()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("SAZANDORA_LARGE"):SetManpu("MP_FLY_SWEAT")
  TASK:Regist(subEveDoubleJump, {
    CH("SAZANDORA_LARGE")
  })
  WINDOW:DrawFace(324, 88, SymAct("SAZANDORA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("SAZANDORA"), -818099627)
  WINDOW:Talk(SymAct("SAZANDORA"), -468608618)
  WINDOW:DrawFace(324, 88, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), -49633065)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("EMONGA"):SetManpu("MP_QUESTION")
  CH("EMONGA"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("EMONGA"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("EMONGA"), 2056434712)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("EMONGA"):SetManpu("MP_SHOCK_R")
  CH("EMONGA"):WaitManpu()
  TASK:Regist(subEveJump, {
    CH("EMONGA")
  })
  WINDOW:DrawFace(20, 88, SymAct("EMONGA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("EMONGA"), 1669956953)
  WINDOW:Talk(SymAct("EMONGA"), 798754473)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(2.5))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("SAZANDORA_LARGE"):SetManpu("MP_SHOCK_L")
  CH("SAZANDORA_LARGE"):WaitManpu()
  TASK:Regist(subEveDoubleJump, {
    CH("SAZANDORA_LARGE")
  })
  WINDOW:DrawFace(324, 88, SymAct("SAZANDORA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("SAZANDORA"), 914831336)
  WINDOW:Talk(SymAct("SAZANDORA"), 497706027)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("EMONGA"):SetManpu("MP_QUESTION")
  CH("EMONGA"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("EMONGA"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("EMONGA"), 78730602)
  WINDOW:CloseMessage()
  CH("EMONGA"):DirTo(CH("PLAYER"), Speed(350), ROT_TYPE.NEAR)
  CH("EMONGA"):WaitRotate()
  CH("PLAYER"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(1))
  CH("EMONGA"):SetNeckRot(RotateTarget(0), RotateTarget(0), RotateTarget(20), TimeSec(0.3))
  CH("PLAYER"):SetNeckRot(RotateTarget(0), RotateTarget(0), RotateTarget(-20), TimeSec(0.3))
  CH("PLAYER"):WaitNeckRot()
  TASK:Sleep(TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(1))
  FLAG.SceneFlag = CONST.FL_SC_01_END
  FLAG.SCENARIOFLAG = CONST.S1_SAZANDORANOHANASHI_START
  SYSTEM:NextEntry()
end
function sub01_sazandoranohanashi01_end()
end
function sub01_sazandoranohanashi02_init()
end
function sub01_sazandoranohanashi02_start()
  CHARA:SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  CAMERA:SetAzimuthDifferenceVolume(Volume(3.5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:MoveFollow2(SymCam("CAMERA_00_5"), Speed(15, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SCREEN_A:FadeIn(TimeSec(0.5), false)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("NOKOTCHI"):SetManpu("MP_SHOCK_R")
  TASK:Regist(subEveJumpSurprise, {
    CH("NOKOTCHI")
  })
  CH("EMONGA"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  TASK:Regist(subEveJump, {
    CH("EMONGA")
  })
  CH("BURAKKII"):SetManpu("MP_EXCLAMATION")
  CH("EEFI"):SetManpu("MP_EXCLAMATION")
  CH("KERUDYIO"):SetManpu("MP_SHOCK_L")
  WINDOW:DrawFace(324, 88, SymAct("EEFI"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("EEFI"), 1274069933)
  CAMERA:WaitMove()
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(2.5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("BIRIJION"):SetManpu("MP_SHOCK_R")
  CH("BIRIJION"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("BIRIJION"), 1391194860)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(2.5))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(272, 16, SymAct("BURAKKII"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("BURAKKII"), 2043060527)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("KERUDYIO"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("KERUDYIO"), 1625133166)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_00_5"))
  CAMERA:SetTgt(SymCam("CAMERA_00_5"))
  SOUND:PlayBgm(SymSnd("BGM_EVE_METAMORPHOSIS_02"), Volume(256))
  TASK:Sleep(TimeSec(0.1))
  WINDOW:DrawFace(272, 16, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), -414872415)
  WINDOW:Talk(SymAct("SAZANDORA"), -27345440)
  WINDOW:Talk(SymAct("SAZANDORA"), -1759485492)
  WINDOW:Talk(SymAct("SAZANDORA"), -1908715379)
  WINDOW:Talk(SymAct("SAZANDORA"), -1525284018)
  WINDOW:Talk(SymAct("SAZANDORA"), -1139985905)
  WINDOW:Talk(SymAct("SAZANDORA"), -213080888)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  TASK:Sleep(TimeSec(0.3))
  TASK:Regist(subEveDoubleJump, {
    CH("NOKOTCHI")
  })
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("NOKOTCHI"), -363358839)
  CH("EMONGA"):DirTo(CH("NOKOTCHI"), Speed(200), ROT_TYPE.NEAR)
  CH("PLAYER"):DirTo(CH("EMONGA"), Speed(200), ROT_TYPE.NEAR)
  WINDOW:CloseMessage()
  CH("SAZANDORA_LARGE"):DirTo(CH("NOKOTCHI"), Speed(200), ROT_TYPE.NEAR)
  CH("SAZANDORA_LARGE"):WaitRotate()
  CH("EEFI"):DirTo(CH("NOKOTCHI"), Speed(200), ROT_TYPE.NEAR)
  CH("BURAKKII"):DirTo(CH("NOKOTCHI"), Speed(200), ROT_TYPE.NEAR)
  CH("KERUDYIO"):DirTo(CH("NOKOTCHI"), Speed(200), ROT_TYPE.NEAR)
  CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(324, 20, SymAct("SAZANDORA"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("SAZANDORA"), -1048918454)
  WINDOW:Talk(SymAct("SAZANDORA"), -664668405)
  WINDOW:CloseMessage()
  CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  TASK:Regist(subEveDoubleJump, {
    CH("NOKOTCHI")
  })
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.EMOTION)
  WINDOW:Talk(SymAct("NOKOTCHI"), 1610214340)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("EMONGA"):SetManpu("MP_QUESTION")
  CH("EMONGA"):WaitManpu()
  WINDOW:DrawFace(20, 20, SymAct("EMONGA"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("EMONGA"), 1189272197)
  WINDOW:CloseMessage()
  CH("NOKOTCHI"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("SAZANDORA_LARGE"):DirTo(CH("EMONGA"), Speed(200), ROT_TYPE.NEAR)
  CH("SAZANDORA_LARGE"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NOKOTCHI"), -2053779934)
  WINDOW:Talk(SymAct("NOKOTCHI"), -1668350109)
  WINDOW:Talk(SymAct("NOKOTCHI"), -1214010208)
  WINDOW:Talk(SymAct("NOKOTCHI"), -1363632671)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_00_5"))
  CAMERA:SetTgt(SymCam("CAMERA_00_5"))
  TASK:Sleep(TimeSec(0.1))
  local taskLookAt01 = function()
    TASK:Sleep(TimeSec(0.3))
    CH("EMONGA"):DirTo(CH("SAZANDORA_LARGE"), Speed(350), ROT_TYPE.NEAR)
    CH("KERUDYIO"):DirTo(CH("SAZANDORA_LARGE"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("EEFI"):DirTo(CH("SAZANDORA_LARGE"), Speed(350), ROT_TYPE.NEAR)
    CH("PLAYER"):DirTo(CH("SAZANDORA_LARGE"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("BURAKKII"):DirTo(CH("SAZANDORA_LARGE"), Speed(350), ROT_TYPE.NEAR)
    CH("NOKOTCHI"):DirTo(CH("SAZANDORA_LARGE"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt01)
  WINDOW:DrawFace(272, 16, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), -503772378)
  WINDOW:Talk(SymAct("SAZANDORA"), -119391641)
  WINDOW:Talk(SymAct("SAZANDORA"), -741381724)
  WINDOW:Talk(SymAct("SAZANDORA"), -892053275)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  CH("SAZANDORA_LARGE"):DirTo(CH("SUWANNA"), Speed(350), ROT_TYPE.NEAR)
  CH("SAZANDORA_LARGE"):WaitRotate()
  CH("SUWANNA"):DirTo(CH("SAZANDORA_LARGE"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(324, 88, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), 1296843818)
  WINDOW:Talk(SymAct("SAZANDORA"), 1415017835)
  WINDOW:KeyWait()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("SAZANDORA_LARGE"):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFace(324, 88, SymAct("SAZANDORA"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("SAZANDORA"), 1026140487)
  WINDOW:Talk(SymAct("SAZANDORA"), 607295494)
  TASK:Sleep(TimeSec(0.1))
  WINDOW:ForceCloseMessage()
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 20, SymAct("SUWANNA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SUWANNA"), 253742021)
  WINDOW:Talk(SymAct("SUWANNA"), 369425028)
  WINDOW:Talk(SymAct("SUWANNA"), 1497721923)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("SAZANDORA"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("SAZANDORA"), 1079926018)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_00_5"))
  CAMERA:SetTgt(SymCam("CAMERA_00_5"))
  CH("SAZANDORA_LARGE"):DirTo(RotateTarget(-15), Speed(350), ROT_TYPE.NEAR)
  CH("SAZANDORA_LARGE"):WaitRotate()
  WINDOW:DrawFace(272, 16, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), 1802702529)
  WINDOW:Talk(SymAct("SAZANDORA"), 1919434624)
  WINDOW:Talk(SymAct("SAZANDORA"), -168811697)
  WINDOW:Talk(SymAct("SAZANDORA"), -320138738)
  WINDOW:Talk(SymAct("SAZANDORA"), 1699395857)
  WINDOW:Talk(SymAct("SAZANDORA"), 2085718096)
  WINDOW:Talk(SymAct("SAZANDORA"), 1467800467)
  WINDOW:Talk(SymAct("SAZANDORA"), 1315433170)
  WINDOW:Talk(SymAct("SAZANDORA"), 19299349)
  WINDOW:Talk(SymAct("SAZANDORA"), 406670676)
  WINDOW:Talk(SymAct("SAZANDORA"), 856694423)
  WINDOW:Talk(SymAct("SAZANDORA"), 705376214)
  WINDOW:Talk(SymAct("SAZANDORA"), -1382862055)
  WINDOW:Talk(SymAct("SAZANDORA"), -1266154920)
  WINDOW:Talk(SymAct("SAZANDORA"), -571023756)
  WINDOW:Talk(SymAct("SAZANDORA"), -991039691)
  WINDOW:Talk(SymAct("SAZANDORA"), -272581386)
  WINDOW:Talk(SymAct("SAZANDORA"), -153383497)
  WINDOW:Talk(SymAct("SAZANDORA"), -1181082768)
  WINDOW:Talk(SymAct("SAZANDORA"), -1602147791)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_05"))
  CAMERA:SetTgt(SymCam("CAMERA_05"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("EEFI"):SetManpu("MP_QUESTION")
  CH("EEFI"):WaitManpu()
  CH("SAZANDORA_LARGE"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(324, 20, SymAct("EEFI"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("EEFI"), -1951630862)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 20, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), -1833482061)
  WINDOW:Talk(SymAct("SAZANDORA"), 355423356)
  WINDOW:Talk(SymAct("SAZANDORA"), 204760381)
  WINDOW:Talk(SymAct("SAZANDORA"), 1492400310)
  WINDOW:Talk(SymAct("SAZANDORA"), 1106184695)
  WINDOW:Talk(SymAct("SAZANDORA"), 1791121972)
  WINDOW:Talk(SymAct("SAZANDORA"), 1943628661)
  WINDOW:Talk(SymAct("SAZANDORA"), 1016659378)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("NOKOTCHI"):SetManpu("MP_SHOCK_R")
  TASK:Regist(subEveJumpSurprise, {
    CH("NOKOTCHI")
  })
  CH("EEFI"):SetManpu("MP_EXCLAMATION")
  CH("KERUDYIO"):SetManpu("MP_SHOCK_L")
  TASK:Sleep(TimeSec(0.1))
  CH("EMONGA"):SetManpu("MP_EXCLAMATION")
  CH("BURAKKII"):SetManpu("MP_SHOCK_L")
  TASK:Regist(subEveJump, {
    CH("EMONGA")
  })
  WINDOW:DrawFace(324, 20, SymAct("EEFI"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("EEFI"), 629394675)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("BURAKKII"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("BURAKKII"), 246325040)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 20, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), 397782641)
  WINDOW:Talk(SymAct("SAZANDORA"), -1876053314)
  WINDOW:Talk(SymAct("SAZANDORA"), -1992915969)
  WINDOW:Talk(SymAct("SAZANDORA"), -532127789)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(72, 16, SymAct("EMONGA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EMONGA"), -111972718)
  WINDOW:CloseMessage()
  local taskLookAt02 = function()
    TASK:Sleep(TimeSec(0.3))
    CH("SAZANDORA_LARGE"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
    CH("KERUDYIO"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("EEFI"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
    CH("PLAYER"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
    CH("BIRIJION"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("BURAKKII"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
    CH("NOKOTCHI"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt02)
  CH("EMONGA"):DirTo(CH("PLAYER"), Speed(350), ROT_TYPE.NEAR)
  CH("EMONGA"):WaitRotate()
  WINDOW:DrawFace(72, 16, SymAct("EMONGA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EMONGA"), -763478703)
  WINDOW:Talk(SymAct("EMONGA"), -882570224)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), -2077975849)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(2.5))
  CAMERA:MoveFollow(SymCam("CAMERA_07"), Speed(2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  local taskLookAt03 = function()
    CH("BIRIJION"):DirTo(CH("PLAYER"), Speed(350), ROT_TYPE.NEAR)
    CH("KERUDYIO"):DirTo(CH("PLAYER"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("EEFI"):DirTo(CH("PLAYER"), Speed(350), ROT_TYPE.NEAR)
    CH("SAZANDORA_LARGE"):DirTo(CH("PLAYER"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("BURAKKII"):DirTo(CH("PLAYER"), Speed(350), ROT_TYPE.NEAR)
    CH("NOKOTCHI"):DirTo(CH("PLAYER"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt03)
  CAMERA:WaitMove()
  TASK:Sleep(TimeSec(1))
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  CH("PLAYER"):SetFacialMotion(FACIAL_MOTION.SAD)
  CH("PLAYER"):SetNeckRot(RotateTarget(0), RotateTarget(-20), RotateTarget(0), TimeSec(0.5))
  CH("PLAYER"):WaitNeckRot()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SAD)
  WINDOW:SwitchTalk({PARTNER_0 = -1656771690, PARTNER_1 = -1240270763})
  WINDOW:SwitchTalk({PARTNER_0 = -1358313196, PARTNER_1 = 680646107})
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  TASK:Sleep(TimeSec(0.1))
  WINDOW:DrawFace(20, 20, SymAct("EMONGA"), FACE_TYPE.SPECIAL01)
  WINDOW:Talk(SymAct("EMONGA"), 831186074)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 20, SymAct("EEFI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EEFI"), -218238915)
  WINDOW:Talk(SymAct("EEFI"), -337198724)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("BIRIJION"):SetManpu("MP_NOTICE_R")
  CH("BIRIJION"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("BIRIJION"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("BIRIJION"), -1060400449)
  WINDOW:Talk(SymAct("BIRIJION"), -640637954)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SAD)
  WINDOW:SwitchTalk({PARTNER_0 = -1768868551, PARTNER_1 = -1886780296})
  subEveCloseMsg()
  WINDOW:DrawFace(324, 20, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BURAKKII"), -1532536901)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SAD)
  WINDOW:SwitchTalk({PARTNER_0 = -1111726342, PARTNER_1 = 975469109})
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_09"))
  CAMERA:SetTgt(SymCam("CAMERA_09"))
  CAMERA:MoveFollow2(SymCam("CAMERA_09_5"), Speed(0.1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_DESPAIR_L3"), Volume(256))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SAD)
  WINDOW:SwitchTalk({PARTNER_0 = 591350644, PARTNER_1 = 1245812568})
  WINDOW:SwitchTalk({PARTNER_0 = 1398449689, PARTNER_1 = 2021127642})
  WINDOW:SwitchTalk({PARTNER_0 = 1634518171, PARTNER_1 = 774722140})
  WINDOW:SwitchTalk({PARTNER_0 = 926311197, PARTNER_1 = 471544030})
  WINDOW:SwitchTalk({PARTNER_0 = 83886495, PARTNER_1 = -2103960240})
  WINDOW:SwitchTalk({PARTNER_0 = -1685902319, PARTNER_1 = -677990431})
  WINDOW:SwitchTalk({PARTNER_0 = -829579616, PARTNER_1 = -442446493})
  WINDOW:SwitchTalk({PARTNER_0 = -54789086, PARTNER_1 = -1275434267})
  WINDOW:SwitchTalk({PARTNER_0 = -1428071516, PARTNER_1 = -2117334937})
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3.5))
  CAMERA:SetEye(SymCam("CAMERA_06"))
  CAMERA:SetTgt(SymCam("CAMERA_06"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(72, 16, SymAct("EMONGA"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("EMONGA"), -1730725594)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SAD)
  WINDOW:SwitchTalk({PARTNER_0 = 525280745, PARTNER_1 = 106173608})
  WINDOW:SwitchTalk({PARTNER_0 = 1865074820, PARTNER_1 = 1982986693})
  WINDOW:SwitchTalk({PARTNER_0 = 1562159622, PARTNER_1 = 1141349191})
  WINDOW:SwitchTalk({PARTNER_0 = 189140352, PARTNER_1 = 308100289})
  WINDOW:SwitchTalk({PARTNER_0 = 963669762, PARTNER_1 = 543907395})
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 20, SymAct("SUWANNA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SUWANNA"), -1477229940)
  WINDOW:Talk(SymAct("SUWANNA"), -1092062259)
  WINDOW:KeyWait()
  SOUND:FadeOutBgm(TimeSec(3.5))
  WINDOW:Talk(SymAct("SUWANNA"), 2107598698)
  WINDOW:Talk(SymAct("SUWANNA"), 1686394411)
  WINDOW:Talk(SymAct("SUWANNA"), 1336477160)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_00_5"))
  CAMERA:SetTgt(SymCam("CAMERA_00_5"))
  CH("PLAYER"):ResetNeckRot(TimeSec(0.2))
  CH("PLAYER"):WaitNeckRot()
  CH("PLAYER"):DirTo(CH("SUWANNA"), Speed(350), ROT_TYPE.NEAR)
  CH("PLAYER"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SAD)
  WINDOW:SwitchTalk({PARTNER_0 = 1454519465, PARTNER_1 = 435397230})
  subEveCloseMsg()
  WINDOW:DrawFace(272, 16, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), 15242031)
  CH("PLAYER"):DirTo(CH("SAZANDORA_LARGE"), Speed(200), ROT_TYPE.NEAR)
  WINDOW:Talk(SymAct("SAZANDORA"), 734380268)
  WINDOW:Talk(SymAct("SAZANDORA"), 853471661)
  WINDOW:Talk(SymAct("SAZANDORA"), -1253642910)
  WINDOW:Talk(SymAct("SAZANDORA"), -1403134941)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  CH("PLAYER"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("PLAYER"):SetManpu("MP_EXCLAMATION")
  CH("PLAYER"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -987561969, PARTNER_1 = -600297138})
  WINDOW:KeyWait()
  SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_HOPE"), Volume(256))
  WINDOW:SwitchTalk({PARTNER_0 = -149593459, PARTNER_1 = -301050932})
  WINDOW:KeyWait()
  CH("PLAYER"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1588607733, PARTNER_1 = -1202391990})
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_00_5"))
  CAMERA:SetTgt(SymCam("CAMERA_00_5"))
  TASK:Sleep(TimeSec(0.3))
  local taskLookAt04 = function()
    CH("EMONGA"):DirTo(CH("SAZANDORA_LARGE"), Speed(350), ROT_TYPE.NEAR)
    CH("KERUDYIO"):DirTo(CH("SAZANDORA_LARGE"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("EEFI"):DirTo(CH("SAZANDORA_LARGE"), Speed(350), ROT_TYPE.NEAR)
    CH("BIRIJION"):DirTo(CH("SAZANDORA_LARGE"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("BURAKKII"):DirTo(CH("SAZANDORA_LARGE"), Speed(350), ROT_TYPE.NEAR)
    CH("NOKOTCHI"):DirTo(CH("SAZANDORA_LARGE"), Speed(350), ROT_TYPE.NEAR)
    CH("SUWANNA"):DirTo(CH("SAZANDORA_LARGE"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt04)
  WINDOW:DrawFace(272, 16, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), -1820743799)
  WINDOW:Talk(SymAct("SAZANDORA"), -1973250360)
  subEveCloseMsg()
  TASK:Regist(subEveDoubleJump, {
    CH("EMONGA")
  })
  WINDOW:DrawFace(20, 20, SymAct("EMONGA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EMONGA"), 234523143)
  WINDOW:Talk(SymAct("EMONGA"), 350337862)
  subEveCloseMsg()
  WINDOW:DrawFace(272, 16, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), -1656745895)
  WINDOW:Talk(SymAct("SAZANDORA"), -2074402536)
  WINDOW:Talk(SymAct("SAZANDORA"), -1351191845)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("PLAYER"):SetManpu("MP_EXCLAMATION")
  CH("PLAYER"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = -1234353254, PARTNER_1 = -114502307})
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3.5))
  CAMERA:SetEye(SymCam("CAMERA_10"))
  CAMERA:SetTgt(SymCam("CAMERA_10"))
  CH("NOKOTCHI"):DirTo(CH("PLAYER"), Speed(350), ROT_TYPE.NEAR)
  CH("NOKOTCHI"):WaitRotate()
  local taskLookAt05 = function()
    TASK:Sleep(TimeSec(0.2))
    CH("PLAYER"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
    CH("KERUDYIO"):DirTo(CH("PLAYER"), Speed(350), ROT_TYPE.NEAR)
    CH("EEFI"):DirTo(CH("PLAYER"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("EMONGA"):DirTo(CH("PLAYER"), Speed(350), ROT_TYPE.NEAR)
    CH("BURAKKII"):DirTo(CH("PLAYER"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("SUWANNA"):DirTo(CH("PLAYER"), Speed(350), ROT_TYPE.NEAR)
    CH("BIRIJION"):DirTo(CH("PLAYER"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt05)
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("NOKOTCHI"), -533208036)
  WINDOW:Talk(SymAct("NOKOTCHI"), -887441441)
  WINDOW:Talk(SymAct("NOKOTCHI"), -771651938)
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("NOKOTCHI"), 1436129873)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SAD)
  WINDOW:SwitchTalk({PARTNER_0 = 1283631888, PARTNER_1 = 637302588})
  subEveCloseMsg()
  CH("PLAYER"):DirTo(CH("BIRIJION"), Speed(200), ROT_TYPE.NEAR)
  WINDOW:DrawFace(20, 20, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), 1021789821)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.SAD)
  WINDOW:SwitchTalk({PARTNER_0 = 399119806, PARTNER_1 = 248587519})
  WINDOW:CloseMessage()
  CH("EMONGA"):WalkTo(SymPos("P01_EMONGA"), Speed(1.5))
  CH("EMONGA"):WaitMove()
  CH("PLAYER"):DirTo(CH("EMONGA"), Speed(200), ROT_TYPE.NEAR)
  WINDOW:DrawFace(72, 16, SymAct("EMONGA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EMONGA"), 1100001848)
  WINDOW:Talk(SymAct("EMONGA"), 1485538169)
  WINDOW:Talk(SymAct("EMONGA"), 1940312250)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(subEveDoubleJump, {
    CH("EEFI")
  })
  WINDOW:DrawFace(20, 20, SymAct("EEFI"), FACE_TYPE.EMOTION)
  WINDOW:Talk(SymAct("EEFI"), 1790829051)
  CH("PLAYER"):DirTo(CH("BURAKKII"), Speed(200), ROT_TYPE.NEAR)
  subEveCloseMsg()
  CH("KERUDYIO"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  CH("KERUDYIO"):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(324, 88, SymAct("KERUDYIO"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("KERUDYIO"), -316277452)
  subEveCloseMsg()
  CH("KERUDYIO"):ResetManpu()
  WINDOW:DrawFace(272, 16, SymAct("BURAKKII"), FACE_TYPE.EMOTION)
  WINDOW:Talk(SymAct("BURAKKII"), -197211019)
  WINDOW:CloseMessage()
  CH("KERUDYIO"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  TASK:Sleep(TimeSec(0.2))
  CH("PLAYER"):DirTo(CH("SAZANDORA_LARGE"), Speed(200), ROT_TYPE.NEAR)
  CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(324, 20, SymAct("SAZANDORA"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("SAZANDORA"), -564114920)
  subEveCloseMsg()
  CH("PLAYER"):DirTo(CH("NOKOTCHI"), Speed(200), ROT_TYPE.NEAR)
  TASK:Regist(subEveJump, {
    CH("NOKOTCHI")
  })
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.TEARS)
  WINDOW:Talk(SymAct("NOKOTCHI"), -948208807)
  subEveCloseMsg()
  CH("BIRIJION"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(20, 20, SymAct("BIRIJION"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("BIRIJION"), -329897830)
  WINDOW:CloseMessage()
  CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  CH("BIRIJION"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  TASK:Sleep(TimeSec(0.2))
  CH("PLAYER"):DirTo(CH("SUWANNA"), Speed(200), ROT_TYPE.NEAR)
  CH("SUWANNA"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(20, 20, SymAct("SUWANNA"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("SUWANNA"), -179496485)
  WINDOW:CloseMessage()
  CH("SUWANNA"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_07"))
  CAMERA:SetTgt(SymCam("CAMERA_07"))
  TASK:Sleep(TimeSec(0.2))
  CH("PLAYER"):SetShake(Vector(0.005, 0, 0), TimeSec(0.5, TIME_TYPE.FRAME))
  CH("PLAYER"):SetNeckRot(RotateTarget(0), RotateTarget(-20), RotateTarget(0), TimeSec(0.5))
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.TEARS)
  WINDOW:SwitchTalk({PARTNER_0 = -1173582052, PARTNER_1 = -1558725027})
  subEveCloseMsg()
  CH("PLAYER"):ResetShake()
  WINDOW:DrawFace(20, 20, SymAct("EMONGA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EMONGA"), -2009404002)
  WINDOW:Talk(SymAct("EMONGA"), -1860051745)
  subEveCloseMsg()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PLAYER"):SetManpu("MP_FLY_SWEAT")
  CH("PLAYER"):WaitManpu()
  CH("PLAYER"):ResetNeckRot(TimeSec(0.2))
  CH("PLAYER"):WaitNeckRot()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.TEARS)
  WINDOW:SwitchTalk({PARTNER_0 = 381272080, PARTNER_1 = 262336849})
  WINDOW:SwitchTalk({PARTNER_0 = 1725705597, PARTNER_1 = 2143755324})
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_00_5"))
  CAMERA:SetTgt(SymCam("CAMERA_00_5"))
  CH("PLAYER"):DirTo(CH("BIRIJION"), Speed(350), ROT_TYPE.NEAR)
  CH("PLAYER"):WaitRotate()
  TASK:Sleep(TimeSec(0.3))
  CH("PLAYER"):DirTo(CH("EEFI"), Speed(350), ROT_TYPE.NEAR)
  CH("PLAYER"):WaitRotate()
  TASK:Sleep(TimeSec(0.3))
  CH("PLAYER"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  CH("PLAYER"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.TEARS)
  WINDOW:SwitchTalk({PARTNER_0 = 1424642047, PARTNER_1 = 1307672254})
  WINDOW:SwitchTalk({PARTNER_0 = 45148281, PARTNER_1 = 464247096})
  WINDOW:SwitchTalk({PARTNER_0 = 814123771, PARTNER_1 = 698203066})
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_11"))
  CAMERA:SetTgt(SymCam("CAMERA_11"))
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(subEveDoubleJump, {
    CH("NOKOTCHI")
  })
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.EMOTION)
  WINDOW:Talk(SymAct("NOKOTCHI"), -1375361163)
  subEveCloseMsg()
  WINDOW:DrawFace(72, 16, SymAct("EMONGA"), FACE_TYPE.EMOTION)
  WINDOW:Talk(SymAct("EMONGA"), -1222732236)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_12"))
  CAMERA:SetTgt(SymCam("CAMERA_12"))
  TASK:Sleep(TimeSec(0.2))
  local taskLookAt01 = function()
    TASK:Sleep(TimeSec(0.3))
    CH("EMONGA"):DirTo(CH("SAZANDORA_LARGE"), Speed(350), ROT_TYPE.NEAR)
    CH("KERUDYIO"):DirTo(CH("SAZANDORA_LARGE"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("EEFI"):DirTo(CH("SAZANDORA_LARGE"), Speed(350), ROT_TYPE.NEAR)
    CH("BIRIJION"):DirTo(CH("SAZANDORA_LARGE"), Speed(350), ROT_TYPE.NEAR)
    CH("PLAYER"):DirTo(CH("SAZANDORA_LARGE"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("BURAKKII"):DirTo(CH("SAZANDORA_LARGE"), Speed(350), ROT_TYPE.NEAR)
    CH("NOKOTCHI"):DirTo(CH("SAZANDORA_LARGE"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt01)
  CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  CH("SAZANDORA_LARGE"):SetManpu("MP_LAUGH_AL_LP")
  WINDOW:DrawFace(324, 20, SymAct("SAZANDORA"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("SAZANDORA"), 1953071763)
  WINDOW:KeyWait()
  CH("SAZANDORA_LARGE"):ResetManpu()
  WINDOW:Talk(SymAct("SAZANDORA"), 1836233682)
  WINDOW:Talk(SymAct("SAZANDORA"), 1180688401)
  WINDOW:Talk(SymAct("SAZANDORA"), 1598345552)
  WINDOW:CloseMessage()
  CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("EMONGA"):SetManpu("MP_QUESTION")
  CH("EMONGA"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("EMONGA"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("EMONGA"), 268781463)
  WINDOW:Talk(SymAct("EMONGA"), 152991446)
  WINDOW:CloseMessage()
  CH("SAZANDORA_LARGE"):DirTo(CH("EMONGA"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  WINDOW:DrawFace(324, 20, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), 573777173)
  WINDOW:Talk(SymAct("SAZANDORA"), 992482388)
  WINDOW:Talk(SymAct("SAZANDORA"), -1129314149)
  WINDOW:Talk(SymAct("SAZANDORA"), -1515505190)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_00_5"))
  CAMERA:SetTgt(SymCam("CAMERA_00_5"))
  CH("SAZANDORA_LARGE"):DirTo(CH("PLAYER"), Speed(350), ROT_TYPE.NEAR)
  CH("SAZANDORA_LARGE"):WaitRotate()
  CH("PARTNER"):DirTo(CH("SAZANDORA_LARGE"), Speed(350), ROT_TYPE.NEAR)
  local taskLookAt06 = function()
    TASK:Sleep(TimeSec(0.3))
    CH("BIRIJION"):DirTo(CH("PLAYER"), Speed(350), ROT_TYPE.NEAR)
    CH("KERUDYIO"):DirTo(CH("PLAYER"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("EMONGA"):DirTo(CH("PLAYER"), Speed(350), ROT_TYPE.NEAR)
    CH("EEFI"):DirTo(CH("PLAYER"), Speed(350), ROT_TYPE.NEAR)
    TASK:Sleep(TimeSec(0.1))
    CH("BURAKKII"):DirTo(CH("PLAYER"), Speed(350), ROT_TYPE.NEAR)
    CH("NOKOTCHI"):DirTo(CH("PLAYER"), Speed(350), ROT_TYPE.NEAR)
  end
  TASK:Regist(taskLookAt06)
  WINDOW:DrawFace(272, 16, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), -858397194)
  WINDOW:Talk(SymAct("SAZANDORA"), -707865417)
  WINDOW:Talk(SymAct("SAZANDORA"), -18643084)
  WINDOW:Talk(SymAct("SAZANDORA"), -403130827)
  subEveCloseMsg()
  TASK:Regist(subEveDoubleJump, {
    CH("NOKOTCHI")
  })
  CH("PLAYER"):DirTo(CH("NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.EMOTION)
  WINDOW:Talk(SymAct("NOKOTCHI"), -1464262414)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BURAKKII"), -1314778701)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_08"))
  CAMERA:SetTgt(SymCam("CAMERA_08"))
  TASK:Sleep(TimeSec(0.2))
  TASK:Regist(subEveNod, {
    CH("PLAYER")
  })
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1701887376, PARTNER_1 = -2087423183})
  WINDOW:SwitchTalk({PARTNER_0 = 67923966, PARTNER_1 = 488070847})
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(4))
  CAMERA:SetEye(SymCam("CAMERA_00_5"))
  CAMERA:SetTgt(SymCam("CAMERA_00_5"))
  TASK:Sleep(TimeSec(0.2))
  CH("EEFI"):SetManpu("MP_LAUGH_LP")
  TASK:Sleep(TimeSec(0.1))
  CH("SUWANNA"):SetManpu("MP_LAUGH_LP")
  CH("PLAYER"):SetManpu("MP_LAUGH_LP")
  TASK:Regist(subEveDoubleJump, {
    CH("EMONGA")
  })
  CH("EMONGA"):SetManpu("MP_SPREE_LP")
  TASK:Sleep(TimeSec(0.2))
  CH("KERUDYIO"):SetManpu("MP_LAUGH_LP")
  TASK:Sleep(TimeSec(0.1))
  CH("SAZANDORA_LARGE"):SetManpu("MP_SPREE_AL_LP")
  CH("BIRIJION"):SetManpu("MP_LAUGH_LP")
  TASK:Sleep(TimeSec(0.5))
  TASK:Regist(subEveDoubleJump, {
    CH("NOKOTCHI")
  })
  TASK:Sleep(TimeSec(1))
  SOUND:FadeOutBgm(TimeSec(2.5))
  SCREEN_A:FadeOut(TimeSec(1.5), true)
  SOUND:WaitBgm()
  TASK:Sleep(TimeSec(1.5))
  FLAG.SceneFlag = CONST.FL_SC_01_FIRST
  FLAG.SCENARIOFLAG = CONST.S1_SAZANDORANOHANASHI_END
  FLAG.StoryPlayerMode = CONST.ST_MODE_PARTNER
  FLAG.MapFlags = CONST.MAP_EVENT
  FLAG.FreePlay = CONST.FLAG_TRUE
  FLAG.TrigNextEvent = CONST.FLAG_FALSE
  SYSTEM:NextEntry()
end
function sub01_sazandoranohanashi02_end()
end
function groundEnd()
end

