dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
  if FLAG.EventIrai == CONST.FLAG_TRUE then
    FLAG.EventIrai = CONST.FLAG_FALSE
  end
end
function groundStart()
end
function main06_tsunorufuan01_init()
end
function main06_tsunorufuan01_start()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- CH("SUWANNA"):SetMotionBlendMode(BlendMode.NONE)
  -- CH("HIYAPPU"):SetMotionBlendMode(BlendMode.NONE)
  -- CH("KOARUHII"):SetMotionBlendMode(BlendMode.NONE)
  -- CH("HERO"):SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  -- CH("PARTNER"):SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  -- CH("HAADERIA"):SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  -- CH("WASHIBON"):SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  -- CH("BAOPPU"):SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  -- CH("YANAPPU"):SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  -- CH("MINEZUMI"):SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  -- local taskInuWashi = function()
  --   function TaskL.Loop()
  --     CH("HAADERIA"):SetMotion(SymMot("SPEAK"), LOOP.ON)
  --     TASK:Sleep(TimeSec(0.5))
  --     TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
  --     TASK:Sleep(TimeSec(0.5))
  --     CH("HAADERIA"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  --     TASK:Sleep(TimeSec(0.2))
  --     TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
  --     TASK:Sleep(TimeSec(0.2))
  --     TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
  --     TASK:Sleep(TimeSec(0.2))
  --   end
  --   function TaskL.Finish()
  --     CH("HAADERIA"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  --     CH("HAADERIA"):ResetManpu()
  --     return
  --   end
  -- end
  -- local taskSaru3 = function()
  --   function TaskL.Loop()
  --     TASK:Sleep(TimeSec(0.2))
  --     CH("BAOPPU"):SetManpu("MP_SPREE_LP")
  --     CH("BAOPPU"):SetMotion(SymMot("SPEAK"), LOOP.ON)
  --     TASK:Sleep(TimeSec(0.5))
  --     TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
  --     TASK:Sleep(TimeSec(0.5))
  --     CH("BAOPPU"):ResetManpu()
  --     CH("BAOPPU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  --     TASK:Sleep(TimeSec(0.2))
  --     CH("HIYAPPU"):SetManpu("MP_LAUGH_LP")
  --     TASK:Sleep(TimeSec(0.5))
  --     TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
  --     subEveNodDouble(CH("YANAPPU"))
  --     TASK:Sleep(TimeSec(0.2))
  --     CH("HIYAPPU"):ResetManpu()
  --     subEveDoubleJump(CH("BAOPPU"))
  --     TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
  --     TASK:Sleep(TimeSec(0.2))
  --   end
  -- end
  -- local taskAhiruNezumi = function()
  --   function TaskL.Loop()
  --     TASK:Sleep(TimeSec(0.1))
  --     CH("KOARUHII"):SetManpu("MP_LAUGH_LP")
  --     TASK:Sleep(TimeSec(1))
  --     CH("KOARUHII"):ResetManpu()
  --     TASK:Sleep(TimeSec(0.2))
  --     CH("MINEZUMI"):SetMotion(SymMot("SPEAK"), LOOP.ON)
  --     TASK:Sleep(TimeSec(2))
  --     CH("MINEZUMI"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  --     TASK:Sleep(TimeSec(0.5))
  --   end
  -- end
  -- TASK:Regist(Group("grpInuWashi"), taskInuWashi)
  -- TASK:Regist(Group("grpSaru3"), taskSaru3)
  -- TASK:Regist(Group("grpAhiruNezumi"), taskAhiruNezumi)
  -- SOUND:PlayBgm(SymSnd("BGM_MAP_TOWN_01"), Volume(256))
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- subEveFadeAfterTime()
  -- WINDOW:DrawFace(20, 20, SymAct("SUWANNA"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("SUWANNA"), -1115291074)
  -- WINDOW:CloseMessage()
  -- local lastPosHero = CH("HERO"):GetPosition2d()
  -- CH("HERO"):WalkTo(SymPos("P00_HERO"), Speed(1.2))
  -- CH("HERO"):WaitMove()
  -- SOUND:PlaySe(SymSnd("SE_ACT_MONEY"), Volume(256))
  -- TASK:Sleep(TimeSec(0.2))
  -- WINDOW:SysMsg(-1533201537)
  -- WINDOW:CloseMessage()
  -- CH("HERO"):WalkTo(lastPosHero, Speed(1.2), LINK_DIR.OFF)
  -- CH("HERO"):WaitMove()
  -- TASK:Sleep(TimeSec(0.3))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  -- CH("SUWANNA"):SetManpu("MP_NOTICE_R")
  -- CH("SUWANNA"):WaitManpu()
  -- WINDOW:DrawFace(20, 20, SymAct("SUWANNA"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("SUWANNA"), -1884266308)
  -- WINDOW:Talk(SymAct("SUWANNA"), -1767157251)
  -- WINDOW:CloseMessage()
  -- local lastDirHero = CH("HERO"):GetDir()
  -- CAMERA:MoveFollow(SymCam("CAMERA_01"), Speed(2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- CH("SUWANNA"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  -- CH("PARTNER"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.LEFT)
  -- TASK:Sleep(TimeSec(0.3))
  -- CH("HERO"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.LEFT)
  -- CAMERA:WaitMove()
  -- WINDOW:DrawFace(324, 20, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  -- WINDOW:SwitchTalk({PARTNER_0 = -638924998, PARTNER_1 = -1057884549})
  -- WINDOW:CloseMessage()
  -- CAMERA:MoveFollow(SymCam("CAMERA_00"), Speed(2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- CH("PARTNER"):DirTo(CH("SUWANNA"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("HERO"):DirTo(RotateTarget(lastDirHero), Speed(350), ROT_TYPE.NEAR)
  -- CH("PARTNER"):WaitRotate()
  -- CAMERA:WaitMove()
  -- WINDOW:DrawFace(20, 20, SymAct("SUWANNA"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("SUWANNA"), -337861192)
  -- WINDOW:Talk(SymAct("SUWANNA"), -221801223)
  -- WINDOW:Talk(SymAct("SUWANNA"), 1969195062)
  -- WINDOW:Talk(SymAct("SUWANNA"), 1816443255)
  -- subEveCloseMsg()
  -- TASK:ExitNotifyTasks(Group("grpInuWashi"))
  -- WINDOW:DrawFace(272, 16, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  -- WINDOW:SwitchTalk({PARTNER_0 = -1981250370, PARTNER_1 = -1863076353})
  -- subEveCloseMsg()
  -- SOUND:FadeOutBgm(TimeSec(2.5))
  -- WINDOW:DrawFace(20, 20, SymAct("SUWANNA"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("SUWANNA"), -1143019972)
  -- WINDOW:Talk(SymAct("SUWANNA"), -1564092547)
  -- WINDOW:Talk(SymAct("SUWANNA"), -310099526)
  -- WINDOW:Talk(SymAct("SUWANNA"), -190877445)
  -- subEveCloseMsg()
  -- CH("HAADERIA"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  -- CH("HAADERIA"):WaitRotate()
  -- WINDOW:DrawFace(324, 88, SymAct("HAADERIA"), FACE_TYPE.SAD)
  -- WINDOW:Talk(SymAct("HAADERIA"), -541973704)
  -- WINDOW:CloseMessage()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  -- CH("PARTNER"):SetManpu("MP_NOTICE_L")
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("SUWANNA"):SetManpu("MP_NOTICE_R")
  -- CAMERA:MoveFollow(SymCam("CAMERA_02"), Speed(2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- CH("HERO"):DirTo(CH("HAADERIA"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("SUWANNA"):DirTo(CH("HAADERIA"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("PARTNER"):DirTo(CH("HAADERIA"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("WASHIBON"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  -- CH("PARTNER"):WaitRotate()
  -- CAMERA:WaitMove()
  -- WINDOW:DrawFace(324, 88, SymAct("HAADERIA"), FACE_TYPE.SAD)
  -- WINDOW:Talk(SymAct("HAADERIA"), -961998215)
  -- WINDOW:Talk(SymAct("HAADERIA"), 1093734070)
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(324, 20, SymAct("WASHIBON"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("WASHIBON"), 1479163895)
  -- WINDOW:CloseMessage()
  -- CH("HERO"):DirTo(CH("WASHIBON"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("PARTNER"):DirTo(CH("WASHIBON"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("HAADERIA"):DirTo(CH("WASHIBON"), Speed(350), ROT_TYPE.NEAR)
  -- SOUND:PlayBgm(SymSnd("BGM_EVE_OKUSOKO_01"), Volume(256))
  -- WINDOW:DrawFace(324, 20, SymAct("WASHIBON"), FACE_TYPE.SAD)
  -- WINDOW:Talk(SymAct("WASHIBON"), -1688392880)
  -- WINDOW:Talk(SymAct("WASHIBON"), -2109335023)
  -- WINDOW:Talk(SymAct("WASHIBON"), -1452586542)
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(72, 16, SymAct("HERO"), FACE_TYPE.THINK)
  -- WINDOW:Monologue(-1334806381)
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(324, 88, SymAct("HAADERIA"), FACE_TYPE.SAD)
  -- WINDOW:Talk(SymAct("HAADERIA"), -13504940)
  -- CH("WASHIBON"):DirTo(CH("HAADERIA"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("HERO"):DirTo(CH("HAADERIA"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("PARTNER"):DirTo(CH("HAADERIA"), Speed(350), ROT_TYPE.NEAR)
  -- WINDOW:Talk(SymAct("HAADERIA"), -433397995)
  -- WINDOW:Talk(SymAct("HAADERIA"), -855143210)
  -- WINDOW:Talk(SymAct("HAADERIA"), -736313961)
  -- WINDOW:Talk(SymAct("HAADERIA"), 1401200984)
  -- WINDOW:Talk(SymAct("HAADERIA"), 1251971097)
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(324, 20, SymAct("WASHIBON"), FACE_TYPE.SAD)
  -- WINDOW:Talk(SymAct("WASHIBON"), 601967669)
  -- WINDOW:Talk(SymAct("WASHIBON"), 989494644)
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(72, 16, SymAct("HERO"), FACE_TYPE.THINK)
  -- WINDOW:Monologue(299314871)
  -- WINDOW:CloseMessage()
  -- SOUND:FadeOutBgm(TimeSec(2))
  -- SCREEN_A:FadeOut(TimeSec(1), true)
  -- subEveFadeAfterTime()
  -- CAMERA:ResetAzimuthDifferenceVolume()
  -- SOUND:WaitBgm()
  FLAG.SceneFlag = CONST.FL_SC_01_END
  FLAG.SCENARIOFLAG = CONST.M06_TSUNORUFUAN_START
  SYSTEM:NextEntry()
end
function main06_tsunorufuan01_end()
end
function main06_tsunorufuan02_init()
end
function main06_tsunorufuan02_start()
  GIMMICK:SetVisible(SymLayer("SHOP_CHEST"), false)
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("PARTNER"):SetPosition(SymPos("P00_PARTNER"))
  CH("HERO"):SetPosition(SymPos("P00_HERO"))
  CH("HERO"):SetDir(RotateTarget(-45))
  CH("PARTNER"):SetDir(RotateTarget(135))

  -- CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(1.5))
  -- CH("HERO"):WalkTo(SymPos("P00_HERO"), Speed(1.5))
  -- SOUND:FadeInEnv(SymSnd("SE_ENV_CROSSROAD_LP"), TimeSec(0.5), Volume(256))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- CH("HERO"):WaitMove()
  -- CH("HERO"):DirTo(RotateTarget(-45), Speed(350), ROT_TYPE.NEAR)
  -- CH("PARTNER"):WaitMove()
  -- CH("PARTNER"):DirTo(RotateTarget(135), Speed(350), ROT_TYPE.NEAR)
  -- CH("PARTNER"):WaitRotate()
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.THINK)
  -- WINDOW:SwitchTalk({PARTNER_0 = 147595254, PARTNER_1 = 1200458033})
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  -- WINDOW:SwitchTalk({PARTNER_0 = 1586935920, PARTNER_1 = 1975249843})
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.THINK)
  -- WINDOW:Monologue(1822481138)
  -- WINDOW:Monologue(-348600771)
  -- WINDOW:Monologue(-232523908)
  -- WINDOW:Monologue(-1103727476)
  -- WINDOW:Monologue(-1490205235)
  -- subEveCloseMsg()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  -- CH("PARTNER"):SetManpu("MP_QUESTION")
  -- CH("PARTNER"):WaitManpu()
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  -- WINDOW:SwitchTalk({PARTNER_0 = -1946151410, PARTNER_1 = -1793382577})
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.NORMAL)
  -- WINDOW:Monologue(-631590520)
  -- WINDOW:Monologue(-1019117367)
  -- WINDOW:CloseMessage()
  -- subEveNod(CH("HERO"))
  -- CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  -- TASK:Regist(subEveJump, {
  --   CH("PARTNER")
  -- })
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.HAPPY)
  -- WINDOW:SwitchTalk({PARTNER_0 = -395521270, PARTNER_1 = -243801525})
  -- WINDOW:SwitchTalk({PARTNER_0 = 1995439748, PARTNER_1 = 1878314949})
  -- WINDOW:CloseMessage()
  -- CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  -- subEveNod(CH("HERO"))
  -- SOUND:FadeOutEnv(TimeSec(1))
  CAMERA:MoveToHero(Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  FLAG.SceneFlag = CONST.FL_SC_01_FIRST
  FLAG.SCENARIOFLAG = CONST.M06_TSUNORUFUAN_END
  FLAG.MapFlags = CONST.MAP_EVENT
  FLAG.FreePlay = CONST.FLAG_TRUE
  FLAG.TrigNextEvent = CONST.FLAG_FALSE
  SYSTEM:NextEntry(KEEP_PLACEMENT.ON)
end
function main06_tsunorufuan02_end()
end
function groundEnd()
end

