dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main18_hyoushokutai01boss1st01_init()
end
function main18_hyoushokutai01boss1st01_start()
  subEveFromProgFadeSet()
  -- TASK:Sleep(TimeSec(1))
  -- EFFECT:Create("effect01", SymEff("EV_EDDY_WIND_BOSS_LP"))
  -- EFFECT:SetPosition("effect01", SymPos("P01_EFFECT"))
  -- EFFECT:Play("effect01")
  -- EFFECT:Create("effect02", SymEff("BG_FRAME_SMOKE_LP"))
  -- EFFECT:SetPosition("effect02", SymPos("P02_EFFECT"))
  -- EFFECT:Play("effect02")
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- SOUND:FadeInEnv(SymSnd("SE_EVT_HYOUSHOKU_AURA_LP"), TimeSec(0.5), Volume(256))
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- TASK:Sleep(TimeSec(1.5))
  -- SCREEN_A:FadeOut(TimeSec(1), true)
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  -- CAMERA:SetEye(SymCam("CAMERA_00_5"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00_5"))
  -- SCREEN_A:FadeIn(TimeSec(1), true)
  -- TASK:Sleep(TimeSec(1.5))
  -- SCREEN_A:FadeOut(TimeSec(1), true)
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  -- CAMERA:SetEye(SymCam("CAMERA_01"))
  -- CAMERA:SetTgt(SymCam("CAMERA_01"))
  -- CAMERA:MoveFollow(SymCam("CAMERA_01_5"), Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- TASK:Sleep(TimeSec(0.5))
  -- SCREEN_A:FadeIn(TimeSec(1), true)
  -- TASK:Sleep(TimeSec(2))
  -- SCREEN_A:FadeOut(TimeSec(1), true)
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_02"))
  -- CAMERA:SetTgt(SymCam("CAMERA_02"))
  -- CAMERA:MoveFollow2(SymCam("CAMERA_02_5"), Speed(3.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- TASK:Sleep(TimeSec(0.5))
  -- SCREEN_A:FadeIn(TimeSec(1), true)
  -- CAMERA:WaitMove()
  -- TASK:Sleep(TimeSec(1.8))
  -- SCREEN_A:FadeOut(TimeSec(0.5), true)
  FLAG.SceneFlag = CONST.FL_SC_01_END
  FLAG.SCENARIOFLAG = CONST.M18_HYOUSHOKUTAI01BOSS1ST_START
  SYSTEM:NextEntry()
end
function main18_hyoushokutai01boss1st01_end()
end
function main18_hyoushokutai01boss1st02_init()
end
function main18_hyoushokutai01boss1st02_start()
  -- SOUND:PlayEnv(SymSnd("SE_EVT_HYOUSHOKU_AURA_LP"), Volume(256))
  -- CH("HERO"):SetShadow(false)
  -- CH("PARTNER"):SetShadow(false)
  -- CH("HERO"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  -- CH("PARTNER"):SetMotion(SymMot("BATTLE"), LOOP.ON)
  -- EFFECT:Create("effect01", SymEff("EV_EDDY_WIND_BOSS_LP"))
  -- EFFECT:SetPosition("effect01", SymPos("P01_EFFECT"))
  -- EFFECT:Play("effect01")
  -- EFFECT:Create("effect02", SymEff("BG_FRAME_SMOKE_LP"))
  -- EFFECT:SetPosition("effect02", SymPos("P02_EFFECT"))
  -- EFFECT:Play("effect02")
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- CAMERA:MoveFollow2(SymCam("CAMERA_01"), Speed(4.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- TASK:Sleep(TimeSec(0.5))
  -- SOUND:VolumeEnv(Volume(128), TimeSec(1))
  -- SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_DESPAIR_HV2"), Volume(256))
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- CAMERA:WaitMove()
  -- TASK:Sleep(TimeSec(0.8))
  -- WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SPECIAL03)
  -- WINDOW:Monologue(-2077598173)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  -- CAMERA:SetEye(SymCam("CAMERA_02"))
  -- CAMERA:SetTgt(SymCam("CAMERA_02"))
  -- CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.DAMAGE)
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.PAIN)
  -- WINDOW:SwitchTalk({PARTNER_0 = -1657704606, PARTNER_1 = -1239663455})
  -- WINDOW:CloseMessage()
  -- CH("PARTNER"):SetMotion(SymMot("EV011_KNEEATTACHE00"), LOOP.OFF)
  -- CH("PARTNER"):WaitPlayMotion()
  -- CH("PARTNER"):SetMotion(SymMot("EV011_KNEEATTACHE01"), LOOP.ON)
  -- CH("HERO"):DirTo(CH("PARTNER"), Speed(500), ROT_TYPE.NEAR)
  -- CH("HERO"):WaitRotate()
  -- TASK:Sleep(TimeSec(0.3))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  -- CH("HERO"):SetManpu("MP_SHOCK_L")
  -- SOUND:PlaySe(SymSnd("SE_EVT_DOGA"), Volume(128))
  -- CH("PARTNER"):SetMotion(SymMot("EV011_KNEEATTACHE02"), LOOP.OFF)
  -- CH("PARTNER"):WaitPlayMotion()
  -- CH("PARTNER"):SetMotion(SymMot("EV018_KNEEATTACHE00"), LOOP.ON)
  -- WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  -- WINDOW:Monologue(-1358492192)
  -- WINDOW:CloseMessage()
  -- CH("HERO"):WalkTo(SymPos("P00_HERO"), Speed(1.5))
  -- CH("HERO"):WaitMove()
  -- TASK:Sleep(TimeSec(0.5))
  -- WINDOW:Talk(SymAct("KYUREMU"), -532243673)
  -- WINDOW:Talk(SymAct("KYUREMU"), -111302042)
  -- WINDOW:CloseMessage()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  -- CH("HERO"):SetManpu("MP_EXCLAMATION")
  -- CH("HERO"):WaitManpu()
  -- CH("HERO"):DirTo(RotateTarget(0), Speed(500), ROT_TYPE.NEAR)
  -- CH("HERO"):WaitRotate()
  -- WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  -- WINDOW:Monologue(-764347995)
  -- WINDOW:CloseMessage()
  -- SCREEN_A:FadeOut(TimeSec(0.5), true)
  FLAG.SceneFlag = CONST.FL_SC_02_END
  FLAG.SCENARIOFLAG = CONST.M18_HYOUSHOKUTAI01BOSS1ST_START
  SYSTEM:NextEntry()
end
function main18_hyoushokutai01boss1st02_end()
end
function main18_hyoushokutai01boss1st03_init()
end
function main18_hyoushokutai01boss1st03_start()
  -- SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_DESPAIR_HV2"), Volume(256))
  -- SOUND:PlayEnv(SymSnd("SE_EVT_HYOUSHOKU_AURA_LP"), Volume(128))
  -- CH("KYUREMU"):SetMotion(SymMot("DOWNLOOP"), LOOP.ON, TimeSec(0))
  -- CH("KYUREMU"):SetShadow(false)
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- CAMERA:MoveFollow2(SymCam("CAMERA_00_5"), Speed(0.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- TASK:Sleep(TimeSec(0.5))
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- WINDOW:Talk(SymAct("KYUREMU"), -882128668)
  -- WINDOW:Talk(SymAct("KYUREMU"), 1291047979)
  -- subEveCloseMsg()
  -- WINDOW:Monologue(1441326442)
  -- subEveCloseMsg()
  -- WINDOW:Talk(SymAct("KYUREMU"), 341429457)
  -- WINDOW:Talk(SymAct("KYUREMU"), 222494096)
  -- WINDOW:Talk(SymAct("KYUREMU"), 644853331)
  -- WINDOW:Talk(SymAct("KYUREMU"), 1064607506)
  -- WINDOW:CloseMessage()
  -- SCREEN_A:FadeOut(TimeSec(0.5), true)
  FLAG.SceneFlag = CONST.FL_SC_03_END
  FLAG.SCENARIOFLAG = CONST.M18_HYOUSHOKUTAI01BOSS1ST_START
  SYSTEM:NextEntry()
end
function main18_hyoushokutai01boss1st03_end()
end
function main18_hyoushokutai01boss1st04_init()
end
function main18_hyoushokutai01boss1st04_start()
  -- SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_DESPAIR_HV2"), Volume(256))
  -- SOUND:PlayEnv(SymSnd("SE_EVT_HYOUSHOKU_AURA_LP"), Volume(128))
  -- CH("HERO"):SetShadow(false)
  -- CH("PARTNER"):SetShadow(false)
  -- local pokemonIndexPartner = SymAct("PARTNER"):GetIndex()
  -- if pokemonIndexPartner == 42 then
  --   CH("PARTNER"):SetPosition(SymPos("P00_PARTNER_POKABU"))
  -- elseif pokemonIndexPartner == 122 then
  --   CH("PARTNER"):SetPosition(SymPos("P00_PARTNER_POKABU"))
  -- end
  -- CH("PARTNER"):SetMotion(SymMot("EV018_KNEEATTACHE00"), LOOP.ON, TimeSec(0))
  -- EFFECT:Create("effect01", SymEff("EV_EDDY_WIND_BOSS_LP"))
  -- EFFECT:SetPosition("effect01", SymPos("P01_EFFECT"))
  -- EFFECT:Play("effect01")
  -- EFFECT:Create("effect03", SymEff("BG_FRAME_SMOKE_LP"))
  -- EFFECT:SetPosition("effect03", SymPos("P03_EFFECT"))
  -- EFFECT:Play("effect03")
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- WINDOW:Talk(SymAct("KYUREMU"), 1882524117)
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SPECIAL03)
  -- WINDOW:Monologue(1764636820)
  -- WINDOW:CloseMessage()
  -- CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  -- CH("HERO"):WaitRotate()
  -- WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.SPECIAL03)
  -- WINDOW:Monologue(1107520343)
  -- WINDOW:Monologue(1528322582)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2.5))
  -- CAMERA:SetEye(SymCam("CAMERA_01"))
  -- CAMERA:SetTgt(SymCam("CAMERA_01"))
  -- CH("PARTNER"):SetShake(Vector(0.005, 0, 0), TimeSec(0.1, TIME_TYPE.FRAME))
  -- TASK:Sleep(TimeSec(0.5))
  -- CH("PARTNER"):ResetShake()
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.PAIN)
  -- WINDOW:SwitchTalk({PARTNER_0 = -595573031, PARTNER_1 = -979667048})
  -- WINDOW:SwitchTalk({PARTNER_0 = 116155199, PARTNER_1 = 536302206})
  -- WINDOW:SwitchTalk({PARTNER_0 = 886702525, PARTNER_1 = 767635708})
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  -- CAMERA:SetEye(SymCam("CAMERA_02"))
  -- CAMERA:SetTgt(SymCam("CAMERA_02"))
  -- subEveNod(CH("HERO"))
  -- CH("HERO"):DirTo(RotateTarget(180), Speed(200), ROT_TYPE.NEAR)
  -- CH("HERO"):WaitRotate()
  -- TASK:Sleep(TimeSec(0.3))
  -- CH("HERO"):RunTo(SymPos("P00_HERO"), Speed(1))
  -- CH("HERO"):WaitMove()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  -- CH("HERO"):SetManpu("MP_SHOCK_R")
  -- CH("HERO"):SetMotion(SymMot("EV011_KNEEATTACHE00"), LOOP.OFF)
  -- CH("HERO"):WaitPlayMotion()
  -- CH("HERO"):SetMotion(SymMot("EV011_KNEEATTACHE01"), LOOP.ON)
  -- WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SPECIAL03)
  -- WINDOW:Monologue(1652598331)
  -- WINDOW:Monologue(2073794426)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  -- CAMERA:SetEye(SymCam("CAMERA_03"))
  -- CAMERA:SetTgt(SymCam("CAMERA_03"))
  -- TASK:Sleep(TimeSec(0.3))
  -- WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.PAIN)
  -- WINDOW:Monologue(1354155193)
  -- WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SPECIAL03)
  -- WINDOW:Monologue(1236137464)
  -- WINDOW:Monologue(-835327689)
  -- WINDOW:CloseMessage()
  -- CAMERA:MoveFollow(SymCam("CAMERA_04_1"), Speed(0.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- CH("HERO"):SetMotion(SymMot("EV018_LIES01"), LOOP.ON)
  -- CH("HERO"):MoveTo(SymPos("P01_1_HERO"), Speed(0.5))
  -- CH("HERO"):WaitMove()
  -- CH("HERO"):SetMotion(SymMot("EV011_KNEEATTACHE00"), LOOP.OFF)
  -- CH("HERO"):WaitPlayMotion()
  -- CH("HERO"):SetMotion(SymMot("EV011_KNEEATTACHE01"), LOOP.ON)
  -- WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.PAIN)
  -- WINDOW:Monologue(-684795786)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  -- CAMERA:SetEye(SymCam("CAMERA_04_2"))
  -- CAMERA:SetTgt(SymCam("CAMERA_04_2"))
  -- EFFECT:Create("effect02", SymEff("EV_WIND_DESPAIR_LP"))
  -- EFFECT:SetPosition("effect02", SymPos("P02_EFFECT"))
  -- EFFECT:Play("effect02")
  -- SOUND:PlaySe(SymSnd("SE_EVT_HYOUSHOKU_WIND_01"), Volume(256))
  -- CAMERA:SetShake(Vector2(0.01, 0.01), TimeSec(1, TIME_TYPE.FRAME))
  -- CH("HERO"):SetMotion(SymMot("EV018_LIES00"), LOOP.OFF)
  -- CH("HERO"):WaitPlayMotion()
  -- CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  -- CH("HERO"):SetMotion(SymMot("EV018_LIES00LOOP"), LOOP.ON)
  -- WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SPECIAL03)
  -- WINDOW:Monologue(-1102052262)
  -- WINDOW:Monologue(-1488243429)
  -- WINDOW:Monologue(-1939446056)
  -- WINDOW:Monologue(-1786947687)
  -- WINDOW:Monologue(-633552546)
  -- WINDOW:Monologue(-1020792801)
  -- WINDOW:Monologue(-401955876)
  -- WINDOW:CloseMessage()
  -- CH("HERO"):SetMotion(SymMot("EV011_KNEEATTACHE00"), LOOP.OFF)
  -- CH("HERO"):WaitPlayMotion()
  -- CH("HERO"):SetMotion(SymMot("EV011_KNEEATTACHE01"), LOOP.ON)
  -- TASK:Sleep(TimeSec(0.5))
  -- SOUND:FadeOutSe(SymSnd("SE_EVT_HYOUSHOKU_WIND_01"), TimeSec(0.2))
  -- SOUND:FadeOutBgm(TimeSec(0.2))
  -- SOUND:FadeOutEnv(TimeSec(0.2))
  -- SCREEN_A:FadeOut(TimeSec(0.3), true)
  -- SOUND:PlaySe(SymSnd("SE_EVT_ALL_VOICE"), Volume(128))
  -- WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), -250506595)
  -- WINDOW:CloseMessage()
  -- SOUND:FadeInEnv(SymSnd("SE_EVT_HYOUSHOKU_AURA_LP"), TimeSec(0.5), Volume(128))
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  -- CH("HERO"):SetManpu("MP_EXCLAMATION")
  -- CH("HERO"):WaitManpu()
  -- SOUND:PlaySe(SymSnd("SE_EVT_HYOUSHOKU_WIND_01"), Volume(256))
  -- CAMERA:SetShake(Vector2(0.01, 0.01), TimeSec(1, TIME_TYPE.FRAME))
  -- CH("HERO"):SetMotion(SymMot("EV018_LIES00"), LOOP.OFF)
  -- CH("HERO"):WaitPlayMotion()
  -- CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  -- CH("HERO"):SetMotion(SymMot("EV018_LIES00LOOP"), LOOP.ON)
  -- WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SPECIAL03)
  -- WINDOW:Monologue(1988726354)
  -- WINDOW:Monologue(1871888147)
  -- WINDOW:CloseMessage()
  -- TASK:Sleep(TimeSec(0.5))
  -- SOUND:FadeOutSe(SymSnd("SE_EVT_HYOUSHOKU_WIND_01"), TimeSec(0.2))
  -- SOUND:FadeOutEnv(TimeSec(0.2))
  -- SCREEN_A:FadeOut(TimeSec(0.3), true)
  -- SOUND:PlaySe(SymSnd("SE_EVT_ALL_VOICE"), Volume(128))
  -- WINDOW:Narration(TimeSec(0.3), TimeSec(0.3), 596065507)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  -- CAMERA:SetEye(SymCam("CAMERA_04_1"))
  -- CAMERA:SetTgt(SymCam("CAMERA_04_1"))
  -- SOUND:PlayEnv(SymSnd("SE_EVT_HYOUSHOKU_AURA_LP"), Volume(64))
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_01"), Volume(256))
  -- CH("HERO"):SetManpu("MP_EXCLAMATION")
  -- CH("HERO"):WaitManpu()
  -- CAMERA:SetShake(Vector2(0.01, 0.01), TimeSec(1, TIME_TYPE.FRAME))
  -- CH("HERO"):SetMotion(SymMot("EV018_LIES00"), LOOP.OFF)
  -- CH("HERO"):WaitPlayMotion()
  -- CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  -- CH("HERO"):SetMotion(SymMot("EV018_LIES00LOOP"), LOOP.ON)
  -- SOUND:FadeInBgm(SymSnd("BGM_EVE_GANBARE_INTRO"), TimeSec(3), Volume(256))
  -- WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SPECIAL03)
  -- WINDOW:Monologue(983305634)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetEye(SymCam("CAMERA_05"))
  -- CAMERA:SetTgt(SymCam("CAMERA_05"))
  -- TASK:Sleep(TimeSec(0.5))
  -- WINDOW:Explanation(296836705)
  -- WINDOW:CloseMessage()
  -- CH("PARTNER"):SetShake(Vector(0.005, 0, 0), TimeSec(0.1, TIME_TYPE.FRAME))
  -- TASK:Sleep(TimeSec(0.5))
  -- CH("PARTNER"):ResetShake()
  -- WINDOW:SwitchTalk({PARTNER_0 = 145387296, PARTNER_1 = 1206647271})
  -- WINDOW:CloseMessage()
  -- SOUND:FadeOutEnv(TimeSec(1))
  -- SCREEN_A:FadeOut(TimeSec(0.5), true)
  FLAG.SceneFlag = CONST.FL_SC_04_END
  FLAG.SCENARIOFLAG = CONST.M18_HYOUSHOKUTAI01BOSS1ST_START
  SYSTEM:NextEntry()
end
function main18_hyoushokutai01boss1st04_end()
end
function main18_hyoushokutai01boss1st05_init()
end
function main18_hyoushokutai01boss1st05_start()
  -- SOUND:PlayBgm(SymSnd("BGM_EVE_GANBARE_INTRO"), Volume(256))
  -- CH("KYUREMU"):SetMotion(SymMot("DOWNLOOP"), LOOP.ON, TimeSec(0))
  -- CH("KYUREMU"):SetShadow(false)
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetFovy(SymCam("CAMERA_00"))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- WINDOW:ExplanationB(1592838310)
  -- WINDOW:CloseMessage()
  -- WINDOW:Talk(SymAct("KYUREMU"), 1977457509)
  -- WINDOW:CloseMessage()
  -- SCREEN_A:FadeOut(TimeSec(0.3), true)
  -- TASK:Sleep(TimeSec(0.3))
  -- WINDOW:Explanation(1824959012)
  -- WINDOW:CloseMessage()
  FLAG.SceneFlag = CONST.FL_SC_05_END
  FLAG.SCENARIOFLAG = CONST.M18_HYOUSHOKUTAI01BOSS1ST_START
  SYSTEM:NextEntry()
end
function main18_hyoushokutai01boss1st05_end()
end
function main18_hyoushokutai01boss1st06_init()
end
function main18_hyoushokutai01boss1st06_start()
  -- SOUND:PlayBgm(SymSnd("BGM_EVE_GANBARE_INTRO"), Volume(256))
  -- CH("HERO"):SetShadow(false)
  -- CH("PARTNER"):SetShadow(false)
  -- CH("PARTNER"):SetMotion(SymMot("EV018_KNEEATTACHE00"), LOOP.ON, TimeSec(0))
  -- CH("HERO"):SetMotion(SymMot("EV011_KNEEATTACHE01"), LOOP.ON, TimeSec(0))
  -- EFFECT:Create("effect01", SymEff("EV_EDDY_WIND_BOSS_LP"))
  -- EFFECT:SetPosition("effect01", SymPos("P01_EFFECT"))
  -- EFFECT:Play("effect01")
  -- EFFECT:Create("effect02", SymEff("EV_WIND_DESPAIR_LP"))
  -- EFFECT:SetPosition("effect02", SymPos("P02_EFFECT"))
  -- EFFECT:Play("effect02")
  -- EFFECT:Create("effect03", SymEff("BG_FRAME_SMOKE_LP"))
  -- EFFECT:SetPosition("effect03", SymPos("P03_EFFECT"))
  -- EFFECT:Play("effect03")
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- SOUND:PlayEnv(SymSnd("SE_EVT_HYOUSHOKU_AURA_LP"), Volume(64))
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- SOUND:PlaySe(SymSnd("SE_EVT_HYOUSHOKU_WIND_01"), Volume(190))
  -- CAMERA:SetShake(Vector2(0.01, 0.01), TimeSec(1, TIME_TYPE.FRAME))
  -- CH("HERO"):SetMotion(SymMot("EV018_LIES00"), LOOP.OFF)
  -- CH("HERO"):WaitPlayMotion()
  -- CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  -- CH("HERO"):SetMotion(SymMot("EV018_LIES00LOOP"), LOOP.ON)
  -- WINDOW:Explanation(-346114325)
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SPECIAL03)
  -- WINDOW:Monologue(-230324310)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  -- CAMERA:SetEye(SymCam("CAMERA_01"))
  -- CAMERA:SetTgt(SymCam("CAMERA_01"))
  -- WINDOW:Explanation(-1690608762)
  -- WINDOW:Explanation(-2111804729)
  -- WINDOW:CloseMessage()
  -- EFFECT:Remove("effect02")
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  -- CH("HERO"):SetManpu("MP_EXCLAMATION")
  -- CH("HERO"):WaitManpu()
  -- WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  -- WINDOW:Monologue(-1458751228)
  -- subEveCloseMsg()
  -- WINDOW:Explanation(-1340733371)
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  -- WINDOW:Monologue(-11035006)
  -- WINDOW:CloseMessage()
  -- SOUND:FadeOutBgm(TimeSec(3))
  -- SOUND:FadeOutEnv(TimeSec(1))
  -- SCREEN_A:FadeOut(TimeSec(0.5), true)
  FLAG.SceneFlag = CONST.FL_SC_06_END
  FLAG.SCENARIOFLAG = CONST.M18_HYOUSHOKUTAI01BOSS1ST_START
  SYSTEM:NextEntry()
end
function main18_hyoushokutai01boss1st06_end()
end
function main18_hyoushokutai01boss1st07_init()
end
function main18_hyoushokutai01boss1st07_start()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(6))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- EFFECT:Create("effect01", SymEff("EV_EDDY_BIG_LP"))
  -- EFFECT:SetPosition("effect01", SymPos("P01_EFFECT"))
  -- EFFECT:Play("effect01")
  -- SOUND:PlayEnv(SymSnd("SE_EVT_EARTHQUAKE_M_LP"), Volume(64))
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- WINDOW:ExplanationB(-431181885)
  -- WINDOW:ExplanationB(-849216512)
  -- WINDOW:CloseMessage()
  -- SOUND:FadeOutEnv(TimeSec(1))
  -- SCREEN_A:FadeOut(TimeSec(0.5), true)
  FLAG.SceneFlag = CONST.FL_SC_07_END
  FLAG.SCENARIOFLAG = CONST.M18_HYOUSHOKUTAI01BOSS1ST_START
  SYSTEM:NextEntry()
end
function main18_hyoushokutai01boss1st07_end()
end
function main18_hyoushokutai01boss1st08_init()
end
function main18_hyoushokutai01boss1st08_start()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- CHARA:SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  -- SOUND:PlayBgm(SymSnd("BGM_EVE_GANBARE"), Volume(256))
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- WINDOW:ExplanationB(-730149567)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetEye(SymCam("CAMERA_01"))
  -- CAMERA:SetTgt(SymCam("CAMERA_01"))
  -- CH("NOKOTCHI"):WalkTo(SymPos("P01_NOKOTCHI"), Speed(1.2))
  -- CH("NOKOTCHI"):WaitMove()
  -- WINDOW:SysMsg(1407373710)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetEye(SymCam("CAMERA_02"))
  -- CAMERA:SetTgt(SymCam("CAMERA_02"))
  -- CH("NUOO"):WalkTo(SymPos("P01_NUOO"), Speed(1.2))
  -- CH("NUOO"):WaitMove()
  -- WINDOW:SysMsg(1257889999)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetEye(SymCam("CAMERA_03"))
  -- CAMERA:SetTgt(SymCam("CAMERA_03"))
  -- CH("YOOTERII"):WalkTo(SymPos("P01_YOOTERII"), Speed(1.2))
  -- CH("YOOTERII"):WaitMove()
  -- WINDOW:SysMsg(-1987120024)
  -- WINDOW:CloseMessage()
  -- CH("HAADERIA"):WalkTo(SymPos("P01_HAADERIA"), Speed(1.2))
  -- CH("HAADERIA"):WaitMove()
  -- WINDOW:SysMsg(-1869232855)
  -- WINDOW:CloseMessage()
  -- SCREEN_A:FadeOut(TimeSec(0.5), true)
  FLAG.SceneFlag = CONST.FL_SC_08_END
  FLAG.SCENARIOFLAG = CONST.M18_HYOUSHOKUTAI01BOSS1ST_START
  SYSTEM:NextEntry()
end
function main18_hyoushokutai01boss1st08_end()
end
function main18_hyoushokutai01boss1st09_init()
end
function main18_hyoushokutai01boss1st09_start()
  -- CHARA:SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  -- SOUND:PlayBgm(SymSnd("BGM_EVE_GANBARE"), Volume(256))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- WINDOW:ExplanationB(-1145530646)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetEye(SymCam("CAMERA_01"))
  -- CAMERA:SetTgt(SymCam("CAMERA_01"))
  -- CH("SUWANNA"):WalkTo(SymPos("P01_SUWANNA"), Speed(1.2))
  -- CH("SUWANNA"):WaitMove()
  -- WINDOW:SysMsg(-1566333013)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetEye(SymCam("CAMERA_02"))
  -- CAMERA:SetTgt(SymCam("CAMERA_02"))
  -- CH("DOTEKKOTSU"):WalkTo(SymPos("P01_DOTEKKOTSU"), Speed(1.2))
  -- CH("DOTEKKOTSU"):WaitMove()
  -- WINDOW:SysMsg(-303943316)
  -- WINDOW:CloseMessage()
  -- CH("DOKKORAA_1"):WalkTo(SymPos("P01_DOKKORAA_1"), Speed(1.2))
  -- CH("DOKKORAA_1"):WaitMove()
  -- WINDOW:SysMsg(-185008083)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetEye(SymCam("CAMERA_03"))
  -- CAMERA:SetTgt(SymCam("CAMERA_03"))
  -- CH("BIKUTYINI"):SetMotion(SymMot("EV004_PEACE01"), LOOP.OFF)
  -- CH("BIKUTYINI"):WaitPlayMotion()
  -- WINDOW:SysMsg(-539733010)
  -- WINDOW:CloseMessage()
  -- SCREEN_A:FadeOut(TimeSec(0.5), true)
  FLAG.SceneFlag = CONST.FL_SC_09_END
  FLAG.SCENARIOFLAG = CONST.M18_HYOUSHOKUTAI01BOSS1ST_START
  SYSTEM:NextEntry()
end
function main18_hyoushokutai01boss1st09_end()
end
function main18_hyoushokutai01boss1st10_init()
end
function main18_hyoushokutai01boss1st10_start()
  -- CHARA:SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  -- SOUND:PlayBgm(SymSnd("BGM_EVE_GANBARE"), Volume(256))
  -- CH("MUNNA_ZERO"):SetMotion(SymMot("EV013_DOWN00"), LOOP.ON, TimeSec(0))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- TASK:Sleep(TimeSec(0.8))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  -- CAMERA:SetEye(SymCam("CAMERA_01"))
  -- CAMERA:SetTgt(SymCam("CAMERA_01"))
  -- CH("EMONGA"):WalkTo(SymPos("P01_EMONGA"), Speed(1.2))
  -- CH("EMONGA"):WaitMove()
  -- WINDOW:SysMsg(-959487313)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2.5))
  -- CAMERA:SetEye(SymCam("CAMERA_02"))
  -- CAMERA:SetTgt(SymCam("CAMERA_02"))
  -- CH("BURAKKII"):WalkTo(SymPos("P01_BURAKKII"), Speed(1.2))
  -- CH("BURAKKII"):WaitMove()
  -- WINDOW:SysMsg(1096253024)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2.5))
  -- CAMERA:SetEye(SymCam("CAMERA_02_1"))
  -- CAMERA:SetTgt(SymCam("CAMERA_02_1"))
  -- CH("EEFI"):WalkTo(SymPos("P01_EEFI"), Speed(1.2))
  -- CH("EEFI"):WaitMove()
  -- WINDOW:SysMsg(1481396001)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2.5))
  -- CAMERA:SetEye(SymCam("CAMERA_03"))
  -- CAMERA:SetTgt(SymCam("CAMERA_03"))
  -- CH("BIRIJION"):WalkTo(SymPos("P01_BIRIJION"), Speed(1.2))
  -- CH("BIRIJION"):WaitMove()
  -- WINDOW:SysMsg(825398029)
  -- WINDOW:CloseMessage()
  -- CH("KERUDYIO"):WalkTo(SymPos("P01_KERUDYIO"), Speed(1.2))
  -- CH("KERUDYIO"):WaitMove()
  -- WINDOW:SysMsg(673817164)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1.5))
  -- CAMERA:SetEye(SymCam("CAMERA_04"))
  -- CAMERA:SetTgt(SymCam("CAMERA_04"))
  -- CH("MUNNA_ZERO"):SetShake(Vector(0.005, 0, 0), TimeSec(0.1, TIME_TYPE.FRAME))
  -- TASK:Sleep(TimeSec(0.5))
  -- CH("MUNNA_ZERO"):ResetShake()
  -- WINDOW:SysMsg(50655631)
  -- WINDOW:CloseMessage()
  -- SCREEN_A:FadeOut(TimeSec(0.5), true)
  FLAG.SceneFlag = CONST.FL_SC_10_END
  FLAG.SCENARIOFLAG = CONST.M18_HYOUSHOKUTAI01BOSS1ST_START
  SYSTEM:NextEntry()
end
function main18_hyoushokutai01boss1st10_end()
end
function main18_hyoushokutai01boss1st11_init()
end
function main18_hyoushokutai01boss1st11_start()
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetFovy(SymCam("CAMERA_03"))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("HERO"):SetPosition(SymPos("P00_HERO"))
  CH("HERO"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- SOUND:PlayBgm(SymSnd("BGM_EVE_GANBARE"), Volume(256))
  -- CH("HERO"):SetShadow(false)
  -- CH("PARTNER"):SetShadow(false)
  -- local pokemonIndexPartner = SymAct("PARTNER"):GetIndex()
  -- if pokemonIndexPartner == 42 then
  --   CH("PARTNER"):SetPosition(SymPos("P00_PARTNER_POKABU"))
  -- elseif pokemonIndexPartner == 122 then
  --   CH("PARTNER"):SetPosition(SymPos("P00_PARTNER_POKABU"))
  -- elseif pokemonIndexPartner == 45 then
  --   CH("PARTNER"):SetPosition(SymPos("P00_PARTNER_POKABU"))
  -- end
  -- CH("PARTNER"):SetMotion(SymMot("EV018_KNEEATTACHE00"), LOOP.ON, TimeSec(0))
  -- CH("HERO"):SetMotion(SymMot("EV011_KNEEATTACHE01"), LOOP.ON, TimeSec(0))
  -- EFFECT:Create("effect01", SymEff("EV_EDDY_WIND_BOSS_LP"))
  -- EFFECT:SetPosition("effect01", SymPos("P01_EFFECT"))
  -- EFFECT:Play("effect01")
  -- EFFECT:Create("effect02", SymEff("BG_FRAME_SMOKE_LP"))
  -- EFFECT:SetPosition("effect02", SymPos("P02_EFFECT"))
  -- EFFECT:Play("effect02")
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- WINDOW:Explanation(438288590)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  -- CAMERA:SetEye(SymCam("CAMERA_01"))
  -- CAMERA:SetTgt(SymCam("CAMERA_01"))
  -- TASK:Sleep(TimeSec(0.3))
  -- CH("HERO"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  -- WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  -- WINDOW:Monologue(1432245769)
  -- subEveCloseMsg()
  -- WINDOW:Talk(SymAct("KYUREMU"), 1279616840)
  -- WINDOW:Talk(SymAct("KYUREMU"), 1734882443)
  -- WINDOW:Talk(SymAct("KYUREMU"), 2121467338)
  -- WINDOW:Talk(SymAct("KYUREMU"), -102033147)
  -- WINDOW:Talk(SymAct("KYUREMU"), -521131964)
  -- WINDOW:Talk(SymAct("KYUREMU"), 1766949723)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- TASK:Sleep(TimeSec(0.3))
  -- WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  -- WINDOW:Monologue(1883943450)
  -- subEveCloseMsg()
  -- WINDOW:Talk(SymAct("KYUREMU"), 1533534681)
  -- WINDOW:Talk(SymAct("KYUREMU"), 1115476120)
  -- WINDOW:Talk(SymAct("KYUREMU"), 222119519)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetEye(SymCam("CAMERA_05"))
  -- CAMERA:SetTgt(SymCam("CAMERA_05"))
  -- CH("PARTNER"):SetShake(Vector(0.005, 0, 0), TimeSec(0.1, TIME_TYPE.FRAME))
  -- TASK:Sleep(TimeSec(0.5))
  -- CH("PARTNER"):ResetShake()
  -- WINDOW:SwitchTalk({PARTNER_0 = 338065182, PARTNER_1 = 1057694941})
  -- WINDOW:SwitchTalk({PARTNER_0 = 638588316, PARTNER_1 = -1584920237})
  -- WINDOW:SwitchTalk({PARTNER_0 = -1198311406, PARTNER_1 = -772938690})
  -- WINDOW:CloseMessage()
  -- SOUND:FadeOutBgm(TimeSec(2.5))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  -- CAMERA:SetEye(SymCam("CAMERA_01"))
  -- CAMERA:SetTgt(SymCam("CAMERA_01"))
  -- TASK:Sleep(TimeSec(0.3))
  -- CH("HERO"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0.3))
  -- TASK:Sleep(TimeSec(0.3))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  -- CH("HERO"):SetManpu("MP_EXCLAMATION")
  -- CH("HERO"):WaitManpu()
  -- WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.SURPRISE)
  -- WINDOW:Monologue(-923347585)
  -- WINDOW:CloseMessage()
  -- SOUND:PlaySe(SymSnd("SE_EVT_FLUSH"), Volume(256))
  -- subEveFlash()
  -- SOUND:PlayBgm(SymSnd("BGM_EVE_BOSS_HYOUSHOKU_01"), Volume(256))
  -- CH("HERO"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  -- CH("HERO"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
  -- TASK:Sleep(TimeSec(0.8))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  -- CAMERA:SetFovy(SymCam("CAMERA_03"))
  -- CAMERA:SetEye(SymCam("CAMERA_03"))
  -- CAMERA:SetTgt(SymCam("CAMERA_03"))
  -- CH("HERO"):SetPosition(SymPos("P00_HERO"))
  -- CH("HERO"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  -- TASK:Sleep(TimeSec(0.3))
  -- WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.DECIDE)
  -- WINDOW:Monologue(-472152388)
  -- WINDOW:Monologue(-88033283)
  -- WINDOW:CloseMessage()
  -- subEveFlash2()
  SOUND:PlaySe(SymSnd("SE_EVT_BOSS_WIPE_02"), Volume(256))
  EFFECT:BossWipe(TimeSec(60, TIME_TYPE.FRAME), true)
  CAMERA:ResetAzimuthDifferenceVolume()
  FLAG.SceneFlag = CONST.FL_SC_01_FIRST
  FLAG.SCENARIOFLAG = CONST.M18_HYOUSHOKUTAI01BOSS1ST_END
  FLAG.Boss1stClear = CONST.FLAG_FALSE
  SYSTEM:SetNextDungeonBanner(false)
  SYSTEM:EnterDungeon(Dg(23), DG_WAYPOINT.BOSS00)
end
function main18_hyoushokutai01boss1st11_end()
end
function groundEnd()
end

