dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main03_nuonohanashi01_init()
end
function main03_nuonohanashi01_start()
  FLAG.TownRightFlag = CONST.FLAG_FALSE
  FLAG.TownLeftFlag = CONST.FLAG_FALSE
  FLAG.TownMidFlag = CONST.FLAG_FALSE
  FLAG.TownTopFlag = CONST.FLAG_FALSE
  FLAG.TownYado1fFlag = CONST.FLAG_FALSE
  FLAG.TownYado2fFlag = CONST.FLAG_FALSE
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- subEveFadeAfterTime()
  -- WINDOW:DrawFace(226, 8, SymAct("PARTNER"), FACE_TYPE.THINK)
  -- WINDOW:SwitchTalk({PARTNER_0 = 325264608, PARTNER_1 = 175642017})
  -- WINDOW:CloseMessage()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  -- CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  -- CH("PARTNER"):WaitManpu()
  -- CH("PARTNER"):DirTo(RotateTarget(90), Speed(350), ROT_TYPE.NEAR)
  -- CH("PARTNER"):WaitRotate()
  -- WINDOW:DrawFace(118, 8, SymAct("PARTNER"), FACE_TYPE.THINK)
  -- WINDOW:SwitchTalk({PARTNER_0 = 559236706, PARTNER_1 = 944666403})
  -- WINDOW:CloseMessage()
  -- CH("NUOO"):WalkTo(SymPos("P00_NUOO"), Speed(1.5))
  -- TASK:Sleep(TimeSec(0.3))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  -- CH("PARTNER"):SetManpu("MP_NOTICE_R")
  -- TASK:Sleep(TimeSec(0.2))
  -- CH("HERO"):SetManpu("MP_NOTICE_R")
  -- CH("PARTNER"):WaitManpu()
  -- CH("PARTNER"):DirTo(CH("NUOO"), Speed(350), ROT_TYPE.NEAR)
  -- CH("HERO"):WaitManpu()
  -- CH("HERO"):DirTo(CH("NUOO"), Speed(350), ROT_TYPE.NEAR)
  -- WINDOW:DrawFace(118, 8, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  -- WINDOW:SwitchTalk({PARTNER_0 = 1997529572, PARTNER_1 = 1846857893})
  -- subEveCloseMsg()
  -- CH("NUOO"):WaitMove()
  -- WINDOW:DrawFace(324, 88, SymAct("NUOO"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("NUOO"), 1161397094)
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(118, 8, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  -- WINDOW:SwitchTalk({PARTNER_0 = 1545777703, PARTNER_1 = -608522520})
  -- subEveCloseMsg()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  -- CH("NUOO"):SetManpu("MP_QUESTION")
  -- CH("NUOO"):WaitManpu()
  -- WINDOW:DrawFace(324, 88, SymAct("NUOO"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("NUOO"), -1029595223)
  -- WINDOW:Talk(SymAct("NUOO"), 1147029303)
  -- WINDOW:CloseMessage()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_01"), Volume(256))
  -- CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  -- CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("HERO"):SetManpu("MP_EXCLAMATION")
  -- CH("HERO"):WaitManpu()
  -- WINDOW:DrawFace(118, 8, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  -- WINDOW:SwitchTalk({PARTNER_0 = 1564833398, PARTNER_1 = 1986536885})
  -- WINDOW:CloseMessage()
  -- CH("NUOO"):DirTo(RotateTarget(45), Speed(200), ROT_TYPE.RIGHT)
  -- CH("NUOO"):WaitRotate()
  -- WINDOW:DrawFaceF(324, 88, SymAct("NUOO"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("NUOO"), 1869812980)
  -- WINDOW:CloseMessage()
  -- CH("NUOO"):DirTo(RotateTarget(-135), Speed(200), ROT_TYPE.LEFT)
  -- CH("NUOO"):WaitRotate()
  -- WINDOW:DrawFace(324, 88, SymAct("NUOO"), FACE_TYPE.THINK)
  -- WINDOW:Talk(SymAct("NUOO"), 540181043)
  -- WINDOW:CloseMessage()
  -- SCREEN_A:FadeOut(TimeSec(0.5), true)
  -- subEveFadeAfterTime()
  FLAG.SceneFlag = CONST.FL_SC_01_END
  FLAG.SCENARIOFLAG = CONST.M03_NUONOHANASHI_START
  SYSTEM:NextEntry()
end
function main03_nuonohanashi01_end()
end
function main03_nuonohanashi02_init()
end
function main03_nuonohanashi02_start()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- CH("NOKOTCHI"):SetDir(CH("KOMATANA_1"))
  -- local taskNuooWalkToManpu = function()
  --   CH("NUOO"):WalkTo(SplinePath(SymPos("P00_NUOO"), SymPos("P01_NUOO")), Speed(1))
  --   CH("NUOO"):WaitMove()
  --   SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  --   CH("NUOO"):SetManpu("MP_NOTICE_L")
  --   CH("NUOO"):WaitManpu()
  -- end
  -- SCREEN_A:SetSepiaFilter()
  -- TASK:Regist(Group("nuoo"), taskNuooWalkToManpu)
  -- SOUND:PlayBgm(SymSnd("BGM_EVE_NAZO_03"), Volume(256))
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- TASK:Sleep(TimeSec(0.3))
  -- CAMERA:MoveFollow(SymCam("CAMERA_00_5"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- WINDOW:SysMsg(959034226)
  -- WINDOW:CloseMessage()
  -- TASK:WaitTask()
  -- TASK:WaitTask(Group("nuoo"))
  -- CAMERA:MoveFollow(SymCam("CAMERA_01"), Speed(3.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- CAMERA:WaitMove()
  -- WINDOW:DrawFace(226, 8, SymAct("KOMATANA_1"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("???"), 302309553)
  -- WINDOW:Talk(SymAct("???"), 186634736)
  -- WINDOW:CloseMessage()
  -- subEveJump(CH("NOKOTCHI"))
  -- WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.TEARS)
  -- WINDOW:Talk(SymAct("NOKOTCHI"), -1937257153)
  -- WINDOW:CloseMessage()
  -- CH("NOKOTCHI"):DirTo(CH("KOMATANA_2"), Speed(350), ROT_TYPE.NEAR)
  -- WINDOW:DrawFace(324, 88, SymAct("KOMATANA_2"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("???"), -1784873858)
  -- WINDOW:Talk(SymAct("???"), 1458301145)
  -- WINDOW:Talk(SymAct("???"), 1341184408)
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.THINK)
  -- WINDOW:Talk(SymAct("NOKOTCHI"), 1692240475)
  -- subEveCloseMsg()
  -- CH("NOKOTCHI"):DirTo(CH("KOMATANA_1"), Speed(350), ROT_TYPE.NEAR)
  -- WINDOW:DrawFace(226, 8, SymAct("KOMATANA_1"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("???"), 2110176026)
  -- WINDOW:Talk(SymAct("???"), 847719901)
  -- subEveCloseMsg()
  -- CH("NOKOTCHI"):DirTo(CH("KOMATANA_2"), Speed(350), ROT_TYPE.NEAR)
  -- WINDOW:DrawFace(324, 88, SymAct("KOMATANA_2"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("KOMATANA_1"), 731651228)
  -- WINDOW:Talk(SymAct("KOMATANA_1"), 11620191)
  -- WINDOW:Talk(SymAct("KOMATANA_1"), 430603806)
  -- WINDOW:CloseMessage()
  -- CH("KOMATANA_1"):DirTo(SymPos("P00_KOMATANA_1"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("KOMATANA_2"):DirTo(SymPos("P00_KOMATANA_2"), Speed(350), ROT_TYPE.NEAR)
  -- CH("NOKOTCHI"):DirTo(SymPos("P00_NOKOTCHI"), Speed(350), ROT_TYPE.NEAR)
  -- CH("KOMATANA_1"):WaitRotate()
  -- CH("KOMATANA_1"):WalkTo(SymPos("P00_KOMATANA_1"), Speed(1))
  -- CH("KOMATANA_2"):WaitRotate()
  -- CH("KOMATANA_2"):WalkTo(SymPos("P00_KOMATANA_2"), Speed(1))
  -- TASK:Sleep(TimeSec(0.3))
  -- CH("NOKOTCHI"):WalkTo(SplinePath(SymPos("P00_NOKOTCHI"), SymPos("P01_NOKOTCHI")), Speed(1))
  -- WINDOW:SysMsg(-1640865071)
  -- WINDOW:SysMsg(-2027334768)
  -- WINDOW:CloseMessage()
  -- SCREEN_A:FadeOut(TimeSec(0.5), true)
  -- SCREEN_A:ClearSepiaFilter()
  FLAG.SceneFlag = CONST.FL_SC_02_END
  FLAG.SCENARIOFLAG = CONST.M03_NUONOHANASHI_START
  SYSTEM:NextEntry()
end
function main03_nuonohanashi02_end()
end
function main03_nuonohanashi03_init()
end
function main03_nuonohanashi03_start()
  -- SOUND:PlayBgm(SymSnd("BGM_EVE_NAZO_03"), Volume(256))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  -- CH("PARTNER"):SetManpu("MP_SHOCK_R")
  -- CH("HERO"):SetManpu("MP_EXCLAMATION")
  -- CH("HERO"):WaitManpu()
  -- WINDOW:DrawFace(118, 8, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  -- WINDOW:SwitchTalk({PARTNER_0 = -296251460, PARTNER_1 = -145965315})
  -- WINDOW:CloseMessage()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  -- CH("NUOO"):SetManpu("MP_QUESTION")
  -- CH("NUOO"):WaitManpu()
  -- WINDOW:DrawFace(324, 88, SymAct("NUOO"), FACE_TYPE.THINK)
  -- WINDOW:Talk(SymAct("NUOO"), -597562050)
  -- WINDOW:CloseMessage()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  -- CH("NUOO"):SetManpu("MP_NOTICE_L")
  -- CH("NUOO"):WaitManpu()
  -- WINDOW:DrawFace(324, 88, SymAct("NUOO"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("NUOO"), -981803905)
  -- WINDOW:Talk(SymAct("NUOO"), -1975825736)
  -- subEveCloseMsg()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  -- CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  -- CH("PARTNER"):WaitManpu()
  -- WINDOW:DrawFace(118, 8, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  -- WINDOW:SwitchTalk({PARTNER_0 = -1826587655, PARTNER_1 = -1207097286})
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(324, 88, SymAct("NUOO"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("NUOO"), -1592387205)
  -- WINDOW:Talk(SymAct("NUOO"), 646841780)
  -- WINDOW:Talk(SymAct("NUOO"), 1066743029)
  -- WINDOW:Talk(SymAct("NUOO"), 1937815301)
  -- WINDOW:CloseMessage()
  -- SOUND:FadeOutBgm(TimeSec(1.5))
  -- CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  -- CH("HERO"):WaitRotate()
  -- WINDOW:DrawFace(226, 8, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  -- WINDOW:SwitchTalk({PARTNER_0 = 1788577348, PARTNER_1 = 1102501255})
  -- subEveCloseMsg()
  -- TASK:Regist(subEveNod, {
  --   CH("HERO")
  -- })
  -- WINDOW:DrawFace(20, 88, SymAct("HERO"), FACE_TYPE.DECIDE)
  -- WINDOW:Monologue(1487791302)
  -- WINDOW:CloseMessage()
  -- CH("PARTNER"):DirTo(CH("NUOO"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.1))
  -- CH("HERO"):DirTo(CH("NUOO"), Speed(350), ROT_TYPE.NEAR)
  -- CH("HERO"):WaitRotate()
  -- CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  -- WINDOW:DrawFace(118, 8, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  -- WINDOW:SwitchTalk({PARTNER_0 = 401371649, PARTNER_1 = 251085632})
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(324, 88, SymAct("NUOO"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("NUOO"), 635048067)
  -- WINDOW:CloseMessage()
  -- CH("PARTNER"):RunTo(SplinePath(SymPos("P00_PARTNER"), SymPos("P01_PARTNER")), Speed(2.5))
  -- TASK:Sleep(TimeSec(0.2))
  -- CH("HERO"):RunTo(SplinePath(SymPos("P00_HERO"), SymPos("P01_HERO")), Speed(2.5))
  -- TASK:Sleep(TimeSec(0.2))
  -- CH("NUOO"):DirLockToChara(CH("HERO"))
  -- WINDOW:DrawFaceF(324, 88, SymAct("NUOO"), FACE_TYPE.THINK)
  -- WINDOW:Talk(SymAct("NUOO"), 1019290050)
  -- WINDOW:CloseMessage()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  -- CH("NUOO"):SetManpu("MP_FLY_SWEAT")
  -- CH("NUOO"):WaitManpu()
  -- WINDOW:DrawFaceF(324, 88, SymAct("NUOO"), FACE_TYPE.THINK)
  -- WINDOW:Talk(SymAct("NUOO"), -1151779571)
  -- WINDOW:CloseMessage()
  -- TASK:Sleep(TimeSec(1))
  -- CAMERA:MoveFollow(SymCam("CAMERA_01"), Speed(2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- CAMERA:WaitMove()
  -- TASK:Sleep(TimeSec(1))
  -- SCREEN_A:FadeOut(TimeSec(1), true)
  -- subEveFadeAfterTime()
  -- CH("NUOO"):DirLockOff()
  FLAG.SceneFlag = CONST.FL_SC_03_END
  FLAG.SCENARIOFLAG = CONST.M03_NUONOHANASHI_START
  SYSTEM:NextEntry()
end
function main03_nuonohanashi03_end()
end
function main03_nuonohanashi04_init()
end
function main03_nuonohanashi04_start()
  subMapCameraCrossroadDefMode()
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("HERO"):SetPosition(SymPos("P00_HERO"))
  CH("PARTNER"):SetPosition(SymPos("P00_PARTNER"))
  CH("HERO"):DirTo(RotateTarget(-55), Speed(0), ROT_TYPE.NEAR)
  CH("PARTNER"):DirTo(CH("HERO"), Speed(0), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  CH("PARTNER"):WaitRotate()
  -- CH("HERO"):RunTo(SymPos("P00_HERO"), Speed(2.5))
  -- CH("PARTNER"):RunTo(SymPos("P00_PARTNER"), Speed(2.5))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- CH("HERO"):WaitMove()
  -- CH("HERO"):DirTo(RotateTarget(-55), Speed(500), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.2))
  -- CH("PARTNER"):WaitMove()
  -- CH("PARTNER"):DirTo(CH("HERO"), Speed(500), ROT_TYPE.NEAR)
  -- CH("PARTNER"):WaitRotate()
  -- CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  -- WINDOW:SwitchTalk({PARTNER_0 = -1572729780, PARTNER_1 = -885206944})
  -- WINDOW:SwitchTalk({PARTNER_0 = -769138399, PARTNER_1 = -116739358})
  -- WINDOW:SwitchTalk({PARTNER_0 = -535723101, PARTNER_1 = -1353706140})
  -- WINDOW:SwitchTalk({PARTNER_0 = -1236589531, PARTNER_1 = -1654229018})
  -- WINDOW:SwitchTalk({PARTNER_0 = -2072164697, PARTNER_1 = 65362536})
  -- WINDOW:SwitchTalk({PARTNER_0 = 452881193, PARTNER_1 = -645300338})
  -- WINDOW:CloseMessage()
  -- subEveNod(CH("HERO"))
  -- CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  CAMERA:MoveToHero(Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  FLAG.SceneFlag = CONST.FL_SC_01_FIRST
  FLAG.SCENARIOFLAG = CONST.M03_NUONOHANASHI_END
  FLAG.Boss1stMeet = CONST.FLAG_FALSE
  FLAG.MapFlags = CONST.MAP_EVENT
  FLAG.FreePlay = CONST.FLAG_TRUE
  FLAG.TrigNextEvent = CONST.FLAG_FALSE
  SYSTEM:NextEntry(KEEP_PLACEMENT.ON)
end
function main03_nuonohanashi04_end()
end
function groundEnd()
end

