dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main04_dotekkotsunohanashi01_init()
end
function main04_dotekkotsunohanashi01_start()
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CAMERA:MoveFollow(SymCam("CAMERA_01"), Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("PARTNER"):WalkTo(SymPos("P00_PARTNER"), Speed(1.5))
  CH("HERO"):WalkTo(SymPos("P00_HERO"), Speed(1.5))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  CH("HERO"):WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_DOTEKKOTSU"), Volume(256))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  WINDOW:Talk(SymAct("DOTEKKOTSU"), 108734225)
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  CH("PARTNER"):SetManpu("MP_NOTICE_L")
  WINDOW:CloseMessage()
  CAMERA:MoveFollow(SymCam("CAMERA_02"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("DOTEKKOTSU"):WalkTo(SymPos("P00_DOTEKKOTSU"), Speed(2))
  TASK:Regist(subEveMoveDir, {
    CH("DOKKORAA_1"),
    SymPos("P00_DOKKORAA_1"),
    Speed(2),
    RotateTarget(175)
  })
  TASK:Regist(subEveMoveDir, {
    CH("DOKKORAA_2"),
    SymPos("P00_DOKKORAA_2"),
    Speed(2),
    RotateTarget(150)
  })
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):DirTo(CH("DOTEKKOTSU"), Speed(350), ROT_TYPE.NEAR)
  TASK:WaitTask()
  CAMERA:WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  CH("PARTNER"):SetManpu("MP_QUESTION")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 526390864, PARTNER_1 = 877479315})
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("DOTEKKOTSU"), FACE_TYPE.SPECIAL04)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), 760640722)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), 1645732373)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_01"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 2064438100, PARTNER_1 = 1344372887})
  subEveCloseMsg()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  WINDOW:DrawFace(324, 88, SymAct("DOTEKKOTSU"), FACE_TYPE.SPECIAL04)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), 1228583382)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), -828199655)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), -675701672)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  SOUND:PlayBgm(SymSnd("BGM_EVE_COMICAL"), Volume(256))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(324, 88, SymAct("DOKKORAA_2"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DOKKORAA_2"), -789523607)
  CH("HERO"):DirTo(CH("DOKKORAA_2"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):DirTo(CH("DOKKORAA_2"), Speed(200), ROT_TYPE.NEAR)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("DOTEKKOTSU"):SetManpu("MP_NOTICE_L")
  WINDOW:DrawFace(272, 88, SymAct("DOKKORAA_1"), FACE_TYPE.NORMAL)
  WINDOW:DrawFaceOffset(-50, 0)
  WINDOW:Talk(SymAct("DOKKORAA_1"), -907288024)
  WINDOW:CloseMessage()
  CH("DOTEKKOTSU"):DirTo(RotateTarget(-45), Speed(500), ROT_TYPE.NEAR)
  CH("DOTEKKOTSU"):WaitRotate()
  CH("DOKKORAA_1"):DirTo(CH("DOTEKKOTSU"), Speed(500), ROT_TYPE.NEAR)
  CH("DOKKORAA_2"):DirTo(CH("DOTEKKOTSU"), Speed(500), ROT_TYPE.NEAR)
  CH("DOKKORAA_2"):WaitRotate()
  CH("DOKKORAA_1"):SetManpu("MP_FLY_SWEAT")
  CH("DOKKORAA_2"):SetManpu("MP_FLY_SWEAT")
  CH("DOKKORAA_1"):WalkTo(SymPos("P01_DOKKORAA_1"), Speed(4), LINK_DIR.OFF)
  CH("DOKKORAA_2"):WalkTo(SymPos("P01_DOKKORAA_2"), Speed(4), LINK_DIR.OFF)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_ANGRY_02"), Volume(256))
  CH("DOTEKKOTSU"):SetManpu("MP_ANGRY_LP")
  CH("DOTEKKOTSU"):SetFacialMotion(FACIAL_MOTION.ANGRY)
  WINDOW:DrawFace(272, 16, SymAct("DOTEKKOTSU"), FACE_TYPE.ANGRY)
  WINDOW:DrawFaceOffset(10, 0)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), -490294805)
  WINDOW:CloseMessage()
  CH("DOTEKKOTSU"):ResetManpu()
  CH("DOTEKKOTSU"):ResetManpu()
  CH("DOTEKKOTSU"):WalkTo(SymPos("P01_DOTEKKOTSU"), Speed(1.5))
  CH("DOKKORAA_1"):WalkTo(SymPos("P02_DOKKORAA_1"), Speed(2), LINK_DIR.OFF)
  CH("DOKKORAA_2"):WalkTo(SymPos("P02_DOKKORAA_2"), Speed(2), LINK_DIR.OFF)
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  subEveFadeAfterTime()
  WINDOW:DrawFace(20, 88, SymAct("DOKKORAA_1"), FACE_TYPE.SPECIAL05)
  WINDOW:Talk(SymAct("DOKKORAA_1"), -69369686)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_DOKABAKI"), Volume(256))
  WINDOW:SysMsg(-1264839059)
  TASK:Sleep(TimeSec(0.5))
  WINDOW:ForceCloseMessage()
  SOUND:FadeOutSe(SymSnd("SE_EVT_DOKABAKI"), TimeSec(0.5))
  CH("DOKKORAA_1"):SetVisible(false)
  CH("DOKKORAA_2"):SetVisible(false)
  CH("DOTEKKOTSU"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  CH("DOTEKKOTSU"):SetMotion(SymMot("EV002_DAMAGESTAND00"), LOOP.ON, TimeSec(0))
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_04_5"))
  CAMERA:SetTgt(SymCam("CAMERA_04_5"))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  subEveFadeAfterTime()
  WINDOW:DrawFaceF(20, 88, SymAct("DOTEKKOTSU"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), -1383651540)
  subEveCloseMsg()
  CH("DOTEKKOTSU"):SetMotion(SymMot("EV002_DAMAGESTAND01"), LOOP.OFF)
  CH("DOTEKKOTSU"):WaitPlayMotion()
  CH("DOTEKKOTSU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("ZURUGGU"):SetDir(CH("DOTEKKOTSU"))
  WINDOW:DrawFace(324, 88, SymAct("ZURUGGU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("ZURUGGU"), -2035649297)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("DOTEKKOTSU"):SetManpu("MP_NOTICE_L")
  WINDOW:CloseMessage()
  CH("DOTEKKOTSU"):DirTo(CH("ZURUGGU"), Speed(350), ROT_TYPE.NEAR)
  CH("DOTEKKOTSU"):WaitRotate()
  CH("HERO"):DirTo(CH("ZURUGGU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):DirTo(CH("ZURUGGU"), Speed(350), ROT_TYPE.NEAR)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_SHOCK_02"), Volume(256))
  CH("DOTEKKOTSU"):SetManpu("MP_EXCLAMATION")
  CH("DOTEKKOTSU"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("DOTEKKOTSU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), -1615772242)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow(SymCam("CAMERA_05"), Speed(5.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  TASK:Sleep(TimeSec(0.3))
  TASK:Regist(subEveJump, {
    CH("ZURUGGU")
  })
  WINDOW:DrawFace(324, 88, SymAct("ZURUGGU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("ZURUGGU"), 405363041)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("DOTEKKOTSU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), 20080672)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), -1035633529)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("ZURUGGU"):SetManpu("MP_FLY_SWEAT")
  CH("ZURUGGU"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("ZURUGGU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("ZURUGGU"), -614576698)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow(SymCam("CAMERA_05_5"), Speed(2.5, ACCEL_TYPE.LOW, DECEL_TYPE.HIGH))
  CH("ZURUGGU"):SetNeckRot(CH("NUOO"), TimeSec(0.75))
  CH("ZURUGGU"):WaitNeckRot()
  CAMERA:WaitMove()
  TASK:Sleep(TimeSec(1))
  CAMERA:MoveFollow(SymCam("CAMERA_05"), Speed(4, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  CH("ZURUGGU"):ResetNeckRot(TimeSec(0.15))
  CH("ZURUGGU"):WaitNeckRot()
  TASK:Regist(subEveDoubleJump, {
    CH("ZURUGGU")
  })
  CH("ZURUGGU"):SetFacialMotion(FACIAL_MOTION.SAD)
  WINDOW:DrawFace(324, 88, SymAct("ZURUGGU"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("ZURUGGU"), -260891131)
  WINDOW:Talk(SymAct("ZURUGGU"), -379048124)
  WINDOW:KeyWait()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("ZURUGGU"):SetManpu("MP_FLY_SWEAT_LP")
  CH("ZURUGGU"):SetFacialMotion(FACIAL_MOTION.WEEP)
  WINDOW:DrawFace(324, 88, SymAct("ZURUGGU"), FACE_TYPE.WEEP)
  WINDOW:Talk(SymAct("ZURUGGU"), -1507214973)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow(SymCam("CAMERA_04"), Speed(5.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  SOUND:FadeOutBgm(TimeSec(2))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("DOTEKKOTSU"):SetManpu("MP_FLY_SWEAT")
  CH("DOTEKKOTSU"):WaitManpu()
  CH("ZURUGGU"):ResetManpu()
  CH("ZURUGGU"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  WINDOW:DrawFace(20, 88, SymAct("DOTEKKOTSU"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), -1087207230)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), -1809851647)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), -1929057728)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), 178058895)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow(SymCam("CAMERA_02"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("DOTEKKOTSU"):WalkTo(SymPos("P02_DOTEKKOTSU"), Speed(1.5))
  TASK:Sleep(TimeSec(0.5))
  CH("PARTNER"):DirTo(CH("DOTEKKOTSU"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("HERO"):DirTo(CH("DOTEKKOTSU"), Speed(350), ROT_TYPE.NEAR)
  CH("DOTEKKOTSU"):WaitMove()
  CH("DOTEKKOTSU"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  CH("DOTEKKOTSU"):WaitRotate()
  CAMERA:WaitMove()
  SOUND:PlayBgm(SymSnd("BGM_EVE_HAPPY"), Volume(256))
  WINDOW:DrawFace(324, 88, SymAct("DOTEKKOTSU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), 327665614)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), 2063145954)
  subEveCloseMsg()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  WINDOW:SwitchTalk({PARTNER_0 = 1675766435, PARTNER_1 = 1221556576})
  WINDOW:SwitchTalk({PARTNER_0 = 1372866593, PARTNER_1 = 513138406})
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("DOTEKKOTSU"), FACE_TYPE.SPECIAL04)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), 126807975)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), 748928100)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("HERO"):SetManpu("MP_EXCLAMATION")
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("PARTNER"):SetManpu("MP_SHOCK_R")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.SURPRISE)
  WINDOW:SwitchTalk({PARTNER_0 = 901287205, PARTNER_1 = -1306488342})
  WINDOW:CloseMessage()
  CH("DOTEKKOTSU"):DirTo(RotateTarget(-45), Speed(350), ROT_TYPE.NEAR)
  CH("DOTEKKOTSU"):WaitRotate()
  CAMERA:MoveFollow(SymCam("CAMERA_06"), Speed(5.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("PARTNER"):DirTo(RotateTarget(-45), Speed(350), ROT_TYPE.NEAR)
  CH("HERO"):DirTo(RotateTarget(-45), Speed(350), ROT_TYPE.NEAR)
  CAMERA:WaitMove()
  WINDOW:DrawFace(324, 88, SymAct("DOTEKKOTSU"), FACE_TYPE.SPECIAL04)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), -1422155605)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), -416406693)
  WINDOW:CloseMessage()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  CAMERA:MoveFollow(SymCam("CAMERA_02"), Speed(5.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  CH("DOTEKKOTSU"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  CH("DOTEKKOTSU"):WaitRotate()
  CH("PARTNER"):DirTo(CH("DOTEKKOTSU"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("HERO"):DirTo(CH("DOTEKKOTSU"), Speed(350), ROT_TYPE.NEAR)
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("PARTNER"):SetManpu("MP_FLY_SWEAT")
  CH("PARTNER"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("DOTEKKOTSU"), FACE_TYPE.SPECIAL04)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), -30076390)
  WINDOW:DrawFace(324, 88, SymAct("DOTEKKOTSU"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), -719830567)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), -872189800)
  subEveCloseMsg()
  TASK:Regist(subEveDoubleJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -2092767649, PARTNER_1 = -1705388258})
  WINDOW:SwitchTalk({PARTNER_0 = -1317763875, PARTNER_1 = -1469074020})
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("DOTEKKOTSU"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), 804759891)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), 921475090)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), 1603421246)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), 1183413631)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), 1839474364)
  subEveCloseMsg()
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = 1958680573, PARTNER_1 = 1006534970})
  WINDOW:SwitchTalk({PARTNER_0 = 585478267, PARTNER_1 = 164160440})
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("DOTEKKOTSU"):SetManpu("MP_EXCLAMATION")
  CH("DOTEKKOTSU"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("DOTEKKOTSU"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), 282317561)
  subEveCloseMsg()
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1756639690, PARTNER_1 = -1907294345})
  WINDOW:SwitchTalk({PARTNER_0 = 1294461904, PARTNER_1 = 1413274257})
  WINDOW:SwitchTalk({PARTNER_0 = 2131855698, PARTNER_1 = 1711978515})
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("DOTEKKOTSU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), 692793044)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow(SymCam("CAMERA_07"), Speed(4, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("DOTEKKOTSU"):DirTo(SymPos("P_KEIJIBAN"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.3))
  CH("HERO"):DirTo(SymPos("P_KEIJIBAN"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):DirTo(SymPos("P_KEIJIBAN"), Speed(350), ROT_TYPE.NEAR)
  CAMERA:WaitMove()
  WINDOW:DrawFace(324, 88, SymAct("DOTEKKOTSU"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), 810557333)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), 461196374)
  WINDOW:Talk(SymAct("DOTEKKOTSU"), 40271127)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow(SymCam("CAMERA_02"), Speed(4, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Sleep(TimeSec(0.3))
  CH("DOTEKKOTSU"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.2))
  CH("HERO"):DirTo(CH("DOTEKKOTSU"), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CH("PARTNER"):DirTo(CH("DOTEKKOTSU"), Speed(350), ROT_TYPE.NEAR)
  CAMERA:WaitMove()
  TASK:Regist(subEveJump, {
    CH("PARTNER")
  })
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -2046926376, PARTNER_1 = -1662693223})
  WINDOW:SwitchTalk({PARTNER_0 = -174355275, PARTNER_1 = -327107084})
  WINDOW:SwitchTalk({PARTNER_0 = -944902601, PARTNER_1 = -558440586})
  WINDOW:CloseMessage()
  CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("PARTNER"):WaitRotate()
  CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  WINDOW:SwitchTalk({PARTNER_0 = -1846064719, PARTNER_1 = -1997768464})
  WINDOW:SwitchTalk({PARTNER_0 = -1547621581, PARTNER_1 = -1160111502})
  WINDOW:SwitchTalk({PARTNER_0 = 1027737277, PARTNER_1 = 609826812})
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(2))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  CAMERA:ResetAzimuthDifferenceVolume()
  SOUND:WaitBgm()
  FLAG.SceneFlag = CONST.FL_SC_01_FIRST
  FLAG.SCENARIOFLAG = CONST.M04_DOTEKKOTSUNOHANASHI_END
  FLAG.MapFlags = CONST.MAP_EVENT
  FLAG.FreePlay = CONST.FLAG_TRUE
  FLAG.TrigNextEvent = CONST.FLAG_FALSE
  SYSTEM:NextEntry()
end
function main04_dotekkotsunohanashi01_end()
end
function groundEnd()
end

