dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main12_tenninoboruhikari01_init()
  FLAG.SceneFlag = CONST.FL_SC_01_FIRST
  FLAG.SCENARIOFLAG = CONST.M12_TENNINOBORUHIKARI_END
  FLAG.MapFlags = CONST.MAP_EVENT
  FLAG.FreePlay = CONST.FLAG_TRUE
  FLAG.TrigNextEvent = CONST.FLAG_FALSE
  SYSTEM:NextEntry()
end
function main12_tenninoboruhikari01_start()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- SCREEN_A:FadeIn(TimeSec(0.5), false)
  -- CAMERA:MoveFollow(SymCam("CAMERA_01"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- CH("HERO"):WalkTo(SplinePath(SymPos("P00_HERO"), SymPos("P01_HERO")), Speed(1.5))
  -- TASK:Sleep(TimeSec(0.2))
  -- CH("PARTNER"):WalkTo(SplinePath(SymPos("P00_PARTNER"), SymPos("P01_PARTNER")), Speed(1.5))
  -- TASK:Sleep(TimeSec(0.5))
  -- CH("EMONGA"):WalkTo(SymPos("P01_EMONGA"), Speed(1.5))
  -- TASK:Sleep(TimeSec(0.5))
  -- CH("HERO"):WaitMove()
  -- CH("HERO"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  -- CH("HERO"):WaitRotate()
  -- CH("PARTNER"):WaitMove()
  -- CH("PARTNER"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  -- CH("PARTNER"):WaitRotate()
  -- CH("EMONGA"):WaitMove()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  -- CH("EMONGA"):SetManpu("MP_EXCLAMATION")
  -- CH("EMONGA"):WaitManpu()
  -- WINDOW:DrawFace(20, 88, SymAct("EMONGA"), FACE_TYPE.HAPPY)
  -- WINDOW:Talk(SymAct("EMONGA"), -1246685248)
  -- WINDOW:CloseMessage()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  -- CH("PARTNER"):SetManpu("MP_QUESTION")
  -- CH("PARTNER"):WaitManpu()
  -- WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  -- WINDOW:SwitchTalk({PARTNER_0 = -1398135167, PARTNER_1 = -2021165758})
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  -- CAMERA:SetEye(SymCam("CAMERA_02"))
  -- CAMERA:SetTgt(SymCam("CAMERA_02"))
  -- TASK:Sleep(TimeSec(0.3))
  -- WINDOW:DrawFace(324, 88, SymAct("EMONGA"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("EMONGA"), -1633926141)
  -- WINDOW:Talk(SymAct("EMONGA"), -773991740)
  -- subEveCloseMsg()
  -- subEveDoubleJump(CH("PARTNER"))
  -- WINDOW:DrawFace(20, 20, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  -- WINDOW:SwitchTalk({PARTNER_0 = -926489723, PARTNER_1 = -471093178})
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(324, 88, SymAct("EMONGA"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("EMONGA"), -84901625)
  -- WINDOW:Talk(SymAct("EMONGA"), 2104008136)
  -- subEveCloseMsg()
  -- TASK:Regist(subEveNod, {
  --   CH("PARTNER")
  -- })
  -- WINDOW:DrawFace(20, 20, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  -- WINDOW:SwitchTalk({PARTNER_0 = 1685302409, PARTNER_1 = 1846191185})
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(6))
  -- CAMERA:SetEye(SymCam("CAMERA_01"))
  -- CAMERA:SetTgt(SymCam("CAMERA_01"))
  -- CH("PARTNER"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.2))
  -- CH("HERO"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  -- CH("HERO"):WaitRotate()
  -- WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  -- WINDOW:SwitchTalk({PARTNER_0 = 1997640976, PARTNER_1 = 1547486931})
  -- WINDOW:CloseMessage()
  -- subEveNod(CH("HERO"))
  -- TASK:Sleep(TimeSec(0.2))
  -- CH("PARTNER"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.2))
  -- CH("HERO"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  -- CH("PARTNER"):WaitRotate()
  -- TASK:Sleep(TimeSec(0.2))
  -- CH("PARTNER"):WalkTo(SymPos("P02_PARTNER"), Speed(2))
  -- CH("HERO"):WalkTo(SymPos("P02_HERO"), Speed(2))
  -- TASK:Sleep(TimeSec(0.4))
  -- CH("EMONGA"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.8))
  -- SCREEN_A:FadeOut(TimeSec(0.5), true)
  -- CAMERA:ResetAzimuthDifferenceVolume()
  -- FLAG.SceneFlag = CONST.FL_SC_01_END
  -- FLAG.SCENARIOFLAG = CONST.M12_TENNINOBORUHIKARI_START
  -- SYSTEM:NextEntry()
end
function main12_tenninoboruhikari01_end()
end
function main12_tenninoboruhikari02_init()
end
function main12_tenninoboruhikari02_start()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- SOUND:FadeInEnv(SymSnd("SE_MAP_HILLSWIND_LP"), TimeSec(0.5), Volume(128))
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- subEveFadeAfterTime()
  -- WINDOW:DrawFace(324, 88, SymAct("KOARUHII"), FACE_TYPE.THINK)
  -- WINDOW:Talk(SymAct("KOARUHII"), 1160247186)
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(20, 88, SymAct("WASHIBON"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("WASHIBON"), 174481749)
  -- WINDOW:CloseMessage()
  -- CH("HERO"):WalkTo(SymPos("P01_HERO"), Speed(1.5))
  -- CH("PARTNER"):WalkTo(SymPos("P01_PARTNER"), Speed(1.5))
  -- TASK:Sleep(TimeSec(0.1))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  -- CAMERA:SetEye(SymCam("CAMERA_01"))
  -- CAMERA:SetTgt(SymCam("CAMERA_01"))
  -- CH("HERO"):WaitMove()
  -- WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  -- WINDOW:SwitchTalk({PARTNER_0 = 326979604, PARTNER_1 = 944767959})
  -- WINDOW:CloseMessage()
  -- CAMERA:MoveFollow(SymCam("CAMERA_02"), Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  -- CH("HERO"):WalkTo(SplinePath(SymPos("VIA01_HERO"), SymPos("VIA02_HERO"), SymPos("P02_HERO")), Speed(2))
  -- CH("PARTNER"):WalkTo(SplinePath(SymPos("VIA01_PARTNER"), SymPos("VIA02_PARTNER"), SymPos("P02_PARTNER")), Speed(2))
  -- CH("PARTNER"):WaitMove()
  -- TASK:Sleep(TimeSec(0.3))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  -- CH("PARTNER"):SetMotion(SymMot("EV001_CONFIRMS"), LOOP.OFF)
  -- TASK:Sleep(TimeSec(0.5))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  -- CH("PARTNER"):WaitPlayMotion()
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  -- WINDOW:SwitchTalk({PARTNER_0 = 558576278, PARTNER_1 = -1496109479})
  -- WINDOW:CloseMessage()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  -- CH("PARTNER"):SetManpu("MP_EXCLAMATION")
  -- CH("PARTNER"):WaitManpu()
  -- subEveDoubleJump(CH("PARTNER"))
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.EMOTION)
  -- WINDOW:SwitchTalk({PARTNER_0 = -1077403880, PARTNER_1 = 2092895167})
  -- WINDOW:SwitchTalk({PARTNER_0 = 1705261822, PARTNER_1 = 1317628221})
  -- WINDOW:CloseMessage()
  -- CH("HERO"):WalkTo(SymPos("P03_HERO"), Speed(1.5))
  -- CH("HERO"):WaitMove()
  -- SOUND:FadeOutEnv(TimeSec(1))
  -- SCREEN_A:FadeOut(TimeSec(0.5), true)
  FLAG.SceneFlag = CONST.FL_SC_02_END
  FLAG.SCENARIOFLAG = CONST.M12_TENNINOBORUHIKARI_START
  SYSTEM:NextEntry()
end
function main12_tenninoboruhikari02_end()
end
function main12_tenninoboruhikari03_init()
end
function main12_tenninoboruhikari03_start()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(9))
  -- CAMERA:SetFovy(SymCam("CAMERA_00"))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- EFFECT:Create("effectLightHeroLp", SymEff("EV_LIGHT_HERO_LP"))
  -- EFFECT:SetPosition("effectLightHeroLp", SymPos("P01_EFF_LIGHT_HERO_LP"))
  -- EFFECT:Play("effectLightHeroLp")
  -- EFFECT:SetScale("effectLightHeroLp", Scale(0.5))
  -- SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_DAIHYOUGA_03"), Volume(256))
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- TASK:Sleep(TimeSec(1.5))
  -- WINDOW:DrawFace(324, 88, SymAct("HERO"), FACE_TYPE.NORMAL)
  -- WINDOW:Monologue(1469208700)
  -- WINDOW:Monologue(416534203)
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.SPECIAL02)
  -- WINDOW:SwitchTalk({PARTNER_0 = 29949946, PARTNER_1 = 719694905})
  -- WINDOW:SwitchTalk({PARTNER_0 = 872324472, PARTNER_1 = -1268350537})
  -- WINDOW:SwitchTalk({PARTNER_0 = -1384271626, PARTNER_1 = -1006408486})
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(324, 88, SymAct("KOARUHII"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("KOARUHII"), -585605733)
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(324, 88, SymAct("WASHIBON"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("WASHIBON"), -164295080)
  -- WINDOW:Talk(SymAct("WASHIBON"), -282181863)
  -- WINDOW:CloseMessage()
  -- SCREEN_A:FadeOut(TimeSec(0.5), true)
  FLAG.SceneFlag = CONST.FL_SC_03_END
  FLAG.SCENARIOFLAG = CONST.M12_TENNINOBORUHIKARI_START
  SYSTEM:NextEntry()
end
function main12_tenninoboruhikari03_end()
end
function main12_tenninoboruhikari04_init()
end
function main12_tenninoboruhikari04_start()
  -- SOUND:PlayBgm(SymSnd("BGM_EVE_THEME_DAIHYOUGA_03"), Volume(256))
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  -- SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- subEveFadeAfterTime()
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.NORMAL)
  -- WINDOW:SwitchTalk({PARTNER_0 = -1603294754, PARTNER_1 = -1183541089})
  -- WINDOW:SwitchTalk({PARTNER_0 = -1839608996, PARTNER_1 = -1958544867})
  -- subEveCloseMsg()
  -- SOUND:FadeOutBgm(TimeSec(3.5))
  -- WINDOW:DrawFace(324, 88, SymAct("WASHIBON"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("WASHIBON"), 215672530)
  -- WINDOW:CloseMessage()
  -- CH("PARTNER"):DirTo(CH("WASHIBON"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.2))
  -- CH("HERO"):DirTo(CH("WASHIBON"), Speed(350), ROT_TYPE.NEAR)
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  -- CAMERA:SetEye(SymCam("CAMERA_01"))
  -- CAMERA:SetTgt(SymCam("CAMERA_01"))
  -- CH("HERO"):WaitRotate()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_QUESTION_01"), Volume(256))
  -- CH("PARTNER"):SetManpu("MP_QUESTION")
  -- CH("PARTNER"):WaitManpu()
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.THINK)
  -- WINDOW:SwitchTalk({PARTNER_0 = 365025171, PARTNER_1 = 1507087459})
  -- CH("WASHIBON"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.2))
  -- CH("KOARUHII"):DirTo(CH("PARTNER"), Speed(350), ROT_TYPE.NEAR)
  -- CH("WASHIBON"):WaitRotate()
  -- subEveCloseMsg()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  -- CH("WASHIBON"):SetManpu("MP_FLY_SWEAT")
  -- WINDOW:DrawFace(324, 88, SymAct("WASHIBON"), FACE_TYPE.SAD)
  -- WINDOW:Talk(SymAct("WASHIBON"), 1087333666)
  -- WINDOW:Talk(SymAct("WASHIBON"), 1809987297)
  -- WINDOW:Talk(SymAct("WASHIBON"), 1928923040)
  -- WINDOW:Talk(SymAct("WASHIBON"), 1035506023)
  -- WINDOW:Talk(SymAct("WASHIBON"), 614703142)
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(20, 88, SymAct("PARTNER"), FACE_TYPE.THINK)
  -- WINDOW:SwitchTalk({PARTNER_0 = 261026789, PARTNER_1 = 378913444})
  -- subEveCloseMsg()
  -- WINDOW:DrawFace(324, 20, SymAct("KOARUHII"), FACE_TYPE.SAD)
  -- WINDOW:Talk(SymAct("KOARUHII"), -1861362069)
  -- WINDOW:Talk(SymAct("KOARUHII"), -2011762902)
  -- WINDOW:Talk(SymAct("KOARUHII"), -513264890)
  -- WINDOW:Talk(SymAct("KOARUHII"), -126680505)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(2.5))
  -- CAMERA:SetEye(SymCam("CAMERA_03"))
  -- CAMERA:SetTgt(SymCam("CAMERA_03"))
  -- TASK:Sleep(TimeSec(0.3))
  -- WINDOW:Monologue(-748793468)
  -- WINDOW:CloseMessage()
  -- SCREEN_A:FadeOut(TimeSec(1), true)
  -- CAMERA:ResetAzimuthDifferenceVolume()
  FLAG.SceneFlag = CONST.FL_SC_01_FIRST
  FLAG.SCENARIOFLAG = CONST.M12_TENNINOBORUHIKARI_END
  FLAG.MapFlags = CONST.MAP_EVENT
  FLAG.FreePlay = CONST.FLAG_TRUE
  FLAG.TrigNextEvent = CONST.FLAG_FALSE
  SYSTEM:NextEntry()
end
function main12_tenninoboruhikari04_end()
end
function groundEnd()
end

