dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main16_chimyakuairoboss2nd01_init()
end
function main16_chimyakuairoboss2nd01_start()
  subEveFromProgFadeSet()
  TASK:Sleep(TimeSec(1))
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("HERO"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("PARTNER"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("EMONGA"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  CH("BIRIJION"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  SCREEN_A:FadeIn(TimeSec(0.5), false)
  CAMERA:MoveFollow(SymCam("CAMERA_01_1"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("BOOMANDA_H"):SetMotion(SymMot("EV013_ROARING02"), LOOP.OFF, TimeSec(0))
  TASK:Sleep(TimeSec(0.7))
  CAMERA:MoveFollow2(SymCam("CAMERA_01_5"), Speed(6, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("BOOMANDA_H"):WaitPlayMotion()
  CH("BOOMANDA_H"):SetMotion(SymMot("EV013_ROARING03"), LOOP.ON)
  EFFECT:StartMotionBlur(0, 0, 0)
  EFFECT:ChangeMotionBlurLevel(0.04, TimeSec(0.05))
  EFFECT:ChangeMotionBlurAlpha(0.9, TimeSec(0.05))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  SOUND:PlaySe(SymSnd("SE_EVT_BOOMANDA_ROAR"), Volume(256))
  WINDOW:SysMsg(-292557706)
  TASK:Sleep(TimeSec(1.5))
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  WINDOW:ForceCloseMessage()
  EFFECT:EndMotionBlur()
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetDefaultGroundFovy()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  CH("BOOMANDA_H"):SetMotion(SymMot("EV013_ROARING03_END"), LOOP.OFF, TimeSec(0))
  CH("BOOMANDA_H"):SetMotion(SymMot("WAIT02"), LOOP.ON, TimeSec(0))
  SOUND:PlayBgm(SymSnd("BGM_EVE_FEAR_01"), Volume(256))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 88, SymAct("EMONGA"), FACE_TYPE.DECIDE)
  WINDOW:Talk(SymAct("EMONGA"), -141238985)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = -591819020, PARTNER_1 = -979189835})
  WINDOW:SwitchTalk({PARTNER_0 = -1964824206, PARTNER_1 = -1812457421})
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(1))
  CAMERA:SetFovy(SymCam("CAMERA_01"))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CAMERA:MoveFollow(SymCam("CAMERA_01_1"), Speed(1, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("BOOMANDA_H"):SetMotion(SymMot("EV013_ROARING02"), LOOP.OFF, TimeSec(0))
  TASK:Sleep(TimeSec(0.7))
  CAMERA:MoveFollow2(SymCam("CAMERA_01_5"), Speed(6, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("BOOMANDA_H"):WaitPlayMotion()
  CH("BOOMANDA_H"):SetMotion(SymMot("EV013_ROARING03"), LOOP.ON)
  EFFECT:StartMotionBlur(0, 0, 0)
  EFFECT:ChangeMotionBlurLevel(0.04, TimeSec(0.05))
  EFFECT:ChangeMotionBlurAlpha(0.9, TimeSec(0.05))
  CAMERA:SetShake(Vector2(0.02, 0.02), TimeSec(1, TIME_TYPE.FRAME))
  SOUND:PlaySe(SymSnd("SE_EVT_BOOMANDA_ROAR"), Volume(256))
  WINDOW:SysMsg(-1193980944)
  TASK:Sleep(TimeSec(1.5))
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  WINDOW:ForceCloseMessage()
  EFFECT:EndMotionBlur()
  CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetDefaultGroundFovy()
  CAMERA:SetEye(SymCam("CAMERA_03_1"))
  CAMERA:SetTgt(SymCam("CAMERA_03_1"))
  CH("BOOMANDA_H"):SetMotion(SymMot("EV013_ROARING03_END"), LOOP.OFF, TimeSec(0))
  CH("BOOMANDA_H"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0))
  TASK:Sleep(TimeSec(0.2))
  CH("SHANDERA_1"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
  TASK:Sleep(TimeSec(0.1))
  CH("SHANDERA_2"):SetMotion(SymMot("BATTLE"), LOOP.ON, TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("SHANDERA_1"), FACE_TYPE.ANGRY)
  WINDOW:Talk(SymAct("SHANDERA_1"), -1580303695)
  WINDOW:CloseMessage()
  SOUND:FadeOutBgm(TimeSec(1.5))
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetDefaultGroundFovy()
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  WINDOW:DrawFace(324, 88, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = 643196542, PARTNER_1 = 1062033215})
  WINDOW:CloseMessage()
  subEveFlash2()
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_BOSS_WIPE"), Volume(256))
  EFFECT:BossWipe(TimeSec(60, TIME_TYPE.FRAME), true)
  CAMERA:ResetAzimuthDifferenceVolume()
  FLAG.SceneFlag = CONST.FL_SC_01_FIRST
  FLAG.SCENARIOFLAG = CONST.M16_CHIMYAKUAIROBOSS2ND_END
  SYSTEM:SetNextDungeonBanner(false)
  SYSTEM:EnterDungeon(Dg(19), DG_WAYPOINT.BOSS00)
end
function main16_chimyakuairoboss2nd01_end()
end
function groundEnd()
end

