dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function sub01_shukubamachinoyoru01_init()
end
function sub01_shukubamachinoyoru01_start()
  MAP:SetVisible(false)
  MAP:SetBG(SymMap("IM05_03_SKY_NIGHT02"))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(2))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  MAP:SetVisible(true)
  MAP:SetVisibleBG(false)
  FLAG.SceneFlag = CONST.FL_SC_01_END
  FLAG.SCENARIOFLAG = CONST.S1_SHUKUBAMACHINOYORU_START
  SYSTEM:NextEntry()
end
function sub01_shukubamachinoyoru01_end()
end
function sub01_shukubamachinoyoru02_init()
end
function sub01_shukubamachinoyoru02_start()
  CHARA:SetMotionBlendMode(BlendMode.CHANGE_ONLY)
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  local taskSaru3 = function()
    function TaskL.Loop()
      TASK:Sleep(TimeSec(0.2))
      CH("BAOPPU"):SetManpu("MP_SPREE_LP")
      CH("BAOPPU"):SetMotion(SymMot("SPEAK"), LOOP.ON)
      TASK:Sleep(TimeSec(0.5))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.5))
      CH("BAOPPU"):ResetManpu()
      CH("BAOPPU"):SetMotion(SymMot("WAIT02"), LOOP.ON)
      TASK:Sleep(TimeSec(0.2))
      CH("HIYAPPU"):SetManpu("MP_LAUGH_LP")
      TASK:Sleep(TimeSec(0.5))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      subEveNodDouble(CH("YANAPPU"))
      TASK:Sleep(TimeSec(0.2))
      CH("HIYAPPU"):ResetManpu()
      subEveDoubleJump(CH("BAOPPU"))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.2))
    end
  end
  local taskAhiruNezumi = function()
    function TaskL.Loop()
      TASK:Sleep(TimeSec(0.1))
      CH("KOARUHII"):SetManpu("MP_LAUGH_LP")
      TASK:Sleep(TimeSec(1))
      CH("KOARUHII"):ResetManpu()
      TASK:Sleep(TimeSec(0.2))
      CH("MINEZUMI"):SetMotion(SymMot("SPEAK"), LOOP.ON)
      TASK:Sleep(TimeSec(2))
      CH("MINEZUMI"):SetMotion(SymMot("WAIT02"), LOOP.ON)
      TASK:Sleep(TimeSec(0.5))
    end
  end
  local taskSuwanna00 = function()
    function TaskL.Loop()
      CH("DOTEKKOTSU"):SetManpu("MP_SPREE_LP")
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("DOTEKKOTSU"):ResetManpu()
      TASK:Sleep(TimeSec(0.2))
      subEveNodDouble(CH("SUWANNA"))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("SUWANNA"):SetManpu("MP_LAUGH_LP")
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      TASK:Sleep(TimeSec(0.25))
      TASK:Sleep(TimeSec(0), TASK_EXIT.QUICK)
      CH("SUWANNA"):ResetManpu()
    end
    function TaskL.Finish()
      CH("DOTEKKOTSU"):ResetManpu()
      CH("SUWANNA"):ResetManpu()
      return
    end
  end
  CH("SAZANDORA_LARGE"):SetMotionRaito(Raito(2))
  CH("SAZANDORA_LARGE"):SetMotion(SymMot("SPEAK"), LOOP.ON)
  TASK:Regist(Group("grpSaru"), taskSaru3)
  TASK:Regist(Group("grpAhiruNezumi"), taskAhiruNezumi)
  TASK:Regist(Group("grpSuwannna"), taskSuwanna00)
  CAMERA:MoveFollow(SymCam("CAMERA_00_5"), Speed(0.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  SOUND:PlayBgm(SymSnd("BGM_EVE_ENDING_03"), Volume(256))
  SOUND:PlaySe(SymSnd("SE_EVT_GATSUGATSU_LP"), Volume(190))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(4))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.5))
  CAMERA:SetAzimuthDifferenceVolume(Volume(3.5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  SOUND:FadeOutSe(SymSnd("SE_EVT_GATSUGATSU_LP"), TimeSec(0.3))
  CH("SAZANDORA_LARGE"):SetMotionRaito(Raito(1))
  CH("SAZANDORA_LARGE"):SetMotion(SymMot("VICTORY"), LOOP.OFF)
  CH("SAZANDORA_LARGE"):WaitPlayMotion()
  CH("SAZANDORA_LARGE"):SetManpu("MP_SPREE_AL_LP")
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.GLADNESS)
  WINDOW:Talk(SymAct("SAZANDORA"), -349341461)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow(SymCam("CAMERA_01_5"), Speed(3.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("SAZANDORA_LARGE"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CAMERA:WaitMove()
  CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(20, 20, SymAct("SAZANDORA"), FACE_TYPE.GLADNESS)
  WINDOW:Talk(SymAct("SAZANDORA"), -231323222)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SWEAT"), Volume(256))
  CH("NOKOTCHI"):SetManpu("MP_SWEAT_L_AL")
  CH("EMONGA"):SetManpu("MP_SWEAT_L_AL")
  CH("EMONGA"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("EMONGA"), FACE_TYPE.SPECIAL03)
  WINDOW:Talk(SymAct("EMONGA"), -652535191)
  WINDOW:Talk(SymAct("EMONGA"), -1073730776)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NOKOTCHI"), -1891516945)
  WINDOW:CloseMessage()
  CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  CH("SAZANDORA_LARGE"):ResetManpu()
  CH("SAZANDORA_LARGE"):DirTo(CH("NOKOTCHI"), Speed(200), ROT_TYPE.NEAR)
  CH("SAZANDORA_LARGE"):WaitRotate()
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NOKOTCHI"), -1772450642)
  WINDOW:Talk(SymAct("NOKOTCHI"), -1116217491)
  subEveCloseMsg()
  CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(20, 20, SymAct("SAZANDORA"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("SAZANDORA"), -1536365012)
  subEveCloseMsg()
  CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("NOKOTCHI"), 603255523)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_01"), Volume(256))
  CH("EMONGA"):SetManpu("MP_EXCLAMATION")
  CH("EMONGA"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("EMONGA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("EMONGA"), 988791714)
  subEveCloseMsg()
  CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(20, 20, SymAct("SAZANDORA"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("SAZANDORA"), -982025363)
  WINDOW:KeyWait()
  CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  WINDOW:DrawFace(20, 20, SymAct("SAZANDORA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("SAZANDORA"), -596882900)
  WINDOW:CloseMessage()
  SOUND:VolumeBgm(Volume(32), TimeSec(1))
  SCREEN_A:FadeOut(TimeSec(1), true)
  TASK:Sleep(TimeSec(1))
  WINDOW:Narration(TimeSec(0.5), TimeSec(0.5), -146728465)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CH("NOKOTCHI"):SetMotion(SymMot("FALL"), LOOP.OFF, TimeSec(0))
  CH("EMONGA"):SetMotion(SymMot("FALL"), LOOP.OFF, TimeSec(0))
  CH("SAZANDORA_LARGE"):SetManpu("MP_SPREE_AL_LP")
  CH("SAZANDORA_LARGE"):SetMotionRaito(Raito(2))
  CH("SAZANDORA_LARGE"):SetMotion(SymMot("SPEAK"), LOOP.ON, TimeSec(0))
  TASK:Sleep(TimeSec(0.3))
  CH("SAZANDORA_LARGE"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  SOUND:VolumeBgm(Volume(256), TimeSec(0.5))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("SAZANDORA"), -296081234)
  WINDOW:Talk(SymAct("SAZANDORA"), -1592017303)
  WINDOW:Talk(SymAct("SAZANDORA"), -1207922904)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow2(SymCam("CAMERA_03"), Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SWEAT"), Volume(256))
  CH("NOKOTCHI"):SetManpu("MP_SWEAT_L_AL")
  CH("EMONGA"):SetManpu("MP_SWEAT_L_AL")
  CH("EMONGA"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("EMONGA"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("EMONGA"), -1825710869)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("NOKOTCHI"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("NOKOTCHI"), -1976111702)
  subEveCloseMsg()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("EMONGA"):SetManpu("MP_FLY_SWEAT")
  WINDOW:DrawFace(324, 88, SymAct("EMONGA"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("EMONGA"), 229568869)
  WINDOW:CloseMessage()
  CAMERA:MoveFollow2(SymCam("CAMERA_02"), Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("SAZANDORA"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("SAZANDORA"), 347455524)
  WINDOW:Talk(SymAct("SAZANDORA"), -675097469)
  SOUND:FadeOutBgm(TimeSec(2.5))
  SCREEN_A:FadeOutAll(TimeSec(1), false)
  SCREEN_A:WaitFade()
  WINDOW:ForceCloseMessage()
  SOUND:WaitBgm()
  SCREEN_A:FadeOut(TimeSec(0), true)
  SCREEN_A:FadeInAll(TimeSec(0), true)
  TASK:Sleep(TimeSec(0.5))
  FLAG.SceneFlag = CONST.FL_SC_02_END
  FLAG.SCENARIOFLAG = CONST.S1_SHUKUBAMACHINOYORU_START
  SYSTEM:NextEntry()
end
function sub01_shukubamachinoyoru02_end()
end
function sub01_shukubamachinoyoru03_init()
end
function sub01_shukubamachinoyoru03_start()
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  SOUND:FadeInEnv(SymSnd("SE_MAP_HILLSWIND_LP"), TimeSec(0.5), Volume(128))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(2.5))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  subEveFadeAfterTime()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))
  CH("BIRIJION"):SetPosition(SymPos("P00_01_BIRIJION"))
  CH("BIRIJION"):SetDir(RotateTarget(-160))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(1))
  WINDOW:Talk(SymAct("BIRIJION"), -824580670)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_LOW_02"), Volume(256))
  CH("KERUDYIO"):SetManpu("MP_NOTICE_R")
  CH("KERUDYIO"):WaitManpu()
  CAMERA:MoveFollow2(SymCam("CAMERA_01_5"), Speed(1.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CH("KERUDYIO"):DirTo(CH("BIRIJION"), Speed(200), ROT_TYPE.NEAR)
  CAMERA:WaitMove()
  WINDOW:DrawFace(20, 20, SymAct("KERUDYIO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KERUDYIO"), -436947455)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), -51411136)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("KERUDYIO"):SetManpu("MP_FLY_SWEAT")
  CH("KERUDYIO"):WaitManpu()
  WINDOW:DrawFace(20, 20, SymAct("KERUDYIO"), FACE_TYPE.THINK)
  WINDOW:Talk(SymAct("KERUDYIO"), -1280437881)
  WINDOW:DrawFace(20, 20, SymAct("KERUDYIO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KERUDYIO"), -1430970170)
  WINDOW:CloseMessage()
  CH("KERUDYIO"):DirTo(RotateTarget(180), Speed(200), ROT_TYPE.NEAR)
  CH("KERUDYIO"):WaitRotate()
  CAMERA:MoveFollow2(SymCam("CAMERA_02"), Speed(1.2, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  subEveMoveDir(CH("BIRIJION"), SymPos("P01_BIRIJION"), Speed(1.2), RotateTarget(-180))
  CAMERA:WaitMove()
  WINDOW:DrawFace(20, 88, SymAct("KERUDYIO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KERUDYIO"), -2120715515)
  WINDOW:Talk(SymAct("KERUDYIO"), -1736228284)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), 521887371)
  WINDOW:KeyWait()
  CH("BIRIJION"):DirTo(CH("KERUDYIO"), Speed(200), ROT_TYPE.NEAR)
  WINDOW:Talk(SymAct("BIRIJION"), 100691914)
  CH("BIRIJION"):WaitRotate()
  WINDOW:CloseMessage()
  CH("KERUDYIO"):DirTo(CH("BIRIJION"), Speed(200), ROT_TYPE.NEAR)
  CH("KERUDYIO"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("KERUDYIO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KERUDYIO"), 1870574566)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), 1986364071)
  WINDOW:Talk(SymAct("BIRIJION"), 1565053284)
  WINDOW:Talk(SymAct("BIRIJION"), 1146347557)
  subEveCloseMsg()
  TASK:Regist(subEveNod, {
    CH("KERUDYIO")
  })
  WINDOW:DrawFace(20, 88, SymAct("KERUDYIO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KERUDYIO"), 185759458)
  WINDOW:Talk(SymAct("KERUDYIO"), 302598051)
  WINDOW:Talk(SymAct("KERUDYIO"), 958665824)
  WINDOW:Talk(SymAct("KERUDYIO"), 541009185)
  WINDOW:Talk(SymAct("KERUDYIO"), -1482212882)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), -1094973265)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("KERUDYIO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KERUDYIO"), -223769761)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), -340608482)
  subEveCloseMsg()
  TASK:Regist(subEveNod, {
    CH("KERUDYIO")
  })
  WINDOW:DrawFace(20, 88, SymAct("KERUDYIO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KERUDYIO"), -1063261731)
  WINDOW:Talk(SymAct("KERUDYIO"), -645605220)
  WINDOW:Talk(SymAct("KERUDYIO"), -1765454245)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), -1881243878)
  WINDOW:Talk(SymAct("BIRIJION"), -1527567143)
  WINDOW:Talk(SymAct("BIRIJION"), -1108861544)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("KERUDYIO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KERUDYIO"), 980418903)
  WINDOW:Talk(SymAct("KERUDYIO"), 594227222)
  WINDOW:Talk(SymAct("KERUDYIO"), 1242950714)
  WINDOW:Talk(SymAct("KERUDYIO"), 1393483131)
  WINDOW:Talk(SymAct("KERUDYIO"), 2015596216)
  WINDOW:Talk(SymAct("KERUDYIO"), 1631109113)
  WINDOW:Talk(SymAct("KERUDYIO"), 779692350)
  WINDOW:Talk(SymAct("KERUDYIO"), 929175679)
  WINDOW:Talk(SymAct("KERUDYIO"), 474958780)
  WINDOW:Talk(SymAct("KERUDYIO"), 89422589)
  WINDOW:CloseMessage()
  SOUND:FadeOutEnv(TimeSec(1.5))
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  FLAG.SceneFlag = CONST.FL_SC_03_END
  FLAG.SCENARIOFLAG = CONST.S1_SHUKUBAMACHINOYORU_START
  SYSTEM:NextEntry()
end
function sub01_shukubamachinoyoru03_end()
end
function sub01_shukubamachinoyoru04_init()
end
function sub01_shukubamachinoyoru04_start()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_00"))
  CAMERA:SetTgt(SymCam("CAMERA_00"))
  EFFECT:CreateRecollectionFilter()
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  WINDOW:DrawFace(72, 16, SymAct("PARTNER"), FACE_TYPE.DECIDE)
  WINDOW:SwitchTalk({PARTNER_0 = -2100533710, PARTNER_1 = -1680386189})
  WINDOW:SwitchTalk({PARTNER_0 = 1486898132, PARTNER_1 = 1102803605})
  WINDOW:SwitchTalk({PARTNER_0 = 1788223830, PARTNER_1 = 1938624535})
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_GREPALACE_COLLAPSE_01"), Volume(128))
  CAMERA:SetShake(Vector2(0.011, 0.01), TimeSec(1, TIME_TYPE.FRAME))
  TASK:Sleep(TimeSec(0.3))
  CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetEye(SymCam("CAMERA_04_1"))
  CAMERA:SetTgt(SymCam("CAMERA_04_1"))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_NOTICE_HIGH_02"), Volume(256))
  CH("MUNNA"):SetManpu("MP_EXCLAMATION")
  CH("MUNNA"):WaitManpu()
  TASK:Sleep(TimeSec(0.3))
  CAMERA:SetShake(Vector2(0, 0), TimeSec(0))
  CH("MUNNA"):SetFacialMotion(FACIAL_MOTION.TEARS)
  WINDOW:Talk(SymAct("MUNNA"), 1020036816)
  WINDOW:Talk(SymAct("MUNNA"), 634894225)
  WINDOW:Talk(SymAct("MUNNA"), 251323474)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(1.5))
  CAMERA:SetEye(SymCam("CAMERA_13"))
  CAMERA:SetTgt(SymCam("CAMERA_13"))
  CH("PARTNER"):SetDir(SymPos("P02_PARTNER"))
  CH("PARTNER"):SetFacialMotion(FACIAL_MOTION.DECIDE)
  CAMERA:MoveFollow2(SymCam("CAMERA_13_5"), Speed(10, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  TASK:Sleep(TimeSec(0.2))
  CH("PARTNER"):WalkTo(SymPos("P02_PARTNER"), Speed(1.5))
  CH("PARTNER"):WaitMove()
  WINDOW:SwitchTalk({PARTNER_0 = 400676115, PARTNER_1 = -1871066660})
  WINDOW:CloseMessage()
  SCREEN_A:FadeOut(TimeSec(0.5), true)
  EFFECT:DestroyRecollectionFilter()
  FLAG.SceneFlag = CONST.FL_SC_04_END
  FLAG.SCENARIOFLAG = CONST.S1_SHUKUBAMACHINOYORU_START
  SYSTEM:NextEntry()
end
function sub01_shukubamachinoyoru04_end()
end
function sub01_shukubamachinoyoru05_init()
end
function sub01_shukubamachinoyoru05_start()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  CH("BIRIJION"):SetPosition(SymPos("P01_BIRIJION"))
  CH("BIRIJION"):SetDir(CH("KERUDYIO"))
  CH("KERUDYIO"):SetDir(CH("BIRIJION"))
  SOUND:FadeInEnv(SymSnd("SE_MAP_HILLSWIND_LP"), TimeSec(0.5), Volume(128))
  SCREEN_A:FadeIn(TimeSec(0.5), true)
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 88, SymAct("KERUDYIO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KERUDYIO"), -1990002531)
  WINDOW:Talk(SymAct("KERUDYIO"), -535026511)
  WINDOW:Talk(SymAct("KERUDYIO"), -116976144)
  WINDOW:CloseMessage()
  SOUND:FadeOutEnv(TimeSec(2))
  SOUND:PlayBgm(SymSnd("BGM_MAP_TOWN_02"), Volume(256))
  CH("KERUDYIO"):DirTo(RotateTarget(180), Speed(200), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.1))
  CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("KERUDYIO"):WaitRotate()
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(20, 88, SymAct("KERUDYIO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KERUDYIO"), -768981453)
  WINDOW:Talk(SymAct("KERUDYIO"), -885950606)
  WINDOW:Talk(SymAct("KERUDYIO"), -2072976971)
  WINDOW:Talk(SymAct("KERUDYIO"), -1653878540)
  WINDOW:Talk(SymAct("KERUDYIO"), -1236892873)
  WINDOW:Talk(SymAct("KERUDYIO"), -1352813962)
  WINDOW:Talk(SymAct("KERUDYIO"), 684043961)
  WINDOW:Talk(SymAct("KERUDYIO"), 836673528)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(3))
  CAMERA:SetEye(SymCam("CAMERA_04"))
  CAMERA:SetTgt(SymCam("CAMERA_04"))
  TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(324, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), -1199622937)
  WINDOW:CloseMessage()
  CH("KERUDYIO"):DirTo(CH("BIRIJION"), Speed(200), ROT_TYPE.NEAR)
  CH("KERUDYIO"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("KERUDYIO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KERUDYIO"), -1587280474)
  WINDOW:Talk(SymAct("KERUDYIO"), -1974905243)
  subEveCloseMsg()
  TASK:Regist(subEveNod, {
    CH("BIRIJION")
  })
  WINDOW:DrawFace(324, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), -1823316188)
  WINDOW:Talk(SymAct("BIRIJION"), -602672669)
  WINDOW:Talk(SymAct("BIRIJION"), -989282142)
  WINDOW:Talk(SymAct("BIRIJION"), -299527327)
  WINDOW:Talk(SymAct("BIRIJION"), -146890208)
  WINDOW:CloseMessage()
  CH("BIRIJION"):SetNeckRot(RotateTarget(0), RotateTarget(-20), RotateTarget(0), TimeSec(0.3))
  CH("BIRIJION"):WaitNeckRot()
  WINDOW:DrawFace(324, 88, SymAct("BIRIJION"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("BIRIJION"), 1889976047)
  WINDOW:Talk(SymAct("BIRIJION"), 1774030766)
  subEveCloseMsg()
  WINDOW:DrawFace(20, 88, SymAct("KERUDYIO"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("KERUDYIO"), 12800898)
  WINDOW:Talk(SymAct("KERUDYIO"), 433611459)
  WINDOW:Talk(SymAct("KERUDYIO"), 854929664)
  WINDOW:CloseMessage()
  CH("KERUDYIO"):DirTo(RotateTarget(135), Speed(200), ROT_TYPE.NEAR)
  CH("KERUDYIO"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("KERUDYIO"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("KERUDYIO"), 737017921)
  WINDOW:Talk(SymAct("KERUDYIO"), 1689228934)
  subEveCloseMsg()
  CH("BIRIJION"):ResetNeckRot(TimeSec(0.3))
  CH("BIRIJION"):WaitNeckRot()
  WINDOW:DrawFace(324, 88, SymAct("BIRIJION"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("BIRIJION"), 2108991431)
  WINDOW:Talk(SymAct("BIRIJION"), 1452930052)
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(2.5))
  CAMERA:SetEye(SymCam("CAMERA_02"))
  CAMERA:SetTgt(SymCam("CAMERA_02"))
  TASK:Sleep(TimeSec(0.3))
  CH("KERUDYIO"):DirTo(CH("BIRIJION"), Speed(200), ROT_TYPE.NEAR)
  CH("KERUDYIO"):WaitRotate()
  WINDOW:DrawFace(20, 88, SymAct("KERUDYIO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KERUDYIO"), 1333970245)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), -937764470)
  subEveCloseMsg()
  CH("KERUDYIO"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(20, 88, SymAct("KERUDYIO"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("KERUDYIO"), -788404021)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("BIRIJION"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), -1994695643)
  WINDOW:CloseMessage()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("KERUDYIO"):SetFacialMotion(FACIAL_MOTION.SURPRISE)
  CH("KERUDYIO"):SetManpu("MP_SHOCK_R")
  CH("KERUDYIO"):WalkTo(SymPos("P01_KERUDYIO"), Speed(2), LINK_DIR.OFF)
  CH("KERUDYIO"):WaitManpu()
  WINDOW:DrawFace(20, 88, SymAct("KERUDYIO"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("KERUDYIO"), -1879020188)
  WINDOW:CloseMessage()
  CH("KERUDYIO"):SetFacialMotion(FACIAL_MOTION.RELIEF)
  CH("KERUDYIO"):SetMotion(SymMot("EV018_DISAPPOINT00"), LOOP.OFF)
  CH("KERUDYIO"):WaitPlayMotion()
  CH("KERUDYIO"):SetMotion(SymMot("EV018_DISAPPOINT01"), LOOP.ON)
  WINDOW:DrawFace(20, 88, SymAct("KERUDYIO"), FACE_TYPE.SAD)
  WINDOW:Talk(SymAct("KERUDYIO"), -1154662745)
  WINDOW:Talk(SymAct("KERUDYIO"), -1573515290)
  subEveCloseMsg()
  CH("BIRIJION"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  CH("BIRIJION"):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(324, 88, SymAct("BIRIJION"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("BIRIJION"), -310929119)
  WINDOW:KeyWait()
  CH("BIRIJION"):ResetManpu()
  WINDOW:Talk(SymAct("BIRIJION"), -194205600)
  WINDOW:CloseMessage()
  CH("KERUDYIO"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  CH("KERUDYIO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  TASK:Sleep(TimeSec(0.5))
  CH("KERUDYIO"):WalkTo(SymPos("P00_KERUDYIO"), Speed(1))
  TASK:Sleep(TimeSec(0.2))
  WINDOW:DrawFace(20, 88, SymAct("KERUDYIO"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KERUDYIO"), -549323869)
  subEveCloseMsg()
  WINDOW:DrawFace(324, 88, SymAct("BIRIJION"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("BIRIJION"), -967128350)
  WINDOW:KeyWait()
  CH("BIRIJION"):SetFacialMotion(FACIAL_MOTION.NORMAL)
  WINDOW:Talk(SymAct("BIRIJION"), 1103287853)
  WINDOW:Talk(SymAct("BIRIJION"), 1490675564)
  subEveCloseMsg()
  CH("KERUDYIO"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(20, 88, SymAct("KERUDYIO"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("KERUDYIO"), 833043264)
  subEveCloseMsg()
  CH("BIRIJION"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  CH("BIRIJION"):SetManpu("MP_LAUGH_LP")
  WINDOW:DrawFace(324, 88, SymAct("BIRIJION"), FACE_TYPE.GLADNESS)
  WINDOW:Talk(SymAct("BIRIJION"), 683411969)
  WINDOW:Talk(SymAct("BIRIJION"), 59857346)
  subEveCloseMsg()
  CH("BIRIJION"):ResetManpu()
  CH("BIRIJION"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  TASK:Regist(subEveNod, {
    CH("KERUDYIO")
  })
  WINDOW:DrawFace(20, 88, SymAct("KERUDYIO"), FACE_TYPE.GLADNESS)
  WINDOW:Talk(SymAct("KERUDYIO"), 445278339)
  WINDOW:CloseMessage()
  local taskKerudyio01 = function()
    CH("KERUDYIO"):SetMotion(SymMot("VICTORY"), LOOP.OFF)
    CH("KERUDYIO"):WaitPlayMotion()
    CH("KERUDYIO"):SetFacialMotion(FACIAL_MOTION.GLADNESS)
    CH("KERUDYIO"):SetMotion(SymMot("WAIT00"), LOOP.ON)
    CH("KERUDYIO"):SetMotionRaito(Raito(2))
  end
  TASK:Regist(taskKerudyio01)
  WINDOW:DrawFace(20, 88, SymAct("KERUDYIO"), FACE_TYPE.GLADNESS)
  WINDOW:Talk(SymAct("KERUDYIO"), 1439432260)
  TASK:WaitTask()
  WINDOW:CloseMessage()
  CAMERA:SetAzimuthDifferenceVolume(Volume(2))
  CAMERA:SetEye(SymCam("CAMERA_03"))
  CAMERA:SetTgt(SymCam("CAMERA_03"))
  CH("BIRIJION"):SetManpu("MP_LAUGH_LP")
  TASK:Sleep(TimeSec(1.5))
  CH("KERUDYIO"):SetManpu("MP_SPREE_LP")
  TASK:Sleep(TimeSec(1))
  CH("BIRIJION"):ResetManpu()
  TASK:Sleep(TimeSec(0.5))
  CH("KERUDYIO"):ResetManpu()
  CH("KERUDYIO"):SetMotion(SymMot("WAIT02"), LOOP.ON)
  CH("KERUDYIO"):SetMotionRaito(Raito(1))
  CH("KERUDYIO"):SetMotion(SymMot("VICTORY"), LOOP.OFF)
  CH("KERUDYIO"):WaitPlayMotion()
  CH("KERUDYIO"):SetMotion(SymMot("WAIT00"), LOOP.ON)
  CH("KERUDYIO"):SetMotionRaito(Raito(2))
  CH("BIRIJION"):SetManpu("MP_LAUGH_LP")
  SOUND:FadeOutBgm(TimeSec(4))
  TASK:Sleep(TimeSec(1.5))
  SCREEN_A:FadeOut(TimeSec(1), true)
  SOUND:WaitBgm()
  FLAG.StoryPlayerMode = CONST.ST_MODE_PARTNER
  FLAG.SceneFlag = CONST.FL_SC_01_FIRST
  FLAG.SCENARIOFLAG = CONST.S1_SHUKUBAMACHINOYORU_END
  FLAG.MapFlags = CONST.MAP_EVENT
  FLAG.FreePlay = CONST.FLAG_TRUE
  FLAG.TrigNextEvent = CONST.FLAG_FALSE
  SYSTEM:NextSpecialEntry(SPECIAL_ENTRY.NEXT_DAY_ONLY_PARTNER)
end
function sub01_shukubamachinoyoru05_end()
end
function groundEnd()
end

