dofile("script/include/inc_all.lua")
dofile("script/include/inc_event.lua")
function groundInit()
end
function groundStart()
end
function main11_nanroenter01_init()
end
function main11_nanroenter01_start()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_00"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00"))
  SOUND:PlayBgm(SymSnd("BGM_DUN_16"), Volume(256))
  CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  CAMERA:SetEye(SymCam("CAMERA_01"))
  CAMERA:SetTgt(SymCam("CAMERA_01"))

  CH("BURAKKII"):SetPosition(SymPos("P01_BURAKKII"))
  CH("EEFI"):SetDir(SymPos("P01_BURAKKII"))
  CH("PARTNER"):SetDir(SymPos("P01_BURAKKII"))
  CH("BIRIJION"):SetDir(SymPos("P01_BURAKKII"))
  CH("NOKOTCHI"):SetDir(SymPos("P01_BURAKKII"))
  CH("HERO"):SetDir(SymPos("POINT"))
  CH("BURAKKII"):SetDir(CH("HERO"))


  SCREEN_A:FadeIn(TimeSec(0.5), true)
  -- local taskHeroLookAround = function()
  --   CH("HERO"):DirTo(RotateTarget(120), Speed(350), ROT_TYPE.NEAR)
  --   CH("HERO"):WaitRotate()
  --   TASK:Sleep(TimeSec(0.2))
  --   CH("HERO"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  --   CH("HERO"):WaitRotate()
  --   TASK:Sleep(TimeSec(0.4))
  --   CH("HERO"):DirTo(RotateTarget(35), Speed(350), ROT_TYPE.NEAR)
  --   CH("HERO"):WaitRotate()
  -- end
  -- local taskPartnerLookAround = function()
  --   TASK:Sleep(TimeSec(0.2))
  --   CH("PARTNER"):DirTo(RotateTarget(-150), Speed(350), ROT_TYPE.NEAR)
  --   CH("PARTNER"):WaitRotate()
  --   TASK:Sleep(TimeSec(0.2))
  --   CH("PARTNER"):DirTo(RotateTarget(-10), Speed(350), ROT_TYPE.NEAR)
  --   CH("PARTNER"):WaitRotate()
  --   TASK:Sleep(TimeSec(0.3))
  --   CH("PARTNER"):DirTo(RotateTarget(-45), Speed(350), ROT_TYPE.NEAR)
  --   CH("PARTNER"):WaitRotate()
  -- end
  -- local taskNokotchiLookAround = function()
  --   TASK:Sleep(TimeSec(0.2))
  --   CH("NOKOTCHI"):DirTo(RotateTarget(120), Speed(350), ROT_TYPE.NEAR)
  --   CH("NOKOTCHI"):WaitRotate()
  --   TASK:Sleep(TimeSec(0.4))
  --   CH("NOKOTCHI"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.NEAR)
  --   CH("NOKOTCHI"):WaitRotate()
  --   TASK:Sleep(TimeSec(0.3))
  --   CH("NOKOTCHI"):DirTo(RotateTarget(-45), Speed(350), ROT_TYPE.NEAR)
  --   CH("NOKOTCHI"):WaitRotate()
  -- end
  -- local taskBurakkiiLookAround = function()
  --   CH("BURAKKII"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.NEAR)
  --   CH("BURAKKII"):WaitRotate()
  --   TASK:Sleep(TimeSec(0.2))
  --   CH("BURAKKII"):DirTo(RotateTarget(20), Speed(350), ROT_TYPE.NEAR)
  --   CH("BURAKKII"):WaitRotate()
  --   TASK:Sleep(TimeSec(0.2))
  --   CH("BURAKKII"):DirTo(RotateTarget(-100), Speed(350), ROT_TYPE.NEAR)
  --   CH("BURAKKII"):WaitRotate()
  -- end
  -- local taskEefiLookAround = function()
  --   TASK:Sleep(TimeSec(0.3))
  --   CH("EEFI"):DirTo(RotateTarget(-150), Speed(350), ROT_TYPE.NEAR)
  --   CH("EEFI"):WaitRotate()
  --   TASK:Sleep(TimeSec(0.5))
  --   CH("EEFI"):DirTo(RotateTarget(-30), Speed(350), ROT_TYPE.NEAR)
  --   CH("EEFI"):WaitRotate()
  --   TASK:Sleep(TimeSec(0.2))
  -- end
  -- TASK:Regist(Group("hero"), taskHeroLookAround)
  -- TASK:Regist(Group("grpNoko"), taskNokotchiLookAround)
  -- TASK:Sleep(TimeSec(0.2))
  -- CH("BIRIJION"):DirTo(RotateTarget(30), Speed(200), ROT_TYPE.NEAR)
  -- TASK:Regist(Group("partner"), taskPartnerLookAround)
  -- TASK:Regist(Group("grpBura"), taskBurakkiiLookAround)
  -- TASK:Sleep(TimeSec(0.2))
  -- TASK:Regist(Group("grpEefi"), taskEefiLookAround)
  -- TASK:WaitTask()
  -- TASK:Sleep(TimeSec(0.2))
  -- CH("EEFI"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  -- CH("EEFI"):WaitRotate()
  -- CH("BURAKKII"):DirTo(SymPos("POINT"), Speed(350), ROT_TYPE.NEAR)
  -- CH("HERO"):DirTo(SymPos("POINT"), Speed(350), ROT_TYPE.NEAR)
  -- CH("PARTNER"):DirTo(SymPos("POINT"), Speed(350), ROT_TYPE.NEAR)
  -- CH("BIRIJION"):DirTo(SymPos("POINT"), Speed(350), ROT_TYPE.NEAR)
  -- CH("NOKOTCHI"):DirTo(SymPos("POINT"), Speed(350), ROT_TYPE.NEAR)
  -- CH("NOKOTCHI"):WaitRotate()
  -- WINDOW:DrawFace(20, 88, SymAct("EEFI"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("EEFI"), -1459141166)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(4.5))
  -- CAMERA:SetEye(SymCam("CAMERA_00_5"))
  -- CAMERA:SetTgt(SymCam("CAMERA_00_5"))
  -- CH("BURAKKII"):DirTo(SymPos("P01_BURAKKII"), Speed(350), ROT_TYPE.NEAR)
  -- CH("BURAKKII"):WaitRotate()
  -- CH("BURAKKII"):WalkTo(SymPos("P01_BURAKKII"), Speed(1.5))
  -- CH("EEFI"):DirTo(SymPos("P01_BURAKKII"), Speed(200), ROT_TYPE.NEAR)
  -- CH("PARTNER"):DirTo(SymPos("P01_BURAKKII"), Speed(200), ROT_TYPE.NEAR)
  -- CH("BIRIJION"):DirTo(SymPos("P01_BURAKKII"), Speed(200), ROT_TYPE.NEAR)
  -- CH("NOKOTCHI"):DirTo(SymPos("P01_BURAKKII"), Speed(200), ROT_TYPE.NEAR)
  -- CH("BURAKKII"):WaitMove()
  -- TASK:Sleep(TimeSec(0.3))
  -- WINDOW:DrawFace(20, 88, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("BURAKKII"), -1340312429)
  -- WINDOW:CloseMessage()
  -- CAMERA:SetAzimuthDifferenceVolume(Volume(5))
  -- CAMERA:SetEye(SymCam("CAMERA_01"))
  -- CAMERA:SetTgt(SymCam("CAMERA_01"))
  -- CH("BURAKKII"):DirTo(RotateTarget(0), Speed(350), ROT_TYPE.RIGHT)
  -- CH("BURAKKII"):WaitRotate()
  -- WINDOW:DrawFace(72, 16, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("BURAKKII"), -1691277488)
  -- WINDOW:CloseMessage()
  -- CH("BURAKKII"):DirTo(CH("HERO"), Speed(200), ROT_TYPE.NEAR)
  -- CH("BURAKKII"):WaitRotate()
  -- WINDOW:DrawFace(72, 16, SymAct("BURAKKII"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("BURAKKII"), -2111171055)
  -- WINDOW:Talk(SymAct("BURAKKII"), -848592682)
  -- WINDOW:CloseMessage()
  -- subEveNod(CH("HERO"))
  CAMERA:MoveToHero(Speed(2.5, ACCEL_TYPE.NONE, DECEL_TYPE.HIGH))
  CAMERA:WaitMove()
  FLAG.SceneFlag = CONST.FL_SC_01_FIRST
  FLAG.SCENARIOFLAG = CONST.M11_NANROENTER_END
  FLAG.MapFlags = CONST.MAP_EVENT
  FLAG.FreePlay = CONST.FLAG_TRUE
  FLAG.TrigNextEvent = CONST.FLAG_FALSE
  SYSTEM:NextEntry(KEEP_PLACEMENT.ON)
end
function main11_nanroenter01_end()
end
function groundEnd()
end

